### ISSUE TITLE
MNNConvert ERROR from tensoflow pb

### ISSUE THREAD

**Issue by hamal0** [alibaba/MNN#100]
./MNNConvert -f TF --modelFile strip_graph.pb --bizCode MNN --MNNModel strip_graph.mnn
MNNConverter Version: 0.0.0.1 - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [11:30:53] /home/MNN/tools/converter/source/tensorflow/TmpGraph.cpp:258: Check failed: curNode->inEdges.size() == 1 ==> Identity's input node num. != 1 [ conv/control_dependency ]
Aborted

master版本

**Comment by czy2014hust** [comment]
control_dependency is not supported!
