### ISSUE TITLE
Check failed: creator ==> NOT_SUPPORTED_OP: [ SPACE_TO_BATCH_ND ]

### ISSUE THREAD

**Issue by lcaikk1314** [alibaba/MNN#1000]
在将tflite模型转换为mnn模型时报错如下，Check failed: creator ==> NOT_SUPPORTED_OP: [ SPACE_TO_BATCH_ND ]。
tflite支持SPACE_TO_BATCH_ND这个OP，而MNN并不支持，有没有文档讲如何把tflite的OP添加到MNN的实践操作，官网的文档太笼统，看过之后还是无从下手，谢谢

**Comment by jxt1234** [comment]
可以从 tensorflow 直接转换先试试？

**Comment by jxt1234** [comment]
最新已经支持
