### ISSUE TITLE
Where is ceil and floor type of padding in pooling layer ?

### ISSUE THREAD

**Issue by AIGirl10** [alibaba/MNN#1006]
I want to change the padding format from ceil to floor (because it was like that in caffe). Model got converted successfully, but since I am not able to understand how to change padding from ceil to floor, it is giving me shape error. 

If anyone knows, please reply. Thank you.

**Comment by hl1987hl** [comment]
add code `pool->ceilModel` =p.round_mode()? false :true;` to  “void Pool::run” in “tools/converter/source/caffe/Pool.cpp” file. and you can add pooling_param{ round_mode : 1} to use floor format
