### ISSUE TITLE
MNNConvertDeps.dll  link error

### ISSUE THREAD

**Issue by xingjing1** [alibaba/MNN#1007]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows   vs2019 cmake ninja

# Github版本:
# Github Version:

2020.7.24日

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
vs2019
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

LINK: command "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\MNNConvertDeps.dir\objects1.rsp /out:..\..\MNNConvertDeps.dll /implib:MNNConvertDeps.lib /pdb:D:\MNN\MNN-master\build\MNNConvertDeps.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF ..\..\MNN.lib D:\protobuf\protobuf-3.4.0\build-vs2019\install\lib\libprotobuf.lib D:\VulkanSDK\1.2.141.2\Lib\vulkan-1.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\..\MNNConvertDeps.dll.manifest" failed (exit code 1120) with the following output:
TensorConverterMerge.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl MNN::Express::Variable::Info::syncSize(void)" (?syncSize@Info@Variable@Express@MNN@@QEAAXXZ)，函数 "public: bool __cdecl <lambda_17ab683f88c764d45c1c7c286df17d48>::operator()(class std::shared_ptr<class MNN::Express::Expr>)const " (??R<lambda_17ab683f88c764d45c1c7c286df17d48>@@QEBA_NV?$shared_ptr@VExpr@Express@MNN@@@std@@@Z) 中引用了该符号
..\..\MNNConvertDeps.dll : fatal error LNK1120: 1 个无法解析的外部命令
NMAKE : fatal error U1077: “"C:\Program Files\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by xorange** [comment]
see #1010 for a workaround
