### ISSUE TITLE
ARM64 v8编译

### ISSUE THREAD

**Issue by haiyang1981** [alibaba/MNN#101]
我在linux系统上用NDK编译libMNN.so的ARMV8版本，我在cmakelist中做了如下设置
set(ANDROID_ABI arm64-v8a)
set(ANDROID_SYSROOT_ABI arm64)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(ANDROID_TOOLCHAIN_NAME aarch64-linux-android)
set(ANDROID_TOOLCHAIN_ROOT ${ANDROID_TOOLCHAIN_NAME})
set(ANDROID_LLVM_TRIPLE aarch64-none-linux-android)
set(ANDROID_HEADER_TRIPLE aarch64-linux-android)
set(ANDROID_STL c++_shared)
set(ANDROID_NATIVE_API_LEVEL android-21) 

cmake的输出信息也说明我用的处理器是aarch64，但是编译出来的so还是32位的，是哪里的配置还没有做对吗？

**Comment by haiyang1981** [comment]
这里NDK的编译器用的是clang，编译时候会有如下报错
android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: /arm64-v8a/libMNN.so: open: 没有那个文件或目录

**Comment by jxt1234** [comment]
这个还有问题么？可能是配置的问题

**Comment by haiyang1981** [comment]
还没定位问题出在哪里，根据您的经验，哪里的配置会导致以上的错误？

**Comment by jxt1234** [comment]
不加这些配置，用 project/android/build_64.sh 编译不出来？

**Comment by haiyang1981** [comment]
按照说明的方法做，报如下错误：
CMake Error at /usr/local/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:104 (message):
  Could not find toolchain file:
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin:/media/nlp-cad58/0008900300070C70/cgn/coding/faceAI/opencv_face/android-ndk-r15c/build/cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by haiyang1981** [comment]
交叉编译cmake都找到了，却报找不到的错误

**Comment by jxt1234** [comment]
检查一下你的 $ANDROID_NDK 环境变量对不对

**Comment by haiyang1981** [comment]
找到错误了，环境变量配置有问题，谢谢。
