### ISSUE TITLE
does pictureRecognition demo use the wrong config of destFormat （should be RGB?） 

### ISSUE THREAD

**Issue by colincheng10** [alibaba/MNN#1016]
**[issue suspected]**
MobileNetV1 input tensor requires RGB, correct?  
it seems pictureRecognition demo program use stbi_image config with wrong destFormat like: 
_config.destFormat   = BGR;_
should be 
_config.destFormat   = RGB;_ 

**[test samples]**
A good test sample is grace_hopper.jpg, you can load from (https://storage.googleapis.com/download.tensorflow.org/example_images/grace_hopper.jpg)

**[original log]**
./pictureRecognition_001.out my_converted_mobilenet_v1.mnn grace_hopper.jpg ImageNetLabels.txt
Can't Find type=4 backend, use 0 instead
input: w:224 , h:224, bpp: 3
origin size: 512, 600
output size:1001
television: 0.173934
notebook: 0.145654
microphone: 0.110612
suit: 0.097111
loudspeaker: 0.069064

**[after patching log]**  
./pictureRecognition.out my_converted_mobilenet_v1.mnn grace_hopper.jpg ImageNetLabels.txt
Can't Find type=4 backend, use 0 instead
input: w:224 , h:224, bpp: 3
origin size: 512, 600
output size:1001
military uniform: 0.542948
Windsor tie: 0.093525
suit: 0.080486

mobilenet_v1.mnn from MNN engine demo page (https://www.yuque.com/mnn/en/ricgpz) was also verified, the same result.
only after patching, then demo mnn can recognize correctly. 
./pictureRecognition.out ~/MNN/mobilenet_demo/mobilenet_v1.mnn grace_hopper.jpg ImageNetLabels.txt
Can't Find type=4 backend, use 0 instead
input: w:224 , h:224, bpp: 3
origin size: 512, 600
output size:1001
military uniform: 0.687967
Windsor tie: 0.098115

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu on x86

# Github版本:
# Github Version:
MNN-1.0.0 

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_DEMO=true && make -j4

# 编译日志:
# Build Log:
[ 97%] Building CXX object CMakeFiles/pictureRecognition.out.dir/demo/exec/pictureRecognition.cpp.o
[ 97%] Built target MNNV2Basic.out
[ 97%] Built target getPerformance.out
[ 97%] Built target testModel.out
[ 97%] Built target backendTest.out
[ 98%] Built target pictureRotate.out
[ 98%] Built target MNNConvertDeps
[ 99%] Built target TestConvertResult
[100%] Built target MNNConvert
[100%] Linking CXX executable pictureRecognition.out
[100%] Built target pictureRecognition.out

**Comment by jxt1234** [comment]
Origin model come from mobilenet is trained from caffe. So the demo use BGR.
