### ISSUE TITLE
严重内存泄漏

### ISSUE THREAD

**Issue by ritsukaginn** [alibaba/MNN#1018]
多次调用runSession造成明显的内存增长。
多次调用pretreat->convert也会造成少量内存增长。

## Platform(Include target platform as well if cross-compiling):  
arm64-v8a

## Github Version:
a6836bb50a4ba615bfc8b6a367d282120a274097 

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

## Compiling Method
参考https://www.yuque.com/mnn/cn/build_android：
1. ./tools/script/get_model.sh（可选，模型仅demo工程需要）。注意get_model.sh需要事先编译好模型转换工具，参见这里。
2. cd project/android
3. 编译armv7动态库：mkdir build_32 && cd build_32 && ../build_32.sh
4. 编译armv8动态库：mkdir build_64 && cd build_64 && ../build_64.sh

**Comment by jxt1234** [comment]
有测试代码么？MNN一般是不会有内存泄露的，多数是调用的问题

**Comment by ritsukaginn** [comment]
---------------> img is a cv::Mat   

 int width = img.cols;
 int height = img.rows;
while(min_length > MIN_DETECTION_SIZE){
    int ws = (int)std::ceil(width * cur_scale);
    int hs = (int)std::ceil(height * cur_scale);
    std::vector<int> inputDims = {1,3,hs,ws};
    mNet->resizeTensor(mInput, inputDims);
    mNet->resizeSession(mSession);

    MNN::CV::Matrix trans;
    trans.postScale(1.0f/ws, 1.0f/hs);
    trans.postScale(width, height);
    pretreat->setMatrix(trans);
    pretreat->convert((uint8_t*)img.data,width, height, 0, mInput);

    mNet->runSession(mSession);
    cur_scale = cur_scale * FACTOR;
    min_length *= FACTOR;
}


-----------------------------
by running the above code, will observe memory increace.
I tried to set FACTOR to 1 (which means a infinit loop, but the input size of the sesson keep the same), the memory won't increase.

**Comment by jxt1234** [comment]
是不是因为你的输入一直增大而导致 session 占用的内存增大

**Comment by ritsukaginn** [comment]
并没有，FACTOR是一个小于1的数字。在linux c++端测试似乎没有检测到内存泄漏，但是在安卓的arm64-v8a有这个现象。

**Comment by ritsukaginn** [comment]
请问是否有进展。依旧观测到严重的内存泄漏。

**Comment by GukehAn** [comment]
我在ubuntu下测试也有内存泄漏

**Comment by 610265158** [comment]
我也发现了内存泄漏，

循环调用runSession会有内存泄漏
注掉这句话，内存就不增长
 MNN::ErrorCode mnn_excutor_code=mnn_interpreter->runSession(mnn_session);

**Comment by GukehAn** [comment]
我这边最终发现不是内存泄漏。我这边调试的是目标检测的代码，由于输入目标检测的宽高不一致，使得每次申请的内存不一样，而MNN 有内存申请限制，有些较大的图片就会导致报错。

**Comment by 610265158** [comment]
> 我这边最终发现不是内存泄漏。我这边调试的是目标检测的代码，由于输入目标检测的宽高不一致，使得每次申请的内存不一样，而MNN 有内存申请限制，有些较大的图片就会导致报错。

我再定位一下，可能是我使用的姿势不对

**Comment by jxt1234** [comment]
可以更新代码看下是否 resizeSession 的内存增长修复了

**Comment by longzeyilang** [comment]
@jxt1234 在aarch64-liunx下有严重内存泄漏，代码使用：https://github.com/RangiLyu/nanodet
检测工具用：valgrind
并且看内存逐渐在吃掉。

**Comment by longzeyilang** [comment]
@ritsukaginn 我在aarch64进行测试，是内存泄漏。我每张图像大小一致，用检测工具valgrind,存在这个。

**Comment by longzeyilang** [comment]
后面改为MNN1.2.9版本进行测试，MNN修复部分问题，例如在ImageProcess转化的内存泄漏已经修改掉，但是还存在以下问题：
==2146== Memcheck, a memory error detector
==2146== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2146== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==2146== Command: /gzy_mnt/gdsplusv2/demo/clublocal/golfDetection /gzy_mnt/club
==2146== 
111,/gzy_mnt/club/20220602115626285.png
==2146== Invalid write of size 8
==2146==    at 0x682F300: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff000300 is on thread 1's stack
==2146==  16 bytes below stack pointer
==2146== 
==2146== Invalid read of size 8
==2146==    at 0x682FB10: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff000300 is on thread 1's stack
==2146==  16 bytes below stack pointer
==2146== 
==2146== Invalid write of size 8
==2146==    at 0x682FC40: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff000300 is on thread 1's stack
==2146==  16 bytes below stack pointer
==2146== 
==2146== Invalid write of size 8
==2146==    at 0x682FC44: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002f0 is on thread 1's stack
==2146==  32 bytes below stack pointer
==2146== 
==2146== Invalid write of size 8
==2146==    at 0x682FC48: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002e0 is on thread 1's stack
==2146==  48 bytes below stack pointer
==2146== 
==2146== Invalid write of size 8
==2146==    at 0x682FC4C: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002d0 is on thread 1's stack
==2146==  64 bytes below stack pointer
==2146== 
==2146== Invalid read of size 8
==2146==    at 0x6830100: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff000300 is on thread 1's stack
==2146==  16 bytes below stack pointer
==2146== 
==2146== Invalid read of size 8
==2146==    at 0x6830104: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002f0 is on thread 1's stack
==2146==  32 bytes below stack pointer
==2146== 
==2146== Invalid read of size 8
==2146==    at 0x6830108: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002e0 is on thread 1's stack
==2146==  48 bytes below stack pointer
==2146== 
==2146== Invalid read of size 8
==2146==    at 0x683010C: ??? (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==  Address 0x1fff0002d0 is on thread 1's stack
==2146==  64 bytes below stack pointer
==2146== 
time cost: 0.837242
111,/gzy_mnt/club/20220602115626319.png
time cost: 0.772692
time cost: 1111
before:
after:
==2146== 
==2146== HEAP SUMMARY:
==2146==     in use at exit: 54,732 bytes in 662 blocks
==2146==   total heap usage: 59,950 allocs, 59,288 frees, 27,338,846 bytes allocated
==2146== 
==2146== 912 bytes in 3 blocks are possibly lost in loss record 431 of 438
==2146==    at 0x484E024: calloc (vg_replace_malloc.c:1117)
==2146==    by 0x400FA8F: allocate_dtv (in /lib/ld-2.28.so)
==2146==    by 0x4010347: _dl_allocate_tls (in /lib/ld-2.28.so)
==2146==    by 0x48720FB: pthread_create@@GLIBC_2.17 (in /lib/libpthread-2.28.so)
==2146==    by 0x69A9863: std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (in /lib/libstdc++.so.6.0.25)
==2146==    by 0x67E8DE3: MNN::ThreadPool::ThreadPool(int) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x67E9027: MNN::ThreadPool::init(int) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x67933EB: MNN::CPURuntime::CPURuntime(MNN::Backend::Info const&) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x6793543: MNN::CPURuntimeCreator::onCreate(MNN::Backend::Info const&) const (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x66EBBF7: MNN::RuntimeFactory::create(MNN::Backend::Info const&) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x66D8E83: MNN::Interpreter::createRuntime(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146==    by 0x66D9FC3: MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&) (in /gzy_mnt/gdsplusv2/lib/libMNN.so)
==2146== 
==2146== LEAK SUMMARY:
==2146==    definitely lost: 0 bytes in 0 blocks
==2146==    indirectly lost: 0 bytes in 0 blocks
==2146==      possibly lost: 912 bytes in 3 blocks
==2146==    still reachable: 53,820 bytes in 659 blocks
==2146==         suppressed: 0 bytes in 0 blocks
==2146== Reachable blocks (those to which a pointer was found) are not shown.
==2146== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2146== 
==2146== For lists of detected and suppressed errors, rerun with: -s
==2146== ERROR SUMMARY: 221363 errors from 11 contexts (suppressed: 0 from 0)

**Comment by jxt1234** [comment]
这个是全局初始化变量，不会超成内存增加的
