### ISSUE TITLE
预处理模块Convert 结果不对

### ISSUE THREAD

**Issue by bitLiuYang** [alibaba/MNN#1019]
我测试了一下，输入3x384x384的图片，配置的是trans是identity，然后mean是0， val是1，理论上convert前后，数据应该没有区别，但是，最后测试结果是，**每一行的最后一列，rgb都变成0了**，然后，其他位置数据没有变化。

# 平台(如果交叉编译请再附上交叉编译目标平台):  x86
# Platform(Include target platform as well if cross-compiling): x86  

# Github版本:
# Github Version:
commit a6836bb50a4ba615bfc8b6a367d282120a274097

**Comment by jxt1234** [comment]
Wrap 设成 CLAMP_TO_EDGE 呢?
ZERO 类型由于浮点计算精度可能会有边界少1的的情况

**Comment by bitLiuYang** [comment]
Wrap 设成 CLAMP_TO_EDGE 呢?这样最后一列就变成了和倒数第二行一致了，是不是没有从根源上解决掉最后一列少处理的问题?

**Comment by jxt1234** [comment]
你的矩阵不是 identity 吧，identity 的话走直接拷贝，不会有这个问题的。
