### ISSUE TITLE
x86平台与android arm64平台inference结果差异

### ISSUE THREAD

**Issue by bitLiuYang** [alibaba/MNN#1020]
请问下这两个平台结果会有差异吗？如果有，会是什么量级（0.0001?0.00001)
测过两个模型，一个差异在0.00001，另一个有些层甚至达到了0.1（用官方的MNNV2Basic.out工具）

**Comment by jxt1234** [comment]
会有少量差异，需要看百分比，大概在 0.1% 量级

**Comment by bitLiuYang** [comment]
这个差异产生的原因来自于什么呢？我理解的是，如果连个平台都采用标准float计算，那么结果应该是没有任何差别？在MNN中不同平台有些算子或者算法采用不同的计算方法吗?

**Comment by jxt1234** [comment]
SIMD 的实现不是完全按照 IEEE 浮点标准的(ARM 的 NEON , Interl 的 SSE / AVX 等)，
另外，即使完全按照 IEEE 的浮点标准的C++实现，换个计算顺序也都会有差异

**Comment by bitLiuYang** [comment]
![simd_float](https://user-images.githubusercontent.com/10795901/89097235-bc7b0c00-d40f-11ea-9163-be95220fa728.png)
见：https://developer.arm.com/architectures/instruction-sets/floating-point
neon simd是IEEE标准的

**Comment by jxt1234** [comment]
then? IEEE 浮点标准变换计算顺序也会结果有不同的

**Comment by bitLiuYang** [comment]
你能贴一个切换顺序导致结果不同的代码块吗？ @jxt1234
