### ISSUE TITLE
The 315's input is not ready

### ISSUE THREAD

**Issue by blueskywwc** [alibaba/MNN#1021]
interpreter = MNN.Interpreter("mobilenetv2_cifar112.mnn")
    session = interpreter.createSession()
    input_tensor = interpreter.getSessionInput(session)
    print('input_tensor:', input_tensor)
    print('shape:', input_tensor.getShape())

The output after running these 4 lines of code is:
The 315's input is not ready
Resize error for [Convolution], 315, code=3
input_tensor: <MNN.Tensor object at 0x7f95f7a7ef30>
shape: (0, 3, 112, 112)

What is the reason? thanks!

**Comment by jxt1234** [comment]
the input tensor's batch is 0 , please resize as 1

**Comment by blueskywwc** [comment]
我把pytorch模型转为onnx，再用转换工具转为mnn模型，执行上述代码后均为shape: (0, 3, 112, 112),batch为啥会是0;
使用demo中train_mnist训练出的mnn模型,执行上述代码后均为shape: (1, 1, 28, 28),推理正常，怎么解决呢，谢谢

**Comment by blueskywwc** [comment]
我已经解决了这个问题，是我pytorch转onnx时参数不正确，谢谢
