### ISSUE TITLE
[libprotobuf FATAL /usr/local/protobuf/include/google/protobuf/repeated_field.h:1506] CHECK failed: (index) < (current_size_):  terminate called after throwing an instance of 'google::protobuf::FatalException'   what():  CHECK failed: (index) < (current_size_):  Aborted (core dumped)

### ISSUE THREAD

**Issue by zcl912** [alibaba/MNN#103]
将caffe  model 转换成 .mnn事，出现这个错误

**Comment by jxt1234** [comment]
将 tools/converter/source/caffe/caffe.proto 替换为你的 caffe model 的 proto 再编转换工具试一下

**Comment by zcl912** [comment]
> 将 tools/converter/source/caffe/caffe.proto 替换为你的 caffe model 的 proto 再编转换工具试一下

我试了您的方法，还是一样的问题

**Comment by jxt1234** [comment]
你那个是什么样的caffe model ，是不是版本不一致?

**Comment by zcl912** [comment]
> 你那个是什么样的caffe model ，是不是版本不一致?

我是由pytorch转成的caffe model,都是常规的层，都支持。你说的是什么版本不一致呢

**Comment by jxt1234** [comment]
那转成 onnx ，用 onnx 转试一下?

**Comment by zcl912** [comment]
> 那转成 onnx ，用 onnx 转试一下？

转成onnx，用onnx转 mnn也是这样的问题

**Comment by czy2014hust** [comment]
will be added later

**Comment by VivienFu** [comment]
我也遇见了同样的问题，添加了新层，转换后出现同样的问题，先排查了新层的转换并没有问题。后来发现好象是我的prototxt中比caffemodel中的多出了一层，把prototxt最后一层的normlize层删除后，再编译就没有问题了。
我的这个应该只是其中一种错误原因没，给其他有相同问题的做参考。

**Comment by zhedasuiyuan** [comment]
> 将 tools/converter/source/caffe/caffe.proto 替换为你的 caffe model 的 proto 再编转换工具试一下

替换了之后会提示我的版本的caffe.proto里缺少一些layer的定义。按照错误提示加上去之后，还是报错。而且发现repo里的caffe.proto有些ID的layer和我的caffe.proto里同一个ID的不是同一个layer。请问有什么好的方法可以merge两个caffe.proto吗？尤其是id冲突的情况下。谢谢。
