### ISSUE TITLE
使用示例的图像分割的时候，显示 Don't support type [Convolution]

### ISSUE THREAD

**Issue by congjiye** [alibaba/MNN#1034]
# 平台:  
win10  2004 64位系统，vs2017 v15.9
![image](https://user-images.githubusercontent.com/41415004/89405685-91195980-d74e-11ea-9850-45b587003dff.png)
编译时和转换模型的时候都没有报错

# 编译方式:
使用ninja构建项目

```
# cmake 参数
cmake -G "Ninja" -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_CONVERTER=ON -DCMAKE_BUILD_TYPE=Release -DMNN_OPENCL=ON -DMNN_BUILD_DEMO=ON ..
```
### cmake 输出截图:
![image](https://user-images.githubusercontent.com/41415004/89406134-4ba95c00-d74f-11ea-8304-c1e38100d931.png)

# 问题:
使用云雀文档中提供的tensorflow分割模型显示Don't support type [Convolution], MobilenetV2/Conv/Relu16。

**Comment by dan520520520** [comment]
你好，这个问题你是怎么解决的，可以透漏一下吗？

**Comment by JyCAydon** [comment]
> 你好，这个问题你是怎么解决的，可以透漏一下吗？

我是编译了一个动态库以后可以使用。
文档里说可以在编译的时候添加`/WHOLEARCHIVE:MNN`这个。但是我不太清楚怎么用/(ㄒoㄒ)/~~

**Comment by dan520520520** [comment]
我试了在CMakeCache.txt编译时加/WHOLEARCHIVE:MNN，可以用。

**Comment by JyCAydon** [comment]
不好意思，能不能告诉我加到哪里呢😂。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: dan520520520<mailto:notifications@github.com>
发送时间: 2020年8月20日 下午 3:47
收件人: alibaba/MNN<mailto:MNN@noreply.github.com>
抄送: Jyc<mailto:congtheking@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [alibaba/MNN] 使用示例的图像分割的时候，显示 Don't support type [Convolution] (#1034)


我试了在CMakeCache.txt编译时加/WHOLEARCHIVE:MNN，可以用。

**Comment by dan520520520** [comment]
你邮箱有看到吗? 我下午发到你邮箱里面了。
MNN编译是不是不能生成sln，需要自己新建vs工程？你说的编译了动态库怎么编译，跟之前编译方法有什么区别吗？生成动态库以后，还是用自动生成的segment.out.exe吗？

**Comment by JyCAydon** [comment]
> 你邮箱有看到吗? 我下午发到你邮箱里面了。
> MNN编译是不是不能生成sln，需要自己新建vs工程？你说的编译了动态库怎么编译，跟之前编译方法有什么区别吗？生成动态库以后，还是用自动生成的segment.out.exe吗？
编译动态库就是把`-DMNN_BUILD_SHARED_LIBS=OFF`这个改为`-DMNN_BUILD_SHARED_LIBS=ON`，生成之后还是用自动生成的segment.out.exe

**Comment by dan520520520** [comment]
vs 的 sln你有自动生成吗? 还是必须自己建vs工程使用MNN库

**Comment by JyCAydon** [comment]
用的是ninja生成的应该是build.ninja文件，要是想生成vs的sln你要把`cmake -G "Ninja" `改成`cmake -G "NMake Makefiles"`

**Comment by dan520520520** [comment]
谢谢

**Comment by dan520520520** [comment]
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_DEMO=ON -DMNN_BUILD_SHARED_LIBS=ON ..
nmake
我用上面编译，但是好像没有生成sln?

**Comment by JyCAydon** [comment]
sorry，编译sln的应该是这个 `cmake -G "Visual Studio 15 Win64"` 15代表用的vs2017

**Comment by dan520520520** [comment]
谢谢，生成了。

**Comment by jxt1234** [comment]
静态库的使用参考 https://www.yuque.com/mnn/en/faq 
另外新版本 1.1.0 之后CPU的算子默认采用代码生成的方式注册，不再有这个问题
