### ISSUE TITLE
InstanceNorm层x86与android平台结果有差异

### ISSUE THREAD

**Issue by oppoozh555** [alibaba/MNN#1038]
- **其它层是完全能对上的,从这个层后就开始对不上了,差异最大在超过了0.1**
![image](https://user-images.githubusercontent.com/69297146/89504877-bdf15f00-d796-11ea-9a34-7c947e88f7a9.png)

# Github版本:a408209d383f73befb57f93c16532fd952af6156
# Github Version:a408209d383f73befb57f93c16532fd952af6156

**Comment by oppoozh555** [comment]
@jxt1234 能麻烦帮忙看下吗?

**Comment by jxt1234** [comment]
x86 的 instancenorm 实现用了 pow ，可能有些误差

**Comment by oppoozh555** [comment]
那BatchNorm层为啥没有这个误差呢?

**Comment by oppoozh555** [comment]
@jxt1234 麻烦帮忙解答下吗?非常感谢!

**Comment by jxt1234** [comment]
目前已经是一样的逻辑
