### ISSUE TITLE
MMN build error MNNConverterOpt

### ISSUE THREAD

**Issue by HakanKumdakci** [alibaba/MNN#1039]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu 18.04 LTS

# Github版本:
# Github Version:
0.2.2.3

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``
06.07.2020

# 编译方式:
# Compiling Method
cd /path/to/MNN
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j2
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin

cmake .. -DMNN_BUILD_CONVERTER=true && make -j2
```
NN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/hakanhodas/MNN/build

# 编译日志:
# Build Log:
```
粘贴在这里
Paste log here or pastebin
[ 56%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSliceMerge.cpp.o
[ 56%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSoftplus.cpp.o
[ 56%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSoftsign.cpp.o
[ 56%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/FullConnect.cpp.o
[ 56%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/TFliteExtraManager.cpp.o
[ 56%] Built target MNNConverterOpt
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by jizhu1023** [comment]
遇到了同样的问题，@HakanKumdakci 请问最后如何解决？

**Comment by HakanKumdakci** [comment]
我无法解决这个问题。

**Comment by jxt1234** [comment]
关闭历史问题
