### ISSUE TITLE
tflite到mnn，模型加载后输出tensor的形状有问题

### ISSUE THREAD

**Issue by rikichou** [alibaba/MNN#1041]
我进行的是当前tflite到mnn的转换，是一个人脸检测模型，然后先使用python来测试了一下，发现加载模型之后，获取输出tensor的形状，结果是[0,0,0,0]，正确的输出形状应该是[1,6]，输出如下图
![image](https://user-images.githubusercontent.com/10046013/89630133-7fac8a80-d8d1-11ea-9df6-b3e7995aa1f3.png)
而且还出现了一个reshape的error，但是这个tflite是可以正常使用的，转换过程也没有出现警告信息，麻烦知道的朋友提供一些解决思路，模型上传了
[face_detection_test.tflite.zip](https://github.com/alibaba/MNN/files/5040453/face_detection_test.tflite.zip)
[face_oldtf.mnn.zip](https://github.com/alibaba/MNN/files/5040445/face_oldtf.mnn.zip)

**Comment by rikichou** [comment]
我发现这个reshape的错误发生在后处理阶段，生成anchor grid的时候，是不是mnn不支持后处理？需要手动实现？

**Comment by rikichou** [comment]
我使用pip安装的python版本的mnn，目前版本是1.0.1，是不是这个版本太老？
![image](https://user-images.githubusercontent.com/10046013/89631315-35c4a400-d8d3-11ea-98cd-675c04f7051d.png)

**Comment by rikichou** [comment]
发现tflite到MNN这条路不可行，我又自己训练了一个pytorch模型，转为onnx，再转为mnn模型，然后使用和之前一样的测试代码，发现结果正确，预测结果小数点后5位都和pytorch的预测结果一致。其中测试代码分别在MNN的python api和源码里面的C++代码测试，结论均一致。并且在C++代码中，我是直接用如下的形式来拷贝数据到模型的输入的，所以数据输入是没有问题的（sample就是图片数据，经过预处理的），同样的测试代码，使用pytorch和tflite转换过来的mnn模型进行测试，发现只有pytorch的正确率，而且没有精度损失，tflite几乎就是一个定值。
memcpy(inputTensorUser.host<float>(), sample, sizeof(float)*inputTensorUser.height()*inputTensorUser.width()*inputTensorUser.channel());
        inputTensor->copyFromHostTensor(&inputTensorUser);

所以MNN对tflite是支持得不好的，估计是因为tflite仅仅支持NHWC的输入通道顺序（因为我尝试训练了一个NCHW的kera s模型，然后转化为tflite的时候提示我不支持NCHW的通道顺序，版本tf 2.3.0），但是转化为MNN的时候被强制转换成了NCHW的顺序，我估计就是这里出的问题（因为mnnconvert进行模型转换的时候没有参数可以设置我转换的模型是什么通道顺序，所以一律都转换为NCHW）。

所以现在要使用的MNN的话，所有算法都得在pytorch再实现一次，好纠结啊！

MNN和TFLITE比较：
      单线程方面，速度有一定优势，但是不明显（可能跟我使用的移动端的平台或者模型有关？我用的是armv7架构的CPU），比如我一个浮点模型，MNN跑72ms（使用的tlfite模型直接转换过来的，虽然预测结果不对，但是用来看看运行时间还是可以的），tflite跑80ms。
      2线程，都差不多，两个都降了50%左右的时间
      差距在于4线程，MNN的四线程非常稳定，预测时间也就不到20ms，主要是一直都很稳定。但是TFLITE就直接炸了，30-60ms不等，甚至还不如2线程。
      但是，线程再多的话，大家都不行了，时间都跑飞了（应该是我们的板子只有4核的缘故。。。。。）

各位有从tflite转MNN的经历吗，是MNN本身对TFLITE支持不好还是我哪儿弄错了

**Comment by rikichou** [comment]
更正一下上面提到的速度比较（均在MNN的正常精度模式下：0）
单线程：tflite是80ms左右，MNN 60ms
2线程：tflite是43-53ms不等，MNN 25ms
所以MNN还是很强的

**Comment by SomeO** [comment]
> 我进行的是当前tflite到mnn的转换，是一个人脸检测模型，然后先使用python来测试了一下，发现加载模型之后，获取输出tensor的形状，结果是[0,0,0,0]，正确的输出形状应该是[1,6]，输出如下图
> ![image](https://user-images.githubusercontent.com/10046013/89630133-7fac8a80-d8d1-11ea-9df6-b3e7995aa1f3.png)
> 而且还出现了一个reshape的error，但是这个tflite是可以正常使用的，转换过程也没有出现警告信息，麻烦知道的朋友提供一些解决思路，模型上传了
> [face_detection_test.tflite.zip](https://github.com/alibaba/MNN/files/5040453/face_detection_test.tflite.zip)
> [face_oldtf.mnn.zip](https://github.com/alibaba/MNN/files/5040445/face_oldtf.mnn.zip)

你好，我这边遇到的情况是，用Python测试输入和输出是正常的，但是在android studio中测试，输入是正常的，但是输出是{0, 
 0, 0, 0}, 然后换一个模型，同样的代码，输入和输出都是正常的，大佬有遇到过这种情况么，求解

**Comment by SomeO** [comment]
就是这段代码：https://github.com/alibaba/MNN/blob/master/demo/android/app/src/main/jni/mnnnetnative.cpp#L173
