### ISSUE TITLE
运行官方的DEMO发现，在Android和IOS上CPU占用率表现差很多，苹果手机发烫迅速。

### ISSUE THREAD

**Issue by annpeter** [alibaba/MNN#1042]
运行官方的DEMO发现，在Android和IOS上CPU占用率表现差很多，苹果手机发烫迅速。

编译平台：MacOS
运行平台：Android 和 IOS
Android手机型号：华为荣耀7X
IOS手机型号：iPhone7

Android手机运行时截图
![image](https://user-images.githubusercontent.com/7344217/89724005-3757ae80-da30-11ea-87f2-06886c9ac9be.png)
![image](https://user-images.githubusercontent.com/7344217/89724055-c95fb700-da30-11ea-8391-e0663ac6d145.png)

IOS手机运行时截图
![image](https://user-images.githubusercontent.com/7344217/89723943-a08af200-da2f-11ea-9e0d-fc65fa71476c.png)
![image](https://user-images.githubusercontent.com/7344217/89723949-ac76b400-da2f-11ea-8ea0-01997a6556b6.png)

**Comment by lapvision** [comment]
请问这个问题是啥原因，急需答案，谢谢！

**Comment by jxt1234** [comment]
可以把 ios 的 thread 设成 2或 1 试下
