### ISSUE TITLE
mali t860  opencl  device->copyToHostTensor(tensor) very slow

### ISSUE THREAD

**Issue by mathpopo** [alibaba/MNN#1047]
if select opencl  as device

copy opencl tensor to HOST,so slowly.

**Comment by mathpopo** [comment]
https://bbs.gpuworld.cn/index.php?topic=10798.0

**Comment by mathpopo** [comment]
void OpenCLBackend::onCopyBuffer(const Tensor* srcTensor, const Tensor* dstTensor) const {
#ifdef LOG_VERBOSE
    MNN_PRINT("Start onCopyBuffer !\n");
#endif
    //int8
    if(srcTensor->getType().code == halide_type_int && srcTensor->getType().bits == 8){
        if (srcTensor->deviceId() == 0 && dstTensor->deviceId() != 0) {
            copyToDeviceInt8(srcTensor, dstTensor);
        }else if(srcTensor->deviceId() != 0 && dstTensor->deviceId() == 0){
            copyFromDeviceInt8(srcTensor, dstTensor);
        }else{
            MNN_PRINT("onCopyBuffer int8 error !!! \n");
        }
    }else{
        if (srcTensor->deviceId() == 0 && dstTensor->deviceId() != 0) {
            copyToDevice(srcTensor, dstTensor);
        }else if(srcTensor->deviceId() != 0 && dstTensor->deviceId() == 0){
            copyFromDevice(srcTensor, dstTensor);
        }else{
            MNN_PRINT("onCopyBuffer float error !!! \n");
        }
    }

#ifdef LOG_VERBOSE
    MNN_PRINT("end onCopyBuffer !\n");
#endif
}

**Comment by mathpopo** [comment]
void OpenCLBackend::copyFromDevice(const Tensor* srcTensor, const Tensor* dstTensor) const{
    std::vector<int> bufferShape = MNN::OpenCL::tensorShapeFormat(srcTensor);
    MNN::Tensor interBuffer(0, Tensor::TENSORFLOW);
    interBuffer.buffer().dimensions = bufferShape.size();
    for (int i = 0; i < bufferShape.size(); i++) {
        interBuffer.buffer().dim[i].extent = bufferShape.at(i);
    }
    auto needSize = dstTensor->size();
    _allocHostBuffer(needSize);
    interBuffer.buffer().device = (uint64_t)mHostBuffer.second.get();

    MNN_DATA_FORMAT data_format = TensorUtils::getDescribe(dstTensor)->dimensionFormat;
    switch (data_format) {
        case MNN_DATA_FORMAT_NHWC:
            OpenCL::convertImageToNHWCBuffer(srcTensor, &interBuffer,
                                             *const_cast<cl::Kernel*>(&mImageToNHWCBufferFloat), mOpenCLRuntime.get());
            break;
        case MNN_DATA_FORMAT_NCHW:
            OpenCL::convertImageToNCHWBuffer(srcTensor, &interBuffer,
                                             *const_cast<cl::Kernel*>(&mImageToNCHWBufferFloat), mOpenCLRuntime.get());
            break;
        case MNN_DATA_FORMAT_NC4HW4:
            OpenCL::convertImageToNC4HW4Buffer(
                srcTensor, &interBuffer, *const_cast<cl::Kernel*>(&mImageToNC4HW4BufferFloat), mOpenCLRuntime.get());
            break;
        default:
            break;
    }
    auto hostPtr = dstTensor->host<float>();
    cl_int error                = CL_SUCCESS;

    mOpenCLRuntime->commandQueue().enqueueReadBuffer(*mHostBuffer.second, CL_TRUE, 0, needSize, hostPtr);
}

**Comment by mathpopo** [comment]
void OpenCLBackend::_allocHostBuffer(int length) const {
    MNN_ASSERT(length > 0);
    if (nullptr != mHostBuffer.second && length <= mHostBuffer.first) {
        return;
    }
    mHostBuffer.first = length;
    mHostBuffer.second.reset(
        new cl::Buffer(mOpenCLRuntime->context(), CL_MEM_READ_WRITE | CL_MEM_ALLOC_HOST_PTR, length));
}

**Comment by mathpopo** [comment]
bool Tensor::copyToHostTensor(Tensor* hostTensor) const {
    auto bn = mDescribe->backend;
    if (nullptr == bn) {
        return false;
    }
    bn->onCopyBuffer(this, hostTensor);
    return true;
}

**Comment by mathpopo** [comment]
onCopyBuffer--->copyFromDevice--->_allocHostBuffer--->new cl::Buffer(mOpenCLRuntime->context(), CL_MEM_READ_WRITE | CL_MEM_ALLOC_HOST_PTR, length));

**Comment by mathpopo** [comment]
https://www.cnblogs.com/biglucky/p/4033521.html

**Comment by mathpopo** [comment]
CL_MEM_USE_PERSISTENT_MEM_AMD 和CL_MEM_ALLOC_HOST_PTR的不同之处，前者创建device驻留的zero copy memory，后者创建host驻留的zero copy memory。
所以copyfromhosttodevice is quicly
但是，copyformdevicetohost is slowly

**Comment by mathpopo** [comment]
如果host memory object需要频繁进行map操作，建议使用CL_MEM_ALLOC_HOST_PTR和CL_MEM_COPY_HOST_PTR，相应的，如果device memory需要频繁map，使用CL_MEM_USE_PERSISTENT_MEM_AMD以及clEnqueueWriteBuffer。

**Comment by mathpopo** [comment]
请问下现在MNN今后有CL_MEM_USE_PERSISTENT_MEM_AMD的添加计划吗？

**Comment by mathpopo** [comment]
https://blog.csdn.net/cloud_desktop/article/details/20136009?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.channel_param

**Comment by Naville** [comment]
已离职，勿扰

**Comment by mathpopo** [comment]
void OpenCLBackend::copyFromDevice(const Tensor* srcTensor, const Tensor* dstTensor) const{
    std::vector<int> bufferShape = MNN::OpenCL::tensorShapeFormat(srcTensor);
    MNN::Tensor interBuffer(0, Tensor::TENSORFLOW);
    interBuffer.buffer().dimensions = bufferShape.size();
    for (int i = 0; i < bufferShape.size(); i++) {
        interBuffer.buffer().dim[i].extent = bufferShape.at(i);
    }
    auto needSize = dstTensor->size();
    _allocHostBuffer(needSize);
    interBuffer.buffer().device = (uint64_t)mHostBuffer.second.get();

    MNN_DATA_FORMAT data_format = TensorUtils::getDescribe(dstTensor)->dimensionFormat;
    auto timeBegin1 = 1.0;
    auto timeEnd1 = 1.0;
    auto timeBegin2 = 1.0;
    auto timeEnd2 = 1.0;
    auto timeBegin3 = 1.0;
    auto timeEnd3 = 1.0;
    switch (data_format) {
        case MNN_DATA_FORMAT_NHWC:
            timeBegin1 = getTimeInUs();
            OpenCL::convertImageToNHWCBuffer(srcTensor, &interBuffer,
                                             *const_cast<cl::Kernel*>(&mImageToNHWCBufferFloat), mOpenCLRuntime.get());
            timeEnd1 = getTimeInUs();
            std::cout << "CHENXIN  copyFromDevice  convertImageToNHWCBuffer cost: " << (timeEnd1 - timeBegin1) / 1000.0 << " ms." << std::endl;
            break;
        case MNN_DATA_FORMAT_NCHW:
            timeBegin2 = getTimeInUs();
            OpenCL::convertImageToNCHWBuffer(srcTensor, &interBuffer,
                                             *const_cast<cl::Kernel*>(&mImageToNCHWBufferFloat), mOpenCLRuntime.get());
            timeEnd2 = getTimeInUs();
            std::cout << "CHENXIN  copyFromDevice  convertImageToNCHWBuffer cost: " << (timeEnd2 - timeBegin2) / 1000.0 << " ms." << std::endl;
            break;
        case MNN_DATA_FORMAT_NC4HW4:
            timeBegin3 = getTimeInUs();
            OpenCL::convertImageToNC4HW4Buffer(
                srcTensor, &interBuffer, *const_cast<cl::Kernel*>(&mImageToNC4HW4BufferFloat), mOpenCLRuntime.get());
            timeEnd3 = getTimeInUs();
            std::cout << "CHENXIN  copyFromDevice  convertImageToNC4HW4Buffer cost: " << (timeEnd3 - timeBegin3) / 1000.0 << " ms." << std::endl;
            break;
        default:
            break;
    }
    auto hostPtr = dstTensor->host<float>();
    cl_int error                = CL_SUCCESS;
    auto timeBegin = getTimeInUs();
    mOpenCLRuntime->commandQueue().enqueueReadBuffer(*mHostBuffer.second, CL_TRUE, 0, needSize, hostPtr);
    auto timeEnd = getTimeInUs();
    //MNN_PRINT('CHENXIN  copyFromDevice  enqueueReadBuffer cost:%lu ms',(timeEnd - timeBegin) / 1000.0);
    std::cout << "CHENXIN  copyFromDevice  enqueueReadBuffer cost: " << (timeEnd - timeBegin) / 1000.0 << " ms." << std::endl;
}
void OpenCLBackend::copyToDevice(const Tensor* srcTensor, const Tensor* dstTensor) const{
    std::vector<int> bufferShape = MNN::OpenCL::tensorShapeFormat(srcTensor);
    MNN::Tensor interBuffer(0, Tensor::TENSORFLOW);
    interBuffer.buffer().dimensions = bufferShape.size();
    for (int i = 0; i < bufferShape.size(); i++) {
        interBuffer.buffer().dim[i].extent = bufferShape.at(i);
    }
    auto needSize = srcTensor->size();
    _allocHostBuffer(needSize);
    interBuffer.buffer().device = (uint64_t)mHostBuffer.second.get();
    auto hostPtr                = srcTensor->host<float>();
    cl_int error                = CL_SUCCESS;
    auto timeBegin = getTimeInUs();
    mOpenCLRuntime->commandQueue().enqueueWriteBuffer(*mHostBuffer.second, CL_TRUE, 0, needSize, hostPtr);
    auto timeEnd = getTimeInUs();
    std::cout << "CHENXIN  copyToDevice  enqueueWriteBuffer cost: " << (timeEnd - timeBegin) / 1000.0 << " ms." << std::endl;
    // Host -> OpenCL
    MNN_DATA_FORMAT data_format = TensorUtils::getDescribe(srcTensor)->dimensionFormat;
    auto timeBegin1 = 1.0;
    auto timeEnd1 = 1.0;
    auto timeBegin2 = 1.0;
    auto timeEnd2 = 1.0;
    auto timeBegin3 = 1.0;
    auto timeEnd3 = 1.0;
    if (MNN_DATA_FORMAT_NHWC == data_format) {
        timeBegin1 = getTimeInUs();
        OpenCL::convertNHWCBufferToImage(&interBuffer, const_cast<Tensor*>(dstTensor),
                                         *const_cast<cl::Kernel*>(&mNHWCBufferToImageFloat), mOpenCLRuntime.get());
        timeEnd1 = getTimeInUs();
        std::cout << "CHENXIN  copyToDevice  convertNHWCBufferToImage cost: " << (timeEnd1 - timeBegin1) / 1000.0 << " ms." << std::endl;
        return;
    }
    if (MNN_DATA_FORMAT_NCHW == data_format) {
        timeBegin2 = getTimeInUs();
        OpenCL::convertNCHWBufferToImage(&interBuffer, const_cast<Tensor*>(dstTensor),
                                         *const_cast<cl::Kernel*>(&mNCHWBufferToImageFloat), mOpenCLRuntime.get());
        timeEnd2 = getTimeInUs();
        std::cout << "CHENXIN  copyToDevice  convertNCHWBufferToImage cost: " << (timeEnd2 - timeBegin2) / 1000.0 << " ms." << std::endl;
        return;
    }
    if (MNN_DATA_FORMAT_NC4HW4 == data_format) {
        timeBegin3 = getTimeInUs();
        OpenCL::convertNC4HW4BufferToImage(&interBuffer, const_cast<Tensor*>(dstTensor),
                                           *const_cast<cl::Kernel*>(&mNC4HW4BufferToImageFloat),
                                           mOpenCLRuntime.get());
        timeEnd3 = getTimeInUs();
        std::cout << "CHENXIN  copyToDevice  convertNC4HW4BufferToImage cost: " << (timeEnd3 - timeBegin3) / 1000.0 << " ms." << std::endl;
        return;
    }
    MNN_ASSERT(false);
    return;
}

**Comment by mathpopo** [comment]
耗时：enqueueReadBuffer

![145](https://user-images.githubusercontent.com/21274466/89969428-f27a8480-dc88-11ea-9e97-e9e503f7bb4a.jpeg)

**Comment by mathpopo** [comment]
这个请问有用的demo吗？

class SharedBuffer : public NonCopyable {
public:
    SharedBuffer(cl::Context& context, const std::shared_ptr<OpenCLRuntime>& runtime, int length): mRuntime(runtime), mLength(length){
        mHostBufferPtr = new cl::Buffer(context, CL_MEM_READ_WRITE | CL_MEM_ALLOC_HOST_PTR, mLength);
        cl_int error                = CL_SUCCESS;
        mHostPtr = mRuntime.get()->commandQueue().enqueueMapBuffer(*mHostBufferPtr, CL_TRUE, CL_MAP_WRITE|CL_MAP_READ, 0,
                                                                         mLength, nullptr, nullptr, &error);
        if (error != CL_SUCCESS) {
            MNN_ERROR("Error to map buffer in copy buffer, error=%d\n", error);
            return;
        }
    }

    ~SharedBuffer(){
        if(mHostBufferPtr != nullptr && mHostPtr != nullptr){
            mRuntime.get()->commandQueue().enqueueUnmapMemObject(*mHostBufferPtr, mHostPtr);
        }
        if(mHostBufferPtr != nullptr){
            delete mHostBufferPtr;
        }
    }

    cl::Buffer* getBuffer(){
        return mHostBufferPtr;
    }

    void* getHostPtr(){
        return mHostPtr;
    }

private:
    cl::Buffer* mHostBufferPtr{nullptr};
    std::shared_ptr<OpenCLRuntime> mRuntime;
    int mLength;
    void* mHostPtr{nullptr};
};

**Comment by menchunlei** [comment]
> void OpenCLBackend::copyFromDevice(const Tensor* srcTensor, const Tensor* dstTensor) const{
> std::vector bufferShape = MNN::OpenCL::tensorShapeFormat(srcTensor);
> MNN::Tensor interBuffer(0, Tensor::TENSORFLOW);
> interBuffer.buffer().dimensions = bufferShape.size();
> for (int i = 0; i < bufferShape.size(); i++) {
> interBuffer.buffer().dim[i].extent = bufferShape.at(i);
> }
> auto needSize = dstTensor->size();
> _allocHostBuffer(needSize);
> interBuffer.buffer().device = (uint64_t)mHostBuffer.second.get();
> 
> ```
> MNN_DATA_FORMAT data_format = TensorUtils::getDescribe(dstTensor)->dimensionFormat;
> auto timeBegin1 = 1.0;
> auto timeEnd1 = 1.0;
> auto timeBegin2 = 1.0;
> auto timeEnd2 = 1.0;
> auto timeBegin3 = 1.0;
> auto timeEnd3 = 1.0;
> switch (data_format) {
>     case MNN_DATA_FORMAT_NHWC:
>         timeBegin1 = getTimeInUs();
>         OpenCL::convertImageToNHWCBuffer(srcTensor, &interBuffer,
>                                          *const_cast<cl::Kernel*>(&mImageToNHWCBufferFloat), mOpenCLRuntime.get());
>         timeEnd1 = getTimeInUs();
>         std::cout << "CHENXIN  copyFromDevice  convertImageToNHWCBuffer cost: " << (timeEnd1 - timeBegin1) / 1000.0 << " ms." << std::endl;
>         break;
>     case MNN_DATA_FORMAT_NCHW:
>         timeBegin2 = getTimeInUs();
>         OpenCL::convertImageToNCHWBuffer(srcTensor, &interBuffer,
>                                          *const_cast<cl::Kernel*>(&mImageToNCHWBufferFloat), mOpenCLRuntime.get());
>         timeEnd2 = getTimeInUs();
>         std::cout << "CHENXIN  copyFromDevice  convertImageToNCHWBuffer cost: " << (timeEnd2 - timeBegin2) / 1000.0 << " ms." << std::endl;
>         break;
>     case MNN_DATA_FORMAT_NC4HW4:
>         timeBegin3 = getTimeInUs();
>         OpenCL::convertImageToNC4HW4Buffer(
>             srcTensor, &interBuffer, *const_cast<cl::Kernel*>(&mImageToNC4HW4BufferFloat), mOpenCLRuntime.get());
>         timeEnd3 = getTimeInUs();
>         std::cout << "CHENXIN  copyFromDevice  convertImageToNC4HW4Buffer cost: " << (timeEnd3 - timeBegin3) / 1000.0 << " ms." << std::endl;
>         break;
>     default:
>         break;
> }
> auto hostPtr = dstTensor->host<float>();
> cl_int error                = CL_SUCCESS;
> auto timeBegin = getTimeInUs();
> mOpenCLRuntime->commandQueue().enqueueReadBuffer(*mHostBuffer.second, CL_TRUE, 0, needSize, hostPtr);
> auto timeEnd = getTimeInUs();
> //MNN_PRINT('CHENXIN  copyFromDevice  enqueueReadBuffer cost:%lu ms',(timeEnd - timeBegin) / 1000.0);
> std::cout << "CHENXIN  copyFromDevice  enqueueReadBuffer cost: " << (timeEnd - timeBegin) / 1000.0 << " ms." << std::endl;
> ```
> 
> }

@mathpopo hello,  would you fix it ?

**Comment by mathpopo** [comment]
@menchunlei change your device,using "clpeak" apk to test your device first
