### ISSUE TITLE
MNN支持双向LSTM吗

### ISSUE THREAD

**Issue by justcainiao** [alibaba/MNN#1048]
如题

**Comment by tang576225574** [comment]
不支持的，需要自己手动实现

**Comment by jxt1234** [comment]
已经支持，不过性能还待优化

**Comment by thomaszheng** [comment]
@jxt1234 能不能增加一下rnn/lstm网络的demo?

**Comment by xiaoheizi123** [comment]
@jxt1234 下载了最新的MNN便编译后，也能编译完成，但是会有提示”Check it out ==> 74 has empty input, the index is 4”，如下所示
_

```
/opt/MNN1.1-master/build# ./MNNConvert -f ONNX  --modelFile /lstm_net.onnx --MNNModel lstm_net.mnn --bizCode mnn

MNNConverter Version: 0.2.1.5git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
[13:53:26] /opt/MNN1.1-master/tools/converter/source/onnx/onnxConverter.cpp:31: ONNX Model ir version: 6
[13:53:26] /opt/MNN1.1-master/tools/converter/source/onnx/onnxConverter.cpp:155: Check it out ==> 74 has empty input, the index is 4
Start to Optimize the MNN Net...
[13:53:26] /opt/MNN1.1-master/tools/converter/source/optimizer/PostConverter.cpp:64: Inputs: input.1
[13:53:26] /opt/MNN1.1-master/tools/converter/source/optimizer/PostConverter.cpp:69: Outputs: 83
Converted Done!
```

_


在调用编译好的mnn时，没有正确结果返回，断点调试时，报错如下
```
-> session = interpreter.createSession()
(Pdb) n
Error for 143
Resize error for [MatMul], MatMul12, code=3
```


请问这是还不支持bidirectional=True吗？
模型也很简单，如下
```
class RNN(nn.Module):
    def __init__(self, dropout_p=0.5):
        super(RNN, self).__init__()
        self.hidden_size=64
        self.dropout_p = dropout_p
        self.rnn = nn.LSTM(
            input_size=TIME_STEP,
            hidden_size=self.hidden_size,
            num_layers=1,  #10
            batch_first=True,
            bidirectional=True,
        )
        self.dropput1 = nn.Dropout(self.dropout_p)
        self.l_out = nn.Linear(64*2, 8)

    def forward(self, x):
        r_out, (h_n, h_c) = self.rnn(x)
        r_out = self.dropput1(r_out)
        out = self.l_out(r_out[:, -1, :])
        return out
```

**Comment by cendelian** [comment]
> @jxt1234 下载了最新的MNN便编译后，也能编译完成，但是会有提示”Check it out ==> 74 has empty input, the index is 4”，如下所示
> _
> 
> ```
> /opt/MNN1.1-master/build# ./MNNConvert -f ONNX  --modelFile /lstm_net.onnx --MNNModel lstm_net.mnn --bizCode mnn
> 
> MNNConverter Version: 0.2.1.5git - MNN @ 2018
> 
> 
> Start to Convert Other Model Format To MNN Model...
> [13:53:26] /opt/MNN1.1-master/tools/converter/source/onnx/onnxConverter.cpp:31: ONNX Model ir version: 6
> [13:53:26] /opt/MNN1.1-master/tools/converter/source/onnx/onnxConverter.cpp:155: Check it out ==> 74 has empty input, the index is 4
> Start to Optimize the MNN Net...
> [13:53:26] /opt/MNN1.1-master/tools/converter/source/optimizer/PostConverter.cpp:64: Inputs: input.1
> [13:53:26] /opt/MNN1.1-master/tools/converter/source/optimizer/PostConverter.cpp:69: Outputs: 83
> Converted Done!
> ```
> 
> _
> 
> 在调用编译好的mnn时，没有正确结果返回，断点调试时，报错如下
> 
> ```
> -> session = interpreter.createSession()
> (Pdb) n
> Error for 143
> Resize error for [MatMul], MatMul12, code=3
> ```
> 
> 请问这是还不支持bidirectional=True吗？
> 模型也很简单，如下
> 
> ```
> class RNN(nn.Module):
>     def __init__(self, dropout_p=0.5):
>         super(RNN, self).__init__()
>         self.hidden_size=64
>         self.dropout_p = dropout_p
>         self.rnn = nn.LSTM(
>             input_size=TIME_STEP,
>             hidden_size=self.hidden_size,
>             num_layers=1,  #10
>             batch_first=True,
>             bidirectional=True,
>         )
>         self.dropput1 = nn.Dropout(self.dropout_p)
>         self.l_out = nn.Linear(64*2, 8)
> 
>     def forward(self, x):
>         r_out, (h_n, h_c) = self.rnn(x)
>         r_out = self.dropput1(r_out)
>         out = self.l_out(r_out[:, -1, :])
>         return out
> ```

你好请问你解决这个问题了吗？我也遇到一样的问题，lstm 的onnx转mnn后输出不对
