### ISSUE TITLE
交叉編譯 opencl 編譯成功 執行失敗 

### ISSUE THREAD

**Issue by Hank0223** [alibaba/MNN#1053]
# 平台(如果交叉编译请再附上交叉编译目标平台): 
交叉编译目标平台：NXP S32V234evb

# Github版本: MNN-1.0.0

# 编译方式:
mkdir build && cd build
cmake .. \
-DCMAKE_SYSTEM_NAME=Linux \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=aarch64 \
-DCMAKE_C_COMPILER=/home/wpi/NXP/S32DS_Vision_v2018.R1/Cross_Tools/gcc-6.3-arm64-linux/bin/aarch64-linux-gnu-gcc \
-DCMAKE_CXX_COMPILER=/home/wpi/NXP/S32DS_Vision_v2018.R1/Cross_Tools/gcc-6.3-arm64-linux/bin/aarch64-linux-gnu-g++

请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
[CMakeLists.txt](https://github.com/alibaba/MNN/files/5063137/CMakeLists.txt)

# 執行結果:
<img width="802" alt="未命名" src="https://user-images.githubusercontent.com/58155722/90023230-11f3ca80-dce6-11ea-8a87-06f1a85ffdbe.png">

**Comment by wangzhaode** [comment]
请更新至最细代码测试
