### ISSUE TITLE
ERROR CODE : -54 when using opencl

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#1055]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
OSX

# Github版本:
# Github Version:
1.0.2

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

MNN_BUILD_SHARED_LIBS=OFF
MNN_FMA_ENABLE=ON
MNN_OPENCL=ON

# 编译日志:
# Build Log:

```
The Creator Don't support type 7, Greater
Don't support type Cast, ToFloat
beyond cl_image creat size! fallback to cpu backend
beyond cl_image creat size! fallback to cpu backend
Don't support type Cast, ToInt32
Don't support type OneHot, one_hot
beyond cl_image creat size! fallback to cpu backend
ERROR CODE : -54 
ERROR CODE : -54 
ERROR CODE : -54 
ERROR CODE : -54 
ERROR CODE : -54 
ERROR CODE : -54 
ERROR CODE : -54
```

This is not an reproducible issue on all osx. 
Just some users reported me that 
That user's osx spec is below.

iMac (Retina 5k, 27-inch, 2019)
3.7 GHz 6core Intel core i5
32gb ddr4 memory,
Radeon Pro 580X 8gb

Please chec this issue.
Thank you.

**Comment by GHLab** [comment]
I resolved this issue by passing the local_work_size to NULL. https://github.com/alibaba/MNN/blob/master/3rd_party/OpenCLHeaders/CL/cl2.hpp#L7875
But I don't know this is correct way. 
Please take look at this issue.

**Comment by mhsszm** [comment]
遇到了同样的问题，楼主是怎么解决的？ 我这OPENCL版本，1.2

**Comment by jxt1234** [comment]
先更新下试试吧，还有问题再打开
