### ISSUE TITLE
不同平台的精度问题

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [alibaba/MNN#1060]
# 一个三层的简单的TF网络， conv+conv+deconv( 其中激活函数是leaky_relu 无其他算子需求)
config都是只配置了一句‘config.type  = MNN_FORWARD_CPU’
BackendConfig backendConfig;没有更改

在linux系统服务器端编译方式与android arm64-v8a的编译皆完全按照官网步骤 [linux](https://www.yuque.com/mnn/cn/build_linux) [安卓](https://www.yuque.com/mnn/cn/build_android)

- 在安卓手机端运行两次精度会不一样，大约会有2%~3%的值精度有差......
- 转成.mnn之后分别在arm(小米6)与x86 (AMD Ryzen 7 3800X 8-Core)运行结果会不一样, 只有百分之十几的数能一摸一样
-  当然在arm/x86上的mnn，与 cpu的pb运行结果也不一样

# 结果对比
其中对应位置差别大致如下
```bash
In [34]: tensorflow_cpu[0]
Out[34]: -0.014639946

In [35]: linux_x86[0]
Out[35]: -0.014639949

In [36]: android[0]
Out[36]: -0.014639948
```
# 使用到的模型
[mnn model](https://drive.google.com/file/d/1U_-9lXCo8FsElXXrRfUnEb8FGA0S5Fdv/view?usp=sharing)
[input](https://drive.google.com/file/d/1KNjvDLqo4pPUp4Wx6CVXGLnk5rOpXHtZ/view?usp=sharing)
# 想要做的是...
请问大佬们
 因为我的模型需求是一定要保证每次计算一摸一样 可以实现跨平台， 想知道有没有能保证精度一模一样的实现方式啊，比如换成基于OPENCL/OPENGL/VULKAN有能保证一样的情况么？或者将来可以？或者怎么做...

**Comment by matfeb** [comment]
I had the same problem and it seems to be related on how the hardware architecture and/or software (compilers mostly) implement the floating point standard ([IEEE754](https://en.wikipedia.org/wiki/IEEE_754)) 
You will have the same problem if you infer on CPU vs OpenCL vs OpenGL vs Vulkan but with < 1% difference on accuracy.
