### ISSUE TITLE
build pymnn failed

### ISSUE THREAD

**Issue by jameshardennnnn** [alibaba/MNN#1061]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 16.04.5 LTS

# Github版本:
# Github Version:
commit a6836bb50a4ba615bfc8b6a367d282120a274097

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
building MNN with command ‘’cmake .. & make -j8"  succeed,
but building pymnn with command "python build_deps.py"  failed.

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
[100%] Linking CXX executable ../../MNNConvert
/usr/lib/gcc/x86_64-linux-gnu/5/libgomp.a(target.o): In function `gomp_target_init':
(.text+0xba): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
../../libMNN.a(BlstmComputer.cpp.o): In function `MNN::BlstmComputer::onExecute(MNN::Tensor*, std::vector<int, std::allocator<int> > const&, std::vector<std::shared_ptr<MNN::Tensor>, std::allocator<std::shared_ptr<MNN::Tensor> > > const&, std::vector<std::shared_ptr<MNN::Tensor>, std::allocator<std::shared_ptr<MNN::Tensor> > > const&) [clone ._omp_fn.1]':
BlstmComputer.cpp:(.text._ZN3MNN13BlstmComputer9onExecuteEPNS_6TensorERKSt6vectorIiSaIiEERKS3_ISt10shared_ptrIS1_ESaIS9_EESD_._omp_fn.1+0x501): undefined reference to `_ZGVbN4v___expf_finite'
../../libMNN.a(CPUBinary.cpp.o): In function `MNN::ErrorCode MNN::_binaryOp<float, float, MNN::BinaryPow<float, float, float> >(MNN::Tensor*, MNN::Tensor*, MNN::Tensor*)':
CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0x77f): undefined reference to `_ZGVbN2vv___pow_finite'
CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0x7a7): undefined reference to `_ZGVbN2vv___pow_finite'
CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0xa44): undefined reference to `_ZGVbN2vv___pow_finite'
CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0xa6b): undefined reference to `_ZGVbN2vv___pow_finite'
CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0xcf8): undefined reference to `_ZGVbN2vv___pow_finite'
../../libMNN.a(CPUBinary.cpp.o):CPUBinary.cpp:(.text._ZN3MNNL9_binaryOpIffNS_9BinaryPowIfffEEEENS_9ErrorCodeEPNS_6TensorES5_S5_+0xd1f): more undefined references to `_ZGVbN2vv___pow_finite' follow
../../libMNN.a(CPUDetectionOutput.cpp.o): In function `MNN::CPUDetectionOutput::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&)':
CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x4aa): undefined reference to `_ZGVbN2v___exp_finite'
CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x4c3): undefined reference to `_ZGVbN2v___exp_finite'
CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x4fd): undefined reference to `_ZGVbN2v___exp_finite'
CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x519): undefined reference to `_ZGVbN2v___exp_finite'
CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x14d3): undefined reference to `_ZGVbN2v___exp_finite'
../../libMNN.a(CPUDetectionOutput.cpp.o):CPUDetectionOutput.cpp:(.text._ZN3MNN18CPUDetectionOutput9onExecuteERKSt6vectorIPNS_6TensorESaIS3_EES7_+0x14f5): more undefined references to `_ZGVbN2v___exp_finite' follow
../../libMNN.a(CPURNNSequenceGRU.cpp.o): In function `MNN::runRNNStep(float const*, int, std::shared_ptr<MNN::Tensor>&, int, std::shared_ptr<MNN::Tensor>&, std::shared_ptr<MNN::Tensor>&, std::shared_ptr<MNN::Tensor>&, std::shared_ptr<MNN::Tensor>&, std::shared_ptr<MNN::Tensor>&, std::shared_ptr<MNN::Tensor>&) [clone .constprop.33]':
CPURNNSequenceGRU.cpp:(.text._ZN3MNNL10runRNNStepEPKfiRSt10shared_ptrINS_6TensorEEiS5_S5_S5_S5_S5_S5_.constprop.33+0x2a3): undefined reference to `_ZGVbN4v___expf_finite'
collect2: error: ld returned 1 exit status

**Comment by oppoozh555** [comment]
同样出现上述问题
