### ISSUE TITLE
The model don't have init dim

### ISSUE THREAD

**Issue by AIGirl10** [alibaba/MNN#1062]
I converted tensorflow segmentation model to MNN and when I tried to use it using segment.cpp file (available in MNN), it gave me this error,

```sh
The model don't have init dim
```
I am not able to understand the issue since model got converted successfully.

Can anyone please help ?

**Comment by jxt1234** [comment]
the tensorflow's model's input is set as non shape. And the model converted to mnn should be resized firstly before run session
