### ISSUE TITLE
tensorflow中depthwise_conv2d()的channel_multiplier参数转为mnn后未发生作用

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#1065]
# 平台
Ubuntu 16.04
tensorflow-gpu 1.14.0
python 2.7
mnn0.2.1.5 /mnn0.2.3.3

# 问题描述
tensorflow模型中有用到tf.nn.depthwise_con2d()函数，其中一个参数filter=[filter_height, filter_width, in_channels, channel_multiplier]
发现pb模型转为mnn之后，channel_multiplier(代码中设置为6)并未发生作用，导致mnn测试结果很差。
即输出depthwise_con2d()后的一个节点，输出pb模型和mnn模型的输出shape，
发现pb输出为（1，56，56，192），而mnn输出shape为（1，32，56，56），通道数并未x6.
请问目前是mnn不支持tf中的channel_multiplier（>1）时该参数的传递吗？

ps：channel_multiplier=6，模型转换过程中不会报错，但测试会有问题
channel_multiplier改为1，模型转换过程中不会报错，mnn测试结果正确。

**Comment by jxt1234** [comment]
原始模型方便发一下?

**Comment by Echosanmao** [comment]
您好，邮件已发送

**Comment by Echosanmao** [comment]
您好，请问该问题的原因方便告知吗？

> 原始模型方便发一下?

**Comment by jxt1234** [comment]
已经支持，参见 tools/converter/source/optimizer/tfextra/TFConvolutionMerge.cpp
