### ISSUE TITLE
Wrong result when inference with OPPENCL

### ISSUE THREAD

**Issue by sorchaxiaoyu** [alibaba/MNN#1066]
1、Android aarch64,when inference,I get the same result on CPU、GL、Vulkan and the result is right，but the result is wrong on OPENCL，and the result doesn't change as input change, the result is just like some random values,which is always:
file name = /data/local/tmp/face_8.jpg
l32CntTmp1 = 0 0 27 -95.000000 15 -101.000000 3 -101.000000
l32CntTmp1 = 0 1 32 -90.000000 20 -96.000000 8 -96.000000
l32CntTmp1 = 1 0 32 -90.000000 20 -96.000000 8 -96.000000
l32CntTmp1 = 1 1 37 -85.000000 25 -91.000000 14 -90.000000
out = 0.002968  0.003206 0.002115 0.453125 0.000571 0.538086
file name = /data/local/tmp/face_9.jpg
l32CntTmp1 = 0 0 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 0 1 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 1 0 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 1 1 246 124.000000 255 139.000000 254 150.000000
out = 0.002968  0.003206 0.002115 0.453125 0.000571 0.538086
while the right result is like:
file name = /data/local/tmp/face_8.jpg
l32CntTmp1 = 0 0 27 -95.000000 15 -101.000000 3 -101.000000
l32CntTmp1 = 0 1 32 -90.000000 20 -96.000000 8 -96.000000
l32CntTmp1 = 1 0 32 -90.000000 20 -96.000000 8 -96.000000
l32CntTmp1 = 1 1 37 -85.000000 25 -91.000000 14 -90.000000
out = 0.947266  0.000781 0.000107 0.000131 0.000289 0.051086
file name = /data/local/tmp/face_9.jpg
l32CntTmp1 = 0 0 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 0 1 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 1 0 246 124.000000 255 139.000000 254 150.000000
l32CntTmp1 = 1 1 246 124.000000 255 139.000000 254 150.000000
out = 0.950684  0.000196 0.000140 0.000105 0.000345 0.048462

Can anyone give me some suggestions,what can I do?

2、When I test the time on Huawei Honor 10 Lite，the time is as follows:

mnn（cpu） | Mnn(openCL) | Mnn(OpenGL)                                                   
123ms           | 6500ms           | 1200ms（gpu type:Mali-G51,gl version：OpenGL ES 3.2 v1.r18p0-01rel0.6572f917757ede51005f31b623e326ac）

The time with CL、GL optimization is higher than only-cpu，the numThread is 0；
It‘s amazing;While I think only-cpu is slower than  CL、GL optimization;Can anyone give me some suggestion,Why this happened?

**Comment by siweimaodou** [comment]
@sorchaxiaoyu 能帮忙看看1068的case吗？我直接没有跑通opencl的benchmark， 您这边是怎么跑通的啊？
