### ISSUE TITLE
benchmark采用opencl出现Error for 146以及segmentation fault

### ISSUE THREAD

**Issue by siweimaodou** [alibaba/MNN#1068]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu16.04 

# Github版本:
# Github Version:
最新版1.0.2,master分支

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_BENCHMARK=true -DMNN_OPENCL=true -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false
make -j8

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
# ./benchmarkExprModels.out MobileNetV1_100_1.0_224 10 3 4 
MNN Expr Models benchmark
Forward type: **OpenCL** thread=4
Error for 146
Segmentation fault

**Comment by siweimaodou** [comment]
在1.0.0版本上，出现的是Error for 133

**Comment by sorchaxiaoyu** [comment]
First,If use .so，please give the link_path of libMNN_CL.so,and link_lib is libMNN_CL.so,not libMNN.so;If use .a, the link_lib is libMNN.a;When uselibMNN.a, make sure you had set -Wl,-whole-archive MNN -Wl,-no-whole-archive
Second, I use thread=0, I didn't us thread=4,maybe you can try thread =0;

**Comment by siweimaodou** [comment]
@sorchaxiaoyu 我这个直接在build下运行的benchmark
./benchmarkExprModels.out ResNet_100_18 10 3 4
这个还需要指定libMNN_CL.so吗？

**Comment by siweimaodou** [comment]
我发现是opencl版本的问题；换一台机器跑通了
