### ISSUE TITLE
arm82使用不加速

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [alibaba/MNN#1069]
在小米9上(高通骁龙855)想用arm82加速发现 并没有速度改变
编译方式与官网完全一致。 然后编译的时候logcat开了，但是却没有打印MNNinfo [set armv82 backend]..
安卓端运行的时候 config也设置了
 backendConfig.memory = MNN::BackendConfig::MemoryMode::Memory_Low;
 config.backendConfig = &backendConfig;
也System.loadLibrary("MNN_Arm82");
为什么还是不对捏。

**Comment by jxt1234** [comment]
backendConfig.memory = MNN::BackendConfig::MemoryMode::Memory_Low;
改成 
backendConfig.precision = MNN::BackendConfig::MemoryMode::Precision_Low;
