### ISSUE TITLE
/MNN-master/demo/exec   ERROR

### ISSUE THREAD

**Issue by mathpopo** [alibaba/MNN#107]
1. Download [pose model](https://github.com/czy2014hust/posenet-python/raw/master/models/model-mobilenet_v1_075.pb)
2. [Convert](../../tools/converter/README.md) tensorflow model to MNN model
3. run multipose like this:
```bash
./multiPose.out model.mnn input.jpg pose.jpg
```

The MobilenetV1/Conv2D's input is not ready
Resize error for MobilenetV1/Conv2D, code=3
main, 369, cost time: 482.019012 ms
main, 392, cost time: 0.631000 ms

ErrorCode Pipeline::Unit::prepare(Backend* bn, Backend* cpuBn) {
    for (auto t : mInputs) {
        bool valid = true;
        for (int i = 0; i < t->dimensions(); ++i) {
            if (t->length(i) <= 0) {
                valid = false;
                break;
            }
        }
        if (!valid) {
            MNN_ERROR("The %s's input is not ready\n", mContent->name.c_str());
            return COMPUTE_SIZE_ERROR;
        }
    }

**Comment by czy2014hust** [comment]
This is not ERROR! Because there is no input dimensions in model file, it will appear "resize error" firstly.

**Comment by mathpopo** [comment]
no input dimensions in model file-->it mean "pose model" issue?

**Comment by mathpopo** [comment]
> This is not ERROR! Because there is no input dimensions in model file, it will appear "resize error" firstly.
no input dimensions in model file-->it mean "pose model" issue?

**Comment by mathpopo** [comment]
The MobilenetV1/Conv2D's input is not ready
Resize error for MobilenetV1/Conv2D, code=3
