### ISSUE TITLE
rk3399板子 RAMv8架构上ncnn推理时间比mnn快

### ISSUE THREAD

**Issue by blueskywwc** [alibaba/MNN#1073]
mnn模型在x86平台推理时间9ms左右，在rk3399 armv8架构上耗时68ms左右，
另外，ncnn模型在x86平台推理时间13ms左右，在rk3399 armv8架构上耗时58ms左右
在x86上mnn比ncnn快，但在板子上ncnn比mnn快，这是什么情况，谢谢

**Comment by jxt1234** [comment]
模型结构，mnn 版本号是?

**Comment by blueskywwc** [comment]
是mobilenetv2模型，1.0.1版本。
找到问题了，config.numThread = 1时26ms左右；config.numThread = 4时58ms左右；
为什么线程数越多，时间反而越长

**Comment by jxt1234** [comment]
rk3399 两大核 4 小核，一般 2线程是最大值

**Comment by blueskywwc** [comment]
在rk3399上我测试了1,2,3,4线程数，时间依次增加，线程1耗时最短
