### ISSUE TITLE
tflite量化模型在PC与在ARM上推理结果不同

### ISSUE THREAD

**Issue by whuwiqian** [alibaba/MNN#1075]
问题描述：
tflite量化模型转MNN，用MNN做前向推理，模型在X86上的与在ARM上结果不相同，MNN库前向推理X86上的结果与tensorflow python原始测试结果一致。误差还是比较大的。
[Model.zip](https://github.com/alibaba/MNN/files/5106415/Model.zip)

模型输入: 112x112x3
模型输出: 1x136
图片初始化: 量化模型图片不需要进行初始化，直接输入0-255范围原始图片
测试图片: test.bmp

tensorflow python原始结果:
90, 71, 87, 85, 80, 105, 87, 118, 88, 136, 98, 148, 110, 159, 124, 165, 141, 168, 154, 162, 160, 152, 165, 139, 169, 128, 173, 119, 178, 111, 181, 101, 182, 93, 135, 62, 142, 62, 151, 68, 157, 75, 161, 80, 183, 89, 186, 87, 189, 83, 192, 79, 197, 79, 174, 90, 175, 99, 175, 107, 176, 117, 158, 117, 162, 120, 168, 123, 174, 122, 176, 122, 136, 80, 145, 82, 150, 83, 156, 88, 148, 85, 144, 83, 184, 93, 188, 93, 192, 94, 196, 94, 193, 94, 189, 94, 144, 124, 153, 121, 163, 124, 165, 125, 164, 130, 170, 128, 167, 131, 165, 133, 161, 138, 155, 137, 149, 135, 145, 129, 146, 124, 158, 125, 162, 128, 167, 128, 167, 131, 162, 133, 157, 133, 149, 134

X86测试结果:
90, 71, 87, 85, 80, 105, 87, 118, 88, 136, 98, 148, 110, 159, 124, 165, 141, 168, 154, 162, 160, 152, 165, 139, 169, 128, 173, 119, 178, 111, 181, 101, 182, 93, 135, 62, 142, 62, 151, 68, 157, 75, 161, 80, 183, 89, 186, 87, 189, 83, 192, 79, 197, 79, 174, 90, 175, 99, 175, 107, 176, 117, 158, 117, 162, 120, 168, 123, 174, 122, 176, 122, 136, 80, 145, 82, 150, 83, 156, 88, 148, 85, 144, 83, 184, 93, 188, 93, 192, 94, 196, 94, 193, 94, 189, 94, 144, 124, 153, 121, 163, 124, 165, 125, 164, 130, 170, 128, 167, 131, 165, 133, 161, 138, 155, 137, 149, 135, 145, 129, 146, 124, 158, 125, 162, 128, 167, 128, 167, 131, 162, 133, 157, 133, 149, 134

Arm64测试结果:
91, 69, 87, 84, 81, 103, 86, 118, 89, 136, 99, 149, 110, 159, 125, 165, 141, 169, 153, 162, 160, 153, 165, 140, 170, 129, 174, 120, 178, 112, 180, 101, 225, 101, 135, 60, 142, 61, 151, 66, 157, 73, 162, 79, 182, 88, 185, 87, 189, 83, 193, 79, 196, 79, 173, 89, 173, 97, 174, 105, 175, 114, 157, 117, 162, 118, 171, 158, 172, 121, 176, 120, 137, 79, 145, 80, 151, 82, 155, 87, 149, 84, 143, 81, 183, 91, 187, 93, 191, 93, 196, 94, 192, 94, 187, 92, 144, 125, 152, 122, 163, 167, 164, 125, 164, 128, 170, 128, 167, 132, 165, 134, 161, 138, 156, 138, 150, 136, 145, 130, 147, 125, 157, 124, 162, 128, 167, 126, 166, 131, 162, 133, 157, 133, 152, 180

Arm32测试结果:
91, 69, 87, 84, 81, 103, 86, 118, 89, 136, 99, 149, 110, 159, 125, 165, 141, 169, 153, 162, 160, 153, 165, 140, 170, 129, 174, 120, 178, 112, 180, 101, 225, 101, 135, 60, 142, 61, 151, 66, 157, 73, 162, 79, 182, 88, 185, 87, 189, 83, 193, 79, 196, 79, 173, 89, 173, 97, 174, 105, 175, 114, 157, 117, 162, 118, 171, 158, 172, 121, 176, 120, 137, 79, 145, 80, 151, 82, 155, 87, 149, 84, 143, 81, 183, 91, 187, 93, 191, 93, 196, 94, 192, 94, 187, 92, 144, 125, 152, 122, 163, 167, 164, 125, 164, 128, 170, 128, 167, 132, 165, 134, 161, 138, 156, 138, 150, 136, 145, 130, 147, 125, 157, 124, 162, 128, 167, 126, 166, 131, 162, 133, 157, 133, 152, 180

测试模型和图片见附件

**Comment by strivehub** [comment]
这是什么原因，我用Python和安卓上，同一张图像，推理结果也不同。

**Comment by longlong007** [comment]
我也遇到同样的问题，有些操作在arm上用汇编和pc端的常规实现方式导致的差了1。

**Comment by wangzhaode** [comment]
不同的实现确实会有细微差异，对最终结果影响不大可以忽略
