### ISSUE TITLE
关于memory copy

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [alibaba/MNN#1076]
请问
![image](https://user-images.githubusercontent.com/40542615/90891630-99c88b80-e3ee-11ea-8882-fbb2c566dad1.png)
1.  上图， 如果tensor与source都是uint8的时候 到memorycopy时 还是uint8么？ 还是也是转成32bits进行copy
2. 如果1中是uint8 copy那怎么把输入的tensor改成uint8， 
std::shared_ptr<MNN::Tensor> tensor(MNN::Tensor::create<uint8_t>(std::vector<int>{1, 3, 360, 480}, mydata, Tensor::CAFFE));
input->copyFromHostTensor(tensor.get())
我怎么通过copyFromHostTensor 给inputtensor copy uint8的输入，我现在虽然TF pb固化的时候输入时uint8的，但是mnn中inputtensor还是32bits 如说用上述函数，会显示Error in CPUBackend::onCopyBuffer

3. 我固pb的时候，如果输出的类型是fp16， 转化成mnn的时候会显示不支持.但是我想输出是fp16，并以fp16的数据格式copyToHostTensor。
综上， 其实我是想减少memorycopy的时间，因为我的网络是不错resize的，原图尺寸巨大，copy耗时过于明显。。。请求解答。。。。

**Comment by jxt1234** [comment]
1、uint8 ，不会转到 float ，相应地 mean 和 normals 无效
2、不需要改，直接 convert 到 session 中取出的 tensor
3、建议先转到mnn ，加 --fp16 参数，由 mnn 转成 fp16 压缩模型，输出 tensor fp16 数据格式目前不支持
