### ISSUE TITLE
关于demo的几个问题

### ISSUE THREAD

**Issue by CheungBH** [alibaba/MNN#1080]
你好.我想问一下,有目标检测的C++源码嘛?
或者有没文档说明当想部署自己的转好的网络时,整个C++代码调用网络那里应该怎么写?(例如说我看别人那里有blob name什么的要根据自己的网络来写)

然后我跑了android的demo,编译了之后发现找不到动态库.

Build command failed.
Error while executing process /home/hkuit164/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/hkuit164/Documents/MNN/demo/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target mnncore}

ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it

想问问这是怎么回事呢?

谢谢~!

**Comment by dandingol03** [comment]
我也是同样问题

**Comment by xukun6868668** [comment]
我也是这问题，有没有大师回答下

**Comment by dandingol03** [comment]
额这个解决了，其实就是路径问题，自己在android studio对照下so的位置应该是放错了

**Comment by xukun6868668** [comment]
能具体说下么，我都没看到哪有so库

**Comment by Lennon-cheng** [comment]
根据报错提示，在app目录下新建libs/armeabi-v7a 文件夹，将Android 编译好的libMNN.so 复制过去

**Comment by wangzhaode** [comment]
DEMO已更新：https://github.com/alibaba/MNN/pull/2244
