### ISSUE TITLE
android实测的时间和timeProfile测出来的时间差距太大

### ISSUE THREAD

**Issue by StrugglingForBetter** [alibaba/MNN#1081]
在android上面用vulkan跑出来的时间大于用timeProfile测出来的时间，两者差距比较大，是什么原因？

**Comment by suruoxi** [comment]
我提供一个可能的原因。 

timeProfile里的Precision 设置是 low， 而默认是Normal。  这两者在速度和精度上，都有较大的差异。

**Comment by jxt1234** [comment]
可以观察下手机上 gpu 频率，这个一般是 app 使用时 gpu 频率没起来的问题
