### ISSUE TITLE
armv82开启之后模型精度损失较多问题

### ISSUE THREAD

**Issue by scott-mao** [alibaba/MNN#1084]
使用cpu跑的时候模型精度正常，精度和pc端原始模型相似度在99.5％以上，但是换成armv8.2加速后，模型精度损失很大

**Comment by scott-mao** [comment]
> 
![001](https://user-images.githubusercontent.com/70254175/91262651-b247f580-e7a2-11ea-9a00-eb1096bcb4bd.png)
![002](https://user-images.githubusercontent.com/70254175/91262906-c68bf280-e7a2-11ea-9b4b-982f558c1a02.png)
不开和开armv8.2加速的模型推理结果对比

**Comment by Riut521** [comment]
你在什么设备上做的Arm8.2

**Comment by jxt1234** [comment]
可以更新 mnn 试一下（1.1.5），不过看上去像是正常误差范围
