### ISSUE TITLE
开启armv8.2之后模型输出结果为nan问题

### ISSUE THREAD

**Issue by scott-mao** [alibaba/MNN#1085]
不开armv8.2加速模型输出结果正常，但是开启armv8.2加速之后模型输出结果为nan.
MNN推理端已经配置为precision:low，模型为f32模型．

**Comment by jxt1234** [comment]
建议更新 mnn 再试下

**Comment by shguo** [comment]
遇到了相同问题。

**Comment by jiuzhuanzhuan** [comment]
同样

> 建议更新 mnn 再试下

同样也是这个问题， 开启arm82 直接nan了， 用的就是最新版本的mnn

**Comment by VEDFU** [comment]
最新的2.7.1也有这个问题
