### ISSUE TITLE
Error while building engine for iOS

### ISSUE THREAD

**Issue by guopuu** [alibaba/MNN#1086]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
refer: https://www.yuque.com/mnn/cn/build_ios
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
error: unknown target CPU 'armv8.2-a+fp16'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake, cooperlake, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, znver2, x86-64
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')

####More message:

CompileC /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/Objects-normal/x86_64/MNNQuantizeFP16_UNIT4.o /Users/ritsukaginn/Documents/MNN/source/backend/arm82/asm/arm64/MNNQuantizeFP16_UNIT4.S normal x86_64 assembler-with-cpp com.apple.compilers.llvm.clang.1_0.compiler (in target 'MNN' from project 'MNN')
    cd /Users/ritsukaginn/Documents/MNN/project/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x assembler-with-cpp -target x86_64-apple-macos10.15 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fmodules -fmodules-cache-path=/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -fmodule-name=MNN -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -DMNN_CODEGEN_REGISTER=1 -DMNN_SUPPORT_TFLITE_QUAN=1 -DENABLE_ARMV82=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -fvisibility=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/MNN-generated-files.hmap -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/MNN-own-target-headers.hmap -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/MNN-all-non-framework-target-headers.hmap -ivfsoverlay /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/all-product-headers.yaml -iquote /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/MNN-project-headers.hmap -iquote /Users/ritsukaginn/Documents/MNN/schema/current -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Products/Release/include -I/Users/ritsukaginn/Documents/MNN/3rd_party/flatbuffers/include -I/Users/ritsukaginn/Documents/MNN/3rd_party/half -I/Users/ritsukaginn/Documents/MNN/include -I/Users/ritsukaginn/Documents/MNN/source -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/DerivedSources-normal/x86_64 -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/DerivedSources/x86_64 -I/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/DerivedSources -F/Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Products/Release -march=armv8.2-a+fp16 -MMD -MT dependencies -MF /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/Objects-normal/x86_64/MNNQuantizeFP16_UNIT4.d --serialize-diagnostics /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/Objects-normal/x86_64/MNNQuantizeFP16_UNIT4.dia -c /Users/ritsukaginn/Documents/MNN/source/backend/arm82/asm/arm64/MNNQuantizeFP16_UNIT4.S -o /Users/ritsukaginn/Library/Developer/Xcode/DerivedData/MNN-dirfvothtwjujidlbsznawkrbzeb/Build/Intermediates.noindex/MNN.build/Release/MNN.build/Objects-normal/x86_64/MNNQuantizeFP16_UNIT4.o

```
粘贴在这里
Paste log here or pastebin
```

**Comment by YunYang1994** [comment]
一样的错误，你解决了吗？

**Comment by CyCle1024** [comment]
@YunYang1994 @guopuu maybe you should check the active scheme first. I encountered the same error and fixed it by changing the active scheme from 'My Mac' into 'iPhone 8':
![fix_mnn1](https://user-images.githubusercontent.com/12063710/99625678-b5821300-2a6b-11eb-93a4-0301cabdc267.png)
![fix_mnn2](https://user-images.githubusercontent.com/12063710/99625685-b87d0380-2a6b-11eb-9e41-fa9b3ffa10a4.png)

**Comment by wangzhaode** [comment]
ARMv8.2 must specify the target to your iPhone.
