### ISSUE TITLE
The function createFromFile() returns NULL when running  .mnn model file that is transformed form keras .pb model file

### ISSUE THREAD

**Issue by Cranola** [alibaba/MNN#1088]
When trying to apply my MNN format model on Android device, the function createFromFile() returns NULL when creating the net instance. My model is converted from the Keras model (.pb).  The .pb model preforms normal in android project and the transformed MNN format model (.mnn) also performed good in Keras project using MNN package. 

Here is the screenshot of the code for creating net instance. 
![image](https://user-images.githubusercontent.com/41048013/91383113-ed5b2f00-e85d-11ea-9fce-42cc0c81efc6.png)
The parameter mNetInstance returns NULL.

To debug this function, I find the function nativeCreateNetFromFile() returns 0 as the following code shows.
![image](https://user-images.githubusercontent.com/41048013/91383344-7c684700-e85e-11ea-9cd3-63623bbf1a77.png)

Anyone knows how to fix this problem?

**Comment by ymmshi** [comment]
please provide the model .mnn file

**Comment by Cranola** [comment]
@ymmshi Here is my model file.
[yolov3.mnn.zip](https://github.com/alibaba/MNN/files/5134585/yolov3.mnn.zip)

**Comment by Cranola** [comment]
update: 
I change to convert my original .h5 model file (Keras Yolov3 Project) to .tflite file instead of .pb file and then convert the .tflite file to .mnn model file using "./MNNConvert -f TFLITE --modelFile XXX.tflite --MNNModel XXX.mnn --bizCode biz", it works.

But I still don't know why the .mnn model file converted from .pb file doesn't work properly.

**Comment by ymmshi** [comment]
It runs well with my codes. You should check your model path first, I think.

**Comment by Cranola** [comment]
> It runs well with my codes. You should check your model path first, I think.

Thanks for your help. But since the .mnn model converted from .tflite works normally as I mentioned above, maybe there are some other mistakes.
