### ISSUE TITLE
运行lstm的结果不对

### ISSUE THREAD

**Issue by tang576225574** [alibaba/MNN#1089]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  windows,linux

我运行了最简单的lstm模型，但是结果都对不上，为什么？看了好久
这是我随便搭的模型：
class lstm_test_singledir(nn.Module):
    def __init__(self, input_size=24):
        super(lstm_test_singledir, self).__init__()
        self.input_size = input_size
        self.lstm_ = nn.LSTM(self.input_size, 12, 1)
    def forward(self, x):
        y = torch.relu(x)
        return self.lstm_(y)
输入尺寸是(1,1,24)
先转为onnx，onnx的结果没有任何问题，但是mnn的结果就对不上了

**Comment by 123liluky** [comment]
你是多输入吗？

**Comment by tang576225574** [comment]
> 你是多输入吗？

您好，麻烦您了，我已经解决了这个问题了哈，要设置batch_first=true，才能正常运行，另外pytorch转onnx后再转mnn的过程lstm是有问题的，因为输入维度的含义不一样，统一了就可以了

**Comment by tang576225574** [comment]
您好，麻烦您了，我已经解决了这个问题了哈，要设置batch_first=true，才能正常运行，另外pytorch转onnx后再转mnn的过程lstm是有问题的，因为输入维度的含义不一样，统一了就可以了



---原始邮件---
发件人: "123liluky"<notifications@github.com&gt;
发送时间: 2020年9月2日(周三) 下午3:07
收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tang576225574"<576225574@qq.com&gt;;
主题: Re: [alibaba/MNN] 运行lstm的结果不对 (#1089)




 
你是多输入吗？

**Comment by tang576225574** [comment]
> 你是多输入吗？

另外，lstm虽然解决了，但是还有另外一个问题：3d卷积结果不对；最简单的3d卷积也是结果对不上的，能看看是什么原因吗

**Comment by 123liluky** [comment]
@tang576225574  方便分享一下，lstm onnx转mnn过程中，维度怎么统一吗？ 我现在onnx里输出是(1，time_steps，hidden_size)，mnn里输出却是(1，1，hidden_size)

**Comment by ruanmk** [comment]
> > 你是多输入吗？
> 
> 另外，lstm虽然解决了，但是还有另外一个问题：3d卷积结果不对；最简单的3d卷积也是结果对不上的，能看看是什么原因吗

请问需要怎样统一呢，遇到了一样的问题

**Comment by jxt1234** [comment]
已经修正

**Comment by xiao-keeplearning** [comment]
没看懂，维度怎么统一呀
