### ISSUE TITLE
模型输入要求是NC4HW4,  RuntimeError: data size does not match each other

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1090]
我pytorch -> onnx -> MNN后MNN的模型要求输入是NC4HW4，
在运行python API的时候输入默认转为NCHW而不是NC4HW4，导致size不匹配

RuntimeError: data size does not match each other。

请问这个该怎么解决？怎么吧input_tensor转为NC4HW4

谢谢

**Comment by AloneGu** [comment]
if (nn_input.data_format == F.NC4HW4):
        nn_input.reorder(F.NCHW)
