### ISSUE TITLE
tag 1.0.2 版本 编译加上openmp时，模型推理会crash

### ISSUE THREAD

**Issue by conansherry** [alibaba/MNN#1091]
![image](https://user-images.githubusercontent.com/2148224/91551241-6f318200-e95c-11ea-868f-beb601f6dad3.png)

去掉openmp编译，正常。

**Comment by jxt1234** [comment]
这个是 openmp 自身的 bug ，需要换一个 openmp 版本。正是因为如此 mnn 提供了 threadpool 的方式
