### ISSUE TITLE
使用MNN的推理结果和Pytorch的推理结果完全不一样

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1094]
如题，Pytoch -》Onnx -》MNN
使用pytorch的推理结果和MNN的推理结果完全不同，差异极大大，请问可能是什么原因？

**Comment by scutzhe** [comment]
我也遇到这样的问题,最后为了进度,不得不选择tensorflow->tflite直接转换
请问你现在解决了吗?

**Comment by scutzhe** [comment]
> 我也遇到这样的问题,最后为了进度,不得不选择tensorflow->tflite直接转换
> 请问你现在解决了吗?

我解决了,目前解决的办法是MNN的版本问题,MNNConvert版本由0.2.1.5->0.2.1.8即成功
并且MNN转换不支持Normal操作

**Comment by jxt1234** [comment]
更新下版本试试，如果还不行发下模型

**Comment by zhuoran-guo** [comment]
请问如何更新版本
