### ISSUE TITLE
请问为什么对Pytorch的转换必须通过ONNX，不考虑直接转换pytorch模型呢，似乎推断框架在这一块都很默契地选择了onnx

### ISSUE THREAD

**Issue by GDP666** [alibaba/MNN#1095]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by TianzhongSong** [comment]
pytorch的.pth只保存了权重信息，并没有保存计算图，所以只有一个.pth是没法做inference的。而onnx是有完整的计算图的，你可以用[netron](https://lutzroeder.github.io/netron/)可视化.pth 或.onnx， .pth只有一些权重在里面

**Comment by GDP666** [comment]
> pytorch的.pth只保存了权重信息，并没有保存计算图，所以只有一个.pth是没法做inference的。而onnx是有完整的计算图的，你可以用[netron](https://lutzroeder.github.io/netron/)可视化.pth 或.onnx， .pth只有一些权重在里面

python训练出的.pth文件通过torch.jit.trace这个模块的转换后，netron是可以可视化网络结构的，只不过netron解析这个pth的过程比较复杂，没有解析ONNX的过程直观

**Comment by TianzhongSong** [comment]
感觉torch.jit.trace转出来的模型解析起来会很麻烦。而onnx作为一种格式，别的框架也能转onnx，那对于推理框架只需要专注onnx模型的转换，这样开发量是不是可以少一些，个人认为哈

**Comment by jxt1234** [comment]
感谢各位帮忙解答~~~
