### ISSUE TITLE
Quantize model whose input is not an image

### ISSUE THREAD

**Issue by marcinkeviciusp** [alibaba/MNN#1098]
Hi,

As seen [here](https://www.yuque.com/mnn/en/tool_quantize#Jvt3C), the quantizer seems to require the model to use images as inputs. Is it possible to quantize a model that takes, for example, an 128 long vector of float32 values?

If I already had the means and the normals for each layer, perhaps there would be a way to quantize the model without requiring the image inputs?

Thanks,
Povilas

**Comment by jxt1234** [comment]
Please see https://www.yuque.com/mnn/cn/vg3to5#umBOX
