### ISSUE TITLE
rk3399 linux系统编译mnn opengl 报错

### ISSUE THREAD

**Issue by perfyperfect** [alibaba/MNN#1099]
Rk3399 linux系统

github下载日期2020.9.1；

>>>>>>>>>>>>>
MNN BUILD INFO:
	System: Linux
	Processor: aarch64
	Metal: OFF
	OpenCL: OFF
	OpenGL: ON
	Vulkan: OFF
	ARM82: OFF
	OpenMP: OFF
	Hidden: TRUE
	Build Path: /home/firefly/lpf/mnn/MNN-master
Enabling AArch64 Assemblies
Configuring done
# 编译日志:

Traceback (most recent call last):
  File "/home/firefly/lpf/mnn/MNN-master/source/backend/opengl/makeshader.py", line 44, in <module>
    generateFile(gOutputHeadFile, gOutputSourceFile, shaders);
  File "/home/firefly/lpf/mnn/MNN-master/source/backend/opengl/makeshader.py", line 37, in generateFile
    with open(headfile, "w") as f:
IOError: [Errno 2] No such file or directory: '/home/firefly/lpf/mnn/MNN-master/include/MNN/backend/opengl/AllShader.h'
source/backend/opengl/CMakeFiles/MNN_GLCodeGen.dir/build.make:60: recipe for target 'source/backend/opengl/AllShader.cpp' failed
make[2]: *** [source/backend/opengl/AllShader.cpp] Error 1
CMakeFiles/Makefile2:771: recipe for target 'source/backend/opengl/CMakeFiles/MNN_GLCodeGen.dir/all' failed
make[1]: *** [source/backend/opengl/CMakeFiles/MNN_GLCodeGen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by jxt1234** [comment]
mnn - opengl 不支持 linux 编译，建议用 opencl / vulkan / cuda
