### ISSUE TITLE
Can I use it on the windows platform, such as windows 10？

### ISSUE THREAD

**Issue by 791136190** [alibaba/MNN#11]
Can I use it on the windows platform, such as windows 10？

**Comment by li-qing** [comment]
haven't compiled it on windows yet. is there any problem?

**Comment by 791136190** [comment]
#define MNN_PUBLIC __attribute__((visibility("default"))) in windows maybe not the correct way to write like this.And can't get MNN_generated.h.And autotime.cpp get many linux key words....

**Comment by anlongstory** [comment]
@li-qing   请问一下，已经在 Ubuntu 16.04 上编译成功了，已经完成模型转化成 .mnn 文件了，请问是不是可以直接使用一些官方接口或者有没有相关例程可以直接在 ubuntu 下直接调用 .mnn 的模型来测试转化后的模型，实现在 CPU/GPU 上的加速?

**Comment by li-qing** [comment]
> @li-qing 请问一下，已经在 Ubuntu 16.04 上编译成功了，已经完成模型转化成 .mnn 文件了，请问是不是可以直接使用一些官方接口或者有没有相关例程可以直接在 ubuntu 下直接调用 .mnn 的模型来测试转化后的模型，实现在 CPU/GPU 上的加速?

可以参考demo/exec目录下的示例。

**Comment by li-qing** [comment]
> #define MNN_PUBLIC **attribute**((visibility("default"))) in windows maybe not the correct way to write like this.And can't get MNN_generated.h.And autotime.cpp get many linux key words....

have you tried https://github.com/microsoft/Terminal with Linux subsystem including ?

**Comment by 791136190** [comment]
> have you tried https://github.com/microsoft/Terminal with Linux subsystem including ?

not yet,i will try it maybe.thank you.

**Comment by li-qing** [comment]
windows is now supported. check doc/install.md.

**Comment by aa12356jm** [comment]
安装官方文档使用cmake编译时，出现错误：
CMake Error at CMakeLists.txt:270 (install):
  install Library TARGETS given no DESTINATION!

**Comment by aa12356jm** [comment]
在win10下面使用cmake编译时，在CMakeLists.txt的270行应该修改install(TARGETS MNN LIBRARY DESTINATION lib)为install(TARGETS MNN RUNTIME DESTINATION lib)

**Comment by yutianhang** [comment]
> #define MNN_PUBLIC **attribute**((visibility("default"))) in windows maybe not the correct way to write like this.And can't get MNN_generated.h.And autotime.cpp get many linux key words....

1、参考MNNDefine.h，当使用MSVC编译器编译的时候，如果指定BUILDING_DLL宏则MNN_PUBLIC为__declspec(dllexport)，否则为__declspec(dllimport)。__attribute__((visibility("default"))为GCC扩展，在这里不会生效。
2、windows 10 安装流程已验证，请参考doc/install_CN.md安装。

**Comment by yutianhang** [comment]
> 按照官方文档使用cmake编译时，出现错误：
> CMake Error at CMakeLists.txt:270 (install):
> install Library TARGETS given no DESTINATION!

我这边在windows 10 下使用cmake 3.14.5 （maintained and supported by Kitware）未能复现，请提供你的cmake版本。（cmake --version）

**Comment by aa12356jm** [comment]
> > 按照官方文档使用cmake编译时，出现错误：
> > CMake Error at CMakeLists.txt:270 (install):
> > install Library TARGETS given no DESTINATION!
> 
> 我这边在windows 10 下使用cmake 3.14.5 （maintained and supported by Kitware）未能复现，请提供你的cmake版本。（cmake --version）

win10     cmake 版本  3.10.0.rc5

**Comment by yutianhang** [comment]
fixed, update to latest MNN please

**Comment by 17759205390** [comment]
> @li-qing 请问一下，已经在 Ubuntu 16.04 上编译成功了，已经完成模型转化成 .mnn 文件了，请问是不是可以直接使用一些官方接口或者有没有相关例程可以直接在 ubuntu 下直接调用 .mnn 的模型来测试转化后的模型，实现在 CPU/GPU 上的加速?

@li-qing 你成功了吗？我也在弄这
