### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by blueskywwc** [alibaba/MNN#1100]
代码不报错，但MNN推理结果错误，最后一行显示:Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
这是什么问题，怎么解决，谢谢!

**Comment by Heath-zyl** [comment]
同问

**Comment by wangzhaode** [comment]
你的代码应该有错误，导致SIGSEGV
