### ISSUE TITLE
createSession时，调整不同的struct BackendConfig配置，实测推理的CPU和内存占用未见明显变化。

### ISSUE THREAD

**Issue by jiyinghui39** [alibaba/MNN#1102]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
4核Arm A35
# Platform(Include target platform as well if cross-compiling):  
Android 8.1

# Github版本:
# Github Version:
1.0.2
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-18  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
```
问题描述：
我们的项目对CPU和内存占用均比较敏感，正常尝试将模型迁移到mnn。目前测试发现，在A35、单核上，通过调整MemoryMode， PowerMode， PrecisionMode这三个参数。测试出来的CPU资源占用和内存资源占用几乎没有区别。这是为什么呢。
补充说明，我们的模型主要有SSD，SSR和mobilenet_v1。

**Comment by jxt1234** [comment]
Mobilenet 不涉及 winograd 算法（ memory = low 时关闭），A35 不支持 fp16 计算（precision = low），单核则与 power 无关。因此不变化是正常的。减少内存可以在 createSession 完成之后调 releaseModel

**Comment by jiyinghui39** [comment]
懂了。感谢解答。

**Comment by yangy996** [comment]
> Mobilenet 不涉及 winograd 算法（ memory = low 时关闭），A35 不支持 fp16 计算（precision = low），单核则与 power 无关。因此不变化是正常的。减少内存可以在 createSession 完成之后调 releaseModel
 createSession 完成之后调 releaseModel, 这就不能预测了呀，还有别的方式减少内存吗？模型初始化后，内存占用太大
