### ISSUE TITLE
模型转换ONNX到MNN，段错误

### ISSUE THREAD

**Issue by herbiezhao** [alibaba/MNN#1104]
![x2paddle_model](https://user-images.githubusercontent.com/20237776/91836734-c9dd1d80-ec7d-11ea-9087-0c7015c15c7e.png)

ONNX模型是从paddlepaddle转换而来，在ubuntu 1804下面进行的编译和转换，例子tf模型可以成功转换
执行指令：
./MNNConvert -f ONNX --modelFile x2paddle_model.onnx --MNNModel x2paddle_model.mnn --bizCode biz
log：
MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 7
Start to Optimize the MNN Net...
段错误 (核心已转储)

问题：是否是模型本身的问题？

**Comment by cendelian** [comment]
请问你解决了吗

**Comment by herbiezhao** [comment]
没有，没人理我




| |
zhao
邮箱：herbiezhao@163.com
|

Signature is customized by Netease Mail Master

在2020年09月12日 17:41，cendelian 写道：

请问你解决了吗

**Comment by ml-inory** [comment]
兄弟，看你的模型输入好像多了个Constant的算子，还有输入的尺寸是-1开头的，不知道会不会有问题

**Comment by herbiezhao** [comment]
> 兄弟，看你的模型输入好像多了个Constant的算子，还有输入的尺寸是-1开头的，不知道会不会有问题

要么是转换脚本的问题，暂时解决不了。主要是出错给的信息太少，不清楚哪导致的问题，本来想提交个模型让直接分析看下哪出的问题。

**Comment by ml-inory** [comment]
> > 兄弟，看你的模型输入好像多了个Constant的算子，还有输入的尺寸是-1开头的，不知道会不会有问题
> 
> 要么是转换脚本的问题，暂时解决不了。主要是出错给的信息太少，不清楚哪导致的问题，本来想提交个模型让直接分析看下哪出的问题。

我建议你用大老师的工具简化一下onnx模型再试试， 这个：https://github.com/daquexian/onnx-simplifier.git

或者直接这样：
```
pip install onnx-simplifier
python -m onnxsim input.onnx output.onnx
```

**Comment by herbiezhao** [comment]
> > > 兄弟，看你的模型输入好像多了个Constant的算子，还有输入的尺寸是-1开头的，不知道会不会有问题
> > 
> > 
> > 要么是转换脚本的问题，暂时解决不了。主要是出错给的信息太少，不清楚哪导致的问题，本来想提交个模型让直接分析看下哪出的问题。
> 
> 我建议你用大老师的工具简化一下onnx模型再试试， 这个：https://github.com/daquexian/onnx-simplifier.git
> 
> 或者直接这样：
> 
> ```
> pip install onnx-simplifier
> python -m onnxsim input.onnx output.onnx
> ```

好的，多谢，有空我试下

**Comment by jxt1234** [comment]
有相应 onnx 模型么?

**Comment by zhouyongxyz** [comment]
尝试用 python3 -m MNN.tools.mnnconvert 这个python 版本的命令去转换试试，onnx == 1.7.0 亲测有效。
