### ISSUE TITLE
Create MNN::Interpreter from MNN::NetT

### ISSUE THREAD

**Issue by JustasZJ** [alibaba/MNN#1106]
Hello,

I am trying to find the fastest way to load `MNN::Interpreter` from `std::unique_ptr<MNN::NetT> netT`, which I have constructed manually. The current fastest working way, which I have found, is:

```
flatbuffers::FlatBufferBuilder builderOutput(1024);
builderOutput.ForceDefaults(true);

auto len = MNN::Net::Pack(builderOutput, netT.get());
builderOutput.Finish(len);
int bufferSize = builderOutput.GetSize();
auto buffer = builderOutput.GetBufferPointer();

net = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromBuffer(buffer, bufferSize)); 
```

Is there any way to do this faster? Ideally, I would like to get rid of the create buffer part.

**Comment by wangzhaode** [comment]
this is the MNN's default method.
