### ISSUE TITLE
ONNX转MNN报错

### ISSUE THREAD

**Issue by blueskywwc** [alibaba/MNN#1107]
./MNNConvert -f ONNX --modelFile lin.onnx --MNNModel lin.mnn --bizCode biz

MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[18:00:17] /home/wangwc/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
段错误 (核心已转储)

这是模型本身的问题还是MNN出现异常，怎么处理，谢谢!

**Comment by cendelian** [comment]
请问你解决了吗

**Comment by blueskywwc** [comment]
是我模型本身的问题，里面一些算子可能不支持，修改后可以完成模型转换

**Comment by slz929** [comment]
最好升级mnn到最新，bugfix和算子问题
