### ISSUE TITLE
请问mnn提取节点输出的方式只有两种方式getSessionOutput和getSessionOutputAll吗？能不能像ncnn那样提取中间节点的输出？

### ISSUE THREAD

**Issue by 2017ZYS** [alibaba/MNN#1108]
请问mnn提取节点输出的方式只有两种方式getSessionOutput和getSessionOutputAll吗？能不能像ncnn那样提取中间节点的输出？
因为是这样的，我目前转化的一个onnx模型节点输出有4个，其中一个是hp另一个是hp的maxpooling的结果称为hp_maxpool，我在使用onnx2mnn转换工具后发现mnn模型结果变成只有三个了，hp节点变成了中间节点，采用getSessionOutput和getSessionOutputAll都取不出来，比较尴尬影响后处理

**Comment by jxt1234** [comment]
方案一（推荐）：在 createSession 时把中间节点加入 saveTensors
方案二：用回调，参考 tools/cpp/MNNV2Basic.cpp
