### ISSUE TITLE
onComputeSize  error while createsession//Caffe input layer transform

### ISSUE THREAD

**Issue by huwenfeng** [alibaba/MNN#111]
after createmodel from file, createsession error(release version MNN-0.1.1.5), the source model is caffe:

error:
```
MNN-0.1.1.5/source/shape/ShapeInterp.cpp:20: virtual bool MNN::InterpComputer::onComputeSize(const MNN::Op *, const std::vector<Tensor *> &, const std::vector<Tensor *> &) const: assertion "res" failed
```

onComputeSize:
```
   virtual bool onComputeSize(const MNN::Op* op, const std::vector<Tensor*>& inputs,
                               const std::vector<Tensor*>& outputs) const override {
        MNN_ASSERT(1 == inputs.size() || 2 == inputs.size());
```
while exception occur, the  op->name()->str() is data_norm, it's input layer's name; but the op->type() is MNN::OpType_Interp??? 

is it an issue? or any transform for caffe input layer?

**Comment by huwenfeng** [comment]
and the real inputs.size() is 0.

**Comment by huwenfeng** [comment]
while i change the caffe model's input layer to 
```
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 288 dim: 288 } }
}
```
but the convert mnn model main_type is still Interp???
```
{ main_type: Interp, main:
{ widthScale: 0.0, outputWidth: 31675616, resizeType: 31675616 }
, name: "data", outputIndexes:
[ 0 ]
, type: Interp }
```

**Comment by huwenfeng** [comment]
I use new version to convert model, input layer is ok. the session can completed.

but the BatchNorm layer is convert to Scale type, is it right?
{ inputIndexes: 
[ 0 ]
, main_type: Scale, main: 
{ channels: 3, scaleData: ....
 }
, name: "BatchNormBackward1_bn", outputIndexes: 
[ 1 ]
, type: Scale }

**Comment by huwenfeng** [comment]
and I have another caffe model, after converted to MNN model, the BatchNorm layer is stolen， is it merged with previous layer or next layer?

**Comment by jxt1234** [comment]
> I use new version to convert model, input layer is ok. the session can completed.
> 
> but the BatchNorm layer is convert to Scale type, is it right?
> { inputIndexes:
> [ 0 ]
> , main_type: Scale, main:
> { channels: 3, scaleData: ....
> }
> , name: "BatchNormBackward1_bn", outputIndexes:
> [ 1 ]
> , **type: Scale** }

The BatchNormal will firstly be merge info convolution if possible.
Otherwise it will be changed as scale op.

**Comment by huwenfeng** [comment]
ok,
thanks @jxt1234
