### ISSUE TITLE
3D卷积运行结果不对

### ISSUE THREAD

**Issue by tang576225574** [alibaba/MNN#1112]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):   linux, windows

我是通过最简单的方式测试了3D卷积的结果，走的流程是pytorch->onnx->mnn，发现仍然对不上；
输入的维度shape是(batch, channels, depth, height, width)
打开网络结构看，发现是3D卷积前缺少了"ConvertTensor"的层，并最终引起了普通2D卷积计算的维度不对应；
在源码CPUConvolution3D.cpp第251行出错：
    mSubExecution[d]->onExecute({mSubInputTensors[d].get()}, {mSubOutputTensor.get()});

如果再往前回溯，我认为就是mSubInputTensors[d] 的输入没有进行MNNUnpackC4之类的变换导致的。
尝试了修复没成功，想问如何解决？下个版本能修复这个问题吗？

**Comment by zlszhonglongshen** [comment]
也遇到了同样的问题，期待解决~~

**Comment by jxt1234** [comment]
应该修复了，不过目前 3D 卷积实现的性能不是很高。
