### ISSUE TITLE
编译报错： fatal error: google/protobuf/port_def.inc: No such file or directory

### ISSUE THREAD

**Issue by ZiQiangXie** [alibaba/MNN#1113]
# 平台(如果交叉编译请再附上交叉编译目标平台):  ubuntu16.04
# Github版本: 20200906下载
# 编译方式: 
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

# 编译日志:
[ 12%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/StrassenMatmulComputor.cpp.o
[ 13%] Built target MNNCore
[ 13%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUConvolution3D.cpp.o
[ 13%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeCosineSimilarity.cpp.o
[ 14%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeCrop.cpp.o
[ 15%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUConvolutionDepthwise.cpp.o
[ 15%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeCropAndResize.cpp.o
[ 15%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUCosineSimilarity.cpp.o
[ 16%] Built target MNNCompute
Scanning dependencies of target MNNConverterONNX
[ 16%] Building CXX object tools/converter/CMakeFiles/MNNConverterONNX.dir/source/onnx/ArgMaxOnnx.cpp.o
In file included from /home/xieziqiang/projects/MNN/tools/converter/source/onnx/onnxOpConverter.hpp:17:0,
                 from /home/xieziqiang/projects/MNN/tools/converter/source/onnx/ArgMaxOnnx.cpp:9:
/home/xieziqiang/projects/MNN/build/tools/converter/onnx.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
compilation terminated.
tools/converter/CMakeFiles/MNNConverterONNX.dir/build.make:97: recipe for target 'tools/converter/CMakeFiles/MNNConverterONNX.dir/source/onnx/ArgMaxOnnx.cpp.o' failed
make[2]: *** [tools/converter/CMakeFiles/MNNConverterONNX.dir/source/onnx/ArgMaxOnnx.cpp.o] Error 1
CMakeFiles/Makefile2:995: recipe for target 'tools/converter/CMakeFiles/MNNConverterONNX.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/MNNConverterONNX.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by TUT-jiayou** [comment]
@ZiQiangXie 你这个问题解决了么?

**Comment by TUT-jiayou** [comment]
我使用了源码编译proto-3.15 , 然后将include 文件夹下面的问题件, copy到了/usr/include 解决了
 x86-64
ubuntu 16.04
我源码编译参考的这个帖子
https://blog.csdn.net/u014454538/article/details/89005934

**Comment by ZiQiangXie** [comment]
@TUT-jiayou 感谢回复。我当时没有解决，后来换了方法就没再用这个。后续有机会的话再试试这个方法，感谢！

**Comment by wangzhaode** [comment]
现在已经在源码中提供了protobuf，不会再出现该问题
