### ISSUE TITLE
tflite量化模型转换失败 NOT_SUPPORTED_OP: [ DEQUANTIZE ]

### ISSUE THREAD

**Issue by ZhuLingfeng1993** [alibaba/MNN#1114]
我使用的是http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz模型，转换时报错
MNN/tools/converter/source/tflite/liteConverter.cpp:234: Check failed: creator ==> NOT_SUPPORTED_OP: [ DEQUANTIZE ]
请问有解决的办法吗

**Comment by hjchen2** [comment]
目前不支持tflite量化模型的转换
