### ISSUE TITLE
TF MobileNetV2-SSD量化模型转换成MNN的问题

### ISSUE THREAD

**Issue by ZhuLingfeng1993** [alibaba/MNN#1117]
主要目的是想用tf做MobileNetV2-SSD量化训练，然后转换成MNN模型，我做了一些尝试都不行

尝试了tf2的量化训练，使用[官网教程的MINIST分类模型](https://tensorflow.google.cn/model_optimization/guide/quantization/training_example)，运行成功，但量化后的tflite模型转换成MNN模型时报错：Check failed: creator ==> NOT_SUPPORTED_OP: [ QUANTIZE ]， 量化前的浮点tflite模型转换时报core dump，是不是不支持tf2的量化模型？

使用TF OD API 1.x 的model zoo 中的[ssd_mobilenet_v2_quantized_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz)中的pb模型，转换为MNN是报错Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::Conv2D | Tensorflow::DepthwiseConv2dNative | Tensorflow::FakeQuantWithMinMaxVars |,这个模型应该是量化训练模型，不能直接转换，官方没有提供量化后的tflite模型；使用[ssd_mobilenet_v3_small_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz)中的tflite模型报错Check failed: creator ==> NOT_SUPPORTED_OP: [ DEQUANTIZE ]，forzen.pb模型转换MNN成功，后者应该为浮点训练模型，前者应该为训练后量化模型

tf1.15环境下用TF OD API训练mobilenetv2-ssd训练不起来（使用已经训练好的浮点模型做预训练模型），报错NaN loss during training，不知道大家有没有遇到这个问题，或者有没有什么解决办法

尝试下载tf-slim官方的mobilenet-v3分类int8模型，发现转换成MNN成功

MNN版本：0df31a8

**Comment by strivehub** [comment]
我也遇到了这个问题，用object_detectionAPI量化训练的mobilenet-ssd，用.pb模型转.mnn时报错typt = Conv2D,failed.may be some node is not const;用.tflite模型在转.mnn模型的时候报错Check failed: creator ==> NOT_SUPPORTED_OP: [ DEQUANTIZE ]，请问目前解决了吗？解决了麻烦请教一下，谢谢了！！

**Comment by Bluewind001** [comment]
是不是编译MNN的时候没有开启：MNN_SUPPORT_TFLITE_QUAN 这个。可以试一下

**Comment by strivehub** [comment]
这个编译的时候默认就是开启的

**Comment by Bluewind001** [comment]
@strivehub   mnn转化好像不支持tflite的量化模型。  #1114
