### ISSUE TITLE
Android OpenCL incorrect result with Const node

### ISSUE THREAD

**Issue by ml-inory** [alibaba/MNN#1119]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android (API level 21)

# Github版本:
# Github Version:
547a284baafa9443c6d2615980eabec3200e10b5

# 编译方式:
# Compiling Method
在demo/exec中增加了RetinaNet的cpp，加入了后处理和画图的功能，通过adb push到手机上运行并把结果图片pull回来。

cmake ../../ \
	  -DCMAKE_SYSTEM_NAME="Android" \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DANDROID_ABI="${ABI}" \
          -DANDROID_STL=c++_static \
          -DCMAKE_BUILD_TYPE=Release \
          -DANDROID_NATIVE_API_LEVEL=android-21  \
          -DANDROID_TOOLCHAIN=clang \
          -DMNN_VULKAN:BOOL=ON  \
          -DMNN_OPENCL:BOOL=ON  \
          -DMNN_OPENMP:BOOL=ON \
          -DMNN_OPENGL:BOOL=ON \
          -DMNN_DEBUG:BOOL=OFF \
          -DMNN_BUILD_BENCHMARK:BOOL=OFF \
          -DMNN_BUILD_FOR_ANDROID_COMMAND=true \
          -DMNN_BUILD_DEMO:BOOL=ON \
          -DOpenCV_DIR=/home/rzyang/opencv/android_build \
          -DNATIVE_LIBRARY_OUTPUT=.

# 编译日志:
# Build Log:

rzyang@ubuntu:~/MNN/android_build$ ./bench_android.sh -64
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: ON
-- 	Vulkan: ON
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/rzyang/MNN/android_build/build
-- Enabling AArch64 Assemblies
-- Android
-- MNN Depends:MNNMNN_VulkanMNN_CLMNN_GLMNN_Express
-- Configuring don

现象如下：
我有一个RetinaNet的模型，是通过mmdetection转到ONNX再转MNN的，这个模型的head部分是共享权重的，如下图：

ONNX结构：
![image](https://user-images.githubusercontent.com/8433542/92549027-fa7b1380-f28a-11ea-928a-115bff7301e2.png)

417和423上面的Conv层拥有同样的Weight和Bias，同理418和424也是，分别用于预测物体的类别和位置输出。

转换成MNN以后：
![image](https://user-images.githubusercontent.com/8433542/92549243-6493b880-f28b-11ea-9a3b-ccbacca1d1da.png)
图中显示的是417上面的Conv的属性，可以看到weight变成了empty，bias也是，取而代之input多了两个Const的算子，其中的值确实为对应的权值：
![image](https://user-images.githubusercontent.com/8433542/92549374-a7ee2700-f28b-11ea-831f-18883c4a9b6b.png)

逐步定位到问题出在sour e/backend/opencl/execution/MultiInputConvExecution.cpp这里。
在OpenCL的Conv算子中，有这样的执行路径，上述的这种将权重作为输入的卷积算子称为MultiInputConv。

![image](https://user-images.githubusercontent.com/8433542/92549533-0ca98180-f28c-11ea-9edf-db1550b7360b.png)

通过将ConvExecution.cpp的注册算子部分OpenCLCreatorRegister<ConvolutionCreator> __conv_op(OpType_Convolution);
注释掉以后，模型的输出正确。

==============================================================================
目前我的解决方法是在ONNX中修改共享权值的名称并把权值拷贝进去，这样转换后的MNN模型就没有了Const算子，具体代码如下：
def rename_share_weights(onnx_file):
    model = onnx.load(onnx_file)
    
    tensor_to_del = []
    for t in model.graph.initializer:
        share = 0
        target = []
        for j, node in enumerate(model.graph.node):
            input_names = node.input
            for k, name in enumerate(input_names):
                if t.name == name:
                    share += 1
                    target.append((j, k))
        if share > 1:
            print('share %s %d times' % (t.name, share))
            for i in range(share):
                j, k = target[i]
                
                new_tensor = copy.deepcopy(t)
                new_name = t.name + f'_{i}'
                new_tensor.name = new_name

                model.graph.node[j].input[k] = new_name
                model.graph.initializer.append(new_tensor)
            tensor_to_del.append(t.name)
    # remove tensor
    print('remove tensor ', tensor_to_del)
    for name in tensor_to_del:
        for i, t in enumerate(model.graph.initializer):
            if t.name == name:
                print('remove initializer', model.graph.initializer[i].name)
                del model.graph.initializer[i]
        for i, t in enumerate(model.graph.node):
            if t.name == name:
                print('remove node', model.graph.node[i].name)
                del model.graph.node[i]
        for i, t in enumerate(model.graph.output):
            if t.name == name:
                print('remove output', model.graph.output[i].name)
                del model.graph.output[i]
        for i, t in enumerate(model.graph.input):
            if t.name == name:
                print('remove input', model.graph.input[i].name)
                del model.graph.input[i]

    onnx.save(model, onnx_file)

**Comment by jxt1234** [comment]
应该已经 fix 了, 更新到 1.1.0
