### ISSUE TITLE
MAC上：pip install MNN命令行输入mnn报错

### ISSUE THREAD

**Issue by strivehub** [alibaba/MNN#1120]
# 平台(mac python3.5):  

Traceback (most recent call last):
  File "/Anaconda3-4.0.0/anaconda/bin/mnn", line 5, in <module>
    from MNN.tools.mnn import main
  File "/Anaconda3-4.0.0/anaconda/lib/python3.5/site-packages/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
ImportError: dlopen(/Anaconda3-4.0.0/anaconda/lib/python3.5/site-packages/_mnncengine.cpython-35m-darwin.so, 2): Symbol not found: __PyThreadState_UncheckedGet
  Referenced from: /Anaconda3-4.0.0/anaconda/lib/python3.5/site-packages/_mnncengine.cpython-35m-darwin.so
  Expected in: flat namespace
 in /Anaconda3-4.0.0/anaconda/lib/python3.5/site-packages/_mnncengine.cpython-35m-darwin.so

**Comment by SatanWoo** [comment]
What's your OS version of Mac ? 10.13 or 10.14 or 10.15?

**Comment by wangzhaode** [comment]
请尝试安装最新版本
