### ISSUE TITLE
在跑mobilenet-ssd时候，出错

### ISSUE THREAD

**Issue by strivehub** [alibaba/MNN#1122]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Mac
# Platform(Include target platform as well if cross-compiling):  使用的是Python API 3.6

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

报错内容：
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: numpy type does not match
Abort trap: 6

**Comment by cians** [comment]
我也可以复现：
MNN版本：MNN-1.0.3-cp37-cp37m-macosx_10_13_x86_64.whl
部分代码：
```
    imgfile = 'res/0000001.jpg'
    image = cv2.imread(imgfile)
    #cv2 read as bgr format
    image = image[..., ::-1]
    #change to rgb format
    image = cv2.resize(image, (width, height))
    #resize to mobile_net tensor size
    image = image.astype(float)
    # image = image - (103.94, 116.78, 123.68)
    # image = image * (0.017, 0.017, 0.017)
    #preprocess it
    image = image.transpose((2, 0, 1))
    #cv2 read shape is NHWC, Tensor's need is NCHW,transpose it
    tmp_input = MNN.Tensor((1, 3, height, width), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe)
    #construct tensor from np.ndarray
    input_tensor.copyFrom(tmp_input)
    # input_tensor2.copyFrom(tmp_input2)
    interpreter.runSession(session)
```
