### ISSUE TITLE
pytorch导出的onnx转mnn，cpu模式运行结果正确，opencl运行结果错误？

### ISSUE THREAD

**Issue by mlinxiang** [alibaba/MNN#1123]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android

# Github版本:
# Github Version:
master

# 编译方式:
# Compiling Method
static library

基于mobilenetv2 backbone的centernet结构，pytorch训练导出为onnx后转mnn模型，通过编译static library集成到Android工程中，cpu模式能正常得到结果(和直接在pc上用python调用模型得到结果一致)，但是所有代码一致只修改type为opencl时结果错误，求教如何解决？

**Comment by zhra46** [comment]
我也遇到类似的情况 区别是 vulkan 和 opengl运行结果错误，cpu运行结果正确，请问如何解决？

**Comment by mlinxiang** [comment]
模型文件链接 链接: https://pan.baidu.com/s/1CjR_cHJAoW0fgMMCB6q3OA  密码: 5srb

**Comment by hjchen2** [comment]
#1125 请等待更新，谢谢～

**Comment by hjchen2** [comment]
#1125 请等待更新～

**Comment by bitxsw93** [comment]
> 模型文件链接 链接: https://pan.baidu.com/s/1CjR_cHJAoW0fgMMCB6q3OA 密码: 5srb

方便提供下原始onnx模型，复现问题吗

**Comment by mlinxiang** [comment]
> > 模型文件链接 链接: https://pan.baidu.com/s/1CjR_cHJAoW0fgMMCB6q3OA 密码: 5srb
> 
> 方便提供下原始onnx模型，复现问题吗
链接: https://pan.baidu.com/s/1LjK6jNYGBwShc4GKgsI6NA  密码: aq5b

**Comment by mlinxiang** [comment]
@bitxsw93 有啥进展么，有么有预期啥时候可以解决？

**Comment by mlinxiang** [comment]
另外会有奇怪的现象是 cpu的速度接近opencl的速度，vulkun速度慢很多
链接: https://pan.baidu.com/s/11prb3WiBMy03t6mcQwPTFg  密码: ps55

**Comment by bitxsw93** [comment]
我这边用opencl跑了你的模型，效果正确的。
./backendTest.out ~/Downloads/model_320_320.mnn 3 0.05 1
你可以用backendTest.out测试下看看，另外记得拉最新代码。

**Comment by bitxsw93** [comment]
@mlinxiang vulkan慢于CPU/opencl的情况，和具体硬件，你的模型里面的算子vulkan优化程度等都会相关。想用GPU推理，又不会优化vulkan并且opencl快的话，建议用opencl来做GPU推理

**Comment by mlinxiang** [comment]
> 我这边用opencl跑了你的模型，效果正确的。
> ./backendTest.out ~/Downloads/model_320_320.mnn 3 0.05 1
> 你可以用backendTest.out测试下看看，另外记得拉最新代码。

![image](https://user-images.githubusercontent.com/6283983/94097056-410a6980-fe58-11ea-82af-59e831593334.png)
最新的代码opencl运行依然错误，cpu正常。你这个效果正确是如何评估的，对比cpu和opencl跑的模型输出吗？

**Comment by mlinxiang** [comment]
@bitxsw93 这个问题有任何进展吗，之前在钉钉群里说已经定位到问题，内部使用版本已解决，啥时候能同步到github上勒？

**Comment by jxt1234** [comment]
Fixed
