### ISSUE TITLE
离线MNN模型(float32)转为8bit模型会有报错

### ISSUE THREAD

**Issue by huahuahuo** [alibaba/MNN#1129]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android-ndk-r20

# Github版本:
# Github Version:
master

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
 cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="arm64-v8a" -DANDROID_STL=c++_static -DANDROID_NATIVE_API_LEVEL=android-24 -DNATIVE_LIBRARY_OUTPUT=.;make
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
./quantized.out   raw_float.mnn 8bit.mnn preprocessConfig.json

```
粘贴在这里
Paste log here or pastebin
```
![image](https://user-images.githubusercontent.com/66724181/93157491-e9278080-f73c-11ea-9639-0aa5bebeaf0a.png)

具体代码

[test.zip](https://github.com/alibaba/MNN/files/5222110/test.zip)

**Comment by hjchen2** [comment]
修改preprocessConfig.json文件中的format、mean和normal。你这个输入要求是灰度图，所以format修改为GRAY，mean和normal相应的修改成灰度图的均值和方差。

**Comment by huahuahuo** [comment]
我的参数是灰度图，参数设置如下
{
    "format":"GRAY",
    "mean":[
        0
    ],
    "normal":[
        1
    ],
    "width":320,
    "height":32,
    "path":"./picture",
    "used_image_num":500,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS"
}

**Comment by hjchen2** [comment]
@huahuahuo 这个参数也报错了么

**Comment by huahuahuo** [comment]
设置成GRAY之后，报错如下：
![image](https://user-images.githubusercontent.com/66724181/93185648-412baa80-f770-11ea-8c88-0b738c698eeb.png)

**Comment by hjchen2** [comment]
@yyfcc17 帮忙看一下～

**Comment by hjchen2** [comment]
@huahuahuo 我这边debug看起来是LSTM recurrent gate的权重size有问题，hidden_size是1024，recurrent gate的权重大小应该是[4*1024, 1024]，但我这边看这个size是[4*1024, 512]？

如果方便的话，把原始的模型也发一下吧，我看看是否是模型转换的问题。

**Comment by hjchen2** [comment]
#1130

**Comment by huahuahuo** [comment]
我用公开模型测试下，看看是模型问题还是转换问题
