### ISSUE TITLE
beforeGemm == NULL

### ISSUE THREAD

**Issue by peyer** [alibaba/MNN#113]
I used MNNConvert for converting a caffemodel to mnn format. However, it crashed and I found that parameter of beforeGemm in  PostTreatUtils.cpp just return NULL, what's possible mistake for this?

**Comment by czy2014hust** [comment]
fixed, thx!

**Comment by peyer** [comment]
@czy2014hust I tried again, but beforeGemm still return NULL, then crashed. How to solve thr problem ?

**Comment by czy2014hust** [comment]
> @czy2014hust I tried again, but beforeGemm still return NULL, then crashed. How to solve thr problem ?

update MNN code

**Comment by peyer** [comment]
@czy2014hust I have solved the problem, thanks!
