### ISSUE TITLE
使用离线MNN 8bit模型会有代码段问题

### ISSUE THREAD

**Issue by huahuahuo** [alibaba/MNN#1130]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android-ndk-r20

# Github版本:
# Github Version:
master
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI="arm64-v8a" -DANDROID_STL=c++_static -DANDROID_NATIVE_API_LEVEL=android-24 -DNATIVE_LIBRARY_OUTPUT=.;make
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
[test_quantize.zip](https://github.com/alibaba/MNN/files/5222880/test_quantize.zip)

![image](https://user-images.githubusercontent.com/66724181/93172840-3405c000-f75e-11ea-937b-6b712178108c.png)

```
粘贴在这里
Paste log here or pastebin

**Comment by hjchen2** [comment]
可以编译一个Debug版本，编译命令：
```shell
cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI="arm64-v8a" -DANDROID_STL=c++_static -DANDROID_NATIVE_API_LEVEL=android-24 -DNATIVE_LIBRARY_OUTPUT=.; make
```
看一下具体在哪个文件的172行报错了。

方便的话提供一个可复现的模型。

**Comment by huahuahuo** [comment]
感觉这个错误是和1129连在一起的，是不是需要先把1129的模型转化正确了，再看这个问题
