### ISSUE TITLE
编译armv8 代码，会提示找不到vmaxq_f16 指令集

### ISSUE THREAD

**Issue by chenjiaoAngel** [alibaba/MNN#1131]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
use of undeclared identifier 'vmaxq_f16'

**Comment by hjchen2** [comment]
请问编译时是开启了ARMV82选项吗? 对应的ndk版本是多少呢？

请补充～

**Comment by chenjiaoAngel** [comment]
开启了，r17c

**Comment by hjchen2** [comment]
> 开启了，r17c

请用r21再试一下

**Comment by chenjiaoAngel** [comment]
好，这个是只有r21 才支持吗？r21 以下的r20 r19 都跑不了是吗

**Comment by hjchen2** [comment]
@chenjiaoAngel 我试过r16b、r17c都不行，r20和r19都么有试过，你要是试过了请把结果告诉我，谢谢

**Comment by chenjiaoAngel** [comment]
CXX_FLAGS: android-ndk-r21b/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -fno-rtti -fno-exceptions -march=armv8.2-a+fp16 -fopenmp=libomp -fPIE   -Ofast -ffast-math -Os -DNDEBUG -std=c++11 -fPIC -ldl -pie -lc -W -Wall -Wno-unused-variable -Wformat -Wmissing-declarations -Winit-self -Wpointer-arith -Wno-shadow -fpermissive -Wsign-promo -fdiagnostics-show-option -Wno-undef -Wno-narrowing -Wno-unknown-pragmas -Wno-delete-non-virtual-dtor -Wno-comment -Wno-sign-compare -Wno-ignored-qualifiers -Wno-enum-compare -Wno-unused-parameter -Wno-unused-function -fexceptions
编译还是不对，报undefined vma xq_f16

**Comment by chenjiaoAngel** [comment]
r20 r21 都可以的

**Comment by chenjiaoAngel** [comment]
我看benchmark有FP16 性能，你们应该知道支持arm FP16的NDK版本吧

**Comment by yisongsong** [comment]
r18b 及以上才支持 armv82 特性
