### ISSUE TITLE
mnn.metallib not found for iOS

### ISSUE THREAD

**Issue by charleybian** [alibaba/MNN#1132]
# Platform(Include target platform as well if cross-compiling):  iOS

# Github Version: 1.0.2

# Compiling Method: XCode, following https://www.yuque.com/mnn/cn/build_ios

-----

# Usage problem:
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_NSBundle", referenced from:
      objc-class-ref in MNN(MNNMetalContext.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hjchen2** [comment]
用demo 下面那个可以编出来，project/ios 下面那个有个脚本把 mnn.metallib 删了，需要自己改一下 (provide by 霞影)
