### ISSUE TITLE
ONNX Resize算子转换出错

### ISSUE THREAD

**Issue by ml-inory** [alibaba/MNN#1133]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux

# Github版本:
# Github Version:
547a284baafa9443c6d2615980eabec3200e10b

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DMNN_BUILD_CONVERTER=ON ..

# 现象
转换模型时报了Check failed: (inputs.size() == 4) || (inputs.size() == 2) ==> "Onnx Resize should have 4 or 2 inputs!"

其中Resize算子的输入是这样的：

![image](https://user-images.githubusercontent.com/8433542/93195124-72f63e80-f77b-11ea-904d-16922b0aebfb.png)

可以看到有3个input， 但是转换工具规定输入只能有2个或4个。

# Fix方法
目前通过修改toos/converter/source/optimizer/onnxextra/OnnxUpsample.cpp的代码fix了，由于input[1]（roi输入）的数据是空的，可以简单的fix。

将107行修改为 
```
MNN_CHECK((inputs.size() == 4) || (inputs.size() == 3) || (inputs.size() == 2), "Onnx Resize should have 4 or 3 or 2 inputs!");
```

在152行加入以下代码：
```
else if (inputs.size() == 3) {  
            auto ptr = inputs[2]->readMap<float>();  
            MNN_ASSERT((ptr[0] == 1) && (ptr[1] == 1));  
            resizeParam->heightScale = ptr[2];  
            resizeParam->widthScale = ptr[3];  
            mergeredResize->main.value = resizeParam.release();  
            auto resizeExpr = Expr::create(mergeredResize.get(), {_Convert(inputs[0], NC4HW4)});  
            resizeExpr->setName(expr->name());  
            output = _Convert(Variable::create(resizeExpr), NCHW);  
            return output->expr().first;  
 }
```

最后可以转换成功。

**Comment by gofugoo** [comment]
大神，我按照你的修改，但是还有有问题，能不能帮忙看看。
onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
Don't support type [BatchNorm], 222
Don't support type [BatchNorm], 222
Check failed: shape->dimensions() == 1 ==> "shape rank should be one"
Check failed: indices->length(indicesDimension - 1) == 1 ==> "indices.shape[-1] = shape.rank"
Check failed: updates->dimensions() == dimension ==> "updates dimension should be equal to given shape"
Don't support type [BatchNorm], 222
Don't support type [BatchNorm], 222
Check failed: shape->dimensions() == 1 ==> "shape rank should be one"
Check failed: indices->length(indicesDimension - 1) == 1 ==> "indices.shape[-1] = shape.rank"
Check failed: updates->dimensions() == dimension ==> "updates dimension should be equal to given shape"
Don't support type [BatchNorm], 222
Don't support type [BatchNorm], 222
Check failed: shape->dimensions() == 1 ==> "shape rank should be one"
Check failed: indices->length(indicesDimension - 1) == 1 ==> "indices.shape[-1] = shape.rank"
Check failed: updates->dimensions() == dimension ==> "updates dimension should be equal to given shape"
libMNN_Express.dylib was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by ml-inory** [comment]
@gofugoo 朋友，你的模型我可以转出来，但是报错跟你一样，你再转一次看看，最后应该报了Convert done!的，只是这个模型的输出对不对就很难说了，看它的报错跟我这里的修改没有关系，是别的问题。

转换过程是这样的， 先用大老师的onnx-simplifier简化onnx模型，再用mnn的工具转。

这样子：
```
pip install onnx-simplifier
python -m onnxsim input.onnx output.onnx
```
然后转mnn，我把简化后的onnx和转出来的mnn发你看看：
链接：https://pan.baidu.com/s/1xxM_WFVR10jIjGmKNmq0nA 
提取码：4qzg

**Comment by gofugoo** [comment]
> @gofugoo 朋友，你的模型我可以转出来，但是报错跟你一样，你再转一次看看，最后应该报了Convert done!的，只是这个模型的输出对不对就很难说了，看它的报错跟我这里的修改没有关系，是别的问题。
> 
> 转换过程是这样的， 先用大老师的onnx-simplifier简化onnx模型，再用mnn的工具转。
> 
> 这样子：
> 
> ```
> pip install onnx-simplifier
> python -m onnxsim input.onnx output.onnx
> ```
> 
> 然后转mnn，我把简化后的onnx和转出来的mnn发你看看：
> 链接：https://pan.baidu.com/s/1xxM_WFVR10jIjGmKNmq0nA
> 提取码：4qzg

你用MNN是那个版本？

**Comment by ml-inory** [comment]
@gofugoo https://github.com/alibaba/MNN/commit/547a284baafa9443c6d2615980eabec3200e10b5 这个

**Comment by gofugoo** [comment]
> @gofugoo [547a284](https://github.com/alibaba/MNN/commit/547a284baafa9443c6d2615980eabec3200e10b5) 这个

是别的问题，有没有时间帮助看看这个其它的问题?

**Comment by ml-inory** [comment]
@gofugoo 你提个issue吧，这样别人也能看到
