### ISSUE TITLE
MNN resize结果有问题

### ISSUE THREAD

**Issue by GUN-xing** [alibaba/MNN#1135]
编译的tag1.0.2

目标检测模型，模型的输入是160 120。
移植到MNN之后，
如果输入图片为160 120（不经过MNN的resize），其预测结果和Python模型的结果基本能够对齐。
如果输入图片为640 480（经过MNN的resize，resize到160 120），其预测结果和Python结果相差很多。
如果使用opencv resize好之后，直接转tensor，其预测结果和Python模型的结果基本能够对齐。
具体数值如下
![image](https://user-images.githubusercontent.com/34390030/93345842-e1afc680-f865-11ea-897d-7bd46c5760da.png)

MNN的部署代码如下
       
         input_tensor = objdet_interpreter->getSessionInput(objdet_session, nullptr);
        objdet_interpreter->resizeTensor(input_tensor, {1, 3, in_h, in_w});
        objdet_interpreter->resizeSession(objdet_session);

        config.sourceFormat = MNN::CV::RGB;
        config.destFormat = MNN::CV::RGB;
        config.filterType = MNN::CV::BILINEAR;
        std::memcpy(config.mean, mean_vals, 3 * sizeof(float));
        std::memcpy(config.normal, norm_vals, 3 * sizeof(float));

       // get input tensor
        MNN::CV::Matrix transform;
        transform.setScale((float)(image_w-1)/(in_w-1), (float)(image_h-1)/(in_h-1));
        // in_h in_w是模型输入的高宽，image_h image_w是原图的高宽

        std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(config));
        pretreat->setMatrix(transform);
        pretreat->convert((uint8_t*)rgbDataUsed, image_w, image_h, 0, input_tensor);

        // run network
        objdet_interpreter->runSession(objdet_session);

        // get output data
        std::string scores = "scores";
        std::string boxes = "boxes";
        MNN::Tensor *tensor_scores = objdet_interpreter->getSessionOutput(objdet_session, scores.c_str());
        MNN::Tensor *tensor_boxes = objdet_interpreter->getSessionOutput(objdet_session, boxes.c_str());

**Comment by hjchen2** [comment]
把 transform.setScale((float)(image_w-1)/(in_w-1), (float)(image_h-1)/(in_h-1)) 改成 transform.setScale((float)(image_w)/in_w, (float)(image_h)/in_h) 试试

**Comment by GUN-xing** [comment]
> 把 transform.setScale((float)(image_w-1)/(in_w-1), (float)(image_h-1)/(in_h-1)) 改成 transform.setScale((float)(image_w)/in_w, (float)(image_h)/in_h) 试试

这个修改之后，box像素的差距减小了，但是score的差距更大了。并且我看给的示例用的是我之前的那种写法
![image](https://user-images.githubusercontent.com/34390030/93429437-bd9ac680-f8f3-11ea-8a88-cbf68e5ec578.png)

**Comment by jxt1234** [comment]
MNN 的 resize 和 opencv 的算法不一样，属于正常范围误差
