### ISSUE TITLE
Don't support type [BatchNorm] onnx转化MNN失败

### ISSUE THREAD

**Issue by gofugoo** [alibaba/MNN#1136]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

MAC 上

# Github版本:
# Github Version:
https://github.com/alibaba/MNN/commit/3ea9dd1866e1c502f3632e1564b2fbc546559863

# 编译方式:
# Compiling Method
cmake -GXcode -DMNN_BUILD_CONVERTER=ON  ..

按照这个修复resize算子，还有如下下面错误。
https://github.com/alibaba/MNN/issues/1133

转化失败日志：
onnxConverter.cpp:29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
Don't support type [BatchNorm], 222
Don't support type [BatchNorm], 222
Check failed: shape->dimensions() == 1 ==> "shape rank should be one"
Check failed: indices->length(indicesDimension - 1) == 1 ==> "indices.shape[-1] = shape.rank"
Check failed: updates->dimensions() == dimension ==> "updates dimension should be equal to given shape"
Don't support type [BatchNorm], 222
Don't support type [BatchNorm], 222
Check failed: shape->dimensions() == 1 ==> "shape rank should be one"
Check failed: indices->length(indicesDimension - 1) == 1 ==> "indices.shape[-1] = shape.rank"
Check failed: updates->dimensions() == dimension ==> "updates dimension should be equal to given shape"

模型
[yolov_simp.onnx.zip](https://github.com/alibaba/MNN/files/5232115/yolov_simp.onnx.zip)

**Comment by hjchen2** [comment]
@gofugoo 看你的模型中存在多个convolution输出concat之后计算BatchNorm的结构，这种网络结构在现在的MNN中不支持。由于MNN本身不支持BatchNorm算子，因此BatchNorm都需要fuse到前一个convolution中，但由于中间存在concat的情况，BatchNorm无法被fuse，转换就会失败。解决方法：
1、修改模型结构，在concat之前做batchnorm
2、修改MNN的转换工具，把BatchNorm转换成scale + bias_add，（必要时需要修改一下convolution的fuse逻辑）
3、等MNN更新，时间可能会比较长～

**Comment by gofugoo** [comment]
@hjchen2 
谢谢回复，修改这个类把OnnxBatchNormTransform默认的转换修改成scale + bias_add ?

**Comment by hjchen2** [comment]
> OnnxBatchNormTransform

是的

**Comment by gofugoo** [comment]
> > OnnxBatchNormTransform
> 
> 是的

 大神能不能简单写一点代码粘贴上来，我对项目不是很熟？

**Comment by jxt1234** [comment]
Fixed
