### ISSUE TITLE
开启armv82，基于aarch64-linux下直接编译报错，不开启则OK

### ISSUE THREAD

**Issue by RookieJie** [alibaba/MNN#1137]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
**RK3399 pro
aarch64-linux下直接编译，cmake版本：3.13.4，make版本：GNU Make 4.2.1，GCC版本：Debian 8.3.0-6**

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

**3ea9dd1**

# 编译方式:
# Compiling Method

**aarch64-linux下直接编译，cmake版本：3.13.4，make版本：GNU Make 4.2.1，GCC版本：Debian 8.3.0-6**
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
-- >>>>>>>>>>>>>
-- SNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/toybrick/Desktop/SNN_Release/build
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- Onnx: /home/toybrick/Desktop/SNN_Release/build/tools/converter/onnx.pb.h;/home/toybrick/Desktop/SNN_Release/build/tools/converter/onnx-operators.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/toybrick/Desktop/SNN_Release/build

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp: In function 'void SNN::_SNNArm82ReluWithChannel(FLOAT16*, const FLOAT16*, const FLOAT16*, size_t)':
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:33:60: error: cannot convert 'uint16x8_t' {aka '__vector(8) short unsigned int'} to 'float16x8_t' {aka '__vector(8) __fp16'} in initialization
         float16x8_t lessThanZero = vcleq_f16(value, value_0);
                                                            ^
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:35:60: error: cannot convert 'float16x8_t' {aka '__vector(8) __fp16'} to 'uint16x8_t' {aka '__vector(8) short unsigned int'}
         vst1q_f16(dst + i * ARMV82_CHANNEL_UNIT, vbslq_f16(lessThanZero, mulSlope, value));
                                                            ^~~~~~~~~~~~
In file included from /home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:18:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:12067:23: note:   initializing argument 1 of 'float16x8_t vbslq_f16(uint16x8_t, float16x8_t, float16x8_t)'
 vbslq_f16 (uint16x8_t __a, float16x8_t __b, float16x8_t __c)
            ~~~~~~~~~~~^~~
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp: In function 'void SNN::_SNNArm82LeakyReluWithChannel(FLOAT16*, const FLOAT16*, FLOAT16, size_t)':
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:60:60: error: cannot convert 'uint16x8_t' {aka '__vector(8) short unsigned int'} to 'float16x8_t' {aka '__vector(8) __fp16'} in initialization
         float16x8_t lessThanZero = vcleq_f16(value, value_0);
                                                            ^
/home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:62:60: error: cannot convert 'float16x8_t' {aka '__vector(8) __fp16'} to 'uint16x8_t' {aka '__vector(8) short unsigned int'}
         vst1q_f16(dst + i * ARMV82_CHANNEL_UNIT, vbslq_f16(lessThanZero, mulSlope, value));
                                                            ^~~~~~~~~~~~
In file included from /home/toybrick/Desktop/SNN_Release/source/backend/arm82/Arm82Relu.cpp:18:
/usr/lib/gcc/aarch64-linux-gnu/8/include/arm_neon.h:12067:23: note:   initializing argument 1 of 'float16x8_t vbslq_f16(uint16x8_t, float16x8_t, float16x8_t)'
 vbslq_f16 (uint16x8_t __a, float16x8_t __b, float16x8_t __c)
            ~~~~~~~~~~~^~~
make[2]: *** [source/backend/arm82/CMakeFiles/SNN_Arm82.dir/build.make:206: source/backend/arm82/CMakeFiles/SNN_Arm82.dir/Arm82Relu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:426: source/backend/arm82/CMakeFiles/SNN_Arm82.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by hjchen2** [comment]
请问你使用的是gcc编译器吗，能否改用clang编译器再试试？

**Comment by chienkan** [comment]
https://www.rock-chips.com/a/cn/product/RK33xilie/2018/0130/873.html
https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores

**Comment by TUT-jiayou** [comment]
@hjchen2  我想确认一下, 意思是即使开启 ARM82 编译出来这个MNN, 在CPU上面也不会出现额外的加速么(比不开启
ARM82 编译选项)?
