### ISSUE TITLE
libMNN.a has a size of 126M by default on iOS.

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#114]
The libMNN.so is 1.6M on android. Why the size is so large on iOS?

**Comment by jxt1234** [comment]
The .a compiled from Xcode contain debug symbols. You can change the setting of xcode.

**Comment by GaussRieman** [comment]
Thanks for your reply.
strip linked product   "no" -> "yes"
Generate Debug Symbols  "yes" -> "no"
 
Through these changes in settings, I get a new libMNN.a of 8.5M in size.
Is there anything more I can do to reduce the size of the lib?

**Comment by li-qing** [comment]
I built one in Release mode just now, and it's 6.1MB with a metallib inside the framework.

Is there any other detail environmental info that you could provide?

**Comment by ChisenZhang** [comment]
> Thanks for your reply.
> strip linked product "no" -> "yes"
> Generate Debug Symbols "yes" -> "no"
> 
> Through these changes in settings, I get a new libMNN.a of 8.5M in size.
> Is there anything more I can do to reduce the size of the lib?



> Thanks for your reply.
> strip linked product "no" -> "yes"
> Generate Debug Symbols "yes" -> "no"
> 
> Through these changes in settings, I get a new libMNN.a of 8.5M in size.
> Is there anything more I can do to reduce the size of the lib?

how to generate the .a lib?  I just generated a .framework lib by the default project of project/ios
