### ISSUE TITLE
mnn为啥做那么多封装，为啥不像ncnn一样简洁呢？

### ISSUE THREAD

**Issue by chenjun2hao** [alibaba/MNN#1145]
如题

**Comment by ml-inory** [comment]
你品，你细品

**Comment by jxt1234** [comment]
因为mnn 支持的比ncnn 多啊（OpenCL / Vulkan / OpenGL / Metal / ARM / x86 ，后面还有 CUDA / TensorRT / NPU），框架包括 (Caffe / Onnx / Tensorflow / Tflite等等)
