### ISSUE TITLE
onnx 转 mnn 时网络输出的名字被修改了

### ISSUE THREAD

**Issue by smartadpole** [alibaba/MNN#1147]
# 平台:  ubuntu

# Github版本:  `3ea9dd1`

MNNConverter Version: 0.2.1.5    
MNNConverter  转换模型时，输出的名字被修改了，`anchors` 被改成了 `Relu6394` 这是为什么；

看了下代码，是 `OnnxClip.cpp` 中生成新的 op 时，没有为名字赋值；   
要怎么处理？

-----------------------------------------------

修改了 `OnnxClip.cpp` 文件
```
// line 57 添加了
    newOp->name = expr->name();
```

**Comment by yyfcc17** [comment]
解决了？

**Comment by smartadpole** [comment]
加了那行代码可以了，目前正常，不知道有没有隐含的 bug @yyfcc17

**Comment by jxt1234** [comment]
这个修改方式可以的，我们改一下

**Comment by jxt1234** [comment]
已经修正
