### ISSUE TITLE
在安卓下无法加载so

### ISSUE THREAD

**Issue by md5xwl** [alibaba/MNN#1149]
安卓10手机运行log。我自己编译的和github release下载的都不行。使用网上找的分为CL和vulkan版本的so是可以正常运行的。现在想替换成最新版本的。
报错log：
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN3MNN10FileLoaderC1EPKc" referenced by "/data/app/com.cxfuture.MirrorCalib-fzty0VKg0q3zgYk6J3gXug==/base.apk!/lib/arm64-v8a/libMNN_Express.so"...

Andriod.mk
include $(CLEAR_VARS)
LOCAL_MODULE := MNN
LOCAL_SRC_FILES := $(MNN_BASE)/libs/libMNN.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := MNN_Express
LOCAL_SRC_FILES := $(MNN_BASE)/libs/libMNN_Express.so
include $(PREBUILT_SHARED_LIBRARY)

java:
            System.loadLibrary("MNN_Express");
            System.loadLibrary("MNN");

**Comment by jxt1234** [comment]
像是 MNN_Express 和 MNN 两个 so 的版本不同，可以不使用 MNN_Express
