### ISSUE TITLE
ONNX and converted MNN have different layer.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#1152]
#456 Platform(Include target platform as well if cross-compiling):  
OSX

# Github Version: Latest version

-

Hi, I converted some file to MNN but it didn't work properly so I checked weight file's layer and I found something different each file.
You can check this here https://github.com/GHLab/2d106det
I pushed an image and model files.
Please check it and let me know.
Thank you.

**Comment by ml-inory** [comment]
In Netron, MNN's activation function is merged into Conv op,  You can click on a Conv Op to look into its properties, there's a relu6 inside, checkout mine.
![image](https://user-images.githubusercontent.com/8433542/94541714-79f07700-027a-11eb-9edf-c1c0b49eee89.png)
