### ISSUE TITLE
Invalidate buffer to create interpreter, verifyString failed for linux demo/Is there any demo for windows version?

### ISSUE THREAD

**Issue by woodrocky** [alibaba/MNN#116]
I am testing the demo on Windows. I tried this in two ways.
1> I build the MNN library on the MSYS environment, and compiled the Linux demo by linking the it with built library. But When I run the multiPose demo with converted MNN model,  I got the following error. "Invalidate buffer to create interpreter".
I checked it in the debug mode and found that the buffer verifying process failed. The verifyString 
failed due to the element length is much longer than size_. I don't know how to solve this problem. 

2> In the Beta 0.0.1.6 version, the Windows installation is updated. But there is no related test demo. Will this be released accordingly? 

Thanks!

**Comment by li-qing** [comment]
1. is the MNN model converted by MNNConverter built with the same code on the same environment?
2. what kind of test demo do you prefer?

**Comment by woodrocky** [comment]
> is the MNN model converted by MNNConverter built with the same code on the same environment?
> what kind of test demo do you prefer?

Hello, li-qing. Thank you for your prompt response. 
1> No, it's not same environment for the demo test. Since there is no Windows version while my testing. I install with MSYS and test under windows. 
2> I prefer using windows environment. Now I am trying to install the newly released windows version. But I have problem for the compiling of MNNConverter. I failed at almost the last step with 99% finished. The error is "NMAKE : fatal error U1073: don't know how to make 'source\tensorflow\tensorflow.lib'". Do you know what's wrong with this?

Thanks!

**Comment by li-qing** [comment]
> > is the MNN model converted by MNNConverter built with the same code on the same environment?
> > what kind of test demo do you prefer?
> 
> Hello, li-qing. Thank you for your prompt response.
> 1> No, it's not same environment for the demo test. Since there is no Windows version while my testing. I install with MSYS and test under windows.
> 2> I prefer using windows environment. Now I am trying to install the newly released windows version. But I have problem for the compiling of MNNConverter. I failed at almost the last step with 99% finished. The error is "NMAKE : fatal error U1073: don't know how to make 'source\tensorflow\tensorflow.lib'". Do you know what's wrong with this?
> 
> Thanks!

check doc/install.md, that is an unicode problem.

"Change "Setting -> region and language -> administration -> non-Unicide program language" to English (American), otherwise compile may failed because of encoding format."

**Comment by Liam-zzZ** [comment]
Hello. I have the same problem when compliling the MNNConverter by VS2017.  I already set "non-Unicide program language" to English (American). 

错误	LNK1104	无法打开文件“source\tensorflow\Debug\tensorflow.lib”

@li-qing @woodrocky

**Comment by li-qing** [comment]
> Hello. I have the same problem when compliling the MNNConverter by VS2017. I already set "non-Unicide program language" to English (American).
> 
> 错误	LNK1104	无法打开文件“source\tensorflow\Debug\tensorflow.lib”
> 
> @li-qing @woodrocky

try to build it with nmake as described in install.md
