### ISSUE TITLE
Linux平台编译的MNNConverter，在转换caffemodel失败

### ISSUE THREAD

**Issue by yccaicai** [alibaba/MNN#1161]
想问问作者这是啥原因呢
admin@ubuntu:~/cmm/MNN/MNN-1.0.2/build$ ./MNNConvert -f CAFFE --modelFile /home/admin/cmm/MNN/0605/hunterpro200.caffemodel --prototxt /home/admin/cmm/MNN/0605/hunterpro200.prototxt --MNNModel hunterpro200.mnn --bizCode MNN

MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [11:22:07] /home/admin/cmm/MNN/MNN-1.0.2/tools/converter/source/caffe/BatchNormalScale.cpp:145: Check failed: w0->blobs_size() >= 1 ==> caffemodel error!
已放弃 (核心已转储)

**Comment by HaoLiuHust** [comment]
@yccaicai 我也报这个错误，你解决了吗？

**Comment by jxt1234** [comment]
caffe 版本是?

**Comment by Wenboisstrong** [comment]
我遇到了同样的把问题 现在这个问题有更新么

**Comment by qq297110281** [comment]
遇到同样的问题，有解决方案吗？

**Comment by Azure-huxumin** [comment]
一样呢，请问该如何解决呢

**Comment by ShaunRain** [comment]
遇到了一样的问题，没找到具体原因。说下我的解决方式：先通过TNN的转换工具将caffe model转为ONNX，再用MNN的工具转换ONNX到MNN

**Comment by xiecailang** [comment]
一样的错误，有解决吗？

**Comment by wangzhaode** [comment]
caffe模型更新较少，推荐使用ONNX
