### ISSUE TITLE
Vulkan渲染管线中的Image能否直接利用MNN进行后处理？

### ISSUE THREAD

**Issue by Superlee506** [alibaba/MNN#1168]
您好，
我用Vulkan写了一个渲染管线，如果要多渲染的Image进行后处理，需要将image copy到CPU的内存空间，再利用MNN进行后处理，还是可以更高效的直接作为MNN的输入，省去GPU-CPU的I/O成本？

祝好。

**Comment by jxt1234** [comment]
理论上是可以的。
MNN 留了这个接口，基本流程：
（1）在 createSession 时传入外部 Vulkan 的上下文（Context）。
（2）resizeSession 完成之后，取出 session 的 input tensor 
（3）tensor 中的 deviceId() 是一个VkImageView （注：后面版本会改成 VulkanTensor），可使用这个，依赖 Vulkan Backend 相关头文件，自己编写预处理代码
