### ISSUE TITLE
android Demo闪退

### ISSUE THREAD

**Issue by Kevin-1993-35** [alibaba/MNN#1179]
android下测试Demo出现闪退，提示缺少libomp.so文件，请问如何解决？

**Comment by md5xwl** [comment]
不要32位，好像是现在高版本的ndk里面只有64位的库了

**Comment by yuanjinliang1** [comment]
> android下测试Demo出现闪退，提示缺少libomp.so文件，请问如何解决？
你好，请问你解决闪退的问题了吗？我也是，apk安装成功，一点开app就直接闪退。

**Comment by wangzhaode** [comment]
已修复：https://github.com/alibaba/MNN/pull/2244
