### ISSUE TITLE
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_32 against `_ZN6google8protobuf8internal9ArenaImpl23lifecycle_id_generator_E' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by ffffwyy** [alibaba/MNN#1181]
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_32 against `_ZN6google8protobuf8internal9ArenaImpl23lifecycle_id_generator_E' can not be used when making a shared object; recompile with -fPIC

想编译个模型转换，到这里就不行了。

**Comment by weixing0909** [comment]
> /usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.cc.o): relocation R_X86_64_32 against `_ZN6google8protobuf8internal9ArenaImpl23lifecycle_id_generator_E' can not be used when making a shared object; recompile with -fPIC
> 
> 想编译个模型转换，到这里就不行了。

我也遇到了同样的问题，请问找到解决方法了吗？
按照pymnn/INSTALL.md文件中运行python3 setup.py install遇到同样报错

**Comment by wangzhaode** [comment]
目前最新版本代码已提供protobuf源码编译，该问题可以解决
