### ISSUE TITLE
例程的疑问

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1184]
demo代码如下：
```
    image = image[..., ::-1]
    #change to rgb format
    image = cv2.resize(image, (224, 224))
    #resize to mobile_net tensor size
    image = image - (103.94, 116.78, 123.68)
    image = image * (0.017, 0.017, 0.017)
```
image已经从BGR转成RGB，
均值  (103.94, 116.78, 123.68) 对应的通道是BGR

做normalize的时候为什么是
`image = image - (103.94, 116.78, 123.68)`

而不是
`image = image - (123.68, 116.78, 103.94)`

**Comment by GuoJingtao-1997** [comment]
你好，我也有这个疑问，想问下是例程写错了么
