### ISSUE TITLE
Android demo: Pytorch_Retinaface

### ISSUE THREAD

**Issue by yyqgood** [alibaba/MNN#1187]
你好:
1. 我使用Pytorch_Retinaface: https://github.com/biubug6/Pytorch_Retinaface训练网络模型
2. 并使用MNN转换工具, 成功转换为.mnn格式

我现在想把.mnn格式模型, 部署在Android demo上, 请问有适配的Android demo推荐吗?(我对Android应用了解不多).
期待你的回复, 谢谢!

**Comment by md5xwl** [comment]
网上找到的一个https://github.com/Danicaai/android-mnn

**Comment by yyqgood** [comment]
@md5xwl 多谢你的回复!
