### ISSUE TITLE
Input te

### ISSUE THREAD

**Issue by awl-an-dang** [alibaba/MNN#1188]
I faced the issues:

tmp_input = MNN.Tensor((1, 1, 1024), MNN.Halide_Type_Float,
                           embedding, MNN.Tensor_DimensionType_Caffe)
"libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: numpy type does not match"

However the my input is only a vector with <class 'numpy.ndarray'> with size: (1, 1024) and astype(np.float32) (not an image),

How can pre-process it in the correct way? Do you have sample of inference with input a vector? Thank you so much

**Comment by jxt1234** [comment]
reshape as 1, 1, 1024 ?
