### ISSUE TITLE
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)

### ISSUE THREAD

**Issue by 563816752** [alibaba/MNN#119]
(find_package)wuzongruideiMac:MNN-master wuzongrui$ protoc --version
libprotoc 3.5.0
wuzongruideiMac:MNN-master wuzongrui$  ./tools/script/get_model.sh
building converter ...
===> Generating Schema...
===> Done!
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/FindProtobuf.cmake:594 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:32 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by sumyfly** [comment]
same error here, I use mac 10.14.5, libprotoc 3.9.1, cmake 3.13.4, 

building converter ...
===> Generating Schema...
===> Done!
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindProtobuf.cmake:595 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/shenglong.qian/workspace/android/MNN/tools/converter/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
cp: ../tools/converter/build/MNNConvert: No such file or directory
./get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./get_model.sh: line 48: ./build/MNNConvert: No such file or directory
./get_model.sh: line 48: ./build/MNNConvert: No such file or directory
./get_model.sh: line 58: ./build/MNNConvert: No such file or directory

**Comment by yananchen1989** [comment]
brew install protobuf
