### ISSUE TITLE
LRN层OpenCL与CPU差异过大

### ISSUE THREAD

**Issue by Xyzhao1999** [alibaba/MNN#1190]
# 问题
在使用backendTest.out进行测试时，发现在LRN层，使用OpenCL与CPU的计算结果差异较大（甚至不能通过容忍度0.5的测试）
![image](https://user-images.githubusercontent.com/23482405/96963840-f73a9f00-153b-11eb-8c1c-5d897ab4f552.png)

使用的MNN网络如下：

[age.onnx.mnn](https://drive.google.com/file/d/1GzvQ6vlofCwAQV-xbildfYmzEClsl8sN/view?usp=sharing
)

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

编译平台为Manjaro 20.1.2，交叉编译至Android库，使用NDK版本为r17c。
目标平台Android API版本为27，CPU： MT6763V/CT

# Github版本:
# Github Version:

使用Release版本 1.0.2， Comment = dce22aa352b1b5956d3a98d2168e90812f21fa32

# 编译方式:
# Compiling Method

```
    cmake .. \
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI="$1" \
        -DANDROID_STL=c++_static \
        -DANDROID_NATIVE_API_LEVEL=24  \
        -DANDROID_TOOLCHAIN=clang \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=./install \
        -DMNN_BUILD_FOR_ANDROID_COMMAND=ON \
        -DMNN_BUILD_SHARED_LIBS=ON \
        -DMNN_SEP_BUILD=OFF \
        -DMNN_BUILD_DEMO=ON \
        -DMNN_EVALUATION=ON \
        -DMNN_BUILD_BENCHMARK=ON \
        -DMNN_PORTABLE_BUILD=ON \
        -DMNN_USE_LOGCAT=ON \
        -DMNN_OPENCL=ON \
        -DMNN_OPENGL=ON \
        -DMNN_VULKAN=ON \
        -DMNN_ARM82=OFF \
        -DMNN_METAL=OFF \
        -DMNN_FMA_ENABLE=OFF \
        -DNATIVE_LIBRARY_OUTPUT=./install \
        -DNATIVE_INCLUDE_OUTPUT=./install

    make -j12 install/strip
```

**Comment by Xyzhao1999** [comment]
很奇怪   暂时无法复现这一问题了     如果有情况在open吧😂

**Comment by LiYufengzz** [comment]
> 很奇怪 暂时无法复现这一问题了 如果有情况在open吧😂
请问最后怎么解决的，我最近也遇到这个错误了

**Comment by LiYufengzz** [comment]
请问最后解决了吗？我最近使用backendtest做测试也出错了
