### ISSUE TITLE
android 使用vulkan 进行推理tensor 未发生变化

### ISSUE THREAD

**Issue by eudora-jia** [alibaba/MNN#1194]
# 平台:  Android
# Platform:  android

# Github版本:2.17.1
# Github Version:2.17.1

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
MNN version :1.0.2
Provide date (or b1etter yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:build_32.sh(ndk r17c)
# Compiling Method
为了得到有用的日志提醒，我编译的是debug 版本的MNN
```
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-14  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
说明一下：
我是用的srcformat NV21,dstformat BGR(这个跟模型有关系)
我用的模型是ONNX 转换的模型
我是用
process->convert( 将 图像转换成tensor,logcat 发现出现了这样的错误：
```
E/MNNJNI: Error for /mnt/d/3rdparty/MNN-1.0.2/source/backend/vulkan/execution/VulkanImageConverter.cpp, 79    
A/libc: /mnt/d/3rdparty/MNN-1.0.2/source/backend/vulkan/execution/VulkanImageConverter.cpp:79: void MNN::VulkanImageConverter::encodeBufferToTensor(VkBuffer, const MNN::Tensor *, const int, VkDeviceSize, MNN::MNN_DATA_FORMAT, const VulkanCommandPool::Buffer *): assertion "res" failed
    Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 9620 (pool-3-thread-1), pid 9526 (ple.cameramodel)
```

我看了代码 发现此处的错误来自convert 函数内部；调用逻辑是：
  convert ->copyFromHostTensor -> bn->onCopyBuffer->VulkanImageConverter::encodeBufferToTensor

**Comment by jxt1234** [comment]
应该最新代码已经 fix 了
