### ISSUE TITLE
crash on i5-3570

### ISSUE THREAD

**Issue by xinyu391** [alibaba/MNN#1195]
Ubuntu 20.04

### Compiling Method
 cmake .. -DMNN_BUILD_BENCHMARK=ON  -DMNN_BUILD_DEMO=ON -DMNN_BUILD_CONVERTER=ON ; make
 
执行benchmark 报错
**非法指令（核心已转储）**

GDB 显示
![image](https://user-images.githubusercontent.com/1401364/97255636-04150680-184c-11eb-8ad9-afc615b0bf0e.png)
把编译好的程序，拷贝到其他电脑（i7-6700 Ubuntu 20.04）上，执行无报错。
怀疑是cpu 不支持 sse指令。

**Comment by jxt1234** [comment]
cmake .. -DMNN_USE_SSE=false 可以关闭 sse 优化
