### ISSUE TITLE
yolov3裁剪模型量化后运行时crash

### ISSUE THREAD

**Issue by siweimaodou** [alibaba/MNN#1196]
# 平台(如果交叉编译请再附上交叉编译目标平台): ubuntu16.04  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:1.0.2
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式: 
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin

量化之前的模型是可以正常运行的，量化过程中出现Error for 38; 
检查崩溃点，发现位于MNNFloat2Int8.S中的函数MNNFloat2Int8()
[source.zip](https://github.com/alibaba/MNN/files/5449745/source.zip)

**Comment by fyw17** [comment]
# 平台(如果交叉编译请再附上交叉编译目标平台):  

Android

# Github版本:
mnn-1.0.2，下载地址：
https://github.com/alibaba/MNN/archive/1.0.2.zip

commit id：
https://github.com/alibaba/MNN/commit/dce22aa352b1b5956d3a98d2168e90812f21fa32

# 编译方式:
参考了：
https://www.yuque.com/mnn/cn/build_android

编译armv7动态库：
mkdir build_32 && cd build_32 && ../build_32.sh

#mnnconvert命令
mnnconvert -f ONNX --modelFile model_net_two.onnx --MNNModel dst.mnn

#量化命令
mnnquant dst.mnn quant.mnn preprocessConfig.json
输入结果：
(mobile36) root@M7-10-6-0-46-1-202:/data/image/workspace/libing.chen/test/mnnFaceEngine/faceEngine/models/gesture# mnnquant dst.mnn quant.mnn preprocessConfig.json 
[15:18:50] :78: >>> modelFile: dst.mnn
[15:18:50] :79: >>> preTreatConfig: preprocessConfig.json
[15:18:50] :80: >>> dstFile: quant.mnn
[15:18:50] :107: Calibrate the feature and quantize model...
[15:18:50] @ 109: Use feature quantization method: KL
[15:18:50] @ 110: Use weight quantization method: MAX_ABS
[15:18:50] @ 100: used image num: 300
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
ComputeFeatureRange: 100.00 %
CollectFeatureDistribution: 100.00 %
[15:19:38] :111: Quantize model done!

经过定位，Error for 38位于TensorStatistic.cpp的38行：
MNN_ASSERT(tensor->dimensions() == 4);

#模型加载crash
可重现bug的调用代码：
int testCreateSession(const char* modelPath, int threadNum = 2)
{
	Interpreter *net = NULL;	
	Session *session = NULL;	
	Tensor *input = NULL;
	
	net = Interpreter::createFromFile(modelPath);	
	if (!net)	{
		return -1;
	}	
	
	ScheduleConfig config;	
	config.type = MNN_FORWARD_CPU;
	config.numThread = threadNum;
	
	BackendConfig backendConfig;
	backendConfig.precision = BackendConfig::Precision_Low;
    
        printf("now create session:\n");
        session = net->createSession(config);
	if (!session)	{
		return -1;
	}
    
    input = net->getSessionInput(session, NULL);
    if (input == nullptr)
        	return -1;
	return 0;	
}

#在安卓adb shell执行结果： 
root@shamu: # ./run_motion quant.mnn
now create session:
[1] + Stopped (signal)     ./run_motion quant.mnn
root@shamu: #
[1] + Segmentation fault   ./run_motion quant.mnn

#libMNN打开log以后执行结果：
/mnt/c/exercise/MNN-1.0.2/source/core/Pipeline.cpp, 319

===> prepare op: 315, [Const]
        ===> compute shape: 315, [Const]
Outputs:
192, 2,
315 prepare success
/mnt/c/exercise/MNN-1.0.2/source/core/Pipeline.cpp, 319

===> prepare op: 315___FloatToInt8___0, [FloatToInt8]
        ===> compute shape: 315___FloatToInt8___0, [FloatToInt8]
Inputs:
192, 2,
Outputs:
192, 2,
[1] + Stopped (signal)     ./run_motion quant.mnn

模型文件，复现代码见附件，感谢！
[debug.zip](https://github.com/alibaba/MNN/files/5450358/debug.zip)

**Comment by TUT-jiayou** [comment]
@siweimaodou  @fyw17 
Hi, 两位能把yolov3 量化时,预处理配置的json 文件共享出来么?

**Comment by siweimaodou** [comment]
[preprocessConfig.zip](https://github.com/alibaba/MNN/files/6276809/preprocessConfig.zip)

**Comment by TUT-jiayou** [comment]
@siweimaodou  多谢了, 关于指定在arm gpu mali 上面运行, 你有经验么?

**Comment by siweimaodou** [comment]
没有啊





在 2021-04-08 15:31:31，"Fengtu Wang" ***@***.***> 写道：

@siweimaodou 多谢了, 关于指定在arm gpu mali 上面运行, 你有经验么?

**Comment by TUT-jiayou** [comment]
ok, 已经解决,参考官方的文档,解决了
