### ISSUE TITLE
MNN编译无testQuanModel.out

### ISSUE THREAD

**Issue by dongda118** [alibaba/MNN#1197]
现在是不再支持这个工具了吗？我看中文文档中也没提及这个了，但英文文档还有：https://www.yuque.com/mnn/cn/tool_quantize
如果没有这个工具了，那如何测评量化前后的差异？

**Comment by jxt1234** [comment]
不再支持这个工具，因为量化的评价标准与算法相关性很大，建议自行写代码评估。
