### ISSUE TITLE
MNN Converter NOT_SUPPORTED_OP: [ Pad ]

### ISSUE THREAD

**Issue by 563816752** [alibaba/MNN#120]
MNN Converter NOT_SUPPORTED_OP: [ Pad ]

**Comment by li-qing** [comment]
which training framework? tf? caffe?

**Comment by 563816752** [comment]
ONNX and TF

**Comment by 563816752** [comment]
> which training framework? tf? caffe?
ONNX and TF

**Comment by li-qing** [comment]
collected into pinned issue. and pad will be supported soon.

**Comment by ovthf** [comment]
ramework:
TensorFlow-lite

Not Supported OP:
PAD
