### ISSUE TITLE
iPhone 12的CPU上运行16bit，时长和内存占用与32位一样

### ISSUE THREAD

**Issue by jokerz0624** [alibaba/MNN#1200]
# 平台(如果交叉编译请再附上交叉编译目标平台):  MacOS 目标平台iOS
# Platform(Include target platform as well if cross-compiling):  

# Github版本:最新
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:Xcode编译
# Compiling Method

# 问题描述:
同样的几个模型，设置跑MNN的CPU。在iPhone12 上，不管设置16bit还是32bit，跑模型的内存占用和运行时长都是一样的。但是在iPhone Xs，11，8等设备上。跑16位的内存与时长相较于32位是差不多减半的。经过时间和内存对比，iPhone 12上设置CPU跑16bit，实际跑的仍是32位。

**Comment by jxt1234** [comment]
参考
https://github.com/alibaba/MNN/pull/1221

应该已经解决
