### ISSUE TITLE
有没有提供其他类型的demo示例，比如检测、分割？

### ISSUE THREAD

**Issue by GeneralJing** [alibaba/MNN#1201]

**Comment by jxt1234** [comment]
请下载 mnn 工作台，里面有 
https://www.mnn.zone/

**Comment by SatanWoo** [comment]
@GeneralJing 

可以参考 MNN 模型市场 ，这些模型都通过 MNN 工作台可以直接参考对应的部署代码

https://market.mnn.zone/s/#/modelmarket/list/
