### ISSUE TITLE
示例姿态检测中的pose model不能下载

### ISSUE THREAD

**Issue by wyushun** [alibaba/MNN#1204]
这个链接：https://www.yuque.com/mnn/cn/demo_project 中的**2.1 姿态检测**中的[pose model](https://raw.githubusercontent.com/czy2014hust/posenet-python/master/models/model-mobilenet_v1_075.pb)不能下载

**Comment by wyushun** [comment]
need to connect to google

**Comment by ricann** [comment]
Got it
