### ISSUE TITLE
关于IR的问题请教

### ISSUE THREAD

**Issue by wyushun** [alibaba/MNN#1214]
以Pool为例，我发现Pool的属性的描述都在[CaffeOp.fbs](https://github.com/alibaba/MNN/blob/master/schema/default/CaffeOp.fbs)中：
```
table Pool {
    padX:int;
    padY:int;
    isGlobal:bool=false;
    kernelX:int;
    kernelY:int;
    strideX:int;
    strideY:int;
    type:PoolType;
    padType:PoolPadType;
    dataType:DataType=DT_FLOAT;
    ceilModel:bool=true;
    pads:[int];
}
```

而相应的TensorflowOp.fbs就没有了pool的定义，也就是说CaffeOp.fbs中对Pool的定义就成了MNN的IR对吧。
如果是这样的话，感觉把定义写在CaffeOp.fbs这个文件中就很有迷惑性，感觉把MNN的所有OP的定义单独写在一个单独的文件中更加科学。

**Comment by jxt1234** [comment]
你的建议其实很有道理，目前这么命名是历史原因。
先支持的 caffe, 后面支持的 tensorflow ，相关 Op 在 caffe 中已有就不再添加。

**Comment by wyushun** [comment]
got it.
