### ISSUE TITLE
请问onnx如何利用caffe的crop算子？

### ISSUE THREAD

**Issue by ouyangwenhan** [alibaba/MNN#1215]
对于卷积，onnx能自动识别为caffe。
但是在onnx模型内加入自定义节点crop，mnn模型无法识别。
请问在哪个函数，或者如何解决这一问题？
谢谢

**Comment by jxt1234** [comment]
具体报什么错呢？

**Comment by jxt1234** [comment]
可以在tools/converter/source/onnx 下添加算子转换代码

**Comment by ouyangwenhan** [comment]
> 具体报什么错呢？

these op not support  ONNX::crop

我有一个TENSOR1是经过conv和deconv缩放，和原来的tensor进行concat时尺寸可能不一致，需要对tensor1进行crop。
由于ONNX不支持crop，我在ONNX中用symbolic function封装了一个crop算子，但是无法被MNN中的CAFFE::crop识别

我尝试按照教程自定义了一个ONNX2MNN的crop算子，还是同样的问题，似乎是无法被识别。

目前看上去是两种选择：1自己写一个onnxcrop算子，2调用caffe的crop。

不过对于2，我目前还是不甚了解onnx调用caffe算子的流程，是通过DefaultonnxOpConverter吗？

**Comment by jxt1234** [comment]
Onnx 可以用 slice 替代 crop 的

**Comment by ouyangwenhan** [comment]
> Onnx 可以用 slice 替代 crop 的

您好，谢谢~
如果我想通过ONNX调用caffe的算子请问具体应该如何操作呢？教程似乎没有写的很详细，而我在源码中也暂时没有找到对应的一部分，望指点~

**Comment by jxt1234** [comment]
无论是 Convolution 或是 Crop 都是 MNN 的算子，并不是通用 Onnx 调用 caffe 算子，把 Onnx 的算子转成 MNN 的 Crop 算子以在tools/converter/source/onnx 下添加算子转换代码即可
