### ISSUE TITLE
opencl kernel使用image2d的优势是什么

### ISSUE THREAD

**Issue by huwenfeng** [alibaba/MNN#122]
理解下mnn opencl卷积的bias从host内存转换成image2d的过程：
1.申请cl_buffer，map到cpu地址，copy host内存到cl_buffer，unmap
2.为bias创建DeviceTensor，申请image2d的device地址
3.copyBufferToImage:调用kernel copy内存cl_buffer到image2d
后续kernel使用image2d

从这个过程看，相比使用原生buffer地址，使用image2d作为kernel入参还多了第3步copy过程，请问使用image2d的优势是什么？？如有理解错误也请指出。
谢谢

**Comment by huwenfeng** [comment]
https://community.khronos.org/t/image2d-or-buffer/3708
看了这个链接，是否如链接所说场景原因？
Images are good if you need:
interpolation sampling (effectively free)
non-linear access (e.g. affine transformations, or y-order 2d)
automatic data conversion e.g. from ubyte to float and back again (effectively free)
2d-spatial coherency

**Comment by jxt1234** [comment]
1、如你的链接
2、高通Adreno系列GPU上，使用Image2D读取内存可以利用L1Cache，而Buffer只能用L2Cache
3､部分机器的OpenCL不支持 fp16 的计算，但 Image 的 float16 存储都支持，可以减少内存占用与读写量

**Comment by huwenfeng** [comment]
@jxt1234 ,谢谢答复
如果新增的op需要使用原生buffer作为kernel输入，需要将上一层op的输出的image转换成buffer？

**Comment by jxt1234** [comment]
是的
