### ISSUE TITLE
1.1.0版本编译安卓so文件错误，请问能否发出android的libMNN_CL.so和libMNN_VULKAN.so文件啊

### ISSUE THREAD

**Issue by luqiang6q** [alibaba/MNN#1222]
最新的安卓1.1.0版本编译安卓so文件错误，编译其他都没问题。

错误为：
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)

但我的protobuf已经安装完成，且同一个环境下编译0.2.2.2没有此问题发生。

所以，能否发一下你们编译的android的libMNN_CL.so和libMNN_VULKAN.so文件啊
@jxt1234

**Comment by hjchen2** [comment]
@luqiang6q 如果只需要这两个so，可以在编译时把MNN_BUILD_CONVERTER选项设为OFF，再重新make一下

**Comment by luqiang6q** [comment]
> @luqiang6q 如果只需要这两个so，可以在编译时把MNN_BUILD_CONVERTER选项设为OFF，再重新make一下

您好，按照您说的方法，现在这两个可以编译了。但是编译ARM82时出现以下问题：
`-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/project/android/build_64
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/project/android/build_64
[  2%] Built target MNNUtils
[ 16%] Built target MNNARM64
[ 19%] Building CXX object source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82Convolution3x3.cpp.o
[ 21%] Built target MNNCore
Scanning dependencies of target MNNCV
[ 21%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageBlitter.cpp.o
Scanning dependencies of target MNNCompute
[ 38%] Built target MNNCPU
[ 38%] Building CXX object source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82ConvolutionDepthwise.cpp.o
[ 38%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/BlstmComputer.cpp.o
[ 38%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:80:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b0 = vfmaq_f16(a4i, a2i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:81:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b1 = vfmaq_f16(a3i, a1i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:82:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t b2 = vsubq_f16(a4i, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:83:36: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t b3 = vmulq_f16(vsubq_f16(a3i, a1i), value_2);
                                   ^
[ 38%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:84:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b4 = vfmaq_f16(a4i, a0i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:85:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b5 = vfmaq_f16(a5i, a1i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:87:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t r0 = vfmaq_f16(b4, value_neg_5, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:88:26: error: use of undeclared
      identifier 'vaddq_f16'
        float16x8_t r1 = vaddq_f16(b0, b1);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:89:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t r2 = vsubq_f16(b0, b1);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:90:26: error: use of undeclared
      identifier 'vaddq_f16'
        float16x8_t r3 = vaddq_f16(b2, b3);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:91:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t r4 = vsubq_f16(b2, b3);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:92:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t r5 = vfmaq_f16(b5, value_neg_5, a3i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:110:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b0 = vfmaq_f16(a4i, a2i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:111:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b1 = vfmaq_f16(a3i, a1i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:112:26: error: use of
      undeclared identifier 'vsubq_f16'
        float16x8_t b2 = vsubq_f16(a4i, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:113:36: error: use of
      undeclared identifier 'vsubq_f16'
        float16x8_t b3 = vmulq_f16(vsubq_f16(a3i, a1i), value_2);
                                   ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:114:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b4 = vfmaq_f16(a4i, a0i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:115:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b5 = vfmaq_f16(a5i, a1i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:117:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t r0 = vfmaq_f16(b4, value_neg_5, a2i);
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:49:42: error: use of
      undeclared identifier 'vfmaq_f16'
            acc_value                  = vfmaq_f16(acc_value, src_x_value, weight_x_value);
                                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:61:34: error: use of
      undeclared identifier 'vmaxq_f16'
        acc_value              = vmaxq_f16(acc_value, zero_value);
                                 ^
make[2]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82Convolution3x3.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:66:34: error: use of
      undeclared identifier 'vmaxq_f16'
        acc_value              = vmaxq_f16(acc_value, zero_value);
                                 ^
[ 38%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:67:34: error: use of
      undeclared identifier 'vminq_f16'
        acc_value              = vminq_f16(acc_value, six_value);
                                 ^
4 errors generated.
make[2]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82ConvolutionDepthwise.cpp.o] Error 1
make[1]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...`

**Comment by luqiang6q** [comment]
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/project/android/build_64
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/project/android/build_64
[  2%] Built target MNNUtils
[ 16%] Built target MNNARM64
[ 19%] Building CXX object source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82Convolution3x3.cpp.o
[ 21%] Built target MNNCore
Scanning dependencies of target MNNCV
[ 21%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageBlitter.cpp.o
Scanning dependencies of target MNNCompute
[ 38%] Built target MNNCPU
[ 38%] Building CXX object source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82ConvolutionDepthwise.cpp.o
[ 38%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/BlstmComputer.cpp.o
[ 38%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:80:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b0 = vfmaq_f16(a4i, a2i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:81:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b1 = vfmaq_f16(a3i, a1i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:82:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t b2 = vsubq_f16(a4i, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:83:36: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t b3 = vmulq_f16(vsubq_f16(a3i, a1i), value_2);
                                   ^
[ 38%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:84:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b4 = vfmaq_f16(a4i, a0i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:85:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t b5 = vfmaq_f16(a5i, a1i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:87:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t r0 = vfmaq_f16(b4, value_neg_5, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:88:26: error: use of undeclared
      identifier 'vaddq_f16'
        float16x8_t r1 = vaddq_f16(b0, b1);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:89:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t r2 = vsubq_f16(b0, b1);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:90:26: error: use of undeclared
      identifier 'vaddq_f16'
        float16x8_t r3 = vaddq_f16(b2, b3);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:91:26: error: use of undeclared
      identifier 'vsubq_f16'
        float16x8_t r4 = vsubq_f16(b2, b3);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:92:26: error: use of undeclared
      identifier 'vfmaq_f16'
        float16x8_t r5 = vfmaq_f16(b5, value_neg_5, a3i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:110:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b0 = vfmaq_f16(a4i, a2i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:111:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b1 = vfmaq_f16(a3i, a1i, value_neg_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:112:26: error: use of
      undeclared identifier 'vsubq_f16'
        float16x8_t b2 = vsubq_f16(a4i, a2i);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:113:36: error: use of
      undeclared identifier 'vsubq_f16'
        float16x8_t b3 = vmulq_f16(vsubq_f16(a3i, a1i), value_2);
                                   ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:114:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b4 = vfmaq_f16(a4i, a0i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:115:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t b5 = vfmaq_f16(a5i, a1i, value_4);
                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82Convolution3x3.cpp:117:26: error: use of
      undeclared identifier 'vfmaq_f16'
        float16x8_t r0 = vfmaq_f16(b4, value_neg_5, a2i);
                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:49:42: error: use of
      undeclared identifier 'vfmaq_f16'
            acc_value                  = vfmaq_f16(acc_value, src_x_value, weight_x_value);
                                         ^
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:61:34: error: use of
      undeclared identifier 'vmaxq_f16'
        acc_value              = vmaxq_f16(acc_value, zero_value);
                                 ^
make[2]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82Convolution3x3.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:66:34: error: use of
      undeclared identifier 'vmaxq_f16'
        acc_value              = vmaxq_f16(acc_value, zero_value);
                                 ^
[ 38%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o
/Volumes/学习/programs/MNN-1.1.0/MNN-1.1.0/source/backend/arm82/Arm82ConvolutionDepthwise.cpp:67:34: error: use of
      undeclared identifier 'vminq_f16'
        acc_value              = vminq_f16(acc_value, six_value);
                                 ^
4 errors generated.
make[2]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/Arm82ConvolutionDepthwise.cpp.o] Error 1
make[1]: *** [source/backend/arm82/CMakeFiles/MNN_Arm82.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...

**Comment by jxt1234** [comment]
32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上

**Comment by luqiang6q** [comment]
> 32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上

arm_v8编译，我下了r21b，并没有编译成功。。。。。

**Comment by hjchen2** [comment]
> > 32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上
> 
> arm_v8编译，我下了r21b，并没有编译成功。。。。。

清空build目录后重新编译一下

**Comment by luqiang6q** [comment]
> > > 32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上
> > 
> > 
> > arm_v8编译，我下了r21b，并没有编译成功。。。。。
> 
> 清空build目录后重新编译一下

清空了之后再运行没再报错了，不过没有libMNN_ARM82.so生成，我用的命令是../build_64.sh -DMNN_OPENCL=ON，而opencl等backend用类似命令都可以生成，不知道是我的命令有问题么还是？

**Comment by hjchen2** [comment]
> > > > 32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上
> > > 
> > > 
> > > arm_v8编译，我下了r21b，并没有编译成功。。。。。
> > 
> > 
> > 清空build目录后重新编译一下
> 
> 清空了之后再运行没再报错了，不过没有libMNN_ARM82.so生成，我用的命令是../build_64.sh -DMNN_OPENCL=ON，而opencl等backend用类似命令都可以生成，不知道是我的命令有问题么还是？

需要打开MNN_ARM82选项的

**Comment by luqiang6q** [comment]
> > > > > 32位的不支持 armv82 的编译，如果是 64 位的，升级 android ndk 到 20 及以上
> > > > 
> > > > 
> > > > arm_v8编译，我下了r21b，并没有编译成功。。。。。
> > > 
> > > 
> > > 清空build目录后重新编译一下
> > 
> > 
> > 清空了之后再运行没再报错了，不过没有libMNN_ARM82.so生成，我用的命令是../build_64.sh -DMNN_OPENCL=ON，而opencl等backend用类似命令都可以生成，不知道是我的命令有问题么还是？
> 
> 需要打开MNN_ARM82选项的

![image](https://user-images.githubusercontent.com/28562997/98804233-e00f1300-2450-11eb-8379-dd5b9f78a8a6.png)

**Comment by hjchen2** [comment]
现在不会生成libMNN_ARM82.so这个库了，直接使用libMNN.so就行

**Comment by luqiang6q** [comment]
> 现在不会生成libMNN_ARM82.so这个库了，直接使用libMNN.so就行

行吧
