### ISSUE TITLE
在树莓派4上使用pip install -U MNN报错

### ISSUE THREAD

**Issue by Rsndmmm** [alibaba/MNN#1223]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
rawsberry pi4

报错信息
ERROR: Could not find a version that satisfies the requirement MNN (from versions: none)
ERROR: No matching distribution found for MNN

**Comment by hjchen2** [comment]
树莓派上需要自己编译安装，
cd到目录pymnn/pip_package，执行python build_wheel.py命令，得到wheel包之后安装一下

**Comment by wangzhaode** [comment]
https://github.com/alibaba/MNN/issues/1051
