### ISSUE TITLE
树莓派4  python build_deps.py时报错

### ISSUE THREAD

**Issue by Rsndmmm** [alibaba/MNN#1228]
# 平台(如果交叉编译请再附上交叉编译目标平台):  树莓派4

python build_deps.py时报错
报错信息如下：
[100%] Building CXX object tools/converter/CMakeFiles/MNNConvert.dir/source/MNNConverter.cpp.o
[100%] Linking CXX executable ../../MNNConvert
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::Init(bool)':
arena.cc:(.text+0x3ac): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[3]: *** [tools/converter/CMakeFiles/MNNConvert.dir/build.make:117: MNNConvert] Error 1
make[2]: *** [CMakeFiles/Makefile2:878: tools/converter/CMakeFiles/MNNConvert.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:890: tools/converter/CMakeFiles/MNNConvert.dir/rule] Error 2
make: *** [Makefile:424: MNNConvert] Error 2
pi@raspberrypi:~/zab/MNN/pymnn/pip_package $ protoc --version
libprotoc 3.13.0

**Comment by hjchen2** [comment]
参考下面链接的回答，请更新一下protobuf。

https://github.com/pytorch/pytorch/issues/22564#issuecomment-509029165

**Comment by Winter-of-Cirno** [comment]
> 
> # 平台(如果交叉编译请再附上交叉编译目标平台): 树莓派4
> 
> python build_deps.py时报错
> 报错信息如下：
> [100%] Building CXX object tools/converter/CMakeFiles/MNNConvert.dir/source/MNNConverter.cpp.o
> [100%] Linking CXX executable ../../MNNConvert
> /usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::Init(bool)': arena.cc:(.text+0x3ac): undefined reference to `__atomic_fetch_add_8'
> collect2: error: ld returned 1 exit status
> make[3]: *** [tools/converter/CMakeFiles/MNNConvert.dir/build.make:117: MNNConvert] Error 1
> make[2]: *** [CMakeFiles/Makefile2:878: tools/converter/CMakeFiles/MNNConvert.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:890: tools/converter/CMakeFiles/MNNConvert.dir/rule] Error 2
> make: *** [Makefile:424: MNNConvert] Error 2
> pi@raspberrypi:~/zab/MNN/pymnn/pip_package $ protoc --version
> libprotoc 3.13.0

请问你解决了吗？我更新了protobuf还是不行

**Comment by ling9601** [comment]
@Winter-of-Cirno 
请问你解决了吗，我编译了最新版本也是同样的错误

**Comment by wangzhaode** [comment]
https://github.com/alibaba/MNN/issues/1051
