### ISSUE TITLE
I think there is a littlr error in CPUDetectionOutput.cpp in backend folder

### ISSUE THREAD

**Issue by zhangweihua2003** [alibaba/MNN#123]
在输出检测框阶段，outPtr已经是float型了，为啥还*4呢？
    // write data
    auto outPtr = output->host<float>();
    for (int i = 0; i < numDetected; i++, outPtr += 6 * 4) {
        auto box      = allClassBoxes[i];
        outPtr[0 * 4] = box_label(box);
        outPtr[1 * 4] = box_score(box);
        outPtr[2 * 4] = box_rect_xmin(box);
        outPtr[3 * 4] = box_rect_ymin(box);
        outPtr[4 * 4] = box_rect_xmax(box);
        outPtr[5 * 4] = box_rect_ymax(box);
    }

**Comment by li-qing** [comment]
因为是在通道上做了pack 4
