### ISSUE TITLE
关于ConvertTensor层耗时的问题

### ISSUE THREAD

**Issue by curehabit** [alibaba/MNN#1233]
我在使用mnn过程中遇到了以下问题：mnn转换过的模型的ConvertTensor层非常多，每层的前后基本都有ConvertTensor。用timeProfile查看，ConvertTensor占用了推理时间的57.9%。还有一些ConvertTensor是NCHW->NCHW的操作。请问这个ConvertTensor能关掉或者有其他优化方案可选吗？或者如何避免频繁的转换来提高推理速度？谢谢！

**Comment by jxt1234** [comment]
可以先更新到 1.10，重新转换模型再试下，如果依然很耗时（对应地是 Raster），可以发下模型看看

**Comment by Yong-CV-PR-AI** [comment]
@curehabit 你好！我也遇到同样的问题，请问问题解决了吗？

**Comment by joe0327** [comment]
+1

> @curehabit 你好！我也遇到同样的问题，请问问题解决了吗？

**Comment by GeneralJing** [comment]
遇到了同样的问题，raster耗时占比最高。

**Comment by menchunlei** [comment]
> 遇到了同样的问题，raster耗时占比最高。

+1

**Comment by abcliguanxi** [comment]
> 遇到了同样的问题，raster耗时占比最高。

+1
