### ISSUE TITLE
Linux下编译MNNConvert 报错了

### ISSUE THREAD

**Issue by chenjiaoAngel** [alibaba/MNN#1234]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux

# Github版本:
# Github Version:
1.1.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
参考编译文档进行编译：https://www.yuque.com/mnn/cn/cvrt_linux_mac

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
mkdir build
cd build
cd build && cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

# 编译日志:
# Build Log:
error msg:
/MNN/source/core/BufferAllocator.cpp:199:54: error: no matching function for call to ‘std::multimap<long unsigned int, std::shared_ptr<MNN::BufferAllocator::Node> >::insert(std::pair<int, MNN::BufferAllocator::Node*>)’
     list->insert(std::make_pair(second->size, second));

![image](https://user-images.githubusercontent.com/38650344/99208207-d5f76680-27fa-11eb-8951-9c07b13c3fcc.png)

![image](https://user-images.githubusercontent.com/38650344/99208197-ced05880-27fa-11eb-9bda-7ec3d2242e0c.png)

```
粘贴在这里
Paste log here or pastebin
```

**Comment by smartwell** [comment]
same problem

**Comment by aytunai** [comment]
顶，遇到同样的问题

**Comment by aytunai** [comment]
update 看了mnn的编译构建测试，实测升级gcc版本到7.5可以解决问题

**Comment by jxt1234** [comment]
已经修正
