### ISSUE TITLE
编译android版的opengl so库时报错

### ISSUE THREAD

**Issue by rkshuai** [alibaba/MNN#124]
![cc014dad-dea1-43f7-84d5-a657105c863f](https://user-images.githubusercontent.com/11296462/59492153-ed6e4980-8eba-11e9-91f0-72857cfdd2ff.png)

**Comment by jxt1234** [comment]
opengl 这段时间在优化中，优化后会修复这个问题并且性能提升

**Comment by rkshuai** [comment]
好的，期待中
