### ISSUE TITLE
mnn输出与onnx输出完全对不上 

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1241]
大佬，我onnx转mnn，转换日志如下：
```
[01:41:19] :29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
[01:41:19] :20: Inputs: input
[01:41:19] :37: Outputs: output, Type = Interp
```
onnx输出使正确的，mnn也转换成功没有报错，但是mnn模型的输出与onnx模型输出对不上，mnn输出完全使错误的，导致后面mnn不能正常推理。

请问可能是什么问题？

转换的是DBnet模型，backbone是mobilenetv3.

onnx模型可以正常推理且结果正确，由onnx得到的mnn模型输出结果不对

**Comment by cendelian** [comment]
> 大佬，我onnx转mnn，转换日志如下：
> 
> ```
> [01:41:19] :29: ONNX Model ir version: 6
> Start to Optimize the MNN Net...
> [01:41:19] :20: Inputs: input
> [01:41:19] :37: Outputs: output, Type = Interp
> ```
> 
> onnx输出使正确的，mnn也转换成功没有报错，但是mnn模型的输出与onnx模型输出对不上，mnn输出完全使错误的，导致后面mnn不能正常推理。
> 
> 请问可能是什么问题？
> 
> 转换的是DBnet模型，backbone是mobilenetv3.
> 
> onnx模型可以正常推理且结果正确，由onnx得到的mnn模型输出结果不对

已解决，将mnn的输出格式是nc4hw4，将其转换为nchw即可

**Comment by powerfully** [comment]
请问一下如何把NC4HW4转化成NCHW?

**Comment by cendelian** [comment]
> 请问一下如何把NC4HW4转化成NCHW?

```
import MNN.expr as F
vars = F.load_as_dict("model.mnn")
inputVar = vars["input"]
# 查看输入信息
print(inputVar.shape)
print(inputVar.data_format)
# 修改原始模型的 NC4HW4 输入为 NCHW，便于输入
if (inputVar.data_format == F.NC4HW4):
    inputVar.reorder(F.NCHW)
# 写入数据
inputVar.write(numpy.ones([1, 3, 224, 224], dtype="float32").tolist())

# 查看中间结果的值
midVar = vars['mid']
print(midVar.shape)
# 切换布局便于查看结果
if (midVar.data_format == F.NC4HW4):
    midVar = F.convert(midVar, F.NCHW)
print(midVar.read())

# 查看输出结果
outputVar = vars['output']
print(outputVar.shape)
# 切换布局便于查看结果
if (outputVar.data_format == F.NC4HW4):
    outputVar = F.convert(outputVar, F.NCHW)
print(outputVar.read())

# 将关注的变量数值保存为 mnn 模型，可用 MNNDump2Json 打印查看
midVar.fix_as_const()
outputVar.fix_as_const()

F.save([midVar, outputVar], "outputs.mnn")
```

**Comment by zhuoran-guo** [comment]
> > 请问一下如何把NC4HW4转化成NCHW?
> 
> ```
> import MNN.expr as F
> vars = F.load_as_dict("model.mnn")
> inputVar = vars["input"]
> # 查看输入信息
> print(inputVar.shape)
> print(inputVar.data_format)
> # 修改原始模型的 NC4HW4 输入为 NCHW，便于输入
> if (inputVar.data_format == F.NC4HW4):
>     inputVar.reorder(F.NCHW)
> # 写入数据
> inputVar.write(numpy.ones([1, 3, 224, 224], dtype="float32").tolist())
> 
> # 查看中间结果的值
> midVar = vars['mid']
> print(midVar.shape)
> # 切换布局便于查看结果
> if (midVar.data_format == F.NC4HW4):
>     midVar = F.convert(midVar, F.NCHW)
> print(midVar.read())
> 
> # 查看输出结果
> outputVar = vars['output']
> print(outputVar.shape)
> # 切换布局便于查看结果
> if (outputVar.data_format == F.NC4HW4):
>     outputVar = F.convert(outputVar, F.NCHW)
> print(outputVar.read())
> 
> # 将关注的变量数值保存为 mnn 模型，可用 MNNDump2Json 打印查看
> midVar.fix_as_const()
> outputVar.fix_as_const()
> 
> F.save([midVar, outputVar], "outputs.mnn")
> ```

请问一下，我也遇到了上面的问题，具体是怎么用上面的代码将NC4HW4转化成NCHW的呢？

**Comment by zhuoran-guo** [comment]
用上述代码保存出来的模型只有2个节点而已

**Comment by wayy13** [comment]
> 用上述代码保存出来的模型只有2个节点而已

请问接下来是该怎么解决呢？我也遇到了一模一样的问题
