### ISSUE TITLE
模型量化错误

### ISSUE THREAD

**Issue by ouyangwenhan** [alibaba/MNN#1242]
原ori.mnn模型运行，通过quantized.out量化工具转化的new.mnn，显示转化成功。
查看模型变量发现new.mnn中的w和b均为tensor data is empty，切量化后模型运行结果异常。

mnn模型中无特殊算子。

**Comment by hroken** [comment]
遇到一样的问题，float32的推理结果都没问题，转换也成功了，但是weight和bias显示"Tensor data is empty."

**Comment by Wq-dd** [comment]
> 
同遇到这个问题，请问getSessionOoutput指定了名字后，拿到的输出结果为None是怎么回事呢？而且量化模型的时候打印了debug信息，居然显示overflow了，可是模型转换也成功，推理也不报错。
