### ISSUE TITLE
转为fp16 mnn模型或者是转为int8 mnn模型，推理速度没有任何变化

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1244]
你好，我onnx模型转为mnn时 ，选择--fp16 F16或者 --fp16 INT8， 转出来的模型会小一倍，但是推理速度没有任何变化

**Comment by jxt1234** [comment]
选 fp16 / int8 只影响模型大小，运行时会转成 fp32 ，不影响推理速度

**Comment by lxgyChen** [comment]
> 选 fp16 / int8 只影响模型大小，运行时会转成 fp32 ，不影响推理速度

ARMv8.2的cpu，对比了最新的MNN（v2.2.0）和最新的NCNN(20221128 03550ba)，fp16运行NCNN加速了3倍多，MNN还是没有加速啊
