### ISSUE TITLE
使用mnn 1.1.0, vulkan初始化耗时1.5s左右，是不是哪里配置有问题？

### ISSUE THREAD

**Issue by atlantis1314** [alibaba/MNN#1245]
在高通 晓龙7250平台，mnn 1.1.0版本，模型大小7.5M,
下面这段vulkan初始化耗时1.5s左右， 而cpu版本耗时100多ms，是不是哪里配置有问题？

    MNN::ScheduleConfig netConfig;
     netConfig.type = MNN_FORWARD_VULKAN;
    netConfig.numThread = 4;
    session = net->createSession(netConfig);

runSession vulkan版本倒是比cpu版本快了1倍。

**Comment by jxt1234** [comment]
GPU 初始化比 cpu 慢是正常的

**Comment by atlantis1314** [comment]
慢一点可以理解，300-400ms可以接受，但跑到1s多，有点超了把。

请问可以怎么优化？改编译选项，或者加什么配置。

**Comment by jxt1234** [comment]
你的模型方便发来看一下?

**Comment by atlantis1314** [comment]
我们用的hrnet, 通道数做了点裁减，用的fp16格式
https://github.com/HRNet/HRNet-Semantic-Segmentation

**Comment by GYxiaOH** [comment]
你好，你使用安卓平台的吗？请问下编译vulkan的时候是否有啥需要引入的，我这编译MNN_vulkan成功了，但是运行自己程序的时候回总提示can't find backend type 7

**Comment by atlantis1314** [comment]
用的安卓平台，我没设置BackendConfig

**Comment by QX-N** [comment]
> 

请问你这个问题解决了吗，我也遇到了同样的问题

**Comment by CloudGuardian** [comment]
> 你好，你使用安卓平台的吗？请问下编译vulkan的时候是否有啥需要引入的，我这编译MNN_vulkan成功了，但是运行自己程序的时候回总提示can't find backend type 7

请问解决了吗？
