### ISSUE TITLE
在multiPose demo中使用TRTBackend

### ISSUE THREAD

**Issue by WuYuChun** [alibaba/MNN#1247]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
在Ubuntu18.04 ,cuda10,tensorRT7.0版本环境中

# Github版本:
Github release 1.1.0

# 编译方式:
# Compiling Method

```
cmake -DMNN_CUDA=ON -DMNN_TENSORRT=ON -DMNN_BUILD_DEMO=ON .
```

并且修改multPose.cpp中的代码
```
MNN::ScheduleConfig netConfig;
    //netConfig.type      = MNN_FORWARD_CPU; 
    netConfig.type      = MNN_FORWARD_USER_1; 
    netConfig.numThread = 4;
    auto session        = mnnNet->createSession(netConfig);
```

运行后提示"nvalid Tensor, the session may not be ready"

请问,是否需要还需要怎么配置呢?针对于MultiPose demo

**Comment by jxt1234** [comment]
可以先把 source/cv/ImageProcess.cpp 203 行的逻辑判断去掉，这个是 trt backend 里面一个 bug ，暂时不支持 CV 输入
