### ISSUE TITLE
"TFlite model version ERROR!" using TFLiteConverter from tensorflow-2.0-beta

### ISSUE THREAD

**Issue by crj0322** [alibaba/MNN#125]
Error info: "/MNN/tools/converter/source/tflite/liteConverter.cpp:126: TFlite model version ERROR!"

How to convert tflite model generated by tf2.0?

**Comment by jxt1234** [comment]
What's your model't file type. Tflite or pb ?

**Comment by crj0322** [comment]
> What's your model't file type. Tflite or pb ?

Tflite

**Comment by czy2014hust** [comment]
We will update the schema of tflite

**Comment by kuafu1994** [comment]
@czy2014hust, so it means that MNNConverter does not support transferring xxx.tflite to xxx.mnn?
