### ISSUE TITLE
 _session = _net->createSession(config);报错

### ISSUE THREAD

**Issue by GeneralJing** [alibaba/MNN#1252]
Error for 41
Error for 41
Error for 41
Error for 41
Error for concat size of op [ 919 ], the 3 input not match output
	**Tensor shape**: 1, 6, 1, 1, 
	**Tensor shape**: 1, 6, 1, 3, 
-----------------------------------------------------------------------------------------------------------------------------
due to the internal logic of MNN, if your MNN model doesn't have input shape, you may ignore this 'Resize error' information:
** Resize error for [Concat], 919, code=3 **
it will work after you set the input tensor shape in MNN, and then resize the Session

**Comment by GeneralJing** [comment]
resolved.

**Comment by 553566286** [comment]
I match the same question, could you please tell me how did you solve it ?

**Comment by GeneralJing** [comment]
Update mnn.framework
