### ISSUE TITLE
MNN c++ 对tensor 切片操作[：-1]不支持 问题

### ISSUE THREAD

**Issue by gangeqian** [alibaba/MNN#1254]
使用pytorch模型 转onnx 再转mnn中
对于 51xMxN维 tensor 取前50维操作
![图片](https://user-images.githubusercontent.com/39591200/100174140-d2549580-2f06-11eb-8743-1b7daed85b7f.png)
转onnx 再转mnn 后均未报错。  c++ 编译无报错，运行时出现：
![图片](https://user-images.githubusercontent.com/39591200/100174341-3414ff80-2f07-11eb-88f9-71be5eb81920.png)
即运行结果第0维数是51，与pytorch运行的50不一致。
也就是说
切片操作out_j[:-1 , : , :] 执行结果等效于out_j[：，：，：]，结果出错。
再尝试了下out_j[-1，：，：]执行结果是对的。
再尝试了下out_j[0:50，：，：]执行结果也是对的。

我的pytorch版本：1.5.1
onnx版本：1.7.0
MNNConverter Version: 0.2.1.5git
MNN 代码日期：20200523

**Comment by jxt1234** [comment]
stridedslice 的这个 mask 已经支持
