### ISSUE TITLE
关于ConvertTensor的问题

### ISSUE THREAD

**Issue by Shaquille-Wu** [alibaba/MNN#1255]
小弟有三个问题，请阿里的大神们参详一下：
第一个问题，1.1.0之前create graph之后，会有OpType_ConvertTensor，现在统一改成了Raster.
对于某些模型而言，在模型转换之后，比如从onnx转成MNN，不知道为什么会生成非常多的ConvertTensor。比如我有一个模型，生成MNN之后一共有214个op，其中converttensor就占了50个左右，对于gpu.opencl的实现而言，这样对内存和效率都是有浪费的。因为在opencl的实现中，ConvertTensor其实就是copy，这种ConvertTensor其实可以忽略。
之前发现这个问题，专门针对这部分逻辑进行了修改，可是1.1.0的版本在create graph的逻辑中又做了修改，我们不得不又跟着做修改，能不能请阿里的大神优化一下这块逻辑.
第二个问题，之前的slice,concat,reshape等等，在新版本中都改成了raster，之前针对slice和concat在opencl上面的实现做了一点调整，其实他们在axis等于1的时候，也就是针对channel通道的时候，其实就是一个imagecopy的操作，这样是不是比通过kernel函数的更好一点？现在更新成raster之后，我们又要费很大的功夫，去区分slice和concat跟其他op的区别，有点麻烦。能不能请阿里的大神们针对直接imagecopy的情形，做一些调整？
第三个问题，在新版本中binary_same_channel_broadcast，似乎派不上用场了，1.1.0中遇到需要channel_broadcast的eltwise操作，在之前就执行了broadcast的操作，这样其实是对内存和效率的浪费。能不能恢复到原来的状态？

**Comment by jxt1234** [comment]
关于第二个问题，axis = 1 的 slice / concat 对应到 opencl 的 raster 里面会转成 image copy ，性能不受影响的。其他两个我们也在找更好的解决方案。

**Comment by Shaquille-Wu** [comment]
raster里面的操作都是通过kernel函数实现的，我们的意思是直接调用enqueueCopyImage，这样更简洁一点，效率上会好那么一点点。在slice和concat的操作很多的时候，我们很在乎被优化出来的那么一点点时间

**Comment by Shaquille-Wu** [comment]
其实，只要能把raster对应的原始op及其参数以某种形式明确的表达出来，我们也可以把各种情况区分开。不知道能不能加上这些参数？

**Comment by EdwardVincentMa** [comment]
你好，我想请教一下，经过convertTensor操作后，之后的操作需要相应改变权重顺序嘛？

**Comment by jxt1234** [comment]
> raster里面的操作都是通过kernel函数实现的，我们的意思是直接调用enqueueCopyImage，这样更简洁一点，效率上会好那么一点点。在slice和concat的操作很多的时候，我们很在乎被优化出来的那么一点点时间

1、之前我们测试用 kernel 是快于用 enqueueCopyImage 的，另外你也可以在 Raster 算子中判断连续的区块段，用 enqueueCopyImage，基于 Raster 优化是更高效的。
2、连续形变会被合并，相比原先的网络更快，相应地，也不会有原始 Op 及对应参数

**Comment by Shaquille-Wu** [comment]
谢谢大神的回复，大家的测试结果确实有不一样的地方
