### ISSUE TITLE
部署包含innterproduct的模型结果完全不对。

### ISSUE THREAD

**Issue by ritsukaginn** [alibaba/MNN#1256]
这边尝试转换PCN模型。转换后，stage1的结果是正确的，但是stage2的结果却完全不对。（Stage3还没有测试）
输入输出核实了好多次，应该是没有问题的。
查看了一下mnn模型，stage2有用到innerproduct，到了mnn里被转换成了各种reshape操作。不知道是不是转换的操作不对？
附上了转换前caffe和转换后的mnn模型。

[models.zip](https://github.com/alibaba/MNN/files/5595659/models.zip)

**Comment by jxt1234** [comment]
经验证应该没问题，是使用出错-0-

**Comment by 205418367** [comment]
你好，你用MNN实现了PCN没？代码能让我学习一下么？
