### ISSUE TITLE
Win10编译converter出错

### ISSUE THREAD

**Issue by EdwardVincentMa** [alibaba/MNN#1259]
编译了converter，ALL_BUILD, 提示未定义 MNN_VERSION
![image](https://user-images.githubusercontent.com/39480728/100236631-dfa26c00-2f68-11eb-9e80-dc2d4235dcab.png)

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
win10 

# Github版本:

# Github Version:
上周才下载的最新版

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
vs2019
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
cmake .. -DMNN_BUILD_CONVERTER=true
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
D:\ProgramData\VS2019\MNN\tools\converter\build>cmake .. -DMNN_BUILD_CONVERTER=true
-- Building for: Visual Studio 16 2019
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.27.29112.0
-- The CXX compiler identification is MSVC 19.27.29112.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: D:/Soft/TFSoft/protobuf-3.4.0/build-vs2019/libprotobuf.lib (found version "3.4.0")
-- Onnx: D:/ProgramData/VS2019/MNN/tools/converter/build/onnx.pb.h;D:/ProgramData/VS2019/MNN/tools/converter/build/onnx-operators.pb.h
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.18)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: D:/ProgramData/VS2019/MNN/tools/converter/build
# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
>------ 已启动生成: 项目: MNNConvert, 配置: Release x64 ------
1>MNNConverter.cpp
1>D:\ProgramData\VS2019\MNN\tools\converter\include\cxxopts.hpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\ProgramData\VS2019\MNN\3rd_party\flatbuffers\include\flatbuffers/util.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\ProgramData\VS2019\MNN\tools\converter\include\cxxopts.hpp(408,1): warning C4267: “=”: 从“size_t”转换到“US”，可能丢失数据
1>D:\ProgramData\VS2019\MNN\tools\converter\include\cxxopts.hpp(430): message : 查看对正在编译的函数 模板 实例化“void cxxopts::values::integer_parser<uint8_t>(const std::string &,T &)”的引用
1>        with
1>        [
1>            T=uint8_t
1>        ]
1>config.cpp
1>D:\ProgramData\VS2019\MNN\tools\converter\source\config.cpp(11,43): error C2065: “MNN_VERSION”: 未声明的标识符
1>正在生成代码...
1>已完成生成项目“MNNConvert.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by yutianhang** [comment]
MNN github readme链接：
https://github.com/alibaba/MNN/blob/master/README_CN.md#%E6%96%87%E6%A1%A3%E4%B8%8E%E5%B7%A5%E5%85%B7
语雀文档中Converter编译链接：
https://www.yuque.com/mnn/cn/cvrt_windows#s44Du

使用Ninja编译
