### ISSUE TITLE
NC4HW4和权重之间的关系

### ISSUE THREAD

**Issue by EdwardVincentMa** [alibaba/MNN#1260]
模型由onnx转mnn后出现convertTensor层，请问这一层具体什么操作，是否影响后面卷积的权重的排列顺序，权重顺序如果随之改变的话怎么变的？ 而caffe转mnn则没有出现这种层。

caffe上，卷积操作实际上是 im2col 与 gemm， 如果改变了输入顺序，mnn对权重的顺序是否也改变了，这样的输入顺序，没法用im2col了。

**Comment by jxt1234** [comment]
caffe 所有层一律使用 NC4HW4 格式，所以没有 ConvertTensor 。Onnx 目前多数算子目前用的 NCHW 格式，而 Image 相关 Op （Convolution 等）为NC4HW4，因此有转换。

为了最好性能，mnn 内部有一套与 caffe 等框架完全不一样的数据重排机制，最终运行结果是保证正确的。可以自己用 相关脚本校验。
