### ISSUE TITLE
PyMNN example inference issue

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1262]
Hello
How are you?
Thanks for contributing this project.
I am going to use MNN in Python.
First, I built the latest MNN directly on Raspberry Pi Ubuntu 20.10 64 bit OS (aarch64).
I tested the sample MNN C++ applications, which work well.
I built PyMNN successfully but I failed in running the sample mobilenet test script.

![image](https://user-images.githubusercontent.com/47862419/100494326-a5f57f00-317b-11eb-8d98-605422039270.png)

In fact, I changed the file "setup.py" when install PyMNN so that the dynamic lib file "libprotobuf.so" rather than the static lib file "libprotobuf.a" can be linked. This may be the reason, but this is only for compiling MNN conversion tools.
The environment is following:
Platform: aarch64
Protobuf: 3.12.3
Python: 3.8.6
CMake: 3.16.3
gcc: 10.2.0
I used the mobilenet-v1 model in the "benchmark/models" folder.
Could u help me asap?
Thanks

**Comment by wangzhaode** [comment]
ref : https://github.com/alibaba/MNN/issues/1051
