### ISSUE TITLE
MNN empty output tensor

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#1263]
# Platform(Include target platform as well if cross-compiling):  Android

# Github Version: 135f3d0f84bddd30b489d6eff94e744eb8822eda (latest commit as on 29 Nov 2020)

I have a ONNX model that I converted with latest converter. The output tensor should be of shape 1, 1, 1, 7 (N, H, W, C) but the output shape I get after inference is 0, 0, 0, 7

auto output_feat = paznet_interpreter_emotion_->getSessionOutput(paznet_sess_emotion_, nullptr);

Models are attached below
[Archive.zip](https://github.com/alibaba/MNN/files/5611196/Archive.zip)

**Comment by jxt1234** [comment]
此网络没有初始输入，需要 resizeTensor -> resizeSession

**Comment by jxt1234** [comment]
另附，验证了输入 resize 为 1, 48, 48, 1 之后，mnn 与 onnx 结果是一致的
