### ISSUE TITLE
MNN wrong output for converted TFLITE model

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#1264]
# Platform(Include target platform as well if cross-compiling):  Android

# Github Version: 135f3d0f84bddd30b489d6eff94e744eb8822eda (latest commit as on 29 Nov 2020)

I have a TFLITE model that I converted with latest converter. The output is all wrong and gives value of 1.0 for for every input combination.

for (int i = 0; i < 7; i++) {
            feat->at(i) = feat_tensor.host<float>()[i]; // Output is all 1.0s
}

Models are attached below
[Archive.zip](https://github.com/alibaba/MNN/files/5611237/Archive.zip)

**Comment by jxt1234** [comment]
这个模型有 depth_multiplier ，目前仅支持 pb 的格式转换
