### ISSUE TITLE
config.forwardType=MNNForwardType.FORWARD_AUTO.type的作用

### ISSUE THREAD

**Issue by ZhangZoffy** [alibaba/MNN#1267]
MNN安卓中，在配置时选
config.forwardType=MNNForwardType.FORWARD_AUTO.type，是默认选什么设备进行推理？
跟config.forwardType = MNNForwardType.FORWARD_CPU.type的区别是啥？
我试了在荣耀8手机上， MNNForwardType.FORWARD_CPU.type的运行速度比MNNForwardType.FORWARD_AUTO.type的快1倍多。

**Comment by wangzhaode** [comment]
AUTO会自动选择后端，CPU就是使用CPU后端
