### ISSUE TITLE
Android 平台上，OpenCL，createSession，耗时 N s

### ISSUE THREAD

**Issue by Kasqqqqqqq** [alibaba/MNN#1268]
Android 平台上，GPU OpenCL，createSession，耗时很长，耗时达到 7-8 秒。

**Comment by GYxiaOH** [comment]
...同。在linux上也是如此

**Comment by black-giser** [comment]
我开了OpenGL计算并没有提速啊

**Comment by jxt1234** [comment]
请参考 https://www.yuque.com/mnn/cn/create_session 

1、 mode 设置，选择 关闭 Auto-Tuning
2、保存  cache ，下次 create session 可以变快
