### ISSUE TITLE
量化后速度变慢

### ISSUE THREAD

**Issue by ouyangwenhan** [alibaba/MNN#1269]
同样模型在量化后速度变慢很多，用timeprofile脚本测试：在mflops一致的情况下，Convint8的运行时间为未量化conv op的8-10倍，导致了模型运行速度很慢。请问是什么原因造成的？
均在CPU backend上编译的静态库
谢谢

**Comment by czy2014hust** [comment]
在x86上测试的？在arm平台测试下吧

**Comment by ouyangwenhan** [comment]
> 在x86上测试的？在arm平台测试下吧

现在在linux上做了aarch64的混合编译。在hi3559A上测试的，但是速度还是不理想，是不是因为neon在linux端没有开启的原因？还是其他的原因？
似乎mnn做的优化都是针对android的arm

**Comment by jxt1234** [comment]
参考 FAQ https://www.yuque.com/mnn/en/faq 最后一段，另外，最近会添加全量化支持，会有一定加速
