### ISSUE TITLE
linux运行vulkan backend问题

### ISSUE THREAD

**Issue by Sunnyday2016** [alibaba/MNN#127]
成功在Ubuntu编译生成libMNN_VUlkan.so,但没有关联上，无法运行vulkan backend，提示Can't Find type=7 backend, use 0 instead

**Comment by jxt1234** [comment]
先确认下有没有安装 vulkan 驱动，完成安装后如果还不行，修改
source/backend/vulkan/runtime/vulkan_wrapper.cpp 代码，将 19 行 vulkan 的 位置换成系统中的库的位置

**Comment by Sunnyday2016** [comment]
> 先确认下有没有安装 vulkan 驱动，完成安装后如果还不行，修改
> source/backend/vulkan/runtime/vulkan_wrapper.cpp 代码，将 19 行 vulkan 的 位置换成系统中的库的位置

有成功安装驱动并且跑起来vulkan的示例vkcube以及vulkanInfo。修改后还是不能，甚至没有执行到vulkan_warpper中的代码。

**Comment by Sunnyday2016** [comment]
驱动成功安装
![2019-06-19 19-54-57屏幕截图](https://user-images.githubusercontent.com/21992233/59764054-8216e400-92cd-11e9-8e88-52adf5ebfd16.png)

实验将库的位置替换并检查.so加载情况
![2019-06-19 20-07-04屏幕截图](https://user-images.githubusercontent.com/21992233/59764193-dae67c80-92cd-11e9-8c69-fd2b54cb375d.png)

没有print出相关语句
![2019-06-19 19-59-26屏幕截图](https://user-images.githubusercontent.com/21992233/59764203-e0dc5d80-92cd-11e9-8750-642bb2369755.png)

**Comment by jxt1234** [comment]
Linux 系统有可能需要手动加载 vulkan 库
#inlcude<dlfcn.h>
在 main 函数第一行加入代码
auto handle = dlopen("libMNN_Vulkan.so", RTLD_NOW);

**Comment by Sunnyday2016** [comment]
谢谢！问题解决了，不过还需要在makelists 里面手动链接dl库

**Comment by GYxiaOH** [comment]
@Sunnyday2016 你好，请问你是怎么解决的呢。我也遇到了一样的问题

**Comment by lucaslu1987** [comment]
> 谢谢！问题解决了，不过还需要在makelists 里面手动链接dl库
How to solve the problem finally? Could you share the answer
