### ISSUE TITLE
The release 1.1 for Android seems to be only in debug mode.

### ISSUE THREAD

**Issue by pkubik** [alibaba/MNN#1270]
The binary size of `libMNN.so` in the Android release is around 80MB (for both armv7 and armv8). For Linux version there is `release` and `debug` with binary sizes ~3MB and ~90MB respectively. It seems like in the Android version only the debug binary is being distributed.

I think that the official Android bundle should provide smaller release binaries, because 80MB is rather unacceptable on a mobile device.

**Comment by wangzhaode** [comment]
The binary size is 2M like below:

https://github.com/alibaba/MNN/releases/download/2.3.0/mnn_android_arm82_opencl_vulkan.zip
