### ISSUE TITLE
MNN Python 1.1.0 crash

### ISSUE THREAD

**Issue by thibault20cent** [alibaba/MNN#1272]
Hi,

I upgrade to the latest MNN python 1.1.0 using pip.
It always crash at when calling interpreter.runSession(session) without any error code.
Everything is fine when using MNN 1.0.0
Any solution ?

Python version 3.6.8

**Comment by leosapucaia** [comment]
Hi all/@thibault20cent,

I have a similar problem. Windows environment, running Python 3.8, MNN 1.1.0.
When calling "interpreter.runSession (session)" the application stops without showing any error.

**Comment by wangzhaode** [comment]
Using MNN 2.x
