### ISSUE TITLE
如何获取任意层输出结果

### ISSUE THREAD

**Issue by EdwardVincentMa** [alibaba/MNN#1274]
Tensor* getSessionOutput(const Session* session, const char* name);

如果 name是输出层的名字，则函数没问题，但是如果name是中间层， 例如conv_1_conv2d层，则无法输出结果，报错: can't find output: conv_1_conv2d

ncnn 是可以获取中间层的结果的，mnn如何获取？

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/cn/create_session

这里面有写，createSession 时加入 saveTensors 即可

**Comment by mozpp** [comment]
> https://www.yuque.com/mnn/cn/create_session
> 
> 这里面有写，createSession 时加入 saveTensors 即可

savetensor怎么用啊？没看到有文档讲怎么用

**Comment by mozpp** [comment]
摸出来了
`config.saveTensors.push_back("283");`
这么用
