### ISSUE TITLE
lstm转onnx问题

### ISSUE THREAD

**Issue by cendelian** [alibaba/MNN#1276]
你好，我文字识别crnn模型里面有lstm部分，转onnx没问题，onnx转mnn的时候出现如下：

[06:42:53] :31: ONNX Model ir version: 6
[06:42:53] :155: Check it out ==> 726 has empty input, the index is 4
[06:42:53] :155: Check it out ==> 777 has empty input, the index is 4
Start to Optimize the MNN Net...
[06:42:54] :64: Inputs: input
[06:42:54] :69: Outputs: output

mnn模型输出结果是不对的。
onnx模型输出维度是（1，x，2671），x是不固定的，
但是mnn模型输出固定式（2，1，96）

请问mnn支持lstm转换吗？怎么解决？

onnx中的lstm部分结构图如下：
![image](https://user-images.githubusercontent.com/50360389/101023836-47cb0080-35ae-11eb-9704-786127b4ee0c.png)

**Comment by jxt1234** [comment]
先用 fastTestOnnx.py 测试下转换结果是否正确吧

**Comment by jxt1234** [comment]
另外是 mnn 的什么版本？

**Comment by cendelian** [comment]
> 另外是 mnn 的什么版本？

mnn版本是1.1.0

**Comment by cendelian** [comment]
> 先用 fastTestOnnx.py 测试下转换结果是否正确吧

转为onnx后，我用onnx推理，结果是完全ok的。（转onnx有警告，但是不影响onnx推理，onnx推理结果OK）
但是onnx转mnn后得到的mnn模型输出不对，mnn模型的输出维度固定是（2，1，96），有点莫名其妙。。。


转onnx过程中又以下警告：
**UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model. 
  "or define the initial states (h0/c0) as inputs of the model. ")**


下图是我单独转neck部分得到的onnx图

![image](https://user-images.githubusercontent.com/50360389/102967747-932d5a80-452d-11eb-9292-c327bfa65e54.png)

**Comment by cendelian** [comment]
> 先用 fastTestOnnx.py 测试下转换结果是否正确吧

运行fastTestOnnx.py结果如下：
![image](https://user-images.githubusercontent.com/50360389/102969294-675fa400-4530-11eb-8c02-69e11844d216.png)
看起来转换到onnx不对？？
可是onnx推理却是正常的。。。

**Comment by Mmmoran** [comment]
> > 先用 fastTestOnnx.py 测试下转换结果是否正确吧
> 
> 运行fastTestOnnx.py结果如下：
> ![image](https://user-images.githubusercontent.com/50360389/102969294-675fa400-4530-11eb-8c02-69e11844d216.png)
> 看起来转换到onnx不对？？
> 可是onnx推理却是正常的。。。
你好crnn的ocr识别onnx转mnn的解决没啊，我也遇到了这个问题

**Comment by jxt1234** [comment]
运行这个脚本需要先编译 Converter  （-DMNN_BUILD_CONVERTER=true）

**Comment by Ryuk17** [comment]
请问你解决这个问题了吗？
