### ISSUE TITLE
输入层数据对不上

### ISSUE THREAD

**Issue by EdwardVincentMa** [alibaba/MNN#1278]
先说结论，data层反推原图就出错了：
data层第一个值是1.168222，mean=127.5，scale = 0.007813。反推原图数据， 1.168222 * 128 + 127.5 = 277 已经超过255了，还有个值居然是 3.373189， 3.373189 * 128 + 127.5 = 559，远远超过255。怎么data层会是这样的输出？

![image](https://user-images.githubusercontent.com/39480728/101113013-7631f580-3619-11eb-8db2-3f030986788c.png)
网络的输入是这样的HCW，先减去127.5，再乘以0.007813，图像原始opencv数据如下，这里是从头截取的原始数据：
2
0
0
2
0
0
2
2
2
0
0
1
0
1
5
0
0
4
0
0
4
131
136
139
119
128
131
116
131
133
116
136
137
117
141
141
119
142
144
116
141
143
118
140
145
117
139
144
119
141
139
126
148
146
117
141
139
118
142
142
120
141
142
117
136
139
124
141
144
118
134
140
118
137
142
113
138
142
111
140
144
119
153
153
113
149
149
110
146
146
110
144
144
110
142
141
109
143
143
106
141
144
102
140
142
104
143
145
108
146
146
107
142
138
115
146
139
112
136
128
119
142
138
120
142
147
108
131
146
144
168
190
121
143
171
127
148
180
93
112
145
91
109
140
90
98
127
83
91
120
68
75
102
70
78
101
52
59
79
40
46
65
24
30
49
72
76
95
67
71
90
74
78
97
87
90
...

但是通过api getSessionInput()函数后，得到的data层结果如下:
1.168222
-1.044353
-0.376066
-0.477342
0.469763
3.373189
-0.797949
0.583316
0.693622
-0.928693
0.849160
0.007681
-0.330525
-0.675274
1.395367
-0.788744
0.106586
-0.795067
0.234675
0.965539
-0.220732
-0.009952
0.890184
-0.945304
...

**Comment by jxt1234** [comment]
1. 你怎么进行预处理的（如何填充输入的，有可能是 MNN::CV 的 mean 和 normal 填错了，也有可能是没有按同样的数据格式填充（uint8 / float））
2. 由于内存复用，runSession 之后，网络中的输入内存会变化，是否在 runSession 之后才去取的输入
