### ISSUE TITLE
About precision

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1279]
Hello
How are you?
Thanks for contributing this project.
I have a question.
When create a session of a model without quantization on only CPU, what is the difference between the precisions?
I know that MNN uses Low, Normal and High as precision when configure a session.
What is the default precision?
If the default precision is High, does it mean that the result from MNN model is same as the original model?
If so, what does the precision "Normal" mean?

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/en/create_session

Currently for CPU, the precision is only valid for ARM82, which will use fp16 instead of fp32 for comute.
