### ISSUE TITLE
Android中stl相关问题报错

### ISSUE THREAD

**Issue by AlpacaKnight** [alibaba/MNN#128]
因为原有的项目使用了依赖的库的是gnustl_static的静态库,所以android工程中-DANDROID_STL=选项只能用gnustl_static或者gnustl_share,而mnn的库使用的是c++_static,在其他方法调用时一切正常,但是在调用MNN::Tensor::create<float>(dims, &data);函数时会报undefined reference to 'MNN::Tensor::create()的错误,成员函数都可以正常调用,但是这个静态函数调用后编译会提示错误.

**Comment by jxt1234** [comment]
编译 mnn 的选项改成 gnustl 就可以了，比如 build_gnu_32.sh

**Comment by AlpacaKnight** [comment]
直接在0.2.0.0的版本中这么修改是错误的,不能直接编译通过,尤其是32位的会有问题

**Comment by jxt1234** [comment]
是指 mnn 编译错误?

**Comment by AlpacaKnight** [comment]
> 是指 mnn 编译错误?有编译错误的log么，如果是 opengl 出错的话先关掉

是的，可我要用的就是OpenGL

**Comment by jxt1234** [comment]
那先临时修改一下 GLBackend.cpp，加两个头文件吧 
#include <mutex>
#include <thread>
