### ISSUE TITLE
Not same as the original model result

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1281]
Hello
How are you?
Thanks for contributing this project.
I am going to use MNN for face encoding model, which is  ONNX version of vggface2 model 
https://we.tl/t-5j9vK8Ol6L.
This ONNX model works well on my Windows PC.
I installed Ubuntu 18.04 LTS and the latest master version of MNN on ARMv8(aarch64 platform) using only CPU.
The prebuilt MNN models for face detection downloaded from github works well.
I converted the onnx model for face encoding to MNN model by the following command.

./MNNConvert -f ONNX --modelFile /home/pi/Jin/Jin-FaceCheck-MNN/base_models/vggface2_sim.onnx --MNNModel /home/pi/Jin/Jin-FaceCheck-MNN/base_models/vggface2_sim.mnn --bizCode MNN

The onnx model inference script which get 2048 dimension vector is the following.

import numpy as np
import cv2
import onnxruntime
sess = onnxruntime.InferenceSession('vggface2_sim.onnx')

image_mean = np.array([93.5940, 104.7624, 129.1863], dtype=np.float32)
image_std = 1.0
img_size = 224
img_path = 'face.jpg'  # cropped face image
img = cv2.imread(img_path)
img = cv2.resize(img, img, (img_size, img_size))
img = img[..., ::-1] # to RGB format
img = img.astype(np.float32)
img = (img - image_mean) / image_std
x = np.expand_dims(x, axis=0)
x = x if isinstance(x, list) else [x]
feed = dict([(input.name, x[n]) for n, input in enumerate(sess.get_inputs())])
embedding = sess.run(None, feed)[0]

The MNN model inference script is the following.

import numpy as np
import cv2
import MNN

model_path = 'vggface2_sim.mnn'
interpreter = MNN.Interpreter(model_path)
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
interpreter.resizeTensor(input_tensor, (1, 224, 224, 3))
interpreter.resizeSession(session)

image_mean = np.array([93.5940, 104.7624, 129.1863], dtype=np.float32)
image_std = 1.0
img_path = 'face.jpg'  # cropped face image
img = cv2.imread(img_path)
img = cv2.resize(img, img, (img_size, img_size))
img= img[..., ::-1] # to RGB format
img = img.astype(np.float32)
img = (img - image_mean) / image_std
tmp_input = MNN.Tensor((1, 224, 224, 3), MNN.Halide_Type_Float,
                         img, MNN.Tensor_DimensionType_Tensorflow)
input_tensor.copyFrom(tmp_input)
interpreter.runSession(session)
output = interpreter.getSessionOutput(session).getData()
embedding = np.array(output[0])

I tested two models with 10 face images but results are very different.
This is the result from ONNX model.

![image](https://user-images.githubusercontent.com/47862419/101322363-dcc94480-38a1-11eb-9aa1-fadfb7a16651.png)

This is the result from MNN model.

![image](https://user-images.githubusercontent.com/47862419/101322414-f23e6e80-38a1-11eb-87ee-cee738bc62a9.png)

Could u help me so that this issue can be fixed asap?
Thanks

**Comment by jxt1234** [comment]
You can use tools/scripts/fastTestOnnx.py to check if mnn convert onnx is right.

**Comment by rose-jinyang** [comment]
Could u guide me to use this script?
Thanks

**Comment by rose-jinyang** [comment]
If u want, I can send the ONNX model and scripts for inference again.

**Comment by msx23** [comment]
I had similar problems after conversion from tflite, perhaps its the same as onnx. It turned out that some layers work without any problem and others just give wrong outputs at inference time (without an error message at compile time)

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/tools/convert.html#id3
