### ISSUE TITLE
An issue in conversion of TFLITE model 

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1282]
Hello
How are you?
Thanks for contributing this project.
I am going to convert a tflite model based on ResNet50.
Of course, this tflite model works well.
I installed Ubuntu 20.10 and the latest master version of MNN on ARMv8 (aarch64) platform.
it seems that the MNN engine and conversion tools are built successfully.
I tried to convert this tflite model with the following command.

./MNNConvert -f TFLITE --modelFile /home/pi/Jin/Jin-FaceCheck-MNN/base_models/vggface2.tflite --MNNModel /home/pi/Jin/Jin-FaceCheck-MNN/base_models/vggface2.mnn --bizCode MNN

But I met the following issue.

MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
Error while converting the model!
[18:38:41] /home/pi/Jin/MNN/tools/converter/source/tflite/BroadCastAdd.cpp:61: Check failed: addOption->fused_activation_function == tflite::ActivationFunctionType_NONE ==> BinaryOP Should not has fused_activation_function

I send the tflite model here.
https://we.tl/t-aWFUstWoYh
Could u help me so that this issue can be fixed asap?
Thanks

**Comment by jxt1234** [comment]
64246f6a45820ebc763e3bf55d50dd1ec85ad5f8 fix it.
