### ISSUE TITLE
3号群加不进去；MNN工作台的目标检测训练任务的输入数据是什么格式

### ISSUE THREAD

**Issue by wwdok** [alibaba/MNN#1283]
3号群扫完码说不存在；MNN工作台的目标检测训练任务的输入数据是什么格式，怎样才能让软件识别出我要训练的类别数，目前我的数据集格式是yolo格式

**Comment by wang-y-z** [comment]
我也加不进去，蹲一个新群；

**Comment by SatanWoo** [comment]
@wwdok @wang-y-z 可以加入啊，每天都有新同学加入钉钉群。

**Comment by SatanWoo** [comment]
![image](https://user-images.githubusercontent.com/1303079/115117976-afb93b00-9fd3-11eb-9005-aa8b9d0f2c37.png)
