### ISSUE TITLE
如何在测试metal后端性能？

### ISSUE THREAD

**Issue by devandong** [alibaba/MNN#1284]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS

# Github版本:
# Github Version:
fd488625da4d8864bf5f4ef7f8cfe33040db957f

# 编译方式:
# Compiling Method
使用playground项目，scheme为Release

1）性能测试的正确方式
iOS侧无法直接执行cpp程序，发现playground项目似乎可以用作测试性能，可以用过infer方法的cycles参数设置循环次数，通过这样测试metal性能合理吗？是否还有其他参数需要设置？
2）metalbackend中，在onExecuteBegin内进行了commit操作，但似乎没有同步等待gpu kernel完成的同步操作。在onWaitFinish中通过wait进行了同步操作，但onWaitFinish不在正常的执行路径上，请问在测试性能时是否需要手动添加？

**Comment by devandong** [comment]
any updates?

**Comment by jxt1234** [comment]
目前只能修改 playground 项目的代码测试，除了infer之外，输入输出需要调 copyFromHost / copyToHost 保持 gpu 运行完成

**Comment by devandong** [comment]
> 目前只能修改 playground 项目的代码测试，除了infer之外，输入输出需要调 copyFromHost / copyToHost 保持 gpu 运行完成

好的，谢谢！另外想问下，如果不希望将copy的时间开销考虑在内，那么自行添加同步操作测试性能是否可行?

**Comment by jxt1234** [comment]
可以自己修改 mnn 源码，目前不支持相关接口设置

**Comment by devandong** [comment]
ok，谢谢
