### ISSUE TITLE
转换TFLITE模型以后，调用pictureRecognition.out出现了错误

### ISSUE THREAD

**Issue by meetpos** [alibaba/MNN#1286]
平台: Ubuntu 16.04.1
编译器: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
TFLITE模型文件: 在附件model.tflite.zip
转换命令: ./MNNConvert -f TFLITE --modelFile ~/study/tensorflow-retrain/model.tflite --MNNModel b.mnn --bizCode biz
图像识别命令: ./pictureRecognition.out b.mnn ~/study/tensorflow-retrain/test/test_img_roses.jpg ~/study/tensorflow-retrain/flower_list.txt
重要错误: Error for compute convolution shape, need channel = 1280, input channel = 1
说明: 这个TFLITE模型文件是用tensorflow-r2.3迁移学习生成的，希望用MNN在arm-linux中进行图象分类提高速度

错误信息：
```
Can't Find type=4 backend, use 0 instead
Can't Find type=4 backend, use 0 instead
Error for compute convolution shape, need channel = 1280, input channel = 1
Compute Shape Error for MatMul71
input: w:224 , h:224, bpp: 3
origin size: 500, 375
Invalid Tensor, the session may not be ready
output size:0
```

**Comment by jxt1234** [comment]
附件没有了，另外更新下试试？
