### ISSUE TITLE
linux下aarch64，量化后卷积耗时增加

### ISSUE THREAD

**Issue by ouyangwenhan** [alibaba/MNN#1288]
请问linux下混合编译的arm的cpu优化是否和android相同。

测了若干模型，有略微下降（比如30到29ms，或者8到7ms）

不过性能最差的一个模型，总耗时从600ms增加到720ms（Hi3559A，4线程），主要为卷积耗时增加，卷积以3x3为主，有个别7x7的，耗时几乎全有增加。原先平均8.x ms，量化后平均10.x ms。（计算量8300mflops）

测试使用的benchmark，timeprofile脚本。

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/en/faq 里面最后一条
