### ISSUE TITLE
MNN with OpenGL support on Android

### ISSUE THREAD

**Issue by anahit-m** [alibaba/MNN#1289]
Hi.
I'm using MNN 1.1.0 release version. I want to run MNN model with OpenGL support to accelerate inference. I followed instructions in [this](https://www.yuque.com/mnn/en/build_android) link to compile library. During session creation it's not registering OpenGL backend and it switches to CPU (`Can't Find type=6 backend, use 0 instead`). 

Could u help me to fix this?

**Comment by jxt1234** [comment]
link MNN_GL or dlopen("libMNN_GL.so")
