### ISSUE TITLE
华为手机运行时出错 MemoryLeakMonitor.jar is not exist!

### ISSUE THREAD

**Issue by plbmw** [alibaba/MNN#129]
D/ActivityThread: Attach thread to application
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=won.com.testsdk#10192#256
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=won.com.testsdk#10192#0
I/AwareBitmapCacher: init processName:won.com.testsdk pid=4475 uid=10192
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: Runnable thread started.
D/IMonitor: Load library imonitor_jni
V/ActivityThread: Skipping new config:{1.0 460mcc3mnc [zh_CN_#Hans,en_CN] ldltr sw360dp w360dp h755dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2265, 1080) mAppBounds=Rect(0, 75 - 1080, 2340) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.170}, config:{1.0 460mcc3mnc [zh_CN_#Hans,en_CN] ldltr sw360dp w360dp h755dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2265, 1080) mAppBounds=Rect(0, 75 - 1080, 2340) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.170}
D/OpenGLRenderer: Skia GL Pipeline

**Comment by jxt1234** [comment]
??? 这个和 mnn 的关系是?
