### ISSUE TITLE
ios playground cpu 测试能通过 但metal测试失败

### ISSUE THREAD

**Issue by birham2020** [alibaba/MNN#1291]
**在ios真机上:**
**使用cpu做推理，测试能通过**
 ========= check NC4HW4 result ! ========= 
2020-12-12 23:47:38.528910+0800 Playground[2069:1126549] Metal GPU Frame Capture Enabled
2020-12-12 23:47:38.529167+0800 Playground[2069:1126549] Metal API Validation Enabled
Test 1 Backend

 ========= check NHWC result ! ========= 

 ========= check NC4HW4 result ! ========= 
	running op/elu.
	running op/Dilation2D/cpu.
	running core/tensor.
	running expr/Gather.
	running op/relu6.
	running op/gather_nd.
	running op/gather.
√√√ all tests passed.

### **但使用metal的时候测试没办法通过**

2020-12-12 23:48:21.586036+0800 Playground[2075:1127378] Metal GPU Frame Capture Enabled
2020-12-12 23:48:21.586685+0800 Playground[2075:1127378] Metal API Validation Enabled
	running core/memory_utils.
	running op/pad.
	running op/binary/broadcastShapeTest.
	running op/binary/add.
	running op/binary/subtract.
	running op/binary/multiply.
	running op/binary/divide.
	running op/binary/pow.
	running op/binary/minimum.
	running op/binary/maximum.
	running op/binary/biasadd.
	running op/binary/greater.
binaryop->opType()=10 in onCreate, 76 
The Creator Don't support type 7, 
right: 0, compute: 1
GreaterTest test failed!
	running op/binary/greaterequal.
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
right: 0, compute: 1
GreaterEqualTest test failed!
	running op/binary/less.
binaryop->opType()=12 in onCreate, 76 
The Creator Don't support type 7, 
right: 1, compute: 0
LessTest test failed!
	running op/binary/floordiv.
binaryop->opType()=13 in onCreate, 76 
The Creator Don't support type 7, 
	running op/binary/squareddifference.
	running op/binary/equal.
binaryop->opType()=15 in onCreate, 76 
The Creator Don't support type 7, 
right: 1, compute: 0
EqualTest test failed!
	running op/binary/lessequal.
binaryop->opType()=16 in onCreate, 76 
The Creator Don't support type 7, 
right: 0, compute: 1
LessEqualTest test failed!
	running op/binary/floormod.
	running op/binary/atan2.
binaryop->opType()=20 in onCreate, 76 
The Creator Don't support type 7, 
	running op/binary/logicalor.
binaryop->opType()=21 in onCreate, 76 
The Creator Don't support type 7, 
	running op/binary/notqual.
binaryop->opType()=22 in onCreate, 76 
The Creator Don't support type 7, 
	running op/binary/subtractBroastTest.
	running engine/DirectedAcyclicGraph.
	running expr/MatMul.
782.799988 -> 782.992188
788.950073 -> 788.757812
852.250061 -> 852.355469
858.999939 -> 859.210999
865.750061 -> 865.539062
872.499939 -> 872.394592
927.849976 -> 927.964844
935.199951 -> 935.429749
942.550049 -> 942.320312
949.899963 -> 949.785217
1003.450073 -> 1003.574219
1011.399963 -> 1011.648499
1019.350037 -> 1019.101562
1027.299927 -> 1027.175781
1=1 in run, 192 
	running op/setdiff1d.
	running op/concat.
	running op/OneHotTest.
	running expr/MultiThreadLoad.
	running expr/AllAny.
The Creator Don't support type 68, 
The Creator Don't support type 68, 
	running op/zeroslike.
	running op/gatherv2.
	running op/batch_to_space_nd.
	running op/prelu.
	running op/unary/abs.
	running op/unary/negative.
	running op/unary/floor.
	running op/unary/ceil.
	running op/unary/square.
	running op/unary/sqrt.
	running op/unary/rsqrt.
	running op/unary/exp.
	running op/unary/log.
	running op/unary/sin.
	running op/unary/cos.
	running op/unary/tan.
	running op/unary/asin.
	running op/unary/acos.
	running op/unary/atan.
	running op/unary/reciprocal.
	running op/unary/log1p.
	running op/unary/tanh.
	running op/unary/sigmoid.
	running op/unary/acosh.
	running op/unary/asinh.
	running op/unary/atanh.
	running op/unary/round.
	running op/unary/sign.
	running op/unary/cosh.
	running op/unary/erf.
The Creator Don't support type 101, 
	running op/unary/erfc.
The Creator Don't support type 101, 
	running op/unary/erfinv.
The Creator Don't support type 101, 
	running op/unary/expm1.
	running op/unary/sinh.
	running op/linspace.
	running op/SoftmaxGrad.
	running op/PoolGrad.
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
binaryop->opType()=11 in onCreate, 76 
The Creator Don't support type 7, 
	running op/reduction/reduce_sum.
	running op/reduction/reduce_sum_multi.
right: -82564.6, compute: -inf
ReduceSumMultiTest test failed!
	running op/reduction/reduce_mean.
	running op/reduction/reduce_max.
	running op/reduction/reduce_min.
	running op/reduction/reduce_prod.
	running op/Conv2DBackPropFilter.
	running op/Conv2DBackPropFilterDW.
	running op/tile.
	running op/matmul.

**Comment by MagicSen** [comment]
也遇到了，希望官方回复下

**Comment by wangzhaode** [comment]
Metal还不能完全跑通
