### ISSUE TITLE
Android下OPENGL下输入数据不对

### ISSUE THREAD

**Issue by ritsukaginn** [alibaba/MNN#1295]
CPU下和OPENGL下的输入数据不一致，不知道是不是哪里写错了？还是GPU端有问题？

# 平台(如果交叉编译请再附上交叉编译目标平台):  
Android

**后端的一些配置：**
 
    //set pretreat
    MNN::CV::ImageProcess::Config pretreat_config;
    pretreat_config.filterType = MNN::CV::BILINEAR;
    ::memcpy(pretreat_config.mean, MEAN, sizeof(MEAN));
    ::memcpy(pretreat_config.normal, STD, sizeof(STD));
    pretreat_config.sourceFormat = MNN::CV::BGR;
    pretreat_config.destFormat = MNN::CV::BGR;
    mPretreat = std::shared_ptr<MNN::CV::ImageProcess>(MNN::CV::ImageProcess::create(pretreat_config));

    //create session
    MNN::ScheduleConfig config;
    config.numThread = 3;
    //config.type = static_cast<MNNForwardType>(MNN_FORWARD_CPU);
    config.type = static_cast<MNNForwardType>(MNN_FORWARD_OPENGL);

    MNN::BackendConfig backendConfig;
    backendConfig.memory = MNN::BackendConfig::Memory_Normal;
    backendConfig.precision = MNN::BackendConfig::Precision_Normal;
    backendConfig.power = MNN::BackendConfig::Power_Normal;
    config.backendConfig = &backendConfig;
    mSession = mNet->createSession(config);

**数据操作和网络调用的代码：**

    auto inputTensor = new MNN::Tensor(mInput, MNN::Tensor::CAFFE);
    MNN::CV::Matrix trans;
    trans.setIdentity();
    mPretreat->setMatrix(trans);
    mPretreat->convert((uint8_t*)tmpInput.data, tmpInput.cols,tmpInput.rows, 0, inputTensor);
    mInput->copyFromHostTensor(inputTensor);

    /* debug*/
    auto testTensor = new MNN::Tensor(mInput, MNN::Tensor::CAFFE);
    mInput->copyToHostTensor(testTensor);
    for (int i = 0; i < INPUT_HEIGHT*INPUT_WIDTH; ++i) {
        __android_log_print(ANDROID_LOG_DEBUG, "dosegment", "%d img %d, inputTensor %f, testTensor %f", i, tmpInput.at<uint8_t >(i), inputTensor->host<float>()[i],testTensor->host<float>()[i]);
    }
    delete testTensor;

    delete inputTensor;

    mNet->runSession(mSession);

**输出的img,inputTensor,testTensor的值：**
**CPU下：**
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 0 img 119, inputTensor 2.023000, testTensor 2.023000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 1 img 232, inputTensor 1.224000, testTensor 1.224000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 2 img 250, inputTensor 2.193000, testTensor 2.193000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 3 img 72, inputTensor 2.431000, testTensor 2.431000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 4 img 213, inputTensor 2.703000, testTensor 2.703000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 5 img 241, inputTensor 1.972000, testTensor 1.972000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 6 img 129, inputTensor 2.669000, testTensor 2.669000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 7 img 234, inputTensor 3.400000, testTensor 3.400000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 8 img 247, inputTensor 2.822000, testTensor 2.822000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 9 img 143, inputTensor 2.737000, testTensor 2.737000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 10 img 250, inputTensor 3.060000, testTensor 3.060000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 11 img 255, inputTensor 1.666000, testTensor 1.666000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 12 img 159, inputTensor 0.000000, testTensor 0.000000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 13 img 238, inputTensor 0.000000, testTensor 0.000000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 14 img 243, inputTensor 0.119000, testTensor 0.119000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 15 img 116, inputTensor 0.340000, testTensor 0.340000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 16 img 235, inputTensor 1.938000, testTensor 1.938000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 17 img 247, inputTensor 1.207000, testTensor 1.207000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 18 img 157, inputTensor 1.836000, testTensor 1.836000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 19 img 250, inputTensor 2.380000, testTensor 2.380000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 20 img 252, inputTensor 1.326000, testTensor 1.326000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 21 img 200, inputTensor 0.918000, testTensor 0.918000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 22 img 255, inputTensor 2.057000, testTensor 2.057000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 23 img 255, inputTensor 2.533000, testTensor 2.533000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 24 img 166, inputTensor 1.734000, testTensor 1.734000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 25 img 250, inputTensor 1.904000, testTensor 1.904000
2020/12/15 19:30:10.013 22995 23020 Debug dosegment 26 img 255, inputTensor 2.601000, testTensor 2.601000

**OPENGL下：**
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 0 img 119, inputTensor 2.023000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 1 img 232, inputTensor 1.224000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 2 img 250, inputTensor 2.193000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 3 img 72, inputTensor 2.431000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 4 img 213, inputTensor 2.703000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 5 img 241, inputTensor 1.972000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 6 img 129, inputTensor 2.669000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 7 img 234, inputTensor 3.400000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 8 img 247, inputTensor 2.822000, testTensor 0.085000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 9 img 143, inputTensor 2.737000, testTensor 0.085000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 10 img 250, inputTensor 3.060000, testTensor 0.085000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 11 img 255, inputTensor 1.666000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 12 img 159, inputTensor 0.000000, testTensor 0.833000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 13 img 238, inputTensor 0.000000, testTensor 0.901000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 14 img 243, inputTensor 0.119000, testTensor 0.969000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 15 img 116, inputTensor 0.340000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 16 img 235, inputTensor 1.938000, testTensor 1.428000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 17 img 247, inputTensor 1.207000, testTensor 3.774000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 18 img 157, inputTensor 1.836000, testTensor 3.723000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 19 img 250, inputTensor 2.380000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 20 img 252, inputTensor 1.326000, testTensor 1.700000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 21 img 200, inputTensor 0.918000, testTensor 3.757000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 22 img 255, inputTensor 2.057000, testTensor 3.672000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 23 img 255, inputTensor 2.533000, testTensor 0.000000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 24 img 166, inputTensor 1.734000, testTensor 2.499000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 25 img 250, inputTensor 1.904000, testTensor 4.318000
2020/12/15 19:31:31.590 23997 24023 Debug dosegment 26 img 255, inputTensor 2.601000, testTensor 4.318000

**Comment by wangzhaode** [comment]
请使用OpenCL
