### ISSUE TITLE
How to use MNN as a submodule/subproject?

### ISSUE THREAD

**Issue by daquexian** [alibaba/MNN#13]
There is an `MNN_DEPEND` cmake variable, however, cmake variable is not visible to parent scope. So the super-project cannot get the correct MNN library path and compile flags.

The ideal solution is that the CMakeLists.txt of MNN adds a library target (named "mnn" or something else), and this target depends on vulkan, opengl and so on. So that users can simply depend on target "mnn" without concern about all the dependencies and compile flags.

What's more, I believe MNN should export a target (on `make install` or `cmake -P cmake_install.cmake`) as all modern cmake files do.

**Comment by li-qing** [comment]
good suggestion. we will revise it later.
