### ISSUE TITLE
Python wheels for other platforms like armv7

### ISSUE THREAD

**Issue by msx23** [alibaba/MNN#1306]
# Platform(Include target platform as well if cross-compiling):  
armv7 custom board with iMX7 processor

# Github Version:
1.1.0

# Compiling Method
native compiling

# Problem description
I´m trying to install the python interface of the mnn inference engine onto a custom imx7 board. On Raspberry Pi 4B there was no problem, but when I do the same on the custom board, it gets stuck during executing "setup.py install" without an error message. I suspect the board is running out of RAM during compilation but unfortunately adding a swapfile does not help. Protobuf could be installed without a problem. Basically I was following this guide:
https://programmersought.com/article/15856113308/

It would be much easier if there was a armv7 wheel available on pypi, is there any chance that mnn will be compiled as wheels for such platforms any time soon?

Or is there a way to compile the wheel externally for example on the Raspberry Pi?

**Comment by wangzhaode** [comment]
Please ref: https://github.com/alibaba/MNN/issues/1051
