### ISSUE TITLE
Windows下多线程无效？（benchmark）

### ISSUE THREAD

**Issue by lifengcai** [alibaba/MNN#131]
Hi，

在Linux及Android(交叉编译)下benchmark测试，多线程是有效的。
但是在Windows 10下编译(cmake+nmake)成功后进行benchmark测试，线程设置为1，2，4，时间不降，甚至反而增加，在各个平台的代码没有修改（代码版本beta 0.2.0.0）。

请问这是bug，还是Windows下暂时没有多线程特性？

编译环境：
Windows 10
i5 4590
VS 2019

测试结果：
Thread | 1 | 2 | 4
-- | -- | -- | --
squeezenet | 286.28 | 284.044 | 310.541
mobilenet | 272.945 | 284.37 | 284.442
mobilenet_v2 | 162.34 | 161.041 | 162.148
resnet50 | 1295.803 | 1335.403 | 1366.673

Thanks

**Comment by jxt1234** [comment]
Windows 上 OpenMP安装了么

**Comment by yutianhang** [comment]
1、看下是用debug编译的还是用release编译的
2、看下cmake的输出里，openmp有没有开

**Comment by lifengcai** [comment]
MNN_OPENMP
Defaults ON, When OFF, do not use openmp multi-thread, only effective on Android/Linux.

maybe..not support now.
