### ISSUE TITLE
Python 版本 MNN 1.1.0 和 1.1.2 目标检测模型结果错误，1.0.0结果正确

### ISSUE THREAD

**Issue by ruicx** [alibaba/MNN#1311]
# 平台(如果交叉编译请再附上交叉编译目标平台):
# Platform(Include target platform as well if cross-compiling):  

Python 3.8.5 on Windows 10
Python 3.7.6 on Ubuntu 18.04.5 LTS

# Github版本: 
# Github Version:

1.0.0 / 1.1.0 / 1.1.2

---

MNN 通过 pip 安装，在windows平台上尝试过1.0.0和1.1.0，在Ubuntu上尝试过1.0.0, 1.1.0, 1.1.2

具体情况如下:
| MNN Version | Ubuntu           | Windows 10       |
| ----------- | ---------------- | ---------------- |
| 1.0.0       | 正常             | 正常             |
| 1.1.0       | 框偏大且分类不准 | 框偏大且分类不准 |
| 1.1.2       | 框偏大且分类不准 |                  |

另外，如果在 MNN 1.1.0 或者 MNN 1.1.2 下运行 MNN 1.0.0 时转换的文件，则会出现满屏都是框的情况。

### 测试 1： [官方的 Yolo V3 demo](https://colab.research.google.com/drive/15SZRbFU4rxCJpGlp2qxaJ0R3cecOysDT)
环境：MNN 1.0.0 1.1.0 1.1.2 on Colab
检测结果：
![image](https://user-images.githubusercontent.com/20857887/102967459-ef43af00-452c-11eb-9b32-74ded06bc04d.png)

目标框并不准确，而且有些框的类别不对。 从代码中的 reshape 判断，这个应该是 MNN 1.1.0 的代码？
``` python
#copy tensor from to the temporary
output_tensor.getData().reshape([-1, 25])
output_data = output_tensor.getData().reshape([-1, 25])
```

### 测试2：[Ultra-Light-Fast-Generic-Face-Detector-1MB](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN)
环境：MNN 1.0.0 1.1.0 on Windows 10
使用repo中提供的 *slim-320.mnn*，MNN 1.0.0 下的检测正常
使用repo中提供的 *slim-320.mnn*，MNN 1.1.0 运行卡住没有结果。
MNN 1.1.0 下从repo中的 *version-slim-320_simplified.onnx* 转换，转换正常但是运行卡住没有结果.

### 测试3：Fork 的 [NanoDet](https://github.com/XieRuicheng/nanodet/tree/main/demo_mnn)
环境：MNN 1.0.0 1.1.0 on Windows 10，1.0.0 1.1.0 1.1.2 on Ubuntu 18.04.5 LTS

MNN 1.0.0 下 转换和检测的结果：
![000252](https://user-images.githubusercontent.com/20857887/102969738-30d65900-4531-11eb-9bd7-4c1451299800.jpg)
![000254](https://user-images.githubusercontent.com/20857887/102970183-03d67600-4532-11eb-8cbe-0f18323a8b0e.jpg)

MNN 1.0.0 下转换的模型在MNN 1.1.0 下的检测结果：
![000252](https://user-images.githubusercontent.com/20857887/102969893-7c890280-4531-11eb-95c5-5408cfc4c1c3.jpg)
![000254](https://user-images.githubusercontent.com/20857887/102970220-13ee5580-4532-11eb-9543-df44ceea4094.jpg)

MNN 1.1.0 下 转换和检测的结果：
![000252](https://user-images.githubusercontent.com/20857887/102970035-c1149e00-4531-11eb-83d4-f9c20ddfe527.jpg)
![000254](https://user-images.githubusercontent.com/20857887/102970273-2b2d4300-4532-11eb-8311-7e9300e39cac.jpg)

万望回复，谢谢

**Comment by JackLin-Authme** [comment]
Hi, you may re-transfer model with version 1.1.x. 
I guess some operators were re-written or fixed in 1.1.x. This could make your problem be solved.

**Comment by cvwoker** [comment]
我也碰到通用问题，测试model：nanodet

重新转换，1.0.0, load报 ERROR41
1.1.0运行问题依旧... ...

**Comment by JerryDeepl** [comment]
插个楼，好像mnn跑shufflenet和mobilenetv3，效率都远没mobilenetv1/v2高，所以跑nanodet效率上会不会比较不理想

**Comment by cvwoker** [comment]
1.1.2， 测试nanodet，结果正常了

**Comment by jxt1234** [comment]
图像预处理有确认过是一样的么？另外是否 precision 设成 low 了？

**Comment by XieRuicheng** [comment]
> 
> 
> 图像预处理有确认过是一样的么？另外是否 precision 设成 low 了？

预处理代码相同，经检查，输入矩阵给MNN模型的数据一致。precision使用默认设置没有修改
