### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1313]
Hello
I met an issue when compiling the latest version on aarch64.

![image](https://user-images.githubusercontent.com/47862419/103013764-a3b6f280-4578-11eb-81b9-6eb2697eb51f.png)

**Comment by yyfcc17** [comment]
change line 'mov v28.4s,v29.4s' to 'mov v28.16b,v29.16b', will solve this problem

**Comment by msx23** [comment]
I met the same problem, the supposed fix seems to work without any problems. But the line has to be corrected in two files, for float and integer assember operations

**Comment by jxt1234** [comment]
Fixed
