### ISSUE TITLE
object detection api训练出来的pb文件转mnn的时候很多算子不支持该怎么处理？

### ISSUE THREAD

**Issue by sinsauzero** [alibaba/MNN#1316]
MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Error for binary op: input0's type != input1's type
Error for binary op: input0's type != input1's type

These Op Not Support: Tensorflow::NonMaxSuppressionV4 | Tensorflow::TensorArrayGatherV3 | Tensorflow::TensorArrayReadV3 | Tensorflow::TensorArrayScatterV3 | Tensorflow::TensorArraySizeV3 | Tensorflow::TensorArrayV3 | Tensorflow::TensorArrayWriteV3

**Comment by lanswen** [comment]
do u solved? i have the same problem

**Comment by sinsauzero** [comment]
no.....TNT



At 2021-01-04 16:11:32, "lanswen" <notifications@github.com> wrote:

do u solved? i have the same problem

**Comment by jxt1234** [comment]
1.1.5 has support it.
