### ISSUE TITLE
LSTM 对于动态图的支持情况

### ISSUE THREAD

**Issue by wangjunxiancn** [alibaba/MNN#1318]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Ubuntu 18.04 Intel

# Github版本:

b0dbe49776772d3cba95402a2c9f2f5d9216f6b7

# 编译方式:
cmake ..

-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/wjxcn/Work/code/ML/DL/mnn/build
-- x86_64: Open SSE
-- Onnx: /home/wjxcn/Work/code/ML/DL/mnn/build/tools/converter/onnx.pb.h;/home/wjxcn/Work/code/ML/DL/mnn/build/tools/converter/onnx-operators.pb.h
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wjxcn/Work/code/ML/DL/mnn/build

# 编译日志:
# Build Log:
gcc 用的是 4.9.1 除了如下 Warning 没有发现其他错误

[ 84%] Built target dataTransformer.out
/home/wjxcn/Work/code/ML/DL/mnn/express/Expr.cpp: In static member function ‘static void MNN::Express::Variable::save(const std::vector<MNN::Express::VARP>&, MNN::NetT*)’:
/home/wjxcn/Work/code/ML/DL/mnn/express/Expr.cpp:775:6: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 void Variable::save(const std::vector<VARP>& vars, NetT* dest) {
      ^~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/c++/7/cstdio:42,
                 from /usr/include/c++/7/ext/string_conversions.h:43,
                 from /usr/include/c++/7/bits/basic_string.h:6361,
                 from /usr/include/c++/7/string:52,
                 from /usr/include/c++/7/stdexcept:39,
                 from /usr/include/c++/7/array:39,
                 from /usr/include/c++/7/tuple:39,
                 from /usr/include/c++/7/functional:54,
                 from /home/wjxcn/Work/code/ML/DL/mnn/include/MNN/expr/Expr.hpp:12,
                 from /home/wjxcn/Work/code/ML/DL/mnn/express/Expr.cpp:10:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 2 and 11 bytes into a destination of size 10
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
[ 84%] Built target MNNConverterCaffe
[ 84%] Linking CXX shared library libMNN_Express.so
[ 84%] Built target MNN_Express
[ 84%] Building CXX object CMakeFiles/classficationTopkEval.out.dir/tools/evaluation/classficationTopkEval.cpp.o
[ 84%] Building CXX object CMakeFiles/checkInvalidValue.out.dir/tools/cpp/checkInvalidValue.cpp.o
[ 85%] Building CXX object CMakeFiles/rasterDemo.out.dir/demo/exec/rasterDemo.cpp.o
[ 86%] Building CXX object CMakeFiles/testModel.out.dir/tools/cpp/testModel.cpp.o
[ 86%] Building CXX object CMakeFiles/timeProfile.out.dir/tools/cpp/timeProfile.cpp.o
[ 86%] Building CXX object CMakeFiles/getPerformance.out.dir/tools/cpp/getPerformance.cpp.o
[ 87%] Building CXX object CMakeFiles/backendTest.out.dir/tools/cpp/backendTest.cpp.o
/home/wjxcn/Work/code/ML/DL/mnn/tools/cpp/getPerformance.cpp: In function ‘void getFreqKhz(int, std::vector<int>&)’:
/home/wjxcn/Work/code/ML/DL/mnn/tools/cpp/getPerformance.cpp:71:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(fp, "%d", &freqKhz);
         ~~~~~~^~~~~~~~~~~~~~~~~~~~
/home/wjxcn/Work/code/ML/DL/mnn/tools/cpp/getPerformance.cpp:84:15: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(fp, "%d", &freqKhz);
         ~~~~~~^~~~~~~~~~~~~~~~~~~~

我这里想问得是我使用最简单pytorch 1.7 的两层 LSTM，2 features， 64 hidden， 2 layers.
pytorch 输出到 onnx  ，静态动态各一个 onnx，batchsize 1，time step 13, 再转为 mnn，使用 netron 看静态动态的模型，input/output 的 time step都 13，而 dynamic 的 time step 是 0 ，input dims [1,0,2], ouput [1,0,2] 使用 debug 版本的 libMNN 在 createSession 时 会出错， call stack 如下：

libc.so.6!__printf(const char * format) (/build/glibc-OTsEL5/glibc-2.27/stdio-common/printf.c:33)
libMNN.so!MNN::CPUBackend::allocBuffer(MNN::CPUBackend * const this, int size, MNN::Tensor * dest, MNN::Backend::StorageType storageType) (/home/wjxcn/Work/code/ML/DL/mnn/source/backend/cpu/CPUBackend.cpp:162)
libMNN.so!MNN::CPUBackend::onAcquireBuffer(MNN::CPUBackend * const this, const MNN::Tensor * nativeTensorConst, MNN::Backend::StorageType storageType) (/home/wjxcn/Work/code/ML/DL/mnn/source/backend/cpu/CPUBackend.cpp:209)
libMNN.so!MNN::Pipeline::<lambda(const std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> >&)>::operator()(const std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > &) const(const MNN::Pipeline::<lambda(const std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> >&)> * const __closure, const std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > & tensors) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Pipeline.cpp:219)
libMNN.so!MNN::Pipeline::allocMemory(MNN::Pipeline * const this, bool supportDebug) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Pipeline.cpp:229)
libMNN.so!MNN::Session::resize(MNN::Session * const this, bool isStatic) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Session.cpp:136)
libMNN.so!MNN::Interpreter::createMultiPathSession(MNN::Interpreter * const this, const std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > & configs, const MNN::RuntimeInfo & runtime) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Interpreter.cpp:199)
libMNN.so!MNN::Interpreter::createMultiPathSession(MNN::Interpreter * const this, const std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > & configs) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Interpreter.cpp:170)
libMNN.so!MNN::Interpreter::createSession(MNN::Interpreter * const this, const MNN::ScheduleConfig & config) (/home/wjxcn/Work/code/ML/DL/mnn/source/core/Interpreter.cpp:245)
main() (/home/wjxcn/Work/code/ML/DL/mnn_lstm_sample2/LSTM-MNN/main.cpp:41)

error message:

Error for /home/wjxcn/Work/code/ML/DL/mnn/source/backend/cpu/CPUBackend.cpp, 162
mynet: /home/wjxcn/Work/code/ML/DL/mnn/source/backend/cpu/CPUBackend.cpp:162: bool MNN::CPUBackend::allocBuffer(int, MNN::Tensor*, MNN::Backend::StorageType): Assertion `res' failed.

也就是

bool CPUBackend::allocBuffer(int size, Tensor* dest, StorageType storageType) {
    // MNN_PRINT("Acquire size = %d\n", size);
    if (size <= 0) {
        MNN_ASSERT(false);
        return false;
    }
...
}

因为是动态的原因， size  传入为 0。

lstm 如何支持动态图呢？

多谢！

**Comment by jxt1234** [comment]
size = 0 应该是不支持的并且不会跑的吧，相关模型代码可以发一下?

**Comment by wangjunxiancn** [comment]
> 
> 
> size = 0 应该是不支持的并且不会跑的吧，相关模型代码可以发一下?

[lstm_convex_hull_dyn_exp_test.zip](https://github.com/alibaba/MNN/files/5805944/lstm_convex_hull_dyn_exp_test.zip)

附件里是 onnx，用 ./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz 转换为 mnn。

**Comment by jxt1234** [comment]
测试运行没有问题

#!/usr/bin/python
import os
import sys
import onnx
import onnxruntime as ort
import numpy as np

# a class to get idom for graph
class IDominate:
    def __init__(self, n):
        self.N = n+1
        self.E = 0
        self.dfs_id = 0
        self.__data__ = [[0 for i in range(self.N)] for i in range(7)]
        for i in range(2):
            self.__data__.append([0 for i in range(self.N*10)])
        for i in range(3):
            self.__data__.append([i for i in range(self.N)])
        self.forward = self.__data__[0]
        self.backward = self.__data__[1]
        self.dfn = self.__data__[2]
        self.id = self.__data__[3]
        self.father = self.__data__[4]
        self.dom = self.__data__[5]
        self.idom = self.__data__[6]
        self.to = self.__data__[7]
        self.next = self.__data__[8]
        self.union_find = self.__data__[9]
        self.sdom = self.__data__[10]
        self.best = self.__data__[11]

    def __addedge(self, graph, _from, _to):
        self.E += 1
        self.next[self.E] = graph[_from]
        self.to[self.E] = _to
        graph[_from] = self.E
    # using union_find to compress path
    def __push_union_find(self, v):
        if v == self.union_find[v]:
            return v
        y = self.__push_union_find(self.union_find[v])
        if self.dfn[self.sdom[self.best[self.union_find[v]]]] < self.dfn[self.sdom[self.best[v]]]:
            self.best[v] = self.best[self.union_find[v]]
        self.union_find[v] = y
        return y
    # dfs get dfs_id
    def __dfs(self, s):
        self.dfs_id += 1
        self.dfn[s] = self.dfs_id
        self.id[self.dfs_id] = s
        t = self.forward[s]
        while t:
            if not self.dfn[self.to[t]]:
                self.__dfs(self.to[t])
                self.father[self.to[t]] = s
            t = self.next[t]
    # Lengauer-Tarjan Algorithm: A fast algorithm for finding dominators in a flowgraph
    # ref : https://dl.acm.org/doi/10.1145/357062.357071 
    def __tarjan(self):
        for i in range(self.dfs_id, 1, -1):
            u = self.id[i]
            j = self.backward[u]
            while j:
                if not self.dfn[self.to[j]]:
                    j = self.next[j]
                    continue
                self.__push_union_find(self.to[j])
                if self.dfn[self.sdom[self.best[self.to[j]]]] < self.dfn[self.sdom[u]]:
                    self.sdom[u] = self.sdom[self.best[self.to[j]]]
                j = self.next[j]
            self.__addedge(self.dom, self.sdom[u], u)
            self.union_find[u] = self.father[u]
            u = self.id[i-1]
            j = self.dom[u]
            while j:
                self.__push_union_find(self.to[j])
                if self.sdom[self.best[self.to[j]]] == u:
                    self.idom[self.to[j]] = u
                else:
                    self.idom[self.to[j]] = self.best[self.to[j]]
                j = self.next[j]
        for i in range(2, self.dfs_id+1):
            u = self.id[i]
            if self.idom[u] != self.sdom[u]:
                self.idom[u] = self.idom[self.idom[u]]
    def addEdge(self, _from, _to):
        self.__addedge(self.forward, _from, _to)
        self.__addedge(self.backward, _to, _from)
    def getIDoms(self):
        self.__dfs(1)
        self.__tarjan()
        return self.idom

class TestModel():
    def __copy_to_here(self, modelName):
        newModel = 'onnx/test.onnx'
        print(os.popen("mkdir onnx").read())
        print(os.popen("cp " + modelName + ' ' + newModel).read())
        self.modelName = newModel
        self.model = onnx.load(self.modelName)
        self.outputs = [output.name for output in self.model.graph.output]
    def __init__(self, modelName):
        self.__copy_to_here(modelName)
    def __run_mnn(self):
        result = os.popen("./TestConvertResult Onnx onnx").read()
        print(result)
        return result
    def __run_onnx(self):
        jsonDict = {}
        jsonDict['inputs'] = []
        jsonDict['outputs'] = []
        inputs = {}
        print(self.modelName)
        ort_session = ort.InferenceSession(self.modelName)
        for inputVar in ort_session.get_inputs():
            inp = {}
            inp['name'] = inputVar.name
            inp['shape'] = [1, 128, 2]
            inputs[inputVar.name] = np.random.uniform(0.1, 1.2, [1, 128, 2]).astype(np.float32)
            jsonDict['inputs'].append(inp)
        print([output.name for output in self.model.graph.output])
        for output in self.model.graph.output:
            jsonDict['outputs'].append(output.name)

        import json
        jsonString = json.dumps(jsonDict, indent=4)
        with open('onnx/input.json', 'w') as f:
            f.write(jsonString)

        print('inputs:')
        for key in inputs:
            print(key)
            f = open("onnx/" + key + '.txt', 'w')
            np.savetxt(f, inputs[key].flatten())
            f.close()
        outputs = ort_session.run(None, inputs)
        print('outputs:')
        for i in range(0, len(outputs)):
            outputName = self.model.graph.output[i].name
            name = 'onnx/' + outputName + '.txt'
            print(name, outputs[i].shape)
            f = open(name, 'w')
            np.savetxt(f, outputs[i].flatten())
            f.close()
    def __test_specify_output(self, specify_output_name):
        while len(self.model.graph.output) > 0:
            self.model.graph.output.pop()
        new_output = onnx.helper.ValueInfoProto()
        new_output.name = specify_output_name
        self.model.graph.output.append(new_output)
        onnx.save(self.model, self.modelName)
        res = self.Test()
        is_right = ('TEST_SUCCESS' in res or 'Can\'t find var' in res)
        print('Test Node :', self.output_map[specify_output_name], is_right)
        return is_right
    def __build_graph(self):
        n = len(self.model.graph.node)
        self.nodes = [node.name for node in self.model.graph.node]
        self.nodes.insert(0, '__null__')
        self.output_map = {}
        self.node_map = {}
        self.node_output = {}
        self.node_input = {}
        idom = IDominate(n); idx = 0
        for node in self.model.graph.node:
            idx += 1
            self.node_map[node.name] = idx
            self.node_output[node.name] = []
            self.node_input[node.name] = []
            for output in node.output:
                self.output_map[output] = node.name
                self.node_output[node.name].append(output)
            for input in node.input:
                if self.output_map.__contains__(input):
                    self.node_input[node.name].append(input)
                    idom.addEdge(self.node_map[self.output_map[input]], self.node_map[node.name])
        self.idoms = idom.getIDoms()
        #print(self.idoms)
    def __get_dom_path(self, left_id, right_id):
        path = []
        while left_id != right_id:
            path.insert(0, right_id)
            right_id = self.idoms[right_id]
        path.insert(0, left_id)
        return path
    def __sub_graph(self, last_right_id, first_error_id):
        while last_right_id == self.idoms[first_error_id]:
            right_input = 0
            inputs = self.node_input[self.nodes[first_error_id]]
            for input in inputs:
                if not self.__test_specify_output(input):
                    first_error_id = self.node_map[self.output_map[input]]
                    break
                else:
                    right_input += 1
            if right_input == len(inputs):
                break
        return first_error_id
    def __binary_search(self, left_id, right_id):
        dom_path = self.__get_dom_path(left_id, right_id)
        left = 0; right = len(dom_path) - 1
        while left < right - 1:
            middle = left + (right - left) // 2
            test_node = self.nodes[dom_path[middle]]
            if self.__test_specify_output(self.node_output[test_node][0]):
                left = middle
            else:
                right = middle
        last_right_node = self.nodes[dom_path[left]]
        first_error_node = self.nodes[dom_path[right]]
        last_right_id = self.node_map[last_right_node]
        first_error_id = self.node_map[first_error_node]
        print('Error is between ', last_right_node, ' and ', first_error_node)
        new_first_error_id = -1
        if last_right_id < first_error_id - 1:
            new_first_error_id = self.__sub_graph(last_right_id, first_error_id)
            if self.idoms[new_first_error_id] != last_right_id:
                self.__binary_search(last_right_id, new_first_error_id)
                return
        if new_first_error_id > 0:
            print('### First Error Node is : ', self.nodes[new_first_error_id])
    def Test(self):
        self.__run_onnx()
        res = self.__run_mnn()
        return res
    def Debug(self):
        self.__build_graph()
        left_id = self.node_map[self.nodes[1]]
        right_id = self.node_map[self.output_map[self.outputs[0]]]
        self.__binary_search(left_id, right_id)

if __name__ == '__main__':
    modelName = sys.argv[1]
    debugMode = len(sys.argv) > 2
    print('Debug Mode: ', debugMode)
    t = TestModel(modelName)
    res = t.Test()
    if 'TESTERROR' in res and debugMode:
        t.Debug()
