### ISSUE TITLE
ios

### ISSUE THREAD

**Issue by SSunWuKong** [alibaba/MNN#132]
metal: error: unable to execute command: Segmentation fault: 11
metal: error: clang frontend command failed due to signal (use -v to see invocation)

**Comment by SSunWuKong** [comment]
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	/Users/xiaoi-mac/Downloads/MNN-master/source/backend/metal/MetalDefine.metal:112:14: Generating code for declaration 'MNN::round_divide_by_pot'
metal: error: unable to execute command: Segmentation fault: 11
metal: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 802.3 (metalfe-802.3.15)
Target: air64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/usr/bin
metal: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
metal: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
metal: note: diagnostic msg: /var/folders/45/4ykvfxj13ydc7q94_d90g_tc0000gn/T/MetalTFQuantizedConv2D-95c3f1.metal
metal: note: diagnostic msg: /var/folders/45/4ykvfxj13ydc7q94_d90g_tc0000gn/T/MetalTFQuantizedConv2D-95c3f1.sh
metal: note: diagnostic msg: Crash backtrace is located in
metal: note: diagnostic msg: /Users/xiaoi-mac/Library/Logs/DiagnosticReports/metal_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
metal: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
metal: note: diagnostic msg:

**Comment by jxt1234** [comment]
What's your xcode's version. Update it if possible.
