### ISSUE TITLE
Nearest interpolation got wrong result (tensorflow 2.2.0)

### ISSUE THREAD

**Issue by PigletOS** [alibaba/MNN#1322]
Platform : Python ( MNN 1.1.0)
Tensorflow version : tensorflow-gpu 2.2.0

The code for the model is as follow:
import tensorflow as tf
import tensorflow.keras as keras
x = keras.layers.Input((112,112,3),dtype=tf.float32)
out = tf.image.resize(x, [224, 224], method='nearest')
model = keras.Model(inputs=x,outputs=out)

I uploaded the pb, tflite, mnn models and an image with the test result.

Here is part of the output:
TF output :[[178. 178. 181. 181. 209. 209. 210. 210. 170. 170.]
MNN :           [[178. 178. 178. 181. 181. 209. 209. 210. 210. 170.]

[test.zip](https://github.com/alibaba/MNN/files/5746597/test.zip)

**Comment by bitxsw93** [comment]
i have tested your model provided, it gets correct result.
