### ISSUE TITLE
Support of OpenCL, OpenGL and Vulkan in pymnn

### ISSUE THREAD

**Issue by rose-jinyang** [alibaba/MNN#1323]
Hello
How are you?
Thanks for contributing to this project.
I found that the latest version of pymnn does not support OpenCL, OpenGL and Vulkan.
Could u please fix this issue asap?
Thanks

**Comment by wangzhaode** [comment]
Default support OpenCL.
You can compile python wheel by yourself and with OpenCL/OpenGL/Vulkan.
