### ISSUE TITLE
About add model description 0f Op

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [alibaba/MNN#133]
I want to convert my onnx file to mnn while layer ELU is not support now.So I want to add a description of Op.
Like #49, I want to know  which fbs file to put description in.
![image](https://user-images.githubusercontent.com/30332524/60080891-4fed0280-9763-11e9-999b-01c17c03287e.png)

**Comment by jxt1234** [comment]
Onnx Op turn to CaffeOp.fbs
