### ISSUE TITLE
tensorflow_object_detection_api中的ssd_mobileNet转换有很多算子不支持，如何修改？

### ISSUE THREAD

**Issue by lanswen** [alibaba/MNN#1331]
These Op Not Support: Tensorflow::TensorArrayGatherV3 | Tensorflow::TensorArrayReadV3 | Tensorflow::TensorArrayScatterV3 | Tensorflow::TensorArraySizeV3 | Tensorflow::TensorArrayV3 | Tensorflow::TensorArrayWriteV3

what may i do for this problem?

**Comment by jxt1234** [comment]
Update to 1.1.2 , convert and then use module api (See demo/exec/transformerDemo.cpp)
