### ISSUE TITLE
遍历tensor 数据，崩溃

### ISSUE THREAD

**Issue by idreamerhx** [alibaba/MNN#1332]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:
commit 6e0e9e95cbd430496dd036659486f3e8059a09b3 (HEAD -> master, origin/master, origin/HEAD)

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
export PATH=/opt/protobuf-3.5/bin:$PATH
export LD_LIBRARY_PATH=/opt/protobuf-3.5/lib:$LD_LIBRARY_PATH

cmake \
-DCMAKE_INSTALL_PREFIX=/opt/MNN/inst \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_BUILD_CONVERTER=ON \
-DMNN_BUILD_DEMO=ON \
-DMNN_BUILD_QUANTOOLS=ON \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_TOOLS=ON \
-DMNN_BUILD_TRAIN=ON \
-DMNN_BUILD_SHARED_LIBS=ON \
-DMNN_SEP_BUILD=ON \
-DProtobuf_INCLUDE_DIR=/opt/protobuf-3.5/include \
-DProtobuf_LIBRARY=/opt/protobuf-3.5/lib/libprotobuf.so \
-DMNN_OPENCL=OFF \
-DMNN_OPENGL=OFF \
-DMNN_OPENMP=OFF \
-DMNN_VULKAN=OFF \
-DMNN_DEBUG=ON \
..

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

scheduleConfig.saveTensors.push_back("120"); outputLayerNames.push_back("120"); // TODO test

static void printMNNTensor(const std::string& name, int i, const MNN::Tensor* ten)
{
	std::cout << "MNNTensor[" << i << "] name=" << name << " dim=" << ten->dimensions() << " shape=";
	for (int s : ten->shape())
		std::cout << s << ",";
	std::cout << " size=" << ten->size();
	std::cout << std::endl;
}

	{
		auto aa = MNN::Tensor::createHostTensorFromDevice(outputTensors[2], true);
		printMNNTensor("120", 0, aa);

		std::ofstream fTen("out-120.txt", std::ios::binary);
		float* data = aa->host<float>();
		for (int i = 0; i < aa->size(); i++)
		{
			fTen << data[i];
			if ((i + 1) % 208 == 0)
				fTen << std::endl;
		}
	}

MNNTensor[0] name=120 dim=4 shape=1,32,208,208, size=5537792

崩溃位置在  i=1493824，基本上是随机的。
fTen << data[i];

**Comment by jxt1234** [comment]
size 是 bytes 数（有可能是4倍于实际数组大小），请用 elementSize 获取数组大小进行遍历
