### ISSUE TITLE
Pytorch转ONNX再转MNN后模型结果不对

### ISSUE THREAD

**Issue by bryanlinnan** [alibaba/MNN#1334]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  Ubuntu 16.04

# Github版本:
# Github Version: master version 12.30

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
Cmake
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by bryanlinnan** [comment]
使用的pytorch 1.4训练出来的模型，编译和运行都正常，但是结果和pytorch不一致，请问是模型转换导致的问题吗？MNNConverter我是使用的自己本地编译的

**Comment by jxt1234** [comment]
先用 tools/script/fastTestOnnx.py 测试下在对齐输入输出格式的情况下，mnn 与 onnx  运行结果是否一致

**Comment by bryanlinnan** [comment]
@jxt1234 测试过是OK的，是不是我的mnn测试代码调用方式有问题？
![image](https://user-images.githubusercontent.com/44692637/104152273-0550db00-541a-11eb-8baa-b7365e84400a.png)

**Comment by jxt1234** [comment]
1、你的 buffer 是按什么格式排列的？如果是 RGB Plane 的话应该是建 CAFFE 类型
2、取it->second就行，没有必要再 getSessionOutput
另外，可以把 numberThread 设成 1 试一下，之前有个x86多线程处理的bug(现在已经修复)

**Comment by bryanlinnan** [comment]
@jxt1234 ，修改numtThread为1，it second ,CAFFE的格式输入输出tensor，结果有变化但是还是跟pytorch完全不一致

**Comment by bryanlinnan** [comment]
> 1、你的 buffer 是按什么格式排列的？如果是 RGB Plane 的话应该是建 CAFFE 类型
> 2、取it->second就行，没有必要再 getSessionOutput
> 另外，可以把 numberThread 设成 1 试一下，之前有个x86多线程处理的bug(现在已经修复)

您好，已经按照您的意见修改，但是依旧结果不对，我看了TestConvertResult，调用的似乎是更底层的API运行onnx和mnn，结果是正确的，但是调用外层API（如我上图所示），结果就差异很大了，麻烦研究一下原因并告知

**Comment by the-sword** [comment]
> @jxt1234 ，修改numtThread为1，it second ,CAFFE的格式输入输出tensor，结果有变化但是还是跟pytorch完全不一致

请问你后面有解决吗？我这边也是发现最终的结果跟pytorch完全不一致
