### ISSUE TITLE
关于"OpenCLBackend::copyToDevice"的问题

### ISSUE THREAD

**Issue by Shaquille-Wu** [alibaba/MNN#1335]
小弟最近更新了mnn，现在应该是1.1.1。
发现一个对我比较重要的修改，在OpenCLBackend::copyToDevice的最后，原来是这样的：  
mOpenCLRuntime->commandQueue().enqueueWriteBuffer(*mHostBuffer.second, CL_FALSE, 0, srcTensor->elementSize()*sizeof(float), hostPtr);
也就是说，这个enqueueWrite是一个非阻塞的。
现在改成了这样:
mOpenCLRuntime->commandQueue().enqueueWriteBuffer(*mHostBuffer.second, CL_TRUE, 0, srcTensor->elementSize()*sizeof(float), hostPtr);
也就是说，现在变成了阻塞式的。
copyToDevice，就是把主机端的内存往设备端的现存copy，由于只用于推理之前，用非阻塞的方式更好，避免了不必要的i/o的消耗。
我仔细看了1.1.1的修改，没发现什么地方非要强求这个地方一个阻塞式访问，我不明白MNN为什么要改成阻塞式的，这种I/O消耗，对性能要求很苛刻的场景很不利。或者说，我看得并不全面?请MNN的大神们不吝赐教

**Comment by jxt1234** [comment]
原因是 ImageProcess 的 convert 接口会建一个临时 Tensor 去转换然后拷贝，不阻塞的话会导致部分机型结果错误，后面我们会完善

**Comment by Shaquille-Wu** [comment]
谢谢大佬指点
