### ISSUE TITLE
有channel shuffle 就没办法动态输入？

### ISSUE THREAD

**Issue by GYxiaOH** [alibaba/MNN#1337]
如题
由于channel shuffle里有reshape操作，所以动态输入必然报错Reshape error: 2359296 -> 2457600。。。。
这个问题有方法解决吗

**Comment by jxt1234** [comment]
相关模型发来看一下？可能是中间图优化使用了shape 信息

**Comment by GYxiaOH** [comment]
@jxt1234 就是普通的shufflenet后面跟了一些层，channel shuffle的pytorch实现就是
def channel_shuffle(x, groups):
	batchsize, num_channels, height, width = x.data.size()
	channels_per_group = num_channels // groups
	# reshape
	x = x.view(batchsize, groups, channels_per_group, height, width)
	x = torch.transpose(x, 1, 2).contiguous()
	# flatten
	x = x.view(batchsize, -1, height, width)
	return x
基本可以确定就是这个reshape造成的了。。可是这个reshape没有办法设置为都是非固定的。。
所以MNN有办法onnx转MNN的时候直接把他识别成channel shuffle层然后支持动态输入吗。。

**Comment by jxt1234** [comment]
这个 MNN 应该没有办法，需要按原始模型执行的。。。
这个 channel_shuffle 可以用 shape  op 之类去获取 batchsize, num_channels, height, width 吧，这样可以支持非固定的
