### ISSUE TITLE
onnx 转MNN 时候， 报错 These Op Not Support: ONNX::GRU

### ISSUE THREAD

**Issue by fangxuefei1989** [alibaba/MNN#1339]
在ubuntu 平台， MNN1.1.0 版本， onnx 模型转成成MNN 模型的时候，报错： ./tools/converter/source/common/writeFb.cpp:479: check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX:GRU

请问是就是不支持，还是使用有问题

**Comment by jxt1234** [comment]
最新版已经支持
