### ISSUE TITLE
The format order of output tensor is uncertain

### ISSUE THREAD

**Issue by WenguoLi** [alibaba/MNN#134]
The output tensor of some models is in NC4HW4 format, while the output of others is in NHWC format. How to fix the output format to facilitate post-processing?  Or , is there an API available to obtain the format of the output tensor?
In addition, after model  has been converted, output tensor name can not be explicitly known? Can it be visualized?

Thanks!

**Comment by jxt1234** [comment]
You can create an host tensor as Tensor::Tensorflow (NHWC), and then copyToHostTensor

**Comment by WenguoLi** [comment]
@jxt1234 , Thanks !
https://github.com/alibaba/MNN/blob/master/doc/FAQ.md , more details.
