### ISSUE TITLE
咨询一下bestWinogradUnit的实现原理？

### ISSUE THREAD

**Issue by victorygogogo** [alibaba/MNN#1340]
ConvolutionWinograd::bestWinogradUnit 
/*Let F(6,3) be choosed when it can speed up from F(2,3) than 0.6*/
float penalty = (su * su) / (float)(kernelSize * kernelSize) * 0.12f;
float winogradCost =
            (2 * su * su * ic + su * su * ic * oc + (su + u) * u * oc) * (UP_DIV(ow, u) * UP_DIV(oh, u));
float reduceRate = originCost / winogradCost - penalty;

0.12是怎么来的呢？请解惑一下

**Comment by jxt1234** [comment]
由于 unit size 增大时，会增加 kernel 的矩阵乘大小，多占用内存，0.12 是设置的一个惩罚项，是之前为了让 squeezenet v1.1 不使用 F(6, 3) 而写的，后面可能会更正
