### ISSUE TITLE
使用量化工具后，weight和bias全为0，无法正常预测

### ISSUE THREAD

**Issue by Xthkeer** [alibaba/MNN#1341]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Linux
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version: 
a9976c93c58afa9abe974d6b0fc9160a7bc7f0c3

使用MNN提供的MNIST的demo训练出来的模型做量化
json文件如下
{
    "format":"GRAY",
    "mean":[
        0,
        0,
        0
    ],
    "width":28,
    "height":28,
    "path":"./mnist/mnist_data/quant_img/",
    "used_image_num":1000,
    "feature_clamp_value":127,
    "weight_clamp_value":127,
    "feature_quantize_method":"ADMM",
    "weight_quantize_method":"ADMM",
    "debug":true
}                                                                                              

debug日志如下：
Debug info:

Pooling4 input_tensor_0:  cos distance: 0.092226, overflow ratio: 0.000000
Pooling4 output_tensor_0:  cos distance: 0.123466, overflow ratio: 0.000000
Pooling7 input_tensor_0:  cos distance: 0.193926, overflow ratio: 0.019231
Pooling7 output_tensor_0:  cos distance: 0.253579, overflow ratio: 0.000000
conv1 input_tensor_0:  cos distance: 0.999999, overflow ratio: 0.019602
conv1 output_tensor_0:  cos distance: -0.241742, overflow ratio: 0.050000
conv2 output_tensor_0:  cos distance: -0.222858, overflow ratio: 0.000000
[04:05:31] /MNN/tools/quantization/quantizeWeight.cpp:100: iter: 1000 with diff 0
[04:05:32] /MNN/tools/quantization/quantizeWeight.cpp:100: iter: 1000 with diff 0

[04:05:32] /MNN/tools/quantization/quantized.cpp:55: Quantize model done!

使用MNNDump2Json发现两层卷积层weights和bias均为0

**Comment by Xthkeer** [comment]
3c4906a7 改的可能有问题，下面代码中的abs对float的结果都为0，应改为fabs或std::abs
`    auto findAbsMax = [&] (const float* weights, const int size) {
        float absMax = 0;
        for (int i = 0; i < size; i++) {
            if (abs(weights[i]) > absMax) {
                absMax = abs(weights[i]);
            }
        }

        return absMax;
    };
`

**Comment by yyfcc17** [comment]
好的，多谢指出
