### ISSUE TITLE
Windows平台下的VULKAN编译和TensorRT编译

### ISSUE THREAD

**Issue by janicevidal** [alibaba/MNN#1342]
上面编译都会报错，请问有在win平台上进行编译测试么

**Comment by jxt1234** [comment]
具体报什么错？

**Comment by jxt1234** [comment]
之前是有在 Windows 上编译过 Vulkan 的

**Comment by janicevidal** [comment]
> 之前是有在 Windows 上编译过 Vulkan 的

我用MSVC编的，用Mingw编译生成的.a文件不会用，vs下因为Vulkan依赖linux某些的特定的头文件，MSVC下编不过，但是想直接生成.dll文件，有什么好的方式么

**Comment by jxt1234** [comment]
开 -DMNN_USE_SYSTEM_LIB=true 了么?
