### ISSUE TITLE
图像分割模型cuda后端计算结果错误，cpu后端计算结果正常

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#1344]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 16.04 x86_64 4.15.0-39-generic

# Github版本: 
# Github Version:
MNN-1.1.2

# 问题描述如下：
1.tensorflow模型转换mnn模型没有报错 可以正常转换
2.cpu后端计算结果正常
3.切换cuda后端计算 结果错误。 input_tensor和output_tensor无论是使用tensorflow格式还是caffe格式cuda后端计算的结果都不对。

原始的pb模型：https://www.dropbox.com/s/a3htr6giryi99zw/road_seg.pb?dl=0
转换后的mnn模型: https://www.dropbox.com/s/4335mi0v1w72a9h/road_seg.mnn?dl=0
简单的测试cpp文件: https://www.dropbox.com/s/x4ry6gwy2b2hfkf/road_seg_test.cpp?dl=0
测试输入图像：https://www.dropbox.com/s/p3qss7ngom3wf4p/input_image.jpg?dl=0
预期正确的结果图:https://www.dropbox.com/s/f2ceichyq6wibex/result.png?dl=0

**Comment by jxt1234** [comment]
最新代码修正

**Comment by MaybeShewill-CV** [comment]
@jxt1234 大佬 1.1.4 release版本也修正这个问题了吗?

**Comment by jxt1234** [comment]
需要到最新的 1.1.5
