### ISSUE TITLE
lprnet模型从onnx转mnn没有问题，加载模型报错： Error for compute convolution shape, need channel = 64, input channel = 128  Compute Shape Error for 77

### ISSUE THREAD

**Issue by southsea0725** [alibaba/MNN#1345]
pytorch上测试OK，导出onnx模型，使用最新版MNN转mnn，转换无报错，加载报错，如题。
![图片](https://user-images.githubusercontent.com/19204359/104889783-a48d4980-59a9-11eb-9793-5ac6680c92ef.png)

**Comment by southsea0725** [comment]
[lprnet.zip](https://github.com/alibaba/MNN/files/5832928/lprnet.zip)

**Comment by jxt1234** [comment]
有原始 onnx 模型么？

**Comment by southsea0725** [comment]
有的：
[lprnet--ONNX.zip](https://github.com/alibaba/MNN/files/6053535/lprnet--ONNX.zip)

**Comment by ZZcooller** [comment]
您好，请问这个问题解决了么？遇到了同样的问题

**Comment by southsea0725** [comment]
没有解决，期待mnn的技术支持解决一哈。

**Comment by jxt1234** [comment]
使用 onnxruntime 报错，建议检查下 onnx 模型本身
  File "/usr/local/lib/python3.8/site-packages/onnxruntime/capi/session.py", line 200, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from onnx/test.onnx failed:Node (MaxPool_3) Op (MaxPool) [Sh
