### ISSUE TITLE
nlp模型

### ISSUE THREAD

**Issue by wjxdp** [alibaba/MNN#1348]
支持的
有相关模型已经上线使用

_Originally posted by @czy2014hust in https://github.com/alibaba/MNN/issues/518#issuecomment-564523098_

**Comment by wjxdp** [comment]
你好，想请问一下有相关的nlp模型的训练demo吗，目前看代码不太清楚embedding_lookup，lstm以及rnn的使用，能帮忙给点指导意见吗 ，谢谢@czy2014hust

**Comment by jxt1234** [comment]
目前应该不支持 nlp 模型的训练，可以把 tf / pytorch 训练的 nlp 模型转成 mnn 运行
