### ISSUE TITLE
mnn ubuntu平台开启多线程后运行时间没有提升

### ISSUE THREAD

**Issue by fangxuefei1989** [alibaba/MNN#1349]
平台：ubuntu 平台

createSession时将numThread 设置为4时，观察了一下4个线程中只有一个在跑，其他3个CPU 占用率为0；导致线程设置为4和设置为1时，运行时间相同
配置是默认的配置

<img width="991" alt="CPU" src="https://user-images.githubusercontent.com/26226817/104995943-027d6800-5a62-11eb-8c9b-37baaac75056.png">

**Comment by jxt1234** [comment]
和模型有关系吧，有可能是模型中的算子都不支持并行？

**Comment by jxt1234** [comment]
可参考 https://www.yuque.com/mnn/cn/create_session 里面，有可能建了多个 session / runtime ，线程池使用量超过 2 个了
