### ISSUE TITLE
Compile error “MNN_generated.h”: No such file or directory  on windows 10 + VS2017

### ISSUE THREAD

**Issue by nulli9** [alibaba/MNN#135]
Hi, 
I followed the windows installing instructions  and got the error “MNN_generated.h”: No such file or directory after 'nmake' command.
Thank you

**Comment by paulpanwang** [comment]
Hi ~
'MNN_generated.h' file not found on mac

**Comment by li-qing** [comment]
any error output for nmake ?

**Comment by Linchunhui** [comment]
I got the same problem.

**Comment by Ewenwan** [comment]
me too

**Comment by li-qing** [comment]
any error output for nmake ? @Linchunhui @Ewenwan

**Comment by Ewenwan** [comment]
bata 0.2.0.3 
https://github.com/alibaba/MNN/blob/a367406308541d54b6cbd5e19db063db6240c506/schema/default/MNN.fbs#L129

  PLUGIN = 256 //The Type load from plugin
>>>
 PLUGIN = 256, //The Type load from plugin

**Comment by li-qing** [comment]
> bata 0.2.0.3
> https://github.com/alibaba/MNN/blob/a367406308541d54b6cbd5e19db063db6240c506/schema/default/MNN.fbs#L129
> 
> PLUGIN = 256 //The Type load from plugin
> 
> > > >
> 
> PLUGIN = 256, //The Type load from plugin

fixed check out 0.2.0.4 plz

**Comment by wuxiaolianggit** [comment]
do you solve the problem? @ @ @nulli9

**Comment by xingyanan** [comment]
use poweshell run schema/generate.ps1 ,then u will have MNN_generated.h

**Comment by xiakj** [comment]
@xingyanan 运行generage.ps1，都done了，也没有找到MNN_generated.h

**Comment by Sudo-VP** [comment]
./schema/generate.sh
