### ISSUE TITLE
安卓-DANDROID_STL=gnustl_static时链接失败

### ISSUE THREAD

**Issue by lcings** [alibaba/MNN#1350]
复现条件(build.gradle)：
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=gnustl_static"
                abiFilters  'arm64-v8a', 'armeabi-v7a'
            }
        }
编译打印：
undefined reference to `MNN::Interpreter::resizeTensor(MNN::Tensor*, std::vector<int, std::allocator<int> > const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

不调用resizeTensor接口则可以链接通过。

**Comment by jxt1234** [comment]
编译 mnn 的时候也用  gnustl_static 即可
