### ISSUE TITLE
麻烦帮忙看看模型

### ISSUE THREAD

**Issue by FlowEternal** [alibaba/MNN#1351]
在MNNconverter转换原始test.ONNX模型时候没有任何问题,转换得到test.mnn
但是在用如下python接口调用模型时候出现以下问题：
    interpreter = MNN.Interpreter("test.mnn")
    session = interpreter.createSession()

console打印出来如下
Don't support type [AbsVal],  Process finished with exit code -1073741819 (0xC0000005)

如果直接用c++ API 调用模型，得到如下错误
![image](https://user-images.githubusercontent.com/41542584/105006903-3bbdd400-5a72-11eb-884d-4b499240f5fe.png)

希望能得到解答

[test.zip](https://github.com/alibaba/MNN/files/5834479/test.zip)

**Comment by jxt1234** [comment]
呃，这模型转出来有多余的0值，更新一下试试吧
