### ISSUE TITLE
Android量化后的模型变慢几倍

### ISSUE THREAD

**Issue by int2num** [alibaba/MNN#1354]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
编译机：ubuntu18.04，测试安卓机：小米10pro
# Github版本:
1.1.0
# 问题:
使用benchmark andriod测试量化后int8的模型比量化前模型慢很多：
Hardware	: Qualcomm Technologies, Inc SM8250

Build Flags: ABI=armeabi-v7a OpenMP=ON Vulkan=ON OpenCL=ON
MNN benchmark
Forward type: **CPU** thread=4** precision=2
--------> Benchmarking... loop = 10, warmup = 5
[ - ] quan_draw.mnn               max =  111.443ms  min =   98.545ms  avg =  100.173ms
[ - ] draw.mnn                    max =   73.968ms  min =   70.713ms  avg =   71.498ms
MNN benchmark
Forward type: **Vulkan** thread=4** precision=2
--------> Benchmarking... loop = 10, warmup = 5
[ - ] quan_draw.mnn               max =  350.249ms  min =  335.487ms  avg =  341.836ms
[ - ] draw.mnn                    max =  155.355ms  min =  149.245ms  avg =  151.506ms
MNN benchmark
Forward type: **OpenCL** thread=4** precision=2
--------> Benchmarking... loop = 10, warmup = 5
[ - ] quan_draw.mnn               max = 3110.237ms  min = 3085.204ms  avg = 3096.379ms
[ - ] draw.mnn                    max =   35.348ms  min =   31.997ms  avg =   33.414ms

看到一些类似的问题：#438 说是指令vmlal.s8 的吞吐量没有 vmla.f32 这条指令大
不知道是不是一个原因,如果是的话，这个问题可以优化一下吗？
这是量化后的模型：
![reliao_img_1611062894636](https://user-images.githubusercontent.com/15179412/105040848-4e013780-5a9d-11eb-8355-06b3846a79ae.png)

**Comment by jxt1234** [comment]
可以用 ARMv8 并打开 MNN_ARM82 ，这样开启 sdot 可以快2-3 倍
