### ISSUE TITLE
mnn框架可以转换temporal shift module的pretrain模型吗

### ISSUE THREAD

**Issue by dandingol03** [alibaba/MNN#1355]

**Comment by jxt1234** [comment]
这个是指? 可以详细描述一下或者发个链接？

**Comment by xiaomingnio** [comment]
https://github.com/mit-han-lab/temporal-shift-module

**Comment by wangzhaode** [comment]
> https://github.com/mit-han-lab/temporal-shift-module

需要您自己转换到ONNX/TorchScript/PB等模型，然后尝试用MNNConvert转换
