### ISSUE TITLE
pooling 层量化问题

### ISSUE THREAD

**Issue by yisongsong** [alibaba/MNN#1356]
MNN  源码中已经有 CPUPoolInt8 的实现，但是 quantize.out tool  里面没有加入对 pooling 层的支持，请问：
1. 这是什么原因呢？
2. 是因为精度吗？如果是，比如哪些模型精度降低呢？
3. Pooling 层没有做 rescale， input scale 和 output scale 是一样吗？

**Comment by wangzhaode** [comment]
PoolingInt8实现不完善，正在开发中；
