### ISSUE TITLE
模型转化过程内存占用过大报错 Assertion `size() < FLATBUFFERS_MAX_BUFFER_SIZE' failed

### ISSUE THREAD

**Issue by LiChao-cy** [alibaba/MNN#1360]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Linux

# 模型转化方法:
./MNNConvert -f TF --modelFile xxx.pb --MNNModel xxx.mnn --bizCode biz

# 报错日志:
MNNConvert: MNN/3rd_party/flatbuffers/include/flatbuffers/flatbuffers.h:732: size_t flatbuffers::vector_downward::ensure_space(size_t): Assertion `size() < FLATBUFFERS_MAX_BUFFER_SIZE' failed.
Aborted (core dumped)

# 模型说明:
1.转化的失败的模型是albert_xlarge；
2.尝试过转化bert_base模型，没有问题；
3.albert_xlarge虽然层数较多，但是所有层都是参数共享，难道是MNN在转换模型时，把每层的参数都重复写入，所以占用内存大然后报错吗？

**Comment by wangzhaode** [comment]
2.3.0版本支持权重分离的方式；可以使用`--saveExternalData`选项；
