### ISSUE TITLE
class MNN::Backend’ has no member named ‘onWaitFinish

### ISSUE THREAD

**Issue by smartadpole** [alibaba/MNN#1363]
# Platform(Include target platform as well if cross-compiling):  ubuntu 18
# Github Version: 1.1.0

error:   
```
‘class MNN::Backend’ has no member named ‘onWaitFinish’
     const_cast<MNN::Backend*>(backend)->onWaitFinish();

```

**Comment by jxt1234** [comment]
The function has been remove. Please use copyToHostTensor / copyFromHostTensor instead. Don't need wait backend
