### ISSUE TITLE
Raster 耗时过长，onnx -> mnn

### ISSUE THREAD

**Issue by menchunlei** [alibaba/MNN#1367]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android  arm64-v8a

# Github版本:
# Github Version:
1.1.2

各位大佬，

mobilenetV3 由pytorch 转 onnx 转 mnn，timeProfile.out,  发现Raster耗时占比太大了。
从graph看，convoluation都会有一个，这样正常吗？
如果Raster只是进行NCHW转NC4HW4，那么只需要在input进行一次就可以了。convoluation按照NC4HW4输出。
耗时统计：
Sort by time cost !
Node Type            	Avg(ms)   	%         	Called times 	Flops Rate 	
UnaryOp              	0.027760  	0.080438  	14.000000    	0.000568   	
Softmax              	0.335160  	0.971161  	4.000000     	0.039594   	
ReLU6                	0.371639  	1.076862  	28.000000    	0.313040   	
Reduction            	0.632573  	1.832946  	44.000000    	0.008987   	
Interp               	0.692939  	2.007864  	9.000000     	1.962816   	
Eltwise              	1.431151  	4.146908  	66.000000    	0.831803   	
BinaryOp             	2.026295  	5.871399  	91.000000    	1.073291   	
ConvolutionDepthwise 	2.222929  	6.441167  	20.000000    	5.128068   	
MatMul               	3.144130  	9.110441  	6.000000     	18.523478  	
Sigmoid              	3.796974  	11.002125 	21.000000    	0.282375   	
Raster               	6.249197  	18.107697 	205.000000   	2.301022   	
Convolution          	13.584640 	39.362900 	78.000000    	69.537201
total time : 34.511276 ms, total mflops : 761.670654 
main, 113, cost time: 3480.977051 ms

**Comment by jxt1234** [comment]
这个主要原因是 mobilenet v3 的 hard_swish 拆解的细粒度op 会触发多次形变，目前还没有比较好的解决方式

**Comment by jxt1234** [comment]
1.1.6 已经添加了 hard_swish 的图优化，更新后就会降低了
