### ISSUE TITLE
Raster可以用来实现哪些Op ？

### ISSUE THREAD

**Issue by yonvor** [alibaba/MNN#1368]
从1.1.1版本开始各后端都有Raster，请问Raster主要用来实现哪些Op？

**Comment by jxt1234** [comment]
所有形变算子

**Comment by yonvor** [comment]
您好，能列举以下具体是哪些吗？所有的reshape，reduce，shuffel都支持吗？







在 2021-02-21 10:05:19，"jxt1234" ***@***.***> 写道：

所有形变算子
