### ISSUE TITLE
MNN量化upsample算子不支持？

### ISSUE THREAD

**Issue by dongda118** [alibaba/MNN#1369]
我的模型中有upsample操作，量化后速度并没变快多少，发现量化后，Interp操作前先将int8转float，再做Interp，再将float转Int8，也就是说Interp还是在float层面上做的，所以arm端测试并没有提速多少，请问阿里大神，这样的情况如何解决？

**Comment by gengwb** [comment]
> 我的模型中有upsample操作，量化后速度并没变快多少，发现量化后，Interp操作前先将int8转float，再做Interp，再将float转Int8，也就是说Interp还是在float层面上做的，所以arm端测试并没有提速多少，请问阿里大神，这样的情况如何解决？

请问一下，你的upsample层是怎么转换过去的呢，MNN好像还没支持这个层，我这边caffemodel里面有这个层一直转换失败，要自己添加对应的算子

**Comment by wangzhaode** [comment]
是不支持的
