### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by xinsuinizhuan** [alibaba/MNN#1372]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
windows 下面，使用cmake，然后选择MinGW makefiles，选择Qt安装目录下面的gcc和g++，进行编译
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
Use Threadpool, forbid openmp
>>>>>>>>>>>>>
MNN BUILD INFO:
	System: Windows
	Processor: AMD64
	Metal: OFF
	OpenCL: OFF
	OpenGL: OFF
	Vulkan: OFF
	ARM82: OFF
	oneDNN: OFF
	TensorRT: OFF
	CUDA: OFF
	OpenMP: OFF
	ThreadPool: ON
	Hidden: TRUE
	Build Path: I:/MNN/MNN_mingw/build
AMD64: Open SSE
Configuring done
# 编译日志:
# Build Log:
![图片](https://user-images.githubusercontent.com/40679769/106995328-9ddc4000-67b9-11eb-8602-b6d0dea48bfe.png)

```
粘贴在这里
Paste log here or pastebin
```
Microsoft Windows [版本 10.0.17134.1902]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Windows\system32>cd /d I:\MNN\MNN_mingw\build

I:\MNN\MNN_mingw\build>mingw32-make.exe
Scanning dependencies of target MNNCore
[  0%] Building CXX object CMakeFiles/MNNCore.dir/source/core/AutoTime.cpp.obj
[  1%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Backend.cpp.obj
[  1%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BackendRegister.cpp.obj
[  1%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BufferAllocator.cpp.obj
[  2%] Building CXX object CMakeFiles/MNNCore.dir/source/core/ConvolutionCommon.cpp.obj
[  2%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Execution.cpp.obj
[  2%] Building CXX object CMakeFiles/MNNCore.dir/source/core/FileLoader.cpp.obj
[  3%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Interpreter.cpp.obj
[  3%] Building CXX object CMakeFiles/MNNCore.dir/source/core/MNNMemoryUtils.cpp.obj
[  3%] Building CXX object CMakeFiles/MNNCore.dir/source/core/OpCommonUtils.cpp.obj
[  4%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Pipeline.cpp.obj
[  4%] Building CXX object CMakeFiles/MNNCore.dir/source/core/RuntimeFactory.cpp.obj
[  4%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Schedule.cpp.obj
[  5%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Session.cpp.obj
[  5%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Tensor.cpp.obj
[  5%] Building CXX object CMakeFiles/MNNCore.dir/source/core/TensorUtils.cpp.obj
[  6%] Building CXX object CMakeFiles/MNNCore.dir/source/core/WrapExecution.cpp.obj
[  6%] Built target MNNCore
Scanning dependencies of target MNNCV
[  6%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageBlitter.cpp.obj
[  7%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.obj
[  7%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.obj
[  7%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageSampler.cpp.obj
[  8%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/Matrix_CV.cpp.obj
[  8%] Built target MNNCV
Scanning dependencies of target MNNAVX
[  9%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/CommonOptFunction.cpp.obj
[  9%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/GemmAVX2.cpp.obj
[  9%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/GemmAVX2FMA.cpp.obj
[ 10%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/GemmCommon.cpp.obj
[ 10%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp.obj
[ 10%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNMatrixAdd.cpp.obj
[ 11%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNMatrixSub.cpp.obj
[ 11%] Building ASM object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/_AVX_MNNGemmFloatUnitMainFMA.S.obj
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S: Assembler messages:
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:18: Error: bad register name `%rbp'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:19: Error: bad register name `%rsp'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:22: Error: bad register name `%rsp)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:23: Error: bad register name `%rdi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:24: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:25: Error: bad register name `%r12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:26: Error: bad register name `%r13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:27: Error: bad register name `%rcx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:28: Error: bad register name `%rdx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:29: Error: bad register name `%r8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:30: Error: bad register name `%r9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:31: Error: bad register name `%r10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:38: Error: bad register name `%rcx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:39: Error: bad register name `%rcx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:40: Error: bad register name `%rcx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:46: Error: bad register name `%r9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:49: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:52: Error: bad register name `%rcx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:53: Error: bad register name `%r13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:55: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:59: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:60: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:61: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:63: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:65: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:69: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:71: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:72: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:73: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:75: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:76: Error: bad register name `%ymm10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:77: Error: bad register name `%ymm11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:78: Error: bad register name `%ymm12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:79: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:80: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:81: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:82: Error: bad register name `%rdx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:83: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:84: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:86: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:87: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:89: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:94: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:96: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:97: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:99: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:100: Error: bad register name `%ymm10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:101: Error: bad register name `%ymm11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:102: Error: bad register name `%ymm12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:103: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:104: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:105: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:106: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:107: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:108: Error: bad register name `%rdx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:109: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:111: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:112: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:115: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:119: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:120: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:121: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:123: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:128: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:130: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:131: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:133: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:134: Error: bad register name `%ymm10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:135: Error: bad register name `%ymm11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:136: Error: bad register name `%ymm12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:137: Error: bad register name `%rdx)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:138: Error: bad register name `%rsi)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:139: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:140: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:141: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:142: Error: bad register name `%rdx'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:143: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:144: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:171: Error: bad register name `%rdi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%ymm13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:173: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:175: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%ymm14'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:177: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:179: Error: bad register name `%r11'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%ymm15'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:180: Error: bad register name `%r11)'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:183: Error: bad register name `%r8'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:184: Error: bad register name `%r10'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:186: Error: bad register name `%r9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:187: Error: bad register name `%r9'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:194: Error: bad register name `%r13'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:195: Error: bad register name `%r12'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:196: Error: bad register name `%rsi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:197: Error: bad register name `%rdi'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:198: Error: bad register name `%rbp'
I:\MNN\MNN_mingw\source\backend\cpu\x86_x64\avx\_AVX_MNNGemmFloatUnitMainFMA.S:205: Error: unsupported instruction `ret'
mingw32-make.exe[2]: *** [CMakeFiles\MNNAVX.dir\build.make:180: CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/_AVX_MNNGemmFloatUnitMainFMA.S.obj] Error 1

**Comment by jxt1234** [comment]
先把 source/backend/cpu/x86_x64/CMakeLists.txt 里面的 -DMNN_X86_USE_ASM 去掉吧

**Comment by xinsuinizhuan** [comment]
> 
> 
> 先把 source/backend/cpu/x86_x64/CMakeLists.txt 里面的 -DMNN_X86_USE_ASM 去掉吧
ASM只有这一处：
https://github.com/alibaba/MNN/issues/1372#issuecomment-780423505
