### ISSUE TITLE
模型转换问题：通过--saveStaticModel转为静态模型时的配置文件问题

### ISSUE THREAD

**Issue by a-paw-fish** [alibaba/MNN#1378]
保存静态模型所需要的配置文件, ex: ~/config.txt的格式是怎样的？

**Comment by jxt1234** [comment]
是输入尺寸信息，如果模型中有默认输入尺寸就不需要

**Comment by jxt1234** [comment]
MNN_MINI 还在完善，发布 1.2 的时候会详细说明使用方法

**Comment by jxt1234** [comment]
config.txt demo:

# 多个输入用,分开，不要用空格
# 目前默认输入都是float
# 文件名为输入tensor的名字后缀为txt
# 模型默认名字为：temp.bin
input_size = 1
input_names = ImageTensor
input_dims = 1x3x320x180

**Comment by a-paw-fish** [comment]
好的，谢谢哈~
