### ISSUE TITLE
crash happened when run android demo in v 0.2.0.0

### ISSUE THREAD

**Issue by alexwangfm** [alibaba/MNN#138]
Crash happened when start android demo

mnn version v 0.2.0.0

crash message: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 21631 (MNNNet), pid 21612 (android.mnndemo)

**Comment by jxt1234** [comment]
Will be fixed soon. Currently you can turn ndk to ndk-17 and use gcc to compile. Like project/android/build_32.sh

**Comment by jxt1234** [comment]
Fixed
