### ISSUE TITLE
编译windows版转换工具报错, 找不到'MNN_compression.pb.h'

### ISSUE THREAD

**Issue by flytair** [alibaba/MNN#1380]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows

# Github版本:
# Github Version:
master
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
mkdir build
cd build
cmake -G "Ninja" -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_CONVERTER=ON -DCMAKE_BUILD_TYPE=Release ..
ninja
# 编译日志:
# Build Log:
FAILED: tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/merge/ConvBNReluFuseToConvInt8.cpp.obj
C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"0.2.1.5git\" -DMNN_VERSION_MAJOR=0 -DMNN_VERSION_MINOR=2 -DMNN_VERSION_PATCH=1 -D_CRT_SECURE_NO_WARNINGS -I..\include -I..\source -I..\express -I..\tools -I..\codegen -I..\schema\current -I..\3rd_party -I..\3rd_party\flatbuffers\include -I..\3rd_party\half -I..\3rd_party\imageHelper -I..\3rd_party\OpenCLHeaders -I..\tools\converter\include -I..\tools\converter\source\tflite\schema -ID:\opensource\NCNN\protobuf-3.4.0\src -Itools\converter /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /O2 /MD /O2 /Ob2 /DNDEBUG /Zi /showIncludes /Fotools\converter\CMakeFiles\MNNConverterOpt.dir\source\optimizer\merge\ConvBNReluFuseToConvInt8.cpp.obj /Fdtools\converter\CMakeFiles\MNNConverterOpt.dir\ /FS -c ..\tools\converter\source\optimizer\merge\ConvBNReluFuseToConvInt8.cpp
d:\opensource\ncnn\mnn\tools\converter\include\cxxopts.hpp: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
..\tools\converter\source\optimizer\merge\ConvBNReluFuseToConvInt8.cpp(15): fatal error C1083: Cannot open include file: 'MNN_compression.pb.h': No such file or directory
```
粘贴在这里
Paste log here or pastebin
```

**Comment by mittkongg** [comment]
wo ye 遇到了 linux， 这东西是 protoc生成的。但是我装了protoc啊

**Comment by yyfcc17** [comment]
protoc --version什么版本？

**Comment by TCBocean** [comment]
@yyfcc17 我也遇到了同样的问题，protoc版本是3.15.3

**Comment by Huanyongji** [comment]
Build the total project again

**Comment by panxianzhan** [comment]
同问

**Comment by yyfcc17** [comment]
有没有conda环境，如果有，关掉再编

**Comment by jxt1234** [comment]
最新代码修正了
