### ISSUE TITLE
请问如何从gpu设备直接获取数据

### ISSUE THREAD

**Issue by junfengxue** [alibaba/MNN#1382]
我运行MNN_FORWARD_OPENCL模式下的Mnn,但是我希望直接从device获取opencl结果而不是从host获取。

我在MNN中的onCopyBuffer函数中添加
 std::cout << "num == 1" << std::endl;
    void* hostPtr;
    hostPtr = malloc(29491200);
cl::Buffer &test_buffer = *(cl::Buffer *)(dstTensor->deviceId());
cl_mem test_buffer_mem = test_buffer();
cl::Buffer tst1 = cl::Buffer(test_buffer_mem);
mOpenCLRuntime->commandQueue().enqueueReadBuffer(tst1, CL_TRUE, 0, 29491200, hostPtr);
mOpenCLRuntime->commandQueue().finish();
    cv::Mat TOOL_Mat = cv::Mat::zeros(360, 640*32, CV_32SC1);
for (int i = 0; i < 640 * 360*32; i++)
{
    TOOL_Mat.at<float>(i) = (float)((float*)hostPtr)[i];
}
imwrite("/sdcard/save/getdata_test.png", TOOL_Mat);
确定我的输出tensor outputTensorHost是能获取到正确的gpu数据的，但是我在自己工程中运行Mnn后通过这种方式
cl::Buffer &buf = *(cl::Buffer *)(outputTensorHost->deviceId());
cl_mem shuf_buffer_float = buf();无法获取正确的gpu数据，请问一下该如何获取。我在mnn里面能正确获取数据，调用mnn确无法获取，是不是因为opencl的context这些不同，dstTensor->deviceId()这个地址能直接通用吗？谢谢

**Comment by jxt1234** [comment]
1、目前 mnn 的 opencl 默认用 image_2d ， deviceId 对应 内部定义的一个结构体，需要把 mnn - opencl 相关结构体定义的部分取出来，强转指针使用。
2、需要保证创建 mnn session 里面的 context 和 外面 opencl 用的是同一个 context ，这个如果用 C++ opencl api 的话应该是同一个

**Comment by junfengxue** [comment]
您好，谢谢您的回答。我还是没太明白。我目前是通过读取输出结果的tensor的deviceid拿gpu数据，
您的第一条建议是让我通过deviceid的方式获取数据还是其他方式。
第二条建议是必须使用同一个context，而您说的“这个如果用 C++ opencl api 的话应该是同一个”意思是：我不需要去传递context，只要正常生成context就可以通用吗？
我目前是需要直接获取gpu数据，我看你们代码opencl onCopyBuffer代码里面是通过把tensor的deviceid强制转成cl::buffer然后传递到host的，所以我在工程里面也是希望调用Mnn后通过输出的tensor的deviceid强制转换成cl::buffer传递到我自己的工程kernel里面，这种方式是否可行，还是说不要用deviceid？如果不用deviceid，那需要如何处理，通过在tensor添加新的成员变量处理cl::Buffer或者image_2d的方式传递吗？

**Comment by jxt1234** [comment]
是用 deviceId 获取指针，但这个指针不是 cl::buffer
可以看下 OpenCLBackend::onAcquireBuffer 的代码，大部分情况下是
auto image                               = mImagePool->alloc(imageWidth, imageHeight, dataType);
((Tensor*)nativeTensor)->buffer().device = (uint64_t)image;

**Comment by junfengxue** [comment]
好的，谢谢您的回答。还有一个问题，我想加入钉钉群，可是目前满了，能方便拉我进去吗，谢谢

**Comment by jnulzl** [comment]
> 2、需要保证创建 mnn session 里面的 context 和 外面 opencl 用的是同一个 context ，这个如果用 C++ opencl api 的话应该是同一个

你说的c++ opencl api是如下这个
```cpp
static Context getDefault(cl_int * err = NULL) ;
```
还是说下面这几个c++ api都行？？
```cpp
    Context(
        const VECTOR_CLASS<Device>& devices,
        cl_context_properties* properties = NULL,....)

    Context(
        const Device& device,
        cl_context_properties* properties = NULL,....)

    Context(
        cl_device_type type,
        cl_context_properties* properties = NULL,....)
```

我在MNN外面用`static Context getDefault`这个接口得到的context与MNN里面的context地址不一样，感觉不太对。
