### ISSUE TITLE
关于MNNV2Basic工具测量OpenCL执行时间

### ISSUE THREAD

**Issue by LHC00** [alibaba/MNN#1387]
目前我想要测试mnn模型在安卓OpenCL的执行时间, 在查看MNNV2Basic.cpp时发现里面的时间测试代码包含了copyFromHostTensor和copyToHostTensor的时间, 如果我只想查看执行时间怎么办。

因为我看到其他issue里提到，opencl后端的推理执行时间和copyToHostTensor是异步的，导致单独的runsession时间不是准确的推理执行时间。那我究竟能不能拿到呢？ 我尝试这样修改代码：

             for (int i = 0; i < t; ++i) {

                //auto begin = getTimeInUs();
                auto inputBegin = getTimeInUs();
                inputTensor->copyFromHostTensor(&givenTensor);
                auto begin = getTimeInUs();
                // net->runSessionWithCallBackInfo(session, beforeCallBack, afterCallBack, false);
                net->runSessionWithCallBackInfo(session, beforeCallBack, afterCallBack, true);
                auto end = getTimeInUs();
                outputTensor->copyToHostTensor(&expectTensor);
                auto outputEnd = getTimeInUs();

                //auto end = getTimeInUs();
                times[i] = (end - begin) / 1000.0f;
                inputCopyTimes[i] = (begin - inputBegin) / 1000.0f;
                outputCopyTimes[i] = (outputEnd - end) / 1000.0f;
                totalTimes[i] = (outputEnd - inputBegin) / 1000.0f;
            }

但是我发现无论runSessionWithCallBackInfo的参数是true还是false,最后测到的执行时间都没变. 所以这个执行时间能不能准确的测量到呢, 还是说opencl后端只有 执行+copyTo的和才是准确的？ 还请各位解惑，谢谢

**Comment by suruoxi** [comment]
非官方回复。OpenCL是异步实行的吧，应该是加了 copyTo才是准确的

**Comment by LHC00** [comment]
> 非官方回复。OpenCL是异步实行的吧，应该是加了 copyTo才是准确的

所以这部分推理的代码容易修改吗，比如把异步中copy的部分去除，只运行推理的代码，因为目前我有一个自己的实现，想要知道自己实现的和mnn那个快，带着copyto我很难做出判断吧，还是说copyto时间很短，推理占大头？

**Comment by jxt1234** [comment]
一般情况下 copy 时间较短，可以考虑开 opencl ENABLE_PROFILE 的宏看 gpu 时间
