### ISSUE TITLE
[WRONG]:"Use of undeclared identifier 'g0' " when compiling MNN with "-D MNN_USE_NEON" on iOS

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#139]
Clearly, g0 is a temporary variable in the upper circulation and cannot been used directly in this one.

![FD131B0F-EE11-4569-AA53-8016F603B88F](https://user-images.githubusercontent.com/20228088/60636241-47be5280-9e48-11e9-89a9-bbba0e75c78d.png)

**Comment by jxt1234** [comment]
Fixing
