### ISSUE TITLE
iPhone上createSession函数出现不稳定crash

### ISSUE THREAD

**Issue by JackLiu01** [alibaba/MNN#1397]
iPhone上运行时，在createSession过程出现crash，是不稳定发生的，考虑可能是createSession过程申请内存不成功导致的
堆栈与错误类型：
<img width="422" alt="截屏2021-03-04 下午7 32 25" src="https://user-images.githubusercontent.com/29364023/109958085-c9067080-7d20-11eb-9b27-d420f6ca758e.png">
<img width="300" alt="截屏2021-03-04 下午7 32 35" src="https://user-images.githubusercontent.com/29364023/109958100-d0c61500-7d20-11eb-8424-c8a323c26e7e.png">

**Comment by Kepnu4** [comment]
Does you have step to reproduce this?

**Comment by 553566286** [comment]
你好，这问题解决了吗？我在安卓上也断断续续的有这个问题，更新了MNN版本之后零零星星有几个

**Comment by Stephen-Adams** [comment]
> iPhone上运行时，在createSession过程出现crash，是不稳定发生的，考虑可能是createSession过程申请内存不成功导致的
> 堆栈与错误类型：
> <img alt="截屏2021-03-04 下午7 32 25" width="422" src="https://user-images.githubusercontent.com/29364023/109958085-c9067080-7d20-11eb-9b27-d420f6ca758e.png">
> <img alt="截屏2021-03-04 下午7 32 35" width="300" src="https://user-images.githubusercontent.com/29364023/109958100-d0c61500-7d20-11eb-8424-c8a323c26e7e.png">

您好，想问下您那边createSession的时候，传的config参数，开了几个线程？

**Comment by JackLiu01** [comment]
> > iPhone上运行时，在createSession过程出现crash，是不稳定发生的，考虑可能是createSession过程申请内存不成功导致的
> > 堆栈与错误类型：
> > <img alt="截屏2021-03-04 下午7 32 25" width="422" src="https://user-images.githubusercontent.com/29364023/109958085-c9067080-7d20-11eb-9b27-d420f6ca758e.png">
> > <img alt="截屏2021-03-04 下午7 32 35" width="300" src="https://user-images.githubusercontent.com/29364023/109958100-d0c61500-7d20-11eb-8424-c8a323c26e7e.png">
> 
> 您好，想问下您那边createSession的时候，传的config参数，开了几个线程？
4个线程

**Comment by BerylLuo** [comment]
同样在iPhone上出现这个问题，报错堆栈：

```
0 MNN::DefaultAllocator::onAlloc(int)
1 MNN::BufferAllocator::alloc(int, bool)
2 MNN::BufferAllocator::alloc(int, bool)
3 MNN::CPUBackend::allocBuffer(int, MNN::Tensor*, MNN::Backend::StorageType)
4 MNN::Pipeline::allocMemory()
5 MNN::Session::resize(bool)
6 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&, std::__1::pair<std::__1::map<MNNForwardType, std::__1::shared_ptr<MNN::Runtime>, std::__1::less<MNNForwardType>, std::__1::allocator<std::__1::pair<MNNForwardType const, std::__1::shared_ptr<MNN::Runtime> > > >, std::__1::shared_ptr<MNN::Runtime> > const&) (in MomoChat) + 380
7 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&)
8 MNN::Interpreter::createSession(MNN::ScheduleConfig `const&)
```

**Comment by BerylLuo** [comment]
同样在iPhone上出现这个问题，报错堆栈：

```
0 MNN::DefaultAllocator::onAlloc(int)
1 MNN::BufferAllocator::alloc(int, bool)
2 MNN::BufferAllocator::alloc(int, bool)
3 MNN::CPUBackend::allocBuffer(int, MNN::Tensor*, MNN::Backend::StorageType)
4 MNN::Pipeline::allocMemory()
5 MNN::Session::resize(bool)
6 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&, std::__1::pair<std::__1::map<MNNForwardType, std::__1::shared_ptr<MNN::Runtime>, std::__1::less<MNNForwardType>, std::__1::allocator<std::__1::pair<MNNForwardType const, std::__1::shared_ptr<MNN::Runtime> > > >, std::__1::shared_ptr<MNN::Runtime> > const&)
7 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&)
8 MNN::Interpreter::createSession(MNN::ScheduleConfig `const&)
```

**Comment by Brandon-li** [comment]
请问下这个问题有结论吗？我们线上也有偶先 crash：

 MNN::Interpreter::createSession(MNN::ScheduleConfig const&) + 168
 
 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&) + 60
 
 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&) + 60
 
 MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&, std::__1::pair<std::__1::map<MNNForwardType, std::__1::shared_ptr<MNN::Runtime>, std::__1::less<MNNForwardType>, std::__1::allocator<std::__1::pair<MNNForwardType const, std::__1::shared_ptr<MNN::Runtime> > > >, std::__1::shared_ptr<MNN::Runtime> > const&) + 28

**Comment by LaoTanm** [comment]
辛苦开发大大们跟进下，求求了~

**Comment by LukeChow** [comment]
> 辛苦开发大大们跟进下，求求了~

你加官方钉钉群，问题很快就能解决，我当时就是这样解决的

**Comment by luowei0701** [comment]
问题解决了么

**Comment by wangzhaode** [comment]
错误堆栈信息不足 无法判断具体问题；
出现错误的可能是模型问题，配置设置不正确等原因；只有目前这些信息无法判断原因；
