### ISSUE TITLE
MNN to MNN converter

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#1398]
I need to reduce MNN weight file size by changing the weightQuantBits but does the converter have the functionality to work on previously created MNN weight files?

**Comment by jxt1234** [comment]
It's ok. Just like this: 
./MNNConvert -f MNN --modelFile origin.mnn --MNNModel new.mnn --bizCode AliNNTest --weightQuantBits 8

**Comment by kafan1986** [comment]
@jxt1234 Few of the trained models I have are already in fp16 format. On them weightquantbits 8 does not work, to acieve further weight file compression.
