### ISSUE TITLE
benchmark.cpp 中如何设置多输入多输出

### ISSUE THREAD

**Issue by zhaoyang-star** [alibaba/MNN#1401]
比如模型中有2个输入和2个输出，shape分别为1,3,256,256和1,3,300,300，输出为1,3,256,256和300。
能否给出多输入多输出下的 benchmark.cpp 示例呢？

**Comment by jxt1234** [comment]
只是作  Benchmark 的话，多输入一般输入第一个，输出第一个就可以了。

需要完整统计，参考 https://www.yuque.com/mnn/cn/input 和 https://www.yuque.com/mnn/cn/output 里面，用 getSessionInputAll / getSessionOutputAll 遍历所有输入/输出赋值
