### ISSUE TITLE
windows版在createSession时崩溃

### ISSUE THREAD

**Issue by capriccioo** [alibaba/MNN#1407]
我直接下载的编译好的windows版1.1.0.

写了一个最简单的测试程序：
int main(int argc, char** argv) 
 {   
    MNN::Interpreter* ip=MNN::Interpreter::createFromFile("blazeface.mnn");
    MNN::ScheduleConfig conf;
    MNN::Session* session = ip->createSession(conf);
    return 0;
}
确定“blazeface.mnn”在当前路径下，createFromFile没有返回null。
在createSession时程序会崩溃。

是MNN1.1.0win版有问题还是我哪里搞错了？
我试过了0.2.1.7版也是同样的问题

**Comment by WillTao-RD** [comment]
会不会是blazeface.mnn转换结果不对？
建议换用仓库里的模型验证一下（benchmark/models/*.mnn）

**Comment by xiaohuaibaoguigui** [comment]
您的问题解决了吗？我调用这个模型也崩溃，转换没有报错。

**Comment by RangeLiu** [comment]
自己训练的模型，同样的问题，不知道是不是自己模型的原因。

**Comment by wangzhaode** [comment]
一般是模型格式不正确，具体定位需要提供模型或者崩溃堆栈；
