### ISSUE TITLE
windows+mingw64 卷积出现段错误

### ISSUE THREAD

**Issue by riverlight** [alibaba/MNN#1408]
release版本跑个最简单的 conv2d 操作的模型都会报段错误(segment fault)，但debug不会
经过调试，发现跟 ConvolutionWinograd.cpp 中的 postFunction 函数多线程执行有关

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows 10
用的 mingw64
gcc 版本是  8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)

# Github版本:
# Github Version:
fa5b3cc4de1969cf752b45a450240e6eaefda981
2021.03.15 

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
mingw64

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
postFunction 已经在 1.1.5 之中去掉，请更新后再试
