### ISSUE TITLE
MNN在arm平台上只支持Android版的OpenCL和Vulkan吗？

### ISSUE THREAD

**Issue by capriccioo** [alibaba/MNN#1411]
我用的时RockPi4C，上面装的时Debian的系统，CPU时arm v8a架构，GPU是mali T864，其文档显示支持opencl和vulkan，我在上面也编译成功了MNN的OpenCL和Vulkan，但在使用OpenCL的时候，会在推理时出错。而使用Vulkan时直接提示没有这个type，将使用config.type=0（即CPU），然后正确运行。
是因为MNN OpenCL和Vulkan根本就不支持Debian吗？还是我哪里没弄好？

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/en/faq 里面 Can't use opencl / vulkan in PC 项，是链接静态变量，android  / linux 处理方式不同的原因

**Comment by TUT-jiayou** [comment]
@capriccioo  你好, 关于在rk3399 上面编译 MNN的话, 在Cmakelist.txt 文件中打开, ARM82 的选项中, 是否遇到编译报错的问题.
我遇到了这个问题`error: unknown value ‘armv8.2-a+fp16’ for -march`

我使用交叉编译, x86-64, os 16.04.
