### ISSUE TITLE
MNN团队长期招聘

### ISSUE THREAD

**Issue by hush-alibaba** [alibaba/MNN#1412]
联系邮箱：shuhui.sh@alibaba-inc.com

### 端智能推理引擎架构师
https://job.alibaba.com/zhaopin/position_detail.htm?trace=qrcode_share&positionCode=GP702619

职位描述：
1. 负责端侧推理引擎的顶层架构设计和开发, 负责关键技术方案的架构选型，主导技术方案和系统设计评审；把握复杂系统的设计，确保系统架构质量
2. 负责端侧设备的高性能计算优化，确保在推理引擎，图像处理，视频编解码等复杂计算领域的技术先进性和核心竞争力
3. 负责端侧推理引擎及高性能计算对集团内外的影响力提升

职位要求：
1. 深入了解tensorflow/pytorch的核心, 对其有突出的贡献, 或主导过类似框架的核心架构设计
2. 或者深入了解tvm的核心，对其有突出的贡献，对模型编译/IR设计/端上高性能代码生成有深入洞察
3、或者对机器学习理论有深入研究，特别模型架构搜索/模型结构优化/模型压缩有较高的理论功底；
4. 或者对卷积/矩阵乘法/图像/视频编解码等高性能计算有深入的理解和洞察.
5. 对技术风险敏感，对业务有前瞻性的判断
6. 深度学习领域3年以上工作经验，有一定的知名度和影响力
7. base地杭州、北京

### 深度学习全栈部署 (杭州/北京)
https://job.alibaba.com/zhaopin/position_detail.htm?trace=qrcode_share&positionCode=GP712932 

职位描述：
1. 搭建推理引擎在多端 (Android, iOS, Windows, Mac, Linux)的持续集成、测试、交付系统，保障核心业务的稳定性，支撑业务快速迭代和交付
2. 搭建推理引擎多端业务运行数据监控系统
3. 管控推理引擎对外输出的产物形式、用户接口

职位要求：
1. 深度学习领域3年以上工作经验
2. 有工业级的移动开发、Windows或者Mac OS应用开发的经验
3. 了解主流开源推理引擎的架构设计和基本原理
4. 对技术风险敏感，对业务有前瞻性的判断
5. base地杭州、北京

### 端智能/服务端开发专家 （杭州/北京/深圳）
https://job.alibaba.com/zhaopin/position_detail.htm?trace=qrcode_share&positionCode=GP703103

职位描述：
1、基于推理引擎MNN和端计算框架Walle，探索云-端协同智能的技术体系，包括算法部署、数据回流、性能评测、工作流等部分，助力手淘业务创新突破。
2、基于集团搜索中台技术基础设施，构建简单易用的算法工作平台，提升业务算法研发迭代效率，实现业务价值提升。

职位要求：
1、3年及以上使用C++或者JAVA开发经验，计算机基础扎实，代码能力出色。
2、有搜索推荐系统实现经验，LR、GBDT、Deep Learning等算法工程经验优先考虑。
3、有端侧智能相关经验，异构计算加速和业务应用创新优先考虑。
4、逻辑清晰、踏实勤奋、积极主动、良好沟通、团队协作；对思维活跃，敢于探索者优先考虑。

### 无线AR技术专家 （杭州/北京）
https://job.alibaba.com/zhaopin/position_detail.htm?trace=qrcode_share&positionCode=GP705606

职位描述：
1、负责手机AR产品涉及底层技术前沿性研究，支撑实时场景规模化应用；
2、负责AR真实感渲染算法研发，如人像滤镜效果、3D视觉还原、光线阴影模拟等；
3、负责AR场景检测算法研发，如三维重建、光照估计等；

职位要求：
1、从事移动端AR相关工作2年以上，对AR算法及工程有深刻理解；
2、熟悉计算机视觉相关领域算法，以及图形学、图像渲染OpenGL等领域知识；
3、具有扎实的工程实现能力，熟练使用C/C++及一门脚本语言；
4、有好奇心，创新思维，敢承担，可实战，团队合作，沟通能力佳；
5、有AR试穿试戴、AR互动玩法及其他商业化AR产品研发经验优先；
6、熟悉视觉识别/图形渲染相关领域，有代表性成果或论文优先；

**Comment by SatanWoo** [comment]
https://www.mnn.zone/#download-mnn-workstation 

欢迎大家尝试 MNN 团队推出的 MNN 工作台 和 MNN 模型市场

**Comment by beyonehan** [comment]
> https://www.mnn.zone/#download-mnn-workstation
> 
> 欢迎大家尝试 MNN 团队推出的 MNN 工作台 和 MNN 模型市场
网上登录的上，但是 APP MNNBench  登录不上，按照文档处理了授权问题，还是不行
