### ISSUE TITLE
Can't still use metal on osx?

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#1413]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
osx

# Github版本:
# Github Version:
1.1.3

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin

MNN_METAL = ON
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

Hi,
I tried to use metal on osx yesterday but it was failed.
It worked very well at the beginning but EXC BAD ACCESS error occurred after executing 2~3 times.
The crash was here https://github.com/alibaba/MNN/blob/master/source/backend/metal/MetalBackend.mm#L320
I guess it's multi thread issue or queue issue because I added "[NSThread sleepForTimeInterval:1];" code under https://github.com/alibaba/MNN/blob/master/source/backend/metal/MetalBackend.mm#L328 
It works fine although it's slow.
Can you check this?
Thank you.

**Comment by jxt1234** [comment]
OSX can use metal now. What's your code for using metal ?

**Comment by GHLab** [comment]
@jxt1234 That's great but reported crash issue can be reproducible on 1.1.4 and I pushed simple example https://github.com/GHLab/MNNMetalTest by using UltraFace.
It works good if I set MNN_FORWARD_CPU but it will occur crash if set MNN_FORWARD_METAL.
I also checked read metallib file correctly.
Please check this issue.

**Comment by bitxsw93** [comment]
i try your project. but it print"Can't load mnn.metallib" when using metal backend. So how do u config your mnn.metallib in your project

**Comment by GHLab** [comment]
@bitxsw93 Hi. You can check it after this codes applied. https://github.com/alibaba/MNN/compare/1.1.6...GHLab:version/1.1.6
I modified some codes to be able to load metallib without mnn.metallib by changing mnn.metallib  to hex data.

**Comment by GHLab** [comment]
@anliyuan Yes, The problem was caused by ARC and the MNN added the ARC option after 1.1.7
https://github.com/alibaba/MNN/blob/1.1.7/source/backend/metal/CMakeLists.txt#L14

**Comment by anliyuan** [comment]
> @anliyuan Yes, The problem was caused by ARC and the MNN added the ARC option after 1.1.7 https://github.com/alibaba/MNN/blob/1.1.7/source/backend/metal/CMakeLists.txt#L14

so should I delete this "COMPILE_FLAGS "-fobjc-arc""?
