### ISSUE TITLE
Failed to convert Dynamic Shape onnx to mnn.

### ISSUE THREAD

**Issue by gofugoo** [alibaba/MNN#1416]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Mac

# Github版本:
# Github Version:
master

commit id
5ed9ee8f8d7a392332dac65ba734f1101fc96b98

model files:
dynamic shapes:
[pirates_dymamic.onnx.zip](https://github.com/alibaba/MNN/files/6181061/pirates_dymamic.onnx.zip)
static shapes:
[pirates.onnx.zip](https://github.com/alibaba/MNN/files/6181064/pirates.onnx.zip)

convert commands:
MNNConvert -f ONNX --bizCode biz --modelFile pirates_dymamic.onnx --MNNModel test.mnn
error tips:
```
Start to Optimize the MNN Net...
Error for concat size of op [ 532 ], the 2 input not match output
Error for concat size of op [ 532 ], the 2 input not match output
Converted Done!

``` 
 Converting static shapes model is fine, but failed to convert  Dynamic Shape model.

**Comment by jxt1234** [comment]
有用官方的 onnxruntime 跑过么

**Comment by gofugoo** [comment]
官方的跑过，没有问题

**Comment by gofugoo** [comment]
> 有用官方的 onnxruntime 跑过么
onnxruntime 跑过，没有问题，可以输入任意尺寸。
我使用mnn opencl进行推断， 在固定shape上能够推断结果。1，利用dynamic shape导出的mnn模型进行团队，几乎就没有结果了. 2, 利用固定尺寸模型，改变inputtensor shape, 进行resize session, 进行推断，也是几乎没有结果。

resize 的关键代码.

```
            mInputHeight = 320;
            mInputWidth = 640;
            mNetPtr->setSessionMode(MNN::Interpreter::Session_Input_Inside); //这儿api不是太理解
            mSessionPtr = mNetPtr->createSession(config);
            mNetPtr->resizeTensor(mSessionInputTensorPtr, inputDims);
            mNetPtr->resizeSession(mSessionPtr);
```

**Comment by jxt1234** [comment]
是 opencl 推理有问题还是 cpu 有问题?

**Comment by jxt1234** [comment]
另外 mnn 本身就是天然支持dynamic shape 推理的

**Comment by jxt1234** [comment]
你这个模型我测了下 CPU 没有问题，那个concat 的 size 报错是因为没有初始输入 width/ height ，尝试计算 shape 做图优化失败，可以忽略
