### ISSUE TITLE
iOS - MNN with Metal gives wrong output

### ISSUE THREAD

**Issue by L1onKing** [alibaba/MNN#1418]
# Platform(Include target platform as well if cross-compiling):  iOS 14.1.3
commit id - 5ed9ee8

The issue is simple. When I launch inference on my model using just CPU config `MNN_FORWARD_CPU` the output is correct, but the execution time is near `90ms` on `iPhone XR`. So I have built MNN.framework with Metal support. I have fetched `mnn.metallib` and added it manually to Resources folder.

The execution time with Metal optimisation got smaller but the output is very inaccurate and looks like garbage

The code for Interpreter initialisation is listed below:

```
_interpreter = MNN::Interpreter::createFromFile([p UTF8String]);
    if (_interpreter == nullptr) {
        *err = [NSError errorWithDomain:NSCocoaErrorDomain code:(-999) userInfo:@{ NSLocalizedDescriptionKey: @"Can not create interpreter" }];
        return false;
    }
    
    MNN::ScheduleConfig config;
    
    config.numThread = 4;
    config.type = MNN_FORWARD_METAL;
    config.backupType = MNN_FORWARD_CPU;
    
    MNN::BackendConfig *backendConfig = new MNN::BackendConfig();
    backendConfig->memory = MNN::BackendConfig::Memory_Normal;
    backendConfig->power = MNN::BackendConfig::Power_High;
    backendConfig->precision = MNN::BackendConfig::Precision_Low;
    
    config.backendConfig = backendConfig;
    
    _session = _interpreter->createSession(config);
    if (_session == nullptr) {
        *err = [NSError errorWithDomain:NSCocoaErrorDomain code:(-999) userInfo:@{ NSLocalizedDescriptionKey: @"Can not create session" }];
        return false;
    }
```

Please let me know what I have missed

**Comment by jxt1234** [comment]
Could you upload your model for check result?

**Comment by fakeyee** [comment]
I have the same question. Did you solve it? It runs correct on CPU mode, but not on Metal. Don't know why.

**Comment by jxt1234** [comment]
Update MNN. If still has error, create a new issue
