### ISSUE TITLE
如何升级MNNConvert的版本

### ISSUE THREAD

**Issue by zhuoran-guo** [alibaba/MNN#1419]
你好，
请问如何升级MNNConvert的版本
官方克隆的版本永远都是0.2.1.5git
现在想升级到0.2.1.8git
请问要怎么办呢？ 
谢谢

**Comment by jxt1234** [comment]
这个是代码里面显示的版本号没更新，直接更新代码重编或者更新 pymnn 即可，Converter 版本与 MNN 版本一致
