### ISSUE TITLE
Pod 'MNN'的问题

### ISSUE THREAD

**Issue by wmFrank** [alibaba/MNN#1421]
在iOS工程中使用 pod 'MNN', :git => 'https://github.com/alibaba/MNN.git'， 发现Pods库中的3rd_party中没有half/half.hpp。然后在Xcode的编译中就会显示找不到half.hpp文件。必须手动添加这个文件到Pods中才能编译通过。
想问下这个是不是mnn.podspec编写中的bug。

**Comment by gaoxiao** [comment]
same here, can you please fix?

**Comment by wangzhaode** [comment]
MNN.podspec确实存在问题，下个版本会更新解决该问题
