### ISSUE TITLE
MNN==1.1.3,python,加载模型方式不同，模型输出不一致？？

### ISSUE THREAD

**Issue by fcqfcq** [alibaba/MNN#1424]
方法一：
        vars = F.load_as_dict("test.mnn")
        print(vars.keys())   
        inputVar = vars["input"]
        # 查看输入信息
        print(inputVar.data_format)
        if (inputVar.data_format == F.NC4HW4):
            inputVar.reorder(F.NCHW)
        # 写入数据
        inputVar.write( to_numpy(img).tolist())
        # 查看输出结果
        outputVar = vars['output']

方法2：
    interpreter = MNN.Interpreter("test.mnn")
    print(dir(interpreter))
    session = interpreter.createSession()
    input_tensor = interpreter.getSessionInput(session)
    ...
    output_tensor = interpreter.getSessionOutput(session)
该模型功能是做分割效果，输出结果不一致，方法一是我需要的结果。如何改称c++ 重写，如何写？
c++我尝试了	，没有得到期望输出，代码如下
        auto mnnNet = std::shared_ptr\<MNN::Interpreter\>(MNN::Interpreter::createFromFile(mnn_model_path));
	MNN::ScheduleConfig netConfig;
	netConfig.type = MNN_FORWARD_CPU;
	//netConfig.type = MNN_FORWARD_OPENCL;
	netConfig.numThread = 4;
	auto session = mnnNet->createSession(netConfig);
	auto input = mnnNet->getSessionInput(session, INPUT_NAME);
        .......
        auto output_host = std::make_shared<MNN::Tensor>(output, MNN::Tensor::TENSORFLOW);
	output->copyToHostTensor(output_host.get());
	auto values = output_host->host<float>();

**Comment by jxt1234** [comment]
输入部分和 NCHW 对应的是 CAFFE
