### ISSUE TITLE
转换tflite模型失败，不支持SPACE_TO_BATCH_ND

### ISSUE THREAD

**Issue by herbiezhao** [alibaba/MNN#1428]
# 平台(如果交叉编译请再附上交叉编译目标平台):  ubuntu1804
# Github版本: master
使用MNNConvert转换tflite模型，报错Check failed: creator ==> NOT_SUPPORTED_OP: [ SPACE_TO_BATCH_ND ]
但是我看这个算子MNN是支持的，这个是什么原因？难道这个算子只支持pb的tf算子，不支持tflite？

**Comment by jxt1234** [comment]
新版本已经支持了（1.1.6）
不过一般建议由 pb 转换到  mnn
