### ISSUE TITLE
android demo

### ISSUE THREAD

**Issue by qinghua2016** [alibaba/MNN#143]
Hi, I can successfully run the android demo. The mobilenet model can predict, but when I choose squeezenet, the app flash back. Do you have any idea? @li-qing

**Comment by li-qing** [comment]
was the squeezenet model downloaded and converted correctly?

any crash log that you could provide?

**Comment by chiwangnvp** [comment]
how to run the android demo @qinghua2016 @li-qing

**Comment by qinghua2016** [comment]
@li-qing I find the problem, the squeezenet model can run successfully by opencl, opengl and vulkan.
