### ISSUE TITLE
onnx转换成mnn完成，但输出与权重异常

### ISSUE THREAD

**Issue by oneway234** [alibaba/MNN#1430]
你好:
我通过语雀的转换文档将onnx成功转换成mnn，然而在python层面进行推理验证时，发现输出不符，进一步查看权重时也发现不一样，请问问题点可能出在哪？
以下是转换日志以及模型：

> MNNConverter Version: 0.2.1.5git - MNN @ 2018
> 
> Start to Convert Other Model Format To MNN Model...
> [10:41:34] /Users/wei/work/MNN/tools/converter/source/onnx/onnxConverter.cpp:31: ONNX Model ir version: 7
> Start to Optimize the MNN Net...
> [10:41:34] /Users/wei/work/MNN/tools/converter/source/optimizer/PostConverter.cpp:64: Inputs: input
> [10:41:34] /Users/wei/work/MNN/tools/converter/source/optimizer/PostConverter.cpp:69: Outputs: classifier
> Converted Done!

[model.onnx](https://drive.google.com/file/d/142Y73lSq1j6LCPedxoI5y0DZDAWPXlnW/view?usp=sharing)
[model.mnn](https://drive.google.com/file/d/1YQ5IlDPw9yqduRAlcQUIB8GCrHxb7WsG/view?usp=sharing)

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MAC

# Github版本:
# Github Version:

commit c172010bfd180ef532b98ef2f593a44ec5bc034a

# 编译方式:
# Compiling Method

```
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
```

# 编译日志:
# Build Log:

[log](https://drive.google.com/file/d/1i2yr3PZiWbeVKM1hdC6p_bM-GYFSq9-g/view?usp=sharing)

**Comment by jxt1234** [comment]
权重不符有可能是 mnn 做了 fuse ，请先用 tools/scripts/fastTestOnnx.py 看下 mnn 和 onnx 推理结果是否一致，你这个很高概率是自己输入输出处理问题

**Comment by oneway234** [comment]
推理的结果不一致，但输入输出的维度是相同的

**Comment by oneway234** [comment]
已经使用tools/scripts/fastTestOnnx.py 以及mnn的示例进行推理，原模型与onnx的推理结果相同，onnx与mnn推理结果不同，在输入方面再次确认使用的是相同输入，而输出方面皆是提取"classifiter"的输出，然而结果不同，请问还可能是哪方面的问题呢？

**Comment by jxt1234** [comment]
首先 tools/scripts/fastTestOnnx.py 这个是否返回的是 TEST_SUCCESS ，这个 SUCCESS 表示 MNN 与 onnx 运行结果一致。
然后需要检查自己输入输出的处理，发一下使用的代码吧.

**Comment by oneway234** [comment]
在使用fastTestOnnx.py上有个疑问，根据语雀上的代码以命令行的方式执行

> python3 fastTestOnnx.py XXXX.onnx

fastTestOnnx.py的代码在没有改动下返回是TEST_SUCCESS，请问这样的测试方式是正确的吗？
```
#!/usr/bin/python
import sys
import onnx
import onnxruntime as ort
import numpy as np
modelName = sys.argv[1]

jsonDict = {}
jsonDict['inputs'] = []
jsonDict['outputs'] = []
import os
print(os.popen("mkdir onnx").read())

inputs = {}
ort_session = ort.InferenceSession(modelName)
model = onnx.load(modelName)
for inputVar in ort_session.get_inputs():
    inp = {}
    inp['name'] = inputVar.name
    inp['shape'] = inputVar.shape
    inputs[inputVar.name] = np.random.uniform(0.1, 1.2, inputVar.shape).astype(np.float32)
    jsonDict['inputs'].append(inp)

print([output.name for output in model.graph.output])
for output in model.graph.output:
    jsonDict['outputs'].append(output.name)

import json
jsonString = json.dumps(jsonDict, indent=4)
with open('onnx/input.json', 'w') as f:
    f.write(jsonString)

print('inputs:')
for key in inputs:
    print(key)
    f = open("onnx/" + key + '.txt', 'w')
    np.savetxt(f, inputs[key].flatten())
    f.close()

outputs = ort_session.run(None, inputs)
print('outputs:')
for i in range(0, len(outputs)):
    outputName = model.graph.output[i].name
    name = 'onnx/' + outputName + '.txt'
    print(name, outputs[i].shape)
    f = open(name, 'w')
    np.savetxt(f, outputs[i].flatten())
    f.close()

print(os.popen("cp " + modelName + " onnx/test.onnx").read())

print(os.popen("./TestConvertResult Onnx onnx").read());
```
或是我需要更改输入部分？ 因为当我更改输入，测试代码总是无法运行

**Comment by jxt1234** [comment]
TEST_SUCCESS 说明 MNN 运行结果是正确的，需要检查你使用代码的输入输出处理部分

**Comment by oneway234** [comment]
好的 我再仔细的检查输入输出部分 谢谢

**Comment by oneway234** [comment]
谢谢帮助，问题点确实在输出输入部分

为往后有问题点定位疑问的人做个小结：
1. 先使用fastTestOnnx.py进行onnx与mnn的推理验证
2. 若验证成功必然是输入输出问题
3. 输入输出的维度以及数据处理是检查的关键点

**Comment by zhepherd** [comment]
我也遇到同样的，问题，而且输入是一样的！不知道问题出在哪里

**Comment by myh12138** [comment]
能验证动态模型吗

**Comment by Asuna88** [comment]
1. 先使用fastTestOnnx.py进行onnx与mnn的推理验证, 若验证成功必是输入输出问题
2. 检查的关键点: 输入输出的维度以及数据处理

是的。

**Comment by tea-2017** [comment]
> 1. 先使用fastTestOnnx.py进行onnx与mnn的推理验证, 若验证成功必是输入输出问题
> 2. 检查的关键点: 输入输出的维度以及数据处理
> 
> 是的。

怎么检查输入输出的维度以及数据处理，fastTestOnnx.py处理后的结果不是有输入输出维度吗？？  数据处理是什么  ？？指的是mean  std   这些吗
