### ISSUE TITLE
Why is the storageType for TensorUsage::OUTPUT not DYNAMIC_SEPERATE?

### ISSUE THREAD

**Issue by jongparkoffical** [alibaba/MNN#1431]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MAC / Windows

# Github版本:
# Github Version:
v1.1.4 (or below)

# Question:
https://github.com/alibaba/MNN/blob/master/source/core/Pipeline.cpp#L47
In this code, TensorUsage::OUTPUT is not considered as DYNAMIC_SEPERATE. 
Is there a reason why? 

I have a model that takes multiple outputs and feedback this result right back to multiple inputs (similar to a RNN).
In this case, the results seems to be different from Onnx. 

If I change that code to include TensorUsage::OUTPUT to be DYNAMIC_SEPERATE, the code works as same as onnx. 
It seems like certain memory region collides with tensors that have types of  TensorUsage::OUTPUT and TensorUsage::INPUT. 

Is there a possibility that this might happen?

**Comment by jxt1234** [comment]
Do you set the saveTensors for middle output ?

**Comment by jxt1234** [comment]
What's your code for run mnn?

**Comment by jongparkoffical** [comment]
Here's the way I'm running the session in cpu. Is there a problem?

```
// run session
m_interpreter1->runSession(m_session1);

auto outputTensor = m_interpreter1->getSessionOutput(m_session1, "output");
float* buffer = outputTensor->host<float>();

// ...
// do something with the output
// ...

for (int i = 1; i < num; i++)
 {
         auto tensor_name = std::to_string(i);
         auto tensor_output_name = "o_" + tensor_name;
         auto o1 = interpreter->getSessionOutput(session, tensor_output_name.c_str());
         auto in1 = interpreter->getSessionInput(session, tensor_name.c_str());
         o1->copyToHostTensor(in1);
 }
 


```

**Comment by jongparkoffical** [comment]
> Do you set the saveTensors for middle output ?

No I don't. Is it necessary?

**Comment by jxt1234** [comment]
Maybe for second run, some of MNN's input is not fill with content?
For session, all Input's content needed be input again,  because session will reuse input's memory for middle output.
