### ISSUE TITLE
请问下MNN支持FreeRTOS系统下编译吗，芯片是Coterx-A7的

### ISSUE THREAD

**Issue by Microkitty** [alibaba/MNN#1432]

**Comment by jxt1234** [comment]
默认应该是支持的

**Comment by Microkitty** [comment]
> 
> 
> 默认应该是支持的

FreeRTOS不是linux系统，比较特别，内核什么都不一样，你们有没有专门适配过？

**Comment by jxt1234** [comment]
没有专门适配，按理支持 C++11 就可以

**Comment by Microkitty** [comment]
> 
> 
> 默认应该是支持的

试了不行，裸机版arm-gcc交叉编译不过，报各种错，只能用linux版arm-gcc交叉，故只支持arm-linux系统，无法直接上裸机，能上裸机的只找到tensorflow-lite支持
