### ISSUE TITLE
MNN工作台有没有支持Ubuntu计划

### ISSUE THREAD

**Issue by leemengxing** [alibaba/MNN#1434]
hello，我对于MNN工作台很感兴趣，但遗憾的是我的主要开发环境是Ubuntu，请问是否有计划做下支持工作？相信用Ubuntn做开发环境的工程师有一定比例。

**Comment by SatanWoo** [comment]
@leemengxing  Hello，很高兴你对 MNN 团队发布的 MNN 工作台感兴趣，我们主要工作环境是 Mac / Windows，相对来说对 Ubuntu 不是非常熟悉，有计划但是短期内不太有精力对 Ubuntu 平台进行适配迁移。

不知道你现在是已经工作还是仍在学校学习的学生？不知道你对加入 MNN 团队感不感兴趣，我们一起来完善 MNN 工作台以及 MNN～

@leemengxing 期待收到你的回复哦～
