### ISSUE TITLE
ONNX  NOT SUPPORTED OP [LeakyRelu][Slice][sigmoid][reducesum]

### ISSUE THREAD

**Issue by zhyj3038** [alibaba/MNN#144]
Hi, I am trying to convert a **onnx model**  with "**LeakyReLU, Slice, sigmoid, reducesum**" operater to MNN format. But it seems MNN not supported it .  
I tried several times but failed because I am not familiar with MNN .  Can you kindly add this operater?

**Comment by li-qing** [comment]
there ops are not support for now

**Comment by li-qing** [comment]
collected to pinned issue.
