### ISSUE TITLE
关于图片预处理pretreat->setMatrix(trans)的问题

### ISSUE THREAD

**Issue by le8888e** [alibaba/MNN#1440]
你好，

我在iOS上做一个简单的分类模型，pytorch和MNN模型的推理结果不一致，怀疑是图片预处理的问题
pytorch的预处理很简单：
![image](https://user-images.githubusercontent.com/34771253/114156182-e1d3f880-9954-11eb-82f4-105740418d50.png)
步骤依次是:
1. 将输入图片resize到(224, 224)
2. HWC->CHW，并且每个像素值除以255
3. 减均值，除标准差

我看无论是官方教程还是iOS的demo里面都声明了一个Matrix对象trans, 并且调了pretreat->setMatrix(trans）。这一块我不是特别理解。
我想问我要将输入图片resize到（224，224）的话，需要先调trans.postScale将图片resize成224*224吗？还是说    pretreat->convert(rgba, w, h, 0, input)会自动把输入图片（rgba）resize到 模型输入Tensor（input）的shape？

如果方便的话，可以教一下怎么实现我pytorch的图片预处理3个步骤吗？

谢谢！

**Comment by jxt1234** [comment]
pretreat->convert(rgba, w, h, 0, input)会把输入图片（rgba）按 matrix 变换坐标，填充满 模型输入Tensor（input）
可以参考 demo/exec/pictureRecognize.cpp 
setScale(224.0/inpur_w, 224.0 / input_h)
