### ISSUE TITLE
Can not convert 16 bit to 8 bit (MNN to MNN)

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#1442]
@jxt1234 Few of the trained models I have are already in fp16 format, on them weightquantbits 8 does not work, to achieve further weight file compression. On fp32 weight file the above solution works fine. How to compress fp16 weight file further?

_Originally posted by @kafan1986 in https://github.com/alibaba/MNN/issues/1398#issuecomment-811336158_

**Comment by wangzhaode** [comment]
Don't support.
