### ISSUE TITLE
vulkan速度比cpu慢

### ISSUE THREAD

**Issue by Yoline777** [alibaba/MNN#1443]
cmake 3.10.2
NDK 21
设备 努比亚Z18(骁龙845)
模型 mobilenetV2

![image](https://user-images.githubusercontent.com/50309922/114337267-6c9a3a80-9b83-11eb-9c23-1588000ad4be.png)
![image](https://user-images.githubusercontent.com/50309922/114337415-a53a1400-9b83-11eb-9dd4-9fb1d2ab6553.png)
这个是在arm64上vulkan和cpu的测试结果，vulkan比cpu要慢
对比测试中只修改了MNNForwardType，还需要其他设置才能发挥gpu性能么

**Comment by jxt1234** [comment]
可以看下 gpu 频率或用 benchmark 单独跑模型看下

**Comment by black-giser** [comment]
我在测试过程中也发现CPU4比vulkan要快一点点
