### ISSUE TITLE
图像分割模型 CUDA后端 segment fault, CPU后端运行正常

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#1445]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 16.04 x86_64 4.15.0-39-generic

# Github版本:
# Github Version:

MNN 1.1.5

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

下载日期 2021.4.12 

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

问题描述如下:

1.tensorflow模型转换mnn模型没有报错 可以正常转换
2.cpu后端计算结果正常
3.切换cuda后端计算 程序崩溃 segment fault。
堆栈信息如下
![error](https://user-images.githubusercontent.com/15725187/114349043-f48b3f00-9b99-11eb-866d-5740c90f3f52.png)

如果需要提供模型文件来进行调试 可以告知我哈:)

**Comment by jxt1234** [comment]
已知问题，在修复中

**Comment by MaybeShewill-CV** [comment]
@jxt1234 感谢大佬：）

**Comment by jxt1234** [comment]
同步一下代码再试试看?

**Comment by MaybeShewill-CV** [comment]
@jxt1234 直接pull 最新的代码吗 还是重新下载1.1.5的压缩包?

**Comment by jxt1234** [comment]
pull 最新代码，还没有 tag

**Comment by MaybeShewill-CV** [comment]
@jxt1234 好的 我试试看 有结果及时同步
