### ISSUE TITLE
MODNet模型转换成功, 加载后出现Compute Shape error for 691。

### ISSUE THREAD

**Issue by zichengf1997** [alibaba/MNN#1448]
你好，
       我尝试将MODNet项目中提供的.onnx模型（https://github.com/ZHKKKe/MODNet/tree/master/onnx）
[modnet.zip](https://github.com/alibaba/MNN/files/6301048/modnet.zip)转换成mnn模型然后inference。转换使用的是daquexian的https://convertmodel.com/，onnx optimizer使用前后几乎没有区别。 转换过程没有报错，但是我在C++加载转出的mnn模型时(createSession之后)，显示Compute Shape error for 691。节点具体信息：
![1](https://user-images.githubusercontent.com/73423114/114492862-03322e80-9c4c-11eb-9936-b90ed43682f8.png)
尝试转换成tflite，ncnn都失败了，救救孩子！

**Comment by jxt1234** [comment]
编译 MNN 代码再转换试下?

**Comment by zichengf1997** [comment]
有正常的输出，但是结果跟onnx格式的有点出入，请问会跟这个compute shape error有关系吗？

**Comment by jxt1234** [comment]
没有关系，compute shape error 是因为输入 shape 没指定，后续 resizeTensor -> resizeSession 就可以

**Comment by zichengf1997** [comment]
> 没有关系，compute shape error 是因为输入 shape 没指定，后续 resizeTensor -> resizeSession 就可以

好的，谢谢！

**Comment by kiyse0713** [comment]
请问Modnet 转 mnn 推理成，结果正确吗？我也在尝试转换中。有resizeTensor -> resizeSession， 但 runSession还是  会报Segmentation fault @zichengf1997

**Comment by zichengf1997** [comment]
> 请问Modnet 转 mnn 推理成，结果正确吗？我也在尝试转换中。有resizeTensor -> resizeSession， 但 runSession还是 会报Segmentation fault @zichengf1997

结果跟python上用.pth稍微有点不一样，基本正确。

**Comment by kiyse0713** [comment]
谢谢你的回复，用了最新版的mnnconvert我也转关成功了。原模型20多m，用了mnn的量化工具到6m。但是效果很差，请问你有好的方法做模型压缩吗？或者有什么轻量化的分割模型值得推荐？




| |
梁玉琪
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年05月19日 11:32，zichengf1997 写道：

请问Modnet 转 mnn 推理成，结果正确吗？我也在尝试转换中。有resizeTensor -> resizeSession， 但 runSession还是 会报Segmentation fault @zichengf1997

结果跟python上用.pth稍微有点不一样，基本正确。

**Comment by yyfcc17** [comment]
建议试试这个量化工具 https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant

**Comment by zichengf1997** [comment]
模型压缩了精度肯定会下降的..轻量级模型我之前试过unet和u2netp(https://github.com/xuebinqin/U-2-Net)
，但是参数量一小准确度就下去了，性能和速度没法平衡...我也是刚接触这个方向，不是特别了解，不好意思...

**Comment by kiyse0713** [comment]
> 建议试试这个量化工具 https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant

@yyfcc17 这个工具在MNN.expr.load_as_dict("modnet.mnn")模型的时候报错Segmentation fault。试了其他模型没问题。是MNN python库对某些算子没更新吗？也是用了最新的mnnconvert，才将模型转换成功了
