### ISSUE TITLE
pytorch 的 grid_sampler 层 onnx 转mnn

### ISSUE THREAD

**Issue by daodao316** [alibaba/MNN#1450]
从MNN的代码中，发现了支持 onnx 转MNN的 grid_sampler层：
https://github.com/alibaba/MNN/blob/2e17ca8669fd132e0caa48fb31031330b04a40df/tools/converter/source/onnx/GridSampleOnnx.cpp
但是我这边使用pytorch的torch.nn.functional.grid_sample 转onnx时，提示onnx不支持grid_sampler层。
我使用了最新的onnx代码，依然没发现grid_sampler层。请问您那边时如何实现pytorch的grid_sampler转mnn的呢？

https://github.com/alibaba/MNN/blob/2e17ca8669fd132e0caa48fb31031330b04a40df/tools/converter/source/onnx/GridSampleOnnx.cpp#L70

**Comment by daodao316** [comment]
@jxt1234  @xiaying 大神们可否辛苦帮忙看一下？

**Comment by jxt1234** [comment]
需要修改 pytorch 转 onnx 的代码

**Comment by dcrmg** [comment]
> @jxt1234 @xiaying 大神们可否辛苦帮忙看一下？

解决了吗？

**Comment by Hanson0910** [comment]
> 需要修改 pytorch 转 onnx 的代码

大神，请教一下如何修改pytorch代码？
