### ISSUE TITLE
同样的人像检测模型，样的图片，在IOS和Android上人像检测结果不一样

### ISSUE THREAD

**Issue by sunytan** [alibaba/MNN#1451]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
想确认一下，Android和IOS应用上对于同样的模型数据差异来源是什么？

**Comment by jxt1234** [comment]
差异是多少，预处理（图像解码、缩放等）是否一致

**Comment by tanyang93** [comment]
> 差异是多少，预处理（图像解码、缩放等）是否一致

* 图形解码
android java层通过接口传入的 `ARGB_8888`格式的bitmap。
cpp里会转成像素数组。 
```
AndroidBitmap_lockPixels(env, srcBitmap, &pixels);
process->convert((const unsigned char *)pixels, bitmapInfo.width, bitmapInfo.height, 0, tensor);
```
IOS 直接传入的图片转换成RGBA格式的像素数组。
这两种基本没有差异。

* 缩放方面：
都是按照MNN文档的一样的方式。
```
                    val matrix = Matrix()
                    matrix.setScale(1f / width, 1f / height)
                    matrix.postScale(inputWidth.toFloat(), inputHeight.toFloat())
                    matrix.invert(matrix)
```

最后的模型的输出有每一块的位置信息，人脸置信值，我们通过判断人脸置信值来确定是否是满足要求的人脸。
结果发现IOS上能输出正常人脸信息，切置信值在0.98以上。 但是Android端输出的数据基本在0.1一下。大部分0.0012多。
差距非常大。 如果需要看每一个值，我这边可以把输出数据存文件来对比一下。

能确保模型是完全一样的。

**Comment by jxt1234** [comment]
ios 和 android 的 mnn 库确认都是重编过的么?

**Comment by tanyang93** [comment]
> ios 和 android 的 mnn 库确认都是重编过的么?

android的mnn库我是下载的最新的release版本试了也识别不出人像（此图在IOS能识别出）;
ios的库我目前不确定是否本地编译的还是下载的release版本。

**Comment by tanyang93** [comment]
> ios 和 android 的 mnn 库确认都是重编过的么?

一张950x1220的图片在Android和IOS都能识别出来。
对图片进行编辑剪裁成322x1219 ，保障人像还是完整的，在Android端就没法识别出，在IOS端能识别出来，同样的模型文件。

**Comment by tanyang93** [comment]
> ios 和 android 的 mnn 库确认都是重编过的么?

已经确认了，ios和android端的库都是重新编译过的。

**Comment by jxt1234** [comment]
可以先保证模型输入输出数据一样测试一下？比如把 IOS 输入模型的数据 dump 成文件， android 上直接读文件

**Comment by sunytan** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
