### ISSUE TITLE
retinaface failed on CUDA and tensorRT

### ISSUE THREAD

**Issue by charlestamz** [alibaba/MNN#1453]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu linux 18.04

# Github版本:
# Github Version:
latest master till 2021.4.15

# 编译日志:
# Build Log:
编译正常，可以用benchmark测试cuda和tensorrt。
```

从https://github.com/zeusees/License-Plate-Detector
下载了一个预训练的retinaface‘模型，转化成了mnn模型，用MNN推理，backend是cpu计算没问题，改成CUDA之后，没有输出结果。如果需要转化后的模型和代码，我再找个地方上传。

**Comment by jxt1234** [comment]
相关模型方便发一下?

**Comment by rlczddl** [comment]
https://github.com/syshensyshen/Face-Detector-1MB-with-landmark/tree/mnn 模型在这

**Comment by wangzhaode** [comment]
长时间未回复，问题关闭
