### ISSUE TITLE
Pool padtype not supported!

### ISSUE THREAD

**Issue by sgl123github** [alibaba/MNN#1455]
利用MNN 量化训练 mobielnetv3模型， 当 代码运行到 opt.step(loss)的时候会报错：Pool padtype not supported!
修改了nn.AdaptiveAvgPool2d为MNN支持的算子avgpool（），但是还是报同样的错误

**Comment by jxt1234** [comment]
我看一下

**Comment by yyfcc17** [comment]
用这个python量化工具试试 https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant

**Comment by ZhangJunsong-NR** [comment]
> 用这个python量化工具试试 https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant

请问这个工具和mnnquant工具提供的后量化有那些区别呢

**Comment by yyfcc17** [comment]
精度更好一些，支持多输入，python预处理

**Comment by ZhangJunsong-NR** [comment]
好的 我尝试一下 感谢!
另外关于QAT的这个问题也麻烦看看有没有方法能够解决

**Comment by jxt1234** [comment]
最新提交修正
