### ISSUE TITLE
onnx中pad为负值，mnn结果会不一致

### ISSUE THREAD

**Issue by Chen1399** [alibaba/MNN#1458]
使用torch的nn.ConstantPad1d时，padding选择中有负值，eg:[-1,1]时，转成mnn模型，在推理过程中结果不一致，应该是convert时mnn模型不支持padding中存在负值，onnx是支持的。目前解决方法是用split代替pad中-1的操作。

**Comment by jxt1234** [comment]
可以发个示例Onnx模型么？

**Comment by chen1399** [comment]
nn.ConstantPad1d([-1,1])就是这个方法

**Comment by wangzhaode** [comment]
fixed
