### ISSUE TITLE
MNNConvert error

### ISSUE THREAD

**Issue by liguiyuan** [alibaba/MNN#146]
Hi, I use the mobilenet_v2 model(TF) provided by  this project,  but when I execute the convert command :
`./MNNConvert -f TF --modelFile mobilenet_v2_1.0_224_quant_frozen.pb --MNNModel model.mnn --bizCode MNN`

occurred error:
> MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [11:32:38] /home/liguiyuan/deep_learning/MNN/tools/converter/source/tensorflow/TmpGraph.cpp:64: 

===========This Model Has NOT_SUPPORTED_OP===========!!!

MNN NOT_SUPPORTED_OP: ======>[ FIFOQueueV2, FakeQuantWithMinMaxVars, QueueDequeueManyV2,  ]<======

已放弃 (核心已转储)

**MNN does not support this op?**

**Comment by li-qing** [comment]
these ops are not supported for now. collected to pinned issue.
