### ISSUE TITLE
win10上的vulkan编译失败

### ISSUE THREAD

**Issue by janicevidal** [alibaba/MNN#1462]
# 平台 :  windows 10 

# Github版本: version 1.1.6

# 编译方式: MSVC

```
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DMNN_VULKAN=ON -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=OFF ..
```

# 编译日志:

```
E:\MNN-1.1.6-0420\build>cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DMNN_VULKAN=ON -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=OFF ..
-- The C compiler identification is MSVC 19.16.27031.1
-- The CXX compiler identification is MSVC 19.16.27031.1
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: E:/NNIE/ruyi_env_setup-2.0.31/python35/python.exe (found version "3.5.4")
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Windows
--      Processor: AMD64
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: ON
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16:
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: E:/MNN-1.1.6-0420/build
-- AMD64: Open SSE
-- Found Vulkan: C:/VulkanSDK/1.2.135.0/Lib/vulkan-1.lib
-- Configuring done
-- Generating done
-- Build files have been written to: E:/MNN-1.1.6-0420/build

E:\MNN-1.1.6-0420\build>ninja
[13/309] Building CXX object CMakeFiles\MNNCore.dir\source\core\Interpreter.cpp.obj
..\source\core\Interpreter.cpp(209): warning C4477: “printf”: 格式字符串“%lu”需要类型“unsigned long”的参数，但可变参数 2 拥有了类型“_Ty2”
        with
        [
            _Ty2=size_t
        ]
..\source\core\Interpreter.cpp(209): note: 请考虑在格式字符串中使用“%zu”
[268/309] Building CXX object source\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\runtime\VulkanRuntime.cpp.obj
FAILED: source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/runtime/VulkanRuntime.cpp.obj
C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DBUILDING_MNN_DLL -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"0.2.1.5git\" -DMNN_VERSION_MAJOR=0 -DMNN_VERSION_MINOR=2 -DMNN_VERSION_PATCH=1 -D_CRT_SECURE_NO_WARNINGS -I..\include -I..\source -I..\express -I..\tools -I..\codegen -I..\schema\current -I..\3rd_party -I..\3rd_party\flatbuffers\include -I..\3rd_party\half -I..\3rd_party\imageHelper -I..\3rd_party\OpenCLHeaders -I..\source\backend\vulkan\. -I..\source\backend\vulkan\include -I..\source\backend\vulkan\component -I..\source\backend\vulkan\runtime -I..\source\backend\vulkan\execution -I..\source\backend\vulkan\backend -I..\source\backend\vulkan -I..\source\backend\vulkan\shaders /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /wd4819 /O2 /MD /O2 /Ob2 /DNDEBUG /Zi /showIncludes /Fosource\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\runtime\VulkanRuntime.cpp.obj /Fdsource\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\ /FS -c ..\source\backend\vulkan\runtime\VulkanRuntime.cpp
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(115): error C2270: “onCreate”: 非成员函数上不允许修饰符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(123): error C2270: “onValid”: 非成员函数上不允许修饰符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(129): error C2061: 语法错误: 标识符“VulkanRuntimeCreator”
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(129): error C3861: “MNNInsertExtraRuntimeCreator”: 找不到标识符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(132): error C2059: 语法错误:“}”
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(132): error C2143: 语法错误: 缺少“;”(在“}”的前面)
[273/309] Building CXX object source\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\execution\VulkanSoftmax.cpp.obj
ninja: build stopped: subcommand failed.
```

**Comment by jxt1234** [comment]
了解了，正在解决

**Comment by janicevidal** [comment]
> 了解了，正在解决

有结论了么

**Comment by jxt1234** [comment]
已经解决，还没同步，可以先用 feature/2021_04_28_sync 分支

**Comment by janicevidal** [comment]
> 已经解决，还没同步，可以先用 feature/2021_04_28_sync 分支

没有解决啊，还是有一样的bug
`E:\MNN-feature-2021_04_28_sync\build>NINJA
[45/356] Building CXX object CMakeFiles\MNNCore.dir\source\core\Interpreter.cpp.obj
..\source\core\Interpreter.cpp(209): warning C4477: “printf”: 格式字符串“%lu”需要类型“unsigned long”的参数，但可变参数 2 拥有了类型“_Ty2”
        with
        [
            _Ty2=size_t
        ]
..\source\core\Interpreter.cpp(209): note: 请考虑在格式字符串中使用“%zu”
[276/356] Building CXX object source\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\component\VulkanMemoryPool.cpp.obj
..\source\backend\vulkan\component\VulkanMemoryPool.cpp(129): warning C4101: “imageView”: 未引用的局部变量
[301/356] Building CXX object source\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\runtime\VulkanRuntime.cpp.obj
FAILED: source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/runtime/VulkanRuntime.cpp.obj
C:\PROGRA~2\MIB055~1\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DBUILDING_MNN_DLL -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -DMNN_VERSION=\"0.2.1.5git\" -DMNN_VERSION_MAJOR=0 -DMNN_VERSION_MINOR=2 -DMNN_VERSION_PATCH=1 -D_CRT_SECURE_NO_WARNINGS -I..\include -I..\source -I..\express -I..\tools -I..\codegen -I..\schema\current -I..\3rd_party -I..\3rd_party\flatbuffers\include -I..\3rd_party\half -I..\3rd_party\imageHelper -I..\3rd_party\OpenCLHeaders -I..\source\backend\vulkan\. -I..\source\backend\vulkan\include -I..\source\backend\vulkan\component -I..\source\backend\vulkan\runtime -I..\source\backend\vulkan\execution -I..\source\backend\vulkan\backend -I..\source\backend\vulkan -I..\source\backend\vulkan\shaders /DWIN32 /D_WINDOWS /W3 /GR /EHsc /wd4267 /wd4018 /wd4251 /wd4996 /wd4244 /wd4146 /wd4129 /wd4305 /wd4275 /wd4819 /O2 /MD /O2 /Ob2 /DNDEBUG /Zi /showIncludes /Fosource\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\runtime\VulkanRuntime.cpp.obj /Fdsource\backend\vulkan\CMakeFiles\MNN_Vulkan.dir\ /FS -c ..\source\backend\vulkan\runtime\VulkanRuntime.cpp
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(115): error C2059: 语法错误:“public”
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(116): error C2270: “onCreate”: 非成员函数上不允许修饰符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(124): error C2270: “onValid”: 非成员函数上不允许修饰符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(130): error C2061: 语法错误: 标识符“VulkanRuntimeCreator”
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(130): error C3861: “MNNInsertExtraRuntimeCreator”: 找不到标识符
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(133): error C2059: 语法错误:“}”
..\source\backend\vulkan\runtime\VulkanRuntime.cpp(133): error C2143: 语法错误: 缺少“;”(在“}”的前面)
[306/356] Building CXX object source\backend\opencl\CMakeFiles\MNN_CL.dir\execution\cl\opencl_program.cc.obj
ninja: build stopped: subcommand failed.`

**Comment by jxt1234** [comment]
你检查一下是不是你修改了文件

**Comment by jxt1234** [comment]
另外你 vs 版本是多少?

**Comment by janicevidal** [comment]
> 另外你 vs 版本是多少?

新下的的MNN-feature-2021_04_28_sync包，什么都没改，vs2017

**Comment by janicevidal** [comment]
最开始给的日志信息里，都很详细的，跟vulkan版本有关系么，可以在钉钉群里沟通么，这边交流不及时

**Comment by jxt1234** [comment]
我们这边windows 上编译是正常的... 钉钉群里面你发一下消息 ？

**Comment by jxt1234** [comment]
有可能是中文编码的问题，你修改下中文编码配置，或者把编译错误的代码上面三行注释删掉试试吧

**Comment by jnulzl** [comment]
> 有可能是中文编码的问题，你修改下中文编码配置，或者把编译错误的代码上面三行注释删掉试试吧

删掉这三行居然可以了:
https://github.com/alibaba/MNN/blob/3ab8725569fae5671185afec3c3a90c016a62156/source/backend/vulkan/runtime/VulkanRuntime.cpp#L113-L115

我用的Win10 VS2019
