### ISSUE TITLE
Error for concat size of op [ 392 ], the 3 input not match output

### ISSUE THREAD

**Issue by ghoshaw** [alibaba/MNN#1464]
# Platform
MacOS, catalina, 10.15.6

# Github Version:
commit 3788948b661ca98e6bb5196af76e6a49f39589f8 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4d88350b 84ede68d
Author: jxt1234 <jxt1234@zju.edu.cn>
Date:   Tue Apr 27 12:07:21 2021 +0800

    Merge pull request #1460 from DaydreamCoding/patch-3

    bugfix for schedule by path

# Compiling Method

cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

no error in process of compiling

##########################################
I try to convert  onnx to mnn using command line "./MNNConvert -f ONNX --modelFile xxx.mnn --MNNModel xxxx.mnn --bizCode biz"

the run log:
MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[14:10:24] /*/MNN/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 6
Start to Optimize the MNN Net...
Error for concat size of op [ 392 ], the 3 input not match output
Error for concat size of op [ 392 ], the 3 input not match output
inputTensors : [ data, ]
outputTensors: [ weight, prototype, ]
Converted Done!

The turned model saved, but what the error mean? And running use the saved model has the same error.
How to solve this? thanks

**Comment by jxt1234** [comment]
Firstly, use tools/scripts/fastTestOnnx.py to check onnx and mnn run result.

**Comment by ghoshaw** [comment]
run command line:    python fastTestOnnx.py /*/xxx.mnn
log:

/$$/lib/python3.6/site-packages/onnx/__init__.py:97: RuntimeWarning: Unexpected end-group tag: Not all data was converted
  decoded = cast(Optional[int], proto.ParseFromString(s))
Traceback (most recent call last):
  File "fastTestOnnx.py", line 237, in <module>
    t = TestModel(modelName)
  File "fastTestOnnx.py", line 103, in __init__
    self.__copy_to_here(modelName)
  File "fastTestOnnx.py", line 100, in __copy_to_here
    self.model = onnx.load(self.modelName)
  File "/$$/lib/python3.6/site-packages/onnx/__init__.py", line 119, in load_model
    model = load_model_from_string(s, format=format)
  File "/$$/lib/python3.6/site-packages/onnx/__init__.py", line 156, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/$$/lib/python3.6/site-packages/onnx/__init__.py", line 101, in _deserialize
    decoded, len(s)))
google.protobuf.message.DecodeError: Protobuf decoding consumed too few bytes: 1 out of 7887372

**Comment by jxt1234** [comment]
It means there is some error for your onnx model because onnxruntime can't run it.

**Comment by ghoshaw** [comment]
Thanks, I use another onnx model and the fasttestonnx is good. 
run:  python fastTestOnnx.py /*/xx.onnx
log:

onnx/test.onnx
['prototype', 'weight']
inputs:
data
outputs:
onnx/prototype.txt (1, 6, 64, 40)
onnx/weight.txt (1, 91)
/bin/sh: ./TestConvertResult: No such file or directory

And I turn the onnx to mnn successfully. But when I run the mnn model using python API, It always "段错误（核心已转储）"。

**Comment by jxt1234** [comment]
1. Build MNNConverter firstly before run fastTestOnnx.py , then you will see TestConvertResult .
2. The onnx model you can upload for me to check ?
