### ISSUE TITLE
Linux下编译MNNConverter失败

### ISSUE THREAD

**Issue by hongfangao** [alibaba/MNN#1467]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04LTS

# Github版本:
# Github Version:

commit 3788948b661ca98e6bb5196af76e6a49f39589f8 (HEAD -> master, origin/master, origin/HEAD)
Merge: 4d88350b 84ede68d

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:

# Compiling Method
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.7.5") 
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: 
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /home/xuehao/MNN/build
-- x86_64: Open SSE
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
-- Onnx: /home/xuehao/MNN/build/tools/converter/onnx.pb.h;/home/xuehao/MNN/build/tools/converter/onnx-operators.pb.h
CMake Error at tools/converter/source/optimizer/CMakeLists.txt:3 (target_link_libraries):
  Object library target "MNNConverterOpt" may not link to anything.
Call Stack (most recent call first):
  tools/converter/CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/xuehao/MNN/build/CMakeFiles/CMakeOutput.log".
See also "/home/xuehao/MNN/build/CMakeFiles/CMakeError.log".

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by huailiang** [comment]
我在 macOS平台上使用 master 最新的代码出现同样的问题， 但把 git节点 tag=1.1.4版本是可以编过的

**Comment by pminimd** [comment]
打开tools/converter/source/optimizer/CMakeLists.txt
用#注释掉 target_link_libraries(MNNConverterOpt PRIVATE MNNCompress)

**Comment by jxt1234** [comment]
> 我在 macOS平台上使用 master 最新的代码出现同样的问题， 但把 git节点 tag=1.1.4版本是可以编过的

报什么问题？貌似这里编译时没遇到？

**Comment by huailiang** [comment]
Object library target "MNNConverterOpt" may not link to anything.

> > 我在 macOS平台上使用 master 最新的代码出现同样的问题， 但把 git节点 tag=1.1.4版本是可以编过的
> 
> 报什么问题？貌似这里编译时没遇到？

Object library target "MNNConverterOpt" may not link to anything.

**Comment by jxt1234** [comment]
应该已经修正了
