### ISSUE TITLE
CUDA 不支持的两个层 Eltwise GridSample，CPU 下正常

### ISSUE THREAD

**Issue by daodao316** [alibaba/MNN#1475]
MNN使用版本：当前最新master 3ab8725
cpu结果正确，cuda不支持下两2个层
The Creator Don't support type Eltwise, 5719
Don't support type GridSample, 5880
Don't support type GridSample, 6009

**Comment by jxt1234** [comment]
现在就是这样做的（不支持的层使用 CPU计算）。
结果不对应该是有其他问题，可以自己先用 backendTest.out 测试一下

**Comment by daodao316** [comment]
> 现在就是这样做的（不支持的层使用 CPU计算）。
> 结果不对应该是有其他问题，可以自己先用 backendTest.out 测试一下

感谢。已经定位到是matmul的问题。删除cuda下对应的matmul算子，重新编译，这时候使用cpu的matmul结果就正常了。

**Comment by yjiangling** [comment]
> > 现在就是这样做的（不支持的层使用 CPU计算）。
> > 结果不对应该是有其他问题，可以自己先用 backendTest.out 测试一下
> 
> 感谢。已经定位到是matmul的问题。删除cuda下对应的matmul算子，重新编译，这时候使用cpu的matmul结果就正常了。

您好，请教一下，我也遇到相同的问题，CPU后端推理结果正确，CUDA推理结果错误，请问您是怎么定位到哪个算子异常的？而且您说的这个 matmul 问题是什么问题？是在CUDA后端时，这个算子计算结果不正确吗？

**Comment by JiaoPaner** [comment]
@daodao316 请问如何去除 遇到相同的问题
