### ISSUE TITLE
I want help how can I build in android can I compile with clang ? 

### ISSUE THREAD

**Issue by Saikatsaha1996** [alibaba/MNN#1478]
#please help me#

Platform Android
Os Android 11
Processor Qualcomm Snapdragon 865
Arm V8...
Gpu Adreno 650
In my device already available OpenCL 2.0 
But in termux when I put ./Clinfo
Showing every thing ok
But showing OpenCL gpu max frequency 1 MHz..
But I want to increase my OpenCL performance ...
How can I build it in my device?
Can I build with termux in my device?...
Please 🙏 guide me ....

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-05-18-16-55-43-893_com termux](https://user-images.githubusercontent.com/72664192/118643280-f5973800-b7f9-11eb-94b5-6b7b6a2cf062.jpg)


I got error like this

**Comment by wangzhaode** [comment]
请更新到最新的代码尝试编译
