### ISSUE TITLE
build android app erros

### ISSUE THREAD

**Issue by chiwangnvp** [alibaba/MNN#148]
Build command failed.
Error while executing process C:\Users\chiwang\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\code\MNN\demo\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target mnncore}
[1/353] cmd.exe /C "cd /D D:\code\MNN\demo\android\app\build && bash D:/code/MNN/schema/generate.sh -lazy"
FAILED: cmd.exe /C "cd /D D:\code\MNN\demo\android\app\build && bash D:/code/MNN/schema/generate.sh -lazy"
/bin/bash: D:/code/MNN/schema/generate.sh: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by chiwangnvp** [comment]
Build command failed.
Error while executing process C:\Users\chiwang\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build D:\code\MNN\demo\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target mnncore}
[1/353] cmd.exe /C "cd /D D:\code\MNN\demo\android\app\build && bash D:/code/MNN/schema/generate.sh -lazy"
FAILED: ../../../../build/CMakeFiles/MNN_SCHEMA 
cmd.exe /C "cd /D D:\code\MNN\demo\android\app\build && bash D:/code/MNN/schema/generate.sh -lazy"
/bin/bash: D:/code/MNN/schema/generate.sh: No such file or directory
ninja: build stopped: subcommand failed.

**Comment by chiwangnvp** [comment]
@li-qing

**Comment by smallt-TAO** [comment]
https://github.com/alibaba/MNN/issues/90

You can try to build project on ubuntu system.

**Comment by li-qing** [comment]
cross-compile on windows is not available currently

**Comment by chiwangnvp** [comment]
@li-qing @smallt-TAO So building android demo using Android Studio on ubuntu system is recommended?
