### ISSUE TITLE
Help wanted I got error like this when I compile...

### ISSUE THREAD

**Issue by Saikatsaha1996** [alibaba/MNN#1480]
Platform Android
Android 11
Install via termux with ubuntu in mobile

I got error like this

[ 74%] Built target MNN
[ 74%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/node_def.pb.cc.o
[ 74%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/op_def.pb.cc.o                         [ 74%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/ReIndexTensor.cpp.o
[ 75%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/RemoveDropout.cpp.o
[ 75%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/RemoveInplace.cpp.o
[ 75%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/RemoveOutputTensorConvert.cpp.o
Scanning dependencies of target MNN_Express
[ 75%] Building CXX object express/CMakeFiles/MNN_Express.dir/Executor.cpp.o
[ 76%] Building CXX object express/CMakeFiles/MNN_Express.dir/ExecutorScope.cpp.o
[ 76%] Building CXX object express/CMakeFiles/MNN_Express.dir/Expr.cpp.o
[ 76%] Building CXX object express/CMakeFiles/MNN_Express.dir/MathOp.cpp.o                                      [ 76%] Building CXX object express/CMakeFiles/MNN_Express.dir/MergeOptimizer.cpp.o
Scanning dependencies of target MNN_Vulkan
[ 76%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/RemoveUnusefulOp.cpp.o
[ 76%] Building CXX object express/CMakeFiles/MNN_Express.dir/NeuralNetWorkOp.cpp.o
[ 76%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/backend/VulkanBackend.cpp.o
[ 76%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/resource_handle.pb.cc.o
Scanning dependencies of target MNN_CL
[ 77%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/backend/VulkanTensor.cpp.o
[ 77%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/ResolveTfShapeN.cpp.o
[ 77%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/BufferConvertor.cpp.o
[ 77%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/BufferPool.cpp.o
[ 77%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/tensor.pb.cc.o
[ 77%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/compiler/AllShader.cpp.o
[ 77%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/compiler/VulkanShaderMap.cpp.o
[ 78%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/ImageBufferConvertor.cpp.o
[ 78%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanBuffer.cpp.o
[ 78%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/ImagePool.cpp.o
[ 78%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/tensor_shape.pb.cc.o
[ 78%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformBatchNormal.cpp.o                                       [ 78%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformGroupConvolution.cpp.o
[ 78%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformIm2Seq.cpp.o
[ 78%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/OpenCLBackend.cpp.o
[ 79%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformInnerProduct.cpp.o
/root/MNN/express/Expr.cpp: In static member function ‘static void MNN::Express::Variable::save(const std::vector<MNN::Express::VARP>&, MNN::NetT*)’:
/root/MNN/express/Expr.cpp:24:24: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
   24 |     snprintf(s, 10, "%d", index);
      |                        ^
In file included from /usr/include/stdio.h:867,
                 from /usr/include/c++/9/cstdio:42,
                 from /usr/include/c++/9/ext/string_conversions.h:43,
                 from /usr/include/c++/9/bits/basic_string.h:6493,
                 from /usr/include/c++/9/string:55,
                 from /usr/include/c++/9/stdexcept:39,
                 from /usr/include/c++/9/array:39,
                 from /usr/include/c++/9/tuple:39,
                 from /usr/include/c++/9/functional:54,
                 from /root/MNN/include/MNN/expr/Expr.hpp:12,
                 from /root/MNN/express/Expr.cpp:10:
/usr/include/aarch64-linux-gnu/bits/stdio2.h:67:35: note: ‘__builtin___snprintf_chk’ output between 2 and 11 bytes into a destination of size 10
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    [ 79%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanCommandPool.cpp.o    [ 79%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/types.pb.cc.o                          [ 79%] Building CXX object express/CMakeFiles/MNN_Express.dir/Optimizer.cpp.o                                   [ 79%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanDevice.cpp.o         [ 79%] Building CXX object express/CMakeFiles/MNN_Express.dir/Utils.cpp.o                                       [ 79%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/OpenCLRunningUtils.cpp.o            [ 79%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanFence.cpp.o          [ 79%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanImage.cpp.o          [ 80%] Building CXX object tools/converter/CMakeFiles/MNNConverterTF.dir/versions.pb.cc.o                       [ 80%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/runtime/OpenCLRuntime.cpp.o         [ 80%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/runtime/OpenCLWrapper.cpp.o         [ 80%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformOnnxPad.cpp.o
[ 81%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanInstance.cpp.o
[ 81%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanMemoryPool.cpp.o
[ 82%] Building CXX object express/CMakeFiles/MNN_Express.dir/module/IfModule.cpp.o
[ 82%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanPipeline.cpp.o
[ 82%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/component/VulkanSemaphore.cpp.o
[ 82%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/postconvert/TransformShuffleChannel.cpp.o                                    In file included from /root/MNN/source/core/Macro.h:11,
                 from /root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.hpp:23,
                 from /root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:9:
/root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp: In member function ‘std::pair<const void*, long unsigned int> MNN::OpenCLRuntime::makeCache()’:
/root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:436:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘std::vector<long unsigned int, std::allocator<long unsigned int> >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
  436 |             MNN_ERROR("Can't load binary, binarySize:%d, deviceSize:%d\n", binSizes.size(), devices.size());
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~                    |                                                                                         |
      |                                                                                         std::vector<long unsigned int, std::allocator<long unsigned int> >::size_type {aka long unsigned int}
/root/MNN/include/MNN/MNNDefine.h:28:39: note: in definition of macro ‘MNN_ERROR’
   28 | #define MNN_ERROR(format, ...) printf(format, ##__VA_ARGS__)
      |                                       ^~~~~~
/root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:436:55: note: format string is defined here
  436 |             MNN_ERROR("Can't load binary, binarySize:%d, deviceSize:%d\n", binSizes.size(), devices.size());
      |                                                      ~^                                                       |                                                       |
      |                                                       int
      |                                                      %ld
In file included from /root/MNN/source/core/Macro.h:11,
                 from /root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.hpp:23,
                 from /root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:9:
/root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:436:23: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘std::vector<cl::Device, std::allocator<cl::Device> >::size_type’ {aka ‘long unsigned int’} [-Wformat=]
  436 |             MNN_ERROR("Can't load binary, binarySize:%d, deviceSize:%d\n", binSizes.size(), devices.size());
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   ~~~~~~~~~~~~~~
      |                                                 
      |                                                                                                        std::vector<cl::Device, std::allocator<cl::Device> >::size_type {aka long unsigned int}                          /root/MNN/include/MNN/MNNDefine.h:28:39: note: in definition of macro ‘MNN_ERROR’
   28 | #define MNN_ERROR(format, ...) printf(format, ##__VA_ARGS__)
      |                                       ^~~~~~
/root/MNN/source/backend/opencl/core/runtime/OpenCLRuntime.cpp:436:70: note: format string is defined here
  436 |             MNN_ERROR("Can't load binary, binarySize:%d, deviceSize:%d\n", binSizes.size(), devices.size());
      |                                                                     ~^
      |                                                                      |
      |                                                                      int
      |                                                                     %ld
[ 82%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFApproximateEqual.cpp.o
Scanning dependencies of target MNN_GL
[ 82%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanBasicExecution.cpp.o
[ 82%] Building CXX object express/CMakeFiles/MNN_Express.dir/module/Module.cpp.o
[ 82%] Building CXX object source/backend/opengl/CMakeFiles/MNN_GL.dir/AllShader.cpp.o
[ 82%] Built target MNNConverterTF
[ 82%] Building CXX object express/CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o
[ 82%] Building CXX object source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBackend.cpp.o
[ 83%] Building CXX object source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBinary.cpp.o
In file included from /root/MNN/source/backend/opengl/GLProgram.hpp:13,                                                          from /root/MNN/source/backend/opengl/GLBinary.hpp:12,
                 from /root/MNN/source/backend/opengl/GLBinary.cpp:9:
/root/MNN/source/backend/opengl/GLHead.hpp:28:10: fatal error: GL/glew.h: No such file or directory
   28 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [source/backend/opengl/CMakeFiles/MNN_GL.dir/build.make:89: source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBinary.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/MNN/source/backend/opengl/GLSSBOBuffer.hpp:12,
                 from /root/MNN/source/backend/opengl/GLBackend.cpp:11:
/root/MNN/source/backend/opengl/GLHead.hpp:28:10: fatal error: GL/glew.h: No such file or directory
   28 | #include <GL/glew.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [source/backend/opengl/CMakeFiles/MNN_GL.dir/build.make:76: source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBackend.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:788: source/backend/opengl/CMakeFiles/MNN_GL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanBinary.cpp.o
[ 83%] Building CXX object express/CMakeFiles/MNN_Express.dir/module/StaticModule.cpp.o
[ 83%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/BinaryBufExecution.cpp.o
[ 84%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/ConvBufExecution.cpp.o
[ 84%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFArgMaxMerge.cpp.o                                                  [ 84%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/ConvBufWinograd.cpp.o   [ 84%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/DeconvBufExecution.cpp.o[ 84%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanConvolution.cpp.o    [ 85%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanConvolutionImpl.cpp.o
[ 85%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFBatchNormalMerge.cpp.o                                             [ 85%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFBatchToSpaceND.cpp.o
[ 85%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFClip.cpp.o
[ 85%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/DepthwiseConvBufExecution.cpp.o
[ 85%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/InterpBufExecution.cpp.o
[ 85%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/MatmulBufExecution.cpp.o
[ 85%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanConvolutionWinograd.cpp.o
[ 85%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanDeconvolution.cpp.o  [ 86%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFConcatMerge.cpp.o                                                  [ 86%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanDeconvolutionDepthwise.cpp.o
[ 86%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanImageConverter.cpp.o
[ 86%] Building CXX object express/CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o
[ 86%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanInterp.cpp.o         [ 86%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/PoolBufExecution.cpp.o  [ 86%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFConvolution3DMerge.cpp.o
[ 86%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanMatMul.cpp.o         [ 86%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanMatrixMultier4x4.cpp.o
[ 86%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFConvolutionMerge.cpp.o                                             [ 86%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/RasterBufExecution.cpp.o
[ 87%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/ReductionBufExecution.cpp.o                                                     [ 87%] Linking CXX shared library libMNN_Express.so
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanPool.cpp.o
[ 88%] Built target MNN_Express
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/ReluBufExecution.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/ScaleBufExecution.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/SoftmaxBufExecution.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/UnaryBufExecution.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanROIPooling.cpp.o
[ 88%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFCustomDequantize.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/cl/opencl_program.cc.o
[ 88%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFCustomQuantize.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanRaster.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanReduce.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanRelu.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanResize.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/CommonExecution.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanScale.cpp.o
[ 88%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanSoftmax.cpp.o
[ 88%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFDense.cpp.o
[ 88%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/Conv2DBackPropFilter.cpp.o
[ 89%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanSpatialProduct.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ConvExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ConvWinograd.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ConvertExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/DeconvExecution.cpp.o
[ 90%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanUnary.cpp.o
[ 90%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFExtraManager.cpp.o
[ 91%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFExtraOp.cpp.o
[ 91%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/runtime/VulkanRuntime.cpp.o
[ 91%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFIsFinite.cpp.o                                                     [ 91%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFPrelu.cpp.o
[ 91%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSliceMerge.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/DepthwiseConvExecution.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/DepthwiseDeconvExecution.cpp.o
[ 91%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSoftplus.cpp.o
[ 91%] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/runtime/vulkan_wrapper.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/EltwiseExecution.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/InterpExecution.cpp.o
[ 91%] Linking CXX shared library libMNN_Vulkan.so      [ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/LrnExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/MatmulExecution.cpp.o
[ 92%] Built target MNN_Vulkan                          [ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/MultiInputDWConvExecution.cpp.o
[ 92%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSoftsign.cpp.o
[ 92%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/BinaryActivation.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/MultiInputDWDeconvExecution.cpp.o
[ 92%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/FullConnect.cpp.o
[ 93%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/TFliteBatchToSpace.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/NormalizeExecution.cpp.o
[ 93%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tflitextra/TFliteExtraManager.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/PoolExecution.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/RasterExecution.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ReductionExecution.cpp.o
[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ReluExecution.cpp.o
[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/RoiPoolingExecution.cpp.o[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ScaleExecution.cpp.o
[ 94%] Built target MNNConverterOpt
[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/SoftmaxExecution.cpp.o
[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/TrainableParamExecution.cpp.o
[ 94%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/UnaryExecution.cpp.o
[ 94%] Linking CXX shared library libMNN_CL.so
[ 94%] Built target MNN_CL                              make: *** [Makefile:130: all] Error 2
root@localhost:~/MNN/build#
![Screenshot_2021-05-18-19-03-45-378_com termux](https://user-images.githubusercontent.com/72664192/118660448-d6090b00-b80b-11eb-810d-e4d3c279ef36.jpg)
![Screenshot_2021-05-18-19-03-35-610_com termux](https://user-images.githubusercontent.com/72664192/118660458-d86b6500-b80b-11eb-87d0-0d0019fa3cbf.jpg)

**Comment by jxt1234** [comment]
mnn - opengl is only valid for Android 5.0 + , not support linux / mac / windows

**Comment by Saikatsaha1996** [comment]
> mnn - opengl is only valid for Android 5.0 + , not support linux / mac / windows

In my device already OpenCL , vulkan, OpenGL all available

But I want to increase performance that's why I want to install

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-04-26-16-33-58-406_com termux](https://user-images.githubusercontent.com/72664192/118750721-95e27080-b87d-11eb-9844-413e785630b1.jpg)

**Comment by Saikatsaha1996** [comment]
I got error for c/c++ clang version
But for termux gcc not available
That's why MNN not findings OpenCL, OpenGL, vulkan 






Please add support for compiler "clang"

**Comment by jxt1234** [comment]
mnn's opengl use opengl es , which is for embedding device. Your device support "OPENLGL" but not "OPENGL ES". You can use  mnn's opencl or vulkan for gpu accelation

**Comment by jxt1234** [comment]
For the purpose to use opengl es in PC , you can install angle. https://github.com/google/angle
