### ISSUE TITLE
OpenCL version

### ISSUE THREAD

**Issue by ohyes158** [alibaba/MNN#1481]
HI all:
We Just want to know whether the MNN support OpenCL 1.1?
Just Now Which version of OpenCL are you using for MNN 1.1.6

Thanks

**Comment by ohyes158** [comment]
我们现在使用的是德州仪器的AM5728芯片，支持OpenCL 1.1版本，我们打算将MNN推理引擎移植到AM5728。
因此我们想要知道MNN 1.1.6是否支持OpenCL 1.1版本，如果支持的话，是否还需要修改代码或者更新配置。

 期待您的回复
多谢

**Comment by jxt1234** [comment]
支持的

**Comment by ohyes158** [comment]
多谢回复，既然支持OpenCL 1.1版本，咱们MNN需要修改宏或者配置选项吗？
下面这个宏#define CL_TARGET_OPENCL_VERSION 200表示的什么意思？
#define CL_TARGET_OPENCL_VERSION 200
#define CL_HPP_TARGET_OPENCL_VERSION 110
#define CL_HPP_MINIMUM_OPENCL_VERSION 110

#if !defined(_MSC_VER)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wignored-attributes"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#include "CL/cl2.hpp"
#pragma GCC diagnostic pop
#else
#include "CL/cl2.hpp"
#endif

多谢

**Comment by jxt1234** [comment]
这个是 C++ 头文件的封装，mnn 没有用到 1.0 以上的 api ，影响不大

**Comment by ohyes158** [comment]
明白了，多谢多谢
