### ISSUE TITLE
Segmentation fault with quantized model

### ISSUE THREAD

**Issue by CW-B-W** [alibaba/MNN#1485]
# Problem Description

Segmentation fault when using `timeProfile.out` with [quantized Yolo-Fastest MNN Model](https://github.com/CW-B-W/Yolo-Fastest-MNN/blob/main/model/yolofastest-quant.mnn) converted by myself

Besides, malloc failed when using quantized model to do inference

(No error happened with the original [Yolo-Fastest MNN Model](https://github.com/geekzhu001/Yolo-Fastest-MNN/blob/main/model/yolofastest.mnn))

Thanks for your kindly help!

#### Output of `timeProfile.out`:
```
$ ./timeProfile.out ./quantization/yolofastest-quant.mnn

Open Model ./quantization/yolofastest-quant.mnn
Segmentation fault

$
```

#### C++ code snippet for getting inference output
(Failed at the second line to the last)
```cpp
interpreter->resizeTensor(input_tensor, {1, 3, INPUT_SIZE, INPUT_SIZE}); //输入tensor格式NCHW

interpreter->resizeSession(session);

std::shared_ptr<MNN::CV::ImageProcess> pretreat(
    MNN::CV::ImageProcess::create(MNN::CV::BGR, MNN::CV::RGB, mean_vals, 3, norm_vals, 3));
pretreat->convert(frame.data, INPUT_SIZE, INPUT_SIZE, 0, input_tensor);

interpreter->runSession(session);

std::string scores  = "layer125-conv";
std::string scores2 = "layer115-conv";

MNN::Tensor *tensor_scores  = interpreter->getSessionOutput(session, scores.c_str());
MNN::Tensor *tensor_scores2 = interpreter->getSessionOutput(session, scores2.c_str());
    
auto tensor_scores_host = new Tensor(tensor_scores, MNN::Tensor::TENSORFLOW);//NHWC
tensor_scores->copyToHostTensor(tensor_scores_host);

/* !!!!! Failing here !!!!! */
auto tensor_scores_host2 = new Tensor(tensor_scores2, MNN::Tensor::TENSORFLOW);
/* !!!!! Failed !!!!! */
tensor_scores2->copyToHostTensor(tensor_scores_host2);
```
##### With error message
```
yolo: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```

## Quantize Method
```
$ ./quantized.out yolofastest.mnn yolofastest-quant.mnn conf.json
```
With [yolofastest.mnn](https://github.com/geekzhu001/Yolo-Fastest-MNN/blob/main/model/yolofastest.mnn)
With [Calibration Images](https://github.com/nihui/imagenet-sample-images)
With conf.json file shown below
```
{
    "format":"RGB",
    "mean":[
        127.5,
        127.5,
        127.5
    ],
    "normal":[
        0.00784314,
        0.00784314,
        0.00784314
    ],
    "width":320,
    "height":320,
    "path":"./images",
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS"
}
```

# Platform(Include target platform as well if cross-compiling):  
Raspberry Pi 4B
```
$ lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            270.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

# Github Version:
2021.05.08
[3ab8725: Merge pull request #1395 from WillTao-RD/master](https://github.com/alibaba/MNN/tree/3ab8725569fae5671185afec3c3a90c016a62156)

# Compiling Method
Was compiled on target platform Raspberry Pi 4B
```
$ cmake -D CMAKE_BUILD_TYPE=Release \
        -D MNN_BUILD_QUANTOOLS=ON \
        -D MNN_BUILD_CONVERTER=ON \
        -D MNN_BUILD_DEMO=ON \
        -D MNN_BUILD_BENCHMARK=ON ..
```

**Comment by CW-B-W** [comment]
> # Problem Description
> Segmentation fault when using `timeProfile.out` with [quantized Yolo-Fastest MNN Model](https://github.com/CW-B-W/Yolo-Fastest-MNN/blob/main/model/yolofastest-quant.mnn) converted by myself
> 
> Besides, malloc failed when using quantized model to do inference
> 
> (No error happened with the original [Yolo-Fastest MNN Model](https://github.com/geekzhu001/Yolo-Fastest-MNN/blob/main/model/yolofastest.mnn))
> 
> Thanks for your kindly help!
> 
> #### Output of `timeProfile.out`:
> ```
> $ ./timeProfile.out ./quantization/yolofastest-quant.mnn
> 
> Open Model ./quantization/yolofastest-quant.mnn
> Segmentation fault
> 
> $
> ```
> 
> #### C++ code snippet for getting inference output
> (Failed at the second line to the last)
> 
> ```c++
> interpreter->resizeTensor(input_tensor, {1, 3, INPUT_SIZE, INPUT_SIZE}); //输入tensor格式NCHW
> 
> interpreter->resizeSession(session);
> 
> std::shared_ptr<MNN::CV::ImageProcess> pretreat(
>     MNN::CV::ImageProcess::create(MNN::CV::BGR, MNN::CV::RGB, mean_vals, 3, norm_vals, 3));
> pretreat->convert(frame.data, INPUT_SIZE, INPUT_SIZE, 0, input_tensor);
> 
> interpreter->runSession(session);
> 
> std::string scores  = "layer125-conv";
> std::string scores2 = "layer115-conv";
> 
> MNN::Tensor *tensor_scores  = interpreter->getSessionOutput(session, scores.c_str());
> MNN::Tensor *tensor_scores2 = interpreter->getSessionOutput(session, scores2.c_str());
>     
> auto tensor_scores_host = new Tensor(tensor_scores, MNN::Tensor::TENSORFLOW);//NHWC
> tensor_scores->copyToHostTensor(tensor_scores_host);
> 
> /* !!!!! Failing here !!!!! */
> auto tensor_scores_host2 = new Tensor(tensor_scores2, MNN::Tensor::TENSORFLOW);
> /* !!!!! Failed !!!!! */
> tensor_scores2->copyToHostTensor(tensor_scores_host2);
> ```
> 
> ##### With error message
> ```
> yolo: malloc.c:2385: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
> Aborted
> ```
> 
> ## Quantize Method
> ```
> $ ./quantized.out yolofastest.mnn yolofastest-quant.mnn conf.json
> ```
> 
> With [yolofastest.mnn](https://github.com/geekzhu001/Yolo-Fastest-MNN/blob/main/model/yolofastest.mnn)
> With [Calibration Images](https://github.com/nihui/imagenet-sample-images)
> With conf.json file shown below
> 
> ```
> {
>     "format":"RGB",
>     "mean":[
>         0.0,
>         0.0,
>         0.0
>     ],
>     "normal":[
>         0.0039,
>         0.0039,
>         0.0039
>     ],
>     "width":320,
>     "height":320,
>     "path":"./images",
>     "feature_quantize_method":"KL",
>     "weight_quantize_method":"MAX_ABS"
> }
> ```
> 
> # Platform(Include target platform as well if cross-compiling):
> Raspberry Pi 4B
> 
> ```
> $ lscpu
> Architecture:        armv7l
> Byte Order:          Little Endian
> CPU(s):              4
> On-line CPU(s) list: 0-3
> Thread(s) per core:  1
> Core(s) per socket:  4
> Socket(s):           1
> Vendor ID:           ARM
> Model:               3
> Model name:          Cortex-A72
> Stepping:            r0p3
> CPU max MHz:         1500.0000
> CPU min MHz:         600.0000
> BogoMIPS:            270.00
> Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
> ```
> 
> # Github Version:
> 2021.05.08
> [3ab8725: Merge pull request #1395 from WillTao-RD/master](https://github.com/alibaba/MNN/tree/3ab8725569fae5671185afec3c3a90c016a62156)
> 
> # Compiling Method
> Was compiled on target platform Raspberry Pi 4B
> 
> ```
> $ cmake -D CMAKE_BUILD_TYPE=Release \
>         -D MNN_BUILD_QUANTOOLS=ON \
>         -D MNN_BUILD_CONVERTER=ON \
>         -D MNN_BUILD_DEMO=ON \
>         -D MNN_BUILD_BENCHMARK=ON ..
> ```

**Comment by jxt1234** [comment]
I can't reproduce it by latest version, may has been fixed.
