### ISSUE TITLE
armv8.2 fp16为什么不能运行exynos 9810芯片上？

### ISSUE THREAD

**Issue by intwxw** [alibaba/MNN#1487]
// CPURuntime.cpp
    if ((isa_features & fp16arith_mask) == fp16arith_mask) {
        if (chipset.series == cpuinfo_arm_chipset_series_samsung_exynos && chipset.model == 9810) {
            cpuinfo_isa->fp16arith = false;
        } else {
            cpuinfo_isa->fp16arith = true;
        }
    }

请问armv8.2 fp16为什么不能运行exynos 9810芯片上？
可否能说一下具体原因吗？谢谢！🙏

**Comment by jxt1234** [comment]
cat /proc/cpuInfo 看一下是否有 simdhp

**Comment by jxt1234** [comment]
另外记得有一个系统是大核支持 fp16 但小核不支持，这种情况下没有支持
