### ISSUE TITLE
同一个模型在 移动端和Mac上运行正常  在Windows上运行报错 

### ISSUE THREAD

**Issue by wanglelewang** [alibaba/MNN#1488]
# 平台(如果交叉编译请再附上交叉编译目标平台):   Windows

# Github版本:   https://github.com/alibaba/MNN/releases/tag/1.1.0  下载的Windows版本

报错信息： Error in CPUTensorConver

**Comment by wanglelewang** [comment]
Error in CPUTensorConver

**Comment by wanglelewang** [comment]
Error in CPUTensorConver
Error in CPUBackend::onCopyBuffer

**Comment by wanglelewang** [comment]
有人吗

**Comment by jxt1234** [comment]
windows 自己编译试下？

**Comment by wanglelewang** [comment]
试了一个版本 不行 采用的你们提供的      我再试一遍

**Comment by wanglelewang** [comment]
才

**Comment by Zer0n1-coder** [comment]
> 
![6CE074C3-3835-47d2-B58D-803225E773BF](https://user-images.githubusercontent.com/63442532/119291520-2acfda00-bc81-11eb-8a66-530f9ead1c5f.png)

**Comment by Zer0n1-coder** [comment]
@jxt1234  按照你说的用了最新的库，出现的错误！

**Comment by wanglelewang** [comment]
?

**Comment by wanglelewang** [comment]
有人吗

**Comment by aSmallsheep** [comment]
> 有人吗
解决了吗?我也遇到这个问题

**Comment by wanglelewang** [comment]
还没有解决  等官方人回复吧😹

**Comment by jxt1234** [comment]
> @jxt1234 按照你说的用了最新的库，出现的错误！

这个看上去是使用的问题，你代码发来看下?

**Comment by wanglelewang** [comment]
![image](https://user-images.githubusercontent.com/20278050/121639600-5ba47180-cabf-11eb-810e-39c6a39a2adb.png)

@jxt1234  在加载模型的时候就出错了 是因为windows上模型格式的兼容问题吗

**Comment by wanglelewang** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/20278050/122659803-1ca4a900-d1ae-11eb-8327-9e7b3309c027.png">

@jxt1234   @aSmallsheep   问题已解决
