### ISSUE TITLE
output dim denpends on value of a tensor in inference 动态维度， 输出维度不仅仅取决于输入，还取决于inference过程中的某个tensor的value，MNN支持这种吗 

### ISSUE THREAD

**Issue by Liujingxiu23** [alibaba/MNN#1494]
tensor expand dynamicly, tensor dim depend on tensor value 

My workflow:
Train torch model -> export as *.onnx model -> convert to  *.mnn model

The key op that I can not convert successfully is “torch.repeat_interleave” which expand tensor A to tensor B depands on the values of tensor C.  Since torch.onnx did not support repeat_interleave, I relized "repeat_interleave" myself. Some of the code:

max_len = C.sum(dim=1)
*** some code ***
range_ = torch.arange(max_len)[None, :, None]
mult = torch.eq(reps_cumsum[:, :, :-1] <= range_, reps_cumsum[:, :, 1:] > range_)
B = torch.matmul(mult, A)

The onnx model can be exported sucessfully and the model can do inference correctly. But the *.mnn can be converted successfully, without any error, but when run by C++ api:

mnnNet->resizeTensor(*)
mnnNet->resizeTensor(*)
mnnNet->resizeSession(session);

The code core dump at "resizeSession".  

My question is, since the final dim of tensor B depend on the **value** of tensor C.
Is this the reason of "core dump"? Does MNN support this kind of operation?
Or will  "sizeseesion" determine the dims of every tensor ? 
If yes, how can i relized this ?

**Comment by tianchaolangzi** [comment]
+1

**Comment by jxt1234** [comment]
支持的，但需要用新的 API，两种方法：
1、采用 MNN::Express::Module 加载运行，可参考 demo/exec/transformerDemo.cpp ，推荐这种方案
2、在 createSession 之前，调 net->setSessionMode(Interpreter::Session_Input_User) ，每次运行按如下步骤：
（1）对所有输入执行 resizeTensor ，同旧API
（2）对所有输入赋值自己的数据指针 inputTensor->buffer().host = User_Ptr （主要差别点）
（3）调 net->resizeSession
（4）调 net->runSession

**Comment by Liujingxiu23** [comment]
@jxt1234  使用了第一种方式 可以！ 多谢

**Comment by Liujingxiu23** [comment]
@jxt1234 
你好，我使用你说的第一种方式，新的API，新建一个小工程example，是完全没问题的。
libMNN.so和libMNN_Expression.so和example.cpp等就放在同一个文件夹。

但是当我想把相关的代码，加入现有的一个大工程时候，我将这两个so文件放在一个lib文件夹。
提示错误：undefined reference to `MNN::Express::Module::load(***）
我发现libMNN_Expression.so依赖libMNN.so，且rpath为我编译MNN时候的绝对路径，于是我使用patchref修改libMNN_Expression.so的runpath为$ORIGAN. 但是依然出现上述错误。
即便我将lib文件夹的路径加入到LD_LIBRARY_PATH，依然有上述错误。

请问我该怎么办？

**Comment by jxt1234** [comment]
这个感觉是你工程配置的问题，如果解决不了的话，可以用下面这个简单的解决方案：
设 MNN_SEP_BUILD=false ，这样 express 和 mnn 合并为一个 so

**Comment by Liujingxiu23** [comment]
@jxt1234  谢谢你的回复!
按照你的建议，编译成了一个libMNN.so，问题依然存在呢
std::shared_ptr<Module> model;
Module::Config config;
model.reset(Module::load({"input1", "input2", "input3"},
                         {"output"},
                          "model_path"));




 undefined reference to `MNN::Express::Module::load(std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, char const*, MNN::Express::Module::Config const*)'

你看能看出来问题吗?

**Comment by Liujingxiu23** [comment]
@jxt1234
额 我又遇到问题 来求助了。。

我的应用领域是语音合成（Text to speech）， 输入文本，合成声学特征。
输入文本是变长的，输出wav也是变长的。
即如下phones和mels都包含动态轴， 且mels的长度与phones的长度不是直接成比例的关系。

按照你说的新的接口形式，我完成了类似如下代码：
初始化：Init(model_path)：
model = Module::load({"phones"}, {"mels"}, model_path.c_str());

Inference(model, inputs, output){
auto phones = Input({1, seq_len}, NHWC, halide_type_of());
memcpy(...)
vector outputs = model->onForward({phones});
....
}

我遇到的问题是：
假如我要依次合成2句话，输入为text1, text2, text1和text2内容不同，我调用：
Init(***);
Inference(text1)
Inference(text2)

1.如果text1和text2输出的维度不同，即mels的dim不同，则输出正常
2.如果text1和text2输入的维度相同，但输出mels的维度不同，输出也正常
3.如果text1和text2的“输出”维度是一样的，比如都是[1, 80, 124], 虽然两次输出的维度相同，但由于输入的具体内容是不同的，预期的输出具体内容也不同。但是我运行得到的结果是， text2的输出同text1的输出也完全一致。

也就是说，当连续两次调用，输出维度一样时，即便输入不同，第二次的输出结果同第一次完全相同。

我尝试:
1）每次Inference后，model->clearCache();， 没有作用
2) 每次Inference前，Module* model2 = Module::clone(model);， model2->onForward;
有效果，运行正常。但是clone耗费时间。

请问我该如何解决这个问题？

**Comment by jxt1234** [comment]
像是没有触发 resize ，之前是有这个问题，看看更新后看看能不能解决？

**Comment by Liujingxiu23** [comment]
@jxt1234 我这边唯一不匹配的就是mnnconvert用的python安装的1.1.4的版本，但是推理用的1.1.7（https://github.com/alibaba/MNN/releases/tag/1.1.7）

因此我重新从源码编译了MNNConvert， 保证它的版本与推理Forward的版本一致，都是1.1.7.
但是依然有这个问题。

你说的“更新”是指这个不？ 我看1.1.7已经是最新的版本了

**Comment by jxt1234** [comment]
是推理引擎更新到 1.2.0 ，或者你可以自己改一下 express/module/StaticModule.cpp 
把 setNeedMalloc 改成 setNeedResize

**Comment by Liujingxiu23** [comment]
@jxt1234  按照你说自己改了下express/module/StaticModule.cpp 可以解决呢。 谢谢你！
