### ISSUE TITLE
编译Android库，32位无法编译，64位正常

### ISSUE THREAD

**Issue by friskyliu** [alibaba/MNN#1495]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
系统: Ubuntu 18.04
NDK 版本: android-ndk-r21e
CMake:  3.10.2

# Github版本:
# Github Version: MNN-1.1.7

# 编译日志:
# Build Log:
somebody@ubuntu:~/Desktop/99_share/MNN-1.1.7/project/android/build_32$ ../build_32.sh
-- The ASM compiler identification is unknown
-- Found assembler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- broken
CMake Error at /usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/home/liubo/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:
.....
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_4dd15.dir/build.make:97: recipe for target 'cmTC_4dd15' failed
    make[1]: *** [cmTC_4dd15] Error 1
    make[1]: Leaving directory '/mnt/hgfs/99_share/MNN-1.1.7/project/android/build_32/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_4dd15/fast' failed
    make: *** [cmTC_4dd15/fast] Error 2

    

somebody@ubuntu:~/Desktop/99_share/MNN-1.1.7/project/android$ mkdir build_64 && cd build_64 && ../build_64.sh
-- The ASM compiler identification is Clang
-- Found assembler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/somebody/Work/ndk/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Use Threadpool, forbid openmp
..........

**Comment by jxt1234** [comment]
这个看上去是 ndk 的问题

**Comment by friskyliu** [comment]
> 这个看上去是 ndk 的问题

从NDK 20， 21， 22三个版本都试过，就32位无法正常编译， clang检查不通过

**Comment by friskyliu** [comment]
是gcc和g++路径的问题，指定下路径就可以了

#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-14  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
**-DCMAKE_C_COMPILER=/usr/bin/gcc \
-DCMAKE_CXX_COMPILER=/usr/bin/g++ \**
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
