### ISSUE TITLE
onnx的算子不支持：These Op Not Support: ONNX::GreaterOrEqual

### ISSUE THREAD

**Issue by tianchaolangzi** [alibaba/MNN#1496]
模型从torch转onnx再转mnn，在转onnx时设置了opset_version=12后torch.ge会转为ONNX::GreaterOrEqual，再转mnn就不支持了。看了一下，在opset_version=9时torch.ge会转为ONNX::NOT 和ONNX::LESS，再转mnn就可以。。。但是模型别的算子需要opset_version=12所以催促大佬们赶紧支持onnx opset12的算子吧。还有cumsum这个算子也是。

**Comment by jxt1234** [comment]
收到了，GreaterOrEqual 最近会同步，不过自己修改下 tools/converter/source/onnx/BinaryOpOnnx.cpp 也不麻烦

**Comment by jxt1234** [comment]
CUMSUM 还需要看一下，应该会排在 loop 之后...

**Comment by jxt1234** [comment]
已经添加 GreaterOrEqual , cumsum 在其他 issue 有提，后续跟进
