### ISSUE TITLE
GPU运行crash

### ISSUE THREAD

**Issue by wanglelewang** [alibaba/MNN#1497]
# 平台(如果交叉编译请再附上交叉编译目标平台):   iOS 

# Github版本:
# Github Version:1.2.0

-[MTLDebugComputeCommandEncoder setComputePipelineState:]:243: failed assertion `computePipelineState must not be nil.'

**Comment by wanglelewang** [comment]
![Uploading image.png…]()

**Comment by wanglelewang** [comment]
源码 依赖之后  错误信息

**Comment by wanglelewang** [comment]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/20278050/120096729-b48b1600-c15f-11eb-8fbd-5500a8f388e1.png">

**Comment by wanglelewang** [comment]
我这边的问题解决了 步骤如下
1. 输入的时候 按照模型的输入格式走(或者自定义OP支持不同格式的转换)

**Comment by wanglelewang** [comment]
1. 输入的获取 在GPU上需要 额外做一次 copyTo  才能读到 Tensor中的 host里面的数据

**Comment by xisi789** [comment]
> 我这边的问题解决了 步骤如下
> 
> 1. 输入的时候 按照模型的输入格式走(或者自定义OP支持不同格式的转换)
>    2.输入的获取 在GPU上需要 额外做一次 copyTo  才能读到 Tensor中的 host里面的数据

大佬，我也遇到了同样的问题，但我有点不太明白您这两个步骤具体是怎么做的。我的数据相关代码如下，在runSession时出错：
![image](https://user-images.githubusercontent.com/41114558/123222460-8ef4f080-d502-11eb-827d-a4bfa8fde2e2.png)

**Comment by xisi789** [comment]
> 我这边的问题解决了 步骤如下
> 
> 1. 输入的时候 按照模型的输入格式走(或者自定义OP支持不同格式的转换)
>    2.输入的获取 在GPU上需要 额外做一次 copyTo  才能读到 Tensor中的 host里面的数据

大佬，我也遇到了同样的问题，但我有点不太明白您这两个步骤具体是怎么做的。我的数据相关代码如下，在runSession时出错：
![image](https://user-images.githubusercontent.com/41114558/123223327-65889480-d503-11eb-951a-e7dcb7a14cba.png)

**Comment by wanglelewang** [comment]
3. 需要源码依赖MNN的最新代码 或者重新编一个最新版本的
