### ISSUE TITLE
plan to support mxnet converter?

### ISSUE THREAD

**Issue by onexuan** [alibaba/MNN#15]
plan to support mxnet converter?

**Comment by nihui** [comment]
mxnet -> onnx -> mnn

**Comment by onexuan** [comment]
> mxnet -> onnx -> mnn
I think that it is not a good way. 
Ncnn Author

**Comment by li-qing** [comment]
Not plan to support MXNet directly.

What is the problem with MXNet -> ONNX -> MNN ?

**Comment by onexuan** [comment]
> Not plan to support MXNet directly.
> 
> What is the problem with MXNet -> ONNX -> MNN ?

no problem! convenient

**Comment by fanwenyang** [comment]
Where can I find  a useful converter of mxnet2onnx?  I've once downloaded a python file from mxnet web,but i failed to convert my mxnet models. Does anybody know the meaning of the "Input shape of the model"?
