### ISSUE TITLE
Exception: initMNN: init numpy failed

### ISSUE THREAD

**Issue by Hawrkw** [alibaba/MNN#1500]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
暂时可以升级 numpy 到 1.2.0 解决

**Comment by Ryuk17** [comment]
> 暂时可以升级 numpy 到 1.2.0 解决

你好，1.1.7版本对应的numpy是什么版本呢，试了好几个版本都报initMNN: init numpy failed这个错误
![image](https://user-images.githubusercontent.com/22525811/173519957-c8b57e2b-79b8-4072-ba0d-43176decec1b.png)

**Comment by jxt1234** [comment]
升级 mnn 到 2.0.0 ，该问题应该已经修正了
