### ISSUE TITLE
多线程 + 动态输入维度 multithread + dynamic input dims

### ISSUE THREAD

**Issue by Liujingxiu23** [alibaba/MNN#1501]
想问下，如果是动态输入，输入大小不同时，都要resizeInput和resizeSession，那动态输入大小的时候， 是否支持多线程呢？ 如果支持，是如何实现的呢？

Does MNN support multithread  and dynamic input dims at the same time？

**Comment by jxt1234** [comment]
支持多线程的，resize 只是涉及一些资源申请（一般有相应资源池缓存），不影响并行

**Comment by Liujingxiu23** [comment]
@jxt 谢谢你的回复。我还有另一个疑问哈，不知能否帮我解答。
动态维度的情况， 输出维度不仅仅取决于输入，还取决于inference过程中的某个tensor的value，MNN支持这种吗？具体在：
https://github.com/alibaba/MNN/issues/1494

**Comment by jxt1234** [comment]
这种情况下由于 resizeTensor -> resizeSession 事实上已经不具备之前的意义了，需要采用 MNN::Express::Module 去运行，可参考 demo/exec/transformerDemo.cpp

**Comment by Liujingxiu23** [comment]
谢谢回复！了解了
