### ISSUE TITLE
请问动作识别模型（输入是多帧）应该怎么量化？

### ISSUE THREAD

**Issue by barbecacov** [alibaba/MNN#1502]
现在训练好的动作识别模型已经转成mnn了，输入是nchw，其中n不为1（我是将帧数t和batch size合并了），请问这样的模型该怎么写.josn，进行量化呢

**Comment by yyfcc17** [comment]
用这个 https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant

**Comment by barbecacov** [comment]
貌似pytorch2onnx的时候，没办法关闭merge bn。这个和你提供的这个工具里有点对冲了。

另外，我现在的mnn模型输入为(8，3，224，224），看似也是正常的呀。不知为啥正常量化行不通。

**Comment by yyfcc17** [comment]
1. 导出到onnx的时候，torch.onnx.export中设置 training=1即可保存BN
2. 不保存BN也可以用这个工具进行量化，只是精度可能没有保留BN的好

**Comment by barbecacov** [comment]
Reshape error: 75264 -> 602112。
这个正好是差了8倍。是不是虽然我是在.json里写的是batch_size为8 ，但读入的还是没办法以序列图片读进去呢

**Comment by barbecacov** [comment]
非常感谢回答，我这就尝试一下。另外官方可以出一个图片时序模型的demo，网上几乎找不到用mnn做时序的例子。

**Comment by barbecacov** [comment]
大致明白了这个工具是什么意思。就是需要自己重写一个dataset来适配这个图片序列的输入，是这样吗。也就是说可以直接把训练的dataset稍作修改拿过来用

**Comment by yyfcc17** [comment]
是的

**Comment by barbecacov** [comment]
你好。我按照这个工具里的说明做了。报错：
  File "mnn_offline_quant.py", line 72, in main
    dataloader = MNN.data.DataLoader(calibration_dataset, batch_size=batch_size, shuffle=True)
RuntimeError: Unable to cast from non-held to held instance (T& to Holder<T>) (compile in debug mode for type information)

我重新调整了mnn的输入为(1, 24, 224, 224)。

我在训练的dataset的__getitem__后面加
        process_data = process_data.numpy()
        dv = F.const(process_data.flatten().tolist(), [24, 224, 224], F.data_format.NCHW, F.dtype.float)
        return [dv], []
config.yaml里shapes是[1, 24, 224, 224]。


请问这是什么问题呢

**Comment by barbecacov** [comment]
现在用这个工具可以进行到跑进度条那一步了，进度条100%之后报错如下：
Epoch cost: 431.433 s.
Reshape error: 1354752 -> 602112

我的mnn模型输入为(1, 24, 224, 224)

请问会是什么问题呢

**Comment by yyfcc17** [comment]
已知bug，如果等不了，可以自己修复，然后源码编译。具体的，请在 express/NeuralNetWorkOp.cpp中，第1492，1528，1578行，这三处之后添加下面4行代码：
`
if (pads.size() == 2) {
    conv2D->common->padX        = pads[0];
    conv2D->common->padY        = pads[1];
} else {
    conv2D->common->pads = std::move(pads);
}
`

**Comment by barbecacov** [comment]
你们找bug的速度也太快了！，我还是等官方包吧。感谢答复

**Comment by barbecacov** [comment]
@yyfcc17 正常编译了mnn1.2.0的python版本后，如此量化操作后，进度条0%，还没train起来就报segment fault。mnn 1.1.4是可以正常跑完那个进度条，只不过报Reshape error。

**Comment by FinnSu** [comment]
> 貌似pytorch2onnx的时候，没办法关闭merge bn。这个和你提供的这个工具里有点对冲了。
> 
> 另外，我现在的mnn模型输入为(8，3，224，224），看似也是正常的呀。不知为啥正常量化行不通。

你好，麻烦问下，对于(8，3，224，224）的输入，我是用libtorch实现的，mnn支持这样的输入吗？如果支持的话怎么用mnn实现的啊？

**Comment by Ryuk17** [comment]
请问解决了吗，我也遇到了reshape error的问题[1950](https://github.com/alibaba/MNN/issues/1950)
