### ISSUE TITLE
如何获取模型节点的多维输出

### ISSUE THREAD

**Issue by bestpower** [alibaba/MNN#1503]
Android
7af23d29f43ad358f8f9e508e2edcdd15bfe17d5
cmake
-DMNN_BUILD_CONVERTER=true

原模型本身是多节点输出，且有的输出数据格式是多维数组，并需要对这些输出做整合计算才能得出最终的结果，通过MNNConvert工具将onnx模型转为mnn模型后，在安卓端进行推理验证，在获取输出节点数据时只能拿到float[]类型的一维数组数据，无法拿到多维数组类型的数据，参考语雀文档中的获取输出里也无法拿到对应的多维数组格式的数据，请问该如何解决？

**Comment by bestpower** [comment]
参照语雀文档：https://www.yuque.com/mnn/cn/output
中的代码：
auto outputTensor = interpreter->getSessionOutput(session, NULL);
auto nchwTensor = new Tensor(outputTensor, Tensor::CAFFE);
outputTensor->copyToHostTensor(nchwTensor);
auto score = nchwTensor->host<float>()[0];
auto index = nchwTensor->host<float>()[1];
// ...
delete nchwTensor;
其中nchwTensor对象仍是一维数组，在ncnn中是可以获取多维数组的，请问mnn中是否有类似的获取方式？

**Comment by yyfcc17** [comment]
没有。这个是底层的内存，数据你自己按照nchw解释即可
