### ISSUE TITLE
how to config if i have two models

### ISSUE THREAD

**Issue by Liujingxiu23** [alibaba/MNN#1504]
I have two mnn models,  somethings like encoder and decoder.
How can I do config of mnn models to improve the speed and avoid memory leak?
The two models is runned sequentially, first encoder and tehn decoder

**Comment by jxt1234** [comment]
Just create two interpreter and session. For sequentially model you can use same runtime for memory reuse. See https://www.yuque.com/mnn/cn/create_session 's "共享运行时资源"

**Comment by Liujingxiu23** [comment]
@jxt1234  谢谢回复！看到了
