### ISSUE TITLE
torch.cat  Compute Shape Error for

### ISSUE THREAD

**Issue by Liujingxiu23** [alibaba/MNN#1508]
torch.cat seem raises error info "Compute Shape Error for" . But the inference can do successfully.
how can I eliminate this info.  Does any error really occur?

**Comment by jxt1234** [comment]
Maybe your model don't has input shape(or the shape is 0), it may print error for the first time. But if you resizeTensor -> resizeSession, it won't cause error.

**Comment by Liujingxiu23** [comment]
谢谢回复，是有shape等于0
