### ISSUE TITLE
OCR中GRU的输出作为hidden layer再次输入的情况下如何获取GRU的输出

### ISSUE THREAD

**Issue by HIT123-C** [alibaba/MNN#1509]
![1](https://user-images.githubusercontent.com/83197894/120739661-693c8300-c524-11eb-9bea-7ba921722ca9.jpg)

如上图所示，decoder_attention转换为mnn后可以拿到输出值，但是decoder_hidden的结果无法通过，而进行for循环时需要该hidden的值作为下一次循环的输入 ，通过 net->getSessionOutput(decoder_session,"decoder_hidden");获得，显示没有这个输出，这块应该是被优化掉了，想问一下各位遇到这种情况是如何处理的呢，我常识了通过在网论运行时候暂存这个值，但是目前还没有很好的解决

**Comment by jxt1234** [comment]
多输出的问题应该已经修复了

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/blob/312b003f4c05b35d1306cea8a7234f658f849cee/source/backend/cpu/CPURNNSequenceGRU.cpp#L188
decoder_hidden有输出，用netron看下MNN模型结构，有两个输出，就getSessionOutpu(xxx, "xxx_hidden)，有一个输出就是和decoder_attention在一个tensor内

**Comment by HIT123-C** [comment]
谢谢回复，这块代码也看过，实际测试中指定hidden的名字的方法也是不行，我做的时候是发现在解析ONNX模型的时候，参数的数据排布方式有些问题导致了最后计算的结果有问题，后来利用mnn本身的计算库重新计算了一下。

**Comment by HIT123-C** [comment]
使用getSessionOutpu(xxx, "xxx_hidden)接口可以获取hidden的输出，但是在Encoder-decoder的结构中，图中的结构要循环21次而不是GRU本身一个算子循环多次，造成每次循环的输入input_decoder都是以0作为初始化的，这样在计算时就出现问题了。目前问题已解决，谢谢

**Comment by Ryuk17** [comment]
> 谢谢回复，这块代码也看过，实际测试中指定hidden的名字的方法也是不行，我做的时候是发现在解析ONNX模型的时候，参数的数据排布方式有些问题导致了最后计算的结果有问题，后来利用mnn本身的计算库重新计算了一下。

请问您这步具体是怎么做的呢？
