### ISSUE TITLE
multiPose.out 调用opencl时，Can't Find type=3 backend, use 0 instead

### ISSUE THREAD

**Issue by ZZ-QTD** [alibaba/MNN#1510]
![图片](https://user-images.githubusercontent.com/52046747/120758048-f216e700-c543-11eb-88c6-dd0d7081ff1b.png)

[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/ScaleExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/SoftmaxExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/TrainableParamExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/image/UnaryExecution.cpp.o
[ 92%] Linking CXX shared library libMNN_CL.so
[ 92%] Built target MNN_CL
Scanning dependencies of target pictureRecognition.out
Scanning dependencies of target timeProfile.out
Scanning dependencies of target transformerDemo.out
Scanning dependencies of target pictureRotate.out
Scanning dependencies of target expressDemo.out
Scanning dependencies of target multiPose.out
Scanning dependencies of target testModelWithDescrisbe.out
Scanning dependencies of target rasterDemo.out

我已经将opencl的库编译成功了，但是在调用opencl时却提示失败

![图片](https://user-images.githubusercontent.com/52046747/120757949-ceec3780-c543-11eb-8bc1-f68d99690b68.png)

~/MNN/demo/model/pose_get$ ./multiPose.out model-mobilenet_v1_075.mnn psoe.jpg pose.png
Can't Find type=3 backend, use 0 instead
Can't Find type=3 backend, use 0 instead
main, 382, cost time: 65.429001 ms
main, 406, cost time: 0.506000 ms

请问是需要编译好的opencl.so文件路径不对吗，还是一些其他什么原因，不能调用

**Comment by ZZ-QTD** [comment]
已解决

**Comment by dolphintear** [comment]
怎么解决的？谢谢

**Comment by dolphintear** [comment]
> 已解决

怎么 解决的？

**Comment by hongjizhu** [comment]
@ZZ-QTD 请问是怎么解决的呢？

**Comment by guchunqi-git** [comment]
> 已解决

我最近也遇到这个问题，请问怎么解决的呢？
