### ISSUE TITLE
安装python wheel库

### ISSUE THREAD

**Issue by wlgcqh** [alibaba/MNN#1514]
auditwheel repair dist/MNN-1.0.0-cp37-cp37m-linux_x86_64.whl -w wheelhouse
auditwheel: error: cannot repair "dist/MNN-1.0.0-cp37-cp37m-linux_x86_64.whl" to "manylinux1_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.

**Comment by wangzhaode** [comment]
这个需要在many_linux的docker环境下运行；

可以直接`pip install MNN`
