### ISSUE TITLE
MNN支持MLPerf RNNT(Recurrent Neural Network Transducer)推理文档

### ISSUE THREAD

**Issue by jianlongf** [alibaba/MNN#1516]
关于MNN推理RNNT，有没有相关文档:
1. MNN支持RNNT这种模型的推理?
2. 如果支持的话，运行计算图的构建是怎么动态构建？

**Comment by jianlongf** [comment]
> https://github.com/alibaba/MNN/issues/741
> 带 Control flow 的模型目前已经支持，参考 demo/exec/transformDemo.cpp 使用
看起来这就是可以参考的了

**Comment by Liujingxiu23** [comment]
@jxt1234 
额 我又遇到问题 来求助了。。

我的应用领域是语音合成（Text to speech）， 输入文本，合成声学特征。
输入文本是变长的，输出wav也是变长的。
即如下phones和mels都包含动态轴， 且mels的长度与phones的长度不是直接成比例的关系。

按照你说的新的接口形式，我完成了类似如下代码：
初始化：Init(model_path)：
model = Module::load({"phones"}, {"mels"}, model_path.c_str());

Inference(model, inputs, output){
    auto phones = _Input({1, seq_len}, NHWC, halide_type_of<int>());
    vector<VARP> outputs_ = model->onForward({phones});
}

我遇到的问题是：
假如我要依次合成2句话，输入为text1, text2,  text1和text2内容不同，我调用：
Init(***);
Inference(text1)
Inference(text2)

1.如果text1和text2输出的维度不同，即mels的dim不同，则输出正常
2.如果text1和text2输入的维度相同，但输出mels的维度不同，输出也正常
3.如果text1和text2的“输出”维度是一样的，比如都是[1, 80, 124],  虽然两次输出的维度相同，但由于输入的具体内容是不同的，预期的输出具体内容也不同。但是我运行得到的结果是， text2的输出同text1内容也完全一致。

也就是说，当连续两次调用，输出维度一样时，即便输入不同，第二次的输出结果同第一次完全相同。

我尝试:
1）每次Inference后，model->clearCache();， 没有作用
2)  每次Inference前，Module* model2 = Module::clone(model);， model2->onForward;
     有效果，运行正常。但是clone耗费时间。

请问我该如何解决这个问题？
