### ISSUE TITLE
android demo 不应该写个readme 吗？

### ISSUE THREAD

**Issue by 1icas** [alibaba/MNN#1517]
libMNN.so 我需要看CMakeLists.txt才知道放到哪个目录，模型文件目前还不知道放到哪里。

**Comment by bestpower** [comment]
我最近也在看这个demo，你把安卓的工程导入到Android Studio里就能看到这些了，libMNN.so在libs目录下，CMakeLists.txt就在app目录下，模型文件在MNN/resource/model目录下

**Comment by Divya932** [comment]
For the model files, put it simply into assets directory. 
1. Foremost change your *minSdkVersion* inside app level *build.gradle* to 16 or above.
2. Inside app level *build.gradle* file. Remove this block from *sourceSets* block to avoid any confusion in path and directory:
	assets {
                srcDirs = ["../../model", "../../../resource/model"]
            }
3. Create *assets* directory inside *app/src/main*
4. Put your model and label files/directory inside  *app/src/main/assets/*  in your desired structure.
Check my folder structure below as a sample.
![Folder Structure](https://user-images.githubusercontent.com/46338924/124238292-072c6900-db36-11eb-95ae-632c19fe6ed9.png)

**Comment by wangzhaode** [comment]
OK. 正在考虑完善Demo的文档

**Comment by wangzhaode** [comment]
https://github.com/alibaba/MNN/tree/master/project/android/demo
