### ISSUE TITLE
[bug] BN层训练，当dim=2的时候存在内存泄漏

### ISSUE THREAD

**Issue by HaoyuanLuo** [alibaba/MNN#1519]
带有1维BN层的网络在训练时，训练时间会逐渐递增直至出现coreDump，去除1维BN层问题消失

![image](https://user-images.githubusercontent.com/29444696/121773354-fda28780-cbad-11eb-886b-17f758ff686c.png)

**Comment by jxt1234** [comment]
仅 dim = 2 的时候出错么?

**Comment by HaoyuanLuo** [comment]
@jxt1234 目前测试是这样的
