### ISSUE TITLE
output tensor 是空的？

### ISSUE THREAD

**Issue by sharepointer** [alibaba/MNN#152]
android 32位环境下：
createFromFile() createSession() 都返回有效的指针，但是getSessionOutput()查询的输出节点tensor 的chanel() width() height()  elementSize()全部是0，这是为何？

**Comment by jxt1234** [comment]
1､是否 input 输入没有指定，有 resize error
2、output tensor 是否是  DetectOutput 出来的，有可能计算出来大小为0

**Comment by sharepointer** [comment]
@jxt1234 
Debug打开，有如下log：
01-02 00:59:57.751   354  2515 I MNNJNI  : Don't support type 12, conv1/Conv2D
01-02 00:59:57.751   354  2515 I MNNJNI  : Don't support type 12, conv1/Conv2D
01-02 00:59:57.751   354  2515 E MNNJNI  : Resize error for conv1/Conv2D, code=2

PC上就没这个问题

**Comment by jxt1234** [comment]
链接 MNN 静态库时要加 -Wl,--whole-archive

**Comment by sharepointer** [comment]
> 链接 MNN 静态库时要加 -Wl,--whole-archive

@jxt1234 
这个加在哪啊，android.mk哪里？

**Comment by sharepointer** [comment]
@jxt1234 
REGISTER_CPU_OP_CREATOR(ConvolutionFactory, OpType_Convolution);
跟踪到这句话没有有运行，可是无法理解，里面定义的是一个static 全局变量，应该总是要初始化的啊

**Comment by sharepointer** [comment]
@jxt1234 
非常感谢～ 用 LOCAL_WHOLE_STATIC_LIBRARIES 这个命令就没有问题了

**Comment by StephenLee2016** [comment]
我也遇到这个问题，multipose的demo在pc上cpu运行结果正确，android上cpu和vulkan上getSessionOutput的channel都是0，这个什么问题呢？
