### ISSUE TITLE
mnn设计上是否支持multiTask训练？

### ISSUE THREAD

**Issue by HaoyuanLuo** [alibaba/MNN#1520]
当网络中存在支路及多Loss时，MNN实现的code可以运行，但是存在与pytorch等框架的结果差异，请问下问题定位方向应该往哪儿走呢？
看了OpGrad源码的计算逻辑，理论推导是一致的
是optimizer还是哪儿与第三方存在差异？

**Comment by jxt1234** [comment]
具体结果差异是?

**Comment by HaoyuanLuo** [comment]
@jxt1234 表现是准确率不如第三方高
