### ISSUE TITLE
MNN1.2.0，可以发布mnn1.2.0的whl到pypi上吗

### ISSUE THREAD

**Issue by barbecacov** [alibaba/MNN#1524]

**Comment by jxt1234** [comment]
稍等，还有一些 bugfix

**Comment by barbecacov** [comment]
我这个有点急，天天在pypi里搜mnn还是没看到更新。主要是我自己编译老是出错

**Comment by LanWong1** [comment]
我也是 ,自己编译总是不成功.感觉文档太不详细了

**Comment by GuoJingtao-1997** [comment]
1.2.0 我在树莓派上也编译不了，换成1.1.7就可以了，感觉是还有bug没处理好

**Comment by wangzhaode** [comment]
从2.3.0之后每个版本都会通过Github Action编译Windows/MacOSX/Linux三个平台的包并上传到pypi
