### ISSUE TITLE
nn.Unfold算子可以成功导出onnx，但是onnx转换为mnn不成功’

### ISSUE THREAD

**Issue by zymale** [alibaba/MNN#1527]
pytorch中的nn.Unfold算子，onnx目前支持导出，但是使用该onnx转换为mnn会出错。查看了语雀上的支持算子列表，目前mnn应该是不支持该算子。所以想问下有没有添加该算子的计划？在转换自定义的一些卷积方式时，会用到该算子，如果支持的话，会方便很多。

**Comment by jxt1234** [comment]
报什么错误?

**Comment by zymale** [comment]
MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
[14:02:32] /media/disk1/zhangyi/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
段错误 (核心已转储)
以上是转换的时候报的错误信息


import torch
from torch import nn
class Demo(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.unfold=nn.Unfold(kernel_size=3)
	def forward(self,x):
		unfold_x=self.unfold(x)
		return unfold_x

if __name__=="__main__":
	input_tensor=torch.zeros((1,16,100,100))
	demo=Demo()
	torch.onnx.export(demo, input_tensor, "export.onnx", verbose=True, input_names=['data'], opset_version=11,
					  output_names=['output'])
以上是简单的pytorch导出onnx模型

**Comment by zymale** [comment]
系统是Ubuntu 16.04

**Comment by jxt1234** [comment]
File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Demo' object has no attribute 'unfold'

**Comment by zymale** [comment]
不好意思，没有写pytorch的版本，你这个错误，我用pytorch1.7.1也会报，但是用pytorch1.8.1就可以正常导出。

**Comment by jxt1234** [comment]
import torch
from torch import nn
class Demo(torch.nn.Module):
    def __init__(self):
        nn.Module.__init__(self)
        self.mod = nn.Unfold(kernel_size=3)
        print(self.mod)
    def forward(self,x):
        unfold_x=self.mod(x)
        return unfold_x

input_tensor=torch.zeros((1,16,100,100))
demo=Demo()
demo.forward(input_tensor)
scripted_module = torch.jit.script(Demo())
torch.onnx.export(demo, input_tensor, "export.onnx", verbose=True, input_names=['data'], opset_version=11,
output_names=['output'])

**Comment by jxt1234** [comment]
import torch
from torch import nn
class Demo(torch.nn.Module):
    def __init__(self):
        nn.Module.__init__(self)
        self.mod = nn.Unfold(kernel_size=3)
        print(self.mod)
    def forward(self,x):
        unfold_x=self.mod(x)
        return unfold_x

input_tensor=torch.zeros((1,16,100,100))
demo=Demo()
demo.forward(input_tensor)
scripted_module = torch.jit.script(Demo())
torch.onnx.export(demo, input_tensor, "export.onnx", verbose=True, input_names=['data'], opset_version=11,
output_names=['output'])

**Comment by jxt1234** [comment]
看来是 github 显示问题，修改了下 init 函数跑出来了，导出来的 onnx 是算子组合，这个 mnn 是支持的，fastTestOnnx.py 测试正确
