### ISSUE TITLE
同一模型在linux的mnn上与Android的mnn上推理结果不一致

### ISSUE THREAD

**Issue by Codesticker** [alibaba/MNN#1529]
最近在用bilstm做分类任务，将pytorch模型转成mnn模型，再在Android上用mnn推理，发现Android端推理结果精确率下降。于是用同一个测例，同一模型，尝试用mnn在linux上和Android上进行推理，发现推理出来结果不一致（当然并非所有测例都不一致）。请问有可能是什么造成这样的结果？      **另外**推理过程中出现过Compute Shape Error for 111，但不会使推理中断，请问这个Error又是怎么回事呢？

**Comment by jxt1234** [comment]
结果差异是多大呢? 是否是开了 precision = low 并用了 ARM82 (FP16加速)

**Comment by jxt1234** [comment]
Compute Shape Error for 111 这个有可能是在 createSession 中尝试按初始输入大小 reshape 失败打出来的，不一定有影响

**Comment by wangzhaode** [comment]
长时间未回复，关闭问题；
