### ISSUE TITLE
window10 build MNN 

### ISSUE THREAD

**Issue by Linchunhui** [alibaba/MNN#153]
无法加载文件 D:\app\MNN-master\schema\generate.ps1。未对文件 D:\app\MNN-master\
schema\generate.ps1 进行数字签名。无法在当前系统上运行该脚本。

**Comment by piaobuliao** [comment]
我是用cmake-gui编译成sln，编译的时候 提示 :

2>------ 已启动生成: 项目: MNN_SCHEMA, 配置: Release x64 ------
2>D:/Project/_Sunyard/SunyardMobileOCR/MNN-master/schema/generate.ps1 : 无法加载文件 D:\Project\_Sunyard\SunyardMobileOCR
2>\MNN-master\schema\generate.ps1，因为在此系统上禁止运行脚本。

-------------------------------------------------------------------------
我参考 https://blog.csdn.net/weixin_34032792/article/details/86127624 
执行   set-executionpolicy -executionpolicy unrestricted
generate.ps1直接运行是可以了的，虽然还是会报错，但是在sln编译 还是报 
2>\MNN-master\schema\generate.ps1，因为在此系统上禁止运行脚本。

**Comment by Linchunhui** [comment]
> 我是用cmake-gui编译成sln，编译的时候 提示 :
> 
> 2>------ 已启动生成: 项目: MNN_SCHEMA, 配置: Release x64 ------
> 2>D:/Project/_Sunyard/SunyardMobileOCR/MNN-master/schema/generate.ps1 : 无法加载文件 D:\Project_Sunyard\SunyardMobileOCR
> 2>\MNN-master\schema\generate.ps1，因为在此系统上禁止运行脚本。
> 
> 我参考 https://blog.csdn.net/weixin_34032792/article/details/86127624
> 执行 set-executionpolicy -executionpolicy unrestricted
> generate.ps1直接运行是可以了的，虽然还是会报错，但是在sln编译 还是报
> 2>\MNN-master\schema\generate.ps1，因为在此系统上禁止运行脚本。

我现在报错是找不到MNN_generate.h ,原因是generate.ps1执行的时候出错，不知道怎么编译

**Comment by piaobuliao** [comment]
@Linchunhui 

我现在编译是能编译了，但是编译到60%出错，
我总结下吧 感觉官网的 win10下的install写的太简洁了，好多坑，你按照我的步骤试试 

要先执行 schema\generate.ps1 的，但是ps1文件是PowerShell写好的脚本文件。在Windows系统中，默认情况下是不允许执行.ps1文件的。需要 执行如下命令，降低系统的安全性，允许执行脚本：set-executionpolicy -executionpolicy unrestricted ，参考：https://blog.csdn.net/weixin_34032792/article/details/86127624

及时步骤1做了 执行 schema\generate.ps1 还会报如下错误：
无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
cmdlet、函数、脚本文件或可运行程序的名称。

这个去 https://github.com/google/flatbuffers/releases 下载下flatc.exe 放到/3rd_party/flatbuffers/tmp 目录下即可

执行这两条指令
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
nmake
这两条指令，我都是在我的电脑的开始菜单的VirtualStudio 2019下的 x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
直接powershell 执行报错

目前我步骤3 编译到60% 还是有问题，可能是官方文档里写的 ”将设置-区域与语言-管理-非unicode程序的语言改成英语（美国），否则可能因编码问题导致编译失败”，但是这个找半天找不到在哪里设置啊

**Comment by Linchunhui** [comment]
> @Linchunhui
> 
> 我现在编译是能编译了，但是编译到60%出错，
> 我总结下吧 感觉官网的 win10下的install写的太简洁了，好多坑，你按照我的步骤试试
> 
> 1. 要先执行 schema\generate.ps1 的，但是ps1文件是PowerShell写好的脚本文件。在Windows系统中，默认情况下是不允许执行.ps1文件的。需要 执行如下命令，降低系统的安全性，允许执行脚本：set-executionpolicy -executionpolicy unrestricted ，参考：https://blog.csdn.net/weixin_34032792/article/details/86127624
> 
> 2）即使步骤1做了 执行 schema\generate.ps1 还会报如下错误：
> 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。
> 这个去 https://github.com/google/flatbuffers/releases 下载下flatc.exe 放到/3rd_party/flatbuffers/tmp 目录下即可
> 
> 1. 执行这两条指令
>    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
>    nmake
>    这两条指令，我都是在我的电脑的开始菜单的VirtualStudio 2019下的 x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
>    直接powershell 执行报错
> 
> 4）目前我步骤3 编译到60% 还是有问题，可能是官方文档里写的 ”将设置-区域与语言-管理-非unicode程序的语言改成英语（美国），否则可能因编码问题导致编译失败”，但是这个找半天找不到在哪里设置啊

4)谢谢，win10系统你可以右键左下角的window,然后在设置里面  日期和时间->语言 ->管理语言设置->更改系统区域设置。你可以试试

**Comment by yutianhang** [comment]
在原生x64上编译没复现你说的问题，但是在交叉编译x86版本的MNN时遇到了你说的这个问题。以下是解决方案：
如果遇到因为电脑权限问题或者脚本数字签名问题导致powershell脚本无法执行，可以在设置里面搜索编辑组策略，或者win+R然后输入gpedit.msc。然后在左侧依次选择计算机配置-管理模板-Windows组件-Windows PowerShell，在右侧设置面板双击“启用脚本执行”，将左上未配置或已禁用改为已启用，然后在左下执行策略里选允许所有脚本就可以了。

**Comment by yutianhang** [comment]
顺便说，在amd64机器上交叉编译x86时，指定CMAKE_BUILD_TYPE为Release会在CPUDetectionOutput.cpp第82行报MSVC编译器内部错误，但是指定为Debug就不会出现这个问题，可能和MSVC在代码优化时的bug有关，具体原因待查。
另外，找不到头文件可能是一开始powershell未能正确执行，建议删除schema/current然后重新编译。

**Comment by YangYangTaoTao** [comment]
> @Linchunhui
> 
> 我现在编译是能编译了，但是编译到60%出错， 我总结下吧 感觉官网的 win10下的install写的太简洁了，好多坑，你按照我的步骤试试
> 
> 1. 要先执行 schema\generate.ps1 的，但是ps1文件是PowerShell写好的脚本文件。在Windows系统中，默认情况下是不允许执行.ps1文件的。需要 执行如下命令，降低系统的安全性，允许执行脚本：set-executionpolicy -executionpolicy unrestricted ，参考：https://blog.csdn.net/weixin_34032792/article/details/86127624
> 
> 2）即使步骤1做了 执行 schema\generate.ps1 还会报如下错误： 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。 这个去 https://github.com/google/flatbuffers/releases 下载下flatc.exe 放到/3rd_party/flatbuffers/tmp 目录下即可
> 
> 3. 执行这两条指令
>    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
>    nmake
>    这两条指令，我都是在我的电脑的开始菜单的VirtualStudio 2019下的 x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
>    直接powershell 执行报错
> 
> 4）目前我步骤3 编译到60% 还是有问题，可能是官方文档里写的 ”将设置-区域与语言-管理-非unicode程序的语言改成英语（美国），否则可能因编码问题导致编译失败”，但是这个找半天找不到在哪里设置啊

我参考这篇文章，貌似就OK了

**Comment by boriszhang78** [comment]
> @Linchunhui
> 
> 我现在编译是能编译了，但是编译到60%出错， 我总结下吧 感觉官网的 win10下的install写的太简洁了，好多坑，你按照我的步骤试试
> 
> 1. 要先执行 schema\generate.ps1 的，但是ps1文件是PowerShell写好的脚本文件。在Windows系统中，默认情况下是不允许执行.ps1文件的。需要 执行如下命令，降低系统的安全性，允许执行脚本：set-executionpolicy -executionpolicy unrestricted ，参考：https://blog.csdn.net/weixin_34032792/article/details/86127624
> 
> 2）即使步骤1做了 执行 schema\generate.ps1 还会报如下错误： 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。 这个去 https://github.com/google/flatbuffers/releases 下载下flatc.exe 放到/3rd_party/flatbuffers/tmp 目录下即可
> 
> 3. 执行这两条指令
>    cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
>    nmake
>    这两条指令，我都是在我的电脑的开始菜单的VirtualStudio 2019下的 x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
>    直接powershell 执行报错
> 
> 4）目前我步骤3 编译到60% 还是有问题，可能是官方文档里写的 ”将设置-区域与语言-管理-非unicode程序的语言改成英语（美国），否则可能因编码问题导致编译失败”，但是这个找半天找不到在哪里设置啊

需要下载flatbuffers的源码，替换原来3rd_party的源码进行编译，我替换后编译成功
