### ISSUE TITLE
CMAKE_BUILD_TYPE=Debug 和 CMAKE_BUILD_TYPE=Release 同一模型运算结果不同，使用Debug版本可以有正确输出，Release版本结果错误

### ISSUE THREAD

**Issue by HIT123-C** [alibaba/MNN#1534]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
aarch64

# Github版本:
# Github Version:
git version 2.20.1
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD TYPE:Debug
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: FALSE
-- 	Build Path: /home/toybrick/MNN/build
-- Enabling AArch64 Assemblies
-- Onnx: /home/toybrick/MNN/build/tools/converter/onnx.pb.h;/home/toybrick/MNN/build/tools/converter/onnx-operators.pb.h
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /home/toybrick/MNN/build

```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin

```

**Comment by HIT123-C** [comment]
请问如何选择有效的编译优化等级

**Comment by jxt1234** [comment]
是量化模型计算出错？可以更新一下看看问题有没解决，另外相关模型可以发一下？

**Comment by HIT123-C** [comment]
感谢回复，是一个基于Attention的ocr识别。目前只用了模型转换，没有经过量化。模型分为Encoder和Decoder两个，均为ONNX格式.通过转换代码将onnx模型转换为mnn，Debug模式下与服务器上跑的结果对比小数点后3位开始有不同，Release模式数据差别较大。按照之前的经验，应该是编译器优化等级过高导致的某些指令集优化过度造成的。
考虑到无法添加onnx文件，下附百度云链接，内含模型转换前的onnx模型和转换后的mnn文件
 https://pan.baidu.com/s/1obCI0zhz8KGo9sFzXExBJw 提取码: xene 。
整个pipeline：图片输入到encoder中，输出的结果作为decoder的输入，然后获得decoder的输出进行后处理，整个decoder模型循环21次

**Comment by jxt1234** [comment]
是否是 mnn 的输入没有填充满?
