### ISSUE TITLE
Error at compile time

### ISSUE THREAD

**Issue by TD-wzw** [alibaba/MNN#1536]
![FU@ H(PJ$PZOX` V )JY{M4](https://user-images.githubusercontent.com/57340568/123199840-33b30600-d4e2-11eb-970b-5ebe5f4f288d.png)

**Comment by TD-wzw** [comment]
What is the cause of this? Is it because Ninja is installed incorrectly?

**Comment by jxt1234** [comment]
It seems you need to update CMake to 3.14 or higher

**Comment by TD-wzw** [comment]
I'll try it. Thank you very much
