### ISSUE TITLE
关于MNN打印tensor的value的问题

### ISSUE THREAD

**Issue by zhuoran-guo** [alibaba/MNN#1537]
你好，我使用你们的repo做了benchmark，
MNN在OPENGL(2ms)下的速度是OPENCL(15ms)下的7倍,
想通过打印tensor的值来看这个测试结果是不是有bug
使用如下代码打印tensor，但是运行后却没有显示打印结果，请问你们知道如何办吗？

// Warming up...

```
for (int round = 0; round < loop; round++)
{
    auto timeBegin = getTimeInUs();

    input->copyFromHostTensor(givenTensor.get());
    net->runSession(session);
    outputTensor->copyToHostTensor(expectTensor.get());

    auto timeEnd = getTimeInUs();
    //(*(expectTensor.get())).print();
    costs.push_back((timeEnd - timeBegin) / 1000.0);
}
input->copyFromHostTensor(givenTensor.get());
net->runSession(session);
outputTensor->copyToHostTensor(expectTensor.get());
(*(expectTensor.get())).print();
return costs;
```

**Comment by jxt1234** [comment]
应该是 opengl 有 bug ，你 MNN 是什么版本?

**Comment by zhuoran-guo** [comment]
@jxt1234 
你好，用的就是master branch 
# download repo
if [ ! -d "./mnn" ]; then
     git clone https://github.com/alibaba/mnn.git mnn
else
    echo "local mnn repo exited"
fi
请问下打印不出tensor来是什么原因呢？ opencl也打印不出来

**Comment by jxt1234** [comment]
你在哪里看的，APP 上看的话需要在编译时MNN 开启 -DMNN_USE_LOGCAT 宏，然后在 logcat 里面看

**Comment by zhuoran-guo** [comment]
@jxt1234 
你好，我是用adb连接的设备，直接使用adb命令来运行的，所以应该是可以直接显示出来才对。
用的以下命令
adb -H 'host.docker.internal' -s 7893c2d0 shell "export LD_LIBRARY_PATH=/data/local/tmp/ai-performance/mnn/android-armv8;/data/local/tmp/ai-performance/mnn/android-armv8/benchmark.out /data/local/tmp/ai-performance/mnn/incam-face-c-7.0-2.0.mnn 100 20 6 1"
