### ISSUE TITLE
pytorch模型转mnn模型 使用metal backend推理报错：computePipelineState must not be nil.

### ISSUE THREAD

**Issue by xisi789** [alibaba/MNN#1538]
运行机器为iphone6 mnn版本为1.1.0 使用cpu可以正常运行 gpu则报错

报错代码如下：
![image](https://user-images.githubusercontent.com/41114558/123241378-af797680-d513-11eb-9c0f-1e62b4aea609.png)
在mnn_net_->runSession(mnn_session_);语句报错
computePipelineState must not be nil.

对代码进行修改：
![image](https://user-images.githubusercontent.com/41114558/123242738-e8feb180-d514-11eb-98de-4d2ba83d9f0c.png)
在mnn_img_tensor_->copyFromHostTensor(inputUser);语句报错
computePipelineState must not be nil.

**Comment by jxt1234** [comment]
看上去是输入为 NCHW 布局，convert 到 mnn_img_tensor_ 就可以了，那个 copyFromHostTensor 以及 inputUser 的创建是不需要的

**Comment by xisi789** [comment]
> 看上去是输入为 NCHW 布局，convert 到 mnn_img_tensor_ 就可以了，那个 copyFromHostTensor 以及 inputUser 的创建是不需要的

@jxt1234 我没太明白您的意思，我的输入是NCHW的，但直接用convert报错呀。
更为详细的代码如下，输入为1 * 48 * 128 * 128

mnn_img_tensor_ = mnn_net_->getSessionInput(mnn_session_, "in.1");
cv::Mat cv_mat( 512, 512, CV_8UC3, cv::Scalar(0,255,0) );
cv::Mat dst = cv_mat.reshape(48, 128);
std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(MNN::CV::BGR, MNN::CV::BGR, means, 3, norms, 3));
pretreat->convert(dst.data, img_width, img_height, 1, mnn_img_tensor_);
mnn_net_->runSession(mnn_session_);
