### ISSUE TITLE
MNN1.2.0 release CoreML如何使用

### ISSUE THREAD

**Issue by richlaji** [alibaba/MNN#1545]
看到1.2.0的release的更新，想问一下
（1）支持CoreML后端，iOS要怎么开启呢
（2）Arm8.2&Arm bf16在iOS上能使用吗
感谢~

# 平台(如果交叉编译请再附上交叉编译目标平台):  
XCode iOS

# Github版本:
MNN 1.2.0 Release

# 编译方式:
https://www.yuque.com/mnn/cn/build_ios

**Comment by jxt1234** [comment]
(1) forwordtype 设成 NN 
(2) Arm8.2 在ios上默认打开的，可以使用。bf16 也可以用，但 iOS 支持 fp16 的设备相对更广，不建议用 bf16 。
