### ISSUE TITLE
NDK r17c 编译 麒麟 NPU 64 位 arm64-v8a 的时候，linker 不上 hiai.so

### ISSUE THREAD

**Issue by Kasq-Lee** [alibaba/MNN#1547]
NDK r17c 编译 麒麟 NPU 64 位 arm64-v8a 的时候，linker 不上 hiai.so

报错如下：
/home/gdd/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/gdd/mnn/MNN/source/backend/hiai/3rdParty/arm64-v8a/libhiai.so, not found (try using -rpath or -rpath-link)
/home/gdd/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/gdd/mnn/MNN/source/backend/hiai/3rdParty/arm64-v8a/libhiai.so, not found (try using -rpath or -rpath-link)
/home/gdd/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/gdd/mnn/MNN/source/backend/hiai/3rdParty/arm64-v8a/libhiai.so, not found (try using -rpath or -rpath-link)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/testModelWithDescrisbe.out.dir/build.make:90: testModelWithDescrisbe.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:419: CMakeFiles/testModelWithDescrisbe.out.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/timeProfile.out.dir/build.make:120: timeProfile.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:387: CMakeFiles/timeProfile.out.dir/all] Error 2
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/benchmarkExprModels.out.dir/build.make:165: benchmarkExprModels.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:269: CMakeFiles/benchmarkExprModels.out.dir/all] Error 2
[ 75%] Linking CXX executable run_test.out
/home/gdd/android-ndk-r17c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/gdd/mnn/MNN/source/backend/hiai/3rdParty/arm64-v8a/libhiai.so, not found (try using -rpath or -rpath-link)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/run_test.out.dir/build.make:1815: run_test.out] Error 1
make[1]: *** [CMakeFiles/Makefile2:301: CMakeFiles/run_test.out.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

/home/gdd/mnn/MNN/source/backend/hiai/3rdParty/arm64-v8a/libhiai.so
这个文件是存在的，也验证过，

32 位编译正常，

**Comment by fkh12345** [comment]
也遇到了一样的问题， 32位编译正常但是64位出现了一样的问题。我是用的android-ndk-r21e 请问您找到解决方案了吗？

**Comment by fkh12345** [comment]
我也遇到过这个问题，我把build64.sh中-DANDROID_STL=c++_shared 更改为-DANDROID_STL=c++_static 就能正常编译了。

不过在mate40 pro手机上运行还是遇到了其他问题qwq
cmake编译方式如下：
```
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DMNN_NPU:BOOL=true \
-DMNN_OPENCL=ON \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_shared \
-DMNN_USE_LOGCAT=true \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j8
```
