### ISSUE TITLE
Metal支持半精度或int8嘛

### ISSUE THREAD

**Issue by richlaji** [alibaba/MNN#1548]
平台(如果交叉编译请再附上交叉编译目标平台):  macOS iOS

Github版本:1.2.0

编译方式: 参考https://www.yuque.com/mnn/cn/build_ios

iOS的Metal支持半精度或者int8推理嘛，yuque上好像没提到，如果可以支持的话需要打开哪些开关呢？感谢回答

**Comment by jxt1234** [comment]
支持半精度

**Comment by richlaji** [comment]
> 支持半精度，Int8 还不支持

想问一下，半精度是默认打开嘛，在哪里能设置呢，感谢~
