### ISSUE TITLE
ONNX 模型转换 Segmentation Fault

### ISSUE THREAD

**Issue by wk5ovc** [alibaba/MNN#1550]
# 平台:  
# Platform:
Linux

# Github版本:
# Github Version:
1.2.0

# 编译方式:
# Compiling Method

```
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=on && make -j4
```

转换 ONNX 模型 Segmentation Fault
```
./MNNConvert -f ONNX --modelFile model.onnx --MNNModel model.mnn --debug

Start to Optimize the MNN Net...
Signal: SIGSEGV (Segmentation fault)
```

调试发现 [/3rd_party/flatbuffers/include/flatbuffers/base.h#L311](https://github.com/alibaba/MNN/blob/master/3rd_party/flatbuffers/include/flatbuffers/base.h#L311) `const void *p` 空指针

``` cpp
template<typename T>
// UBSAN: C++ aliasing type rules, see std::bit_cast<> for details.
__supress_ubsan__("alignment")
T ReadScalar(const void *p) {
  return EndianScalar(*reinterpret_cast<const T *>(p));
}
```
将 [/tools/converter/source/optimizer/merge/FuseGeLu.cpp#L35](https://github.com/alibaba/MNN/blob/master/tools/converter/source/optimizer/merge/FuseGeLu.cpp#L35) 修改为如下代码:

``` cpp
bool IsTanh(EXPRP expr) {
    return false;
}
```
MNNConvert 没有再 Segmentation Fault，模型转换成功。

**Comment by jxt1234** [comment]
了解了，等会我们修复一下

**Comment by jxt1234** [comment]
已经修正，同步一下看看? 还有问题的话麻烦发一下onnx 模型?

**Comment by wk5ovc** [comment]
问题已经解决了。
