### ISSUE TITLE
Linux编译Converter失败

### ISSUE THREAD

**Issue by xingjing1** [alibaba/MNN#1551]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86  ubuntu16.04

# Github版本:
# Github Version:
master 分支
commit：
8a82f5c5a7ae37192784c2dbd6dfc8ca8833565a

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_CONVERTER=true -DProtobuf_INCLUDE_DIR=/workspace/mnn/protobuf/protobuf/install/include  -DProtobuf_LIBRARY=/workspace/mnn/protobuf/protobuf/install/lib/libprotobuf.a
或者：cmake .. -DMNN_BUILD_CONVERTER=true

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /workspace/mnn/MNN_new/MNN/build_convert
-- x86_64: Open SSE
CMake Warning at /opt/cmake-3.10/share/cmake-3.10/Modules/FindProtobuf.cmake:455 (message):
  Protobuf compiler version doesn't match library version 3.14.0
Call Stack (most recent call first):
  tools/converter/CMakeLists.txt:12 (find_package)

-- Onnx: /workspace/mnn/MNN_new/MNN/build_convert/tools/converter/onnx.pb.h;/workspace/mnn/MNN_new/MNN/build_convert/tools/converter/onnx-operators.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/mnn/MNN_new/MNN/build_convert

# 编译日志:
# Build Log:

[  1%] Built target MNNUtils
[  2%] Built target MNNSSE
[  3%] Built target MNNAVXFMA
[  4%] Built target MNNCV
[  5%] Built target MNNX8664
tools/converter/CMakeFiles/MNNCompress.dir/build.make:61: *** target pattern contains no '%'.  Stop.
CMakeFiles/Makefile2:1269: recipe for target 'tools/converter/CMakeFiles/MNNCompress.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/MNNCompress.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
tools/converter/CMakeFiles/OnnxClip.dir/build.make:61: *** target pattern contains no '%'.  Stop.
[  6%] Built target MNNAVX
CMakeFiles/Makefile2:1045: recipe for target 'tools/converter/CMakeFiles/OnnxClip.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/OnnxClip.dir/all] Error 2
[  6%] Built target MNNMath

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
你 cmake 版本是?

**Comment by xingjing1** [comment]
> 你 cmake 版本是?

3.10.3

**Comment by jules-ai** [comment]
> # 平台(如果交叉编译请再附上交叉编译目标平台):
> # Platform(Include target platform as well if cross-compiling):
> x86 ubuntu16.04
> 
> # Github版本:
> # Github Version:
> master 分支
> commit：
> [8a82f5c](https://github.com/alibaba/MNN/commit/8a82f5c5a7ae37192784c2dbd6dfc8ca8833565a)
> 
> 直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过`7z l zip包路径`命令并在输出信息中搜索`Comment` 获得，形如`Comment = bc80b11110cd440aacdabbf59658d630527a7f2b`)。 git clone请提供 `git commit` 第一行的commit id
> 
> Provide date (or better yet, git revision from the comment section of the zip. Obtainable using `7z l PATH/TO/ZIP` and search for `Comment` in the output) if downloading source as zip,otherwise provide the first commit id from the output of `git commit`
> 
> # 编译方式:
> # Compiling Method
> cmake .. -DMNN_BUILD_CONVERTER=true -DProtobuf_INCLUDE_DIR=/workspace/mnn/protobuf/protobuf/install/include -DProtobuf_LIBRARY=/workspace/mnn/protobuf/protobuf/install/lib/libprotobuf.a
> 或者：cmake .. -DMNN_BUILD_CONVERTER=true
> 
> ```
> 请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
> Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
> ```
> 
> -- Use Threadpool, forbid openmp
> -- >>>>>>>>>>>>>
> -- MNN BUILD INFO:
> -- System: Linux
> -- Processor: x86_64
> -- Metal: OFF
> -- OpenCL: OFF
> -- OpenGL: OFF
> -- Vulkan: OFF
> -- ARM82: OFF
> -- oneDNN: OFF
> -- TensorRT: OFF
> -- CoreML: OFF
> -- CUDA: OFF
> -- OpenMP: OFF
> -- BF16: OFF
> -- ThreadPool: ON
> -- Hidden: TRUE
> -- Build Path: /workspace/mnn/MNN_new/MNN/build_convert
> -- x86_64: Open SSE
> CMake Warning at /opt/cmake-3.10/share/cmake-3.10/Modules/FindProtobuf.cmake:455 (message):
> Protobuf compiler version doesn't match library version 3.14.0
> Call Stack (most recent call first):
> tools/converter/CMakeLists.txt:12 (find_package)
> 
> -- Onnx: /workspace/mnn/MNN_new/MNN/build_convert/tools/converter/onnx.pb.h;/workspace/mnn/MNN_new/MNN/build_convert/tools/converter/onnx-operators.pb.h
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /workspace/mnn/MNN_new/MNN/build_convert
> 
> # 编译日志:
> # Build Log:
> [ 1%] Built target MNNUtils
> [ 2%] Built target MNNSSE
> [ 3%] Built target MNNAVXFMA
> [ 4%] Built target MNNCV
> [ 5%] Built target MNNX8664
> tools/converter/CMakeFiles/MNNCompress.dir/build.make:61: *** target pattern contains no '%'. Stop.
> CMakeFiles/Makefile2:1269: recipe for target 'tools/converter/CMakeFiles/MNNCompress.dir/all' failed
> make[1]: *** [tools/converter/CMakeFiles/MNNCompress.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> tools/converter/CMakeFiles/OnnxClip.dir/build.make:61: *** target pattern contains no '%'. Stop.
> [ 6%] Built target MNNAVX
> CMakeFiles/Makefile2:1045: recipe for target 'tools/converter/CMakeFiles/OnnxClip.dir/all' failed
> make[1]: *** [tools/converter/CMakeFiles/OnnxClip.dir/all] Error 2
> [ 6%] Built target MNNMath
> 
> ```
> 粘贴在这里
> Paste log here or pastebin
> ```

用 "Protobuf_LIBRARIES" 而非 "Protobuf_LIBRARY"试试呢？

**Comment by jxt1234** [comment]
已经修正
