### ISSUE TITLE
win10 vs2019 编译失败

### ISSUE THREAD

**Issue by moyans** [alibaba/MNN#1554]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows amd64

# Github版本:
# Github Version:
8a82f5c5

# 编译方式:
# Compiling Method
powershell # 运行该命令从cmd环境进入powershell环境，后者功能更强大
./schema/generate.ps1
# CPU, 64位编译
.\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x64

# 编译日志:
# Build Log:
 D:\code\TFLITE\MNN  .\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x64

    Directory: D:\code\TFLITE\MNN\MNN-CPU\lib

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2021/7/5     20:53                x64
*** cleaning up ***
*** generating fbs under default ***
*** done ***

    Directory: D:\code\TFLITE\MNN\MNN-CPU\lib\x64\Debug

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2021/7/5     20:53                MD
d-----         2021/7/5     20:53                MT
d-----         2021/7/5     20:53                Static

    Directory: D:\code\TFLITE\MNN\MNN-CPU\lib\x64\Release

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2021/7/5     20:53                MD
d-----         2021/7/5     20:53                MT
d-----         2021/7/5     20:53                Static

    Directory: D:\code\TFLITE\MNN

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2021/7/5     20:53                build
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- The ASM compiler identification is GNU
-- Found assembler: D:/mingw64/bin/gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/mingw64/bin/gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: D:/miniconda3/python.exe (found version "3.7.6")
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
--      System: Windows
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16:
--      ThreadPool: ON
--      Hidden: FALSE
--      Build Path: D:/code/TFLITE/MNN/build
-- Configuring done
-- Build files have been written to: D:/code/TFLITE/MNN/build
[339/339] Linking CXX executable runTrainDemo.out.exe
cp : Cannot find path 'D:\code\TFLITE\MNN\build\MNN.lib' because it does not exist.
At D:\code\TFLITE\MNN\package_scripts\win\build_lib.ps1:65 char:1
+ cp MNN.lib $PACKAGE_PATH\Debug\MT
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\code\TFLITE\MNN\build\MNN.lib:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

```
粘贴在这里
Paste log here or pastebin
```

**Comment by iszhuangsha** [comment]
has ur problem beed sloved? i encounter the same problem

**Comment by moyans** [comment]
> has ur problem beed sloved? i encounter the same problem

You can succeed with cmake, Ninja will fail。
