### ISSUE TITLE
portch的模型转成onnx的，再转成mnn的，pc上可以成功预测，放到android中崩溃【MNN::Session::resize(bool)+192】

### ISSUE THREAD

**Issue by MuXIaoHong** [alibaba/MNN#1557]
## Github版本:
`commit 8a82f5c5a7ae37192784c2dbd6dfc8ca8833565a (HEAD -> master, origin/master, origin/HEAD)
Author: xiaying <xiaotang.jxt@alibaba-inc.com>
Date:   Mon Jun 28 16:21:41 2021 +0800
Fix bug for oneof don't support`

我将portch的模型转成onnx的，再转成mnn的。mnn的模型在linux上通过pip install MNN方式安装的库可以成功运行。但是放到安卓的demo中使用编译的安卓so库运行时崩溃了。

## 将portch的模型转成onnx
`import torch
import torch.nn as nn
import torch.onnx
import onnx
from DORNnet import DORN

pt_model_path = './best_coreml.pth'
onnx_model_path = './nestModel.onnx'

model = DORN()
model.load_state_dict(torch.load(pt_model_path, map_location=torch.device('cpu')))
input_tensor = torch.randn(1, 3, 257, 353)
input_names = ['input']
output_names = ['output']
torch.onnx.export(model, input_tensor, onnx_model_path, verbose=True, input_names=input_names, output_names=output_names,opset_version=11)`
## onnx转成mnn
`./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz`

## 编译android
`mkdir build_64 && cd build_64 && ../build_64.sh`

## 报错信息
`libMNN.so (MNN::Session::resize(bool)+192) (BuildId: ed41c6c11126ed007b5266eed647f6a8f5cfa737)
libMNN.so (MNN::Interpreter::createMultiPathSession(std::__ndk1::vector<MNN::ScheduleConfig, std::__ndk1::allocator<MNN::Schedu
libMNN.so (MNN::Interpreter::createMultiPathSession(std::__ndk1::vector<MNN::ScheduleConfig, std::__ndk1::allocator<MNN::Schedu
libMNN.so (MNN::Interpreter::createSession(MNN::ScheduleConfig const&)+360) (BuildId: ed41c6c11126ed007b5266eed647f6a8f5cfa737)`

**Comment by jxt1234** [comment]
有没可能是占用内存太大了，PC 上会打印占用的内存大小

**Comment by MuXIaoHong** [comment]
> 有没可能是占用内存太大了，PC 上会打印占用的内存大小

应该是了，转换的时候加上--fp16就好了，但是推理的时候结果和linux上差距很大，完全不可用。

**Comment by jxt1234** [comment]
PC 上正确的话不大可能，检查下输入输出的处理逻辑吧

**Comment by MuXIaoHong** [comment]
> PC 上正确的话不大可能，检查下输入输出的处理逻辑吧
