### ISSUE TITLE
android benchmark

### ISSUE THREAD

**Issue by gray2bgr** [alibaba/MNN#1559]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:2021.07.02版本的代码，手机是mate 40 pro， 麒麟9000
（1）照着教程跑android benchmark，重复跑结果波动很大，如mobilenet0.25从3ms到15ms。
（2）CPU的速度比VULKAN快这个是正常的结果么

**Comment by jxt1234** [comment]
1. 和手机频率有关，可以把次数/warmup 调大
2. 看机型，kirlin 9000 上是正常的

**Comment by gray2bgr** [comment]
好的谢谢，另外再请教一个问题。我跑benchmark，cpu和vulkan都可以正常。opencl有时是能跑，多数的情况是卡主一段时间然后就程序终止，结果里面也没有opencl的结果

**Comment by xxssd-awsl** [comment]
> 好的谢谢，另外再请教一个问题。我跑benchmark，cpu和vulkan都可以正常。opencl有时是能跑，多数的情况是卡主一段时间然后就程序终止，结果里面也没有opencl的结果

你好，我也是遇到了opencl卡住闪退的情况（MNN1.2.0），请问是怎么解决的，谢谢
