### ISSUE TITLE
Fail to build on windows10 

### ISSUE THREAD

**Issue by LJXLJXLJX** [alibaba/MNN#156]
I used vs2017 and got the error “MNN_generated.h": No such file or directory.

Then I tried to run generate.ps1 and also got a lot errors

> PS D:\MNN-master\schema> .\generate.ps1
> 
> 安全警告
> 请只运行你信任的脚本。虽然来自 Internet 的脚本会有一定的用处，但此脚本可能会损坏你的计算机。如果你信任此脚本，请使用 Unblock-File
> cmdlet 允许运行该脚本，而不显示此警告消息。是否要运行 D:\MNN-master\schema\generate.ps1?
> [D] 不运行(D)  [R] 运行一次(R)  [S] 暂停(S)  [?] 帮助 (默认值为“D”): r
> *** building flatc ***
> False
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:6 (project):
>   The CMAKE_C_COMPILER:
> 
>     cl
> 
>   is not a full path and was not found in the PATH.
> 
>   To use the NMake generator with Visual C++, cmake must be run from a shell
>   that can use the compiler cl from the command line.  This environment is
>   unable to invoke the cl compiler.  To fix this problem, run cmake from the
>   Visual Studio Command Prompt (vcvarsall.bat).
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
>   the compiler, or to the compiler name if it is in the PATH.
> 
> 
> CMake Error at CMakeLists.txt:6 (project):
>   The CMAKE_CXX_COMPILER:
> 
>     cl
> 
>   is not a full path and was not found in the PATH.
> 
>   To use the NMake generator with Visual C++, cmake must be run from a shell
>   that can use the compiler cl from the command line.  This environment is
>   unable to invoke the cl compiler.  To fix this problem, run cmake from the
>   Visual Studio Command Prompt (vcvarsall.bat).
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/MNN-master/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
> See also "D:/MNN-master/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeError.log".
> nmake : 无法将“nmake”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 D:\MNN-master\schema\generate.ps1:25 字符: 3
> +   nmake
> +   ~~~~~
>     + CategoryInfo          : ObjectNotFound: (nmake:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> *** cleaning up ***
> *** generating fbs under default ***
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b D:\MNN-master\schema\ ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> 
> 安全警告
> 请只运行你信任的脚本。虽然来自 Internet 的脚本会有一定的用处，但此脚本可能会损坏你的计算机。如果你信任此脚本，请使用 Unblock-File
> cmdlet 允许运行该脚本，而不显示此警告消息。是否要运行 D:\MNN-master\tools\converter\generate_schema.ps1?
> [D] 不运行(D)  [R] 运行一次(R)  [S] 暂停(S)  [?] 帮助 (默认值为“D”): R
> ===> Generating Schema...
> *** building flatc ***
> False
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:6 (project):
>   The CMAKE_C_COMPILER:
> 
>     cl
> 
>   is not a full path and was not found in the PATH.
> 
>   To use the NMake generator with Visual C++, cmake must be run from a shell
>   that can use the compiler cl from the command line.  This environment is
>   unable to invoke the cl compiler.  To fix this problem, run cmake from the
>   Visual Studio Command Prompt (vcvarsall.bat).
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
>   the compiler, or to the compiler name if it is in the PATH.
> 
> 
> CMake Error at CMakeLists.txt:6 (project):
>   The CMAKE_CXX_COMPILER:
> 
>     cl
> 
>   is not a full path and was not found in the PATH.
> 
>   To use the NMake generator with Visual C++, cmake must be run from a shell
>   that can use the compiler cl from the command line.  This environment is
>   unable to invoke the cl compiler.  To fix this problem, run cmake from the
>   Visual Studio Command Prompt (vcvarsall.bat).
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/MNN-master/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
> See also "D:/MNN-master/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeError.log".
> nmake : 无法将“nmake”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 D:\MNN-master\tools\converter\generate_schema.ps1:23 字符: 3
> +   nmake
> +   ~~~~~
>     + CategoryInfo          : ObjectNotFound: (nmake:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> 
> -------------------------------------------------------------------------------
>    ROBOCOPY     ::     Windows 的可靠文件复制
> -------------------------------------------------------------------------------
> 
>   开始时间: Thursday, July 11, 2019 6:54:30 PM
>         源: D:\MNN-master\3rd_party\flatbuffers\include\flatbuffers\
>       目标: D:\MNN-master\tools\converter\source\IR\flatbuffers\
> 
>       文件: *.*
> 
>       选项: *.* /S /E /DCOPY:DA /COPY:DAT /XO /XN /XC /R:1000000 /W:30
> 
> ------------------------------------------------------------------------------
> 
>                           14    D:\MNN-master\3rd_party\flatbuffers\include\flatbuffers\
> 
> ------------------------------------------------------------------------------
> 
>                   总数        复制        跳过       不匹配        失败        其他
>        目录:         1         0         1         0         0         0
>        文件:        14         0        14         0         0         0
>        字节:   322.8 k         0   322.8 k         0         0         0
>        时间:   0:00:00   0:00:00                       0:00:00   0:00:00
>    结束时间: Thursday, July 11, 2019 6:54:30 PM
> 
> ../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
> cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> + ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> ===> Done!
> *** done ***

**Comment by piaobuliao** [comment]
你是cl.exe的路径没有设置到path，我path里设置了D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64
但是还是有错

**Comment by LJXLJXLJX** [comment]
> 你是cl.exe的路径没有设置到path，我path里设置了D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64
> 但是还是有错

是的，我后来设置了还是报错。

**Comment by piaobuliao** [comment]
@LJXLJXLJX  我折腾了下 编译是可以编译了 但是编译到60% 有错误

cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
ImageSampler.cpp
[ 59%] Building CXX object CMakeFiles/MNN.dir/source/cv/Matrix_CV.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
Matrix_CV.cpp
[ 59%] Building CXX object CMakeFiles/MNN.dir/source/math/Matrix.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
Matrix.cpp
[ 60%] Building CXX object CMakeFiles/MNN.dir/source/math/WingoradGenerater.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
WingoradGenerater.cpp
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\WingoradGenerater.hpp(34): warning C4251: “MNN::Math::WinogradGenerater::mA”: class“std::shared_ptr<MNN::Tensor>”需要有 dll  接口由 class“MNN::Math::WinogradGenerater”的客户端使用
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\Matrix.hpp(31): note: 参见“std::shared_ptr<MNN::Tensor>”的声明
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\WingoradGenerater.hpp(35): warning C4251: “MNN::Math::WinogradGenerater::mG”: class“std::shared_ptr<MNN::Tensor>”需要有 dll  接口由 class“MNN::Math::WinogradGenerater”的客户端使用
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\Matrix.hpp(31): note: 参见“std::shared_ptr<MNN::Tensor>”的声明
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\WingoradGenerater.hpp(36): warning C4251: “MNN::Math::WinogradGenerater::mB”: class“std::shared_ptr<MNN::Tensor>”需要有 dll  接口由 class“MNN::Math::WinogradGenerater”的客户端使用
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\math\Matrix.hpp(31): note: 参见“std::shared_ptr<MNN::Tensor>”的声明
[ 60%] Building CXX object CMakeFiles/MNN.dir/source/shape/ShapeArgMax.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
ShapeArgMax.cpp
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(17): error C2270: “onComputeSize”: 非成员函数上不允许修饰符
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(17): error C3158: “MNN::onComputeSize”:“override”只能应用于虚成员函数
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(45): error C2143: 语法错误: 缺少“;”(在“<”的前面)
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(45): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(47): error C2059: 语法错误:“}”
D:\Project\_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(47): error C2143: 语法错误: 缺少“;”(在“}”的前面)
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\Hostx64\x64\cl.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by piaobuliao** [comment]
无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
cmdlet、函数、脚本文件或可运行程序的名称。

这个去 https://github.com/google/flatbuffers/releases 下载下 放到/3rd_party/flatbuffers/tmp 目录下即可

-------------------------------------------------------------
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
nmake
这两条指令，我都是在 开始的  x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
直接powershell报错 
  x64 Native Tools Command Prompt for VS 2019 在我电脑上的路径是
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Visual Studio 2019\Visual Studio Tools\VC

**Comment by piaobuliao** [comment]
我总结下吧 感觉官网的 win10下的install写的太简洁了，好多坑
1) 要先执行 schema\generate.ps1 的，但是ps1文件是PowerShell写好的脚本文件。在Windows系统中，默认情况下是不允许执行.ps1文件的。需要 执行如下命令，降低系统的安全性，允许执行脚本：set-executionpolicy -executionpolicy unrestricted  ，参考：https://blog.csdn.net/weixin_34032792/article/details/86127624 

2) 及时步骤1做了 执行 schema\generate.ps1 还会报如下错误：
无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为
cmdlet、函数、脚本文件或可运行程序的名称。

这个去 https://github.com/google/flatbuffers/releases 下载下flatc.exe  放到/3rd_party/flatbuffers/tmp 目录下即可

3) 执行这两条指令
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
nmake

这两条指令，我都是在我的电脑的开始菜单的VirtualStudio 2019下的 x64 Native Tools Command Prompt for VS 2019 打开的命令行运行的
直接powershell 执行报错

4) 目前我步骤3 编译到60% 还是有问题，可能是官方文档里写的 ”将设置-区域与语言-管理-非unicode程序的语言改成英语（美国），否则可能因编码问题导致编译失败”，但是这个找半天找不到在哪里设置啊

**Comment by LJXLJXLJX** [comment]
@piaobuliao 感谢大佬分享经验，这个语言设置指的是windows10的。你可以尝试在控制面板-区域里面进行修改。

**Comment by piaobuliao** [comment]
@LJXLJXLJX 谢谢，我在控制面板里 设置了下 区域与语言-管理-非unicode程序的语言改成英语（美国），就能100% 成功编译了

**Comment by LJXLJXLJX** [comment]
@piaobuliao 可以加个qq吗，我最近也在研究这个，希望能多交流 335272236

**Comment by baiyuang** [comment]
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\xutility(2414): error C2280: “std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: 尝试引用已删除的函数

Pipeline哪里使用了拷贝或者赋值函数啊，没有人遇到这个问题吗？

**Comment by mingliangfu** [comment]
遇到类似错误提示：C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\xutility(2310): error C2280: 'std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function
目前还没解决

**Comment by xxm52** [comment]
"D:\Project_Sunyard\SunyardMobileOCR\MNN-master\source\shape\ShapeArgMax.cpp(17): error C2270: “onComputeSize”: 非成员函数上不允许修饰符"
这个错误的解决方案如下：
删除类ArgMaxComputer之前的几行注释即可
