### ISSUE TITLE
这个框架支持安卓训练吗

### ISSUE THREAD

**Issue by Lizhihzzx** [alibaba/MNN#1565]
您好，最近在做端侧机器学习相关的调研，想问下这个框架支持在Android端侧部署训练模型吗？因为推理的话现有的方案很多，训练的话端侧方案很少。

**Comment by HIT123-C** [comment]
不支持的，不过不太明白为什么要在终端侧训练呢，是那种在线学习类型的模型吗？可以考虑分布式的形式来部署，终端侧一般都是受限于算力才进行推理框架的开发，在内存，cpu算力、NPU算力有限的情况下进行有效的推理;

**Comment by Lizhihzzx** [comment]
> 不支持的，不过不太明白为什么要在终端侧训练呢，是那种在线学习类型的模型吗？可以考虑分布式的形式来部署，终端侧一般都是受限于算力才进行推理框架的开发，在内存，cpu算力、NPU算力有限的情况下进行有效的推理;

您好，因为有时候数据不方便离开端侧，类似联邦学习，端侧迁移学习的场景，需要考虑在端侧有训练的能力，目前确实算力还差一些

**Comment by Lizhihzzx** [comment]
> 不支持的，不过不太明白为什么要在终端侧训练呢，是那种在线学习类型的模型吗？可以考虑分布式的形式来部署，终端侧一般都是受限于算力才进行推理框架的开发，在内存，cpu算力、NPU算力有限的情况下进行有效的推理;

您好，因为有些场景数据不方便离开端侧，比如联邦学习，端侧迁移学习之类的，所以需要端侧一定的训练能力，不过确实算力还差些

**Comment by jxt1234** [comment]
MNN 训练模块支持在 Android 上运行
