### ISSUE TITLE
【MNNConverter ONNX】转换工具对reshape的dim个数是有限制的吗？

### ISSUE THREAD

**Issue by TuringKi** [alibaba/MNN#1566]
如下的pytorch 代码：
H = 36
W = 64
mask = mask.view(N, 1, 9, 8, 8, H, W)

能够成功转成onnx，但是在onnx转MNN模型的时候报如下错误：
![image](https://user-images.githubusercontent.com/9394223/125259508-f4821300-e331-11eb-9511-6cd074f1fc94.png)

也是就说mnnconverter在转的时候只用到了前6个dim，而忽略了第七个。

请问如果是这样，怎样修改呢？

**Comment by HIT123-C** [comment]
这个应该是你自己手动写死的reshape吧，如果是的话，可以尝试使用其他算子代替。如果想直接用的话，需要修改MNN的源码。Reshape本身不改变数据在内存中的排布方式

**Comment by jxt1234** [comment]
MNN 目前不支持 DIM > 6 的情形，有需要可以修改 MNN 的 MNN_MAX_TENSOR_DIM 宏定义
