### ISSUE TITLE
同一个模型x86上可以运行，arm32上createSession时报Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#1569]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86:  Linux version 5.8.0-59-generic (buildd@lcy01-amd64-022) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021

arm32：Linux version 4.9.84 (causer@xmjk6401) (gcc version 8.2.1 20180802 (GNU Toolchain for the A-profile Architecture 8.2-2018-08 (arm-rel-8.23)) ) #1 SMP PREEMPT Wed Apr 7 10:57:27 CST 2021

# Github版本:
# Github Version:
下载日期：20210713
Comment = 36da4f10ec4e7cd52b66b5227ce63328fd1b51f4

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
x86:
`mkdir build
cd build
cmake..
make -j8`

arm32: 
`./project/cross-compile/build.sh arm-gnueabihf
`

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by Ryuk17** [comment]
调用代码
```
	ScheduleConfig config;    
	config.type = MNN_FORWARD_CPU;  
	config.numThread = 1;  
	Session *session = net->createSession(config);  
```

**Comment by Ryuk17** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00106ae4 in MNN::BufferAllocator::free(std::pair<void*, int>) ()

段错误发生在这个函数

**Comment by wangzhaode** [comment]
尝试使用最新的代码
