### ISSUE TITLE
run get_model.sh error

### ISSUE THREAD

**Issue by chiwangnvp** [alibaba/MNN#157]
chiwang@ubuntu:~/MNN$ sudo ./tools/script/get_model.sh 
building converter ...
===> Generating Schema...
===> Done!
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.6.1") 
CMake Error at CMakeLists.txt:59 (add_subdirectory):
  add_subdirectory given source "source/mnn" which is not an existing
  directory.

-- Configuring incomplete, errors occurred!
See also "/home/chiwang/MNN/tools/converter/build/CMakeFiles/CMakeOutput.log".
See also "/home/chiwang/MNN/tools/converter/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat '../tools/converter/build/MNNConvert': No such file or directory
downloading mobilenet_v1.caffe.caffemodel ...
download mobilenet_v1.caffe.caffemodel failed
./tools/script/get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./tools/script/get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./tools/script/get_model.sh: line 38: ./build/MNNConvert: No such file or directory
./tools/script/get_model.sh: line 48: ./build/MNNConvert: No such file or directory

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
./tools/script/get_model.sh: line 58: ./build/MNNConvert: No such file or directory

**Comment by chiwangnvp** [comment]
chiwang@ubuntu:~/MNN$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by li-qing** [comment]
could not find 'source/mnn' in our CMakeLists.txt. did you edit it?

**Comment by 17759205390** [comment]
@chiwangnvp 加微信17759205390，这个我解决了
