### ISSUE TITLE
ONNX conversion  produce expected result on arm CPU only with --fp16 option !!!!

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#1571]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Imx8 plus

# Github版本:
# Github Version:
master

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
8a82f5c5a7ae37192784c2dbd6dfc8ca8833565a
Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``
git clone
# 编译方式:
# Compiling Method
cmake -DCMAKE_BUILD_TYPE=Release  -DMNN_OPENMP=ON -DMNN_OPENCL=ON  -DMNN_VULKAN=ON -DMNN_OPENGL=ON -DMNN_USE_THREAD_POOL=OFF -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DMNN_BUILD_BENCHMARK=true
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

Hi , 
1. I am converted ONNX model from https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch.
   ./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz
2. I am comparing execution same input on windows with openvino and imx8 plus with MNN.
3. Pose estimation failed with MNN output on imx8  plus .
4. NOW IF I ADD TO CONVERSION OPTION --fp16 and STILL RUNNING ON CPU I AM GETTING SAME POSE ESTIMATION AS ON WINDOWS !!!!!!!!!!!!!!!!!

Please check .

**Comment by jxt1234** [comment]
fp16 doesn't matter for the execute of model. And we can't reproduce your error.
