### ISSUE TITLE
CPURNNSequenceGRU 一个 batch 中的每个 slice 是否需要初始化 hiddenState

### ISSUE THREAD

**Issue by DreamChaserMXF** [alibaba/MNN#1573]
https://github.com/alibaba/MNN/blob/36da4f10ec4e7cd52b66b5227ce63328fd1b51f4/source/backend/cpu/CPURNNSequenceGRU.cpp#L197-L200

CPURNNSequenceGRU 一个 batch 中的每个 slice 是否需要初始化 hiddenState 为0？如果不初始化的话，b=1的结果会受到b=0的结果的影响吧？

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/blob/36da4f10ec4e7cd52b66b5227ce63328fd1b51f4/source/backend/cpu/CPURNNSequenceGRU.cpp#L186

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/blob/36da4f10ec4e7cd52b66b5227ce63328fd1b51f4/source/backend/cpu/CPURNNSequenceGRU.cpp#L186
是有初始化的

**Comment by DreamChaserMXF** [comment]
> https://github.com/alibaba/MNN/blob/36da4f10ec4e7cd52b66b5227ce63328fd1b51f4/source/backend/cpu/CPURNNSequenceGRU.cpp#L186
> 
> 
> 是有初始化的

很明显这是一次性的初始化，并不是每个 batch slice 都初始化。

**Comment by jxt1234** [comment]
这个是所有的 hidden data 初始化

**Comment by DreamChaserMXF** [comment]
> 这个是所有的 hidden data 初始化

代码中一个 batch 的所有 slice 共用一段 hidden data。

b=0 推理完成，得到正确结果，hidden data 此时已经不为0。
b=1 推理时，会用到已经被写花了的 hidden data。
