### ISSUE TITLE
onnx转mnn问题

### ISSUE THREAD

**Issue by SicleBoypy** [alibaba/MNN#1579]
onnx转mnn，突然多出一个output，多出output和其中的一个input名字一样，导致getSessionInputAll找不到该input，
![image](https://user-images.githubusercontent.com/23249973/126461037-61ce8739-95ed-4f4c-9b3b-a085e0fe0019.png)

**Comment by jxt1234** [comment]
这个是因为在 onnx 里面该 input 直接作为输出了吧
