### ISSUE TITLE
run Portrait errors !

### ISSUE THREAD

**Issue by chiwangnvp** [alibaba/MNN#158]
--------- beginning of crash
01-02 06:56:14.895  1842  1842 E AndroidRuntime: FATAL EXCEPTION: main
01-02 06:56:14.895  1842  1842 E AndroidRuntime: Process: com.taobao.android.mnndemo, PID: 1842
01-02 06:56:14.895  1842  1842 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.taobao.android.mnndemo/com.taobao.android.mnndemo.PortraitActivity}: java.lang.RuntimeException: Fail to connect to camera service
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:203)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6251)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
01-02 06:56:14.895  1842  1842 E AndroidRuntime: Caused by: java.lang.RuntimeException: Fail to connect to camera service
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.hardware.Camera.<init>(Camera.java:643)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.hardware.Camera.open(Camera.java:491)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.taobao.android.utils.PortraitCameraView.openCamera(PortraitCameraView.java:77)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.taobao.android.utils.PortraitCameraView.switchCamera(PortraitCameraView.java:209)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.taobao.android.mnndemo.PortraitActivity.cameraDetect(PortraitActivity.java:131)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at com.taobao.android.mnndemo.PortraitActivity.onCreate(PortraitActivity.java:118)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6666)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
01-02 06:56:14.895  1842  1842 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)

**Comment by jxt1234** [comment]
Fail to connect to camera service

Check if the camera permission is open for demo

**Comment by chiwangnvp** [comment]
yes! videoactivity could open the camera, but the portraitactivity is failed.
