### ISSUE TITLE
多个模型串行运行，MNN每次推理时间不一样

### ISSUE THREAD

**Issue by ycdhqzhiai** [alibaba/MNN#1581]
android ndk-r21e编译，多个模型串行运行，其中某一个每次推理耗时相差较大，最小的16ms，最大的47ms.如果单独测试该模型推理耗时，稳定在16ms左右，这是什么原因，有人遇见过吗

**Comment by jxt1234** [comment]
是否是第三个模型，多线程失效了，参考 https://www.yuque.com/mnn/cn/create_session 里面用共享 runtime 的方法试试

**Comment by pineleen** [comment]
> 是否是第三个模型，多线程失效了，参考 https://www.yuque.com/mnn/cn/create_session 里面用共享 runtime 的方法试试

大佬，有计划修改这个限制吗？ 能不能做成线程池和模型绑定，配置4个就会创建4个，再多一个模型，共创建8个，以此类推，让使用的人自己决定线程数

**Comment by ycdhqzhiai** [comment]
@jxt1234 是这样的，按照https://www.yuque.com/mnn/cn/create_session里面共享runtime解决了。谢谢解答
