### ISSUE TITLE
MNN1.1.0 opencl使用闪退

### ISSUE THREAD

**Issue by xxssd-awsl** [alibaba/MNN#1582]
android，MNN1.1.0不论是编译出的.so文件还是提供的.so文件，在使用时都会在检测到人脸时闪退，调用的代码是[UltraFace.cpp](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/MNN/src/UltraFace.cpp)，模型也是用他的slim-320.mnn模型，甚至用mnn1.2.0转换工具重新转换了一次，MNN1.0.2和MNN0.2都没有问题

**Comment by xxssd-awsl** [comment]
debug一天了，目前确定是1.1、1.2有这个问题，1.0及0.2正常

**Comment by xxssd-awsl** [comment]
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10bf0 in tid 32174 (CameraBackgroun), pid 31647 (traface_android)
Connected to process 32274 on device 'xiaomi-mi_10-953684f4'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Perf: Connecting to perf service.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/traface_androi: The ClassLoaderContext is a special shared library.
I/traface_androi: The ClassLoaderContext is a special shared library.
W/traface_androi: Accessing hidden method Lmiui/contentcatcher/sdk/Token;-><init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V (greylist, linking, allowed)
W/traface_androi: Accessing hidden method Lmiui/contentcatcher/InterceptorProxy;->getWorkThread()Landroid/os/HandlerThread; (greylist, linking, allowed)
D/ViewContentFactory: initViewContentFetcherClass
    getInterceptorPackageInfo
W/traface_androi: Accessing hidden method Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application; (greylist, linking, allowed)
D/ViewContentFactory: getInitialApplication took 0ms
    packageInfo.packageName: com.miui.catcherpatch
D/ViewContentFactory: initViewContentFetcherClass took 5ms
I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory: createInterceptor took 5ms
W/traface_androi: Accessing hidden method Lmiui/contentcatcher/sdk/injector/IContentDecorateCallback$Stub;-><init>()V (greylist, linking, allowed)
    Accessing hidden method Lmiui/contentcatcher/sdk/ContentCatcherManager;->getInstance()Lmiui/contentcatcher/sdk/ContentCatcherManager; (greylist, linking, allowed)
    Accessing hidden method Lmiui/contentcatcher/sdk/ContentCatcherManager;->registerContentInjector(Lmiui/contentcatcher/sdk/Token;Lmiui/contentcatcher/sdk/injector/IContentDecorateCallback;)V (greylist, linking, allowed)
W/traface_androi: Accessing hidden method Lmiui/contentcatcher/sdk/ContentCatcherManager;->getPageConfig(Lmiui/contentcatcher/sdk/Token;)Lmiui/contentcatcher/sdk/data/PageConfig; (greylist, linking, allowed)
    Accessing hidden method Lmiui/contentcatcher/sdk/data/PageConfig;->getFeatures()Ljava/util/ArrayList; (greylist, linking, allowed)
    Accessing hidden method Lmiui/contentcatcher/sdk/data/PageConfig;->getCatchers()Ljava/util/ArrayList; (greylist, linking, allowed)
W/traface_androi: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
I/AdrenoGLES-0: QUALCOMM build                   : 191610ae03, Ic907de5ed0
    Build Date                       : 09/17/20
    OpenGL ES Shader Compiler Version: EV031.32.02.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.12.10.00.00.582.274
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
    Build Config                     : S P 10.0.5 AArch64
    Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016dd091, ME: 0x00000000
I/traface_androi: ProcessProfilingInfo new_methods=704 is saved saved_to_disk=1 resolve_classes_delay=8000

**Comment by xxssd-awsl** [comment]
用rk3288（android7）试了一下，不断重复opencl检测（画面无人脸），这个信息会一直报出来：
E/MNNJNI: Load Cache file error.
I/MNNJNI: softmax not support dimensions == 3 
I/MNNJNI: The Creator Don't support type 85, scores
I/MNNJNI: Write cache to .tempcache, size = 220492
E/MNNJNI: Open .tempcache error

**Comment by xxssd-awsl** [comment]
debug两天了，解决方法：根据地址获取数值那块请参考官方demo中的方法，类同。应该是opencl优化导致以前的操作现在在cpu上没问题但是用Opencl就出错

**Comment by wjwang0816** [comment]
xxssd-awsl 您好~  在下最近嘗試  [UltraFace.cpp](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/MNN/src/UltraFace.cpp)  無論使用UltraFace 所提供的哪種MNN模型, 都會遇到 **"softmax not support dimensions == 3"** 的問題, 請教您最後具體是如何解決的呢? 非常謝謝!

**Comment by fuerpy** [comment]
@wjwang0816 你好，请问这个问题有解决吗？
