### ISSUE TITLE
PyTorch模型转换后，BN层计算错误（Pytorch->ONNX->MNN）

### ISSUE THREAD

**Issue by 369zz** [alibaba/MNN#1584]
从一些资料看，MNN 的 BN 层采用了如下简化计算的方法：
![image](https://user-images.githubusercontent.com/22151569/126855507-a253ea3f-bc82-4c3b-86e0-bfcb71b45b83.png)

但是，我根据这个公式算出来的结果和 MNN 的输出刚好差一个 b ……

# 平台(如果交叉编译请再附上交叉编译目标平台):  
Ubuntu 18.04 x86

# Github版本:
8a82f5c5a7ae37192784c2dbd6dfc8ca8833565a

# 编译方式:
同官方示例

# 编译日志:
无异常

**Comment by jxt1234** [comment]
呃，有参考 https://www.yuque.com/mnn/cn/model_convert 校验过么。这个层一般是不会有问题的

**Comment by 369zz** [comment]
校验过了，结果就是误差过大……

`
TESTERROR output value error : absMaxV:2.845006 - DiffMax 0.777814
Save mnn result to  .error director
`
测试的网络结构和参数如图所示：
![image](https://user-images.githubusercontent.com/22151569/127823479-51bac664-2633-4d09-bcef-8720f06841d3.png)
