### ISSUE TITLE
Converted MNN file had big file size

### ISSUE THREAD

**Issue by AnhPC03** [alibaba/MNN#1586]
Hello, my pytorch model had 17MB file size. When I exported to ONNX model, it had 30MB file size. But after that, I converted to MNN model, it had 30MB file size. Was I wrong? I hoped that MNN model had small size than Pytorch one.
Thank you for your explanation.
P.s: I used [this](https://www.yuque.com/mnn/en/usage_in_python) method to convert ONNX model to MNN one.

**Comment by pablogsanchez** [comment]
Quantize the model or use float16 to reduce the size of the model.

**Comment by AnhPC03** [comment]
@pablogsanchez I did it, thanks for your suggestions.
