### ISSUE TITLE
android demo使用opencl或者vulkan不起作用

### ISSUE THREAD

**Issue by gray2bgr** [alibaba/MNN#1587]
你好，我初始化的设置如下图所示，使用opencl和vulkan还有其他需要设置的么，因为我这么设置实际在跑demo的时候，选用opencl或者valkan时候的性能与cpu一致，且与线程数相关。从结果上来看不太合理，这里还有什么地方可以操作的么
![image](https://user-images.githubusercontent.com/43072388/126903244-df42eeb8-aacd-492b-90a0-258d04427a85.png)

代码参考来源：https://github.com/cmdbug/MNN_Demo/blob/main/android_MNN_Demo/app/src/main/cpp/NanoDet.cpp
我测试了这个demo，同样不起作用

**Comment by CDLCHOI** [comment]
需要在你执行build_64.sh时添加 -DMNN_OPENCL=ON，然后会产生一个libMNN_CL.so，把库链接上，才会真正调用到opencl。虽然写的是FORWARD_OPENCL，但是他找不到opencl库的时候会自动换回cpu运行，去demo/exec/pictureRecognition.cpp的第51行看，可以显示真正调用的后端是什么
