### ISSUE TITLE
MNN INT8 quantization sucess, but inference got error.

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [alibaba/MNN#1593]
# 问题描述
INT8量化成功，没有报错，但是使用python和c++推理报错。(注意fp32的mnn模型是正常运行的，INT8的mnn模型会报错)。
报错信息如下：
```
Error for compute convolution shape, need channel = 3, input channel = 1
Compute Shape Error for superpoint/pred_tower0/backbone/mobilenetv2_s16/init_conv/conv/BiasAdd:0
Can't run session because not resized
```
# pyhon推理脚本
注意：其中superpoint_mb_softmax_op11-opt.mnn为fp32模型，superpoint_mb_softmax_op11-opt_int8.mnn为INT8模型。
```
#interpreter = MNN.Interpreter("superpoint_mb_softmax_op11-opt.mnn")
interpreter = MNN.Interpreter("superpoint_mb_softmax_op11-opt_int8.mnn")
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
img = np.zeros((1,1,480,640),dtype=np.float32)
tmp_input = MNN.Tensor((1, 1, 480, 640), MNN.Halide_Type_Float,img, MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(tmp_input)

interpreter.runSession(session)
output_tensor = interpreter.getSessionOutput(session)
```

# Platform(Include target platform as well if cross-compiling):  
CentOS Linux release 7.5.1804 (Core)

# Github Version:
Commit = 36da4f10ec4e7cd52b66b5227ce63328fd1b51f4
Date:   Fri Jul 9 22:40:45 2021 +0800

# 模型INT8量化过程
```
./quantized.out quan/superpoint_mb_softmax_op11-opt.mnn quan/superpoint_mb_softmax_op11-opt_int8.mnn preprocessConfig.json
```
# preprocessConfig.json内容
```
{
    "format":"RGB",
    "mean":[
        127.5,
        127.5,
        127.5
    ],
    "normal":[
        0.00784314,
        0.00784314,
        0.00784314
    ],
    "width":640,
    "height":480,
    "path":"quan/coco",
    "used_image_num":500,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS"
}
```

# INT8量化日志
```
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:23: >>> modelFile: quan/superpoint_mb_softmax_op11-opt.mnn
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:24: >>> preTreatConfig: preprocessConfig.json
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:25: >>> dstFile: quan/superpoint_mb_softmax_op11-opt_int8.mnn
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:52: Calibrate the feature and quantize model...
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:155: Use feature quantization method: KL
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:156: Use weight quantization method: MAX_ABS
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:176: feature_clamp_value: 127
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:177: weight_clamp_value: 127
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/Helper.cpp:104: used image num: 500
[21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:660: fake quant weights done.
ComputeFeatureRange: 100.00 %
CollectFeatureDistribution: 100.00 %
[21:06:17] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:57: Quantize model done!
```
# 模型链接
[INT8quantization.zip](https://github.com/alibaba/MNN/files/6885724/INT8quantization.zip)

**Comment by zhuxiaoxuhit** [comment]
模型为自己修改的superpoint~
# 输入输出信息
输入：
```
superpoint/image: [1, 480, 640, 1]
```
输出：
```
superpoint/descriptors_raw: [1, 60, 80, 128]
superpoint/logits_softmax: [1, 60, 80, 65]
```

**Comment by zhuxiaoxuhit** [comment]
辛苦修复一下bug~~

**Comment by barbecacov** [comment]
.json里 你是不是需要修改一下？
format
图片统一按RGBA读取，然后转换到format指定格式
可选："RGB", "BGR", "RGBA", "GRAY"

**Comment by zhuxiaoxuhit** [comment]
> .json里 你是不是需要修改一下？
> format
> 图片统一按RGBA读取，然后转换到format指定格式
> 可选："RGB", "BGR", "RGBA", "GRAY"

感谢回复，谢谢提醒。
通过量化得到可以用的模型，是不是和数据没关系？数据格式输入错误可能会影响模型预测准确度，但是模型应该能正常推理，只是推理结果不好，而不应该报错。

**Comment by liuqinglong110** [comment]
> 遇到同样的问题使用GRAY format解决了

您好，我也在使用GRAY 单通道的图片。量化模型转换都没问题，就是检测不到结果。但是，量化之前都检测正确的。
{
    "format":"GRAY",
    "mean":[
        129.75343168

    ],
    "normal":[
        0.0138767869
    ],

    "width":320,
    "height":320,
    "path":"/app/img/",
    "used_sample_num":500,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS",
    "batch_size":220,
    "quant_bits":8,
    "input_type":"image",
    "debug":false
}

**Comment by yyfcc17** [comment]
> # 问题描述
> INT8量化成功，没有报错，但是使用python和c++推理报错。(注意fp32的mnn模型是正常运行的，INT8的mnn模型会报错)。 报错信息如下：
> 
> ```
> Error for compute convolution shape, need channel = 3, input channel = 1
> Compute Shape Error for superpoint/pred_tower0/backbone/mobilenetv2_s16/init_conv/conv/BiasAdd:0
> Can't run session because not resized
> ```
> 
> # pyhon推理脚本
> 注意：其中superpoint_mb_softmax_op11-opt.mnn为fp32模型，superpoint_mb_softmax_op11-opt_int8.mnn为INT8模型。
> 
> ```
> #interpreter = MNN.Interpreter("superpoint_mb_softmax_op11-opt.mnn")
> interpreter = MNN.Interpreter("superpoint_mb_softmax_op11-opt_int8.mnn")
> session = interpreter.createSession()
> input_tensor = interpreter.getSessionInput(session)
> img = np.zeros((1,1,480,640),dtype=np.float32)
> tmp_input = MNN.Tensor((1, 1, 480, 640), MNN.Halide_Type_Float,img, MNN.Tensor_DimensionType_Caffe)
> input_tensor.copyFrom(tmp_input)
> 
> interpreter.runSession(session)
> output_tensor = interpreter.getSessionOutput(session)
> ```
> 
> # Platform(Include target platform as well if cross-compiling):
> CentOS Linux release 7.5.1804 (Core)
> 
> # Github Version:
> Commit = [36da4f1](https://github.com/alibaba/MNN/commit/36da4f10ec4e7cd52b66b5227ce63328fd1b51f4) Date: Fri Jul 9 22:40:45 2021 +0800
> 
> # 模型INT8量化过程
> ```
> ./quantized.out quan/superpoint_mb_softmax_op11-opt.mnn quan/superpoint_mb_softmax_op11-opt_int8.mnn preprocessConfig.json
> ```
> 
> # preprocessConfig.json内容
> ```
> {
>     "format":"RGB",
>     "mean":[
>         127.5,
>         127.5,
>         127.5
>     ],
>     "normal":[
>         0.00784314,
>         0.00784314,
>         0.00784314
>     ],
>     "width":640,
>     "height":480,
>     "path":"quan/coco",
>     "used_image_num":500,
>     "feature_quantize_method":"KL",
>     "weight_quantize_method":"MAX_ABS"
> }
> ```
> 
> # INT8量化日志
> ```
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:23: >>> modelFile: quan/superpoint_mb_softmax_op11-opt.mnn
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:24: >>> preTreatConfig: preprocessConfig.json
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:25: >>> dstFile: quan/superpoint_mb_softmax_op11-opt_int8.mnn
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:52: Calibrate the feature and quantize model...
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:155: Use feature quantization method: KL
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:156: Use weight quantization method: MAX_ABS
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:176: feature_clamp_value: 127
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:177: weight_clamp_value: 127
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/Helper.cpp:104: used image num: 500
> [21:01:39] /data/zhuxiaoxu/MNN/tools/quantization/calibration.cpp:660: fake quant weights done.
> ComputeFeatureRange: 100.00 %
> CollectFeatureDistribution: 100.00 %
> [21:06:17] /data/zhuxiaoxu/MNN/tools/quantization/quantized.cpp:57: Quantize model done!
> ```
> 
> # 模型链接
> [INT8quantization.zip](https://github.com/alibaba/MNN/files/6885724/INT8quantization.zip)

报错说了需要的输入通道是3，你却给了1，当然报错，你输入应该给3通道

**Comment by yyfcc17** [comment]
@liuqinglong110 你模型输入是什么格式，量化时就指定什么格式，跟别人的模型没关系。量化是有误差的，可能你这个模型量化之后误差较大，feature量化方法可以试试EMA方法。如果还不行的话，可以用MNN转换器的权值量化选项，仅压缩模型大小到原来4分之一，速度和float一样，精度基本无损

**Comment by 0Element0** [comment]
我的也是量化前的MNN模型是能跑的，量化后却报这个错，Alloc memory error for extract idst int8
Segmentation fault，怎么解呢？
