### ISSUE TITLE
mnnconvert bug

### ISSUE THREAD

**Issue by barbecacov** [alibaba/MNN#1601]
When i convert my model from onnx -> mnn in mnn-1.1.4，everything is OK

But when i do it in mnn-1.2.1， there is a msg "532 op name is empty or dup, set to Const532" print，and the transed model is not OK.

**Comment by jxt1234** [comment]
The msg "532 op name is empty or dup, set to Const532" print doesn't matter.
Use tools/scripts/fastTestOnnx.py to check it.
If has error, upload onnx model and I will check.
