### ISSUE TITLE
很奇怪！我用mnn-python-1.1.4转的模型在mnn-python-1.2.1上运行，结果差别很大

### ISSUE THREAD

**Issue by barbecacov** [alibaba/MNN#1602]

**Comment by barbecacov** [comment]
pytorch -> onnx：
torch.onnx.export(pytorch_model, dummpy_input, ONNX_PATH, verbose=False, opset_version=11,                  
                  input_names=['input1'], output_names=['output1'])

onnx -> mnn:
'mnnconvert -f ONNX --modelFile %s --MNNModel %s --bizCode biz ' % (ONNX_PATH, MNN_PATH)

msg print:

Start to Convert Other Model Format To MNN Model...
[10:05:22] :30: ONNX Model ir version: 6
Start to Optimize the MNN Net...
532 op name is empty or dup, set to Const532
inputTensors : [ input1, ]
outputTensors: [ output1, ]
Converted Success!


But When eval the model, the result is:
torch out : tensor([[ 1.6257, -1.6097]])
onnx out : [[ 1.6257136 -1.6096536]]
mnn out: (1.222586989402771, -1.232900619506836)


And When do these in mnn-python-1.1.4, everything is fine！

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/model_convert 先校验一下

**Comment by MambaWong** [comment]
我也遇到了同样的问题。我的模型中的问题反应在 `Eltwise` 上。
1.1.4 中量化之后已经将 `Eltwise` 的 outputScaleParam 写进了量化之后的模型中，但是在 1.2.1 中会调整量化模型的 scale，其中可能就会调整某个 `Eltwise` 的 outputScale。而 `Eltwise` 在初始化的时候又是按照量化模型中的 scale 做的，所以会有问题。
**最简单的解决方式就是保持 MNN 版本一致。这只是我所发现的问题所在，仅供参考。**
相关代码块如下：
https://github.com/alibaba/MNN/blob/5e127496fc7da0612f4ccb323871452ee999b92b/tools/quantization/calibration.cpp#L500-L529
https://github.com/alibaba/MNN/blob/1a7d0a61731d544ec34cb641811bad7c9890aedd/source/core/Pipeline.cpp#L202-L286
https://github.com/alibaba/MNN/blob/1a7d0a61731d544ec34cb641811bad7c9890aedd/source/backend/cpu/CPUEltwiseInt8.cpp#L22-L42
