### ISSUE TITLE
这东西在win上咋编译啊

### ISSUE THREAD

**Issue by GesilaA** [alibaba/MNN#1603]
# 平台(如果交叉编译请再附上交叉编译目标平台):  windows11

# Github版本: 2.31.1

# 编译方式:
./schema/generate.ps1
.\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x64

总是回车之后要求输入pyc_env MNN_path 啥的，输入python路径和mnn路径后回车，又报路径过长

**Comment by jxt1234** [comment]
./schema/generate.ps1 这个可以不用执行
