### ISSUE TITLE
Run  python demo failed in 'MNN/pymnn/examples/MNNEngineDemo'

### ISSUE THREAD

**Issue by liziru** [alibaba/MNN#1604]
Thanks for your great job. 

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86_64 linux 

# Github版本:
# Github Version:
76e62a1
mnn-1.2.1 
# 编译方式:
# Compiling Method
python pip package 
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
When MNN is installed via 'pip install MNN', I test python decoding scripts. And I got the following error message: 
![image](https://user-images.githubusercontent.com/34911790/127736241-02cfcf6d-c830-4b2b-a399-b072b0071f4f.png)

environment info: python version3.7.11
![image](https://user-images.githubusercontent.com/34911790/127736267-c2a7d255-104e-4473-b756-dc5089c70833.png)

What's the problem? 
Looking forward to your reply.

**Comment by jxt1234** [comment]
Load cache file error doesn't matter. 
The pymnn hasen't been updated, you can build it by build it self.

**Comment by liziru** [comment]
> Load cache file error doesn't matter.
> The pymnn hasen't been updated, you can build it by build it self.

yes, I also tried to build it myself, but got the following error message: 
![image](https://user-images.githubusercontent.com/34911790/127819969-bc4849dc-d802-47dd-bb71-60d870509793.png)
