### ISSUE TITLE
setup.py: error: the following arguments are required: --version

### ISSUE THREAD

**Issue by zjykzj** [alibaba/MNN#1605]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04

# Github版本:
# Github Version:
MNN1.2.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

refer to  MNN/pymnn/INSTALL.md 

1、进入pymnn/pip_package 目录 2、python3 build_deps.py 3、sudo python3 setup.py install

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

$ sudo python3 setup.py install
usage: setup.py [-h] [--x86] --version VERSION
setup.py: error: the following arguments are required: --version

my question: why need support version again???  and what the version is ??？

**Comment by zjykzj** [comment]
问题解决了！！！

官方教程[推理框架Windows编译](https://www.yuque.com/mnn/cn/build_windows)有问题

```
cd /path/to/MNN
powershell # 运行该命令从cmd环境进入powershell环境，后者功能更强大

./schema/generate.ps1

# CPU, 64位编译
.\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x64
# CPU, 32位编译
.\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x86

# CPU+OpenCL+Vulkan, 64位编译
.\package_scripts\win\build_lib.ps1 -path MNN-CPU-OPENCL/lib/x64 -backends "opencl,vulkan"
# CPU+OpenCL+Vulkan, 32位编译
.\package_scripts\win\build_lib.ps1 -path MNN-CPU-OPENCL/lib/x86 -backends "opencl,vulkan"
```

进入powershell后执行上述编译命令，会要求你输入版本、MNN路径等的等等信息

参考[win10 + VS2017 + MNN 编译使用](https://www.cnblogs.com/xuanyuyt/p/14727374.html)

1. 首先以管理员身份打开命令行窗口
2. 执行下述命令允许直接运行powershell命令

```
powershell set-executionpolicy -executionpolicy unrestricted
```

3. 参考官网教程继续后续操作

```
$ powershell ./schema/generate.ps1
$ powershell .\package_scripts\win\build_lib.ps1 -path MNN-CPU/lib/x64
```

@MNNTeam 需要修改一下官方教程

**Comment by wangzhaode** [comment]
必须指定版本，用法为：`sudo python setup.py install --version 1.0.0`

不过当前最新版本不指定版本可以使用默认版本
