### ISSUE TITLE
MNNPythonOfflineQuant这个工具量化出来后的模型

### ISSUE THREAD

**Issue by barbecacov** [alibaba/MNN#1606]
症状：
我是因为我的模型输入是（1， 24， 224， 224），所以才用到这个工具。

然而量化出来的模型，无论什么输入，其前向的输出结果都是一样的。

请问这种情况可能会是什么造成的呢

**Comment by barbecacov** [comment]
我发现了一个问题。

[config.yaml](https://github.com/alibaba/MNN/blob/1.1.7/tools/MNNPythonOfflineQuant/config.yaml)中写的是shape:(1, 3, 224,224)， formats:（nchw）

但是在[calibration_dataset.py](https://github.com/alibaba/MNN/blob/master/tools/MNNPythonOfflineQuant/calibration_dataset.py)的84行写的却是（1， 224， 224， 3），以及F.data_format.NHWC。
正好相悖了。

请问这是demo给错了还是本身就应该这样呢

**Comment by jxt1234** [comment]
有可能是数据问题?

**Comment by StrugglingForBetter** [comment]
> 我发现了一个问题。
> 
> [config.yaml](https://github.com/alibaba/MNN/blob/1.1.7/tools/MNNPythonOfflineQuant/config.yaml)中写的是shape:(1, 3, 224,224)， formats:（nchw）
> 
> 但是在[calibration_dataset.py](https://github.com/alibaba/MNN/blob/master/tools/MNNPythonOfflineQuant/calibration_dataset.py)的84行写的却是（1， 224， 224， 3），以及F.data_format.NHWC。 正好相悖了。
> 
> 请问这是demo给错了还是本身就应该这样呢

请问是一定要这样才能跑成功吗？如果不这样是不是不能成功？我这边有和你类似的情况，但是一直没有跑成功

**Comment by yyfcc17** [comment]
config里面写 1， 24， 224， 224
