### ISSUE TITLE
mnn支持unfold算子吗

### ISSUE THREAD

**Issue by tonylin52** [alibaba/MNN#1607]
请问ncnn支持torch的 unfold算子吗？有哪些算子是支持的呢？

**Comment by jxt1234** [comment]
这里是 mnn ，你可以自己导出转一下试试

**Comment by nihui** [comment]
> 请问ncnn支持torch的 unfold算子吗？有哪些算子是支持的呢？

用 pnnx 工具支持 torch unfold 转到 ncnn，如有问题请去 ncnn github 发issue
