### ISSUE TITLE
Segmentation fault with OpenGL on GPU

### ISSUE THREAD

**Issue by msx23** [alibaba/MNN#1614]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Raspberry Pi 4 B, but also tested on other armv7 boards with Linux (same behaviour) 

# Github版本:
# Github Version:
1.1.6  (because 1.2 gives Assembler error when compiling, probably another bug)

# 编译方式:
# Compiling Method
cmake -DMNN_BUILD_BENCHMARK=true -D MNN_OPENGL=ON -D MNN_USE_SYSTEM_LIB=ON -D MNN_SEP_BUILD=OFF ..

also tested (with same behaviour):
cmake -DMNN_BUILD_BENCHMARK=true -D MNN_OPENGL=ON -D CMAKE_BUILD_TYPE=Release -D MNN_BUILD_QUANTOOLS=ON -D MNN_BUILD_CONVERTER=ON -D MNN_BUILD_DEMO=ON -D MNN_USE_SYSTEM_LIB=ON -D MNN_SEP_BUILD=ON ..

the following commands are necessary for a successful build on Raspberry Pi:
```
$ apt-get install libglew-dev mesa-common-dev libegl1-mesa-dev libgles2-mesa-dev
$ ln -s  /usr/lib/arm-linux-gnueabihf/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv3.so

# edit build/CMakeFiles/benchmarkExprModels.out.dir/link.txt and append the following in the middle (before -Wl):
-L/usr/lib/arm-linux-gnueabihf -lGLEW

```

# 编译日志:
# Build Log:
```
$ make MNN_GL benchmarkExprModels.out -j 4
[  0%] Built target MNNUtils
[  6%] Built target MNNCV
[ 20%] Built target MNNARM32
[ 51%] Built target MNNCPU
[ 51%] Built target MNNMath
[ 55%] Built target MNNCore
[ 93%] Built target MNNTransform
[ 93%] Built target MNN
[100%] Built target MNN_GL
[  0%] Built target MNNUtils
[  6%] Built target MNNCV
[ 19%] Built target MNNARM32
[ 47%] Built target MNNCPU
[ 47%] Built target MNNMath
[ 52%] Built target MNNCore
[ 86%] Built target MNNTransform
[ 86%] Built target MNN
[ 91%] Built target MNN_Express
[ 97%] Built target MNN_GL
Scanning dependencies of target benchmarkExprModels.out
[100%] Building CXX object CMakeFiles/benchmarkExprModels.out.dir/benchmark/benchmarkExprModels.cpp.o
[100%] Linking CXX executable benchmarkExprModels.out
[100%] Built target benchmarkExprModels.out
```

--> Compilation is successful

--> CPU inference works as expected

--> But as soon as I use the OpenGL backend I get the following error:
```
$ ./benchmarkExprModels.out ResNet_100_18 2 4 1
MNN Expr Models benchmark
Forward type: **N/A** thread=1
libEGL warning: DRI2: failed to authenticate
not support half 
Speicherzugriffsfehler (is german for segmentation fault)
```

--> I get the same error when using another default model or an own model

--> Changing the backend settings "Precision" and "Power" does also not help

Does someone have an idea how I can get MNN working on a GPU with OpenGL?

**Comment by jxt1234** [comment]
Can you use opencl / vulkan instead ?

**Comment by msx23** [comment]
No, unfotunately not, these are not available on my board
