### ISSUE TITLE
build MNN failed in raspberry os. 

### ISSUE THREAD

**Issue by liziru** [alibaba/MNN#1615]
# Github版本:
# Github Version:
312b003f4c05b35d1306cea8a7234f658f849cee

# 编译方式:
# Compiling Method
build in raspberry os directly, which follows building steps as follows: 

![image](https://user-images.githubusercontent.com/34911790/128499693-4f0850d1-e698-45d6-8e25-c72cc0b903ec.png)

# 编译日志:
# Build Log:
![image](https://user-images.githubusercontent.com/34911790/128499748-b5356740-5724-467a-be84-73e7b38aef78.png)

What's wrong with my building steps? 
Looking forward to your reply.

**Comment by wangzhaode** [comment]
movw & movt is standard instruction in ARMv7.
WHAT compiler and WHICH version do you use ?

**Comment by liziru** [comment]
> movw & movt is standard instruction in ARMv7.
> WHAT compiler and WHICH version do you use ?

Thanks for your reply. 
After 'cmake ..', I use 'make' to compile mnn, so the default compiler should be gcc and g++ whose version is shown as follows.
![image](https://user-images.githubusercontent.com/34911790/128511420-d841d7cd-a0a6-43e5-929f-68d0201a7463.png)

**Comment by wangzhaode** [comment]
Ok, I will replace these two instruction with memory load later.

**Comment by liziru** [comment]
> Ok, I will replace these two instruction with memory load later.

Nice.  Thank you very much. Looking forward to your updates.

**Comment by Qengineering** [comment]
I've the same issue here. I suspect it's to do with gcc's default settings on a Raspberry Pi 32-bit OS. Although armv7, the compiler is default set to armv6, which, indeed, don't support the assembly instructions. 

![image](https://user-images.githubusercontent.com/44409029/128518241-79229adf-ff05-4c1c-b55e-ede750046e8e.png)

**Comment by Qengineering** [comment]
Dear @liziru,

Please change line 247 in CMakeLists.txt to
```
add_definitions(-march=armv7-a -mfpu=neon-vfpv4)    #please define in project/cross-compile/arm.toolchain.cmake
```
This will fix the issue on the Raspberry Pi 32-bit OS

**Comment by liziru** [comment]
> the

Great! It works. Thank you.

**Comment by wangzhaode** [comment]
> Dear @liziru,
> 
> 
> 
> Please change line 247 in CMakeLists.txt to
> 
> ```
> 
> add_definitions(-march=armv7-a -mfpu=neon-vfpv4)    #please define in project/cross-compile/arm.toolchain.cmake
> 
> ```
> 
> This will fix the issue on the Raspberry Pi 32-bit OS

Thanks!So these v7 instructions don't need replace.

**Comment by Qengineering** [comment]
No, don't change the assembly code, it's fine. Only add the -mfpu=neon-vfpv4 to the make file. After all, the instructions where it all goes wrong are NEON instructions, hence the extra directive
