### ISSUE TITLE
Tensorflow NHWC格式 转换成 CAFFE NCHW格式，出现错误，隔一个数字就出现一个0。

### ISSUE THREAD

**Issue by mao381332619** [alibaba/MNN#1618]
```
photo = cv::imread("test_image/2007_000039.jpg");
photo.convertTo(photo,CV_32FC3);
auto hostTensor = Tensor::create<float>({1,224,224,3},NULL,MNN::Tensor::TENSORFLOW);
auto data = hostTensor->host<float>();
memcpy(data,photo.data,hostTensor->size());
inputTensor->copyFromHostTensor(hostTensor);
```

inpurTensor是CAFFE格式的，类型也是float
hostTensor内容
![image](https://user-images.githubusercontent.com/54882489/128676984-b4cd8814-7385-487e-a90f-c48c90939138.png)
copy后inputTensor的内容
![image](https://user-images.githubusercontent.com/54882489/128677106-0351495c-22e5-44c3-bc4b-2ecfc53a01b1.png)

**Comment by jxt1234** [comment]
这个是 NC4HW4 会补零上对齐，对外透出仍然是 CAFFE 以便用户建 host tensor
