### ISSUE TITLE
针对Transformer结构的加速 

### ISSUE THREAD

**Issue by HIT123-C** [alibaba/MNN#1619]
抱歉没有按照给定的issue格式来提问，想问问MNN团队，针对transformer这块，有没有什么加速的方法呢，看T厂有Evo-ViT的论文用于加速transformer，那mnn这块是否会选择跟进呢。

**Comment by jxt1234** [comment]
这个像是模型结构上的优化，MNN 专注于模型的高效执行，应该不会跟进
