### ISSUE TITLE
Convert tf model fail

### ISSUE THREAD

**Issue by chiwangnvp** [alibaba/MNN#162]
what():  [17:13:24] /mnt/d/code/MNN/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ FAKE_QUANT ]

what():  [17:26:16] /mnt/d/code/MNN/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ CUSTOM ]

==============================================================
Is there any plans to support these ops on MNN ?

**Comment by jxt1234** [comment]
The FAKE_QUANT  and CUSTOM OP can't support because they are for temp usage.
If just want to quantize model. You can try the quantize tool in MNN. https://github.com/alibaba/MNN/blob/master/tools/quantization/README_CN.md

**Comment by chiwangnvp** [comment]
Ok. Thank you for your replying. And we'll think about it. But here is another one:
  what():  [11:33:39] /mnt/d/code/MNN/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ DEQUANTIZE ]

Is this the same case?

**Comment by czy2014hust** [comment]
> Ok. Thank you for your replying. And we'll think about it. But here is another one:
> what(): [11:33:39] /mnt/d/code/MNN/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ DEQUANTIZE ]
> 
> Is this the same case?

Yes.
