### ISSUE TITLE
 GPU doesn't seem to have effect on Inference

### ISSUE THREAD

**Issue by madhu-korada** [alibaba/MNN#1620]
The inference time of GPU and CPU are very similar. 

Platform:- Android 
Testing Devices:- Snapdragon Dragonboard 410c (OpenCL 1.1), POCO F1 - Adreno 630, MI 5A - Adreno 306 (OpenCL 1.1) 

I am a beginner using MNN. I am trying to set up MNN for android (for Snapdragon Dragonboard 410c) so that the GPU of the board can be accessible. I compiled MNN successfully and built the android app given in the demo folder. But when I am running the app on hardware I am getting similar inference times for CPU, OpenCL, OpenGL. I am not even sure If it is accessing GPU. I have the following questions. 

1. To access the GPU, do I need to compile MNN some other way ??
2. My device has Adreno 306, is OpenCL 1.1 supported in MNN??
3. Any tips for using MNN in Snapdragon Dragonboard 410c with Android (as GPU is inaccessible in Linux) ??

Any helpful suggestions would be appreciated.

**Comment by jxt1234** [comment]
You need build mnn opencl by -DMNN_OPENCL=true , and load libMNN_CL.so
