### ISSUE TITLE
error: undefined reference to 'MNN::'  when using libMNN_CL.so  in Android

### ISSUE THREAD

**Issue by awl-arief-darmawan** [alibaba/MNN#1622]
# Platform(Include target platform as well if cross-compiling):  
Android arm64 and 32

# Github Version:
58545d6 (1.2.0 release)

# Compiling Method

## CMakeLists.txt

Change
```
option(MNN_OPENCL "Enable OpenCL" OFF)
```
to
```
option(MNN_OPENCL "Enable OpenCL" ON)
```

## Build libraries
```
cd project/android

mkdir build_32 && cd build_32 && ../build_32.sh
mkdir build_64 && cd build_64 && ../build_64.sh
```

# Build Log:
No error message while building libraries

# Problem : 
If I tried using libMNN.so instead of CL library, the application works fine. However, when I tried to use libMNN_CL.so into my project, I got this error log

```
// All kinds of "error: undefined reference to 'MNN::" type error
...
...
error: undefined reference to 'MNN::CV::ImageProcess::setMatrix(MNN::CV::Matrix const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Any help would be appreciated.
Thank you

**Comment by jxt1234** [comment]
It's your library not link MNN.
