### ISSUE TITLE
MNN master 推理框架Android编译报错

### ISSUE THREAD

**Issue by xiaochunrilihe** [alibaba/MNN#1623]
# 平台(如果交叉编译请再附上交叉编译目标平台): ubuntu18.04
# Platform(Include target platform as well if cross-compiling):   ubuntu18.04

# Github版本: master
# Github Version: master

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
源码编译android MNN
```
-- The ASM compiler identification is Clang
-- Found assembler: /home/liujiahan/data3_liujiahan_ln/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/liujiahan/data3_liujiahan_ln/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/liujiahan/data3_liujiahan_ln/android-ndk-r17c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Android
--      Processor: aarch64
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: ON
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16: OFF
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /home/liujiahan/data3_liujiahan_ln/MNN/project/android/build_64
--      MNN_BUILD_SHARED_LIBS: OFF
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- Configuring done
-- Generating done
-- Build files have been written to: /home/liujiahan/data3_liujiahan_ln/MNN/project/android/build_64
Scanning dependencies of target MNN_Arm82
Scanning dependencies of target MNNARM64
```

# 编译日志:
# Build Log:
[  0%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageBlitter.cpp.o
[  1%] Building CXX object CMakeFiles/MNNCore.dir/source/core/AutoTime.cpp.o
[  2%] Building CXX object express/CMakeFiles/MNN_Express.dir/Executor.cpp.o
[  3%] Building CXX object CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o
[  3%] Building CXX object CMakeFiles/MNN_Arm82.dir/source/backend/arm82/Arm82Backend.cpp.o
[  3%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o
[  3%] Building CXX object CMakeFiles/MNNTransform.dir/source/geometry/ConvertUtils.cpp.o
[  3%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddC4WithStride.S.o
[  4%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAxByClampBroadcastC4.S.o
[  4%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBlitC1ToFloatRGBA.S.o
[  4%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Backend.cpp.o
[  4%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBlitC3ToFloatRGBA.S.o
[  5%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23MulTransUnit.S.o
[  5%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23SourceTransUnit.S.o
[  5%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseInt8.S.o
[  5%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseUint8.S.o
[  6%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthwise.S.o
[  6%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWise.S.o
[  6%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWiseUint8.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNCopyC4WithStride.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNDeconvRunForUnitDepthWise.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNExpC8.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNFloat2Int8.S.o
[  8%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit.S.o
[  8%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit_FAST.S.o
[  8%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV82_Unit.S.o
[  9%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmint8to32_8x4_Unit.S.o
[  9%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNInt8ScaleToFloat.S.o
[  9%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScaleUnit.S.o
[ 10%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLoadU8AndSum.S.o
[ 10%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixAdd.S.o
[ 10%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixMax.S.o
[ 10%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixProd.S.o
[ 11%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixSub.S.o
[ 11%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMaxFloat.S.o
[ 11%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMinFloat.S.o
[ 12%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToBGRAUnit.S.o
[ 12%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToBGRUnit.S.o
[ 12%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToRGBAUnit.S.o
[ 12%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToRGBUnit.S.o
[ 13%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4.S.o
[ 13%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4ForMatMul_A.S.o
[ 13%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC8.S.o
[ 14%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMul.S.o
[ 14%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMulRemain.S.o
[ 14%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseMatMulEpx1.S.o
[ 14%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseMatMulEpx4.S.o
[ 15%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPowC8.S.o
[ 15%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNQuanToDestUint8.S.o
[ 15%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluInt8.S.o
[ 16%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluWithSlopeChannel.S.o
[ 16%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC1BilinearOpt.S.o
[ 16%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC1NearestOpt.S.o
[ 16%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o
[ 17%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC4BilinearOpt.S.o
[ 17%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC4NearestOpt.S.o
[ 17%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAddInt8.S.o
[ 17%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAndAddBias.S.o
[ 18%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSoftmax.S.o
[ 18%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNStrassenMergeCFunction.S.o
[ 18%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNTranspose32Bit4x4.S.o
[ 19%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Common.S.o
[ 19%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Fast.S.o
[ 19%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUnPackC4.S.o
[ 19%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o
[ 20%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Int32.S.o
[ 20%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductLeft.S.o
[ 20%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductRight.S.o
[ 21%] Building CXX object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/CommonOptFunctionNeon.cpp.o
[ 21%] Building CXX object CMakeFiles/MNNMath.dir/source/math/WingoradGenerater.cpp.o
[ 22%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
[ 22%] Built target MNNARM64
[ 23%] Building CXX object CMakeFiles/MNN_Arm82.dir/source/backend/arm82/Arm82Binary.cpp.o
[ 23%] Building CXX object CMakeFiles/MNNTransform.dir/source/geometry/GeometryBatchMatMul.cpp.o
[ 23%] Built target MNNMath
[ 23%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageSampler.cpp.o
[ 23%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BackendRegister.cpp.o
[ 23%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUAsString.cpp.o
[ 24%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUBackend.cpp.o
[ 24%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/Matrix_CV.cpp.o
[ 24%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUBinary.cpp.o
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:204:16: error: use of undeclared identifier 'vaddq_f16'
        return vaddq_f16(x, y);
               ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:210:16: error: use of undeclared identifier 'vsubq_f16'
        return vsubq_f16(x, y);
               ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:216:16: error: use of undeclared identifier 'vmulq_f16'
        return vmulq_f16(x, y);
               ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:222:16: error: use of undeclared identifier 'vminq_f16'
        return vminq_f16(x, y);
               ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:228:16: error: use of undeclared identifier 'vmaxq_f16'
        return vmaxq_f16(x, y);
               ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:234:26: error: use of undeclared identifier 'vsubq_f16'
        return vmulq_f16(vsubq_f16(x, y), vsubq_f16(x, y));
                         ^
/home/liujiahan/data3_liujiahan_ln/MNN/source/backend/arm82/Arm82Binary.cpp:234:43: error: use of undeclared identifier 'vsubq_f16'
        return vmulq_f16(vsubq_f16(x, y), vsubq_f16(x, y));
                                          ^
```
粘贴在这里
Paste log here or pastebin
```

**Comment by czy2014hust** [comment]
升级 android ndk 到 20 及以上
