### ISSUE TITLE
android-aarch64编译报错(abs改成std::abs后ok)

### ISSUE THREAD

**Issue by whlook** [alibaba/MNN#1628]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

android-aarch64 ndk-r14b (api level-21)
# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
依赖cmt:6ad2a632fd269be8d6b9c2b01e4f726624b0fec6
Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake -DCMAKE_TOOLCHAIN_FILE=../Android-aarch64.cmake ..
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
![image](https://user-images.githubusercontent.com/13912755/129481886-ec50a42b-63ed-46d6-b4f4-86b9e03fc0b0.png)

```
粘贴在这里
Paste log here or pastebin
```
![image](https://user-images.githubusercontent.com/13912755/129481829-f369d67d-9115-4718-a333-054a328aa273.png)

**Comment by jxt1234** [comment]
呃，用 fabsf 有问题么?

**Comment by jxt1234** [comment]
已经改成 fabsf
