### ISSUE TITLE
分割模型在MNN1.2版本pc opencl上初始化慢慢慢到17秒，pc cpu正常2-3s

### ISSUE THREAD

**Issue by zhangyunming** [alibaba/MNN#1629]
分割模型，模型大小2m，用mnn1.2.0版本，在pc端opencl初始化要17s，createSession used :16822
比之前1.1版本5秒慢很多
慢的离谱， cpu初始化正常。

有什么原因吗？

**Comment by kangmingit** [comment]
+1

**Comment by jxt1234** [comment]
可以参考 https://www.yuque.com/mnn/cn/create_session 里面把 mode 设成 1 （不做 autotuning），或者加 cache
