### ISSUE TITLE
attribute(target(" sse2")) is unknown

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#163]
刚更新了最新的代码，正常linux编译  报了一个错：
MNN/source/backend/cpu/sse/MNNConvSlideWindowMiddle.cpp:15:23: error: attribute(target(" sse2")) is unknown
 TargetBegin("sse, sse2")
怎么解决？

**Comment by ChisenZhang** [comment]
去掉了TargetBegin逗号后面的空格，不报这个错了，出现了下面这个报错：
MNN/source/backend/cpu/sse/MNNConvSlideWindowMiddle.cpp:84:82: error: ‘_mm256_loadu2_m128’ was not declared in this scope
                     auto srcValue = _mm256_loadu2_m128(src_x + src_w_setup, src_x);

**Comment by jxt1234** [comment]
正在解决，可以先把 CMakeLists.txt 中 USE_SSE 这个宏关掉

**Comment by ChisenZhang** [comment]
好的
