### ISSUE TITLE
window下opencl比cpu慢很多，怎么确定是哪些op导致的

### ISSUE THREAD

**Issue by gray2bgr** [alibaba/MNN#1631]
你好，我有个模型CPU运行大约是7ms，换成opencl运行则变成40ms，因特尔集显630。
请问有什么办法分析是哪些op导致变慢么

**Comment by gray2bgr** [comment]
你好，能否看看这两个模型在opencl为什么变慢，coco那个从8ms变到40ms，另一个从6变成12。cpu是i7，gpu是英特尔集显630
[mnn_model.zip](https://github.com/alibaba/MNN/files/7012404/mnn_model.zip)

**Comment by jxt1234** [comment]
mobilenet / squeezenet 等模型的耗时是怎么样的？集显的 gpu 性能不一定比 cpu 高

**Comment by gray2bgr** [comment]
> mobilenet / squeezenet 等模型的耗时是怎么样的？集显的 gpu 性能不一定比 cpu 高
你好，我跑了一下benchmark，mobilebet0.5大约提升25%，模型大一点能提速明显一点。最差的squeenet 1.1速度相近，没有明显的差别。
用netron查看上述模型和分类网络的，发现上述模型的图比较复杂，多了很多converttensor和slice等op，而分类网络一卷到底。
我目前猜测是某些op效率差导致，不知道具体哪些op效率差。请问是否有相关的文档说明，设计模型时候可以避免这一类
