### ISSUE TITLE
How do I get which device is running my model?

### ISSUE THREAD

**Issue by raisinglc** [alibaba/MNN#1639]
I am deploying a small model with forward type of 2 (MNN_FORWARD_CUDA) on Linux, but I cannot find my app on the list of nvidia-smi, so I don't know whether I enable cuda correctly. Because the model is very small, the average  execution time of each step in a 10000 times loop is 1 ms, so I cannot figure it out by it.

**Comment by raisinglc** [comment]
Further, the gpu usage increased when my app was running, but gpu memory usage didn't change.

**Comment by jxt1234** [comment]
You can use getSessionInfo API to check which backend is created.

**Comment by raisinglc** [comment]
> You can use getSessionInfo API to check which backend is created.
Thank you for your reply :)
