### ISSUE TITLE
networking running slow in normal mode vs benchmark warming up mode

### ISSUE THREAD

**Issue by lucwan** [alibaba/MNN#164]
when i run benchmarking tool of mnn network it runs at 25ms
but when i run the same network by writing a normal code without warming up it takes 80ms
and ncnn takes 85 ms
openmp is on and i am using 4 threads on my xiaomi phone

**Comment by jxt1234** [comment]
What's your normal code?  For the first inference, CPU freq may be low thus running slow.

**Comment by lucwan** [comment]
In your benchmark code, you are running the inference for three times first for warming up then you are running the inference in a loop and calculting min max and average inference time.
So here the average time is 25ms for inference.

Now i change your benchmark code, i compute inference of a network then do some other arm calculations and then again compute inference on next image. So when i measure the time of only inference the time has slowed down to 80ms.

The inference time of network should not be affected by a completely independent code i run just after one inference.

I think your original benchmark inference is running at 25ms because the data remains cached as you keep doing inference on same constant data in your loop thats why it becomes faster and this is leading to wrong interpretation that mnn is 3 times faster. Also i have not quantized the network.

What speedup should i expect when we use mnn vs ncnn? I am using resnet type model with no batch normalization

**Comment by jxt1234** [comment]
There is not any cached data for benchmark. The performance is affected only by cpu freq and big-little core.
What's your measure code, do you create session per time? The session should be created once and use many time.
You can also check your device's cpu freq when running your measure code.

However, there are two way to update your usage to avoid it:
1. Wait for the mnn update for thread pool.
2. Use mnn's opencl or vulkan. MNN's gpu is much faster than ncnn.

**Comment by lucwan** [comment]
We are doing our test on redmi note 5 pro having snapdragon 636 which does not have big little cores,
it has 8 cores of same cpu frequency.

As you suggested please tell us How to Wait for the mnn update for thread pool ? any sample source code i can refer to?

please see the  code from https://github.com/alibaba/MNN/blob/master/benchmark/benchmark.cpp line 156

we create session only one time line 134

for (int round = 0; round < loop; round++) {
        auto timeBegin = getTimeInUs();

        input->copyFromHostTensor(givenTensor.get());
        net->runSession(session);
        outputTensor->copyToHostTensor(expectTensor.get());

        auto timeEnd = getTimeInUs();
        costs.push_back((timeEnd - timeBegin) / 1000.0);
    }
this code give 25 ms average time for costs for loop of 10
but when i change the above code to below

float ab = 0.000001f;
for (int round = 0; round < loop; round++) {
        auto timeBegin = getTimeInUs();

        input->copyFromHostTensor(givenTensor.get());
        net->runSession(session); 
        outputTensor->copyToHostTensor(expectTensor.get());

        auto timeEnd = getTimeInUs();
        costs.push_back((timeEnd - timeBegin) / 1000.0);    
     ///this gives 80ms average costs now after doing below extra calculations

     //extra calculations 10 million floating multiplications
      ab = 0.000001f;
      for(int iter=0;iter<10000000;iter++)
      {
        ab = ab* 0.000001f;
      }
    }
   printf("value of ab is %f\n",ab);
   this code give 80 ms average time for inference costs for a loop 10

so just inserting extra calculations is leading to slowdown of inference time of network

**Comment by jxt1234** [comment]
The code has updated. You can open the option MNN_USE_THREAD_POOL , it will use non-mutex threadpool instead of openmp.
