### ISSUE TITLE
转换tflite2模型提示SPLIT_V OP不支持

### ISSUE THREAD

**Issue by MegatronKing** [alibaba/MNN#1643]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
MacOS:  

# Github版本:
1.2.1

# 报错:
```
Start to Convert Other Model Format To MNN Model...
[16:07:05] /Users/megatronking/Workspace/MNN/tools/converter/source/tflite/liteConverter.cpp:239: Check failed: creator ==> NOT_SUPPORTED_OP: [ SPLIT_V ]
[1]    79070 segmentation fault
```

**Comment by anklebreaker** [comment]
I had the same issue and was able to convert from TFLite -> ONNX -> MNN. However, the converted model has several permute operations to keep the split axis the same. I hope in a future release that the conversion can convert to a TFLite split_v function along the proper axis in MNN's NCHW format.
