### ISSUE TITLE
runSession过程中的异常内存增长

### ISSUE THREAD

**Issue by pplljj** [alibaba/MNN#1644]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  arm64-v8a

# Github版本:
# Github Version: 575a2c97dd6d0d5dd889b342424ae247471b9899

# 编译方式:
# Compiling Method

cmake $MNN_SDK_ROOT \
-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Debug \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DMNN_BUILD_SHARED_LIBS=ON \
-DMNN_ARM82=ON \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=.

# 编译日志:
# Build Log: 编译没有问题

# 问题
runSession过程中的异常内存增长
使用附件模型，在运行到 名称为 ‘495’ 这个 1x1 pointwise 卷积之后，内存突然上升 300M（从原来的600M 上升至 0.9G），之后的几个算子也陆续造成 内存进一步上升，最终 达到内存 1.5 G，之后再次 runSession 内存不再增长，一直停留在 1.5 G。但是目前这个内存增长有些大，对运行在手机平台有限制，所以想问一下： 这个内存异常增长是否是内部bug造成？ '495'及之后各节点增长的内存是否是内存复用策略失效导致的？ 能否增强一下内存复用策略让‘495’及之后这些节点不再申请新的内存？
[net_fp32.mnn.zip](https://github.com/alibaba/MNN/files/7067933/net_fp32.mnn.zip)

**Comment by lengerfulluse** [comment]
@pplljj 我也遇到类似的内存增长问题，请问你最终怎么解决的？

**Comment by pplljj** [comment]
> @pplljj 我也遇到类似的内存增长问题，请问你最终怎么解决的？

这个内存上升是那些算子确实需要输出很大的tensor。最后也是减模型来处理这个内存问题的。

**Comment by lengerfulluse** [comment]
> > @pplljj 我也遇到类似的内存增长问题，请问你最终怎么解决的？
> 
> 这个内存上升是那些算子确实需要输出很大的tensor。最后也是减模型来处理这个内存问题的。
感谢感谢。我最近发现MNN论文提到的矩阵相乘优化算法winograd几乎吃掉了1G的内存。
