### ISSUE TITLE
fp16版本和fp32版本 所用内存问题

### ISSUE THREAD

**Issue by GitHub-ZRQ** [alibaba/MNN#1645]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  arm64-v8a

# Github版本:
# Github Version: 575a2c97dd6d0d5dd889b342424ae247471b9899

# 编译方式:
# Compiling Method

cmake $MNN_SDK_ROOT \
-DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Debug \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DMNN_BUILD_SHARED_LIBS=ON \
-DMNN_ARM82=ON \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=.

# 编译日志:
# Build Log: 编译没有问题

# 问题
fp16版本和fp32版本 所用内存问题
同一个模型的 fp16版本 和 fp32 版本 所用内存 很接近，fp32 是 1.5G, fp16 也是 1.2G，没有达到想象之中的接近 1/2 的比例。想请问一下，这种情况算是正常吗？ 是什么可能会造成这种情况呢？
运行的模型见附件。
[net.zip](https://github.com/alibaba/MNN/files/7067946/net.zip)

**Comment by jxt1234** [comment]
fp16 模型与 fp32 模型仅有模型大小的区别，你 precision 设成low 了么? 在什么机器上运行的
