### ISSUE TITLE
输入尺寸可变模型在调用resizeSession时报错

### ISSUE THREAD

**Issue by HITer-lwp** [alibaba/MNN#1647]
你好，我在使用mnn进行模型推理时遇到如下报错信息：
        Reshape error: 33280 -> 102400
        Compute Shape Error for 488
        input: w:208 h:156 bpp:3
        **Tensor shape**: 1, 3, 156, 208,
        Can't run session because not resized
我的模型原始输入尺寸为3x320x320，输入尺寸可变，当我用如下代码调整输入尺寸时出现上述报错：
--------------------------------------------------------------------------------------------------------------------------------------
    int width,height,channel;
    width = src.cols;
    height = src.rows;
    float maxl = src.cols > src.rows?src.cols:src.rows;
    float ratio = 208/maxl;
    int dst_width = src.cols*ratio;
    int dst_height = src.rows*ratio;
    auto input = net->getSessionInput(session,nullptr);
    net->resizeTensor(input,{1,3,dst_height,dst_width});
    net->resizeSession(session);
    std::shared_ptr<MNN::Tensor>inputUser(new MNN::Tensor(input,MNN::Tensor::CAFFE));
    int bpp = inputUser->channel();
    int size_w = inputUser->width();
    int size_h = inputUser->height();
    MNN_PRINT("input: w:%d h:%d bpp:%d\n",size_w,size_h,bpp);
    MNN::CV::ImageProcess::Config config;
    config.filterType = MNN::CV::BILINEAR;
    config.sourceFormat = MNN::CV::BGR;
    config.destFormat = MNN::CV::BGR;
    std::memcpy(config.mean,_mean_val,sizeof(_mean_val));
    auto pretreat = std::shared_ptr<MNN::CV::ImageProcess>(MNN::CV::ImageProcess::create(config));
    MNN::CV::Matrix trans;
    trans.setScale((float)(width-1)/(dst_width-1),(float)(height-1)/(dst_height-1));
    pretreat->setMatrix(trans);
    pretreat->convert(
        (uint8_t*)src.data,
        width,
        height,
        0,
        inputUser->host<uint8_t>(),
        dst_width,
        dst_height,
        bpp,
        0,
        inputUser->getType()
    );
    input->copyFromHostTensor(inputUser.get());
    input->printShape();
    auto out = net->getSessionOutput(session,"output0");
    auto out1 = net->getSessionOutput(session,"942");
    auto out2 = net->getSessionOutput(session,"941");
    net->runSession(session);
    std::shared_ptr<MNN::Tensor>outUser(new MNN::Tensor(out,out->getDimensionType()));
    out->copyToHostTensor(outUser.get());
    std::shared_ptr<MNN::Tensor>out1User(new MNN::Tensor(out1,out1->getDimensionType()));
    out1->copyToHostTensor(out1User.get());
    std::shared_ptr<MNN::Tensor>out2User(new MNN::Tensor(out2,out2->getDimensionType()));
    out2->copyToHostTensor(out2User.get());
----------------------------------------------------------------------------------------------------------------------------------------
请问我该如何实现输入尺寸可变模型的推理？

**Comment by jxt1234** [comment]
原始模型可以跑么？ onnx 的话先用 fastTestOnnx.py 测试一下?

**Comment by HITer-lwp** [comment]
> 原始模型可以跑么？ onnx 的话先用 fastTestOnnx.py 测试一下?

原始模型可以正常跑，以下是fastTestOnnx.py的测试结果：
inputs:
input0
outputs:
onnx/output0.txt (1, 4200, 4)
onnx/942.txt (1, 4200, 2)
onnx/941.txt (1, 4200, 10)

Test onnx
Start to Convert Other Model Format To MNN Model...
[10:24:31] /home/carl/lwp/mnn/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 4
Start to Optimize the MNN Net...
inputTensors : [ input0, ]
outputTensors: [ 941, 942, output0, ]
Converted Success!
input0
output: output0
output: 942
output: 941
TEST_SUCCESS

**Comment by holyYodu** [comment]
> 请问我该如何实现输入尺寸可变模型的推理？

你好， 我也遇到相同的问题了， 请问你解决了这个问题吗？

**Comment by ciwei123** [comment]
@HITer-lwp @jxt1234 I meet the same question. I also get "TEST_SUCCESS"by " fastTestOnnx.py",but it still get `Can't run session because not resized`.Could you share me the solution?Thank you very much!!

**Comment by wangzhaode** [comment]
执行runSession前需要执行resizeTensor和resizeSession
