### ISSUE TITLE
opencl推理量化模型时设置precision为high、low均崩溃

### ISSUE THREAD

**Issue by jules-ai** [alibaba/MNN#1648]
如题，直接clone下来编译，没做任何更改，然后目标平台上运行MNNV2Basic.out，任意模型都可复现。
现象1：用fp32模型推理，精度设为normal、low、high都不崩溃；
现象2：用fp16模型推理，精度设为normal正常运行，设为low、high都崩溃；
现象3：用int8量化模型推理，精度设为normal正常运行，设为low、high都崩溃；
现象4：debug编译，然后用gdb查看堆栈，崩溃位于createSession时内部调用的memcpy函数，但更详细的信息看不到了。

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
在Ubuntu16.04上，使用ndk-r15c编译，目标运行平台为rk3568（目标推理设备mali g52）

# Github版本:
# Github Version:
尝试过多个版本（包括1.2.0，包括当前最新的commit，均复现此问题），因此直接用最新commit=5dfe97e4c883fcae8ed25e6759dae7cb8ec2a9a8即可

# 编译方式:
# Compiling Method

NDK_PATH_TO_USE=/home/jules/android-ndk-r15c

cmake ../ \
-DCMAKE_TOOLCHAIN_FILE=$NDK_PATH_TO_USE/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX=$(pwd)/install \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DANDROID_NATIVE_API_LEVEL=android-21 \
-DMNN_BUILD_FOR_ANDROID_COMMAND=ON \
-DMNN_USE_LOGCAT=OFF \
-DMNN_BUILD_BENCHMARK=OFF \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_HARD=OFF \
-DMNN_BUILD_SHARED_LIBS=OFF \
-DMNN_FORBID_MULTI_THREAD=OFF \
-DMNN_OPENMP=OFF \
-DMNN_USE_THREAD_POOL=ON \
-DMNN_BUILD_TRAIN=OFF \
-DMNN_BUILD_DEMO=OFF \
-DMNN_BUILD_QUANTOOLS=OFF \
-DMNN_EVALUATION=OFF \
-DMNN_BUILD_CONVERTER=OFF \
-DMNN_SUPPORT_TFLITE_QUAN=ON \
-DMNN_DEBUG_MEMORY=OFF \
-DMNN_DEBUG_TENSOR_SIZE=OFF \
-DMNN_BUILD_TOOLS=ON \
-DMNN_GPU_TRACE=OFF \
-DMNN_PORTABLE_BUILD=OFF \
-DMNN_SEP_BUILD=OFF \
-DMNN_AAPL_FMWK=OFF \
-DMNN_METAL=OFF \
-DMNN_OPENCL=ON \
-DMNN_OPENGL=OFF \
-DMNN_VULKAN=OFF \
-DMNN_ARM82=OFF \
-DMNN_USE_CPP11=ON

# 编译日志:
# Build Log:
(全部日志太长了，贴了简版，但完全正常编译，也可正常运行的)
[  2%] Built target MNN_Express
[ 14%] Built target MNNARM64
[ 32%] Built target MNNCPU
[ 32%] Built target MNNUtils
[ 33%] Built target MNNCV
[ 34%] Built target MNNMath
[ 37%] Built target MNNCore
[ 60%] Built target MNNTransform
[ 70%] Built target MNN_CL
[ 70%] Built target MNN
[ 94%] Built target run_test.out
[ 95%] Built target backendTest.out
[ 96%] Built target testTrain.out
[ 97%] Built target testModel.out
[ 97%] Built target testModelWithDescrisbe.out
[ 98%] Built target mobilenetTest.out
[ 98%] Built target checkInvalidValue.out
[ 99%] Built target MNNV2Basic.out
[ 99%] Built target getPerformance.out
[100%] Built target timeProfile.out

**Comment by bitxsw93** [comment]
我们这边没有这个目标设备，使用手机上无法复现问题。可否具体查看下crash的createSession底层函数信息？也可去钉钉群留言私聊沟通看看

**Comment by jules-ai** [comment]
> 我们这边没有这个目标设备，使用手机上无法复现问题。可否具体查看下crash的createSession底层函数信息？也可去钉钉群留言私聊沟通看看

感谢提示，似乎确实与设备有关，我换了台RK3399就没有复现。
使用gdb得到的堆栈如下（因在安卓也没有更详细的信息了）：
`0x0000007ff6b4e0f8 in __memcpy () from /apex/com.android.runtime/lib64/bionic/libc.so`
`(gdb) bt`
`#0  0x0000007ff6b4e0f8 in __memcpy () from /apex/com.android.runtime/lib64/bionic/libc.so`
`#1  0x0000007d64227c98 in ?? () from /vendor/lib64/egl/libGLES_mali.so`
`#2  0x0000007d6423187c in ?? () from /vendor/lib64/egl/libGLES_mali.so`
`#3  0x0000007d6423428c in ?? () from /vendor/lib64/egl/libGLES_mali.so`
`#4  0x0000007d64238db8 in ?? () from /vendor/lib64/egl/libGLES_mali.so`
`#5  0x0000007d6439601c in ?? () from /vendor/lib64/egl/libGLES_mali.so`
`#6  0x0000007ff6bb3884 in __pthread_start(void*) () from /apex/com.android.runtime/lib64/bionic/libc.so`
`#7  0x0000007ff6b540d4 in __start_thread () from /apex/com.android.runtime/lib64/bionic/libc.so`

另外我会尝试下加钉钉群。谢谢回复。

**Comment by bitxsw93** [comment]
如钉钉沟通，已经fix了。

**Comment by jxt1234** [comment]
最新提交已经修复
