### ISSUE TITLE
MNN::CV::ImageProcess 使用结果不对

### ISSUE THREAD

**Issue by eudora-jia** [alibaba/MNN#1655]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
microsoft windows 10 专业版
版本 10.0.18363

# Github版本:
MNN .1.2.0

# 编译方式:
# x86 方式  参考的 https://www.yuque.com/mnn/cn/build_windows
然后我编译成功的
编译的尝试：刚开始我忽略了vs2017 这个要求，因为我一直用的vs2015 毋庸置疑，出现了编译的问题，我修改了mnn 的代码
之后编译成功了。然后测试了模型，结果错误。所以开始怀疑编译器有影响，所以换成了 2017 按照所示方法， 使用全新的mnn 代码进行编译，没有出现问题。

# 编译日志:
编译日志我不提供了，确定编译没有问题

日志不贴了：我说明一下问题，并且贴一下我的代码。我在android 上面使用 process->convert 感觉很有效率，所以windows 平台我也想用这种方式。最后我的工程编译没有问题，但，输出的tensor 结果不对。另外我用的是 cpu 的推理。

怀疑点1：由于我提前获取了 inputtesor 的地址，但是没有通过copyFromHostTensor 方式喂值，所以认为要通过copyFromHostTensor 将  process->convert 之后的cpu 的内容拷贝倒mnn 的排布内存里面去。但没有效果。

我初始化函数里面做了这样的事情：
```
    	MNN::Tensor* tensor =  interpreter->getSessionInput(session,NULL);
    	assert(NULL != tensor);
    	input_tensors.push_back(tensor);
```
我推理的函数里面做了这样的事情：
```
        /// TODO bug for those process
       	MNN::CV::Matrix trans;

       	///！先归一化
        trans.postScale(1.0f /input->width, 1.0f /input->height);
        ///！缩放
		trans.postScale(inputTensor->width(), inputTensor->height());
		bool invert_flag = trans.invert(&trans);
		if(!invert_flag)
		{
			LOGE("the matrix inverted failed\n");
			return -1;
		}
		process->setMatrix(trans);
        auto nchwTensor = new MNN::Tensor(inputTensor, MNN::Tensor::CAFFE);
        MNN::ErrorCode  err =  process->convert(input->data, input->width, input->height, 0, nchwTensor);
        if (err)
        {
            LOGE("convert err:%d\n", err);
            return -1;
        
        }
        inputTensor->copyFromHostTensor(nchwTensor);
```

怀疑点2：
由怀疑点1 我开始考虑平台的问题，所以我在linux上面测试了我的程序居然没有问题 同样的代码。我的linux 平台是x64 的我编译的程序也是 x64的

怀疑点3：
我还是开始怀疑我生成的mnn.dll 不能用，因为 我确认了我的前处理代码没有问题，我的后处理也是copyToHost 方式，那肯定是中间过程有问题，所以。。。。然而我并不想再次编译MNN，因为编译过程太过于简单，而没有检查的必要。我通过everything 工具搜索了我电脑的 MNN.dll 发现 dingding 这个办公工具也用的是MNN.dll 所以我使用了他，然而。。。 结果还是不对。

怀疑点4：
x86 和 x64 的 数据位数问题吗？ 我编译了x64 的 MNN ，最后我的工程还是没有得到我想要的效果，最后我自己写了简单的前处理了过程:
```
        cv::Mat src(input->height,input->width,CV_8UC3, input->data);
        cv::Mat resizeMat;
        cv::resize(src, resizeMat,cv::Size(inputTensor->width(),inputTensor->height()));
        Image aMat;
        aMat.data = resizeMat.data;
        aMat.height = resizeMat.rows;
        aMat.width = resizeMat.cols;
        auto nchwTensor = new MNN::Tensor(inputTensor, MNN::Tensor::CAFFE);
		convert_image_to_tensor(&aMat, nchwTensor, mean_value_, std_val_);
        inputTensor->copyFromHostTensor(nchwTensor);
//	    std::shared_ptr<AMat<float>>  permute_tensor = 
```

**Comment by jxt1234** [comment]
可以打印一下 tensor 内容看下差别在哪么? 按理不应该有平台差异
