### ISSUE TITLE
官方例子报错，如何解决？MNN/demo/exec/segment.cpp:(.text+0x1fe63): undefined reference to `MNN::Express::Expr::create(MNN::Tensor*, bool)'

### ISSUE THREAD

**Issue by fcqfcq** [alibaba/MNN#1656]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu  5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# Github版本:
# Github Version:
MNN 1.1.7  
```Comment = 3ab8725569fae5671185afec3c3a90c016a62156```
MNN 1.2.2   
```Comment =5dfe97e4c883fcae8ed25e6759dae7cb8ec2a9a8```
# 编译方式:
# Compiling Method
```
cd path/to/MNN
mkdir build && cd build
cmake -DMNN_BUILD_DEMO=ON .. or  cmake ..
make -j8
```
cmake_minimum_required(VERSION 3.0) # 设置cmake版本
project(run) # 设置工程名字
message(STATUS "    version: ${OpenCV_VERSION}")
message(STATUS "    libraries: ${OpenCV_LIBS}")
message(STATUS "    include path: ${OpenCV_INCLUDE_DIRS}")
message(STATUS "   LD_LIBRARY_PATH  path: ${LD_LIBRARY_PATH}")
set(MNN_DIR  /path/to/MNN-1.2.2/build )
set(MNN_ROOT  /path/to//MNN-1.2.2/include )
//set(MNN_DIR  / path/to/a/software/MNN-1.1.7/build )
//set(MNN_ROOT  /path/to/software/MNN-1.1.7/include )
include_directories(${MNN_ROOT})
set(OpenCV_DIR /path/to/opencv-4.5.3/build ) #你之前源码包里的build文件夹，防止版本冲突
find_package(OpenCV 4 REQUIRED) #寻找这个包 opencv 包名 4 最低版本号 REQUIRED 如果没找到就报错
add_executable(${PROJECT_NAME}  segment.cpp ) #生成可执行文件
target_link_libraries(${PROJECT_NAME}   ${OpenCV_LIBS} -lrt -lpthread  -lstdc++ -ldl )
target_link_libraries( ${PROJECT_NAME} 
${MNN_DIR}/libMNN.so
)
# 编译日志:
# Build Log:
```
/usr/bin/ld: CMakeFiles/run.dir/segment.cpp.o: in function `main':
segment.cpp:(.text+0x1fe63): undefined reference to `MNN::Express::Expr::create(MNN::Tensor*, bool)'
/usr/bin/ld: segment.cpp:(.text+0x1fe81): undefined reference to MNN::Express::Variable::create(std::shared_ptr<MNN::Express::Expr>, int)'
/usr/bin/ld: segment.cpp:(.text+0x1fea7): undefined reference to `MNN::Express::Variable::getInfo()'
/usr/bin/ld: segment.cpp:(.text+0x1ff01): undefined reference to `MNN::Express::_Convert(MNN::Express::VARP, MNN::Express::Dimensionformat)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/run.dir/build.make:113：run] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/run.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
```
#  error  informations
 // Turn dataFormat to NHWC for easy to run TopKV2
 output = _Convert(output, NHWC);
https://github.com/alibaba/MNN/blob/d21fd2a910b8c7f5542f551b9863ccf841e66691/demo/exec/segment.cpp#L109
# code 
https://github.com/alibaba/MNN/blob/master/demo/exec/segment.cpp

**Comment by jxt1234** [comment]
没有链接 libMNN_Express.so ，在编译 MNN 时关闭分离编译也可以 -DMNN_SEP_BUILD=false（这样 Express 部分与. MNN 合一）

**Comment by fcqfcq** [comment]
ok,   解决了，谢谢！
