### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Divenirelrn** [alibaba/MNN#1657]
# Platform(Include target platform as well if cross-compiling):  
ubuntu18.04

# Github Version:
1.2.2

# 编译方式:
cmake .. -DMNN_BUILD_CONVERTER=true -DCMAKE_BUILD_TYPE=Debug -DProtobuf_PROTOC_EXECUTABLE=/usr/local/protobuf/bin/protoc -DProtobuf_LIBRARIES=/usr/local/protobuf/

I get resnet50.onnx model through the code below in which the python version is 3.7.9 and torch version is 1.6:
![image](https://user-images.githubusercontent.com/53744518/132219790-b2e4e90d-c23c-4c89-ad3d-e80fff0eb902.png)
then, i conver the onnx model to mnn model, the converter progress's all nomal:
![image](https://user-images.githubusercontent.com/53744518/132220464-34a0adba-e257-4918-bdda-e6a7fa6fc945.png)
However, when i run the python demo below in which the MNN version is 1.1.4:
![image](https://user-images.githubusercontent.com/53744518/132220576-e4959a5d-a3ed-4150-b76b-966fd16a4a04.png)
the error  occured as below:
![image](https://user-images.githubusercontent.com/53744518/132220722-223d1096-57d0-4bf6-899a-85fed8c5e80f.png)
I cannot locate the error, could you please figure it out?

**Comment by zhuzhu18** [comment]
I found this error occurs on this line: 
output_tensor.copyToHostTensor(tmp_output)
but i cannot solve it either.
