### ISSUE TITLE
高通855，888上跑benchmark时cpu被限频

### ISSUE THREAD

**Issue by xbwee1024** [alibaba/MNN#1658]
亮屏静止放置，跑benchmark.out, 与手动来回滑动屏幕，跑benchmark.out 结果差异很大。
看了下systrace，有UI操作下CPU基本上都满频跑，没有滑动情况CPU 频率非常低，怀疑是没有UI操作的情况进入了低功耗模式导致。
理论上benchmark设置了Power_High模式，应该让系统认为是一个high loading task，频率拉到最高才对~

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MacOS 11.5.2
Anroid arm64-v8a

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
cd project/android
mkdir build_64;cd build_64
../build_64.sh
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by czy2014hust** [comment]
这个没办法，系统的权限是最高的
