### ISSUE TITLE
Device Support Snapdragon 410c Linux

### ISSUE THREAD

**Issue by madhu-korada** [alibaba/MNN#1659]
I am a beginner using MNN. Any suggestions would be appreciated.

## Hardware Info :- Snapdragon Dragonboard 410c 
- Quad Core ARMv8 A53 CPU (@1.0GHz)
- Adreno 306 GPU, powered by freedreno Mesa/Gallium GPU driver, version 20.3.5
   - OpenGL 3.1, OpenGLES 3.0, GLX, EGL
   - OpenCL 1.1 (for Android only)

## Query
I am trying to utilize the GPU of Snapdragon Dragonboard 410c (Adreno 306), above are the specs and OpenGL, OpenCL support versions. I have few questions, 
1. Using Linux I can access GPU using OpenGL only, OpenCL on Linux is not possible. My device supports OpenGL 3.1, OpenGLES 3.0 as mentioned above. Does MNN have support for the mentioned version??
    - I saw thread #413, it's mentioned that MNN has support for GLESv3.1, does this mean my device doesn't support it? and what about OpenGL 3.1 ???
2. Considering my GPU (Adreno 306), which is very old, how much performance gain do you think I might be able to achieve ??
3. As I am looking into OpenGL based deep learning framework, I didn't come across any apart from MNN, if anyone has more info on OpenGL or OpenGLES based deep learning framework please let me know.

**Comment by Itamare4** [comment]
Hi @madhu-korada,
Any news? Were you able to utilize the Adreno 306 GPU?

**Comment by madhu-korada** [comment]
No, I wasn't able to use. With few libraries such as MACE, MNN GPU was accessible. But 306 seems to be very weak, it's not impactful for inferencing neural networks (CNNs). The fps with GPU is a little less than with CPU. I was guessing CPU-GPU mem copy was taking a lot of time or the 306 gpu is very weak.

**Comment by Itamare4** [comment]
Great. Thanks @madhu-korada!
Sure better than nothing. The GPU just sits there and does nothing, I want to squeeze some juice out of it.

**Comment by madhu-korada** [comment]
That was my intention as well. Wasted 3-4 weeks exploring the workarounds. 
1. In Linux it's not possible to access GPU, have to transition to Android completely to achieve that. 
2. Adreno 306 doesn't have enough juice to squeeze. Trying to do that made me realize that I should better spend the time on optimizing my existing code.

This is what I found, I don't know if it's accurate.

**Comment by jxt1234** [comment]
OpenGLES 3.0 is not supported by MNN.
We need compute shader in OpenGLES 3.1 or OpenGL 4
