### ISSUE TITLE
andorid工程中的一些问题

### ISSUE THREAD

**Issue by smallt-TAO** [alibaba/MNN#166]
请教大佬几个问题：
1）通过tf转的mnn模型在c++的代码中可以推理，但将其放入andorid 工程中就出现apk结束问题（不报错误）。
通过分层的方式，发现conv2d层是引发apk崩的原因，全连接以及flatten层都是没有问题的。后面我使用caffe转的相同的网络结构的mnn在andorid工程中是可以推理的。
请问这是什么原因导致的呢？

2）在caffe转的mnn的andorid工程推理中，发现每次运行的时间波动较大，3-50ms。另外运行官网自带的模型（mobilenet）的推理时间同样波动30ms左右。
请问模型的推理时间为何波动很大。
以上的测试数据来自于小米4。主要代码来自于demo文件夹中的andorid。

**Comment by li-qing** [comment]
what is your input tensor dimension ?

**Comment by 17759205390** [comment]
> 请教大佬几个问题：
> 1）通过tf转的mnn模型在c++的代码中可以推理，但将其放入andorid 工程中就出现apk结束问题（不报错误）。
> 通过分层的方式，发现conv2d层是引发apk崩的原因，全连接以及flatten层都是没有问题的。后面我使用caffe转的相同的网络结构的mnn在andorid工程中是可以推理的。
> 请问这是什么原因导致的呢？
> 
> 2）在caffe转的mnn的andorid工程推理中，发现每次运行的时间波动较大，3-50ms。另外运行官网自带的模型（mobilenet）的推理时间同样波动30ms左右。
> 请问模型的推理时间为何波动很大。
> 以上的测试数据来自于小米4。主要代码来自于demo文件夹中的andorid。

@smallt-TAO 可以留个微信吗？想请教下TF如何生成pb文件，我是mtcnn模型，生成meta那三个模型文件

**Comment by smallt-TAO** [comment]
输入维度 【1， 32， 48， 20】.
后面在MNN的官方群里将问题反映，第一个可能是v7的openmp的问题。第二个问题可能是安卓本身的问题。再次谢谢大佬的关注。

**Comment by smallt-TAO** [comment]
输入维度 【1， 32， 48， 20】.
后面在MNN的官方群里将问题反映，第一个可能是v7的openmp的问题。第二个问题可能是安卓本身的问题。再次谢谢大佬的关注。

**Comment by smallt-TAO** [comment]
输入维度 【1， 32， 48， 20】.
后面在MNN的官方群里将问题反映，第一个可能是v7的openmp的问题。第二个问题可能是安卓本身的问题。再次谢谢大佬的关注。 @li-qing

**Comment by smallt-TAO** [comment]
@17759205390 你的问题解决了吗？ 如果需要的话，可以添加微信：llt2268226155

**Comment by 17759205390** [comment]
@smallt-TAO 请问官方群号多少？微信群吗？

**Comment by 17759205390** [comment]
@li-qing 
在海思3556S上，测试benchmark，运行完一个模型就挂了，而且超级慢

# ./benchmark.out models/ 1 0
MNN benchmark
Forward type: **CPU** thread=4** precision=2
--------> Benchmarking... loop = 1
[ - ] MobileNetV2_224.mnn         max = 13330.345ms  min = 13330.345ms  avg = 13330.345ms
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by 17759205390** [comment]
一个线程也是一样

# ./benchmark.out models/ 2 0
MNN benchmark
Forward type: **CPU** thread=1** precision=2
--------> Benchmarking... loop = 2
[ - ] MobileNetV2_224.mnn         max = 13272.568ms  min = 13270.068ms  avg = 13271.318ms
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
