### ISSUE TITLE
安卓平台，opencl cache方式运行，横竖屏旋转时算法运行卡顿

### ISSUE THREAD

**Issue by janicevidal** [alibaba/MNN#1660]
横竖屏切换时，图像分辨率w和h发生了调换，opencl cache的生成是发生在模型初始化阶段，在算法执行时，需要加resizeSession的操作应对横竖屏切换分辨率改变，但是中间会出现4~5s的卡顿，应该是cache文件不对齐引起的，这种该怎么解决呢

**Comment by jxt1234** [comment]
已知问题，还在解决中

**Comment by xin486946** [comment]
请问这个问题已经解决了吗？

**Comment by xin486946** [comment]
还没有解决吗？

**Comment by janicevidal** [comment]
> 还没有解决吗？

没有再做验证了，先关掉issues了。
