### ISSUE TITLE
fastTestTf.py定位到模型的错误节点位置该如何进行修复

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [alibaba/MNN#1663]
使用fastTestTf.py校验ONNX模型正确性时遇到问题。定位到了错误节点的位置，但是不知道该如何去修改。模型文件是这个
[unquant_1.zip](https://github.com/alibaba/MNN/files/7132706/unquant_1.zip)
fastTestTf.py输出如下：

$ python fastTestOnnx.py /home/lsc/unquant_1.onnx DEBUG
mkdir: cannot create directory ‘onnx’: File exists

Debug Mode:  True
onnx/test.onnx
tensor(float)
tensor(float)
['model_1/lstm_5/lstm_cell_5/mul_2:0']
inputs:
input_2
onnx/
input_3
onnx/
outputs:
onnx/model_1/lstm_5/lstm_cell_5/mul_2:0.txt (1, 128)
onnx/model_1/lstm_5/lstm_cell_5/
Test onnx
Start to Convert Other Model Format To MNN Model...
[09:16:03] /home/lsc/docker/crnn/M/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 4
Start to Optimize the MNN Net...
42 op name is empty or dup, set to Const42
inputTensors : [ input_2, input_3, ]
outputTensors: [ activation_2, tf.stack_2, ]
Converted Success!
input_2
input_3
output: model_1/lstm_5/lstm_cell_5/mul_2:0
TESTERROR model_1/lstm_5/lstm_cell_5/mul_2:0 value error : absMaxV:0.959979 - DiffMax 0.960216
Save mnn result to  .error director

Test Node : model_1/lstm_5/lstm_cell_5/mul_2 False
onnx/test.onnx
tensor(float)
tensor(float)
['model_1/lstm_5/lstm_cell_5/mul:0']
inputs:
input_2
onnx/
input_3
onnx/
outputs:
onnx/model_1/lstm_5/lstm_cell_5/mul:0.txt (1, 128)
onnx/model_1/lstm_5/lstm_cell_5/
Test onnx
Start to Convert Other Model Format To MNN Model...
[09:16:03] /home/lsc/docker/crnn/M/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 4
Start to Optimize the MNN Net...
42 op name is empty or dup, set to Const42
inputTensors : [ input_2, input_3, ]
outputTensors: [ activation_2, tf.stack_2, ]
Converted Success!
input_2
input_3
output: model_1/lstm_5/lstm_cell_5/mul:0
TESTERROR model_1/lstm_5/lstm_cell_5/mul:0 value error : absMaxV:1.146170 - DiffMax 1.037544
Save mnn result to  .error director

Test Node : model_1/lstm_5/lstm_cell_5/mul False
onnx/test.onnx
tensor(float)
tensor(float)
['model_1/tf.__operators__.getitem_3/strided_slice__10:0']
inputs:
input_2
onnx/
input_3
onnx/
outputs:
onnx/model_1/tf.__operators__.getitem_3/strided_slice__10:0.txt (1, 128)
onnx/model_1/tf.__operators__.getitem_3/
Test onnx
Start to Convert Other Model Format To MNN Model...
[09:16:03] /home/lsc/docker/crnn/M/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 4
Start to Optimize the MNN Net...
42 op name is empty or dup, set to Const42
[unquant_1.zip](https://github.com/alibaba/MNN/files/7132703/unquant_1.zip)

99 op name is empty or dup, set to Const99
inputTensors : [ input_2, input_3, ]
outputTensors: [ tf.stack_2, activation_2, ]
Converted Success!
input_2
input_3
output: model_1/tf.__operators__.getitem_3/strided_slice__10:0
TESTERROR model_1/tf.__operators__.getitem_3/strided_slice__10:0 value error : absMaxV:1.192772 - DiffMax 1.071571
Save mnn result to  .error director

Test Node : model_1/tf.__operators__.getitem_3/strided_slice__10 False
Error is between  model_1/tf.__operators__.getitem_3/strided_slice  and  model_1/tf.__operators__.getitem_3/strided_slice__10

**Comment by KAWAKO-in-GAYHUB** [comment]
使用转换后的MNN模型去进行推理，能够推理不会报错，但是出来的结果不对。
MNN推理结果与ONNX推理结果如图。
![image](https://user-images.githubusercontent.com/54660064/132609913-515c85b3-f467-4be3-b7fa-f43c5847af4e.png)

**Comment by jxt1234** [comment]
出错直接提 issue 或在群里发即可，我等会看一下

**Comment by jxt1234** [comment]
该问题已经被近期提交的 bugfix 修复（slice 转换问题），请同步到 master 最新再测试一下

**Comment by zhanglaplace** [comment]
这边转换后用fastTestOnnx.py也有类似的错误，onnx转ncnn没有问题。
```shell
python fastTestOnnx.py ../../build/uGATIT_deploy_iter_259000_sim.onnx  2>&1 |tee -a log.txt
```
- 结果
![image](https://user-images.githubusercontent.com/12178974/149264465-1dc87f2d-ac9b-4591-97cd-d42ea4810311.png)

```shell
Error for output output
Save mnn result to  .error director
```

可能原因是u-gat-it中的adaLin等模块的广播机制，辛苦看下。
onnx模型地址：
链接：https://pan.baidu.com/s/1f00sLzNnLXjrDyT2IwGegg 提取码：77j9
