### ISSUE TITLE
模型推理时报Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [alibaba/MNN#1664]
使用的模型是
[model.zip](https://github.com/alibaba/MNN/files/7134642/model.zip)
使用的是master版的MNN
模型推理的顺序是：第一个模型 -> ifft -> 第二个模型
第一个模型的推理和输出都没有问题，第二个模型的输入也没有问题，但第二个模型推理的时候报了“Segmentation fault (core dumped)”

模型初始化代码是
int32_t MYMNN::init()
{
    cout << "step into  MYMNN::init" << endl;
    this->interpreter_1.reset(Interpreter::createFromFile(this->modelPath1));
    if (!this->interpreter_1) {
        cout << "Failed to load model file " << this->modelPath1 << endl;
        return RET_ERR;
    }
    this->interpreter_2.reset(Interpreter::createFromFile(this->modelPath2));
    if (!this->interpreter_2) {
        cout<<"Failed to load model file " << this->modelPath2 << endl;
        return RET_ERR;
    }
    ScheduleConfig config;
    config.type = MNN_FORWARD_AUTO;
    //config.numThread = 4;
    auto runtimeInfo = Interpreter::createRuntime({config});
    this->session1 = this->interpreter_1->createSession(config, runtimeInfo);
    if (!this->session1) {
        cout << "Failed to create session1\n";
        return RET_ERR;
    }
    this->session2 = this->interpreter_2->createSession(config, runtimeInfo);
    if (!this->session2) {
        cout <<"Failed to create session2 \n";
        return RET_ERR;
    }
    this->input_details_1[0] = interpreter_1->getSessionInput(this->session1, "input_2");
    this->input_details_1[1] = interpreter_1->getSessionInput(this->session1, "input_3");
    this->interpreter_1->resizeTensor(this->input_details_1[0], { 1,1,fft_out_size });
    this->interpreter_1->resizeTensor(this->input_details_1[1], { 1,2,128,2 });
    this->interpreter_1->resizeSession(this->session1);
    //this->input_details_1[0] = interpreter_1->getSessionInput(this->session1, "input_2");
    //this->input_details_1[1] = interpreter_1->getSessionInput(this->session1, "input_3");
    this->output_details_1[0] = interpreter_1->getSessionOutput(this->session1, "activation_2");
    this->output_details_1[1] = interpreter_1->getSessionOutput(this->session1, "tf.stack_2");//tf_op_layer_stack_2
    this->input_details_2[0] = interpreter_2->getSessionInput(this->session2, "input_4");
    this->input_details_2[1] = interpreter_2->getSessionInput(this->session2, "input_5");
    this->interpreter_2->resizeTensor(this->input_details_2[0], { 1,1,block_len });
    this->interpreter_2->resizeTensor(this->input_details_2[1], { 1,2,128,2 });
    this->interpreter_2->resizeSession(this->session2);
    //this->input_details_2[0] = interpreter_2->getSessionInput(this->session2, "input_4");
    //this->input_details_2[1] = interpreter_2->getSessionInput(this->session2, "input_5");
    this->output_details_2[0] = interpreter_2->getSessionOutput(this->session2, "conv1d_3");
    this->output_details_2[1] = interpreter_2->getSessionOutput(this->session2, "tf.stack_5");//tf_op_layer_stack_5
    return RET_OK;
}
第二个模型的推理代码是
if (this->interpreter_2->runSession(this->session2) != NO_ERROR) {
        cout << "infer2 failed" << endl;
    }
    else {
        cout << "infer2 success!!!!!!!!!!!!!!!!!!!!!!!" << endl;
    }

**Comment by KAWAKO-in-GAYHUB** [comment]
已解决

**Comment by Ryuk17** [comment]
请问你是怎么解决的呢？

**Comment by KAWAKO-in-GAYHUB** [comment]
> 请问你是怎么解决的呢？

抱歉，时间有点远了，解决的过程我记不太清了。我当时好像是用了MNN的另一种推理方法实现的推理过程。
