### ISSUE TITLE
离线量化问题

### ISSUE THREAD

**Issue by aiyongchun** [alibaba/MNN#1665]
采用./quantized.out /Users/aiyongchun/Downloads/1074_14.mnn 1074_quant.mnn QuantConfig.json量化后，用Netron打开模型，每个op的类型还是没变，而且查看量化log的时候发现cos distance为nan，请教为啥会出现这种情况![image](https://user-images.githubusercontent.com/25132713/132790754-08b8796d-8048-4ddc-89a4-7a0e2d2838b3.png)量化配置文件{
    "format":"BGR",
    "width":256,
    "height":256,
    "path":"/Users/aiyongchun/Downloads/mm",
    "used_sample_num":100,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS",
    "feature_clamp_value":127,
    "weight_clamp_value":127,
    "quant_bits":8,
    "input_type":"image",
    "debug":true
}

**Comment by aiyongchun** [comment]
![image](https://user-images.githubusercontent.com/25132713/132790865-3d50d219-a0e8-4aec-bf2a-758a1f418b2a.png)

**Comment by yyfcc17** [comment]
现在量化之后的op type还是float的，但是参数已经是int8了，可以用MNNDump2Json看。你可以测下精度，如果不行的话建议用EMA方法

**Comment by HAOCHENYE** [comment]
你好，请问量化的log信息是在哪里看的？

**Comment by aiyongchun** [comment]
> 你好，请问量化的log信息是在哪里看的？

在写配置参数里面将debug设为true
