### ISSUE TITLE
tf2.4模型转mnn失败

### ISSUE THREAD

**Issue by GuoPL** [alibaba/MNN#1666]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
intel mac

# Github版本:
# Github Version:
MNN 1.2.0

# 编译方式:
# Compiling Method
mkdir build && cd build && cmake .. && make -j8

#错误信息
Start to Convert Other Model Format To MNN Model...
[17:04:27] /Users/xxxxx/Documents/dev/git_tool/MNN/tools/converter/source/tensorflow/tensorflowConverter.cpp:21: Check failed: success ==> read_proto_from_binary failed
Start to Optimize the MNN Net...
./transfer2mnn.sh: line 1: 35309 Segmentation fault: 11  ./MNNConvert -f TF --modelFile /Users/xxxxxx/Documents/dev/git_work/mi-predict-app/predict_app/xxxxxx/submit/model/saved_model.pb --MNNModel /Users/xxxxxx/Documents/dev/git_work/mi-predict-app/predict_app/xxxxxx/submit/model.mnn --bizCode mnn

**Comment by jxt1234** [comment]
TF 2.4 不支持 pb 导出，需要导出 tflite 或 onnx 转 mnn
