### ISSUE TITLE
Android   'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7c65a15940)' 

### ISSUE THREAD

**Issue by xing-shuai** [alibaba/MNN#1668]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Android （ubuntu18.04编译）

# 编译方式:
```
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_SHARED_LIBS=OFF \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
```

libMNNJni.so为JNI逻辑+libMNN.a

********** Crash dump: **********
Build fingerprint: 'samsung/m21nsser/m21:11/RP1A.200720.012/M215FXXU2BUD3:user/release-keys'
Abort message: 'FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7c65a15940)'
#00 0x0000000000089bfc /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
#01 0x00000000000ecf04 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL15__fortify_fatalPKcz+124)
#02 0x00000000000ec3e0 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL25HandleUsingDestroyedMutexP15pthread_mutex_tPKc+52)
#03 0x00000000000ec228 /apex/com.android.runtime/lib64/bionic/libc.so (pthread_mutex_lock+172)
#04 0x0000000000125dd0 /data/app/~~r0EbkPGCgGVPNHwMtMAoOQ==/lib/arm64/libMNNJni.so (_ZNSt6__ndk15mutex4lockEv+8)
                                                                                                                                                std::__ndk1::__libcpp_mutex_lock(pthread_mutex_t*)
                                                                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/include/__threading_support:264:10
                                                                                                                                                std::__ndk1::mutex::lock()
                                                                                                                                                /buildbot/src/android/ndk-release-r21/external/libcxx/src/mutex.cpp:33:0
#05 0x00000000000319d4 /data/app/~~r0EbkPGCgGVPNHwMtMAoOQ==/lib/arm64/libMNNJni.so (_ZNK3MNN11Interpreter19getSessionOutputAllEPKNS_7SessionE+52)MNN::Interpreter::getSessionOutputAll(MNN::Session const*) const   ??:0:0
#06 0x000000000002eb1c /data/app/~~r0EbkPGCgGVPNHwMtMAoO==/lib/arm64/libMNNJni.so

**Comment by jxt1234** [comment]
这个像是推理过程中原网络被另一个线程释放了
