### ISSUE TITLE
语雀示例工程问题

### ISSUE THREAD

**Issue by zhangcheng-007** [alibaba/MNN#1669]
1. 我已经利用示例工程代码成功运行姿态检测。
2. 在运行图像检测上出现了与示例不同的结果，输出图片。
![result](https://user-images.githubusercontent.com/54843450/133064880-fa08c539-f48a-4284-8a1f-7a29cb546da8.png)

3. 在图像识别当中，无法打开synset_words.txt
求解答：）

**Comment by jxt1234** [comment]
2. 复现了，是有问题，我看一下
3. 现在 synset_words.txt 去掉了，改成了多张图片输入，我修改下文档

**Comment by jxt1234** [comment]
2. 的问题已经修正，demo 代码的问题，请同步最新代码
