### ISSUE TITLE
Errors on inference of a model on android OPENCL MNN_FORWARD_OPENCL

### ISSUE THREAD

**Issue by lucwan** [alibaba/MNN#167]
by using MNN_FORWARD_OPENCL  i am getting the following errors on redmi note 5 pro

Don't support type 517, data___FloatToInt8___
Don't support type 513, conv1a
Don't support type 513, conv1b
Don't support type 514, ___Int8ToFloat___For_relu1b
Don't support type 517, relu1b___FloatToInt8___
Don't support type 513, conv2_1
Don't support type 514, ___Int8ToFloat___For_relu2_1
Don't support type 517, relu2_1___FloatToInt8___
Don't support type 513, conv2_2
Don't support type 514, ___Int8ToFloat___For_res2_2
Don't support type 514, ___Int8ToFloat___For_res2_2
Don't support type 517, relu2_2___FloatToInt8___
Don't support type 513, conv2_3
Don't support type 514, ___Int8ToFloat___For_relu2_3
Don't support type 517, relu2_3___FloatToInt8___
Don't support type 513, conv2_4
Don't support type 514, ___Int8ToFloat___For_res2_4
Don't support type 517, relu2_4___FloatToInt8___
Don't support type 513, conv2_5
Don't support type 514, ___Int8ToFloat___For_relu2_5
Don't support type 517, relu2_5___FloatToInt8___
Don't support type 513, conv2_6
Don't support type 514, ___Int8ToFloat___For_res2_6
Don't support type 517, relu2_6___FloatToInt8___
Don't support type 513, conv2
Don't support type 514, ___Int8ToFloat___For_relu2
Don't support type 517, relu2___FloatToInt8___
Don't support type 513, conv3_1
Don't support type 514, ___Int8ToFloat___For_relu3_1
Don't support type 517, relu3_1___FloatToInt8___
Don't support type 513, conv3_2
Don't support type 514, ___Int8ToFloat___For_res3_2
Don't support type 514, ___Int8ToFloat___For_res3_2
Don't support type 517, relu3_2___FloatToInt8___
Don't support type 513, conv3_3
Don't support type 514, ___Int8ToFloat___For_relu3_3
Don't support type 517, relu3_3___FloatToInt8___
Don't support type 513, conv3_4
Don't support type 514, ___Int8ToFloat___For_res3_4
Don't support type 517, relu3_4___FloatToInt8___
Don't support type 513, conv3_5
Don't support type 514, ___Int8ToFloat___For_relu3_5
Don't support type 517, relu3_5___FloatToInt8___
Don't support type 513, conv3_6
Don't support type 514, ___Int8ToFloat___For_res3_6
Don't support type 517, relu3_6___FloatToInt8___
Don't support type 513, conv3_7
Don't support type 514, ___Int8ToFloat___For_relu3_7
Don't support type 517, relu3_7___FloatToInt8___
Don't support type 513, conv3_8
Don't support type 514, ___Int8ToFloat___For_res3_8
Don't support type 517, relu3_8___FloatToInt8___
Don't support type 513, conv3_9
Don't support type 514, ___Int8ToFloat___For_relu3_9
Don't support type 517, relu3_9___FloatToInt8___
Don't support type 513, conv3_10
Don't support type 514, ___Int8ToFloat___For_res3_10
Don't support type 517, relu3_10___FloatToInt8___
Don't support type 513, conv3_11
Don't support type 514, ___Int8ToFloat___For_relu3_11
Don't support type 517, relu3_11___FloatToInt8___
Don't support type 513, conv3_12
Don't support type 514, ___Int8ToFloat___For_res3_12
Don't support type 517, relu3_12___FloatToInt8___
Don't support type 513, conv3_13
Don't support type 514, ___Int8ToFloat___For_relu3_13
Don't support type 517, relu3_13___FloatToInt8___
Don't support type 513, conv3_14
Don't support type 514, ___Int8ToFloat___For_res3_14
Don't support type 517, ____reshape____fc5___FloatToInt8___
Don't support type 513, fc5
Don't support type 514, ___Int8ToFloat___For_46

**Comment by czy2014hust** [comment]
Int8 inference only support CPU NOW

**Comment by lucwan** [comment]
We have turned off the flag  MNN_USE_INT8_FAST  in the compilation of MNN android and i have not set INT* anywhere but still this error is coming.

**Comment by czy2014hust** [comment]
Do you use MNN quantization tool to quantize your model?
