### ISSUE TITLE
MNN是否支持强制试用bf16做推理

### ISSUE THREAD

**Issue by zhuguiqian** [alibaba/MNN#1670]
请问，在windows上普通的intel cpu，是否可以用bf16来做网络的推理？目前哪些算子支持bf16？谢谢

**Comment by jxt1234** [comment]
可以，打开 -DMNN_SUPPORT_BF16 就行

**Comment by jxt1234** [comment]
source/core/OpCommonUtils.cpp 里面的 OpCommonUtils::opCompabilityForLowp 为所有 bf16 / fp16 支持的算子，这个算子是经过几何计算化简之后的
