### ISSUE TITLE
请问 BENCHMARK的这个错误是因为 metal 不支持这个算子吗?

### ISSUE THREAD

**Issue by letian-jiang** [alibaba/MNN#1673]
<img width="1546" alt="417d3ee0589f6fd62e177b4db8417d65" src="https://user-images.githubusercontent.com/16740944/133759788-e9c40762-ffee-49d9-8bb5-f74e29e0de85.png">

<img width="1008" alt="52f6e61e56a06cd196a7b7dc3c50f3ec" src="https://user-images.githubusercontent.com/16740944/133759749-0c714637-7c57-4884-ad6c-a0c9ffcdd417.png">

**Comment by jxt1234** [comment]
出错原因应该是在 onCopyBuffer 里面数据格式不支持，这个算子不支持不影响

**Comment by letian-jiang** [comment]
这个模型是demo里的resnet-v2-50.mnn , 是因为不支持fp16 格式吗？
