### ISSUE TITLE
Android 端GPU模型推理时，前处理 pretreat->convert 耗时很多

### ISSUE THREAD

**Issue by wukui1900** [alibaba/MNN#1674]
# 平台:  Android

# Github版本: e6db5c69fc91d3fe3a10dfc455c1780f66c515b9

在Android 端GPU( *使用OpenCL* )测试模型推理时间的时候，主要代码如下：
![image](https://user-images.githubusercontent.com/69660461/133760091-d23576dc-7b0c-4b5c-ad5c-3c470618aeaf.png)
经测试时间为
![image](https://user-images.githubusercontent.com/69660461/133760865-51bb4892-f031-4ce9-a596-9cafc048da15.png)

**但是将 162 行```pretreat->convert((uint8_t *) inputImage, width, height, 0, input);``` 放到循环外**：
![image](https://user-images.githubusercontent.com/69660461/133761057-18ab7bd9-2483-470d-af9a-22bdca679993.png)
测试时间为：
![image](https://user-images.githubusercontent.com/69660461/133760784-ec14f8e5-4a5d-492a-bf01-d95169969144.png)
使用 timeProfile 分析模型时间，如下：
![image](https://user-images.githubusercontent.com/69660461/133761944-8b94de2f-f353-4ca2-abce-2d5856176e90.png)
模型推理耗时的确不多。

**为什么模型推理耗时很少，但是前处理 pretreat->convert 耗时非常多？？？**

**Comment by jxt1234** [comment]
计时没有包括 copyToHostTensor ，有可能是异步执行的原因

**Comment by wukui1900** [comment]
> 计时没有包括 copyToHostTensor ，有可能是异步执行的原因

所以这里主要的耗时在数据拷贝吗？从内存拷贝到显存？
