### ISSUE TITLE
关于opengl后端

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#168]
现有的框架支持非android和ios的的嵌入式设备吗？譬如jetson tk1，tx2这种，这些是支持opengles2/3的，能否编译opengl后端，在这些设备上运行吗？

**Comment by jxt1234** [comment]
1、需要 opengl es 3.1 ，可以用 angle https://github.com/google/angle 去安装 opengl es 环境.

2、一般来说，支持 compute shader 的设备也支持 opencl 或 vulkan ，可以考虑用 opencl 或 vulkan
