### ISSUE TITLE
iPhoneOS Emulator runtime error

### ISSUE THREAD

**Issue by huypl53** [alibaba/MNN#1714]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS simulator

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
	running core/memory_utils.
	running expr/ModuleTest.
Increase: 38.992828 in rt
Increase: 6.892685 in rt
	running expr/SessionTest.
run, 166, cost time: 2591.647949 ms
operator(), 182, cost time: 2861.960938 ms
operator(), 182, cost time: 2872.289062 ms
operator(), 182, cost time: 2872.803955 ms
operator(), 182, cost time: 3056.972900 ms
	running op/pad.
	running op/binary/broadcastShapeTest.
	running op/binary/add.
	running op/binary/subtract.
	running op/binary/multiply.
	running op/binary/divide.
	running op/binary/pow.
	running op/binary/minimum.
	running op/binary/maximum.
	running op/binary/biasadd.
	running op/binary/greater.
	running op/binary/greaterequal.
	running op/binary/less.
	running op/binary/floordiv.
	running op/binary/squareddifference.
	running op/binary/equal.
	running op/binary/lessequal.
	running op/binary/floormod.
	running op/binary/atan2.
	running op/binary/logicalor.
	running op/binary/notqual.
	running op/binary/subtractBroastTest.
	running expr/MatMul.
	running op/setdiff1d.
	running op/concat.
	running op/OneHotTest.
	running expr/MultiThreadLoad.
	running expr/AllAny.
	running op/zeroslike.
	running op/gatherv2.
	running op/batch_to_space_nd.
	running op/prelu.
	running op/unary/abs.
	running op/unary/negative.
	running op/unary/floor.
	running op/unary/ceil.
	running op/unary/square.
	running op/unary/sqrt.
	running op/unary/rsqrt.
	running op/unary/exp.
	running op/unary/log.
	running op/unary/sin.
	running op/unary/cos.
	running op/unary/tan.
	running op/unary/asin.
	running op/unary/acos.
	running op/unary/atan.
	running op/unary/reciprocal.
	running op/unary/log1p.
	running op/unary/tanh.
	running op/unary/sigmoid.
	running op/unary/acosh.
	running op/unary/asinh.
	running op/unary/atanh.
	running op/unary/round.
	running op/unary/sign.
	running op/unary/cosh.
	running op/unary/erf.
	running op/unary/erfc.
	running op/unary/erfinv.
	running op/unary/expm1.
	running op/unary/sinh.
	running op/unary/gelu.
	running op/linspace.
	running op/PoolGrad.
	running op/reduction/reduce_sum.
	running op/reduction/reduce_sum_multi.
	running op/reduction/reduce_mean.
	running op/reduction/reduce_max.
	running op/reduction/reduce_min.
	running op/reduction/reduce_prod.
	running op/Conv2DBackPropFilter.
	running op/Conv2DBackPropFilterDW.
	running op/tile.
	running op/matmul.
	running op/matmulBConst.
	running op/size.
	running op/crop.
	running expr/MatrixBand.
	running expr/ExprResize.
	running op/spacetodepth.
	running cv/image_process/gray_to_gray.
	running cv/image_process/gray_to_gray_bilinear_transorm.
	running cv/image_process/gray_to_gray_nearest_transorm.
	running cv/image_process/gray_to_rgba.
	running cv/image_process/bgr_to_gray.
	running cv/image_process/rgb_to_bgr.
	running cv/image_process/rgba_to_bgra.
	running cv/image_process/bgr_to_bgr.
	running cv/image_process/rgb_to_gray.
	running cv/image_process/rgba_to_gray.
	running cv/image_process/rgba_to_gray_bilinear_transorm.
	running cv/image_process/rgba_to_gray_nearest_transorm.
	running cv/image_process/rgba_to_bgr.
	running cv/image_process/bgr_to_bgr_blitter.
	running cv/image_process/gray_to_gray_blitter.
	running cv/image_process/yuv_blitter.
	running op/squeeze.
	running core/buffer_allocator.
	running op/MultiDeconv.
	running core/tensor_utils.
	running op/shape.
	running expr/Padding.
	running expr/ReverseSequence.
	running op/range.
	running op/resize.
	running op/Interp.
	running op/MaxPool3d.
	running op/AvePool3d.
	running op/selu.
	running op/fill.
	running op/matrixbandpart.
	running op/softsign.
	running op/depthtospace.
	running op/ConvInt8/im2col_gemm.
	running op/ConvInt8/winograd.
	running op/ConvInt8/depthwise.
	running op/split.
	running core/auto_storage.
	running op/UnravelIndexTest.
	running op/moments.
	running op/softplus.
	running op/reshape/nchw.
	running op/reshape/nhwc.
	running op/reshape/nc4hw4.
	running op/softmax.
	running op/argmax.
	running op/argmin.
	running core/size_computer.
	running op/ScatterNdTest.
	running op/convolution/conv2d.
	running op/convolution/sparse_conv2d.
	running op/convolution/depthwise_conv.
	running op/convolution/conv_group.
	running op/Conv2DBackPropTest.
	running op/bias_grad.
	running op/unstack.
	running op/relu.
	running op/BroadcastToTest.
	running op/MultiConv.
	running expr/Replace.
	running expr/Precompute.
	running expr/PrecomputeDynamic.
	running op/rank.
	running op/expand_dims.
	running op/convolution/conv3d.
	running op/space_to_batch_nd.
	running expr/Extra.
	running op/stack.
	running cv/matrix/scale.
	running engine/backend/copy_buffer_float.
Test 0 Backend for 0 

 ========= check NC4HW4_2_NC4HW4_float result ! ========= 

alloc deviceTensor_pre

alloc deviceTensor
copy from host to  deviceTensor_pre

copy from deviceTensor_pre to  deviceTensor

copy from deviceTensor to  new host

 ========= check nhwc_2_NC4HW4_2_nhwc_float result ! ========= 
Test 0 Backend for 1 

 ========= check NC4HW4_2_NC4HW4_float result ! ========= 

alloc deviceTensor_pre

alloc deviceTensor
copy from host to  deviceTensor_pre

copy from deviceTensor_pre to  deviceTensor

copy from deviceTensor to  new host

 ========= check nhwc_2_NC4HW4_2_nhwc_float result ! ========= 
Test 0 Backend for 2 

 ========= check NC4HW4_2_NC4HW4_float result ! ========= 

alloc deviceTensor_pre

alloc deviceTensor
copy from host to  deviceTensor_pre

copy from deviceTensor_pre to  deviceTensor

copy from deviceTensor to  new host

 ========= check nhwc_2_NC4HW4_2_nhwc_float result ! ========= 
Test 5 Backend for 0 

 ========= check NC4HW4_2_NC4HW4_float result ! ========= 

alloc deviceTensor_pre

alloc deviceTensor
copy from host to  deviceTensor_pre

copy from deviceTensor_pre to  deviceTensor

copy from deviceTensor to  new host

 ========= check nhwc_2_NC4HW4_2_nhwc_float result ! ========= 
Error for bn:0, -0.007843 -> -0.266667. F32_BF16_MAX_LOSS:0.007812
Error for 5 bn
	running engine/backend/copy_buffer_cpu.
Test 0 Backend for 0 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 
Test 0 Backend for 1 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 
Test 0 Backend for 2 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check NC4HW4_2_NC4HW4_IntType result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 

 ========= check nhwc_2_NC4HW4_2_nhwc_inttype result ! ========= 
	running op/elu.
	running op/Dilation2D/cpu.
	running core/tensor.
	running expr/Gather.
	running op/relu6.
	running op/clamp.
	running op/gather_nd.
	running op/gather.
Error: engine/backend/copy_buffer_float
TEST_NAME_UNIT: 单元测试
TEST_CASE_AMOUNT_UNIT: {"blocked":0,"failed":1,"passed":174,"skipped":0}
Message from debugger: Terminated due to signal 9

```
```

**Comment by wangzhaode** [comment]
单元测试错误，不是编译问题
