### ISSUE TITLE
函数直接返回new出来的裸指针

### ISSUE THREAD

**Issue by jnulzl** [alibaba/MNN#1725]
https://github.com/alibaba/MNN/blob/7f50ae689d26d930152ecb1cee8a30ae4cb0b8db/source/core/Tensor.cpp#L151-L155
这个函数直接返回new出来的指针，不注意的话用起来很危险啊

**Comment by jxt1234** [comment]
在使用时是要求调求方 delete 的，一般写法是 std::shared_ptr<Tensor> tensor(Tensor::createDevice(...));

**Comment by jnulzl** [comment]
> 在使用时是要求调求方 delete 的，一般写法是 std::shared_ptr tensor(Tensor::createDevice(...));

好的，觉得最好在头文件做个说明会好点
