### ISSUE TITLE
building error for OPENCL option on windows.

### ISSUE THREAD

**Issue by woodrocky** [alibaba/MNN#173]
I am trying to build the MNN with NMAKE on windows. However, I get the following error. 
"fatal error U1073: don't know how to make 'source\backend\opencl\MNN_CL.lib'. 
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop."
Does anyone know the reason for this? I already changed the non-Unicide program language to English (American).

Thanks!

**Comment by yutianhang** [comment]
MNN currently does not support opencl on Windows, we plan to support it on the next version.

**Comment by woodrocky** [comment]
OK, Yutianhang. Thank you very much for your prompt response. 

> MNN currently does not support opencl on Windows, we plan to support it on the next version.

**Comment by woodrocky** [comment]
New version will solve this problem.
