### ISSUE TITLE
使用 EMA 量化精度崩溃

### ISSUE THREAD

**Issue by ShiquanYu** [alibaba/MNN#1730]
使用 "EMA" int8 量化精度完全奔溃，float测试正常，模型及转换/量化指令见附件。

我在板子上进行推理时，预处理/后处理 int8 与 float 方法完全一致，不知道是不是我调用上的问题？

[molels.zip](https://github.com/alibaba/MNN/files/7387473/molels.zip)

# Github版本:
# Github Version: commit: a469efe8adf2d212381957b68525c7b8f8569099

**Comment by songyonger** [comment]
请问这个问题解决了吗? 我测的使用EMA量化方法转换的float32和int8的MNN模型得到的推理结果也都是错的。 @ShiquanYu @jxt1234
