### ISSUE TITLE
MNN converter windows编译失败　MNN converter build problem on windows

### ISSUE THREAD

**Issue by TigerVersusT** [alibaba/MNN#1740]
我自己用ninjia 在windows 下编译MNN converter 失败，issue上也有很多编译失败的问题。我换成visual studio 2019后编译成功，供参考

since there is no official replay about MNN converter complie problems on windows, I write this for your consideration: try more compilers guys, in my case, visual studio 2019 works fine

**Comment by WolfKingAlex** [comment]
> 我自己用ninjia 在windows 下编译MNN converter 失败，issue上也有很多编译失败的问题。我换成visual studio 2019后编译成功，供参考
> 
> since there is no official replay about MNN converter complie problems on windows, I write this for your consideration: try more compilers guys, in my case, visual studio 2019 works fine

@TigerVersusT how do you figure out the converter compile problems with protobuf, would you mind showing the detailed routine of your try? I went through the main MNN， but failed 1000 times on compiling the converter.
Great thanks.

**Comment by TigerVersusT** [comment]
@WolfKingAlex 时间太久了，我只记得自己把-G 参数改成了“Visual Studio 16 2019”，然后vs下编译的，有些不支持的feature在vs里更新了安装包就好了，实在搞不定就去钉钉群里问问吧，issue问太慢了

**Comment by WolfKingAlex** [comment]
@TigerVersusT 可否问一下钉钉群的号码或者二维码的网址，MNNgithub那个二维码都过期了进不去~
