### ISSUE TITLE
PyUnicodeUCS2_AsUTF8String Error

### ISSUE THREAD

**Issue by ziaoang** [alibaba/MNN#1744]
Hi Guys,
I install MNN by pip, which version is 1.1.6. My python version is 2.7.16.
Installation is success, but error happens when import, like this:
```
ImportError: /home/xxx/.local/lib/python2.7/site-packages/_mnncengine.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
```

**Comment by jxt1234** [comment]
Update python to 3.8+ and retry.
