### ISSUE TITLE
如何构造单通道数据？

### ISSUE THREAD

**Issue by JiaoPaner** [alibaba/MNN#1747]
1.mxnet转onnx,输入为(1,1,100,100),类型为float32
2.onnx转MNN,转换成功,但正确性校验报 "absMaxV:0.004360 - DiffMax 0.756104"的错误,经咨询说是相对误差过小，超过阈值了，但模型可用
3.加载模型,的确未报错,但是输出结果不太对,打印 input->printShape(),input->elementSize()结果如下:
	**Tensor shape**: 1, 1, 100, 100, 
        **elementSize()**: 40000
疑问：input->elementSize()的值不应该是100*100=10000吗？为什么会是40000，input->size()的值是40000才对呀，都多乘了一个4，这种情况是否是onnx模型就错了，但onnx打印出shape也为[1, 1, 100, 100]

**Comment by JiaoPaner** [comment]
经过咨询，通道为1时上对齐到4，那么通道为1的时候 输入应该怎么传入呢？

**Comment by anliyuan** [comment]
大佬，这个问题最终是怎么解决的呢？

**Comment by JiaoPaner** [comment]
@anliyuan  直接使用copyFromHostTensor
```cpp
string datapath = "./data/";
    datapath.append(to_string(index)).append(".bat");
    out_txt_file.open(datapath, ios::out | ios::trunc);
    for (int i = 0; i < image.size(); i++) {
        out_txt_file << to_string(image[i]) << endl;
    }
    out_txt_file.close();
    auto m_inputTensor = m_mnnNet->getSessionInput(m_session, NULL);
    auto m_tempTensor = new Tensor(m_inputTensor, Tensor::CAFFE);
    auto nhwc_data = m_tempTensor->host<float>();
    auto nhwc_size = m_tempTensor->size();
    ::memcpy(nhwc_data, &image[0], nhwc_size);
    m_inputTensor->copyFromHostTensor(m_tempTensor);
```

**Comment by anliyuan** [comment]
> @anliyuan 直接使用copyFromHostTensor
> 
> ```c++
> cv::Mat image = cv::imread("test.jpg");
> auto m_inputTensor = m_mnnNet->getSessionInput(m_session, NULL);
> auto m_tempTensor = new Tensor(m_inputTensor, Tensor::CAFFE);
> auto nhwc_data = m_tempTensor->host<float>();
> auto nhwc_size = m_tempTensor->size();
> ::memcpy(nhwc_data, image.data, nhwc_size);
> m_inputTensor->copyFromHostTensor(m_tempTensor);
> ```

我也是这么写的，但是输出的结果有很多有问题的值，大佬有遇到过这种情况吗？
```c++
auto nhwc_Tensor = new MNN::Tensor(input_tensor_, MNN::Tensor::CAFFE);
auto nhwc_data = nhwc_Tensor->host<float>();
auto nhwc_size = nhwc_Tensor->size();
::memcpy(nhwc_data, Y.data, nhwc_size);
input_tensor_->copyFromHostTensor(nhwc_Tensor);
delete(nhwc_Tensor);
tinyunet_interpreter_->runSession(tinyunet_session_);
MNN::Tensor* output_tensor_ =tinyunet_interpreter_->getSessionOutput(tinyunet_session_, "output");
MNN::Tensor output_tensor_host(output_tensor_, output_tensor_->getDimensionType());
output_tensor_->copyToHostTensor(&output_tensor_host);
output_tensor_host.print();
```

**Comment by JiaoPaner** [comment]
@anliyuan 你的输入是否是固定 没固定需要resize

**Comment by anliyuan** [comment]
我的输入大小是固定的，resizeTensor也试过，结果还是一样。这个任务是一个超分辨率的任务，输入输出都是单通道，这些是否会导致输出结果有问题呢？

**Comment by JiaoPaner** [comment]
@anliyuan 
不会 mnn支持任意维度 你先打印出 前处理后 输入到模型里的数据是否和原始模型(python onnx)一致吧  输入都不一致  最终结果肯定不一致

**Comment by anliyuan** [comment]
这个我检查过了，同一张图输入是一致，找不到原因了
