### ISSUE TITLE
如何避免在onnx转mnn时出现transpose算子？opencl推理

### ISSUE THREAD

**Issue by 674106399** [alibaba/MNN#1748]
你好，我的网络结构非常常见，backbone输出的特征图经过一个GAP以后flatten送入fc层进行分类。但是我在onnx转mnn后，发现mnn转换工具会对flatten后的特征进行transpose和reshape再送进分类层。我目前需要用到opencl进行推理，但opencl不支持transpose运行会直接崩溃。请问有什么办法吗？

我尝试过不同版本的mnn，1.2.0会出现transpose，1.1.6是出现rank和stridedslice，这些都是opencl不支持的。
这样一个非常常见的结构按理来说不应该不支持，请问有什么办法解决吗？

这里是我的onnx图
![POPO-screenshot-20211104-190539](https://user-images.githubusercontent.com/13503330/140303273-9c77b16a-fdd1-4e24-9f71-ba414b3153a8.png)

这里是1.2.0转换得到的mnn
![POPO-screenshot-20211104-190635](https://user-images.githubusercontent.com/13503330/140303396-2681dcd0-d305-4da2-85b9-43c9288b0f0b.png)

**Comment by jxt1234** [comment]
这个 MNN 的 opencl 是支持的，也不需要避免。直接 crash 是指什么？
