### ISSUE TITLE
onnx模型转mnn模型出现段错误，发现mnn源代码有错误！

### ISSUE THREAD

**Issue by MayBeLoveYou** [alibaba/MNN#175]
在MNN/tools/converter/source/onnx/onnxOpConverter.cpp中以下代码：
if (dataSize == 1 || dimSize == 0) {
        // scalar or one dim data(only one data)
        switch (constantTp->data_type()) {
            case onnx::TensorProto_DataType_DOUBLE:
                tensor_content = constantTp->double_data().data();
                break;
            case onnx::TensorProto_DataType_INT64:
                tensor_content = constantTp->int64_data().data();
                break;
            case onnx::TensorProto_DataType_INT32:
                tensor_content = constantTp->int32_data().data();
                break;
            default:
                tensor_content = constantTp->float_data().data();
                break;
        }
        // some Const node is Scalar, but must
        // access to data from tensor_content
        if (!tensor_content) {
            tensor_content = constantTp->raw_data().data();
        }
        
    } else {
        tensor_content = constantTp->raw_data().data();
    }

当运行到else处onnx数据类型为float型保存在float_data()中但mnn取得是raw_data()的数据出现数据错误，当数据过大时出现段错误！

**Comment by czy2014hust** [comment]
Could you please send your model to me?
