### ISSUE TITLE
使用OPENCL后端推理时出现ERROR CODE : -45和-48

### ISSUE THREAD

**Issue by ZiluoW** [alibaba/MNN#1751]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86_64

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
-DMNN_OPENCL=true
-DMNN_SEP_BUILD=OFF
-DMNN_USE_SYSTEM_LIB=OFF

使用backend后端，MNNV2Basic.out提示
~/MNN-master/build2$ ./MNNV2Basic.out ~/crn.mnn 1 0 3 1
Use extra forward type: 3

Open Model ./crn.mnn
Invalid Cache
Cache invalid, will be reset
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s copy_buffer_to_image2d in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
Build program failed, err:-11 !
programName.c_str()=s conv_2d in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
setArg err -48
Build program failed, err:-11 !
programName.c_str()=s raster in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
setArg err -48
Build program failed, err:-11 !
programName.c_str()=s buffer_to_image in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
Build program failed, err:-11 !
programName.c_str()=s deconv_2d in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s raster in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:convertBufferToImage
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
Build program failed, err:-11 !
programName.c_str()=s unary in buildKernel, 387
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
CL ERROR CODE : -45, info:getKernel
setArg err -48
Write cache to .tempcache, size = 9036
test_main, 213, cost time: 1732.232056 ms
Session Info: memory use 4.034683 MB, flops is 3.740555 M, backendType is 3
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
===========> Session Resize Done.
===========> Session Start running...
Input size:644
        **Tensor shape**: 1, 1, 161, 1,
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
output: output
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
output: output_c_state
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
output: output_h_state
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
precision:2, Run 1 time:
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run2d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -48, info:run3d
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:nchw_buffer_to_image
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -48, info:Raster
CL ERROR CODE : -45, info:getKernel
CL ERROR CODE : -48, info:image_to_nchw_buffer
                                           While15      [While] run 1 average cost 0.001000 ms, 0.094 %, FlopsRate: 0.000 %
                                           While21      [While] run 1 average cost 0.001000 ms, 0.094 %, FlopsRate: 0.000 %
                                               286      [Deconvolution] run 1 average cost 0.003000 ms, 0.281 %, FlopsRate: 5.913 %
                                               314      [Convolution] run 1 average cost 0.003000 ms, 0.281 %, FlopsRate: 6.242 %
                                               320      [Convolution] run 1 average cost 0.003000 ms, 0.281 %, FlopsRate: 1.314 %
                                               108      [PReLU] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 0.015 %
                                               289      [PReLU] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 0.031 %
                                               291      [Deconvolution] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 12.483 %
                                               296      [Deconvolution] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 25.624 %
                                               301      [Deconvolution] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 1.352 %
                                               317      [Convolution] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 2.957 %
                                         UnaryOp37      [UnaryOp] run 1 average cost 0.004000 ms, 0.374 %, FlopsRate: 0.016 %
                                               281      [Deconvolution] run 1 average cost 0.005000 ms, 0.468 %, FlopsRate: 2.628 %
                                               311      [Convolution] run 1 average cost 0.005000 ms, 0.468 %, FlopsRate: 12.812 %
                                          Raster28      [Raster] run 1 average cost 0.005000 ms, 0.468 %, FlopsRate: 0.062 %
                                          Raster31      [Raster] run 1 average cost 0.005000 ms, 0.468 %, FlopsRate: 0.127 %
                                          Raster34      [Raster] run 1 average cost 0.005000 ms, 0.468 %, FlopsRate: 0.258 %
                                               100      [PReLU] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.064 %
                                               112      [PReLU] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.007 %
                                               294      [PReLU] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.064 %
                                               299      [PReLU] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.129 %
                                               304      [PReLU] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.016 %
                                               308      [Convolution] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.676 %
                                          Raster25      [Raster] run 1 average cost 0.006000 ms, 0.561 %, FlopsRate: 0.029 %
                                               104      [PReLU] run 1 average cost 0.007000 ms, 0.655 %, FlopsRate: 0.031 %
                                               284      [PReLU] run 1 average cost 0.007000 ms, 0.655 %, FlopsRate: 0.015 %
                                                96      [PReLU] run 1 average cost 0.007000 ms, 0.655 %, FlopsRate: 0.129 %
                                          Raster41      [Raster] run 1 average cost 0.007000 ms, 0.655 %, FlopsRate: 0.013 %
                                          Raster39      [Raster] run 1 average cost 0.008000 ms, 0.748 %, FlopsRate: 0.013 %
                                          Raster10      [Raster] run 1 average cost 0.009000 ms, 0.842 %, FlopsRate: 0.007 %
                                          Raster19      [Raster] run 1 average cost 0.009000 ms, 0.842 %, FlopsRate: 0.007 %
                                          Raster13      [Raster] run 1 average cost 0.010000 ms, 0.935 %, FlopsRate: 0.007 %
                                          Raster18      [Raster] run 1 average cost 0.010000 ms, 0.935 %, FlopsRate: 0.007 %
                                          Raster12      [Raster] run 1 average cost 0.011000 ms, 1.029 %, FlopsRate: 0.007 %
                                          Raster16      [Raster] run 1 average cost 0.036000 ms, 3.368 %, FlopsRate: 0.007 %
                                          Raster22      [Raster] run 1 average cost 0.040000 ms, 3.742 %, FlopsRate: 0.013 %
                                          Raster40      [Raster] run 1 average cost 0.054000 ms, 5.051 %, FlopsRate: 0.013 %
                                          Raster38      [Raster] run 1 average cost 0.055000 ms, 5.145 %, FlopsRate: 0.013 %
                                           While17      [While] run 1 average cost 0.129000 ms, 12.067 %, FlopsRate: 6.684 %
                                           While11      [While] run 1 average cost 0.144000 ms, 13.471 %, FlopsRate: 6.684 %
                                           While20      [While] run 1 average cost 0.159000 ms, 14.874 %, FlopsRate: 6.768 %
                                           While14      [While] run 1 average cost 0.165000 ms, 15.435 %, FlopsRate: 6.768 %
Avg= 1.069000 ms, min= 1.069000 ms, max= 1.069000 ms
`

**Comment by jxt1234** [comment]
什么设备上出现的问题?

**Comment by areafire** [comment]
> 什么设备上出现的问题?

x86_64服务器(Ubuntu 16.04)和树莓派3B上用Opencl后端推理都出现了这个问题

**Comment by songshaoze** [comment]
> > 什么设备上出现的问题?
> 
> x86_64服务器(Ubuntu 16.04)和树莓派3B上用Opencl后端推理都出现了这个问题

麻烦问下这个问题解了吗？我在Android平台上也遇到了类似的情况
