### ISSUE TITLE
MNN的内存， 安卓测试

### ISSUE THREAD

**Issue by Liujingxiu23** [alibaba/MNN#1752]
我遇到的问题，在安卓上，我所使用的模型，在cpu,运行速度上都可以，但是内存占用挺大的。
想问下，MNN是如何处理内存相关的？或者有什么方法， 例如编译配置，不同的调用方式，等等，可以减少内存占用的吗？

我所使用的代码，需要处理动态维度的输入。
在实际的推理之前，“resizeTensor/resizeSession”是完成了模型推理所需所有内存的分配吗？
我简单查看了下MNN的代码，source/core/Session.cpp
148         for (auto& iter : mPipelines) {
149             auto error = iter->allocMemory();
150             if (NO_ERROR != error) {
151                 return error;
152             }
153         }

**Comment by jxt1234** [comment]
MNN 会有内存复用机制，减少中间内存占用的。
占用较大有没有量化的数据

**Comment by Liujingxiu23** [comment]
@jxt1234  谢谢您的回复 我又检查了一下，可能不是MNN造成的内存问题。不太了解安卓的测试，测试报告参数指标较多，抱歉了。我关闭问题啦，谢谢你！

**Comment by Liujingxiu23** [comment]
不好意思  还是想请教下， 由于我们的app内存整体还是比较高（不仅包括MNN模型，还有些其他模块等，其他可以优化的都进行内存优化了）。想问下MNN是否还有内存优化的空间，如果有的话，我该从哪里着手呢？

**Comment by summerrain321** [comment]
我也遇到类似的问题，Native heap在Android平台偏高，在Linux平台用massif测试会低一点。
