### ISSUE TITLE
如何精简MNN

### ISSUE THREAD

**Issue by ShiquanYu** [alibaba/MNN#1753]
你好，我想缩小库的体积，想咨询下如何进行裁剪以适配量化模型的推理，当前尝试了打开 MNN_BUILD_MINI 选项，库体积有明显下降，但是无法用于推理量化后的模型，请问还有其他方式可以精简库吗，谢谢

**Comment by jxt1234** [comment]
可以推理，但目前没有途径产生静态量化MNN模型，后面会支持 把 MNN 模型转成静态MNN模型的

**Comment by ShiquanYu** [comment]
> 可以推理，但目前没有途径产生静态量化MNN模型，后面会支持 把 MNN 模型转成静态MNN模型的

好的，非常感谢，期待静态量化版发布。

那有没有什么方式可以去除一些用不到的算子以精简库体积呢，当前我通过删减 `source/backend/cpu/CPUOPRegister.cpp` 中的相关算子减小了一部分体积，但没有找到其他组件如 `Transform` 的精简方式，不知道是否有类似 `CPUOPRegister` 的文件可以自由选择所需算子的方法？

**Comment by jxt1234** [comment]
啊，搞错了，现在就可以转的，先用普通版本得到量化的 MNN 模型，然后 
./MNNConvert -f MNN --modelFile origin.mnn --MNNModel static.mnn  就可以了

**Comment by jxt1234** [comment]
Transform 采用 build mini 方式就可以去除的

**Comment by ShiquanYu** [comment]
> 啊，搞错了，现在就可以转的，先用普通版本得到量化的 MNN 模型，然后 ./MNNConvert -f MNN --modelFile origin.mnn --MNNModel static.mnn 就可以了

啊感谢大佬！测试成功了转换模型使用的指令是：

```bash
$ ./MNNConvert -f MNN --modelFile origin.mnn --MNNModel static.mnn --saveStaticModel
```

笔芯~

**Comment by AITosee** [comment]
@jxt1234 啊大佬，再问一个问题，改成 static model 后推理速度反而变慢了啥情况，变慢了45%

**Comment by ShiquanYu** [comment]
@jxt1234 大佬，我把模型转换成static model后推理速度比非静态的慢了45%，这个正常吗

**Comment by Hughheyu** [comment]
> > 可以推理，但目前没有途径产生静态量化MNN模型，后面会支持 把 MNN 模型转成静态MNN模型的
> 
> 好的，非常感谢，期待静态量化版发布。
> 
> 那有没有什么方式可以去除一些用不到的算子以精简库体积呢，当前我通过删减 `source/backend/cpu/CPUOPRegister.cpp` 中的相关算子减小了一部分体积，但没有找到其他组件如 `Transform` 的精简方式，不知道是否有类似 `CPUOPRegister` 的文件可以自由选择所需算子的方法？

请问大佬，你删减`source/backend/cpu/CPUOPRegister.cpp`之后用的 cmake 参数是怎样的，我修改后没有生效，得到的 libMNN.so 库还是那么大
