### ISSUE TITLE
MNNPackedMatMul参数的疑惑

### ISSUE THREAD

**Issue by andyweiqiu** [alibaba/MNN#1758]
最近看了下MNN的代码，看到汇编‘MNNPackedMatMul’这个方法时
void MNNPackedMatMul(float* C, const float* A, const float* B, const size_t* parameter, const float* postParameters, const float* bias);
对parameter和postParameters不是很了解，可以说说这两个参数集合里面每个元素代表什么吗？

**Comment by no5-aaron-wu** [comment]
个人理解，parameter是尺寸信息，postParameters是后处理信息，主要就是relu或relu6的min max阈值

**Comment by andyweiqiu** [comment]
> 个人理解，parameter是尺寸信息，postParameters是后处理信息，主要就是relu或relu6的min max阈

**Comment by jxt1234** [comment]
> 个人理解，parameter是尺寸信息，postParameters是后处理信息，主要就是relu或relu6的min max阈值

基本没问题
