### ISSUE TITLE
MNN Don't support type [ ConvolutionDepthwise ]

### ISSUE THREAD

**Issue by qaz734913414** [alibaba/MNN#176]
MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [23:23:17] /home/MNN/tools/converter/source/caffe/caffeConverter.cpp:143: Don't support type [ ConvolutionDepthwise ], for ConvolutionDepthwise1
./run.sh: 行 1:  4130 已放弃               ./MNNConvert -f CAFFE --modelFile FaceAlignment.caffemodel --prototxt FaceAlignment.prototxt --MNNModel FaceAlignment.mnn --bizCode MNN

**Comment by jxt1234** [comment]
Use convolution with group instead of ConvolutionDepthwise

**Comment by qaz734913414** [comment]
> Use convolution with group instead of ConvolutionDepthwise
请问如何操作，需要修改caffe的prototxt吗？

**Comment by qaz734913414** [comment]
> Use convolution with group instead of ConvolutionDepthwise

请问如何操作？是需要修改caffe中prototxt吗？

**Comment by doodoo0006** [comment]
可以修改prototxt来做， 就是类型用卷积，增加一个group参数

**Comment by qaz734913414** [comment]
谢谢指教，我去试一下
