### ISSUE TITLE
如何理解Strassen递归的cost终止条件

### ISSUE THREAD

**Issue by no5-aaron-wu** [alibaba/MNN#1760]
https://github.com/alibaba/MNN/blob/71cd04e91c9281412ff8f7c2b29cd9019195131e/source/backend/cpu/compute/StrassenMatmulComputor.cpp#L259-L272

按仅有的注释，这里计算的应该是访存量（但按命名看又像是乘加次数），对每个变量的具体含义还是很困惑，大佬能不能对每个变量的含义及其计算的数学逻辑详细解释一下

@jxt1234 

恳请赐教，不胜感激！

**Comment by jxt1234** [comment]
按访存量来算的，AComputeCost , BComputeCost, CComputeCost 分别 是 A / B / C 矩阵相关变换（加减）所需。
saveMatMulCost 是节省下的一次矩阵乘法访存量
由于公式不是特别准确，由实验加速效果设置一个 penalty ，增大 A, B, C 的额外消耗权重
