### ISSUE TITLE
Don't support type [ArgMax], 552

### ISSUE THREAD

**Issue by Ying-Kang** [alibaba/MNN#1765]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
ios

# Github版本:
latest

# 编译方式:
官网推荐方式

# 编译日志:
编译没有报错

# 问题描述
推理结果可视化正确，但是在加载模型的时候会有这个报错
请问这个是什么原因

**Comment by jxt1234** [comment]
是用 metal 后端吧，这个只是说 metal 后端没实现这个算子，会回退到 CPU

**Comment by Ying-Kang** [comment]
> 

有没有办法让gpu支持这个算子呢？如果自定义的话需要怎么实现呢？有无教程，这个算子应该还是比较简单的

**Comment by Ying-Kang** [comment]
希望官方能实现下gpu的argmax，目前仅仅支持cpu的argmax，这个操作还是比较常规的，好多模型里面都有涉及，希望未来GPU能尽快支持上来
