### ISSUE TITLE
量化实现问题

### ISSUE THREAD

**Issue by 946166920** [alibaba/MNN#1767]
看量化代码https://github.com/alibaba/MNN/commit/d91fc6397630c0a7e4c5daac73f65c7b5e2dec92#diff-a2252f0a68ed9575539d1d3f2e161c0f62ed42a150ea5a47256abc1085893d16
已经把updateScale方法删去了，opType 从MNN::OpType_Convolution映射成MNN::OpType_ConvInt8的实现都删了。用netron打开看量化后的模型还是op的类型没变。
请问量化实现具体的变动有文档可以看到吗？这么变动的是出于什么考虑？

**Comment by wangzhaode** [comment]
会在量化保留tensor scale；在实际运行时根据scale自动将Conv转换为ConvInt8

**Comment by wangzhaode** [comment]
您好，还有什么疑惑可以在这里继续提问

**Comment by 946166920** [comment]
MNN量化支持在哪些IP上运行，支持NPU芯片吗？

**Comment by wangzhaode** [comment]
> 会在量化保留tensor scale；在实际运行时根据scale自动将Conv转换为ConvInt8

这个不提供列表；需要自行测试
