### ISSUE TITLE
交叉编译aarch64平台报错

### ISSUE THREAD

**Issue by TD-wzw** [alibaba/MNN#1768]
<img width="771" alt="err1" src="https://user-images.githubusercontent.com/57340568/143734437-c4bcf1d9-3ee1-445a-bf4a-948b14077048.PNG">

**Comment by TD-wzw** [comment]
<img width="751" alt="err2" src="https://user-images.githubusercontent.com/57340568/143734462-f3e8f5a0-c8e5-4d6c-87a4-d154224a675d.PNG">

**Comment by TD-wzw** [comment]
工具链：https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-i686_aarch64-linux-gnu.tar.xz

**Comment by jxt1234** [comment]
更新版本
