### ISSUE TITLE
opencl推理找不到后端

### ISSUE THREAD

**Issue by TD-wzw** [alibaba/MNN#1770]
![2$HZOLA~ %KCX@% T@OO}YA](https://user-images.githubusercontent.com/57340568/143826649-64473399-c268-4618-9713-40f8dbdd5e2a.png)

**Comment by TD-wzw** [comment]
option(MNN_OPENCL "Enable OpenCL" ON)编译时候确认已经打开，也尝试过auto handle = dlopen("libMNN_CL.so", RTLD_NOW);
依旧这样

**Comment by jxt1234** [comment]
可以用 dlerror 打印是否 dlopen 成功
