### ISSUE TITLE
量化mnn模型debug设置为true，打印overflow。并且将量化后的模型使用python推理，拿到的某些输出结果为None。

### ISSUE THREAD

**Issue by Wq-dd** [alibaba/MNN#1771]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# ubuntu:  
## quant.json参数
![微信图片_20211129211059](https://user-images.githubusercontent.com/62586707/143874038-c61c8e03-1141-42a0-bc4b-c4b8b8b0f34b.png)
## 报错截图
![微信图片_20211129210918](https://user-images.githubusercontent.com/62586707/143873891-dd288f91-4335-4572-b105-6018ad44470f.png)

**Comment by Wq-dd** [comment]
已解决

**Comment by Z-yq** [comment]
你好，请问这是怎么解决的呢？

**Comment by Wq-dd** [comment]
你好，我是将最后一个层不量化解决的。发自我的华为手机-------- 原始邮件 --------发件人： Z-yq ***@***.***>日期： 2021年12月15日周三 中午11:57收件人： alibaba/MNN ***@***.***>抄送： Wq-dd ***@***.***>, State change ***@***.***>主    题： Re: [alibaba/MNN] 量化mnn模型debug设置为true，打印overflow。并且将量化后的模型使用python推理，拿到的某些输出结果为None。 (Issue #1771)

你好，请问这是怎么解决的呢？
