### ISSUE TITLE
模型中有while算子，resizeSession出错

### ISSUE THREAD

**Issue by yanxiaoying** [alibaba/MNN#1776]
# 模型里面包含LSTM，成功转换成MNN模型

在调用mnnNet->resizeSession(session) 时候打印输出：

Compute Shape for lstm_1/while
Don't support compute shape for control flow opCompute Shape Error for lstm_1/while

增加打印语句，发现在SizeComputer.cpp里面 的
bool SizeComputer::computeOutputSize(const MNN::Op* op, const std::vector<Tensor*>& inputs,
                                     const std::vector<Tensor*>& outputs) 函数中对while算子直接返回了。
        // Don't support compute shape for control flow op
        if (op->type() == OpType_While || op->type() == OpType_If) {
            return false;
        }

请问我该如何处理呢？

**Comment by jxt1234** [comment]
有 while 算子需要借助 MNN_Express 运行，参考 demo/exec/transformerDemo.cpp 或 tools/cpp/ModuleBasic.cpp

**Comment by wtmilk** [comment]
> 有 while 算子需要借助 MNN_Express 运行，参考 demo/exec/transformerDemo.cpp 或 tools/cpp/ModuleBasic.cpp

问下具体怎么使用，有对应能跑的模型吗

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/gaa5xa#1645f9ac
