### ISSUE TITLE
量化为int8时直接报Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TD-wzw** [alibaba/MNN#1778]
![TSEB3HTR@3(FQ{6` M4 ETO](https://user-images.githubusercontent.com/57340568/144701393-42d90671-d959-43a3-8b17-856389349155.png)

**Comment by TD-wzw** [comment]
看着好像是先读的imageInputConfig.json,读完直接报错，请问这个是有什么特别注意的么？是我操作不当还是怎么回事？

**Comment by Louis24** [comment]
有群么

**Comment by TD-wzw** [comment]
主页有钉钉群你可以加一下看看
