### ISSUE TITLE
tensorflow模型（mobilenetV2）转MNN提示Check failed: success ==> read_proto_from_binary failed

### ISSUE THREAD

**Issue by usertianqin** [alibaba/MNN#1780]
执行：./MNNConvert -f TF --modelFile ./MobileNetV2/saved_model.pb --MNNModel MobileNetV2.mnn --bizCode MNN后提示下面的内容是什么原因呢？试了好几个其他模型也报同样的错

MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
Error while converting the model!
[06:26:52] /workspace/mnn/MNN/tools/converter/source/tensorflow/tensorflowConverter.cpp:23: Check failed: success ==> read_proto_from_binary failed

**Comment by usertianqin** [comment]
~

**Comment by wuyx517** [comment]
同样遇到这种情况，求解

**Comment by jxt1234** [comment]
tf 模型的格式不对，需要是 1.X 导出的 pb 格式
