### ISSUE TITLE
Linear算子转mnn时出现了许多碎操作

### ISSUE THREAD

**Issue by xingyueye** [alibaba/MNN#1783]
![image](https://user-images.githubusercontent.com/40205112/145330443-ec6ed4c6-6369-48db-becb-b6d18889fd97.png)
你好，我这里是一个简单的分类网络，最后接一个FC分类器，但是在转mnn后得到了如图所示的一大堆。好像是默认采用1x1卷积来实现Linear，同时为了维度匹配久自动添加了一堆的碎操作？
请教下这个情况是不是常见的，会不会对推理速度产生影响，或者有没有较好的方法来避免该问题？

**Comment by yyfcc17** [comment]
MNN会将矩阵乘转成conv1*1，所以多出来很多碎的op，对性能一般没有太大影响，如果想要避免这样的情况，可以自己手动将代码中的矩阵乘改成reshape + conv1*1 + reshape的组合，这样MNN就不会多转出来一些op了
