### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by dachengai** [alibaba/MNN#1785]
MNNConvert error 

编译环境：gcc version 4.9.4 (Ubuntu 4.9.4-2ubuntu1~16.04) 

转换命令：
./MNNConvert -f TF --batch 1 --debug  --modelFile frozen_model-2.pb --keepInputFormat --MNNModel test.mnn --bizCode biz --optimizeLevel 1 --saveStaticModel 

输出：
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Floating point exception (core dumped)

模型：

[frozen_model-2.pb.zip](https://github.com/alibaba/MNN/files/7685220/frozen_model-2.pb.zip)

**Comment by pablogsanchez** [comment]
Same issue with ONNX.

**Comment by wangzhaode** [comment]
在转换时会把conv group计算成0导致出错；已修复，下版本同步；
