### ISSUE TITLE
使用MNNPythonOfflineQuant.py 进行MNN模型PTQ之后，MNN模型输出为固定值

### ISSUE THREAD

**Issue by Z-yq** [alibaba/MNN#1788]
平台：Ubuntu 20.04

使用MNN Python版本为1.1.6， 测试脚本为 python API

安装方式 pip install -U MNN

问题：

我想对Conv1D之类的模型进行PTQ操作，于是随便搭了一个Conv1D的结构，模型导入路径为 onnx->mnn->mnn ptq

但使用MNNPythonOfflineQuant.py进行PTQ之后，模型任何输入的输出都是固定值。

是我的使用方式有问题吗？感谢答疑。

我使用的代码在这里：

[mnn_ptq.zip](https://github.com/alibaba/MNN/files/7711012/mnn_ptq.zip)

**Comment by hzpzlz** [comment]
我的也是，离线量化后的结果是两个Const，请问有解决方案吗？
onnx->mnn阶段：
mnnconvert -f ONNX --modelFile xx.onnx --MNNModel xx.mnn --bizCode biz --forTraining

mnn quant阶段：
使用mnn_offline_quant.py，生成了一个量化后后的模型，用工具查看，只有一个Const的输入和Const1的输出。

量化模型inference阶段：
报错：
`Invalidate buffer to create interpreter
Traceback (most recent call last):
  File "mnn_inter.py", line 27, in <module>
    interpreter = MNN.Interpreter(mnn_model_path)
Exception: PyMNNInterpreter_new: NetInstance::createFromFile failed. Invalid model file, Check console log messages!
`
感谢感谢

**Comment by wangzhaode** [comment]
在`mnn_offline_quant.py`开头加上`F.lazy_eval(True)`
