### ISSUE TITLE
Android平台MNN内存回收

### ISSUE THREAD

**Issue by summerrain321** [alibaba/MNN#1791]
MNN在Android平台上，releaseModel或者releaseSession之后，仍然有内存没有释放掉（我确定不是内存泄漏）。请问MNN有没有内存回收的功能？看到内部有很多STL变量，可能需要回收内存。我原本想用malloc_trim函数回收，但是Android不支持。

盼回复！

**Comment by jxt1234** [comment]
删除 Interpreter 会回收全部内存
