### ISSUE TITLE
编译不出TestConvertResult

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#1792]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Linux x64
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
Release 1.2
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

![image](https://user-images.githubusercontent.com/22525811/146709047-1a71a3a5-8680-4f23-9fdb-9ee0a6bc3704.png)
mkdir build
cd build 
cmake ..

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
![image](https://user-images.githubusercontent.com/22525811/146709119-ee6daa4c-f3be-4d21-88e0-5b02bcdda05c.png)

**Comment by YongyuG** [comment]
+1

**Comment by jxt1234** [comment]
cmake .. -DMNN_BUILD_CONVERTER=ON ，或者先清掉当前的 build 目录

如果编译出了 MNNConvert 但没有 TestConvertResult ，更新代码。
Windows 系统上目前不支持 TestConvertResult 编译，后续会把相应功能集成到 MNNConvert 里面
