### ISSUE TITLE
【MNNPythonOfflineQuant】Error for FloatToInt8 because var not ready

### ISSUE THREAD

**Issue by hatinenshiro** [alibaba/MNN#1793]
（1）pytorch模型转onnx模型
seq = torch.zeros((1, 10), dtype=torch.int64)
pos = torch.zeros((1, 10), dtype=torch.int64)
torch.onnx.export(encoder,
                      (seq, pos), 
                      "encoder.onnx",
                      opset_version=11,
                      do_constant_folding=False,
                      training=True,
                      input_names=['seq', 'pos'],
                      output_names=['output'])

（2）onnx模型转mnn模型
mnnconvert -f ONNX --modelFile encoder.onnx --MNNModel encoder.mnn --bizCode biz --forTraining

（3）使用MNNPythonOfflineQuant量化mnn模型
python mnn_offline_quant.py --mnn_model encoder.mnn --quant_model encoder_quant.mnn --batch_size 1

步骤（3）报错：Error for FloatToInt8 because var not ready
请问这是什么原因呢？

注：python MNN version: 1.1.6

**Comment by Liujingxiu23** [comment]
@hatinenshiro 你好 请问这个问题解决了吗？我也遇到一样的问题呢
