### ISSUE TITLE
Mac/IOS结果不一致

### ISSUE THREAD

**Issue by UnderController** [alibaba/MNN#1794]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
IOS

# Github版本:
# Github Version:
1.2.0

# 编译方式:
# Compiling Method
IOS MNN.framework使用Project/ios/MNN xcode工程编译得到, Mac使用直接编译得到动态库

# 编译日志:
# Build Log:

# 问题描述

目前在移植一个分割模型，模型转成mnn后在Mac下结果正常，但是在IOS下结果错误，Mac/IOS都是通过C++接口调用的方式

**Comment by jxt1234** [comment]
更新代码再试下
