### ISSUE TITLE
onnx to mnn error

### ISSUE THREAD

**Issue by feipxyz** [alibaba/MNN#18]
error message:
./MNNConvert -f ONNX --modelFile ~/GitHub/DFace/mobile_v2_pnet.onnx --MNNModel ~/GitHub/DFace/mobile_v2_pnet.mnn --bizCode MNN

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[22:08:27] /Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
libc++abi.dylib: terminating with uncaught exception of type Error: [22:08:27] /Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:83: Check failed: opConverter ==> MNN Converter NOT_SUPPORTED_OP: [ Clip ]
[1]    22273 abort      ./MNNConvert -f ONNX --modelFile ~/GitHub/DFace/mobile_v2_pnet.onnx --MNNMode

how can i solve it?

**Comment by feipxyz** [comment]
another:
/Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
libc++abi.dylib: terminating with uncaught exception of type Error: [23:45:20] /Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:83: Check failed: opConverter ==> MNN Converter NOT_SUPPORTED_OP: [ Constant ]

**Comment by czy2014hust** [comment]
Got it. Will be added later.

**Comment by daquexian** [comment]
> another:
> /Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
> libc++abi.dylib: terminating with uncaught exception of type Error: [23:45:20] /Users/feipeng/GitHub/MNN/tools/converter/source/onnx/onnxConverter.cpp:83: Check failed: opConverter ==> MNN Converter NOT_SUPPORTED_OP: [ Constant ]

Constant can be eliminated by onnx optimizer or [onnx-simplifier](https://github.com/daquexian/onnx-simplifier)
