### ISSUE TITLE
opengl 与opencl性能差异很大

### ISSUE THREAD

**Issue by chenliang110** [alibaba/MNN#1800]
I convert a tflite model to .mnn，then use   different MNNForwardType  to test time on android phone。I find below
opencl :   1137.9ms
opengl:    0.86ms 

renoir:/data/local/tmp # ./benchmark.out /data/local/tmp/modell 80 10 3 1
./benchmark.out /data/local/tmp/modell 80 10 3 1
MNN benchcccmark111
Forward type: **OpenCL** thread=1** precision=2** sparsity=0** sparseBlockOC=1
--------> Benchmarking... loop = 80, warmup = 10
[ - ] XXX111.mnn                  max = 1148.479 ms  min = 1129.541 ms  avg = 1137.906 ms

renoir:/data/local/tmp # ./benchmark.out /data/local/tmp/modell 80 10 6 1
./benchmark.out /data/local/tmp/modell 80 10 6 1
MNN benchcccmark111
Forward type: **N/A** thread=1** precision=2** sparsity=0** sparseBlockOC=1
--------> Benchmarking... loop = 80, warmup = 10
[ - ] XXX111.mnn                  max =    1.229 ms  min =    0.820 ms  avg =    0.879 ms

the opengl time is or not normal??

**Comment by jxt1234** [comment]
这个应该是opengl 存在问题，计算结果不正确，建议用 opencl / vulkan
