### ISSUE TITLE
请问怎么把NC4HW4的输出转换为NCHW?

### ISSUE THREAD

**Issue by fxfviolet** [alibaba/MNN#1806]
pytorch==1.3.0
分割模型保存为pt后转成mnn，发现mnn是NC4HW4格式，请问怎么转成NCHW？谢谢！

**Comment by zhanglaplace** [comment]
同问~

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/cn/rrqay9 
FAQ 里面有
