### ISSUE TITLE
量化错误Compute Shape Error Can't run session because not resized

### ISSUE THREAD

**Issue by Louis24** [alibaba/MNN#1807]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux

# Github版本:
# Github Version:
None

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
Download Date = 2021.12.24

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
################# Compile Quantization #################

cd MNN && mkdir build && cd build
cmake -DMNN_BUILD_QUANTOOLS=ON .. && make -j32
会在tools/quantization生成一个

################# pythpn API #################
pip install MNN

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
使用量化工具
MNN/build/quantized.out rvm_mb3_fp32.mnn res.mnn imageInputConfig.json
```
粘贴在这里
Paste log here or pastebin
```
liyexing@BVC-SMT-001:~$ vi imageInputConfig.json
liyexing@BVC-SMT-001:~$ MNN/build/quantized.out rvm_mb3_fp32.mnn res.mnn imageInputConfig.json
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/quantized.cpp:23: >>> modelFile: rvm_mb3_fp32.mnn
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/quantized.cpp:24: >>> preTreatConfig: imageInputConfig.json
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/quantized.cpp:25: >>> dstFile: res.mnn
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/quantized.cpp:52: Calibrate the feature and quantize model...
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:158: Use feature quantization method: KL
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:159: Use weight quantization method: MAX_ABS
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:179: feature_clamp_value: 127
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:180: weight_clamp_value: 127
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:189: skip quant op name: 388
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/Helper.cpp:103: used image num: 100
Compute Shape Error for 427
[20:02:56] /mnt/HDD0/liyexing/MNN/tools/quantization/calibration.cpp:666: fake quant weights done.
Compute Shape Error for 427
Error for concat size of op [ 388 ], the 1 input not match output
Compute Shape Error for 388
Error for concat size of op [ 388 ], the 1 input not match output
Compute Shape Error for 388
Can't run session because not resized
Can't run session because not resized
Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 1.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 2.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 3.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 4.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 5.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 6.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 7.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 8.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 9.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 10.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 11.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 12.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 13.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 14.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 15.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 16.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 17.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 18.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 19.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 20.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 21.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 22.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 23.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 24.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 25.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 26.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 27.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 28.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 29.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 30.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 31.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 32.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 33.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 34.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 35.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 36.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 37.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 38.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 39.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 40.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 41.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 42.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 43.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 44.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 45.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 46.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 47.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 48.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 49.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 50.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 51.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 52.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 53.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 54.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 55.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 56.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 57.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 58.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 59.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 60.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 61.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 62.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 63.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 64.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 65.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 66.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 67.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 68.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 69.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 70.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 71.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 72.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 73.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 74.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 75.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 76.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 77.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 78.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 79.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 80.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 81.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 82.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 83.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 84.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 85.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 86.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 87.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 88.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 89.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 90.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 91.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 92.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 93.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 94.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 95.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 96.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 97.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 98.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 99.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
ComputeFeatureRange: 100.00 %
Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 1.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 2.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 3.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 4.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 5.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 6.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 7.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 8.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 9.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 10.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 11.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 12.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 13.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 14.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 15.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 16.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 17.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 18.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 19.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 20.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 21.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 22.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 23.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 24.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 25.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 26.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 27.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 28.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 29.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 30.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 31.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 32.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 33.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 34.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 35.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 36.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 37.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 38.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 39.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 40.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 41.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 42.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 43.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 44.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 45.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 46.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 47.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 48.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 49.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 50.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 51.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 52.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 53.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 54.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 55.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 56.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 57.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 58.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 59.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 60.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 61.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 62.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 63.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 64.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 65.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 66.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 67.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 68.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 69.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 70.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 71.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 72.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 73.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 74.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 75.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 76.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 77.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 78.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 79.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 80.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 81.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 82.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 83.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 84.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 85.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 86.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 87.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 88.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 89.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 90.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 91.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 92.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 93.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 94.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 95.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 96.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 97.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 98.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 99.00 %Invalid Tensor, the session may not be ready
Can't run session because not resized
CollectFeatureDistribution: 100.00 %
Can't find tensors for 823
Segmentation fault (core dumped)
liyexing@BVC-SMT-001:~$

**Comment by wangzhaode** [comment]
输入形状是不是跟模型要求的不一致

**Comment by m00nLi** [comment]
> 输入形状是不是跟模型要求的不一致

我也遇到这个问题，输入形状已经跟模型要求完全一致了的，还是报这个错误。
另外，模型输入是1280x1280大尺寸分辨率时，我用EMA量化会报错；但是在量化配置json文件里改下量化校正图片缩放尺寸改小到640x640就不报错
