### ISSUE TITLE
about tensorflow op tf.keras.layers.SeparableConv1D

### ISSUE THREAD

**Issue by tricky61** [alibaba/MNN#1808]
tf2 model convert to tflite model
when convert tflite model, this operation caussed error:
MNN-1.2.5/tools/converter/source/tflite/CustomTflite.cpp:65: Check failed: tfliteOp->inputs.size() == 3 ==> TFLite_Detection_PostProcess should have 3 inputs!
MNN-1.2.5/tools/converter/source/tflite/CustomTflite.cpp:66: Check failed: tfliteOp->outputs.size() == 4 ==> TFLite_Detection_PostProcess should have 4 outputs!

cout this op seems:FlexFusedBatchNormV3
will support this op?

**Comment by wangzhaode** [comment]
目前没有计划支持
