### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by silaopi** [alibaba/MNN#1809]
新手，macbook（intel版）上在自己的项目里编译不通过，一直在报这个错。MNN是用package_scripts/mac/build_lib.sh编译的。

完整的错误信息：
====================[ Build | mnn_demo | Debug ]================================
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --build /Users/admin/CLionProjects/mnn_demo/cmake-build-debug --target mnn_demo -- -j 6
[ 50%] Linking CXX executable mnn_demo
Undefined symbols for architecture x86_64:
  "MNN::Interpreter::createFromFile(char const*)", referenced from:
      _main in main.cpp.o
  "MNN::Interpreter::~Interpreter()", referenced from:
      std::__1::default_delete<MNN::Interpreter>::operator()(MNN::Interpreter*) const in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [mnn_demo] Error 1
make[2]: *** [CMakeFiles/mnn_demo.dir/all] Error 2
make[1]: *** [CMakeFiles/mnn_demo.dir/rule] Error 2
make: *** [mnn_demo] Error 2

自己的C++代码：
#include <iostream>
#include <opencv2/opencv.hpp>
#include <MNN/Interpreter.hpp>

#define IMAGE_VERIFY_SIZE 224
#define CLASSES_SIZE 2
#define INPUT_NAME "input"
#define OUTPUT_NAME "output"

int main() {
    std::cout << "Hello, World!" << std::endl;

    std::string image_path = "/Users/admin/Desktop/projects/MNN_models/val/0_main/143_852641_P21022264333346_shipai_5.jpg";

    std::string mnn_model_path = "/Users/admin/Desktop/projects/MNN-1.2.5/build/models/qcshoes_parts_cls_20211224_quant.mnn";
    auto mnnNet = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(mnn_model_path.data()));

    return 0;
}

**Comment by wangzhaode** [comment]
没有正确使用动态链接库；export一下动态库的路径
