### ISSUE TITLE
求助Retry时报错

### ISSUE THREAD

**Issue by ali-996** [alibaba/MNN#1810]
工作台模型训练->图像分类 Image Classifier 样例中执行Retry报错：
[2021/12/30 15:52:45.029][INFO][6096] -- install finished  c {
  isSuccess: false,
  message: "Error: 'C:\\Users\\xwl' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n" +
    '���������ļ���\r\n' +
    'C:\\Users\\xwl : �޷�����C:\\Users\\xwl����ʶ��Ϊ cmdlet���������ű��ļ�������г�������ơ��������Ƶ�ƴд���������·������ȷ\r\n' +
    '��·����ȷ��Ȼ������һ�Ρ�\r\n' +
    '����λ�� ��:1 �ַ�: 1\r\n' +
    '+ C:\\Users\\xwl Zipper WanLi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\ ...\r\n' +
    '+ ~~~~~~~~~~~~\r\n' +
    '    + CategoryInfo          : ObjectNotFound: (C:\\Users\\xwl:String) [], CommandNotFoundException\r\n' +
    '    + FullyQualifiedErrorId : CommandNotFoundException\r\n' +
    ' \r\n' +
    'Install Requirements From https://mirrors.aliyun.com/pypi/simple/Failed!!!!!!\r\n',
  finished: true,
  percent: 1
}

**Comment by wangzhaode** [comment]
环境没有装好
