### ISSUE TITLE
Error while running generate.sh

### ISSUE THREAD

**Issue by gj-raza** [alibaba/MNN#1812]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

ARMv7hf

# Github版本:
# Github Version:

Latest Release 1.2.0

# Compiling Method
Cross Compile

I am getting this error while running the header file generating script: 

./schema/generate.sh

Output: 

*** cleaning up ***
*** generating fbs under default ***
../../3rd_party/flatbuffers/tmp/flatc: 1: Syntax error: word unexpected (expecting ")")
*** done ***

How do i resolve it?

**Comment by SpaceQ-Z** [comment]
我也遇到这个问题了，我这重装了一个CMAKE就好了，希望能帮到你。。。

**Comment by TCBocean** [comment]
> 我也遇到这个问题了，我这重装了一个CMAKE就好了，希望能帮到你。。。

哈哈哈，你这么一说，我才发现我新装的系统里面没有CMake
