### ISSUE TITLE
MNN 图像预处理后 调用 tensor print ，中间打印出来很多 0 ，这个正确吗？

### ISSUE THREAD

**Issue by CaichaoGitHub** [alibaba/MNN#1817]
代码参考自： segment.cpp , Tensor 内部格式是 NC4HW4
![image](https://user-images.githubusercontent.com/12059897/148167943-37443d32-68a1-48e7-9ae9-05e3d86f0164.png)

打印结果：
<img width="1913" alt="截屏2022-01-05 上午11 51 02" src="https://user-images.githubusercontent.com/12059897/148158000-ec9b607e-1460-48fc-9238-bdc7ae299ad3.png">

深度分析了一下：
这段逻辑执行了内存的拷贝，但是里面用的 pack_unit = 8
<img width="684" alt="企业微信截图_21201fe6-3099-471d-b879-1d77f2cf2d98" src="https://user-images.githubusercontent.com/12059897/148172201-9e32ad4d-00eb-48d3-86b1-00ea62d9a015.png">
但是print 的地方 channel step =4
![image](https://user-images.githubusercontent.com/12059897/148172395-f849360e-2b0f-4093-b599-ebeb8d7c9ac5.png)

**Comment by anliyuan** [comment]
我也发现了这个问题，是影响了推理结果的吗？

**Comment by CaichaoGitHub** [comment]
> 

没

**Comment by jxt1234** [comment]
NC"4"HW"4" 布局原因，这个 4 会按平台用 4 / 8 / 16 修改
