### ISSUE TITLE
tensorflow的Tensor分片操作支持吗？

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#182]
tensorflow的Tensor分片操作支持吗？类numpy的分片操作，例如：输入的是一个Tensor **input**
我要取这个tensor的前四个channel的feature Map，slice = input[:, :, :, 0:4] 这种操作支持吗？
现在在搞一个模型，老怕模型搞完  有MNN不支持的op，除了参考 op support list  还有其他的参考吗？

**Comment by czy2014hust** [comment]
Yes, you can use tf.slice.

**Comment by ChisenZhang** [comment]
> Yes, you can use tf.slice.

不用tf.slice  直接用上面我写的那种形式有问题吗？

**Comment by czy2014hust** [comment]
It depends on whether tensorflow support for this operation.

**Comment by kitein9t** [comment]
@ChisenZhang 我实际用过slice和上述两种写法，MNN均报错，请问你这里顺利解决了吗？
