### ISSUE TITLE
interpreter.createSession()卡住不动

### ISSUE THREAD

**Issue by Yumi-345** [alibaba/MNN#1820]
rk3399 ubuntu1604
        
self.interpreter = MNN.Interpreter("./models/test.mnn")
self.interpreter.setCacheFile(".tempCache")
runtimeinfo, exists = MNN.Interpreter.createRuntime((config,))
print(runtimeinfo, exists)
self.session = self.interpreter.createSession(config, runtimeinfo)

最新git源码，pymnn安装，仅修改opencl为ON

程序运行在self.session = self.interpreter.createSession(config, runtimeinfo)时卡住不动，为报任何错误也为结束。
运行过程中查看maliT860使用率，发现在这句话执行初始，GPU有负载，表示被调用，但很快降为0，应该是调用失败？

更神奇的是，昨天同样的机器，同样的源码跑通了，今天cachfile也加载不了，删了重新加载也卡在这里不动。
请大佬指点 感激不尽

**Comment by liujiaxing7** [comment]
你好，我遇到了同样的问题，请问你怎么解决的

**Comment by xinyu391** [comment]
cpu 模式， 频繁 createSession() run(), releaseSession().
同样出现 createSession（）卡住不返回问题。

**Comment by ly0303521** [comment]
你们的cachfile对模型初始化有加速作用吗，我这里GPU模型加载好慢，而且cachfile起不到加速作用

**Comment by bitxsw93** [comment]
试下设置gpuMode(thread_num)为1，看看会不会卡住。

**Comment by bitxsw93** [comment]
设置gpuMode(thread_num)为1试一下
