### ISSUE TITLE
onnx 模型一致性错误

### ISSUE THREAD

**Issue by guxiangtao** [alibaba/MNN#1822]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86

# Github版本:
# Github Version:
commit 4b8699bbf767db5a013ac465e6388086371cba8f (HEAD -> master, tag: 1.2.6, origin/master, origin/HEAD)

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

onnx 模型一致性不对
Dir exist
onnx/test.onnx
tensor(float)
['output']
inputs:
input
onnx/
outputs:
onnx/output.txt (1, 256, 1)
onnx/
Test onnx
Start to Convert Other Model Format To MNN Model...
[11:38:38] /home/ai/work/MNN/tools/converter/source/onnx/onnxConverter.cpp:30: ONNX Model ir version: 6
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ output, ]
Converted Success!
input
output: output
output: (1, 256, 1, 1, )
TESTERROR output value error : absMaxV:0.954025 - DiffMax 0.609265
expected value
shape: {1, 256, 1, 1}
0 th:shape: {256}
{-0.393741, -0.048417, 0.079341, 0.334849, -0.068274, 0.055312, 0.009921, -0.040913, 0.340218, -0.175321, -0.089709, 0.516384, 0.293874, 0.827636, 0.191106, -0.017225, -0.044043, 0.049858, 0.339704, -0.499568, 0.167313, -0.241589, 0.366898, -0.109596, 0.221987, -0.120547, -0.146886, -0.158792, -0.288077, 0.110079, 0.469125, 0.173263, -0.219131, 0.025078, 0.554243, -0.097416, 0.321161, -0.240328, -0.010036, -0.319128, -0.075512, -0.252745, 0.297048, 0.319487, -0.479152, 0.052196, -0.408527, -0.443049, -0.299870, -0.576009, 0.081702, -0.204945, -0.236827, -0.294958, 0.090376, -0.118549, -0.692432, 0.042545, -0.163262, 0.163626, -0.544508, -0.253002, -0.141253, 0.139533, 0.070319, -0.275918, -0.392799, 0.267961, -0.128201, 0.055872, -0.248959, 0.581970, 0.194033, -0.038241, -0.063908, -0.124592, -0.091598, -0.006151, 0.072453, 0.025071, 0.570873, 0.419509, -0.334039, 0.057690, -0.045997, -0.616037, -0.051393, 0.089059, 0.162396, -0.197217, 0.141917, 0.116399, -0.304381, -0.291939, -0.139793, -0.318617, 0.134607, 0.021922, -0.047465, 0.125222, , …skip middle 56…,0.777772, -0.196001, 0.451785, 0.097101, -0.481434, 0.151889, 0.370704, 0.303813, -0.298598, 0.035973, 0.134872, -0.371482, 0.078005, 0.435572, 0.037572, 0.086896, 0.365436, 0.046399, -0.190206, 0.157365, 0.298378, -0.318635, -0.460539, 0.110424, -0.207258, 0.036089, 0.289176, -0.371737, -0.315534, -0.512106, 0.251130, 0.081753, 0.023981, -0.102747, 0.363814, 0.422089, 0.070468, -0.252138, 0.383269, -0.307203, -0.078660, -0.126785, -0.113346, -0.508212, 0.052304, 0.172450, -0.801887, 0.309019, -0.214573, 0.164558, -0.638638, 0.052366, 0.187427, 0.633246, -0.030672, 0.330712, -0.367716, -0.128791, 0.823368, 0.047146, -0.018067, 0.739382, -0.256021, 0.291019, -0.018644, -0.221994, 0.313762, -0.160240, 0.081172, 0.805447, 0.022731, -0.130692, 0.448956, -0.108570, 0.954025, -0.291287, 0.373473, -0.181865, -0.369121, 0.211946, 0.058777, -0.539371, 0.422028, -0.115494, 0.039201, 0.123561, -0.030791, 0.459534, 0.115691, -0.161361, -0.228800, 0.427447, 0.202327, 0.307564, 0.895469, 0.020926, -0.268674, -0.329962, 0.092055, -0.203111, }
real value
shape: {1, 256, 1, 1}
0 th:shape: {256}
{-0.117857, 0.194279, -0.056420, 0.153426, 0.086107, -0.078438, 0.087216, -0.385942, 0.378601, 0.030722, 0.080219, 0.323017, 0.101026, 0.424875, 0.070831, -0.028890, -0.201230, -0.020020, 0.340195, -0.123010, 0.151418, -0.072591, 0.007338, 0.084213, -0.028551, -0.124223, -0.028594, -0.029687, -0.228253, 0.039641, 0.379224, 0.314795, -0.417837, -0.043561, 0.255595, -0.033599, 0.239800, -0.208934, -0.221919, -0.159955, -0.099555, 0.090467, 0.280923, 0.100973, -0.435031, -0.040553, -0.294014, -0.589311, -0.052852, -0.288951, 0.148531, -0.060805, -0.211617, 0.002859, 0.007799, -0.061562, -0.491110, -0.033598, 0.010816, 0.033683, -0.367294, -0.186253, 0.056471, 0.276938, 0.223185, -0.038005, -0.352899, 0.335053, -0.168320, 0.013462, 0.140905, 0.207936, -0.037778, -0.075060, -0.267664, -0.226018, -0.000906, -0.120033, 0.264080, -0.245670, 0.267050, 0.411840, -0.394403, 0.026495, -0.111940, -0.006772, 0.066777, -0.111163, 0.174198, -0.303125, -0.078577, 0.082753, -0.223977, -0.139237, 0.048413, -0.098407, -0.150004, 0.224755, -0.104862, -0.022128, , …skip middle 56…,0.344303, -0.249162, 0.429545, 0.062680, -0.416995, 0.230192, 0.231171, 0.213400, -0.200605, -0.035768, -0.062473, -0.279094, 0.032797, -0.008121, 0.150505, -0.041610, 0.198701, 0.039572, -0.091703, 0.048611, 0.074476, -0.243564, -0.378102, 0.191168, -0.047590, -0.018792, 0.305268, -0.201304, -0.278749, -0.176498, 0.113492, 0.101704, 0.047703, 0.010796, 0.485802, 0.357581, -0.068691, -0.047887, 0.265561, -0.205308, -0.248540, -0.031434, -0.326412, -0.506377, 0.145127, 0.112059, -0.416637, 0.174444, -0.120645, -0.055974, -0.333812, 0.080214, 0.196565, 0.227185, 0.397602, 0.034293, -0.388603, -0.104170, 0.463239, 0.125857, 0.086523, 0.380017, -0.046383, 0.186392, -0.120313, -0.318375, 0.231079, -0.228503, 0.032216, 0.482169, -0.029512, -0.240812, 0.372677, 0.089679, 0.621795, -0.105712, 0.411556, 0.012753, -0.198365, -0.115009, 0.131163, -0.115790, 0.454881, -0.214914, 0.237240, 0.210471, 0.051600, 0.260364, 0.034521, 0.111377, 0.005447, 0.217380, 0.323035, 0.153932, 0.377487, 0.033166, -0.357710, -0.190104, 0.232185, -0.042177, }
Error for output output
Save mnn result to  .error director

**Comment by jxt1234** [comment]
更新代码再试下，如果仍然报错另外开 issue 并附上 onnx 文件
