### ISSUE TITLE
python调用mnn，多输入

### ISSUE THREAD

**Issue by Note-Liu** [alibaba/MNN#1823]
使用python调用MNN模型，单输入的话使用：

    interpreter = MNN.Interpreter(weight_path)
    session = interpreter.createSession()
    input_tensor = interpreter.getSessionInput(session)
    tmp_input = MNN.Tensor((1, 3, 224, 224), MNN.Halide_Type_Float,image, MNN.Tensor_DimensionType_Caffe)
    input_tensor.copyFrom(tmp_input)
    interpreter.runSession(session)
    output_tensor = interpreter.getSessionOutput(session)

如果模型有多个输入参数，请问怎么修改代码呢？

**Comment by YongyuG** [comment]
同问，很多例子都没有跟RNN相关的，这里我理解是用getSessionInputAll吧？

**Comment by Note-Liu** [comment]
多次调用getSessionInput应该可以

**Comment by Note-Liu** [comment]
遇到了个bug：
No quant info for Cast
Error in CPUBackend::onCopyBuffer:cast

**Comment by YongyuG** [comment]
> 
崩溃的是 createSession不咋work

**Comment by wangzhaode** [comment]
1. 使用[getSessionInput](https://mnn-docs.readthedocs.io/en/latest/cpp/Interpreter.html#getsessioninput)获取多输入中的输入Tensor;
2. 使用[copyFromHostTensor](https://mnn-docs.readthedocs.io/en/latest/cpp/Tensor.html#copyfromhosttensor)拷贝数据；
