### ISSUE TITLE
opencl 设置后 实际跑得是cpu 我该如何debug

### ISSUE THREAD

**Issue by wwangxinhao** [alibaba/MNN#1827]
![image](https://user-images.githubusercontent.com/29766368/149621623-3f69d2d2-22c2-4891-82b0-d29b26ae5f8d.png)

**Comment by wwangxinhao** [comment]
编译的时候有链接libMNN_CL.so

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/rrqay9#EUeMJ
