### ISSUE TITLE
MNN对时序模型部署的支持

### ISSUE THREAD

**Issue by groovemaxRong** [alibaba/MNN#1829]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux

想问一下MNN是否支持时序模型的部署呢？
找了下Issue比较少这方面的帖子，
#1823 #659 #1502 
比如RNN涉及到rnn state的缓存，就会有多输入多输出的场景。
在这种多输入多输出的场景下，是否支持tflite模型的转换、以及多输入多输出的量化呢？
谢谢。

**Comment by YongyuG** [comment]
+1 我也想知道

**Comment by Ryuk17** [comment]
+1

**Comment by zcunyi** [comment]
同问，最近做动作识别，STGCN 模型的输入是连续帧中人物关键点，希望也能提供这种支持

**Comment by jxt1234** [comment]
MNN 支持多输入多输出，时序模型可以通过 Tensorflow - pb / Onnx / Torchscripts 转换到 mnn ，使用方式与原始模型相同。量化需要使用 pymnn 走训练量化。
