### ISSUE TITLE
C++和python，多输入时createSession直接报错

### ISSUE THREAD

**Issue by YongyuG** [alibaba/MNN#1830]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows10

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
win10
cd /path/to/MNN
powershell ./schema/generate.ps1
mkdir build
cd build
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
ninja
```
# 转换日志:
# ConvertLog:
```
$ ./MNNConvert.exe -f ONNX --modelFile E:/workspace/aec_baseline/icassp2022/dec-baseline-model-icassp2022.onnx  --MNN
Model E:/workspace/aec_baseline/icassp2022/new3.mnn --bizCode mnn
Start to Convert Other Model Format To MNN Model...
[13:54:43] :30: ONNX Model ir version: 6
[13:54:43] :154: Check it out ==> 34 has empty input, the index is 4
[13:54:43] :154: Check it out ==> 59 has empty input, the index is 4
Start to Optimize the MNN Net...
[13:54:43] :65:  OnnxSequenceGRUMerge:  W shape:{1, 966, 322}; R shape: {1, 966, 322}, inputs num:5, outputs num:2
[13:54:43] :65:  OnnxSequenceGRUMerge:  W shape:{1, 966, 322}; R shape: {1, 966, 322}, inputs num:5, outputs num:2
45 op name is empty or dup, set to SliceTf45
inputTensors : [ input, h01, h02, ]
outputTensors: [ hn1, hn2, output, ]
Converted Success!
```
# 问题：
我准备尝试多输入和时序模型，
我用的模型来源于icassp2022的aec challenge的baseline模型：```https://github.com/microsoft/AEC-Challenge/tree/main/baseline/icassp2022/dec-baseline-model-icassp2022.onnx```

成功转换MNN后，我在写推理脚本的时候，发现不管是python还是c++，使用interpreter.createSession()时会出错，
这个模型是多输入多输出的。
python脚本：
```
    interpreter = MNN.Interpreter("dec-baseline-model-icassp2022.mnn")
    session = interpreter.createSession()
```
C++:
```
	MNN::Interpreter* net = MNN::Interpreter::createFromFile(modelPath.c_str());

	ScheduleConfig conf;
	Session* session = net->createSession(conf);
```
错误log：
```
Reshape error: 161 -> 25921
Compute Shape Error for Reshape49
```

**Comment by Ryuk17** [comment]
请问您这MNN是什么版本的呢，同样的模型，我使用MNNCovert发现input和output都只剩1个了
![image](https://user-images.githubusercontent.com/22525811/153357497-e21ffcca-7c1b-4217-95fe-b80b4c6ba007.png)

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/rrqay9#Kya42  ，报错不一定有问题，resizeTensor -> resizeSession 即可

**Comment by bigsealing** [comment]
> 参考 https://www.yuque.com/mnn/cn/rrqay9#Kya42 ，报错不一定有问题，resizeTensor -> resizeSession 即可

现在Expr模式支持这种多输入了吗？ 我去年用expr做多输入也总是出错
