### ISSUE TITLE
[python][quantization_aware_training] Training Speed

### ISSUE THREAD

**Issue by hoangtnm** [alibaba/MNN#1836]
Hi, I'm using MNN=1.1.4 to train model in quantization_aware_training mode as described in [MNN example](https://github.com/alibaba/MNN/blob/master/pymnn/examples/MNNTrain/quantization_aware_training/quant_aware_training.py#L99). However, it seems that only one core of CPU is used, which makes the traning speed so slow. Is there any way to speed up the speed such multi-core CPU or GPU offloading? thank you

**Comment by wangzhaode** [comment]
Now just support CPU train.
