### ISSUE TITLE
MNN interp算子支持的插值方式

### ISSUE THREAD

**Issue by zhanglaplace** [alibaba/MNN#1837]
你好，从文档上看支持三种插值方式， Nearstneighbor, bilinear, cubic
但是从代码看，好像只支持两种：    mResizeType = interp->resizeType(); MNN_ASSERT(mResizeType == 1 || mResizeType == 2
另外这两种分别对应pytroch的Upsample的哪两个呢，这边训练用的bicubic，发现转化为mnn结果会异常，bilinear可以正常

![image](https://user-images.githubusercontent.com/12178974/150765848-c2762518-c87e-4f80-8ebe-0e06f7fb902b.png)
![image](https://user-images.githubusercontent.com/12178974/150766129-191730e8-e603-4aab-9646-e927dc039001.png)

**Comment by jxt1234** [comment]
都支持
