### ISSUE TITLE
[python][quantization_aware_training] Data Format for model

### ISSUE THREAD

**Issue by hoangtnm** [alibaba/MNN#1838]
Hi, I'm using MNN=1.1.4 to train model in quantization_aware_training mode as described in MNN example. However, it seems that dataset return image in [F.data_format.NHWC](https://github.com/alibaba/MNN/blob/1.1.4/pymnn/examples/MNNTrain/quantization_aware_training/imagenet_dataset.py#L86)(channel last) but as I understand MNN model (converted from PyTorch --> ONNX --> MNN) requires model in `NCHW` (channel first). So I think there is a mismatch here.

**Comment by yyfcc17** [comment]
the example use tf pb model, so it is nhwc
