### ISSUE TITLE
Multi thread use GPU will block

### ISSUE THREAD

**Issue by Crusoekid** [alibaba/MNN#1839]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android plantform

# Github版本:
# Github Version:
1.2.0

# 编译方式:
# Compiling Method
use android/project/build_64.sh build
ndk 22

多线程GPU推理会导致整个程序挂起。

**Comment by jxt1234** [comment]
请在 2.0.0 再验证下，有问题再重新提 issue
