### ISSUE TITLE
Onnx 转 MNN时 upsample操作的参数问题

### ISSUE THREAD

**Issue by Kay-Tian** [alibaba/MNN#184]
Onnx中upsample的目标参数是Scale，MNN在转换工具MNN/tools/converter/source/onnx/UpsampleOnnx.cpp中也是这样处理的

    if (onnxNode->input_size() != 1) {
        const onnx::TensorProto* scalesTp = initializers[0];
        if (!scalesTp) {
            DLOG(FATAL) << "Scales No TensorProto data!!!==> " << dstOp->name;
        }
        const float* raw_data = (const float*)scalesTp->raw_data().data();
        if (!raw_data) {
            DLOG(FATAL) << "Scales No raw data!!!==> " << dstOp->name;
        }

        int float_data_size = scalesTp->raw_data().size() / sizeof(float);
        for (int j = 0; j < float_data_size; ++j) {
            scales.push_back(raw_data[j]);
        }
    }

但是在ShapeInterp.cpp文件中把Interp层的第二个入参默认处理为outputWidth和outputHeight：

        if (1 == inputSize) {
            auto interp = op->main_as_Interp();
            // get output dims
            w = interp->outputWidth();
            h = interp->outputHeight();
            if (w == 0 || h == 0) {
                w = input.dim[3].extent * interp->widthScale();
                h = input.dim[2].extent * interp->heightScale();
            }
            output.dim[3].extent = w;
            output.dim[2].extent = h;
        } else {
            // copy data from device to host if needed
            std::shared_ptr<Tensor> tmpShape;
            auto shape = inputs[1]; // input shape(shape)
            if (!shape->host<int32_t>() && shape->deviceId()) {
                tmpShape.reset(Tensor::createHostTensorFromDevice(shape, true));
                shape = tmpShape.get();
            }

            MNN_ASSERT(2 == shape->buffer().dim[0].extent);
            const int32_t* shapeData = shape->host<int32_t>();
            w                        = shapeData[1];
            h                        = shapeData[0];
            output.dim[3].extent     = w;
            output.dim[2].extent     = h;
        }

测试的时候报错如下：
Error for /home/kay/DiskT/TJG/MyProjectGitHub/MNN/source/shape/ShapeInterp.cpp, 50
Resize error for 421, code=3

如下修改代码后能正常跑通

        if (1 == inputSize) {
            auto interp = op->main_as_Interp();
            // get output dims
            w = interp->outputWidth();
            h = interp->outputHeight();
            if (w == 0 || h == 0) {
                w = input.dim[3].extent * interp->widthScale();
                h = input.dim[2].extent * interp->heightScale();
            }
            output.dim[3].extent = w;
            output.dim[2].extent = h;
        } else {
            // copy data from device to host if needed
            std::shared_ptr<Tensor> tmpShape;
            auto shape = inputs[1]; // input shape(shape)
            if (!shape->host<int32_t>() && shape->deviceId()) {
                tmpShape.reset(Tensor::createHostTensorFromDevice(shape, true));
                shape = tmpShape.get();
            }

            // MNN_ASSERT(2 == shape->buffer().dim[0].extent);
            // const int32_t* shapeData = shape->host<int32_t>();
            // w                        = shapeData[1];
            // h                        = shapeData[0];
            // output.dim[3].extent     = w;
            // output.dim[2].extent     = h;

            if(shape->getType().code == 2){
                auto interp = op->main_as_Interp();
                // get output dims
                w = interp->outputWidth();
                h = interp->outputHeight();
                if (w == 0 || h == 0) {
                    w = input.dim[3].extent * interp->widthScale();
                    h = input.dim[2].extent * interp->heightScale();
                }
                output.dim[3].extent = w;
                output.dim[2].extent = h;
            }else{
                printf("shape->buffer().dim[0].extent = %d shape->getType() = %d\n",shape->buffer().dim[0].extent,shape->getType());
                shape->print();
                const int32_t* shapeData = shape->host<int32_t>();
                w                        = shapeData[1];
                h                        = shapeData[0];
                output.dim[3].extent     = w;
                output.dim[2].extent     = h;
            }
        }

**Comment by czy2014hust** [comment]
Please update code, and try again.

**Comment by Kay-Tian** [comment]
> Please update code, and try again.

Thank you for your reply.
I have updated my code and this problem still exist.
I checked the git log and I did not find any commit related to this issue.
It will be nice if you could tell me something more about it.

commit 94cf471eb857fc9acab70683bf42010df18ab677
Merge: 34d0758 d3d12cd
Author: jxt1234 <jxt1234@zju.edu.cn>
Date:   Mon Jul 15 14:29:29 2019 +0800

    Merge pull request #155 from yisongsong/dev/yisongsong/test_quantize
    
    Fix: bug in int8 convolution when dilateX is not equal to dilateY

commit 34d07580c461810e496771a0079921552eb6d795
Merge: 9a1c07f 6adb76e
Author: jxt1234 <jxt1234@zju.edu.cn>
Date:   Mon Jul 15 14:28:56 2019 +0800

    Merge pull request #160 from Howave/develop
    
    fix mnn_bizcode source dir path

commit 6adb76e58be0a72d8f3e05a0a99a31b936f41b2b
Author: Hao Zeng <myhouseng@gmail.com>
Date:   Sun Jul 14 20:36:08 2019 +0800

    fix mnn_bizcode source dir path

commit 9a1c07f9dbb07387b49f4c13bd44c0f05964fbde
Author: 鹿尤 <luyou.cy@alibaba-inc.com>
Date:   Thu Jul 11 16:41:59 2019 +0800

    repo mirror

commit 670d2e5ebb9aca5d92dba88bc9df6683dee8525d
Author: liqing <yiliu.cyl@alibaba-inc.com>
Date:   Thu Jul 11 15:27:01 2019 +0800

    fix schema

commit d3d12cd4755346159523bd068b8c8b260591d2b3
Author: yisongsong <yisongsong@bigo.sg>
Date:   Thu Jul 11 14:09:06 2019 +0800

    Fix: bug in int8 convolution when dilateX is not equal to dilateY

**Comment by czy2014hust** [comment]
The latest commit is @161c655c6b2, Please update code!
