### ISSUE TITLE
模型市场的模型工具 模型转换MNN失败

### ISSUE THREAD

**Issue by 408550969** [alibaba/MNN#1844]
网址是这个：https://market.mnn.zone/s/#/modelmarket/serviceUnits/
IOException: Cannot run program "home/admin/MNN/usr/local/bin/mnnconvert"(in directory "tmp/1644214737233"); error=2,没有那个文件或目录(10010)
无论上传什么都是报这个错

**Comment by RangeLiu** [comment]
> 网址是这个：https://market.mnn.zone/s/#/modelmarket/serviceUnits/ IOException: Cannot run program "home/admin/MNN/usr/local/bin/mnnconvert"(in directory "tmp/1644214737233"); error=2,没有那个文件或目录(10010) 无论上传什么都是报这个错

相同问题，请问楼主解决了没？
