### ISSUE TITLE
MNN使用切片操作后维度变为0

### ISSUE THREAD

**Issue by yjiangling** [alibaba/MNN#1847]
网络中使用了切片操作（例如 y = x[:, :k, :]）后mnn推理出来的tensor维度就会变成0了？

**Comment by yjiangling** [comment]
不好意思，弄错了，output_tensor获取放在了runSession前面，导致打印出来的是内存里随机的数值

**Comment by yjiangling** [comment]
目前版本对于算子 tf.sequence_mask 是不是没有支持？

**Comment by yjiangling** [comment]
@jxt1234 大佬，请教一下，目前不管是直接使用 y = x[:, :k, :] 还是用算子 y = tf.slice(x, [0, 0, 0], [-1, k, -1]) 进行切片操作，mnn推理得到的结果第二维度都是0，怎么回事？

**Comment by yjiangling** [comment]
切片操作的序号 k 不能是tensor？直接使用数值切片不会存在问题，使用tensor去切片得到的维度就会变为0

**Comment by yjiangling** [comment]
@jxt1234 目前发现不支持的算子有： 1. 使用tensor作为index的切片操作（MNN推理后切片维度会变为0）；2. tf.sequence_mask，在transformer模型中使用较多；3. 翻转运算 tf.reverse_sequence

**Comment by frspring** [comment]
2.0.1 使用切片操作会导致cuda backend输出全0
