### ISSUE TITLE
内存占用过大，希望得到一些降低内存的建议

### ISSUE THREAD

**Issue by forwiat** [alibaba/MNN#1849]
目前在android手机上用上了MNN，但是内存占用过大，模型结构已经无法再压缩了，想请教一下代码中如何调整或修改MNN，来降低内存占用（可以牺牲一些计算速度）。十分感谢！

**Comment by yyfcc17** [comment]
模型量化一下

**Comment by forwiat** [comment]
模型已经是最低量化过了

**Comment by forwiat** [comment]
看到矩阵乘使用了Strassen算法，这会多耗费一些内存，我能否在代码中指定不使用Strassen算法呢？

**Comment by forwiat** [comment]
OK，读了源码已经知道该修改哪儿了

**Comment by StrugglingForBetter** [comment]
请问下应该修改源码哪一快？该如何修改才能让内存更低？
