### ISSUE TITLE
mac电脑上ios编译失败

### ISSUE THREAD

**Issue by huangfuts** [alibaba/MNN#1854]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
你好，我手动下载了MNN-master分支代码，编译project/ios/代码时一直失败，其中protobuf==3.19.1，
编译步骤如下：

a）编译project/iOS/
1、下载MNN-master分支代码；
2、cd /path/to/MNN;
3、./schema/generate.sh
4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。
编译错误信息：
error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')

上述步骤参考官方语雀文档：**推理框架iOS编译**章节部分，请问我哪里操作有误？
非常感谢！

**Comment by lipanpan1226** [comment]
我跟你遇到了一样的错误，请问你解决了吗？

**Comment by wangzhaode** [comment]
1. 在Xcode的目录中删除internal文件夹下的代码; 关闭MNN中Debug/Release下的`MNN_INTERNAL_ENABLED`宏选项；
![image](https://user-images.githubusercontent.com/8401806/199173251-ba7c3083-acbd-4cd3-a97c-827217b9f891.png)
![image](https://user-images.githubusercontent.com/8401806/199173352-353c9d4e-b192-4bcb-9702-be965ca0fdb3.png)

2. 重新编译；
