### ISSUE TITLE
Android MNN  runSession线上检测存在crash

### ISSUE THREAD

**Issue by bimonth** [alibaba/MNN#1856]
platform:android
version：1.2.0
crash log:
libMNN 0x7a993837d4  <unknown> /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a99382c30
_ZN3MNN10ThreadPool15enqueueInternalEONSt6__ndk14pairINS1_8functionIFviEEEiEEi /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a993829f0
_ZN3MNN10ThreadPool7enqueueEONSt6__ndk14pairINS1_8functionIFviEEEiEEi /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a9938f648
<unknown> /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a9938f2a0
<unknown> /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a992d46dc
<unknown> /data/user/0/xxx/app_mnn_lib/libMNN.so
libMNN
0x7a992da43c
_ZNK3MNN7Session3runEv /data/user/0/xxx/app_mnn_lib/libMNN.so

请问这个崩溃有人遇到么，怎么解决？

**Comment by wangzhaode** [comment]
这些信息无法定位问题，需要提供更加详细的crashlog
