### ISSUE TITLE
Framework Input ERROR or Not Support This Model Type Now!

### ISSUE THREAD

**Issue by zjykzj** [alibaba/MNN#1864]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

# Github版本:
# Github Version:

Path = MNN-1.2.0.zip
Type = zip
Physical Size = 105706227
Comment = 58545d6ca142682424dfd1eed578a8393b81b76e

# 问题

打算用MNNConverter转换TorchScript模型，参考文档[TorchScript -> MNN](https://www.yuque.com/mnn/cn/model_convert#Rt7QW)

```
$ ./MNNConvert -f TORCH --modelFile model_script.pt --MNNModel model_script.mnn --bizCode biz
Framework Input ERROR or Not Support This Model Type Now!
```

模型model_script.pt也参考了示例代码，就是一个简单的AlexNet

```
import torch
from torchvision.models import alexnet

if __name__ == '__main__':
    model = alexnet()
    model.eval()

    model_trace = torch.jit.trace(model, torch.randn(1, 3, 224, 224))
    model_trace.save("model_trace.pt")

    model_script = torch.jit.script(model)
    model_script.save("model_script.pt")
```

**Comment by zjykzj** [comment]
> 

参考交流群意见，重新编译转换器，添加script支持

```
cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_TORCH=ON && make -j4
```

重新运行，出现了其他错误：

```
$ ./MNNConvert -f TORCH --modelFile model_trace.pt --MNNModel model_trace.mnn --bizCode biz
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[15:07:09] /home/zj/mnn/MNN-1.2.0/tools/converter/source/common/writeFb.cpp:577: These Op Not Support: Torch::_convolution | Torch::linear 
Converted Failed!

$ ./MNNConvert -f TORCH --modelFile model_trace.pt --MNNModel model_trace.mnn --bizCode biz

Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[15:13:45] /home/zj/mnn/MNN-1.2.0/tools/converter/source/common/writeFb.cpp:577: These Op Not Support: Torch::_convolution | Torch::linear 
Converted Failed!
```

**Comment by zjykzj** [comment]
> 

下载最新仓库源码，重新进行编译并开启TORCH支持开关，能够完成AlexNet模型的转换

**Comment by huangfuts** [comment]
你好，看到你提到交流群，请问我如何加入交流群呢？MNN项目里的钉钉二维码都失效了。
非常感谢～～

**Comment by zjykzj** [comment]
> 你好，看到你提到交流群，请问我如何加入交流群呢？MNN项目里的钉钉二维码都失效了。 非常感谢～～

https://github.com/alibaba/MNN#how-to-discuss-and-get-help-from-mnn-community

**Comment by huangfuts** [comment]
> 

这些二维码已经失效了，现在进不去了！！！
iOS运行库你有编译吗？我一直编译失败，能指导一下吗？

编译步骤如下：
我手动下载了MNN-master分支代码，其中protobuf==3.19.1
a）编译project/iOS/
1、下载MNN-master分支代码；
2、cd /path/to/MNN;
3、./schema/generate.sh
4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。
编译错误信息：
error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN')
warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')

上述步骤参考官方语雀文档：推理框架iOS编译章节部分（https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？
非常感谢！

**Comment by yjiangling** [comment]
> > 
> 
> 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> 
> 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> 
> 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！

语雀上这个二维码没有失效 https://www.yuque.com/mnn/cn/feedback

**Comment by huangfuts** [comment]
> > 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> > 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> > 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！
> 
> 语雀上这个二维码没有失效 https://www.yuque.com/mnn/cn/feedback

嗯嗯，二维码没有失效，但是已达群人数上限，不能申请加入了。
看来你是加入的早，我现在加不进去了。。。哎，为啥不再建个群呢！
多谢你啦～～～

**Comment by yjiangling** [comment]
> > > 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> > > 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> > > 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！
> > 
> > 
> > 语雀上这个二维码没有失效 https://www.yuque.com/mnn/cn/feedback
> 
> 嗯嗯，二维码没有失效，但是已达群人数上限，不能申请加入了。 看来你是加入的早，我现在加不进去了。。。哎，为啥不再建个群呢！ 多谢你啦～～～

前面两个群满了，第三个还可以进的

**Comment by huangfuts** [comment]
> > > > 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> > > > 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> > > > 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！
> > > 
> > > 
> > > 语雀上这个二维码没有失效 https://www.yuque.com/mnn/cn/feedback
> > 
> > 
> > 嗯嗯，二维码没有失效，但是已达群人数上限，不能申请加入了。 看来你是加入的早，我现在加不进去了。。。哎，为啥不再建个群呢！ 多谢你啦～～～
> 
> 前面两个群满了，第三个还可以进的

我一直认为第三个二维码只能阿里内部人员才能加入。
已进，感谢🙏

**Comment by lipanpan1226** [comment]
> > 
> 
> 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> 
> 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> 
> 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！

请问你解决了吗， 我遇到了同样的问题。

**Comment by wangzhaode** [comment]
torchscript转换问题已解决；


> 这些二维码已经失效了，现在进不去了！！！ iOS运行库你有编译吗？我一直编译失败，能指导一下吗？
> 
> 编译步骤如下： 我手动下载了MNN-master分支代码，其中protobuf==3.19.1 a）编译project/iOS/ 1、下载MNN-master分支代码； 2、cd /path/to/MNN; 3、./schema/generate.sh 4、在macOS下，用Xcode打开project/iOS/MNN.xcodeproj。 编译错误信息： error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/md5.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN') error: Build input file cannot be found: '/Users/dasouche/Documents/workspace/serverConnect/MNN-master/source/internal/logging/aliyun-log-c-sdk/src/lz4.c' (in target 'MNN' from project 'MNN') warning: Could not read serialized diagnostics file: Cannot Load File: Failed to open diagnostics file (in target 'MNN' from project 'MNN')
> 
> 上述步骤参考官方语雀文档：推理框架iOS编译章节部分（[https://www.yuque.com/mnn/cn/build_ios），请问我哪里操作有误？](https://www.yuque.com/mnn/cn/build_ios%EF%BC%89%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%88%91%E5%93%AA%E9%87%8C%E6%93%8D%E4%BD%9C%E6%9C%89%E8%AF%AF%EF%BC%9F) 非常感谢！

这个问题已在对应issue下回答；
