### ISSUE TITLE
Session Resize: Reshape Error

### ISSUE THREAD

**Issue by pablogsanchez** [alibaba/MNN#1865]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Ubuntu 18.04

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

[Tag 1.2.6
](https://github.com/alibaba/MNN/tree/1.2.6)

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cmake -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_BENCHMARK=ON

When running [Benchmark binary](https://github.com/alibaba/MNN/blob/1.2.6/benchmark/benchmark.cpp) with the model provided in the zip file is crashing when resizing the session (v1.2.6):

```
Reshape error: 2560 -> 1280
Compute Shape Error for fc1_Reshape_Y
```
Crashing in this part of the code. [ShapeReshape.cpp](https://github.com/alibaba/MNN/blob/1.2.6/source/shape/ShapeReshape.cpp#L137)

[Benchmark.cpp ](https://github.com/alibaba/MNN/blob/1.2.6/benchmark/benchmark.cpp)modifications:

```
    // Mainly I do a change of the batch size of the net.
    std::vector<float> costs;
    MNN::Session* session = net->createSession(config);
    //net->releaseModel(); // Must be commented in order to resize the net
    MNN::Tensor* input    = net->getSessionInput(session, NULL);

    auto dims = input->shape();
    dims[0]=2;
    net->resizeTensor(input, dims);
    net->resizeSession(session);
```
**Note**: It is crashing when I convert the model with v1.2.6, but when I convert the model with v1.1.7 It is not crashing.

Network (Netron) Visualization:

![image](https://user-images.githubusercontent.com/79853788/155094765-30c2d80f-58ae-438f-b257-9c18bba45ca7.png)
Marked in red the node that crash when resizing the session.

Model in onnx, model converted in v1.2.6 and v1.1.7:

[model.zip](https://github.com/alibaba/MNN/files/8114949/model.zip)

**Comment by pablogsanchez** [comment]
Thanks in advance guys!!!!!

**Comment by pablogsanchez** [comment]
Note: Also getting this error when quantize the model.

**Comment by huangfuts** [comment]
你好，我也在用这个框架，但是我遇到了iOS编译问题，你可以正常编译iOS运行库吗？方便私下交流一下吗？
我的邮箱：huangfu-ts@zju.edu.cn，非常感谢！！！

**Comment by wangzhaode** [comment]
看样子reshape的`shape`写成固定的了，所以当你设置成`batch=2`时，reshape算子会出错
