### ISSUE TITLE
armv8.2 高通骁龙855 输出结果都是nan

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [alibaba/MNN#1866]
# android

# Github版本:
# Github Version:
1.2.6
编译没有任何问题，如果不开始arm82结果跟tensorflow跑的也是一样的，但是一开启arm82，结果就nan了（其中有反卷积操作，但是没有任何报错或者warning信息）
编译的时候，开启了arm82与fp16.

要是没有记错，早在v1.0的时候，我测试的时候是没有问题的， 请问要怎么解决问题呢？？

**Comment by jiuzhuanzhuan** [comment]
想问下  armv8.2 底层是用fp16计算的么？ 难道是精度不够了？

**Comment by jiuzhuanzhuan** [comment]
[test.zip](https://github.com/alibaba/MNN/files/8175586/test.zip)
大佬们  我把这个问题细分了一下， 发现是在某一层的输出突然就一直是nan。
这是一层3x3的stride是1的简单卷积， 其输出的第18432位开始就是nan了，我打印了这一位置的计算过程，都是很小的数值，不懂为什么bf16会精度不够, 可以帮忙看一下看么？

还有个发现是 我试着 把weight*10 再把input/10之后 就不会出nan值了，但是最后的结果跟tensorflow的输出结果误差就变大了了很多

**Comment by jiuzhuanzhuan** [comment]
还是没有解决这个问题， 只要是相似结构的网络，总是再这一层nan，可以帮忙看一看么？？？？

**Comment by wangzhaode** [comment]
最新版本是否还有这个问题呢
