### ISSUE TITLE
RaspberryPi3/4 benchmarking support? 

### ISSUE THREAD

**Issue by ghimiredhikura** [alibaba/MNN#187]
Hello, 

I am trying to benchamrk several caffe models using this library in RaspberryPi3B+. I was wondering if there is any standard protocol to do so. 
Thanks. 

Best,
Deepak

**Comment by jxt1234** [comment]
use benchmark.out

**Comment by 17759205390** [comment]
> Hello,
> 
> I am trying to benchamrk several caffe models using this library in RaspberryPi3B+. I was wondering if there is any standard protocol to do so.
> Thanks.
> 
> Best,
> Deepak

@ghimiredhikura what is your cmakelist like？can you show me，i am boring for crossing build

**Comment by ghimiredhikura** [comment]
Thanks for the reply guys. I can use benchmark.out. 

However I have some issue converting standard cnn architecture caffemodels into MNN format. I tried with alexnet, vgg16 etc, below is the log information. 

```
~mnn/mnn-0.2.0.3/tools/converter/build # ./MNNConvert -f CAFFE --modelFile vgg16.caffemodel --prototxt vgg16.prototxt --MNNModel test.mnn --bizCode MNN

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [02:32:40] /home/demouser/Desktop/devplatform-rasberrypi3/benchmark/frameworks/mnn/mnn-0.2.0.3/tools/converter/source/caffe/Convolution.cpp:30: Check failed: weightBlob.shape().dim_size() == 4 ==> Conv Weight Dimension ERROR!
Aborted
```

Some help will be greatly appreciated! 
Thanks.
