### ISSUE TITLE
IOS性能问题。 

### ISSUE THREAD

**Issue by zhyf198766** [alibaba/MNN#1870]
我这边用MNN打包的算法SDK,  碰到点问题，模型大概10-20M的浮点量， 用demo测试可能也就1-2MS（iphone 6s），  
但是算法打包SDK给到IOS camera下跑的时候，时间就很不稳定了， 开始是1-2ms,   后面很快就跳到10+ms.

**Comment by jxt1234** [comment]
看下 CPU 频率，另外再检查下是否有内存泄露
