### ISSUE TITLE
python推理，模型双输入，fastTestOnnx显示success，推理的python脚本也不报错，就是结果不对

### ISSUE THREAD

**Issue by lg920810** [alibaba/MNN#1873]
# 平台(如果交叉编译请再附上交叉编译目标平台):  ubuntu18.04
# Github版本:
mnn中的MNNConvert使用的1.20，onnx->mnn正确，且fastTestOnnx运行后也显示success。
python版的MNN先后尝试1.2.0，1.2.2，1.2.6版本进行推理，均正确。使用python setup install和pip install安装都试过。

python推理脚本结构如下：(两个输入分别是(1,3,320,320)和(1,1,320,320))

interpreter = MNN.Interpreter(model_path)
session = interpreter.createSession()

input_tensor1 = interpreter.getSessionInput(session, "input_1")
input_tensor2 = interpreter.getSessionInput(session, "input_2")

interpreter.resizeTensor(input_tensor1, (1, 3, 320, 320))
interpreter.resizeTensor(input_tensor2, (1, 1, 320, 320))
interpreter.resizeSession(session)

output_tensor = interpreter.getSessionOutput(session)

......
input_tensor1.copyFrom(MNN.Tensor((1, 3, 320, 320), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe))
input_tensor2.copyFrom(MNN.Tensor((1, 1, 320, 320), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe))

interpreter.runSession(session)
result = interpreter.getSessionOoutput(session).getData()
.......

目前的问题就是没有任何地方报错，模型是个分割问题，结果输出不对，请教各位大神我应该从哪儿入手排查问题？

**Comment by jxt1234** [comment]
pymnn 重编安装试下，另外 result 部分可能要加一步数据类型转换
