### ISSUE TITLE
iOS 平台Pod 安装1.2.0版本mnn，使用metal报错。

### ISSUE THREAD

**Issue by JKangTan** [alibaba/MNN#1874]
iOS 平台Pod 安装1.2.0版本mnn，使用metal报错。
        MNNMetalTensorContent sharedContent;
        
        MNNMetalGetTensorContent(&sharedContent, _input);
        // For Metal Context to write, don't need finish, just use flush
        _input->wait(MNN::Tensor::MAP_TENSOR_WRITE, false);
        [enc setBuffer:sharedContent.buffer offset:sharedContent.offset atIndex:0];

<img width="999" alt="image" src="https://user-images.githubusercontent.com/11549075/156732843-a6163ee2-cb02-4489-9aa4-fb8db121e805.png">

**Comment by tuyuwang** [comment]
pod 的版本是1.2.0对应tag版本1.2.0，但是demo中的版本其实是tag版本1.2.7

**Comment by wangzhaode** [comment]
试下最新的代码

**Comment by jxt1234** [comment]
最新代码已经修正，有问题重新提 issue
