### ISSUE TITLE
多输入的支持

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#1876]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
ios平台

# Github版本:
1.2.4

遇到一个模型有3个输入inputTensor1， inputTensor2和inputTensor3。
其中inputTensor1是输入图片的tensor，inputTensor2是图片的长，inputTensor3是图片的宽。

对第一个输入tensor的设置：
    MNN::CV::ImageProcess pretreat(MNN::CV::ImageProcess::create(net_config));
    pretreat->setMatrix(trans);
    pretreat->convert((char *)data, width, width, 0, inputTensor1);

对第二个tensor的设置：
    auto temp = new MNN::Tensor(inputTensor2, MNN::Tensor::CAFFE);
    temp->host<float>()[0] = width;
    inputTensor2->copyFromHostTensor(temp);
    delete temp;

对第三个tensor的设置：
    auto temp = new MNN::Tensor(inputTensor3, MNN::Tensor::CAFFE);
    temp->host<float>()[0] = height;
    inputTensor3->copyFromHostTensor(temp);
    delete temp;

请问一下这样设置对吗？如果inputTensor2和inputTensor3里面分别只存储宽和高的话，他们的shape(n,c,h,w)是（1,1,1,1）还是（0,0,0,1)还是（0,0,0,0)。

**Comment by JKangTan** [comment]
你好 问一下gpu跑模型的MNNMetalGetTensorContent(）找不到 你出现了吗

**Comment by jxt1234** [comment]
设置是对的，inputTensor2和inputTensor3里面分别只存储宽和高的话，他们的shape 是 ()，维度数组为空，  不过你这模型有可能出现 Interpreter 不支持的情况（内容决定中间形状），建议参考 demo/exec/transformerDemo.cpp 去运行
