### ISSUE TITLE
图像处理模块MNN::CV是否支持opencv的copyMakeBorder函数？

### ISSUE THREAD

**Issue by zihaog0724** [alibaba/MNN#1877]
opencv里的cv::copyMakeBorder()这个函数，是否支持？
另外，哪里有MNN::CV模块的教程和支持的函数列表呢

**Comment by wangzhaode** [comment]
1. 不支持
2. https://mnn-docs.readthedocs.io/en/latest/inference/python.html#cv

**Comment by yangy996** [comment]
大佬，我需要用到这个方法，可否有平替方案？
