### ISSUE TITLE
how to run MNN in cuda mode?

### ISSUE THREAD

**Issue by twmht** [alibaba/MNN#1879]
I force benchmark to use cuda mode by facing forward to MNN_FORWARD_CUDA in benchmark.cpp (https://github.com/alibaba/MNN/blob/master/benchmark/benchmark.cpp#L129)
 
```c++
forward=MNN_FORWARD_CUDA
net->setSessionMode(MNN::Interpreter::Session_Release);
MNN::ScheduleConfig config;
config.numThread = numberThread;
config.type      = static_cast<MNNForwardType>(forward);
MNN::BackendConfig backendConfig;
```

the bench run works without error but running time is too fast to believe.

![image](https://user-images.githubusercontent.com/1567200/157844825-1aa2cc51-cf52-4e71-ad11-a73300ea047a.png)

the hardware is jetson nano

any idea?

**Comment by jxt1234** [comment]
You can check the result by MNNV2Basic
