### ISSUE TITLE
Quantization keeps reporting error of TensorStatistic.cpp. 

### ISSUE THREAD

**Issue by woodrocky** [alibaba/MNN#188]
I installed the newest version (beta 0.2.0.5). But while running the quantization.exe tool, it keeps showing unterminated error as "Error for MNN/tools/quantization/TenrStatistic.cpp, 46". Anyone knows how to solve it?

**Comment by czy2014hust** [comment]
It will fixed next version.

**Comment by czy2014hust** [comment]
It will fixed next version.

**Comment by czy2014hust** [comment]
It will fixed next version. If you just want to test the performance of the quantized model, ignore this error.

**Comment by czy2014hust** [comment]
fixed
