### ISSUE TITLE
No CUDA compute_53 and sm_53 for Jetson Nano installation any more

### ISSUE THREAD

**Issue by Qengineering** [alibaba/MNN#1882]
Platform(Include target platform as well if cross-compiling):  **_Jetson Nano 4 GB_**

Github Version: **_1.2.7_**

Compiling Method: gcc 7.5.0

As of version 1.2.6 the autodetect of `CUDA_ARCH_FLAGS` is dropped by the `IF (FALSE)` branch at line 5. 
Found at line 44 in `/source/backend/cuda)/CMakeLists.txt` there is now hardcoded 
```cmake
    set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS}
        -gencode arch=compute_70,code=sm_70
        -gencode arch=compute_75,code=sm_75
    )
```

The Jetson Nano needs ` -gencode arch=compute_53,code=sm_53`.
When the gencode 53 and sm 53 are applied, the compilation errors.

With only 70 and 75 the installation runs fine on a Jetson Nano.
However, I'm absolutely not sure if it will be error-less using the wrong CUDA architectural numbers.

**Comment by bitxsw93** [comment]
Please update lastest mnn code, and add sm_53 to cuda cmakelist.txt， retry again. If having any problem, please let me know.

**Comment by Qengineering** [comment]
@bitxsw93,

After the sm_53 modification in cmakelist.txt, the compilation (`make -j4`) runs fine.
However `sudo make install` gives an error.
![Screenshot from 2023-02-25 14-17-39](https://user-images.githubusercontent.com/44409029/221505067-d4e80196-5aeb-441c-9f1f-d432ded89381.png)
