### ISSUE TITLE
android上推理先快后慢

### ISSUE THREAD

**Issue by aisegmentcn** [alibaba/MNN#1886]
我们的一个模型，mnn转换后在android(多款手机)上跑，用cpu。
前20秒左右，推理速度大多数情况是10ms，20秒后大多数情况是20ms，然后后续一直基本稳定在20ms，偶尔会有耗时抖动。
请问这是正常的吗?

**Comment by minushuang** [comment]
> 我们的一个模型，mnn转换后在android(多款手机)上跑，用cpu。 前20秒左右，推理速度大多数情况是10ms，20秒后大多数情况是20ms，然后后续一直基本稳定在20ms，偶尔会有耗时抖动。 请问这是正常的吗?

我也遇到同样的问题，请问您这个问题有解决吗？
