### ISSUE TITLE
Is there some reference doc or code for testing the object dection model?

### ISSUE THREAD

**Issue by Dreamerzzw** [alibaba/MNN#189]
system: linux

I converted the caffe model of MobilenetSSD to MNN, i want to use the converted MNN model for detection, is there some apis can be used for reading the MNN model, outputing the detection result (score & coordinate)?

**Comment by li-qing** [comment]
here is a dump tool to read MNN model: https://github.com/alibaba/MNN/blob/master/tools/converter/README.md

but there is no api for modeling result. use a for loop to read data from the output tensor.
