### ISSUE TITLE
Demo CAN NOT RUN ?!!

### ISSUE THREAD

**Issue by butterluo** [alibaba/MNN#1891]
The Demo CAN NOT RUN  even follow the MNN DOC: https://www.yuque.com/mnn/cn/demo_project, https://www.yuque.com/mnn/cn/model_convert,  https://www.yuque.com/mnn/cn/build_android

I build MNN following https://www.yuque.com/mnn/cn/demo_project, https://www.yuque.com/mnn/cn/model_convert as the build log showing below.

I run Demo following session 2.3 in  https://www.yuque.com/mnn/cn/demo_project using MobileNet: https://github.com/czy2014hust/posenet-python/raw/master/models/model-mobilenet_v1_075.pb which is also shown in the doc page. The input file is MNN_Path/resource/images/TestMe.jpg which is also shown in the doc page.
Demo is ran using command:  build/pictureRecognition.out tf_mblnet.mnn resource/images/TestMe.jpg

BUT it throw an EXCEPTION:
Compute Shape Error for MobilenetV1/add
Session Info: memory use 0.000000 MB, flops is 0.000000 M, backendType is 13, batch size = 1
Resize error, the model can't run batch: 1

# 平台(如果交叉编译请再附上交叉编译目标平台):  linux CentOS 7
# MNN版本: tags/1.2.7

# 编译方式: 
cmake  -DMNN_BUILD_DEMO=ON  -DMNN_BUILD_CONVERTER=ON ..

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
-- The C compiler identification is GNU 8.3.1
-- The CXX compiler identification is GNU 8.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /opt/rh/devtoolset-8/root/usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-8/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-8/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python (found version "3.7.10") 
-- 
-- 3.19.0.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Success
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: x86_64
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16: 
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /vsws/mnn/build
-- WIN_USE_ASM: 
-- x86_64: Open SSE
-- MNN_AVX512:OFF
-- Onnx: 
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /vsws/mnn/build
```

# 编译日志:
Scanning dependencies of target MNNUtils
Scanning dependencies of target MNNAVXFMA
Scanning dependencies of target MNNCV
Scanning dependencies of target MNNCore
Scanning dependencies of target MNNMath
Scanning dependencies of target MNNTransform
Scanning dependencies of target checkDir.out
Scanning dependencies of target MNNDump2Json
Scanning dependencies of target MNNSSE
Scanning dependencies of target MNNX8664
Scanning dependencies of target MNNCompress
Scanning dependencies of target checkFile.out
Scanning dependencies of target MNNRevert2Buffer
Scanning dependencies of target MNNAVX
Scanning dependencies of target libprotobuf-lite
Scanning dependencies of target MNNCPU
Scanning dependencies of target libprotobuf
make[2]: Warning: File `CMakeFiles/checkDir.out.dir/depend.make' has modification time 49 s in the future
make[2]: Warning: File `CMakeFiles/checkFile.out.dir/depend.make' has modification time 49 s in the future
[  1%] Building CXX object CMakeFiles/checkDir.out.dir/tools/cpp/checkDir.cpp.o
[  1%] Building CXX object CMakeFiles/checkFile.out.dir/tools/cpp/checkFile.cpp.o
make[2]: Warning: File `CMakeFiles/MNNMath.dir/depend.make' has modification time 49 s in the future
make[2]: Warning: File `CMakeFiles/MNNUtils.dir/depend.make' has modification time 49 s in the future
[  1%] Building CXX object CMakeFiles/MNNMath.dir/source/math/WingoradGenerater.cpp.o
[  1%] Building CXX object CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o
make[2]: Warning: File `tools/converter/CMakeFiles/MNNDump2Json.dir/depend.make' has modification time 49 s in the future
[  1%] Building CXX object CMakeFiles/MNNUtils.dir/source/utils/InitNet.cpp.o
[  1%] Building CXX object CMakeFiles/MNNUtils.dir/source/utils/JNIHelper.cpp.o
[  1%] Building CXX object tools/converter/CMakeFiles/MNNDump2Json.dir/source/MNNDump2Json.cpp.o
make[2]: Warning: File `CMakeFiles/MNNX8664.dir/depend.make' has modification time 49 s in the future
make[2]: Warning: File `CMakeFiles/MNNCV.dir/depend.make' has modification time 49 s in the future
[  1%] Building CXX object CMakeFiles/MNNX8664.dir/source/backend/cpu/x86_x64/AVX2Backend.cpp.o
[  1%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
[  1%] Building CXX object CMakeFiles/MNNX8664.dir/source/backend/cpu/x86_x64/AVX2Functions.cpp.o
[  2%] Building CXX object CMakeFiles/MNNX8664.dir/source/backend/cpu/x86_x64/cpu_id.cc.o
[  2%] Building CXX object CMakeFiles/MNNX8664.dir/source/backend/cpu/x86_x64/FunctionDispatcher.cpp.o
make[2]: Warning: File `CMakeFiles/MNNAVXFMA.dir/depend.make' has modification time 49 s in the future
[  3%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/Matrix_CV.cpp.o
make[2]: Warning: File `tools/converter/CMakeFiles/MNNRevert2Buffer.dir/depend.make' has modification time 49 s in the future
[  3%] Building CXX object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/GemmSparseFMA.cpp.o
[  3%] Building CXX object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/GemmAVX2FMA.cpp.o
[  3%] Building CXX object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/MathFunctions.cpp.o
make[2]: Warning: File `CMakeFiles/MNNSSE.dir/depend.make' has modification time 49 s in the future
[  4%] Building ASM object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/_AVX_MNNGemmFloatUnitMainFMA.S.o
[  4%] Building CXX object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/PackedFunction.cpp.o
[  4%] Building CXX object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/GemmAVX2FMABF16.cpp.o
[  4%] Building ASM object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/_AVX_MNNGemmFloatUnitMainFMA6x16.S.o
[  4%] Building ASM object CMakeFiles/MNNAVXFMA.dir/source/backend/cpu/x86_x64/avxfma/_AVX_MNNGemmFloatUnitMainFMA_Fused.S.o
make[2]: Warning: File `tools/converter/CMakeFiles/MNNCompress.dir/depend.make' has modification time 49 s in the future
[  6%] Building CXX object tools/converter/CMakeFiles/MNNRevert2Buffer.dir/source/MNNRevert2Buffer.cpp.o
........
Scanning dependencies of target MNNConvertDeps
make[2]: Warning: File `tools/converter/CMakeFiles/MNNConvertDeps.dir/depend.make' has modification time 49 s in the future
[ 95%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/AddSparseInfo.cpp.o
[ 95%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/OpCount.cpp.o
[ 95%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/AddUUID.cpp.o
[ 95%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/Common.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/cli.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/FullQuantAndCoding.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/convertToStaticModel.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/ConverterScope.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/WeightQuantAndCoding.cpp.o
[ 96%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/SaveHalfFloat.cpp.o
[ 97%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/writeFb.cpp.o
[ 97%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/RemoveParams.cpp.o
[ 97%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/source/common/options.cpp.o
[ 97%] Building CXX object tools/converter/CMakeFiles/MNNConvertDeps.dir/__/__/3rd_party/flatbuffers/src/util.cpp.o
[ 97%] Linking CXX executable ModuleBasic.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 97%] Built target ModuleBasic.out
[ 97%] Linking CXX executable mobilenetTest.out
[ 97%] Linking CXX executable pictureRecognition.out
[ 97%] Linking CXX executable segment.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 97%] Built target mobilenetTest.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 97%] Built target pictureRecognition.out
[ 97%] Built target segment.out
[ 98%] Linking CXX executable multithread_imgrecog.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 98%] Built target multithread_imgrecog.out
[ 98%] Linking CXX executable rasterDemo.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 98%] Built target rasterDemo.out
[ 99%] Linking CXX executable pictureRotate.out
[ 99%] Linking CXX executable pictureRecognition_module.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 99%] Built target pictureRecognition_module.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 99%] Built target pictureRotate.out
[ 99%] Linking CXX executable multiPose.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 99%] Built target multiPose.out
[ 99%] Linking CXX executable aoa_nlu_decoder2.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 99%] Built target aoa_nlu_decoder2.out
[ 99%] Linking CXX executable MNNV2Basic.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 99%] Built target MNNV2Basic.out
[100%] Linking CXX executable timeProfile.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target timeProfile.out
[100%] Linking CXX executable aoa_nlu_decoder1.out
[100%] Linking CXX executable aoa_nlu_encoder.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target aoa_nlu_decoder1.out
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target aoa_nlu_encoder.out
[100%] Linking CXX shared library libMNNConvertDeps.so
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target MNNConvertDeps
Scanning dependencies of target TestConvertResult
Scanning dependencies of target MNNConvert
Scanning dependencies of target TestPassManager
make[2]: Warning: File `tools/converter/CMakeFiles/MNNConvert.dir/depend.make' has modification time 49 s in the future
[100%] Building CXX object tools/converter/CMakeFiles/MNNConvert.dir/source/MNNConverter.cpp.o
make[2]: Warning: File `tools/converter/CMakeFiles/TestPassManager.dir/depend.make' has modification time 49 s in the future
make[2]: Warning: File `tools/converter/CMakeFiles/TestConvertResult.dir/depend.make' has modification time 49 s in the future
[100%] Building CXX object tools/converter/CMakeFiles/TestPassManager.dir/source/TestPassManager.cpp.o
[100%] Building CXX object tools/converter/CMakeFiles/TestConvertResult.dir/source/TestConvertResult.cpp.o
[100%] Linking CXX executable ../../MNNConvert
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target MNNConvert
[100%] Linking CXX executable ../../TestConvertResult
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target TestConvertResult
[100%] Linking CXX executable ../../TestPassManager
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[100%] Built target TestPassManager

**Comment by jxt1234** [comment]
The mobilenet model from tf don't has shape, you need resizeTensor -> resizeSession . The demo's model you can get by get_model.sh
