### ISSUE TITLE
onnx模型转fp32mnn可以正常推理，量化后的int8mnn推理时runSession出现Segmentation fault

### ISSUE THREAD

**Issue by zhanggd001** [alibaba/MNN#1894]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
aarch64

# Github版本:
# Github Version:
tag 1.2.7

# 编译方式:
# Compiling Method
aarch64上直接进行的编译

cmake .. \
-DMNN_BUILD_QUANTOOLS=on \
-DMNN_BUILD_CONVERTER=on \

#问题描述
onnx转fp32mnn，模型可以正常推理，返回正确的结果；
相同的代码，发现fpmnn量化到int8mnn后，在mnn_interpreter->createSession(schedule_config)出现Segmentation fault。

量化方式：
{
    "format":"GRAY",
    "mean":[
        0.0
    ],
    "normal":[
        0.00392156863
    ],
    "width":1216,
    "height":1024,
    "path":"/home/gdzhang/mnn/source_quant_images",
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS",
    "feature_clamp_value":127,
    "weight_clamp_value":127,
    "quant_bits":8,
    "input_type":"image",
    "debug":true
}

**Comment by zhanggd18** [comment]
发现量化之后的int8mnn模型，

Weight  type: float32[8,1,3,3]  **Tensor data is empty**.
bias type: float32[8]
[
    0.01459179911762476,
    -0.00009850945207290351,
    0.2169875055551529,
    0.00434713251888752,
    0.3137591481208801,
    -0.0197175070643425,
    0.4109663963317871,
    0.05484956130385399
]

所有的**weight Tensor data is empty**，bias正常

**Comment by jxt1234** [comment]
mnn forward type 是?

**Comment by zhanggd18** [comment]
> mnn forward type 是?
    std::cout << "MNNSegNet::initialize_interpreter : createFromFile ..."  << std::endl;
    mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(mnn_path));
  
    // 3. create session
    std::cout << "MNNSegNet::initialize_interpreter : create session ..."  << std::endl;

    // 选择Backend
    schedule_config.type = MNN_FORWARD_CPU;
    // 线程数
    schedule_config.numThread = 2;
    // 配置相应的Backend
    MNN::BackendConfig backendConfig;

    // Option 2: 如需运行量化模型以运用INT8 SDOT加速，选择普通精度（默认值）
    backendConfig.precision = MNN::BackendConfig::Precision_Low;
    schedule_config.backendConfig = &backendConfig;
    
    mnn_session = mnn_interpreter->createSession(schedule_config);

    // 4. init input tensor
    std::cout << "MNNSegNet::initialize_interpreter : init input tensor ..."  << std::endl;
    input_tensor = mnn_interpreter->getSessionInput(mnn_session, "input");

    // 5. init input dims
    std::cout << "MNNSegNet::initial

**Comment by happyday-lkj** [comment]
> > mnn forward type 是?
> > std::cout << "MNNSegNet::initialize_interpreter : createFromFile ..."  << std::endl;
> > mnn_interpreter = std::shared_ptrMNN::Interpreter(MNN::Interpreter::createFromFile(mnn_path));
> 
> ```
> // 3. create session
> std::cout << "MNNSegNet::initialize_interpreter : create session ..."  << std::endl;
> 
> // 选择Backend
> schedule_config.type = MNN_FORWARD_CPU;
> // 线程数
> schedule_config.numThread = 2;
> // 配置相应的Backend
> MNN::BackendConfig backendConfig;
> 
> // Option 2: 如需运行量化模型以运用INT8 SDOT加速，选择普通精度（默认值）
> backendConfig.precision = MNN::BackendConfig::Precision_Low;
> schedule_config.backendConfig = &backendConfig;
> 
> mnn_session = mnn_interpreter->createSession(schedule_config);
> 
> // 4. init input tensor
> std::cout << "MNNSegNet::initialize_interpreter : init input tensor ..."  << std::endl;
> input_tensor = mnn_interpreter->getSessionInput(mnn_session, "input");
> 
> // 5. init input dims
> std::cout << "MNNSegNet::initial
> ```

请问后来解决了吗？遇到了同样的，创建session时报错 segmentation fault
