### ISSUE TITLE
WebAssembly very slow speed.

### ISSUE THREAD

**Issue by harutyuntagushyan8** [alibaba/MNN#1895]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
WebAssembly

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
export EMSCRIPTEN=$EMSDK/upstream/emscripten
cd $MNN_SOURCES_ROOT
mkdir -p wasm && cd wasm

alias WASM_CMAKE_CMD="cmake ../ \
-DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DMNN_BUILD_SHARED_LIBS=OFF \
-DMNN_BUILD_TOOLS=OFF \
-DMNN_SEP_BUILD=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=$MNN_SOURCES_ROOT/wasm/out"
```

### MNN Wasm build without multithread support

WASM_CMAKE_CMD -DMNN_FORBID_MULTI_THREAD=ON -DMNN_USE_THREAD_POOL=OFF
make -j8 install

### MNN Wasm build with multithread support
Hardcode thread numbers in ThreadPool.
In file `source/backend/cpu/CPUBackend.cpp` change `mThreadNumber = std::min(mThreadNumber, MAX_THREAD_NUMBER);` instruction 
into `mThreadNumber = 4;` in CPURuntime constructor.
Then add -pthread compiler flag to CMakeLists.txt.
For example add it alongside with optimization level `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -pthread")`.

WASM_CMAKE_CMD
make -j8 install

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
All compiles sucessfully for both multithread and without-multithread and runs model on Chrome and Safari.
The main problem is in MNN function runSessionWithCallBack which takes 3 seconds on 6MB model and 8 seconds on Safari(on Safari maybe this is OK because it runs in one thread) but on Android it takes 1 seconds. 3 times slower.
Maybe I miss something essential in build process.
Can you help me?

```
粘贴在这里
Paste log here or pastebin
```

**Comment by wangzhaode** [comment]
我们没有测试过WASM

**Comment by yunshangyue71** [comment]
hello， Is this problem solved？ I have the same problem。你好问题最终解决了吗？我也遇到了这个问题。
