### ISSUE TITLE
支持设备求助

### ISSUE THREAD

**Issue by liyang0112** [alibaba/MNN#1899]
您好，我们团队正在评估使用MNN将模型运行在GPU上，但从贵司提供的文档来看，只看到“Android上提供了OpenCL、Vulkan、OpenGL三套方案，尽可能多地满足设备需求，针对主流GPU（Adreno和Mali）做了深度调优”的表述，问题是，对于不同型号的Mali设备，是否有些支持有些不支持？可以给我发送一个支持的具体设备列表吗？

万分感谢！

**Comment by jxt1234** [comment]
一般而言，设备支持 OpenCL （最好是 1.2及以上）就是支持的
