### ISSUE TITLE
iOS playground assertion failed

### ISSUE THREAD

**Issue by pashanhenlei** [alibaba/MNN#19]
Assertion failed: (TensorUtils::compareTensors(infer(net, GPU), infer(net, CPU), 0.01)), function operator(), file /Users/tudou/Downloads/MNN-master/test/op/QuantizedSoftmaxTest.cpp, line 136.

**Comment by li-qing** [comment]
1. Metal result varies from device to device. On older devices, deviation may be larger.
2. We uses half(float16_t) in shader, which is configurable in MetalDefine.h & MetalDefine.metal.
