### ISSUE TITLE
tflite 不支持RELU operator？

### ISSUE THREAD

**Issue by MirrorYuChen** [alibaba/MNN#190]
>>  ./MNNConvert -f TFLITE --modelFile facedetector_front.tflite --MNNModel model.mnn --bizCode MNN

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [17:35:27] /home/gli-ai/MNN/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ RELU ]
Aborted (core dumped)

**Comment by MirrorYuChen** [comment]
我使用提供的工具转换tflite模型，报错不支持RELU操作，寻求帮助~

**Comment by li-qing** [comment]
当前还未支持。可以尝试从TensorFlow模型转。

**Comment by MirrorYuChen** [comment]
好的，谢谢~
