### ISSUE TITLE
[PythonAPI] MNN 1.2.0

### ISSUE THREAD

**Issue by hoangtnm** [alibaba/MNN#1906]
Hi, as I understand MNN released v1.2.x and I want to try v1.2.0 with python API. However, MNN has just released [v1.1.x on PyPi](https://pypi.org/project/MNN/). It seems that the model exported from ONNX to MNN using MNN v1.2.0 cannot be loaded using python MNN v1.1.4. Does MNN provide any doc for building the wheel for v1.2.x? Thank you

**Comment by yjiangling** [comment]
You can follow this papaer to build whl package with MNN 1.2.x code, I successfully build 1.2.7 version of Python API and install it.
https://blog.csdn.net/weixin_43529394/article/details/124718078
