### ISSUE TITLE
onResize function acquire buffer

### ISSUE THREAD

**Issue by Lanjiejie** [alibaba/MNN#1913]
In `source/backend/cpu/CPUArgMax.cpp`, the onResize function acquire buffer space, but the buffer is then immediately released. The code is that :

```
backend()->onAcquireBuffer(&mInputBuffer, Backend::DYNAMIC);
backend()->onAcquireBuffer(&mOutputBuffer, Backend::DYNAMIC);

// release temp buffer space
backend()->onReleaseBuffer(&mInputBuffer, Backend::DYNAMIC);
backend()->onReleaseBuffer(&mOutputBuffer, Backend::DYNAMIC);
```

I don't quite understand this process, can anyone answer my doubts? Thank you for your time.

**Comment by wangzhaode** [comment]
MNN中使用内存池进行内存分配，这个地方使用内存池中的DYNAMIC类型的内存代表该内存可以被动态复用；
`onAcquireBuffer`表示在执行该OP时需要占用内存，`onReleaseBuffer`表示在OP结束后不在占用内存；
