### ISSUE TITLE
Check failed: creator ==> NOT_SUPPORTED_OP: [ WHILE ]

### ISSUE THREAD

**Issue by Fighthub** [alibaba/MNN#1915]
刚接触MNN，tflite模型转换 出现Check failed: creator ==> NOT_SUPPORTED_OP: [ WHILE ]，怎么解决 谢谢

**Comment by jxt1234** [comment]
tflite 的 While Op 暂不支持，可以转成 tf 的 pb 或者 onnx 再试下
