### ISSUE TITLE
按通道合并Tensor

### ISSUE THREAD

**Issue by miaodd98** [alibaba/MNN#1916]
请问MNN里是否提供类似pytorch的合并tensor的cat函数？
官方文档中的Matrix类操作仅仅是创建一个Matrix对象，并没有向Matrix中进行赋值操作。
官方文档示例：https://www.yuque.com/mnn/cn/input
现在我的需求是读取两张图像，一张为三通道图像，另一张为单通道图像，想要合并成一个四通道Tensor，请问该如何操作能够实现类似于pytorch中的torch.concat((a,b),dim=1)的操作？万分感谢！

**Comment by miaodd98** [comment]
补充：已经尝试过利用ImageProcess中的setMatrix方法将读取的图像转换为Matrix，请问是否有反向方法，将Matrix类型转换为Tensor？

**Comment by jxt1234** [comment]
可参考 MNN 表达式使用，include/MNN/expr/NeuralNetWorkOp.hpp

https://www.yuque.com/mnn/cn/hksf1g
