### ISSUE TITLE
mnn量化模型没有跑ConvInt8

### ISSUE THREAD

**Issue by StrugglingForBetter** [alibaba/MNN#1917]
量化成功了，但是用timeProfile.out.exe测试 发现量化模型根本没有跑ConvInt8, 跑的是没有量化的卷积Convolution，如图片所示
用的是KL量化， 在CPU上跑，量化后的模型可以做推理，但是内存，和速度均没有提升，可能是因为没有跑ConvInt8, 但是不知道是什么原因导致模型没有跑ConvInt8?

测试的指令： timeProfile.out.exe model_quant.mnn 2 0 1x768x512x51

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
win10 x64 CPU

# Github版本:
# Github Version:

commit 344629419f710b39559e616f1af7bb7bd29617db (HEAD -> master, tag: 1.2.7, origin/master, origin/HEAD)

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
目前 ConvInt8 是内部实现量化的，用户不可见。原始模型和量化后模型发一下?

**Comment by StrugglingForBetter** [comment]
> 目前 ConvInt8 是内部实现量化的，用户不可见。原始模型和量化后模型发一下?

您好！方便留下您的钉钉账户吗？或者邮箱也可以，钉钉更加方便一点

**Comment by StrugglingForBetter** [comment]
> 目前 ConvInt8 是内部实现量化的，用户不可见。原始模型和量化后模型发一下?

您好！已经把原始模型和量化后模型发到您的邮箱:[jxt1234@zju.edu.cn],麻烦帮忙看看，谢谢！

**Comment by jxt1234** [comment]
问题已经沟通，卷积已经跑到了量化，但因为 3x3 较多而没有加速，内存没变小是 prelu 不支持的原因，后续按别的 issue 解决。
