### ISSUE TITLE
pymnn import error on macos m1

### ISSUE THREAD

**Issue by chiaitian** [alibaba/MNN#1919]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
macos m1
version 12.3.1

# Github版本:
# Github Version:

``commit id = 344629419f710b39559e616f1af7bb7bd29617db``

# 编译方式:
# Compiling Method

```
cd pymnn/pip_package
python build_deps.py
python setup.py install --version 1.2.0
```

# 编译日志:
# Build Log:
[all_log](https://gist.github.com/chiaitian/76b35a19f735cd175da19da9dd06b7e0)

# import error

When run `python setup.py install --version 1.2.0`, show warnings like `ld: warning: object file (/Users/mad/xdf/MNN/pymnn_build/libMNN.a(CPURNNSequenceGRU.cpp.o)) was built for newer macOS version (12.0) than being linked (11.0)`.
When run `import MNN` in python, shows 
```
>>> import MNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mad/xdf/MNN/pymnn/pip_package/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
ImportError: dlopen(/Users/mad/miniforge3/envs/pytorch-1.11.0/lib/python3.9/site-packages/MNN-1.2.0-py3.9-macosx-11.0-arm64.egg/_mnncengine.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_OBJC_CLASS_$_NSArray'
```

When run `MACOSX_DEPLOYMENT_TARGET=12.0 python setup.py install --version 1.2.0`, no ld warnings.
When run `import MNN` in python, shows 
```
>>> import MNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mad/xdf/MNN/pymnn/pip_package/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
ImportError: dlopen(/Users/mad/miniforge3/envs/pytorch-1.11.0/lib/python3.9/site-packages/MNN-1.1.7-py3.9-macosx-11.0-arm64.egg/_mnncengine.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

I suspect this may because setup.py built with macosx-11.0 but build_deps.py built with macosx-12.0.
And i think the c++ lib and converter are ok, I can converter an onnx model to mnn successfully.

**Comment by chiaitian** [comment]
I found that NSArray was used in metal backend code, so i turned off metal building option, and import MNN was ok.
I guess something was wrong with my machine metal framework.

**Comment by jxt1234** [comment]
Close MNN Metal and then rebuild it

**Comment by jinfagang** [comment]
@jxt1234 I got some import error as well on M1 macos, any idea?

```
/miniforge3/lib/python3.9/site-packages/_tools.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6google8protobuf8internal12MapFieldBaseD2Ev'
```

**Comment by thelou1s** [comment]
@jxt1234 how to Close MNN Metal and then rebuild it?
