### ISSUE TITLE
how to implement solov2 in MNN

### ISSUE THREAD

**Issue by Evoluange** [alibaba/MNN#1920]
Hi~
Thanks your work, I am training solov2 model and want to deploy the model to android.
Do you have the solov2 implementation in MNN ?

**Comment by jxt1234** [comment]
Export your model to TorchScripts / ONNX / TF and then convert to MNN. 
See docs:
https://www.yuque.com/mnn/cn/create_session
https://www.yuque.com/mnn/cn/model_convert
https://www.yuque.com/mnn/cn/tool_test#NUIrw

And Examples:
demo/exec/multiPose.cpp

**Comment by Evoluange** [comment]
你好，模型转换MNN这块没有问题，但是前传C++代码在输入输出部分没能走通
因为solov2模型中不止有图片数据输入还有坐标信息输入，目前没有找到这种多输入的例子，输出部分还有进行一个卷积计算
请问有计划实现一版solov2模型的C++前传调用吗？
