### ISSUE TITLE
在window10 上使用MNN.dll 会在createfrombuffer 处crash

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#1923]
Download .dll and .lib of the mnn_1.1.0 version ， The model will report an error at createfrombuffer on vs2017,  what may be the reason for this error？

**Comment by jxt1234** [comment]
更新代码，重新编译模型转换工具转换模型测试看看?

**Comment by keke444** [comment]
就发现有的模型能正常运行，不会crash，但只更换模型，代码等其他因素都不变，就会在createfrombuffer 处crash，不知道是什么原因？请问跟模型有关系吗？难道是对模型中的一些算子不支持之类的吗？

**Comment by keke444** [comment]
> 更新代码，重新编译模型转换工具转换模型测试看看?
嗯嗯更新之后，可以啦
