### ISSUE TITLE
MNN是否支持动态维度的输入

### ISSUE THREAD

**Issue by Helloworld0214** [alibaba/MNN#1925]
**任务：**
将torch->ONNX->MNN，转换的过程没问题，但是由于torch模型中存在动态输入，导出onnx时
```python
torch.onnx.export(self.net,
                                input_img,
                                onnx_output_path,
                                opset_version=11,
                                input_names=["input"],
                                output_names=["output"],
                                dynamic_axes=dynamic_axes,
                                export_params = True,
                                do_constant_folding = True
                                )
```
**异常：**
在推理阶段会产生
`Can't run session because not resized`
的错误

请问MNN中是否支持动态维度的输入，在[相同的问题](https://github.com/alibaba/MNN/issues/463#issue-524834609)中解决方案为删除动态输入模块，并提出后续加入动态输入，想请问
+ MNN是否支持动态输入？
+ 若不支持，那后续会有计划加入吗？
期待您的回答。

**Comment by jxt1234** [comment]
1. 支持
2. 参考 https://www.yuque.com/mnn/cn/input , resizeTensor -> resizeSession

**Comment by Helloworld0214** [comment]
您好，我已收到您的邮件，尽快给您回复。祝好

**Comment by Helloworld0214** [comment]
我已经使用resizeTensor -> resizeSession对输入维度进行缩放，但在获取输入变量时
```python
input_tensor = interpreter.getSessionInput(session)
```
会出现
`Compute Shape Error for 398/If`的错误，在运行时出现`Can't run session because not resized`的错误
动态输入转ONNX时是否需要特殊设置？
此外，在使用mnn convert时，出现了`The modle has subgraphs, please use MNN::Module to run it`的提醒，不知道是否有关系。
期待您的回复

**Comment by Helloworld0214** [comment]
> 1. 支持
> 2. 参考 https://www.yuque.com/mnn/cn/input , resizeTensor -> resizeSession

我已经使用resizeTensor -> resizeSession对输入维度进行缩放，但在获取输入变量时
```python
input_tensor = interpreter.getSessionInput(session)
```
会出现
`Compute Shape Error for 398/If`的错误，在运行时出现`Can't run session because not resized`的错误
动态输入转ONNX时是否需要特殊设置？
此外，在使用mnn convert时，出现了`The modle has subgraphs, please use MNN::Module to run it`的提醒，不知道是否有关系。
期待您的回复

**Comment by rlczddl** [comment]
遇到了同样的问题,你解决了吗

**Comment by Helloworld0214** [comment]
您好，我已收到您的邮件，尽快给您回复。祝好

**Comment by Ryuk17** [comment]
请问Expr有没有类似resizeTensor的函数？

**Comment by Helloworld0214** [comment]
您好，我已收到您的邮件，尽快给您回复。祝好
