### ISSUE TITLE
多个模型串行推理时如何传递数据

### ISSUE THREAD

**Issue by cvsod** [alibaba/MNN#1928]
在用opencl推理时，有两个数据传递的问题想请教一下：
（1）如果模型a的输出是模型b的输入，我现在是把模型a的输出copyToHostTensor，模型b的输入再copyFromHostTensor， 这样数据传递有点慢，有更加直接在opencl上传递的方法吗？
（2）我用opencl写了一段特征处理的代码，想嵌入到mnn推理的过程中，cl_mem和mnn Tensor(opencl后端)之间如何不通过host传递数据？

非常感谢！

**Comment by jxt1234** [comment]
关于(1) ，有两种方案
A、设置模型 b 的 sessionMode 为 Session_Input_User ，在模型 a 的 session  resize 完成后，把 a 的 output tensor 的 deviceId() 赋值给 模型 b 的 input tensor ，再调模型 b 的 session 去 resizeSession
B、采用 Module API ，VARP 传递过去即可，不会出现内存拷贝

关于(2)，目前 mnn opencl 不支持传入 opencl 上下文，需要修改 mnn 源码

**Comment by cvsod** [comment]
> 关于(1) ，有两种方案 A、设置模型 b 的 sessionMode 为 Session_Input_User ，在模型 a 的 session resize 完成后，把 a 的 output tensor 的 deviceId() 赋值给 模型 b 的 input tensor ，再调模型 b 的 session 去 resizeSession B、采用 Module API ，VARP 传递过去即可，不会出现内存拷贝
> 
> 关于(2)，目前 mnn opencl 不支持传入 opencl 上下文，需要修改 mnn 源码
感谢解答！
请问一下（1）A中的方案，“deviceId() 赋值给 模型 b 的 input tensor” 这步是如何实现的?deviceId()返回值的类型不是tensor类型，好像不能直接赋值

**Comment by jxt1234** [comment]
b->buffer().device = a->buffer().device

**Comment by jxt1234** [comment]
两个 session 需要是同一个 runtime ，参考 https://www.yuque.com/mnn/cn/create_session#xtQLb 共享 runtime 试下
