### ISSUE TITLE
不支持的算子ONNX::Multinomial 

### ISSUE THREAD

**Issue by li2058088** [alibaba/MNN#1930]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux Ubuntu18

# Github版本:
# Github Version:
v1.2.8

tools/converter/source/common/writeFb.cpp:577: These Op Not Support: ONNX::Multinomial

**Comment by jxt1234** [comment]
收到，我们看一下
