### ISSUE TITLE
怎么实现MNN输入为（8,3,224,224）的推理？

### ISSUE THREAD

**Issue by FinnSu** [alibaba/MNN#1932]
你好，我想确认下MNN的输入的dims设置为{8,3,224,224}可以正常推理吗？

       // mConfig.saveTensors;
        mSession = mNetInstance.createSession(mConfig);

        // get input tensor
        mInputTensor = mSession.getInput(null);

        int[] dimensions = mInputTensor.getDimensions();
        dimensions[0] = 8; // force batch = 8  NCHW  [batch, channels, height, width]
        mInputTensor.reshape(dimensions);
        mSession.reshape();

        mLockUIRender.set(false);
        ......

        MNNImageProcess.convertBuffer(data, imageWidth, imageHeight, mInputTensor, config, matrix);

如果可以推理的话是将8个图片的数据放到data中再进行getOutput的调用吗？
不确认以上处理是否正确，麻烦有经验的同学可以告知一下，提前谢谢了~

**Comment by jxt1234** [comment]
session 部分代码没有问题，但 Python 的 MNNImageProcess 暂不支持 batch > 1 的处理，需要用其他库
