### ISSUE TITLE
iOS SDK在iPhone6Plus上运行Metal异常。

### ISSUE THREAD

**Issue by xiaowei4895** [alibaba/MNN#1934]
iOS 平台，Github 1.2.8版本代码，使用project/ios/mnn.xcodeproj编译。运行手机iPhone6Plus iOS 12.5.5系统。

在MetalConvolutionGEMM.mm里面，[context pipelineWithName:@"matmul4x4"]这一行系统会报错：
[METAL] create pipeline error: Function matmul4x4 is using language version 2.2 which is incompatible with this OS.

从而导致创建出来mPipelineGEMM为空，但是后续代码并未对mPipelineGEMM为空进行处理，引发后续再调用getGridAndThreadgroup里[encoder setComputePipelineState:pipeline] 这一行时，触发系统assert：
-[MTLDebugComputeCommandEncoder setComputePipelineState:]:282: failed assertion `computePipelineState must not be nil.'

**Comment by jxt1234** [comment]
后续会把 metal source 移到在线编译，应该可以解决

**Comment by jxt1234** [comment]
更新到 2.0.3 及以上，如果还有问题再提 issue
