### ISSUE TITLE
OpenCL环境下的测试MNNV2Basic.out，内存会一直增加然后崩溃

### ISSUE THREAD

**Issue by heartXXkiller** [alibaba/MNN#1935]
# 平台(如果交叉编译请再附上交叉编译目标平台):  全志MR813
Linux version 4.9.191 (lsf@ubuntu) (gcc version 6.4.1 (OpenWrt/Linaro GCC 6.4-2017.11 2017-11) )
# Github版本: 1.2.1
# GPU GE8300

```
./MNNV2Basic.out voc544.mnn 1 0 3
voc544.mnn来自Model Zoom  https://github.com/apxlwl/MNN-yolov3
```
补充
通过打断点
MNNV2Basic.out测试卡在interpreter.cc的函数
Session* Interpreter::createMultiPathSession(const std::vector<ScheduleConfig>& configs, const RuntimeInfo& runtime)
进入判断
if (validForResize && mNet->inputMode == Session_Input_Inside) {
        result->resize(mNet->net->usage() == Usage_INFERENCE_STATIC);
}
然后再也没出来，内存一直在增长，直到崩溃
再往下走是resize()函数中
if (mNeedMalloc) {
        // Set needResize = true for easy for judge in runSession when error
        mNeedResize = true;
        // Turn Pipeline to Command Buffer and Malloc resource
        // TODO: Seperate Schedule and Malloc
        for (auto &iter : mPipelines) {
            auto error = iter->allocMemory();
            if (NO_ERROR != error) {
                return error;
            }
        }
        MNN_PRINT("[Debug] For Runtime\n");
        for (auto &iter : mRuntime.first) {
            iter.second->onGabageCollect(0);
        }
        mNeedMalloc = false;
        mNeedResize = false;
    }
内存申请
在mPipelines遍历申请内存时，卡在第一个内存申请
auto error = iter->allocMemory();

通过对匿名函数打断点
auto allocFunction = [&](const std::vector<Tensor*>& tensors) {
            MNN_PRINT("[Debug] Lamda start for tensors size is %d\n", tensors.size());
            for (auto t : tensors) {
                auto des = TensorUtils::getDescribe(t);
                if (des->memoryType == Tensor::InsideDescribe::MEMORY_VIRTUAL) {
                    // Raster's inputs
                    MNN_PRINT("[Debug] Judge memoryType is MEMORY_VIRTUAL\n");
                    for (auto &r : des->regions) {
                        MNN_PRINT("[Debug] For Start _allocTensor\n");
                        auto allocRes = _allocTensor(r.origin, curBackend);
                        if (!allocRes) {
                            return OUT_OF_MEMORY;
                        }
                    }
                } else {
                    MNN_PRINT("[Debug] Judge memoryType is not MEMORY_VIRTUAL\n");
                    MNN_PRINT("[Debug] Start _allocTensor\n");
                    auto allocRes = _allocTensor(t, curBackend);
                    if (!allocRes) {
                        return OUT_OF_MEMORY;
                    }
                }
            }
            return NO_ERROR;
        };
每次为一个op申请内存时，内存一直增加，且不释放
![1](https://user-images.githubusercontent.com/35839319/172564227-fcc4174a-0951-4f49-ae63-04c47acac9c9.png)
最后是
static bool _allocTensor(Tensor* t, Backend* curBackend)
static void _releaseTensor(Tensor* origin, bool mAllocInput)
这两个函数在主导
更具体是
bn->onReleaseBuffer(origin, Backend::DYNAMIC);
auto res     = curBackend->onAcquireBuffer(t, memoryType);

后续
定位到Pipeline.cpp中函数调用
auto code = mExecutions[i]->onResize(iter.inputs, iter.outputs);
会导致GPU在使用的同时，CPU快速增加15MB左右

**Comment by heartXXkiller** [comment]
有，目前升级到2.0.0，依旧会出现上述现象

**Comment by wangzhaode** [comment]
是否方便提供一下您的测试模型

**Comment by luowei0701** [comment]
这个问题解决了么
