### ISSUE TITLE
win10编译converter报错

### ISSUE THREAD

**Issue by xiaoyu1004** [alibaba/MNN#1936]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  win10

# Github版本:
# Github Version: master

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
ninjia
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
"MNN_BUILD_CONVERTER": "ON",
"MNN_FORBID_MULTI_THREAD": "ON"

# 编译日志:
# Build Log:
[build] [390/394  98% :: 292.128] Building CXX object tools\converter\CMakeFiles\MNNConverterONNX.dir\source\onnx\SequenceOnnx.cpp.obj
[build] [391/394  99% :: 299.487] Linking CXX shared library MNNConvertDeps.dll
[build] FAILED: MNNConvertDeps.dll tools/converter/MNNConvertDeps.lib 
[build] cmd.exe /C "cd . && C:\softwares\VisualStudio\VS2019\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe -E vs_link_dll --intdir=tools\converter\CMakeFiles\MNNConvertDeps.dir --rc=C:\WINDOW~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\WINDOW~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\softwares\VisualStudio\VS2019\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\MNNConvertDeps.rsp  /out:MNNConvertDeps.dll /implib:tools\converter\MNNConvertDeps.lib /pdb:MNNConvertDeps.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL  && cd ."
[build] LINK Pass 1: command "C:\softwares\VisualStudio\VS2019\VC\Tools\MSVC\14.28.29910\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\MNNConvertDeps.rsp /out:MNNConvertDeps.dll /implib:tools\converter\MNNConvertDeps.lib /pdb:MNNConvertDeps.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:tools\converter\CMakeFiles\MNNConvertDeps.dir/intermediate.manifest tools\converter\CMakeFiles\MNNConvertDeps.dir/manifest.res" failed (exit code 1120) with the following output:
[build] MNN.lib(MNN.dll) : error LNK2005: "public: __cdecl MNN::Express::VARP::VARP(void)" (??0VARP@Express@MNN@@QEAA@XZ) already defined in GenerateSubGraph.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: __cdecl MNN::Express::VARP::~VARP(void)" (??1VARP@Express@MNN@@QEAA@XZ) already defined in GenerateSubGraph.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: __cdecl MNN::Express::VARP::VARP(class MNN::Express::VARP const &)" (??0VARP@Express@MNN@@QEAA@AEBV012@@Z) already defined in GenerateSubGraph.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: class MNN::Express::VARP & __cdecl MNN::Express::VARP::operator=(class MNN::Express::VARP const &)" (??4VARP@Express@MNN@@QEAAAEAV012@AEBV012@@Z) already defined in PostConverter.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: class MNN::Express::Variable * __cdecl MNN::Express::VARP::operator->(void)const " (??CVARP@Express@MNN@@QEBAPEAVVariable@12@XZ) already defined in GenerateSubGraph.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: struct halide_buffer_t & __cdecl MNN::Tensor::buffer(void)" (?buffer@Tensor@MNN@@QEAAAEAUhalide_buffer_t@@XZ) already defined in InitNet.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: struct halide_type_t __cdecl MNN::Tensor::getType(void)const " (?getType@Tensor@MNN@@QEBA?AUhalide_type_t@@XZ) already defined in InitNet.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: int __cdecl MNN::Tensor::dimensions(void)const " (?dimensions@Tensor@MNN@@QEBAHXZ) already defined in InitNet.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "public: int __cdecl MNN::Tensor::elementSize(void)const " (?elementSize@Tensor@MNN@@QEBAHXZ) already defined in InitNet.cpp.obj
[build] MNN.lib(MNN.dll) : error LNK2005: "bool __cdecl MNN::initConstTensors(class std::vector<class std::shared_ptr<class MNN::Tensor>,class std::allocator<class std::shared_ptr<class MNN::Tensor> > > &,struct MNN::Net const *,class MNN::Backend *,enum MNN::ErrorCode &)" (?initConstTensors@MNN@@YA_NAEAV?$vector@V?$shared_ptr@VTensor@MNN@@@std@@V?$allocator@V?$shared_ptr@VTensor@MNN@@@std@@@2@@std@@PEBUNet@1@PEAVBackend@1@AEAW4ErrorCode@1@@Z) already defined in InitNet.cpp.obj
[build] libprotobufd.lib(libprotobufd.dll) : error LNK2005: "protected: int __cdecl google::protobuf::internal::RepeatedPtrFieldBase::size(void)const " (?size@RepeatedPtrFieldBase@internal@protobuf@google@@IEBAHXZ) already defined in PipelineBuilder.cpp.obj
[build] libprotobufd.lib(libprotobufd.dll) : error LNK2005: "protected: void * const * __cdecl google::protobuf::internal::RepeatedPtrFieldBase::raw_data(void)const " (?raw_data@RepeatedPtrFieldBase@internal@protobuf@google@@IEBAPEBQEAXXZ) already defined in PipelineBuilder.cpp.obj
[build] libprotobufd.lib(libprotobufd.dll) : error LNK2005: "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl google::protobuf::internal::ArenaStringPtr::Get(void)const " (?Get@ArenaStringPtr@internal@protobuf@google@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) already defined in PipelineBuilder.cpp.obj
[build] libprotobufd.lib(libprotobufd.dll) : error LNK2005: "protected: class google::protobuf::Arena * __cdecl google::protobuf::MessageLite::GetOwningArena(void)const " (?GetOwningArena@MessageLite@protobuf@google@@IEBAPEAVArena@23@XZ) already defined in TfModelOptimizer.cpp.obj
[build]    Creating library tools\converter\MNNConvertDeps.lib and object tools\converter\MNNConvertDeps.exp
[build] LINK : warning LNK4217: symbol '?get@OpCount@MNN@@SAPEAV12@XZ (public: static class MNN::OpCount * __cdecl MNN::OpCount::get(void))' defined in 'OpCount.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::initializeMNNConvertArgs(class modelConfig &,int,char * *)" (?initializeMNNConvertArgs@Cli@MNN@@SA_NAEAVmodelConfig@@HPEAPEAD@Z)'
[build] LINK : warning LNK4217: symbol '?getMap@OpCount@MNN@@QEAAAEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@std@@XZ (public: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > const & __cdecl MNN::OpCount::getMap(void))' defined in 'OpCount.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::initializeMNNConvertArgs(class modelConfig &,int,char * *)" (?initializeMNNConvertArgs@Cli@MNN@@SA_NAEAVmodelConfig@@HPEAPEAD@Z)'
[build] LINK : warning LNK4217: symbol '?optimizeNet@@YA?AV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@std@@AEAV12@_NAEAVmodelConfig@@@Z (class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > __cdecl optimizeNet(class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &,bool,class modelConfig &))' defined in 'PostConverter.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?addBizCode@@YAHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@2@@Z (int __cdecl addBizCode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &))' defined in 'addBizCode.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?caffe2MNNNet@@YAHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00AEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@2@@Z (int __cdecl caffe2MNNNet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &))' defined in 'caffeConverter.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?tflite2MNNNet@@YAHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@2@@Z (int __cdecl tflite2MNNNet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &))' defined in 'liteConverter.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?onnx2MNNNet@@YAHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@2@@Z (int __cdecl onnx2MNNNet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &))' defined in 'onnxConverter.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?tensorflow2MNNNet@@YAHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@2@@Z (int __cdecl tensorflow2MNNNet(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &))' defined in 'tensorflowConverter.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] LINK : warning LNK4217: symbol '?writeFb@@YAHAEAV?$unique_ptr@UNetT@MNN@@U?$default_delete@UNetT@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@AEBVmodelConfig@@@Z (int __cdecl writeFb(class std::unique_ptr<struct MNN::NetT,struct std::default_delete<struct MNN::NetT> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class modelConfig const &))' defined in 'writeFb.cpp.obj' is imported by 'cli.cpp.obj' in function '"public: static bool __cdecl MNN::Cli::convertModel(class modelConfig &)" (?convertModel@Cli@MNN@@SA_NAEAVmodelConfig@@@Z)'
[build] tensor_shape.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] onnx.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] caffe.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] node_def.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] op_def.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] resource_handle.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] tensor.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] TfUtils.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] tfOpConverter.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] attr_value.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] function.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] PadTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] Pooling3DTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] PoolingTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] ReduceJoinTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] MNN_compression.pb.cc.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] AsStringTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] CropAndResizeTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] DequantizeTf.cpp.obj : error LNK2001: unresolved external symbol "class google::protobuf::internal::ExplicitlyConstructed<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3V?$ExplicitlyConstructed@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@123@A)
[build] TfUtils.cpp.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
[build] OnnxUtils.cpp.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
[build] CaffeUtils.cpp.obj : error LNK2001: unresolved external symbol "private: static int google::protobuf::io::CodedInputStream::default_recursion_limit_" (?default_recursion_limit_@CodedInputStream@io@protobuf@google@@0HA)
[build] attr_value.pb.cc.obj : error LNK2001: unresolved external symbol "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlobalEmptyTable@internal@protobuf@google@@3QBQEAXB)
[build] function.pb.cc.obj : error LNK2001: unresolved external symbol "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlobalEmptyTable@internal@protobuf@google@@3QBQEAXB)
[build] node_def.pb.cc.obj : error LNK2001: unresolved external symbol "void * const * const google::protobuf::internal::kGlobalEmptyTable" (?kGlobalEmptyTable@internal@protobuf@google@@3QBQEAXB)
[build] attr_value.pb.cc.obj : error LNK2001: unresolved external symbol "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)
[build] function.pb.cc.obj : error LNK2001: unresolved external symbol "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)
[build] node_def.pb.cc.obj : error LNK2001: unresolved external symbol "private: static char const * const * const google::protobuf::FieldDescriptor::kCppTypeToName" (?kCppTypeToName@FieldDescriptor@protobuf@google@@0QBQEBDB)
[build] MNNConvertDeps.dll : fatal error LNK1120: 4 unresolved externals
[build] ninja: build stopped: subcommand failed.
```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
更新 mnn 并清除 build 目录再试下吧，vs2017 测试了当前版本 2.0.0 是可以的
