### ISSUE TITLE
官网案例2.1姿态检测 demo/exec/multiPose.cpp + OpenCL程序5-10min后才能退出

### ISSUE THREAD

**Issue by JingliangGao** [alibaba/MNN#1940]
版本、环境信息：
   1）MNN 版本：最新版本
   2）Host 环境：Ubuntu 18.04
   3）边缘设备环境：aarch64 + Ubuntu 20.04 + OpenCL3.0

模型信息
   1）模型名称 ：model-mobilenet_v1_075.pb
   2）模型链接 ：https://github.com/czy2014hust/posenet-python/raw/master/models/model-mobilenet_v1_075.pb

复现信息：./buildOpenCL/multiPose.out model/mobilenetV1.mnn image/4.jpg result/mmpose/output4.jpg

问题描述：
       在运行官网案例2.1 姿态估计时（链接: https://www.yuque.com/mnn/cn/demo_project），发现程序难以退出的问题，示意图如下所示。
<img width="349" alt="b2a3fedb10ce7ba59f351aaa41f16da" src="https://user-images.githubusercontent.com/32430057/170903529-69237d85-e2de-4bfe-94e4-0f0c65ebc8e1.png">

        通过在程序中添加一些信息进行输出打印，发现是析构函数~OpenCLRuntime（）中mContext.reset（）执行极为缓慢，详情见下图。
<img width="452" alt="c4ee886d6f48dedf055c75bac9a843e" src="https://user-images.githubusercontent.com/32430057/170903876-97b054fe-32d9-48da-945d-b0bf7bbcb509.png">

**Comment by jxt1234** [comment]
numberthread 设成 1 试下

**Comment by JingliangGao** [comment]
> 

您好，经过测试，numberthread 设成 1 能够正常退出。那我若需要OpenCL分配多个线程运行程序，应该在程序中做怎样的修改呢？

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/create_session#Wi4on ，这里面的 numberThread 其实对应 opencl 的不做 autotuning ，并不是设线程数

**Comment by JingliangGao** [comment]
亲，问题还没解决呢。为什么close issure呢？

**Comment by JingliangGao** [comment]
我注释掉了config.numThread = 1并更换为
config.mode = MNN_GPU_TUNING_NORMAL | MNN_GPU_MEMORY_IMAGE;
仍然退出，十分缓慢（耗时3-6min）
