### ISSUE TITLE
Python离线量化工具使用报错和部分算子在CUDA后端没有实现

### ISSUE THREAD

**Issue by yjiangling** [alibaba/MNN#1941]
1. 编译生成的离线量化工具主要用于对图像处理的模型进行量化，而非图像或多输入、输出模型量化需借助于Python离线量化工具----mnn_offline_quant.py，但是关于这个工具的说明非常少，实际测试问题比较多。即使在 fastTestTf.py 和测试工具 ModuleBasic.out 验证完全没有问题的情况下，使用该离线量化工具量化也会报错，验证发现是因为在量化时加载模型 net = nn.load_module(inputs, outputs, for_training=True)  需要将for_training参数设置为TRUE，而后面的推理就会报错。希望可以对该量化工具做一些优化更新；

2. 针对TensorFlow模型中部分算子，目前CPU实现较好，基本上常用的算子都已经实现了覆盖，但是有一些算子在CUDA后端没有实现，例如Range和MatrixBandPart，期待后续能在CUDA后端实现。

**Comment by yjiangling** [comment]
![image](https://user-images.githubusercontent.com/42861880/170969919-4903ee4b-557b-484e-bd5e-25352da30db6.png)

使用Python离线量化工具只看到这个报错

**Comment by jxt1234** [comment]
呃，这两个并不是小问题，我们后续会完善

**Comment by yjiangling** [comment]
> 呃，这两个并不是小问题，我们后续会完善

好吧，感谢大神回复~
