### ISSUE TITLE
官网案例2.1姿态检测 demo/exec/multiPose.cpp + OpenCL程序5-10min后才能退出（请不要随便close问题，谢谢~）

### ISSUE THREAD

**Issue by JingliangGao** [alibaba/MNN#1944]
版本、环境信息：
1）MNN 版本：最新版本
2）Host 环境：Ubuntu 18.04
3）边缘设备环境：aarch64 + Ubuntu 20.04 + OpenCL3.0

模型信息
1）模型名称 ：model-mobilenet_v1_075.pb
2）模型链接 ：https://github.com/czy2014hust/posenet-python/raw/master/models/model-mobilenet_v1_075.pb

复现信息：./buildOpenCL/multiPose.out model/mobilenetV1.mnn image/4.jpg result/mmpose/output4.jpg

问题描述：
在运行官网案例2.1 姿态估计时（链接: https://www.yuque.com/mnn/cn/demo_project），发现程序难以退出的问题，示意图如下所示。
<img width="349" alt="aaaa" src="https://user-images.githubusercontent.com/32430057/171354771-15b2d97e-d0c3-4dea-a6c6-12a19ff78cf6.png">

        在程序中添加一些信息进行输出打印，发现是析构函数~OpenCLRuntime（）中mContext.reset（）执行极为缓慢，详情见下图。

<img width="452" alt="bbbb" src="https://user-images.githubusercontent.com/32430057/171354873-477315f1-4745-4393-9e00-834ffd3064c4.png">

解决状态（未完全解决）：
         根据[jxt1234](https://github.com/jxt1234)给的建议，numberthread 设成 1 能够正常退出（即不做autotuning）。如果我需要autotuning并设置config.mode = MNN_GPU_TUNING_NORMAL | MNN_GPU_MEMORY_IMAGE仍然退出十分缓慢（耗时5-10min），如上图所示。所以autotuning还是有问题的。

关于交流群：
         Group #3: https://h5.dingtalk.com/circle/healthCheckin.html?dtaction=os&corpId=ding2c1d5c85a81030b9a483726330e8af54&574b2bb2-c53a-4=497bad6b-25a5-4&cbdbhh=qwertyuiop。

这个链接点击后，根本输入不了手机号码所以也加不了群。

**Comment by jxt1234** [comment]
这个链接在手机上点击即可，之前已经回复过，这个主要是设备上 Tuning 较慢，导致结束程序后等 tuning 完成
