### ISSUE TITLE
tflite模型转换mnn出现错误

### ISSUE THREAD

**Issue by litong123** [alibaba/MNN#1945]
pc上Linux平台
# Github Version: commit b9bfa2342f3b84fc141c65e8c058e496bbe9a885

使用cmake进行编译，在使用tflite模型转换的时候：
./MNNConvert -f TFLITE --modelFile testmodel/up1.tflite --MNNModel up1.mnn --bizCode biz 
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Error for compute convolution shape, inputCount:1, group:1, inputChannel: 0, batch:1, width:1, height:128. Input data channel may be mismatch with filter channel count
inputTensors : [ input_1, ]
outputTensors: [ Identity, ]
Converted Success!
显示可以转换成功，但有一个error

使用fastTestTflite.py进行验证的时候
python ../tools/script/fastTestTflite.py testmodel/up1.tflite 

出现结果：
tflite/test.tflite
['Identity']
inputs:
input_1
outputs:
tflite/Identity.txt
Test tflite
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Error for compute convolution shape, inputCount:1, group:1, inputChannel: 0, batch:1, width:1, height:128. Input data channel may be mismatch with filter channel count
inputTensors : [ input_1, ]
outputTensors: [ Identity, ]
Converted Success!
input_1
output: Identity
Identity: (1, 128, 1, )
TESTERROR Identity value error : absMaxV:2.556030 - DiffMax 3.441303
expected value
shape: {1, 128, 1}
0 th:shape: {128}
{0.985155, 1.147877, 1.001436, 0.348921, 1.087415, 0.332316, 1.254972, 0.825057, 1.094458, 0.829349, 1.617669, 1.195132, 0.933825, 1.195127, 0.908209, 1.238761, 1.047074, 1.276031, 1.346346, 1.543416, 1.388107, 0.801074, 0.839457, 1.267357, 1.408390, 1.568365, 1.414535, 1.176834, 1.378158, 1.184018, 1.066503, 1.434020, 0.766617, 1.253147, 1.315156, 0.818915, 0.886835, 0.951404, 1.102128, 1.140138, 0.538220, 0.602932, 0.334479, 0.145517, 0.534243, 0.735703, -0.537939, -0.413615, 0.084055, -0.042551, -0.000337, 0.197459, -0.468329, 0.190567, -0.723322, -0.143824, -0.411301, -0.179192, -0.276612, 0.340919, -0.157234, -0.361129, 0.369151, 0.030237, 0.569268, 0.371905, 0.599583, 0.680822, 0.617365, 0.675943, 0.675250, 0.750301, 0.362520, -0.015884, 0.073393, 0.404813, 0.850864, 0.393226, 0.227908, 1.007274, 0.771150, 0.842151, 0.919452, 0.441880, 0.141725, 0.943159, 0.426888, 0.545222, 0.004149, 0.617010, 0.434152, 0.723294, 0.380849, 0.182751, 1.016795, 0.794903, 0.018800, 0.497490, 0.572814, 1.119671, 0.534606, 0.848361, 1.122570, 1.173567, 0.760483, 0.953370, 1.231548, 0.638876, 0.647254, 1.237747, 0.865935, 0.884618, 1.148234, 0.989697, 0.640669, 0.408167, 1.119684, 0.460630, 1.098088, 0.758937, 0.882758, 1.307995, -0.773172, -0.578489, -1.866161, -2.225713, -2.556030, -2.136438, }
real value
shape: {1, 128, 1}
0 th:shape: {128}
{1.367163, 1.529884, 1.914786, 1.262272, 1.874154, 1.119055, 1.453025, 1.023109, 1.354427, 1.089318, 1.877618, 1.455081, 1.416443, 1.677745, 1.407089, 1.737641, 1.327441, 1.556398, 1.670169, 1.867239, 1.628184, 1.041150, 1.067024, 1.494924, 1.656775, 1.816750, 1.744888, 1.507187, 1.911671, 1.717531, 1.756928, 2.124445, 1.407681, 1.894210, 1.996001, 1.499760, 1.533886, 1.598456, 1.898274, 1.936285, 1.150373, 1.215085, 1.136599, 0.947636, 1.842423, 2.043883, 1.120525, 1.244849, 1.692821, 1.566216, 1.678385, 1.876180, 1.187089, 1.845985, 0.970014, 1.549511, 1.202871, 1.434980, 1.287711, 1.905243, 1.457556, 1.253661, 1.888573, 1.549659, 1.875393, 1.678030, 1.787817, 1.869056, 1.731961, 1.790539, 1.648807, 1.723857, 1.272495, 0.894091, 0.990910, 1.322330, 2.050442, 1.592803, 1.401356, 2.180722, 1.648134, 1.719135, 1.726120, 1.248548, 0.757944, 1.559378, 1.051189, 1.169523, 1.003504, 1.616366, 1.540030, 1.829172, 1.644769, 1.446670, 2.204589, 1.982696, 0.883705, 1.362395, 1.274544, 1.821401, 1.227813, 1.541569, 1.698375, 1.749372, -0.863993, -0.671106, -0.500117, -1.092789, 0.635192, 1.225685, 0.738560, 0.757243, 1.651486, 1.492949, 1.234756, 1.002254, 1.674565, 1.015511, 1.372321, 1.033170, -2.558545, -2.133308, -2.530203, -2.335521, -0.230817, -0.590370, -0.148939, 0.270653, }
Error for output Identity
Save mnn result to  .error director

后续验证转换后的模型发现输出结果和tflite输出结果不一致，应该就是模型转换时候存在错误导致的吧？请问转换时的问题是什么原因，怎么解决呢？

**Comment by jxt1234** [comment]
tflite 模型发一下看看?

**Comment by litong123** [comment]
模型已经发送到您的邮箱，标题为 关于MNN中issue #1945的tflite模型 ，请查收下，谢谢！

**Comment by jxt1234** [comment]
已收到，我们排查一下

**Comment by jxt1234** [comment]
最新代码已经修正 ： 9a1405b6..8ba6a540 ，麻烦验证一下

**Comment by jxt1234** [comment]
不是转换错误，是运行时ExpandDims没考虑 axis < -1 的情况

**Comment by litong123** [comment]
更新代码后已解决，谢谢！
