### ISSUE TITLE
Convert model meet reshape error but Converted Sucess

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#1946]
使用MNNConvert转模型时，遇到reshape error，但是最后报Converted Success，请问这是转成功还是失败了？
![image](https://user-images.githubusercontent.com/22525811/171547382-26ccfb6d-c099-453a-8985-f1e504bbfe07.png)

**Comment by Ryuk17** [comment]
转换失败，运行时报错
![image](https://user-images.githubusercontent.com/22525811/171575241-2c2d629c-ed34-4683-a130-05153effa378.png)

**Comment by jxt1234** [comment]
参考 https://www.yuque.com/mnn/cn/model_convert#nxImR 进行正确性校验

**Comment by Ryuk17** [comment]
正确性校验成功，但create session时报Reshape error.
![image](https://user-images.githubusercontent.com/22525811/172320618-d2cfe98e-a9cc-46b6-9bc6-735eba8337c3.png)
![image](https://user-images.githubusercontent.com/22525811/172320676-fb0327fd-ae7b-40ba-b1f5-fbd544aad161.png)

**Comment by Ryuk17** [comment]
定位到错误位置了，我onnx输入是三维的[1, 400, 80]，在MNN推理时第一个reshape算子报错，请问这种情况要怎么resize MNN的输入呢？

**Comment by jxt1234** [comment]
使用 MNN 时 resizeTensor -> resizeSession 了么?

**Comment by Ryuk17** [comment]
因为我ONNX模型输入是[1, 400, 80]就可以直接推理，但是转成MNN后进行推理报reshape error。 我想请问的是MNN的输入要resizeTensor到什么样子才和ONNX的[1, 400, 80]对上？

**Comment by Ryuk17** [comment]
我试了[1,1,400, 80], [1, 400,80,1]都不行

**Comment by Ryuk17** [comment]
这是对应的onnx算子
![image](https://user-images.githubusercontent.com/22525811/172383188-7f9e4737-1991-400d-b09f-cb8902f44e1e.png)
转换后的MNN对应这个
![image](https://user-images.githubusercontent.com/22525811/172383781-59dbfc44-27c6-44a5-b479-bfd817a3b91c.png)

**Comment by jxt1234** [comment]
下载中，我等会看看

**Comment by Ryuk17** [comment]
重新编译一次，可以了，谢谢
