### ISSUE TITLE
OpenCL生成的Cache文件在不同机型的适用范围咨询

### ISSUE THREAD

**Issue by CanChengZheng** [alibaba/MNN#1948]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
- Android平台

# Github版本:
- commit: af9e2689

# 问题描述

在"大淘宝技术"公众号发表的文章[《深入浅出 | 谈谈MNN GPU性能优化策略》](https://mp.weixin.qq.com/s?__biz=MzAxNDEwNjk5OQ==&mid=2650424271&idx=1&sn=d9a38856dddc5fc7ddd59e42b4885904)中的"MNN Cache技术设计"章节提到

> 由于OpenCL kernel需要根据**不同机型**在线编译源码program，以及加入精细化调优Auto-tuning试跑机制后，获得极佳性能的同时会带来启动时间较慢的代价。

> 如果应用仅限某种或某几种特定机型，可以事先生成好该机型的cache文件。

请问这里的“不同机型”应该如何理解，能否进一步解释下“不同机型”实际上应该是根据设备的哪些信息进行区分判定？
（打比方：设备A 和设备B 应该获取设备的哪些信息进行校验，相同则可以认为属于相同设备/机型，进而复用cache文件？）

**Comment by CanChengZheng** [comment]
> 主要根据GPU的类型以及代系去判定是不是相同设备

感谢解答，查看了MNN有关OpenCL运行环境初始化的代码（OpenCLRuntime::OpenCLRuntime），MNN会获取设备信息：
   - 设备名称（deviceName）
   - 设备版本（deviceVersion）
   - 设备厂商（deviceVendor）
   - OpenCL版本（mCLVersion）
   - 每秒浮点运算次数（mFlops）、全局存储器缓存（CL_DEVICE_GLOBAL_MEM_CACHE_SIZE）等参数信息。

同时在不同设备上运行程序来获取设备信息时，发现`Adreno`、`Mali` GPU类型获取到的设备信息存在差异：
```
# 下方信息是通过对代码(OpenCLRuntime::OpenCLRuntime)中定义的各个字段进行打印输出得到

# MI 5 
deviceName: QUALCOMM Adreno(TM)
deviceVersion: OpenCL 2.0 Adreno(TM) 530
deviceVendor: QUALCOMM
mCLVersion: 2.0
adrenoVersion: 530
mFlops: 4.000000

# Mate30Pro
deviceName: Mali-G76
deviceVersion: OpenCL 2.0 v1.r18p0-01rel0.e098644a2658b0905d91d87153032847
deviceVendor: ARM
mCLVersion: 2.0
mFlops: 31.610001
```
从获取的信息中，发现`Mali`可直接从设备名称(deviceName)中获取架构名称`G76`，而`Adreno`需要在设备版本(deviceVersion)或者字段adrenoVersion中获取adreno的版本`530`。

---

基于上述获取到的信息，设想是否可以针对这两种不同GPU类型，制定不同的设备识别策略，用来判定是否为"相同设备"：
1. 识别到`Adreno`设备后，通过将`adrenoVersion`及`CLVersion`结合的方式（生成字符串`Adreno_<AdrenoVersion>_CL_<CLVersion>`）进行判断，判定是否为"相同设备"。
   - 例如已为`Adreno(TM) 530 CLVersion=2.0`的设备预生成了`Adreno_530_CL_2.0.cache`的缓存文件。
   - 如果运行的设备为Adreno为530，CLVersion为2.0，则判定为"相同设备"，可使用该缓存文件；
   - 如果如果运行的设备为Adreno为504，CLVersion为2.0，则认为"非相同设备"，不适用该缓存文件。

2. 识别到`Mali`设备后，通过将`deviceName`及`CLVersion`结合的方式（生成字符串`<deviceName>_CL_<CLVersion>`）进行判断，判定是否为"相同设备"。
   - 例如已为`Mali-G76 CLVersion=2.0`的设备预生成了”Mali-G76_CL_2.0.cache“的缓存文件。
   - 如果运行的设备为Mali为G76，CLVersion为2.0，则判定为"相同设备"，可使用该缓存文件；
   - 如果如果运行的设备为Mali为G72，CLVersion为2.0，则认为"非相同设备"，不适用该缓存文件。

还请解答下上述的设备识别策略是否可行，谢谢 : ）

**Comment by bitxsw93** [comment]
这个方法可以的

**Comment by CanChengZheng** [comment]
好的了解了，感谢解答！
