### ISSUE TITLE
[Feature Request] Asymmetrical Pads in Convolution/Pooling

### ISSUE THREAD

**Issue by daquexian** [alibaba/MNN#195]
Currently, MNN doesn't support asymmetrical pads in convolution/pooling. As a result, ONNX GoogleNet cannot be converted into MNN format.

**Comment by daquexian** [comment]
@czy2014hust This issue is not solved, could you please reopen it?

**Comment by yizhaoyanbo** [comment]
@daquexian 
请问ONNX转mnn现在没有支持asymmetrical pads吗，我用的8月23号更新的MNN代码。
模型转换时候报错：
Check failed: (padX == padX_end) && (padY == padY_end) ==> Asymmetrical pads in convolution is not supported

**Comment by jxt1234** [comment]
supported in 0.2.1.8
