### ISSUE TITLE
多输入量化时维度问题

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#1950]
我对多输入模型进行量化时发现维度有问题，使用的模型在[这里](https://github.com/alibaba/MNN/issues/1946)。
我的模型的两个输入是[1, 400, 80]和[1]，config文件也是这么设置的
![image](https://user-images.githubusercontent.com/22525811/172805410-5c1222b1-bc02-4976-bbe4-91c2ae5c4147.png)
但是运行时报
![image](https://user-images.githubusercontent.com/22525811/172805498-f031be69-f911-4bd6-a169-ce6307fcd6a8.png)
我batch_size设置的是32，而903168/28224 = 32，这显然是把一个batch的输入([32, 1, 400, 80])当成单个网络模型输入([1, 400, 80])了

**Comment by Ryuk17** [comment]
float32转int8速度只快了5%，正常吗？
[model.zip](https://github.com/alibaba/MNN/files/8909267/model.zip)

**Comment by wangzhaode** [comment]
目前不支持，需要你修改代码去支持
