### ISSUE TITLE
mnn模型量化问题

### ISSUE THREAD

**Issue by litong123** [alibaba/MNN#1955]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux

# Github版本:
# Github Version:
eac58ab5f51beb49105d53b0e0a3388bd1b8ad1f

看了教程和代码，目前mnn模型量化只支持两种输入类型
enum InputType {
        IMAGE = 0,
        SEQUENCE = 1,
    };

请问如果是针对音频文件的模型该怎么量化？我的模型输入和输出是语音的fft特征，这种情况可以把特征存在TXT文件中，使用SEQUENCE这种输入类型进行量化吗？

**Comment by yyfcc17** [comment]
请使用mnncompress，看中文文档
