### ISSUE TITLE
Release note question

### ISSUE THREAD

**Issue by xingjing1** [alibaba/MNN#1956]
![aab1c3b496cc1657ad24a97689c108e1](https://user-images.githubusercontent.com/33440396/173842333-859eb243-9de2-4e99-80b9-5ad92162b3f8.png)
（1）请问增加bf16后端，a53或者a55有支持bf16计算的指令吗？是有特殊计算的指令还是转成fp32后用fmla计算的？
（2）有A55上bf16和fp16的对比吗？我觉得bf16可能没有fp16性能好。

**Comment by jxt1234** [comment]
bf16 是给不支持 fp16 计算的机器用的，A55 上肯定不如用 fp16 性能

**Comment by xingjing1** [comment]
> bf16 是给不支持 fp16 计算的机器用的，A55 上肯定不如用 fp16 性能

int8不够用了吗，非要bf16？

**Comment by jxt1234** [comment]
int8 可以。
理论上 int8 精度损失比 bf16 大，模型转成 int8 需要校准集或者训练，相比 bf16 的使用略复杂些
