### ISSUE TITLE
[CoreML] Don't support type Convolution.

### ISSUE THREAD

**Issue by anliyuan** [alibaba/MNN#1961]
IOS推理时使用：
int forward = MNN_FORWARD_NN;
config.type = static_cast<MNNForwardType>(forward);
log里出现：[CoreML] Don't support type Convolution.
[CoreML] Don't support type Interp.
[CoreML] Don't support type Raster.
cpu占用率依然很高，似乎所有的计算都转到cpu上进行了，请问怎么解决

**Comment by jxt1234** [comment]
没有 all load 的原因，可以更新代码，现在 master 上 coreml backend 不需要加 all load 了

**Comment by anliyuan** [comment]
新的master分支 metal  runsession时候computePipelineState must not be nil.

**Comment by anliyuan** [comment]
> 没有 all load 的原因，可以更新代码，现在 master 上 coreml backend 不需要加 all load 了

新的master分支 metal runsession时候computePipelineState must not be nil.
