### ISSUE TITLE
MNNConvert saveStaticModel 转换时出错，请教原因

### ISSUE THREAD

**Issue by lzlsha** [alibaba/MNN#1962]
Start to Convert Other Model Format To MNN Model...
inputTensors : [ data0, data1, data2, data3, data4, ]
outputTensors: [ crnn_cell0_softmax0, ]
**Const Folder Error for lstm0_l0_t0_i2hdim_minus_1**
gen Static Model ...
Converted Success!

在用MNNConvert 静态转换时，提示如上图错误提示：Const Folder Error for lstm0_l0_t0_i2hdim_minus_1，是不支持这个算子吗？有办法解决吗？

**Comment by lvyong1943** [comment]
我这边saveStaticModel  没有模型出来

**Comment by wangzhaode** [comment]
尝试转换成普通模型吧
