### ISSUE TITLE
在编译转换器的最后一步的时候遇到了这个问题，请问有什么解决办法吗？官网给的过程有点不清楚，可以提供一下方法吗

### ISSUE THREAD

**Issue by flingshen** [alibaba/MNN#1964]
C:\Users\yangshen\Documents\code\mnn\MNN\package_scripts\win\build_tools.ps1 : 不能对 Null 值表达式调用方法。
所在位置 行:1 字符: 1
+ .\package_scripts\win\build_tools.ps1 -path MNN-CPU/lib/x64
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [build_tools.ps1]，RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,build_tools.ps1

**Comment by jxt1234** [comment]
vs 版本是？详细编译日志发一下?
