### ISSUE TITLE
关于如何编译cuda版本的问题

### ISSUE THREAD

**Issue by zhoumenghan** [alibaba/MNN#1965]
您好，我现在的mnn模型可以在CPU和opencl上跑通，但opencl的速度比CPU还要慢，我想利用机器上的nvidia GPU跑程序，请问应该如何编译mnn，并且配置呢？我看语雀中还没有利用cuda mnn在nvidia gpu进行程序运行的指导文档，希望得到您的回复。

**Comment by jxt1234** [comment]
-DMNN_CUDA=true 就可以
