### ISSUE TITLE
Conv bias doesn't support convert to fp16?

### ISSUE THREAD

**Issue by jinfagang** [alibaba/MNN#1967]
https://github.com/alibaba/MNN/blob/47d6fc5adcdff3658d2e4c69e854f28f7debc888/tools/converter/source/common/SaveHalfFloat.cpp#L30

bias was commented out, why ?

**Comment by jinfagang** [comment]
BTW, why does FC weight doesn't support convert to fp16?

**Comment by jxt1234** [comment]
Normally bias data is much less than weight data, so we don't compress it yet.
FC will be converted to 1x1 Convolution, and then convert to fp16
