### ISSUE TITLE
Android NNAPI support

### ISSUE THREAD

**Issue by kwonhyeokmin** [alibaba/MNN#1968]
Hello! 
I try to use MNN in android mobile. And I saw the option MNN_FORWARD_NN is not yet support yet in Android 8.1's NNAPI in MNNForwardType.h file. 
I'm wonder that the NNAPI not supported only in Android 8.1's NNAPI or all android versions not supported NNAPI yet.

Thank you!

**Comment by jxt1234** [comment]
MNN don't adapt NNAPI yet.

**Comment by kwonhyeokmin** [comment]
Thank you for reply!

**Comment by wangzhaode** [comment]
下个版本将会支持NNAPI Backend

**Comment by wangzhaode** [comment]
> @wangzhaode 你好，我就是冲着MNN支持NNAPI来的，所以我还没用过MNN，但很想试一下MNN的NNAPI，请问有什么推荐的入门上手资料或代码仓库吗，谢谢！

2.2.0已经支持了NNAPI，文档参考 https://mnn-docs.readthedocs.io/en/latest/
NNAPI只需要将`MNNForwardType`设置成`MNN_FORWARD_NN`，其他用法与CPU无区别

**Comment by wangzhaode** [comment]
感谢你对我们工作的认可！
MNN的CPU性能是一直领先tflite的；NNAPI性能有可能是MNN对访存算子的融合又一定性能提升，也有可能tflite没有成功执行到accelerate设备（原因可能与算子不支持有关）

**Comment by hajungong007** [comment]
> > @wangzhaode 你好，我就是冲着MNN支持NNAPI来的，所以我还没用过MNN，但很想试一下MNN的NNAPI，请问有什么推荐的入门上手资料或代码仓库吗，谢谢！
> 
> 2.2.0已经支持了NNAPI，文档参考 https://mnn-docs.readthedocs.io/en/latest/ NNAPI只需要将`MNNForwardType`设置成`MNN_FORWARD_NN`，其他用法与CPU无区别

请问使用NNAPI后端可以直接使用release上编译好的[mnn_2.5.0_android_armv7_armv8_cpu_opencl_vulkan.zip](https://github.com/alibaba/MNN/releases/download/2.5.0/mnn_2.5.0_android_armv7_armv8_cpu_opencl_vulkan.zip)库吗
