### ISSUE TITLE
能否提供一个caffe和tf的简单用例呢？谢谢

### ISSUE THREAD

**Issue by 17759205390** [alibaba/MNN#197]

**Comment by li-qing** [comment]
demo里有示例啊？？

**Comment by 17759205390** [comment]
> demo里有示例啊？？

@li-qing 海思板子一个A53处理器，速度很慢啊，比ncnn慢了几十倍呀。makelist里需要配置什么加速选项吗？参考ncnn那样，打开neon什么的，速度比ncnn慢了几十倍呀

**Comment by 17759205390** [comment]
@li-qing 另外，能不能提供一个mtcnn的实例呀？ 我跑P层的模型，得到的指针是1*1*channel，貌似只跑了一张12*12的图，我实际输入是500*500，但在ncnn上，一次就可以跑出整张图片的所有结果，得到的数据指针包含多个候选框，是不是我没有把MNN用好？能详细指导下吗谢谢

**Comment by 17759205390** [comment]
@li-qing 另外，海思arm交叉编译的时候，加上-mfloat-abi=softp会报错

**Comment by jxt1234** [comment]
参考 https://github.com/liushuan/MNN-MTCNN-CPU-OPENCL

**Comment by 17759205390** [comment]
@jxt1234 你用的什么板子？我不知道交叉编译怎么写才能速度快一些~~

**Comment by jxt1234** [comment]
MNN_BUILD_HARD 宏打开

**Comment by jxt1234** [comment]
另外参考下 project/cross-compile/arm.toolchain.cmake

**Comment by 17759205390** [comment]
> MNN_BUILD_HARD 宏打开

@jxt1234 会报错
