### ISSUE TITLE
CL ERROR CODE: -1001, info: getPlatform

### ISSUE THREAD

**Issue by feixuedudiao** [alibaba/MNN#1974]
问题描述：
电脑显卡驱动装的版本与显卡不匹配，但问题解决该问题，采用手动加载对应显卡的Opencl库，但需要手动指定OpenCL库文件路径；
在调用MNN库时将Opecl库指定到MNN.dll所在目录的子目录下文件夹下，MNN编译时 MNN_USE_SYSTEM_LIB=ON，如何设置MNN编译开关才能支持手动指定OpenCL库文件路径解决该问题。

**Comment by jxt1234** [comment]
MNN_USE_SYSTEM_LIB=OFF ，然后自行修改 mnn opencl 相关加载 so 的代码

**Comment by rlczddl** [comment]
遇到同样的问题,废了我两天时间,说下我遇到的问题和解决方法,给后来人做个参考,我是在docker下的,环境是ubuntu16,系统安装了cuda,使用其自带的opencl后端。
1)编译选项MNN_USE_SYSTEM_LIB=ON,MNN_OPENCL=ON时,此时直接编译寻找opencl库.cmake文件无法找到相应的OpenCL_INCLUDE_DIR和OpenCL_LIBRARY,故在编译时直接手动指定它们为/usr/local/cuda-xxx/include和/usr/local/cuda-xxx/lib64,此时可以正常编译,但是链接到自己程序时还是无法使用,报了该issue提到的错误。
2)后面参考https://linuxhandbook.com/setup-opencl-linux-docker/,发现我直接键入clinfo时返回device=0,且无/etc/OpenCL/vendors该目录及目录下文件,猜测是这边有问题,故键入mkdir -p /etc/OpenCL/vendors 和 echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd,此时clinfo有输出,然后重复1)重新编译,此时链接到自己程序时后端就可以用了。

**Comment by rlczddl** [comment]
遇到了同样的问题,说下我怎么解决的,供后来人参考:
1)在docker里面编译遇到了遇到同样的问题,因为FindOpenCL.cmake无法找到cuda自带的opencl的头文件和库文件目录,故手动指定了它们,然后此时编译无误,链接到自己程序时会报CL ERROR CODE: -1001, info: getPlatform的错误
2.后面发现了一篇博客https://linuxhandbook.com/setup-opencl-linux-docker/,发现我的clinfo无任何输出,故参考博客里dockflie里面的步骤,键入mkdir -p /etc/OpenCL/vendors 和 echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd,然后重新编译,问题解决。
