### ISSUE TITLE
it reports Segmentation fault when inferencing my model with mnn on mobile device

### ISSUE THREAD

**Issue by FengMu1995** [alibaba/MNN#1975]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Galaxy Note10 android12 

# 编译方式:
# Compiling Method
cd project/android
mkdir build_64 && cd build_64 && ../build_64.sh
"
option(MNN_OPENCL "Enable OpenCL" ON)
option(MNN_OPENGL "Enable OpenGL" OFF)
option(MNN_VULKAN "Enable Vulkan" ON)
"

在手机上用openCL推理时,报如下错误, 用了vulkan也是报错, 在cpu上推理正常

SVM capalibilties: SVM_FINE_GRAIN_BUFFER
SVM capalibilties: SVM_ATOMICS
SVM capalibilties: SVM_FINE_GRAIN_BUFFER
SVM capalibilties: SVM_ATOMICS
SVM capalibilties: SVM_FINE_GRAIN_BUFFER
SVM capalibilties: SVM_ATOMICS
SVM capalibilties: SVM_FINE_GRAIN_BUFFER
SVM capalibilties: SVM_ATOMICS
Segmentation fault

**Comment by jxt1234** [comment]
应该是你直接使用了session 中 tensor 的ptr ，对 opencl 和 vulkan 而言，这个指针是 nullptr ，参考 https://www.yuque.com/mnn/cn/input 里面的输入数据

**Comment by FengMu1995** [comment]
this is my minimal code:
    MNN::Session *mnn_session = mnn_interpreter->createSession(schedule_config);
    MNN::Tensor *src_tensor = mnn_interpreter->getSessionInput(mnn_session, "src");
    MNN::Tensor *r1i_tensor = mnn_interpreter->getSessionInput(mnn_session, "r1i");;
    mnn_interpreter->resizeTensor(src_tensor, {1, 3, src_h, src_w});
    mnn_interpreter->resizeTensor(r1i_tensor, {1, 16, 60, 107});

    unsigned int r1i_size = 1 * 16 * 60 * 107;
    mnn_interpreter->resizeSession(mnn_session);
    std::fill_n(r1i_tensor->host<float>(), r1i_size, 0.f);

you mean like the following code:
auto inTensor = net->getSessionInput(session, NULL);
auto outTensor = net->getSessionInput(session, NULL);
auto _Tensor = MNN::Tensor::create<float>(inTensor->shape(), NULL, MNN::Tensor::TENSORFLOW);
for (int i = 0; i < _Tensor->elementSize(); i++) {
        _Tensor->host<float>()[i] = image.data[i];
    }
inTensor->copyFromHostTensor(_Tensor);

**Comment by FengMu1995** [comment]
Hi, I have solved the problem with reference to what you said. Thank you very much.
