### ISSUE TITLE
import an int8 QAT model fails

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/MNN#1976]
用MNNConverter转换一个 int8 QAT的tflilte模型，会有如下错误信息：

***MNN DO NOT SUPPORT Tflite [INT8] quantized model, please use MNN quantization tool to quantize model***

看起来是不支持量化后的模型。有别的方法可以把这个tflite模型转成Mnn模型吗？

**Comment by jxt1234** [comment]
tflite int8 目前不支持，建议基于 tensorflow 重新训练  https://www.yuque.com/mnn/cn/wwueoh
