### ISSUE TITLE
multiple inputs when quantifying my model

### ISSUE THREAD

**Issue by FengMu1995** [alibaba/MNN#1977]
I have four 4-dimension arrays as inputs, like [1, 16, 80, 80], and my quantization json is following: 
I wonder if the quantization tool supports multiple inputs. If it does, how should I modify the json for quantization.

{"format":"RGB",
"mean":[0.0,0.0,0.0],
"normal":[0.00392157,0.00392157,0.00392157],
"width":214,
"height":120,
"path":"/home/wudi/project/project_rvm/rvm_mnn_android/quant_data/",
"used_image_num":560,
"feature_quantize_method":"KL",
"weight_quantize_method":"MAX_ABS"
}

**Comment by jxt1234** [comment]
The cpp's quant tool only support single input. See https://www.yuque.com/mnn/cn/ng8qc1  for multiple input support.

**Comment by FengMu1995** [comment]
OK.
