### ISSUE TITLE
MNN-2.0.0 release CUDA bacnend outputs error

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#1978]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Ubuntu 16.04 GCC-8.2 CUDA-10.2

MNN-Version: MNN-2.0.0 release

# 编译方式:
# Compiling Method

-DCMAKE_BUILD_TYPE=Release -DMNN_CUDA=ON

Model's output was wrong with MNN-2.0.0 cuda backend. Everythin's ok with MNN-1.2.0 release.

BTW. Both of them performs normal with cpu backend :)

**Comment by jxt1234** [comment]
All model is error or your own model is error? Could you upload your model for us to test ?

**Comment by MaybeShewill-CV** [comment]
@jxt1234 All my image model which can be rightly deployed with MNN-1.2.0 has met such a problem. Besides how can i share the model to you guys. Maybe baidu-net disk ? :)

**Comment by jxt1234** [comment]
Baidu-net disk we can't install. You can send one of the model to my email (jxt1234@zju.edu.cn).
BTW, does mobilenet / squeezenet is error in your environment ?

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Ok I will send the mode to that email :) MobilenetV2 also stuck in this which can be correctly deployed via MNN-1.2.0 instead:)

**Comment by MaybeShewill-CV** [comment]
@jxt1234 BTW mobilenet you mentioned above is some of your official example? The mobilenetv2 used for testing was developed by myself :)

**Comment by MaybeShewill-CV** [comment]
@jxt1234 I have sent the model to your email. Looking forward to your kindly replay:)

**Comment by jxt1234** [comment]
Received.

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Any progress here? Looking forward to your kindly replay:)

**Comment by jxt1234** [comment]
We test CUDA in our machine and don't cause error. Maybe it's bug of CUDA code compability. We will refract code later.

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Strange....I have met the same problem no matter using CUDA 10.2 or CUDA 11.1. Is there any chance that cudnn could cause the problem? Besides could you please kindly tell me your CUDA version and CUDNN version ? :)

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Could you plz share the information? :)

**Comment by jxt1234** [comment]
> @jxt1234 Strange....I have met the same problem no matter using CUDA 10.2 or CUDA 11.1. Is there any chance that cudnn could cause the problem? Besides could you please kindly tell me your CUDA version and CUDNN version ? :)

MNN CUDA don't use cudnn now. Your GPU's type is ?

**Comment by MaybeShewill-CV** [comment]
@jxt1234 I have test GTX-1070 and RTX-3080:)

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Any progress here? Looking forward to your kindly replay:)

**Comment by rlczddl** [comment]
你编译cuda后端除了-DCMAKE_BUILD_TYPE=Release -DMNN_CUDA=ON这个选项有做其它修改吗?我的cuda后端死活不能用,不知道什么原因......

**Comment by MaybeShewill-CV** [comment]
@rlczddl 链接 不到cuda库的话可以自己手动指定一下cuda的目录地址

**Comment by rlczddl** [comment]
尝试过,加上include_dir和link_dir,编译没问题,用到自己的程序里链接还是报对‘libMNN.so：对‘MNN::CUDA::CUDARuntimeWrapper:xxx"未引用的错误,很奇怪

**Comment by rlczddl** [comment]
尝试过,结果依旧,很奇怪
编译选项
![2022-08-17 11-37-16屏幕截图](https://user-images.githubusercontent.com/21055131/185029369-7187f61b-fb34-42ab-b84d-064b2219a597.png)
链接到自己程序时报错
![2022-08-17 11-38-30屏幕截图](https://user-images.githubusercontent.com/21055131/185029451-a3735eaa-0738-4496-afb5-730f6c156430.png)

**Comment by MaybeShewill-CV** [comment]
@rlczddl 我倒是没遇到这个链接的问题 只是CUDA后端计算的结果都不对:)

**Comment by MaybeShewill-CV** [comment]
@jxt1234 今天又尝试了下2.0.5版本。编译时取消链接cudnn库，编译成功没有问题。使用2.0.5新编译的模型转换工具转换mobilenet.pb模型成功没有报错，使用mnn的backendTest工具测试cuda后端时报错

```
./backendTest.out ./mobilenetv2.mnn 2
Test forward type: 2
Tolerance Rate: 0.050000
Open Model ./mobilenetv2.mnn
Input: 224,224,3,1
precision=0 in main, 268 
modeNum=1 in main, 273 
stopOp.c_str()=s  in main, 278 
File: MNN-2.0.5/source/backend/cuda/execution/ConvCutlassExecution.cu Line 643: failed: Error Internal
Aborted
```
请问这个问题可以如何解决呢?

**Comment by bitxsw93** [comment]
Please update lastest mnn code, retry again.  If having any problem, please let me know.

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 latest means latest master branch or MNN-2.3.0 release. MNN-2.3.0 release also have such a problem. #2211
