### ISSUE TITLE
A question about loading model from memory

### ISSUE THREAD

**Issue by FengMu1995** [alibaba/MNN#1979]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
linux x86-64

# 编译方式:
# cmake

I see other's use,
"""
auto revertor = std::unique_ptr<Revert>(new Revert(filename));
revertor->initialize();
auto modelBuffer      = revertor->getBuffer();
const auto bufferSize = revertor->getBufferSize();
std::shared_ptr<MNN::Interpreter> mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromBuffer(modelBuffer, bufferSize));
"""
i don't know if I have the lib support revertor,
I add the above code into my project, it reports many undefined error
"/home/wudi/project/project_rvm/rvm_mnn/main.cpp:20: error: undefined reference to `Revert::Revert(char const*)''
if I need to open something when building the mnn with cmake?

**Comment by jxt1234** [comment]
Don't need call Revert.

**Comment by FengMu1995** [comment]
OK, I get it.
