### ISSUE TITLE
数据归一化问题

### ISSUE THREAD

**Issue by shengdewu** [alibaba/MNN#1981]
现象： mnn 提供的数据转化类 MNN::CV::ImageProcess 的 convert 方法 只能接受类型是 uint_8 的原始图像

问题：如果我的数据已经归一化了，以及是float类型 ， 我怎么才能把数据填充到input_tensor并且不做归一化

**Comment by yyfcc17** [comment]
看看文档

**Comment by shengdewu** [comment]
你好是这种方法吗
auto inputTensor = interpreter->getSessionInput(session, NULL);
inputTensor->host<float>()[0] = 1.f;

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/cn/input

**Comment by shengdewu** [comment]
> https://www.yuque.com/mnn/cn/input

感谢，我已经解决

采用copyFromHostTensor 是为了把数据从cpu拷贝到gpu吗

**Comment by jxt1234** [comment]
处理数据内存布局与异构内存的转换

**Comment by shengdewu** [comment]
> 处理数据内存布局与异构内存的转换

感谢
