### ISSUE TITLE
attention中的矩阵乘法，MNN会量化吗？

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#1982]

**Comment by jxt1234** [comment]
当矩阵乘法的一个输入为 Const 时，mnn 会将其转换成对应的 1x1 卷积，从而可以量化

**Comment by Ryuk17** [comment]
那继续请教下，MNN对ONNX中的gemm matmul 这两个算子处理方式是一样的吗？

**Comment by jxt1234** [comment]
onnx 的 matmul 与 mnn 的 matmul 直接对应
onnx 的 gemm 用 mnn MatMul + 后处理组合实现

两者均为走上面所说的矩阵乘转换的优化
