### ISSUE TITLE
MNN Opencl在骁龙865上的性能问题

### ISSUE THREAD

**Issue by mjp9527** [alibaba/MNN#1983]
您好，
我的硬件平台是865（xiaomi10)
<img width="548" alt="image" src="https://user-images.githubusercontent.com/54735487/177705935-353d564b-218d-4c5f-a055-e323c5b87dab.png">

我在网上找了一些开源onnx模型，对比了几个框架的opencl性能差距，使用MNNV2Basic.out这个demo进行测试，打印的精度也是fp16+image的方式，为什么模型的性能会差很多，还需要做哪些设置吗？或者从哪里可以找到一些相同模型的官方的benchmark数据？

**Comment by jxt1234** [comment]
你的 numThread / mode 设置是什么，参考 https://www.yuque.com/mnn/cn/create_session#KtfMk 修改 mode ，性能会有很大差别

**Comment by jxt1234** [comment]
mobilenet v1 865 mnn opencl 参考性能数据记得是 6 - 7 ms

**Comment by mjp9527** [comment]
> mobilenet v1 865 mnn opencl 参考性能数据记得是 6 - 7 ms

您好，我设置了    config.numThread = MNN_GPU_TUNING_WIDE | MNN_GPU_MEMORY_IMAGE;
使用了get_model.sh里的mobilenetv1，在865上耗时9.87ms，还是无法得到高性能的数据

**Comment by jxt1234** [comment]
mnn 版本是，master 上 (2.0.0) benchmark  model 的 mobilenet v1 在小米 10 上是 7 ms （mode 设成 4 ，precision = 2）

**Comment by mjp9527** [comment]
> 

![image](https://user-images.githubusercontent.com/54735487/177764611-28b0a5fe-ecc4-41e4-9e26-9157343786d8.png)
最小值也在9.2ms左右

**Comment by jxt1234** [comment]
用 benchmark.out 测试下？有可能是和 map - unmap 相关

**Comment by mjp9527** [comment]
> 用 benchmark.out 测试下？有可能是和 map - unmap 相关

![image](https://user-images.githubusercontent.com/54735487/177906712-81c0180b-760d-43dd-b5c3-ee642d1ac595.png)
benchmark确实可以得到正确的数据，还想请教一下为什么benchmark提供的模型用MNN2Basic运行会报 『Trap』

**Comment by firework-github** [comment]
> 用 benchmark.out 测试下？有可能是和 map - unmap 相关

MNN版本是2.9.0，想测试OpenCL在android上跑GPU的耗时
1. 想问下benchmark的源码中，也用了map -unmap，测试推理耗时是否有影响呢
2. 测试耗时时，多测调用runSession，推理结果就不对了，是因为推理时复用内存导致的吗
3. 官方文档显示，runSession对于其他后端，如GPU，测试的时间是GPU指令的提交时间，那用benchmark测试时，耗时是不是就不准确了呢
