### ISSUE TITLE
请问release包中的android预测库编译命令是什么

### ISSUE THREAD

**Issue by lxwlaq** [alibaba/MNN#1985]
![image](https://user-images.githubusercontent.com/43700894/177930569-11df16b2-95f5-4292-8493-c8d0df9ed73d.png)

我自己编译的预测库预测耗时要比官方发布的预测库慢很多，所以想知道官方发布的预测库编译命令是什么

**Comment by jxt1234** [comment]
project/android/demo/app/build.gradle 里面 arguments 里面额外加一个 -DMNN_ARM82=ON
