### ISSUE TITLE
MNN工作台Mac-m1版模型转换工具不支持torch模型转换

### ISSUE THREAD

**Issue by VictoryDong** [alibaba/MNN#1993]
在使用转换工具转换模型时，如图报错，期望下个版本可以使用这个工具转换torch模型，方便快捷
<img width="969" alt="image" src="https://user-images.githubusercontent.com/11418609/178644694-a2af8945-2100-4f3a-9681-620b62c3b224.png">

**Comment by jxt1234** [comment]
收到
