### ISSUE TITLE
Can not build pymnn on macOS M1

### ISSUE THREAD

**Issue by jinfagang** [alibaba/MNN#2001]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
-- MNN BUILD INFO:
-- 	System: Darwin
-- 	Processor: arm64
-- 	Version: 2.0.3
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16:
-- 	ThreadPool: ON
-- 	Hidden: TRUE
```

I disabled METAL and MNNTrain.

# 编译日志:
# Build Log:

```
python build_wheel.py --version 0.1.2
```

```
USE_TRT  False
Building with python wheel with package name  MNN
```

```
ld: warning: directory not found for option '-L/Users//MNN/pymnn_build/source/backend/tensorrt'
ld: warning: directory not found for option '-L/Users/MNN/pymnn_build/3rd_party/protobuf/cmake'
ld: library not found for -lMNNConvertDeps
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/opt/homebrew/opt/llvm/bin/clang++' failed with exit code 1
```

**Comment by jxt1234** [comment]
请看一下 pymnn/INSTALL.md

需要先运行 python3 build_deps.py
