### ISSUE TITLE
session_ = interpreter->createSession 创建会话成功，interpreter->getSessionOutput（session_, NULL）返回输出Tensor的shape所有维度为0

### ISSUE THREAD

**Issue by songkq** [alibaba/MNN#2004]

**Comment by songkq** [comment]
部署环境：Andriod ARMv8a
转模型MNN版本：2.0，MNN部署环境版本：1.2

**Comment by songkq** [comment]
@jxt1234 hi，可以帮忙看下这个问题嘛

**Comment by jxt1234** [comment]
一般是输入没有 resize 的原因，参考 https://www.yuque.com/mnn/cn/input#9xXDG

**Comment by songkq** [comment]
@jxt1234 并不是，问题暂时解决了，C++推理时使用MNN2.0版本源码编译的runtime
不知道MNN 2.0版本有没有新增一些以前不支持的算子，导致有一些2.0版本转的模型在低版本runtime下运行崩溃？？

**Comment by jxt1234** [comment]
哦，这个是有可能的，部署环境的版本建议不要低于模型转换的版本，有可能新版本会做优化或者在模型里面加一些额外信息，导致旧版本的引擎不兼容。

反之没有问题，新版本的引擎是向下兼容老版本模型的。
