### ISSUE TITLE
请问在哪里可以找到ONNX2MNN的OP映射表？

### ISSUE THREAD

**Issue by songkq** [alibaba/MNN#2005]

**Comment by jxt1234** [comment]
ONNX 的 Op 到 MNN 不是一一对应的，MNN 支持的 ONNX 算子可用 ./MNNConvert - f ONNX --OP 查看

**Comment by songkq** [comment]
@jxt1234 好的，谢谢。这边看到timeProfiler.out可以分析MNN模型逐层耗时，如果想看某个层对应的onnx op，有什么方法嘛？
