### ISSUE TITLE
  MNN2.0 conversion reasoning result is incorrect

### ISSUE THREAD

**Issue by 2495165664** [alibaba/MNN#2007]
# Platform(Include target platform as well if cross-compiling):  ubuntu1604, gcc version 5.4.0 20160609

# Github Version: MNN2.0

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``
Comment = 4679f848c45510531976ebdf32c42b1c27b92960

# Compiling Method
GCC G++

Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

Problem:
The model transformed by the 2.0 compiled transformation tool cannot be matched with the reasoning result of 2.0. Cross verify the two versions. If 1.1 reasoning and 2.0 transformation results are selected, the 1.1 transformation model is selected, and the reasoning results of 2.0 and 1.1 are completely consistent and correct.

**Comment by jxt1234** [comment]
See https://www.yuque.com/mnn/cn/model_convert#nxImR. Use fastTestOnnx.py / fastTestTf.py to check if MNN's result is the same as TF / ONNX
