### ISSUE TITLE
paddleocr动态识别模型通过onnx转MNN， Acquire buffer size = 0

### ISSUE THREAD

**Issue by qihang720** [alibaba/MNN#2008]
# Github版本:
# Github Version:
9aef4b6ff4ad297bec728317e7b526ad8544a6e7

# 编译方式:
# Compiling Method
cd MNN
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true
make
```

模型地址：
https://drive.google.com/file/d/1AfzVYamixjf0eFE-5yKpA2tPoyUciV0b/view?usp=sharing

复现流程：
1. python -m onnxsim model/ch_PP_OCRv3_rec.onnx model/ch_PP_OCRv3_rec_sim.onnx
2. ./MNNConvert -f ONNX --modelFile ch_PP_OCRv3_rec_sim.onnx --MNNModel h_PP_OCRv3_rec_sim.mnn --bizCode MNN

使用静态模型，成功转换，且没有报错，使用动态模型，转换成功，但出现Acquire buffer size = 0，且最后结果与onnx相差很大。

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/cn/model_convert#nxImR

先用 fastTestOnnx.py 进行正确性校验测试

**Comment by jxt1234** [comment]
另外建议先不用 onnxsim 试下

**Comment by qihang720** [comment]
> 另外建议先不用 onnxsim 试下

不适用onnxsim，同时使用新版本的MNN转换模型和推理，虽然还有Acquire buffer size = 0，但准确率没有下降很多。感谢帮助
