### ISSUE TITLE
编译android包时报错

### ISSUE THREAD

**Issue by qiaowei1214** [alibaba/MNN#201]
Cmakelist中OpenGL、OpenCL置为ON
编译GL、CL的时候报错
[ 88%] Linking CXX shared library libMNN_GL.so
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:219: error: undefined reference to 'glDispatchCompute'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:159: error: undefined reference to 'glBindImageTexture'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:219: error: undefined reference to 'glDispatchCompute'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:170: error: undefined reference to 'glMemoryBarrier'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:194: error: undefined reference to 'glBindImageTexture'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:219: error: undefined reference to 'glDispatchCompute'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:235: error: undefined reference to 'glBindImageTexture'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:219: error: undefined reference to 'glDispatchCompute'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:246: error: undefined reference to 'glMemoryBarrier'
/Users/qiaowei/Desktop/workspace/MNN/source/backend/opengl/GLBackend.cpp:283: error: undefined reference to 'glBindImageTexture'
collect2: error: ld returned 1 exit status
make[2]: *** [source/backend/opengl/libMNN_GL.so] Error 1
make[1]: *** [source/backend/opengl/CMakeFiles/MNN_GL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 89%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/LrnExecution.cpp.o
[ 89%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/NormalizeExecution.cpp.o
[ 89%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/PermuteExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/PoolExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/ReluExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/ReshapeExecution.cpp.o
[ 90%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/ResizeExecution.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/RoiPoolingExecution.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/ScaleExecution.cpp.o
[ 91%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/SliceExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/SoftmaxExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/SpaceToBatchExecution.cpp.o
[ 92%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/SpatialProductExecution.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/UnaryExecution.cpp.o
[ 93%] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/cl/codegen/opencl_program.cc.o
[ 93%] Linking CXX shared library libMNN_CL.so
[ 93%] Built target MNN_CL
make: *** [all] Error 2

**Comment by jxt1234** [comment]
build_32.sh 中 android-19 改成 android-21
