### ISSUE TITLE
cuda后端编译成功,为啥推理时还不能用

### ISSUE THREAD

**Issue by rlczddl** [alibaba/MNN#2013]
勾选了MNN_CUDA,MNN_USE_SYSTEM_LIB,取消了MNN_SEP_BUILD,ubuntu18上成功编译,推理时采用cuda后端还是报Can't Find type=2 backend, use 0 instead

**Comment by jxt1234** [comment]
把 cmakecache.txt 及 build 目录删除再编试下

**Comment by rlczddl** [comment]
这之后又试了好多次,还是推理时不能用,可能是什么原因呢

**Comment by rlczddl** [comment]
![image](https://user-images.githubusercontent.com/21055131/183058435-bfe0709c-5a17-4b0f-83f9-a29829fc6680.png)
bendmark测试如上,这表示成功了吗

**Comment by rlczddl** [comment]
更新下,编译无错误信息,链接时会报 对'MNN::CUDA:xxx'未定义的引用错误,看错误是编译mnn动态库时cuda后端没法成功编进去

**Comment by bitxsw93** [comment]
Please update lastest mnn code, retry again. If having any problem, please let me know.
