### ISSUE TITLE
MNN在aarch64上导入两个模型时会在导入第二个模型时createSession时死机

### ISSUE THREAD

**Issue by heartXXkiller** [alibaba/MNN#2014]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  aarch64-openwrt-linux-gun gcc 6.3.0

# Github版本:
# Github Version: 1.2.10

在aarch64环境下，将两个模型导入到GPU上，会出现在第二个模型上崩溃，给出的错误日志
```
[SignalHandler]catch signal: 11
[logGetBackTrace]string:linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f78345770]
[logGetBackTrace]string:/lib/libPVROCL.so(+0x39cc4) [0x7f7e390cc4]

```
压测抓到过一帧日志是
![企业微信截图_16560342784579](https://user-images.githubusercontent.com/35839319/184091533-e6a1b6aa-40a7-47c8-a3d0-cafaf4c1f181.png)
显示是内核不合法

**Comment by wangzhaode** [comment]
使用的是什么后端？OpenCL嘛

**Comment by heartXXkiller** [comment]
OpenCL1.2

**Comment by jxt1234** [comment]
更新到 2.4.2 测试吧。如果仍有问题重新提 issue.
