### ISSUE TITLE
sigmastar平台编译失败：internal compiler error: in decompose_automod_address

### ISSUE THREAD

**Issue by qihang720** [alibaba/MNN#2015]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
在sigmastar平台上编译

# Github版本:
# Github Version:
1.2.6版本之后都编译失败，1.2.5之前正常

# 编译日志:
# Build Log:
/3rdparty/MNN/source/backend/cpu/compute/WinogradOptFunction.cpp:799:1: internal compiler error: in decompose_automod_address, at rtlanal.c:6311
  800 | }
      | ^
0xdadb07 decompose_automod_address
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/rtlanal.c:6311
0xdadb07 decompose_address(address_info*, rtx_def**, machine_mode, unsigned char, rtx_code)
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/rtlanal.c:6476
0xc88671 process_address_1
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/lra-constraints.c:3322
0xc8a43a process_address
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/lra-constraints.c:3593
0xc8a43a curr_insn_transform
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/lra-constraints.c:3908
0xc8da3e lra_constraints(bool)
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/lra-constraints.c:4978
0xc752fc lra(_IO_FILE*)
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/lra.c:2472
0xc275f9 do_reload
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/ira.c:5516
0xc275f9 execute
        /home/meng/toolchain/build/snapshots/gcc.git~gcc-9_1_0-release/gcc/ira.c:5700
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://gcc.gnu.org/bugs/> for instructions.
3rdparty/MNN/CMakeFiles/MNNCPU.dir/build.make:1251: recipe for target '3rdparty/MNN/CMakeFiles/MNNCPU.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o' failed
make[2]: *** [3rdparty/MNN/CMakeFiles/MNNCPU.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o] Error 1
CMakeFiles/Makefile2:597: recipe for target '3rdparty/MNN/CMakeFiles/MNNCPU.dir/all' failed
make[1]: *** [3rdparty/MNN/CMakeFiles/MNNCPU.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```
粘贴在这里
Paste log here or pastebin
```

**Comment by tianyashu2020** [comment]
确认下，题主中的  ”1.2.6版本之后都编译失败，1.2.5之前正常”，这个版本应该指的是本地安装的git的版本吧，为啥是github的版本？
