### ISSUE TITLE
离线量化，转出来的量化模型只有两个常量

### ISSUE THREAD

**Issue by huahuahuo** [alibaba/MNN#2016]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux x86_64

# Github版本:
# Github Version:
2.0.3

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
![image](https://user-images.githubusercontent.com/66724181/184062518-56bdd233-1685-4be2-916b-a8a285b1e7f2.png)

**Comment by lyyiangang** [comment]
编译命令是什么？

**Comment by mjp9527** [comment]
请问你解决了吗

**Comment by hzpzlz** [comment]
使用python API进行离线量化，数据集训练完之后出来的模型没法用MNN.Interpreter()加载，请问下怎么解决呀。

**Comment by wangzhaode** [comment]
> 使用python API进行离线量化，数据集训练完之后出来的模型没法用MNN.Interpreter()加载，请问下怎么解决呀。

加载时报错还是`Segment Fault`呢

**Comment by hzpzlz** [comment]
> > 使用python API进行离线量化，数据集训练完之后出来的模型没法用MNN.Interpreter()加载，请问下怎么解决呀。
> 
> 加载时报错还是`Segment Fault`呢

报错了，错误信息是这样的：
Invalidate buffer to create interpreter
Traceback (most recent call last):
  File "mnn_inter.py", line 27, in <module>
    interpreter = MNN.Interpreter(mnn_model_path)
Exception: PyMNNInterpreter_new: NetInstance::createFromFile failed. Invalid model file, Check console log messages!

**Comment by jxt1234** [comment]
pymnn 上采用 eager 计算模式所致，
更新 master 代码，参考 tools/MNNPythonOfflineQuant/mnn_offline_quant.py 
在最前加上 MNN.expr.lazy_eval(True) 即可
