### ISSUE TITLE
版本问题，mnn1.1.7转了一个mnn模型，只能用1.1.7版本才能运行，换其他版本都不能运行

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2018]
用了别人的mnn1.1.7转的mnn模型，现在想升级到1.2.0版本上，但是怎么搞，这个模型就会导致崩溃，2.0也一样。而且2.0以后的版本onnx转mnn总是失败。

**Comment by jxt1234** [comment]
原则上都是用最新版本。目前最新版本 onnx 转 mnn 失败对应的错误是什么？
