### ISSUE TITLE
MNN.podspec 为什么一直都是1.2.0版本呢

### ISSUE THREAD

**Issue by fndppx** [alibaba/MNN#2020]
MNN.podspec 为什么一直都是1.2.0版本呢，想通过pod 使用mnn 1.2.7版本但是 podspec 是1.2.0

**Comment by wangzhaode** [comment]
这个目前没有更新

**Comment by fndppx** [comment]
> 这个目前没有更新

您好，能支持下podspec么，这样我们可以直接通过pod 引入对应版本mnn

**Comment by wangzhaode** [comment]
目前已经更新了 等`2.4.0`版本会发布
