### ISSUE TITLE
一个图像buffer转成一个Tensor 喂给input 好难，能给个demo么，真搞不出来

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2022]
bool Mat2Tensor(const cv::Mat& imgGray)
{
    auto  inTensor = net->getSessionInput(session, indices0InputName.c_str());
  
    cv::Mat preImage = cv::Mat(imgGray.size(), CV_32FC1);
    imgGray.convertTo(preImage, CV_32FC1, 1 / 255.);

   // std::shared_ptr<MNN::Tensor> inputUser(new MNN::Tensor(inTensor, MNN::Tensor::CAFFE_C4));
    MNN::Tensor* inputUser = MNN::Tensor::create(inTensor->shape(), inTensor->getType(), preImage.data,
        inTensor->getDimensionType());
 
    ::memcpy(inputUser->host<float>(), preImage.data, inputUser->elementSize()*4);
    
    tensor2Mat(inputUser, imgGray.size());
    //return inTensor->copyFromHostTensor(inputUser.get());
   bool flag= inTensor->copyFromHostTensor(inputUser);
     //bool flag = inputUser->copyToHostTensor(inTensor);
    return flag;
}

flag 一直都是false

bool readImg2Tensor1()
{
	int imgwidth = 0;
	int imgheight = 0;
	int  channel = 0;
	stbi_uc* inputImage = stbi_load("F:/mnn/MNN-master/vc2019/Debug/11.jpg", &imgwidth, &imgheight, &channel, 1);

	auto  inTensor = net->getSessionInput(session, indices0InputName.c_str());
	std::shared_ptr<MNN::Tensor> inputUser(new MNN::Tensor(inTensor, inTensor->getDimensionType()));

	auto bpp = inputUser->channel();
	int width = inputUser->width();
	int height = inputUser->height();
	int eleSize = inputUser->elementSize();
	int inSize = inTensor->elementSize();

	MNN::CV::ImageProcess::Config config;
	config.filterType = MNN::CV::BILINEAR;
	if (channel == 1)
	{
		config.sourceFormat = MNN::CV::GRAY;//
	}
	else
	{
		config.sourceFormat = MNN::CV::BGR;//
	}

	config.destFormat = MNN::CV::GRAY;
	MNN::CV::Matrix trans;
	trans.setScale((float)(imgwidth - 1) / (width - 1), (float)(imgheight - 1) / (height - 1));
	std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(config));
	pretreat->setMatrix(trans);
	//崩溃
	//pretreat->convert((uint8_t*)inputImage, imgwidth, imgheight, 0, inputUser->host<uint8_t>() + inputUser->stride(0) * 1 * inputUser->getType().bytes(), width, height, bpp, 0, inputUser->getType());
	//失败
	pretreat->convert((uint8_t*)inputImage, imgwidth, imgheight, 0, inputUser->host<uint8_t>(), width, height, bpp, 0, inputUser->getType());
	bool flag = inTensor->copyFromHostTensor(inputUser.get());
	return flag;
}

用demo里的stbi_load也不行，好绝望

**Comment by jxt1234** [comment]
这个返回 false 说明 session 还没 resize 成功，先 resizeTensor -> resizeSession 进行 resize

**Comment by lvyong1943** [comment]
> 
    mnn_interpreter->resizeTensor(
        input_tensor, {input_batch, input_channel, input_height, input_width});
    mnn_interpreter->resizeSession(mnn_session)
有resize的，我发现，源码这么写好像什么也没调用
void Interpreter::resizeSession(Session* session) {
    resizeSession(session, 0);
}

失败的 原因是因为input_tensor 里的des 的backend指针一直是空的

**Comment by jxt1234** [comment]
backend指针为空的原因是 session 没有 resize 成功，可以看下报错 log
