### ISSUE TITLE
模型在Android平台上推理时间不稳定，波动很大

### ISSUE THREAD

**Issue by yuanluw** [alibaba/MNN#2024]
我的方法有3个模型，采用了文档里推荐的共享运行时资源的方式，在华为荣耀8x上进行测试。
共享运行资源的配置如下：
MNN::BackendConfig backendConfig;
backendConfig.precision = MNN::BackendConfig::Precision_Normal;
backendConfig.power = MNN::BackendConfig::Power_Low;
backendConfig.memory = MNN::BackendConfig::Memory_High;
MNN::ScheduleConfig scheduleConfig;
scheduleConfig.type = MNN_FORWARD_CPU;
scheduleConfig.numThread = 4;
scheduleConfig.backendConfig = &backendConfig;
auto runtimeInfo = MNN::Interpreter::createRuntime({scheduleConfig});

三个模型是前后顺序执行，从测试结果来看，三个模型每一次的推理时间都不一致，
这是第一个模型的结果：
getFacePoints consuming 18 ms
getFacePoints consuming 7 ms
getFacePoints consuming 11 ms
 getFacePoints consuming 13 ms
getFacePoints consuming 10 ms
getFacePoints consuming 12 ms
 getFacePoints consuming 11 ms
 getFacePoints consuming 15 ms
getFacePoints consuming 17 ms
 getFacePoints consuming 8 ms
 getFacePoints consuming 24 ms
getFacePoints consuming 17 ms
getFacePoints consuming 11 ms
getFacePoints consuming 9 ms
 getFacePoints consuming 7 ms
 getFacePoints consuming 11 ms
 getFacePoints consuming 13 ms
getFacePoints consuming 18 ms
getFacePoints consuming 10 ms
getFacePoints consuming 23 ms
getFacePoints consuming 17 ms
getFacePoints consuming 20 ms
getFacePoints consuming 17 ms
getFacePoints consuming 20 ms
getFacePoints consuming 9 ms
getFacePoints consuming 11 ms
 getFacePoints consuming 19 ms
getFacePoints consuming 29 ms
getFacePoints consuming 12 ms
getFacePoints consuming 14 ms
getFacePoints consuming 6 ms
getFacePoints consuming 12 ms
 getFacePoints consuming 11 ms
这是第二个模型的结果：
getFaceParams consuming 7 ms
getFaceParams consuming 7 ms
getFaceParams consuming 9 ms
getFaceParams consuming 7 ms
 getFaceParams consuming 8 ms
getFaceParams consuming 7 ms
 getFaceParams consuming 11 ms
getFaceParams consuming 9 ms
getFaceParams consuming 4 ms
 getFaceParams consuming 4 ms
getFaceParams consuming 10 ms
getFaceParams consuming 7 ms
 getFaceParams consuming 8 ms
getFaceParams consuming 4 ms
getFaceParams consuming 8 ms
 getFaceParams consuming 9 ms
getFaceParams consuming 8 ms
getFaceParams consuming 8 ms
getFaceParams consuming 8 ms
 getFaceParams consuming 8 ms
getFaceParams consuming 9 ms
getFaceParams consuming 6 ms
 getFaceParams consuming 6 ms
 getFaceParams consuming 16 ms
getFaceParams consuming 8 ms
getFaceParams consuming 6 ms
getFaceParams consuming 9 ms
第三个模型的推理时间也差不多，就不贴了。然后我有在windows上单独测试了第一个模型的推理时间，发现除了前几帧，后面的帧处理时间都稳定在一个确定的值。
考虑到可能是多个模型运行占用资源太多，我也在android平台上单独测试了一个模型，发现推理时间还是波动很大。安卓的包编译方法应该就是开了一个MNN_OPENMP的多线程优化。

**Comment by jxt1234** [comment]
这个是移动端设备  CPU 调频 / 调度的问题，没有什么好办法解决

**Comment by chinaTony1124** [comment]
@yuanluw ，波动的问题，你有fix掉吗，如何解决呀

**Comment by chinaTony1124** [comment]
> 这个是移动端设备 CPU 调频 / 调度的问题，没有什么好办法解决

现在有方案或者patch来缓解吗

**Comment by yangy996** [comment]
遇到相同的问题，有解决办法吗？
