### ISSUE TITLE
createSession takes >5 minutes with openCL on Android

### ISSUE THREAD

**Issue by jianzhangru** [alibaba/MNN#2025]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):
Compiling on: MacOS
Running on: Android on Qualcomm snapdragon 845

# Github版本:
# Github Version:

719910c1

# 编译方式:
# Compiling Method
By build.gradle in the Android demo app
```
            cmake {
                arguments "-DANDROID_ARM_NEON=TRUE", "-DANDROID_PLATFORM=android-21", "-DANDROID_STL=c++_shared", "-DMNN_JNI=TRUE", "-DMNN_OPENCL=true", "-DMNN_VULKAN=true", "-DMNN_OPENGL=true", "-DCMAKE_BUILD_TYPE=Release"
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
```
#  The problem
We convert [CRAFT](https://github.com/clovaai/CRAFT-pytorch) model to onnx and then to mnn format. When we run the model on Android with FORWARD_OPENCL, it takes mNetInstance.createSession more than 5 minutes to finish. After loading, the model runs successfully. We also tried createSession with FORWARD_VULKAN or CPU, and both got loaded quickly.

We looked into the createSession call with FORWARD_OPENCL, and looks like it got stuck on the following line:
In interpreter.cpp:
```result->resize(mNet->net->usage() == Usage_INFERENCE_STATIC);```
which calls the following in Session.cpp:
```auto error = iter->allocMemory(firstMalloc);```
and further in one of the for loops in Pipeline.cpp.

Would you please advise if there is any way to reduce the createSession time?

**Comment by jxt1234** [comment]
Set numberThread to 1 to avoid auto-tuning

**Comment by jianzhangru** [comment]
It is working. Thank you!
