### ISSUE TITLE
mnnWorkbench  按照操作登录不上

### ISSUE THREAD

**Issue by zhanglaplace** [alibaba/MNN#2028]
![image](https://user-images.githubusercontent.com/12178974/186299772-23179314-544e-4be3-95a7-c5cba28c85ee.png)

ram授权、cookie清除，按照文档指引都做了，

**Comment by beyonehan** [comment]
同样问题，也是搞了很久没有解决

**Comment by zhanglaplace** [comment]
> 同样问题，也是搞了很久没有解决

好像他们都没维护了。。都不见人处理issue的

**Comment by wangzhaode** [comment]
这个目前主要对内部使用
