### ISSUE TITLE
为何只提供AArch64的交叉编译，其他arm呢？

### ISSUE THREAD

**Issue by 17759205390** [alibaba/MNN#203]
@li-qing @nihui @llhe @intheway @80945

**Comment by 17759205390** [comment]
只提供了以下这些，那么我的是hisi3556，是himix200的编译器，ncnn是有提供chains的，你们咋没有呢？我该怎么办？
 @li-qing 
if( ARM_NAME STREQUAL "hisi3519v101" )
	set( CMAKE_SYSTEM_NAME Linux )
	set( CMAKE_SYSTEM_PROCESSOR armv7-a )
	set( CMAKE_C_COMPILER arm-hisiv500-linux-gcc)
	set( CMAKE_CXX_COMPILER arm-hisiv500-linux-g++)
	add_definitions(-mcpu=cortex-a17.cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4 -mno-unaligned-access -fno-aggressive-loop-optimizations -ffunction-sections -fdata-sections)
elseif( ARM_NAME STREQUAL "hisi3516d100" )
	set( CMAKE_SYSTEM_NAME Linux )
	set( CMAKE_SYSTEM_PROCESSOR armv7-a )
	set( CMAKE_C_COMPILER arm-hisiv300-linux-gcc)
	set( CMAKE_CXX_COMPILER arm-hisiv300-linux-g++)
	add_definitions(-mcpu=cortex-a7 -mfloat-abi=softfp -mfpu=neon-vfpv4)
elseif( ARM_NAME STREQUAL "hisi3518e200" )
	set( CMAKE_SYSTEM_NAME Linux )
	set( CMAKE_SYSTEM_PROCESSOR armv5 )
	set( CMAKE_C_COMPILER arm-hisiv300-linux-gcc)
	set( CMAKE_CXX_COMPILER arm-hisiv300-linux-g++)
	add_definitions()
elseif( ARM_NAME STREQUAL "arm-gnueabihf" )
	set( CMAKE_SYSTEM_NAME Linux )
	set( CMAKE_SYSTEM_PROCESSOR armv7-a )
	set( CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
	set( CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
	add_definitions( -mfloat-abi=hard -fsigned-char -marm -mfpu=neon -march=armv7-a -fvisibility=hidden)
elseif( ARM_NAME STREQUAL "aarch64-gnueabihf" )
	set( CMAKE_SYSTEM_NAME Linux )
	set( CMAKE_SYSTEM_PROCESSOR aarch64v )
	set( CMAKE_C_COMPILER aarch64-linux-gnueabihf-gcc)
	set( CMAKE_CXX_COMPILER aarch64-linux-gnueabihf-g++)
	add_definitions()
endif()

**Comment by li-qing** [comment]
交叉编译上 其他架构的在http://releases.linaro.org/components/toolchain/binaries/latest-7/也可以找到的…AArch64是给了个示例

**Comment by 17759205390** [comment]
> 交叉编译上 其他架构的在[http://releases.linaro.org/components/toolchain/binaries/latest-7/也可以找到的…AArch64是给了个示例](http://releases.linaro.org/components/toolchain/binaries/latest-7/%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9A%84%E2%80%A6AArch64%E6%98%AF%E7%BB%99%E4%BA%86%E4%B8%AA%E7%A4%BA%E4%BE%8B)

@li-qing 编译器我有，我要toolchain呀，所有芯片的toolchain都有吗？

**Comment by 17759205390** [comment]
> 交叉编译上 其他架构的在[http://releases.linaro.org/components/toolchain/binaries/latest-7/也可以找到的…AArch64是给了个示例](http://releases.linaro.org/components/toolchain/binaries/latest-7/%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9A%84%E2%80%A6AArch64%E6%98%AF%E7%BB%99%E4%BA%86%E4%B8%AA%E7%A4%BA%E4%BE%8B)

@li-qing 没有找到himix200的chain，我有编译器，只需要编译选项那几行提供给我就行了，这个应该你们mnn官方要提供吧

**Comment by li-qing** [comment]
> > 交叉编译上 其他架构的在[http://releases.linaro.org/components/toolchain/binaries/latest-7/也可以找到的…AArch64是给了个示例](http://releases.linaro.org/components/toolchain/binaries/latest-7/%E4%B9%9F%E5%8F%AF%E4%BB%A5%E6%89%BE%E5%88%B0%E7%9A%84%E2%80%A6AArch64%E6%98%AF%E7%BB%99%E4%BA%86%E4%B8%AA%E7%A4%BA%E4%BE%8B)
> 
> @li-qing 没有找到himix200的chain，我有编译器，只需要编译选项那几行提供给我就行了，这个应该你们mnn官方要提供吧

https://www.yuque.com/mnn/cn/build_linux 本质上也就是示例改两行
