### ISSUE TITLE
 MNNConvert  --saveStaticModel true crash on ubuntu

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2030]
2.04 2.05版本  --saveStaticModel true
MNNConvert.exe -f ONNX --modelFile superpoint.onnx --MNNModel superpoint.mnn --bizCode MNN   --saveStaticModel true  windows上没有结果输出

ubuntu 上会崩溃
./MNNConvert -f ONNX --modelFile ./superpoint.onnx --MNNModel ./superpoint.mnn --bizCode MNN   --saveStaticModel true

如果不加 --saveStaticModel true 都可以导出

**Comment by jxt1234** [comment]
相关模型可以发一下?

**Comment by lvyong1943** [comment]
https://pan.baidu.com/s/1EvTlnVxvVoqrPXGgkTTNZw?pwd=1234
这个onnx 模型用 onnxruntime是有结果的。就是这个转成mnn模型，input_tensor 里的mDescribe 的backend指针一直是空的

**Comment by lvyong1943** [comment]
> 相关模型可以发一下?

我刚试了一下2.1还是不行.
模型在网盘里
https://pan.baidu.com/s/1EvTlnVxvVoqrPXGgkTTNZw?pwd=1234
这个onnx 模型用 onnxruntime是有结果的。就是这个转成mnn模型，input_tensor 里的mDescribe 的backend指针一直是空的

**Comment by lvyong1943** [comment]
> 相关模型可以发一下?

就是我找到模型不能运行的原因了有一个算子不支持torch.nonzero,取tenser的非0数据索引这个，会报错。如果不用这个算子，结果能出来。我看源码里onnx也有nonzero这个算子呀，很奇怪！

**Comment by MirrorYuChen** [comment]
问题解决了吗？
