### ISSUE TITLE
在amd athlon ii x4 631 quad-core processor 2.60 ghz平台奔溃了

### ISSUE THREAD

**Issue by hg123-we** [alibaba/MNN#2036]
系统windows 7
cpu： amd athlon ii x4 631 quad-core processor 2.60 ghz
mnn版本：1.2.0

在此平台有些mnn推理正常，但现在碰到了一个可以无限复现的bug，一直推理失败，导致程序奔溃，然在其它平台暂未见过，以下是dmp文件奔溃信息，问一下是否某个算子在此平台不兼容

**崩溃调用栈：**
![image](https://user-images.githubusercontent.com/56747555/187420175-4dd99643-9d0c-4a98-8a8f-13fd03570b5e.png)

**.frame 0**
![image](https://user-images.githubusercontent.com/56747555/187418998-8c57b58f-91ad-4122-bd69-89fbb6973a8f.png)

**.frame 1**
![image](https://user-images.githubusercontent.com/56747555/187419228-e3a44704-1cef-4e33-8392-4872447ab236.png)

**.frame 2**
![image](https://user-images.githubusercontent.com/56747555/187419534-85271e9d-3073-4556-9901-9017a3cfb03a.png)

**.frame3**
![image](https://user-images.githubusercontent.com/56747555/187419740-45a34e61-47e0-4be8-9e53-627a71e01914.png)

**.frame4**
![image](https://user-images.githubusercontent.com/56747555/187420041-04904974-570b-47a9-9ea7-6e50b4c1bc54.png)

**Comment by wangzhaode** [comment]
这个[处理器](https://www.cpu-world.com/CPUs/K10/AMD-Athlon%20II%20X4%20631%20-%20AD631XWNZ43GX%20(AD631XWNGXBOX).html)不支持SSE 4.1 所以在执行`_mm_mullo_epi32 `时crash了

在编译时禁用SSE，应该可以正确执行

**Comment by hg123-we** [comment]
感谢，已成功执行

**Comment by dttlgotv** [comment]
> 感谢，已成功执行

 这样的话就无法使用sse的指令集了，会变慢很多。

还是希望mnn在这些不支持sse4.1的处理器上能够支持 sse sse2 或者 sse3等指令集。

**Comment by dttlgotv** [comment]
> 这个[处理器](https://www.cpu-world.com/CPUs/K10/AMD-Athlon%20II%20X4%20631%20-%20AD631XWNZ43GX%20(AD631XWNGXBOX).html)不支持SSE 4.1 所以在执行`_mm_mullo_epi32 `时crash了
> 
> 在编译时禁用SSE，应该可以正确执行

 这样的话就无法使用sse的指令集了，会变慢很多。

还是希望mnn在这些不支持sse4.1的处理器上能够支持 sse sse2 或者 sse3等指令集。

**Comment by wangzhaode** [comment]
sse / sse2 / sse3是支持的 只是我们SSE 目前是默认使用全功能的SSE的，如果你必须使用不支持SSE4.1的处理器，可以自行搜索到相关指令修改；或者把使用SSE 4.1指令的函数改成用不使用SSE的实现
