### ISSUE TITLE
最新release版本，崩溃在AMD Athlon(tm) II X4 631 处理器。

### ISSUE THREAD

**Issue by dttlgotv** [alibaba/MNN#2041]
版本2.1.0

奔溃调用栈：
![1662103273195](https://user-images.githubusercontent.com/5996999/188081298-ba29cd9f-440b-4061-8922-d1ddfe324673.png)

这个处理器不支持sse4.1，但是mnn代码里面使用了 sse4.1的指令函数，所以crash了。

mnn是否会增加别的sse指令集(sse sse2 sse3)来支持更多的低端cpu 加速推理？

**Comment by jxt1234** [comment]
了解，后面会对 sse3 做兼容处理

**Comment by wangzhaode** [comment]
最新版本代码已修复该问题
