### ISSUE TITLE
调用  release      MNN::BufferAllocator::Node::~Node() + 52  crash

### ISSUE THREAD

**Issue by fndppx** [alibaba/MNN#2043]
# 平台(如果交叉编译请再附上交叉编译目标平台):  iOS
# Platform(Include target platform as well if cross-compiling):  

# Github版本:1.2.7
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式: 官方脚本编译
![image](https://user-images.githubusercontent.com/7971897/188534283-e6795a91-a4d7-4398-85db-ddd194ba17a4.png)

调用  release      MNN::BufferAllocator::Node::~Node() + 52  crash

<img width="844" alt="image" src="https://user-images.githubusercontent.com/7971897/188534452-ce732514-4e36-49c1-8ce0-b9ceaae2fd2b.png">

**Comment by jxt1234** [comment]
1. 建议使用 project/ios 下面的 xcode 编译 MNN framework
2. 是必现的么，复现代码可以发一下？
3. 更新到最新 2.1.0 试一下？

**Comment by fndppx** [comment]
😂不好复现，线上几十万用户出现了10几次，好的，这边升级下mnn试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 下午5:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/MNN] 调用  release      MNN::BufferAllocator::Node::~Node() + 52  crash (Issue #2043)




  
建议使用 project/ios 下面的 xcode 编译 MNN framework
 
是必现的么，复现代码可以发一下？
 
更新到最新 2.1.0 试一下？
