### ISSUE TITLE
想一下，mnn可以在dsp这种芯片上部署吗

### ISSUE THREAD

**Issue by chaotiaor** [alibaba/MNN#2044]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by wangzhaode** [comment]
具体是哪种dsp呢？目前MNN最新版本支持NNAPI，看看能否调用到你所用的DSP

**Comment by chaotiaor** [comment]
你好，是adi的dsp，是裸板，没有协议层




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/MNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月1日(星期二) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/MNN] 想一下，mnn可以在dsp这种芯片上部署吗 (Issue #2044)





 
具体是哪种dsp呢？目前MNN最新版本支持NNAPI，看看能否调用到你所用的DSP

**Comment by chaotiaor** [comment]
你好，谢谢回复，我已经使用c语言写了一套框架，可以在板子上部署




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月15日(星期三) 晚上8:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/MNN] 想一下，mnn可以在dsp这种芯片上部署吗 (Issue #2044)





  
你好，是adi的dsp，是裸板，没有协议层
  
这是不支持的
