### ISSUE TITLE
索引之后跟Pooling转出来的结构过于复杂

### ISSUE THREAD

**Issue by frspring** [alibaba/MNN#2045]
版本是2.0.1，对于以下结构（ONNX,ir version7）
![WXWorkCapture_16624458118763](https://user-images.githubusercontent.com/23132977/188563009-df8244d5-d444-4c1b-a555-9f4cb8e943b6.png)
MNN转出来的结构如下：
![WXWorkCapture_166244581922](https://user-images.githubusercontent.com/23132977/188563146-096f38bf-c52e-4981-a9ad-dcfe1c8079e7.png)
TNN转出来结构如下：

![WXWorkCapture_16624542836916](https://user-images.githubusercontent.com/23132977/188591703-2d7f9169-b6b8-41e9-b33e-68aa8d2d938d.png)

**Comment by jxt1234** [comment]
MNN 的 strideslice  op 参考 TF 实现，与 ONNX 的 slice 不完全一致，有一定的胶水算子，这个不影响实际运行性能

**Comment by frspring** [comment]
但是这里使用tflite转换结果也是比较简单的，如下图
![WXWorkCapture_1662457496842](https://user-images.githubusercontent.com/23132977/188605437-87e4873f-8cf2-4c19-9781-0a6b2b011898.png)


另外实际运行存在问题。进行等价操作
`
x[:,1:2] = pool(x[:,1:2])
x = function(x[:,0:1],x[:,1:2])
`
和
`
x = function(x[:,0:1],pool(x[:,1:2]))
`
在pytorch上结果一致
在MNN上结果差异巨大（高精度模式、OPENCL）

**Comment by frspring** [comment]
> MNN 的 strideslice op 参考 TF 实现，与 ONNX 的 slice 不完全一致，有一定的胶水算子，这个不影响实际运行性能
