### ISSUE TITLE
pytorch ->onnx->MNN 推理结果完全错乱 

### ISSUE THREAD

**Issue by dwygs** [alibaba/MNN#2046]
MNN已更新到最新的2.1.0版本
模型转换工具按照语雀的教程编译；模型推理部分直接在GitHub下载的
期望输出结果值域（0，1±），但是实际推理结果都是10e-19或10e+19级别的值；
已确认模型输入无误且验证了pytorch转onnx正确，模型转MNN时候报了这两行：
287 op name is empty or dup, set to Unsqueeze287
421 op name is empty or dup, set to Unsqueeze421
如果只是Unsqueeze 的问题的话，推理结果不会偏差如此大，所以想请教一下是不是哪步出错了

**Comment by dwygs** [comment]
> MNN已更新到最新的2.1.0版本 模型转换工具按照语雀的教程编译；模型推理部分直接在GitHub下载的 期望输出结果值域（0，1±），但是实际推理结果都是10e-19或10e+19级别的值； 已确认模型输入无误且验证了pytorch转onnx正确，模型转MNN时候报了这两行： 287 op name is empty or dup, set to Unsqueeze287 421 op name is empty or dup, set to Unsqueeze421 如果只是Unsqueeze 的问题的话，推理结果不会偏差如此大，所以想请教一下是不是哪步出错了

已解决

**Comment by jxt1234** [comment]
"op name is empty or dup, set to" 这个一般原因是在模型转换过程中引入了新的胶水 op ，需要加个命名，不影响模型转换结果

**Comment by MrZhouWenBo** [comment]
> > MNN已更新到最新的2.1.0版本 模型转换工具按照语雀的教程编译；模型推理部分直接在GitHub下载的 期望输出结果值域（0，1±），但是实际推理结果都是10e-19或10e+19级别的值； 已确认模型输入无误且验证了pytorch转onnx正确，模型转MNN时候报了这两行： 287 op name is empty or dup, set to Unsqueeze287 421 op name is empty or dup, set to Unsqueeze421 如果只是Unsqueeze 的问题的话，推理结果不会偏差如此大，所以想请教一下是不是哪步出错了
> 
> 已解决

你好，我也是遇到了该类问题，量化后结果结果偏差很大，请问您是通过什么途径解决的

**Comment by BeingGod** [comment]
> > MNN已更新到最新的2.1.0版本 模型转换工具按照语雀的教程编译；模型推理部分直接在GitHub下载的 期望输出结果值域（0，1±），但是实际推理结果都是10e-19或10e+19级别的值； 已确认模型输入无误且验证了pytorch转onnx正确，模型转MNN时候报了这两行： 287 op name is empty or dup, set to Unsqueeze287 421 op name is empty or dup, set to Unsqueeze421 如果只是Unsqueeze 的问题的话，推理结果不会偏差如此大，所以想请教一下是不是哪步出错了
> 
> 已解决

同问，我这测试发现使用SessionAPI反序列化的模型推理结果是正确的，但是使用ModuleAPI反序列化的模型推理结果是错误的。怀疑可能与SessionAPI采用查找下标的方式进行反序列化，ModuleAPI采用查找名称的方式进行反序列化的方式有关。
