### ISSUE TITLE
多输入多输出模型转换出错

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#2050]
我在转换多输入多输出的模型时候结果不对，使用fastTestOnnx.py报如下的错误，请问如何定位是哪个位置转换出问题了呢？
![image](https://user-images.githubusercontent.com/22525811/188896387-2da7a7f0-6993-4992-b8de-077046910efe.png)

```

**Comment by jxt1234** [comment]
1. 先确保 mnn 代码是最新的，如果是最新代码仍然报这个错误，相关模型发我们排查一下
2. 参考 https://mnn-docs.readthedocs.io/en/latest/tools/convert.html ，传 DEBUG 去尝试定位
