### ISSUE TITLE
pymnn和C++推理结果不一致

### ISSUE THREAD

**Issue by mutouoa** [alibaba/MNN#2052]
pymnn和C++推理结果不一致

**Comment by mutouoa** [comment]
@jxt1234

**Comment by ld-xy** [comment]
macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？

```
    tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
                            MNN.Tensor_DimensionType_Caffe)
    output_tensor.copyToHostTensor(tmp_output)
```

如果可以的话，怎么转换啊，求助！！！

**Comment by lyyiangang** [comment]
> 

先转换为numpy.array,  然后torch.from_numpy

**Comment by wangzhaode** [comment]
清给出具体的复现方法

**Comment by wangzhaode** [comment]
> macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> 
> ```
>     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
>                             MNN.Tensor_DimensionType_Caffe)
>     output_tensor.copyToHostTensor(tmp_output)
> ```
> 
> 如果可以的话，怎么转换啊，求助！！！

```python
np_data = output_tensor.read() # convert to numpy.ndarray
torch_data = torch. from_numpy(np_data) # convert ndarray to torch.Tensor
```
