### ISSUE TITLE
Expr模型输入维度获取有误

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#2055]
onnx模型输入大小为[1, 131, 80]，转为MNN后使用Interperter方法加载模型输入为[1, 131, 80]，但是使用Expr方法加载模型，通过getInfo()->size获取的输入大小为[1, 132, 80]，请问这是什么错误。

**Comment by Ryuk17** [comment]
![image](https://user-images.githubusercontent.com/22525811/189343307-ab6ad381-7538-403d-b608-23069da6f856.png)
模型输入为chunk，那么它的size应该是1*131*80 = 10480，但是这里计算的是10560

**Comment by jxt1234** [comment]
是否是不同的输入节点

**Comment by Ryuk17** [comment]
用_ChangeInputFormat修改为NCHW后，Expr的size也正确了。Expr和Interperter加载模型有什么差别吗？

**Comment by jxt1234** [comment]
Expr 的 getInfo()->size 是按 NC4HW4 去算的
