### ISSUE TITLE
输出一个1280*720的单通道图片时，iphone xr上 copyToHostTensor耗时非常长（27ms左右）怎么破

### ISSUE THREAD

**Issue by anliyuan** [alibaba/MNN#2057]
是在METAL上做的推理

**Comment by ld-xy** [comment]
macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？

```
    tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
                            MNN.Tensor_DimensionType_Caffe)
    output_tensor.copyToHostTensor(tmp_output)
```

如果可以的话，怎么转换啊，求助！！！

**Comment by anliyuan** [comment]
> macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> 
> ```
>     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
>                             MNN.Tensor_DimensionType_Caffe)
>     output_tensor.copyToHostTensor(tmp_output)
> ```
> 
> 如果可以的话，怎么转换啊，求助！！！

转成numpy再转成tensor吧

**Comment by ld-xy** [comment]
> > macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> > ```
> >     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
> >                             MNN.Tensor_DimensionType_Caffe)
> >     output_tensor.copyToHostTensor(tmp_output)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果可以的话，怎么转换啊，求助！！！
> 
> 转成numpy再转成tensor吧

请问一下，具体的代码有吗？我使用下面代码转的，产生的结果保存图片缺模糊了（我的模型是做压缩和重建的）
`y = torch.from_numpy(y.getNumpyData())`

**Comment by anliyuan** [comment]
> > > macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> > > ```
> > >     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
> > >                             MNN.Tensor_DimensionType_Caffe)
> > >     output_tensor.copyToHostTensor(tmp_output)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果可以的话，怎么转换啊，求助！！！
> > 
> > 
> > 转成numpy再转成tensor吧
> 
> 请问一下，具体的代码有吗？我使用下面代码转的，产生的结果保存图片缺模糊了（我的模型是做压缩和重建的） `y = torch.from_numpy(y.getNumpyData())`

没怎么用python搞过mnn😂，不过为什么需要混着用呢？直接用pytorch不就行了？

**Comment by ld-xy** [comment]
> > > > macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> > > > ```
> > > >     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
> > > >                             MNN.Tensor_DimensionType_Caffe)
> > > >     output_tensor.copyToHostTensor(tmp_output)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 如果可以的话，怎么转换啊，求助！！！
> > > 
> > > 
> > > 转成numpy再转成tensor吧
> > 
> > 
> > 请问一下，具体的代码有吗？我使用下面代码转的，产生的结果保存图片缺模糊了（我的模型是做压缩和重建的） `y = torch.from_numpy(y.getNumpyData())`
> 
> 没怎么用python搞过mnn😂，不过为什么需要混着用呢？直接用pytorch不就行了？

哈哈，相比较一下onnx，mnn，ncnn，tnn这几个速度，就目前来看，onnx在python调用推理时竟然是最快的，，，，，，
