### ISSUE TITLE
/MNN/tools/converter/source/cli.cpp:98: Model File Does Not Exist!

### ISSUE THREAD

**Issue by wuxiaolianggit** [alibaba/MNN#206]
/MNN/tools/converter/source/cli.cpp:98: Model File Does Not Exist!请问各位大佬，这个怎么解决

**Comment by wuxiaolianggit** [comment]
@nihui @llhe @intheway @li-qing

**Comment by czy2014hust** [comment]
Model File Does Not Exist!
