### ISSUE TITLE
MNN申请的Tensor如何释放

### ISSUE THREAD

**Issue by Ryuk17** [alibaba/MNN#2064]
我用这种方式申请的Tensor
![image](https://user-images.githubusercontent.com/22525811/190596687-f7ad34be-abb6-4543-8459-f57265d3f620.png)
然后使用`delete output_tensor`删除，使用valgrind还是检测到内存泄漏
![image](https://user-images.githubusercontent.com/22525811/190597507-46eb5925-8c0f-4149-bdd1-d0892147e2f9.png)

**Comment by jxt1234** [comment]
new / create 出来的 tensor delete 就行，你这个内存泄露应该不是 Tensor 里面的

**Comment by ld-xy** [comment]
macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？

```
    tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
                            MNN.Tensor_DimensionType_Caffe)
    output_tensor.copyToHostTensor(tmp_output)
```

如果可以的话，怎么转换啊，求助！！！

**Comment by Ryuk17** [comment]
> macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> 
> ```
>     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
>                             MNN.Tensor_DimensionType_Caffe)
>     output_tensor.copyToHostTensor(tmp_output)
> ```
> 
> 如果可以的话，怎么转换啊，求助！！！
我记得好像可以转numpy的，然后numpy转torch.tensor

**Comment by ld-xy** [comment]
> > macos平台：使用下面这两行代码，得到的类型是MNN.tensor类型，这种类型能转化成torch.tensor然后接着执行模型下面的代码吗？
> > ```
> >     tmp_output = MNN.Tensor((1, 240, 384), MNN.Halide_Type_Float, np.ones([1, 240, 384]).astype(np.float32),
> >                             MNN.Tensor_DimensionType_Caffe)
> >     output_tensor.copyToHostTensor(tmp_output)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果可以的话，怎么转换啊，求助！！！
> > 我记得好像可以转numpy的，然后numpy转torch.tensor

请问一下，有具体代码吗？为使用下面的代码转了一下，保存的结果图片变模糊了(我的模型是图像压缩重建的)
`y = torch.from_numpy(y.getNumpyData())`

**Comment by Ryuk17** [comment]
内存泄漏解掉了：
1）申请的Tensor要及时delete
2）Interpreter releaseModel后也要delete
3）但是还有少部分内存处于still reachable状态

**Comment by wangdada-love** [comment]
我看官方文档里面说自己申请的tensor通过destroy方法可以释放。并且interpreter使用完之后modelrelease即可释放模型资源，还有session使用完之后也要releaseSession。可是我执行完这一套之后，发现内存一点都没有减少，之后我又加了delete， 但是内存仍然没有减少。感觉好奇怪。
