### ISSUE TITLE
yolov5n安卓部署mnn --weightQuantBits检测无效

### ISSUE THREAD

**Issue by Derek-Kun** [alibaba/MNN#2069]
训练好的yolov5n, 部署在安卓摄像头上，用正常的--fp16量化的能正常检测，但是用 --weightQuantBits 8量化后，检测的模型加载后完全没有在检测，fps一直50多，请问用--weightQuantBits 8量化后加载模型有什么不一样的地方吗？

**Comment by wangzhaode** [comment]
这个选项是仅权值量化为了降低模型大小用的；使用8bit量化可能会丢失精度；
