### ISSUE TITLE
how can i use build shell to build opencl opengl vulkan

### ISSUE THREAD

**Issue by jabinwang** [alibaba/MNN#207]

**Comment by czy2014hust** [comment]
check out [here](https://github.com/alibaba/MNN/blob/master/doc/Install_EN.md#android)

**Comment by jabinwang** [comment]
when i build vulkan ,hava a  problem 
MNN/source/backend/vulkan/compiler/AllShader.cpp:81:7: error: 
      expected unqualified-id
const 
      ^
79 warnings and 1 error generated.

**Comment by jabinwang** [comment]
how to solve it @czy2014hust

**Comment by czy2014hust** [comment]
What kind of platform you use to build MNN vulkan library?

**Comment by jabinwang** [comment]
i have solved it ,using  lastest code
