### ISSUE TITLE
torch nonzero not support

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2076]
pytorch 里nonzero 获取指定索引这个算子只要加上，导成onnx再专成mnn模型就会崩溃。如果不用这个算子，就不会崩溃。windows linux都会崩溃。用的最新的版本。

**Comment by wangzhaode** [comment]
麻烦发一下crashlog，或者提供一下onnx模型

**Comment by jxt1234** [comment]
先用 fastTestOnnx.py 测试。
另外这个算子不满足形实分离条件，加入后需要用 Module API 运行：https://mnn-docs.readthedocs.io/en/latest/inference/module.html
