### ISSUE TITLE
MNNConvert支持ONNX量化模型的转换吗

### ISSUE THREAD

**Issue by mjp9527** [alibaba/MNN#2084]
使用MNNConvert转换ONNX量化模型时报错
Start to Optimize the MNN Net.
Convolution should know weight shape infromation!
Convert Onnx's Op conv2d_81.tmp_0, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!
Convert Onnx's Op depthwise_conv2d_@.tmp_0, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!
Convert Onnx's Op conv2d_82.tmp_0, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!
Convert Onnx's Op conv2d 83.tmp 0
, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!
Convert Onnx's Op conv2d_84.tmp_0, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!
Convert Onnx's Op conv2d 85. tmp 0, type = Conv, failed, may be some node is not const
Convolution should know weight shape infromation!

量化模型格式如下：
<img width="474" alt="image" src="https://user-images.githubusercontent.com/54735487/192719645-cf0c76af-593d-471f-93cc-66f05cf5900a.png">

**Comment by mjp9527** [comment]
These Op Not Support: ONNX::Conv | ONNX::DequantizeLinear | ONNX::QuantizeLinear

**Comment by jxt1234** [comment]
目前不支持

**Comment by mjp9527** [comment]
> 目前不支持

请问目前MNN自己的工具只支持 卷积层 的量化吗
