### ISSUE TITLE
苹果m1 macbook metal后端循环运行推理时候内存持续增长

### ISSUE THREAD

**Issue by RobbertOnly** [alibaba/MNN#2085]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
 mac m1 macbook 
macos version :12.5.1
CMAKE_OSX_ARCHITECTURES: x86_64

# Github版本:
# Github Version:
v2.1.0

# 编译方式:
# Compiling Method
Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 

3.19.0.0
Use Threadpool, forbid openmp
>>>>>>>>>>>>>
MNN BUILD INFO:
	System: Darwin
	Processor: x86_64
	Version: 2.1.0
	Metal: ON
	OpenCL: ON
	OpenGL: OFF
	Vulkan: OFF
	ARM82: OFF
	oneDNN: OFF
	TensorRT: OFF
	CoreML: OFF
	CUDA: OFF
	OpenMP: OFF
	BF16: OFF
	ThreadPool: ON
	Hidden: TRUE
	Build Path: /Users/eeo/MNN/build
WIN_USE_ASM: 
x86_64: Open SSE
MNN_AVX512:ON
Onnx: 
Configuring done

# 编译日志:
# Build Log:
[Build MNN_2022-09-29T14-59-59.txt](https://github.com/alibaba/MNN/files/9671931/Build.MNN_2022-09-29T14-59-59.txt)

测试代码片段如下图： 模型使用的是demo Portrait.tflite.mnn
<img width="734" alt="截屏2022-09-29 15 04 49" src="https://user-images.githubusercontent.com/24694993/192962928-eedcf6f5-72c8-483a-a054-66a9515fe933.png">

**Comment by jxt1234** [comment]
Metal 内部是 OC 的引用计数对象，需要在 OC 代码中释放，参考 https://cloud.tencent.com/developer/article/1615642 用 autoreleasepool 括住 runSession 运行
