### ISSUE TITLE
可以在windows 10 利用vs2015编译MNN吗

### ISSUE THREAD

**Issue by wuxiaolianggit** [alibaba/MNN#209]

**Comment by wuxiaolianggit** [comment]
请问各位大佬，可以在windows 10 利用vs2015编译MNN吗 @llhe @intheway @li-qing

**Comment by xingyanan** [comment]
可以的

**Comment by huillll** [comment]
谁给我发个MMN的windows lib啊，感激不尽啊

**Comment by wuxiaolianggit** [comment]
在windows编译出错，D:\workspace\MNN\source\core\Backend.cpp(12): fatal error C1083: 无法打开包括文件: “MNN_generated.h”: No such file or directory，该怎么解决呢 @xingyanan

**Comment by xingyanan** [comment]
你需要先用powershell运行 schema/generate.ps1 ,这个脚本会生成MNN_generated.h，还可能遇到字符编码不对的问题，需要在windows语言设置，设置非unicode语言为英语-美国@wuxiaolianggit
