### ISSUE TITLE
setCacheFile GPU模型初始化不起作用，耗时没有减少

### ISSUE THREAD

**Issue by ly0303521** [alibaba/MNN#2090]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# android设备，MTK GPU

GPU模型初始化，刚开始有一个299KB的模型，一个937KB的模型，一个1.1M的模型，使用“MNN_GPU_TUNING_NONE | MNN_GPU_MEMORY_IMAGE” 模式初始化模型耗时6秒左右，但是现在增加一个1.9M的模型，初始化耗时增加至35秒左右，并且使用setCacheFile没有起到提速的效果

**Comment by ly0303521** [comment]
你们的钉钉交流群没有了吗，扫码进去竟然是疫情防控，输入群号却搜索不到

**Comment by wangzhaode** [comment]
> 你们的钉钉交流群没有了吗，扫码进去竟然是疫情防控，输入群号却搜索不到

已更新

**Comment by wangzhaode** [comment]
setCacheFile之后，首次速度没有提升，之后使用会有加速

**Comment by CloudGuardian** [comment]
> setCacheFile之后，首次速度没有提升，之后使用会有加速

请问我也是在Android下调用setCacheFile，报错：“Load Cache file error”

**Comment by CloudGuardian** [comment]
> setCacheFile之后，首次速度没有提升，之后使用会有加速

请问我使用setCacheFile之后，第二次load是成功了，但是速度没有提升，主要是createSession的时间很长
