### ISSUE TITLE
在opencCL环境下模型出现cl::Kernel崩溃问题

### ISSUE THREAD

**Issue by heartXXkiller** [alibaba/MNN#2091]
使用OpenCL1.2的库，和MNN项目中3rd_party的CL头文件编译出来的MNN库在导入模型到GPU上会出现cl::Kernel创建崩溃的问题，创建的program是buffer_to_image，核函数名是conv2d_filter_image_to_buffer，是不是需要在编译的时候增加一些宏控制OpenCL头文件版本适配1.2，还是这是别的什么原因？
```

**Comment by bitxsw93** [comment]
请贴上具体崩溃日志，你使用的机器以及可以复现的代码。
