### ISSUE TITLE
GPU的运行耗时问题

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2092]
在调用opencl时，如果不设置mode, 同时设置numThread  ，运行耗时会比cpu快，
但为了减少初始化时间，设置mode 为 MNN_GPU_TUNING_NONE | MNN_GPU_MEMORY_IMAGE ，同事注释掉numThread ，此时运行耗时就会变慢。
      请问mode设置会影响运行耗时吗？如何避免呢，谢谢

**Comment by jxt1234** [comment]
mode 和 numberThread 是共用一个数据位置的，会互相覆盖。只设其中一个即可

**Comment by keke444** [comment]
> mode 和 numberThread 是共用一个数据位置的，会互相覆盖。只设其中一个即可

那我们设置了mode 后，不设numberThread  ，默认线程是多少呢，是自动的吗
