### ISSUE TITLE
ONNX模型转换成MNN模型后，fp16推理失败！

### ISSUE THREAD

**Issue by wz1qqx** [alibaba/MNN#2093]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux+arm

# Github版本:
# Github Version:
最新分支

# 编译方式:
# Compiling Method
sed -i '11 a -DMNN_OPENCL=ON \\' MNN/project/android/build_64.sh
sed -i '12 a -DMNN_ARM82=ON \\' MNN/project/android/build_64.sh
sed -i 's/DMNN_BUILD_TEST=ON/DMNN_BUILD_TEST=OFF/' MNN/project/android/build_64.sh
./schema/generate.sh
sed -i 's/int precision = BackendConfig::Precision_High;/int precision = BackendConfig::Precision_Low;/' ./tools/cpp/MNNV2Basic.cpp
cd project/android && rm -rf build_64_fp16 && mkdir build_64_fp16 && cd build_64_fp16
../build_64.sh

./MNNV2Basic.out ../MNNModels/mnn/en_ocr_table_structure_infer.mnn 30 0 0 1 1x3x488x488

# 编译日志:
# Build Log:
Compute Shape Error for p2o.fill_constant_9.tmp_0.1/Loop

# 模型结构
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/55830058/195560353-24a23dc9-4161-4f13-9ea0-42931d0ac2a5.png">

**Comment by wangzhaode** [comment]
有控制流的模型不能使用V2接口；用Module接口跑推理；
