### ISSUE TITLE
MNN在 iOS 15.5 上用Metal GPU跑 Craft Model 内存使用2G

### ISSUE THREAD

**Issue by lengerfulluse** [alibaba/MNN#2094]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
"device_model" = "iPhone14,4";
    "device_osBuild" = "15.6.1 (19G82)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "sdk_canonicalName" = "iphoneos15.5";
    "sdk_osVersion" = "15.5";
    "sdk_variant" = iphoneos;

# Github版本:
# Github Version:

**git commit:** 4ba6232657c1a3dd95d96237ba17d3ce37656246

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

**直接run 自带的：./buildiOS.sh**

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
./buildiOS.sh

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

# 问题
用MNN CPU forward type 跑没问题，改成Metal之后，就会在runSession()的时候出现下面错误：**Terminated due to memory issue**
```
Domain: IDEDebugSessionErrorDomain
Code: 10
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
    DVTErrorCreationDateKey = "2022-10-17 22:27:52 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
```

```cpp
    auto modelInputTensor = _net->getSessionInput(_session, nullptr); 
    MNN::Tensor * inHostTensor = MNN::Tensor::create<float>(modelInputTensor->shape(), NULL, MNN::Tensor::CAFFE);
    for (int i = 0; i < inHostTensor->elementSize(); i++) {
        inHostTensor->host<float>()[i] = resizeOutput.resizeOutput[i];
    }
    modelInputTensor->copyFromHostTensor(inHostTensor);
    delete inHostTensor;
    delete resizeOutput.resizeOutput;
    _net->runSession(_session); // 出现crash的行
    char outputName[] = "outputy";
    MNN::Tensor *output = _net->getSessionOutput(_session, outputName);
```

不知道是应用端代码的memory leaking还是MNN Metal的问题，感谢！

**Comment by lengerfulluse** [comment]
用xcode profiler看了下，在用Metal type时，整体memory将近2GB，debug发现主要在这块内存急剧增加(Pipeline.cpp)：

```cpp
ErrorCode Pipeline::execute() {
    mBackend->onExecuteBegin();
    int i = 0;
    for (auto& info : mInfo) {
        printf("Current mInfo is %d\n", i++);
        auto& buffer = info.executeBuffer;
        for (auto& cmdP : buffer.command) {
            auto& cmd = *cmdP;
            auto code = cmd.execution->onExecute(cmd.inputs, cmd.outputs);
            if (NO_ERROR != code) {
                mBackend->onExecuteEnd();
                return code;
            }
        }
    }
    printf("Backend type is: %d\n", mBackend->type()); // 执行到这块时只要264MB
    mBackend->onExecuteEnd(); //执行到这块时要1.2 GB
    return NO_ERROR; // 执行到这行时要1.9 GB 
}
```
然后继续进入OnExecutionEnd() for Metal，发现主要在这块增加(MetalBackend.cpp)：
```cpp
void MetalBackend::onExecuteEnd() const {
    flushEncoder();
    auto ctx = (__bridge MNNMetalContext *)context();
    [ctx commit_net]; // 这块增加到1.9GB

    if(mFrameEncodeCache) {
        for(auto opEncoder : mOpEncoders) {
            opEncoder();
        }
        setOpEncoder();
    }
}
```

**Comment by hk19941214** [comment]
请问你这个问题解决了吗？我在mac上也遇到了内存泄漏的问题，用metal推理会有，cpu推理就不会有

**Comment by anliyuan** [comment]
> 请问你这个问题解决了吗？我在mac上也遇到了内存泄漏的问题，用metal推理会有，cpu推理就不会有

请问你这个问题解决了么？我遇到了相同的问题

**Comment by bitxsw93** [comment]
麻烦写下复现步骤，以及你出问题的模型

**Comment by hk19941214** [comment]
使用opencv采集摄像头视频，设置30帧，然后将采集图片灌进MNN里面做推理操作，需要设置模型为metal推理，任意卷积类的模型都可以，比如什么超分啊，分割啊之类的就会出现

**Comment by jxt1234** [comment]
最新版本优化了 Metal 的内存占用问题，在 2.4.1 之后再试试。仍然有问题新提 issue 吧
