### ISSUE TITLE
请问有没有mnn推理yolov5 6.2的官方例子？研究的结果对不上

### ISSUE THREAD

**Issue by ouxiand** [alibaba/MNN#2098]
请问有没有mnn推理yolov5 6.2的官方例子？研究的结果对不上，期望能回复

**Comment by jxt1234** [comment]
https://www.mnn.zone/m/0.3/

第三方的这里看看 https://github.com/techshoww/mnn-yolov5

另外参考 https://mnn-docs.readthedocs.io/en/latest/tools/convert.html 先校验模型

**Comment by ouxiand** [comment]
thx  先学习下
