### ISSUE TITLE
如何存Mnn的tensor结构的数据到图片里

### ISSUE THREAD

**Issue by Lannist** [alibaba/MNN#2099]
我使用MNN的官方接口做resize，推理结果和直接使用opencv，以及stb库的resize差异很大。
于是我想把MNN做完resize操作后的tensor数据存下来。
具体代码如下：
string tensorPath = "save.jpg";
pretreat->convert(input_img, IMG_WIDTH, IMG_HEIGHT, 0, input_tensor);
stbi_write_jpg( tensorPath.c_str(), input_tensor->width(), input_tensor->height(), input_tensor->channel(), input_tensor->buffer().host, 0);
存下来的图尺寸正常，但是一堆图像噪点。
我用fwrite写文件的方式，写的也不对
file = fopen(tensorPath ="save.jpg";
int size = input_tensor->height() * input_tensor->width() * input_tensor->channel()
fwrite(input_tensor->buffer().host, 1,  size, file);

请问，是不是Mnn:tensor结构体的数据存放结构和正常RGB通道不一样，要怎样能把tensor格式数据，存成图片显示

**Comment by jxt1234** [comment]
参考 demo/exec/pictureRotate.cpp 里面的存储方式，保证 mnn 的输出 tensor 是 uint8_t 且为 NHWC 格式即可
