### ISSUE TITLE
how to run some layers in gpu and others layer in cpu? 

### ISSUE THREAD

**Issue by biwe** [alibaba/MNN#210]
caffe to mnn; 
Since some layer, such as detectionout, is unsupported in gpu(opencl), we want to run backbone in gpu and others layers in cpu or how to assign some layers to run in cpu? thanks!

**Comment by czy2014hust** [comment]
You do not have to care about this problem, just specify the MNNForwardType. If one layer is not supported by GPU, it will run on CPU automatically.

**Comment by biwe** [comment]
> You do not have to care about this problem, just specify the MNNForwardType. If one layer is not supported by GPU, it will run on CPU automatically.

thanks,  it may produce different result between gpu(opencl) and cpu sometimes, such as flatten layer(gpu's wrong, why?), so  i want to run those layers in cpu.

**Comment by jxt1234** [comment]
You can set path in ScheduleConfig
