### ISSUE TITLE
Issues in document and python API.

### ISSUE THREAD

**Issue by DavdGao** [alibaba/MNN#2104]
# Platform(Include target platform as well if cross-compiling):  
ubuntu(x86)

# Github Version:
Version 2.0.0 and directly installed via pip.

# Issue
- First, the document in [yuque](https://www.yuque.com/mnn/cn/gsdegf) is outdated. The `PipelineModule` in section 1.1 "Convert other framework models to MNN trainable models" only loads the computation graph and cannot load parameters normally. Replace `PipelineModule` by `NN` is fine. 
- Second, in python API `F.load_as_dict()`(Version 2.0.0, python 3.7.13), when I load parameters from mnn file, and convert the `Var` arrary into numpy array by `read()`, sometimes partial data in numpy array will change into zero for unknown reasons (maybe memory leakage).
```
import MNN.expr as F
path_mnn = "..."
parameters = F.load_as_dict(path_mnn)

new_dict = dict()
for key, value in parameters.items():
    new_dict[key] = value.read()

# sometimes, partial values in new_dict will change into zero here!!!

```

**Comment by wangzhaode** [comment]
1. 新的文档链接：https://mnn-docs.readthedocs.io
2. load_as_dict中的tensor还未计算，有一些是随机值；
