### ISSUE TITLE
自己编译MNN2.2.0的windows x64位为啥比MNN1.2.8版本速度慢了很多

### ISSUE THREAD

**Issue by hbulaoma** [alibaba/MNN#2105]
自己编译的mnn，相同的调用代码。我测试2.2.0比1.2.8慢了将近一倍。网络结构很简单，就是OCR里的DBnet 和 CRNN，可能是什么原因呢？

**Comment by jxt1234** [comment]
CPU 支持的指令集是？MNN 运行时使用的是哪一套？SSE4 / AVX2 / AVX2FMA / AVX512 ?
单线程测试结果是？

**Comment by hbulaoma** [comment]
MNN_AVX512_VNNI宏开启，MNN::ScheduleConfig schedule_config;	schedule_config.numThread = 4;我都是用cmake-gui自动生成解决方案，编译静态库。我刚测试2.0.4速度也是正常的

**Comment by jxt1234** [comment]
代码上应该没什么大的改动，帮忙用 timeProfile 测试一下，找出变慢的算子？
另外可以把numThread都设成 1 测试下，会稳定些

**Comment by hbulaoma** [comment]
我用我们程序测试，速度是从2.1.2这个版本变慢的。以前的版本速度都正常，这个版本和2.2.0基本是一样的，慢了不少

**Comment by jxt1234** [comment]
单线程测试结果是? 你们的测试代码是?

**Comment by JiaoPaner** [comment]
这个问题+1  DBnet 和 CRNN 回退到2.0.3 速度正常 ,用9月份之后的版本 速度变慢2倍 ， 空了我给出 timeProfile的测试结果

**Comment by jxt1234** [comment]
检查是2.1.2 修改了  Winograd 启用的判断逻辑 ，2.2.2 更新后改了回去，可以更新再试试看，有问题再新建 issue
