### ISSUE TITLE
YOLOv5 量化问题

### ISSUE THREAD

**Issue by Hank880223** [alibaba/MNN#2106]
请问有人有成功将YOLOv5量化成功吗？
用MNN提供的量化工具，会出现下图的错误，在模型最后的输出会进行ReShape，使模型量化失败
![image](https://user-images.githubusercontent.com/84907438/199191919-41b381b9-fcc0-4921-8730-f45ae2c104cc.jpeg)

**Comment by dreamibor** [comment]
Any updates on this?

**Comment by yyfcc17** [comment]
试试最新的pymnn 2.4.0

**Comment by zhxsking** [comment]
原版yolov5的swish和detect头量化损失很大，量化时可考虑去掉
