### ISSUE TITLE
getPerformance在windows上面编译报错

### ISSUE THREAD

**Issue by feibuguocanghai** [alibaba/MNN#2107]
# 编译日志:
# Build Log:
1>getPerformance.cpp
1>MNN.lib(CPURuntime.obj) : error LNK2005: "int __cdecl MNNSetCPUThreadsMode(enum MNNCPUThreadsMode)" (?MNNSetCPUThreadsMode@@YAHW4MNNCPUThreadsMode@@@Z) 已经在 getPerformance.obj 中定义
1>MNN.lib(CPURuntime.obj) : error LNK2005: "float __cdecl MNNGetCPUFlops(unsigned int)" (?MNNGetCPUFlops@@YAMI@Z) 已经在 getPerformance.obj 中定义
1>MNN.lib(CPURuntime.obj) : error LNK2005: "void __cdecl cpuinfo_arm_init(struct cpuinfo_arm_isa *)" (?cpuinfo_arm_init@@YAXPEAUcpuinfo_arm_isa@@@Z) 已经在 getPerformance.obj 中定义

原因：
getPerformance.cpp  line 20：#include "backend/cpu/CPURuntime.cpp"

**Comment by wangzhaode** [comment]
感谢反馈，这个问题已经修复，等待合入

**Comment by wangzhaode** [comment]
Fixed
