### ISSUE TITLE
转换pb格式的多输出模型，convert后output节点不正确

### ISSUE THREAD

**Issue by VaneYb** [alibaba/MNN#2108]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MacOS

# Github版本:
# Github Version:
commit 6027a441d5bb13680e9c2c50c63254a57caca0fd

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

# 我的问题:
原本的pb模型是3输入3输出的，模型的输入输出应该为：
<img width="839" alt="image" src="https://user-images.githubusercontent.com/39575986/199636028-b88dc59d-c678-4e1c-b3e3-c36b3b0837cc.png">

但是转换到mnn格式后仅有一个输出，且不是真正的输出节点
![image](https://user-images.githubusercontent.com/39575986/199635896-ea0d827c-3916-42e0-9c3b-8e7747e503c5.png)

在使用fastTestTf.py检查时发现，我的模型中有type=’NoType‘的节点被当做了输入or输出节点而导致了错误。

不知道是不是我pb模型的问题，因为这个pb是从keras的.h5转过来的。模型在这里，麻烦帮忙看下
[model.pb.zip](https://github.com/alibaba/MNN/files/9925266/model.pb.zip)

**Comment by jxt1234** [comment]
Tensorflow 的 PB 并没有 output 节点名的信息，MNN 只能根据是否被引用来判断输出节点，但节点本身是存在模型中的，加载 MNN 时增加中间节点名即可：
https://mnn-docs.readthedocs.io/en/latest/inference/module.html

**Comment by VaneYb** [comment]
了解了，感谢解答~
