### ISSUE TITLE
release 2.2.0中bp16的结果图没有放上去。

### ISSUE THREAD

**Issue by jeezrick** [alibaba/MNN#2111]
如题，下图中提到的这个图没有放在release中，至少我刷新了好几次都没有看见。
![image](https://user-images.githubusercontent.com/47274616/199659677-f9251446-dc81-4ffc-b680-b5b6fc1a966e.png)

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/intro/releases.html#latest

**Comment by jeezrick** [comment]
> https://mnn-docs.readthedocs.io/en/latest/intro/releases.html#latest

谢谢！是我找资料的问题。

**Comment by wangzhaode** [comment]
github确实是漏掉了bf16的图 稍后补上 你先看文档里的吧
