### ISSUE TITLE
钉钉群搜不到?

### ISSUE THREAD

**Issue by Lenan22** [alibaba/MNN#2112]
你们的两个钉钉群怎么都搜不到呢？如何加入呢？
23329087
23350225

**Comment by jeezrick** [comment]
> 23329087

第一个可以搜到啊，我刚试了一下。

**Comment by Lenan22** [comment]
> > 23329087
> 
> 第一个可以搜到啊，我刚试了一下。

群里人数已经达到上限，我怎么加入啊？

**Comment by wsqat** [comment]
@Lenan22  换个浏览器，加第三个群

**Comment by wangzhaode** [comment]
可以扫码加群

**Comment by whr819987540** [comment]
可以更新一二维码吗？
