### ISSUE TITLE
onnx转MNN失败， ONNX::Cast报错Compute Shape Error for onnx::Cast

### ISSUE THREAD

**Issue by xingxinghanzi** [alibaba/MNN#2113]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows

# Github版本:
# Github Version:
2.1.0
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
.\package_scripts\win\build_lib.ps1 -path MNN-CPU-OPENCL/lib/x64 -backends "opencl,vulkan"
```

# 转换错误:
![7ERU75 @QWLH7ZAY_(H`XBU](https://user-images.githubusercontent.com/71701360/199728033-ad18016a-28c9-4197-a011-7dce22256795.png)

# onnx结构
![7FZ0O}DABJ%GA` TVS XA@P](https://user-images.githubusercontent.com/71701360/199727882-816b4916-d35d-4807-9a3b-cbf38d584032.png)

# MNN对应结构
![8$3H~HY0{H3)CLK`X1BB0YR](https://user-images.githubusercontent.com/71701360/199727643-0fa822a4-b9a0-4f16-8f21-391e025dbd8e.png)

# pytorch代码
![FOYY%TAS)Q(OFWWSCR Z3T](https://user-images.githubusercontent.com/71701360/199727738-5b4d6036-cc7a-4c3a-b8ba-1b83ac547caa.png)

# vs报错
![90ZRXS`DXO}}KF(BNCMHOJ](https://user-images.githubusercontent.com/71701360/199728792-ee7188b3-9e39-4638-a247-b14ae7cba12c.png)

**Comment by jxt1234** [comment]
用 fastTestOnnx.py 测试下

**Comment by xingxinghanzi** [comment]
@jxt1234   我要onnxruntime是可以正常运行的。   fastTestOnnx.py 测试结果

'''
Dir exist
onnx\test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(bool)
D:\MNN_compile\MNN-2.1.0-BK\tools\script\fastTestOnnx.py:146: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  inputs[inputVar.name] = np.random.uniform(0, 1, shapes).astype(np.bool)
tensor(float)
tensor(int32)
tensor(float)
['pred_bbox', 'max_score']
inputs:
x_patch
onnx/
x_mask
onnx/
feat_vec_z
onnx/
mask_vec_z
onnx/
pos_vec_z
onnx/
bbox
onnx/
resize_factor
onnx/
outputs:
onnx/pred_bbox.txt (4,)
onnx/
onnx/max_score.txt (1,)
onnx/
Start to Convert Other Model Format To MNN Model...
[18:09:25] :40: ONNX Model ir version: 6
Start to Optimize the MNN Net...
213 op name is empty or dup, set to Const213
280 op name is empty or dup, set to Shape280
291 op name is empty or dup, set to BinaryOp291
306 op name is empty or dup, set to Unsqueeze306
310 op name is empty or dup, set to Unsqueeze310
323 op name is empty or dup, set to BinaryOp323
539 op name is empty or dup, set to Const539
989 op name is empty or dup, set to Const989
1214 op name is empty or dup, set to Const1214
1439 op name is empty or dup, set to Const1439
2754 op name is empty or dup, set to Const2754
3128 op name is empty or dup, set to Const3128
3502 op name is empty or dup, set to Const3502
3870 op name is empty or dup, set to Shape3870
3876 op name is empty or dup, set to Unsqueeze3876
3901 op name is empty or dup, set to Const3901
3908 op name is empty or dup, set to Unsqueeze3908
3925 op name is empty or dup, set to BinaryOp3925
3957 op name is empty or dup, set to Const3957
3958 op name is empty or dup, set to BinaryOp3958
3985 op name is empty or dup, set to Shape3985
3993 op name is empty or dup, set to BinaryOp3993
4021 op name is empty or dup, set to BinaryOp4021
4045 op name is empty or dup, set to Const4045
4061 op name is empty or dup, set to Unsqueeze4061
4062 op name is empty or dup, set to Const4062
4069 op name is empty or dup, set to Rank4069
4101 op name is empty or dup, set to BinaryOp4101
4129 op name is empty or dup, set to BinaryOp4129
4152 op name is empty or dup, set to Unsqueeze4152
4208 op name is empty or dup, set to BinaryOp4208
inputTensors : [ feat_vec_z, x_patch, pos_vec_z, x_mask, mask_vec_z, resize_factor, bbox, ]
outputTensors: [ max_score, pred_bbox, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
x_patch
x_mask
feat_vec_z
mask_vec_z
pos_vec_z
bbox
resize_factor
output: pred_bbox
output: max_score
pred_bbox: (4, )
TESTERROR pred_bbox value error : absMaxV:62.822525 - DiffMax 97.493576
Error for output pred_bbox
max_score: (1, )
TESTERROR max_score value error : absMaxV:0.505229 - DiffMax 0.502624
Error for output max_score
Save mnn result to  .error director
'''

**Comment by wangzhaode** [comment]
1. 模型转换时报错的log是优化阶段的可以忽略；
2. 你下边用`fastTestOnnx.py`测试的模型跟你上边发的截图好像不是一个模型；

**Comment by jxt1234** [comment]
更新版本看看问题有没解决，如没解决，重新提 issue
