### ISSUE TITLE
新版本aarch64下编译报错，x64_x86编译没问题

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2114]
mnn-2.2.0 ，刚下载的代码arm下编译报错，上一个版本没有问题直接编译过。ubuntu 虚拟机 x64_x86编译也没问题。
 
gcc 7.3编译

[  3%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S.o
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S: Assembler messages:
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:99: 错误：operand mismatch -- `mov v1.4s,v0.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:99: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:99: Info:      mov v1.8b, v0.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:99: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:99: Info:      mov v1.16b, v0.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:102: 错误：operand mismatch -- `mov v14.4s,v12.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:102: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:102: Info:     mov v14.8b, v12.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:102: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:102: Info:     mov v14.16b, v12.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:103: 错误：operand mismatch -- `mov v15.4s,v13.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:103: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:103: Info:     mov v15.8b, v13.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:103: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:103: Info:     mov v15.16b, v13.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: 错误：operand mismatch -- `mov v16.4s,v14.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v16.8b, v14.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v16.16b, v14.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: 错误：operand mismatch -- `mov v18.4s,v14.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v18.8b, v14.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v18.16b, v14.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: 错误：operand mismatch -- `mov v20.4s,v14.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v20.8b, v14.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v20.16b, v14.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: 错误：operand mismatch -- `mov v22.4s,v14.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    did you mean this?
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v22.8b, v14.8b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:    other valid variant(s):
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:104: Info:     mov v22.16b, v14.16b
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:105: 错误：operand mismatch -- `mov v24.4s,v14.4s'
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S:105: Info:    did you mean this?

**Comment by lvyong1943** [comment]
还有一个错误
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/CPURuntime.cpp: 在函数‘void cpuinfo_arm_init(cpuinfo_arm_isa*)’中:
/home/kylin/mnn/MNN-master_2022-11-03/source/backend/cpu/CPURuntime.cpp:1559:28: 错误：‘HWCAP2_I8MM’在此作用域中尚未声明
         if (isa_features & HWCAP2_I8MM) {

**Comment by duanshanchong** [comment]
遇到同样问题，发现源码里默认把arm64下的文件都编译了，其中包含armv86的文件MNNGemmInt8AddBiasScale_ARMV86_Unit.S ，把该文件删掉就可以了

**Comment by wangzhaode** [comment]
> MNNGemmInt8AddBiasScale_ARMV86_Unit

是的 最近新增了ARMv8.6的实现，可以手动删除掉这些文件在编译；我们后续做一下处理
