### ISSUE TITLE
benchmark Build bench tools failed,无法读取远程仓库

### ISSUE THREAD

**Issue by mrbrantofgithub** [alibaba/MNN#2116]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Macos, target Android

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
./build.sh --android --mnn-tag 90719ce2 --torch-tag v1.11.0 --tf-tag v2.7.0
```

# 编译日志:
# Build Log:

```
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/site-packages (4.4.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/site-packages (6.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (1.23.4)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python3.10 -m pip install --upgrade pip
正克隆到 'MNN'...
ssh: connect to host gitlab.alibaba-inc.com port 22: Operation timed out
致命错误：无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
正克隆到 'MNN'...
ssh: connect to host gitlab.alibaba-inc.com port 22: Operation timed out
致命错误：无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在
```

**Comment by wangzhaode** [comment]
请先从Github下载代码编译后测试

**Comment by WenBank** [comment]
我也遇到这个问题，方法无效，从Github下载代码编译后，再编译任然不行
![image](https://user-images.githubusercontent.com/23031303/225603052-0764264a-c02f-4404-ac66-ae60c7470ef1.png)

**Comment by wangzhaode** [comment]
把脚本里的repo修改一下 里面有一行github的repo
