### ISSUE TITLE
AttributeError: module 'MNN' has no attribute 'Interpreter' + Raspberry Pi3 B+ 

### ISSUE THREAD

**Issue by dFuong** [alibaba/MNN#2117]
# Platform:  

> **Raspberry Pi3 B+ armv7 + 32-bits OS**

# Github Version:
`git clone --depth=1 https://github.com/alibaba/MNN.git`

# Compiling Method
```
$ cd MNN
$ ./schema/generate.sh
# install MNN
$ mkdir build
$ cd build
# generate build script
$ cmake -D CMAKE_BUILD_TYPE=Release \
        -D MNN_OPENMP=ON \
        -D MNN_USE_THREAD_POOL=OFF \
        -D MNN_BUILD_QUANTOOLS=ON \
        -D MNN_BUILD_CONVERTER=ON \
        -D MNN_BUILD_DEMO=ON \
        -D MNN_BUILD_BENCHMARK=ON ..
```
```
# build MNN (± 20 min)
$ make -j4
$ sudo make install
```

# Build Log:
![image](https://user-images.githubusercontent.com/48349629/200535807-3b2a2e80-5c86-4fb2-ae69-2a77c5877056.png)

Please help me !

**Comment by wangzhaode** [comment]
你这编译的不是Pymnn，请参考：https://github.com/alibaba/MNN/issues/1051
