### ISSUE TITLE
pymnn支持N/A的GPU 调用吗？

### ISSUE THREAD

**Issue by DDX1994** [alibaba/MNN#2118]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu 18.04 x86 

# Github版本:
# Github Version:
* master 7374ddfe Merge pull request #2115 from wangzhaode/feature/sync_221

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
MNN源码编译好了可以调用GPU，但是在构建pymnn的时候打开了cuda，无法调用

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
pytmm修改后的build_deps.py文件：-DMNN_CUDA=ON 
    elif IS_LINUX:
        extra_opts = '-DMNN_TENSORRT=ON \
        -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs/ ' if USE_TRT else ' '
        extra_opts += ' -DMNN_INTERNAL=ON ' if IS_INTERNAL_BUILD else ' '
        extra_opts += ' -DMNN_BUILD_TORCH=ON ' if IS_BUILD_TORCH else ' '
        os.system('cmake ' + extra_opts +
            '-DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_TRAIN=ON -DCMAKE_BUILD_TYPE=Release \
            -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_AAPL_FMWK=OFF -DMNN_CUDA=ON  -DMNN_SEP_BUILD=OFF -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON \
            -DMNN_USE_THREAD_POOL=ON -DMNN_OPENMP=OFF .. && make MNN MNNTrain MNNConvert -j16')

```

# 编译日志:
# Build Log:
[top_level.txt](https://github.com/alibaba/MNN/files/9967709/top_level.txt)
[SOURCES.txt](https://github.com/alibaba/MNN/files/9967710/SOURCES.txt)
[requires.txt](https://github.com/alibaba/MNN/files/9967711/requires.txt)
[entry_points.txt](https://github.com/alibaba/MNN/files/9967712/entry_points.txt)
[dependency_links.txt](https://github.com/alibaba/MNN/files/9967713/dependency_links.txt)

```
安装后调用CUDA报错
MNN-2.2.1-py3.6-linux-x86_64.egg/_mnncengine.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3MNN4CUDA18CUDARuntimeWrapperD0Ev
```

**Comment by kunlongsolid** [comment]
我相同的操作也遇到了同样的问题，undefined symbol: _ZN3MNN4CUDA18CUDARuntimeWrapperD0Ev，请问您解决了吗？

**Comment by wangzhaode** [comment]
我们看一下

**Comment by m00nLi** [comment]
```lib/python3.9/site-packages/_mnncengine.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3MNN4CUDA18CUDARuntimeWrapperD0Ev```
给个预编译的cuda whell吧

**Comment by Jackerz312** [comment]
i have the same problem, any news?

**Comment by liuyingbin123** [comment]
同样的问题

**Comment by jasseeeem** [comment]
I am facing this issue while running MNN with CUDA in Docker. Any updates?

**Comment by jasseeeem** [comment]
I fixed the issue by deleting all the build folders and .egg files and recompiling MNN from scratch again.
```
rm -rf MNN/build MNN/pymnn_build
rm -rf MNN/pymnn/build MNN/pymnn/pip_package/*.egg*
```
