### ISSUE TITLE
onnx2mnn convert failed/Reshape error

### ISSUE THREAD

**Issue by qiankl** [alibaba/MNN#2120]
最新版本mnn 2.2.1，转模型报错
![image](https://user-images.githubusercontent.com/43663481/200811131-f7fde119-6f05-45ff-b0d3-31342da86f76.png)
改了模型结构，把报错的这个conv改成了矩阵乘加，转换成功但是报reshape错误，推理的时候任然报错。
![image](https://user-images.githubusercontent.com/43663481/200811505-04d8725d-98d1-4069-8183-9e816a586393.png)
onnx模型测试没问题，输入为1x3x224x224
模型文件超过25M，无法上传，放在google drive了 https://drive.google.com/file/d/11aXCmZLC2MBraw-kfpIi3IntP8xojQjI/view?usp=sharing

**Comment by fifika** [comment]
遇到了同样的问题，我试过虽然转换报错Reshape error但是转换出来的模型输出的结果是正确的。不过在输出时仍然会报错Reshape error 和Compute Shape Error for onnx::  但输出结果正确

**Comment by fifika** [comment]
正确性验证也是 TEST_SUCESS，转出onnx若不使用dynamic参数并且在mnn推理时使用resizeTensor会报错：Reshape error:   Compute Shape Error for onnx:  运行时报错： Can't run session because not resized，，转出onnx时使用dynamic参数设置想要动态的维度，转出时就和刚刚上面说的一样，mnn推理结果是对的，并且能更改维度。

**Comment by qiankl** [comment]
> 

我的问题是模型里面有一维输入的矩阵乘，已经通过mnn的钉钉群找大佬解决了转模型的报错问题。你可以加钉钉群在群里问下

**Comment by yftongbupt** [comment]
> > 
> 
> 我的问题是模型里面有一维输入的矩阵乘，已经通过mnn的钉钉群找大佬解决了转模型的报错问题。你可以加钉钉群在群里问下

你好，请问具体是怎么解决一维输入的矩阵乘的问题的呢？

**Comment by qiankl** [comment]
> > > 
> > 
> > 
> > 我的问题是模型里面有一维输入的矩阵乘，已经通过mnn的钉钉群找大佬解决了转模型的报错问题。你可以加钉钉群在群里问下
> 
> 你好，请问具体是怎么解决一维输入的矩阵乘的问题的呢？

群里大佬给了个补丁，打上就没问题了
