### ISSUE TITLE
fastTestOnnx.py crash when checking an onnx model

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/MNN#2121]
使用fastTestOnnx.py检验某个onnx的时候发生segmentation fault用法如下：

python3.6 ../tools/script/fastTestOnnx.py  test.onnx

具体模型请参考附档。

[test.zip](https://github.com/alibaba/MNN/files/9977287/test.zip)

**Comment by liamsun2019** [comment]
承接这个问题，此Onnx可以转成Mnn，但runtime发生segmentation fault:
Compute Shape Error for linear_0.tmp_0
Can't run session because not resized
Segmentation fault (core dumped)

**Comment by liamsun2019** [comment]
对应的layer如下：
![image](https://user-images.githubusercontent.com/51946663/201237374-05acc2e6-1b55-4089-9764-9eaf3dcc892e.png)

相应的onnx layer如下：
![image](https://user-images.githubusercontent.com/51946663/201237594-393247b2-db2a-4b5f-91bf-4750a648ed50.png)

**Comment by jxt1234** [comment]
1D MatMul 问题，这周会出个版本规避一下，完全解决的方案还需要再想。

**Comment by liamsun2019** [comment]
好的，谢谢！！

**Comment by liamsun2019** [comment]
请问1D MatMul 目前有更新吗？

**Comment by jxt1234** [comment]
已经更新并修正
