### ISSUE TITLE
yolov3_darknet53 paddle->onnx->mnn convert 错误 

### ISSUE THREAD

**Issue by hellosiri** [alibaba/MNN#2122]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
cmake .. -DMNN_BUILD_CONVERTER=true
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
MNNConvert -f ONNX --modelFile /home/c/infer/output_inference/yolov3_darknet53_270e_coco/test.onnx --MNNModel /home/c/infer/output_inference/yolov3_darknet53_270e_coco/inference.mnn --bizCode MNN --optimizeLevel 0
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[18:28:58] /home/c/下载/MNN-2.2.0/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 7
Start to Optimize the MNN Net...
Check failed: attrs != nullptr ==> "TopKV's attr is empty"
段错误 (核心已转储)

Paste log here or pastebin
```

**Comment by wangzhaode** [comment]
https://github.com/alibaba/MNN/issues/2152
