### ISSUE TITLE
opencl not support MatMul？

### ISSUE THREAD

**Issue by shenjingcheng-a** [alibaba/MNN#2127]
I convert a onnx model only contains a signal op Matmul to MNN, when I use MNN to create  a session with backend opencl，it throw "Don't support type While memObject:2, Z", why there is While op, how to fix it?

**Comment by wsqat** [comment]
Excuse me, why can't I submit a new issue?

**Comment by shenjingcheng-a** [comment]
> Excuse me, why can't I submit a new issue?

? 不至于吧

**Comment by wangzhaode** [comment]
是不是BatchMatMul

**Comment by shenjingcheng-a** [comment]
> 
不是，就是MatMul

**Comment by shenjingcheng-a** [comment]
> 是不是BatchMatMul

不是，就是MatMul，但是转换出while 循环，debug不出来。

**Comment by shenjingcheng-a** [comment]
> Collaborator
OPENCL 只能支持二维输出的矩阵乘法吗

**Comment by jxt1234** [comment]
这个是三维或者更高维的 MatMul ，转成了 Loop 算子，目前 opencl 尚不支持
