### ISSUE TITLE
模型量化的问题

### ISSUE THREAD

**Issue by DHNicoles** [alibaba/MNN#213]
机器的环境：Ubuntu, cmake-3.5.1, gcc-5.4.0
按照[量化教程](https://github.com/alibaba/MNN/blob/master/tools/quantization/README_CN.md) 执行成功，但是timeProfile对比后，量化版的前向耗时远高于原始版：
### Int8:
![8](https://user-images.githubusercontent.com/13547926/62407037-9f391500-b5e4-11e9-9192-19af169c18fd.jpg)

### FP32:
![32](https://user-images.githubusercontent.com/13547926/62407042-ab24d700-b5e4-11e9-8bb2-bcdc7b61a3d9.jpg)

请问下，是不是步骤有误，或者其他原因？

**Comment by czy2014hust** [comment]
Please test on Arm CPU.INT8 is not optimized on x86 platform.

**Comment by leo-nullptr** [comment]
We also found the quantinized model takes 5 times longer than the original model for official mbv2 on ubuntu 19.04.
