### ISSUE TITLE
关于MNN钉钉群

### ISSUE THREAD

**Issue by LRY89757** [alibaba/MNN#2130]
可以提供一下MNN钉钉群的二维码吗？之前一直申请操作都没加上，现在最新的这个链接也操作不成功。官方网址的二维码也过期了。谢谢！

**Comment by xingxinghanzi** [comment]
https://mnn-docs.readthedocs.io/en/latest/intro/about.html    我之前通过这个加的，你可以试试

**Comment by LRY89757** [comment]
> https://mnn-docs.readthedocs.io/en/latest/intro/about.html 我之前通过这个加的，你可以试试

![image](https://user-images.githubusercontent.com/77330637/202451765-66826920-955e-4cb7-94ca-67485ad3bc1d.png)
我点开第三个群链接长这个样子，没有办法输入手机号

**Comment by Shulin-Zhang** [comment]
同问，怎么入群啊，很多问题解决不了

**Comment by LRY89757** [comment]
@wangzhaode 请MNN社区人员来发下二维码好吗

**Comment by xingxinghanzi** [comment]
@LRY89757 我那个时候也是显示这样的 可以填的  那个+86后面有个横线，可以填号码（你自己只能看到一部分）

**Comment by LRY89757** [comment]
> @LRY89757 我那个时候也是显示这样的 可以填的 那个+86后面有个横线，可以填号码（你自己只能看到一部分）

非常感谢！现已成功入群！ @xingxinghanzi

**Comment by LRY89757** [comment]
> 同问，怎么入群啊，很多问题解决不了

可以试试tab键跳转，他那个确实不显示框很难受

**Comment by Embed-Debuger** [comment]
已经失效了，还有好兄弟能拉我进去吗
