### ISSUE TITLE
请问我在mac上使用2.2.0版本的metal推理，copyFromHostTensor函数出现了内存泄漏的问题，这是正常的嘛？

### ISSUE THREAD

**Issue by hk19941214** [alibaba/MNN#2133]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MacOs

# Github版本:
# Github Version:
2.2.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
动态库（静态库编译会失败）
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by anliyuan** [comment]
请问这个问题解决了么？我也遇到这个问题了

**Comment by wangzhaode** [comment]
请问具体是怎样的内存泄漏？

**Comment by hk19941214** [comment]
> 请问具体是怎样的内存泄漏？

就是我调用了runsession之后，MetalConvolutionWinogard::onFloat、MetalBinary::onExecute、MetalRaster::onExecute等函数都会不断申请内存导致内存一直上涨且不释放

**Comment by hk19941214** [comment]
解决了，需要在自己的代码里加
@autoreleasepool{
}

**Comment by hk19941214** [comment]
> 请问这个问题解决了么？我也遇到这个问题了

解决了，需要在自己的代码里加
@autoreleasepool{
}

**Comment by wangzhaode** [comment]
> > 请问这个问题解决了么？我也遇到这个问题了
> 
> 解决了，需要在自己的代码里加 @autoreleasepool{ }

这个不是内存泄露；苹果的释放时间问题；
