### ISSUE TITLE
arm cpu gcc 9.3,CPURuntime.cpp:1559:28: error: ‘CPUINFO_ARM_LINUX_FEATURE_I8MM’ was not declared in this scope

### ISSUE THREAD

**Issue by lvyong1943** [alibaba/MNN#2137]
aarch64,gcc 9.3
/CPURuntime.cpp:1559:28: error: ‘CPUINFO_ARM_LINUX_FEATURE_I8MM’ was not declared in this scope; did you mean ‘CPUINFO_ARM_LINUX_FEATURE_FPHP’?
 1559 |         if (isa_features & CPUINFO_ARM_LINUX_FEATURE_I8MM) 
 
This problem exists in both the current version and the previous version

**Comment by juanfxlopez** [comment]
Same error here. Not able  to continue installing after this

**Comment by wangzhaode** [comment]
Thanks! Fixed.
Now add the define :
```
#define CPUINFO_ARM_LINUX_FEATURE_I8MM UINT32_C(0x00002000)
```
