### ISSUE TITLE
请问NNAPI后端可以提供官方的demo吗

### ISSUE THREAD

**Issue by ZhangJunsong-NR** [alibaba/MNN#2139]
尝试复现MNN 2.2.0对NNAPI的测试结果。
![image](https://user-images.githubusercontent.com/82858927/203249987-f81fd88b-13e1-45a9-9d04-5990415e319c.png)

有看到编译选项-DMNN_NNAPI和相关代码，但MNNForwardType.h里面又写了not support yet，请问具体如何在推理时指定NNAPI后端？可以提供一个官方的demo用于复现结果吗？

**Comment by jxt1234** [comment]
呃，就是指定 MNN_FORWARD_NN ，头文件注释没有修改过来，我们后续修改

**Comment by ZhangJunsong-NR** [comment]
好的，我尝试一下。
还有一个小问题是，NNAPI在APP中的使用会受到Android系统相关的安全策略影响吗，似乎在targetSDK version比较高的情况下，系统会对高通NPU的访问有安全策略限制。

**Comment by wangzhaode** [comment]
> 好的，我尝试一下。 还有一个小问题是，NNAPI在APP中的使用会受到Android系统相关的安全策略影响吗，似乎在targetSDK version比较高的情况下，系统会对高通NPU的访问有安全策略限制。

确实会受系统影响；在测试的多款机型中目前只遇到过MIUI 13有部分版本有访问限制；其他机型大没有遇到限制情况；
