### ISSUE TITLE
MNN是否能适配复杂的ONNX，opencl比cpu推理慢4倍，比torch慢24倍

### ISSUE THREAD

**Issue by liujiaxing7** [alibaba/MNN#2143]
CREstereo深度估计网络，3090 pt推理300ms。3080 12代i7 cpu推理2s，opencl推理8s。是不是因为MNN无法适应较复杂的模型

onnx模型位置( 23.8MB )：https://drive.google.com/file/d/1DeCLxKp_otuzhQz_F35P8NH8LSAk_lXx/view?usp=share_link
转换出的mnn模型( 27.9MB )：https://drive.google.com/file/d/1UVhTqJV0sg9AtngY34wkhQnsSGv2KhK2/view?usp=share_link
推理demo：https://github.com/liujiaxing7/CREStereo-MNN/blob/master/main.cpp
![Screenshot from 2022-11-23 11-27-42](https://user-images.githubusercontent.com/52067608/203464743-bd4fc68c-a20b-44bf-b836-f1197f5c49e1.png)

**Comment by jxt1234** [comment]
GPU 建议用 MNN CUDA ，这个和模型是否复杂没有关系
