### ISSUE TITLE
yolor模型用测试工具能在cpu上跑通，但cuda后端一直报错

### ISSUE THREAD

**Issue by filbertsun** [alibaba/MNN#2144]
$ ./timeProfile.out ../../yolor/yolor-p6-640-640.mnn 1 2 1x3x640x640

Use extra forward type: 2
1 3 640 640
Open Model ../../yolor/yolor-p6-640-640.mnn
Can't run session because not resized
Sort by node name !
Node Name       Op Type         Avg(ms)         %       Flops Rate
Print <=20 slowest Op for Convolution, larger than 3.00

Sort by time cost !
Node Type       Avg(ms)         %       Called times    Flops Rate
total time : 0.000000 ms, total mflops : 0.000000
main, 138, cost time: 0.224000 ms

这是为什么呢？

**Comment by wangzhaode** [comment]
是否方便提供一下模型
