### ISSUE TITLE
执行这个build_32.sh并且 option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib"  ON) ，但总是生成的是静态库，这是什么原因呢

### ISSUE THREAD

**Issue by bigsealing** [alibaba/MNN#2145]
# 平台(如果交叉编译请再附上交叉编译目标平台):   android
# Platform(Include target platform as well if cross-compiling):  andorid

# Github版本: [Sync] Sync Internal 2.2.2
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method  命令行

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE="/home/xxx/opt/android-ndk-r16b/build/cmake/android.toolchain.cmake" \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=OFF \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4

# 编译日志:
# Build Log:
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Android
--      Processor: aarch64
--      Version: 2.2.2
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      NNAPI: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16: OFF
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /home/guestdev/MNN/project/android/build_64
--      CUDA PROFILE: OFF
-- Enabling AArch64 Assemblies
-- Configuring done
-- Generating done
-- Build files have been written to: /home/guestdev/MNN/project/android/build_64
[  0%] Built target MNNMath
[  1%] Built target mergeInplaceForCPU
[ 17%] Built target MNNARM64
[ 20%] Built target MNN_Express
[ 20%] Built target MNNCV
[ 20%] Built target MNNUtils
[ 21%] Built target checkFile.out
[ 26%] Built target MNNCore
[ 26%] Built target checkDir.out
[ 52%] Built target MNNCPU
[ 84%] Built target MNNTransform
[ 85%] Linking CXX static library libMNN.a
[ 85%] Built target MNN
[ 85%] Linking CXX executable ModuleBasic.out
[ 85%] Linking CXX executable GetMNNInfo
[ 85%] Linking CXX executable SequenceModuleTest.out
[ 85%] Linking CXX executable aoa_nlu_decoder2.out
[ 85%] Built target GetMNNInfo
[ 85%] Linking CXX executable backendTest.out
[ 86%] Built target SequenceModuleTest.out
[ 86%] Built target ModuleBasic.out
[ 87%] Built target aoa_nlu_decoder2.out
[ 87%] Linking CXX executable testTrain.out
[ 87%] Linking CXX executable testModel_expr.out
[ 88%] Linking CXX executable modelCompare.out
[ 88%] Built target backendTest.out
[ 88%] Linking CXX executable benchmarkExprModels.out
[ 89%] Built target testTrain.out
[ 89%] Built target testModel_expr.out
[ 89%] Built target modelCompare.out
[ 89%] Linking CXX executable testModel.out
[ 90%] Linking CXX executable testModelWithDescrisbe.out
[ 90%] Linking CXX executable getPerformance.out
[ 90%] Built target getPerformance.out
[ 91%] Linking CXX executable checkInvalidValue.out
[ 93%] Built target benchmarkExprModels.out
[ 93%] Linking CXX executable timeProfile.out
[ 93%] Built target testModel.out
[ 93%] Built target testModelWithDescrisbe.out
[ 93%] Linking CXX executable MNNV2Basic.out
[ 93%] Linking CXX executable aoa_nlu_decoder1.out
[ 93%] Built target checkInvalidValue.out
[ 93%] Linking CXX executable winogradExample.out
[ 94%] Built target timeProfile.out
[ 95%] Built target MNNV2Basic.out
[ 96%] Linking CXX executable aoa_nlu_encoder.out
[ 97%] Built target aoa_nlu_decoder1.out
[ 98%] Linking CXX executable winogradGenerateGLSL.out
[ 98%] Linking CXX executable winogradGenerateCL.out
[ 98%] Built target winogradExample.out
[ 98%] Linking CXX executable mobilenetTest.out
[ 98%] Built target winogradGenerateGLSL.out
[ 99%] Built target winogradGenerateCL.out
[ 99%] Linking CXX executable benchmark.out
[ 99%] Built target aoa_nlu_encoder.out
[ 99%] Built target mobilenetTest.out
[100%] Built target benchmark.out

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
清下 CMake 文件夹看下

**Comment by bigsealing** [comment]
> 清下 CMake 文件夹看下

删过无数次了

**Comment by snow-tyan** [comment]
> > 清下 CMake 文件夹看下
> 
> 删过无数次了

你加上-DMNN_BUILD_SHARED_LIBS=ON 也不行吗

**Comment by wangzhaode** [comment]
CMAKE宏选项设置错了；执行以下命令看看是不是`ON`
```
-> % grep MNN_BUILD_SHARED_LIBS CMakeCache.txt
MNN_BUILD_SHARED_LIBS:BOOL=ON
// MNN_BUILD_SHARED_LIBS=ON
```
