### ISSUE TITLE
android studio打开D:\xxxx\MNN\project\android\demo 编译报错

### ISSUE THREAD

**Issue by bigsealing** [alibaba/MNN#2146]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:[jxt1234](https://github.com/alibaba/MNN/commits?author=jxt1234) [Merge pull request](https://github.com/alibaba/MNN/commit/767086816d339587d42c11dc7b8e336c52f3c98b) https://github.com/alibaba/MNN/pull/2131 [from alibaba/feature/sync_2_2_2](https://github.com/alibaba/MNN/commit/767086816d339587d42c11dc7b8e336c52f3c98b)
…
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method  android studio直接编译

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
> Task :app:buildCMakeDebug
C/C++: ninja: Entering directory `D:\Qiniu_code\MNN\project\android\demo\app\.cxx\Debug\4834571y\armeabi-v7a'
C/C++: ../../../../../../../../tools/cpp/mergeInplaceForCPU.cpp:121: error: undefined reference to '__android_log_print'
C/C++: ../../../../../../../../tools/cpp/mergeInplaceForCPU.cpp:69: error: undefined reference to '__android_log_print'
C/C++: clang++: error: linker command failed with exit code 1 (use -v to see invocation)

> Task :app:buildCMakeDebug FAILED
Execution failed for task ':app:buildCMakeDebug'.
> Build command failed.
  Error while executing process D:\android\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\Qiniu_code\MNN\project\android\demo\app\.cxx\Debug\4834571y\armeabi-v7a GetMNNInfo MNN MNN_CL MNN_Express MNN_Vulkan mergeInplaceForCPU mnncore}
  ninja: Entering directory `D:\Qiniu_code\MNN\project\android\demo\app\.cxx\Debug\4834571y\armeabi-v7a'
  [1/142] Linking CXX executable ..\..\..\..\build\intermediates\cxx\Debug\4834571y\obj\armeabi-v7a\mergeInplaceForCPU
  FAILED: ../../../../build/intermediates/cxx/Debug/4834571y/obj/armeabi-v7a/mergeInplaceForCPU 
  cmd.exe /C "cd . && D:\android\ndk\21.4.7075529\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi21 --gcc-toolchain=D:/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/android/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -std=c++11 -g -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math -fno-rtti -fno-exceptions  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/mergeInplaceForCPU.dir/tools/cpp/mergeInplaceForCPU.cpp.o  -o ..\..\..\..\build\intermediates\cxx\Debug\4834571y\obj\armeabi-v7a\mergeInplaceForCPU  -latomic -lm && cd ."
  ../../../../../../../../tools/cpp/mergeInplaceForCPU.cpp:121: error: undefined reference to '__android_log_print'
  ../../../../../../../../tools/cpp/mergeInplaceForCPU.cpp:69: error: undefined reference to '__android_log_print'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  [2/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/BufferPool.cpp.o
  [3/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/ImagePool.cpp.o
  [4/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/BufferConvertor.cpp.o
  [5/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/ImageBufferConvertor.cpp.o
  [6/142] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanScale.cpp.o
  [7/142] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/execution/VulkanSoftmax.cpp.o
  [8/142] Building CXX object source/backend/vulkan/CMakeFiles/MNN_Vulkan.dir/runtime/VulkanRuntime.cpp.o
  [9/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/execution/buffer/BinaryBufExecution.cpp.o
  [10/142] Building CXX object source/backend/opencl/CMakeFiles/MNN_CL.dir/core/OpenCLBackend.cpp.o
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
收到，可以先把对应的工具注掉编译

**Comment by wangzhaode** [comment]
新版本修复了Android Demo的一些问题
