### ISSUE TITLE
MNN模型本地离线量化后运行时间比不量化更长

### ISSUE THREAD

**Issue by wsqat** [alibaba/MNN#2147]
使用MNNPythonOfflineQuant工具进行本地量化，

按照教程修改为多输入，单输出

在Andoroid上测试的耗时原来cpu300ms，现在量化后500ms

大佬有空帮忙看下，谢谢~

**Comment by wsqat** [comment]
量化后，我的BN层都没了，还多了很多notused的层

<img width="908" alt="截屏2022-11-28 17 32 38" src="https://user-images.githubusercontent.com/5681594/204243206-2f43a170-f2b1-4999-8f1e-f5854aac657f.png">

**Comment by FengMu1995** [comment]
离线量化之后卷积的权重变为空了, 你出现这个问题了吗

**Comment by wangzhaode** [comment]
Ref: https://mnn-docs.readthedocs.io/en/latest/faq.html#id16
