### ISSUE TITLE
编译的动态库之间的关系

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2149]
hi
      想问下，打开opencl 的宏开关，编译会生成libMNN.so，libMNN_CL.so，libMNN_Express.so  这三个库，请问这三个库都包含什么内容，以及这三个库有什么依赖关系吗？

谢谢

**Comment by jxt1234** [comment]
libMNN_Express 依赖 libMNN ，提供额外的表达式计算功能（支持动态图、复杂模型的运行）
libMNN_CL 依赖 libMNN，提供基于 opencl 的 gpu 加速能力
