### ISSUE TITLE
几点疑问，关于MNN-build的问题

### ISSUE THREAD

**Issue by snow-tyan** [alibaba/MNN#2159]
### 平台(如果交叉编译请再附上交叉编译目标平台):  
x64-ubuntu20.04

### Github版本: 
tag: 2.2.2

### 编译方式: 
通过CMake构建源码编译, cmake-3.24, gcc-9

### 关于构建的几点疑问
1. MNN_TENSORRT构建选项
CMakeLists里没有target_include_directories(${TensorRT_ROOT}/include)这样的字样，那我怎么把作为第三方库的TensorRT编进去呢，它怎么知道我的TensorRT放在哪里呢

2. MNN_CUDA
2.2.2版本的MNN_CUDA可以用，怎么把它编成静态库？
其次好像没写cmake install，make install的时候MNN_Cuda_Main没安装到lib下

**Comment by jxt1234** [comment]
1. TensorRT 需要自行安装并设定 TensorRT_ROOT 环境变量
2. MNN_CUDA 目前不支持编成静态库

**Comment by snow-tyan** [comment]
> 1. TensorRT 需要自行安装并设定 TensorRT_ROOT 环境变量
> 2. MNN_CUDA 目前不支持编成静态库

感谢回复，不过设置TensorRT_ROOT环境变量还是找不到NvInfer.h 
我在source/backend/tensorrt/CMakeLists.txt中加入了include_directories相应目录，但遇到很多错误都是关于插件IPlugin，应该版本不匹配，想问下MNN-2.2.2支持的TensorRT版本是多少，支持30系显卡吗，cuda版本有要求吗，我是cuda11.5，RTX3090，TensorRT-8.2.5.1

**Comment by jxt1234** [comment]
MNN 的 TRT backend 对应是 TensorRT 7.0
