### ISSUE TITLE
createSession error

### ISSUE THREAD

**Issue by garspace** [alibaba/MNN#216]
I counter create session error after converting .mnn model sucessfully, the error :

I/MNNJNI: Unsupported data type!
E/MNNJNI: Error for D:\MNN_0\MNN\source\core\Tensor.cpp, 245
A/libc: D:\MNN_0\MNN\source\core\Tensor.cpp:245: void MNN::Tensor::setType(int): assertion "res" failed
    Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27093 (android.mnndemo), pid 27093 (android.mnndemo)

how can i solve this problem, who help me?

**Comment by czy2014hust** [comment]
Please check out your data type.
