### ISSUE TITLE
模型在不同运行平台的内存

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2164]
hi

        想问下，模型在cpu和gpu平台上的内存是一样的吗？
使用这个model->getSessionInfo(session, MNN::Interpreter::MEMORY, &memoryUsage);  接口发现在cpu和gpu平台上的内存不一样，
怎么统计gpu上的内存呢?

谢谢

**Comment by keke444** [comment]
同一个模型使用上述接口，在cpu上：Session Info: memory use 129.395508 MB
                                            在gpu上：Session Info: memory use 0.001335 MB
为什么差别会如此大呢？

**Comment by jxt1234** [comment]
目前 opencl 后端没有支持内存统计，另外 GPU 的内存占用看具体设备驱动实现，MNN统计的不一定完整。

**Comment by keke444** [comment]
> 目前 opencl 后端没有支持内存统计，另外 GPU 的内存占用看具体设备驱动实现，MNN统计的不一定完整。

那还有别的方法统计吗？估计也行，回和cpu上的内存差不多吗

**Comment by xin486946** [comment]
同问，走opencl时内存如何统计？和cpu上的内存差不多吗
