### ISSUE TITLE
通用模型量化

### ISSUE THREAD

**Issue by MrZhouWenBo** [alibaba/MNN#2168]
（1）使用python通用模型量化代码量化模型，MNN1.1.6量化后结果正确。MNN2.+量化后测试推理出错（另，MNN1.1.6在ubuntu20.04上编译报错，在ubuntu18.04可完成编译）

（2）MNN1.1.6使用python通用量化代码后测试发现：两个cov层之间必须加一个pooling层，否则量化后模型输出的名子和数据类型会被改变。

（3）多输出的mnn模型获取输出size时统一打印10000（实际五个输出维度分别为[1,2,50,50] [1,2,50,50] [1,1,50,50] [1,3,50,50] [1,1,50,50]）

上述三个问题困扰许久如有指点不胜感激

**Comment by MrZhouWenBo** [comment]
ubuntu20.04上编译选项选择MNNConverter
错误提示：
[  3%] Built target MNNCore
[  4%] Built target MNNCV
[  4%] Built target MNNMath
[ 23%] Built target MNNTransform
[ 23%] Built target MNNUtils
[ 37%] Built target MNNCPU
[ 38%] Built target MNNX8664
[ 39%] Built target MNNAVX
[ 40%] Built target MNNAVXFMA
[ 41%] Built target MNNSSE
[ 41%] Built target MNN
[ 43%] Built target MNN_Express
[ 43%] Built target MNNV2Basic.out
[ 43%] Built target mobilenetTest.out
[ 43%] Built target backendTest.out
[ 44%] Built target testModel.out
[ 44%] Built target testModelWithDescrisbe.out
[ 44%] Built target getPerformance.out
[ 45%] Built target checkInvalidValue.out
[ 46%] Built target timeProfile.out
tools/converter/CMakeFiles/MNNCompress.dir/build.make:73: *** 目标模式不含有“%”。 停止。
make[1]: *** [CMakeFiles/Makefile2:714：tools/converter/CMakeFiles/MNNCompress.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by 1783696285** [comment]
你好，想问一下，通用模型量化时，它的json配置文件怎么构建？

**Comment by jxt1234** [comment]
相关 python 代码和模型可以发一下看看?
