### ISSUE TITLE
windows上编译mnn

### ISSUE THREAD

**Issue by yizhaoyanbo** [alibaba/MNN#217]
windows10 + vs2019编译mnn，得到dll和lib库，没有报错，顺利编过，如下：
![image](https://user-images.githubusercontent.com/26928415/62473110-a9b90180-b7d2-11e9-9b20-67be3292536f.png)

然后我在cmakelists.txt中链接.lib静态库，如下：
![image](https://user-images.githubusercontent.com/26928415/62473224-e71d8f00-b7d2-11e9-9015-c07d1dfefe91.png)

使用cmake-gui生成VS工程后，我 #include "Tensor.hpp"，编译就会报错，如下：
![image](https://user-images.githubusercontent.com/26928415/62473383-3499fc00-b7d3-11e9-893b-981d8d3ad0a5.png)

请问是我编译的lib静态库有问题吗 @li-qing @woodrocky

**Comment by li-qing** [comment]
从什么地方include的？C文件？

不include就不会报错？
