### ISSUE TITLE
Win10 OPENCL后端使用GPU推理时，如果两次runSession之间时间隔得太久，推理速度瞬间变慢1~2倍

### ISSUE THREAD

**Issue by zhanggd001** [alibaba/MNN#2170]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Win10
# Platform(Include target platform as well if cross-compiling):  

# Github版本: Release 2.2.0
# Github Version:

OPENCL后端调用GPU进行推理，测试1000次：
void MNNSegNet::detect(const cv::Mat &mat, cv::Mat &out_rsult)
{
	if (mat.empty()) return;

	// 1. make input tensor
	this->transform(mat);

	// 2. inference & run session

	auto startDoing = std::chrono::steady_clock::now();

	m_mnn_interpreter->runSession(m_mnn_session);

	auto endDoing = std::chrono::steady_clock::now();
	std::chrono::duration<double> timeDoing = endDoing - startDoing;
	std::cout << " Inference Time : " << timeDoing.count() * 1000 << "ms" << std::endl;

	auto output_tensors = m_mnn_interpreter->getSessionOutputAll(m_mnn_session);

	// 3. fetch
	auto device_scores_ptr = output_tensors.at("output"); // (1,c,h,w)
	MNN::Tensor host_scores_tensor(device_scores_ptr, device_scores_ptr->getDimensionType());
	device_scores_ptr->copyToHostTensor(&host_scores_tensor);

	// for debug
	// host_scores_tensor.printShape();

	auto scores_dims = host_scores_tensor.shape();
	const unsigned int output_classes = scores_dims.at(1);
	const unsigned int output_height = scores_dims.at(2);
	const unsigned int output_width = scores_dims.at(3);

	float *scores_ptr = host_scores_tensor.host<float>();

	cv::Mat output_tensor(output_height, output_width, CV_32FC1, scores_ptr + output_height * output_width);

	output_tensor.convertTo(out_rsult, CV_8UC1, 255, 0);
	cv::threshold(out_rsult, out_rsult, 102, 255, cv::THRESH_BINARY);
}

//如果使用下面的代码测试，1000次推理时间都很稳定，再13ms左右
for (int i = 0; i < 1000; ++i)
{
  std::cout << i << std::endl;
  segnet->detect(img, result);
}

![image](https://user-images.githubusercontent.com/48872511/208466005-7a77c248-b26d-4453-951a-b05894dd1471.png)

// 但如果两次推理之间加入一些后处理和其他比较耗时的操作，大概几十ms，那么整个推理速度都会变慢
for (int i = 0; i < 1000; ++i)
{
  std::cout << i << std::endl;
  segnet->detect(img, result);
  
  //auto startDoing = std::chrono::steady_clock::now();
  if (i < 500)
  {
          // 存一张130万像素的彩色图，我的电脑上耗时大概在70ms左右
	  cv::imwrite("result.png", img);
  }
}
推理速度瞬间变慢
![image](https://user-images.githubusercontent.com/48872511/208466182-03eef020-c6be-40cc-a50f-c4fbafae9463.png)

i > 500后，不在存储图片，两次推理之间的时间间隔变短，推理速度又变正常
![image](https://user-images.githubusercontent.com/48872511/208466724-a1bf6336-8fb6-4c24-9afc-f08d493a7d46.png)

整个测试都是单线程的，所有步骤都是串行的。不知道为何推理速度会受到这么大的影响。

**Comment by liyanjun0925** [comment]
请问有解决这个问题么

**Comment by zhanggd001** [comment]
经测试这个是GPU 驱动的问题。我在windows下RTX950m GPU使用47X的GPU驱动不会有这个问题，高版本的GPU驱动会有这个问题。

> 请问有解决这个问题么

**Comment by zhanggd001** [comment]
> 请问有解决这个问题么

经测试这个是GPU 驱动的问题。我在windows下GTX950m GPU使用47X的GPU驱动不会有这个问题，高版本的GPU驱动会有这个问题。你可以测试一下不同版本的GPU驱动效果。

**Comment by liyanjun0925** [comment]
> 

确实是这样。。

**Comment by jxt1234** [comment]
可能是这个驱动在长时间 gpu 空闲时会降频，可以找工具分析看看
