### ISSUE TITLE
请问是否有方法判断模型推理时是否使用了指令集加速？

### ISSUE THREAD

**Issue by MicroYu-jt** [alibaba/MNN#2175]
## 请教两个问题
1、是否有方法判断模型推理时是否使用了指令集加速？
2、Winograd 启用的判断逻辑是怎样的呢？

**Comment by jxt1234** [comment]
1. 没有接口判断，MNN 默认会寻找最优指令集并使用
2. Winograd 的启用按照一个损失公式判断，可以看 README.md 里面的 paper

**Comment by MrJungle1** [comment]
@jxt1234 请问一下winograd的paper是哪个，好像没有看到
