### ISSUE TITLE
Undefined symbol: _MNNGemmInt8AddBiasScale_ARMV82_Unit    Undefined symbol: _MNNMetalGetTensorContent

### ISSUE THREAD

**Issue by Madara39** [alibaba/MNN#2176]
iOS  demo  error when  build:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/110812666/209342922-d565074e-a62b-411b-bf8a-bf7922597f49.png">

**Comment by Madara39** [comment]
anyone know how to solve it？

**Comment by jxt1234** [comment]
demo needed to be builded for IOS real maching. Not simulator.
