### ISSUE TITLE
这个极其简单的模型无法推理

### ISSUE THREAD

**Issue by jinfagang** [alibaba/MNN#2178]
[mb1_120x120_w_pts2d_sim.onnx.zip](https://github.com/alibaba/MNN/files/10298225/mb1_120x120_w_pts2d_sim.onnx.zip)

这个模型onnx本应很简单，结果倒出来极其复杂， 且无法推理。是否能修复一下？

**Comment by jxt1234** [comment]
用 fastTestOnnx.py 测试过么?

**Comment by jxt1234** [comment]
[15:22:58] /Users/xtjiang/alicnn/AliNNPrivate/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ param, pts3d, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
input
output: param
output: pts3d
param: (1, 62, )
pts3d: (1, 3, 68, )
TEST_SUCCESS

我测试了一下是可以正常转换并推理的，请更新 mnn 版本后测试

**Comment by jinfagang** [comment]
@jxt1234  hi，我有一个模型 fastONNX推理正确，纯c++里面推理结果也是正确的。但是一样的代码，编译成wasm推理结果就不对了，是为啥呀
