### ISSUE TITLE
处理视频流速度很慢,stbi_image 和cv::mat区别这么大？

### ISSUE THREAD

**Issue by xingyanan** [alibaba/MNN#218]
目前在工程里面看用stbi_image库读取图片路径如“/test.jpg”,这种方式读图片再处理，模型速度很快，但是不用stbi_image读，用opencv读转成Mat格式输入模型，运算速度至少满了七八倍，请问这是为什么？？ @li-qing @nihui

**Comment by 17759205390** [comment]
> 目前在工程里面看用stbi_image库读取图片路径如“/test.jpg”,这种方式读图片再处理，模型速度很快，但是不用stbi_image读，用opencv读转成Mat格式输入模型，运算速度至少满了七八倍，请问这是为什么？？ @li-qing @nihui

@xingyanan 你怎么测速度的，在runsession上打时间错吗？
