### ISSUE TITLE
NNAPI supportOps

### ISSUE THREAD

**Issue by guopeng-nreal** [alibaba/MNN#2180]
尝试了下MNN 的NNAPI，库版本2.2.0，模型使用的是benchmark中的model，mobilnetv1，但是在870上出现了部分算子不支持的情况：
```

[NNAPI] device [0 : qti-default] supportOps = {
	MobilenetV1/MobilenetV1/Conv2d_0/Conv2D : 0
        MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise : 1
	MobilenetV1/MobilenetV1/Conv2d_1_pointwise/Conv2D : 1
	MobilenetV1/MobilenetV1/Conv2d_2_depthwise/depthwise : 0

```
更换到888点手机上可以正确执行，看了下NNAPI的文档只有关于android版本的支持问题，想问下这个是硬件问题导致的吗，应该如何查验？

另外测试了一下其他模型，发现interp层同样不支持，看文档上最近临和双线性都是支持的，这个是配置的问题还是硬件的问题？

**Comment by wangzhaode** [comment]
这个支持与否是硬件向NNAPI提供的支持列表，我们也无法直接获取；
