### ISSUE TITLE
Mobilenetv3 exported mnn model seems very complicated and output result wrong

### ISSUE THREAD

**Issue by jinfagang** [alibaba/MNN#2181]
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/21303438/209748233-956f5e66-76c3-451a-888e-982974111086.png">

A very tipical mobilenetv3 model in onnx.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/21303438/209748258-6f15db4e-38cb-41dc-915e-1bff73931e47.png">

mnn model exported.

this is really terrifying.... Such a small model became a monster, is that normal?

**Comment by jxt1234** [comment]
It does not mattern. If you want simply structure, you can add --saveStaticModel to build static one.
