### ISSUE TITLE
动态输入，onnx结果与mnn模型结果不一致

### ISSUE THREAD

**Issue by xiaoheizi123** [alibaba/MNN#2183]
原模型是pytorch模型，输入为宽度不定的图像。运行位置是pc机。
pt模型转onnx,转mnn的过程都没有报错，pt的结果只能与onnx结果一致，与mnn结果不一致。
pymnn的版本是1.1.0

 ### 转onnx的代码:

`input1_names = ['input1']
output1_names = ['output1']
input2_names = ['input2']
output2_names = ['output2']

dynamic_image = True
image_width = 160
word_num = 20
feature_num = 259
if dynamic_image:
    inputs = torch.randn(1, 1, 80, image_width)
    dynamic_axes= {'input1':{3:'image_width'}, 'output1':{0:'predict_num'} }
    torch.onnx.export(model1, inputs, f=save_path1, export_params=True, verbose=False,
                                    input_names=input1_names, output_names=output1_names, dynamic_axes=dynamic_axes)
    onnx_model1 = onnx.load(save_path1)
    onnx.checker.check_model(onnx_model1)
    onnx.helper.printable_graph(onnx_model1.graph)
    print('test onnx')

`

### 测试mnn模型的代码：

interpreter1 = MNN.Interpreter("./cnn_model1.mnn")
session = interpreter1.createSession()
input_tensor = interpreter1.getSessionInput(session, 'input1')
_, _, h, w = input.shape
interpreter1.resizeTensor(input_tensor, (1, 1, 80, w))
interpreter1.resizeSession(session)
tmp_input_ = MNN.Tensor((1, 1, 80, w), MNN.Halide_Type_Float, input.numpy(), MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(tmp_input_)
interpreter1.runSession(session)
output1_tensor = interpreter1.getSessionOutputAll(session)['output1'].getData()    # mnn结果与onnx结果不匹配

看了之前的提问，MNN应该是支持CNN模型的动态图像输入、RNN的不定长输入的，但是好像都是C++的应用，用python调用一直调试也没有解决。

**Comment by jxt1234** [comment]
pymnn 更新到 2.0.0 ，或者在最新代码重新编译 pymnn 试下。
然后用下面指令查看一下模型状态，有可能需要输入输出做内存布局转换
mnnconvert -f MNN --modelFile XXX.mnn --info

**Comment by xiaoheizi123** [comment]
pymnn更新到2.0.0之后，pt模型还是与onnx结果匹配，与mnn结果不一致，但我觉得应该是您说的需要内存布局转换的事，我拿onnx结果只取到前3~4位，在mnn的结果中去搜索，能搜到大致匹配的，但是没有找到布局规律，这个内存布局转换该怎么转换或者有相关的资料看看吗？
我用您给的指令测了下mnn模型状态，结果是没有输出.

**Comment by xiaoheizi123** [comment]
在代码的最后加上这些代码，将输出格式由NC4HW4改为NCHW，mnn的结果与ONNX还是不匹配，虽然shape一样。

output1_tensor = interpreter1.getSessionOutputAll(session)['output1']
mnn_output_tensor_shape = output1_tensor.getShape()
mnn_output_tensor = MNN.Tensor(mnn_output_tensor_shape, MNN.Halide_Type_Float,
                               np.ones(mnn_output_tensor_shape).astype(np.float32),
                               MNN.Tensor_DimensionType_Caffe)
output1_tensor.copyToHostTensor(mnn_output_tensor)
mnn_output = mnn_output_tensor.getData()
mnn_output = np.array(mnn_output).reshape(mnn_output_tensor_shape)

**Comment by jxt1234** [comment]
更新到 2.3.0 用 fastTestOnnx.py 再测试下吧。具体日志是什么？
