### ISSUE TITLE
转换MNN模型， 多输入输出问题

### ISSUE THREAD

**Issue by Zhangts98** [alibaba/MNN#2188]
MNNConvert version: 2.0.4
windows 10

请问在转mnn模型时能指定输入输出节点吗？

我的pb模型有三个输出， 但是转换成mnn模型后， 输出节点变成了两个，节点名也发生了变化。
` .\MNNConvert.exe -f TF --modelFile my.pb --MNNModel my.mnn`
pb模型的输入节点是: `[input_1, input_img_shape]`, 输出节点是:`[concat_5, concat_6, concat_7]`,
转换成mnn模型后，节点如下。
![image](https://user-images.githubusercontent.com/61573829/210917654-388c8ff7-407f-46f4-8b9e-67e7c5f8c2ad.png)

**Comment by jxt1234** [comment]
目前不支持转换时指定，可以自己找一下中间节点对应名称，加载时指定

**Comment by ghoshaw** [comment]
三个输出 变成 两个的问题我也遇到了，请问解决了吗

**Comment by Zhangts98** [comment]
> 

抱歉，之后就没有再关注这个问题了。 请问您解决这个问题了么?

**Comment by Zhangts98** [comment]
> 三个输出 变成 两个的问题我也遇到了，请问解决了吗

抱歉， 之后没再关注这个问题了， 请问您解决了吗？

**Comment by ghoshaw** [comment]
解决了，主要是 取输出值的函数用的不对，必须用这个函数 copyToHostTensor
