### ISSUE TITLE
win平台使用mnn的opencl后端推理模型，单次速度在12ms~60ms之间震荡;  显卡是RTX3080,之前使用1080ti不存在这种情况； 如果只针对固定的输入重复推理100次，速度也是12ms非常稳定

### ISSUE THREAD

**Issue by liyanjun0925** [alibaba/MNN#2189]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows

# Github版本:
# Github Version:
2.0.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by wangzhaode** [comment]
性能震荡的时候测试的输入是固定形状吗

**Comment by liyanjun0925** [comment]
> 

固定的现状；经过测试发现是显卡降频的问题
