### ISSUE TITLE
模型量化后，前向结果为空

### ISSUE THREAD

**Issue by sherlockgjh** [alibaba/MNN#219]
使用量化前的模型，可以正常运行，而使用相同的前向代码，同一批图像，模型量化后，模型前向结果就变为空了。请问这个是否是量化过程有问题呢？是不支持量化吗？

**Comment by czy2014hust** [comment]
模型是检测任务？量化时需要的样本是训练样本或者验证集样本吗？检测任务为空可能是误差的原因，可以增加量化校准用的样本数量试一下
