### ISSUE TITLE
iOS debug模式，析构的时候不会销毁MLModel内存，重复创建销毁会导致内存一直增加。

### ISSUE THREAD

**Issue by OOSYOO** [alibaba/MNN#2190]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS

# Github版本:
2.3.0

# 编译方式:
参考官方文档编译

**Comment by wangzhaode** [comment]
CoreML的mlmodel在析构时会销毁内存，不存在内存泄露；

请问你是指哪里？
