### ISSUE TITLE
device tensor与host tensor理解问题

### ISSUE THREAD

**Issue by HaiLongEmb** [alibaba/MNN#2197]
MNN的开发团队你们好：
     我使用的是MNN2.1发布版本，CPU后端进行推理。
     使用getSessionOutput获取到的数据是在device tensor中，我如果直接使用device tensor中的数据有什么问题？我看目前MNN中提供的Demo都是通过copyToHostTensor将device tensor拷贝到host tensor中。
     我想提高效率减少拷贝，请问这部拷贝是必须的吗？或者什么情况下是必须的。
     另外还请讲解一下device tensor与host tensor关系。
     在API手册中没查到明确的介绍。
     
     再次感谢

**Comment by jxt1234** [comment]
1. 在 Tensor 的内存布局为 NC4HW4 是必须的，因为 MNN 内部的NC4HW4数据结构有可能随着优化需要变更，不拷贝的话无法一直保证结果正确性。
2. 在 Tensor 的 deviceId 不等于 0 时是必须的，这种情况下 Tensor 有可能是 fp16 或者 bf16 的数据类型。
3. device tensor 是 MNN Interpreter-Session 所拥有的 Tensor ，随着 Interpreter 的析构而释放。host tensor 是用户使用 Tensor.hpp 里面的构造函数 自行创建的 Tensor 。
4. 用 Module API 默认不需要拷贝，参考 https://mnn-docs.readthedocs.io/en/latest/inference/module.html 和 demo/exec/pictureRecognition_module.cpp
