### ISSUE TITLE
What's the precision=2 in benchmark?

### ISSUE THREAD

**Issue by ysh329** [alibaba/MNN#220]
I found code about precision with `high, low, normal`, what's 2 meaning in benchmark? what does the kernel implement when precision=2? fp16 or fp32?

thanks in advance.

**Comment by leo-nullptr** [comment]
opencl backend: fp16 or not for kernel option and data type

**Comment by ysh329** [comment]
You means: use fp16 if have fp16 kernel, or not when no fp16 kernel implemented?

**Comment by leo-nullptr** [comment]
Refer to: [OpenCLRuntime](https://github.com/alibaba/MNN/blob/master/source/backend/opencl/core/runtime/OpenCLRuntime.cpp#L173) and [ConvWinograd](https://github.com/alibaba/MNN/blob/master/source/backend/opencl/execution/ConvWinograd.cpp#L93)

**Comment by li-qing** [comment]
https://www.yuque.com/mnn/en/create_session

refer to PrecisionMode.

**Comment by li-qing** [comment]
Low = 2. for OpenCL, that means fp16 is used for both calculation and storage.
