### ISSUE TITLE
采用MNN_BUILD_MINI编译后，无法输出。

### ISSUE THREAD

**Issue by aijianiula0601** [alibaba/MNN#2200]
cmakelist.txt中把MNN_BUILD_MINI设置为ON，编译成功得到libMNN.so后，执行demo（Portait segmentation）无法得到输出的图片。我在mac和手机端都试过MNN_BUILD_MINI=ON，都无法得到结果。定位到：

https://github.com/alibaba/MNN/blob/2.3.0/source/core/Pipeline.cpp 这里的 956行 buffer.command.size()全为0 ，是什么问题导致呢？

**Comment by jxt1234** [comment]
MNN_BUILD_MINI设置为ON 后对应的模型是需要加 --saveStaticModel 转换的，相关模型加参数转换过了么？

**Comment by aijianiula0601** [comment]
是onnx 模型转mnn时候加--saveStaticModel 这个参数吗？麻烦举个例子哈

**Comment by aijianiula0601** [comment]
转mnn时候，加了--saveStaticModel也不行。操作如下：
1.cmakelist.txt 设置MNN_BUILD_MINI 为ON
2.编译MNN源码
3.编译出demo执行文件
4.把tflite模型转换mnn，加入saveStaticModel
     /MNNConvert -f TFLITE --modelFile deeplabv3_257_mv_gpu.tflite --MNNModel deeplabv3_257_mv_gpu.mnn --bizCode biz --saveStaticModel
5.测试demo
     /segment.out deeplabv3_257_mv_gpu.mnn input.jpg result.png

出现错误如下：

`(base) jiahong@jiadeMac-mini build % ./segment.out deeplabv3_257_mv_gpu.mnn input.jpg result.png
The device support dot:0, support fp16:0, support i8mm: 0
input: w:257 , h:257, bpp: 3
origin size: 121, 140
output w = 257, h=257
zsh: segmentation fault  ./segment.out deeplabv3_257_mv_gpu.mnn`

**Comment by aijianiula0601** [comment]
上面的出现的问题是因为我先改为MNN_BUILD_MINI=ON再去编译源码，和编译出demo的执行文件。然后采用--saveStaticModel参数去保存mnn模型，就执行不通。
如果是MNN_BUILD_MINI=OFF编译源码，再用 --saveStaticModel去保存mnn文件，就可以执行通。

**Comment by jxt1234** [comment]
编译模型转换工具时不要设置 MNN_BUILD_MINI 为ON 。

这个 MNN_BUILD_MINI 仅限编译用于集成的 MNN 库
