### ISSUE TITLE
Onnx转mnn后使用python api做推理，如何还原动态维度的输出结果呢

### ISSUE THREAD

**Issue by AnyangAngus** [alibaba/MNN#2201]
pip install MNN=2.3.0
onnx的输入为固定维度[1380, 1850, 3]
onnx的输出为动态维度[-1, 5]
python fastTestOnnx.py model.onnx 输出TEST_SUCCESS
但使用python对转换后的MNN模型做推理， 如何还原动态维度的输出呢
我使用的demo代码如下:
```python
import MNN
interpreter = MNN.Interpreter("convert_cache.mnn")
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
print(input_tensor.getShape())
import numpy as np
ipt = np.load("/home/xxx.npy")
tmp_input = MNN.Tensor((1380,1850,3), MNN.Halide_Type_Uint8, ipt, MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(tmp_input)
interpreter.runSession(session)
output_tensor = interpreter.getSessionOutput(session, 'boxes')
output_tensor.getData()
```

**Comment by jxt1234** [comment]
输入维度不变，但输出维度变化，应该是有内容决定形状的情况，需要用 Expr/Module API 。参考 pymnn/examples/MNNExpr/mnn_numpy_cv_demo.py

**Comment by AnyangAngus** [comment]
> 
MNN.expr.convert(input_var, MNN.expr.NC4HW4)
尝试了这个Api, 发现input_var只支持np.int32类型的矩阵转换，因为模型的输入是uint8的，导致报错：*** RuntimeError: parameter `x` must be var_like.
请问有什么方法可以解决么

**Comment by AnyangAngus** [comment]
> 输入维度不变，但输出维度变化，应该是有内容决定形状的情况，需要用 Expr/Module API 。参考 pymnn/examples/MNNExpr/mnn_numpy_cv_demo.py

借鉴 fastTestOnnx.py
使用c++的 libMNN_Express.so Api做推理， 可以成功得到动态维度的输出
