### ISSUE TITLE
coreml推理出现问题

### ISSUE THREAD

**Issue by anliyuan** [alibaba/MNN#2207]
[coreml] The model expects input feature 0 to be an image, but the input (MultiArray : Float32 1 × 112 × 112 × 3 array) is of type 5.
[coreml] Failure verifying inputs.
Error executing model: The model expects input feature 0 to be an image, but the input (MultiArray : Float32 1 × 112 × 112 × 3 array) is of type 5.
Failed to Invok the Model.

**Comment by wangzhaode** [comment]
如果使用float输入，precision需要设置成normal；
precision = low的时候默认使用Image格式输入，即uint8类型；
