### ISSUE TITLE
2.3.0版本编译华为NPU报错

### ISSUE THREAD

**Issue by dlyshare** [alibaba/MNN#2208]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu18.04，目标平台为： armeabi-v7a

# Github版本:
# Github Version:
2.17

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

2023.2.2 下载的 2.3.0版本ZIP文件

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
先修改project/andoird/build_32.sh，增加了 -DMNN_NPU:BOOL=true 选项，在source中的hiai目录按要求增加了华为ddk的库，并对目录改名。

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
ndk版本尝试过r25b，r17, r14, r21等版本，均相同错误。
编译脚本中cmake参数如下 ：
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_shared \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_USE_SSE=OFF \
-DMNN_NPU=ON \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j16

# 编译日志:
# Build Log:
```
粘贴在这里
Paste log here or pastebin
```
1 warning generated.
[ 59%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUFloatToInt8.cpp.o
[ 59%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUGatherV2.cpp.o
[ 59%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUInstanceNorm.cpp.o
[ 59%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUInt8ToFloat.cpp.o
/home/jackie/prog/MNN-2.3.0/source/backend/hiai/execution/NPUDepthToSpace.cpp:42:78: error: expected '(' for function-style cast or type construction
        .SetAttr("NCHW_to_NHWC", ge::AttrValue::CreateFrom<ge::AttrValue::INT>(1));
                                                           ~~~~~~~~~~~~~~~~~~^
/home/jackie/prog/MNN-2.3.0/source/backend/hiai/execution/NPUDepthToSpace.cpp:52:78: error: expected '(' for function-style cast or type construction
        .SetAttr("NHWC_to_NCHW", ge::AttrValue::CreateFrom<ge::AttrValue::INT>(1));
                                                           ~~~~~~~~~~~~~~~~~~^
[ 59%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUInterp.cpp.o
[ 60%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUMatmul.cpp.o
[ 60%] Building CXX object source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUNonMaxSuppressionV2.cpp.o
2 errors generated.
source/backend/hiai/CMakeFiles/MNN_NPU.dir/build.make:257: recipe for target 'source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUDepthToSpace.cpp.o' failed
make[2]: *** [source/backend/hiai/CMakeFiles/MNN_NPU.dir/execution/NPUDepthToSpace.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1513: recipe for target 'source/backend/hiai/CMakeFiles/MNN_NPU.dir/all' failed
make[1]: *** [source/backend/hiai/CMakeFiles/MNN_NPU.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Linking CXX shared library ../libMNN_Express.so
[ 60%] Built target MNN_Express
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangzhaode** [comment]
请看这个issue是否有参考性: https://github.com/alibaba/MNN/issues/2125

**Comment by dlyshare** [comment]
我的情况不是2125的报错，我是修改了MNN代码编译通过了。


| |
段翰聪
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年2月15日 19:34 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [alibaba/MNN] 2.3.0版本编译华为NPU报错 (Issue #2208) |

请看这个issue是否有参考性: #2125
