### ISSUE TITLE
开源模型resnet18量化后精度很差？

### ISSUE THREAD

**Issue by Lenan22** [alibaba/MNN#2209]
我是在x86平台上跑的

# 编译方式:
vim option(MNN_BUILD_QUANTOOLS "Build Quantized Tools or not" ON)
./schema/generate.sh
mkdir build && cd build
cmake .. -DMNN_OPENCL=true -DMNN_SEP_BUILD=false -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_TORCH=true -DMNN_BUILD_DEMO=true -DMNN_BUILD_BENCHMARK=true -DMNN_BUILD_TOOLS=true -DCMAKE_INSTALL_PREFIX=./install
make -j8
make install

## 转换过程
./MNNConvert -f ONNX --modelFile resnet18.onnx --MNNModel resnet18_fp32.mnn --bizCode mnn

./quantized.out resnet18_fp32.mnn resnet18_int8.mnn quant.json

quant.json内容：
{
    "format":"RGB",
    "mean":[
        0.0,
        0.0,
        0.0
    ],
    "normal":[
        1.0,
        1.0,
        1.0
    ],
    "width":224,
    "height":224,
    "batch_size":1,
    "path":"/work/alibaba-mnn/resnet18/ImageNet_1k_quant_png_hwc"
}

路径path中的png图片都是预处理后的，所以mean为0，normal为1

我把量化后的resnet_int8.mnn和resnet_fp32.mnn针对同一个png图片做了推理，结果如下:
模型的输出shape是[1,1000]，为了方便对比，我各取了前100个数

fp32模型的前100个输出:
[12.742216    4.4360995   8.816084    8.670319    7.6019115   2.913645
  5.43311     4.121519    2.9392538   1.4992108   0.23089553  4.8504815
  3.9164364   2.315303    3.867383    1.1765555   3.3835804   3.7539146
 -0.7667724   3.1459823   0.35213944  4.769018    3.6413321   5.840478
  2.9826405   0.18909352  3.1657524  -0.47984263  0.5200454   8.089202
  4.156925    3.2206254   1.4942017   7.207699    3.4364457   3.249976
  6.176567    3.2939005   3.5007265  11.682398    8.2322855   4.17298
  4.2746296   7.3005633   4.6583605   4.180897    6.6968193   6.413568
 13.687677    9.298014    9.308926    5.807146   -0.97055656 -3.1188142
 -0.7083801   4.136017    0.47970003 -3.8439682   6.18503     0.3098549
  3.0525546   7.850658    8.582454    1.482417    4.6652594   2.5042086
  0.99332815  4.2170777   0.93517774 -1.6688769  -4.030277    2.1298537
 -1.8213689  -0.66111934 -0.0185784  -2.0918243   3.3557873   1.7106587
 -1.2701557  -0.01704757  1.0240293   1.5324826   5.995762    0.59092486
  4.954894    4.8788495   3.891735    4.4710894   6.0668545   4.7576785
  3.234582    4.321925    1.5749501   3.6988404   3.3425605   2.062288
  5.561131    2.9683585   0.13139708  2.8504062 ]

int8模型的前100个输出:
[-2.9946000e-13 -6.2425152e-26 -5.1914234e-26 -3.3275268e-36
 -3.1007260e-30 -2.4250283e-22  5.7946933e+36 -1.4460843e-29
 -8.7905518e-31 -1.7232076e-05 -6.3564145e-17 -2.7032648e-19
 -4.5441942e-21 -2.0472985e-25 -5.7463926e-38 -2.5677827e-34
 -2.1738226e-25 -7.0557313e-34  5.0006932e+30  3.3034200e+38
 -9.1997392e-37 -9.2502791e-28 -8.8723693e-28 -3.4562847e-33
 -3.2185754e-30 -6.3013587e-11 -1.4816603e-35  3.1349239e+35
  5.0601984e+30 -2.1231499e-37 -1.3725453e-32  2.2799070e+34
 -1.1215590e-35  9.2585622e+28  2.4835875e+28  1.9843077e+31
 -5.1091894e-29 -9.3090887e-34 -4.9209344e-32 -1.9178994e-37
 -8.9344872e-28 -3.3824666e-33 -6.0418257e-35 -3.1189674e-33
 -3.3847284e-33  9.5090482e+34 -1.3435812e-32 -1.8998488e-34
 -8.2770368e-34 -5.4638687e-29 -2.2046690e-34 -8.2256809e-25
  1.3767517e+36 -5.8804237e-26 -2.2430221e-31 -8.3759838e-37
 -2.3283446e-28 -5.6045302e-32 -1.5091716e-20 -1.3213844e-35
 -1.4445432e-29 -3.4471781e-27  9.5409895e+37 -2.1569663e-25
 -1.2635113e-38 -1.1730244e-35  3.3428303e+38 -4.4911296e-18
 -2.8061024e-19 -9.5013679e-22 -9.8444419e-34 -3.1092411e-19
 -1.7497968e-14 -1.6047986e-20 -2.1161626e-34  1.9186667e+34
  2.3117159e+34 -1.9219132e-31 -1.4204309e-32 -2.4704029e-28
  4.7503681e+24  7.8571722e+37 -8.9072934e-31 -2.3242790e-34
 -4.9140772e-35 -4.1084874e-18 -5.8368725e-32 -5.2477799e-35
 -8.3023990e-28 -9.0951007e-31 -6.1840889e-23 -2.7350104e-16
 -4.2780339e-21 -2.4748609e-22 -1.6948070e-14 -1.0763847e-21
 -2.4911377e-22 -7.8524514e-05 -3.5290225e-07  4.6669977e+30]

**Comment by Lenan22** [comment]
是我编译的quantized.out有问题？ 还是某个环节出了什么问题？为什么精度很差，可视化输出结果后差距这么大呢？？？

**Comment by m00nLi** [comment]
默认的KL量化策略不能用的，精度下降严重

**Comment by jxt1234** [comment]
已沟通， mean / normal 有问题，另外机器上运行 avx2 跑量化模型时目前有 bug ，2.3.1 更新后修正
