### ISSUE TITLE
谁给我发个MMN的windows lib啊，感激不尽啊

### ISSUE THREAD

**Issue by huillll** [alibaba/MNN#221]
本人尝试很多办法，运行出现这个错误
PS C:\Users\Administrator> cd .\MNN\
PS C:\Users\Administrator\MNN> cd .\schema\
PS C:\Users\Administrator\MNN\schema> .\generate.ps1
*** building flatc ***
False
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_6a367\fast &&       "E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_6a367.dir\build.make /nologo -L                  CMakeFiles\cmTC_6a367.dir\build
    Building C object CMakeFiles/cmTC_6a367.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe @C:\Users\ADMINI~1\AppData\Local\Temp\nm16D7.tmp
    testCCompiler.c
    Linking C executable cmTC_6a367.exe
        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_6a367.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\cmTC_6a367.dir\objects1.rsp @C:\Users\ADMINI~1\AppData\Local\Temp\nm18DB.tmp
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_6a367.dir/manifest.res CMakeFiles\cmTC_6a367.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。NMAKE : fatal error U1077: “"C:\Program Files\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
    Stop.
    NMAKE : fatal error U1077: “"E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\nmake.exe"”: 返回代码“0x2”
    Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeError.log".
NMAKE : fatal error U1073: 不知道如何生成“flatc”
Stop.
*** cleaning up ***
*** generating fbs under default ***
..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

..\..\3rd_party\flatbuffers\tmp\flatc.exe : 无法将“..\..\3rd_party\flatbuffers\tmp\flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ..\..\3rd_party\flatbuffers\tmp\flatc.exe -c -b C:\Users\Administrato ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\3rd_party...s\tmp\flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

===> Generating Schema...
*** building flatc ***
False
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeTmp

    Run Build Command(s):nmake /nologo cmTC_e9cfd\fast &&       "E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_e9cfd.dir\build.make /nologo -L                  CMakeFiles\cmTC_e9cfd.dir\build
    Building C object CMakeFiles/cmTC_e9cfd.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe @C:\Users\ADMINI~1\AppData\Local\Temp\nm1E97.tmp
    testCCompiler.c
    Linking C executable cmTC_e9cfd.exe
        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_e9cfd.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo @CMakeFiles\cmTC_e9cfd.dir\objects1.rsp @C:\Users\ADMINI~1\AppData\Local\Temp\nm1F44.tmp
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_e9cfd.dir/manifest.res CMakeFiles\cmTC_e9cfd.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。NMAKE : fatal error U1077: “"C:\Program Files\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
    Stop.
    NMAKE : fatal error U1077: “"E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\nmake.exe"”: 返回代码“0x2”
    Stop.

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Administrator/MNN/3rd_party/flatbuffers/tmp/CMakeFiles/CMakeError.log".
NMAKE : fatal error U1073: 不知道如何生成“flatc”
Stop.
../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Windows 的可靠文件复制
-------------------------------------------------------------------------------

  开始时间: 2019年8月7日 22:27:03
        源: C:\Users\Administrator\MNN\3rd_party\flatbuffers\include\flatbuffers\
      目标: C:\Users\Administrator\MNN\tools\converter\source\IR\flatbuffers\

      文件: *.*

      选项: *.* /S /E /DCOPY:DA /COPY:DAT /XO /XN /XC /R:1000000 /W:30

------------------------------------------------------------------------------

                          14    C:\Users\Administrator\MNN\3rd_party\flatbuffers\include\flatbuffers\

------------------------------------------------------------------------------

                  总数        复制        跳过       不匹配        失败        其他
       目录:         1         0         1         0         0         0
       文件:        14         0        14         0         0         0
       字节:   331.8 k         0   331.8 k         0         0         0
       时间:   0:00:00   0:00:00                       0:00:00   0:00:00
   结束时间: 2019年8月7日 22:27:03

../../3rd_party/flatbuffers/tmp/flatc.exe : 无法将“../../3rd_party/flatbuffers/tmp/flatc.exe”项识别为 cmdlet、函数、
脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ ../../3rd_party/flatbuffers/tmp/flatc.exe -c -b --reflect-types --gen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (../../3rd_party...s/tmp/flatc.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

===> Done!
*** done ***

**Comment by huillll** [comment]
谁能给我到邮箱2257878821@qq.com
我可以发红包感激不尽

**Comment by JeanXL** [comment]
您好，请问您解决了没？

**Comment by huillll** [comment]
可以啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jxt1234 <notifications@github.com&gt;
发送时间: 2019年11月3日 20:31
收件人: alibaba/MNN <MNN@noreply.github.com&gt;
抄送: huillll <2257878821@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[alibaba/MNN] 谁给我发个MMN的windows lib啊，感激不尽啊 (#221)




Closed #221.

**Comment by baicaiPCX** [comment]
已经有人解决了：https://blog.csdn.net/Hunter_pcx/article/details/128673577
