### ISSUE TITLE
MNN-2.3.0 CUDA backend inference error

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#2211]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Ubuntu 20.04 GCC-8.2 CUDA-11.5

MNN-Version: MNN-2.3.0 release

Graphic Cards: GTX-1070

# 编译方式:
# Compiling Method

-DCMAKE_BUILD_TYPE=Release -DMNN_CUDA=ON

CUDA后端测试分类模型，显示

File:/ MNN-2.3.0/source/backend/cuda/execution/ConvCutlassExecution.cu Line 917: failed: Error Internal
Aborted (core dumped)

这个问题该如何解决呢?

**Comment by bitxsw93** [comment]
-DCMAKE_BUILD_TYPE=Debug库，重新看下堆栈信息

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 好的，我再试一下。需要更新到latest master分支吗 还是这个release的版本就可以哈.

**Comment by bitxsw93** [comment]
最新的master分支测下吧，详细堆栈贴一下

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 好的，明天我测试一下:)

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 今天测试发现master分支 使用backendTest.out 工具测试cuda后端，如果设置precision为normal可以通过，如果为high则会core dump

```
~/workspace/MNN/cmake-build-release$ ./backendTest.out ~/workspace/weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn 2 0.05 1
Test forward type: 2
Tolerance Rate: 0.050000
Open Model /weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn
The device support dot:0, support fp16:0, support i8mm: 0
Input: 224,224,3,1
precision=1 in main, 271 
modeNum=1 in main, 276 
stopOp.c_str()=s  in main, 281 
File: workspace/MNN/source/backend/cuda/execution/ConvCutlassExecution.cu Line 368: failed: Error Internal
Aborted (core dumped)

~/workspace/MNN/cmake-build-release$ ./backendTest.out ~/workspace/weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn 2 0.05 0
Test forward type: 2
Tolerance Rate: 0.050000
Open Model /weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn
The device support dot:0, support fp16:0, support i8mm: 0
Input: 224,224,3,1
precision=0 in main, 271 
modeNum=1 in main, 276 
stopOp.c_str()=s  in main, 281 
Correct ! Run second pass
Correct !

```
在1.2.0上同样的测试没有问题

~/workspace/MNN-1.2.0/cmake-build-release$ ./backendTest.out ~/workspace/weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn 2 0.05 1
Test forward type: 2
Tolerance Rate: 0.050000
Open Model /weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn
Input: 224,224,3,1
precision=1 in main, 250 
modeNum=1 in main, 255 
stopOp.c_str()=s  in main, 260 
Correct ! Run second pass
Correct !

~/workspace/MNN-1.2.0/cmake-build-release$ ./backendTest.out ~/workspace/weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn 2 0.05 0
Test forward type: 2
Tolerance Rate: 0.050000
Open Model /weights/classification/mobilenetv2/mobilenetv2_ilsvrc2012.mnn
Input: 224,224,3,1
precision=0 in main, 250 
modeNum=1 in main, 255 
stopOp.c_str()=s  in main, 260 
Correct ! Run second pass
Correct !

···

Ps. master编译开启了 -DCMAKE_BUILD_TYPE=Debug。1.2.0编译使用release模式。

**Comment by MaybeShewill-CV** [comment]
@wangzhaode

**Comment by wangzhaode** [comment]
> @wangzhaode

麻烦 @bitxsw93  看一下吧

**Comment by bitxsw93** [comment]
@MaybeShewill-CV 我们这边1070显卡，你加下首页钉钉群，群里反馈下问题找下我。单聊给你看下

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 @wangzhaode GTX-3080显卡设置 precision_mode=Normal 目前可以解决这个问题:)
