### ISSUE TITLE
MNN的`MNN_BUILD_MINI`编译选项使用上是否存在错误？

### ISSUE THREAD

**Issue by foreverlms** [alibaba/MNN#2212]
我理解该选项打开意思就是要求用户转模型时就确保模型的输入是固定的，shape信息是正确无误的；MNN则去除掉ShapeInfer。
但是我在Executor.cpp里发现反过来了：
```
#ifdef MNN_BUILD_MINI
        SizeComputerSuite::init();
        GeometryComputer::init();
#endif
```
按理说不应该是#ifndef吗？

**Comment by jxt1234** [comment]
这里是希望 MNN_Expr 在 Mini 模式下仍然具备 shape 计算的能力。现在这段逻辑应该是有问题的，我们后续修正一下
