### ISSUE TITLE
unity加载release版本MNN.dll 崩溃

### ISSUE THREAD

**Issue by icechenbing** [alibaba/MNN#2214]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows 11

# Github版本:
# Github Version:
最新版本

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
windows_x64_travis.bat构建
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
![db7c5292-eadc-409b-b654-65e16a085703](https://user-images.githubusercontent.com/6427220/217485405-24eea49b-83d7-45c8-84db-8a2936f1008f.jpeg)
```

**Comment by icechenbing** [comment]
![db7c5292-eadc-409b-b654-65e16a085703](https://user-images.githubusercontent.com/6427220/217485626-302bfd9d-1c6c-4481-b02a-4695548f4815.jpeg)

**Comment by icechenbing** [comment]
debug版本MNN.dll不会出现该问题

**Comment by wangzhaode** [comment]
能否联调看下crash再合处，只看这个截图无法判断
