### ISSUE TITLE
Inference of quantized model on python

### ISSUE THREAD

**Issue by lukseny** [alibaba/MNN#2218]
Hi everyone!
I've faced the following problem: after quantization I can't run model inference on python correctly. The logs are 'recover int8 weights error'. What can be the issue here and how to deal with it? (before quantization mnn model runs perfectly)
I'm using MNN library
'''
interpreter = MNN.Interpreter(args.model_path)
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
...
tmp_input = MNN.Tensor((1, 3, input_size[1], input_size[0]), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(tmp_input)
interpreter.runSession(session)
scores = interpreter.getSessionOutput(session, "scores").getData()
boxes = interpreter.getSessionOutput(session, "boxes").getData()
'''

**Comment by wangzhaode** [comment]
can you provide the quantization model ?

**Comment by yyfcc17** [comment]
use latest code & latest pymnn
