### ISSUE TITLE
一个简单的模型转成mnn模型进行推理，在createSession时出现报错

### ISSUE THREAD

**Issue by qaz734913414** [alibaba/MNN#222]
> Error for F:\MNN\source\shape\ShapeTensorConvert.cpp, 44
Resize error for dense_2___tr4activation_6, code=3

请问该如何解决此问题？

**Comment by czy2014hust** [comment]
Please update your code, there is no MNN_ASSERT in [line 44](https://github.com/alibaba/MNN/blob/master/source/shape/ShapeTensorConvert.cpp#L44)

**Comment by qaz734913414** [comment]
但是我就是用的最新代码，自己转出来的模型有问题，但是用别人转的mnn模型可以运行

**Comment by li-qing** [comment]
> 但是我就是用的最新代码，自己转出来的模型有问题，但是用别人转的mnn模型可以运行

那么新代码的报错是？

**Comment by qaz734913414** [comment]
> Error for F:\MNN\source\shape\ShapeTensorConvert.cpp, 44
Resize error for dense_2___tr4activation_6, code=3
还是一样的错误

**Comment by zeyuanlicbpm** [comment]
我用mxnet->onnx->mnn转换模型，报类似的错误：
![image](https://user-images.githubusercontent.com/33452561/63346673-16fa9400-c388-11e9-8e1d-d182349564b6.png)
![image](https://user-images.githubusercontent.com/33452561/63346689-1feb6580-c388-11e9-9b24-bbf1eb88967b.png)

可能的原因是？

**Comment by yizhaoyanbo** [comment]
@li-qing @czy2014hust 
我遇到了同样的问题，更新的是8月23号最新的代码，windows下编译库，模型转换也正常，前向推理mobilenetv2训练的分类模型。debug模式下会在runsession时报错，错误如下：
![image](https://user-images.githubusercontent.com/26928415/63911751-eb4d6d00-ca5d-11e9-90d8-dd0ef3e2d4e9.png)
Release下不报错，但是结果有时候执行是对的，有时候是不对的。

**Comment by li-qing** [comment]
> @li-qing @czy2014hust
> 我遇到了同样的问题，更新的是8月23号最新的代码，windows下编译库，模型转换也正常，前向推理mobilenetv2训练的分类模型。debug模式下会在createSession时报错，错误如下：
> The ____reshape____outTensor's input is not ready
> Resize error for ____reshape____outTensor, code=3
> 
> Release下不报错，但是结果有时候执行是对的，有时候是不对的。

这里的input is not ready指____reshape____outTensor的某个输入的size <= 0。

Release下不报错只是因为关闭了日志，问题依然还在。

建议检查一下数据输入的大小，尤其存在resize的情况。

**Comment by MaybeShewill-CV** [comment]
@li-qing 遇到類似的問題. 

- MNN source code: 0.2.0.6 

- tensorflow pb文件使用tensorflow調用正常工作, 使用MNNConverter轉換模型過程也正常 沒有錯誤和異常
![Screenshot from 2019-09-10 17-49-47](https://user-images.githubusercontent.com/15725187/64603738-6cf4b180-d3f3-11e9-9e80-8800c8dfc3c6.png)

- 測試代碼片段如下
![Screenshot from 2019-09-10 17-51-16](https://user-images.githubusercontent.com/15725187/64603863-9ad9f600-d3f3-11e9-930f-beb6d4ee0b61.png)
編譯成功 沒有錯誤和異常 運行時在createSession部分出錯
![Screenshot from 2019-09-10 17-46-11](https://user-images.githubusercontent.com/15725187/64603916-b80ec480-d3f3-11e9-8979-c050717d3c7a.png)

可能是哪裏有問題呢?

**Comment by jiarenyf** [comment]
试试0.2.0.9版本。。。



---原始邮件---
发件人: "MaybeShewill-CV"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 下午5:52
收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [alibaba/MNN] 一个简单的模型转成mnn模型进行推理，在createSession时出现报错 (#222)



@li-qing 遇到類似的問題.
  
 
MNN source code: 0.2.0.6
 

 
tensorflow pb文件使用tensorflow調用正常工作, 使用MNNConverter轉換模型過程也正常 沒有錯誤和異常
 
 

 
測試代碼片段如下
 
 編譯成功 沒有錯誤和異常 運行時在createSession部分出錯
 
 
 
可能是哪裏有問題呢?

**Comment by MaybeShewill-CV** [comment]
@jiarenyf 你也遇到過這個問題嗎

**Comment by MaybeShewill-CV** [comment]
@jiarenyf 切換了0.2.0.9版本依然是這個問題
![Screenshot from 2019-09-10 18-51-13](https://user-images.githubusercontent.com/15725187/64608069-6e76a780-d3fc-11e9-8e3c-45f4ab087d2e.png)

**Comment by jiarenyf** [comment]
试试debug一下，或者cmakelist里面打开mnn_debug，看一下输出。



---原始邮件---
发件人: "MaybeShewill-CV"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 晚上6:54
收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"jiarenyf"<yfjiaren@foxmail.com&gt;;
主题: Re: [alibaba/MNN] 一个简单的模型转成mnn模型进行推理，在createSession时出现报错 (#222)



@jiarenyf 切換了0.2.0.9版本依然是這個問題

**Comment by zeyuanlicbpm** [comment]
好的




------------------ 原始邮件 ------------------
发件人: "jiarenyf"<notifications@github.com>; 
发送时间: 2019年9月10日(星期二) 晚上7:03
收件人: "alibaba/MNN"<MNN@noreply.github.com>; 
抄送: "GZSHD"<zeyuan.li.cbpm@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [alibaba/MNN] 一个简单的模型转成mnn模型进行推理，在createSession时出现报错 (#222)



试试debug一下，或者cmakelist里面打开mnn_debug，看一下输出。 
 
 
 
 ---原始邮件--- 
 发件人: "MaybeShewill-CV"<notifications@github.com&gt; 
 发送时间: 2019年9月10日(星期二) 晚上6:54 
 收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;; 
 抄送: "Mention"<mention@noreply.github.com&gt;;"jiarenyf"<yfjiaren@foxmail.com&gt;; 
 主题: Re: [alibaba/MNN] 一个简单的模型转成mnn模型进行推理，在createSession时出现报错 (#222) 
 
 
 
 @jiarenyf 切換了0.2.0.9版本依然是這個問題

**Comment by MaybeShewill-CV** [comment]
@li-qing @jiarenyf 打開mnn_debug輸出如下
![Screenshot from 2019-09-10 19-17-10](https://user-images.githubusercontent.com/15725187/64609531-bb0fb200-d3ff-11e9-9dd1-e8ed8cd7a9a0.png)

**Comment by li-qing** [comment]
ellipsis mask & new axis mask未支持
