### ISSUE TITLE
RK3588编译MNN的whl包

### ISSUE THREAD

**Issue by DDX1126** [alibaba/MNN#2221]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

rk3588-armv8-aarch64(本地编译)
ubuntu 18.04

# Github版本:
# Github Version:
    https://github.com/alibaba/MNN/tree/master

(1) 需要将build_whl里面的plat-name修改成什么名字
(2)需要将setup.py文件的plat修改成什么名字？

**Comment by wangzhaode** [comment]
直接执行以下命令有什么问题吗？
```
cd pymnn/pip_package
python3 build_deps.py
sudo python3 setup.py install --version 2.3.0
```

**Comment by DDX1126** [comment]
平台名称不对，里面给的是x86的，但是arm的编译没有相应的选项可以选择，官方文档也没写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/MNN] RK3588编译MNN的whl包 (Issue #2221)




 
直接执行以下命令有什么问题吗？
 cd pymnn/pip_package python3 build_deps.py sudo python3 setup.py install --version 2.3.0

**Comment by wangzhaode** [comment]
请贴一下报错信息

**Comment by DDX1126** [comment]
好的👌



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月15日(周三) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/MNN] RK3588编译MNN的whl包 (Issue #2221)




 
请贴一下报错信息

**Comment by wangzhaode** [comment]
> 平台名称不对，里面给的是x86的，但是arm的编译没有相应的选项可以选择，官方文档也没写
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年2月15日(周三) 上午10:14 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [alibaba/MNN] RK3588编译MNN的whl包 (Issue #2221) 直接执行以下命令有什么问题吗？ cd pymnn/pip_package python3 build_deps.py sudo python3 setup.py install --version 2.3.0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

官方文档只会针对主要平台；不会包含所有的

**Comment by wangzhaode** [comment]
长时间未回复；编译可以参考：https://github.com/alibaba/MNN/issues/1051
