### ISSUE TITLE
在使用gpu时，cache文件生成和什么因素有关

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2222]
hi:

    想请教一下，在gpu 初始化时，为了提升初始化的时间，生成的cache文件，跟什么因素有关呢？机型？还是配置参数？
比如，我们的tuning 参数设置config.mode = MNN_GPU_TUNING_WIDE | MNN_GPU_MEMORY_IMAGE;
在这种方式下生成的cache文件，在调用时，必须还得是这种配置才行吗？如果更改，会重新生成cache吗？

谢谢

**Comment by jxt1234** [comment]
1. 与 MNN_GPU_MEMORY_IMAGE / BUFFER 有关，与 MNN_GPU_TUNING_WIDE / NONE 无关。
2. 不需要重新生成，如果 cache 中找不到对应的项，会去增加

**Comment by wangzhaode** [comment]
问题已解答
