### ISSUE TITLE
请问同一个MNN模型可以在AOS和IOS 共用吗？

### ISSUE THREAD

**Issue by bakboem** [alibaba/MNN#2232]
模型在安卓端可用，现在想在ios端引用相同的模型。
我已经在Flutter plugin端 引入了MMN.framework 和 opencv，导入MNN的各种头文件均没报错。
这种情况下，我想直接把以.MNN为后缀的量化模型 复制到插件ios包里调用它，这会不会出问题啊？
这个量化模型是参考https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB 制作的。
因为安卓模型是前辈们做的，我并不清楚制作的过程，现在就想知道这个模型可不可以在IOS共用。谢谢费心解答！

**Comment by wangzhaode** [comment]
MNN的模型是可以共用的，不区分平台系统的；

**Comment by bakboem** [comment]
@wangzhaode  非常感谢！
