### ISSUE TITLE
android 和 x86精度不一致问题

### ISSUE THREAD

**Issue by wwkww** [alibaba/MNN#2236]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by wwkww** [comment]
使用MNNV2Basic.out在x86和android上跑mobilenet，相同的模型和输入数据，输出结果会有小数后几位的误差

**Comment by wangzhaode** [comment]
> 输出结果会有小数后几位的误差
这个误差是合理的；不同平台之间底层是线上可能会有略微差异

**Comment by wwkww** [comment]
好的，谢谢
