### ISSUE TITLE
RK3588s support?

### ISSUE THREAD

**Issue by Crazylov3** [alibaba/MNN#2237]
I have RK3588s from rockchip. Currently, I use rknn toolkitv2 from to convert torch model to rknn format in order to run in NPU, however that api is poor support. I wonder that can I use MNN intead? Do MNN support convert to the format which can run in NPU in RK3588s?
Many thanks

**Comment by wangzhaode** [comment]
MNN don't support RK3588s NPU. You can use CPU/GPU with MNN.
