### ISSUE TITLE
怎么把输出的特征图保存成图片（转换成opencv然后保存也可）

### ISSUE THREAD

**Issue by zhenxing9968** [alibaba/MNN#2238]
类似demo/segment.cpp，获得的outputTensor怎么保存成图片呢？

```
net->runSession(session);
auto outputTensor = net->getSessionOutput(session, nullptr);
```

**Comment by wangzhaode** [comment]
- 如果使用opencv，可以吧outputTensor内的数据拷贝的`cv::Mat`中，然后使用`cv::imwrite`保存成图片；
- 如果使用MNN内的cv函数，可以先将`Tensor`转换为`Var`，然后使用`imwrite`保存成图片；
