### ISSUE TITLE
GRU模型pb转onnx再转mnn推理结果错误

### ISSUE THREAD

**Issue by maoxin7676** [alibaba/MNN#2239]
# 1.遇到主要问题
* **主要问题：项目中GRU模型pb转onnx再转mnn推理结果错误，但推理速度很快，需要解决这种情况推理准确性问题**
* pb直接转mnn推理速度很慢结果正常，推理速度不符合项目要求

# 2.采用模型介绍
采用如下tensorflow代码生成一个gru模型
```
#!/usr/bin/python
from __future__ import print_function
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "-1"
from keras.layers import Input
from keras.models import Model
from keras.layers import GRU
noise_input = Input(batch_shape=(1, 1, 90), name='noise_input',)
state_noise_gru = Input(batch_shape=(1, 48), name="state_noise_gru")
(noise_gru, state_noise) = GRU(48, activation='relu', recurrent_activation='sigmoid', return_sequences=True, name='noise_gru',
                unroll=True, return_state=True)(noise_input, initial_state=state_noise_gru)
model = Model(inputs=[noise_input,state_noise_gru], outputs=[noise_gru, state_noise])
model.load_weights("mnn_issues.hdf5")
```
采用如上代码，生成模型，并将模型转成了""mnn_issues.pb""
# 3.pb转onnx再转mnn过程
## 3.1 pb2onnx
```
python -m tf2onnx.convert --input mnn_issues.pb --inputs noise_input:0,state_noise_gru:0 --outputs noise_gru/transpose_1:0 noise_gru/gru_cell_1/add_3:0 --output mnn_issues.onnx
```
## 3.2 onnx2mnn
```
./MNNConvert -f ONNX --modelFile mnn_issues.onnx --MNNModel mnn_issues.mnn --bizCode biz
```
# 4.pb转mnn过程
```
./MNNConvert -f TF --modelFile mnn_issues.pb --MNNModel mnn_issues_pb2mnn.mnn --bizCode biz
```
# 5.部署方式
* 平台: Ubuntu 18.04.6
*  Github版本: 2.3.1
# 6.附件说明
* 附件1：c++ 以及python的推理代码，可以参考供比对使用
* 附件2：各个阶段的模型文件（pb, mnn,onnx等）

[pthon及c测试代码.zip](https://github.com/alibaba/MNN/files/10811874/pthon.c.zip)

[mnn_issues.zip](https://github.com/alibaba/MNN/files/10811830/mnn_issues.zip)

**Comment by wangzhaode** [comment]
onnx转换出来的mnn模型结果是否能给onnx对齐呢

**Comment by maoxin7676** [comment]
> onnx转换出来的mnn模型结果是否能给onnx对齐呢
* onnx 采用python推理 结果正确
* 很奇怪的，pb转onnx再转mnn 的结果用python推理也是结果正确，但是c++ 的结果不正确。按道理说，底层应该也是c++ 推理的

**Comment by wangzhaode** [comment]
pb -> onnx -> mnn 这条链路转换得到的mnn用Python推理正确，用C++不正确嘛？

**Comment by wangzhaode** [comment]
看了一下你的C++代码有问题，不能直接给input拷贝数据，需要使用`copyFromHost`函数;

请仔细阅读[文档](https://mnn-docs.readthedocs.io/en/latest/inference/session.html)！

**Comment by maoxin7676** [comment]
> 看了一下你的C++代码有问题，不能直接给input拷贝数据，需要使用`copyFromHost`函数;
> 
> 请仔细阅读[文档](https://mnn-docs.readthedocs.io/en/latest/inference/session.html)！

采用pb转mnn，C++这种直接拷贝的方式是没有问题的。我试一下copyFromHost

**Comment by wangzhaode** [comment]
> > 看了一下你的C++代码有问题，不能直接给input拷贝数据，需要使用`copyFromHost`函数;
> > 请仔细阅读[文档](https://mnn-docs.readthedocs.io/en/latest/inference/session.html)！
> 
> 采用pb转mnn，C++这种直接拷贝的方式是没有问题的。我试一下copyFromHost

有可能不出错 但是也是不正确的用法；你改正后再测试一下看看onnx链路的结果是否正常

**Comment by maoxin7676** [comment]
> > > 看了一下你的C++代码有问题，不能直接给input拷贝数据，需要使用`copyFromHost`函数;
> > > 请仔细阅读[文档](https://mnn-docs.readthedocs.io/en/latest/inference/session.html)！
> > 
> > 
> > 采用pb转mnn，C++这种直接拷贝的方式是没有问题的。我试一下copyFromHost
> 
> 有可能不出错 但是也是不正确的用法；你改正后再测试一下看看onnx链路的结果是否正常
已经改成正确的用法，计算出的结果和原onnx 链路相同。
```
auto nchwTensor = new Tensor(inputs["noise_input:0"], Tensor::CAFFE);
    for (int i = 0; i < 90; i++)
    {
        nchwTensor->host<float>()[i] = input[i];
    }
    auto nchwTensor1 = new Tensor(inputs["state_noise_gru:0"], Tensor::CAFFE);
    for (int i = 0; i < 48; i++)
    {
        nchwTensor1->host<float>()[i] = input1[i];
    }
    inputs["noise_input:0"]->copyFromHostTensor(nchwTensor);
    inputs["state_noise_gru:0"]->copyFromHostTensor(nchwTensor1);

    delete nchwTensor;
    delete nchwTensor1;
```

**Comment by wangzhaode** [comment]
我测试了下ONNX可能确实有问题；我找一下原因

**Comment by maoxin7676** [comment]
> 我测试了下ONNX可能确实有问题；我找一下原因
这个问题有没有进展?

**Comment by wangzhaode** [comment]
嗯 模型中有一个带参数的`split`转换之后结果与ONNX不一致；我们在下个版本发布的时候会修复该问题；到时候我会同步在这个issue下

**Comment by wangzhaode** [comment]
![image](https://user-images.githubusercontent.com/8401806/223611533-0cae6868-b243-49ee-8fe2-99a4aac2f047.png)
你可以把这个split__11先改成`[48, 48]`就可以正确执行了

**Comment by jxt1234** [comment]
split 相关算子已经修正，更新版本到 2.6.2 及以上测试，如果仍有问题再重新提 issue
