### ISSUE TITLE
Cannot build MNN

### ISSUE THREAD

**Issue by deargqy** [alibaba/MNN#224]
Hi,

  I use Centos 7,  GCC  7.3.0, Cmake 3.9.2  protobuf 3.9.1 and followed your instruction to build MNN. Unfortunately, I got the following error.

![image](https://user-images.githubusercontent.com/32410576/62752099-abb3e680-ba98-11e9-8b22-3081f31c741d.png)

  It seems like there is something wrong according to the functions begin with '_mm256'  

  Thanks

**Comment by zoooo0820** [comment]
I've met the same problem. Could you please share how to solve it? Thanks.

**Comment by deargqy** [comment]
> I've met the same problem. Could you please share how to solve it? Thanks.

I changed the environment.

Ubuntu 18.04
gcc version 7.4.0
libprotoc 3.6.1
cmake version 3.10.2

**Comment by zoooo0820** [comment]
Got it. I've also build MNN successfully under Ubuntu 16.04 LTS instead of Centos 7. It seems like a system problem.
