### ISSUE TITLE
如何进行metal的benchmark测试？

### ISSUE THREAD

**Issue by 17818587795** [alibaba/MNN#2240]
没有找到能够进行Metal的benchmark测试，也许playground可以进行，但是执行会卡住，这是什么原因？
<img width="590" alt="截屏2023-02-24 09 55 56" src="https://user-images.githubusercontent.com/49740899/221073050-991a5521-b29c-4604-8264-2e9b027d4232.png">

**Comment by wangzhaode** [comment]
你需要修改Playground中的源文件`project/ios/Playground/AppDelegate.mm`
把目前的代码注释掉，打开BENCHMARK的部分

**Comment by 17818587795** [comment]
解决了，感谢你的帮助
