### ISSUE TITLE
tanh运算符的精度问题

### ISSUE THREAD

**Issue by Embed-Debuger** [alibaba/MNN#2241]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04
Python 3.7
MNN 2.3.0

# 描述
我使用tanh的和角公式来检查了tanh运算符的性能。我发现它的误差error很大。我进一步使用allclose函数检查它的相对误差，flag为false，这说明可能在tanh运算符上出现了精度的性能问题。我们设置的数值范围为[-1,1]，扰动范围为[-1,1]。

# 实现代码
import MNN.expr as _F
from MNN.expr import tanh
import numpy
import MNN.numpy as np

if __name__ == "__main__":
    shape = (10, 3, 32, 32)
    R=1
    for i in range(100):
        data = np.array(numpy.random.uniform(-1, 1, shape).tolist(), dtype=_F.float)
        delta = np.array(numpy.random.uniform(-R, R, 1).tolist(), dtype=_F.float)
        source_result = tanh(data + delta)
        follow_result = (tanh(data) + tanh(delta)) \
                        / (1 + tanh(data) * tanh(delta))
        error = np.sum(abs(source_result-follow_result))
        flag = numpy.allclose(source_result.read(), follow_result.read())
        print(i, error, flag)

# 完整错误日志

```
The device support dot:0, support fp16:0, support i8mm: 0
0 0.0022080030757933855 False
1 1.473619818687439 False
2 0.007464563474059105 False
3 0.07846873998641968 False
4 0.008638249710202217 False
5 0.03888801857829094 False
6 0.25329676270484924 False
7 0.027687640860676765 False
8 0.6051061749458313 False
9 0.22141718864440918 False
10 0.26929062604904175 False
11 1.9354978799819946 False
12 0.0415191724896431 False
13 0.010270325466990471 False
14 0.15201985836029053 False
15 0.684792697429657 False
16 0.17752912640571594 False
17 0.032008830457925797 False
18 0.015209631994366646 False
19 0.0029680205043405294 False
20 0.03578580915927887 False
```

**Comment by wangzhaode** [comment]
MNN使用的float32计算，tanh的和角公式计算出来的结果却是存在误差；用numpy的float32来计算这里一样也都是False
