### ISSUE TITLE
使用反卷积计算傅里叶逆变换速度慢

### ISSUE THREAD

**Issue by MicroYu-jt** [alibaba/MNN#2242]
# 平台:  cortex-a35, cortex-a53
最近在做语音相关的任务，其中使用了反卷积实现傅里叶逆变换，算子细节如下图所示：
![image](https://user-images.githubusercontent.com/68805221/221418805-e253974d-628e-4e8b-addd-aab7f743ad4d.png)

使用MNN编译出来的工具进行测试，这个算子的计算消耗了60%以上的推理时间，请问针对这些大卷积核的反卷积算子有对应的优化手段吗？

**Comment by wangzhaode** [comment]
请问运行设备和耗时是多少

**Comment by MicroYu-jt** [comment]
> 请问运行设备和耗时是多少

树莓派model3b，cortex-a53，1.2GHz，50次推理平均用时60ms
算子943就是iSTFT
![image](https://user-images.githubusercontent.com/68805221/221471994-16970214-81c8-453b-8d59-e6e10cd4f4ea.png)

**Comment by jxt1234** [comment]
相关模型发我们研究一下吧

**Comment by MicroYu-jt** [comment]
这个是我模型的ONNX文件，使用MNN编译出的工具进行转换和测试


1286547293
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/MNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月28日(星期二) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/MNN] 使用反卷积计算傅里叶逆变换速度慢 (Issue #2242)





 
相关模型发我们研究一下吧

**Comment by MicroYu-jt** [comment]
> 相关模型发我们研究一下吧

好的，我邮件到您的主页邮箱了。

**Comment by MicroYu-jt** [comment]
补充一下上面的结果图，333算子是使用卷积实现的傅里叶变换，其理论上的浮点运算数与943算子一样，但是运行时间却差得很远
