### ISSUE TITLE
seaformer 语义分割模型转换MNN推理输出不对

### ISSUE THREAD

**Issue by ghoshaw** [alibaba/MNN#2243]
# 问题:  
使用最新的seaformer网络训练语义分割,训练完成后pytorch->onnx->mnn. 然后使用 Python调用MNN和onnxruntime测试运行结果. 发现MNN的运行结果不对. 具体表现为两种错误: 
1.我的模型输入为1X3X360X480, 输出为1X9X360X480, 如果我用MNN1.1.0的转换工具, 并且torch-onnx 的opt设为11时,转换MNN时没有warning,一切正常, 在opt设为13时,会有warning(WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.),但是也转换成功了. 在推理测试的时候,onnx的输出没有问题,但是MNN的输出的维度就不对,本来应该是 1X9X360X480,但是MNN输出为[2073600,], 算下来是12*360*480,多了3个通道.  
2.如果我用MNN的转换工具版本和推理版本一致,则有可能输出对的 数据维度,但是数值不对.
![image](https://user-images.githubusercontent.com/23494873/221464647-0e93cd13-1a94-41cf-98af-8d24c3d9fee8.png)

总之我从三个变量上去做实验, torch的版本,optset, MNN的转换工具, 遍历的方式做实验,都没有找到一种方案能得到正常的MNN的输出.

请问这个MNN输出维度多了一些通道一般是什么原因呢?
上传了两个 onnx模型,希望能帮我分析下.

[seaformer.zip](https://github.com/alibaba/MNN/files/10835764/seaformer.zip)

**Comment by wangzhaode** [comment]
初步测试了一下：`4_model_opt11_torch131.onnx` 这个模型转换与执行都没有问题，结果与ONNX一致的；

**Comment by wangzhaode** [comment]
你可以用[testMNNFromOnnx.py ](https://mnn-docs.readthedocs.io/en/latest/tools/convert.html#id3)工具测试一下

**Comment by ghoshaw** [comment]
我用MNN2.3.1中的这个工具测试报错了:
python ./pythonTestOnnx.py /xx/4_model_opt11_torch131.onnx 
中间有warning,最后报错了.
warning 是 这种

2023-02-27 14:13:20.783855110 [W:onnxruntime:, graph.cc:1220 Graph] Initializer backbone.trans1.transformer_blocks.0.attn.pos_emb_rowq.pos_embed appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
2023-02-27 14:13:20.783877670 [W:onnxruntime:, graph.cc:1220 Graph] Initializer backbone.trans1.transformer_blocks.0.attn.pos_emb_rowk.pos_embed appears in graph inputs and will not be treated as constant value/weight. This may prevent some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.

报错是:
['output']
inputs:
data
outputs:
onnx/output.txt (1, 9, 360, 480)

usage: mnnconvert [-h] -f {TF,CAFFE,ONNX,TFLITE,MNN} --modelFile MODELFILE
                  [--prototxt PROTOTXT] --MNNModel MNNMODEL [--fp16 FP16]
                  [--weightQuantBits WEIGHTQUANTBITS]
                  [--compressionParamsFile COMPRESSIONPARAMSFILE]
mnnconvert: error: unrecognized arguments: --bizCode test

Error for open temp.bin
Traceback (most recent call last):
  File "./pythonTestOnnx.py", line 62, in <module>
    v = varsMap[name]
KeyError: 'data'

**Comment by jxt1234** [comment]
看下 https://mnn-docs.readthedocs.io/en/latest/faq.html#tensor-elementsize ，一般是你输入输出没有做内存布局转换的原因

**Comment by ghoshaw** [comment]
怎么做内存布局转换?我好像没找到Python API. 下面是我现在用的推理代码,输出size不对.

`
# load model
        self.model_path = model_path
        self.interpreter = self.MNNlib.Interpreter(self.model_path)
        self.session = self.interpreter.createSession()
        self.input_tensor = self.interpreter.getSessionInput(self.session)
        self.interpreter.resizeTensor(self.input_tensor, (1, 3, 360, 480))
        self.interpreter.resizeSession(self.session)

    def infer_image(self, img_input):
        # print('MNN  infer :  ',img_input.shape)
        tmp_input = self.MNNlib.Tensor(
            (1, 3, 360, 480),
            self.MNNlib.Halide_Type_Float,
            img_input,
            self.MNNlib.Tensor_DimensionType_Caffe
        )
        self.input_tensor.copyFrom(tmp_input)
        self.interpreter.runSession(self.session)

        output_tensor = self.interpreter.getSessionOutput(self.session)
        tmp_output = self.MNNlib.Tensor((1, 9, 360, 480), self.MNNlib.Halide_Type_Float, np.ones([1, 9, 360, 480]).astype(np.float32), self.MNNlib.Tensor_DimensionType_Caffe)
        output_tensor.copyToHostTensor(tmp_output)
        print('>>>>>>>>>>debug:   mnn output shape sss:    \n',np.array(tmp_output).shape)
        # score_out_name = ["output"]
        # scores = [self.interpreter.getSessionOutput(self.session, x).getData() for x in score_out_name]
        scores = np.array(self.interpreter.getSessionOutput(self.session, 'output').getData() )
`

**Comment by wangzhaode** [comment]
> 

你应该取`tmp_output`的值

**Comment by ghoshaw** [comment]
好的，明白了，不能直接用scores = np.array(self.interpreter.getSessionOutput(self.session, 'output').getData() )。 谢谢。
