### ISSUE TITLE
onnx转换成mnn模型结果无法对齐，使用testMNNFromOnnx.py DEBUG还是无法定位

### ISSUE THREAD

**Issue by wwdok** [alibaba/MNN#2245]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
windows

# Github版本:
最新版本，昨天刚拉的

# 编译方式:
无

# 问题描述:
我要把这个onnx模型
[model.zip](https://github.com/alibaba/MNN/files/10846183/model.zip)
转成mnn模型，但推理后发现结果无法对齐，于是想使用`testMNNFromOnnx.py DEBUG`来定位出错节点，但该脚本似乎有bug，中途报了错，如下log所示：
```
PS D:\AI\repos\MNN\tools\script> python testMNNFromOnnx.py model.onnx DEBUG
Dir exist
Debug Mode:  True
onnx\test.onnx
tensor(float)
['input.403']
inputs:
input
onnx/
outputs:
onnx/input.403.txt (1, 8, 72, 96)
onnx/
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[10:49:17] @ 40: ONNX Model ir version: 6
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ input.403, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : Conv_137 False
onnx\test.onnx
tensor(float)
['onnx::Conv_266']
inputs:
input
onnx/
outputs:
onnx/onnx::Conv_266.txt (1, 8, 72, 96)
onnx/
Traceback (most recent call last):
  File "testMNNFromOnnx.py", line 275, in <module>
    t.Debug()
  File "testMNNFromOnnx.py", line 266, in Debug
    self.__binary_search(left_id, right_id)
  File "testMNNFromOnnx.py", line 239, in __binary_search
    if self.__test_specify_output(self.node_output[test_node][0]):
  File "testMNNFromOnnx.py", line 185, in __test_specify_output
    res = self.Test()
  File "testMNNFromOnnx.py", line 259, in Test
    self.__run_onnx()
  File "testMNNFromOnnx.py", line 175, in __run_onnx
    f = open(name, 'w')
OSError: [Errno 22] Invalid argument: 'onnx/onnx::Conv_266.txt'
```
我猜测是脚本没有在onnx文件夹内生成假数据onnx::Conv_266.txt。我这个模型是类U-Net模型，decoder会逐层去拿encoder的中间输出，onnx::Conv_266位于模型横向桥接最浅的那一层。

**Comment by jxt1234** [comment]
先不要加 DEBUG ，看下结果是什么。DEBUG 是在确定模型转到 MNN 有误才用的（不加 DEBUG 时报错）。

**Comment by jxt1234** [comment]
收到，我看一下

**Comment by jxt1234** [comment]
我测试了最新代码（2.4.0）是 TEST_SUCCESS 的，你更新代码重编后再试下

[16:16:48] /Users/xtjiang/alicnn/GithubMNN/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 6
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ confidence, heatmap, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
input
output: heatmap
output: confidence
heatmap: (1, 2, 144, 192, )
confidence: (1, 1, )
TEST_SUCCESS

**Comment by jxt1234** [comment]
呃，这个脚本需要在编译了 MNNConvert 的路径下运行。进入 build 目录并且执行 python3 ../tools/scripts/testMNNFromOnnx.py XXX.onnx
