### ISSUE TITLE
如何对模型的参数进行深拷贝？

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2248]
因为研究需要，我需要把model->parameters()返回的参数进行深拷贝，请问如何对VARP变量，特别是model->parameters()返回的VARP 进行深拷贝？

非常感谢！

**Comment by wangzhaode** [comment]
如果深拷贝到别的`VARP`可以用[_Clone](https://mnn-docs.readthedocs.io/en/latest/cpp/NeuralNetWorkOp.html#clone)函数；
如果是想拷贝出内部的数据，可以用`var->readMap<float>()`获取数据指针，然后使用`memcpy`进行数据拷贝；

**Comment by fubukishiro** [comment]
我需要实现的功能是之后把model->parameters()返回的参数的数值重新加载回模型，目前的做法是将var->readMap<void>()返回的指针放到一个用_Const创建的VARP copiedVar中，再在之后通过model->parameters()[0]->input(copiedVar) 来加载。请问这种方法可行吗？

**Comment by wangzhaode** [comment]
加载权重用[loadParameters](https://mnn-docs.readthedocs.io/en/latest/cpp/Module.html#loadparameters)

**Comment by fubukishiro** [comment]
非常感谢：)
