### ISSUE TITLE
Does your optimized code of backend of ARM64 contain NEON instruction set?

### ISSUE THREAD

**Issue by peyer** [alibaba/MNN#225]
Hi, thanks for your great work! I found that your assembly code of arm64 seem to use none NEON instruction set, am I right?

**Comment by jxt1234** [comment]
The assembly code of arm64 use NEON instruction for simd compute, like that fmla v0.4s, v1.4s, v2.s[0]

**Comment by peyer** [comment]
@jxt1234 Thanks. I am not that familiar with NEON, only take looks at NCNN which use some NEON instrcution set like vld1.f3, vadd.f32 and so on. So I misread that all NEON instruction set started with v. Thanks for your reply!

**Comment by jxt1234** [comment]
vadd.f32  is the instruction of armv7a 
For armv8 you must use new instruction
