### ISSUE TITLE
ONNX int64输入转MNN后输入类型为NULL

### ISSUE THREAD

**Issue by pugnazhaotianqi** [alibaba/MNN#2251]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Windows

# Github版本:
# Github Version:
2.3.1

# 编译方式:
# Compiling Method
cmake -G "Ninja" -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_CONVERTER=ON -DCMAKE_BUILD_TYPE=Release -DMNN_WIN_RUNTIME_MT=ON ..

**Comment by wangzhaode** [comment]
是否可以提供一下ONNX模型？

**Comment by pugnazhaotianqi** [comment]
模型在公司电脑上无法上传，通过netron查看onnx模型，输入类型为int64，通过MNNConvert转换后的模型使用pythonapi 加载模型后使用getDataType()的结果为capsule object NULL at 0x000002A8436A8FC0，并且按照官方的编译方式，在build目录下没有MNNDump2Json可执行文件，目前也没有办法自行修改MNN模型的结构

**Comment by wangzhaode** [comment]
> capsule object NULL at 0x000002A8436A8FC0

这个不是NULL， 请看文档：https://mnn-docs.readthedocs.io/en/latest/pymnn/Tensor.html#getdatatype

`PyCapsule`是一种Python的数据结构
