### ISSUE TITLE
CPU后端推理使用Float指令计算int32数据的问题

### ISSUE THREAD

**Issue by summer-wing** [alibaba/MNN#2252]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux x86-64

# Github版本:
# Github Version:
Commit:
dcb080c09dc733c22784819bdbbd3397fee0cc72 [dcb080c0]
Tag: 2.4.0

说明：
注意到在[MNN:Sync] Sync Internal 2.3.0这个提交(Commit:c2476448a74dc34b41bada62fff70db4aa1aebe0 [c2476448])
中，MNN仓库已经部分修复了这个问题，但是还有一点遗留的问题，我在此反馈一下：
1）对于int和float的处理方式不一致，格式上不统一，对代码维护可能会带来影响
以CPUBinary.cpp，line 240左右为例，
float使用core->MNNSelectBinaryFunctionForFloat(type)，
修改后的int仍然使用auto func = CPUBinary::selectForInt(type);
以CPURaster.cpp, line 1118左右为例，
float 使用proc = static_cast<CPUBackend*>(backend())->functions()->MNNSelectBinaryFunctionForFloat(op->main_as_BinaryOp()->opType());
修改后的int使用：proc = CPUBinary::selectForInt(op->main_as_BinaryOp()->opType());
2）Eltwise算子也存在此问题，但未修改
CPUEltwise.cpp， line 65左右，直接使用了auto proc = core->MNNSelectBinaryFunctionForFloat(opType);
比较合理的方式还是和Raster一样，对于输入数据类型做判断，根据判断结果进行计算指令的选择。

**Comment by wangzhaode** [comment]
这里格式不统一是没问题的；int32类型计算比较简单不需要根据后端选择函数指针；float的类型在低精度(如：ARMv82)情况下会使用fp16计算，所以需要根据后端选择函数指针；

**Comment by summer-wing** [comment]
疑问：Eltwise算子不用修改吗？

2）Eltwise算子也存在此问题，但未修改
CPUEltwise.cpp， line 65左右，直接使用了auto proc = core->MNNSelectBinaryFunctionForFloat(opType);
