### ISSUE TITLE
LSTM 流式推理中间细胞状态保存问题

### ISSUE THREAD

**Issue by Asxin** [alibaba/MNN#2253]
在语音增强场景下，模型推理都是流式的，即输入一帧数据输出一帧结果。大致的代码流程如下（伪代码）：

createFromFile(MODEL_PATH);
session = createSession(netConfig);

while (1) {
    getSessionInput(session, "input");

    // 拷贝输入一帧数据

    runSession(session);

    getSessionOutput(session, "output");

    // 获取输出结果
}

模型结构是由若干层LSTM 组成，需要每帧推理都要自动保存 LSTM 细胞状态，这在 pytorch 训练过程是不用考虑的。

但是在 MNN C++ 推理时每次调用 runSession 后LSTM 的状态内容似乎没有保存。

当然，修改模型结构，将所有LSTM状态都返回模型外部进行保存，在推理前重新输入给session，相当于在外部保存这些状态是可以做到的。但是当模型结构很复杂时LSTM 的状态信息数据量很大较难维护了。

如果要实现上述流式推理，需要怎么做呢？请问当前 runSession 之后的 LSTM 细胞状态都有保存吗，上面的理解对吗？

**Comment by Asxin** [comment]
我尝试了使用 saveTensors.push_back（）保存中间的tensor，但是模型由onnx转换为mnn 后，里面没有明确的LSTM 结构了，都是由卷积和基本的算子组成。所以没有成功。流式推理结果不正确。

**Comment by wangzhaode** [comment]
> 当然，修改模型结构，将所有LSTM状态都返回模型外部进行保存，在推理前重新输入给session，相当于在外部保存这些状态是可以做到的。

建议这么做

**Comment by Asxin** [comment]
好的，已验证在外部保存LSTM状态流式运行OK；

再请教一下，当前 ARM 嵌入式平台基本都支持 NEON 指令加速， MNN 是否支持NEON呢？是否比CPU 计算推理效率会提高？
好像看到这方面的信息比较少。

**Comment by wangzhaode** [comment]
MNN支持NEON；NEON也是CPU指令的一部分，是一种SIMD指令，相比普通的标量指令是有明显的性能提升的
