### ISSUE TITLE
多模型并行

### ISSUE THREAD

**Issue by MuYu-zhi** [alibaba/MNN#2254]
想了解下，最新的MNN是否支持APP内多线程启动多个Interpreter，实现多个不同模型同时推理，多谢

**Comment by jxt1234** [comment]
一直都是支持的

**Comment by wangzhaode** [comment]
支持的

**Comment by xin486946** [comment]
> 支持的
多个模型并行推理时，线程池是共用的？怎么保障多个不同模型结果正确，线程池共用那耗时会变慢？
