### ISSUE TITLE
Android编译如何链接系统的opencl库？

### ISSUE THREAD

**Issue by songshaoze** [alibaba/MNN#2257]
#Android平台编译问题请教

Android平台  opencl
参数配置： MNN_USE_SYSTEM_LIB OFF
根据文档说明，该参数OFF时，未使用dlopen的方式获取CL的函数库，

同时查看libMNN.so和 libMNN_CL.so 也都没发现有libOpenCL.so的 shared library

请问这这个链接是怎么做的呢？

```

**Comment by wangzhaode** [comment]
当`MNN_USE_SYSTEM_LIB=OFF`，不是通过链接来处理符号依赖；而是通过`dlopen`加载cl库获取函数指针的方式来处理依赖；
