### ISSUE TITLE
Protobuf parsing failed

### ISSUE THREAD

**Issue by kitterive** [alibaba/MNN#2260]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
ubuntu20.04

# Github版本:
# Github Version:
2.4.0

同一个版本编译的转换工具和库，但加载模型的时候，提示 Protobuf parsing failed

**Comment by wangzhaode** [comment]
> 但加载模型的时候，提示 Protobuf parsing failed

请发出你加载模型的代码，或者提供模型

**Comment by kitterive** [comment]
谢谢答复
代码 已经上传到： 链接：https://pan.baidu.com/s/1Uyl_fv8AOIy3cBNwkMR_ug?pwd=mb1y 
提取码：mb1y 

解压后 ocml_engine_linux_mnn_test是测试工程，所用转换代码在里面的models目录中的yolov5s.mnn和yolov5s_fp16.mnn，我做了一个封装mnn的库，里面加载mnn模型的代码可以参照MnnLib.c中，所用的转换工具在mnn_model_convert中.

谢谢

**Comment by jxt1234** [comment]
MNN 并不使用 Protobuf 加载模型。“Protobuf parsing failed  ” 这个你需要自己检查是哪里打印的

**Comment by kitterive** [comment]
ptModelHdl->m_pInterpreter = MNN::Interpreter::createFromFile(strModelAbsolutePath.c_str());

就是这个加载模型的时候打印的

**Comment by kitterive** [comment]
这个是打印信息
Begin to load onnx model  /home/guo/docker/mydev/android_engine/ocml_engine_linux_mnn_test/bin/../models/yolov5s.mnn
Load model from /home/guo/docker/mydev/android_engine/ocml_engine_linux_mnn_test/bin/../models/yolov5s.mnn failed:Protobuf parsing failed.

我的加载代码是：
std::cout << "Begin to load mnn model  " << strModelAbsolutePath << std::endl;
        ptModelHdl->m_pInterpreter = MNN::Interpreter::createFromFile(strModelAbsolutePath.c_str());

**Comment by jxt1234** [comment]
mnn 里面没有这个打印的，你再检查一下代码

**Comment by jxt1234** [comment]
另外，不要用百度网盘，这边下载不了

**Comment by jxt1234** [comment]
另外，不要用百度网盘，这边下载不了

**Comment by kitterive** [comment]
非常感谢，确实是我代码的问题，加载模型的时候用了onnx那边的引擎了，因为我是两个引擎封装在一起的。请问，如果有大模型，怎么上传给你们能收到？
