### ISSUE TITLE
模型转换量化int8时， 出现段错误

### ISSUE THREAD

**Issue by kitterive** [alibaba/MNN#2265]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu20.04

# Github版本:
# Github Version:
2.4.0

# 编译方式:
# Compiling Method

cmake .. -DMNN_BUILD_CONVERTER=ON

转换模型出错

 ./MNNConvert -f ONNX --modelFile anime_bg.onnx --MNNModel anime_bg_int8.mnn --bizCode MNN --weightQuantBits 8
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[14:39:05] /home/guo/docker/mydev/external_lib/mnn/MNN_source/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 7
Start to Optimize the MNN Net...
段错误 (核心已转储)

模型可以提供，请问如何上传？

**Comment by kitterive** [comment]
模型在这里

https://drive.google.com/file/d/1WspkEAFFyScDbgpgdcLLY0XP8zUAWxK3/view?usp=sharing

**Comment by yyfcc17** [comment]
此问题是因为你的模型中有权重共享造成的

> --weightQuantBits 8

此选项表示转换时进行仅权值量化，运行时仍会解码为float执行

要解决此问题，请在WeightQuantAndCoding.cpp 第71行后添加：
> if (weightSize == 0) { return; }

**Comment by kitterive** [comment]
谢谢，已经测试，是该问题！为你们的响应点赞！
