### ISSUE TITLE
【需求】MNN不支持maxpooling不支持输出indices，求支持

### ISSUE THREAD

**Issue by XiaotaoChen** [alibaba/MNN#2268]
背景：
分割模型希望基于maxpool的indices，用于上采用提高精度。[模型地址](https://github.com/XiaotaoChen/sources/blob/master/mnn/hair_segmentation.op12.sim.onnx)

**Comment by wangzhaode** [comment]
这个需求目前看使用到的场景比较有限，目前还没有计划；

您可以自行修改代码实现。

**Comment by jxt1234** [comment]
2.7.2 支持
