### ISSUE TITLE
内存拷贝问题

### ISSUE THREAD

**Issue by wwkww** [alibaba/MNN#2269]
你好，请问：
 mnn的demo中目前都是getSessionInput后再从另外一个tensor中进行copyFromHostTensor操作，这会影响性能，比如我在前面的模块中已经得到了输入buffer的指针（比如char *buffer），在不拷贝的情况下怎么给inputtensor使用？是通过设置SessionMode来改变吗？具体如何操作？

**Comment by wwkww** [comment]
> 

不需要显示调用，只需要显示释放我前面模块申请的buffer就可以，比如前面malloc了char *buffer，后面free掉buffer

**Comment by wangzhaode** [comment]
> getSessionInput 得到的这个Tensor* 需要显示调用destroy()进行释放吗？

不需要

**Comment by wwkww** [comment]
> 你好，请问：
> mnn的demo中目前都是getSessionInput后再从另外一个tensor中进行copyFromHostTensor操作，这会影响性能，比如我在前面的模块中已经得到了输入buffer的指针（比如char *buffer），在不拷贝的情况下怎么给inputtensor使用？是通过设置SessionMode来改变吗？具体如何操作？

请问这个怎么做？

**Comment by wangzhaode** [comment]
> 你好，请问： mnn的demo中目前都是getSessionInput后再从另外一个tensor中进行copyFromHostTensor操作，这会影响性能，比如我在前面的模块中已经得到了输入buffer的指针（比如char *buffer），在不拷贝的情况下怎么给inputtensor使用？是通过设置SessionMode来改变吗？具体如何操作？

调用`copyFromHostTensor `是为了做一些可能必要的格式转换，如果你确定不需要这些转换也可以正确执行，那么你就直接给赋值`getSessionInput`得到的`Tensor`就可以了

**Comment by wwkww** [comment]
> > 你好，请问： mnn的demo中目前都是getSessionInput后再从另外一个tensor中进行copyFromHostTensor操作，这会影响性能，比如我在前面的模块中已经得到了输入buffer的指针（比如char *buffer），在不拷贝的情况下怎么给inputtensor使用？是通过设置SessionMode来改变吗？具体如何操作？
> 
> 调用`copyFromHostTensor `是为了做一些可能必要的格式转换，如果你确定不需要这些转换也可以正确执行，那么你就直接给赋值`getSessionInput`得到的`Tensor`就可以了

请问这个具体是怎么把char*buffer的指针给inputtensor呢？可以具体说下吗

**Comment by wangzhaode** [comment]
使用[Session_Input_User](https://mnn-docs.readthedocs.io/en/latest/cpp/Interpreter.html?highlight=Session_Input_User#sessionmode); 直接给inputTensor赋值地址即可；
```
inputTensor->buffer().host = your_ptr;
```

**Comment by wwkww** [comment]
> 使用[Session_Input_User](https://mnn-docs.readthedocs.io/en/latest/cpp/Interpreter.html?highlight=Session_Input_User#sessionmode); 直接给inputTensor赋值地址即可；
> 
> ```
> inputTensor->buffer().host = your_ptr;
> ```

好的，非常感谢，上面说的应该是cpu的情况，如果是opencl的话应该怎么操作呢？用svm和不用svm的情况

**Comment by wwkww** [comment]
> 使用[Session_Input_User](https://mnn-docs.readthedocs.io/en/latest/cpp/Interpreter.html?highlight=Session_Input_User#sessionmode); 直接给inputTensor赋值地址即可；
> 
> ```
> inputTensor->buffer().host = your_ptr;
> ```

上面说的应该是cpu的情况，请问如果是opencl的话应该怎么操作呢？用svm和不用svm的情况

**Comment by wangzhaode** [comment]
cl的你参考opencl后端的内存申请方式写一下就可以了

**Comment by jxt1234** [comment]
> 

这种情况建议用 expr + module api 运行，先调一个 MNN::Express::_Cast 把 uint8_t 转成 float ，再传给 Module onForward 即可
https://mnn-docs.readthedocs.io/en/latest/inference/module.html
