### ISSUE TITLE
MNNPythonOfflineQuant通用量化导出的模型只存在const

### ISSUE THREAD

**Issue by syxrz789** [alibaba/MNN#2271]
平台：Ubuntu 218.04

使用MNN Python版本为2.4.0， 测试脚本为 python API

因为想保留yolov5的letterbox预处理方式，选择通用模型的量化方式（MNNPythonOfflineQuant）

按照流程转换onnx时保留BN层，转换MNN时在MNNConvert工具加上 --forTraining，测试命令结果和转换结果均为success。

按要求写好calibration_dataset.py和config.yaml文件

但运行mnn_offline_quant.py后保存的文件用netron工具查看，只有一个Const的输入和Const1的输出

考虑过只是netron不能解码量化模型，但MNN进行推理时createSession正常，但runSession时报错不能运行。

有人提出类似问题
https://github.com/alibaba/MNN/issues/1788，
但没人解答。

所用的代码：
[quant.zip](https://github.com/alibaba/MNN/files/10938108/quant.zip)

**Comment by jxt1234** [comment]
不加 --forTrain 是否能量化成功?

**Comment by syxrz123** [comment]
不加 --forTrain 进行量化也会产生相同的问题 
![image](https://user-images.githubusercontent.com/84340192/224232478-bfed565e-ac65-4653-b297-ca12e37ff29a.png)

**Comment by syxrz789** [comment]
不加 --forTrain 进行量化也会产生相同的问题, 量化过程也没有报错，但就是产生了一个只有const权重文件
![image](https://user-images.githubusercontent.com/57850253/224232798-01b263e7-06f3-4c8c-a0c6-add6c04c975b.png)

**Comment by syxrz789** [comment]
加上F.lazy_eval(True)后有成功在MNN-2.4.0的版本上量化和推理，谢谢

**Comment by wangzhaode** [comment]
ok 我们下个版本修复该问题
