### ISSUE TITLE
表达式接口添加层的问题

### ISSUE THREAD

**Issue by zhenxing9968** [alibaba/MNN#2272]
# 问题描述
我想像benchmark/exprModels目录下的cpp一样 搭建自己的网络结构，其中包含LSTM或者GRU这样的layer，但是却找不到这些层
在NeuralNetWorkOp.hpp和NeuralNetWorkOp.cpp里面加一下就好了吗？
如果要是在android平台上面使用vulkan和opencl加速的话，还需要修改或者增加别的部分的代码吗？

有表达式接口添加层的文档吗？

**Comment by wangzhaode** [comment]
- 添加接口没有文档
- Vulkan/OpenCL是否支持是看具体后端是否支持这个Op；跟构图无关；
