### ISSUE TITLE
表达式接口找不到 LSTM、GRU 这些层

### ISSUE THREAD

**Issue by zhenxing9968** [alibaba/MNN#2273]
我想像benchmark/exprModels目录下的cpp一样 搭建自己的网络结构，其中包含LSTM或者GRU这样的layer，但是却找不到这些层，是不支持吗？

**Comment by jxt1234** [comment]
目前表达式接口没有支持这些层，需要自己写 OpT 去创建

**Comment by wangzhaode** [comment]
参考：https://github.com/alibaba/MNN/blob/master/express/NeuralNetWorkOp.cpp
自己加一下即可

**Comment by zhenxing9968** [comment]
@wangzhaode  在这个NeuralNetWorkOp.hpp和NeuralNetWorkOp.cpp里面添加了之后就可以了吗？然后vulkan和opencl支持不？
