### ISSUE TITLE
GPU初始化较慢的问题

### ISSUE THREAD

**Issue by wwkww** [alibaba/MNN#2281]
请问GPU创建session（createSession函数）非常慢，我试了下mobilenet，用cache的情况下大概1.5s，不用的话6s，这个时间正常吗？这1.5s具体在干什么，看起来时间也挺长

**Comment by jxt1234** [comment]
在什么设备上呢？1.5 s 估计是 GPU 创建内存和做 CPU -> GPU 权重数据拷贝，设备比较差的情况下可能耗时较多。

**Comment by wwkww** [comment]
> 在什么设备上呢？1.5 s 估计是 GPU 创建内存和做 CPU -> GPU 权重数据拷贝，设备比较差的情况下可能耗时较多。

在小米12s ultra上面测试的，这个现象正常吗？请问你们平时测试这一块的时间大概多长

**Comment by jxt1234** [comment]
不正常，这个是 cache 没生效吧

**Comment by jxt1234** [comment]
一般中高端机型，有 cache 之后启动时间应该小于 1 s

**Comment by wwkww** [comment]
> 一般中高端机型，有 cache 之后启动时间应该小于 1 s
我检查了确实有cache文件，也没有load cahce失败的打印信息，都没有问题，而且如果我不用cache的话，createSession的时间更长，要6s

**Comment by wwkww** [comment]
> 一般中高端机型，有 cache 之后启动时间应该小于 1 s

我检查了确实有cache文件，也没有load cahce失败的打印信息，都没有问题，而且如果我不用cache的话，createSession的时间更长，要6s

**Comment by bitxsw93** [comment]
可以加下时间戳，定位下初始化耗时分配情况，看看哪一块耗时较多。

**Comment by minushuang** [comment]
@jxt1234 @wwkww cache文件在哪里？我这opencl下，加载要三四十秒~   设备oppo find x3，骁龙870 八核

**Comment by bitxsw93** [comment]
@minushuang 通过setCacheFile去设置cache文件路径，可以参考tools/cpp/MNNV2Basic.cpp
