### ISSUE TITLE
mnn推理结果和onnx不一致

### ISSUE THREAD

**Issue by minushuang** [alibaba/MNN#2282]
onnx转mnn后，onnx和mnn输出结果不一致。
![image](https://user-images.githubusercontent.com/5811852/224946014-94247324-d92a-423e-b59c-1457377ddd23.png)
![image](https://user-images.githubusercontent.com/5811852/224946084-27a265bd-a811-45a8-9310-6054d990e579.png)

**Comment by jxt1234** [comment]
代码和模型发一下

**Comment by minushuang** [comment]
> 代码和模型发一下

https://drive.google.com/file/d/19_-7DguTXcrQ8RgiThsODuVuvVgDgceT/view?usp=sharing

**Comment by jxt1234** [comment]
这个 value_20x20[i * height + j * 66 + 4] 的逻辑是什么?

**Comment by jxt1234** [comment]
应该是 d = value_20x20[i * height * width + j * 66 + 4] 吧

**Comment by minushuang** [comment]
> 应该是 d = value_20x20[i * height * width + j * 66 + 4] 吧

oo.  是的，谢谢指正！！
