### ISSUE TITLE
GeometryImageOp栈变量未初始化即使用的风险

### ISSUE THREAD

**Issue by summer-wing** [alibaba/MNN#2287]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Linux x86_64

# Github版本:
Tag 2.4.0
Commit:dcb080c09dc733c22784819bdbbd3397fee0cc72 [dcb080c0]

# 问题描述：
GeometryImageOp.cpp, line 61，在栈上定义info变量时，未对成员InterpInfo::depthScale进行初始化。
```         
InterpInfo info;
info.widthScale = (float)inputs[0]->width() / (float)outputs[0]->width();
info.heightScale = (float)inputs[0]->height() / (float)outputs[0]->height();
flatbuffers::FlatBufferBuilder builder;
builder.Finish(makeInterp(builder, &info, 2, op, OpType_Interp));
```
后续未初始化即直接使用。使用的具体位置在GeometryImageOp.cpp, line 24
`intp3DB.add_depthScale(info->depthScale);`

valgrind测试发现报错"Conditional jump or move depends on uninitialised value(s)"

**Comment by wangzhaode** [comment]
感谢反馈，确实`Scale`的成员变量未初始化；
