### ISSUE TITLE
图像分割deeplabv3plus模型的输出错误

### ISSUE THREAD

**Issue by wujiexiaowugui** [alibaba/MNN#229]
使用deeplabv3plus.pb模型，最后输出的结果不正确：
获取最终输出的代码：
auto outputs = mnnNet->getSessionOutput(static_cast<const MNN::Session *>(session), "ArgMax")
其中outputs的shape应是1×512×512×1，
但是实际输出的结果shape为1×2×512×1.

MNN版本0.2.0.6

**Comment by li-qing** [comment]
测试了一下TF的deeplabv3_257_mv_gpu https://www.tensorflow.org/lite/guide/hosted_models 输出大小和模型描述一致 没有发现shape错误 可以给出pb链接么？

**Comment by JiangtianPan** [comment]
我也尝试了一个deeplabv3plus.pb转MNN，会显示LogicalAnd和Assert两个op不支持。

**Comment by jxt1234** [comment]
已经支持了
