### ISSUE TITLE
onnx模型转MNN，testFromMNN工具测试失败，能够稳定出现

### ISSUE THREAD

**Issue by guoguocode** [alibaba/MNN#2293]
# Platform:Linux  

# Github Version:2-3-1

# 编译方式:
# Compiling Method

```
cd /path/to/MNN
./schema/generate.sh
mkdir build && cd build && cmake .. && make -j8
```
[badcase.zip](https://github.com/alibaba/MNN/files/11037005/badcase.zip)

**Comment by guoguocode** [comment]
原始pytorch模型文件和导出的onnx文件在附件里面了

**Comment by jxt1234** [comment]
2.4.1 上测试过了么？命令行和日志是什么?

**Comment by jxt1234** [comment]
附件要不发我邮箱吧 jxt1234@zju.edu.cn ，下载总是失败

**Comment by jxt1234** [comment]
2.4.1 上测试了一下，是正确的。应该是已经解决过的问题。
tensor(float)
['output']
inputs:
input
onnx/
2023-03-22 15:22:34.389383 [W:onnxruntime:, execution_frame.cc:828 VerifyOutputSizes] Expected shape from model of {1,80,102} does not match actual shape of {1,80,1} for output output
outputs:
onnx/output.txt (1, 80, 1)
onnx/
hw.cpufamily: 458787763 , size = 4
The device support dot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[15:22:37] /Users/xtjiang/alicnn/GithubMNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 6
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ output, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
input
output: output
output: (1, 80, 1, )
TEST_SUCCESS
