### ISSUE TITLE
MNN是否支持cpu后端 动态batch推理

### ISSUE THREAD

**Issue by hxer7963** [alibaba/MNN#2294]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
X86/ARM CPU backend

# Github版本:
# Github Version: 

`commit dcb080c09dc733c2`

# 编译方式:
# Compiling Method

```
cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_TOOLS=ON -DMNN_BUILD_BENCHMARK=ON -DMNN_BUILD_DEMO=ON  -DMNN_BUILD_TEST=ON -DMNN_USE_THREAD_POOL=OFF
```

# 疑问
请问MNN是否支持CPU后端的动态batch推理，如pb模型的输入为 `(-1,256)`,真实推理时，其中-1表示batch维；
我应该调用哪个接口来设置batch维呢? 直接设置inputTensors的dims，然后调用 `net->resizeTensor` 和 `net->resizeSession` 就可以跑runSession得到推理结果？

另外，请问有可参考的测试样例么？这样我可以通过代码快速熟悉MNN动态batch推理的完整context。

感谢！

**Comment by jxt1234** [comment]
支持的，参考 MNN 目录下面如下示例：
1. demo/exec/pictureRecognition.cpp （基于 MNN::Interpreter）
2. demo/exec/pictureRecognition_batch.cpp （基于 MNN::Express::Module）
