### ISSUE TITLE
目前的MNN对麒麟芯片的支持？

### ISSUE THREAD

**Issue by xiaoguoer** [alibaba/MNN#2295]
#763 
按照[文档](https://www.yuque.com/mnn/cn/xfs77m)里的说明，目前是不是仍然不支持非达芬奇架构的NPU？
例如：麒麟980，970.

**Comment by jxt1234** [comment]
非达芬奇架构的 NPU 不支持，这个只有厂商软件能用

**Comment by xiaoguoer** [comment]
@jxt1234 华为似乎说HiAI支持970，MNN中不就是使用HiAI调NPU？
[官网](https://www.hisilicon.com/cn/products/Kirin/Kirin-flagship-chips/Kirin-970)“麒麟970采用了先进的TSMC 10nm工艺，在指甲大小的芯片上集成55亿晶体管，其中包含8核CPU、12核GPU、双ISP、1.2Gbps 高速LTE Cat.18 Modem以及**_创新的HiAI移动计算架构_**。麒麟970拥有极速联接、智慧算力、高清视听、长效续航等优势。”

**Comment by jxt1234** [comment]
映象中970不支持使用 HIAI 接口自己搭建网络结构

**Comment by cwang-zju** [comment]
实测Kirin 980跑不了，相对应的DDK V200现在网上已经没法下载了，DDK 100.320.xxx的在麒麟980上显示版本不对。

**Comment by xiaoguoer** [comment]
@cwang-zju 感谢！

**Comment by kkHAIKE** [comment]
> 映象中970不支持使用 HIAI 接口自己搭建网络结构

实测不行，hiai 新版上的支持列表也没有 970，是不是要找到很老的版本?
