### ISSUE TITLE
安卓arm-v8机器使用fp16推理结果异常，fp32结果正确

### ISSUE THREAD

**Issue by guoguocode** [alibaba/MNN#2296]
# 平台(如果交叉编译请再附上交叉编译目标平台):  android
NDK版本为android-ndk-r21e-linux-x86_64

# Github版本:
MNN-2.4.1

# 编译方式:
# Compiling Method

```
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
```

# 编译日志:
# Build Log:

```
>>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Version: 2.4.1
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	NNAPI: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
```
[fp16-bad.zip](https://github.com/alibaba/MNN/files/11048295/fp16-bad.zip)

**Comment by guoguocode** [comment]
原始模型和fp16模型已经上传附件了，之前2.3.1版本onnx转MNN模型使用testMNNFromOnnx.py测试失败，2.4.1版本修复了，但是使用转出来的fp16计算全是0，fp32计算正确

**Comment by jxt1234** [comment]
使用的测试数据是什么，我用随机构造的数据没有复现，fp16 （precision 设成 low）时计算是对的

**Comment by guoguocode** [comment]
我拿全是0作为输入，输入大小是1x640x102。可以直接把timeProfile.out的输出print出来测试

**Comment by jxt1234** [comment]
用 MNNV2Basic 或者 ModuleBasic 测试吧，timeProfile 那个不适合来测结果，不确定内存布局转换的配置是否正确的

**Comment by jxt1234** [comment]
[onnx.zip](https://github.com/alibaba/MNN/files/11049186/onnx.zip)

用 ./ModuleBasic.out fp16-bad/test_model-fp16.mnn onnx 0 0 0 0 2 测试 fp16 精度，结果是正确的，output/0_0 也不是0

**Comment by tzhang2014** [comment]
> [onnx.zip](https://github.com/alibaba/MNN/files/11049186/onnx.zip)
> 
> 用 ./ModuleBasic.out fp16-bad/test_model-fp16.mnn onnx 0 0 0 0 2 测试 fp16 精度，结果是正确的，output/0_0 也不是0

你这个是cpu上跑的，用gpu试试

**Comment by guoguocode** [comment]
> 

我找到原因了，我的模型输出没用做一次copy，直接拿getSessionOutput的结果获取输出，这情况在fp32下没问题，在fp16就会报错，谢谢大佬
