### ISSUE TITLE
Resize error from onnx

### ISSUE THREAD

**Issue by FrancisCaig** [alibaba/MNN#2298]
Ubuntu 20.04

MNN版本: 2.4.1, commit: eea434c02

pytorch导出的onnx模型，导出时未使用dynamic input

转换成mnn成功
`./MNNConvert -f ONNX --modelFile ../../data/mnn_rd/model.onnx --MNNModel ../../data/mnn_rd/model.mnn --bizCode biz --debug --info

The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
18:36:08] /mnt/data/hpc_lab/cgh/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 243, ]
Converted Success!`

运行出错
`./MNNV2Basic.out ../../data/mnn_rd/unet3d_new_dynamic.mnn 1 0 0
Use extra forward type: 0

Open Model ../../data/mnn_rd/model.mnn
Load Cache file error.
The device support dot:0, support fp16:0, support i8mm: 0
Acquire size = -218103808
Acquire buffer size = -218103808
in pipeline:144, memoryType:1, res:0
Session:198, firstMalloc:1, error:1
test_main, 225, cost time: 18.664001 ms
Session:264, mNeedResize:1
Resize error, can't execute MNN`

跑testMNNFromOnnx.py不通过
`python ./testMNNFromOnnx.py ../../../model.onnx DEBUG
Dir exist
Debug Mode:  True
onnx/test.onnx
tensor(float)
['153']
inputs:
images
onnx/
outputs:
onnx/153.txt (1, 64, 9, 256, 256)
onnx/

/bin/sh: 1: ./MNNConvert: not found

Test Node : Add_5 False
onnx/test.onnx
tensor(float)
['247']
inputs:
images
onnx/

outputs:
onnx/247.txt (1, 64, 9, 256, 256)
onnx/
/bin/sh: 1: ./MNNConvert: not found

Test Node : Conv_2 False
onnx/test.onnx
tensor(float)
['148']
inputs:
images
onnx/
outputs:
onnx/148.txt (1, 64, 9, 256, 256)
onnx/

/bin/sh: 1: ./MNNConvert: not found

Test Node : Relu_1 False
Error is between  Conv_0  and  Relu_1`

看了一下内存爆了是因为转出来的mnn有个node输入是 float32[1728,589824]，int溢出了，但是转的时候没有报错。

模型
https://pan.baidu.com/s/1yYe3Z7XDf43ZQdoqmSVPgQ ，提取码euu2

**Comment by jxt1234** [comment]
/bin/sh: 1: ./MNNConvert: not found

表示需要你在编译了 MNNConvert 的目录下调用这个脚本

**Comment by FrancisCaig** [comment]
在编译了 MNNConvert 的目录下调用结果如下，最终有打印"TEST_SUCCESS"，但是又有错误node的范围，中间还有Segmentation fault

`python ../tools/script/testMNNFromOnnx.py ../../unet3d.onnx DEBUG
Dir exist
Debug Mode:  True
onnx/test.onnx
tensor(float)
['153']
inputs:
images
onnx/
outputs:
onnx/153.txt (1, 64, 9, 256, 256)
onnx/
Segmentation fault (core dumped)
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[09:55:30] /home/container/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 153, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : Add_5 False
onnx/test.onnx
tensor(float)
['247']
inputs:
images
onnx/
outputs:
onnx/247.txt (1, 64, 9, 256, 256)
onnx/
Segmentation fault (core dumped)
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[09:56:47] /home/container/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 247, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : Conv_2 False
onnx/test.onnx
tensor(float)
['148']
inputs:
images
onnx/
outputs:
onnx/148.txt (1, 64, 9, 256, 256)
onnx/
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[09:58:03] /home/container/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 148, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
images
output: 148
148: (1, 64, 9, 256, 256, )
TEST_SUCCESS

Test Node : Relu_1 True
Error is between  Relu_1  and  Conv_2`


如果这种情况代表onnx转换至mnn没有问题，那运行时问题该怎么定位呢？具体是在CPUBackend.cpp里getTensorSize函数，计算tensor size时int溢出了。我这里使用的是testMNNFromOnnx.py脚本生成的mnn模型

`./MNNV2Basic.out convert_cache.mnn 1 0 0
Use extra forward type: 0

Open Model convert_cache.mnn
Load Cache file error.
The device support dot:0, support fp16:0, support i8mm: 0
Acquire buffer size = -218103808
test_main, 225, cost time: 16.629002 ms
Resize error, can't execute MNN`

**Comment by jxt1234** [comment]
验证是否正确时不要加 DEBUG

**Comment by FrancisCaig** [comment]
尝试了不加DEBUG，check input之后直接终止了

`python ../tools/script/testMNNFromOnnx.py ../../unet3d.onnx
Dir exist
onnx/test.onnx
tensor(float)
['243']
inputs:
images
onnx/
outputs:
onnx/243.txt (1, 3, 9, 256, 256)
onnx/
Segmentation fault (core dumped)
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[15:39:46] /home/container/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 243, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01`

**Comment by FrancisCaig** [comment]
尝试不加DEBUG，check完input直接终止
`python ../tools/script/testMNNFromOnnx.py ../../unet3d.onnx

Dir exist
onnx/test.onnx
tensor(float)
['243']
inputs:
images
onnx/
outputs:
onnx/243.txt (1, 3, 9, 256, 256)
onnx/
Segmentation fault (core dumped)
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[15:39:46] /home/container/MNN/tools/converter/source/onnx/onnxConverter.cpp:93: ONNX Model ir version: 7
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ 243, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01`

**Comment by jxt1234** [comment]
模型可以换个方式传么，百度网盘这里没法访问，可以用 github 或者 google  / qq 邮箱的大文件功能

**Comment by wangzhaode** [comment]
> 已经查明原因是模型size过大，导致con3d算子在运行im2col时size溢出int了， 在某一层con3d算子时，weight是[64,64,3,3,3]，input和output都是[64,9,256,256]，im2col展开后有个矩阵变为1728*589824，所得的值再乘sizeof(float)就会导致int溢出。 请问一下这种情况MNN内部现在有解决办法吗？

这个问题确实之前也遇到过，我们考虑处理一下
