### ISSUE TITLE
nmake error

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#230]
E:\zy\MNN-0.2.0.6\build>nmake

Microsoft (R) 程序维护实用工具 14.22.27905.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

*** done ***
[  0%] Built target MNN_SCHEMA
[ 90%] Built target MNN
[ 92%] Built target testModelWithDescrisbe.out
[ 93%] Built target MNNV2Basic.out
[ 94%] Built target testModel.out
[ 94%] Built target mobilenetTest.out
[ 94%] Building CXX object tools/cpp/CMakeFiles/getPerformance.out.dir/getPerformance.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
getPerformance.cpp
E:\zy\MNN-0.2.0.6\tools\cpp\getPerformance.cpp(102): error C2491: “cpuFloatMlaTest”: 不允许 dllimport 函数 的定义
NMAKE : fatal error U1077: “D:\workenv\VS\VC\Tools\MSVC\14.22.27905\bin\Hostx64\x64\cl.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\workenv\VS\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\workenv\VS\VC\Tools\MSVC\14.22.27905\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.

**Comment by jlcai5** [comment]
I also encountered the same problem, have you solved it?

**Comment by xiexuliunian** [comment]
not all ,I have just delete something about the  getPerformance.cpp in Cmakelist to make it not compile,and then it can compile success,but I'm not sure the .lib file can use later.

**Comment by li-qing** [comment]
problem confirmed. just delete `MNN_PUBLIC` before `cpuFloatMlaTest`.

fixing soon.

**Comment by xiexuliunian** [comment]
thanks.......................................

**Comment by li-qing** [comment]
fixed
