### ISSUE TITLE
zsh: segmentation fault

### ISSUE THREAD

**Issue by qazzombie** [alibaba/MNN#2301]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
Start to Convert Other Model Format To MNN Model...
[22:27:49] /Users/admin/Desktop/MNN-2.4.0/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 7
Start to Optimize the MNN Net...
zsh: segmentation fault  ./MNNConvert -f ONNX --modelFile  --MNNModel  --bizCode MNN --weightQuantBits
```

**Comment by jxt1234** [comment]
MNN 版本更到 2.4.1 试下？仍然有问题提供一下 onnx 吧

**Comment by qazzombie** [comment]
> MNN 版本更到 2.4.1 试下？仍然有问题提供一下 onnx 吧

你好，更新到2.4.1之后, --optimizePrefer 1 --weightQuantBits 8使用这样的命令得到mnn模型确实不会报错了，但是比使用--optimizePrefer 1 --fp16 量化得到的模型还大，这个是什么原因呢

**Comment by jxt1234** [comment]
有可能是有较大的 constant ，这个 fp16 能量化但 --weightQuantBits 8 不行
