### ISSUE TITLE
onnx模型使用testMNNFromOnnx.py 报错

### ISSUE THREAD

**Issue by zrpkid** [alibaba/MNN#2303]
使用mnn中的工具进行onnx模型转化测试，报如下错误：

![Snipaste_2023-03-29_09-30-35](https://user-images.githubusercontent.com/32765084/228403204-d23bd5d6-6b9f-4fb5-9c16-ef8554bfd348.png)
请问是生成的onnx模型的原因还是我使用的有问题

**Comment by jxt1234** [comment]
生成测试用的输入数据时出错了，看下你 onnx 的输入数据类型是什么，到 提示的 testMNNFromOnnx.py 行(149) 修改一下

**Comment by zrpkid** [comment]
我尝试打印了onnxruntime中nodeArg类的信息为NodeArg(name='input', type='tensor(float)', shape=[None, None, 3])
![111](https://user-images.githubusercontent.com/32765084/228455674-f72fd133-53a7-4bb7-8977-ffd06624c4d8.png)
尝试修改了各种数据类型，都不行

**Comment by jxt1234** [comment]
onnx 模型发上来看看吧
