### ISSUE TITLE
CUDA推理结果与CPU推理结果有差异

### ISSUE THREAD

**Issue by HaiLongEmb** [alibaba/MNN#2305]
硬件平台
Nvidia Drive Orin

MNN2.4发布版本
# 编译日志:
# Build Log:
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.8.10")
--
-- 3.19.0.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Success
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: aarch64
--      Version: 2.4.0
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: ON
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      NNAPI: OFF
--      CUDA: ON
--      OpenMP: OFF
--      BF16:
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /home/MNN-2.4.0/build
--      CUDA PROFILE: OFF
-- WIN_USE_ASM:
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- Found CUDA: /usr/local/cuda (found suitable version "11.4", minimum required is "7.0")
-- Autodetected CUDA architecture(s):  8.7
-- Enabling CUDA support (version: 11.4, archs: sm_87)
-- message  -D_FORCE_INLINES -Wno-deprecated-gpu-targets -w  -O3 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_72,code=sm_72 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -gencode arch=compute_86,code=sm_86 !!!!!!!!!!! /usr/local/cuda/include
-- Onnx:
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done

```
问题：
使用./MNNConvert转换模型后，MNN_FORWARD_CPU推理结果正常，但MNN_FORWARD_CUDA推理结果异常。该问题应该如何解决？

**Comment by HaiLongEmb** [comment]
对比过模型输出结果，差异很大
CPU
0.934854  0.065146  0.057808  0.942192   0.371094  0.495117  0.456055  0.485352  0.529297  0.497070  0.566406  0.533203
CUDA
0.380392  0.435294  0.427451  0.000000   0.427451  0.427451  0.419608  0.000000  0.419608  0.443137  0.372549  0.000000

并且使用-DMNN_BUILD_DEMO 中demo测试，修改成CUDA推理输出结果也是不正常的。

**Comment by jxt1234** [comment]
嵌入式上面的 cuda 芯片这边没有环境测试，可以用 backendTest.out 检查一下?

**Comment by HaiLongEmb** [comment]
nvidia@tegra-ubuntu:~/MNN-2.4.0/build_new$ ./backendTest.out mobilenetV2.mnn 2 0.15 1
Test forward type: 2
Tolerance Rate: 0.150000
Open Model mobilenetV2.mnn
The device support dot:1, support fp16:1, support i8mm: 0
Input: 48,48,3,1
precision=1 in main, 271
modeNum=1 in main, 276
stopOp.c_str()=s  in main, 281
1175: 0.323341 != 1.080402
classnet/block_01_dw/depthwise - 0 is error

重新cmake 并编译，重新转换模型试验，请问还能做哪些尝试？

**Comment by jxt1234** [comment]
把 source/backend/cuda/execution/ConvDepthWiseExecution.cu 注掉试试，

753行：// static CUDACreatorRegister<ConvDepthWiseExecutionCreator> __init(OpType_ConvolutionDepthwise);

**Comment by HaiLongEmb** [comment]
> 把 source/backend/cuda/execution/ConvDepthWiseExecution.cu 注掉试试，
> 
> 753行：// static CUDACreatorRegister __init(OpType_ConvolutionDepthwise);

738 class ConvDepthWiseExecutionCreator : public CUDABackend::Creator {
739 public:
740     virtual Execution* onCreate(const std::vector<Tensor*>& inputs, const std::vector<Tensor*>& outputs,
741                                 const MNN::Op* op, Backend* backend) const override {
742         if (inputs.size() > 1) {
743             return nullptr;
744         }
745         auto res = _makeResource(op, backend);
746         if (nullptr == res) {
747             return nullptr;
748         }
749         return new ConvDepthWiseExecution(op, backend, res);
750     }
751 };
752
753 //static CUDACreatorRegister<ConvDepthWiseExecutionCreator> __init(OpType_ConvolutionDepthwise);
754 }
755 }


./backendTest.out mobilenetV2.mnn 2 0.15 1
Test forward type: 2
Tolerance Rate: 0.150000
Open Model eye_mask_mobilenetv2_relu.mnn
The device support dot:1, support fp16:1, support i8mm: 0
Input: 48,48,3,1
precision=1 in main, 271
modeNum=1 in main, 276
stopOp.c_str()=s  in main, 281
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_01_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_02_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_03_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_04_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_05_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_06_dw/depthwise
2305: 1.577701 != 0.839149
classnet/block_01_dw/depthwise - 0 is error

还是不行，请问还有其他可以测试的方案吗？

**Comment by HaiLongEmb** [comment]
> 把 source/backend/cuda/execution/ConvDepthWiseExecution.cu 注掉试试，
> 
> 753行：// static CUDACreatorRegister __init(OpType_ConvolutionDepthwise);

738 class ConvDepthWiseExecutionCreator : public CUDABackend::Creator {
739 public:
740 virtual Execution* onCreate(const std::vector<Tensor*>& inputs, const std::vector<Tensor*>& outputs,
741 const MNN::Op* op, Backend* backend) const override {
742 if (inputs.size() > 1) {
743 return nullptr;
744 }
745 auto res = _makeResource(op, backend);
746 if (nullptr == res) {
747 return nullptr;
748 }
749 return new ConvDepthWiseExecution(op, backend, res);
750 }
751 };
752
753 //static CUDACreatorRegister __init(OpType_ConvolutionDepthwise);
754 }
755 }

./backendTest.out mobilenetV2.mnn 2 0.15 1
Test forward type: 2
Tolerance Rate: 0.150000
Open Model mobilenetV2.mnn
The device support dot:1, support fp16:1, support i8mm: 0
Input: 48,48,3,1
precision=1 in main, 271
modeNum=1 in main, 276
stopOp.c_str()=s in main, 281
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_01_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_02_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_03_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_04_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_05_dw/depthwise
CUDABackend Don't support type ConvolutionDepthwise, classnet/block_06_dw/depthwise
2305: 1.577701 != 0.839149
classnet/block_01_dw/depthwise - 0 is error

还是不行，请问还有其他可以测试的方案吗？

**Comment by bitxsw93** [comment]
打开debug宏 -DCMAKE_BUILD_TYPE=Debug ，看下有没有报错。另外可以使用MNNV2Basic.out dump每层结果，对比下CPU是哪层开始出错的。

**Comment by HWSQHL** [comment]
朋友，解决了吗，怎么解决的？我也是嵌入式设备CUDA推理结果与CPU完全不一样
