### ISSUE TITLE
What is the benefit of NC4HW4 over NHWC?

### ISSUE THREAD

**Issue by jiecaoyu** [alibaba/MNN#231]
I am curious about what is the advantage of NC4HW4 over NHWC? In what scenario (except Winograd convolution), using NC4HW4 can give better performance than NHWC?

**Comment by li-qing** [comment]
- better memory continuity for SIMD
- make it possible to optimize kernel with different parameters using a general implementation

**Comment by jiecaoyu** [comment]
Hi @li-qing , thanks for your answer! I wonder what do you mean by "better memory continuity for SIMD"? I think for conventional convolutional layers, NHWC has better memory continuity since it does not require the memory stride from the one 4x(input channels) to the next 4x(input channels).

**Comment by li-qing** [comment]
> or conventional convolutional layer

for NHWC, different implementations for different paramters (like kernel size) are needed to achieve a better performance.

**Comment by jiecaoyu** [comment]
@li-qing Thanks again for the answer!
