### ISSUE TITLE
bert dynamic  input shape  Broad cast error, dim1 = 0, dim2 = 768 Compute Shape Error for /bert/encoder/layer.0/attention/self/Add_output_0

### ISSUE THREAD

**Issue by dshwei** [alibaba/MNN#2310]
# 平台  
Broad cast error, dim1 = 0, dim2 = 768
Compute Shape Error for /bert/encoder/layer.0/attention/self/Add_output_0

# bert  动态input  shape 出现 Broad cast error, dim1 = 0, dim2 = 768

mnn resize 代码：

  inputs = interpreter.getSessionInputAll(session)

  interpreter.resizeTensor(inputs["attention_mask"], (1,128))
  interpreter.resizeTensor(inputs["token_type_ids"], (1,128))
  interpreter.resizeTensor(inputs["input_ids"], (1,128))

  interpreter.resizeSession(session)

```
The device support dot:0, support fp16:0, support i8mm: 0
2023-04-04 15:27:50.718446: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-04-04 15:27:50.718483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
./bert-pretrain-model/vocab.txt
MNN use high precision
Can't Find type=3 backend, use 0 instead
Can't Find type=3 backend, use 0 instead
Broad cast error, dim1 = 0, dim2 = 768
Compute Shape Error for /bert/encoder/layer.0/attention/self/Add_output_0
prediction result is:  news_tech
```

**Comment by jxt1234** [comment]
这个 log 估计是在 createSession 时打印的，尝试对初始 shape resizeSession 失败。在后续使用中应该不影响。

在 createSession 之前，调用 setSessionMode(Session_Resize_Defer) 可以避免打印这个信息

**Comment by jxt1234** [comment]
这个 log 估计是在 createSession 时打印的，尝试对初始 shape resizeSession 失败。在后续使用中应该不影响。

在 createSession 之前，调用 setSessionMode(Session_Resize_Defer) 可以避免打印这个信息

**Comment by wangzhaode** [comment]
`resizeSession`时没有log就可以正常执行

**Comment by LiYufengzz** [comment]
除了Broad cast error和Compute Shape Error的log之外，还有Can't run session because not resized怎么办？

**Comment by jxt1234** [comment]
> > 这个 log 估计是在 createSession 时打印的，尝试对初始 shape resizeSession 失败。在后续使用中应该不影响。
> > 在 createSession 之前，调用 setSessionMode(Session_Resize_Defer) 可以避免打印这个信息
> 
> 这个信息不影响运行结果吗

不影响

**Comment by jxt1234** [comment]
> 除了Broad cast error和Compute Shape Error的log之外，还有Can't run session because not resized怎么办？

你遇到的应该不是同一个问题，另外提个 issue 吧

**Comment by dshwei** [comment]
> 

没有找到你这个api 啊 setSessionMode(Session_Resize_Defer)

**Comment by dshwei** [comment]
> setSessionMode(Session_Resize_Defer)

![image](https://user-images.githubusercontent.com/42167236/232005724-9a2b2299-c63b-4d22-8f82-e16593c6f382.png)

**Comment by dshwei** [comment]
# 重新计算形状分配内存
    interpreter.resizeSession(session)
        # set 9 for Session_Backend_Auto, Let BackGround Tuning
    interpreter.setSessionMode(6)
    
    
设置了不生效
