### ISSUE TITLE
相同平台、相同DDK下，同一个cache文件，初始化build program次数增多是为什么？

### ISSUE THREAD

**Issue by songshaoze** [alibaba/MNN#2311]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

前提条件：同一款芯片、cache文件相同、DDK版本号一致、模型一致

问题如下：A B两个安卓pac包（都是A13的版本，不涉及GPU驱动升级）
A上生成的cache文件给B用，发现初始化时间多了4s，模型运行结果是正确的，就是初始化时间长

追了底层log，发现B机器上进行build program的次数多了很多次

如果模型没变的话，一个算法只需要build一次，为什么会平白无故多了很多次build program呢？

**Comment by xin486946** [comment]
底层opencl api加log发现，初始化时间变成是从clCreateProgramWithBinary&clBuildProgram后，又走一遍在线编译clCreateProgramWithSource&clBuildProgram(造成初始化时间从<1s 变为 >4s。前提条件(同一款芯片、cache文件相同、DDK版本号一致、模型一致)都相同只是不同安卓版本(同为A13), 为什么会出现modelcache不适配重新走在线编译呢？

**Comment by bitxsw93** [comment]
B机器生成cache。之后初始化还会多4s吗？

**Comment by jxt1234** [comment]
2.4.0 时的 bug ，2.5.0 已经修正
