### ISSUE TITLE
同一个模型 在不同显卡上  耗时差异大

### ISSUE THREAD

**Issue by jellyDL** [alibaba/MNN#2312]
# 平台
GTX1650TI
RTX2060

# Github版本:
MNN v2.3.0

相同的分割模型，都使用cuda后端，在GTX1650Ti上 推理耗时比 RTX2060上 慢5倍 （从5ms -> 24 ms)
尚在排查具体慢的网络层，按理两者都是属于图灵架构(大致资源如下图），也是同一个mnn模型，想请问还有哪些会导致mnn处理上的差异化？

<img width="697" alt="截屏2023-04-06 10 35 12" src="https://user-images.githubusercontent.com/8485570/230258092-64a48347-2da3-4111-8260-5e5020f881ef.png">

**Comment by wangzhaode** [comment]
这2个卡算力差异不小吧

**Comment by jellyDL** [comment]
> 这2个卡算力差异不小吧

相同架构，对于计算量不是很大的模型，按理不会有这么大的差异，感觉像是逻辑上做了分别处理

**Comment by jellyDL** [comment]
补充一下  我试过tensorRT  推理时间的变化差不多是 3ms -> 5ms
还发现一个现象，在GTX1650上，启动2个推理进程，两个进程耗时都会被拉慢。比如单个进程推理耗时是24ms，2个进程同时跑时，每个进程的推理耗时都会来到40ms，在RTX2060上貌似没这个问题。

**Comment by wangzhaode** [comment]
@bitxsw93

**Comment by bitxsw93** [comment]
图灵架构代码没有分别处理，两个线程变慢可能是资源不足导致各自变慢。

**Comment by jellyDL** [comment]
> 图灵架构代码没有分别处理，两个线程变慢可能是资源不足导致各自变慢。

了解，那单线程的情况，同架构耗时会差异这么大么？会根据sm的数量来选择算子么？

**Comment by bitxsw93** [comment]
目前没有根据sm数量选择算子
