### ISSUE TITLE
IOS上 CoreML+NPU运行yolov5s报错，帮忙看一下，感谢

### ISSUE THREAD

**Issue by oyw233** [alibaba/MNN#2318]
在iPhoneXS上跑yolov5s GPU没问题，NPU报错，报错信息如下

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
macos: 13.2.1
xcode: 14.2
ios: 16.3.1
mnn: 2.4.0
NPU推理报错信息：
 Error compiling model compiler error: Error reading protobuf spec. validator error: Layer 'Permute' of type 'Permute' has output rank 4 but expects rank exactly 5.
Failed to Compile and save Model.Failed to Invok the Model.

# 编译方式:
# Compiling Method
Xcode

mm模型出错节点：
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/75017181/230570076-42fc49ab-551e-4c7a-bcf4-90e81c769dce.png">

源onnx模型j结点:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/75017181/230570262-996ce5a9-05ad-40a5-9c2a-34b93e74d5e2.png">

**Comment by jxt1234** [comment]
了解了，我们先看一下

**Comment by jxt1234** [comment]
onnx 模型可以上传一下?

**Comment by oyw233** [comment]
[](url)

**Comment by oyw233** [comment]
[yolov5_Person_Hand_best_v3.onnx.zip](https://github.com/alibaba/MNN/files/11227962/yolov5_Person_Hand_best_v3.onnx.zip)

**Comment by wangzhaode** [comment]
ok

**Comment by wangzhaode** [comment]
Permute算子维度问题，已解决
