### ISSUE TITLE
npu 跑姿态检测的demo：精度失败

### ISSUE THREAD

**Issue by yangshanjun** [alibaba/MNN#2319]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
arm64-v8a

# 修改
multiPose.cpp 将 netConfig.type   设置成 MNN_FORWARD_USER_0，用hiai Npu跑，跑出来的结果不对，没有打点

# 编译方式:
andriod  build_64.sh

#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_shared \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_DEMO=ON \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_NPU:BOOL=true \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4

**Comment by jxt1234** [comment]
hiai 后端出错，后续安排排查
