### ISSUE TITLE
set input (or output) node name, when MNNConvert a tf model

### ISSUE THREAD

**Issue by LeeKuo1990** [alibaba/MNN#232]
does the converter-tool support such a usage now, or will it be supported in future?

**Comment by czy2014hust** [comment]
Why do you need this?

**Comment by LeeKuo1990** [comment]
> Why do you need this?

maybe sometimes the model is from somewhere else, we don't have the souce code, and unfortunately, some ops in the model are not supported by MNN, so .....

**Comment by key-word** [comment]
Did you solve the problem？？

**Comment by li-qing** [comment]
> > Why do you need this?
> 
> maybe sometimes the model is from somewhere else, we don't have the souce code, and unfortunately, some ops in the model are not supported by MNN, so .....

you mean you want to use only part of the model by setting input & output node name?

**Comment by LeeKuo1990** [comment]
> > > Why do you need this?
> > 
> > 
> > maybe sometimes the model is from somewhere else, we don't have the souce code, and unfortunately, some ops in the model are not supported by MNN, so .....
> 
> you mean you want to use only part of the model by setting input & output node name?

yes, and for now, i can solve that by editing the pbtxt file, but not quite clever.

**Comment by li-qing** [comment]
consider to support this feature later.
