### ISSUE TITLE
输入数据经过input_tensor.copyFrom()后发生变化

### ISSUE THREAD

**Issue by cj1820147** [alibaba/MNN#2320]
（1）我的输入数据是numpy数据类型的，
（2）于是我通过MNN.Tensor(shape, dtype, value_list, dimension)将其变为mnn.tensor的数据类型，此时数据没有发生变化。
（3）但是当我使用input_tensor.copyFrom(data)后，我的input_tensor和(2)中data里面的数据并不相同
请问有没有大佬知道这是什么原因造成的，下面是我的代码段

`IMG_Path = "./data/images/bus.jpg"
imgsz = (640, 640)

img = cv2.imread(IMG_Path)
img = cv2.resize(img, (640, 640))

im = letterbox(img, imgsz, auto=True)[0]  # padded resize
im = im.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
im = np.ascontiguousarray(im)  # contiguous
im = im.astype(np.float32)
im /= 255  # 0 - 255 to 0.0 - 1.0
if len(im.shape) == 3:
    im = im[None]  # expand for batch dim

interpreter = MNN.Interpreter(mnnModulePath)
session = interpreter.createSession()

input_tensor = interpreter.getSessionInput(session)
output_tensor = interpreter.getSessionOutput(session)

mnn_input = MNN.Tensor((1, 3, 640, 640), MNN.Halide_Type_Float, im, MNN.Tensor_DimensionType_Caffe)

input_tensor.copyFrom(mnn_input)`

**Comment by LiYufengzz** [comment]
是不是多了很多列0

**Comment by jxt1234** [comment]
可以用 mnnconvert -f MNN XXX.mnn --info 查看 MNN 文件信息，应该会显示你的输入是 NC4HW4 布局
input_tensor = interpreter.getSessionInput(session) 这个 tensor 是由模型中取出的，亦即 NC4HW4 布局，它的排列方式和 NCHW 不一样，但 mnn 内部会保证最终结果计算的正确。具体可以看 FAQ
