### ISSUE TITLE
我们的单元测试  run_test.out 能跑在npu上面吗

### ISSUE THREAD

**Issue by yangshanjun** [alibaba/MNN#2322]
我们的单元测试  run_test.out 能跑在npu上面吗

**Comment by jxt1234** [comment]
可以用 ./run_test.out op 5 去跑对应 npu 的算子单测

**Comment by yangshanjun** [comment]
跑其中一个用例，报段错误了
![image](https://user-images.githubusercontent.com/11879626/230814507-284ab7a2-9d76-4468-84b1-ae3c23a4c4f1.png)

**Comment by yangshanjun** [comment]
> 可以用 ./run_test.out op 5 去跑对应 npu 的算子单测
跑其中一个用例，报段错误了
![image](https://user-images.githubusercontent.com/11879626/230814581-ea3c1fb8-9839-4675-a698-1801a807218b.png)

**Comment by yangshanjun** [comment]
是不是因为我们run_test 用的是表达式，npu不支持表达式，所以跑不了？

**Comment by jxt1234** [comment]
一般是有些算子 npu 不支持

**Comment by jxt1234** [comment]
单元测试的时候，很多前后处理也是用的 MNN 算子，有可能这些子在 npu 上还没支持
