### ISSUE TITLE
metal推理速度比cpu慢4倍

### ISSUE THREAD

**Issue by LiYufengzz** [alibaba/MNN#2331]
机型信息：
![image](https://user-images.githubusercontent.com/26202915/231751964-1b51846a-1832-4827-bbf6-c9d4d83c02c3.png)

模型：
https://drive.google.com/file/d/1bNB0MTNJ6K8O74-UKDHEcEWVjr7hQ_s_/view?usp=share_link
使用./MNNV2Basic.out ~/Desktop/EDSR/RLFN_sim.mnn 10 0 0来测试运行时间，metal平均耗时560ms，cpu平均耗时120ms

**Comment by jxt1234** [comment]
了解了，我们先看一下

**Comment by LiYufengzz** [comment]
> 了解了，我们先看一下

请问，分析出来什么原因了吗？
