### ISSUE TITLE
Crash: Broad cast error, Compute Shape Error

### ISSUE THREAD

**Issue by sgxu** [alibaba/MNN#2336]
iMac(x64) 平台

MNN commit id: 3d75f7e2

 按照 ChatGLM-MNN 的说明文档重新走了一遍转模型流程(pytorch -> onnx -> mnn),  运行 cl_demo 时提示：
 
 Q: 用Python帮我写一段快速排序代码

A: Broad cast error, dim1 = 4, dim2 = 11
Compute Shape Error for /transformer/layers.0/attention/Add_3_output_0
Can't run session because not resized
[1]    55441 segmentation fault  ./cli_demo

**Comment by jxt1234** [comment]
1. Pytorch 导出 onnx 时是否指定了dynamic_axis
2. 回退 MNN 版本到 2.4.1 或 2.3.0 试试
3. 用 testMNNFromOnnx.py一步步检查各个 ONNX 到 MNN 的转换

**Comment by wangzhaode** [comment]
导出onnx需要对原始代码做一些修改，不然无法支持动态形状；这个并非MNN的问题；
