### ISSUE TITLE
自定义后端问题

### ISSUE THREAD

**Issue by syxrz789** [alibaba/MNN#2338]
想要在MNN框架上添加光算芯片的后端，但是官方文档说明的比较简单
能否提供MNN自定义后端的最小示例，或者在官方文档上补充一些细节

**Comment by jxt1234** [comment]
嗯，感谢提议。我们后续完善一下

**Comment by wangzhaode** [comment]
ok 下个版本更新一下文档

**Comment by syxrz789** [comment]
这边在做MNN自定义后端相关的工作，如若已经将自定义后端文档完善，能否提前给我这份自定义后端的补充文档，对我帮助很大，谢谢。415560135@qq.com
