### ISSUE TITLE
opencl 后端问题

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#234]
我看到MNN\source\backend\opencl\execution\cl\codegen\opencl_program.cc 这个文件是源码里本来就有的，这个应该是根据cl的kernel生成的吧，我修改了*.cl文件，如何生成这个opencl_program.cc呢？

**Comment by li-qing** [comment]
参考自定义算子 https://www.yuque.com/mnn/cn/customize_op#KUn9O 用脚本opencl_codegen.py来生成
