### ISSUE TITLE
使用Python Expr API进行推理时，将结果使用read()转为ndarray时出错"SystemError: <built-in method read of Var object at 0x7f6d16b52170> returned a result with an error set"

### ISSUE THREAD

**Issue by cj1820147** [alibaba/MNN#2340]
问题如下：
我使用Python Expr API用作推理，因为这种方式比Python Session API能够更容易的修改数据的data_format，便于调试。
所以我将输入输出都改成了nchw布局，但是在对结果使用var.read()时，出现了下述错误：

TypeError: call to readMap meet a error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xx/yolov5/yolov5_mnn_test_infer.py", line 75, in <module>
    # read(),读取ar数据并返回numpy数据类型
SystemError: <built-in method read of Var object at 0x7f6d16b52170> returned a result with an error set

请问可能是什么原因造成的，我的代码如下：

`    mnnModulePath = "./rknn_onnx_model/yolov5x.mnn"
    IMG_Path = "./data/images/bus.jpg"
    imgsz = (640, 640)

    img = cv2.imread(IMG_Path)
    img = cv2.resize(img, (640, 640))
    # preprocess
    im = letterbox(img, imgsz, auto=True)[0]  # padded resize
    im = im.transpose((2, 0, 1))[::-1]  # HWC to CHW, BGR to RGB
    im = np.ascontiguousarray(im)  # contiguous
    im = im.astype(np.float32)
    im /= 255  # 0 - 255 to 0.0 - 1.0
    if len(im.shape) == 3:
        im = im[None]  # expand for batch dim

    vars = F.load_as_dict(mnnModulePath)
    inputVar = vars["images"]
    print('input shape: ', inputVar.shape)

    print(type(inputVar))

    if (inputVar.data_format == F.NC4HW4):
        inputVar.reorder(F.NCHW)
    print("inputVar:", inputVar.data_format)

    outputVar = vars['output0']

    # 切换布局便于查看结果
    if (outputVar.data_format == F.NC4HW4):
        outputVar = F.convert(outputVar, F.NCHW)

    # read(),读取var数据并返回numpy数据类型
    print(outputVar.read())`

**Comment by wangzhaode** [comment]
能否提供以下模型

**Comment by Raise-me-up** [comment]
你好~ 我也遇到了这个问题，不知道后面你是怎么解决的呢？
