### ISSUE TITLE
MNN1.2 opencl生成的modelcache，初始化700ms,切换MNN2.4后modelcache不适配且会自动重新生成modelcache。另外MNN2.4新生成的modelcache在setcachefile后还是每次重新在线编译program withsource，造成每次初始化耗时变长到5s

### ISSUE THREAD

**Issue by xin486946** [alibaba/MNN#2341]
1. MNN1.2走opencl生成的modelcache，初始化700ms。切换MNN2.4后modelcache不适配，且会走自动重新生成modelcache。
2. 另外MNN2.4新生成的modelcache在setcachefile后还是每次重新在线编译program withsource，造成每次初始化耗时变长到5s

**Comment by wangzhaode** [comment]
> 想问一下哥哥，2.4相较2.3有cpu推理性能和内存占用的优化吗？

看release note

**Comment by bitxsw93** [comment]
> 1. MNN1.2走opencl生成的modelcache，初始化700ms。切换MNN2.4后modelcache不适配，且会走自动重新生成modelcache。
> 2. 另外MNN2.4新生成的modelcache在setcachefile后还是每次重新在线编译program withsource，造成每次初始化耗时变长到5s

是Windows上么？

**Comment by jxt1234** [comment]
关于 2 ，2.5.0 更新后修改了，可以验证一下
