### ISSUE TITLE
c 语言调用mnn 库

### ISSUE THREAD

**Issue by chyohoo** [alibaba/MNN#2342]
请问mnn 支持c 吗

**Comment by wangzhaode** [comment]
> Let me tell you: 不行。 我在仓库里翻了个遍，结果并没找到有C api的东西。 而C语言是没法直接调用C++类成员函数的，得包装一下做成C api。 我现在是自己写C api，然后和源码一起编译，并导出C函数。 类似这样：
> 
> ```c
> extern "C" void* mnn_create_interpreter_from_file(const char* model_path) {
>     auto interpreter      = MNN::Interpreter::createFromFile(model_path);
>     return (void *)interpreter;
> }
> 
> extern "C" int32_t mnn_run_session_with_cb(void* interpreter_ptr, void* session_ptr, void* ctx, uint8_t (*after_fn)(void* ctx), uint8_t sync) {
>     auto interpreter     = (MNN::Interpreter *)interpreter_ptr;
>     auto session = (MNN::Session *)session_ptr;
>     MNN::TensorCallBack before_cb = [&](const std::vector<MNN::Tensor *> &ntensors, const std::string &opName) {
>         return true;
>     };
>     MNN::TensorCallBack after_cb = [&](const std::vector<MNN::Tensor *> &ntensors, const std::string &opName) {
>         return after_fn(ctx)==1;
>     };
>     return interpreter->runSessionWithCallBack(session, before_cb, after_cb, sync==1);
> }
> ```

API的数据结构有部分C++依赖，如果使用C调用可以自行做一下封装，类似这样的封装就可以；

**Comment by chyohoo** [comment]
> Let me tell you: 不行。 我在仓库里翻了个遍，结果并没找到有C api的东西。 而C语言是没法直接调用C++类成员函数的，得包装一下做成C api。 我现在是自己写C api，然后和源码一起编译，并导出C函数。 类似这样：
> 
> ```c
> extern "C" void* mnn_create_interpreter_from_file(const char* model_path) {
>     auto interpreter      = MNN::Interpreter::createFromFile(model_path);
>     return (void *)interpreter;
> }
> 
> extern "C" int32_t mnn_run_session_with_cb(void* interpreter_ptr, void* session_ptr, void* ctx, uint8_t (*after_fn)(void* ctx), uint8_t sync) {
>     auto interpreter     = (MNN::Interpreter *)interpreter_ptr;
>     auto session = (MNN::Session *)session_ptr;
>     MNN::TensorCallBack before_cb = [&](const std::vector<MNN::Tensor *> &ntensors, const std::string &opName) {
>         return true;
>     };
>     MNN::TensorCallBack after_cb = [&](const std::vector<MNN::Tensor *> &ntensors, const std::string &opName) {
>         return after_fn(ctx)==1;
>     };
>     return interpreter->runSessionWithCallBack(session, before_cb, after_cb, sync==1);
> }
> ```

hello, 是不是所有在mnn namespace 下的调用函数都要用c api 封装？
