### ISSUE TITLE
windows上多gpu，opencl 选择设备

### ISSUE THREAD

**Issue by latermarch** [alibaba/MNN#2343]
- 请教个问题，对于windows上多gpu，跑opencl，有对应的接口传入device id，来选择使用哪个gpu吗？

**Comment by latermarch** [comment]
另外，mnn内部的opencl的设备选取策略是什么，针对多卡，是随机选一个吗？

**Comment by bitxsw93** [comment]
目前是选择第一个卡。后续我们加上接口让用户可选。
