### ISSUE TITLE
cpu跑yolov5， int8 fp16 fp32 推理时间均是2400ms左右，未见量化后推理速度变化。

### ISSUE THREAD

**Issue by sunbin1993** [alibaba/MNN#2344]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by superbattery** [comment]
量化过的模型本来就没有性能加成的保证。实际上量化后的模型只是模式变小了，推理时还是会把数据类型转换会f32，所以不会变快。

**Comment by jxt1234** [comment]
MNNConvert 里面只会量化weight，不会把featuremap量化以提升性能，量化featuremap 的参考
https://mnn-docs.readthedocs.io/en/latest/tools/quant.html

**Comment by wangzhaode** [comment]
- 权值量化不会加速；运行时fp16需要把precision设置为low; int8量化需要使用量化工具；
- fp16和int8是否有加速效果还取决于硬件是否有指令支持，具体参考：https://mnn-docs.readthedocs.io/en/latest/faq.html#id16
