### ISSUE TITLE
mnn int8量化是否支持embedding相关算子

### ISSUE THREAD

**Issue by jylink** [alibaba/MNN#2345]
我完成了tinybert模型的torch->onnx->mnn的转换和用MNNPythonOfflineQuant进行量化，但量化后模型大小仅减少了约1MB

该torch模型的word embedding占了90%参数量，推测embedding没有被量化，请问mnn int8量化是否支持embedding相关算子？

**Comment by jxt1234** [comment]
目前还未支持，后续会考虑增加（这个主要是支持常量量化）

**Comment by wangzhaode** [comment]
这个目前量化工具不支持，你可以在模型转换时使用权值量化
