### ISSUE TITLE
testMNNFromTf.py TESS pb error

### ISSUE THREAD

**Issue by JaosonMa** [alibaba/MNN#2346]
参考github：https://github.com/RRanddom/tf_doc_localisation
问题描述：
使用自己的数据重新训练模型，然后用下面代码导出.pb文件
`with tf.Session(graph=tf.Graph()) as sess:
    inputImg = tf.placeholder(dtype=tf.float32,shape=(1,800,600,3),name=input_name)

    #saver = tf.train.import_meta_graph(input_checkpoint + '.meta', input_map={'IteratorGetNext:0': inputImg},clear_devices=True)
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', input_map={'sub:0': inputImg},clear_devices=True)
    saver.restore(sess, input_checkpoint)
    graph = tf.get_default_graph() #获得默认的图
    graph_def = graph.as_graph_def()
    
    

    for op in sess.graph.get_operations():
        print(op.name, op.values())

    # print
    #tf.import_graph_def(graph_def,input_map={"IteratorGetNext: 0": inputImg})
    #print(tf.get_default_graph( ).as_graph_def() == graph_def)
    
    # outputNodes = outputNodeNames.split("","")
    output_graph_def = tf.graph_util.convert_variables_to_constants(sess,graph_def,outputNodeNames)
    # Finally we serialize and dump the output graph to the filesystem
    with tf.gfile.GFile(graph_def_file,"wb" ) as f:
        f.write(output_graph_def.SerializeToString())
    print("_______________________end_____________________")
`
然后使用
`python ../tools/script/testMNNFromTf.py ./qqm_frozen_model_paperas_kpts_pred.pb` 测试一致性 

结果如下：
`inputs:
input:0
tf/
2023-04-22 13:59:15.222041: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2023-04-22 13:59:15.262116: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499815000 Hz
2023-04-22 13:59:15.274215: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5633e8196260 executing computations on platform Host. Devices:
2023-04-22 13:59:15.274295: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
outputs:
tf/
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ keypoints_pred, ]
Converted Success!
Check convert result by tf, thredhold is 0.01
input
output: keypoints_pred
keypoints_pred: (1, 4, 2, )
TESTERROR keypoints_pred value error : absMaxV:0.906205 - DiffMax 0.471082
Error for output keypoints_pred
Save mnn result to  .error director`

**Comment by jxt1234** [comment]
TF PB 发上来看看?

**Comment by wangzhaode** [comment]
是不是tf导出后`is_training=true`的问题

**Comment by JaosonMa** [comment]
> 是不是tf导出后`is_training=true`的问题

我该在尝试，怎么搞出来一个is_training=false的pb。有结果后我在更新问题。
