### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by alexliyang** [alibaba/MNN#2347]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ARMV8

# Github版本: 2.4.0
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

![image](https://user-images.githubusercontent.com/31059043/233823906-8482c18f-81ba-4cf0-8361-b1cb60e6e119.png)

使用MNN作为推理工具，总是提示有内存泄漏，使用perfetto 查找泄漏点，总是提供显示在session 的resize这里有泄漏。调用的方式如下：
  detectorInterpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(modelPath.c_str()));
    MNN::ScheduleConfig schedule_config;
    schedule_config.type = MNN_FORWARD_CPU;
    schedule_config.numThread = 1;
    MNN::BackendConfig backend_config;
    backend_config.memory = MNN::BackendConfig::Memory_Normal;
    backend_config.power = MNN::BackendConfig::Power_Normal;
    backend_config.precision = MNN::BackendConfig::Precision_Low; 
    schedule_config.backendConfig = &backend_config;
    mnnSess = detectorInterpreter->createSession(schedule_config);
    Tensor *inputTensor = detectorInterpreter->getSessionInput(mnnSess, nullptr);

**Comment by jxt1234** [comment]
detectorInterpreter 没有释放吧

**Comment by wangzhaode** [comment]
看起来是 detectorInterpreter 没有释放；内存泄露问题建议用valgrind检查一下

**Comment by alexliyang** [comment]
上面是使用的一个举例，释放流程也有的，类似如下：

    if (detectorInterpreter != nullptr) {

        if (mnnSess != nullptr) {
            detectorInterpreter->releaseModel();
            detectorInterpreter->releaseSession(this->mnnSess);
	
            mnnSess = nullptr;
        }
	
        detectorInterpreter = nullptr;
    }

这样释放是否能完整释放？ 现在看似乎总是指向创建的时候的session：resize 这个地方。
