### ISSUE TITLE
ARM V8 CPU占用过高

### ISSUE THREAD

**Issue by 2495165664** [alibaba/MNN#2351]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
v2.0.0

# 编译方式:
# Compiling Method
cmake .. -DCMAKE_SYSTEM_NAME=linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=$TPATH/aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=$TPATH/aarch64-linux-gnu-g++

# 问题描述
相同的测试源代码，linux_x86-64设置 numThread = 1时在加载模型之后休眠，CPU是占用0，在armv8上CPU占用在70%左右，且修改numThread参数没有变化

**Comment by jxt1234** [comment]
power 设成 normal 了么?

**Comment by 2495165664** [comment]
改过之后armv8的确不会占用cpu了， 这是什么原因呢？ x86和arm架构不同导致的吗
