### ISSUE TITLE
python api 调用mnn 动态输入 input_tensor 初始化为空， copyFrom一直失败

### ISSUE THREAD

**Issue by zr-icu** [alibaba/MNN#2352]
模型输入为 [1, 3, 32, -1] 发现初始化之后的 input_tensor 一直为 array([])，根据例子构建完 tmp_input， 在input_tensor.copyFrom(tmp_input) 这一步一直显示 False，请问这里应该怎么正确传入？ 感谢大佬

**Comment by zr-icu** [comment]
self.session = self.interpreter.createSession()

**Comment by zr-icu** [comment]
class test():
def __init__(self):
    self.session = self.interpreter.createSession()
    self.input_tensor_mnn = self.interpreter.getSessionInput(self.session) # 1, 3, 32, -1 
def __call__(images):
    images = images.astype(np.float32)
    tmp_batch, tmp_c, tmp_h, tmp_w = images.shape # 1, 3, 32, 320
    self.interpreter.resizeTensor(self.input_tensor_mnn, (tmp_batch, tmp_c, tmp_h, tmp_w)) 
    tmp_input = MNN.Tensor((tmp_batch, tmp_c, tmp_h, tmp_w), MNN.Halide_Type_Float, \
                                       images, MNN.Tensor_DimensionType_Caffe)
    self.input_tensor_mnn.copyFrom(tmp_input) # 输出为False

**Comment by jxt1234** [comment]
要加上 self.interpreter.resizeSession

**Comment by jxt1234** [comment]
resizeTensor -> resizeSession ，然后再 copyFrom

**Comment by zr-icu** [comment]
您好 程铖已经收到您的邮件

**Comment by zr-icu** [comment]
您好 程铖已经收到您的邮件
