### ISSUE TITLE
转换TFLITE模型不支持

### ISSUE THREAD

**Issue by MaXueGao** [alibaba/MNN#2354]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)  SMP Fri Jan 27 02:56:13 UTC 2023

执行：./MNNConvert -f TFLITE --modelFile pose_detection.tflite --MNNModel pose_detection.mnn --bizCode biz
输出：
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[10:46:22] /root/MNN-master/SRC/tools/converter/source/tflite/liteConverter.cpp:252: Check failed: creator ==> NOT_SUPPORTED_OP: [ DENSIFY ]
[ERROR] Convert error, please check your file format.

模型：
[pose_detection.zip](https://github.com/alibaba/MNN/files/11339173/pose_detection.zip)

**Comment by wangzhaode** [comment]
算子不支持：NOT_SUPPORTED_OP: [ DENSIFY ]

**Comment by MaXueGao** [comment]
1.是否有支持计划？
2.尝试先转ONNX也是失败的。因此我需要怎么处理？（初学者）
