### ISSUE TITLE
转换Tensorflow模型出错 curNode->inEdges.size() == 1 ==> Identity's input node num. != 1

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#236]
转换一个Tensorflow的PB模型，网络input之后加了一个
tf.image.resize_image_with_pad(self.input, 256, 256)
resize输入的图像。转换就报这个错误了。
是不支持这个OP还是？
Check failed: curNode->inEdges.size() == 1 ==> Identity's input node num. != 1 [ Net/resize_image_with_pad/control_dependency ]

**Comment by czy2014hust** [comment]
control_dependency

**Comment by ChisenZhang** [comment]
> control_dependency
这个op不支持是吗？  有替代的方法吗？

**Comment by czy2014hust** [comment]
导出模型的问题，不应该有control_dependency

**Comment by ChisenZhang** [comment]
> 导出模型的问题，不应该有control_dependency

这样导出模型应该没错误吧，不知道为啥会出现 control_dependency这个东西
`output_node_names = "Net/probs,Net/reg"
    net = mobileNet.MobileNetV2(num_classes=2, training=False, batch_size=1)
    net.blazeModel(learning_rate=1e-3, decay_step=50)
    saver = tf.train.Saver()
    with tf.Session(config=config) as sess:
        saver.restore(sess, tf.train.latest_checkpoint(input_checkpoint))
        output_graph_def = graph_util.convert_variables_to_constants(
            sess=sess,
            input_graph_def=sess.graph_def,
            output_node_names=output_node_names.split(",")) 

        with tf.gfile.GFile(output_graph, "wb") as f:
            f.write(output_graph_def.SerializeToString())
        print("%d ops in the final graph." % len(output_graph_def.node))
`
