### ISSUE TITLE
2.0.0以上版本模型转换出错

### ISSUE THREAD

**Issue by m00nLi** [alibaba/MNN#2360]
# 环境
- OS: Ubuntu 22.04
- python: 3.9.16
- onnx:   0.12.0
- onnx-simplifier:   0.4.17
- onnxruntime:  1.14.1
- paddle2onnx:  1.0.6
- paddlepaddle: 2.4.2
- paddledet: 2.5.0
- mnn: 2.0.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0（pip安装）

# 模型
- 百度网盘 [PP-YOLOE_Plus_s](https://pan.baidu.com/s/1rfiPLs1375iuBOiRNZ4rzw?pwd=yolo) 

# 现象
将从paddledetection下载的ppyoloe-plus-s模型通过百度官方的脚本转换为onnx格式模型后，得到ppyoloe_plus_crn_s_80e_coco_fix.onnx，经测试：
- 只有mnn-2.0.0版本可以正确转换；
- 大于2.0.0版本的转换错误，得到的模型会有非常多的链接，用Netron打开可以观察到（打开速度能感觉到明显变慢），服务器上能推理，但移动端不能用，读取失败；
- 用onnx-simplifier简化后（merge bn、constant folding），用各个版本的mnn转换都会出错，链接非常多；
- 将onnx版本升级为0.13.1后，mnn-2.0.0也不能正确转换

**Comment by jxt1234** [comment]
1. 应该是移动端上 mnn 版本比服务器上低，如果移动端上不能升级 mnn 版本，保证服务器上的版本与移动端一致
2. 模型用别的方式，google 云盘、github 大文件等方式发送吧，百度网盘这里不能访问

**Comment by m00nLi** [comment]
mnn-2.0.0正常转换:
![正常转换](https://user-images.githubusercontent.com/102453574/236989084-ca00e995-ee5b-4f27-b658-f3a09c7f2226.jpg)
mnn-2.0.0以上版本
![太多连接](https://user-images.githubusercontent.com/102453574/236988742-1caf65f6-39ee-411f-8391-cabc107d16dd.jpg)
移动端的mnn各个版本都尝试过了, 读取模型失败.

**Comment by m00nLi** [comment]
gitee可以吧？[pp-yoloe-plus-s.onnx](https://gitee.com/registerlogin/assets/blob/master/models/pp_yoloe_plus/ppyoloe_plus_crn_s_80e_coco_fix.onnx)

**Comment by jxt1234** [comment]
测试了没问题

**Comment by jxt1234** [comment]
netron 出现的连线是因为做了同类算子合并，一些常量被合成同一个算子

**Comment by jxt1234** [comment]
android 上跑了下也没问题，请检查自己的使用代码和端上 MNN 编译时的版本
