### ISSUE TITLE
Conv1x1 still using packed instead of NC4HW4

### ISSUE THREAD

**Issue by jackychen0131** [alibaba/MNN#2361]
Hi, I'm tracing the inference code for ARM 32bit CPU that using SIMD, and I found that for a convolution 1x1 strassen inference flow, the first operation is to reorder the data from NC4HW4 to packed, so I'm wondering that why it can't just start with NC4HW4 instead of transfer to packed data?

**Comment by jxt1234** [comment]
1. Not all Ops use NC4HW4 format.
2. The user input can be set as NCHW if needed. (add --keepInputFormat) , otherwise will set as NC4HW4 if link with NC4HW4 Ops.
