### ISSUE TITLE
添加gru之后 pb->mnn or onnx->mnn 都会报错

### ISSUE THREAD

**Issue by GongYuxiu** [alibaba/MNN#2362]
# Platform:  
Ubuntu 16.04.7 LTS

# Github Version:
2.7.4

pb->mnn：
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Segmentation fault (core dumped)

onnx->mnn:
The device support dot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[09:55:57] /home/gyx/mnn/MNN/tools/converter/source/onnx/onnxConverter.cpp:40: ONNX Model ir version: 7
Start to Optimize the MNN Net...
86 op name is empty or dup, set to Const86
98 op name is empty or dup, set to Const98
305 op name is empty or dup, set to Const305
311 op name is empty or dup, set to Const311
578 op name is empty or dup, set to Unsqueeze578
589 op name is empty or dup, set to BinaryOp589
791 op name is empty or dup, set to BinaryOp791
815 op name is empty or dup, set to BinaryOp815
992 op name is empty or dup, set to Const992
1022 op name is empty or dup, set to Unsqueeze1022
1024 op name is empty or dup, set to BinaryOp1024
1060 op name is empty or dup, set to BinaryOp1060
1833 op name is empty or dup, set to Rank1833
1896 op name is empty or dup, set to Unsqueeze1896
2003 op name is empty or dup, set to BinaryOp2003
2134 op name is empty or dup, set to Unsqueeze2134
2145 op name is empty or dup, set to BinaryOp2145
2212 op name is empty or dup, set to Unsqueeze2212
2524 op name is empty or dup, set to BinaryOp2524
2549 op name is empty or dup, set to Const2549
2553 op name is empty or dup, set to BinaryOp2553
2555 op name is empty or dup, set to Unsqueeze2555
2588 op name is empty or dup, set to BinaryOp2588
2679 op name is empty or dup, set to Unsqueeze2679
2751 op name is empty or dup, set to Unsqueeze2751
2762 op name is empty or dup, set to BinaryOp2762
2785 op name is empty or dup, set to BinaryOp2785
[09:55:57] /home/gyx/mnn/MNN/tools/converter/source/common/writeFb.cpp:91: These Op Not Support: ONNX::TensorListReserve | ONNX::TensorListSetItem 
Converted Failed!

**Comment by jxt1234** [comment]
Tensorflow 版本是？之前的版本是用 TensorArray 而不是 TensorList 的，可能版本更新后换了算子。

**Comment by GongYuxiu** [comment]
tensorflow版本是2.4.0

**Comment by GongYuxiu** [comment]
需要tensorflow是什么版本的呢？这个问题目前可以解决吗？
