### ISSUE TITLE
mnn模型加密

### ISSUE THREAD

**Issue by wojiaoyanmin** [alibaba/MNN#2363]
在给mnn做模型加密时，文档中有如下方法：

MNN模型如何加密[](https://mnn-docs.readthedocs.io/en/latest/faq.html?highlight=%E5%8A%A0%E5%AF%86#id18)
加密与破解是攻防的较量，端侧加密很难做到绝对安全。 可以通过构造独有的模型格式来增加反向的难度，按照以下步骤操作可以得到独特的模型格式：

针对schema/default/*.fbs下的文件，对参数顺序，枚举类顺序进行重新排序；比如：可以重新调整MNN.fbs中OpType的顺序；重新调整CaffeOp.fbs中Convolution2DCommon成员变量的顺序；

执行schema/generate.sh重新生成flatbuffers头文件；

重新编译MNN库文件， Convert等所有工具；

使用新的工具重新转换模型；

在端侧使用新模型和新的MNN库文件进行部署；

使用schema/generate.sh时出现
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30145.0
-- The CXX compiler identification is MSVC 19.29.30145.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/vsstudio/install/install/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/vsstudio/install/install/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for _strtof_l
-- Looking for _strtof_l - found
fatal: not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: H:/humanseg/beauty_seg/MNN-master/3rd_party/flatbuffers/tmp
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

MSBUILD : error MSB1001: 未知开关。
开关:-j4

若要显示开关的语法，请键入“MSBuild -help”
*** cleaning up ***
*** generating fbs under default ***
xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
*** done ***

请问这个问题如何解决？

**Comment by jxt1234** [comment]
windows 上应该是 powershell generate.ps1
