### ISSUE TITLE
mobilenetv2分类模型8bit量化的两个问题

### ISSUE THREAD

**Issue by yizhaoyanbo** [alibaba/MNN#237]
mobilenetv2训练的分类模型，量化(KL + MAX_ABS，校正图片976张)后遇到的两个问题：
1. 8bit量化后前向推导耗时是原32bit模型的5倍（使用MNNV2Basic.out工具测量）
2. 使用testQuanModel.out查看量化后模型与原模型匹配度 top1:82.68%  top5: 98.56%。但是实际跑测试集的时候，8bit模型的准确率比没有量化的原模型低了将近40个点，查看预处理操作和json文件是一致的。
困惑，求解答。
测试环境mac mini 3 GHz Intel Core i5,  8 GB 2667 MHz DDR4,  mnn库cpu版

**Comment by czy2014hust** [comment]
1. MNN是针对端上设备的推理引擎，所以主要优化ARM平台，原始float在x86上有些优化，int8的在x86没有优化
2. 检查下预处理，保持和原始训练模型一致的预处理，(检查下crop还是resize，另外均值和方差)

**Comment by yizhaoyanbo** [comment]
@czy2014hust 请问下不同模型量化时校正图片有特殊要求吗，是随便选取的较正图片还是要与模型的测试集对应。
比如我分类是100个类别，我是从每个类别中抽10张出来，共计1000张校正图片，这样做对不。如果是这样的话是不是针对每个分类模型都要组织对应的校正图片。

**Comment by czy2014hust** [comment]
这样来说是最好的。

**Comment by yizhaoyanbo** [comment]
预处理确实是一样的：
代码中的预处理：
![image](https://user-images.githubusercontent.com/26928415/63094131-1f268e00-bf9a-11e9-8903-c72571473cd6.png)

json中的预处理
![image](https://user-images.githubusercontent.com/26928415/63094175-38c7d580-bf9a-11e9-864f-e0361e1ac790.png)

32bit和8bit在代码中用的都是resize。
奇怪的是预测得到的类别confidence top5 top10很多置信度都是一样的：
![image](https://user-images.githubusercontent.com/26928415/63094432-f6eb5f00-bf9a-11e9-9748-acb4454d23c1.png)

**Comment by jxt1234** [comment]
确定 json 配置的 image 路径对么，运行 ./quantized.out 时会打印有图片数

**Comment by yizhaoyanbo** [comment]
@jxt1234 是的，图像路径是对的。我代码中用的是opencv读的图像bgr格式，预处理转为rgb，给到session input

**Comment by jxt1234** [comment]
按图像数减到 10 - 20 张，用 ADMM  量化特征试一下吧，另外模型方便发送测试一下么？

https://www.yuque.com/mnn/cn/tool_quantize
json 中配置：
feature_quantize_method: ADMM
weight_quantize_method: ADMM

**Comment by yizhaoyanbo** [comment]
@jxt1234 
我按照上面的json配置试了下ADMM，top1: 0.8%  top5: 3.6%.
我把mnn32bit和8bit_kl以及8bit_admm放在附件了，谢谢。
[mobilenetv2_classify.zip](https://github.com/alibaba/MNN/files/3507797/mobilenetv2_classify.zip)

**Comment by firstadam** [comment]
@jxt1234 楼主，你的问题最终解决了吗？我跟你遇到相同的问题
