### ISSUE TITLE
关于动态输入的输入维度设置

### ISSUE THREAD

**Issue by yjhdhr** [alibaba/MNN#2370]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86 ubuntu18

# Github版本:
# Github Version:
commit d7d1efe03ba616de9fcdd8eeb9d8ce5c2d788349 (HEAD -> master, tag: 2.5.0, origin/master, origin/HEAD)

# CMD:
# cmd Log:

```
MNN/build$ ./GetMNNInfo text.mnn 
The device support i8sdot:0, support fp16:0, support i8mm: 0
Model default dimensionFormat is NCHW
Model Inputs:
[ input_ids ]: dimensionFormat: NCHW, size: [ 1,-1 ], type is int32
Model Outputs:
[ last_hidden_state ]
[ pooler_output ]
![a_she](https://github.com/alibaba/MNN/assets/53865451/8049a65d-72d8-4601-bd4d-0326f40244e1)

```
请问动态输入的模型，输入只有2维，在用C++部署时，如何设置输入的维度呢？
虽然我看到用resizeTensor和resizeSession可以设定输入的size，但是我不清楚这个2维具体如何设置size。。输入一定是要设定为NCHW四个维度吗？比如std::vector<int> dims{1, 1, 1, 100}; //NCHW
还是直接 std::vector<int> dims{1, 100}; 就可以啦？

**Comment by jxt1234** [comment]
std::vector dims{1, 100}; 就可以
