### ISSUE TITLE
在Mac下开启Metal加速的方式

### ISSUE THREAD

**Issue by xp19870106** [alibaba/MNN#2373]
系统：MacOS M2 Chip  

版本：mnn_2.5.0_macos_x64_arm82_cpu_opencl_metal

在接入https://github.com/DefTruth/lite.ai.toolkit 项目的时候希望将MNN的Metal加速开启

`void MNNRobustVideoMatting::initialize_context()
{
  if (variant_type == VARIANT::MOBILENETV3)
  {
    if (input_width == 1920 && input_height == 1080)
    {
      mnn_interpreter->resizeTensor(r1i_tensor, {1, 16, 135, 240});
      mnn_interpreter->resizeTensor(r2i_tensor, {1, 20, 68, 120});
      mnn_interpreter->resizeTensor(r3i_tensor, {1, 40, 34, 60});
      mnn_interpreter->resizeTensor(r4i_tensor, {1, 64, 17, 30});
      r1i_size = 1 * 16 * 135 * 240;
      r2i_size = 1 * 20 * 68 * 120;
      r3i_size = 1 * 40 * 34 * 60;
      r4i_size = 1 * 64 * 17 * 30;
    } // hxw 480x640 480x480 640x480
    else
    {
      mnn_interpreter->resizeTensor(r1i_tensor, {1, 16, input_height / 2, input_width / 2});
      mnn_interpreter->resizeTensor(r2i_tensor, {1, 20, input_height / 4, input_width / 4});
      mnn_interpreter->resizeTensor(r3i_tensor, {1, 40, input_height / 8, input_width / 8});
      mnn_interpreter->resizeTensor(r4i_tensor, {1, 64, input_height / 16, input_width / 16});
      r1i_size = 1 * 16 * (input_height / 2) * (input_width / 2);
      r2i_size = 1 * 20 * (input_height / 4) * (input_width / 4);
      r3i_size = 1 * 40 * (input_height / 8) * (input_width / 8);
      r4i_size = 1 * 64 * (input_height / 16) * (input_width / 16);
    }
  }// RESNET50
  else
  {
    if (input_width == 1920 && input_height == 1080)
    {
      mnn_interpreter->resizeTensor(r1i_tensor, {1, 16, 135, 240});
      mnn_interpreter->resizeTensor(r2i_tensor, {1, 32, 68, 120});
      mnn_interpreter->resizeTensor(r3i_tensor, {1, 64, 34, 60});
      mnn_interpreter->resizeTensor(r4i_tensor, {1, 128, 17, 30});
      r1i_size = 1 * 16 * 135 * 240;
      r2i_size = 1 * 32 * 68 * 120;
      r3i_size = 1 * 64 * 34 * 60;
      r4i_size = 1 * 128 * 17 * 30;
    } // hxw 480x640 480x480 640x480
    else
    {
      mnn_interpreter->resizeTensor(r1i_tensor, {1, 16, input_height / 2, input_width / 2});
      mnn_interpreter->resizeTensor(r2i_tensor, {1, 32, input_height / 4, input_width / 4});
      mnn_interpreter->resizeTensor(r3i_tensor, {1, 64, input_height / 8, input_width / 8});
      mnn_interpreter->resizeTensor(r4i_tensor, {1, 128, input_height / 16, input_width / 16});
      r1i_size = 1 * 16 * (input_height / 2) * (input_width / 2);
      r2i_size = 1 * 32 * (input_height / 4) * (input_width / 4);
      r3i_size = 1 * 64 * (input_height / 8) * (input_width / 8);
      r4i_size = 1 * 128 * (input_height / 16) * (input_width / 16);
    }
  }
  // resize session
  mnn_interpreter->resizeSession(mnn_session);
  // init 0.
  std::fill_n(r1i_tensor->host<float>(), r1i_size, 0.f);
  std::fill_n(r2i_tensor->host<float>(), r2i_size, 0.f);
  std::fill_n(r3i_tensor->host<float>(), r3i_size, 0.f);
  std::fill_n(r4i_tensor->host<float>(), r4i_size, 0.f);

  context_is_initialized = true;
}
`

std::fill_n(r1i_tensor->host<float>(), r1i_size, 0.f);)的时候会报错，我知道在GPU加速下是不使用tensor的host的，那么这段代码应该如何修改呢？如果直接注释掉fill_n的四行代码，那么背景替换的效果非常差，请问我应该如何做呢？谢谢！

**Comment by jxt1234** [comment]
1. 新特性下的推荐做法 : ptr = tensor->map(Tensor::MAP_TENSOR_WRITE, Tensor::CAFFE); fill(ptr) ; tensor->unmap(Tensor::MAP_TENSOR_WRITE, Tensor::CAFFE, ptr);
3. 建一个 hostTensor ，fill 0.0f 之后再调 copyFromHostTensor
