### ISSUE TITLE
mnn 模型解析的Const 算子的Tensor数据为空，可能是什么原因

### ISSUE THREAD

**Issue by yangshanjun** [alibaba/MNN#2375]
mnn 模型：

{ "bizCode": "biz", "extraInfo": 
{ "version": "2.4.1" }
, "oplists": 
[ 

{ "main_type": "Input", "main": 
{ "dims": 
[ 3, 2, 2 ]
, "dtype": "DT_FLOAT", "dformat": "NCHW" }
, "name": "input1", "outputIndexes": 
[ 0 ]
, "type": "Input", "defaultDimentionFormat": "NHWC" }
, 

{ "inputIndexes": 
[ 0 ]
, "main_type": "UnaryOp", "main": 
{ "opType": "ABS", "T": "DT_FLOAT" }
, "name": "/Abs_output_0", "outputIndexes": 
[ 1 ]
, "type": "UnaryOp", "defaultDimentionFormat": "NHWC" }

, 
{ "main_type": "Blob", "main": 
{ "dims": 
[ 2, 2, 2 ]
, "dataFormat": "NCHW", "dataType": "DT_FLOAT", "float32s": 
[ 0.1, 3.7, 0.44, 0.98, 0.555, -0.9, 0.6, -0.4 ]
 }
, "name": "/Constant_output_0", "outputIndexes": 
[ 2 ]
, "type": "Const", "defaultDimentionFormat": "NHWC" }
, 

{ "inputIndexes": 
[ 1, 2 ]
, "main_type": "Axis", "main": 
{ "axis": 0 }
, "name": "output", "outputIndexes": 
[ 3 ]
, "type": "Concat", "defaultDimentionFormat": "NHWC" }
 ]

 , "outputName": 
[ "output" ]
, "preferForwardType": "CPU", "sourceType": "ONNX", "tensorName": 
[ "input1", "/Abs_output_0", "/Constant_output_0", "output" ]
, "tensorNumber": 0, "usage": "INFERENCE", "mnn_uuid": "dd2a68f3-98a1-4f09-a380-e39e4531b9e1" }

打印为空：
![image](https://github.com/alibaba/MNN/assets/11879626/c35fd5df-4a97-4ae9-be54-125882876a22)

**Comment by jxt1234** [comment]
你是怎么读取 mnn 模型并取出 tensor 的？

**Comment by jxt1234** [comment]
想要读取内部的 const 算子参数，建议用 Express 接口: auto varps = MNN::Express::Variable::loadMap("XXX.mnn"); auto constTensor = varps["/Constant_output_0"]; auto ptr = constTensor->readMap<float>();
