### ISSUE TITLE
softmax not support dimensions == 3

### ISSUE THREAD

**Issue by yjhdhr** [alibaba/MNN#2376]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86 ，目标是部署再android

# Github版本:
# Github Version:

commit https://github.com/alibaba/MNN/commit/d7d1efe03ba616de9fcdd8eeb9d8ce5c2d788349 (HEAD -> master, tag: 2.5.0, origin/master, origin/HEAD)

# 编译方式:
# Compiling Method

# 问题:

```
在安卓端推理模型，使用CPU（MNN_FORWARD_CPU）模型可以正常resizesession和运行，使用GPU（MNN_FORWARD_OPENCL）时会出现“softmax not support dimensions == 3”问题，无法完成后续。

请问这个现在有什么方案解决吗？
```

**Comment by wangzhaode** [comment]
OpenCL没有支持输入shape是维度是3的情况

**Comment by fuerpy** [comment]
@yjhdhr 你好，请问这个问题你有后续解决吗？
