### ISSUE TITLE
pt转onnx，使用onnx转mnn模型成功，onnx结果正确，但mnn推理结果对不齐

### ISSUE THREAD

**Issue by Z-Xiong** [alibaba/MNN#2377]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux x86_64

# Github版本:
# Github Version: 2.5

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cd /path/to/MNN/pymnn/pip_package
python build_deps.py
python setup.py install --version 2.5

# 问题描述
模型为OSTrack，一个基于Transformer的单目标跟踪算法。从pt转为onnx后，使用onnx python api推理结果正确，几乎无精度损失。但是onnx转为mnn后，在输入预处理相同的情况下，mnn的推理结果完全不正确。

# 问题排查
使用testMNNFromOnnx.py 测试有问题，但是不知应该如何更改

# 模型文件
onnx：链接: https://pan.baidu.com/s/1K4qDWjk99F-XeJxmQJoolA?pwd=czqc 提取码: czqc 复制这段内容后打开百度网盘手机App，操作更方便哦
mnn： 链接: https://pan.baidu.com/s/1mSOnBc1KMrcLYzWzIbRL0Q?pwd=xz5h 提取码: xz5h 复制这段内容后打开百度网盘手机App，操作更方便哦

# 模型推理代码(包含onnx推理)
 https://github.com/Z-Xiong/ostrack-pymnn

**Comment by jxt1234** [comment]
可以用其他方式传模型？这里无法访问百度网盘，另外 testMNNFromOnnx.py 的 log 发一下吧

**Comment by jxt1234** [comment]
测试了 testMNNFromOnnx 无问题

**Comment by jxt1234** [comment]
代码中这里没有给输入赋值。另外 resizeTensor 之后需要 resizeSession 
"        # tmp_input = MNN.Tensor(x_patch_arr)
        # self.interpreter.resizeTensor(self.input_tensors_dict['x'], (1, C, H, W))
        # self.input_tensors_dict['x'].copyFrom(tmp_input)

        ret = self.interpreter.runSession(self.session)
        output_tensors_dict = self.interpreter.getSessionOutputAll(self.session)"

**Comment by jxt1234** [comment]
![image](https://github.com/alibaba/MNN/assets/5484403/735c7ac3-ae00-416e-a9a1-1a976dd30589)

**Comment by jxt1234** [comment]
使用 testMNNFromOnnx.py 测试是否正确时不要加 DEBUG 参数。在测试出错之后再加参数定位问题

**Comment by Z-Xiong** [comment]
> 代码中这里没有给输入赋值。另外 resizeTensor 之后需要 resizeSession " # tmp_input = MNN.Tensor(x_patch_arr) # self.interpreter.resizeTensor(self.input_tensors_dict['x'], (1, C, H, W)) # self.input_tensors_dict['x'].copyFrom(tmp_input)
> 
> ```
>     ret = self.interpreter.runSession(self.session)
>     output_tensors_dict = self.interpreter.getSessionOutputAll(self.session)"
> ```
输入赋值，这样不可以吗？我没有进行resizeTensor，因为输入形状是固定的。

 self.input_tensors_z = self.interpreter.getSessionInput(self.session, 'z')
        self.input_tensors_x = self.interpreter.getSessionInput(self.session, 'x')
 self.input_tensors_z = MNN.Tensor([1, C, H, W], MNN.Halide_Type_Float, z_patch_arr.astype(np.float32), MNN.Tensor_DimensionType_Caffe)

**Comment by Z-Xiong** [comment]
输入设置为：
```
self.input_tensors_z = self.interpreter.getSessionInput(self.session, 'z')
        self.input_tensors_x = self.interpreter.getSessionInput(self.session, 'x')

tmp_input = MNN.Tensor([1, C, H, W], MNN.Halide_Type_Float, z_patch_arr.astype(np.float32), MNN.Tensor_DimensionType_Caffe)
        self.input_tensors_z.copyFrom(tmp_input)

tmp_input = MNN.Tensor([1, C, H, W], MNN.Halide_Type_Float, x_patch_arr.astype(np.float32), MNN.Tensor_DimensionType_Caffe)
        self.input_tensors_x.copyFrom(tmp_input)
```
观察发现，self.input_tensors_x的值与tmp input的值不一致。
查看mnn模型信息：
```
(lighttrack) ubuntu@ubuntu-Super-Server:/mnt/sata1/xiongzhuang/github/MNN/build$ ./MNNConvert -f MNN --info --modelFile ostrack.mnn
The device support i8sdot:0, support fp16:0, support i8mm: 0
Model default dimensionFormat is NCHW
Model Inputs:
[ z ]: dimensionFormat: NC4HW4, size: [ 1,3,128,128 ], type is float
[ x ]: dimensionFormat: NC4HW4, size: [ 1,3,256,256 ], type is float
Model Outputs:
[ 1313 ]
[ 1809 ]
[ 2052 ]
[ 2159 ]
[ 821 ]
[ offset_map ]
[ pred_boxes ]
[ score_map ]
[ size_map ]
Model Version: 2.5.0 
```
请问是什么原因导致的呢？

**Comment by jxt1234** [comment]
"self.input_tensors_x的值与tmp input的值不一致" ，这个是因为 self.input_tensors_x 是 nc4hw4 布局，tmp input 是 nchw 布局

**Comment by Z-Xiong** [comment]
谢谢！通过转换加了--keepInputFormat以及转换输出格式解决了输出对齐的问题了。现在就是onnx的推理结果和mnn推理的有一点点偏差，表现在跟踪任务上就是onnx不会跟踪错误，mnn的会跟踪错误。请问有可能是什么原因呢

**Comment by jxt1234** [comment]
mnn 的precision 设成 high 试下?
