### ISSUE TITLE
rtdetr模型转mnn失败，使用testMNNFromOnnx.py测试没有测试成功

### ISSUE THREAD

**Issue by yy2yy** [alibaba/MNN#2378]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
ubuntu20.4

# Github版本:
MNN 2.5

# 编译方式:

```
cd /path/to/MNN
./schema/generate.sh
./tools/script/get_model.sh # 可选，模型仅demo工程需要
mkdir build && cd build && cmake .. && make -j8
```

rtdetr模型：https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rtdetr
采用的paddle官方的T-DETR-R18模型，转换成onnx：
python3 tools/export_model.py -c configs/rtdetr/rtdetr_r18vd_6x_coco.yml -o weights=./rtdetr_r18vd_dec3_6x_coco.pdparams trt=True --output_dir=output_inference

paddle2onnx --model_dir=./output_inference/rtdetr_r18vd_6x_coco/ --model_filename model.pdmodel --params_filename model.pdiparams --opset_version 16 --save_file rtdetr_r18vd_6x_coco.onnx

然后使用testMNNFromOnnx.py测试转换onnx，出现如下错误：
python3 testMNNFromOnnx.py ./rtdetr_r18vd_6x_coco.onnx

![1684378887306_14B5F30D-4CD7-4ceb-8BB8-76E8F7E3A6F7](https://github.com/alibaba/MNN/assets/51770574/9a79db6a-5f96-442d-8959-120d92919ac6)

**Comment by jxt1234** [comment]
onnx 模型中存在inf ，可以去除 inf 数值再试试
