### ISSUE TITLE
output issues

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#238]
in document:
![image](https://user-images.githubusercontent.com/24749356/63099244-4899e680-bfa7-11e9-9e91-915b726b2a92.png)
but when i try:
![无标题](https://user-images.githubusercontent.com/24749356/63099635-0b822400-bfa8-11e9-9e69-454fa8fe0987.png)

**Comment by li-qing** [comment]
thanks. `()` is missing in the document. fixed.

change `host<float>[0]` to `host<float>()[0]` would fix your problem.
