### ISSUE TITLE
MNN有计划适配MTK的APU和高通的cDSP么？

### ISSUE THREAD

**Issue by zaykl** [alibaba/MNN#2380]
MNN有单独适配了华为的NPU，但是像MTK的APU和高通的cDSP有适配的计划么？

**Comment by jxt1234** [comment]
MNN 支持 NNAPI 后端。
MTK 的 APU 按厂商建议基于 NNAPI 调用。
高通的 cDSP 目前也可以通过 NNAPI 调用，后续会考虑改成别的方案。

**Comment by zaykl** [comment]
但实际上，我们发现调用nnapi比调用各家官方的sdk要慢一个级别。此外paddle-lite目前也是单独支持各家芯片的接口。
MTK版本TFlite单次推理平均耗时15ms
谷歌原生版本TFlite单次推理平均耗时191ms

模型使用openpose_mobilenet
参考：https://neuropilot.mediatek.com/resources/public/latest/en/docs/readme

**Comment by zaykl** [comment]
另外在高通845下，基于MNN测试mobilenet，nnapi的性能也比opencl要慢得多，远没有高通的snpe推理速度快。

**Comment by jxt1234** [comment]
> 另外在高通845下，基于MNN测试mobilenet，nnapi的性能也比opencl要慢得多，远没有高通的snpe的DSP模式推理速度快和低CPU占用。

NNAPI 应该要用 precision = low

**Comment by zaykl** [comment]
是用了precision = low
//NNAPI 应该要用 precision = low

**Comment by zaykl** [comment]
//MTK 的 APU 按厂商建议基于 NNAPI 调用。
关于这个问题你们可以看下MTK官方文档，MTK调用NNAPI的方式是参考了Android官方的接口改成调用他们内部实现的，实际上并不是调用Android的NNAPI。具体可以参考MTK提供的NeuroPilotTFLiteShim.h头文件。

inline void* getTFLiteLibraryHandle() {
    if (sTFLiteHandle == nullptr) {
        // Load library for platform level development
        sTFLiteHandle = loadTFLiteLibrary("libtflite_mtk.so");
    }
    if (sTFLiteHandle == nullptr) {
        // Load library for APK JNI level development
        sTFLiteHandle = loadTFLiteLibrary("libtflite_mtk_static.so");
    }
    return sTFLiteHandle;
}

**Comment by zhangw864680355** [comment]
@zaykl 你好，打扰了，请问如何获取MTK的NeuroPilot开发资料包？我这边按照官方开发者中心的要求发了多次邮件申请均无反馈，能否方便提供MTK的开发资料包，谢谢！

**Comment by zaykl** [comment]
@zhangw864680355 也是公司签商业合作合同, 才能登录到开发者后台下载的, 不对外...

**Comment by noahzhy** [comment]
How about the infer time of MNN now?

**Comment by Lexlum** [comment]
> How about the infer time of MNN now?

same question
