### ISSUE TITLE
相同的算子在不同模型中耗时差别很大

### ISSUE THREAD

**Issue by ding-github** [alibaba/MNN#2382]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
/proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"

# 编译方式:
./schema/generate.sh
cd project/android
mkdir build_64 
cd build_64 
../build_64.sh

# 日志:
lito:/system/ding # ./GetMNNInfo det.mnn
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
Model default dimensionFormat is NCHW
Model Inputs:
[ data ]: dimensionFormat: NC4HW4, size: [ 1,3,320,240 ], type is float
[ im_info ]: dimensionFormat: NC4HW4, size: [ 1,3 ], type is float
Model Outputs:
[ bbox_pred ]
[ cls_prob ]
Model Version: < 2.0.0
lito:/system/ding #
lito:/system/ding # ./GetMNNInfo T630-X1.mnn
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
Model default dimensionFormat is NCHW
Model Inputs:
[ input ]: dimensionFormat: NC4HW4, size: [ 1,1,512,640 ], type is float
Model Outputs:
[ output ]
Model Version: 2.0.1
lito:/system/ding #
lito:/system/ding #
lito:/system/ding #
lito:/system/ding # ./MNNV2Basic.out det.mnn 10 0 0 1
Use extra forward type: 0

Open Model det.mnn
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
test_main, 226, cost time: 9.527000 ms
Session Info: memory use 2.388794 MB, flops is 32.288136 M, backendType is 13
===========> Session Resize Done.
===========> Session Start running...
Input size:307200
        **Tensor shape**: 1, 3, 320, 240,
output: bbox_pred
output: cls_prob
precision:2, memory: 0, Run 10 time:
                                 cls_prob_raster_0      [Raster] run 10 average cost 0.001000 ms, 0.021 %, FlopsRate: 0.000 %
                                bbox_pred_raster_0      [Raster] run 10 average cost 0.001100 ms, 0.023 %, FlopsRate: 0.001 %
                        student_v2/roinet/fc2/relu      [ReLU] run 10 average cost 0.002300 ms, 0.049 %, FlopsRate: 0.025 %
               student_v2/roinet/fc2/relu_raster_0      [Raster] run 10 average cost 0.002300 ms, 0.049 %, FlopsRate: 0.025 %
                            Convolution51_raster_1      [Raster] run 10 average cost 0.003000 ms, 0.063 %, FlopsRate: 0.049 %
               student_v2/roinet/fc1/relu_raster_0      [Raster] run 10 average cost 0.003400 ms, 0.072 %, FlopsRate: 0.025 %
                        student_v2/roinet/fc1/relu      [ReLU] run 10 average cost 0.003800 ms, 0.080 %, FlopsRate: 0.025 %
                 student_v2/roinet/roi_pool/conv_2      [ROIPooling] run 10 average cost 0.005700 ms, 0.120 %, FlopsRate: 0.006 %
                                          cls_prob      [Softmax] run 10 average cost 0.006100 ms, 0.129 %, FlopsRate: 0.000 %
                                  student_v2/pool2      [Pooling] run 10 average cost 0.007900 ms, 0.167 %, FlopsRate: 0.131 %
                                 proposal_raster_0      [Raster] run 10 average cost 0.011400 ms, 0.241 %, FlopsRate: 0.018 %
                                  student_v2/pool1      [Pooling] run 10 average cost 0.013500 ms, 0.285 %, FlopsRate: 0.261 %
                             rpn_cls_prob_raster_0      [Raster] run 10 average cost 0.016600 ms, 0.351 %, FlopsRate: 0.033 %
                     student_v2/proposal_cls_score      [Convolution] run 10 average cost 0.021400 ms, 0.452 %, FlopsRate: 0.616 %
                        student_v2/roinet/roi_pool      [ROIPooling] run 10 average cost 0.024600 ms, 0.520 %, FlopsRate: 0.049 %
                     student_v2/proposal_bbox_pred      [Convolution] run 10 average cost 0.025400 ms, 0.537 %, FlopsRate: 1.232 %
                            Convolution51_raster_0      [Raster] run 10 average cost 0.031200 ms, 0.659 %, FlopsRate: 0.049 %
                                student_v2/conv3_1      [Convolution] run 10 average cost 0.037900 ms, 0.801 %, FlopsRate: 4.379 %
                                      rpn_cls_prob      [Softmax] run 10 average cost 0.041600 ms, 0.879 %, FlopsRate: 0.033 %
                                student_v2/conv2_1      [Convolution] run 10 average cost 0.057500 ms, 1.215 %, FlopsRate: 4.379 %
                                student_v2/conv3_3      [Convolution] run 10 average cost 0.062100 ms, 1.312 %, FlopsRate: 8.759 %
                                student_v2/conv3_4      [Convolution] run 10 average cost 0.062100 ms, 1.312 %, FlopsRate: 8.759 %
                                student_v2/conv3_2      [Convolution] run 10 average cost 0.063200 ms, 1.336 %, FlopsRate: 8.759 %
                                student_v2/conv2_2      [Convolution] run 10 average cost 0.080800 ms, 1.708 %, FlopsRate: 8.759 %
                   student_v2/conv_proposal/conv_3      [Convolution] run 10 average cost 0.083500 ms, 1.765 %, FlopsRate: 9.853 %
                                student_v2/conv2_3      [Convolution] run 10 average cost 0.087300 ms, 1.845 %, FlopsRate: 8.759 %
                                student_v2/conv1_3      [Convolution] run 10 average cost 0.118800 ms, 2.511 %, FlopsRate: 8.759 %
                                student_v2/conv1_2      [Convolution] run 10 average cost 0.128100 ms, 2.707 %, FlopsRate: 8.759 %
                                student_v2/conv1_1      [Convolution] run 10 average cost 0.183300 ms, 3.874 %, FlopsRate: 3.284 %
                                     Convolution51      [Convolution] run 10 average cost 0.232500 ms, 4.913 %, FlopsRate: 13.287 %
                                          proposal      [Proposal] run 10 average cost 0.236500 ms, 4.998 %, FlopsRate: 0.001 %
                                       data_resize      [Interp] run 10 average cost 0.317600 ms, 6.712 %, FlopsRate: 0.928 %
Avg= 4.732001 ms, OpSum = 1.973500 ms min= 4.619000 ms, max= 4.927000 ms
lito:/system/ding #
lito:/system/ding #
lito:/system/ding # ./MNNV2Basic.out  T630-X1.mnn 10 0 0 1
Use extra forward type: 0

Open Model T630-X1.mnn
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc LAGOON"
The device support i8sdot:1, support fp16:1, support i8mm: 0
test_main, 226, cost time: 10.003000 ms
Session Info: memory use 65.939392 MB, flops is 36678.777344 M, backendType is 13
===========> Session Resize Done.
===========> Session Start running...
Input size:1310720
        **Tensor shape**: 1, 1, 512, 640,
output: output
precision:2, memory: 0, Run 10 time:
                                            output      [BinaryOp] run 10 average cost 1.713100 ms, 0.218 %, FlopsRate: 0.003 %
                                                39      [BinaryOp] run 10 average cost 4.778600 ms, 0.608 %, FlopsRate: 0.027 %
                                                69      [BinaryOp] run 10 average cost 4.788500 ms, 0.610 %, FlopsRate: 0.027 %
                                                45      [BinaryOp] run 10 average cost 4.797400 ms, 0.611 %, FlopsRate: 0.027 %
                                                63      [BinaryOp] run 10 average cost 4.805500 ms, 0.612 %, FlopsRate: 0.027 %
                                                57      [BinaryOp] run 10 average cost 4.815000 ms, 0.613 %, FlopsRate: 0.027 %
                                                51      [BinaryOp] run 10 average cost 4.824900 ms, 0.614 %, FlopsRate: 0.027 %
                                       53_raster_0      [Raster] run 10 average cost 6.439001 ms, 0.820 %, FlopsRate: 0.027 %
                                       41_raster_0      [Raster] run 10 average cost 6.449901 ms, 0.821 %, FlopsRate: 0.027 %
                                       65_raster_0      [Raster] run 10 average cost 6.458801 ms, 0.822 %, FlopsRate: 0.027 %
                                                52      [BinaryOp] run 10 average cost 6.922801 ms, 0.881 %, FlopsRate: 0.027 %
                                                64      [BinaryOp] run 10 average cost 6.978900 ms, 0.889 %, FlopsRate: 0.027 %
                                                40      [BinaryOp] run 10 average cost 6.999701 ms, 0.891 %, FlopsRate: 0.027 %
                                                58      [BinaryOp] run 10 average cost 7.055300 ms, 0.898 %, FlopsRate: 0.027 %
                                                46      [BinaryOp] run 10 average cost 7.062500 ms, 0.899 %, FlopsRate: 0.027 %
                                                70      [BinaryOp] run 10 average cost 7.108501 ms, 0.905 %, FlopsRate: 0.027 %
                                       47_raster_0      [Raster] run 10 average cost 7.138700 ms, 0.909 %, FlopsRate: 0.027 %
                                       59_raster_0      [Raster] run 10 average cost 7.170300 ms, 0.913 %, FlopsRate: 0.027 %
                                       71_raster_0      [Raster] run 10 average cost 7.198799 ms, 0.917 %, FlopsRate: 0.027 %
                                       51_raster_0      [Raster] run 10 average cost 8.368700 ms, 1.065 %, FlopsRate: 0.027 %
                                       63_raster_0      [Raster] run 10 average cost 8.381600 ms, 1.067 %, FlopsRate: 0.027 %
                                       40_raster_0      [Raster] run 10 average cost 8.555301 ms, 1.089 %, FlopsRate: 0.027 %
                                       69_raster_0      [Raster] run 10 average cost 8.609600 ms, 1.096 %, FlopsRate: 0.027 %
                                       45_raster_0      [Raster] run 10 average cost 8.611300 ms, 1.096 %, FlopsRate: 0.027 %
                                       39_raster_0      [Raster] run 10 average cost 8.612600 ms, 1.096 %, FlopsRate: 0.027 %
                                       57_raster_0      [Raster] run 10 average cost 8.633300 ms, 1.099 %, FlopsRate: 0.027 %
                                                33      [Convolution] run 10 average cost 14.431500 ms, 1.837 %, FlopsRate: 0.257 %
                                                71      [Convolution] run 10 average cost 55.964199 ms, 7.125 %, FlopsRate: 0.257 %
                                                61      [Convolution] run 10 average cost 61.211700 ms, 7.793 %, FlopsRate: 8.233 %
                                                49      [Convolution] run 10 average cost 61.436096 ms, 7.822 %, FlopsRate: 8.233 %
                                                35      [Convolution] run 10 average cost 61.604309 ms, 7.843 %, FlopsRate: 8.233 %
                                                53      [Convolution] run 10 average cost 61.659706 ms, 7.850 %, FlopsRate: 8.233 %
                                                65      [Convolution] run 10 average cost 61.946400 ms, 7.887 %, FlopsRate: 8.233 %
                                                41      [Convolution] run 10 average cost 62.104805 ms, 7.907 %, FlopsRate: 8.233 %
                                                47      [Convolution] run 10 average cost 62.132710 ms, 7.910 %, FlopsRate: 8.233 %
                                                59      [Convolution] run 10 average cost 62.184914 ms, 7.917 %, FlopsRate: 8.233 %
                                                67      [Convolution] run 10 average cost 62.230206 ms, 7.923 %, FlopsRate: 8.233 %
                                                43      [Convolution] run 10 average cost 62.413403 ms, 7.946 %, FlopsRate: 8.233 %
                                                37      [Convolution] run 10 average cost 62.439400 ms, 7.949 %, FlopsRate: 8.233 %
                                                55      [Convolution] run 10 average cost 62.543499 ms, 7.963 %, FlopsRate: 8.233 %
Avg= 785.463501 ms, OpSum = 987.581360 ms min= 784.474060 ms, max= 786.473022 ms

在det.mnn和T630-X1.mnn两个模型都有weight<32x32x3x3>bias<32>的Convolution算子，
其中det.mnn模型中该算子耗时为 student_v2/conv3_2      [Convolution] run 10 average cost 0.063200 ms，
T630-X1.mnn模型中该算子耗时为 41      [Convolution] run 10 average cost 62.104805 ms，
虽然两个模型的输入有差异，det.mnn模型输入为1,3,320,240，T630-X1.mnn模型输入为1,1,512,640，但是耗时也不应该差别这么大。

**Comment by jxt1234** [comment]
用 width * height * ic * oc 估算一下卷积计算。并用 timeProfile.out 测试下看看 slowest op ，看计算效率是否有区别: 

Print <=20 slowest Op for Convolution, larger than 3.00:
