### ISSUE TITLE
不同平台做模型转换生成的mnn模型通用吗？

### ISSUE THREAD

**Issue by wojiaoyanmin** [alibaba/MNN#2384]
请问不同平台做模型转换生成的mnn模型通用吗？
比如我在windows用mnn convert转换生成的model.mnn模型，现在安卓平台上可以直接用还是需要在安卓上重新转换生成呢？

另：请问mnn现在支持macos吗？

谢谢

**Comment by jxt1234** [comment]
1. mnn 模型是通用的
2. 支持 macos 的
