### ISSUE TITLE
前处理后图像发生部分列像素从右侧边界位移到左侧边界

### ISSUE THREAD

**Issue by neptune4year** [alibaba/MNN#2386]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android

# Github版本: 2.2

# 编译方式: cmake build
# Compiling Method

前处理过程：将相机图片转换为垂直，并转为RGB，长边等比例居中缩放到256，短边两侧补0
代码：
int _size = 256;
int w = 720;
int h = 1280;
int rotation = 0;
const float means[3] = {103.53f, 116.535f, 122.40f};
const float normals[3] = {0.01743f, 0.01751f, 0.01712f};
auto pretreat = std::shared_ptr<MNN::CV::ImageProcess>(
  MNN::CV::ImageProcess::create(MNN::CV::RGBA, MNN::CV::RGB, means, 3, normals, 3));
auto fit = MNN::CV::Matrix::ScaleToFit::kCenter_ScaleToFit;
MNN::CV::Matrix matrix = MNN::CV::Matrix::MakeRectToRect(
  MNN::CV::Rect::MakeIWH(w, h),MNN::CV::Rect::MakeIWH(_size, _size), fit);

matrix.postRotate(rotation, _size / 2, _size / 2);
if (0) {
  matrix.postScale(1.0/_size, 1.0/_size);
  matrix.postScale(-1.0, 1.0, 0.5, 0.0);
  matrix.postScale(_size, _size);
}
matrix.invert(&matrix);
pretreat->setMatrix(matrix);
auto input = _net->getSessionInput(_session, nullptr);
pretreat->convert(pImage, w, h, 0, input);

输出结果：
![lQLPJwGl2oIG8_7NAfrNAfyw3dJ7arQ538kEYlUYbUDTAA_508_506](https://github.com/alibaba/MNN/assets/25241494/4ca0f0ce-0674-4941-a6d2-3ca55e98c5ff)
正确结果应为：
![lQLPJw-uW5Xj577NAf7NAfywKVA_bwi7jD4EYlVJvADQAA_508_510](https://github.com/alibaba/MNN/assets/25241494/d3c57403-859d-4633-b32b-05893d94c108)
麻烦帮忙查一下问题所在

**Comment by jxt1234** [comment]
原始图片也放上来吧

**Comment by neptune4year** [comment]
> 原始图片也放上来吧

![dfad](https://github.com/alibaba/MNN/assets/25241494/c1e80e4e-0886-497f-9e3e-e494b6cff1c8)

**Comment by v0jiuqi** [comment]
hi, 我看到你描述的是想要把图片转成竖直格式，这里应该把rotation设置成90？

**Comment by v0jiuqi** [comment]
hi, 我用你的代码转图片结果显示正常，代码提供给你

`auto angle = 0;
int destSize = 256;
int width = 720, height = 1280;
auto fit = Matrix::ScaleToFit::kCenter_ScaleToFit;

    MNN_PRINT("size: %d, %d\n", width, height);
    Matrix trans;
    trans = MNN::CV::Matrix::MakeRectToRect(
    MNN::CV::Rect::MakeIWH(width, height),MNN::CV::Rect::MakeIWH(destSize, destSize), fit);

    trans.postRotate(angle, destSize / 2, destSize / 2);
    trans.invert(&trans);

    CV::ImageProcess::Config _config;
    _config.sourceFormat = CV::RGBA;
    _config.destFormat   = CV::RGB;
    _config.filterType   = CV::NEAREST;
    _config.wrap         = CV::ZERO;

    std::shared_ptr<ImageProcess> pretreat(ImageProcess::create(_config));
    pretreat->setMatrix(trans);
    {
        std::shared_ptr<Tensor> wrapTensor(ImageProcess::createImageTensor<uint8_t>(destSize, destSize, 3, nullptr));
        pretreat->convert((uint8_t*)inputImage, width, height, 0, wrapTensor.get());
        stbi_write_png(argv[3], destSize, destSize, 3, wrapTensor->host<uint8_t>(), 0);
    }`

**Comment by v0jiuqi** [comment]
![cvtest_output](https://github.com/alibaba/MNN/assets/124856990/ed1156fd-c1ce-48b9-ac87-ceff67c76b8a)
这是我转换的结果
