### ISSUE TITLE
Tutorial_CN不能正常访问

### ISSUE THREAD

**Issue by zeyuanlicbpm** [alibaba/MNN#239]
你好，昨天工程中还有一个Android Demo。具体关于在Android Studio中一步步添加so库，修改参数，编译ndk，运行程序的例子，今天貌似没有了！  是删除了吗？

**Comment by nullptr-leo** [comment]
文档迁移到了：http://www.yuque.com/mnn
或者git reset看看呗

**Comment by zeyuanlicbpm** [comment]
好的 谢谢
