### ISSUE TITLE
AMD平台使用opencl推理，出现内存越界

### ISSUE THREAD

**Issue by HaiLongEmb** [alibaba/MNN#2393]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake -DMNN_BUILD_SHARED_LIBS=ON -DMNN_BUILD_CONVERTER=ON -DMNN_OPENCL=ON -DCMAKE_BUILD_TYPE=Debug -DMNN_BUILD_BENCHMARK=true   -DMNN_BUILD_DEMO=ON -DMNN_USE_SYSTEM_LIB=ON -DOpenCL_LIBRARY=/opt/rocm-5.4.5/opencl/lib/libOpenCL.so -DOpenCL_INCLUDE_DIR=/home/gwmos/MNN-2.4.0/3rd_party/OpenCLHeaders -DMNN_SEP_BUILD=OFF -DCMAKE_BUILD_TYPE=Debug ..
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

--
-- 3.19.0.0
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: x86_64
--      Version: 2.4.0
--      Metal: OFF
--      OpenCL: ON
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      NNAPI: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16: OFF
--      ThreadPool: ON
--      Hidden: FALSE
--      Build Path: /home/os/MNN-2.4.0/build_debug
--      CUDA PROFILE: OFF
-- WIN_USE_ASM:
-- x86_64: Open SSE
-- MNN_AVX512:OFF
-- Onnx:
-- MNN Depends:MNN
-- Configuring done
-- Generating done
-- Build files have been written to: /home/os/MNN-2.4.0/build_debug
```
粘贴在这里
Paste log here or pastebin
```
./MNNV2Basic.out models/hp_relu_64.mnn 10 0 3 4
Use extra forward type: 3

Open Model models/hp_relu_64.mnn
The device support dot:0, support fp16:0, support i8mm: 0
test_main, 225, cost time: 7279.549805 ms
Session Info: memory use 0.001293 MB, flops is 14.850842 M, backendType is 3
===========> Session Resize Done.
===========> Session Start running...
Input size:12288
        **Tensor shape**: 1, 64, 64, 3,
Memory access fault by GPU node-1 (Agent handle: 0x56434ccb5180) on address 0x7f0096c84000. Reason: Page not present or supervisor privilege.
已放弃 (核心已转储)

./MNNV2Basic.out models/hp_relu_64.mnn 10 0 0 4
Use extra forward type: 0

Open Model models/hp_relu_64.mnn
The device support dot:0, support fp16:0, support i8mm: 0
test_main, 225, cost time: 14.350000 ms
Session Info: memory use 2.600475 MB, flops is 14.850842 M, backendType is 13
===========> Session Resize Done.
===========> Session Start running...
Input size:12288
        **Tensor shape**: 1, 64, 64, 3,
output: functional_1/pred_pose/mul_24
precision:2, Run 10 time:
                  functional_1/pred_pose/truediv_1      [BinaryOp] run 10 average cost 0.001200 ms, 0.027 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_14      [BinaryOp] run 10 average cost 0.001200 ms, 0.027 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_8_raster_0      [Raster] run 10 average cost 0.001200 ms, 0.027 %, FlopsRate: 0.000 %
                  functional_1/pred_pose/truediv_2      [BinaryOp] run 10 average cost 0.001300 ms, 0.030 %, FlopsRate: 0.000 %
         functional_1/k3_delta_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001300 ms, 0.030 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_18      [BinaryOp] run 10 average cost 0.001300 ms, 0.030 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_19      [BinaryOp] run 10 average cost 0.001300 ms, 0.030 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_10      [BinaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
         functional_1/k1_delta_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
        functional_1/k3_loacal_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_19      [BinaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_8      [BinaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_9      [BinaryOp] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_7_raster_0      [Raster] run 10 average cost 0.001400 ms, 0.032 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_21      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
            functional_1/pred_pose/mul_10_raster_0      [Raster] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
               functional_1/pred_pose/mul_raster_0      [Raster] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                  functional_1/pred_pose/truediv_5      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_10      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_2      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_23      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_3      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_15      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_17      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_24      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_6_raster_0      [Raster] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_7      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_9      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
                  functional_1/pred_pose/truediv_4      [BinaryOp] run 10 average cost 0.001500 ms, 0.034 %, FlopsRate: 0.000 %
        functional_1/k2_loacal_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
           functional_1/k3_delta_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_13      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_15      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_16      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_20      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_22      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_24      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
            functional_1/pred_pose/mul_11_raster_0      [Raster] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_14      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_21      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_23      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_8      [BinaryOp] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_9_raster_0      [Raster] run 10 average cost 0.001600 ms, 0.037 %, FlopsRate: 0.000 %
           functional_1/k1_delta_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
          functional_1/k1_loacal_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
        functional_1/k1_loacal_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
           functional_1/k2_delta_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_1      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_11      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_12      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_25      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_1      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_11      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_20      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_5      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
                    functional_1/pred_pose/truediv      [BinaryOp] run 10 average cost 0.001700 ms, 0.039 %, FlopsRate: 0.000 %
          functional_1/k2_loacal_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
                        functional_1/pred_pose/mul      [BinaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_13      [BinaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_16      [BinaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_3_raster_0      [Raster] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_4      [BinaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
                  functional_1/pred_pose/truediv_3      [BinaryOp] run 10 average cost 0.001800 ms, 0.041 %, FlopsRate: 0.000 %
         functional_1/k2_delta_value/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
          functional_1/k3_loacal_fea/Tanh_raster_1      [UnaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_17      [BinaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/add_18      [BinaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_5      [BinaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_12      [BinaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_1_raster_0      [Raster] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                     functional_1/pred_pose/mul_22      [BinaryOp] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_4_raster_0      [Raster] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_5_raster_0      [Raster] run 10 average cost 0.001900 ms, 0.043 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_4      [BinaryOp] run 10 average cost 0.002000 ms, 0.046 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_6      [BinaryOp] run 10 average cost 0.002000 ms, 0.046 %, FlopsRate: 0.000 %
             functional_1/pred_pose/mul_2_raster_0      [Raster] run 10 average cost 0.002000 ms, 0.046 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_3      [BinaryOp] run 10 average cost 0.002000 ms, 0.046 %, FlopsRate: 0.000 %
                        functional_1/pred_pose/add      [BinaryOp] run 10 average cost 0.002100 ms, 0.048 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_6      [BinaryOp] run 10 average cost 0.002100 ms, 0.048 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/add_7      [BinaryOp] run 10 average cost 0.002200 ms, 0.050 %, FlopsRate: 0.000 %
                                    Convolution271      [Convolution] run 10 average cost 0.002300 ms, 0.052 %, FlopsRate: 0.000 %
                      functional_1/pred_pose/mul_2      [BinaryOp] run 10 average cost 0.002300 ms, 0.052 %, FlopsRate: 0.000 %
                                    Convolution345      [Convolution] run 10 average cost 0.002400 ms, 0.055 %, FlopsRate: 0.000 %
                                    Convolution470      [Convolution] run 10 average cost 0.002400 ms, 0.055 %, FlopsRate: 0.000 %
                                    Convolution545      [Convolution] run 10 average cost 0.002400 ms, 0.055 %, FlopsRate: 0.000 %
                                    Convolution642      [Convolution] run 10 average cost 0.002600 ms, 0.059 %, FlopsRate: 0.000 %
                                    Convolution144      [Convolution] run 10 average cost 0.002700 ms, 0.062 %, FlopsRate: 0.000 %
                           Convolution545_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
        functional_1/k1_loacal_value/Tanh_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
         functional_1/k2_delta_value/Tanh_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
           functional_1/k3_delta_fea/Tanh_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
                           Convolution271_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
                           Convolution470_raster_0      [Raster] run 10 average cost 0.003900 ms, 0.089 %, FlopsRate: 0.000 %
                           Convolution345_raster_0      [Raster] run 10 average cost 0.004000 ms, 0.091 %, FlopsRate: 0.000 %
         functional_1/k1_delta_value/Tanh_raster_0      [Raster] run 10 average cost 0.004000 ms, 0.091 %, FlopsRate: 0.000 %
          functional_1/k2_loacal_fea/Tanh_raster_0      [Raster] run 10 average cost 0.004000 ms, 0.091 %, FlopsRate: 0.000 %
                     functional_1/k2_pred_fea/Relu      [ReLU] run 10 average cost 0.004000 ms, 0.091 %, FlopsRate: 0.000 %
        functional_1/k3_loacal_value/Tanh_raster_0      [Raster] run 10 average cost 0.004000 ms, 0.091 %, FlopsRate: 0.000 %
         functional_1/k3_delta_value/Tanh_raster_0      [Raster] run 10 average cost 0.004100 ms, 0.094 %, FlopsRate: 0.000 %
           functional_1/k1_delta_fea/Tanh_raster_0      [Raster] run 10 average cost 0.004100 ms, 0.094 %, FlopsRate: 0.000 %
        functional_1/k2_loacal_value/Tanh_raster_0      [Raster] run 10 average cost 0.004100 ms, 0.094 %, FlopsRate: 0.000 %
            functional_1/k2_pred_fea/Relu_raster_0      [Raster] run 10 average cost 0.004100 ms, 0.094 %, FlopsRate: 0.000 %
          functional_1/k1_loacal_fea/Tanh_raster_0      [Raster] run 10 average cost 0.004200 ms, 0.096 %, FlopsRate: 0.000 %
           functional_1/k2_delta_fea/Tanh_raster_0      [Raster] run 10 average cost 0.004200 ms, 0.096 %, FlopsRate: 0.000 %
                     functional_1/k3_pred_fea/Relu      [ReLU] run 10 average cost 0.004200 ms, 0.096 %, FlopsRate: 0.000 %
                           Convolution642_raster_0      [Raster] run 10 average cost 0.004300 ms, 0.098 %, FlopsRate: 0.000 %
            functional_1/k1_pred_fea/Relu_raster_0      [Raster] run 10 average cost 0.004400 ms, 0.100 %, FlopsRate: 0.000 %
          functional_1/k3_loacal_fea/Tanh_raster_0      [Raster] run 10 average cost 0.004400 ms, 0.100 %, FlopsRate: 0.000 %
                           Convolution144_raster_0      [Raster] run 10 average cost 0.004400 ms, 0.100 %, FlopsRate: 0.000 %
                     functional_1/k1_pred_fea/Relu      [ReLU] run 10 average cost 0.004500 ms, 0.103 %, FlopsRate: 0.000 %
            functional_1/k3_pred_fea/Relu_raster_0      [Raster] run 10 average cost 0.004500 ms, 0.103 %, FlopsRate: 0.000 %
                           functional_1/k2_mul/mul      [Eltwise] run 10 average cost 0.007500 ms, 0.171 %, FlopsRate: 0.007 %
                           functional_1/k3_mul/mul      [Eltwise] run 10 average cost 0.007700 ms, 0.176 %, FlopsRate: 0.007 %
                           Convolution437_raster_0      [Raster] run 10 average cost 0.008500 ms, 0.194 %, FlopsRate: 0.007 %
                           Convolution379_raster_0      [Raster] run 10 average cost 0.008800 ms, 0.201 %, FlopsRate: 0.007 %
                           Convolution312_raster_0      [Raster] run 10 average cost 0.008900 ms, 0.203 %, FlopsRate: 0.007 %
                           Convolution178_raster_0      [Raster] run 10 average cost 0.009000 ms, 0.205 %, FlopsRate: 0.007 %
                       functional_1/k2_avg/MaxPool      [Pooling] run 10 average cost 0.009700 ms, 0.221 %, FlopsRate: 0.026 %
                           Convolution238_raster_0      [Raster] run 10 average cost 0.010300 ms, 0.235 %, FlopsRate: 0.007 %
                       functional_1/k3_avg/MaxPool      [Pooling] run 10 average cost 0.010400 ms, 0.237 %, FlopsRate: 0.026 %
                           Convolution111_raster_0      [Raster] run 10 average cost 0.012000 ms, 0.274 %, FlopsRate: 0.007 %
                           Convolution609_raster_0      [Raster] run 10 average cost 0.012000 ms, 0.274 %, FlopsRate: 0.026 %
                       functional_1/k3_max/AvgPool      [Pooling] run 10 average cost 0.012500 ms, 0.285 %, FlopsRate: 0.026 %
                       functional_1/k2_max/AvgPool      [Pooling] run 10 average cost 0.013100 ms, 0.299 %, FlopsRate: 0.026 %
                           functional_1/k1_mul/mul      [Eltwise] run 10 average cost 0.016100 ms, 0.367 %, FlopsRate: 0.026 %
                                    Convolution437      [Convolution] run 10 average cost 0.017900 ms, 0.408 %, FlopsRate: 0.041 %
                            Convolution39_raster_0      [Raster] run 10 average cost 0.018300 ms, 0.418 %, FlopsRate: 0.026 %
                                    Convolution312      [Convolution] run 10 average cost 0.018500 ms, 0.422 %, FlopsRate: 0.041 %
                                    Convolution238      [Convolution] run 10 average cost 0.018800 ms, 0.429 %, FlopsRate: 0.041 %
                           Convolution512_raster_0      [Raster] run 10 average cost 0.019200 ms, 0.438 %, FlopsRate: 0.026 %
                                    Convolution111      [Convolution] run 10 average cost 0.019500 ms, 0.445 %, FlopsRate: 0.041 %
                                    Convolution379      [Convolution] run 10 average cost 0.022000 ms, 0.502 %, FlopsRate: 0.062 %
                                    Convolution178      [Convolution] run 10 average cost 0.023000 ms, 0.525 %, FlopsRate: 0.062 %
                       functional_1/k1_avg/MaxPool      [Pooling] run 10 average cost 0.025600 ms, 0.584 %, FlopsRate: 0.105 %
                   functional_1/s1_b5_pool/MaxPool      [Pooling] run 10 average cost 0.026700 ms, 0.609 %, FlopsRate: 0.105 %
           functional_1/k3_s1_conv2d/Tanh_raster_0      [UnaryOp] run 10 average cost 0.026900 ms, 0.614 %, FlopsRate: 0.026 %
           functional_1/k2_s1_conv2d/Tanh_raster_0      [UnaryOp] run 10 average cost 0.027000 ms, 0.616 %, FlopsRate: 0.026 %
                       functional_1/k1_max/AvgPool      [Pooling] run 10 average cost 0.031900 ms, 0.728 %, FlopsRate: 0.105 %
                 functional_1/k2_s1_conv2d/BiasAdd      [Convolution] run 10 average cost 0.032700 ms, 0.746 %, FlopsRate: 1.765 %
                   functional_1/s2_b5_pool/AvgPool      [Pooling] run 10 average cost 0.035800 ms, 0.817 %, FlopsRate: 0.105 %
                     functional_1/s2_b1_sc/BiasAdd      [Convolution] run 10 average cost 0.035900 ms, 0.819 %, FlopsRate: 1.324 %
                 functional_1/k2_s2_conv2d/BiasAdd      [Convolution] run 10 average cost 0.036200 ms, 0.826 %, FlopsRate: 1.765 %
                     functional_1/s2_b2_sc/BiasAdd      [Convolution] run 10 average cost 0.036200 ms, 0.826 %, FlopsRate: 3.530 %
                     functional_1/s1_b1_sc/BiasAdd      [Convolution] run 10 average cost 0.036600 ms, 0.835 %, FlopsRate: 1.324 %
                 functional_1/k1_s2_conv2d/BiasAdd      [Convolution] run 10 average cost 0.039000 ms, 0.890 %, FlopsRate: 3.530 %
                     functional_1/s1_b2_sc/BiasAdd      [Convolution] run 10 average cost 0.039300 ms, 0.897 %, FlopsRate: 3.530 %
  functional_1/s2_b6_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.039800 ms, 0.908 %, FlopsRate: 0.248 %
                     functional_1/s1_b4_sc/BiasAdd      [Convolution] run 10 average cost 0.040000 ms, 0.913 %, FlopsRate: 3.530 %
  functional_1/s1_b6_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.040200 ms, 0.917 %, FlopsRate: 0.248 %
                     functional_1/s2_b4_sc/BiasAdd      [Convolution] run 10 average cost 0.040600 ms, 0.926 %, FlopsRate: 3.530 %
                 functional_1/k1_s1_conv2d/BiasAdd      [Convolution] run 10 average cost 0.043300 ms, 0.988 %, FlopsRate: 3.530 %
              functional_1/s1_b7_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.046300 ms, 1.056 %, FlopsRate: 0.053 %
                   functional_1/s1_b3_pool/MaxPool      [Pooling] run 10 average cost 0.046400 ms, 1.059 %, FlopsRate: 0.210 %
                     functional_1/s1_b6_sc/BiasAdd      [Convolution] run 10 average cost 0.048600 ms, 1.109 %, FlopsRate: 3.530 %
  functional_1/s1_b4_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.048900 ms, 1.116 %, FlopsRate: 0.496 %
              functional_1/s1_b6_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.049100 ms, 1.120 %, FlopsRate: 0.053 %
                     functional_1/s2_b6_sc/BiasAdd      [Convolution] run 10 average cost 0.049300 ms, 1.125 %, FlopsRate: 3.530 %
                     functional_1/s2_b3_sc/BiasAdd      [Convolution] run 10 average cost 0.053400 ms, 1.218 %, FlopsRate: 7.061 %
  functional_1/s2_b4_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.053800 ms, 1.228 %, FlopsRate: 0.496 %
                     functional_1/s1_b3_sc/BiasAdd      [Convolution] run 10 average cost 0.057200 ms, 1.305 %, FlopsRate: 7.061 %
                   functional_1/s2_b3_pool/AvgPool      [Pooling] run 10 average cost 0.057400 ms, 1.310 %, FlopsRate: 0.210 %
                 functional_1/k3_s1_conv2d/BiasAdd      [Convolution] run 10 average cost 0.058100 ms, 1.326 %, FlopsRate: 3.530 %
                 functional_1/k3_s2_conv2d/BiasAdd      [Convolution] run 10 average cost 0.060000 ms, 1.369 %, FlopsRate: 3.530 %
                                    Convolution512      [Convolution] run 10 average cost 0.066700 ms, 1.522 %, FlopsRate: 0.165 %
                     functional_1/s1_b5_sc/BiasAdd      [Convolution] run 10 average cost 0.067200 ms, 1.533 %, FlopsRate: 7.061 %
                                    Convolution609      [Convolution] run 10 average cost 0.067300 ms, 1.536 %, FlopsRate: 0.165 %
                     functional_1/s2_b5_sc/BiasAdd      [Convolution] run 10 average cost 0.069400 ms, 1.583 %, FlopsRate: 7.061 %
  functional_1/s2_b7_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.072900 ms, 1.663 %, FlopsRate: 0.496 %
                                     Convolution39      [Convolution] run 10 average cost 0.074200 ms, 1.693 %, FlopsRate: 0.248 %
  functional_1/s1_b7_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.075100 ms, 1.714 %, FlopsRate: 0.496 %
                     functional_1/s1_b7_sc/BiasAdd      [Convolution] run 10 average cost 0.082600 ms, 1.885 %, FlopsRate: 7.061 %
              functional_1/s1_b4_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.085900 ms, 1.960 %, FlopsRate: 0.105 %
              functional_1/s1_b5_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.086400 ms, 1.971 %, FlopsRate: 0.105 %
                     functional_1/s2_b7_sc/BiasAdd      [Convolution] run 10 average cost 0.087300 ms, 1.992 %, FlopsRate: 7.061 %
           functional_1/k1_s1_conv2d/Tanh_raster_0      [UnaryOp] run 10 average cost 0.089400 ms, 2.040 %, FlopsRate: 0.105 %
functional_1/s1_b1_sc/separable_conv2d/depthwise_raster_0       [Raster] run 10 average cost 0.095900 ms, 2.188 %, FlopsRate: 0.105 %
  functional_1/s2_b5_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.098300 ms, 2.243 %, FlopsRate: 0.993 %
  functional_1/s1_b5_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.108400 ms, 2.473 %, FlopsRate: 0.993 %
                   functional_1/s1_b1_pool/MaxPool      [Pooling] run 10 average cost 0.155600 ms, 3.550 %, FlopsRate: 0.421 %
  functional_1/s1_b2_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.160300 ms, 3.658 %, FlopsRate: 0.993 %
              functional_1/s1_b3_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.167300 ms, 3.817 %, FlopsRate: 0.210 %
  functional_1/s2_b3_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.168200 ms, 3.838 %, FlopsRate: 1.986 %
              functional_1/s1_b2_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.173700 ms, 3.963 %, FlopsRate: 0.210 %
  functional_1/s1_b3_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.176700 ms, 4.032 %, FlopsRate: 1.986 %
  functional_1/s2_b2_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.181000 ms, 4.130 %, FlopsRate: 0.993 %
                   functional_1/s2_b1_pool/AvgPool      [Pooling] run 10 average cost 0.260900 ms, 5.953 %, FlopsRate: 0.421 %
              functional_1/s1_b1_act/Tanh_raster_0      [UnaryOp] run 10 average cost 0.322000 ms, 7.347 %, FlopsRate: 0.421 %
  functional_1/s2_b1_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.507200 ms, 11.573 %, FlopsRate: 0.745 %
  functional_1/s1_b1_sc/separable_conv2d/depthwise      [ConvolutionDepthwise] run 10 average cost 0.583900 ms, 13.323 %, FlopsRate: 0.745 %
Avg= 4.382700 ms, OpSum = 5.897300 ms min= 2.797000 ms, max= 6.727000 ms

如何确定是哪个op在opencl中不支持，并且在MNN-2.5版本中测试结果一样。

**Comment by jxt1234** [comment]
最新版本中是否正常?

**Comment by jxt1234** [comment]
相关模型可以上传一下?
