### ISSUE TITLE
MNN推理多次调用获取到的结果不是最新结果。

### ISSUE THREAD

**Issue by ZyElite** [alibaba/MNN#2394]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android 13

# Github版本:
# Github Version:
v2.5.0
https://github.com/alibaba/MNN/releases/download/2.5.0/mnn_2.5.0_android_armv7_armv8_cpu_opencl_vulkan.zip

部分代码 :

初始化：

    const char *class_names[2] = {
            "mouse", "mouse"
    };

    mnn_interpreter = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_path));
    if (nullptr == mnn_interpreter) {
        return 0;
    }

    MNN::ScheduleConfig config;
    config.numThread = num_threads;
    MNN::BackendConfig backendConfig;
    backendConfig.precision = MNN::BackendConfig::Precision_High; 
    config.backendConfig = &backendConfig;
    mnn_session = mnn_interpreter->createSession(config);
    input_tensor = mnn_interpreter->getSessionInput(mnn_session, nullptr);
    input_batch = input_tensor->batch();
    input_channel = input_tensor->channel();
    input_height = input_tensor->height();
    input_width = input_tensor->width();
    dimension_type = input_tensor->getDimensionType();

    if (dimension_type == MNN::Tensor::CAFFE) {
        mnn_interpreter->resizeTensor(input_tensor, {input_batch, input_channel, input_height, input_width});
        mnn_interpreter->resizeSession(mnn_session);
    } else if (dimension_type == MNN::Tensor::TENSORFLOW) {
        mnn_interpreter->resizeTensor(input_tensor, {input_batch, input_height, input_width, input_channel});
        mnn_interpreter->resizeSession(mnn_session);
    } else if (dimension_type == MNN::Tensor::CAFFE_C4) {
        // NC4HW4

    }

    std::map<std::string, MNN::Tensor *> sessionOutputAll = mnn_interpreter->getSessionOutputAll(mnn_session);
    num_outputs = sessionOutputAll.size();

    LOG(ERROR) << "num_outputs:" << num_outputs;

    auto tmp_output_map = sessionOutputAll;
    for (const auto &it: tmp_output_map) {
        LOG(ERROR) << "Output: " << it.first << ": ";
        it.second->printShape();
    }

    pretreat = std::shared_ptr<MNN::CV::ImageProcess>(
            MNN::CV::ImageProcess::create(MNN::CV::RGB, MNN::CV::RGB, mean_vals, 3, norm_vals, 3)
    );

推理：
    auto output_tensors = mnn_interpreter->getSessionOutputAll(mnn_session);
    mnn_interpreter->runSession(mnn_session);

    ......

    auto device_pred_ptr = output_tensors.at("output0");
    MNN::Tensor host_pred_tensor(device_pred_ptr, device_pred_ptr->getDimensionType()); // NCHW
    device_pred_ptr->copyToHostTensor(&host_pred_tensor);

    auto pred_dims = host_pred_tensor.shape();
    const unsigned int num_anchors = pred_dims.at(1); 
    const unsigned int num_classes = pred_dims.at(2) - 5; 

    float r_ = scale_params.r;
    int dw_ = scale_params.dw;
    int dh_ = scale_params.dh;

    bbox_collection.clear();
    unsigned int count = 0;
    for (unsigned int i = 0; i < num_anchors; ++i) {
        const float *offset_obj_cls_ptr = host_pred_tensor.host<float>() + (i * (num_classes + 5)); 
         float obj_conf = offset_obj_cls_ptr[4];
        if (obj_conf < score_threshold) continue;
        ....
    }

模型：

 https://www.aliyundrive.com/s/wUfKnbb4Anj
 71co

问题：
多次推理，获取到的结果为上一次。

**Comment by jxt1234** [comment]
多次推理的完整代码补充一下吧，用省略号难以保证是一样的
