### ISSUE TITLE
Cmake时-DMNN_BUILD_QUANTOOLS的影响

### ISSUE THREAD

**Issue by yingfenging** [alibaba/MNN#2396]
你好，采用MNNConvert对onnx模型转换时增加--fp16选项，在android arm64-v8a平台上，进行推理。在生成libMNN.so时，采用如下两种方法
方法1：cmake增加-DMNN_BUILD_QUANTOOLS=ON
方法2：cmake增加-DMNN_BUILD_QUANTOOLS=OFF

上述两种不同的产生libMNN.so的方法，会对推理速度产生影响吗？谢谢

**Comment by jxt1234** [comment]
不会影响。-DMNN_BUILD_QUANTOOLS=ON 是开启 离线量化工具 的编译，不影响 libMNN.so 的编译结果
