### ISSUE TITLE
How to Create a tensor from a buffer ? 

### ISSUE THREAD

**Issue by WenguoLi** [alibaba/MNN#240]
I want to create tensor from a buffer, How to do ?

Thanks !

**Comment by li-qing** [comment]
`
static Tensor* create(const std::vector<int>& shape, halide_type_t type, void* data = NULL,
                          DimensionType dimType = TENSORFLOW);

template <typename T>
static Tensor* create(const std::vector<int>& shape, void* data = NULL, DimensionType dimType = TENSORFLOW)
`
create methods with data param are provided.
