### ISSUE TITLE
These Op Not Support: ONNX::LayerNormalization

### ISSUE THREAD

**Issue by xxaier** [alibaba/MNN#2400]
我已经把 https://huggingface.co/BAAI/AltCLIP-m18 转为了onnx
我尝试吧 onnx转为mnn的时候报错
These Op Not Support: ONNX::LayerNormalization

**Comment by jxt1234** [comment]
onnx 模型上传一下吧（不要用百度网盘）

**Comment by jxt1234** [comment]
LayerNormalization 是比较新的 onnx op ，如果想绕过去也可以在 导出 onnx 时把 opset 版本降低试试下

**Comment by jxt1234** [comment]
2.6.2 新增支持

**Comment by xxaier** [comment]
https://huggingface.co/xxai-art/tar/tree/main
模型在这里，我回头再测试下
<img width="533" alt="image" src="https://github.com/alibaba/MNN/assets/130831741/0b2ba799-28d5-4850-acef-57571c852f43">
