### ISSUE TITLE
python API: Reshape error  Can't run session because not resized

### ISSUE THREAD

**Issue by Lddyy** [alibaba/MNN#2401]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 20.04.6 LTS（WSL2）

# Github版本:
# Github Version:
git clone 
commit id：ffb93cf80195f7cbcb7d6c6c50db18fd8e8271e6

# 编译方式:
# Compiling Method
```
./schema/generate.sh 
mkdir build 
cd build 
cmake .. -DMNN_BUILD_CONVERTER=true 
make -j8
```
# pytorch -> onnx
尝试了动态输入和非动态输入，onnx推理都没问题。
onnx推理代码：

```
import onnxruntime
import numpy as np
onnx_file_name = "PITS_7000_dynamic.onnx"
ort_session = onnxruntime.InferenceSession(onnx_file_name)  
pinyi = np.zeros((1,153), dtype=np.int64)
speakerid = np.zeros((1, ), dtype=np.int64)
ort_inputs = {ort_session.get_inputs()[0].name:pinyi,
              ort_session.get_inputs()[1].name:speakerid}
ort_output = ort_session.run(None, ort_inputs)[0]
```

# onnx-> mnn：./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz
动态输入下：testMNNFromOnnx.py无错误输出，Converted Success
非动态输入下：testMNNFromOnnx.py输出
```
Reshape error: 30048 -> 60096
2078 op name is empty or dup
set to BinaryOp2078
Converted Success
```
#  mnn python api 推理
python api version:2.5.1
推理代码：
```
sess = MNN.nn.load_module_from_file(MODEL_PATH, ["text", "speakerid"], ["modelOutput"], shape_mutable=True)
def _run(feats_length):
    v0 = np.zeros((1, feats_length), dtype=np.int32)
    v1 = np.zeros((1, ), dtype=np.int32)
    output = sess.forward([v0, v1])
    print(output)
_run(100)
_run(200)
```
动态输入下输出：
Reshape error: 19200 -> 1164096
Compute Shape Error for Reshape124
Can't run session because not resized
非动态输入下输出：
Broad cast error, dim1 = 157, dim2 = 100
Compute Shape Error for input
Can't run session because not resized
#  onnx model
[PITS_dynamic.onnx](https://drive.google.com/file/d/1w7xY5BgJb2W6ImFFJ1hHXV8QCsy1jQp3/view?usp=sharing)
[PITS_nodynamic.onnx](https://drive.google.com/file/d/1er5wXWAn2Vom0jGHkQoeggr9Fees1ouq/view?usp=sharing)

**Comment by jxt1234** [comment]
einsum 部分情况下转换的问题，修正中

**Comment by GuangyanZhang** [comment]
> 

请问修复好了吗，我也出现了Can't run session because not resized的问题

**Comment by jxt1234** [comment]
einsum 修正了，但这个模型里面有 random 算子，无法验证整体正确性，后续有问题重新提 issue 吧

**Comment by zll0000** [comment]
> einsum 修正了，但这个模型里面有 random 算子，无法验证整体正确性，后续有问题重新提 issue 吧

### First Error Node is :  Einsum_193  遇到同样einsum问题请问怎么修复的
