### ISSUE TITLE
Pytorch预训练模型的参数迁移问题

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2402]
我想把Pytorch上预训练好的模型参数拷贝到MNN上做fine-tuning，但是因为研究需要，我要把参数拷贝到我所指定的Module上，比如说一个pytorch卷积层的参数拷贝到mnn的一个卷积层里面（尺寸是一致的），请问这是可行的吗？
非常感谢！

**Comment by jxt1234** [comment]
建议导出 onnx 时把卷积层的权重部分设成输入，然后用输入方式传入就好了

**Comment by wangzhaode** [comment]
建议还是通过导出到onnx然后再转换到MNN比较好 实现起来最简单
