### ISSUE TITLE
android 平台无法调用opencl 和 vulkan，Can't Find type=3 backend, use 0 instead

### ISSUE THREAD

**Issue by zhanghongwei** [alibaba/MNN#2403]
cmakelist里面设置MNN_OPENGL 为ON
1. MNN_USE_SYSTEM_LIB 为ON
    Can't Find type=3 backend, use 0 instead
2.  MNN_USE_SYSTEM_LIB 为OFF, 在OpenCLWrapper.cpp 加入了手机端libOpenCL.so的路径
   还是Can't Find type=3 backend, use 0 instead
请教如何定位问题阿？   BackendRegister.cpp函数中为何没有registerOPENCLRuntimeCreator？

//
//  BackendRegister.cpp
//  MNN
//
//  Created by MNN on 2019/05/08.
//  Copyright © 2018, Alibaba Group Holding Limited
//

#include <mutex>
#include "geometry/GeometryComputer.hpp"
#include "shape/SizeComputer.hpp"
#include "Macro.h"
#ifdef MNN_INTERNAL_ENABLED
#include "internal/logging/Log.hpp"
#endif
namespace MNN {
extern void registerCPURuntimeCreator();

#if MNN_METAL_ENABLED
extern void registerMetalRuntimeCreator();
#endif
#if MNN_COREML_ENABLED
extern void registerCoreMLRuntimeCreator();
#endif
#if MNN_NNAPI_ENABLED
extern void registerNNAPIRuntimeCreator();
#endif

static std::once_flag s_flag;
void registerBackend() {
    std::call_once(s_flag, [&]() {
#ifdef MNN_INTERNAL_ENABLED
        LogInit();
#endif
        registerCPURuntimeCreator();
#ifndef MNN_BUILD_MINI
        SizeComputerSuite::init();
        GeometryComputer::init();
#endif
#if MNN_COREML_ENABLED
        registerCoreMLRuntimeCreator();
#endif
#ifdef MNN_NNAPI_ENABLED
        registerNNAPIRuntimeCreator();
#endif
#if MNN_METAL_ENABLED
        registerMetalRuntimeCreator();
#endif
    });
MNN_PRINT("register Backend done!!!!!!\n");
}
} // namespace MNN

**Comment by jxt1234** [comment]
用 project/android/ 下面的 build_64.sh  -DMNN_OPENCL=ON 等方式编译，这个是需要 link libMNN_OpenCL.so 或者手动dlopen 的。参考 https://mnn-docs.readthedocs.io/en/latest/faq.html#gpu

**Comment by zhanghongwei** [comment]
多谢回复， 我实验了上述解决方案，还是报错：Can't Find type=3 backend, use 0 instead ，                                                       1）在mnn初始化之前，手动dlopen了opencl库（修复了报错）返回值正常， handle = dlopen("libMNN_CL.so", RTLD_NOW);
        if (handle == nullptr)
        {
            ALOGE("MNN Model: dlopen libMNN_CL failed!!!!!!\n");
            ALOGE("dlopen - %sn", dlerror());
        }
2） 我使用的libmnn.a，编译的时候打开了MNN_OPENCL为ON
