### ISSUE TITLE
使用MNN::Express::Module如何设置单线程运行

### ISSUE THREAD

**Issue by yingfenging** [alibaba/MNN#2405]
你好，使用MNN::Express::Module进行模型推理，如何设置单线程运行？谢谢

**Comment by jxt1234** [comment]
参考 tools/cpp/ModuleBasic.cpp 里面numThread 的设置（numThread 与 mode 等价）

**Comment by jxt1234** [comment]
另外，默认的情况下是单线程运行的

**Comment by yingfenging** [comment]
> 参考 tools/cpp/ModuleBasic.cpp 里面numThread 的设置（numThread 与 mode 等价）

多谢。参考你说的方法进行设置，设置numThead=4，根据测试结果，还是单线程运行，没起作用。在linux上和Android手机上都是同样的测试结论。请问是咋回事呢？谢谢

**Comment by jxt1234** [comment]
先用 ModuleBasic 测试工具跑多线程测试，这个一般是使用的问题，重新提 issue 附上你的使用代码
