### ISSUE TITLE
MNN interpreter createSession and runSession的时候出错

### ISSUE THREAD

**Issue by junqiangchen** [alibaba/MNN#2406]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

gcc version 11.2.0 (Rev7, Built by MSYS2 project)

# Github版本:
# Github Version:
v2.5.0
https://github.com/alibaba/MNN/releases/tag/2.5.0

部分代码：
初始化：
` std::cout<<"step1"<<std::endl;
    this->_interpreter.reset(MNN::Interpreter::createFromFile(mdlfile.c_str()));
    if (this->_interpreter == nullptr) {
        std::cout << "Invalid input Model" << std::endl;
    }

    MNN::ScheduleConfig config;
    config.numThread = num_thread;
    config.type = MNN_FORWARD_CPU;
    MNN::BackendConfig backendConfig;
    backendConfig.precision = (MNN::BackendConfig::PrecisionMode) 0;
    config.backendConfig = &backendConfig;
    std::cout<<"step2"<<std::endl;
    this->_session = this->_interpreter->createSession(config);
    std::cout<<"step3"<<std::endl;
    this->_input_tensor = this->_interpreter->getSessionInput(this->_session, nullptr);`

输出结果：
`step1

step2

Signal: SIGSEGV (Segmentation fault)`

问题：
再步骤2和步骤3之间的createSession的时候出现了问题。

请问这个有什么解决方法么？

**Comment by jxt1234** [comment]
参考 demo/exec/transformerDemo.cpp ，用 Module 加载测试看看。原因参考：
https://mnn-docs.readthedocs.io/en/latest/faq.html#mnnv2basic

**Comment by junqiangchen** [comment]
@jxt1234  我尝试用了Module方法去加载模型进行推理，但是还是存在这个问题，示例代码如下：

cv::Mat input_image = cv::imread("D:/zjj3316200 1.jpg");
    cv::Mat img_gray;
    if (input_image.channels() == 3)
        cv::cvtColor(input_image, img_gray, cv::COLOR_BGR2GRAY);
    else
        img_gray = input_image.clone();
    //resize image
    cv::Mat resizeimage;
    int in_w = 512;
    int in_h = 512;
    cv::resize(img_gray, resizeimage, cv::Size(in_w, in_h));
    cv::Mat meanimage, stdimage;
    cv::meanStdDev(resizeimage, meanimage, stdimage);
    double meanvalue = meanimage.at<double>(0, 0);
    double stdvalue = stdimage.at<double>(0, 0);
    if (stdvalue == 0) {
        std::cout << "input_image is empty ,please check!" << std::endl;
    }
    cv::Mat floatresizeimage;
    resizeimage.convertTo(floatresizeimage, CV_32FC1);
    floatresizeimage = (floatresizeimage - meanvalue) / stdvalue;

    MNN::BackendConfig config;
    auto modelName = "D:/corsegvnet2d.mnn";
    std::shared_ptr<MNN::Express::Module> model;
    MNN::Express::Module::Config mdconfig;
    mdconfig.rearrange = true;
    std::cout<<"step1"<<std::endl;
    model.reset(MNN::Express::Module::load({ "input" }, { "output0", "output1" }, modelName, &mdconfig));
    std::cout<<"step2"<<std::endl;
    auto first = MNN::Express::_Input({ 1,1,512,512 }, MNN::Express::NCHW, halide_type_of<float>());
    std::memcpy(first->writeMap<float>(), floatresizeimage.data, in_w * in_h * sizeof(float));

    std::vector<MNN::Express::VARP> outputs = model->onForward({ first });
    auto info = outputs[1]->getInfo();
    std::ostringstream dimInfo;
    for (int d = 0; d < info->dim.size(); ++d) {
        dimInfo << info->dim[d] << "_";
    }
    auto ptr = outputs[1]->readMap<float>();
    std::memcpy(floatresizeimage.data, ptr, in_w * in_h * sizeof(float));

    int height = img_gray.rows;
    int width = img_gray.cols;
    cv::Size dsize = cv::Size(width, height);
    cv::resize(floatresizeimage, floatresizeimage, dsize, 0, 0, cv::INTER_NEAREST);
    cv::Mat _output_mask;
    floatresizeimage.convertTo(_output_mask, CV_8UC1);
    cv::imwrite("cornelexpre.bmp", _output_mask);

在model.reset(MNN::Express::Module::load({ "input" }, { "output0", "output1" }, modelName, &mdconfig))运行时出现
Signal: SIGSEGV (Segmentation fault)

上述程序在vs2019的编译环境下都是可以正常运行计算结果的。

**Comment by junqiangchen** [comment]
我发现原因了，还是在模型从onnx转成mnn的时候出了问题，还是要用MNN框架下自带的脚本testMNNFromOnnx.py去转换模型，可以在GCC编译器下运行

onnx\test.onnx
tensor(float)
['output0', 'output1']
inputs:
input
onnx/
outputs:
onnx/output0.txt (1, 1, 512, 512)
onnx/
onnx/output1.txt (1, 1, 512, 512)
onnx/
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[13:39:08] @ 98: ONNX Model ir version: 7
[13:39:08] @ 99: ONNX Model opset version: 14
Start to Optimize the MNN Net...
inputTensors : [ input, ]
outputTensors: [ output0, output1, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
