### ISSUE TITLE
量化json配置

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2407]
Hi:

      请问模型输入是4维数组，想对模型进行量化的话，preprocessConfig.json 怎么配置呢？看到format只能选"RGB", "BGR", "RGBA", "GRAY"

谢谢

**Comment by jxt1234** [comment]
4维数组具体的大小是？如果非图像类的输入，参考 https://mnn-docs.readthedocs.io/en/latest/tools/compress.html 量化

**Comment by keke444** [comment]
> 4维数组具体的大小是？如果非图像类的输入，参考 https://mnn-docs.readthedocs.io/en/latest/tools/compress.html 量化
就是非图像类的输入，找到了，谢谢
