### ISSUE TITLE
如果输入图像大小为320*320

### ISSUE THREAD

**Issue by dingzhuoyue** [alibaba/MNN#2408]
int num_classes=80;       // 模型推理类别数
std::vector<YoloLayerData> yolov5s_layers{
        {"482",    32, {{116, 90}, {156, 198}, {373, 326}}},  // 第一层的输出
        {"416",    16, {{30,  61}, {62,  45},  {59,  119}}},  // 第二层的输出
        {"output", 8,  {{10,  13}, {16,  30},  {33,  23}}},   // 第三层的输出
};
这里如何修改？

**Comment by jxt1234** [comment]
参考 https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id16 ，改输入大小 (resizeTensor) -> resizeSession
