### ISSUE TITLE
YOLOx 单输入模型离线量化int8 C++推理，MNN::CPUBinaryInt8::onResize 报错Segmentation fault

### ISSUE THREAD

**Issue by zxdask67u2** [alibaba/MNN#2409]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86_64 ubuntu20.04

# Github版本:

2.5.1

过程：

YOLOx  -> onnx -> mnn fp16 -> mnn int8 

int8过程正常：
![图片](https://github.com/alibaba/MNN/assets/33893813/574d64fa-e0a8-4312-a9db-38f8d4184db2)

推理代码：在createSession函数就报错了
![图片](https://github.com/alibaba/MNN/assets/33893813/f70f7ac6-a77b-4d4a-bc52-4d46e3eea265)

**Comment by jxt1234** [comment]
已经复现问题，修正中

**Comment by jxt1234** [comment]
已经修正，如有新的问题重新提下 issue

**Comment by happyday-lkj** [comment]
> 已经修正，如有新的问题重新提下 issue

使用离线量化工具转int8模型成功，模型加载也成功，但是在创建session时，报错 Segmentation fault。
![image](https://github.com/alibaba/MNN/assets/18274241/c89244e7-ac38-4fc3-a574-d0b4b34ec295)
