### ISSUE TITLE
caffe模型转化问题

### ISSUE THREAD

**Issue by zeyuanlicbpm** [alibaba/MNN#241]
get_model.sh中有一个模型的转化出现问题：
get_caffe1 \
  "https://raw.githubusercontent.com/shicai/MobileNet-Caffe/master/mobilenet.caffemodel" \
  "build/mobilenet_v1.caffe.caffemodel" \
  "https://raw.githubusercontent.com/shicai/MobileNet-Caffe/master/mobilenet_deploy.prototxt" \
  "build/mobilenet_v1.caffe.prototxt" \
  "MobileNet V1" \
  "model/MobileNet/v1/mobilenet_v1.caffe.mnn"

具体报错信息：MNN-master/tools/converter/source/caffe/caffeConverter.cpp:52: Check failed: succ ==>read_proto_from_binary failed
可能是什么原因呢？

**Comment by czy2014hust** [comment]
read_proto_from_binary failed! 这个脚本需要联网下载模型，这是模型没有下载下来。

**Comment by crystaldan** [comment]
Hi,how did you resolve this problem? I meet the same error

**Comment by thelou1s** [comment]
demo能直接提供mobilenet_v1.caffe.mnn吗
