### ISSUE TITLE
opencl 优化后的算子问题

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2414]
hi :

        在打开 opencl ENABLE_PROFILE 的宏看 gpu 时间，发现原模型的卷积算子（如下），
有的还是Conv2D，有的却成了ConvWino，请问在什么条件下，
卷积会使用Winograd 进行优化？

kernel cost:4280    us      Conv2D							
kernel cost:6328    us      Conv2D				
kernel cost:1198    us      ConvWino0
kernel cost:26100    us    ConvWino1
kernel cost:3877    us     ConvWino2
kernel cost:31175    us   ConvWino total

谢谢

**Comment by wangzhaode** [comment]
在`ConvWinograd.cpp`中有一个`ConvWinograd::valid`函数是用来判断是否使用Winograd的
