### ISSUE TITLE
GCC编译器下MNN不支持GroupNorm层

### ISSUE THREAD

**Issue by junqiangchen** [alibaba/MNN#2418]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
gcc version 11.2.0 (Rev7, Built by MSYS2 project)

# Github版本:
# Github Version:
v2.5.0
https://github.com/alibaba/MNN/releases/tag/2.5.0

```
我发现GCC编译器版本下，MNN对pytorch的nn.GroupNorm不支持么？
```

**Comment by wangzhaode** [comment]
支持 跟GCC无关 请把你遇到的具体问题发出来
