### ISSUE TITLE
多线程runSession的问题

### ISSUE THREAD

**Issue by Lingfeng-Sun** [alibaba/MNN#2419]
看了这个帖子(https://github.com/alibaba/MNN/issues/2364)， 想确认一下关于多线程的一些问题

1. 如果有多个session，希望在多个线程跑，可以直接调用 session->run() 对吗，会不会有其他冲突？ 这种方法和基于Module API相比有什么明确优劣吗
2.   session->run() 会阻塞调用吗，还是立即就能返回
3.  如果是非阻塞式的，同一个session连续调用多次run会出错吗，底层有没有容错处理，还是需要自己保证？

**Comment by wangzhaode** [comment]
1. 多线程可以，有加锁；
2. CPU会阻塞；OpenCL不会；
3. 非阻塞的会在请求读取数据时阻塞；
