### ISSUE TITLE
问一个简单的问题，MNN的OpenCL kernel backend是打包到MNN库里的，还是用手机提供的libOpenCL.so的？

### ISSUE THREAD

**Issue by ldfandian** [alibaba/MNN#2422]
Android 7.0+后很多手机的libOpenCL.so就不能用了，没有被标记成公开库，之前试过好几款手机都这样。
我们有一个不小的类ResNet50模型想在手机上跑，希望用到GPU加速，所以过来问一个简单的问题，MNN的OpenCL kernel backend是打包到MNN库里的，还是用手机提供的libOpenCL.so的？

**Comment by wangzhaode** [comment]
MNN OpenCL是使用系统提供的动态库；详情参考：`source/backend/opencl/core/runtime/OpenCLWrapper.cpp`

**Comment by ldfandian** [comment]
> MNN OpenCL是使用系统提供的动态库；详情参考：`source/backend/opencl/core/runtime/OpenCLWrapper.cpp`

感谢，那如果手机的libOpenCL.so没有被标记成公开库（试过好几款Honor/Oppo/Xiaomi机器都是），就只能用vulkan了吧？

**Comment by shaoguanglin** [comment]
可以在manifest 设置<uses-native-library
            android:name="libOpenCL.so"
            android:required="true"/>

**Comment by shaoguanglin** [comment]
> > MNN OpenCL是使用系统提供的动态库；详情参考：`source/backend/opencl/core/runtime/OpenCLWrapper.cpp`
> 
> 感谢，那如果手机的libOpenCL.so没有被标记成公开库（试过好几款Honor/Oppo/Xiaomi机器都是），就只能用vulkan了吧？

可以设置manifest  <uses-native-library  android: name="libOpenCL.so" android: required="true"/>

**Comment by ldfandian** [comment]
> > > MNN OpenCL是使用系统提供的动态库；详情参考：`source/backend/opencl/core/runtime/OpenCLWrapper.cpp`
> > 
> > 
> > 感谢，那如果手机的libOpenCL.so没有被标记成公开库（试过好几款Honor/Oppo/Xiaomi机器都是），就只能用vulkan了吧？
> 
> 可以设置manifest

use-native-library / use-library ? 不行啊，设置这个的前提是，手机厂商标记为公开可使用库（public.libraries.txt）啊

**Comment by shaoguanglin** [comment]
我测试了小米se8 honorv20还有三星s10 华为mate30pro 都可以诶 android: name="libOpenCL.so"

**Comment by ldfandian** [comment]
> 我测试了小米se8 honorv20还有三星s10 华为mate30pro 都可以诶 android: name="libOpenCL.so"

和机型相关。。。吧

**Comment by chenghuaWang** [comment]
> MNN OpenCL是使用系统提供的动态库；详情参考：`source/backend/opencl/core/runtime/OpenCLWrapper.cpp`

@wangzhaode 我看这里是用dlopen的方法来online加载symbols。但是在OpenCLRuntime.cpp里面使用的cl2.hpp是直接使用opencl函数的，也就说还是需要在编译的时候链接opencl lib？

**Comment by Juude** [comment]
opencl 运行时用的是系统的
