### ISSUE TITLE
Android手机上跑推理模型，NNAPI/Vulkan/OpenCL 这三个backend应该怎么选？

### ISSUE THREAD

**Issue by ldfandian** [alibaba/MNN#2423]
分别有什么优势呢？

**Comment by wangzhaode** [comment]
1. GPU的话可以用OpenCL; Vulkan的实现完整度不如OpenCL；
2. NNAPI是可以调用DSP或者其他加速硬件的，具体与设备有关；

**Comment by ldfandian** [comment]
> * GPU的话可以用OpenCL; Vulkan的实现完整度不如OpenCL；
> * NNAPI是可以调用DSP或者其他加速硬件的，具体与设备有关；

谢谢超快的回复~

OpenCL的坑在于，Android 7.0+后很多手机的libOpenCL.so就不能用了，没有被标记成公开库，之前试过好几款手机都这样。
如果考虑兼容性，可能还是Vulkan强不少吧？

另外，请问一下，"Vulkan的实现完整度不如OpenCL"，是从MNN的角度，还是从Vulkan本身来说的？MNN的角度来看，OpenCL和Vulkan两种kernel的成熟度好不？
