### ISSUE TITLE
MNN支持similarTransform？

### ISSUE THREAD

**Issue by Reversev** [alibaba/MNN#2425]
MNN支持五个关键点的人脸对齐操作吗？只能用opencv实现这一操作？

**Comment by jxt1234** [comment]
五个关键点的人脸对齐操作是一个算法，一般是用模型+推理引擎实现，MNN 是推理引擎。如果有对应 人脸对齐操作 模型，可以转换到 MNN 格式进行推理，从而实现这个操作。

**Comment by Reversev** [comment]
我只是想用MNN做图像处理中简单的关键点匹配对人脸进行对齐（opencv可以实现），并不把它作为一个推理引擎。我看了文档上并没有提供这种方法，应该是不支持？还是我看漏了？

**Comment by jxt1234** [comment]
不支持的

**Comment by Reversev** [comment]
好的，谢谢
