### ISSUE TITLE
Session问题

### ISSUE THREAD

**Issue by haiyang1981** [alibaba/MNN#243]
请问，我在程序里做编码如下

MNN::Session *session_gen1;

则session_gen1的buffer是否需要手动删除，谢谢

**Comment by li-qing** [comment]
“
函数返回的Session实例是由Interpreter管理，务必在不再需要时，调用Interpreter::releaseSession释放，以免造成内存泄露。
”
详见文档：https://www.yuque.com/mnn/cn/create_session
