### ISSUE TITLE
Wrong conversion from onnx split to nnapi slice

### ISSUE THREAD

**Issue by dccho** [alibaba/MNN#2430]
https://github.com/alibaba/MNN/blob/18ba09e1e9d32088e3a418d3a1339f1acf3b43eb/tools/converter/source/onnx/SplitOnnx.cpp#L19
https://github.com/alibaba/MNN/blob/18ba09e1e9d32088e3a418d3a1339f1acf3b43eb/source/backend/nnapi/execution/NNAPIRaster.cpp#L74

When onnx model is converted to mnn, onnx split is converted to mnn slice which is fine. Both case, one input tensor splits to two output tensors. However, when nnapi is used for backend, mnn slice is converted to nnapi slice which converts one input tensor to one output tensor. mnn slice should be converted to either nnapi slice or nnapi split depending upon output size.

**Comment by jxt1234** [comment]
Does it cause compute error?
After Geometry Compute to NNAPI Backend, the origin split op has been converted to two slice op, the logic is right.
