### ISSUE TITLE
在没有numpy库的情况下，MNN本身的numpy和expr能直接调用吗？

### ISSUE THREAD

**Issue by jeremyjyxie** [alibaba/MNN#2431]
# 问题
  
在没有numpy库的情况下，调用MNN本身的numpy和expr导致kernel直接挂掉，请问如何解决

**Comment by jxt1234** [comment]
MNN本身的numpy和expr 不依赖 numpy 库，挂掉的 crash log 和复现代码发一下?

**Comment by jeremyjyxie** [comment]
> 
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MNN.numpy as np
[Warnning] import numpy failed, please reinstall numpy!
The device support i8sdot:0, support fp16:0, support i8mm: 0
Numpy not found. Using MNN without numpy.
>>> 
>>> np.array([1])
Segmentation fault

麻烦看看，谢谢

**Comment by jeremyjyxie** [comment]
> MNN本身的numpy和expr 不依赖 numpy 库，挂掉的 crash log 和复现代码发一下?



> MNN本身的numpy和expr 不依赖 numpy 库，挂掉的 crash log 和复现代码发一下?

Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import MNN.numpy as np
[Warnning] import numpy failed, please reinstall numpy!
The device support i8sdot:0, support fp16:0, support i8mm: 0
Numpy not found. Using MNN without numpy.
>>> 
>>> np.array([1])
Segmentation fault

麻烦看看，谢谢~

**Comment by jeremyjyxie** [comment]
> MNN本身的numpy和expr 不依赖 numpy 库，挂掉的 crash log 和复现代码发一下?



Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import MNN.numpy as np
[Warnning] import numpy failed, please reinstall numpy!
The device support i8sdot:0, support fp16:0, support i8mm: 0
Numpy not found. Using MNN without numpy.
\>>> 
\>>> np.array([1])
Segmentation fault

**Comment by wangzhaode** [comment]
> Numpy not found. Using MNN without numpy.

如果不想依赖`numpy`可以把`PYMNN_NUMPY_USABLE`设置为`OFF`

**Comment by wangzhaode** [comment]
> > MNN本身的numpy和expr 不依赖 numpy 库，挂掉的 crash log 和复现代码发一下?
> 
> Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) [GCC 9.3.0] on linux Type "help", "copyright", "credits" or "license" for more information. >>> import MNN.numpy as np [Warnning] import numpy failed, please reinstall numpy! The device support i8sdot:0, support fp16:0, support i8mm: 0 Numpy not found. Using MNN without numpy. >>> >>> np.array([1]) Segmentation fault

这个crash是因为 MNN.Var 的 __repr__ 是read成ndarray然后调用ndarray的__repr__；如果没有numpy这里会崩溃掉

**Comment by jeremyjyxie** [comment]
> > Numpy not found. Using MNN without numpy.
> 
> 如果不想依赖`numpy`可以把`PYMNN_NUMPY_USABLE`设置为`OFF`

请问这个是要在编译的时候指定吧？ 使用pip install的话是没办法设定的吧？

**Comment by jxt1234** [comment]
目前是的，后续我们改一下
