### ISSUE TITLE
MNNNetInstance.createSession()创建第二个Session的耗时特别大

### ISSUE THREAD

**Issue by cmelody999** [alibaba/MNN#2436]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

荣耀nova 10手机上测试FORWARD_CPU、FORWARD_OPENCL、FORWARD_VULKAN、FORWARD_NNAPI和FORWARD_AUTO的推理耗时，每个MNNForwardType创建一个Session，第一个Session创建耗时265ms，第二个Session创建耗时特别大，达到52038ms，请问原因是啥，有啥解决办法吗？多谢！
![image](https://github.com/alibaba/MNN/assets/5425469/af592e17-c692-4661-9dfa-37c079491182)

**Comment by jxt1234** [comment]
OpenCL 默认会进行 autotuning ，会有较高耗时，可通过设置 mode 或用 cachefile 优化。
https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id4
