### ISSUE TITLE
WIN11环境下cuda部分编译失败！

### ISSUE THREAD

**Issue by xivisi** [alibaba/MNN#2439]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
WIN11 + VS2022 + CUDA12.1
# Github版本: 2.5.0 - 2.5.3
# 编译方式:
VS2022
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
cmake -G"Visual Studio 17 2022" .. -DMNN_USE_SYSTEM_LIB=ON -DMNN_BUILD_TRAIN=ON -DMNN_BUILD_CONVERTER=ON -DMNN_CUDA=ON -DMNN_WIN_RUNTIME_MT=ON

# 编译日志:

Building NVCC (Device) object source/backend/cuda/CMakeFiles/MNN_CUDA.dir/execution/Debug/MNN_CUDA_generated_ArgMaxExecution.cu.obj
ArgMaxExecution.cu
cl: 鍛戒护琛?warning D9025 :姝ｅ湪閲嶅啓鈥?O2鈥?鐢ㄢ€?Od鈥?
cl: 鍛戒护琛?warning D9025 :姝ｅ湪閲嶅啓鈥?Od鈥?鐢ㄢ€?O2鈥?
cl: 鍛戒护琛?error D8016 :鈥?RTC1鈥濆拰鈥?O2鈥濆懡浠よ閫夐」涓嶅吋瀹?
CMake Error at MNN_CUDA_generated_ArgMaxExecution.cu.obj.Debug.cmake:220 (message):
 Error generating
 E:/Source/MNN/build/source/backend/cuda/CMakeFiles/MNN_CUDA.dir/execution/Debug/MNN_CUDA_generated_ArgMaxExecution.cu.obj

**Comment by whyb** [comment]
WIN10 + VS2019 + CUDA v11.6

遇到一样的问题，只要加上CUDA的backend编译，cmake -DCMAKE_BUILD_TYPE=Release -DMNN_CUDA=ON
就会报下图这样的错：
![圖片](https://github.com/alibaba/MNN/assets/2672931/370e418d-d9ef-4479-afdb-ef7999156fa0)

**Comment by tony2u** [comment]
WIN10 + VS2022 + CUDA v11.8
cmake -DCMAKE_BUILD_TYPE=Debug -DMNN_CUDA=ON
![image](https://github.com/alibaba/MNN/assets/20885359/b363e683-ecd8-416f-9075-e387c849b213)

**Comment by jxt1234** [comment]
编译 cuda 需要指定一些选项，参考 https://mnn-docs.readthedocs.io/en/latest/compile/engine.html#windows
