### ISSUE TITLE
resnet Eltwise层问题，有人用vulkan跑resnet吗？

### ISSUE THREAD

**Issue by xingyanan** [alibaba/MNN#244]
实测同样的resnet模型在用CPU和openCL跑出来的结果是正确的，但是用vulkan跑出来的结果不对。查看Ops支持，发现Eltwise层存在区别：
- CPU: support Product, Sum, Max
-Metal: support Product, Sum, Max
-Vulkan: supports Product, Sum
-OpenCL: supports Product, Sum, Max
  其中CPU和OpenCL相同VULKAN没有MAX计算，但是在我所用模型中Eltwise的参数是SUM，不知为什么结果不对，请问是哪地方出了问题，我看了一下benchmark有测试resnet的，只测试了时间并没用测试结果对不对，求解

**Comment by hacker-joe** [comment]
什么设备？resnet18验证过结果是正确的，你可以用backendTest.out工具测试一下具体哪一层错误？

**Comment by xingyanan** [comment]
A73上测过，krin970上也测过，我看问题应该是处在eltwise层，resnet也没有其他特殊的层了

**Comment by xingyanan** [comment]
测了一下用原始的resnet,CPU和VULKAN结果都是正确的，应该是模型哪里出了问题，谢了@hacker-joe
