### ISSUE TITLE
onnx转mnn成功，但是在python session api调用mnn是输入输出都为空

### ISSUE THREAD

**Issue by Skylarking** [alibaba/MNN#2440]
![image](https://github.com/alibaba/MNN/assets/78296375/e6ee0fe8-88fe-46a7-84c2-f409addcc0a0)

一旦使用copyFrom又会显示malloc(): memory corruption错误，检查了onnx和torch模型的输入输出都是正确的

**Comment by jxt1234** [comment]
先用 testMNNFromOnnx.py 测试

**Comment by jxt1234** [comment]
有可能是你的模型不支持用 session api 运行，换用 module api 吧
