### ISSUE TITLE
nn.Linear通过onnx转换为MNN模型时权重获取问题

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2442]
我将nn.Linear通过导出成onnx并且使用MNNConverter转换成了MNN的算子，但是通过Variable::load()方法返回的算子里面找不到nn.Linear的权重，但是在可视化工具Netron中是看到的。请问在代码中应该如何获取下图中红框的weight和bias，非常感谢！

![issue](https://github.com/alibaba/MNN/assets/19640215/259dcee2-b793-43fe-a7b3-ddda27c4e44b)

**Comment by jxt1234** [comment]
默认结构无法获取。如需要获取得用训练模式加载 mnn 模型。参考 transformerExecution.cpp 里面
    auto turnTrainable = Train::TurnTrainable(trainConfig);
    turnTrainable.onExecute(Variable::mapToSequence(outputVars));

**Comment by fubukishiro** [comment]
> 默认结构无法获取。如需要获取得用训练模式加载 mnn 模型。参考 transformerExecution.cpp 里面
> auto turnTrainable = Train::TurnTrainable(trainConfig);
> turnTrainable.onExecute(Variable::mapToSequence(outputVars));

我可以使用NN:Utils::ExtractConvolution(expr)，然后获取他的weight吗？
