### ISSUE TITLE
TFlite model Dense layer convert with wrong results using MNNConvert

### ISSUE THREAD

**Issue by jackychen0131** [alibaba/MNN#2451]
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 16.04 using tensorflow 2.3

# Github Version:
commit 551974a6d741d7f5c927b8039df5632933cb5491
Merge: 728796b 3d5751a
Author: jxt1234 <jxt1234@zju.edu.cn>
Date:   Wed Jun 21 11:15:09 2023 +0800

Merge pull request #2445 from handongke/master

NPUBackend ModelManager V1 update to V2

# Compiling Method
cmake .. -DMNN_BUILD_CONVERTER=true

# Build Log:
Not a build error

MNNConvert command line
./MNNConvert -f TFLITE --modelFile model.tflite --MNNModel model.mnn --bizCode MNN --saveStaticModel

Question describe:
Hi, I've searched "tflite" in the history issues and did not see some similay issues so I decided to create a new one. 
As titled, if my tflite model contains Dense layers. I found that the converted MNN model will map to convolution 1x1 layer. 
However, if the dense layer is fused with its activation function, as it in the bellow image:
![dense_fused_example](https://github.com/alibaba/MNN/assets/61727041/b3f36f1b-12fa-4f2c-876c-77429d376844)
The converted MNN model of this layer won't have the same activation dunction, it simply jsut output the results (or as a linear activation function), and it will cause wrong results.
BTW, I've solved this issue by maually work-arong using additional activation functions in tensorflow model construction. Just hope this report helps. Thanks~~

**Comment by jxt1234** [comment]
Fixed, wait for code sync.

**Comment by jxt1234** [comment]
2.6.2 Fixed
