### ISSUE TITLE
python如何从bytes加载模型MNN.nn.load_module

### ISSUE THREAD

**Issue by futureflsl** [alibaba/MNN#2453]
MNN从文件加载模型可以这么样：net = MNN.nn.load_module_from_file(model, [], [], runtime_manager=rt)
但是由于公司要求MNN加密，需要从内存里面加载，因此需要一个接口可以
net = MNN.nn.load_module(bytes, [], [], runtime_manager=rt)，请问官方有这样的接口吗

**Comment by jxt1234** [comment]
目前没有接口，此 issue 同 https://github.com/alibaba/MNN/issues/2458
