### ISSUE TITLE
It is recommended to add support for loading MNN models from bytes to the MNN Python version

### ISSUE THREAD

**Issue by futureflsl** [alibaba/MNN#2458]
It is recommended to add support for loading MNN models from bytes to the Python version, as sometimes it is necessary to encrypt MNN and perform encryption and decryption operations on bytes, and then load the MNN model from the memory stream. However, I have found that C++ has such an interface function, but the Python version lacks such an interface function

**Comment by jxt1234** [comment]
we will check it.
