### ISSUE TITLE
flatbuffers error

### ISSUE THREAD

**Issue by noiplcx** [alibaba/MNN#246]
macOS 10.12.6
cmake 3.12.2
gcc 5.5.0

/Users/yoline/MNN-master/3rd_party/flatbuffers/src/idl_gen_cpp.cpp:77:3: error: constructor for 'flatbuffers::cpp::CppGenerator' must
      explicitly initialize the const member 'float_const_gen_'
  CppGenerator(const Parser &parser, const std::string &path,
  ^
/Users/yoline/MNN-master/3rd_party/flatbuffers/src/idl_gen_cpp.cpp:2788:35: note: 'float_const_gen_' declared here
  const CppFloatConstantGenerator float_const_gen_;

how to fix it?

**Comment by li-qing** [comment]
seems to be a bug in flatbuffers. https://github.com/google/flatbuffers/issues/5119

did you try to build flatbuffers on other environment?
