### ISSUE TITLE
Android平台MNN使用Vulkan后端推理会crash

### ISSUE THREAD

**Issue by wojiaoyanmin** [alibaba/MNN#2460]
在android，用官方的mnn_vulkan.so 使用Vulkan后端推理会crash，模型是paddle2onnx 再mnnconvert到mnn的，是什么原因呢

**Comment by jxt1234** [comment]
1. 先用 https://mnn-docs.readthedocs.io/en/latest/tools/test.html 里面 MNNV2Basic 在 Android 上测试下看看
2. 发一下模型

**Comment by wohaiaini** [comment]
> 1. 先用 https://mnn-docs.readthedocs.io/en/latest/tools/test.html 里面 MNNV2Basic 在 Android 上测试下看看
> 2. 发一下模型

[MNNV2Basic.out](http://mnn-docs.readthedocs.io/en/latest/tools/test.html#id5)
你好 android 系统上运行这个命令没有任何输出？只有output.txt（top查看确实运行了一段时间的）
./MNNV2Basic.out img.fp16.mnn 1 1 0 1 1x3x224x224
