### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by shengdewu** [alibaba/MNN#2461]
MNN 版本2.5.3

在pytorch forward中使用如下
F.interpolate(x,  y.shape[2:], mode=bilinear）

转换成mnn模型成功，使用python测试

mnn_interpreter = MNN.Interpreter(mnn_path)
mnn_session = mnn_interpreter.createSession()
mnn_in_tensor = mnn_interpreter.getSessionInput(self.mnn_session)

执行 mnn_interpreter.createSession 时 崩溃，并报错： Floating point exception (core dumped)

如果 不使用F.interpolate 就不会报错

**Comment by jxt1234** [comment]
这种情况有可能是出现了形状计算与内容计算不可分离的情况，参考 
https://mnn-docs.readthedocs.io/en/latest/inference/python.html#python-module-api 
用 module api 加载运行
