### ISSUE TITLE
Mac 上无法使用 Vulkan 吗？

### ISSUE THREAD

**Issue by sunjian2015** [alibaba/MNN#2466]
# 平台(如果交叉编译请再附上交叉编译目标平台):  

macOS m1

# 编译方式:

编译 MNN 的时候开启了 Vulkan
```
cmake -DMNN_VULKAN=ON -DMNN_OPENGL=OFF -DMNN_ONEDNN=OFF -DCMAKE_OSX_ARCHITECTURES="arm64" ..
```

# 编译日志:

使用 MNN 的时候，好像无法指定使用 Vulkan
```
hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Load vulkan library error
Can't Find type=7 backend, use 0 instead
Can't Find type=7 backend, use 0 instead
```

**Comment by jxt1234** [comment]
mac 官方不支持 vulkan ，可以安装这个驱动 https://github.com/KhronosGroup/MoltenVK

**Comment by sunjian2015** [comment]
> mac 官方不支持 vulkan ，可以安装这个驱动 https://github.com/KhronosGroup/MoltenVK

在官网下载了 Vulcan SDK，这个应该也可以吧？

**Comment by jxt1234** [comment]
也可以的

**Comment by sunjian2015** [comment]
> 也可以的

那为什么还报这个警告呢？
```
Load vulkan library error
Can't Find type=7 backend, use 0 instead
```

**Comment by jxt1234** [comment]
可能是 vulkan 驱动无效，你到相应驱动目录，用 libMoltenVk.dydlib 替换 libvulkan.dydlb 试下

**Comment by sunjian2015** [comment]
> 可能是 vulkan 驱动无效，你到相应驱动目录，用 libMoltenVk.dydlib 替换 libvulkan.dydlb 试下

在编译 mnn 的时候吗？该怎么操作呢？

**Comment by jxt1234** [comment]
不是，修改你安装的那个驱动...

**Comment by sunjian2015** [comment]
> 不是，修改你安装的那个驱动...

感谢大佬回复，还是没有解决...，我用的 Vulkan 版本是 1.3.250。我用 ./MNNV2Basic.out model_v3.mnn 100 0 7 4 1x3x1280x720 这个命令测试，日志如下：
```
Use extra forward type: 7

Open Model model_v3.mnn
Load Cache file error.
hw.cpufamily: 458787763 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
sj - not success
Invalide device for support vulkan
Can't Find type=7 backend, use 7 instead
sj - not success
Invalide device for support vulkan
Create Runtime Failed because no creator for 7
Can't create Runtime: 
Runtime not valid for create session
test_main, 282, cost time: 3.475000 ms
```
那个 sj - not success 是我加的一个 log，加在 source/backend/vulkan/runtime/VulkanRuntime.cpp 下边这个函数中：
```
static bool _testVulkan() {
    // std::make_unique need c++14
    std::unique_ptr<VulkanInstance> instance(new VulkanInstance());
    if (nullptr == instance) {
        MNN_PRINT("sj - nullptr\n");
        MNN_ERROR("Invalide device for support vulkan\n");
        return false;
    }
    if (!instance->success()) {
        MNN_PRINT("sj - not success\n");
        MNN_ERROR("Invalide device for support vulkan\n");
        return false;
    }
    if (!instance->supportVulkan()) {
        MNN_PRINT("sj - not support\n");
        MNN_ERROR("Invalide device for support vulkan\n");
        return false;
    }
    return true;
}
```

**Comment by sunjian2015** [comment]
> 不是，修改你安装的那个驱动...

已解决，谢谢大佬~

**Comment by sunjian2015** [comment]
> > 不是，修改你安装的那个驱动...
> 
> 感谢大佬回复，还是没有解决...，我用的 Vulkan 版本是 1.3.250。我用 ./MNNV2Basic.out model_v3.mnn 100 0 7 4 1x3x1280x720 这个命令测试，日志如下：
> 
> ```
> Use extra forward type: 7
> 
> Open Model model_v3.mnn
> Load Cache file error.
> hw.cpufamily: 458787763 , size = 4
> The device support i8sdot:1, support fp16:1, support i8mm: 0
> sj - not success
> Invalide device for support vulkan
> Can't Find type=7 backend, use 7 instead
> sj - not success
> Invalide device for support vulkan
> Create Runtime Failed because no creator for 7
> Can't create Runtime: 
> Runtime not valid for create session
> test_main, 282, cost time: 3.475000 ms
> ```
> 
> 那个 sj - not success 是我加的一个 log，加在 source/backend/vulkan/runtime/VulkanRuntime.cpp 下边这个函数中：
> 
> ```
> static bool _testVulkan() {
>     // std::make_unique need c++14
>     std::unique_ptr<VulkanInstance> instance(new VulkanInstance());
>     if (nullptr == instance) {
>         MNN_PRINT("sj - nullptr\n");
>         MNN_ERROR("Invalide device for support vulkan\n");
>         return false;
>     }
>     if (!instance->success()) {
>         MNN_PRINT("sj - not success\n");
>         MNN_ERROR("Invalide device for support vulkan\n");
>         return false;
>     }
>     if (!instance->supportVulkan()) {
>         MNN_PRINT("sj - not support\n");
>         MNN_ERROR("Invalide device for support vulkan\n");
>         return false;
>     }
>     return true;
> }
> ```

已解决

**Comment by chfeizy** [comment]
这个怎么解决的，我现在mac上也是这个情况，ncnn的vulkan 正常，但是mnn就报错
handle=p 0x721c2560 in main, 16 
The device supports: i8sdot:1, fp16:1, i8mm: 1, sve2: 0, sme2: 0
Invalide device for support vulkan
Can't Find type=7 backend, use 7 instead
Invalide device for support vulkan
Create Runtime Failed because no creator for 7
Can't create Runtime: VULKAN
Runtime not valid for create session
Exception: EXC_BAD_ACCESS (code=1, address=0x40)
killed
