### ISSUE TITLE
onnx模型转换的mnn模型 cpu后端和cuda后端计算结果不一致

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#2467]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 20.04

MNN 版本 MNN-2.5.0-release

## testMNNFromOnnx.py 测试脚本显示无异常 可以正常通过

脚本运行方式:
`python ../tools/script/testMNNFromOnnx.py fastsam_s/FastSAM-s.onnx`

运行结果如图:
![1](https://github.com/alibaba/MNN/assets/15725187/a7619980-1658-4e9e-a4e1-9375d008d58d)

## cpu backendTest 通过
运行方式:
`./backendTest.out fastsam_s/FastSAM-s.mnn 0`

运行结果如图:
![2_mosaic](https://github.com/alibaba/MNN/assets/15725187/13b88293-0d88-4e0a-bf5d-2cd9604c817c)

## cuda backendTest 失败
运行方式:
`./backendTest.out fastsam_s/FastSAM-s.mnn 2`

运行结果如图:
![3_mosaic](https://github.com/alibaba/MNN/assets/15725187/0a9cac00-4977-41cc-a67a-f1992381fc7c)

## 模型推理实测
cpu后端推理结果可以和onnx模型对齐，cuda后端推理结果完全错误.

## Converter 版本

MNN-2.5.0 
转换执行: MNNConverter -f ONNX --modelFile ./xxx.onnx --MNNModel ./xxx.mnn --keepInputFormat --bizCode MNN

## 模型文件
mnn model: https://www.dropbox.com/s/ii8ge6ywd3sxb15/FastSAM-s.mnn?dl=0
onnx model: https://www.dropbox.com/s/v1lckp2emxijrrw/FastSAM-s.onnx?dl=0

@jxt1234 求大佬帮忙看看这个应该是什么问题？如果还需要提供什么额外信息，欢迎提出:)

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 @jxt1234 大佬这个有结论了吗。这个问题应该和 #2428 是同一个问题，faatsam也是yolov8做backbone的：）

**Comment by bitxsw93** [comment]
已经修复，待同步代码

**Comment by MaybeShewill-CV** [comment]
@bitxsw93 感谢:)
