### ISSUE TITLE
离线量化比特数设置似乎不生效

### ISSUE THREAD

**Issue by GtxMiracle** [alibaba/MNN#2468]
我使用该文档介绍的方式进行模型量化：https://mnn-docs.readthedocs.io/en/latest/tools/quant.html，并且将quant_bits设置为了4。但是实际测试时发现该选项未生效，因为精度和8bit是完全相同的。请问是我的config设置有问题还是当前还不支持非8bit的量化？我的config如下：
{
    "format":"RGB",
    "mean":[
        103.94,
        116.78,
        123.68
    ],
    "normal":[
        0.017,
        0.017,
        0.017
    ],
    "width":224,
    "height":224,
    "path":"imagenet_data",
    "used_image_num":32,
    "batch_size":32,
    "feature_quantize_method":"ADMM",
    "weight_quantize_method":"ADMM",
    "quant_bits": 4
}

**Comment by jxt1234** [comment]
看着没有问题，这个正常就是生效的，未生效是指什么？你用 MNNDump2Json 打印量化的模型看一下

**Comment by GtxMiracle** [comment]
感谢回复！
未生效指的是我用不同的比特数的到的模型在测试时的精度都和8bit的模型是相同的。我尝试了2bit和4bit，结果与8bit都一样，这不太符合逻辑。模型的json文件指的是下面这种吗，里面只有scale信息，没有看到跟比特数有关的信息。
{
        "name": "input.1",
        "outputs": [
            {
                "tensorIndex": 0,
                "scales": [
                    0.019268879666924478
                ]
            }
        ]
    },
    {
        "name": "466",
        "inputs": [
            {
                "tensorIndex": 0,
                "scales": [
                    0.019268879666924478
                ]
            }
        ],
        "outputs": [
            {
                "tensorIndex": 1,
                "scales": [
                    0.04357196018099785
                ]
            }
        ]
    },
    {
        "name": "469",
        "inputs": [
            {
                "tensorIndex": 1,
                "scales": [
                    0.04357196018099785
                ]
            }
        ],
        "outputs": [
            {
                "tensorIndex": 2,
                "scales": [
                    0.04623638838529587
                ]
            }
        ]
    },

**Comment by jxt1234** [comment]
这个 bits 数只对 convolution 系列算子有效，看一下 convolution 相关算子的参数

**Comment by GtxMiracle** [comment]
看了下json中有如下输出：
{ "method": "DEFAULT", "nbits": 4, "zeroPoint": 0, "outputZeroPoint": 0, "clampMin": -128, "clampMax": 127 }
这是不是意味着我想做4bit量化，还需要将量化时将weight_clamp_value和feature_clamp_value设置为7？

**Comment by jxt1234** [comment]
这个说明已经是 4bit 量化的了。。。 有可能你的模型中 0 比较多

**Comment by GtxMiracle** [comment]
这个4bit是只针对weight的吗？如果我希望feature也是4bit应该如何设置？

**Comment by jxt1234** [comment]
目前不支持 feature 是 4bit 的

**Comment by jxt1234** [comment]
linear 算子在转换到 MNN 时会替换为 conv ，也是支持的。
