### ISSUE TITLE
MNN on x86 with Android

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#247]
Hi , 
1. can I use MNN to run on Intel CPU/GPU with ANDROID OS ?
2. If yes does it have the same convolution  optimization CPU/GPU as for ARM CPU/GPU ?

Thanks.

**Comment by li-qing** [comment]
CPU/GPU with optimizations on Android are supported.  x86/arm are both supported too.

But I did not try it on Android-x86 yet. If you get any performance trouble, leave a comment here.

check out doc https://www.yuque.com/mnn/en/build_android for detail.

**Comment by dimitryn** [comment]
Hi @li-qing ,
I try to compile libMNN library for Android OS and  Intel CPU .
I changed build_64.sh with -DANDROID_ABI="x86_64" \

I have error compilation:

MatrixSub.cpp.o
[ 78%] Linking CXX shared library libMNN.so
/home/administrator/Code/MNN/source/core/Tensor.cpp:296: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:317: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:271: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:336: error: undefined reference to '__gnu_h2f_ieee'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/MNN.dir/build.make:3203: recipe for target 'libMNN.so' failed
make[2]: *** [libMNN.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/MNN.dir/all' failed
make[1]: *** [CMakeFiles/MNN.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iazrael** [comment]
@li-qing x86编译会失败，x86_64则成功，看代码，是没有支持x86吗？
