### ISSUE TITLE
多输入+动态shape输入的模型量化问题

### ISSUE THREAD

**Issue by GuangyanZhang** [alibaba/MNN#2471]
问题描述如下：
1.多输入的模型量化：参照https://github.com/alibaba/MNN/blob/master/pymnn/examples/MNNQuant/test_mnn_offline_quant.py， 脚本支持多输入模型的量化，模型量化成功
2.动态shape+多输入模型量化：通过学习文档动态shape需要resizeTensor+resizeSession配合使用，结果如下：
   a.python的api使用https://mnn-docs.readthedocs.io/en/latest/pymnn/Interpreter.html#mnn-interpreterd， 支持该模型float模型正常推理,请问使用mnn.interpreter如何做动态shape+多输入模型的量化呢？
   b.python的api模型量化使用的MNN.nn api，请问nn api是否有resizeTensor+resizeSession这两个函数，如何使用呢？
备注：以上所有基于python实现的。

**Comment by jxt1234** [comment]
这个工具是用的 expr API 做的模型量化。部分模型可能无法用 Interpreter + Session 的 API 运行，需要使用Module API https://mnn-docs.readthedocs.io/en/latest/inference/python.html#python-module-api
