### ISSUE TITLE
使用MNNConvert转换模型保持原始模型的inputshape

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2473]
Hi：

         我们使用MNNConvert 转换pb模型到mnn模型， pb模型的输入shape是（NHWC）,想要转换的mnn模型输入shape
也是NHWC,  在转换时，加了 --keepInputFormat true,   但转出的mnn模型输入还是NCHW，请问该怎么做呢？

thanks

**Comment by jxt1234** [comment]
从 pb 转成 mnn ，输入应该就是 NHWC ，但如果先把 pb 转 onnx ，再转 mnn ，输入会变成 NCHW

**Comment by jxt1234** [comment]
加 --keepInputFormat 就行，不用跟 true

**Comment by keke444** [comment]
生效了，感谢
