### ISSUE TITLE
使用AMD显卡，运行OpenCL后端，跑YOLOv5的执行时间不准问题

### ISSUE THREAD

**Issue by darrenearl** [alibaba/MNN#2474]
我在使用AMD 7600显卡，OpenCL后端，使用MNN运行YOLOv5的时候，runSession()时间仅仅0.3ms，同样的代码，在RTX3070上需要3ms，请问runSession()方法是异步执行的吗？如何统计执行时间呢？
我的代码如下：

    auto start = std::chrono::steady_clock::now();
    mnnNet_->runSession(session_);
    auto end = std::chrono::steady_clock::now();
    auto time = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
    std::cout << "model exec time: " << time << "ms." << std::endl;

**Comment by jxt1234** [comment]
runSession 不一定会等待 GPU 执行完成，若需要等待，参考 tools/cpp/timeProfile.cpp：
获取 outputTensor ，执行，outputTensor->wait(MNN::Tensor::MAP_TENSOR_READ, true)

**Comment by darrenearl** [comment]
> 

Tank you very much!
