### ISSUE TITLE
MNN Converted Model given different predictions from PyTorch and ONNX

### ISSUE THREAD

**Issue by notha99y** [alibaba/MNN#2475]
# Problem
I am trying to convert RetinaFace (https://github.com/biubug6/Pytorch_Retinaface) to MNN and the converted MNN model is given different results. 

MNN verison = 2.5.1

# Conversion Process
PyTorch -> ONNX -> MNN

## PyTorch to Onnx
``` python
output_onnx = "retinaface.onnx"
print("==> Exporting model to ONNX format at '{}'".format(output_onnx))
input_names = ["input0"]
output_names = ["output_bbox", "output_conf", "output_landm"]
inputs = torch.randn(1, 3, 640, 640)

torch_out = torch.onnx._export(
    model,
    inputs,
    output_onnx,
    export_params=True,
    verbose=True,
    input_names=input_names,
    output_names=output_names,
)
```

## Onnx to MNN
```bash
mnnconvert -f ONNX --modelFile retinaface.onnx --MNNModel retinaface.mnn --bizCode MNN
```

![image](https://github.com/alibaba/MNN/assets/29172421/52a7b8b8-b1e2-4c03-b822-7aea49785e40)

## Inference
```python
import numpy as np
import torch
import MNN
import MNN.cv as cv
import MNN.expr as expr

# Setting up MNN
interpreter = MNN.Interpreter("retinaface.mnn")
# 创建session
config = {}
config['precision'] = 'high'
config['backend'] = 'CPU'
config['thread'] = 4
session = interpreter.createSession(config)
# 获取会话的输入输出
input_tensor = interpreter.getSessionInput(session)
output_tensor = interpreter.getSessionOutputAll(session)

# Running
example = np.array(np.random.randn(1,3,640,640), dtype=np.float32)
torch_example = torch.from_numpy(example)
input_data = MNN.Tensor((1,3,640,640), MNN.Halide_Type_Float, example, MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(input_data)
interpreter.runSession(session)

output_data = MNN.Tensor(output_tensor['output_bbox'].getShape(), MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
output_tensor['output_bbox'].copyToHostTensor(output_data)

# Pytorch outputs
with torch.no_grad():
    out = model.forward(torch_example)
# Onnx outputs
outputs = ort_sess.run(None, {'input0': example})

# MNN outputs 
output_tensor['output_bbox'].getNumpyData()
```
![image](https://github.com/alibaba/MNN/assets/29172421/484b951b-5b02-4a0f-9aec-a0eb023fcd4f)

**Comment by notha99y** [comment]
# Update

I realized the problem is due to the value of the output changing when I run 
```python
output_data = MNN.Tensor(output_tensor['output_bbox'].getShape(), MNN.Halide_Type_Float, MNN.Tensor_DimensionType_Caffe)
output_tensor['output_bbox'].copyToHostTensor(output_data)
```

the output_data is more or less the same as the output from pytorch and onnx where output_tensor is the one which is very different.

![image](https://github.com/alibaba/MNN/assets/29172421/202af489-fa54-4a51-bfd2-f04d40be91d7)

**Comment by jxt1234** [comment]
Don't use output_tensor['output_bbox'] directly. It may be NC4HW4 format. Use the output_data which has turn to NCHW.

**Comment by jxt1234** [comment]
You can add --keepInputFormat when Convert onnx to MNN to avoid dimension format convert.

**Comment by notha99y** [comment]
hmm I see. so I should use output_data instead of output_tensor['output_bbox'] and the values are different even though we copy from output_tensor['output_bbox']  is because it maybe in NC4HW4? 

I tried using --keepInputFormat and also another one with both --keepInputFormat and --keepOutputFormat but the results are the same. does that mean output_tensor['output_bbox']  is not in NC4HW4?
