### ISSUE TITLE
MNN-2.6.0 Windows上编译错误

### ISSUE THREAD

**Issue by lizexu-nreal** [alibaba/MNN#2476]
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON -DMNN_CUDA=ON -DMNN_BUILD_CONVERTER=ON -DMNN_SEP_BUILD=OFF  -DMNN_BUILD_QUANTOOLS=ON -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON
报错：
FAILED: transformer.out.exe
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=tools\train\CMakeFiles\transformer.out.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo tools\train\CMakeFiles\transformer.out.dir\source\exec\transformerExecution.cpp.obj tools\train\CMakeFiles\transformer.out.dir\source\transformer\OpConverter.cpp.obj tools\train\CMakeFiles\transformer.out.dir\source\transformer\Transformer.cpp.obj  /out:transformer.out.exe /implib:tools\train\transformer.out.lib /pdb:transformer.out.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF /subsystem:console  /WHOLEARCHIVE:D:/MNN-2.6.0/build/MNN.lib  MNN.lib  source\backend\cuda\MNN_CUDA.lib  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib\x64\cudart_static.lib"  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo tools\train\CMakeFiles\transformer.out.dir\source\exec\transformerExecution.cpp.obj tools\train\CMakeFiles\transformer.out.dir\source\transformer\OpConverter.cpp.obj tools\train\CMakeFiles\transformer.out.dir\source\transformer\Transformer.cpp.obj /out:transformer.out.exe /implib:tools\train\transformer.out.lib /pdb:transformer.out.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF /subsystem:console /WHOLEARCHIVE:D:/MNN-2.6.0/build/MNN.lib MNN.lib source\backend\cuda\MNN_CUDA.lib C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\lib\x64\cudart_static.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:transformer.out.exe.manifest" failed (exit code 1169) with the following output:
MNN.lib(OpConverter.cpp.obj) : error LNK2005: "public: static class std::shared_ptr<class MNN::Express::Expr> __cdecl OpConverter::convert(class std::shared_ptr<class MNN::Express::Expr>,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class MNN::Express::VARP,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class MNN::Express::VARP> > > &)" (?convert@OpConverter@@SA?AV?$shared_ptr@VExpr@Express@MNN@@@std@@V23@AEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VVARP@Express@MNN@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VVARP@Express@MNN@@@std@@@2@@3@@Z) 已经在 OpConverter.cpp.obj 中定义
MNN.lib(OpConverter.cpp.obj) : error LNK2005: "public: static class OpConverter * __cdecl OpConverter::get(enum MNN::OpType)" (?get@OpConverter@@SAPEAV1@W4OpType@MNN@@@Z) 已经在 OpConverter.cpp.obj 中定义
MNN.lib(OpConverter.cpp.obj) : error LNK2005: "public: static void __cdecl OpConverter::insert(enum MNN::OpType,class OpConverter *)" (?insert@OpConverter@@SAXW4OpType@MNN@@PEAV1@@Z) 已经在 OpConverter.cpp.obj  中定义
MNN.lib(Transformer.cpp.obj) : error LNK2005: "public: virtual bool __cdecl MNN::Train::InferOptimizer::onExecute(class std::vector<class MNN::Express::VARP,class std::allocator<class MNN::Express::VARP> > const &,class std::shared_ptr<class MNN::Express::Optimizer::Parameters>)" (?onExecute@InferOptimizer@Train@MNN@@UEAA_NAEBV?$vector@VVARP@Express@MNN@@V?$allocator@VVARP@Express@MNN@@@std@@@std@@V?$shared_ptr@VParameters@Optimizer@Express@MNN@@@5@@Z) 已经在 Transformer.cpp.obj 中定义
MNN.lib(Transformer.cpp.obj) : error LNK2005: "public: virtual bool __cdecl MNN::Train::TurnTrainable::onExecute(class std::vector<class MNN::Express::VARP,class std::allocator<class MNN::Express::VARP> > const &,class std::shared_ptr<class MNN::Express::Optimizer::Parameters>)" (?onExecute@TurnTrainable@Train@MNN@@UEAA_NAEBV?$vector@VVARP@Express@MNN@@V?$allocator@VVARP@Express@MNN@@@std@@@std@@V?$shared_ptr@VParameters@Optimizer@Express@MNN@@@5@@Z) 已经在 Transformer.cpp.obj 中定义
MNN.lib(Transformer.cpp.obj) : error LNK2005: "public: static class std::shared_ptr<class MNN::Express::Optimizer> __cdecl MNN::Train::Transformer::turnModelToInfer(void)" (?turnModelToInfer@Transformer@Train@MNN@@SA?AV?$shared_ptr@VOptimizer@Express@MNN@@@std@@XZ) 已经在 Transformer.cpp.obj 中定义
MNN.lib(Transformer.cpp.obj) : error LNK2005: "public: static class std::shared_ptr<class MNN::Express::Optimizer> __cdecl MNN::Train::Transformer::turnModelToTrainable(struct MNN::Train::Transformer::TrainConfig)" (?turnModelToTrainable@Transformer@Train@MNN@@SA?AV?$shared_ptr@VOptimizer@Express@MNN@@@std@@UTrainConfig@123@@Z) 已经在 Transformer.cpp.obj 中定义
  正在创建库 tools\train\transformer.out.lib 和对象 tools\train\transformer.out.exp
transformer.out.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
ninja: build stopped: subcommand failed.

**Comment by jxt1234** [comment]
修正中，可以先设 -DMNN_BUILD_QUANTOOLS=OFF -DMNN_BUILD_TRAIN=OFF ，关闭这两部分编译

**Comment by lizexu-nreal** [comment]
> 修正中，可以先设 -DMNN_BUILD_QUANTOOLS=OFF -DMNN_BUILD_TRAIN=OFF ，关闭这两部分编译

确实

**Comment by jxt1234** [comment]
已经修正
