### ISSUE TITLE
int32作为网络输入时，Opencl后端精度设置为Low时结果错误

### ISSUE THREAD

**Issue by 791136190** [alibaba/MNN#2478]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86-64

# Github版本:
# Github Version:
2.6.0-release

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake .. -DMNN_OPENCL=ON

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

-- 
-- 3.19.0.0
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: x86_64
--      Version: 2.6.0
--      Metal: OFF
--      OpenCL: ON
--      OpenGL: OFF
--      Vulkan: ON
--      ARM82: OFF
--      oneDNN: OFF
--      TensorRT: OFF
--      CoreML: OFF
--      NNAPI: OFF
--      CUDA: OFF
--      OpenMP: OFF
--      BF16: OFF
--      ThreadPool: ON
--      Hidden: TRUE
--      Build Path: /alg_sources/MNN-2.6.0/build
--      CUDA PROFILE: OFF
-- WIN_USE_ASM: 
-- x86_64: Open SSE
-- MNN_AVX512:OFF
-- Onnx: 
-- Configuring done (0.0s)
-- Generating done (0.1s)
-- Build files have been written to: /alg_sources/MNN-2.6.0/build

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

模型输入如果是int类型，在opencl后端时，设置为low会得到错误结果，需要设置为high。但是模型中其它部分是float计算的，所以是否可以在int输入时做一些特殊处理

**Comment by jxt1234** [comment]
int输入对opencl 也是用 int 存的，有可能是中间某个层越过了 fp16 界限。

**Comment by 791136190** [comment]
> int输入对opencl 也是用 int 存的，有可能是中间某个层越过了 fp16 界限。

但是我通过回调函数看tensor里面的值，输入第一个节点的值就错了，比如40486可能就成了40487，然后用high就没问题

**Comment by jxt1234** [comment]
应该是前面有 int32 转 float 的算子吧

**Comment by yiguanxian** [comment]
@jxt1234 @791136190 这个问题我也遇到了，给模型喂输入（opencl）调用copyFromHost后再打印tensor结果发现与我给进去的值有差异，例如给的值是274，但拷贝后打印出来的是275这种。
