### ISSUE TITLE
npu推理崩溃

### ISSUE THREAD

**Issue by TnoobT** [alibaba/MNN#2482]
版本：mnn-2.5
手机：红米k50
编译：../build_64.sh -DMNN_ARM82=true -DMNN_NNAPI=true -DMNN_NPU=true
手机推理把config_.type = MNN_FORWARD_NN改成nn后，程序闪退。图片是android studio的报错信息
![image](https://github.com/alibaba/MNN/assets/44052395/9774f69c-92f9-452b-a8e3-2d2100c9b798)

**Comment by wangzhaode** [comment]
你这个错误信息不是MNN的堆栈信息，forward_type设置成CPU是否能执行呢

**Comment by TnoobT** [comment]
cpu能正常运行，cpu上正常运行也会报上面的这个错，所以不是图片上的问题。下面这个图是崩溃信息
![image](https://github.com/alibaba/MNN/assets/44052395/cc847072-d2a5-4014-8a74-05b5d081dc62)

**Comment by TnoobT** [comment]
leakrelu算子 npu推理是不是不支持啊

**Comment by TnoobT** [comment]
还有报这个错，用cpu就不会错。上面的图和下面的图是两个工程
![image](https://github.com/alibaba/MNN/assets/44052395/44ffd85c-8b17-4c2f-9f37-62ab62da30f4)

**Comment by wangzhaode** [comment]
请把崩溃的完整信息发一下吧

**Comment by TnoobT** [comment]
![image](https://github.com/alibaba/MNN/assets/44052395/836132fc-addd-426c-b7d5-84623c3f2def)
这个，我用的yolov5，大佬要不要看看模型

**Comment by wangzhaode** [comment]
错误信息是在这里了：
![image](https://github.com/alibaba/MNN/assets/8401806/495ae2d0-9354-4c05-8c3e-5d7c669cfacb)

**Comment by wangzhaode** [comment]
看报错信息这个OP要求输入的tensor dim <= 4; 你这里输入的维度是5导致无法创建NN的计算图

**Comment by TnoobT** [comment]
我咋解决，输入是四维的吧。大佬，麻烦帮我看看模型，我用netron看是四维的啊
[归档.zip](https://github.com/alibaba/MNN/files/12037658/default.zip)

**Comment by TnoobT** [comment]
大佬还有个问题，我看文档中的算子支持，是指.mnn模型中的算子还是.onnx中的算子。 我这onnx模型有gather操作，转到mnn就变成gatherv2了，文档里好像对gatherv2算子不支持？

**Comment by wangzhaode** [comment]
`文档里好像对gatherv2算子不支持？`

这个是什么意思 ？

**Comment by TnoobT** [comment]
![image](https://github.com/alibaba/MNN/assets/44052395/58fc793e-c5c3-4526-bd38-80846346b706)
文档里没写支持gatherv2算子，还有这个"gether"是不是打错了

**Comment by wangzhaode** [comment]
你说的是哪个文档 是指MNNConvert支持的onnx算子嘛？

**Comment by wangzhaode** [comment]
嗯 这个Gather对应的OpType就是GatherV2, 确实打错了 应该是Gather 不是 Gether

**Comment by TnoobT** [comment]
大佬，加个钉钉呗，我这个模型的输入维度应该没问题吧
