### ISSUE TITLE
python api的支持的量化算法

### ISSUE THREAD

**Issue by GuangyanZhang** [alibaba/MNN#2485]
1.请问nn.compress.train_quant(net, quant_bits=8)支持quant_bits=16吗？我设置过16推理结果全是错的
2.请问nn.compress.train_quant支持那些量化算法，我看了api的说明支持的有限，
`参数：

module 待训练模型

quant_bits 量化位数，默认为 8

feature_scale_method 特征的量化方式，默认为 PER_TENSOR/PER_CHANNEL

scale_update_method scale的更新方式，默认为 MOVING_AVERAGE/MAXMIN

返回：是否成功

返回类型：bool`
请问还支持其他量化算法吗？哪里查看使用方法，目前用默认的方法掉点严重

**Comment by jxt1234** [comment]
1. 不支持
2. 只有上面这两种

需要更高精度可以用基于 pytorch / tensorflow 插件实现的模型压缩工具箱相关功能
https://mnn-docs.readthedocs.io/en/latest/tools/compress.html
