### ISSUE TITLE
cuda比onnxruntime在TITANXP卡上比onnxruntime慢很多，且多线程比单线程性能提升有限

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#2486]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
CUDA

# Github版本:
# Github Version: 2.5.3

```
cmake .. -DCMAKE_BUILD_TYPE=Release \
	-DMNN_BUILD_TEST=OFF \
	-DMNN_BUILD_QUANTOOLS=OFF \
	-DMNN_BUILD_DEMO=OFF \
	-DMNN_BUILD_CONVERTER=OFF \
	-DMNN_SUPPORT_BF16=OFF \
	-DMNN_BUILD_OPENCV=OFF \
	-DMNN_CUDA=ON \
	-DMNN_ENABLE_COVERAGE=OFF && make -j4
```

# MNN cuda比Onnxruntime在TITANXP卡上慢很多
输入：3 * 640 * 640
ort耗时： 14.1ms
mnn cuda耗时：38.1ms

**Comment by bitxsw93** [comment]
Pascal系列显卡目前MNN优化投入不多，优化投入目前主要集中在图灵及其以上显卡。

**Comment by ppl21847** [comment]
> Pascal系列显卡目前MNN优化投入不多，优化投入目前主要集中在图灵及其以上显卡。

好的 明白
