### ISSUE TITLE
input Output 输入shape 问题

### ISSUE THREAD

**Issue by fuerpy** [alibaba/MNN#2487]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Onnx Convert to MNN

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
./MNNConvert -f ONNX --modelFile ../../../torch_onnx/unet/model.onnx --MNNModel unet.mnn --bizCode biz --keepInputFormat --fp16
```

# 编译日志:
# Build Log:

# 获取会话的输入输出

```
sample = interpreter.getSessionInput(session,"sample")
timestep = interpreter.getSessionInput(session, "timestep");
encoder_hidden_states = interpreter.getSessionInput(session, "encoder_hidden_states");
output = interpreter.getSessionOutput(session);

print(sample.getShape())

(1, -1, -1, -1)

print(output.getShape())


(0, 0, 0, 0)
```

**Comment by fuerpy** [comment]
input 应该是 （batch，4，64，64）类似这样吧  输出同样

**Comment by jxt1234** [comment]
1. 应该是没有 resizeTensor -> resizeSession
2. 建议改用 Module API :  https://mnn-docs.readthedocs.io/en/latest/inference/python.html#python-module-api
