### ISSUE TITLE
OpenCV在Windows上编译报错

### ISSUE THREAD

**Issue by lizexu-nreal** [alibaba/MNN#2489]
cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON -DMNN_CUDA=ON -DMNN_BUILD_CONVERTER=ON -DMNN_SEP_BUILD=OFF  -DMNN_BUILD_QUANTOOLS=ON -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_OPENCV_TEST=ON -DMNN_OPENCV_BENCH=ON 
我在Windows平台下使用MinGW Makefiles成功编译了Opencv，并且设置了环境变量，可以我使用x64 Native Tool Command Prompt for VS 2019的时候使用上面这个命令，报错
CMake Warning at D:/opencv-3.4.16/build/install/OpenCVConfig.cmake:191 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  tools/cv/test/CMakeLists.txt:3 (find_package)

CMake Error at tools/cv/test/CMakeLists.txt:3 (find_package):
  Found package configuration file:

    D:/opencv-3.4.16/build/install/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!
See also "D:/MNN-2.6.0/build1/CMakeFiles/CMakeOutput.log".
See also "D:/MNN-2.6.0/build1/CMakeFiles/CMakeError.log".
但是我在普通的cmd命令使用cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON -DMNN_CUDA=ON -DMNN_BUILD_CONVERTER=ON -DMNN_SEP_BUILD=OFF  -DMNN_BUILD_QUANTOOLS=ON -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_OPENCV_TEST=ON -DMNN_OPENCV_BENCH=ON 就对了，就是换了个终端，请问为什么？

**Comment by jxt1234** [comment]
看上去是 vs 环境下找不到 opencv 的配置
