### ISSUE TITLE
tflite 转换过程中， 为什么有些add被转换成BinaryOp，有些被转换成Eltwise？

### ISSUE THREAD

**Issue by zihaomu** [alibaba/MNN#2493]
两者输入大小都是一样大的。

**Comment by jxt1234** [comment]
在模型转换过程中能确定形状一致的用 Eltwise ，不能确定时转 Binary

**Comment by zihaomu** [comment]
奇怪的是，这两者的形状都是一致。
converter的optimizer中是否有什么优化策略去添加`ConvertTensor`?我debug进去看看。

## 转换成BinaryOp
原始节点：
![image](https://github.com/alibaba/MNN/assets/16487352/5ca3f16b-e550-4263-8be3-2814ed9292ce)

转换后节点
![image](https://github.com/alibaba/MNN/assets/16487352/36a4189f-5edc-43b0-b5c1-3ee44aecd91e)

## 转换成Eltwise
原始节点
![image](https://github.com/alibaba/MNN/assets/16487352/1d0f0656-64ac-4124-9784-8c0ff3299779)

转换后节点
![image](https://github.com/alibaba/MNN/assets/16487352/8909dcbb-0384-4344-8d58-86b01446b091)

可以看到映射到BinaryOp和Eltwise的都是一样的输入一致的Add节点，出来的确实不一样。

**Comment by jxt1234** [comment]
主要与转换 binary 到 eltwise 的逻辑有关
tools/converter/source/optimizer/postconvert/ConvertBinaryToElementwise.cpp

**Comment by zihaomu** [comment]
换用最新版的MNN，没有上面这个问题，应该已经修复了。 👍
