### ISSUE TITLE
请问有提供openCV做预处理的推理demo吗？

### ISSUE THREAD

**Issue by xiaochengsky** [alibaba/MNN#2494]
发现openCV和MNNCV的图像预处理差距比较大。
请问有提供openCV做预处理的推理demo吗，想比较一下，和原始模型对齐。我找了几个历史的branch，好像也没看到。

**Comment by jxt1234** [comment]
OpenCV 处理后的浮点数据输入 MNN 模型就行

**Comment by jxt1234** [comment]
python 上可以参考 mobilenet_demo.py
