### ISSUE TITLE
MNN模型的推理结果与ONNX推理结果不一致

### ISSUE THREAD

**Issue by lizexu-nreal** [alibaba/MNN#2495]
模型的输入格式是.raw格式的，输入的维度是NCHW，
![image](https://github.com/alibaba/MNN/assets/134259938/d5202bf6-8f47-4051-8fc9-dc86b33f3521)
这是输入的shape和name，输出的维度为[1,1,288,384]。
#include "Deployment_Tool.h"

#include "NR_MNN_Deploy.h"
#include "NR_SNPE_Deploy.h"
#include "NR_NCNN_Deploy.h"
#include "NR_TNN_Deploy.h"
#include <iostream>
#include <sys/types.h>
#include <dirent.h>
#include <string>

// using namespace std;

#define EXPORT_FUNC __attribute__ ((visibility("default")))

void GetFileNames(std::string path, std::vector<std::string>& dst_filenames, std::string dst_ext)
{
    DIR *pDir;
    struct dirent* ptr;
    if(!(pDir = opendir(path.c_str()))){
        std::cout<<"Folder doesn't Exist!"<<std::endl;
        return;
    }
    while((ptr = readdir(pDir))!=0) {
        if (strcmp(ptr->d_name, ".") != 0 && strcmp(ptr->d_name, "..") != 0){
            std::string file_ext = std::string(ptr->d_name).substr(std::string(ptr->d_name).length() - dst_ext.length());
            // std::cout << file_ext << std::endl;
            if (dst_ext == file_ext) {
                dst_filenames.push_back(ptr->d_name);
            }
        }
    }
    closedir(pDir);
}

std::set<std::string> GetFileNameSet(std::vector<std::string> files, std::string deli) {
    std::set<std::string> fileSet;
    for (auto file : files) {
        auto pos = file.rfind("_" + deli);
        if (pos == file.npos) {
            // std::cout << "wrong file format for input data" << std::endl;
        }
        else {
            file = file.substr(0, pos);
            fileSet.insert(file);
        }
    }
    return fileSet;
}

std::vector<float> GetRawData(std::string rawDataPath) {

    // load file
    std::ifstream infile(rawDataPath, std::ifstream::binary);

    // count file size
    infile.seekg(0, infile.end);
    int size = infile.tellg();
    // std::cout << "inputfilesize = " << size << std::endl;

    // load data
    infile.seekg(0, infile.beg);
    char *buf = new char[size];
    infile.read(buf, size);
    std::vector<float> rawData(size / 4);
    memcpy(rawData.data(), buf, size);
    infile.close();
    delete[] buf;
    return rawData;
}

void SaveRawData(std::string rawDataPath, std::vector<float> outData) {
    // open file
    std::ofstream outfile(rawDataPath, std::ofstream::binary);
    int dataSize = outData.size() * sizeof(float);
    char *buf = new char[dataSize];
    memcpy(buf, outData.data(), dataSize);
    outfile.write(buf, dataSize);
    delete[] buf;
}

EXPORT_FUNC bool DeploymentTest(std::string model_name, TEST_MODE test_mode, PRECISION_MODE precision_mode, std::string input_path, std::string output_path) {

    NrealAI::NNConfig deploy_config;
    std::unique_ptr<NrealAI::NRNN> pNetwork;

    if ((int)precision_mode > 4) {  // tnn extention
        deploy_config.modelPath = model_name;
        deploy_config.precision = (NrealAI::PrecisionMode)(int(precision_mode) - 5);
        pNetwork = std::unique_ptr<NrealAI::NRNN> (new NrealAI::TNN_Deployment(deploy_config));
    }
    else if ((int)precision_mode > 2) {  // ncnn extention
        deploy_config.modelPath = model_name;
        deploy_config.precision = (NrealAI::PrecisionMode)(int(precision_mode) - 3);
        pNetwork = std::unique_ptr<NrealAI::NRNN> (new NrealAI::NCNN_Deployment(deploy_config));
    }
    else { // mnn or snpe
        deploy_config.modelPath = model_name;
        deploy_config.precision = (NrealAI::PrecisionMode)precision_mode;

        if (deploy_config.precision == NrealAI::PrecisionMode::int8) {
            pNetwork = std::unique_ptr<NrealAI::NRNN> (new NrealAI::SNPE_Deployment(deploy_config));
        }
        else {
            pNetwork = std::unique_ptr<NrealAI::NRNN> (new NrealAI::MNN_Deployment(deploy_config));
        }
    }

    if (test_mode == TEST_MODE::SPEED) {
        // warm up
        int warm_up_times = 10;
        if (deploy_config.precision == NrealAI::PrecisionMode::int8) {
            warm_up_times = 200;
        }
        std::cout << "warm up times = " << warm_up_times << std::endl;
        for (int i = 0; i < warm_up_times; i ++){
            pNetwork->inference();
        }
        // timing
        // ====== timing start ======
        const int test_times = 100;
        struct timespec start;
        clock_gettime(CLOCK_MONOTONIC, &start);
        uint64_t start_nanos = start.tv_sec * 1000000000LL + start.tv_nsec;

        uint64_t max_infer_time = 0;
        uint64_t min_infer_time = ULONG_MAX;
        uint64_t sum_infer_time = 0;
        for (int i = 0; i < test_times; i ++){
            struct timespec time_st;
            clock_gettime(CLOCK_MONOTONIC, &time_st);
            uint64_t time_st_nanos = time_st.tv_sec * 1000000000LL + time_st.tv_nsec;

            pNetwork->inference();

            struct timespec time_et;
            clock_gettime(CLOCK_MONOTONIC, &time_et);
            uint64_t time_et_nanos = time_et.tv_sec * 1000000000LL + time_et.tv_nsec;

            auto infer_time = time_et_nanos - time_st_nanos;
            std::cout << "infer_id: " << i << "\ttime: " << infer_time / 1000000. << "\n";
            sum_infer_time += infer_time;
            max_infer_time = max_infer_time > infer_time ? max_infer_time : infer_time;
            min_infer_time = min_infer_time < infer_time ? min_infer_time : infer_time;
        }
        struct timespec end;
        clock_gettime(CLOCK_MONOTONIC, &end);
        uint64_t end_nanos = end.tv_sec * 1000000000LL + end.tv_nsec;
        auto overall = end_nanos - start_nanos;

        auto aver_infer_time = sum_infer_time / (test_times);

        std::cout << "Inference time: average = " << aver_infer_time / 1000000. << "ms" << std::endl;
        std::cout << "Inference time: max = " << max_infer_time / 1000000. << "ms" << std::endl;
        std::cout << "Inference time: min = " << min_infer_time / 1000000. << "ms" << std::endl;

        // std::cout << "Inference time: average = " << aver_infer_time << " max = " << max_infer_time << " min = " << min_infer_time << std::endl;
        std::cout << "OverallTime = " << overall << std::endl;
        // ====== timing end ======
        std::ofstream f_speed("Speed.txt", std::ios::app);
        f_speed << "Inference time: average = " << aver_infer_time / 1000000. << "ms" << std::endl;
        f_speed << "Inference time: max = " << max_infer_time / 1000000. << "ms" << std::endl;
        f_speed << "Inference time: min = " << min_infer_time / 1000000. << "ms" << std::endl;
        f_speed.close();
    }
    else if (test_mode == TEST_MODE::INFERENCE) {
        auto InputTensorNames = pNetwork->GetInputTensorNames();
        auto OutputTensorNames = pNetwork->GetOutputTensorNames();

        std::vector<std::string> files;
        std::string inputFormat = ".raw";
        std::string outputFormat = ".raw";
        GetFileNames(input_path, files, inputFormat);
        std::cout << "filenums = " << files.size() << std::endl;

        if (InputTensorNames.size() == 1){
            // only one input tensor
            for (int i = 0; i < files.size(); i++) {
                std::map<std::string, std::vector<float>> InputMap;
                std::map<std::string, std::vector<float>> OutputMap;
                auto inputRawData = GetRawData(input_path + "/" + files[i]);
                InputMap.insert(std::make_pair(InputTensorNames[0], inputRawData));
                // std::cout << files[i] << std::endl;
                pNetwork->inference(InputMap, OutputMap);
                for (auto it = OutputMap.begin(); it != OutputMap.end(); it++) {
                    std::string fullOutName = files[i].substr(0, files[i].length() - outputFormat.length())  + "_" + it->first + outputFormat;
                    SaveRawData(output_path + "/" + fullOutName, it->second);
                    // std::cout << "output_path" << output_path << "/" << fullOutName << std::endl;
                }
            }
        }
        else {
           
			std::vector<std::string> files;
			std::string inputFormat = ".raw";
			std::string outputFormat = ".raw";
			getFileName(input_path, files, inputFormat);

			// std::cout << "filenums = " << files.size() << std::endl;

			std::map<std::string, std::vector<float>> InputMap;
			std::map<std::string, std::vector<float>> OutputMap;
			std::string rawDataPath = "D:/MNN-2.6.0/test_data_nchw/planer_depth/";
			auto inputRawData = GetRawData(rawDataPath  + "25_left_image.raw");
			auto inputRawData1 = GetRawData(rawDataPath  + "25_right_image.raw");

			// 保存 inputRawData
			std::string filename = "25_left_image.raw";
			SaveRawData(filename, inputRawData);

			// 保存 inputRawData1
			filename = "25_right_image.raw";
			SaveRawData(filename, inputRawData1);

			InputMap.insert(std::make_pair("left_image",inputRawData));
			InputMap.insert(std::make_pair("right_image",inputRawData1));
			deployment.inference(InputMap,OutputMap);
               
            }
        }
    }

    return true;
}这是我的代码，因为他的输入多输入，就走了后面这个else循环，我是把输入的东西放到了InputMap中，然后进行推理，我测试了onnx和mnn的输入的图片(因为都是raw格式)，两者基本没差别，然后模型转换也没有问题，但是输出就是对不上，有没有大佬可以帮忙看一下

**Comment by lizexu-nreal** [comment]
输出维度是可以对的上的。源码和模型可提供

**Comment by lizexu-nreal** [comment]
![image](https://github.com/alibaba/MNN/assets/134259938/7aaf39f2-ffcc-4a45-af52-53134839a4f7)
这是测试转换成MNN和ONNX的对比，证明了模型转换是没有问题的

**Comment by lizexu-nreal** [comment]
MNN版本 2.6.0

**Comment by lizexu-nreal** [comment]
我查到了问题，
![image](https://github.com/alibaba/MNN/assets/134259938/296dfa25-5e61-442e-958f-75dcb291bbdb)
我打印了name的名字为disp__tr，可是onnx模型的名字为
![image](https://github.com/alibaba/MNN/assets/134259938/653e40d9-6bb2-436f-8d81-cc13d3166659)
我还打印了一下mNetworkoutBuffer[name].data()，结果全是0，有人知道怎么解决吗

**Comment by jxt1234** [comment]
> ![image](https://user-images.githubusercontent.com/134259938/253726592-7aaf39f2-ffcc-4a45-af52-53134839a4f7.png) 这是测试转换成MNN和ONNX的对比，证明了模型转换是没有问题的

这个就证明 MNN 的推理结果没有问题

**Comment by jxt1234** [comment]
应该是你 inference 时输入 MNN 的 tensor 没有做格式转换

**Comment by jxt1234** [comment]
简单起见在模型转换时加上 --keepInputFormat

**Comment by lizexu-nreal** [comment]
> 

我试了，这个没用

**Comment by lizexu-nreal** [comment]
> 简单起见在模型转换时加上 --keepInputFormat
我试了这个了，没用，
![image](https://github.com/alibaba/MNN/assets/134259938/8234a0f9-3baf-4f9f-8c51-e1c6eedcc1f5)
而且我在模型前处理的时候就把raw的输入变成了nchw的格式

**Comment by lizexu-nreal** [comment]
> 应该是你 inference 时输入 MNN 的 tensor 没有做格式转换

我输入的raw的都是nchw格式的，然后在前处理的时候，也是用的MNN::Tensor::CAFFE，要不我把源码给您看一下，我刚入门MNN两周，还不太熟悉

**Comment by jxt1234** [comment]
1. GetMNNInfo 看一下，是不是没有 resizeTensor -> resizeSession
2. 后续建议用 Module API 实现，相比 Session API 易用一些

**Comment by jxt1234** [comment]
可以重新提个 issue 附上代码
