### ISSUE TITLE
请问使用GPU时生成Cache文件时，未加密的话有技术泄密风险吗？

### ISSUE THREAD

**Issue by zhanghongwei** [alibaba/MNN#2496]
请问使用GPU时生成Cache文件时，cache文件未加密的话有技术泄密风险吗？

**Comment by bitxsw93** [comment]
Cache可能有kernel部分信息，不过你可以多个模型使用同一个cache文件，相当于不同模型cache并集成一个文件。增加还原单个模型cache的难度。

**Comment by jxt1234** [comment]
这部分与模型本身关联很小，主要与 MNN 的 GPU 代码相关，也不太可能通过 cache 反推模型结构。泄密风险较低。
