### ISSUE TITLE
FloatToInt8和Int8ToFloat耗时较多

### ISSUE THREAD

**Issue by songyonger** [alibaba/MNN#2499]
# 平台(如果交叉编译请再附上交叉编译目标平台): 
# Platform(Include target platform as well if cross-compiling): 
交叉编译目标平台: android armv82

# Github版本:
# Github Version:
551974a6d741d7f5c927b8039df5632933cb5491

# 编译方式:
# Compiling Method
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_ARM82=ON \
-DMNN_BUILD_TOOLS=ON \
-DANDROID_NATIVE_API_LEVEL=android-22  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4

bisenet网络int8量化后timeprofile：
Sort by time cost !
Node Type            	Avg(ms)   	%         	Called times 	Flops Rate 	
Reduction            	0.145100  	0.504539  	4.000000     	0.000093   	
Pooling              	0.147700  	0.513580  	1.000000     	0.241048   	
Interp               	0.173800  	0.604334  	2.000000     	0.066958   	
ReLU                 	0.860100  	2.990723  	29.000000    	0.713130   	
BinaryOp             	0.922400  	3.207352  	14.000000    	0.241048   	
Int8ToFloat          	1.674300  	5.821845  	37.000000    	1.001119   	
ConvolutionDepthwise 	1.678200  	5.835405  	13.000000    	1.674518   	
UnaryOp              	2.086900  	7.256531  	4.000000     	0.214335   	
FloatToInt8          	4.171602  	14.505418 	157.000000   	2.564678   	
Raster               	4.850299  	16.865370 	133.000000   	0.944199   	
Convolution          	12.048683 	41.895462 	148.000000   	92.339020  	
total time : 28.758923 ms, total mflops : 262.525208 
main, 147, cost time: 302.013000 ms

全精度模型timeprofile：
Sort by time cost !
Node Type            	Avg(ms)   	%         	Called times 	Flops Rate 	
Reduction            	0.146300  	0.603591  	4.000000     	0.000096   	
Pooling              	0.162000  	0.668364  	1.000000     	0.249961   	
Interp               	0.265200  	1.094137  	2.000000     	0.069434   	
BinaryOp             	0.368700  	1.521148  	14.000000    	0.249961   	
ReLU                 	0.864300  	3.565847  	29.000000    	0.739498   	
ConvolutionDepthwise 	0.923100  	3.808440  	13.000000    	1.736433   	
Raster               	1.826300  	7.534777  	133.000000   	0.979110   	
UnaryOp              	2.072200  	8.549289  	4.000000     	0.222260   	
Convolution          	17.610151 	72.654305 	148.000000   	95.753212  	
total time : 24.238276 ms, total mflops : 253.164551 
main, 147, cost time: 253.386017 ms

模型中激活函数是LeakyReLU, 换成ReLU或者ReLU6之后FloatToInt8和Int8ToFloat耗时仍较多。在对mobilenet做int8量化时能够正常加速。

**Comment by jxt1234** [comment]
有可能是无法量化的算子较多导致转换多。2.6.0 新增了   Interp 和 Binary 的量化支持，可以更新后量化再试试，Unary 算子的量化还在支持中。
