### ISSUE TITLE
为什么使用mnncompress和test_mnn_offline_quant.py做8比特的量化，量化后模型大小不一样呢？

### ISSUE THREAD

**Issue by GuangyanZhang** [alibaba/MNN#2501]
1.使用test_mnn_offline_quant.py做8w8a的量化生成mnn大小从40M->11M。
2.使用mnncompress参考https://mnn-docs.readthedocs.io/en/latest/tools/compress.html?highlight. 的8w8a量化，生成mnn的大小40M->14M?
请问为什么会相差那么大？
补充下：我的模型存在conv1d，参数量挺大的！

**Comment by jxt1234** [comment]
用 MNNDump2Json 看一下，可能是 mnncompress 遗漏了一些算子（因为原始名字没匹配上）没有量化
