### ISSUE TITLE
MNN warpaffine is slower than OpenCV, why?

### ISSUE THREAD

**Issue by HonglinChu** [alibaba/MNN#2505]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
when i test MNN::CV::warpAffine function(C++ Version) on PC with CPU，it is slower than opencv（C++ version), why？ (MNN version 2.6.0), 

# Github版本:
# Github Version: 

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
```

**Comment by HonglinChu** [comment]
> 我在Mac本地测试的结果显示warpAffine比OpenCV快10倍。

你可以提供一下你的测试代码么？我测试所有所有MNN提供的类opencv的函数（如 resize），只要底层涉及到需要matrix转换和convert转换的都会比opencv慢（warpAffine）； 测试太小的图像差距不明显，可以输入1024x1024的图像试试，差距很大

**Comment by v0jiuqi** [comment]
> > 我在Mac本地测试的结果显示warpAffine比OpenCV快10倍。
> 
> 你可以提供一下你的测试代码么？我测试所有所有MNN提供的类opencv的函数（如 resize），只要底层涉及到需要matrix转换和convert转换的都会比opencv慢（warpAffine）； 测试太小的图像差距不明显，可以输入1024x1024的图像试试，差距很大

我直接编译运行的opencv_bench

**Comment by v0jiuqi** [comment]
我把源图像大小设置为1024x1024，目标图像大小设置为512x512，结果显示MNNCV的速度仍然比OpenCV快。测试代码提供给你：
![image](https://github.com/alibaba/MNN/assets/124856990/705d98e3-42e7-4f36-b9be-37872aa667ab)
将上述代码粘贴至opencv_benchmark.cpp的186行，然后在build目录下打开编译宏 cmake .. -DMNN_BUILD_OPENCV=ON -DMNN_OPENCV_BENCH=ON，然后编译运行:make -j8&&./opencv_bench 
我这里的运行结果如下:
![image](https://github.com/alibaba/MNN/assets/124856990/68aea565-bbc5-49ce-9914-a90d26eb2376)

**Comment by HonglinChu** [comment]
你的测试结果有个问题，为什么resize要慢很多，可以测试1000次取平均值看看
![image](https://github.com/alibaba/MNN/assets/11087575/e5cee5a9-e7a1-46f3-93e2-e988ee43e511)

**Comment by HonglinChu** [comment]
好的，我理解的是 MNN 中的resize和warpfine的核心实现是差不多的， 至于OpenCV中是如何实现的就不清楚了；另外，在MNN中resize操作在图像预处理的时候使用频率非常高，如果确实没有OpenCV的快，希望后续可以重点优化一下。

![image](https://github.com/alibaba/MNN/assets/11087575/c52c3809-932a-4921-a7e4-50338ddad36d)
![image](https://github.com/alibaba/MNN/assets/11087575/403cea49-4a1b-4219-8daf-0c7a56867939)
