### ISSUE TITLE
量化转模型assertion failed

### ISSUE THREAD

**Issue by wojiaoyanmin** [alibaba/MNN#2507]
命令：
quantized.out model.mnn quan.mnn imageInputConfig.json  
文件夹内容
![image](https://github.com/alibaba/MNN/assets/57952327/b734262e-d6ba-4bfb-a0e2-1a48abde8890)
出现错误
![259482f8111b78cfd40da478bf50074f_83329](https://github.com/alibaba/MNN/assets/57952327/71600087-454a-4f79-b720-391214cad7ae)
![image](https://github.com/alibaba/MNN/assets/57952327/e481a247-f944-4862-970b-313896e51b7d)

json文件内容：
{
    "format":"RGB",
    "mean":[
        127.5,
        127.5,
        127.5
    ],
    "normal":[
        127.5,
        127.5,
        127.5
    ],
    "width":256,
    "height":144,
    "path":"./images/",
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS",
    "input_type":"image",
    "debug":false
}

请问什么原因造成

**Comment by jxt1234** [comment]
这个 model 是不是已经用 weightQuantBits = 8 量化过的？

**Comment by wojiaoyanmin** [comment]
> 这个 model 是不是已经用 weightQuantBits = 8 量化过的？

不是，是float32的原模型

**Comment by jxt1234** [comment]
可能是 images 目录下面有非图片的文件，检查一下看看
