### ISSUE TITLE
pytorch训练的分割算法，MNN推理结果错误

### ISSUE THREAD

**Issue by happyday-lkj** [alibaba/MNN#2508]
第一次使用mnn，如果问的问题低级，也请回答一下：
       如题：首先，使用pytorch训练了一个分割算法，然后转成ONNX模型，最后转成MNN模型，
但是MNN的推理结果错误。需要说明的是，转ONNX的时候，模型已经进行了max以及squeeze
操作，所以最终模型的输出就是 H x W 大小，而且里面的元素只有0 和1 两种。但是目前模型的
输出只有0。

      工程总体参考 [yolov5_mnn](https://github.com/tymanman/yolov5_mnn)，图片采用OpenCV
进行读取，然后进行resize以及pad处理(均值和方差已经放到了网络中，输入格式为BGR)，最后
将数据拷贝到网络中进行推理，最后，拿推理后的结果

**Comment by happyday-lkj** [comment]
[seg.zip](https://github.com/alibaba/MNN/files/12159202/seg.zip)
上述代码的压缩文件

**Comment by happyday-lkj** [comment]
参考另外一个 [链接](https://github.com/DefTruth/lite.ai.toolkit) 中yolov5的实现，
[seg2.zip](https://github.com/alibaba/MNN/files/12159392/seg2.zip)

**Comment by happyday-lkj** [comment]
![2023-07-25_17-52](https://github.com/alibaba/MNN/assets/18274241/348bed6a-c161-4fa6-9cec-f490d9b69dc4)
使用 testMNNFromOnnx.py测试结果

**Comment by happyday-lkj** [comment]
solved

**Comment by yangy996** [comment]
> ，拿推理后的结

怎么解决的呢？我用新版2.7.1的也出现这个问题，老版2.5.0正常

**Comment by happyday-lkj** [comment]
前处理参考网上其它的实现方法

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月23日 20:37 |
| 收件人 | alibaba/MNN ***@***.***> |
| 抄送人 | linkejun ***@***.***>,
State ***@***.***> |
| 主题 | Re: [alibaba/MNN] pytorch训练的分割算法，MNN推理结果错误 (Issue #2508) |

，拿推理后的结

怎么解决的呢？我用新版2.7.1的也出现这个问题，老版2.5.0正常
