### ISSUE TITLE
ONNX::LayerNormalization Converted Failed

### ISSUE THREAD

**Issue by ThisisBillhe** [alibaba/MNN#2509]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
 Platform(Include target platform as well if cross-compiling):  x86-64

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
Comment = d8266f9697650d4a90cccea337c2ae3ee070c373
Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
mkdir build && cd build
cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_TORCH=ON
make -j8

# 编译日志:
# Build Log:
[100%] Built target TestPassManager
```
粘贴在这里
Paste log here or pastebin
```
基于部署ChatGLM的[案例](https://qnmlgb.tech/articles/64ae635f48efc8e43dc6517e/)，通过onnx转换layernorm应该是支持的，请问如何解决？

**Comment by jxt1234** [comment]
layernorm 是 onnx 较新的算子，可以先在导出 onnx 时把 opset 设低些，比如 11 ，就不会产生 layernorm

**Comment by ThisisBillhe** [comment]
感谢！
