### ISSUE TITLE
请问使用opencl gpu后端时 有什么方法加快生成cache的时间？  除了backendConfig 一些配置项的方法

### ISSUE THREAD

**Issue by zhanghongwei** [alibaba/MNN#2510]
请问使用opencl gpu后端时 有什么方法加快生成cache的时间？  除了backendConfig 一些配置项的方法

**Comment by Qxinyu** [comment]
这个我们也在优化当中，现在你可以设置ScheduleConfig中的mode参数来控制tune的模式，可以加快生成cache时tunning的时间，具体的mode设置值可以看下MNNForwardType.h文件里的MNNGpuMode。

**Comment by Qxinyu** [comment]
这个可能会对推理的性能有点影响。
