### ISSUE TITLE
VARP 创建大尺寸变量时，申请内存失败。

### ISSUE THREAD

**Issue by CVRS-CJH** [alibaba/MNN#2512]
当我使用 
`VARP varpPref = _Input({ 1, 100, 3840, 2560 }, MNN::Express::NCHW); `
创建变量时，报错：
```
Error for D:\ThirdParty\MNN2.5.1\MNN\express\Expr.cpp, 166
Assertion failed: res, file D:\ThirdParty\MNN2.5.1\MNN\express\Expr.cpp, line 166。
```
查看源代码是allocMemoryForHostTensor函数报错。
![image](https://github.com/alibaba/MNN/assets/22935687/6cc99d77-58e6-4f4c-ad28-03f38c2910d9)
请问这个有解决办法吗？谢谢。

**Comment by jxt1234** [comment]
这个可能是内存不足了

**Comment by yangy996** [comment]
内存不够的时候，可不可以抛出一个异常，而不是让应用崩溃呢？

**Comment by yangy996** [comment]
> 内存不够的时候，可不可以抛出一个异常，而不是让应用崩溃呢？

内存不足时，可否先抛出一个异常，等下次内存足够时在调用？一直崩溃导致的体验很差
