### ISSUE TITLE
iOS not working the same as Android

### ISSUE THREAD

**Issue by notha99y** [alibaba/MNN#2514]
# Background
I have written some C++ code running RetinaFace on MNN and I am using JNI to get it to run on Android and Objective C++ to get it to run on iOS

The MNN libraries I am using are from this release https://github.com/alibaba/MNN/releases/tag/2.4.0

# Problem 
I managed to get it running well on Android, but for iOS I am facing the problem where the detected Face Boxes have a consistent Face width and height which are powers of 2, e.g. (16, 32, 64, 128)

The xcode version I am using is 14.3.1  and I have added the MNN.framework.

I have verified the input to be the same when running on Android and iOS.

This is the output of the face detections. 
![image](https://github.com/alibaba/MNN/assets/29172421/15f7b271-f3a0-4c23-a415-544a76b7bf84)

# Code
This is the cpp code using MNN which works in android
```cpp
int RetinaFace::DetectFace(unsigned char *data, int width, int height, int channel, vector<FaceInfo> &faces) {
    auto inputTensor = net_->getSessionInput(session_, "input0");
    net_->resizeTensor(inputTensor, {1, 3, width_, height_});
    net_->resizeSession(session_);
    auto nchwInputTensor = new MNN::Tensor(inputTensor, MNN::Tensor::CAFFE);
    Utils::convertBufferToTensor(data, nchwInputTensor, width_, norm_vals_, mean_vals_);
    inputTensor->copyFromHostTensor(nchwInputTensor);
    net_->runSession(session_);

    delete nchwInputTensor;
    std::map<std::string, MNN::Tensor*> outputTensors = net_->getSessionOutputAll(session_);
    auto outputTensor = net_->getSessionOutput(session_, "output_bbox");
    auto nchwOutputTensor = new MNN::Tensor(outputTensor, MNN::Tensor::CAFFE);
    outputTensor->copyToHostTensor(nchwOutputTensor);
    auto output_bbox = nchwOutputTensor->host<float>();

    auto output2Tensor = net_->getSessionOutput(session_, "output_conf");
    auto nchwOutput2Tensor = new MNN::Tensor(output2Tensor, MNN::Tensor::CAFFE);
    output2Tensor->copyToHostTensor(nchwOutput2Tensor);
    auto output_conf= nchwOutput2Tensor->host<float>();
// more code
}
```

**Comment by jxt1234** [comment]
How does the session create?

**Comment by notha99y** [comment]
```cpp
int RetinaFace::Initial() {
    net_ = MNN::Interpreter::createFromBuffer(retinaface_160_mnn, retinaface_160_mnn_len);
    MNN::ScheduleConfig netConfig;

    netConfig.type      = MNN_FORWARD_CPU;
    netConfig.numThread = 4;

    session_ = net_->createSession(netConfig);
    return 0;
}
```

**Comment by jxt1234** [comment]
Try update to 2.6.0 . If still error. Can you upload your model for us to check?

**Comment by notha99y** [comment]
tried and still same problem. shared the model with you on your email

**Comment by notha99y** [comment]
hi @jxt1234 were you able to run it?

**Comment by jxt1234** [comment]
1. Can't reproduce. the shape compute will not diff from ios and android.
2. Try export onnx with dynamic axes and reconvert mnn with new mnn converter

**Comment by jxt1234** [comment]
You can dump the mnn's output to output_bbox.txt and check.
The error may exists in the process which turn output_bbox to screen cord.

**Comment by notha99y** [comment]
yes the output shape is the same as android, but the values inside the tensor is different.  `auto output_bbox = nchwOutputTensor->host<float>();`

> You can dump the mnn's output to output_bbox.txt and check.
> The error may exists in the process which turn output_bbox to screen cord.
the process is the same code as they are written in C++. 

> Try export onnx with dynamic axes and reconvert mnn with new mnn converter
What do you mean by this?

**Comment by jxt1234** [comment]
We can't reproduce the problem. In simple ios project, the result from ios machine is the same with android. You can make a simple ios project for us to reproduce it?

**Comment by notha99y** [comment]
I just managed to fix the issue but I am not too sure why it works. What I did was to delete the new MNN::Tensors at the end where I copy the values to variables. 

From the above code I change to the following

```cpp
int RetinaFace::DetectFace(unsigned char *data, int width, int height, int channel, vector<FaceInfo> &faces) {
    auto inputTensor = net_->getSessionInput(session_, "input0");
    net_->resizeTensor(inputTensor, {1, 3, width_, height_});
    net_->resizeSession(session_);
    auto nchwInputTensor = new MNN::Tensor(inputTensor, MNN::Tensor::CAFFE);
    Utils::convertBufferToTensor(data, nchwInputTensor, width_, norm_vals_, mean_vals_);
    inputTensor->copyFromHostTensor(nchwInputTensor);
    net_->runSession(session_);

    std::map<std::string, MNN::Tensor*> outputTensors = net_->getSessionOutputAll(session_);
    auto outputTensor = net_->getSessionOutput(session_, "output_bbox");
    auto nchwOutputTensor = new MNN::Tensor(outputTensor, MNN::Tensor::CAFFE);
    outputTensor->copyToHostTensor(nchwOutputTensor);
    auto output_bbox = nchwOutputTensor->host<float>();

    auto output2Tensor = net_->getSessionOutput(session_, "output_conf");
    auto nchwOutput2Tensor = new MNN::Tensor(output2Tensor, MNN::Tensor::CAFFE);
    output2Tensor->copyToHostTensor(nchwOutput2Tensor);
    auto output_conf= nchwOutput2Tensor->host<float>();
// more code
    // create a variable 
    float *out_loc = new float[length*4];
    // some code to assign the output of output_box into out_loc*
    // release memory from the heap
    delete nchwInputTensor;
    delete nchwOutputTensor;
    delete nchwOutput2Tensor
}
```

I am not sure why but could it be due to the differences in the way the different OS release memories from the heap?
