### ISSUE TITLE
第一次resize推理结果正确，第二次resize推理后获取outputTensor.shape崩溃

### ISSUE THREAD

**Issue by zhiyaotl** [alibaba/MNN#2515]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
x86-64 linux

# Github版本:
Tag 2.6.0

# 编译方式:
mkdir build; cd build; cmake .. ; make

# 问题描述
尝试了MNN 1.2.10没有问题。MNN 2.4.0，MNN 2.5.0 第二次resize推理后获取outputTensor.shape不会崩溃，但输出全0。

**Comment by jxt1234** [comment]
请附上可复现的工程环境

**Comment by zhiyaotl** [comment]
用MNN 2.6.0编译的MNNConvert重转一下模型，可以跑通了。谢谢你的回复。
