### ISSUE TITLE
调用Opencl模式的createSession时崩溃

### ISSUE THREAD

**Issue by hk19941214** [alibaba/MNN#2517]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Windows

# Github版本:
使用直接编译好的压缩文件 mnn_2.5.0_windows_x64_cpu_opencl.zip

# 编译方式:
直接下载

# 崩溃函数：
调用Opencl模式的createSession时崩溃

# 崩溃堆栈：

**Comment by bitxsw93** [comment]
这个堆栈看不出有效信息，更新到MNN最新版本。用debug版本看下堆栈，或者使用源码编译复现下crash堆栈。
