### ISSUE TITLE
在推理时，如何使得输入tensor的值在Device端比如GPU上不被修改

### ISSUE THREAD

**Issue by YingkunZhou** [alibaba/MNN#2519]
尝试过使用config.saveTensors，但看起来没有用

**Comment by jxt1234** [comment]
需要自行分配输入内存可以用 setSessionMode(Session_Input_User) ，不过不推荐。
一般是多个网络串联执行吧，建议改成 Module API ，默认输入不会拷贝

**Comment by whyb** [comment]
请教 @jxt1234  我有模型需要input 2个Tensor，但有1个Tensor始终数据是一成不变的，

我现在的做法是将这个不变的buffer备份一份存在cv::Mat中，每推理一次都调用 `MNN::CV::ImageProcess::convert()` 将其转换成Tensor，想进行优化，避免重复转换和上传显存，尝试过优化的办法：

调用 `MNN::Tensor::clone(backupTensor, true);` 存一份放在成员变量中，每次推理再clone出来，发现没有任何效果。

后来发现是clone并没有实现深拷贝
![圖片](https://github.com/alibaba/MNN/assets/2672931/209429bb-53f2-4480-900e-7b76be8b1fcd)

还尝试过把Session API改用Module API，卡在了Module没有类似Session中的getSessionOutput的函数用来创建Tensor，而几乎都是  `MNN::Express::_Input({ 1, 3, 192, 192 }, MNN::Express::NCHW, halide_type_of<float>());` 和  `varp->writeMap<float>()` 填充数据，发现即便是用VARP内部还是存的Tensor，始终都绕不过创建Tensor这一步。

所以带着很大的疑惑来发的这份留言~

**Comment by YingkunZhou** [comment]
感谢，我再看看

**Comment by jxt1234** [comment]
> 请教 @jxt1234 我有模型需要input 2个Tensor，但有1个Tensor始终数据是一成不变的，
> 
> 我现在的做法是将这个不变的buffer备份一份存在cv::Mat中，每推理一次都调用 `MNN::CV::ImageProcess::convert()` 将其转换成Tensor，想进行优化，避免重复转换和上传显存，尝试过优化的办法：
> 
> 调用 `MNN::Tensor::clone(backupTensor, true);` 存一份放在成员变量中，每次推理再clone出来，发现没有任何效果。
> 
> 后来发现是clone并没有实现深拷贝 ![圖片](https://user-images.githubusercontent.com/2672931/260352291-209429bb-53f2-4480-900e-7b76be8b1fcd.png)
> 
> 还尝试过把Session API改用Module API，卡在了Module没有类似Session中的getSessionOutput的函数用来创建Tensor，而几乎都是 `MNN::Express::_Input({ 1, 3, 192, 192 }, MNN::Express::NCHW, halide_type_of<float>());` 和 `varp->writeMap<float>()` 填充数据，发现即便是用VARP内部还是存的Tensor，始终都绕不过创建Tensor这一步。
> 
> 所以带着很大的疑惑来发的这份留言~

Module API 是会创建 Tensor ，不过不会做内存拷贝。用 Module API 可以固定不变的那个输入变量，也就是用同一个 VARP 反复传入。
