### ISSUE TITLE
ONNX模型转换缺失权重数据，导致CUDA后端运行时出现内存错误

### ISSUE THREAD

**Issue by lucaslv404** [alibaba/MNN#2520]
# 平台

- X64
- Microsoft Windows 10 企业版 10.0.19045 内部版本 19045
- CUDA:10.2
- NVIDIA Driver: 511.65
- GPU: GTX 1080 Ti

# Github版本:
# Github Version:

tag: `2.6.1`
commit: `43445b7e2084602d6823d13cb2867f83dc76a555`

# 现象

1. 使用testMNNFromOnnx.py转换ONNX模型，CPU测试结果`TEST_SUCCESS`
2. 将生成的convert_cache.mnn放到benchmark中用CUDA后端运行，发生crash，用VS调试，定位到在session create时为这个op分配内存时发生空指针异常
![image](https://github.com/alibaba/MNN/assets/46597668/446a6ad5-2c54-43e8-a5ef-9b175c8aa7ad)
3. 用netron查看对应的conv op，发现转换的mnn模型中权重是空的
![image](https://github.com/alibaba/MNN/assets/46597668/8cc0fde0-0ca0-4c1d-8c4a-fa453cf83bd9)

# 疑问

1. 出现`Tensor data is empty`是符合预期的吗？
2. 在缺少权重数据的情况下，CPU为何可以正常推理，并产生正确结果？
3. CUDA后端crash的问题该如何解决？

**Comment by jxt1234** [comment]
1. 这个模型应该是进行了压缩 (int8 /. fp16 / 稀疏等)，检查一下你转换模型时使用的参数。如果什么参数都没加的话可能是模型权重0较多触发了稀疏压缩，模型转换时加上 --detectSparseSpeedUp 0 避免稀疏压缩即可
2. 看上去 cuda 后端在加载稀疏权重的卷积时出错了，我们查一下

**Comment by lucaslv404** [comment]
模型权重确实有许多0，加上--detectSparseSpeedUp 0问题解决了，使用CUDA后端推理不再出现崩溃，非常感谢！
