### ISSUE TITLE
哪个地方可以修改pymnn的依赖选项

### ISSUE THREAD

**Issue by cj1820147** [alibaba/MNN#2522]
ubuntu 18.04编译pymnn，在执行python3.7 setup.py install --version 2.2.2时，出现如下错误
`Processing dependencies for MNN==2.2.2
Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
Reading https://pypi.org/simple/urllib3/
/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
Downloading https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl#sha256=f5321fbe4bf3fefa0efd0bfe7fb14e90909eb62a48ccda331726b4319897dd5e
Best match: urllib3 1.25.11
Processing urllib3-1.25.11-py2.py3-none-any.whl
Installing urllib3-1.25.11-py2.py3-none-any.whl to /usr/lib/python3.7/site-packages
Adding urllib3 1.25.11 to easy-install.pth file

Installed /usr/lib/python3.7/site-packages/urllib3-1.25.11-py3.7.egg
error: urllib3 1.25.11 is installed but urllib3<2,>=1.26.2 is required by {'elastic-transport'}`

很明显这要求urllib3要>1.26.2，但是执行上述代码后，会自动Searching for urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1后安装urllib3 1.25.11，并且这是通过setup安装的，我通过pip安装其他版本的，并不能生效。这导致安装的版本不符合要求，应该如何进行修改

**Comment by cj1820147** [comment]
ok,解决了

**Comment by jxt1234** [comment]
depend_pip_packages 保留一个 numpy 就可以，这个还没有修改

**Comment by cj1820147** [comment]
解决！
