### ISSUE TITLE
MNN中GatherV2反向传播的问题

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2527]
我在实现一个Embedding的Module，其中有一个操作调用GatherV2算子。
代码类似于
`VARP y = _GatherV2(weight, x)`

我现在想获取反向传播后 x变量 对应的梯度，但是在OpGrad.cpp的grad()函数里面的backwardMap里没有存储x->expr().first所对应的梯度张量，请问是因为_GatherV2不支持梯度计算，还是因为x的变量类型是int呀？非常感谢

**Comment by jxt1234** [comment]
1. int 类型变量没有梯度
2. 部分情况下的 GatherV2 不支持梯度计算，但基于几何计算分解后可以。设置 expr 的延迟计算模式为 CONTENT ，再调 _GatherV2 ，可以计算出来梯度。
