### ISSUE TITLE
Arm上import MNN时，出现ModuleNotFoundError: No module named '_mnncengine'

### ISSUE THREAD

**Issue by cj1820147** [alibaba/MNN#2529]
MNN version:2.2.2
python version: python3.7
当我编译完成pymnn时，尝试使用import MNN时，出现了：
`File "/home/ubuntu/MNN-2.2.2/pymnn/pip_package/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
ModuleNotFoundError: No module named '_mnncengine'
`
我并没有在issue中看到有类似的问题被提出，请问应该如何解决这个问题

**Comment by cj1820147** [comment]
已解决

**Comment by Magic-meet** [comment]
> 已解决

您好，我也遇到了一样的问题，请问是如何解决的？
