### ISSUE TITLE
getSessionOutput的返回结果不正确

### ISSUE THREAD

**Issue by zeyuanlicbpm** [alibaba/MNN#253]
在Linux下：
sess = Net_->createSession(config);
p_input = Net_->getSessionInput(sess, NULL);
p_output = Net_->getSessionOutput(sess, NULL);
std::vector<int> inputDims = {1, 3, WIDTH, HEIGHT};
Net_->resizeTensor(p_input, inputDims);
Net_->resizeSession(sess);
pretreat_data->convert(img.data, WIDTH, HEIGHT, 0, p_input);
Net_->runSession(sess);
float* feat_ptr = p_output->host<float>();
这份代码是正确的能够正确运行；但是在Android环境下，p_output中host（）返回的feat_ptr这个指针是nullptr；
原因是什么呢？

**Comment by li-qing** [comment]
使用GPU backend了？

**Comment by li-qing** [comment]
输出参考：https://www.yuque.com/mnn/cn/output
如果是GPU，直接取host就是nullptr。
