### ISSUE TITLE
GAT CPU比pytorch onnxruntime慢很多

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#2530]
# 平台(如果交叉编译请再附上交叉编译目标平台):  win x64 cpu

# Github版本: 2.5.3

# 编译方式: cmake

具体耗时如下表：
![MNN pytorch onnx_time](https://github.com/alibaba/MNN/assets/34120042/92595225-6974-4b7c-8819-f3f981250cbd)

**Comment by v0jiuqi** [comment]
能否提供一下模型

**Comment by jxt1234** [comment]
2.7.2 部分解决，目前单线程慢 20% 左右
