### ISSUE TITLE
armv7和armv8 平台下的so体积差异较大, 请问怎么回事

### ISSUE THREAD

**Issue by 10061100** [alibaba/MNN#2531]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

交叉编译平台: m1 mac 上 开启的amd64 docker ubuntu
交叉编译目标平台: Linux  armv7a cpu 和 armv8 cpu

# Github版本: fa653d7bc5d8b3e1b003baae2bb829ec132a3892
# Github Version: fa653d7bc5d8b3e1b003baae2bb829ec132a3892

# 编译方式:
# Compiling Method

/usr/bin/cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
    -DCMAKE_C_COMPILER=/usr/lib/qz_tools/bin/aarch64-openwrt-linux-gcc \
    -DCMAKE_CXX_COMPILER=/usr/lib/qz_tools/bin/aarch64-openwrt-linux-g++ \
    -DCMAKE_INSTALL_PREFIX=./armv8
编译链下载地址: https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar.xz

/usr/bin/cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_VERSION=1 \
    -DCMAKE_SYSTEM_PROCESSOR=armv7 \
    -DCMAKE_C_COMPILER=/tmp/armv7/bin/arm-linux-gnueabihf-gcc \
    -DCMAKE_CXX_COMPILER=/tmp/armv7/bin/arm-linux-gnueabihf-g++ \
    -DCMAKE_INSTALL_PREFIX=./armv7
编译链下载地址: https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
armv8体积: 
![image](https://github.com/alibaba/MNN/assets/5662369/2e485612-d41e-488a-b58f-59bd78077176)

armv7体积
![image](https://github.com/alibaba/MNN/assets/5662369/8c1ae80c-c05c-4dd0-accc-340bc5613048)

两者CMakeFile中的参数都是一致的, 但是编译出来的so大小相差很大, 两者都没有开启 MNN_BUILD_MINI, 如果开启了的话,  armv7依然有40m左右, 还是相差很大.

**Comment by jxt1234** [comment]
估计和编译工具链里面的参数相关，额外加一下 set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -s")

**Comment by 10061100** [comment]
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -s")  完美解决
