### ISSUE TITLE
在x64 linux环境下量化的模型，arm android库无法加载(windows库可以加载)

### ISSUE THREAD

**Issue by yang20091116** [alibaba/MNN#2532]
安卓库编译版本：mnn-master
安卓硬件：rk3399
安卓库编译ndk版本：r18b
安卓编译方式：../build_64.sh -DMNN_BUILD_SHARED_LIBS=false
此库调用非量化模型是正常的

量化方法：
量化用版本：mnn-master
量化环境：x64 linux
量化编译方式：
         option(MNN_BUILD_QUANTOOLS "Build Quantized Tools or not" ON)
        cmake .. -DMNN_BUILD_CONVERTER=true -DCMAKE_INSTALL_PREFIX=../mnn-master_x64_linux/install -DMNN_BUILD_SHARED_LIBS=false
量化指令：./quantized.out ***.mnn ***_quant.mnn ***.json
此量化模型在windows 库上运行正常，虽然正确率降低很多
json内容：
{
    "format":"RGB",
    "mean":[
        0,
        0,
        0
    ],
    "normal":[
        0.00392157,
        0.00392157,
        0.00392157
    ],
    "center_crop_h":0.95,
    "center_crop_w":0.95,
    "width":416,
    "height":32,
    "path":"../images_e",
    "used_sample_num":500,
    "feature_quantize_method":"KL",
    "weight_quantize_method":"MAX_ABS",
    "feature_clamp_value":127,
    "weight_clamp_value":127,
    "batch_size":1,
    "quant_bits":8,
    "skip_quant_op_names":[
        "skip_quant_op_name1", "skip_quant_op_name2"
    ],
    "input_type":"image",
    "debug":false
}

windows库编译：(参考)
windows库版本：mnn-master
vs工具：2017
windows编译方式：
1.打开 VS2017 x64本机工具命令提示符
2.cd E:\MNN-master\3rd_party\flatbuffers
3.mkdir build && cd build
4.cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
5.ninja
6.管理员身份打开 VS2017 x64本机工具命令提示符
7.cd E:\MNN-master
8.powershell set-executionpolicy -executionpolicy unrestricted
9.powershell ./schema/generate.ps1
10.powershell .\package_scripts\win\build_lib.ps1 -path MNN-CPU/

**Comment by jxt1234** [comment]
无法加载的log 是什么? MNN 模型是平台无关的

**Comment by yang20091116** [comment]
没有任何异常信息，唯独前传完了得不到结果
-DMNN_USE_LOGCAT=true
也没有log信息
