### ISSUE TITLE
Mac M1芯片 编译MNN-Converter模型转换工具失败 error: use of undeclared identifier '__builtin_ia32_readeflags_u3

### ISSUE THREAD

**Issue by Qinlong275** [alibaba/MNN#2536]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
mkdir build && cd build && cmake .. -DMNN_BUILD_CONVERTER=true && make

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
-- Build files have been written to: /Users/qinlong/aiInterpret/MNN/build
Scanning dependencies of target MNNSSE
[  1%] Building CXX object CMakeFiles/MNNSSE.dir/source/backend/cpu/x86_x64/sse/GemmCommon.cpp.o
clang: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.cpp:10:
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/FunctionSummary.hpp:12:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/x86intrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:200:10: error: use of undeclared identifier '__builtin_ia32_readeflags_u32'
  return __builtin_ia32_readeflags_u32();
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:206:3: error: use of undeclared identifier '__builtin_ia32_writeeflags_u32'
  __builtin_ia32_writeeflags_u32(__f);
  ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:288:10: error: use of undeclared identifier '__builtin_ia32_crc32qi'
  return __builtin_ia32_crc32qi(__C, __D);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:309:10: error: use of undeclared identifier '__builtin_ia32_crc32hi'; did you mean '__builtin_arm_crc32h'?
  return __builtin_ia32_crc32hi(__C, __D);

```
粘贴在这里
Paste log here or pastebin
```

**Comment by Qinlong275** [comment]
在Cmakelists中手动添加了
add_definitions(-D__x86_64__)宏定义后又有新的错误：

Scanning dependencies of target MNNSSE
[  1%] Building CXX object CMakeFiles/MNNSSE.dir/source/backend/cpu/x86_x64/sse/GemmCommon.cpp.o
clang: warning: argument unused during compilation: '-msse4.1' [-Wunused-command-line-argument]
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.cpp:9:
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.hpp:11:
In file included from /Users/qinlong/aiInterpret/MNN/include/MNN/MNNDefine.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/assert.h:44:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/stdlib.h:93:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/stdlib.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/wait.h:186:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/machine/endian.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/i386/endian.h:101:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/_endian.h:130:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/_OSByteOrder.h:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/arm/OSByteOrder.h:15:1: error: redefinition of '_OSSwapInt16'
_OSSwapInt16(
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/i386/_OSByteOrder.h:46:1: note: previous definition is here
_OSSwapInt16(
^
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.cpp:9:
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.hpp:11:
In file included from /Users/qinlong/aiInterpret/MNN/include/MNN/MNNDefine.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/assert.h:44:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/stdlib.h:93:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/stdlib.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/wait.h:186:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/machine/endian.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/i386/endian.h:101:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/_endian.h:130:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/_OSByteOrder.h:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/arm/OSByteOrder.h:25:1: error: redefinition of '_OSSwapInt32'
_OSSwapInt32(
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/i386/_OSByteOrder.h:55:1: note: previous definition is here
_OSSwapInt32(
^
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.cpp:9:
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.hpp:11:
In file included from /Users/qinlong/aiInterpret/MNN/include/MNN/MNNDefine.h:12:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/assert.h:44:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/stdlib.h:93:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/stdlib.h:66:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/wait.h:186:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/machine/endian.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/i386/endian.h:101:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/sys/_endian.h:130:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/_OSByteOrder.h:80:
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/arm/OSByteOrder.h:41:1: error: redefinition of '_OSSwapInt64'
_OSSwapInt64(
^
/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include/libkern/i386/_OSByteOrder.h:70:1: note: previous definition is here
_OSSwapInt64(
^
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/GemmCommon.cpp:10:
In file included from /Users/qinlong/aiInterpret/MNN/source/backend/cpu/x86_x64/sse/FunctionSummary.hpp:12:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/x86intrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:187:10: error: use of undeclared identifier '__builtin_ia32_readeflags_u64'
  return __builtin_ia32_readeflags_u64();
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:193:3: error: use of undeclared identifier '__builtin_ia32_writeeflags_u64'
  __builtin_ia32_writeeflags_u64(__f);
  ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:288:10: error: use of undeclared identifier '__builtin_ia32_crc32qi'
  return __builtin_ia32_crc32qi(__C, __D);
         ^
/Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/ia32intrin.h:309:10: error: use of undeclared identifier '__builtin_ia32_crc32hi'; did you mean '__builtin_arm_crc32h'?
  return __builtin_ia32_crc32hi(__C, __D);

**Comment by jxt1234** [comment]
cmake 加上 -DCMAKE_OSX_ARCHITECTURES=arm64 看下

**Comment by Qinlong275** [comment]
> cmake 加上 -DCMAKE_OSX_ARCHITECTURES=arm64 看下

**Comment by Qinlong275** [comment]
> 



> cmake 加上 -DCMAKE_OSX_ARCHITECTURES=arm64 看下

Cmakelists中添加了set(CMAKE_OSX_ARCHITECTURES "arm64") 后可以了，Cool~
