### ISSUE TITLE
windows10 open MNN_BUILD_QUANTOOLS build error

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#254]
![image](https://user-images.githubusercontent.com/24749356/63399362-df7cfd80-c402-11e9-9dec-30d2f953ae2d.png)

**Comment by li-qing** [comment]
尝试一下tag 0.2.0.9 量化工具相关编译已经修正

**Comment by xiexuliunian** [comment]
好的，谢谢大大

**Comment by xiexuliunian** [comment]
git pull到最新代码，然后重新编译。
![image](https://user-images.githubusercontent.com/24749356/64160519-ab77f280-ce6e-11e9-91c4-22bebbd56f7a.png)

**Comment by li-qing** [comment]
schema有更新 需重新generate header

**Comment by xiexuliunian** [comment]
嗯，编译成功了。谢谢离青大大，我还有个issue，您帮忙看看吧。#287
