### ISSUE TITLE
提问：在哪里能找到`AliNNModel`?

### ISSUE THREAD

**Issue by zihaomu** [alibaba/MNN#2541]
想测试一下这个脚本：[./pymnn/test/model_test.py](https://github.com/alibaba/MNN/blob/master/pymnn/test/model_test.py)，请问在哪里能下载`AliNNModel`?

**Comment by jxt1234** [comment]
这个是内部回归测试用的模型库，不对外提供

**Comment by zihaomu** [comment]
@jxt1234 我们想接入MNN作为推理殷勤，有没有模型列表可以用来验证MNN推理的精度？
