### ISSUE TITLE
编译MNN源码，在RK3399板子上报错

### ISSUE THREAD

**Issue by zhyy2345** [alibaba/MNN#2549]
[  5%] Built target MNNCore
[ 10%] Built target MNN_Arm82
[ 11%] Built target MNNUtils
[ 11%] Built target MNNMath
Scanning dependencies of target MNNARM64
[ 11%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S.o
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S: Assembler messages:
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S:650: Error: operand mismatch -- `mov v9.4s,v16.4s'
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S:650: Info:    did you mean this?
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S:650: Info:    	mov v9.8b, v16.8b
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S:650: Info:    other valid variant(s):
/home/lws/mnt/MNN-master/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S:650: Info:    	mov v9.16b, v16.16b
make[2]: *** [CMakeFiles/MNNARM64.dir/build.make:233: CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:488: CMakeFiles/MNNARM64.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by jxt1234** [comment]
临时先把 mov XX .4s  都换成 XX.16b 吧

**Comment by zhyy2345** [comment]
修改之后确实可以编译了，多谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/MNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月21日(星期一) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/MNN] 编译MNN源码，在RK3399板子上报错 (Issue #2549)





 
临时先把 mov XX .4s  都换成 XX.16b 吧

**Comment by jxt1234** [comment]
2.7.0 修正
