### ISSUE TITLE
转换工具安装报错

### ISSUE THREAD

**Issue by mamingjie-China** [alibaba/MNN#255]
![image](https://user-images.githubusercontent.com/52770436/63414118-bcb40e80-c42d-11e9-8d35-2d38ac48264d.png)
按照文档安装tensorflow转换工具，提示图片中所列错误，请问可能是什么原因？

**Comment by BokyLiu** [comment]
protobuf没装好,需要3.0以上的

**Comment by mamingjie-China** [comment]
> protobuf没装好,需要3.0以上的

装的是3.5.2版本的

**Comment by BokyLiu** [comment]
> > protobuf没装好,需要3.0以上的
> 
> 装的是3.5.2版本的

一般出这种问题都是库没链接好,你可以检查一下cmakelist,看到底链接上了没有

**Comment by ChisenZhang** [comment]
> > protobuf没装好,需要3.0以上的
> 
> 装的是3.5.2版本的

可能有多个版本 冲突了    例如python的protobuf包
