### ISSUE TITLE
yolov8推理demo

### ISSUE THREAD

**Issue by zhyy2345** [alibaba/MNN#2552]
通过yolov8.pt ->yolov8.onnx-> yolov8.mnn  (yolo export model=best.pt format=onnx ,    ./MNNConvert -f ONNX --modelFile yolov8.onnx --MNNModel yolov8.mnn --fp16 --bizCode MNN),这个yolov8.mnn 有没有推理demo 可以参考一下？

**Comment by jxt1234** [comment]
google 上搜有个 https://github.com/ZhouJiaHuan/yolo_deploy ，可以看看
