### ISSUE TITLE
2.6.2版本 + 2433 的bugfix，Vulkan Image模式（-DMNN_VULKAN_IMAGE=ON）的误差很小了，但是性能很差了，符合预期吗

### ISSUE THREAD

**Issue by cmelody999** [alibaba/MNN#2553]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
2.6.2版本 + https://github.com/alibaba/MNN/issues/2433 的bugfix（https://github.com/alibaba/MNN/pull/2542 ），Vulkan Image模式（-DMNN_VULKAN_IMAGE=ON）的误差很小了，但是性能很差了，符合预期吗
![image](https://github.com/alibaba/MNN/assets/5425469/2db4746d-c1f4-4458-9a5c-e01ad3b0dbb7)

**Comment by jxt1234** [comment]
precision 是?
建议优先用 OpenCL ，优化投入较多

**Comment by cmelody999** [comment]
16位的模型，cost是ms

**Comment by jxt1234** [comment]
运行性能与模型无关，主要是 precision 设的是 normal / high / low ?

**Comment by jxt1234** [comment]
有用 benchmark.out 测试过么？

**Comment by cmelody999** [comment]
backendConfig.precision = MNN::BackendConfig::Precision_Low

![image](https://github.com/alibaba/MNN/assets/5425469/d88764b3-62e3-4858-865e-bd4c080b44ef)

**Comment by cmelody999** [comment]
> 有用 benchmark.out 测试过么？

benchmark.out测试方法有文档么

**Comment by jxt1234** [comment]
https://mnn-docs.readthedocs.io/en/latest/tools/benchmark.html

**Comment by qiankl** [comment]
2.7.0 vulkan推理误差变小了，速度问题还没有解决是吗

**Comment by jxt1234** [comment]
这个模型到后面尺寸较大，被 vulkan image 拆成了很多份 image ，执行效率下降。速度问题由于 厂商加速相关扩展主要在 opencl ，mnn 主要基于 opencl 优化，建议都优先使用 opencl 。mnn vulkan 主要是启动性能上有优势。
