### ISSUE TITLE
模型推理分辨率为800*800的，同一个进程在推理800*800/2592*1944的opencv读取的图片时，800*800的物理内存占用比2592*1944的大，请问是怎么回事呢？

### ISSUE THREAD

**Issue by yy2yy** [alibaba/MNN#2554]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
armeabi-v7a

# Github版本:
# Github Version:
MNN2.5

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin

cmake -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
      -DCMAKE_TOOLCHAIN_FILE="${NDK_ROOT}/build/cmake/android.toolchain.cmake" \
      -DANDROID_NDK="${ANDROID_NDK_ROOT}" \
      -DCMAKE_INSTALL_PREFIX=../install \
      -DANDROID_ARM_NEON=ON \
      -DANDROID_ABI="armeabi-v7a" \
      -DANDROID_PLATFORM="android-19"    \
      -DBUILD_TESTING=OFF \
      -DMNN_HOME=$PWD/../3rdparty/MNN2.5/androidApi19 \
      -DANDROID_STL="c++_static" \
      -DOSTYPE=Linux \
      -DPC_JSON=ON \
      -DARCH="armeabi-v7a" \
      ..
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
同样一个进程采用MNN推理，模型的推理分辨率是800*800的，输入一个2592*1944的图片进行推理的时候，进程占用的物理内存是211M；如果直接输入一个800*800的图片，进程占用的物理内存却变成了227M。800*800的不用经过resize，不应该占用的物理内存变小吗？为什么反而占用的内存变大了呢？希望能帮忙解惑，谢谢！
```

**Comment by jxt1234** [comment]
可以用 getSessionInfo 查看内存

**Comment by jxt1234** [comment]
你是 resizeTensor -> resizeSession 调整了模型输入大小么？如果没有调整模型输入大小的话 MNN 占用的内存应该没有差距

**Comment by jxt1234** [comment]
ImageProcess convert 的目标 Tensor 的 dimensionformat 是? 可以用 windows 上内存分析工具看下是哪部分占用的么？

**Comment by jxt1234** [comment]
按理如果 tensor 的 dimensionFormat 不是 NCHW ，ImageProcess 所需的内存不会有区别

**Comment by yy2yy** [comment]
> 按理如果 tensor 的 dimensionFormat 不是 NCHW ，ImageProcess 所需的内存不会有区别

（1）目标Tensor 的 dimensionformat 是NCHW。
（2）NCHW为什么会有区别呢？有区别的话不应该是图越大占用内存越多，图越小占用内存越小吗？为什么相反呢？
（3）如果我读入这张大图（2592*1944），再把它cv::resize()成800*800，再经过process->convert，内存与大图送入process->convert中resize是一样的，不会变化；而绘图软件制作的800*800的图像送入，无论是否使用cv::resize，经过process->convert之后内存都会变大。

**Comment by jxt1234** [comment]
NCHW 需要增加一次 NC4HW4 到 NCHW 的拷贝，多申请 目标Tensor 量级的 NC4HW4 格式的大小。内存问题感觉和图像有关。ImageProcess 不会因为输入而多申请内存，有可能是系统是延迟分配内存，刚好 ImageProcess 是第一次读图像，产生内存的增量计算
