### ISSUE TITLE
MNN failed to build with "error C2143: syntax error: missing ')' before '('" with MSVC on Windows arm64ec

### ISSUE THREAD

**Issue by Luan-Novaes** [alibaba/MNN#2555]
MNN failed to build with "error C2143: syntax error: missing ')' before '('" with MSVC on Windows arm64ec. It can reproduce on latest version c442ff3 on master branch. Could you please help look at this issue?

**Versions and configuration:**
OS: Windows 10
VS: Visual Studio 2022(17.7.2)

**Repro steps:**

1. git clone https://github.com/alibaba/MNN.git
2. Open "x64 Native Tools Command Prompt for VS 2022"
3. mkdir build_arm64ec
4. cd build_arm64ec
5. cmake -G "Visual Studio 17 2022" -A arm64ec -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DMNN_USE_SSE=OFF ..
6. msbuild /m /p:Platform=arm64ec /p:Configuration=Release MNN.sln /t:Rebuild 

**Error info:**
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\softintrin.h(72,196): error C2143: syntax error: missing ')' before '(' [F:\gitP\MNN\build_arm64ec\MNNCore.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\softintrin.h(72,196): error C2059: syntax error: '(' [F:\gitP\MNN\build_arm64ec\MNNCore.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\softintrin.h(72,316): error C2059: syntax error: ')' [F:\gitP\MNN\build_arm64ec\MNNCore.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\softintrin.h(73,1): error C2143: syntax error: missing ';' before '{' [F:\gitP\MNN\build_arm64ec\MNNCore.vcxproj]
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um\softintrin.h(73,1): error C2447: '{': missing function header (old-style formal list?) [F:\gitP\MNN\build_arm64ec\MNNCore.vcxproj]

**Error log:**
[build.log](https://github.com/alibaba/MNN/files/12420096/build.log)

**Comment by jxt1234** [comment]
windows with arm64 arch ?

**Comment by jxt1234** [comment]
Does ninja work?

cmake .. -G ninja
ninja -j16

**Comment by Luan-Novaes** [comment]
When using the following command, the issue does not happen.

cmake -G Ninja -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64ec -DMNN_USE_SSE=OFF ..
ninja -j16

[build.log](https://github.com/alibaba/MNN/files/12429018/build.log)
