### ISSUE TITLE
MNN的OpenCL和CUDA算子支持列表在哪里可以查阅

### ISSUE THREAD

**Issue by CaiWeibo** [alibaba/MNN#2558]
请问MNN的OpenCL和CUDA算子支持列表在哪里可以查阅

**Comment by jxt1234** [comment]
OpenCL 和 CUDA 所支持的算子是经过几何计算分解后重定义的算子，与用户原始模型算子无法对应。
大部分情况是都支持的，即便不支持也会通过回退 CPU 的方式支持模型正确推理。
