### ISSUE TITLE
怎么把图像等比resize然后填充到固定长宽？

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#256]
如题，我用tensorflow的pad和tf.image的相关resize和pad函数都试了模型，tf.image的相关函数转换的时候会提示control_dependency这个不支持，上次提问有人说模型转换不对？tf.image相关的几个函数好像转换都有这个。 tf.pad转换的时候没有报错，跑的时候会提示 NC4HW4 don't support channel padding。
另外问一句，MNN支持可变输入吗？

**Comment by jxt1234** [comment]
MNN支持可变输入，建议直接用 mnn 的 resizeTensor -> resizeSession ，不要用 tensorflow 的 pad / image 中的 resize

**Comment by ChisenZhang** [comment]
> MNN支持可变输入，建议直接用 mnn 的 resizeTensor -> resizeSession ，不要用 tensorflow 的 pad / image 中的 resize

 mnn 的 resizeTensor -> resizeSession 可以达到等比缩放图像并把长宽填充到固定长度的作用是吗？

**Comment by jiarenyf** [comment]
Use opencv ...

**Comment by ChisenZhang** [comment]
> Use opencv ...

那不还得用opencv的库，代价太大了，想知道MNN库有没有函数可以实现这个

**Comment by jxt1234** [comment]
你的意思是图像预处理进行缩放以及pad填充0么
ImageProcess 里面 
Matrix 控制目标到源的位置变换实现缩放
config.wrap 设成 ZERO  就可以实现填充0的效果

**Comment by ltss1988** [comment]
有人用MNN图像预处理，实现了等比例缩放再pad填充到固定尺寸吗

**Comment by ChisenZhang** [comment]
> 有人用MNN图像预处理，实现了等比例缩放再pad填充到固定尺寸吗
	Matrix trans;
	// Dst -> [0, 1]
	float r = (float)(max(width, height) - 1) / (SCALE - 1);
	trans.setScale(r, r);
	////trans.setScale((float)(width - 1) / (size_w - 1), (float)(height - 1) / (size_h - 1));
	// Flip Y
	//trans.postScale(1.0, -1.0, 0.0, 0.5);
	//[0, 1] -> Src
	//trans.postScale(width, height);
	ImageProcess::Config config;
	config.filterType = BILINEAR;
	//float mean[3] = { 0.0f, 0.0f, 0.0f };
	//float normals[3] = { 1.0f / 255.0f, 1.0f / 255.0f, 1.0f / 255.0f };
	//::memcpy(config.normal, normals, sizeof(normals));

	config.sourceFormat = RGB;
	config.destFormat = RGB; // request RGB
	config.wrap = ZERO;
我之前就这样写的  反正结果都对。 左上对齐

**Comment by anyongjin** [comment]
使用Matrix可以实现图片的缩放和平移居中。
使用ImageProcess的Wrap可以设置图片填充。
下面是kotlin使用MNN的示例，可以让大图片缩放到640*640，然后居中输入到模型。

```kotlin
// 设置填充
dataConfig.wrap = MNNImageProcess.Wrap.ZERO

// 计算缩放系数
val scale = min(inputWidth * 1f / bmp.width, inputHeight * 1f / bmp.height)
// 计算缩放后宽高
val scaleWidth = (scale * bmp.width).roundToInt()
val scaleHeight = (scale * bmp.height).roundToInt()
// 使图片居中的padding
val padTop = (inputHeight - scaleHeight) / 2
val padLeft = (inputWidth - scaleWidth) / 2
// 构造Matrix应用缩放和平移
val matrix = Matrix()
matrix.postScale(scale, scale)
matrix.postTranslate(padLeft.toFloat(), padTop.toFloat())
matrix.invert(matrix)
// 输入数据
MNNImageProcess.convertBitmap(bmp, mInputTensor!!, dataConfig, matrix)
//执行推理
mSession!!.run()
```
