### ISSUE TITLE
发现了MNN关于维度broadcast的一个非常低级的bug (Vulkan后端)

### ISSUE THREAD

**Issue by YingkunZhou** [alibaba/MNN#2560]
well，整个网络非常简单

<img width="895" alt="image" src="https://github.com/alibaba/MNN/assets/43129850/f76cc631-4355-4c34-b4c3-0b83e803b75a">

输入是一个四维的Tensor (1x4x196x196)，然后固定常量是一个三维的Tensor (4x196x196)，两者相加

我自己写了一个测试程序，然后用CPU后端和Vulkan后端来跑，发现Vulkan后端跑错了，目前我也正在调这个bug

输入Tensor就是初始化为全1

Vulkan后端输出结果
```log
parsed /proc/cpuinfo Hardware = "Amlogic"
The device support i8sdot:0, support fp16:0, support i8mm: 0
[len: 153664] (0: 6.64453) (1: -9.67188) (-2:1) (-1:1)
```

CPU后端输出结果

```log
parsed /proc/cpuinfo Hardware = "Amlogic"
The device support i8sdot:0, support fp16:0, support i8mm: 0
[len: 153664] (0: 6.64336) (1: 6.14926) (-2:3.50332) (-1:3.2117)
```

通过简单的加法口算就可以发现显然Vulkan后端算错了！

**Comment by YingkunZhou** [comment]
[debug.mnn.zip](https://github.com/alibaba/MNN/files/12435195/debug.mnn.zip)

mnn模型文件

**Comment by YingkunZhou** [comment]
我实在Vim3开发板的android系统中跑出来的bug，但我觉得这应该是general的bug，就是dimensions : [4, 3] broatcast 没有支持好

**Comment by jxt1234** [comment]
更新代码测试吧
