### ISSUE TITLE
opencl下bn2d算子问题

### ISSUE THREAD

**Issue by CaiWeibo** [alibaba/MNN#2561]
使用./MNNV2Basic.out基于opencl执行模型时，提示如下故障
===========> Resize Again...
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
Map error scalePtrCL == nullptr
Map error biasPtrCL == nullptr
test_main, 282, cost time: 950.974060 ms
排查发现该错误对应batchnorm2d，请问opencl的bn2d目前尚未支持吗，还是存在其他故障，望解答，感谢您！
注：模型可以继续执行，但对比和cpu下的output.txt结果存在显著差异，应该是opencl下模型的输出是错误的。

**Comment by jxt1234** [comment]
相关模型发一下吧

**Comment by CaiWeibo** [comment]
> 相关模型发一下吧
在叮叮群里确认opencl后端下bn尚不支持，改用conv-bn融合来消除bn的方案已经解决问题
