### ISSUE TITLE
由tflite模型转换后多输入中的一个输入不生效

### ISSUE THREAD

**Issue by jindanchu** [alibaba/MNN#2564]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android

# Github版本:
【新增Int8 量化算子，OpenCL后端适配 recordable queue】2.6.0

# 问题描述:
你好，我有一个mnn模型从tflite转换而来，没有添加特殊参数：
MNNConvert -f TFLITE --modelFile float_mc.tflite --MNNModel float_mc.mnn --bizCode biz
转换后模型结构没有发现明显异常。

该模型接受两个输入图片，输出一个图片。

然后我基于mnn android runtime运行模型，输入采用如下操作：
...
 auto input_tensor1 = interpreter->getSessionInput(session, ".../lambda/sub");
 interpreter->resizeTensor(input_tensor1, {1, 3, y, x});
 auto input_tensor2 = interpreter->getSessionInput(session, "x2");
interpreter->resizeTensor(input_tensor2, {1, 3, y*4, x*4});
 interpreter->resizeSession(session);
...
 auto nhwc_input_tensor1 = new MNN::Tensor(input_tensor1, MNN::Tensor::TENSORFLOW);
    for (int i = 0; i < y; ++i)
    {
        for (int j = 0; j <x; ++j)
        {
            nhwc_input_tensor1->host<float>()[(i*x+j)*3+0] = ...;
            ...
        }
    }
auto nhwc_input_tensor2 = new MNN::Tensor(input_tensor2, MNN::Tensor::TENSORFLOW);
    for (int i = 0; i < y*4; ++i)
    {
        for (int j = 0; j <x*4; ++j)
        {
            nhwc_input_tensor2->host<float>()[(i*x*4+j)*3+0] =...;
           ...
        }
    }
...
input_tensor1->copyFromHostTensor(nhwc_input_tensor1);
    delete nhwc_input_tensor1;
nput_tensor2->copyFromHostTensor(nhwc_input_tensor2);
    delete nhwc_input_tensor2;

接了下来run模型：
MNN::TensorCallBack before = [&](const std::vector<MNN::Tensor *> &ntensors,
                                     const std::string &opName) {
        return true;
    };
    MNN::TensorCallBack after = [&](const std::vector<MNN::Tensor *> &ntensors,
                                    const std::string &opName) {
        return true;
    };
    interpreter->runSessionWithCallBack(session, before, after, true);

最后获取输出：
auto output_tensor = interpreter->getSessionOutput(session, NULL);
    auto nhwc_output_tensor = new MNN::Tensor(output_tensor, MNN::Tensor::TENSORFLOW);
    output_tensor->copyToHostTensor(nhwc_output_tensor);
    memcpy(..., nhwc_output_tensor->host<float>(), x*y*3);
delete nhwc_output_tensor;

结果发现input_tensor2无论输入什么数据都不影响输出，通过callback观察所有节点都有运行到，推测是input_tensor2没有真正输入到模型。请问是我的操作方式有误吗？

Best Regards

**Comment by jindanchu** [comment]
![模型概览](https://github.com/alibaba/MNN/assets/106735221/0657d524-0817-4c28-88c1-e9147ab40417)

**Comment by jxt1234** [comment]
相关 tflite 传上来看看吧

**Comment by jxt1234** [comment]
可以用 ./GetMNNInfo XXX.mnn 看下 mnn 信息

**Comment by jindanchu** [comment]
你好，感谢回复！
附件是相关的tflite模型以及转换后的MNN模型：
[模型.zip](https://github.com/alibaba/MNN/files/12450678/default.zip)

**Comment by jindanchu** [comment]
GetMNNInfo 看起来挺正常的：
../build/GetMNNInfo float_mc_gsg.mnn
The device support i8sdot:0, support fp16:0, support i8mm: 0
Model default dimensionFormat is NHWC
Model Inputs:
[ edsr_compressed_tune_gs_guide/lambda/sub ]: dimensionFormat: NC4HW4, size: [ 1,3,360,640 ], type is float
[ x2 ]: dimensionFormat: NC4HW4, size: [ 1,3,1440,2560 ], type is float
Model Outputs:
[ Identity ]
Model Version: 2.6.2

**Comment by jindanchu** [comment]
> 可以用 ./GetMNNInfo XXX.mnn 看下 mnn 信息

你好，同时也尝试了尽量不改变原模型：

**Comment by jindanchu** [comment]
另外做了一个测试，同样的MNN模型在PC端用python session方式引用，同样的输入，结果是正确的，难道是runtime的问题？

**Comment by jindanchu** [comment]
@jxt1234 麻烦帮忙看下哈

**Comment by jindanchu** [comment]
已解决，这题可以关闭了，感谢
