### ISSUE TITLE
如何将MNN::Tensor转化为cv::Mat?

### ISSUE THREAD

**Issue by HWSQHL** [alibaba/MNN#2566]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# 

# Github版本:
# 2.6.1

# 编译方式:
# c++

如何将MNN::Tensor转化为cv::Mat?
mnn分割模型的输出的数据类型是MNN::Tensor,我需要采用使用opencv对该数据进行操作，如何将MNN::Tensor转化为cv::Mat?

**Comment by xingxinghanzi** [comment]
可以这样

    MNN::Tensor output_host_tensor(output_tensor, m_output_tensor->getDimensionType());
    output_tensor->copyToHostTensor(&output_host_tensor); 

    for (int i = 0; i < m_img_width * m_img_height; i++)
    {
       output_vector[i] = output_host_tensor.host<float>()[i];
    }
    m_mask = Mat(m_img_height, m_img_width, CV_32FC1, m_output_vector.data());
