### ISSUE TITLE
FP16 模型权重压缩问题以及ARMV8.2指令集支持疑问

### ISSUE THREAD

**Issue by Asxin** [alibaba/MNN#2568]
平台是RK3562 aarch64 ubuntu 交叉编译，编译
cmake .. -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake -DMNN_ARM82=ON
编译OK；
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Version: 2.4.0
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	NNAPI: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /home/xxx/build
-- 	CUDA PROFILE: OFF
-- WIN_USE_ASM: 
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- Configuring done
-- Generating done

然后将ONNX模型使用 ./MNNConvert -f ONNX --modelFile model.onnx --MNNModel out.mnn --bizCode biz --fp16
转换为 fp16 版的mnn模型
这里有一个问题：转换后的mnn模型通过查看卷积权重参数依旧是 fp32 的，只有 GRU 的权重参数变成了 FP16，所以 fp16 版的mnn模型大小相比fp32版本并不是1/2 大小；看说明 conv 应该也可以把参数转为 fp16 吧？这个现象是否正常呢？

第二个问题：使用python 版本的 mnnconvert 做相同的转换，可以看到生成的 mnn 模型文件变小了很多，但是推理时创建模型就会报错（C++版本的MNNConvert 则正常）：
The device support dot:0, support fp16:0, support i8mm: 0
Error for concat size of op [ /encoder.0.0/Concat_output_0 ], the 2 input not match output
Compute Shape Error for /encoder.0.0/Concat_output_0

以上是 将fp32 ONNX 模型转换 fp16 mnn的疑问。

在 C++中推理上面生成的mnn模型，fp32版本和fp16版本都可以正常运行，执行耗时一模一样，貌似并没有启用到 ARMV82指令加速，libMNN.so 编译明确已经开启了 MNN_ARM82, 还有其他原因么？

每次运行都会输出 The device support dot:0, support fp16:0, support i8mm: 0 是不是表明 ARMV82 并未正确支持呢？

**Comment by Asxin** [comment]
运行时fp16模型时已经把precision设置为low了

**Comment by jxt1234** [comment]
0. 统一更新 mnn 到最新测试
1. 有可能是因为卷积已经量化过或者卷积权重存在共享的情况（多个卷积用同一权重）
2. 模型转换的 --fp16 及 --weightQuantBits 与运行时性能无关，运行统一先解压到 fp32 ，再根据设备情况和precision 判断基于什么数据类型推理
3. The device support dot:0, support fp16:0, support i8mm: 0  表示设备不支持基于 fp16 数据类型推理
