### ISSUE TITLE
Module API并行计算问题

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2572]
我现在想用一个VARP分别跟两个VARP进行_MatMul，请问这两个运算可以并行进行吗？如果可以的话是使用std::thread还是MNN_CONCURRENCY的宏定义？

**Comment by jxt1234** [comment]
目前不支持算子间并行的，后续可能会优化。但不需要上层调用 std::thread 或者 MNN_CONCURRENCY 。
