### ISSUE TITLE
tflite模型转换时直接阻塞

### ISSUE THREAD

**Issue by Small-Sagittarius** [alibaba/MNN#2573]
## 日志如下，没有任何报错信息，但是一直卡在Start to Optimize the MNN Net。
./MNNConvert -f TFLITE --modelFile exported_models/my_ssd_mobilenet_v2_fpn/frozen/saved_model/saved_model.tflite --MNNModel exported_models/my_ssd_mobilenet_v2_fpn/frozen/saved_model/saved_model.mnn --bizCode biz

The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...

## 附上TFLite模型文件
[saved_model.zip](https://github.com/alibaba/MNN/files/12481639/saved_model.zip)

## 在线转化
通过在线模型转化网站可以将该模型转化为MNN模型，且可以正常完成推理。附网址：https://converter-web.oss-cn-beijing.aliyuncs.com/

**Comment by jxt1234** [comment]
出问题的 MNN 的版本是？

**Comment by jxt1234** [comment]
已经复现，定位中

**Comment by jxt1234** [comment]
2.7.2 已经修正
