### ISSUE TITLE
模型裁剪后统计计算量Flops 降低，但是实际推理耗时反而增加了！

### ISSUE THREAD

**Issue by Asxin** [alibaba/MNN#2576]
各位大佬，我有个模型，使用MNN的getSessionInfo() 得到每次推理的计算量为2MFlops，1秒钟要运行125次；
通过降低卷积通道等一系列操作后，获得的计算量变为 1.8MFlops x 125。
但是实际测试推理耗时不降反升！升高了15%左右。这个正常么？怎么解释

**Comment by jxt1234** [comment]
模型结构发出来看下吧，可能是输出通道不是 8 对齐 / 4 对齐，在实际运算时会上对齐处理，导致耗时增加
