### ISSUE TITLE
关于内存和显存拷贝的问题

### ISSUE THREAD

**Issue by darrenearl** [alibaba/MNN#2577]
请问MNN支持直接将内存地址或者显存地址赋给input和output吗？

我现在存在一个性能问题，使用的是AMD RX7600显卡，MNN的OpenCL后端，因为我的数据前处理和模型的后处理解析用的是自己写的hip核函数，为了使模型能够正常的输入，我构建了一个hostInputTensor和hostOutputTensor变量，但是这样就存在性能问题，请问MNN能否像TensorRT那样直接给定一个显存地址或者内存地址呢？减少拷贝

**Comment by jxt1234** [comment]
支持直接传值，但 OpenCL 需要是相同上下文，并用同样的数据结构。建议是写 MNN OpenCL 算子，通过表达式计算然后传入
