### ISSUE TITLE
iOS官方的playground工程使用CoreML会crash

### ISSUE THREAD

**Issue by ruanmk** [alibaba/MNN#2578]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
ios

# Github版本:
2.6.3

# 编译方式:
./schema/generate.sh 
xcode打开project/ios编译，跑playground项目

<img width="642" alt="image" src="https://github.com/alibaba/MNN/assets/3760556/8a84f0ca-29e7-4ef0-9ce1-21e6389ed01e">
将benchmark打开，默认的forward type就是MNN_FORWARD_NN，直接跑真机会crash，其中部分Tensor是空指针

**Comment by v0jiuqi** [comment]
在CoreML下对输入输出数据的赋值方式和其他后端不同，需要对benchmark.cpp做如下修改,
在warmup阶段的循环外申请一个临时Tensor,并把输入数据的值复制到该Tensor中，如下：
std::shared_ptr<MNN::Tensor> givenInput(new MNN::Tensor(input));
    auto ptr_ = givenInput->host<float>();
    for (int k = 0; k<size_input; ++k) {
        ptr_[k] =  0.01; // 复制你的数据
    }
//申请一个Tensor来存储输出数据
std::shared_ptr<MNN::Tensor> expectTensor(MNN::Tensor::createHostTensorFromDevice(outputTensor, false));
上面的赋值操作在warmup循环外进行。
161行和162行修改为：
input->copyFromHostTensor(givenInput.get());
166行和167行修改为：
outputTensor->copyToHostTensor(expectTensor.get());
如果要读取输出数据，在循环外进行如下操作：
auto ptr_out  = expectTensor->host<float>();
printf("first output data: %f", ptr_out[0]);
如果不熟悉copyToHostTensor和copyFromHostTensor的用法，参照MNN其他文件中的使用。
