### ISSUE TITLE
MNNConvert -f ONNX 提示成功，但实际不可用

### ISSUE THREAD

**Issue by xp19870106** [alibaba/MNN#2579]
# 平台：MacOS 

# Github版本: 2.6.3

使用如下的方式将onnx转换为mnn
```
./MNNConvert -f ONNX --modelFile ./rvm_mobilenetv3_fp32.onnx --MNNModel ./test.mnn --bizCode biz
```

转换后提示如下
```
hw.cpufamily: 3660830781 , size = 4
The device support i8sdot:1, support fp16:1, support i8mm: 0
Start to Convert Other Model Format To MNN Model...
[13:53:02] :46: ONNX Model ir version: 6
[13:53:02] :47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
The Convolution use shared weight, may increase the model size
inputTensors : [ src, downsample_ratio, r4i, r3i, r2i, r1i, ]
outputTensors: [ fgr, pha, r1o, r2o, r3o, r4o, ]
Converted Success!
```

使用转换后的mnn文件，打印出来的模型参数不对：
LITEMNN_DEBUG LogId: ../../../../hub/mnn/cv/test.mnn
=============== Input-Dims ==============
	**Tensor shape**: 1, 3, -1, -1, 
	**Tensor shape**: 1, -1, -1, -1, 
	**Tensor shape**: 1, -1, -1, -1, 
	**Tensor shape**: 1, -1, -1, -1, 
	**Tensor shape**: 1, -1, -1, -1,

**Comment by xp19870106** [comment]
this is the onnx file:
[rvm_mobilenetv3_fp32.onnx.zip](https://github.com/alibaba/MNN/files/12510142/rvm_mobilenetv3_fp32.onnx.zip)

**Comment by xp19870106** [comment]
> 设定



> 先用 testMNNFromOnnx.py 测试。 另外，这个是模型本身没有指定输入大小，在使用 mnn 时设定输入大小即可，不影响使用

请问设定输入大小是调用哪个API

**Comment by jxt1234** [comment]
建议使用 Module API
https://mnn-docs.readthedocs.io/en/latest/inference/module.html
构建输入时即指定好输入大小了

用 Session API 的话参考
https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id16

resizeTensor -> resizeSession
