### ISSUE TITLE
mnn支持多输入多输出吗

### ISSUE THREAD

**Issue by ztwe** [alibaba/MNN#258]
如题，谢谢！

**Comment by ztwe** [comment]
getSessionOutputAll()
getSessionInputAll()

这两个函数好像可以解决多输入多输出问题？怎么用？有没有示例？

**Comment by li-qing** [comment]
参考文档 https://www.yuque.com/mnn/cn/output

两个接口是按输入输出分开返回的

**Comment by ztwe** [comment]
> 参考文档 https://www.yuque.com/mnn/cn/output
> 
> 两个接口是按输入输出分开返回的

另外，能通过多次调用getSessionOutput()、getSessionInput()来解决多输入多输出吗

**Comment by li-qing** [comment]
> > 参考文档 https://www.yuque.com/mnn/cn/output
> > 两个接口是按输入输出分开返回的
> 
> 另外，能通过多次调用getSessionOutput()、getSessionInput()来解决多输入多输出吗

可以的
