### ISSUE TITLE
MNN images process 归一化问题

### ISSUE THREAD

**Issue by lyC121** [alibaba/MNN#2585]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
服务器Linux平台：Ubuntu 20.04.2 LTS
交叉编译目标平台：RK3566

# Github版本: 2.3.0
# Github Version:

MNN的归一化代码如下：
    //cvt
    Matrix trans;
    trans.setScale(1.f,1.f);
    //image process
    ImageProcess::Config config;
    config.filterType = BILINEAR;

    float mean[3]     = {0.485*255.f, 0.456*255.f, 0.406*255.f};
    float normals[3] = {1/(255.f*0.229), 1/(255.f*0.224), 1/(255.f*0.225)}; 

    ::memcpy(config.mean, mean, sizeof(mean));
    ::memcpy(config.normal, normals, sizeof(normals));
    config.sourceFormat = BGR;
    config.destFormat   = BGR;

    std::shared_ptr<ImageProcess> pretreat(ImageProcess::create(config), ImageProcess::destroy);
    pretreat->setMatrix(trans);
    pretreat->convert((uint8_t*) img_resized.data, d_w, d_h, 0, mInput_tensor);

交叉编译后在RK3566平台上执行目标文件后，归一化处的值不对。
MNN的images process 处理 ：It's dst = (img - mean) * normal。
但在RK3566平台的结果是：（179-116.1）*1.0 = 62.9062；正确应该是62.9；
                                             （182-116.1）*1.0 = 65.875； 正确应该是65.9；
                                             （175-116.1）*1.0 = 58.9062；正确应该是58.9062；
请问是原因呢？

**Comment by lyC121** [comment]
MNN::CV::images process在Linux平台和Android平台的归一化有差异的原因是什么呢

**Comment by jxt1234** [comment]
几个可能性：
1. mean 和 normal 做除法后产生误差
2. 浮点数计算顺序在 LINUX 的 x86 向量指令和 Android 的 NEON 指令下不一样导致误差
3. 双线性插值引入额外运算导致误差，这个可以把 filterType 设成 NEREST 试下
config.filterType = NEREST

**Comment by lyC121** [comment]
@jxt1234 
感谢回复。

对可能性3，把 filterType 设成 NEREST 试下config.filterType = NEREST后，没有变化。

根据MNN的images process 的处理 ：It's dst = (img - mean) * normal。
Linux平台获得正确的计算值，但交叉编译后在RK3566平台获得的计算器有偏差：如下
RK3566平台经过MNN的images process 后如（179-116.1）*1.0 = 62.9062；而正确值应该是62.9（Linux平台获得正确计算值）；
（182-116.1）*1.0 = 65.875； 正确应该是65.9；
（175-116.1）*1.0 = 58.9062；正确应该是58.9062；

可能性1mean 和 normal 做除法后产生误差，这误差Linux平台和Android平台应该是一样的。（而现在问题是Linux平台没问题，Android计算有偏差）

可能性2浮点数计算顺序在 LINUX 的 x86 向量指令和 Android 的 NEON 指令下不一样导致误差，目前是MNN在Android平台的归一化都有误差吗？
