### ISSUE TITLE
MNN ios16.2使用CoreML必现崩溃，可能是因为代码中存在一个过早析构的bug

### ISSUE THREAD

**Issue by ruanmk** [alibaba/MNN#2586]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS SDK 16.2

# Github版本:
# Github Version:
32f72f4fb983a700d3c8f20549e159ee3860952b

# 编译方式:
# Compiling Method
xcode 打开 project/ios/demo
```
使用CoreML的时候，这段代码Tensor是浅拷贝，在srcTensor析构后，mInputTensors中的成员将指向一段未定义的内存
https://github.com/alibaba/MNN/blob/master/source/backend/coreml/backend/CoreMLBackend.cpp#L118
<img width="956" alt="image" src="https://github.com/alibaba/MNN/assets/3760556/ee45b5bd-8232-41b7-b343-bfad1937a811">
调用这段代码的上层是这样的：跳出作用域后srcTensor就被析构了
<img width="574" alt="image" src="https://github.com/alibaba/MNN/assets/3760556/801ccf3f-5047-44db-9a33-125eb4afdfc7">

这个bug必现，为什么没有其他人注意到的？

**Comment by wangzhaode** [comment]
> 使用CoreML的时候，这段代码Tensor是浅拷贝，在srcTensor析构后，mInputTensors中的成员将指向一段未定义的内存

这个地方不是Bug。为了减少内存拷贝，CoreML后端推理时直接依赖外部输入，所以在runSession之前需要保持外部Tensor存活。
