### ISSUE TITLE
MNN能否支持导入量化参数

### ISSUE THREAD

**Issue by zhxsking** [alibaba/MNN#2587]
现在不支持转换已量化的onnx模型，请问能手动导入量化参数吗，或者有这个计划吗？
#2084

**Comment by jxt1234** [comment]
可以按 tools/converter/source/compression/MNN_compression.proto 里面的格式生成量化所需文件 compress.bin，然后用 MNNConvert 转换 MNN 模型时加上 --compressionParamsFile compress.bin 。后续会考虑支持 Json 格式的文件，以便用户编辑
