### ISSUE TITLE
Metal对ArgMax算子的支持

### ISSUE THREAD

**Issue by wyatt-zozo** [alibaba/MNN#2589]
# 平台:  macOS & iOS
# Github版本:2.6.2
 
 Metal不支持ArgMax算子，希望大佬们能安排上

 
![image](https://github.com/alibaba/MNN/assets/143981375/22948f47-5dd5-4ddc-9894-37390e2236c4)

**Comment by jxt1234** [comment]
收到，预计下个版本支持

**Comment by wyatt-zozo** [comment]
> 收到，预计下个版本支持

给大佬递茶.jpg
