### ISSUE TITLE
包含Argmax算子的tf模型运行失败

### ISSUE THREAD

**Issue by huabb** [alibaba/MNN#259]
包含argmax算子的tf模型用mnn推理时存在以下问题：
1.tensorflow中argmax算子的输出是整型，但mnn中argmax输出是float类型，当其输出是gather算子的indice参数时，要求indice是int类型，由于类型不匹配无法运行；
2.在tensorflow中argmax的输出维度低于输入维度，而mnn中argmax算子的输出维度与输入维度相同，导致后续Tensor维度与预期不符，运行出错；
3.算子的axis参数没有发挥作用；
4.对于输入维度低于4维的情况当前实现存在问题

**Comment by li-qing** [comment]
已知问题 近期会修

**Comment by czy2014hust** [comment]
fixed!
