### ISSUE TITLE
反向传播中LoopGrad的Assert语句报错

### ISSUE THREAD

**Issue by fubukishiro** [alibaba/MNN#2590]
我利用MNN提供的算子实现了一个Bert，但是在训练过程进行反向传播的时候，在LoopGrad.cpp的第251行Assert语句中断言失败
`MNN_ASSERT(iter != allTensors.end());`

看debug应该是一个Binary Op的command调用了LoopGrad里面的onGrad。
请问哪些算子可能会用到LoopGrad，以及应该如何排错？

**Comment by TKH666** [comment]
同样遇到这个问题，请问你最后如何解决？ @fubukishiro
