### ISSUE TITLE
2.7.0中int8 depthwise conv 做了什么优化呢？2.7.0中int8 depthwise conv test/op测例加了speed测速，掐算的x->writeMap<float>(); y->readMap<float>()时间为何是float以及掐的时间是LOOP100次的总时间？没看到取平均

### ISSUE THREAD

**Issue by hayyaw** [alibaba/MNN#2594]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
参考 https://mnn-docs.readthedocs.io/en/latest/inference/expr.html ，_Conv 是构图，在 readMap 的时候才会执行计算

**Comment by hayyaw** [comment]
统计的是dwconv 100次的执行时间吗？看平均时间并没有除以循环次数LOOP， 然后为何是float类型？，前面计算都是int8，时间统计用的x->writeMap<float>();y->readMap<float>()

**Comment by hayyaw** [comment]
> 参考 https://mnn-docs.readthedocs.io/en/latest/inference/expr.html ，_Conv 是构图，在 readMap 的时候才会执行计算

**Comment by jxt1234** [comment]
writeMap 再 readMap 就会执行计算，不取数据的情况下用什么类型没有区别。
