### ISSUE TITLE
根目录的CMakeLists.txt在构建darwin平台的静态库时存在链接选项错误

### ISSUE THREAD

**Issue by shine-xia** [alibaba/MNN#2596]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
darwin x86_64

# Github版本:
32f72f4fb983a700d3c8f20549e159ee3860952b [32f72f4f]

# 编译方式:
# Compiling Method
clang

# 具体问题
根目录的CMakeLists.txt，line 725，在构建darwin平台的静态库时，编译选项有问题。
--whole-archive/--no-whole-archive应该替换为-all_load/-noall_load

if (NOT MNN_BUILD_SHARED_LIBS)
    if (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        # Static-link will not replace thread-related weak symbol in glibc with strong symbol
        # in pthread library, so we need use --whole-archive to pthread
        # https://stackoverflow.com/questions/35116327/when-g-static-link-pthread-cause-segmentation-fault-why
        if(CMAKE_SYSTEM_NAME MATCHES "^Linux")
            set(MNN_DEPS -Wl,--whole-archive ${MNN_DEPS} -lpthread -Wl,--no-whole-archive)
        else()
            set(MNN_DEPS -Wl,--whole-archive ${MNN_DEPS} -Wl,--no-whole-archive)
        endif()
    endif()
endif()

**Comment by DaydreamCoding** [comment]
https://github.com/alibaba/MNN/pull/2581
