### ISSUE TITLE
Add op error

### ISSUE THREAD

**Issue by nullian** [alibaba/MNN#26]
I am following [https://github.com/alibaba/MNN/blob/master/doc/AddOp_EN.md](url) this doc to add  a caffe Op named AffineCrop. After finish 4 steps in the doc, compile error 

Scanning dependencies of target MNNConvert
[ 98%] Building CXX object CMakeFiles/MNNConvert.dir/source/MNNConverter.cpp.o
[ 99%] Building CXX object CMakeFiles/MNNConvert.dir/source/cli.cpp.o
[100%] Building CXX object CMakeFiles/MNNConvert.dir/source/config.cpp.o
[100%] Linking CXX executable MNNConvert
source/caffe/libcaffe.so: undefined reference to `vtable for AffineCrop'
collect2: error: ld returned 1 exit status
CMakeFiles/MNNConvert.dir/build.make:121: recipe for target 'MNNConvert' failed
make[2]: *** [MNNConvert] Error 1
CMakeFiles/Makefile2:152: recipe for target 'CMakeFiles/MNNConvert.dir/all' failed
make[1]: *** [CMakeFiles/MNNConvert.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Sorry about my poor knowledge of flatbuffers, can someone gives any suggestion, thanks

**Comment by jxt1234** [comment]
The flatbuffers doesn't matter.
Do you rerun the cmake?
Or the AffineCrop class complete all virtual function?

**Comment by nullian** [comment]
Yes, i have rerun the cmake. and in MNN/schema/CaffeOp_generated.h  exists 

```
struct AffineCrop FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NEWSHAPEDESC = 4,
    VT_SHOWOUTPUTIMAGE = 6
  };
  const flatbuffers::Vector<flatbuffers::Offset<AffineImageParameter>> *newShapeDesc() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<AffineImageParameter>> *>(VT_NEWSHAPEDESC);
  }
  bool showOutputImage() const {
    return GetField<uint8_t>(VT_SHOWOUTPUTIMAGE, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NEWSHAPEDESC) &&
           verifier.VerifyVector(newShapeDesc()) &&
           verifier.VerifyVectorOfTables(newShapeDesc()) &&
           VerifyField<uint8_t>(verifier, VT_SHOWOUTPUTIMAGE) &&
           verifier.EndTable();
  }
};
```

and my AffineCrop.cpp looks like this:

```
#include "OpConverter.hpp"

class AffineCrop : public OpConverter {
public:
    AffineCrop() {

    }

    virtual ~AffineCrop() {

    }

    virtual MNN::OpType opType() {
        return MNN::OpType_AffineCrop;
    }

    virtual MNN::OpParameter type() {
        return MNN::OpParameter_AffineCrop;
    }

    virtual void run(MNN::OpT* dstOp, const caffe::LayerParameter& parameters, const caffe::LayerParameter& weight);

};

void run(MNN::OpT* dstOp, const caffe::LayerParameter& parameters, const caffe::LayerParameter& weight) {
    auto affineCrop = new MNN::AffineCropT;
    dstOp->main.value = affineCrop;
    .......
}
static OpConverterRegister<AffineCrop> a("AffineCrop");
```

**Comment by jxt1234** [comment]
/*
void run(MNN::OpT* dstOp, const caffe::LayerParameter& parameters, const caffe::LayerParameter& weight) {
*/

To:
/*
void AffineCrop::run(MNN::OpT* dstOp, const caffe::LayerParameter& parameters, const caffe::LayerParameter& weight) {
*/

**Comment by nullian** [comment]
Thanks, it works
