### ISSUE TITLE
出现crash 在android demo 使用自己训练的模型

### ISSUE THREAD

**Issue by Fight-hawk** [alibaba/MNN#260]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 3613 (MNNNet), pid 3585 (android.mnndemo)
看到之前issue 你有提到已经解决了这个bug，为什么还会出现 请问有什么解决思路吗

**Comment by li-qing** [comment]
0x0 空指针访问 建议检查流程链路

**Comment by Fight-hawk** [comment]
@li-qing 我在自己机器上编译了so文件，替换了demo里的so文件，就没有问题了。使用的ndk是r16b。

**Comment by li-qing** [comment]
> @li-qing 我在自己机器上编译了so文件，替换了demo里的so文件，就没有问题了。使用的ndk是r16b。

明白了 感谢反馈
