### ISSUE TITLE
有什么方法可以输出mnn运行的backend呢？

### ISSUE THREAD

**Issue by DeepSpace98** [alibaba/MNN#2607]
我用mnn在mt6765上部署模型，使用除cpu的方法进行推理，但是结果推理时间都是一样的，我怀疑是否成功使用gpu进行加速，有什么方法可以输出mnn所用推理方法的日志吗？还有就是在安卓平台上使用mnn框架，OpenCL和opengl等方法需要提前做些什么工作吗？类似安装驱动之类的？因为第一次搞这个，没经验，希望大佬帮忙解答一下

**Comment by DeepSpace98** [comment]
> 我用mnn在mt6765上部署模型，使用除cpu的方法进行推理，但是结果推理时间都是一样的，我怀疑是否成功使用gpu进行加速，有什么方法可以输出mnn所用推理方法的日志吗？还有就是在安卓平台上使用mnn框架，OpenCL和opengl等方法需要提前做些什么工作吗？类似安装驱动之类的？因为第一次搞这个，没经验，希望大佬帮忙解答一下

我在log上看到mnnjni的输出显示，只有cpu情况下是正常运行的，其他的类似opencl和opengl都是can't find type ＝x backend，use 0 instead。安卓板上怎么才能启用opengl和opencl呢？

**Comment by wangzhaode** [comment]
需要在编译时打开opencl的选项

**Comment by DeepSpace98** [comment]
> 需要在编译时打开opencl的选项

使用的是官方编译的静态库

**Comment by wangzhaode** [comment]
使用的哪个版本？

**Comment by wangzhaode** [comment]
android的话使用这个：https://github.com/alibaba/MNN/releases/download/untagged-87bed4234e39c7e2618c/mnn_2.7.1_android_armv7_armv8_cpu_opencl_vulkan.zip

**Comment by DeepSpace98** [comment]
> 使用的哪个版本？

2.6.0

**Comment by DeepSpace98** [comment]
> android的话使用这个：https://github.com/alibaba/MNN/releases/download/untagged-87bed4234e39c7e2618c/mnn_2.7.1_android_armv7_armv8_cpu_opencl_vulkan.zip

这个链接无法打开呀

**Comment by wangzhaode** [comment]
更新了一下 https://github.com/alibaba/MNN/releases/download/2.7.1/mnn_2.7.1_android_armv7_armv8_cpu_opencl_vulkan.zip

**Comment by DeepSpace98** [comment]
> 更新了一下 https://github.com/alibaba/MNN/releases/download/2.7.1/mnn_2.7.1_android_armv7_armv8_cpu_opencl_vulkan.zip

好的，我更新试试

**Comment by wangzhaode** [comment]
如果这个包还是找不到cl后端，请参考：https://mnn-docs.readthedocs.io/en/latest/faq.html#can-t-find-type-3-backend

**Comment by DeepSpace98** [comment]
> 如果这个包还是找不到cl后端，请参考：https://mnn-docs.readthedocs.io/en/latest/faq.html#can-t-find-type-3-backend

opengl的也是这样吗？

**Comment by wangzhaode** [comment]
建议使用cl

**Comment by DeepSpace98** [comment]
> 建议使用cl

cl显示set multi tuning mode is not permitted，这是什么原因呢？

**Comment by DeepSpace98** [comment]
> 建议使用cl

我现在在win上自己编译的benchmark可以正常使用opencl，但是如果是自己代码使用编译的MNN.lib和MNN.dll的话，就用不了opencl
