### ISSUE TITLE
使用quantized离线int8量化后，使用2.7.1以及2.6.0编译的timeProfile.out测试时，发现量化后的模型cost time不一致

### ISSUE THREAD

**Issue by Nao-Chu** [alibaba/MNN#2609]
# 使用2.7.1版本，量化后的模型推理时间变长

### 在2.7.1编译生成quantized，使用quantized.out进行离线int8量化，得到量化后模型test_quant.mnn
MNN/build$ ./quantized.out test.mnn test_quant.mnn mobilnet_quant.json        
[15:50:07] MNN/tools/quantization/quantized.cpp:23: >>> modelFile: test.mnn
[15:50:07] MNN/tools/quantization/quantized.cpp:24: >>> preTreatConfig: mobilnet_quant.json
[15:50:07] MNN/tools/quantization/quantized.cpp:25: >>> dstFile: test_quant.mnn
[15:50:07] MNN/tools/quantization/quantized.cpp:53: Calibrate the feature and quantize model...
[15:50:07] MNN/tools/quantization/calibration.cpp:158: Use feature quantization method: KL
[15:50:07] MNN/tools/quantization/calibration.cpp:159: Use weight quantization method: MAX_ABS
[15:50:07] MNN/tools/quantization/calibration.cpp:179: feature_clamp_value: 127
[15:50:07] MNN/tools/quantization/calibration.cpp:180: weight_clamp_value: 127
The device support i8sdot:0, support fp16:0, support i8mm: 0
[15:50:07] MNN/tools/quantization/Helper.cpp:111: used image num: 20
[15:50:07] MNN/tools/quantization/calibration.cpp:665: fake quant weights done.
ComputeFeatureRange: 100.00 %
CollectFeatureDistribution: 100.00 %
[15:50:10] MNN/tools/quantization/quantized.cpp:58: Quantize model done!

### 在2.7.1编译生成timeProfile，使用timeProfile.out测试
Open Model test.mnn
Sort by time cost !
Node Type               Avg(ms)         %               Called times    Flops Rate
Scale                   0.001870        0.028947        1.000000        0.000025
Raster                  0.002250        0.034829        2.000000        0.000179
Pooling                 0.009620        0.148912        1.000000        0.000000
BinaryOp                0.051280        0.793787        10.000000       0.054368
ConvolutionDepthwise    1.215403        18.813784       17.000000       5.561063
Convolution             5.179736        80.179474       36.000000       94.384453
total time : 6.460176 ms, total mflops : 990.718201
main, 147, cost time: 670.926025 ms

Open Model test_quant.mnn
Sort by time cost !
Node Type               Avg(ms)         %               Called times    Flops Rate
Raster                  0.001660        0.021476        2.000000        0.000179
Scale                   0.002140        0.027685        1.000000        0.000025
Pooling                 0.031950        0.413339        1.000000        0.000000
FloatToInt8             0.168620        2.181444        1.000000        0.039413
BinaryOp                0.447519        5.789579        10.000000       0.054347
ConvolutionDepthwise    2.461695        31.847065       17.000000       5.558872
Convolution             4.616162        59.719509       36.000000       94.347260
total time : 7.729738 ms, total mflops : 991.108765
main, 147, cost time: 786.915039 ms

### 在2.6.0编译生成timeProfile，使用timeProfile.out测试
Open Model test.mnn
Sort by time cost !
Node Type               Avg(ms)         %               Called times    Flops Rate
Scale                   0.001700        0.025572        1.000000        0.000025
Raster                  0.002440        0.036704        2.000000        0.000179
Pooling                 0.009720        0.146213        1.000000        0.000000
BinaryOp                0.052410        0.788376        10.000000       0.054368
ConvolutionDepthwise    1.332569        20.045124       17.000000       5.561063
Convolution             5.249006        78.958008       36.000000       94.384453
total time : 6.647845 ms, total mflops : 990.718201
main, 147, cost time: 690.797058 ms

Open Model test_quant.mnn
Sort by time cost !
Node Type               Avg(ms)         %               Called times    Flops Rate
Raster                  0.001720        0.025084        2.000000        0.000179
Scale                   0.002270        0.033105        1.000000        0.000025
Pooling                 0.033390        0.486955        1.000000        0.000000
FloatToInt8             0.175570        2.560489        1.000000        0.039413
BinaryOp                0.462118        6.739472        10.000000       0.054347
ConvolutionDepthwise    1.568697        22.877666       17.000000       5.558872
Convolution             4.613128        67.277245       36.000000       94.347260
total time : 6.856892 ms, total mflops : 991.108765
main, 147, cost time: 699.805054 ms

### 结论：
在2.7.1 测试时 cost time分别是 670.926025 ms和786.915039 ms，int8量化后反而变慢很多
在2.6.0 测试时 cost time分别是 690.797058 ms和699.805054 ms，int8量化后和原模型差不多，有毫秒级的误差能理解

**Comment by jxt1234** [comment]
看上去是 binary 量化后，sse 没有支持 int8 计算导致的
