### ISSUE TITLE
MNN多次提特征时间差距比较大，前两次很快，后面很慢。

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#261]
![image](https://user-images.githubusercontent.com/24749356/63495522-9f954380-c4f2-11e9-8a2e-13f74f41c451.png)
连续十次提特征，出现前两次很快，到后面很慢的情况，测试好几次都是这样，请问这种情况正常吗？
![1566452997072](https://user-images.githubusercontent.com/24749356/63495785-1df1e580-c4f3-11e9-818b-7ec642942a2b.png)

**Comment by li-qing** [comment]
extracter是什么？？？？

**Comment by xiexuliunian** [comment]
`cv::Mat FaceFeatExtracter::Extracter(cv::Mat _targetImg) {
	const char* inputImageFileName = "tmp.jpg";
	cv::imwrite(inputImageFileName, _targetImg);
	int originalWidth;
	int originalHeight;
	int originChannel;
	auto inputImage = stbi_load(inputImageFileName, &originalWidth, &originalHeight, &originChannel, 4);
	if (nullptr == inputImage) {
		MNN_ERROR("Invalid path: %s\n", inputImageFileName);
	}

	//创建网络和会话
	MNN::ScheduleConfig netConfig;
	netConfig.type = MNN_FORWARD_CPU;
	netConfig.numThread = 4;
	auto session = mnn_net->createSession(netConfig);
	auto input = mnn_net->getSessionInput(session, nullptr);
	std::cout << "input elementSize:" << input->elementSize() << std::endl;

	if (input->elementSize() <= 4) {
		mnn_net->resizeTensor(input, { 1, 3, originalHeight, originalWidth });
		mnn_net->resizeSession(session);
	}

	// 处理图片
	{
		const float means[3] = { 127.5f, 127.5f, 127.5f };
		const float norms[3] = { 2.0f / 255.0f, 2.0f / 255.0f, 2.0f / 255.0f };
		CV::ImageProcess::Config preProcessConfig;
		::memcpy(preProcessConfig.mean, means, sizeof(means));
		::memcpy(preProcessConfig.normal, norms, sizeof(norms));
		preProcessConfig.sourceFormat = CV::RGBA;
		preProcessConfig.destFormat = CV::RGB;
		preProcessConfig.filterType = CV::BILINEAR;

		auto pretreat = std::shared_ptr<CV::ImageProcess>(CV::ImageProcess::create(preProcessConfig));
		CV::Matrix trans;

		// Dst -> [0, 1]
		trans.postScale(1.0 / originalWidth, 1.0 / originalHeight);
		//[0, 1] -> Src
		trans.postScale(originalWidth, originalHeight);

		pretreat->setMatrix(trans);
		const auto rgbaPtr = reinterpret_cast<uint8_t*>(inputImage);
		pretreat->convert(rgbaPtr, originalWidth, originalHeight, 0, input);
	}

	// 运行...
	{
		AUTOTIME;
		mnn_net->runSession(session);
	}

	// 获取输出
	//auto m = mnn_net->getSessionOutputAll(session);
	//for (auto& it : m) {
	//	std::cout << it.first << "->" << it.second << std::endl;
	//}
	auto offsets = mnn_net->getSessionOutput(session, NULL);
	auto outputTensor = mnn_net->getSessionOutput(session, NULL);
	auto nchwTensor = new Tensor(outputTensor, Tensor::CAFFE);
	outputTensor->copyToHostTensor(nchwTensor);
	// nchwTensor->print();
	auto mnn_feature = nchwTensor->host<float>();
	//std::cout << "mnn_feature[0]:" << mnn_feature[0] << std::endl;
	//std::cout << "nchwTensor size:" << nchwTensor->elementSize() << std::endl;
	cv::Mat probMat(1, 128, CV_32FC1, cv::Scalar(0));
	for (int j = 0; j < nchwTensor->elementSize(); j++)
		probMat.at<float>(0, j) = mnn_feature[j];
	delete nchwTensor;
	return probMat.clone();
}`

**Comment by jxt1234** [comment]
session 是可以复用的，不要每次都 createSession 
你这个原因是每次都 create session  且不 release ，内存使用量渐渐增大了

**Comment by xiexuliunian** [comment]
哇的一声哭了出来，谢谢大大。
