### ISSUE TITLE
2.7.1版本的OpenCL后端的softmax算子似乎存在问题

### ISSUE THREAD

**Issue by shine-xia** [alibaba/MNN#2610]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
darwin x86_64

# Github版本:
# Github Version:
94e1212b837ea160aed908a83c81b87c475fe7a2, tag 2.7.1

# 编译方式:
# Compiling Method
cmake

38b7196c6789dcc34fe8dd1a8e1a75c19ba3cda2 提交中，引入的OpenCL后端的softmax算子的修改似乎存在问题。
手上有一个模型，最后一层是softmax，此提交之前结果正确，此提交之后结果错误。

**Comment by bitxsw93** [comment]
附上你的模型 复现的步骤，我们检查看下。
