### ISSUE TITLE
MNNConvert 在2.6.3版本及以后在有些模型上出现了巨大的性能回退

### ISSUE THREAD

**Issue by YingkunZhou** [alibaba/MNN#2611]
采用的编译选项为：
```bash
mkdir build && cd build
cmake -D CMAKE_BUILD_TYPE=Release .. \
-D CMAKE_INSTALL_PREFIX=../install -D MNN_BUILD_BENCHMARK=ON -D MNN_BUILD_CONVERTER=ON
```

在Jetson Orin上本地编译

[debug.onnx.tar.gz](https://github.com/alibaba/MNN/files/12839966/debug.onnx.tar.gz)
[debug.mnn.tar.gz](https://github.com/alibaba/MNN/files/12839968/debug.mnn.tar.gz)
[debug-2.6.2.mnn.tar.gz](https://github.com/alibaba/MNN/files/12839970/debug-2.6.2.mnn.tar.gz)

附件包含了一个原始的onnx模型，以及版本2.6.2的MNNConvert和最新拉取的MNNConvert转化后的mnn模型，转换命令均为

`./MNNConvert -f ONNX --modelFile debug.onnx --MNNModel debug.mnn --bizCode MNN`

在Jetson Orin上运行benchmark的效果是

```bash
MNN benchmark
Forward type: CPU thread=1 precision=2 sparsity=0 sparseBlockOC=1 testQuantizedModel=0
--------> Benchmarking... loop = 300, warmup = 50
[-INFO-]: precision=2, use fp16 inference if your device supports and open MNN_ARM82=ON.
The device support i8sdot:1, support fp16:1, support i8mm: 0
[ - ] debug-2.6.2.mnn             max =   35.441 ms  min =   20.577 ms  avg =   20.980 ms
[ - ] debug.mnn                   max =   65.686 ms  min =   60.936 ms  avg =   61.805 ms
```

**Comment by jxt1234** [comment]
我们看一下

**Comment by jxt1234** [comment]
初步看了一下，应该是 GELU 合并原先是用的近似计算，2.6.3 之后修正为原始的计算模式所致。如果确认模型推理结果没有问题，可以把 tools/converter/source/optimizer/merge/FuseTemplateOp.cpp 349 行 UnaryOpOperation_GELU_STANDARD 改成 UnaryOpOperation_GELU 。
