### ISSUE TITLE
MNN安卓端mobilenetv2分类任务多线程运行结果会变化

### ISSUE THREAD

**Issue by yizhaoyanbo** [alibaba/MNN#262]
今天编译好的MNN安卓库，只用CPU，4个线程(config.numThread = 4)跑mobilenetv2 分类任务。使用荣耀9安装apk后，多次点击app运行，分类结果不一致（蓝色标记为正确结果），如下：
![捕获](https://user-images.githubusercontent.com/26928415/63513026-c154f180-c517-11e9-8ee6-100132910867.JPG)

这个情况在小米8上测也会出现。

我改为单线程跑(config.numThread = 1)，不会出现上述情况。
困惑，求解答。

**Comment by jxt1234** [comment]
请检查你调用的代码，这个和mnn 关系不大。一般原因是在 session 还没有准备好时异步执行了推理

**Comment by jiarenyf** [comment]
@jxt1234 用MNNV2Basic.out进行测试时，有时候输出也会很奇怪。。。
网络结构含有1*8的dilation cnn，在I7电脑上CPU测试一次且输出正确需要8秒，但是有时候输出很快只要20ms，不过这时候结果一定是错的。。。

**Comment by yizhaoyanbo** [comment]
mobilenetv2分类应该是多线程的问题，单线程跑结果是正常的，就是比较慢。

**Comment by jiarenyf** [comment]
@yizhaoyanbo 对，所以多线程还是有问题的。。。

**Comment by jxt1234** [comment]
把 MNN_USE_THREAD_POOL 设成 OFF ，用 openmp 多线程有问题么

**Comment by yizhaoyanbo** [comment]
@jxt1234 
我试了下，设置MNN_USE_THREAD_POOL为OFF，重新编译库测还是不行。

**Comment by li-qing** [comment]
> @jxt1234
> 我试了下，设置MNN_USE_THREAD_POOL为OFF，重新编译库测还是不行。

确认一下 看日志这里是多次执行取平均？数据有每次都输入么？

**Comment by yizhaoyanbo** [comment]
@li-qing 
已经麻烦@jxt1234帮忙复现了，给出了解决方案。应该是reshape的时候对onnx的兼容性问题，希望下一个版本能更新。

**Comment by li-qing** [comment]
> @li-qing
> 已经麻烦@jxt1234帮忙复现了，给出了解决方案。应该是reshape的时候对onnx的兼容性问题，希望下一个版本能更新。

那么0.2.0.9里应该已经修复过了

**Comment by yizhaoyanbo** [comment]
@li-qing @jxt1234 
确实，更新到0.2.0.9已经OK了，感谢大佬们。

**Comment by jiarenyf** [comment]
。。。我这边也有这个问题，用的0.2.0.9版本，但是线程数改为1也有这个问题。。。

**Comment by yizhaoyanbo** [comment]
@jiarenyf 
我的模型是从onnx转过来的，他们修了reshape的bug就好了，不是多线程的问题。你可以在他们mnn的开发群里提出来。
