### ISSUE TITLE
MNNConvert 在2.7.1版本转换的mnn模型无法预测出结果

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#2621]
我使用的2.7.1版本编译的Android armv7和armv8包，使用 2.5.0的MNNConvert 转换的mnn模型可以正常在2.7.1版本上预测，但2.7.1上转换的mnn模型就无法正常输出结果。
我将两个模型转成json对比后，使用BeyondCompare对比后，除了开始的版本和最后的id不一样以外，其他基本一致。

**Comment by yangy996** [comment]
[cls-2.5.0.json](https://github.com/alibaba/MNN/files/13052459/cls-2.5.0.json)
[cls-2.7.1.json](https://github.com/alibaba/MNN/files/13052461/cls-2.7.1.json)

**Comment by v0jiuqi** [comment]
这两个模型文件的大小一致吗。我也比较了这两个JSON文件，确实除了开始的版本和最后的id不一样以外，其他完全一致

**Comment by yangy996** [comment]
> 这两个模型文件的大小一致吗。我也比较了这两个JSON文件，确实除了开始的版本和最后的id不一样以外，其他完全一致



> 这两个模型文件的大小一致吗。我也比较了这两个JSON文件，确实除了开始的版本和最后的id不一样以外，其他完全一致

一致，在2.5.0版本下预测是 0.73，在2.7.0版本下结果是0

**Comment by yangy996** [comment]
![image](https://github.com/alibaba/MNN/assets/15188456/67ee6533-562d-4bed-81fb-5eb6a848fdcc)
在新的版本中，我将norm的值扩大两倍，就有结果出来，但结果也不是特别准
初始值是normValues={1.0 / 0.5 / 255.0, 1.0 / 0.5 / 255.0, 1.0 / 0.5 / 255.0}，这是什么导致的呢？
