### ISSUE TITLE
android armeabi-v7a build with NDK-r25c failed

### ISSUE THREAD

**Issue by DaydreamCoding** [alibaba/MNN#2627]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android armeabi-v7a with NDK r25c

# Github版本:
# Github Version:
master 2.7.2

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:65:1: error: invalid instruction, any one of the following would fix this:
vmov.f16 q4, #5.0
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:65:10: note: operand must be a register in range [s0, s31]
vmov.f16 q4, #5.0
         ^
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:65:5: note: invalid operand for instruction
vmov.f16 q4, #5.0
    ^
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:66:1: error: invalid instruction, any one of the following would fix this:
vmov.f16 q5, #-5.0
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:66:10: note: operand must be a register in range [s0, s31]
vmov.f16 q5, #-5.0
         ^
MNN/source/backend/arm82/asm/arm32/MNNGeluFP16.S:66:5: note: invalid operand for instruction
vmov.f16 q5, #-5.0
    ^

```
粘贴在这里
Paste log here or pastebin
```

**Comment by v0jiuqi** [comment]
已修复

**Comment by viviansmlie** [comment]
MNNGeluFP16.S:65:1: error: invalid instruction, any one of the following would fix this:
vmov.f16 q4, #5.0

想请教一下，这个问题是怎么解决的啊~
