### ISSUE TITLE
android jni中是否存在内存泄漏问题

### ISSUE THREAD

**Issue by zeyuanlicbpm** [alibaba/MNN#263]
jni中存在三个获取Tensor数据的方法：TensorGetUINT8Data，TensorGetIntData，nativeTensorGetData
前两种方法：
auto tensor = (MNN::Tensor *)tensorPtr;
    if (nullptr == dest) {
        return tensor->elementSize();
    }

    auto length = env->GetArrayLength(dest);
    if (tensor->host<int>() == nullptr) {
        // GPU buffer
        std::unique_ptr<MNN::Tensor> hostTensor(new MNN::Tensor(tensor, tensor->getDimensionType(), true));
        tensor->copyToHostTensor(hostTensor.get());
        tensor = hostTensor.get();
    }

    auto size = tensor->elementSize();
    if (length < size) {
        MNN_ERROR("Can't copy buffer, length no enough");
        return JNI_FALSE;
    }

    auto destPtr = env->GetIntArrayElements(dest, nullptr);
    ::memcpy(destPtr, tensor->host<int>(), size * sizeof(int));
    env->ReleaseIntArrayElements(dest, destPtr, 0);

    return JNI_TRUE;
我想问的是，假如数据在GPU上时，创建的hostTensor指向的空间会不会导致内存泄漏呢？

**Comment by jxt1234** [comment]
此处应该会有内存访问越界的问题，后续修改

**Comment by jxt1234** [comment]
Fixed
