### ISSUE TITLE
请问： 推理时候功耗配置项powerMode 如果从默认normal改为low ，为达到减少功耗的目标，会如何影响其他性能，比如内存，精度等

### ISSUE THREAD

**Issue by zhanghongwei** [alibaba/MNN#2632]
请问： 推理时候功耗配置项powerMode 如果从默认normal改为low ，为达到减少功耗的目标，会如何影响其他性能，比如内存，精度等？  thx

**Comment by jxt1234** [comment]
目前 powermode 设成 low 只对高通平台用 mnn opencl backend 生效，具体可见 source/backend/opencl/core/OpenCLBackend.cpp 
高通GPU 上有扩展设置 opencl 的运行优先级
