### ISSUE TITLE
mnn getsessioninfo获取的memory是申请的总内存吗？

### ISSUE THREAD

**Issue by xin486946** [alibaba/MNN#2642]
mnn getsessioninfo获取的memory是申请的总内存吗？
在MNN/source/core/MNNMemoryUtils.cpp里统计malloc的总size，会比getsessioninfo获取的memory要大，这是为什么？

**Comment by jxt1234** [comment]
getSessionInfo 是 MNN 统计的内存，具体统计方式见 source/core/BufferAllocator.cpp
MNN 在创建网络过程中有可能会对一些算子做权重重排、常量折叠等操作，此时会申请临时内存，用完即释放，所以统计的 malloc 的 size 会比这个值大

**Comment by xin486946** [comment]
> getSessionInfo 是 MNN 统计的内存，具体统计方式见 source/core/BufferAllocator.cpp MNN 在创建网络过程中有可能会对一些算子做权重重排、常量折叠等操作，此时会申请临时内存，用完即释放，所以统计的 malloc 的 size 会比这个值大

若有统计所有内存，如何修改？
