### ISSUE TITLE
valgrind检查发现express接口存在Conditional jump or move depends on uninitialised value

### ISSUE THREAD

**Issue by shine-xia** [alibaba/MNN#2643]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux x86_64

# Github版本:
# Github Version:
94e1212b837ea160aed908a83c81b87c475fe7a2
版本2.7.1

问题说明：
CPUBackend.cpp，line 222，创建backend对象时，有一个条件判断：
```
    if (mRuntime->getAllocatorType() == Runtime::Allocator_Defer) {
        mDynamicAllocator.reset(new DeferBufferAllocator(defaultAlloc));
    } else {
        mDynamicAllocator.reset(new EagerBufferAllocator(defaultAlloc));
    }
```
在interpreter接口中，runtime通过Interpreter.cpp, line 254，对runtime的memoryAllocatorType变量进行了初始化
```
runtime.second->setAllocatorType(mNet->modes.memoryAllocatorType);
```
但是在express接口中，runtime创建后直接用于创建backend了，并没有进行初始化，并且runtime对象的构造函数里也没有赋初值，结果可能是随机的。

**Comment by jxt1234** [comment]
已知问题，内部已经修复，等同步吧

**Comment by shine-xia** [comment]
> 已知问题，内部已经修复，等同步吧

你好，还发现另外一个类似问题，会一起修复吧？

StaticModule.cpp, line 256, 构造函数内，会使用scheduleInfo.validForResize进行条件判断。
```
bool needResize = scheduleInfo.validForResize && mResource->mModes.inputMode == Interpreter::Session_Input_Inside;
mSession.reset(new Session(std::move(scheduleInfo), mResource->mModes, std::move(rt)));
resetInputOutputs();
if (needResize) {
    mSession->resize();
}
```
PipelineModule.cpp, line 517, 定义一个scheduleInfo对象时，没有手动对validForResize初始化，Schedule::ScheduleInfo结构体也没有自定义构造函数，使用默认构造函数的话，定义在栈上的对象的成员变量初始值在构造时是随机的。
```
Schedule::ScheduleInfo scheduleInfo;
```

**Comment by jxt1234** [comment]
了解，会一并修正

**Comment by jxt1234** [comment]
已经修正
