### ISSUE TITLE
Mac m2上，无法调用opencl、vulkan

### ISSUE THREAD

**Issue by Baiyuetribe** [alibaba/MNN#2647]
# 编译方式:
mac m2(arm64)
`cmake -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=install -DMNN_METAL=ON -DMNN_OPENCL=ON -DMNN_OPENGL=OFF -DMNN_VULKAN=ON -DMNN_SEP_BUILD=OFF -DMNN_USE_SYSTEM_LIB=ON ..`
编译正常通过。

代码里调用vulkan时，报错
`Can't Find type=7 backend, use 0 instead`

已尝试过cmake和dlopen加载等方法，均无效

**Comment by jxt1234** [comment]
mac 上调用 vulkan 需要安装 https://github.com/KhronosGroup/MoltenVK 。 OpenCL 不能调用的 log 是？

**Comment by Baiyuetribe** [comment]
@jxt1234 vulkan确认已安装。OpenCL的报错也一样`Can't Find type=3 backend, use 0 instead`.
能否将vulkan或opencl也静态化打包到mnn库里呢？以及有其他解决办法吗

**Comment by jxt1234** [comment]
静态库需要额外加 all_load 去触发加载，设置 -DMNN_BUILD_SHARED_LIBS=ON 吧

-DMNN_SEP_BUILD=ON 可以把 opencl / vulkan 打包进 mnn 库里面
