### ISSUE TITLE
MNN resize 后，32位和64位结果对不上

### ISSUE THREAD

**Issue by keke444** [alibaba/MNN#2648]
Hi:

       使用mnn-1.2 版本，模型输入（1，3，256，256），resize到（1，3，256，192）后，32位和64位结果能对上，
但resize到(1, 3, 256,160)后，32位和64位结果就对不上了，差别还是挺大的
更新mnn2.0版本后，又可以对上。请问是1.2 版本，resizetensor 和resizesession  是必须64位对齐吗？

谢谢

**Comment by keke444** [comment]
另外我们使用动态库就会有这个问题，编译静态库就不会有，这mnn的静态库和动态库还有区别吗

**Comment by jxt1234** [comment]
估计是历史版本有内存越界问题，新版本如果复现再重新提 issue 吧
