### ISSUE TITLE
执行C++ inforence的时候出现Reshape error: 0 -> 216 Compute Shape Error for 200 Can't run session because not resized Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hfwanguanghui** [alibaba/MNN#2649]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# Github版本:
commit 91ad3954184b2b77bd1d9d5a6947d4bf556c15e5

# 编译方式:
rm build_pc -rf
mkdir build_pc
cd build_pc

cmake  -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_DEMO=ON ..

make -j16

mnn_test.cpp
`#include <MNN/AutoTime.hpp>
#include <MNN/expr/ExecutorScope.hpp>
#include <MNN/expr/Expr.hpp>
#include <MNN/expr/Module.hpp>
#include <MNN/expr/NeuralNetWorkOp.hpp>
#include <iostream>

using namespace MNN::Express;
int main(int argc, char*argv[])
{
    int nthreads = 1;
    const std::string model_filename = argv[1];
    const std::vector<std::string> input_names{"0", "hidden"};
    const std::vector<std::string> output_names{"275","338"};
    MNN::BackendConfig config;
    std::shared_ptr<MNN::Express::Executor> executor(Executor::newExecutor(MNN_FORWARD_CPU, config, nthreads));
    MNN::Express::ExecutorScope scope(executor);

    std::unique_ptr<Module> module;
    Module::Config mdconfig;
    mdconfig.rearrange = true; // Reduce net buffer memory
    {
        AUTOTIME;
        module.reset(Module::load(input_names, output_names, model_filename.c_str(), &mdconfig));
    }
    std::cout << "Loaded" << std::endl;
    // Load inputs
    std::vector<VARP> inputs(2);
    inputs[0] = _Input({1, 15,256,1}, NHWC, halide_type_of<float>());
    inputs[1] = _Input({1, 1, 28}, NHWC, halide_type_of<float>());

    for (size_t i = 0; i < 15*256; i++)
    {
        inputs[0]->writeMap<float>()[i] = 0.01f;
    }
    
    for (size_t i = 0; i < 28; i++)
    {
        inputs[1]->writeMap<float>()[i] = 0.0;
    }

    std::vector<VARP> outputs  = module->onForward(inputs);
    std::cout<<"output0 datasize:"<<outputs[0]->getInfo()->size<<std::endl;
    std::cout<<"output1 datasize:"<<outputs[1]->getInfo()->size<<std::endl;

    for (int i = 0; i < 10; ++i) {
        std::cout << outputs[0]->readMap<float>()[i] <<" ";
    }

    for (int i = 0; i < 10; ++i) {
        std::cout << outputs[1]->readMap<float>()[i] << std::endl;
    }

    std::cout<<"Hello world";
    return 0;
}`

CMakeLists.txt
`cmake_minimum_required(VERSION 3.0)

project(MNNInference)

# 设置编译器
#set(CMAKE_CXX_COMPILER "g++")

# 设置编译选项
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

# 设置MNN的头文件路径
include_directories(/mnt/fileroot/xx.wan/MNN/include)

# 设置MNN的库文件路径
link_directories(/mnt/fileroot/xx.wan/MNN/build_pc/express)

# 添加可执行文件
add_executable(MNNInference mnn_test.cpp)

# 链接MNN库
target_link_libraries(MNNInference MNN_Express)`

可以正确得到执行可执行文件：
MNNInference

执行 MNNInference CRN.mnn得到如下结果
The device support i8sdot:0, support fp16:0, support i8mm: 0
Loaded
Reshape error: 0 -> 216
Compute Shape Error for 200
Can't run session because not resized
Segmentation fault (core dumped)

MNN模型获取方式：
 MNNConvert -f ONNX --modelFile CRN_16K6_20230906_SpecLoss_Small1102.onnx --MNNModel CRN.mnn --bizCode MNN --keepInputFormat

附件中提供onnx文件和MNN文件

[models.zip](https://github.com/alibaba/MNN/files/13264209/models.zip)

谢谢帮忙指点一下。

**Comment by hfwanguanghui** [comment]
GetMNNInfo CRN.mnn 
The device support i8sdot:0, support fp16:0, support i8mm: 0
Model default dimensionFormat is NCHW
Model Inputs:
[ 0 ]: dimensionFormat: NCHW, size: [ 1,15,256,1 ], type is float
[ hidden ]: dimensionFormat: NCHW, size: [ 1,1,28 ], type is float
Model Outputs:
[ 275 ]
[ 338 ]
Model Version: 2.7.2

**Comment by v0jiuqi** [comment]
用testMNNFromOnnx.py这个脚本先测试一下，如果最后结果没有出现 Test Success 再在此Issue下回复

**Comment by hfwanguanghui** [comment]
> 用testMNNFromOnnx.py这个脚本先测试一下，如果最后结果没有出现 Test Success 再在此Issue下回复

出现了Test Success。

**Comment by v0jiuqi** [comment]
> > 用testMNNFromOnnx.py这个脚本先测试一下，如果最后结果没有出现 Test Success 再在此Issue下回复
> 
> 出现了Test Success。

那就说明MNN转模型以及推理没有问题
