### ISSUE TITLE
Incorrect output of the 1st interpreter if there are 2 instances.

### ISSUE THREAD

**Issue by jiarenyf** [alibaba/MNN#265]
- I use 2 interpreters instance of difference models in one android app:

```
interpreter1 = Interpreter::createFromFile(modelPath1)
session1 = interpreter1->createSession(config1)

interpreter2 = Interpreter::createFromFile(modelPath2)
session2 = interpreter2->createSession(config2)
```

- **When I initialize `interpreter1` before `interpreter2`, the output of `interpreter2` is correct while the output of `interpreter1` is random around 0.**

- **When I initialize `interpreter2` before `interpreter1`, the output of `interpreter1` is correct while the output of `interpreter2` is random around 0.**

- **I create the two instances in the main thread, and run each session in different thread**, is this matter ?

- I wonder why and how to solve the problem ...

**Comment by jiarenyf** [comment]
@czy2014hust Do you have any idea ...

**Comment by jiarenyf** [comment]
The 2 model have the same structure and corresponding tensors have the same name, is this matter ?

**Comment by jxt1234** [comment]
What's your code of "run each session in different thread,"

**Comment by jiarenyf** [comment]
The problem disappeared, and I don't know why ...

**Comment by jiarenyf** [comment]
The problem occurs again, and I don't know why ...

**Comment by vealocia** [comment]
did you find out the reason? I meet this problem and don't know how to solve it

> The problem occurs again, and I don't know why ...
