### ISSUE TITLE
if i want to use Opencv2 to read image, what can i do

### ISSUE THREAD

**Issue by xudh1991** [alibaba/MNN#267]
I get this error, when i add opencv2 into pictureRecognition
/usr/local/include/opencv2/flann/any.h: In member function ‘virtual const std::type_info& cvflann::anyimpl::typed_base_any_policy<T>::type()’:
/usr/local/include/opencv2/flann/any.h:58:59: error: cannot use typeid with -fno-rtti
     virtual const std::type_info& type() { return typeid(T); }

**Comment by jiarenyf** [comment]
https://github.com/alibaba/MNN/blob/27f45dac83aae27d147c8c58d346a230d900dfce/CMakeLists.txt#L131

Change `-fno-rtti -fno-exceptions` to `-frtti -fexceptions`, and everything is ok ...

**Comment by xudh1991** [comment]
Thank you for your answer. I've solved it,

**Comment by ybai62868** [comment]
I still have this problem when I change  -fno-rtti -fno-exceptions to -frtti -fexceptions. Can you help me to solve this problem when I want to use opencv in my mnn inference code.

**Comment by DengZeshuai** [comment]
I did what @jiarenyf said, but it still reports an error, ```undefined reference to `cv::String::deallocate()'```. Does anyone know how to fix that?
