### ISSUE TITLE
量化感知训练 demo 不可用

### ISSUE THREAD

**Issue by happat12138** [alibaba/MNN#2674]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Linux X86

# Github版本:
8d5d8b8844893d4cc1d6e0d3572870b8d53867e3

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_QUANTOOLS=ON -DMNN_BUILD_TRAIN=ON -DMNN_BUILD_TRAIN_MINI=OFF -DMNN_USE_OPENCV=OFF -DMNN_CUDA=ON -DMNN_BUILD_DEMO=ON 
cmake --build . -j32

# 编译日志:
# Build Log:
编译通过

# 问题
1. 编译后下载提供的 mobilenetv2 的预训练模型进行训练量化，在保存时 ConvertToFullQuant::convert 函数（train/source/demo/MobilenetV2Utils）内部报错 Segmentation fault (core dumped)
2. 根据文档 https://www.yuque.com/mnn/cn/bhz5eu , 使用 PipelineModule::extract 和 PipelineModule::turnQuantize 替换 mobileetV2Train.cpp 中 MobilenetV2TrainQuant 部分的  NN::extract 和  NN::turnQuantize，编译报错，提示 PipelineModule::turnQuantize 找不到函数。
3. python 3.7.16, mnn 2.5.1, 使用 pymnn 训练时量化保存的模型不对，训练时多次运行 test_func 会出现 Segmentation fault (core dumped)
4. 在 train/source/demo/ 下添加自己的 demo，使用  ConvertToFullQuant::convert  函数时链接时出错，报 convert 函数 multidefine 问题

**Comment by jxt1234** [comment]
参考 https://mnn-docs.readthedocs.io/en/latest/tools/compress.html 文档试一下

**Comment by happat12138** [comment]
> 参考 https://mnn-docs.readthedocs.io/en/latest/tools/compress.html 文档试一下

Hi, 我发现 mnncompress 工具中模型剪枝工具使用 TaylorFOChannelPruner 进行通道剪枝，发现对于 resnet 和 mobilenet 中的残差连接会出现通道无法对齐的问题。请问目前 TaylorFOChannelPruner 有支持任意拓扑结构的能力吗

**Comment by happat12138** [comment]
> 参考 https://mnn-docs.readthedocs.io/en/latest/tools/compress.html 文档试一下
hi，我发现 mnncompress 工具中的通道剪枝 TaylorFOChannelPruner 会对于 resnet 和 mobilenet 有残差连接的的模型会导致模型通道对不齐，导致推理出错，这个是不是对模型拓扑结构有要求？
