### ISSUE TITLE
MNN_THREAD_POOL_MAX_TASKS 具体是什么意思？>=3个模型分别创建interpreter和session且并行 是否有问题？

### ISSUE THREAD

**Issue by xin486946** [alibaba/MNN#2678]

**Comment by jxt1234** [comment]
MNN_THREAD_POOL_MAX_TASKS 表示线程池最多可供几个运行时持有。默认情况下每个Session单独持有一个运行时，也即最多只有 2 个模型可以并行。
可以通过 https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id7 共享运行时，解除这个限制。

**Comment by xin486946** [comment]
> MNN_THREAD_POOL_MAX_TASKS 表示线程池最多可供几个运行时持有。默认情况下每个Session单独持有一个运行时，也即最多只有 2 个模型可以并行。 可以通过 https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id7 共享运行时，解除这个限制。

>=3个模型是并行的，不需要共享运行时资源，要相互独立。>=3个模型分别创建interpreter和session且并行，这样是否受MNN_THREAD_POOL_MAX_TASKS限制？

**Comment by jxt1234** [comment]
受限制，可以把 MNN_THREAD_POOL_MAX_TASKS 设大

**Comment by 486946** [comment]
> 受限制，可以把 MNN_THREAD_POOL_MAX_TASKS 设大
我实验，不把MNN_THREAD_POOL_MAX_TASKS 设大，>=3个模型分别创建interpreter和session且并行 没有问题
