### ISSUE TITLE
高通的android设备跑npu失败，报Can’t Find type=5 backend

### ISSUE THREAD

**Issue by yiguanxian** [alibaba/MNN#2679]
运行npu时报：Can’t Find type=5 backend
这个应该是编译出来的mnn库不带mnn_nnapi，不知道如何解决。
mnn版本：2.7.0
编译方式：cd mnn/project/android/build-64;../build_64.sh -DMNN_NNAPI=ON
ndk:r23

**Comment by jxt1234** [comment]
编译时NNAPI 相关代码编进去了么?

**Comment by yiguanxian** [comment]
默认nnapi库和mnn库是分开的，但编译产物里并没有nnapi相关的库

**Comment by yiguanxian** [comment]
@jxt1234 编进去了
![Uploading 191461D0-50B1-4965-BAF6-53EA7CD78E1B.jpeg…]()

**Comment by jxt1234** [comment]
修改下 build_64.sh 脚本，把 ANDROID_NATIVE_API_LEVEL 改成 29 看看

**Comment by jxt1234** [comment]
另外你是什么机器

**Comment by yiguanxian** [comment]
问题：android设备调用mnn的MNN_FORWARD_NN走npu硬件推理模型，报Can’t Find type=5 backend
办法：请按如下顺序做校验：
  1.要求目标设备必须是android10.0以上，即配置编译参数ANDROID_NATIVE_API_LEVEL>=29。
  2.检查编译出来的libMNN.so是否包含`NNAPI`相关接口。命令是：strings libMNN.so | grep NNAPI。
  3.检查是否加载到安卓设备上的libneuralnetworks.so库（具体位置在：NNAPISymbol.cpp:loadNNAPISymbol）。
