### ISSUE TITLE
int8的模型比fp16的模型还大

### ISSUE THREAD

**Issue by yiguanxian** [alibaba/MNN#2686]
模型：模型有大量的matmul算子
1. cvt to int8 cmd：
MNNConvert -f ONNX --batch 1 --optimizeLevel 1 --optimizePrefer 2 --bizCode biz --weightQuantBits 8 --weightQuantAsymmetric --modelFile vad_20231201_pruned_sim_v3.onnx --MNNModel vad-int8-1.mnn

2. cvt to fp16 cmd：
MNNConvert -f ONNX --batch 1 --optimizeLevel 1 --optimizePrefer 2 --bizCode biz --fp16 --modelFile vad_20231201_pruned_sim_v3.onnx --MNNModel vad-fp16-1.mnn

3.模型大小
31M vad_20231201_pruned_sim_v3.onnx
16M vad-fp16-1.mnn
17M vad-int8-1.mnn

**Comment by wangzhaode** [comment]
能否提供一下onnx模型

**Comment by wangzhaode** [comment]
因为int8只针对卷积或者matmul const的情况量化，可能是模型中其他常量占比较大。

提问者没有提供模型无法具体分析，先关闭该issue
