### ISSUE TITLE
请问使用pytorch训练的模型可以进行量化吗

### ISSUE THREAD

**Issue by Fight-hawk** [alibaba/MNN#269]

**Comment by Fight-hawk** [comment]
使用pytorch框架训练的模型，转成onnx后可以成功转换为mnn，但是使用量化工具一直报错，是因为还不支持onnx量化吗

**Comment by czy2014hust** [comment]
报什么错？跟onnx没有关系

**Comment by Fight-hawk** [comment]
modelFile=s /Users/kanhaipeng/Downloads/model_best.mnn in main, 21 
preTreatConfig=s ../../../tools/quantization/hrnetcoonfig.json in main, 22 
dstFile=s quan_model_best.mnn in main, 23 
[15:58:08] /Users/kanhaipeng/Pyproject/MNN/tools/quantization/quantized.cpp:50: calibrate the feature according to KL-divergence and quantize model...
Invalid json
Can't find tensors for 4332
Segmentation fault: 11

**Comment by Fight-hawk** [comment]
抱歉 已解决 原来是json文件路径出错了，指向了一个不存在的文件，建议Invalid json 提示可以考虑这种情况

**Comment by ChenCongGit** [comment]
你好我出现了另一个问题，我是用pytorch写的模型，通过onnx转化为mnn模型，使用mnn自带的量化工具进行量化，结果报错：/data00/home/chencong/MNN/tools/quantization/calibration.cpp:142: Input Data Format ERROR!The ConvertTensor2's input is not ready

**Comment by sudabai666** [comment]
@ChenCongGit  和你出现同样的问题了，你解决了吗？

**Comment by yyfcc17** [comment]
请更新代码，最新代码已经解决此问题

**Comment by lilili-0203** [comment]
大家更新完代码这个问题还有吗

**Comment by lilili-0203** [comment]
@yyfcc17 我使用最新版也是有这个问题

**Comment by buptlj** [comment]
> 抱歉 已解决 原来是json文件路径出错了，指向了一个不存在的文件，建议Invalid json 提示可以考虑这种情况

几年过去了，还是只有一个Invalid json 提示，就不能把信息提示清楚一些吗
