### ISSUE TITLE
iOS demo编译报错Undefined symbols___CPUQuantizeLinearCreator__OpType_QuantizeLinear__

### ISSUE THREAD

**Issue by zcs110** [alibaba/MNN#2692]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
MAC M1 芯片
# Platform(Include target platform as well if cross-compiling):  
目标平台iOS

cd MNN
mkdir build && cd build
cmake -DMNN_BUILD_CONVERTER=ON ..
make -j8
```
wget https://github.com/shicai/MobileNet-Caffe/blob/master/mobilenet_v2.caffemodel
wget https://github.com/shicai/MobileNet-Caffe/blob/master/mobilenet_v2_deploy.prototxt
./MNNConvert -f CAFFE --modelFile mobilenet_v2.caffemodel --prototxt mobilenet_v2_deploy.prototxt --MNNModel mobilenet_v2.caffe.mnn
mv mobilenet_v2.caffe.mnn ../resource/model/MobileNet/v2/

# Github版本:
# Github Version:
1.2.0

```
错误信息
ld: Undefined symbols:
  MNN::___CPUQuantizeLinearCreator__OpType_QuantizeLinear__(), referenced from:
      MNN::registerCPUOps() in MNN[197](CPUOPRegister.o)
  MNN::___CPUDequantizeLinearCreator__OpType_DequantizeLinear__(), referenced from:
      MNN::registerCPUOps() in MNN[197](CPUOPRegister.o)

**Comment by RobertLiu0905** [comment]
请问这个问题解决了吗

**Comment by luomo-pro** [comment]
同问，遇到了同样的报错
