### ISSUE TITLE
model convertion failure

### ISSUE THREAD

**Issue by RookieHuang** [alibaba/MNN#2695]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu 18.04.6 LTS
# Github版本:
# Github Version:
commit ID：1ea55f467fb231655cf1e08f77d4a0f1043c4c29

# 编译方式:
# Compiling Method
According to the official compilation method

# 编译日志:
# Build Log:
Build success

# 问题
## 1.convert
when I try to convert the model of transformer structure, covert success as follow:
**script:**./MNNConvert -f ONNX --modelFile ightglue.onnx --MNNModel lighglue.mnn --bizCode biz --debug
**result:**
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:05:01] /home/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:05:01] /home/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc0, kpts0, desc1, kpts1, ]
outputTensors: [ matches0, mscores0, ]
Converted Success!
## 2.testMNNfromONNX
but when I run testMNNfromONNX.py, something went wrong:
**script**:python testMNNFromOnnx.py lightglue.onnx DEBUG
**result:**
Dir exist
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['matches0', 'mscores0']
inputs:
kpts0
onnx/
kpts1
onnx/
desc0
onnx/
desc1
onnx/
outputs:
onnx/matches0.txt (0, 2)
onnx/
onnx/mscores0.txt (0,)
onnx/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:39] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:39] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc0, kpts0, desc1, kpts1, ]
outputTensors: [ matches0, mscores0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:39] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:39] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc0, kpts0, desc1, kpts1, ]
outputTensors: [ matches0, mscores0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Debug Mode:  True
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['/log_assignment.8/Log_1_output_0']
inputs:
kpts0
onnx/
kpts1
onnx/
desc0
onnx/
desc1
onnx/
outputs:
onnx//log_assignment.8/Log_1_output_0.txt (1, 256, 1)
onnx//log_assignment.8/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:42] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:42] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc1, kpts1, desc0, kpts0, ]
outputTensors: [ /log_assignment.8/Log_1_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /log_assignment.8/Log_1 False
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['/log_assignment.8/matchability_1/Add_output_0']
inputs:
kpts0
onnx/
kpts1
onnx/
desc0
onnx/
desc1
onnx/
outputs:
onnx//log_assignment.8/matchability_1/Add_output_0.txt (1, 256, 1)
onnx//log_assignment.8/matchability_1/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:45] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:45] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc1, kpts1, desc0, kpts0, ]
outputTensors: [ /log_assignment.8/matchability_1/Add_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /log_assignment.8/matchability_1/Add False
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['/log_assignment.8/matchability_1/MatMul_output_0']
inputs:
kpts0
onnx/
kpts1
onnx/
desc0
onnx/
desc1
onnx/
outputs:
onnx//log_assignment.8/matchability_1/MatMul_output_0.txt (1, 256, 1)
onnx//log_assignment.8/matchability_1/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:48] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:48] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
Convert MatMul Convolution use shared const B inputs, may increase the model size
inputTensors : [ desc1, kpts1, desc0, kpts0, ]
outputTensors: [ /log_assignment.8/matchability_1/MatMul_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /log_assignment.8/matchability_1/MatMul False
Error is between  Identity_0  and  /log_assignment.8/matchability_1/MatMul
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['/transformers.8/cross_attn/Add_1_output_0']
inputs:
kpts0
onnx/
kpts1
onnx/
desc0
onnx/
desc1
onnx/
outputs:
onnx//transformers.8/cross_attn/Add_1_output_0.txt (1, 256, 256)
onnx//transformers.8/cross_attn/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[11:09:52] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:09:52] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
inputTensors : [ desc1, kpts1, desc0, kpts0, ]
outputTensors: [ /transformers.8/cross_attn/Add_1_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /transformers.8/cross_attn/Add_1 False
**(Program blocking here)**

## 3.models
**models download link:**
https://drive.google.com/file/d/1KDAq2J6bBPcjtryfc79hgXglcw-yiTWz/view?usp=sharing

**Comment by v0jiuqi** [comment]
网址我们无法打开。请发送到邮箱：b25y2525@163.com

**Comment by RookieHuang** [comment]
> 网址我们无法打开。请发送到邮箱：[b25y2525@163.com](mailto:b25y2525@163.com

已经解决，感谢回复！
