### ISSUE TITLE
fp16参数存储的MNN模型，dump到json后Convolution2D和Blob的算子是int8/uint8

### ISSUE THREAD

**Issue by zihaog0724** [alibaba/MNN#2697]
您好，我用MNNConvert加上--fp16参数转换模型，然后用MNNDump2Json查看参数，发现Convolution2D的weight存储的是int8类型(bias是float)，Blob的参数也存的是uint8。

随机挑一个Convolution2D层的示例：
`{'inputIndexes': [3099], 'main_type': 'Convolution2D', 'main': {'common': {'padX': 0, 'padY': 1, 'kernelX': 1, 'kernelY': 3, 'strideX': 1, 'strideY': 1, 'dilateX': 1, 'dilateY': 1, 'padMode': 'CAFFE', 'group': 1, 'outputCount': 8, 'inputCount': 8, 'relu': False, 'relu6': False, 'pads': [1, 0, 1, 0], 'hasOutputShape': False}, 'bias': [-0.116882, 0.068359, -0.031097, 0.022873, -0.118896, 0.016418, -0.175293, 0.087158], 'quanParameter': {'buffer': [-107, -83, 75, -88, 9, 44, -29, 41, -33, 16, 18, -85, 28, -83, -9, 44, -79, 38, 124, 48, -88, 38, 91, 48, -93, 49, -119, 43, -47, 49, 65, 45, 123, -84, -68, -86, 104, 46, 49, -84, 108, -80, -48, -89, -41, 42, 108, -85, -128, -78, 71, 40, 115, -80, -120, -84, -104, -81, -57, 36, -12, 36, 77, 41, 82, -89, -59, -81, 125, -80, 8, -84, 119, 37, 110, -85, -71, 32, 58, 45, -36, -79, 76, 44, 8, 45, -43, -83, -113, -83, 32, -79, 55, -80, -128, 31, -76, -81, 63, 41, 113, -85, -114, -83, -60, -85, 91, 36, 26, -88, 121, -80, 24, -87, -76, -85, -96, 44, -74, -83, 0, 48, 105, -88, 49, 28, 96, -83, 115, -94, 97, -87, 53, -82, -123, 41, 2, 46, -60, -77, 49, 38, -28, 44, -16, -83, -126, 43, 111, -82, 105, -81, 57, -84, -83, 41, 39, -88, -84, -79, -78, 38, 94, -83, -37, -82, -107, 47, -73, 48, -8, -84, 54, 46, -108, -110, 33, -80, -53, -81, -100, -84, 24, 43, 38, 43, -111, -95, 115, -92, -53, -82, 54, 43, -97, 48, 35, -86, -6, 31, -26, -82, -121, 48, 116, -78, 40, -79, -57, -85, 54, 42, 73, 49, -77, 44, 45, 49, 95, -92, -18, -84, -16, 46, -94, -82, 14, 44, 24, -79, 63, 45, -18, -80, 17, -83, 21, -83, -24, -93, 53, 44, -117, -92, 54, -82, -115, 38, -27, -84, -55, 45, 74, -88, -115, -85, 68, 44, -61, 45, 12, -98, 97, -89, -33, 50, -63, -86, 22, -88, -113, 40, 46, -86, -29, 38, 25, -92, -15, -79, 20, -82, -34, -92, -19, -89, 6, -87, -45, 41, -104, -84, 92, -100, 60, -90, -93, -92, 29, -112, -37, 49, 39, 47, -41, 46, 6, -82, -82, 43, 82, 41, 125, -85, -101, 30, -54, 30, 29, -79, 28, 44, 97, 34, 36, -100, 30, -82, 83, -84, 113, 43, 36, 51, -22, -88, -3, 39, -1, 49, -49, 42, -26, -86, -76, 46, 74, 47, 24, -85, -118, -104, -86, -92, -19, 45, 4, -86, -71, -108, -58, 40, 20, 40, -21, -95, -21, 49, 86, -82, -79, 46, 68, -82, -106, -92, -31, 46, -94, -84, -103, 46, -6, -83], 'type': 3, 'useInt32': False, 'quantScale': 0.0, 'scaleIn': 0.0, 'scaleOut': 0.0, 'aMax': 0, 'aMin': 0, 'readType': 0, 'has_scaleInt': False, 'shapeInt32': False, 'weightSize': 0}}, 'name': '/dec/resblocks.12/convs2.2/Conv_output_0', 'outputIndexes': [3100], 'type': 'Convolution', 'defaultDimentionFormat': 'NHWC'}`
可以看到bias是float，weight（buffer）应该是经过了int8量化

随机挑一个Blob层的示例：
`{'main_type': 'Blob', 'main': {'dims': [1, 21, 96], 'dataFormat': 'NCHW', 'dataType': 'DT_HALF', 'uint8s': [228, 184, 125, 56, 118, 52, 10, 51, 21, 56, 122, 57, 147, 49, 202, 186, 68, 180, 53, 179, 112, 52, 67, 48, 243, 51, 94, 48, 207, 54, 63, 54, 166, 184, 12, 161, 14, 161, 52, 56, 100, 56, 48, 56, 207, 183, 222, 53, 62, 58, 206, 41, 195, 53, 109, 49, 77, 186, 167, 185, 141, 57, 73, 59, 228, 56, 153, 183, 234, 54, 153, 186, 112, 184, 30, 41, 151, 180, 60, 54, 59, 53, 133, 178, 39, 184, 81, 183, 8, 181, 209, 183, 158, 57, 154, 181, 80, 51, 51, 52, 47, 57, 24, 181, 108, 183, 85, 169, 135, 183, 196, 180, 183, 181, 24, 165, 121, 182, 107, 56, 144, 50, 114, 55, 62, 52, 42, 53, 157, 177, 169, 53, 82, 49, 81, 56, 216, 185, 67, 177, 204, 183, 215, 171, 46, 56, 152, 54, 122, 47, 164, 178, 210, 55, 244, 54, 170, 57, 167, 183, 109, 56, 103, 36, 126, 49, 135, 51, 5, 45, 127, 176, 36, 37, 245, 184, 82, 50, 190, 182, 207, 55, 253, 176, 180, 56, 242, 185, 81, 57, 34, 184, 246, 180, 44, 54, 96, 50, 36, 47, 199, 52, 223, 55, 37, 160, 70, 185, 185, 181, 77, 172, 54, 173, 26, 48, 69, 51, 119, 47, 215, 45, 201, 159, 249, 179, 46, 176, 20, 49, 183, 48, 184, 48, 26, 51, 4, 183, 127, 55, 101, 51, 127, 165, 148, 49, 36, 38, 52, 186, 186, 181, 77, 50, 87, 57, 173, 55, 199, 180, 236, 54, 4, 184, 38, 183, 69, 46, 25, 29, 122, 52, 208, 54, 6, 175, 9, 180, 78, 177, 20, 180, 182, 180, 220, 54, 210, 181, 175, 169, 243, 47, 108, 55, 69, 179, 57, 170, 237, 38, 194, 180, 30, 181, 222, 176, 19, 44, 29, 178, 218, 52, 246, 52, 160, 51, 95, 53, 50, 46, 10, 181, 209, 55, 135, 47, 133, 48, 140, 183, 113, 182, 133, 178, 199, 177, 112, 49, 55, 56, 206, 50, 63, 178, 142, 54, 167, 53, 111, 55, 34, 183, 108, 53, 10, 30, 212, 50, 132, 164, 209, 46, 40, 176, 11, 160, 179, 183, 38, 47, 7, 175, 117, 53, 9, 172, 136, 56, 110, 180, 242, 53, 192, 181, 149, 182, 236, 53, 169, 52, 136, 50, 194, 53, 131, 56, 129, 180, 144, 184, 133, 182, 113, 182, 79, 54, 12, 44, 119, 48, 244, 166, 148, 52, 93, 53, 159, 183, 75, 180, 73, 52, 4, 53, 207, 55, 242, 54, 160, 183, 232, 52, 252, 55, 5, 164, 120, 53, 97, 49, 239, 184, 72, 183, 163, 54, 140, 56, 215, 56, 22, 181, 196, 55, 254, 183, 82, 185, 11, 50, 196, 164, 71, 51, 21, 57, 61, 177, 229, 178, 50, 183, 165, 179, 122, 181, 123, 56, 26, 181, 178, 44, 59, 51, 89, 54, 212, 180, 234, 180, 114, 158, 246, 183, 219, 168, 231, 182, 97, 177, 173, 177, 144, 53, 119, 50, 128, 55, 248, 55, 91, 50, 238, 182, 2, 55, 30, 49, 41, 54, 238, 183, 214, 181, 244, 182, 113, 176, 93, 54, 156, 56, 189, 54, 140, 178, 181, 53, 219, 56, 222, 54, 98, 183, 20, 55, 0, 178, 112, 19, 7, 180, 232, 162, 138, 182, 34, 40, 77, 182, 97, 50, 166, 181, 1, 54, 20, 177, 59, 57, 77, 179, 237, 53, 45, 183, 243, 180, 49, 48, 70, 49, 216, 48, 130, 53, 214, 56, 21, 178, 84, 181, 191, 180, 194, 182, 63, 54, 242, 174, 15, 51, 206, 168, 166, 54, 27, 52, 28, 185, 122, 182, 112, 48, 100, 45, 58, 54, 98, 55, 138, 181, 125, 52, 255, 54, 53, 39, 255, 52, 145, 51, 17, 183, 64, 185, 153, 52, 247, 53, 168, 56, 1, 183, 32, 56, 177, 183, 124, 184, 72, 39, 45, 172, 53, 47, 4, 55, 93, 177, 205, 182, 143, 181, 114, 181, 83, 182, 35, 55, 0, 183, 236, 44, 149, 52, 115, 56, 69, 182, 229, 177, 179, 44, 250, 185, 246, 179, 39, 180, 189, 179, 114, 179, 236, 52, 190, 49, 125, 56, 38, 56, 239, 45, 147, 178, 195, 53, 163, 170, 97, 54, 143, 184, 220, 182, 33, 184, 200, 176, 8, 52, 25, 53, 152, 54, 66, 176, 190, 53, 100, 57, 81, 53, 225, 183, 89, 54, 133, 182, 82, 37, 181, 177, 216, 41, 139, 177, 79, 174, 86, 180, 71, 53, 101, 180, 205, 53, 192, 176, 77, 56, 128, 183, 93, 54, 170, 180, 155, 179, 140, 47, 90, 52, 83, 50, 179, 52, 138, 51, 145, 173, 183, 180, 219, 178, 62, 158, 199, 52, 90, 47, 230, 53, 188, 167, 129, 41, 169, 43, 216, 176, 129, 179, 13, 50, 202, 51, 248, 51, 140, 163, 105, 177, 21, 50, 50, 53, 46, 49, 106, 50, 174, 46, 179, 181, 190, 177, 110, 53, 14, 48, 237, 52, 46, 180, 238, 51, 205, 180, 25, 182, 80, 50, 143, 40, 106, 49, 5, 56, 56, 174, 68, 177, 191, 176, 33, 180, 46, 179, 60, 50, 106, 181, 20, 174, 52, 54, 94, 53, 31, 179, 29, 173, 209, 156, 151, 183, 6, 183, 33, 179, 215, 177, 17, 168, 35, 46, 226, 52, 215, 52, 39, 49, 117, 45, 242, 181, 229, 41, 206, 175, 230, 52, 163, 180, 245, 183, 81, 174, 212, 168, 220, 44, 198, 53, 152, 52, 67, 181, 172, 51, 193, 53, 82, 48, 136, 182, 124, 50, 181, 174, 66, 43, 38, 180, 42, 48, 112, 182, 215, 172, 90, 179, 107, 47, 168, 173, 18, 53, 140, 173, 158, 52, 31, 181, 204, 54, 146, 180, 247, 181, 198, 48, 121, 47, 65, 168, 12, 52, 33, 29, 89, 178, 98, 179, 43, 44, 232, 172, 219, 50, 79, 36, 163, 48, 9, 178, 254, 175, 240, 163, 149, 47, 33, 183, 138, 50, 103, 176, 117, 52, 232, 38, 209, 160, 160, 52, 95, 47, 231, 48, 34, 180, 117, 179, 208, 174, 28, 168, 171, 52, 130, 43, 111, 30, 170, 178, 246, 46, 148, 173, 129, 45, 164, 52, 39, 163, 10, 176, 164, 54, 142, 156, 159, 47, 3, 174, 173, 170, 50, 179, 106, 166, 32, 182, 134, 177, 64, 56, 138, 32, 159, 173, 1, 44, 89, 44, 124, 178, 200, 178, 17, 177, 80, 174, 27, 169, 232, 172, 170, 36, 86, 49, 238, 50, 103, 39, 146, 181, 34, 173, 166, 176, 35, 52, 78, 174, 213, 183, 119, 32, 92, 43, 107, 42, 27, 49, 84, 54, 114, 169, 1, 52, 131, 45, 104, 180, 119, 173, 87, 53, 129, 44, 222, 45, 203, 181, 122, 52, 195, 181, 226, 176, 185, 175, 132, 169, 235, 47, 24, 52, 146, 176, 218, 48, 6, 176, 253, 175, 114, 178, 227, 164, 46, 176, 30, 48, 95, 180, 98, 47, 84, 180, 143, 47, 72, 33, 153, 45, 161, 169, 168, 49, 123, 53, 32, 174, 85, 177, 181, 177, 219, 180, 21, 54, 188, 178, 156, 44, 85, 178, 178, 50, 254, 183, 232, 174, 3, 50, 228, 178, 22, 52, 195, 181, 99, 181, 103, 164, 244, 49, 100, 52, 127, 177, 44, 181, 131, 47, 239, 47, 76, 50, 149, 52, 0, 53, 158, 30, 65, 176, 153, 53, 101, 176, 247, 50, 38, 50, 45, 181, 102, 176, 1, 164, 153, 179, 100, 180, 152, 55, 28, 178, 201, 170, 112, 171, 104, 169, 37, 32, 100, 180, 204, 176, 136, 172, 198, 49, 81, 180, 14, 40, 90, 178, 11, 177, 96, 173, 249, 176, 198, 180, 135, 176, 228, 22, 192, 48, 225, 182, 106, 49, 31, 51, 42, 176, 63, 49, 31, 52, 181, 170, 102, 165, 160, 178, 98, 182, 138, 50, 200, 46, 19, 53, 155, 48, 191, 182, 82, 49, 128, 177, 195, 175, 147, 47, 137, 180, 136, 49, 179, 171, 236, 175, 171, 176, 226, 51, 202, 180, 193, 46, 234, 49, 236, 180, 253, 177, 189, 48, 198, 159, 0, 186, 188, 32, 28, 175, 177, 53, 104, 48, 57, 52, 240, 55, 219, 182, 236, 181, 183, 180, 1, 185, 52, 57, 245, 177, 76, 176, 110, 179, 204, 47, 5, 185, 186, 176, 255, 152, 76, 185, 252, 50, 132, 185, 95, 182, 2, 53, 100, 57, 169, 52, 164, 177, 207, 184, 114, 53, 229, 174, 63, 56, 69, 54, 167, 48, 73, 51, 98, 183, 155, 174, 3, 53, 3, 56, 59, 57, 17, 182, 124, 174, 182, 172, 93, 182, 123, 183, 234, 53, 134, 183, 104, 46, 126, 42, 29, 167, 171, 54, 234, 183, 115, 176, 31, 45, 228, 53, 246, 184, 128, 50, 156, 184, 172, 180, 138, 177, 219, 180, 156, 181, 237, 176, 48, 183, 40, 55, 36, 181, 252, 55, 132, 56, 145, 182, 126, 53, 80, 52, 18, 52, 39, 170, 187, 185, 167, 184, 91, 53, 139, 174, 75, 56, 158, 52, 237, 183, 225, 173, 22, 184, 215, 181, 234, 54, 232, 184, 123, 54, 247, 169, 75, 181, 160, 178, 210, 56, 105, 185, 60, 54, 157, 55, 194, 180, 12, 173, 168, 48, 66, 44, 12, 188, 141, 37, 178, 174, 61, 57, 252, 55, 81, 52, 212, 56, 3, 184, 215, 185, 10, 178, 6, 187, 224, 58, 125, 179, 75, 174, 159, 179, 172, 52, 67, 186, 192, 153, 190, 40, 148, 187, 232, 49, 9, 188, 4, 185, 26, 56, 227, 59, 125, 51, 239, 45, 73, 185, 3, 55, 127, 176, 1, 58, 31, 57, 240, 54, 147, 55, 104, 187, 217, 177, 88, 54, 122, 59, 90, 60, 70, 182, 156, 49, 225, 173, 86, 181, 152, 182, 62, 54, 86, 186, 152, 53, 53, 54, 54, 180, 114, 55, 196, 187, 237, 181, 96, 177, 150, 56, 240, 185, 30, 54, 89, 188, 237, 185, 45, 177, 70, 181, 45, 182, 28, 182, 162, 185, 246, 54, 20, 181, 18, 58, 62, 56, 79, 184, 105, 53, 44, 42, 136, 52, 195, 171, 168, 186, 31, 185, 48, 56, 170, 181, 211, 58, 233, 54, 200, 183, 153, 30, 235, 185, 133, 180, 234, 56, 130, 187, 248, 54, 150, 171, 243, 176, 133, 177, 240, 56, 124, 186, 20, 56, 160, 56, 127, 179, 132, 180, 135, 56, 187, 171, 244, 187, 158, 49, 154, 179, 218, 56, 7, 58, 155, 49, 187, 57, 239, 185, 189, 185, 193, 178, 108, 189, 166, 59, 233, 179, 175, 180, 53, 181, 119, 55, 16, 186, 162, 171, 59, 44, 111, 188, 73, 51, 41, 188, 131, 185, 56, 55, 87, 60, 2, 52, 219, 48, 219, 186, 71, 56, 176, 177, 12, 59, 53, 56, 65, 53, 35, 55, 199, 187, 133, 181, 103, 54, 93, 60, 176, 59, 177, 182, 20, 52, 78, 172, 245, 183, 203, 179, 102, 51, 246, 184, 208, 47, 151, 51, 181, 181, 148, 53, 130, 187, 83, 184, 146, 178, 167, 56, 138, 185, 130, 55, 119, 188, 138, 185, 36, 178, 167, 183, 90, 180, 62, 179, 40, 185, 31, 53, 132, 181, 251, 57, 50, 55, 157, 185, 123, 56, 222, 46, 29, 168, 236, 35, 6, 185, 140, 185, 15, 56, 0, 184, 6, 58, 213, 54, 84, 184, 158, 171, 116, 185, 248, 183, 46, 57, 31, 188, 201, 56, 135, 37, 1, 180, 189, 182, 48, 58, 183, 187, 82, 57, 86, 57, 50, 173, 151, 181, 244, 54, 10, 12, 151, 185, 21, 53, 68, 181, 134, 56, 91, 58, 97, 52, 99, 57, 93, 187, 245, 186, 185, 181, 200, 188, 6, 60, 224, 177, 252, 180, 66, 184, 158, 54, 191, 186, 118, 40, 107, 44, 250, 188, 181, 55, 34, 188, 180, 184, 197, 53, 116, 60, 156, 53, 92, 48, 142, 186, 224, 53, 38, 165, 156, 59, 123, 56, 32, 55, 85, 53, 161, 188, 167, 179, 250, 56, 76, 61, 76, 60, 6, 184, 251, 48, 121, 154, 83, 184, 39, 179, 121, 49, 40, 186, 106, 41, 133, 54, 240, 181, 33, 50, 81, 188, 80, 185, 254, 183, 200, 56, 106, 186, 214, 56, 62, 189, 83, 186, 22, 176, 224, 185, 117, 180, 192, 181, 239, 185, 217, 54, 48, 184, 126, 57, 67, 56, 18, 186, 117, 57, 130, 40, 194, 45, 39, 176, 105, 186, 192, 186, 127, 57, 118, 182, 252, 56, 240, 55, 147, 184, 105, 168, 228, 186, 244, 184, 188, 57, 103, 187, 184, 56, 45, 178, 129, 172, 33, 179, 102, 58, 34, 188, 211, 57, 130, 56, 217, 175, 122, 179, 137, 55, 201, 42, 135, 185, 196, 49, 4, 180, 225, 53, 182, 56, 127, 51, 54, 58, 86, 186, 30, 186, 58, 183, 235, 187, 74, 58, 126, 41, 13, 183, 53, 183, 155, 57, 228, 186, 50, 171, 96, 34, 12, 188, 136, 53, 44, 188, 161, 184, 14, 57, 122, 60, 255, 52, 60, 49, 172, 186, 12, 56, 0, 177, 24, 58, 123, 56, 1, 53, 166, 51, 23, 188, 130, 179, 0, 55, 143, 60, 128, 60, 177, 183, 175, 47, 50, 45, 222, 180, 131, 180, 161, 52, 6, 186, 207, 51, 196, 54, 124, 181, 216, 52, 252, 187, 199, 184, 146, 183, 21, 55, 13, 186, 89, 56, 65, 188, 139, 185, 46, 172, 89, 184, 238, 177, 93, 183, 127, 186, 28, 55, 37, 184, 28, 58, 37, 50, 81, 184, 27, 57, 68, 167, 182, 49, 129, 177, 116, 184, 14, 186, 226, 57, 215, 176, 221, 56, 184, 54, 162, 184, 82, 177, 151, 186, 125, 185, 158, 56, 101, 186, 102, 56, 123, 179, 6, 46, 159, 178, 253, 57, 94, 187, 192, 58, 238, 55, 240, 180, 161, 176, 28, 56, 94, 48, 60, 187, 181, 171, 151, 32, 120, 56, 202, 55, 108, 50, 158, 56, 168, 186, 122, 185, 125, 181, 236, 185, 1, 58, 228, 165, 197, 180, 73, 179, 248, 54, 170, 185, 14, 41, 220, 50, 15, 187, 178, 52, 151, 187, 242, 184, 44, 57, 44, 60, 233, 54, 76, 161, 82, 185, 206, 54, 224, 176, 64, 58, 213, 56, 94, 55, 79, 52, 174, 187, 234, 181, 149, 51, 67, 59, 42, 60, 110, 184, 226, 49, 120, 47, 92, 180, 132, 172, 203, 51, 118, 185, 135, 53, 86, 54, 117, 181, 4, 52, 12, 186, 167, 184, 136, 182, 12, 56, 95, 185, 17, 56, 237, 188, 77, 185, 29, 179, 54, 184, 94, 178, 52, 181, 158, 184, 87, 56, 175, 184, 120, 57, 126, 53, 224, 184, 16, 58, 117, 162, 184, 47, 199, 180, 224, 185, 67, 186, 113, 58, 138, 174, 223, 55, 146, 53, 51, 184, 78, 173, 74, 186, 107, 181, 116, 55, 78, 188, 197, 54, 136, 171, 92, 37, 226, 178, 201, 56, 134, 187, 151, 58, 225, 53, 203, 177, 109, 172, 101, 53, 240, 45, 205, 185, 15, 172, 129, 177, 190, 49, 125, 52, 1, 52, 40, 52, 166, 184, 89, 183, 112, 183, 84, 185, 213, 55, 98, 176, 2, 177, 13, 179, 11, 55, 213, 183, 135, 44, 201, 51, 150, 185, 148, 52, 36, 185, 65, 184, 33, 56, 24, 56, 211, 53, 113, 178, 163, 183, 86, 52, 175, 181, 239, 56, 176, 55, 78, 50, 222, 41, 65, 184, 165, 177, 135, 49, 39, 58, 13, 58, 69, 181, 75, 49, 41, 48, 101, 179, 17, 176, 111, 50, 20, 184, 248, 50, 49, 52, 190, 180, 164, 54, 8, 186, 19, 179, 137, 179, 61, 57, 34, 183, 100, 52, 32, 187, 234, 182, 20, 179, 182, 182, 64, 177, 4, 176, 211, 181, 126, 49, 134, 184, 1, 56, 112, 52, 252, 184, 160, 53, 73, 48, 241, 36, 33, 176, 246, 184, 209, 184, 235, 56, 29, 172, 235, 55, 43, 48, 16, 182, 239, 40, 137, 185, 72, 181, 195, 56, 142, 186, 252, 53, 39, 51, 111, 167, 54, 44, 83, 54, 78, 185, 171, 55, 113, 46, 160, 167, 61, 157, 237, 48, 23, 49, 24, 179, 204, 176, 242, 179, 88, 47, 67, 169, 80, 46, 229, 42, 77, 179, 62, 176, 235, 180, 125, 178, 85, 49, 221, 172, 252, 173, 52, 38, 237, 51, 73, 173, 189, 37, 139, 50, 77, 177, 74, 50, 189, 179, 154, 179, 81, 53, 236, 48, 209, 48, 20, 180, 128, 176, 28, 49, 146, 179, 1, 48, 249, 36, 226, 48, 146, 180, 150, 178, 170, 38, 134, 171, 156, 48, 192, 50, 224, 177, 229, 42, 150, 21, 218, 173, 178, 44, 111, 51, 118, 177, 254, 51, 255, 46, 229, 181, 59, 55, 168, 180, 72, 180, 35, 165, 227, 52, 6, 181, 199, 41, 70, 179, 106, 32, 121, 178, 233, 181, 161, 179, 208, 29, 198, 47, 186, 52, 138, 183, 42, 50, 151, 169, 140, 179, 53, 50, 176, 40, 84, 173, 45, 50, 131, 180, 210, 181, 11, 55, 136, 41, 174, 43, 213, 46, 97, 178, 115, 49, 63, 184, 100, 177, 203, 45, 219, 182, 104, 48, 77, 40, 91, 174, 115, 49, 99, 176, 185, 177, 243, 54, 18, 176, 208, 49, 69, 170, 63, 38, 81, 49, 48, 163, 169, 179, 19, 180, 43, 176, 243, 177, 155, 53, 239, 171, 163, 44, 111, 50, 129, 39, 72, 41, 138, 44, 254, 167, 178, 47, 155, 47, 248, 45, 205, 42, 168, 172, 187, 52, 167, 53, 26, 52, 252, 27, 86, 172, 65, 45, 179, 177, 66, 52, 179, 170, 136, 51, 220, 179, 43, 178, 152, 177, 105, 174, 82, 162, 47, 181, 238, 177, 60, 51, 48, 181, 198, 159, 110, 175, 95, 180, 224, 166, 18, 52, 99, 176, 177, 37, 105, 41, 249, 22, 91, 175, 55, 175, 20, 181, 97, 17, 212, 42, 23, 176, 79, 178, 216, 49, 249, 51, 206, 173, 189, 37, 25, 50, 161, 175, 216, 180, 175, 41, 220, 9, 26, 55, 120, 38, 242, 183, 72, 42, 41, 174, 11, 36, 35, 53, 104, 41, 152, 176, 115, 49, 42, 49, 130, 33, 193, 173, 13, 53, 139, 40, 21, 171, 145, 41, 190, 48, 188, 178, 12, 182, 189, 31, 41, 176, 78, 170, 52, 47, 166, 178, 3, 51, 242, 182, 20, 42, 11, 50, 25, 177, 62, 50, 220, 172, 251, 48, 78, 55, 60, 53, 52, 172, 20, 182, 63, 178, 154, 180, 60, 54, 126, 176, 171, 51, 169, 53, 128, 43, 250, 50, 34, 180, 126, 170, 152, 52, 62, 53, 128, 52, 93, 56, 83, 182, 59, 53, 0, 57, 134, 38, 70, 49, 154, 51, 71, 180, 85, 183, 24, 54, 244, 52, 3, 54, 225, 180, 171, 49, 152, 181, 137, 182, 64, 178, 42, 182, 129, 51, 99, 54, 108, 180, 122, 180, 175, 181, 206, 181, 15, 177, 47, 56, 248, 177, 88, 47, 250, 47, 180, 53, 125, 180, 241, 178, 132, 48, 76, 170, 14, 174, 171, 179, 185, 177, 77, 36, 233, 51, 31, 48, 70, 55, 165, 52, 19, 49, 182, 182, 21, 54, 26, 51, 69, 57, 206, 177, 170, 183, 240, 181, 38, 174, 94, 50, 90, 55, 188, 51, 224, 170, 239, 52, 230, 55, 146, 48, 201, 180, 6, 56, 18, 180, 228, 171, 212, 32, 58, 47, 134, 178, 121, 180, 148, 182, 196, 52, 177, 181, 48, 53, 23, 180, 14, 53, 110, 183, 111, 51, 54, 177, 33, 179, 249, 53, 115, 167, 116, 50, 24, 56, 115, 55, 242, 181, 111, 182, 234, 181, 49, 184, 200, 55, 179, 182, 53, 56, 80, 48, 193, 45, 54, 52, 218, 182, 237, 42, 241, 53, 222, 55, 114, 55, 191, 52, 215, 180, 14, 57, 102, 56, 248, 41, 117, 53, 109, 54, 89, 184, 128, 184, 234, 45, 221, 52, 192, 54, 49, 184, 163, 52, 79, 184, 52, 184, 125, 180, 66, 180, 187, 53, 129, 57, 33, 181, 173, 181, 229, 183, 143, 178, 178, 178, 162, 56, 102, 40, 4, 52, 3, 44, 230, 53, 51, 182, 207, 182, 39, 48, 143, 181, 218, 171, 242, 179, 69, 181, 195, 179, 197, 53, 42, 166, 219, 56, 12, 56, 116, 173, 147, 181, 59, 51, 189, 50, 148, 56, 130, 181, 104, 184, 31, 184, 38, 176, 126, 52, 122, 54, 41, 51, 168, 180, 45, 55, 112, 56, 147, 56, 38, 182, 82, 56, 103, 180, 203, 176, 112, 170, 216, 49, 130, 179, 95, 177, 173, 183, 110, 50, 102, 182, 30, 54, 207, 178, 23, 52, 79, 184, 69, 55, 64, 182, 31, 176, 10, 54, 192, 48, 4, 57, 19, 54, 139, 53, 223, 178, 190, 181, 124, 182, 113, 181, 95, 54, 214, 179, 236, 52, 170, 41, 5, 51, 205, 49, 99, 180, 152, 175, 165, 52, 152, 54, 90, 54, 142, 51, 203, 182, 64, 55, 163, 56, 66, 36, 25, 56, 141, 49, 155, 183, 53, 184, 222, 42, 5, 53, 230, 52, 59, 184, 181, 56, 106, 183, 186, 182, 19, 176, 127, 181, 158, 41, 167, 53, 57, 182, 5, 178, 109, 182, 207, 180, 10, 31, 9, 55, 198, 35, 193, 47, 248, 44, 213, 53, 53, 183, 208, 175, 220, 170, 156, 181, 48, 179, 24, 180, 97, 180, 186, 28, 173, 51, 186, 162, 99, 56, 4, 55, 208, 41, 107, 179, 32, 52, 165, 51, 174, 54, 231, 183, 85, 182, 252, 183, 110, 176, 40, 49, 76, 52, 3, 51, 83, 180, 178, 53, 171, 56, 181, 53, 219, 183, 195, 56, 189, 180, 19, 179, 222, 178, 230, 42, 216, 180, 117, 182, 196, 181, 250, 54, 224, 177, 216, 52, 113, 184, 218, 53, 93, 184, 88, 54, 25, 180, 191, 166, 99, 52, 135, 49, 138, 53, 116, 53, 168, 52, 161, 177, 159, 173, 101, 180, 135, 177, 209, 55, 156, 180, 74, 52, 44, 49, 204, 52, 119, 51, 222, 178, 39, 177, 10, 54, 251, 53, 89, 53, 166, 54, 200, 184, 241, 55, 201, 54, 114, 173, 73, 55, 104, 39, 26, 181, 224, 181, 106, 54, 80, 54, 85, 53, 128, 177, 164, 54, 166, 183, 231, 183, 48, 180, 244, 176, 237, 44, 133, 54, 233, 178, 6, 176, 206, 182, 173, 182, 225, 169, 136, 56, 219, 30, 218, 49, 143, 178, 28, 53, 217, 183, 122, 180, 72, 181, 156, 180, 23, 183, 87, 179, 1, 180, 241, 32, 25, 52, 60, 44, 213, 53, 129, 54, 164, 45, 247, 173, 182, 46, 203, 54, 47, 51, 195, 182, 52, 180, 117, 182, 0, 176, 228, 45, 11, 52, 17, 52, 149, 175, 61, 50, 128, 56, 18, 53, 151, 180, 35, 51, 110, 170, 12, 178, 68, 175, 100, 177, 103, 180, 106, 182, 8, 179, 176, 46, 36, 175, 126, 52, 59, 185, 131, 50, 14, 184, 13, 53, 152, 175, 252, 159, 157, 56, 64, 48, 245, 54, 255, 56, 133, 57, 103, 174, 150, 178, 45, 177, 127, 178, 157, 53, 247, 183, 130, 55, 123, 52, 67, 57, 255, 54, 20, 184, 229, 176, 161, 53, 240, 54, 102, 52, 239, 56, 156, 184, 154, 57, 235, 56, 52, 180, 223, 54, 18, 51, 68, 185, 17, 184, 137, 50, 85, 57, 75, 56, 14, 182, 177, 56, 70, 187, 189, 183, 232, 181, 205, 174, 143, 54, 210, 54, 29, 25, 90, 182, 125, 185, 49, 181, 168, 48, 249, 57, 162, 152, 56, 55, 47, 168, 240, 55, 106, 184, 77, 182, 19, 182, 83, 184, 12, 182, 192, 182, 213, 180, 130, 177, 108, 56, 137, 48, 52, 56, 101, 55, 100, 50, 74, 173, 217, 55, 184, 56, 115, 56, 160, 183, 72, 179, 158, 185, 73, 180, 156, 56, 35, 55, 115, 54, 50, 180, 18, 55, 21, 58, 14, 58, 137, 185, 253, 53, 225, 179, 208, 168, 177, 39, 47, 43, 235, 178, 213, 182, 40, 184, 178, 55, 66, 178, 137, 55, 151, 186, 84, 56, 130, 184, 119, 56, 35, 184]}, 'name': 'enc_p.encoder.attn_layers.1.emb_rel_k', 'outputIndexes': [365], 'type': 'Const', 'defaultDimentionFormat': 'NHWC'}`
这里是看起来是经过了unsigned int8量化。

我想在移动端做mnn模型参数的线性变换，如果直接用int8/uint8的话结果不对；如果转模型的时候不用--fp16的话，模型又太大。
想咨询一下有没有办法可以在fp16模型dump到json后，json中全部用float表示？

**Comment by wangzhaode** [comment]
这是正常的 只是放在里这个buffer里 这个buffer 的类型是uint8而已

**Comment by wangzhaode** [comment]
如果你想要float的json可以转成fp32的模型

**Comment by zihaog0724** [comment]
> 如果你想要float的json可以转成fp32的模型

@wangzhaode 您好，我想在移动端修改参数，fp32的模型体积太大了；但fp16的模型解出json的buffer是int8，没法直接做变换，结果不对

**Comment by zihaog0724** [comment]
> 这是正常的 只是放在里这个buffer里 这个buffer 的类型是uint8而已

json里这个buffer 的类型，在转换模型不变的情况下，有没有可能变成float的？

**Comment by wangzhaode** [comment]
json里也没法给你展示fp16呀 本来fp16不是一个标准类型，所以才会被存储到uint8的buffer里，在实际计算时候按照float16读取并计算就可以了
