### ISSUE TITLE
Create execution error : 101 Create execution error : 101 Can't run session because not resized  转换模型推理正确，但是相同推理代码量化模型推理报错 

### ISSUE THREAD

**Issue by irobotDavinci** [alibaba/MNN#2698]
# 平台(如果交叉编译请再附上交叉编译目标平台):  PC-LINUX-X86
# Platform(Include target platform as well if cross-compiling):  

# Github版本: MASTER(2023.12)
# Github Version:2.8.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cd build_pc
cmake .. \
-DMNN_OPENCL=ON \
-DMNN_BUILD_DEMO=ON \
-DMNN_BUILD_CONVERTER=ON \
-DMNN_BUILD_TORCH=ON \
-DMNN_BUILD_QUANTOOLS=ON \
-DMNN_BUILD_TOOL=ON \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_EVALUATION=ON \
-DMNN_BUILD_DEMO=ON \
-DMNN_BUILD_TEST=ON
make -j20

# 编译日志:
# Build Log:
-- 
-- 3.19.0.0
-- Use Threadpool, forbid openmp
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Version: 2.8.0
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	NNAPI: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /home/titan/work/project/STUDY/MNN/build_pc
-- 	CUDA PROFILE: OFF
-- WIN_USE_ASM: 
-- x86_64: Open SSE
-- MNN_AVX512:OFF
-- Onnx: 
-- LibTorch Path is : /home/titan/work/project/STUDY/MNN/build_pc/tools/converter/libtorch/share/cmake
-- MNN Depends:MNNMNN_CLMNN_ExpressMNNTrainMNNTrainUtils
-- Configuring done
-- Generating done
-- Build files have been written to: /home/titan/work/project/STUDY/MNN/build_pc
[  1%] Built target MNNAVX
[  1%] Built target MNNUtils
[  2%] Built target MNNMath
[  4%] Built target MNNCore
[  4%] Built target MNNSSE
[  4%] Built target MNNCV
[  4%] Built target MNNX8664
[  6%] Built target checkDir.out
[  6%] Built target checkFile.out
[  6%] Built target MNNAVXFMA
[  9%] Built target libprotobuf-lite
[ 10%] Built target MNNCompress
[ 20%] Built target MNNTransform
[ 28%] Built target MNNCPU
[ 35%] Built target libprotobuf
[ 36%] Built target MNNConverterMNN
[ 40%] Built target MNNConverterTFL
[ 40%] Built target MNN
[ 41%] Built target OnnxClip
[ 44%] Built target MNNConverterCaffe
[ 47%] Built target MNNConverterONNX
[ 51%] Built target MNN_Express
[ 61%] Built target MNNConverterOpt
[ 67%] Built target MNNConverterTF
[ 72%] Built target MNN_CL
[ 75%] Built target MNNConverterTorch
[ 78%] Built target MNNTrain
[ 79%] Built target MNNTrainUtils
[ 79%] Built target timeProfile.out
[ 79%] Built target testModel_expr.out
[ 79%] Built target benchmarkExprModels.out
[ 79%] Built target testModelWithDescribe.out
[ 80%] Built target getPerformance.out
[ 80%] Built target winogradExample.out
[ 80%] Built target testModel.out
[ 81%] Built target quantized.out
[ 81%] Built target ModuleBasic.out
[ 81%] Built target multiPose.out
[ 82%] Built target multithread_imgrecog.out
[ 81%] Built target pictureRecognition_batch.out
[ 81%] Built target pictureRecognition.out
[ 82%] Built target pictureRecognition_module.out
[ 83%] Built target pictureRotate.out
[ 83%] Built target benchmark.out
[ 83%] Built target segment.out
[ 83%] Built target expressDemo.out
[ 83%] Built target transformerDemo.out
[ 83%] Built target checkInvalidValue.out
[ 84%] Built target MNNV2Basic.out
[ 84%] Built target expressMakeModel.out
[ 84%] Built target mobilenetTest.out
[ 84%] Built target nluDemo.out
[ 84%] Built target classficationTopkEval.out
[ 84%] Built target SequenceModuleTest.out
[ 84%] Built target GetMNNInfo
[ 85%] Built target testTrain.out
[ 85%] Built target mergeInplaceForCPU
[ 85%] Built target backendTest.out
[ 86%] Built target extractForInfer
[ 86%] Built target transformer
[ 87%] Built target runTrainDemo.out
[ 99%] Built target run_test.out
[100%] Built target MNNConvertDeps
[100%] Built target MNNRevert2Buffer
[100%] Built target TestConvertResult
[100%] Built target TestPassManager
[100%] Built target MNNDump2Json
[100%] Built target MNNConvert

```
粘贴在这里
Paste log here or pastebin
```

问题： 如题目
[code.zip](https://github.com/alibaba/MNN/files/13694576/code.zip)
推理量化后的模型报错：
Create execution error : 101
Create execution error : 101
Can't run session because not resized

推理转换的模型，不量化，推理结果正确

**Comment by v0jiuqi** [comment]
这个问题应该是input的shape没对上吧。另外文件夹中没有模型只有脚本文件

**Comment by bigmover** [comment]
> 这个问题应该是input的shape没对上吧。另外文件夹中没有模型只有脚本文件

模型interpreter.getSessionInput(session) 是一个动态值（1， 3， -1， -1），推理的时候真实输入是（1， 3， 800， 800）也报Can't run session because not resized，请问这是怎么回事？
![image](https://github.com/alibaba/MNN/assets/26063296/e269a9cd-a148-4096-a383-43d25dddafd7)

**Comment by v0jiuqi** [comment]
推理之前要resize，你可以参考MNNV2Basic.cpp(单输入) ，ModuleBasic.cpp (多输入）来写demo，或直接使用MNNV2Basic.out ModuleBasic.out
