### ISSUE TITLE
 MNN::CV::resize 负数的feature map结果会错误，输出全部整数疑似溢出

### ISSUE THREAD

**Issue by slz929** [alibaba/MNN#2699]

**Comment by wangzhaode** [comment]
你是说的tools/cv下的resize吗

**Comment by slz929** [comment]
> 你是说的tools/cv下的resize吗

是的， 代码 
```python
 mask= cv2.resize(mask, [length, length])
```
执行前后的map如下，
resize before  [256, 256, 4] 
array([[[-23.91765  , -26.492884 , -17.744608 , -11.131535 ],
        [-23.505884 , -25.57762  , -17.615    , -10.671636 ],
        [-23.523773 , -26.844044 , -17.752674 , -11.43016  ],
        ...,
        [-24.985153 , -29.62366  , -12.904721 , -10.200054 ],
        [-24.897804 , -28.633852 , -13.160109 ,  -9.924609 ],
        [-24.722208 , -29.467743 , -12.883072 , -10.360117 ]],

       [[-23.841345 , -25.253454 , -16.929487 , -11.210915 ],
        [-23.898058 , -26.771645 , -18.185686 , -10.70154  ],
        [-23.838161 , -25.389725 , -17.238216 , -11.731779 ],
        ...,
        [-25.193338 , -29.472021 , -13.298164 , -10.41081  ],
        [-24.693743 , -26.340223 , -12.385376 , -10.23895  ],
        [-24.592781 , -29.637224 , -13.081308 , -10.055473 ]],

       [[-22.764482 , -25.812603 , -17.298174 , -10.771151 ],
        [-22.240458 , -24.978502 , -17.291313 , -10.307157 ],
        [-22.882664 , -26.968285 , -17.691015 , -10.635887 ],
        ...,
        [-24.66161  , -29.155767 , -13.317525 ,  -9.3532   ],
        [-25.187965 , -28.60845  , -13.721687 ,  -9.758822 ],
        [-24.693111 , -29.272821 , -13.230663 , -10.026303 ]],

       ...,

       [[-24.453812 , -25.126617 , -17.62641  , -11.218266 ],
        [-25.226019 , -26.626745 , -18.468645 , -11.63923  ],
        [-23.38819  , -23.633533 , -17.38655  ,  -9.480167 ],
        ...,
        [-25.224424 , -27.635431 , -13.317781 , -10.419314 ],
        [-24.467596 , -24.754854 , -12.652757 , -10.013985 ],
        [-23.293863 , -26.380407 , -12.242338 ,  -8.72707  ]],

       [[-26.630764 , -27.309856 , -18.181114 , -10.841579 ],
        [-25.419127 , -24.48495  , -16.861698 , -11.109423 ],
        [-25.879988 , -26.74712  , -18.589108 , -10.318467 ],
        ...,
        [-26.270294 , -27.561617 , -13.241167 , -11.843055 ],
        [-25.701033 , -27.414608 , -13.776032 , -10.783622 ],
        [-24.469288 , -26.179543 , -12.561915 , -11.466339 ]],

       [[-24.682444 , -23.418295 , -17.060644 , -10.894257 ],
        [-25.323214 , -26.389523 , -17.492481 , -10.584619 ],
        [-23.944775 , -24.492453 , -17.79397  , -10.114152 ],
        ...,
        [-25.839226 , -28.714512 , -13.562561 , -11.3733425],
        [-24.076574 , -24.088984 , -12.285718 , -10.755466 ],
        [-24.28478  , -27.504585 , -12.761623 , -10.344379 ]]],
      dtype=float32)

resize after [1024, 1024, 4] 
array([[[ 89.,  87., 191., 193.],
        [ 89.,  87., 191., 193.],
        [ 91., 106., 193., 193.],
        ...,
        [215.,  39., 227., 192.],
        [217.,  24., 241., 192.],
        [217.,  24., 241., 192.]],

       [[ 89.,  87., 191., 193.],
        [ 89.,  87., 191., 193.],
        [ 91., 106., 193., 193.],
        ...,
        [215.,  39., 227., 192.],
        [217.,  24., 241., 192.],
        [217.,  24., 241., 192.]],

       [[ 96., 103., 186., 193.],
        [ 96., 103., 186., 193.],
        [ 99., 120., 189., 193.],
        ...,
        [203.,  56., 200., 192.],
        [204.,  44., 210., 192.],
        [204.,  44., 210., 192.]],

       ...,

       [[ 69., 148., 130., 193.],
        [ 69., 148., 130., 193.],
        [ 72., 148., 132., 193.],
        ...,
        [ 60., 115., 205., 178.],
        [ 43., 117., 227., 176.],
        [ 43., 117., 227., 176.]],

       [[ 79., 159., 138., 193.],
        [ 79., 159., 138., 193.],
        [ 80., 158., 139., 193.],
        ...,
        [ 39., 105., 227., 192.],
        [ 17., 108., 252., 192.],
        [ 17., 108., 252., 192.]],

       [[ 79., 159., 138., 193.],
        [ 79., 159., 138., 193.],
        [ 80., 158., 139., 193.],
        ...,
        [ 39., 105., 227., 192.],
        [ 17., 108., 252., 192.],
        [ 17., 108., 252., 192.]]], dtype=float32)


采用opencv：
```python
mask= mask.read()
mask = opencv2.resize(mask, (length, length), interpolation=cv2.INTER_LINEAR)
```
结果如下
resize before  [256, 256, 4] array([[[-23.91765  , -26.492884 , -17.744608 , -11.131535 ],
        [-23.505884 , -25.57762  , -17.615    , -10.671636 ],
        [-23.523773 , -26.844044 , -17.752674 , -11.43016  ],
        ...,
        [-24.985153 , -29.62366  , -12.904721 , -10.200054 ],
        [-24.897804 , -28.633852 , -13.160109 ,  -9.924609 ],
        [-24.722208 , -29.467743 , -12.883072 , -10.360117 ]],

       [[-23.841345 , -25.253454 , -16.929487 , -11.210915 ],
        [-23.898058 , -26.771645 , -18.185686 , -10.70154  ],
        [-23.838161 , -25.389725 , -17.238216 , -11.731779 ],
        ...,
        [-25.193338 , -29.472021 , -13.298164 , -10.41081  ],
        [-24.693743 , -26.340223 , -12.385376 , -10.23895  ],
        [-24.592781 , -29.637224 , -13.081308 , -10.055473 ]],

       [[-22.764482 , -25.812603 , -17.298174 , -10.771151 ],
        [-22.240458 , -24.978502 , -17.291313 , -10.307157 ],
        [-22.882664 , -26.968285 , -17.691015 , -10.635887 ],
        ...,
        [-24.66161  , -29.155767 , -13.317525 ,  -9.3532   ],
        [-25.187965 , -28.60845  , -13.721687 ,  -9.758822 ],
        [-24.693111 , -29.272821 , -13.230663 , -10.026303 ]],

       ...,

       [[-24.453812 , -25.126617 , -17.62641  , -11.218266 ],
        [-25.226019 , -26.626745 , -18.468645 , -11.63923  ],
        [-23.38819  , -23.633533 , -17.38655  ,  -9.480167 ],
        ...,
        [-25.224424 , -27.635431 , -13.317781 , -10.419314 ],
        [-24.467596 , -24.754854 , -12.652757 , -10.013985 ],
        [-23.293863 , -26.380407 , -12.242338 ,  -8.72707  ]],

       [[-26.630764 , -27.309856 , -18.181114 , -10.841579 ],
        [-25.419127 , -24.48495  , -16.861698 , -11.109423 ],
        [-25.879988 , -26.74712  , -18.589108 , -10.318467 ],
        ...,
        [-26.270294 , -27.561617 , -13.241167 , -11.843055 ],
        [-25.701033 , -27.414608 , -13.776032 , -10.783622 ],
        [-24.469288 , -26.179543 , -12.561915 , -11.466339 ]],

       [[-24.682444 , -23.418295 , -17.060644 , -10.894257 ],
        [-25.323214 , -26.389523 , -17.492481 , -10.584619 ],
        [-23.944775 , -24.492453 , -17.79397  , -10.114152 ],
        ...,
        [-25.839226 , -28.714512 , -13.562561 , -11.3733425],
        [-24.076574 , -24.088984 , -12.285718 , -10.755466 ],
        [-24.28478  , -27.504585 , -12.761623 , -10.344379 ]]],
      dtype=float32)
resize after  (1024, 1024, 4) [[[-23.91765   -26.492884  -17.744608  -11.131535 ]
  [-23.91765   -26.492884  -17.744608  -11.131535 ]
  [-23.86618   -26.378475  -17.728407  -11.074047 ]
  ...
  [-24.744158  -29.363506  -12.917702  -10.305678 ]
  [-24.722208  -29.467743  -12.883072  -10.360117 ]
  [-24.722208  -29.467743  -12.883072  -10.360117 ]]

 [[-23.91765   -26.492884  -17.744608  -11.131535 ]
  [-23.91765   -26.492884  -17.744608  -11.131535 ]
  [-23.86618   -26.378475  -17.728407  -11.074047 ]
  ...
  [-24.744158  -29.363506  -12.917702  -10.305678 ]
  [-24.722208  -29.467743  -12.883072  -10.360117 ]
  [-24.722208  -29.467743  -12.883072  -10.360117 ]]

 [[-23.908112  -26.337955  -17.642717  -11.141457 ]
  [-23.908112  -26.337955  -17.642717  -11.141457 ]
  [-23.863962  -26.26157   -17.64817   -11.083197 ]
  ...
  [-24.726814  -29.346205  -12.9272785 -10.277269 ]
  [-24.70603   -29.488928  -12.907851  -10.322037 ]
  [-24.70603   -29.488928  -12.907851  -10.322037 ]]

 ...

 [[-24.925983  -23.90474   -17.200703  -10.887672 ]
  [-24.925983  -23.90474   -17.200703  -10.887672 ]
  [-24.977135  -24.185577  -17.22732   -10.85799  ]
  ...
  [-24.304317  -26.98467   -12.703578  -10.51892  ]
  [-24.307844  -27.338955  -12.73666   -10.484625 ]
  [-24.307844  -27.338955  -12.73666   -10.484625 ]]

 [[-24.682444  -23.418295  -17.060644  -10.894257 ]
  [-24.682444  -23.418295  -17.060644  -10.894257 ]
  [-24.762539  -23.789698  -17.114624  -10.855552 ]
  ...
  [-24.258755  -27.077635  -12.702135  -10.395765 ]
  [-24.28478   -27.504585  -12.761623  -10.344379 ]
  [-24.28478   -27.504585  -12.761623  -10.344379 ]]

 [[-24.682444  -23.418295  -17.060644  -10.894257 ]
  [-24.682444  -23.418295  -17.060644  -10.894257 ]
  [-24.762539  -23.789698  -17.114624  -10.855552 ]
  ...
  [-24.258755  -27.077635  -12.702135  -10.395765 ]
  [-24.28478   -27.504585  -12.761623  -10.344379 ]
  [-24.28478   -27.504585  -12.761623  -10.344379 ]]]

**Comment by wangzhaode** [comment]
这个函数只支持uint8的输入；浮点的resize需要使用`MNN.expr.resize`
