### ISSUE TITLE
请问有没有Linux和Android调用MNN模型做前向推理的demo代码

### ISSUE THREAD

**Issue by hot-dog** [alibaba/MNN#270]
刚接触MNN这个框架，按照官方的说明文档编译好了MNN框架，也将pytorch模型转成了MNN模型，但是对怎么在代码里面用MNN框架调用转好的模型来做前向推理完全没有头绪，不知道代码的大致框架和写法是什么样子的，比如代码里面要包含哪些库文件，怎么加载模型，怎么调用模型等，想问一下有没有这种demo代码可以参考一下，谢谢了！

**Comment by hot-dog** [comment]
刚在demo文件夹下找到了官方提供的demo，先学习下~

**Comment by nullptr-leo** [comment]
See [mobilenetTest.cpp](https://github.com/alibaba/MNN/blob/master/tools/cpp/mobilenetTest.cpp).

**Comment by hot-dog** [comment]
好的，多谢~

**Comment by yuanjinliang1** [comment]
> 刚接触MNN这个框架，按照官方的说明文档编译好了MNN框架，也将pytorch模型转成了MNN模型，但是对怎么在代码里面用MNN框架调用转好的模型来做前向推理完全没有头绪，不知道代码的大致框架和写法是什么样子的，比如代码里面要包含哪些库文件，怎么加载模型，怎么调用模型等，想问一下有没有这种demo代码可以参考一下，谢谢了！

同学，你这个问题解决了吗？我也有类似的需求，想把MNN的框架加到android开发中，开发进一步的功能。
