### ISSUE TITLE
Module->parameters()取模型权重失败

### ISSUE THREAD

**Issue by zihaog0724** [alibaba/MNN#2700]
您好，想从mnn模型中取到权重, 用module->parameters(), 但是取不成功

```
int test_module() {
    const std::string contentvec_model_path = "./transfered_models/contentvec_test_v3_fp16.mnn";
    MNN::ScheduleConfig sConfig;
    sConfig.type = MNN_FORWARD_CPU;
    std::shared_ptr<MNN::Express::Executor::RuntimeManager> rtmgr = std::shared_ptr<MNN::Express::Executor::RuntimeManager>(
            MNN::Express::Executor::RuntimeManager::createRuntimeManager(sConfig));
    if(rtmgr == nullptr) {
        return 0;
    }
    rtmgr->setCache(".cachefile");

    std::shared_ptr<MNN::Express::Module> net(MNN::Express::Module::load(std::vector<std::string>{}, std::vector<std::string>{}, contentvec_model_path.c_str(), rtmgr));

    std::vector<MNN::Express::VARP> param = net->parameters();
    printf("%lu \n", param.size());
    return 0;
}
```
模型是单输入单输出, 看源码parameters()返回一个vector, 但长度是0, 应该是没有取到, 可以提供模型

**Comment by v0jiuqi** [comment]
按截图搜索关键词使用试试

**Comment by v0jiuqi** [comment]
> 您好，想从mnn模型中取到权重, 用module->parameters(), 但是取不成功
> 
> ```
> int test_module() {
>     const std::string contentvec_model_path = "./transfered_models/contentvec_test_v3_fp16.mnn";
>     MNN::ScheduleConfig sConfig;
>     sConfig.type = MNN_FORWARD_CPU;
>     std::shared_ptr<MNN::Express::Executor::RuntimeManager> rtmgr = std::shared_ptr<MNN::Express::Executor::RuntimeManager>(
>             MNN::Express::Executor::RuntimeManager::createRuntimeManager(sConfig));
>     if(rtmgr == nullptr) {
>         return 0;
>     }
>     rtmgr->setCache(".cachefile");
> 
>     std::shared_ptr<MNN::Express::Module> net(MNN::Express::Module::load(std::vector<std::string>{}, std::vector<std::string>{}, contentvec_model_path.c_str(), rtmgr));
> 
>     std::vector<MNN::Express::VARP> param = net->parameters();
>     printf("%lu \n", param.size());
>     return 0;
> }
> ```
> 
> 模型是单输入单输出, 看源码parameters()返回一个vector, 但长度是0, 应该是没有取到, 可以提供模型

![image](https://github.com/alibaba/MNN/assets/124856990/5274d5b1-c063-4ff9-bea0-c0dcae3a764a)

**Comment by zihaog0724** [comment]
@v0jiuqi 试过了, 还是因为model->parameters()没东西, 然后loadParameters()不成功。我save落盘的文件只有56B, 但这个模型应该有30多M的权重。
同时我参考这里https://mnn-docs.readthedocs.io/en/latest/train/expr.html，用`std::shared_ptr<Module> model(PipelineModule::extract(inputs, outputs, true));` 转训练模式后也一样取不到parameters()

**Comment by v0jiuqi** [comment]
那转模型的阶段先用testMNNFromONNX.py验证一下。如果是ONNX模型转过来的话。看模型大小不太对

**Comment by zihaog0724** [comment]
@v0jiuqi 模型本身没什么问题，可以推理出正常结果的。但就是取不到parameters()，不知道是不是我的用法不对。
