### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by RookieHuang** [alibaba/MNN#2705]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu 18.04.6 LTS
RKNN tookkit 1.7.5
# Github版本:
# Github Version:
commit ID：1ea55f467fb231655cf1e08f77d4a0f1043c4c29
# 编译方式:
# Compiling Method
按文档记录方式编译
# 编译日志:
# Build Log:
略
# 问题：
ONNX模型：
[disk_delivery.zip](https://github.com/alibaba/MNN/files/13749641/disk_delivery.zip)
在转换上述压缩包中类unet结构onnx模型时，从第一层conv->averagepool过程即报错，使用testMNNfromONNX脚本结果如下：
Dir exist
onnx/test.onnx
tensor(float)
['descriptors', 'heatmaps']
inputs:
image
onnx/
outputs:
onnx/descriptors.txt (1, 32, 64, 96)
onnx/
onnx/heatmaps.txt (1, 1, 64, 96)
onnx/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:01] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:01] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ descriptors, heatmaps, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:01] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:01] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ descriptors, heatmaps, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Debug Mode:  True
onnx/test.onnx
tensor(float)
['/unet/path_up.1/conv/conv.0/BatchNormalization_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_up.1/conv/conv.0/BatchNormalization_output_0.txt (1, 48, 64, 96)
onnx//unet/path_up.1/conv/conv.0/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:02] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:02] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_up.1/conv/conv.0/BatchNormalization_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_up.1/conv/conv.0/BatchNormalization False
onnx/test.onnx
tensor(float)
['/unet/path_up.1/Concat_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_up.1/Concat_output_0.txt (1, 48, 64, 96)
onnx//unet/path_up.1/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:02] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:02] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_up.1/Concat_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_up.1/Concat False
Error is between  /unet/path_down.0/path_down.0.1/path_down.0.1.3/Conv  and  /unet/path_up.1/Concat
onnx/test.onnx
tensor(float)
['/unet/path_up.1/upsample/Resize_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_up.1/upsample/Resize_output_0.txt (1, 32, 64, 96)
onnx//unet/path_up.1/upsample/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_up.1/upsample/Resize_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_up.1/upsample/Resize False
onnx/test.onnx
tensor(float)
['/unet/path_down.1/path_down.1.1/path_down.1.1.3/Conv_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_down.1/path_down.1.1/path_down.1.1.3/Conv_output_0.txt (1, 32, 32, 48)
onnx//unet/path_down.1/path_down.1.1/path_down.1.1.3/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_down.1/path_down.1.1/path_down.1.1.3/Conv_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_down.1/path_down.1.1/path_down.1.1.3/Conv False
onnx/test.onnx
tensor(float)
['/unet/path_down.1/path_down.1.1/path_down.1.1.0/BatchNormalization_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_down.1/path_down.1.1/path_down.1.1.0/BatchNormalization_output_0.txt (1, 16, 32, 48)
onnx//unet/path_down.1/path_down.1.1/path_down.1.1.0/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:03] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_down.1/path_down.1.1/path_down.1.1.0/BatchNormalization_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_down.1/path_down.1.1/path_down.1.1.0/BatchNormalization False
onnx/test.onnx
tensor(float)
['/unet/path_down.1/path_down.1.0/AveragePool_output_0']
inputs:
image
onnx/
outputs:
onnx//unet/path_down.1/path_down.1.0/AveragePool_output_0.txt (1, 16, 32, 48)
onnx//unet/path_down.1/path_down.1.0/
Segmentation fault (core dumped)
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:52:04] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[15:52:04] /home/sunby/MNN-master/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 12
Start to Optimize the MNN Net...
inputTensors : [ image, ]
outputTensors: [ /unet/path_down.1/path_down.1.0/AveragePool_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /unet/path_down.1/path_down.1.0/AveragePool False
Error is between  /unet/path_down.0/path_down.0.1/path_down.0.1.3/Conv  and  /unet/path_down.1/path_down.1.0/AveragePool

**Comment by v0jiuqi** [comment]
zip的我解压不了，你传个tar的

**Comment by RookieHuang** [comment]
> zip的我解压不了，你传个tar的

github无法传tar包，模型已邮件发送，请查收！
@v0jiuqi

**Comment by v0jiuqi** [comment]
![image](https://github.com/alibaba/MNN/assets/124856990/ea6a50c1-dad7-455d-9df0-9b5e7d5988ab)
我这边测试没问题啊

**Comment by jxt1234** [comment]
更新代码再测试吧
