### ISSUE TITLE
NHWC结构的数据怎么转成NC4HW4结构的数据

### ISSUE THREAD

**Issue by mandeer** [alibaba/MNN#271]
Pytorch模型转换成ONNX后，再转换成MNN的模型，转换后的模型要求输入格式是NC4HW4，
{ main_type: Input, main: 
{ dims: 
[ 1, 3, 192, 256 ]
, dtype: DT_FLOAT, dformat: NC4HW4 }
, name: "0", outputIndexes: 
[ 0 ]
, type: Input }
使用opencv读入数据，数据格式为NHWC
pretreat->convert(img.data, 256, 192, 0, nhwcTensor);     // NHWC
将NHWC格式的数据转换成NC4HW4时，出错
    auto input_tensor = net->getSessionInput(session, NULL);
    auto nhwcTensor = new MNN::Tensor(input_tensor, MNN::Tensor::TENSORFLOW);
    pretreat->convert(img.data, 256, 192, 0, nhwcTensor);     // NHWC
    input_tensor->copyFromHostTensor(nhwcTensor);
    auto nc4hw4Tensor = new MNN::Tensor(input_tensor, MNN::Tensor::CAFFE_C4);

    auto tmp1 = input_tensor->getDimensionType();
    auto tmp2 = nhwcTensor->getDimensionType();
    auto tmp3 = nc4hw4Tensor->getDimensionType();
    std::cout << tmp1 << " " << tmp2 << " " << tmp3 << std::endl;
打印出的结果为： 1 0 1

MNN中DimensionType的定义为：
enum DimensionType {
        /** for tensorflow net type. uses NHWC as data format. */
        TENSORFLOW,
        /** for caffe net type. uses NCHW as data format. */
        CAFFE,
        /** for caffe net type. uses NC4HW4 as data format. */
        CAFFE_C4
    };

**Comment by jiarenyf** [comment]
https://www.yuque.com/mnn/en/faq#8ee9e1fc

**Comment by mandeer** [comment]
@jiarenyf 已经按照教程上做了，
auto input_tensor = net->getSessionInput(session, NULL);
auto nhwcTensor = new MNN::Tensor(input_tensor, MNN::Tensor::TENSORFLOW);
pretreat->convert(img.data, 256, 192, 0, nhwcTensor); // NHWC
input_tensor->copyFromHostTensor(nhwcTensor);

还有，为什么构建Tensor时声明是Caffe_C4， 
new MNN::Tensor(input_tensor, MNN::Tensor::CAFFE_C4);
打印出来确实CAFFE呢

**Comment by jiarenyf** [comment]
@mandeer 也许是bug吧。。。

**Comment by li-qing** [comment]
> @jiarenyf 已经按照教程上做了，
> auto input_tensor = net->getSessionInput(session, NULL);
> auto nhwcTensor = new MNN::Tensor(input_tensor, MNN::Tensor::TENSORFLOW);
> pretreat->convert(img.data, 256, 192, 0, nhwcTensor); // NHWC
> input_tensor->copyFromHostTensor(nhwcTensor);
> 
> 还有，为什么构建Tensor时声明是Caffe_C4，
> new MNN::Tensor(input_tensor, MNN::Tensor::CAFFE_C4);
> 打印出来确实CAFFE呢

getDimensionType是一个历史存留问题…

**Comment by ffffwyy** [comment]
是不是把数据传进去就自动转化为NC4HW4了。不需要额外转换把。

**Comment by li-qing** [comment]
> 是不是把数据传进去就自动转化为NC4HW4了。不需要额外转换把。

使用Copy接口，会自行转换的。

**Comment by cendelian** [comment]
请问使用pythonAPI怎么转换 NCHW -> NC4HW4

**Comment by cendelian** [comment]
请问为什么MNN转出的模型默认输入格式是NC4HW4呢？我也遇到这个问题。
然后python推理出现data size不匹配的情况
请问知道怎么解决吗？
