### ISSUE TITLE
设置MNN::BackendConfig::Power_High后，cpu占用异常

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#2715]
2.7.1版本
设置backendConfig.power = MNN::BackendConfig::Power_High;后，识别完成后，CPU一直处于占用状态
![d47f2f72faebda5fec3e65a19b6ce2c0](https://github.com/alibaba/MNN/assets/15188456/1fedba89-b79d-4c3d-8221-aa298e912749)

设置backendConfig.power = MNN::BackendConfig::Power_Low;后，识别完成后，CPU就释放了
![0a771e38869b1fde45fc04943af5835c](https://github.com/alibaba/MNN/assets/15188456/bfc95129-0f08-4c39-adcf-15fc41365735)

**Comment by jxt1234** [comment]
目前 power_high 主要用于测试用，会让线程池持续空跑以获取最优性能，实际使用时用 normal 或 low
