### ISSUE TITLE
OpenCL对Select、Cast、Range等算子不支持，性能较慢，请问后续有支持计划吗？

### ISSUE THREAD

**Issue by Zdahap** [alibaba/MNN#2718]
在Chatglm-6b的遇到以上不支持的算子：
Don't support type Range memObject:2, /block/attention/rotary_emb/Range_output_0
Don't support type Cast memObject:2, /block/attention/rotary_emb/Cast_1_output_0
Don't support type Select memObject:2, /block/attention/Where_output_0
Don't support type Cast memObject:2, /block/attention/Cast_1_output_0
Don't support type Cast memObject:2, /block/attention/Cast_2_output_0
附：
当前OpenCL版本实现和ARM版本不一样，需要先把int4参数转为浮点类型，再送到kernel，后续有直接支持int4的计划吗？

**Comment by jxt1234** [comment]
这个 2.8.0 之后就已经支持了，更新代码吧
