### ISSUE TITLE
DetectionOutput和PriorBox算子只支持Caffe模型，Torch和ONNX模型里的不支持吗

### ISSUE THREAD

**Issue by MuYu-zhi** [alibaba/MNN#2719]
最新的master版本里，使用 `./MNNConvert -f CAFFE/ONNX/TORCH --OP`命令，发现只有CAFFE框架支持DetectionOutput和PriorBox算子，其他两种框架里都没有，如果需要支持onnx/torch模型里的这两个算子，该怎么实现

**Comment by jxt1234** [comment]
onnx 里面没有对应的算子，是由其他方式组合实现的，对应地 mnn 也是支持的。

**Comment by jxt1234** [comment]
如遇不能转换的情形重新提 issue
