### ISSUE TITLE
无法安装python api pymnn

### ISSUE THREAD

**Issue by niuxiaozhang** [alibaba/MNN#2720]
Window10

# Github版本:
2.7.2

# 编译方式:
# Compiling Method
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON

cmake源码编译成功，模型转换也能成功。但是用python build_deps.py  python setup.py install 安装pymnn时报错。

# 编译日志:
# Build Log:
(tf) D:\3rdParty\MNN\MNN-2.7.2\pymnn\pip_package>python setup.py install
USE_TRT  False
USE_CUDA: False
Building with python wheel with package name  MNN
['D:\\3rdParty\\MNN\\MNN-2.7.2\\pymnn_build', 'D:\\3rdParty\\MNN\\MNN-2.7.2\\pymnn_build\\tools\\train', 'D:\\3rdParty\\MNN\\MNN-2.7.2\\pymnn_build\\tools\\cv', 'D:\\3rdParty\\MNN\\MNN-2.7.2\\pymnn_build\\source\\backend\\tensorrt', 'D:\\3rdParty\\MNN\\MNN-2.7.2\\pymnn_build\\source\\backend\\cuda']
running install
C:\ProgramData\anaconda3\envs\tf\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\ProgramData\anaconda3\envs\tf\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating MNN.egg-info
writing MNN.egg-info\PKG-INFO
writing dependency_links to MNN.egg-info\dependency_links.txt
writing entry points to MNN.egg-info\entry_points.txt
writing requirements to MNN.egg-info\requires.txt
writing top-level names to MNN.egg-info\top_level.txt
writing manifest file 'MNN.egg-info\SOURCES.txt'
reading manifest file 'MNN.egg-info\SOURCES.txt'
writing manifest file 'MNN.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-cpython-311
creating build\lib.win-amd64-cpython-311\MNN
copying MNN\__init__.py -> build\lib.win-amd64-cpython-311\MNN
creating build\lib.win-amd64-cpython-311\MNN\cv
copying MNN\cv\__init__.py -> build\lib.win-amd64-cpython-311\MNN\cv
creating build\lib.win-amd64-cpython-311\MNN\data
copying MNN\data\__init__.py -> build\lib.win-amd64-cpython-311\MNN\data
creating build\lib.win-amd64-cpython-311\MNN\expr
copying MNN\expr\__init__.py -> build\lib.win-amd64-cpython-311\MNN\expr
creating build\lib.win-amd64-cpython-311\MNN\nn
copying MNN\nn\__init__.py -> build\lib.win-amd64-cpython-311\MNN\nn
creating build\lib.win-amd64-cpython-311\MNN\numpy
copying MNN\numpy\__init__.py -> build\lib.win-amd64-cpython-311\MNN\numpy
creating build\lib.win-amd64-cpython-311\MNN\optim
copying MNN\optim\__init__.py -> build\lib.win-amd64-cpython-311\MNN\optim
creating build\lib.win-amd64-cpython-311\MNN\tools
copying MNN\tools\mnn.py -> build\lib.win-amd64-cpython-311\MNN\tools
copying MNN\tools\mnnconvert.py -> build\lib.win-amd64-cpython-311\MNN\tools
copying MNN\tools\mnnquant.py -> build\lib.win-amd64-cpython-311\MNN\tools
copying MNN\tools\__init__.py -> build\lib.win-amd64-cpython-311\MNN\tools
creating build\lib.win-amd64-cpython-311\MNN\numpy\linalg
copying MNN\numpy\linalg\__init__.py -> build\lib.win-amd64-cpython-311\MNN\numpy\linalg
creating build\lib.win-amd64-cpython-311\MNN\numpy\random
copying MNN\numpy\random\__init__.py -> build\lib.win-amd64-cpython-311\MNN\numpy\random
creating build\lib.win-amd64-cpython-311\MNN\tools\utils
copying MNN\tools\utils\getkey.py -> build\lib.win-amd64-cpython-311\MNN\tools\utils
copying MNN\tools\utils\log.py -> build\lib.win-amd64-cpython-311\MNN\tools\utils
copying MNN\tools\utils\__init__.py -> build\lib.win-amd64-cpython-311\MNN\tools\utils
running build_ext
building '_mnncengine' extension
creating build\temp.win-amd64-cpython-311
creating build\temp.win-amd64-cpython-311\Release
creating build\temp.win-amd64-cpython-311\Release\3rdParty
creating build\temp.win-amd64-cpython-311\Release\3rdParty\MNN
creating build\temp.win-amd64-cpython-311\Release\3rdParty\MNN\MNN-2.7.2
creating build\temp.win-amd64-cpython-311\Release\3rdParty\MNN\MNN-2.7.2\pymnn
creating build\temp.win-amd64-cpython-311\Release\3rdParty\MNN\MNN-2.7.2\pymnn\src
"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\3rdParty\MNN\MNN-2.7.2\include -ID:\3rdParty\MNN\MNN-2.7.2\express -ID:\3rdParty\MNN\MNN-2.7.2\express\module -ID:\3rdParty\MNN\MNN-2.7.2\source -ID:\3rdParty\MNN\MNN-2.7.2\tools -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\nn -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\grad -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\module -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\parameters -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\optimizer -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\data -ID:\3rdParty\MNN\MNN-2.7.2\tools\train\source\transformer -ID:\3rdParty\MNN\MNN-2.7.2\source\core -ID:\3rdParty\MNN\MNN-2.7.2\schema\current -ID:\3rdParty\MNN\MNN-2.7.2\3rd_party\flatbuffers\include -ID:\3rdParty\MNN\MNN-2.7.2\tools\cv\include -IC:\ProgramData\anaconda3\envs\tf\Lib\site-packages\numpy\core\include -IC:\ProgramData\anaconda3\envs\tf\include -IC:\ProgramData\anaconda3\envs\tf\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.38.33130\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /TpD:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc /Fobuild\temp.win-amd64-cpython-311\Release\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.obj -DBUILD_OPTYPE -DPYMNN_TRAIN_API /MT /Zi /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /experimental:preprocessor -DPYMNN_EXPR_API -DPYMNN_NUMPY_USABLE -DPYMNN_OPENCV_API /DEBUG
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
cl: 命令行 warning D9025 :正在重写“/EHs”(用“/EHa”)
cl: 命令行 warning D9035 :“experimental:preprocessor”选项已否决，并将在将来的版本中移除
cl: 命令行 warning D9036 :使用“Zc:preprocessor”而不使用“experimental:preprocessor”
MNN.cc
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
C:\ProgramData\anaconda3\envs\tf\Lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
D:\3rdParty\MNN\MNN-2.7.2\tools\cpp/IDSTEncoder.hpp(53): warning C4018: “<”: 有符号/无符号不匹配
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\nn.h(357): warning C4477: “printf”: 格式字符串“%d”需要类型“int”的参数，但可变参数 1 拥有了类型“unsigned __int64”
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\nn.h(357): note: 请考虑在格式字符串中使用“%zd”
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(585): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1334): error C2059: 语法错误:“delete”
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1335): error C2065: “self”: 未声明的标识符
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1335): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1335): error C2365: “Py_TYPE”: 重定义；以前的定义是“函数”
C:\ProgramData\anaconda3\envs\tf\include\object.h(132): note: 参见“Py_TYPE”的声明
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1335): error C2059: 语法错误:“->”
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1336): error C2059: 语法错误:“}”
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1336): error C2143: 语法错误: 缺少“;”(在“}”的前面)
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1339): error C2143: 语法错误: 缺少“;”(在“{”的前面)
D:\3rdParty\MNN\MNN-2.7.2\pymnn\src\MNN.cc(1339): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by jxt1234** [comment]
更新代码到 2.8.1 再重编下看看
