### ISSUE TITLE
ubuntu22.04系统，硬件为i7-12700，对yolo8n模型进行推理。为什么利用AVX512指令集没有推理加速效果，

### ISSUE THREAD

**Issue by lhz123** [alibaba/MNN#2725]
利用指令：objdump -d libMNN.so | grep AVX512，也可以查询到libmnn.so中包含使用 AVX-512指令。
![20240108-154642](https://github.com/alibaba/MNN/assets/27394058/f92a11ed-4143-464f-8951-08ab50d4fc9a)

**Comment by wangzhaode** [comment]
12700不支持AVX512

**Comment by LimeVista** [comment]
12700 处理器只有部分主板在修改设置时为P核开启 AVX-512，E核不支持。一般情况下可以认为不支持 AVX-512 指令集。

**Comment by wangzhaode** [comment]
> 12700 处理器只有部分主板在修改设置时为P核开启 AVX-512，E核不支持。一般情况下可以认为不支持 AVX-512 指令集。

是的，你说的对

**Comment by wangzhaode** [comment]
@lhz123 如果使用12/13/14代intel CPU的话可以使用AVX2，这个issue我关掉了

**Comment by lhz123** [comment]
> @lhz123 如果使用12/13/14代intel CPU的话可以使用AVX2，这个issue我关掉了

好的，谢谢
