### ISSUE TITLE
关于模型量化后的速度

### ISSUE THREAD

**Issue by Fight-hawk** [alibaba/MNN#273]
模型量化后，在一加7上测试 使用cpu速度与原始模型相当 使用gpu后速度非常慢

**Comment by czy2014hust** [comment]
量化的模型暂不能用GPU，你模型原始应该不是很大，计算量不是很大吧

**Comment by Fight-hawk** [comment]
原始 2gflop cpu推理时间150-170ms

**Comment by czy2014hust** [comment]
在其他手机上测试一下，看下对比，另外编译的什么架构的？
