### ISSUE TITLE
UHDM模型cuda 显存比ORT大很多，耗时是ort的3倍

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#2730]
MNN 2.8.1，在Tesla T4 卡上，运行UHDM模型https://github.com/CVMI-Lab/UHDM，显存和耗时都异常。
![uhdm](https://github.com/alibaba/MNN/assets/34120042/9390371b-311f-49a3-9cf6-064c0a64e075)

**Comment by bitxsw93** [comment]
耗时主要是global avg pool导致的性能很慢。等内部修复同步吧。显存问题也会一并看下
