### ISSUE TITLE
can not convert this model to MNN

### ISSUE THREAD

**Issue by meixitu17** [alibaba/MNN#2731]
system : ubuntu
version: tag 2.8.1
command:

got floating point exception(core dumped)

Thanks

**Comment by meixitu17** [comment]
Is there anyone can help?

Thanks

**Comment by jxt1234** [comment]
MNN LSTM not support dynamic sequence_lens.

**Comment by meixitu17** [comment]
@jxt1234 
Thank you.
do you have plan to support LSTM with dynamic sequence_lens?
