### ISSUE TITLE
RK3588 (A76+A55) + Ubuntu 22.04 + MNN_ARM82=ON: "MNNAbsMaxFP16.S:106: Error: operand 1 must be a SIMD vector register"

### ISSUE THREAD

**Issue by kmn1024** [alibaba/MNN#2736]
# 平台: [Orange Pi 5](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5.html) (RK3588) + Ubuntu 22.04

# Github版本: f558df9a746f94980ccf2738be04223e3f4e7936

# 编译方式:
`cmake .. -DMNN_LOW_MEMORY=ON -DMNN_ARM82=ON`
> ...
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Version: 2.8.1
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: ON
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	NNAPI: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /home/ubuntu/mnn-llm/MNN/build
-- 	CUDA PROFILE: OFF
-- WIN_USE_ASM: 
-- Enabling AArch64 Assemblies
-- Enable INT8 SDOT
-- Configuring done (0.3s)
-- Generating done (0.3s)
-- Build files have been written to: /home/ubuntu/mnn-llm/MNN/build

`make -j4`
> ...
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S: Assembler messages:
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:106: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:106: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:106: Error: operand 1 must be a SIMD vector register -- `fadd #192.8h,#192.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:106: Error: operand 1 must be a SIMD vector register -- `fadd .8h,.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:160: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:160: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:160: Error: operand 1 must be a SIMD vector register -- `fadd #160.8h,#160.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:160: Error: operand 1 must be a SIMD vector register -- `fadd .8h,.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:202: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:202: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:202: Error: operand 1 must be a SIMD vector register -- `fadd #128.8h,#128.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:202: Error: operand 1 must be a SIMD vector register -- `fadd .8h,.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:237: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:237: Error: operand 1 must be a SIMD vector register -- `fadd x0.8h,x0.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:237: Error: operand 1 must be a SIMD vector register -- `fadd #16.8h,#16.8h,.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S:237: Error: operand 1 must be a SIMD vector register -- `fadd .8h,.8h,.8h'
make[2]: *** [CMakeFiles/MNN_Arm82.dir/build.make:357: CMakeFiles/MNN_Arm82.dir/source/backend/arm82/asm/arm64/low_memory/MNNAbsMaxFP16.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:388: CMakeFiles/MNN_Arm82.dir/all] Error 2
...

如果我不用DMNN_ARM82 就没问题:
`cmake .. -DMNN_LOW_MEMORY=ON -DMNN_ARM82=OFF`
> ...
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Version: 2.8.1
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	oneDNN: OFF
-- 	TensorRT: OFF
-- 	CoreML: OFF
-- 	NNAPI: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	BF16: OFF
-- 	ThreadPool: ON
-- 	Hidden: TRUE
-- 	Build Path: /home/ubuntu/mnn-llm/MNN/build
-- 	CUDA PROFILE: OFF
-- WIN_USE_ASM: 
-- Enabling AArch64 Assemblies
-- Configuring done (0.1s)
-- Generating done (0.1s)
-- Build files have been written to: /home/ubuntu/mnn-llm/MNN/build

`make -j4`
> ...
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddC4WithStride.S.o
[  7%] Built target checkFile.out
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAvgPoolInt8.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAxByClampBroadcastC4.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBilinearLineC8.S.o
[  7%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBilinearSampleC8.S.o
[  8%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinaryAddInt8.S.o
[  8%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinaryMaxInt8.S.o
[ 21%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o
[ 34%] Built target MNNTransform
[ 34%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinaryMinInt8.S.o
[ 34%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinaryMulInt8.S.o
[ 35%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUBackend.cpp.o
[ 36%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinarySqdInt8.S.o
[ 36%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUBinary.cpp.o
[ 36%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBinarySubInt8.S.o
[ 36%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBlitC1ToFloatRGBA.S.o
[ 36%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNBlitC3ToFloatRGBA.S.o
[ 36%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23MulTransUnit.S.o
[ 37%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23SourceTransUnit.S.o
[ 37%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseInt8.S.o
[ 37%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseUint8.S.o
[ 37%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthwise.S.o
[ 38%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWise.S.o
[ 38%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWiseUint8.S.o
[ 38%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNCopyC4WithStride.S.o
[ 38%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNCubicLineC16.S.o
[ 38%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNCubicSampleC16.S.o
[ 39%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNDeconvRunForUnitDepthWise.S.o
[ 39%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNExpC8.S.o
[ 39%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNFloat2Int8.S.o
[ 39%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGelu.S.o
[ 40%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit.S.o
[ 40%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit_FAST.S.o
[ 40%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV82_Unit.S.o
[ 40%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_ARMV86_Unit.S.o
[ 40%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmint8to32_8x4_Unit.S.o
[ 41%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNInt8ScaleToFloat.S.o
[ 41%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScaleUnit.S.o
[ 41%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLineDepthWiseInt8AddBiasScale_ARMV82_Unit3X3.S.o
[ 41%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLoadU8AndSum.S.o
[ 42%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixAdd.S.o
[ 42%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixMax.S.o
[ 42%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixProd.S.o
[ 42%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixSub.S.o
[ 42%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMaxFloat.S.o
[ 43%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMaxPoolInt8.S.o
[ 43%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMinFloat.S.o
[ 43%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToBGRAUnit.S.o
[ 43%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToBGRUnit.S.o
[ 44%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToRGBAUnit.S.o
[ 44%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNNV21ToRGBUnit.S.o
[ 44%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4.S.o
[ 44%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4ForMatMul_A.S.o
[ 44%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC8.S.o
[ 45%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMul.S.o
[ 45%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMulRemain.S.o
[ 45%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseMatMulEpx1.S.o
[ 45%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseMatMulEpx4.S.o
[ 46%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseQuantMatMulEpx1.S.o
[ 46%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUBinaryInt8.cpp.o
[ 46%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedSparseQuantMatMulEpx4.S.o
[ 46%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPowC8.S.o
[ 46%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNQuanToDestUint8.S.o
[ 46%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluInt8.S.o
[ 47%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluWithSlopeChannel.S.o
[ 47%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluWithSlopeChannelInt8.S.o
[ 47%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC1BilinearOpt.S.o
[ 47%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC1NearestOpt.S.o
[ 48%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC4BilinearOpt.S.o
[ 48%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSamplerC4NearestOpt.S.o
[ 48%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUCast.cpp.o
[ 48%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAddInt8.S.o
[ 48%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAndAddBias.S.o
[ 48%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAndAddBiasInt8.S.o
[ 49%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNSoftmax.S.o
[ 49%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNStrassenMergeCFunction.S.o
[ 49%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNTranspose16Bit8x8.S.o
[ 49%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNTranspose32Bit4x4.S.o
[ 49%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Common.S.o
[ 50%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Fast.S.o
[ 50%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUnPackC4.S.o
[ 50%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o
[ 50%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Int32.S.o
[ 51%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductLeft.S.o
[ 51%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductRight.S.o
[ 51%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNAbsMaxFP32.S.o
[ 51%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNDynamicQuantFP32.S.o
[ 51%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt4FP32.S.o
[ 52%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt4FP32_sdot.S.o
[ 52%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt4FP32_smmla.S.o
[ 52%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt8FP32.S.o
[ 52%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt8FP32_sdot.S.o
[ 53%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNGemmHybridInt8FP32_smmla.S.o
[ 53%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNPackedMatMulRemain_int4.S.o
[ 53%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNPackedMatMulRemain_int8.S.o
[ 53%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNPackedMatMul_int4.S.o
[ 53%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNPackedMatMul_int8.S.o
[ 54%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNQuantScaleFP32.S.o
[ 54%] Building ASM object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/low_memory/MNNQuantSumFP32.S.o
[ 54%] Building CXX object CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/CommonOptFunctionNeon.cpp.o
[ 54%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUConvolution.cpp.o
[ 55%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUConvolutionDepthwise.cpp.o
[ 55%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUCropAndResize.cpp.o
[ 55%] Built target MNNARM64
...

A76+A55 是属于 ARMv8.2-A 的，为什么不能用 MNN_ARM82=ON？

**Comment by v0jiuqi** [comment]
把MNNAbsMaxFP16.S 文件中 15行到20行的内容删掉，再编译。即
![image](https://github.com/alibaba/MNN/assets/124856990/4f6ad160-a356-4d78-b47e-28f2a56c3406)

**Comment by kmn1024** [comment]
谢大佬！但之后有另一个问题：
```
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S: Assembler messages:
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:66: Error: operand mismatch -- `mov v2.8h,v7.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:66: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:66: Info:    mov v2.8b, v7.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:66: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:66: Info:    mov v2.16b, v7.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:68: Error: operand mismatch -- `mov v1.8h,v6.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:68: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:68: Info:    mov v1.8b, v6.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:68: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:68: Info:    mov v1.16b, v6.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:104: Error: operand mismatch -- `mov v2.8h,v7.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:104: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:104: Info:    mov v2.8b, v7.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:104: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:104: Info:    mov v2.16b, v7.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:106: Error: operand mismatch -- `mov v1.8h,v6.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:106: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:106: Info:    mov v1.8b, v6.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:106: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:106: Info:    mov v1.16b, v6.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:158: Error: operand mismatch -- `mov v2.8h,v7.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:158: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:158: Info:    mov v2.8b, v7.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:158: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:158: Info:    mov v2.16b, v7.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:160: Error: operand mismatch -- `mov v1.8h,v6.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:160: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:160: Info:    mov v1.8b, v6.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:160: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:160: Info:    mov v1.16b, v6.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:196: Error: operand mismatch -- `mov v2.8h,v7.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:196: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:196: Info:    mov v2.8b, v7.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:196: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:196: Info:    mov v2.16b, v7.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:198: Error: operand mismatch -- `mov v1.8h,v6.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:198: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:198: Info:    mov v1.8b, v6.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:198: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:198: Info:    mov v1.16b, v6.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:366: Error: operand mismatch -- `mov v3.8h,v21.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:366: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:366: Info:    mov v3.8b, v21.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:366: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:366: Info:    mov v3.16b, v21.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:367: Error: operand mismatch -- `mov v4.8h,v21.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:367: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:367: Info:    mov v4.8b, v21.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:367: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:367: Info:    mov v4.16b, v21.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:417: Error: operand mismatch -- `mov v3.8h,v21.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:417: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:417: Info:    mov v3.8b, v21.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:417: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:417: Info:    mov v3.16b, v21.16b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:418: Error: operand mismatch -- `mov v4.8h,v21.8h'
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:418: Info:    did you mean this?
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:418: Info:    mov v4.8b, v21.8b
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:418: Info:    other valid variant(s):
/home/ubuntu/mnn-llm/MNN/source/backend/arm82/asm/arm64/low_memory/MNNPackedMatMulFP16_int4.S:418: Info:    mov v4.16b, v21.16b
```

**Comment by v0jiuqi** [comment]
诸如 mov v2.8h,v7.8h 改为 mov v2.16b,v7.16b，不要改成 mov v2.8b,v7.8b

**Comment by kmn1024** [comment]
跑得动了！太牛太快了🐄 好期待 opencl 的来临 ！
