### ISSUE TITLE
quantized.out int8量化后的模型在CPU后端运行resnet50出错（已更新到最新commit版本）

### ISSUE THREAD

**Issue by YingkunZhou** [alibaba/MNN#2737]
https://github.com/alibaba/MNN/issues/2614

初步测试mobilenet看起来是正常了许多，感谢开发者的努力！

但和上述issue同样的复现方法，我又用resnet50试了试，得到的结果如下：

模型下载地址：https://github.com/onnx/models/raw/main/Computer_Vision/resnet50_Opset16_timm/resnet50_Opset16.onnx 

```bash
./pictureRecognition.out resnet50.mnn daisy.jpg
Load Cache file error.
The device support i8sdot:1, support fp16:1, support i8mm: 0
Session Info: memory use 29.272980 MB, flops is 4096.363281 M, backendType is 0, batch size = 1
input: w:224 , h:224, bpp: 3
origin size: 2100, 1500
For Image: daisy.jpg
672, -28.451855
657, -28.451855
658, -28.451855
659, -28.451855
660, -28.451855
661, -28.451855
662, -28.451855
663, -28.451855
664, -28.451855
665, -28.451855
```

有点好奇MNN里的量化框架有没有CI自动测试，为什么连最基本的reset50量化完都跑错

而未量化前的模型，被我命名为tmp.mnn （参考https://github.com/alibaba/MNN/issues/2614 的操作流程），得到的分类结果就正常很多了

```bash
./pictureRecognition.out tmp.mnn  daisy.jpg                  
Load Cache file error.
The device support i8sdot:1, support fp16:1, support i8mm: 0
Session Info: memory use 169.978363 MB, flops is 4096.171875 M, backendType is 0, batch size = 1
input: w:224 , h:224, bpp: 3
origin size: 2100, 1500
For Image: daisy.jpg
985, 9.131153
113, -6.110043
506, -6.371115
308, -6.521829
987, -6.540517
714, -6.673302
307, -6.787087
698, -6.899653
783, -6.938828
652, -6.959727
```

**Comment by v0jiuqi** [comment]
我测试了结果没有不对啊，你用pictureRecognition_module.out 测试看看

**Comment by YingkunZhou** [comment]
@v0jiuqi 你确实是测试了**量化后**的模型了吗，能否贴一下结果让我看看，感谢！

模型就是上面提到的两个onnx官方仓库的，然后图片为
![daisy](https://github.com/alibaba/MNN/assets/43129850/cda2326a-cb18-428b-9be3-10fa3b2b8351)

然后我是在arm64的开发板jetson orin上进行编译运行的

**Comment by YingkunZhou** [comment]
具体的量化流程可以参考https://github.com/alibaba/MNN/issues/2614

**Comment by YingkunZhou** [comment]
另外我想问一下，官方是打算放弃Session接口，改用Module接口了吗

**Comment by YingkunZhou** [comment]
> 我测试了结果没有不对啊，你用pictureRecognition_module.out 测试看看

@v0jiuqi 可否提供一下你用pictureRecognition_module.out 测试的config.json文件，感谢

**Comment by v0jiuqi** [comment]
这个是我们的量化工具和后端不一致导致的，你等我们更新吧

**Comment by hebangwen** [comment]
> 这个是我们的量化工具和后端不一致导致的，你等我们更新吧

请问这个问题修复了吗
