### ISSUE TITLE
静态shape转换后的模型模型，是否可以计算动态shape的输入

### ISSUE THREAD

**Issue by MuYu-zhi** [alibaba/MNN#2738]
如标题，如果模型转换时是设定的静态shape输入，转换后推理调用的时候，输入是非设定的静态shape，是否可以通过reszie input tensor和resize session实现动态shape的输入推理计算？

此外，每个tensor的shape计算是在哪个阶段被调用执行的？

**Comment by v0jiuqi** [comment]
不行，模型转换的时候就用动态shape来转
