### ISSUE TITLE
MNN的GPU性能对比CPU

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#2740]
在使用MNN推理的过程中，发现在高通的888，845，855型号上无论框检测，点检测，GPU比CPU的推理速度还慢或者差不多，唯一快的就是分隔网络。是我使用方式不正确还是什么原因导致的，你们有遇到这种情况吗？

**Comment by Qxinyu** [comment]
是否有开启auto tune功能，config.numThread设为4

**Comment by zhangkom** [comment]
> 是否有开启auto tune功能，config.numThread设为4

auto tune是怎么设置的，我直接用的benchark里面安卓的脚本测试的，线程数应该是示例里面写死的。
