### ISSUE TITLE
mobilenetv2caffe与tflite测速偏差，量化模型转换问题

### ISSUE THREAD

**Issue by waiting111** [alibaba/MNN#275]
1、测试MNN/resource/model/MobileNet/v2下的tflite.mnn和caffe.mnn有较大的速度偏差？
2、MNN量化转换工具：caffe->mnn->quantized_mnn没问题，tflite->mnn->quantized_mnn有问题，其中tflite模型来自https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md，下载的v1_1.0模型，tflite_q->mnn_q是没有问题；
报错：Can't find tensors for MobilenetV1/MobilenetV1/Conv2d_0/Relu6
Segmentation fault: 11

**Comment by jxt1234** [comment]
1､caffe 那个v2版本是第三方提供的，本身与 tf 那个模型不同，多了一层卷积
2、确认一下你模型是否有效，以及图片路径是否有图片

**Comment by waiting111** [comment]
1、多一层耗时会差这么多吗：caffe: 104ms, tf: 75ms，v1就挺接近的
2、解决了。

**Comment by jxt1234** [comment]
你可以用timeProfile.out 测下两个模型的flops ，差得比较多，一般应该是以 tf 那个为准 360 m flops 左右

**Comment by waiting111** [comment]
单线程下，非可分离卷积的结构，定点比浮点慢，正常吗

**Comment by jxt1234** [comment]
有这个可能，在 ARM 上定点计算相比浮点没有太大优势
