### ISSUE TITLE
MNN对yolov5n.pt导出的onnx模型剪枝后在在单片机中调用报错Segment fault如何解决

### ISSUE THREAD

**Issue by zjx-beep** [alibaba/MNN#2751]
自己训练的yolov5n。pt转onnx,在转mnn模型后，进行剪枝，之后再在单片机中调用就会失败，，报错Segmeng fault

**Comment by jxt1234** [comment]
1. 先 PC 上跑一下 mnn 看是否正常
2. 确认下设备上 mnn 和 PC 上 mnn 的代码是否一致
