### ISSUE TITLE
mnn模型量化后使用timeProfile.out测速结果分析

### ISSUE THREAD

**Issue by snart-allen** [alibaba/MNN#2753]
MNN版本2.8.0
编译的时候开启了avx512的支持选项
原本模型是CNN和transformer的混合架构，前半部分CNN，后半部分transformer，CNN部分采用mobileone架构，单个模块在onnx模型用netron查看如下图
![image](https://github.com/alibaba/MNN/assets/102366695/72b7949c-6d1a-4535-9289-426880f5c90b)
使用mnn的量化工具quantize.out进行量化，其中仅对CNN部分进行量化，transformer部分不量化，量化配置文件如下：
{
    "format": "RGB",
    "mean": [
        127.5,
        127.5,
        127.5
    ],
    "normal": [
        0.00784314,
        0.00784314,
        0.00784314
    ],
    "width": 112,
    "height": 112,
    "path": "/home/ubuntu/origin_image/",
    "used_image_num": 190,
    "feature_quantize_method": "KL",
    "weight_quantize_method": "MAX_ABS",
    "skip_quant_op_names": [
       transformer部分的所有op
       ]
       }
量化后使用timeProfile.out进行测速，得到的结果如下：
**原模型测速结果：**
![62e4c3fc6baf4cd383a1d360b6e07e0b](https://github.com/alibaba/MNN/assets/102366695/21894429-88d6-4efa-9be1-f30e63fbd9a6)
**量化后模型测速结果：**
![ed3b33dd3c3a4fa5a88a9833d091d128](https://github.com/alibaba/MNN/assets/102366695/07225236-70da-4ae3-ac28-f9b318c0dc57)
**通过对比可以发现，量化后卷积运算的时间有明显的减少，可以说量化是有作用的，但是binaryop的耗时却又明显增加，进一步进行对比发现是add这步操作的耗时明显增加，怀疑是在这一步有int8转成fp32然后执行add然后再进行fp32转int8的操作导致耗时增加，但是讲道理add算子的量化应该是支持的**
**量化模型部分op耗时：**
![image](https://github.com/alibaba/MNN/assets/102366695/e7a122ce-5dc2-43fc-8777-8ab872017ed0)
**原模型部分op耗时：**
![image](https://github.com/alibaba/MNN/assets/102366695/0ca82c74-08cf-470f-b50c-740f8228e1a8)
**对应MNN模型的算子：**
![image](https://github.com/alibaba/MNN/assets/102366695/95404ebc-8265-4d3f-9150-ba34c44ea490)
请各路大神帮忙解答

补充：在netron中查看add算子的信息可以看到张量的格式是float32:
![image](https://github.com/alibaba/MNN/assets/102366695/9d6396bc-fd8f-41a2-89f9-a424b5c1df90)

尝试过把量化模型dump出来然后把里面的float32改为int8，但是没有效果：
![image](https://github.com/alibaba/MNN/assets/102366695/112c8707-7ec9-43b0-8e3b-de611405a0a2)

**Comment by v0jiuqi** [comment]
钉钉答疑群已回复
