### ISSUE TITLE
怎么由opencv Mat转换为前向传播的input?

### ISSUE THREAD

**Issue by BokyLiu** [alibaba/MNN#276]

**Comment by MirrorYuChen** [comment]
感觉对opencv接口非常不友好啊，有没有人能提供一个标准的接口调用opencv的例子？

**Comment by hzpzlz** [comment]
https://github.com/hzpzlz/MNN-Opencv
MNN+opencv验证mnn模型完整教程
记得留个小星星！

> 感觉对opencv接口非常不友好啊，有没有人能提供一个标准的接口调用opencv的例子？

https://github.com/hzpzlz/MNN-Opencv
MNN+opencv验证mnn模型完整教程
记得留个小星星！

**Comment by hzpzlz** [comment]
> 感觉对opencv接口非常不友好啊，有没有人能提供一个标准的接口调用opencv的例子？

https://github.com/hzpzlz/MNN-Opencv
MNN+opencv验证mnn模型完整教程
记得留个小星星！
