### ISSUE TITLE
cannot convert qwen to mnn

### ISSUE THREAD

**Issue by night-is-yong** [alibaba/MNN#2766]
[lm.zip](https://github.com/alibaba/MNN/files/14370349/lm.zip)

```
粘贴在这里
Paste log here or pastebin
```
['', '-f', 'ONNX', '--modelFile', '././onnx/lm.onnx', '--MNNModel', './mnn/lm.mnn', '--weightQuantBits', '4', '--weightQuantAsymmetric']
Don't has bizCode, use MNNTest for default
Start to Convert Other Model Format To MNN Model..., target version: 2.8
[15:18:18] :46: ONNX Model ir version: 8
[15:18:18] :47: ONNX Model opset version: 15
Start to Optimize the MNN Net...
段错误 (核心已转储)

**Comment by jxt1234** [comment]
先用 testMNNFromOnnx.py 测试。
这个模型是和权重分离的，但没有对应的权重文件
