### ISSUE TITLE
如何使用测试用具

### ISSUE THREAD

**Issue by AloneGu** [alibaba/MNN#277]
input_0.txt 这个文件内容是什么，有没有例子？ 例如 input_shape=1*3*224*224

感谢

**Comment by czy2014hust** [comment]
Reference to [here](https://github.com/alibaba/MNN/tree/master/tools/converter/tools)

**Comment by AloneGu** [comment]
f = open(file_name, "w")
        for c in range(3):
            for h in range(self.height):
                for w in range(self.width):
                    f.write(str(self.input_data[0][h][w][c]) + '\n')

原来就是把每个数写入文件，用 \n 分割

**Comment by czy2014hust** [comment]
Yes
