### ISSUE TITLE
Eror When Make

### ISSUE THREAD

**Issue by codes-team** [alibaba/MNN#2776]
[  4%] Built target MNNCore
[  5%] Built target MNNCV
[  6%] Built target MNNMath
[ 38%] Built target MNNTransform
[ 38%] Built target MNNUtils
[ 64%] Built target MNNCPU
[ 85%] Built target MNNARM64
[ 86%] Built target MNN
[ 86%] Linking CXX shared library OFF/libMNN_Express.so
ld.lld: error: duplicate symbol: MNN::Express::WhileModule::create(MNN::Op const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>> const&)
>>> defined at WhileModule.cpp:27 (module/WhileModule.cpp:27)
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(MNN::Express::WhileModule::create(MNN::Op const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>> const&))
>>> defined at WhileModule.cpp:27 (module/WhileModule.cpp:27)
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(.text._ZN3MNN7Express11WhileModule6createEPKNS_2OpERKNSt6__ndk13mapINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS0_8SubGraphENS5_4lessISC_EENSA_INS5_4pairIKSC_SD_EEEEEE+0x0)

ld.lld: error: duplicate symbol: vtable for MNN::Express::WhileModule
>>> defined at WhileModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(vtable for MNN::Express::WhileModule)
>>> defined at WhileModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(.data.rel.ro._ZTVN3MNN7Express11WhileModuleE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::ExprModule::ExprModule(std::__ndk1::shared_ptr<MNN::Express::Expr>)
>>> defined at PipelineModule.cpp:31 (module/PipelineModule.cpp:31)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::ExprModule::ExprModule(std::__ndk1::shared_ptr<MNN::Express::Expr>))
>>> defined at PipelineModule.cpp:31 (module/PipelineModule.cpp:31)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express10ExprModuleC2ENSt6__ndk110shared_ptrINS0_4ExprEEE+0x0)

ld.lld: error: duplicate symbol: vtable for MNN::Express::ExprModule
>>> defined at PipelineModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(vtable for MNN::Express::ExprModule)
>>> defined at PipelineModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.data.rel.ro._ZTVN3MNN7Express10ExprModuleE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::ExprModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&)
>>> defined at PipelineModule.cpp:67 (module/PipelineModule.cpp:67)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::ExprModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&))
>>> defined at PipelineModule.cpp:67 (module/PipelineModule.cpp:67)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express10ExprModule9onForwardERKNSt6__ndk16vectorINS0_4VARPENS2_9allocatorIS4_EEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::ExprModule::clone(MNN::Express::Module::CloneContext*) const
>>> defined at PipelineModule.cpp:93 (module/PipelineModule.cpp:93)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::ExprModule::clone(MNN::Express::Module::CloneContext*) const)
>>> defined at PipelineModule.cpp:93 (module/PipelineModule.cpp:93)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZNK3MNN7Express10ExprModule5cloneEPNS0_6Module12CloneContextE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::PipelineModule(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>>, std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>>, std::__ndk1::function<std::__ndk1::pair<std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::shared_ptr<MNN::Express::Module>> (std::__ndk1::shared_ptr<MNN::Express::Expr>)> const&)
>>> defined at PipelineModule.cpp:102 (module/PipelineModule.cpp:102)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::PipelineModule(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>>, std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>>, std::__ndk1::function<std::__ndk1::pair<std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::shared_ptr<MNN::Express::Module>> (std::__ndk1::shared_ptr<MNN::Express::Expr>)> const&))
>>> defined at PipelineModule.cpp:102 (module/PipelineModule.cpp:102)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModuleC2ENSt6__ndk16vectorINS0_4VARPENS2_9allocatorIS4_EEEES7_RKNS2_8functionIFNS2_4pairINS3_IiNS5_IiEEEENS2_10shared_ptrINS0_6ModuleEEEEENSC_INS0_4ExprEEEEEE+0x0)

ld.lld: error: duplicate symbol: vtable for MNN::Express::PipelineModule
>>> defined at PipelineModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(vtable for MNN::Express::PipelineModule)
>>> defined at PipelineModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.data.rel.ro._ZTVN3MNN7Express14PipelineModuleE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::NMSModule::create(MNN::Op const*)
>>> defined at NMSModule.cpp:20 (module/NMSModule.cpp:20)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(MNN::Express::NMSModule::create(MNN::Op const*))
>>> defined at NMSModule.cpp:20 (module/NMSModule.cpp:20)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(.text._ZN3MNN7Express9NMSModule6createEPKNS_2OpE+0x0)

ld.lld: error: duplicate symbol: vtable for MNN::Express::NMSModule
>>> defined at NMSModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(vtable for MNN::Express::NMSModule)
>>> defined at NMSModule.cpp
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(.data.rel.ro._ZTVN3MNN7Express9NMSModuleE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::NMSModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&)
>>> defined at NMSModule.cpp:105 (module/NMSModule.cpp:105)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(MNN::Express::NMSModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&))
>>> defined at NMSModule.cpp:105 (module/NMSModule.cpp:105)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(.text._ZN3MNN7Express9NMSModule9onForwardERKNSt6__ndk16vectorINS0_4VARPENS2_9allocatorIS4_EEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::NMSModule::clone(MNN::Express::Module::CloneContext*) const
>>> defined at NMSModule.cpp:155 (module/NMSModule.cpp:155)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(MNN::Express::NMSModule::clone(MNN::Express::Module::CloneContext*) const)
>>> defined at NMSModule.cpp:155 (module/NMSModule.cpp:155)
>>>            CMakeFiles/MNN_Express.dir/module/NMSModule.cpp.o:(.text._ZNK3MNN7Express9NMSModule5cloneEPNS0_6Module12CloneContextE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::countOutputReference(std::__ndk1::vector<int, std::__ndk1::allocator<int>>)
>>> defined at PipelineModule.cpp:178 (module/PipelineModule.cpp:178)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::countOutputReference(std::__ndk1::vector<int, std::__ndk1::allocator<int>>))
>>> defined at PipelineModule.cpp:178 (module/PipelineModule.cpp:178)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule20countOutputReferenceENSt6__ndk16vectorIiNS2_9allocatorIiEEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&)
>>> defined at PipelineModule.cpp:200 (module/PipelineModule.cpp:200)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&))
>>> defined at PipelineModule.cpp:200 (module/PipelineModule.cpp:200)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule9onForwardERKNSt6__ndk16vectorINS0_4VARPENS2_9allocatorIS4_EEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::onClearCache()
>>> defined at PipelineModule.cpp:235 (module/PipelineModule.cpp:235)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::onClearCache())
>>> defined at PipelineModule.cpp:235 (module/PipelineModule.cpp:235)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule12onClearCacheEv+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::_createSubGraph(MNN::Net const*, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>>&)
>>> defined at PipelineModule.cpp:237 (module/PipelineModule.cpp:237)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::_createSubGraph(MNN::Net const*, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>>&))
>>> defined at PipelineModule.cpp:237 (module/PipelineModule.cpp:237)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule15_createSubGraphEPKNS_3NetENSt6__ndk110shared_ptrINS0_8Executor14RuntimeManagerEEEPKNS0_6Module6ConfigERNS5_3mapINS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEENS0_8SubGraphENS5_4lessISK_EENSI_INS5_4pairIKSK_SL_EEEEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::WhileModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&)
>>> defined at WhileModule.cpp:165 (module/WhileModule.cpp:165)
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(MNN::Express::WhileModule::onForward(std::__ndk1::vector<MNN::Express::VARP, std::__ndk1::allocator<MNN::Express::VARP>> const&))
>>> defined at WhileModule.cpp:165 (module/WhileModule.cpp:165)
>>>            CMakeFiles/MNN_Express.dir/module/WhileModule.cpp.o:(.text._ZN3MNN7Express11WhileModule9onForwardERKNSt6__ndk16vectorINS0_4VARPENS2_9allocatorIS4_EEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::load(std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::shared_ptr<MNN::BufferStorage>, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>>&)
>>> defined at PipelineModule.cpp:604 (module/PipelineModule.cpp:604)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::load(std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::shared_ptr<MNN::BufferStorage>, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*, std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, MNN::Express::SubGraph, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, MNN::Express::SubGraph>>>&))
>>> defined at PipelineModule.cpp:604 (module/PipelineModule.cpp:604)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule4loadERKNSt6__ndk16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_NS2_10shared_ptrINS_13BufferStorageEEENSE_INS0_8Executor14RuntimeManagerEEEPKNS0_6Module6ConfigERNS2_3mapIS9_NS0_8SubGraphENS2_4lessIS9_EENS7_INS2_4pairIKS9_SP_EEEEEE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::load(std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, unsigned char const*, unsigned long, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*)
>>> defined at PipelineModule.cpp:565 (module/PipelineModule.cpp:565)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::load(std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, std::__ndk1::vector<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::allocator<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>> const&, unsigned char const*, unsigned long, std::__ndk1::shared_ptr<MNN::Express::Executor::RuntimeManager>, MNN::Express::Module::Config const*))
>>> defined at PipelineModule.cpp:565 (module/PipelineModule.cpp:565)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZN3MNN7Express14PipelineModule4loadERKNSt6__ndk16vectorINS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS7_IS9_EEEESD_PKhmNS2_10shared_ptrINS0_8Executor14RuntimeManagerEEEPKNS0_6Module6ConfigE+0x0)

ld.lld: error: duplicate symbol: MNN::Express::PipelineModule::clone(MNN::Express::Module::CloneContext*) const
>>> defined at PipelineModule.cpp:796 (module/PipelineModule.cpp:796)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(MNN::Express::PipelineModule::clone(MNN::Express::Module::CloneContext*) const)
>>> defined at PipelineModule.cpp:796 (module/PipelineModule.cpp:796)
>>>            CMakeFiles/MNN_Express.dir/module/PipelineModule.cpp.o:(.text._ZNK3MNN7Express14PipelineModule5cloneEPNS0_6Module12CloneContextE+0x0)

ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [express/CMakeFiles/MNN_Express.dir/build.make:316: express/OFF/libMNN_Express.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:884: express/CMakeFiles/MNN_Express.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by jxt1234** [comment]
What's your build command? Clear build dir and retry.
