### ISSUE TITLE
onnx模型转成mnn成功，但是testMNNFromOnnx失败

### ISSUE THREAD

**Issue by listzhpzhp** [alibaba/MNN#2778]
模型已经转换成功，运行脚本时segment fault，不清楚什么原因
[final2.zip](https://github.com/alibaba/MNN/files/14517697/final2.zip)

**Comment by jxt1234** [comment]
mnn 的版本是?

**Comment by listzhpzhp** [comment]
> mnn 的版本是?

当时的commit是9748f87eb5c6202c2849b23be8ace9d30360c8c5，谢谢

**Comment by jxt1234** [comment]
更新到最新版本，转换模型时加上 --optimizeLevel=0 ，可以转换成功并正常运行。这个主要原因是模型中有直接传输入输出的情况（不做任何操作把输入作为输出传出）。

**Comment by listzhpzhp** [comment]
> 更新到最新版本，转换模型时加上 --optimizeLevel=0 ，可以转换成功并正常运行。这个主要原因是模型中有直接传输入输出的情况（不做任何操作把输入作为输出传出）。

谢谢答复。转换模型时加上 --optimizeLevel=0，是可以正常运行，但是这样对运行速度是不是影响比较大，感觉这样耗时较多
