### ISSUE TITLE
OPPO A59S OpenCL支持疑问

### ISSUE THREAD

**Issue by geliudan** [alibaba/MNN#278]
源码中对否支持OpenCL的判断，是通过dlopen对应so，以及dlsym查找so中是否有函数符号。但是我在一台OPPO A59S手机（GPU是Mali-T860）测试，benchmark中打印log不支持OpenCL，在源码中跟踪发现dlopen的是libOpenCL.so，打不开libGLES_mali.so。同样的代码我在android studio中调用，dlopen的是libGLES_mali.so，打不开libOpenCL.so，且校验通过可以支持OpenCL。
请问这是什么原因呀？
感谢！

**Comment by runninglei1** [comment]
GLES不是openGL里面的吗？你详细说一下你的openCL安卓库是怎么编译的

**Comment by geliudan** [comment]
> GLES不是openGL里面的吗？你详细说一下你的openCL安卓库是怎么编译的

benchmark/bench_android.sh里的“OPENCL="ON”，然后编译执行了。

在**backend/opencl/core/runtime/OpenCLWrapper.cpp**里
static const std::vector<std::string> gOpencl_library_paths = {

#if defined(__APPLE__) || defined(__MACOSX)
    "libOpenCL.so", "/System/Library/Frameworks/OpenCL.framework/OpenCL"
#elif defined(__ANDROID__)
    "libOpenCL.so",
    "libGLES_mali.so",
    "libmali.so",
#if defined(__aarch64__)
    // Qualcomm Adreno
    "/system/vendor/lib64/libOpenCL.so",
    "/system/lib64/libOpenCL.so",
    // Mali
    "/system/vendor/lib64/egl/libGLES_mali.so",
    "/system/lib64/egl/libGLES_mali.so",
#else
    // Qualcomm Adreno
    "/system/vendor/lib/libOpenCL.so", "/system/lib/libOpenCL.so",
    // Mali
    "/system/vendor/lib/egl/libGLES_mali.so", "/system/lib/egl/libGLES_mali.so",
    // other
    "/system/vendor/lib/libPVROCL.so", "/data/data/org.pocl.libs/files/lib/libpocl.so"
#endif
#elif defined(__linux__)
    "/usr/lib/libOpenCL.so",
    "/usr/local/lib/libOpenCL.so",
    "/usr/local/lib/libpocl.so",
    "/usr/lib64/libOpenCL.so",
    "/usr/lib32/libOpenCL.so",
    "libOpenCL.so"
#endif
};
就有libGLES_mali.so

**Comment by hacker-joe** [comment]
目前这些路径只是针对大部分gpu的so路径。不排除部分比较特殊的存放路径。部分opencl设备的驱动是存在libGLES_mali.so中。所以会有libGLES_mali.so
