### ISSUE TITLE
安装pymnn时无法检测到numpy包导致报错，从而无法安装

### ISSUE THREAD

**Issue by Confetti-lxy** [alibaba/MNN#2782]
# 平台
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              1
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           0
Stepping:                        r0p0
CPU max MHz:                     3000.0000
CPU min MHz:                     3000.0000
BogoMIPS:                        100.00
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; CSV2, BHB
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jsc
                                 vt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flag
                                 m ssbs sb dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint

# Github版本:最新版本（3月10日）

# 编译方式:
默认给出的install方式
1、进入pymnn/pip_package 目录
2、python3 build_deps.py
3、sudo python3 setup.py install

在第三步的时候会出现报错：
USE_INTERNAL: False
USE_TRT: False
USE_CUDA: False
USE_OPENCL: False
USE_VULKAN: False
USE_RENDER: False
Building with python wheel with package name  MNN
['/root/mnn-llm/MNN/pymnn_build', '/root/mnn-llm/MNN/pymnn_build/tools/train', '/root/mnn-llm/MNN/pymnn_build/tools/cv', '/root/mnn-llm/MNN/pymnn_build/source/backend/tensorrt', '/root/mnn-llm/MNN/pymnn_build/source/backend/cuda']
Traceback (most recent call last):
  File "setup.py", line 430, in <module>
    extensions, cmdclass, packages, entry_points, lib_files = configure_extension_build()
  File "setup.py", line 217, in configure_extension_build
    engine_include_dirs += [np.get_include()]
NameError: name 'np' is not defined

但是我此时的环境中时有numpy包:
numpy                     1.21.6                   pypi_0    pypi

不知为何会无法检测并进行import,以及该如何进行安装

**Comment by v0jiuqi** [comment]
安装pymnn的python环境和有numpy的环境是一致的吗
