### ISSUE TITLE
onnx转MNN模型完成，使用 fastTestOnnx.py测试模型报错

### ISSUE THREAD

**Issue by air677** [alibaba/MNN#2783]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows11, vs2022

# Github版本:
# Github Version:
MNN 2.8.1

onnx转MNN模型完成，使用 fastTestOnnx.py测试转换的模型是否正确，fastTestOnnx.py使用https://geekdaxue.co/read/mnn@cn/model_convert提供的代码。在build目录下运行：
python fastTestOnnx.py model.onnx，报如下错误：

['75']
inputs:
x
outputs:
onnx/75.txt (1, 3, 720, 1280)
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

请问是什么原因

**Comment by v0jiuqi** [comment]
这个就是你命令行没有 cp 复制这个指令吧...

**Comment by air677** [comment]
我把代码里的cp改为copy命令后，重新运行python fastTestOnnx.py model.onnx 还是报错:

['75']
inputs:
x
outputs:
onnx/75.txt (1, 3, 720, 1280)
命令语法不正确。

'TestConvertResult' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by jxt1234** [comment]
用 MNN 仓库里面的 tools/scripts/testMNNFromOnnx.py 

fastTestOnnx.py 是老脚本了可能有些问题.
