### ISSUE TITLE
使用 Expr 模块里的 _Interp 接口，输出 tensor 里的值全为 0

### ISSUE THREAD

**Issue by HCRJKF2** [alibaba/MNN#2784]
auto f_device_tensor = mnn_interpreter->getSessionOutput(mnn_session, "f_lr");
    auto f_host_tensor = new MNN::Tensor(f_device_tensor, MNN::Tensor::CAFFE);
    f_device_tensor->copyToHostTensor(f_host_tensor);

    VARP f_lr = _Const(f_host_tensor->host<float>(), {1, f_host_tensor->channel(), input_h, input_w}, NCHW);
    std::vector<VARP> vars;
    vars.push_back(f_lr);
    VARP f_sr = _Interp(vars, 0, 0, out_w, out_h, BILINEAR, false);
    auto out_ptr = f_sr->readMap<float>();
    memcpy(out_data, out_ptr, out_w * out_h * f_host_tensor->channel() * sizeof(float));

代码如上，传入的 f_lr 里的值是正常的非零值，但输出的 f_sr 里的值全为 0。

使用的 MNN 版本是 2.7.1。

**Comment by jxt1234** [comment]
input_h, input_w , out_w, out_h 等参数是什么？ f_host_tensor 不要来源于 session

**Comment by jxt1234** [comment]
这个 resizeType 不对，需要写 1 (nearest) 或者 2(binlinear) ，不是那个宏  BILINEAR

**Comment by HCRJKF2** [comment]
> input_h, input_w , out_w, out_h 等参数是什么？ f_host_tensor 不要来源于 session

应该就是 f_host_tensor 的原因，但是这是为什么呢，把 f_host_tensor 的数据 copy 一遍就好了

**Comment by HCRJKF2** [comment]
> input_h, input_w , out_w, out_h 等参数是什么？ f_host_tensor 不要来源于 session

应该就是 f_host_tensor 的原因，直接把数据 copy 一份就正常了，这是为什么呢，数据都是一模一样的

**Comment by HCRJKF2** [comment]
> input_h, input_w , out_w, out_h 等参数是什么？ f_host_tensor 不要来源于 session

应该就是 f_host_tensor 的原因，直接把数据 copy 一份就正常了，这是为什么呢，数据都是一模一样的

**Comment by HCRJKF2** [comment]
> 这个 resizeType 不对，需要写 1 (nearest) 或者 2(binlinear) ，不是那个宏 BILINEAR

应该就是这个原因。
