### ISSUE TITLE
ios metal 编译生成的metallib 文件为空

### ISSUE THREAD

**Issue by suitmyself** [alibaba/MNN#279]
使用project/ios/MNN.xcodeproj编译生成metallib文件invalid，文件大小为 0KB。
追溯发现，如果设置 METAL_LIBRARY_FILE_BASE （位于POD file）为 default，则metallib文件正常。

**Comment by li-qing** [comment]
可否关注一下编译过程中有没有相关的报错？

**Comment by suitmyself** [comment]
没有看到相关报错，从编译记录来看，metal文件参与了编译，但生成的metallib文件确实为空。

**Comment by wings0820** [comment]
> 使用project/ios/MNN.xcodeproj编译生成metallib文件invalid，文件大小为 0KB。
> 追溯发现，如果设置 METAL_LIBRARY_FILE_BASE （位于POD file）为 default，则metallib文件正常。

这个podfile在哪啊，demo/ios/podfile的这个文件只有：
# coding: utf-8

platform :ios

target 'playground' do
    platform :ios, '8.0'
    pod 'MNN', :path => "../../"
end

**Comment by li-qing** [comment]
> 没有看到相关报错，从编译记录来看，metal文件参与了编译，但生成的metallib文件确实为空。

可以提供日志么？单个metal的编译日志和产物打包成metallib的日志

**Comment by ChisenZhang** [comment]
我的编出来好像也没有mental的库。 没有报错  报了一堆waning。 以前编出来一个metal的库，怎么编出来的忘了

**Comment by li-qing** [comment]
fixed.

**Comment by MrBaiSL** [comment]
hello @li-qing 怎么解决的
