### ISSUE TITLE
mnn跑走arm mali gpu用opencl mode选择MNN_GPU_MEMORY_IMAGE还是MNN_GPU_MEMORY_BUFFER

### ISSUE THREAD

**Issue by 486946** [alibaba/MNN#2790]
1.请问看某些文档上说arm mali gpu用opencl时buffer方式性能更优，实测buffer和image性能差异不大。另外看mnn内部实现支持image但是相比直接用buffer会多出来 buffer转image操作。那是否mnn跑走arm mali gpu用opencl mode应该选择MNN_GPU_MEMORY_BUFFER？

2.还有个问题，当用model cache来减少初始化耗时的情况下，MNN_GPU_MEMORY_BUFFER相比MNN_GPU_MEMORY_IMAGE 初始化耗时却会慢很多，这是因为什么？

**Comment by jxt1234** [comment]
1. mali 上面用 buffer 即可。MNN 默认配置也会在 mali gpu 上走 buffer .

**Comment by jxt1234** [comment]
2. 没明白意思。是指生成 cache 之后，buffer 启动速度慢于image 么？

**Comment by 486946** [comment]
> 2. 没明白意思。是指生成 cache 之后，buffer 启动速度慢于image 么？
对，就是创建model，创建session等这些初始化耗时buffer慢
