### ISSUE TITLE
ONNX转MNN模型提示转换成功结果却不正确(应该是转换有错误）

### ISSUE THREAD

**Issue by linghusmile** [alibaba/MNN#2791]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu20.04

# Github版本:
# Github Version:
commit 8d5d8b8844893d4cc1d6e0d3572870b8d53867e3

# 编译方式:
# Compiling Method
./package_scripts/linux/build.sh

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
-DMNN_BUILD_CONVERTER=on

# 转换时的日志打印
$ ./MNNConvert -f ONNX --modelFile /XXXX/YOLOv6/yolov6n.onnx --MNNModel /XXXX/YOLOv6/yolov6n.mnn --bizCode MNN
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.7
[15:40:55] :46: ONNX Model ir version: 7
[15:40:55] :47: ONNX Model opset version: 13
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ outputs, ]
Converted Success!

#模型验证后的打印
 python ../tools/script/testMNNFromOnnx.py /XXXX/YOLOv6/yolov6n.onnx
Dir exist
onnx/test.onnx
tensor(float)
['outputs']
inputs:
images
onnx/
outputs:
onnx/outputs.txt (1, 6300, 85)
onnx/
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.7
[15:44:43] :46: ONNX Model ir version: 7
[15:44:43] :47: ONNX Model opset version: 13
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ outputs, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
images
output: outputs
outputs: (1, 6300, 85, )
TEST_SUCCESS

然后发现给同样的输入图片时（确认了输入的tensor打印），两者的输出并不相同

yolov6n模型下载从https://github.com/meituan/YOLOv6获得

**Comment by linghusmile** [comment]
https://github.com/meituan/YOLOv6/releases/download/0.4.0/yolov6n.pt 因为无法直接上传onnx文件 所以可以通过这个链接下载pytorch文件

**Comment by v0jiuqi** [comment]
显示了testSunccess说明转模型没问题。

**Comment by v0jiuqi** [comment]
显示了testSuccess及就说明模型转换没问题

**Comment by jxt1234** [comment]
发下你的使用代码，大概率是输入输出的处理问题。较简单的处理方式是在转 mnn 模型时加上参数 --keepInputFormat
