### ISSUE TITLE
关于转换后的算子名称的疑问

### ISSUE THREAD

**Issue by liuyingbin123** [alibaba/MNN#2796]
onnx模型中不存在raster和while类型的算子，转换后出现大量raster和while类型的算子，raster查资料看到是和内存映射有关的操作，如concat、reshape等，while没有找到类似资料，麻烦解答一下while算子对应的是哪种操作

**Comment by jxt1234** [comment]
Raster算子是统一处理形变算子的，参考 https://zhuanlan.zhihu.com/p/674095025

While 是处理形变+计算+循环的情况用的算子，目前没开放资料（可能后续会变更设计方案）。

**Comment by liuyingbin123** [comment]
> Raster算子是统一处理形变算子的，参考 https://zhuanlan.zhihu.com/p/674095025
> 
> While 是处理形变+计算+循环的情况用的算子，目前没开放资料（可能后续会变更设计方案）。

感谢
