### ISSUE TITLE
openCL 2.6.0版本

### ISSUE THREAD

**Issue by aiyongchun** [alibaba/MNN#2799]
所用MNN版本是2.6.0，在安卓上用OPENCL，发现模型初始化时间要到十几秒，差点的手机要到四五十秒，但是我发现MNN2.4.0及以前版本在安卓上初始化耗时大概1秒左右。模型初始化时间要几十秒的问题，请问怎么解决？

**Comment by jxt1234** [comment]
1. numberThread 设成 1 ，去除 autotuning 过程
2. 用 setCacheFile 存储 resize 结果，下次启动时可以加快
