### ISSUE TITLE
ubuntu 16.04 converter error

### ISSUE THREAD

**Issue by jackcc** [alibaba/MNN#28]
os:ubuntu16.04 
gcc:5.4.0

Follow the doc , try convert caffe mobilenet-v1 to MNN,  MNNConvert crushed.

(gdb) r -f CAFFE --prototxt mobilenet_v1.caffe.prototxt  --modelFile mobilenet_v1.caffe.caffemodel --bizCode MNN --MNNModel mobilenet.mnn
Starting program: /home/jack/MNN/resource/build/MNNConvert -f CAFFE --prototxt mobilenet_v1.caffe.prototxt  --modelFile mobilenet_v1.caffe.caffemodel --bizCode MNN --MNNModel mobilenet.mnn
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff67b1970 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007ffff67b1970 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::empty() const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000530f87 in MNN::CreateNet(flatbuffers::FlatBufferBuilder&, MNN::NetT const*, std::function<unsigned long (void*)> const*) (_fbb=..., _o=0x0, _rehasher=0x0)
    at /home/jack/MNN/tools/converter/source/IR/MNN_generated.h:2962
#2  0x0000000000530e11 in MNN::Net::Pack(flatbuffers::FlatBufferBuilder&, MNN::NetT const*, std::function<unsigned long (void*)> const*) (_fbb=..., _o=0x0, _rehasher=0x0)
    at /home/jack/MNN/tools/converter/source/IR/MNN_generated.h:2955
#3  0x0000000000520661 in writeFb (netT=std::unique_ptr<MNN::NetT> containing 0x0, 
    MNNModelFile="mobilenet.mnn", benchmarkModel=false)
    at /home/jack/MNN/tools/converter/source/common/writeFb.cpp:58
#4  0x00000000004d64ba in main (argc=11, argv=0x7fffffffdcb8)
    at /home/jack/MNN/tools/converter/source/MNNConverter.cpp:46

**Comment by czy2014hust** [comment]
Could you give us the model link(for debug conveniently)?

**Comment by jackcc** [comment]
> Could you give us the model link(for debug conveniently)?

thanks for your reply,i pull the new code this morning ,the error disappear.close it.
