### ISSUE TITLE
Dilation CNN is very slow with kernel size (1,8) ...

### ISSUE THREAD

**Issue by jiarenyf** [alibaba/MNN#280]
用MNNV2Basic.out进行测试时，输出很奇怪。。。
网络结构含有1*8的dilation cnn，在I7电脑上CPU测试一次且输出正确需要8秒，但是有时候输出很快只要20ms，不过这时候结果一定是错的。。。

两个问题：1、为啥有时结果会是错的；2、为啥时间要8秒这么久。。。

**Comment by jxt1234** [comment]
有在 android / linux / mac / ios 上测试过么?

**Comment by jiarenyf** [comment]
@jxt1234 抱歉刚看到，在linux上面测试过，1*8的dilation要8秒，改成1*4的dilation只要9毫秒。。。

**Comment by jiarenyf** [comment]
@jxt1234 也许跟这个有关：https://github.com/alibaba/MNN/issues/298

**Comment by jxt1234** [comment]
具体的卷积参数是多少？（输入 w, h, c, 输出 w, h, c ，dilate x, y  kernelSize x, y）

**Comment by jiarenyf** [comment]
@jxt1234 输入w=40,h=4,c=256，输出w=40,h=4,c=128，dilation=(1,8)，kernelSize=(3,3)。。。

**Comment by jxt1234** [comment]
比较奇异的参数。。。 我有空测试下看看

**Comment by jiarenyf** [comment]
@jxt1234 Pad值是PAD_SAME

**Comment by jiarenyf** [comment]
[for_github.zip](https://github.com/alibaba/MNN/files/3655725/for_github.zip)

@jxt1234 这个for_github.zip里面包含一个有问题的mnn文件，我用里面的yfInference.cpp（放在MNN/tool/cpp里面编译得到yfInference）读取input.txt文件进行inference，输出存在output.txt，tensorflow的输出已经存在output_target.txt文件里面。

多次运行yfInference会发现输出、运行时间不一致，貌似与网络结构有关。具体如下：
1、inference几毫秒，output.txt与output_target.txt不一致，即速度快但输出错；
2、inference   几秒，output.txt与output_target.txt    一致，即速度慢但输出对；

麻烦帮忙看下，这个问题卡了很久了，谢谢🙏

**Comment by jiarenyf** [comment]
@jxt1234 能复现吗？🙏

**Comment by jiarenyf** [comment]
更新0.2.1.0版本后貌似修复了，先close啦。
谢谢哈🙏
