### ISSUE TITLE
onnx2mnn error: MNN/tools/converter/source/optimizer/PostTreatUtils.cpp:1202: Check failed: inputNum == 2 ==> BinaryOp should have two inputs Aborted

### ISSUE THREAD

**Issue by whuwiqian** [alibaba/MNN#281]
I converte a MXNET model to an onnx model. Then converting the onnx model to MNN cause an error:

Start to Convert Other Model Format To MNN Model...
[15:18:04] :29: ONNX Model ir version: 3
Start to Optimize the MNN Net...
terminate called after throwing an instance of 'Error'
  what():  [15:18:04] 
./MNN/tools/converter/source/optimizer/PostTreatUtils.cpp:1202: Check failed: inputNum == 2 ==> BinaryOp should have two inputs
Aborted

**Comment by czy2014hust** [comment]
Check your model. BinaryOp(Add,Prod,Sub...) should have two inputs.

**Comment by windhw** [comment]
I meet this issue too. And the reason is that MNN convertor cannot accept an OP that has one internal node  input  and the other one is graph's input.

**Comment by ymz-123** [comment]
> I converte a MXNET model to an onnx model. Then converting the onnx model to MNN cause an error:
> 
> Start to Convert Other Model Format To MNN Model...
> [15:18:04] :29: ONNX Model ir version: 3
> Start to Optimize the MNN Net...
> terminate called after throwing an instance of 'Error'
> what(): [15:18:04]
> ./MNN/tools/converter/source/optimizer/PostTreatUtils.cpp:1202: Check failed: inputNum == 2 ==> BinaryOp should have two inputs
> Aborted
hi, how do you solved this problem?

**Comment by ymz-123** [comment]
hi, how do you solved this problem?

**Comment by ymz-123** [comment]
> I converte a MXNET model to an onnx model. Then converting the onnx model to MNN cause an error:
> 
> Start to Convert Other Model Format To MNN Model...
> [15:18:04] :29: ONNX Model ir version: 3
> Start to Optimize the MNN Net...
> terminate called after throwing an instance of 'Error'
> what(): [15:18:04]
> ./MNN/tools/converter/source/optimizer/PostTreatUtils.cpp:1202: Check failed: inputNum == 2 ==> BinaryOp should have two inputs
> Aborted

hi, how do you solved this issue?
I have the same issue when covert MXNet model to MNN model

**Comment by jason-sticks** [comment]
same issue. how to solve

**Comment by whuwiqian** [comment]
MXNet add sample preprocess as an op, such as  subtract mean. MNN translate this op as BinaryOp, So lead to an error.
Please rewrite symbol file, delete preprocess ops.
