### ISSUE TITLE
linux aarch64 不能使用 vulkan運行benchmark嗎？

### ISSUE THREAD

**Issue by f745311** [alibaba/MNN#2811]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
在ubuntu上編譯，運行在linux aarch64

# Github版本:
# Github Version:
https://github.com/alibaba/MNN/tree/7f652661bfccd61c45b1f6db01a7c7775d1681a6

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
cmake .. \
-DMNN_OPENCL=ON \
-DMNN_VULKAN=ON \
-DMNN_BUILD_BENCHMARK=ON \
-DCMAKE_SYSTEM_NAME=Linux \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=aarch64 \
-DCMAKE_C_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-gcc \
-DCMAKE_CXX_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-g++
make -j8
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
編譯成功沒有問題
```

編譯成功沒有問題
運行benchmark 時，如果使用vulkan 就會出現 
```
libvulkan.so no such file or directory
```
然後更改libvulkan.so 並指向libvulkan.so.1之後出現
![截圖 2024-03-27 下午8 43 53](https://github.com/alibaba/MNN/assets/17903356/326ce516-4d71-4fd1-857d-ba4f273427d6)
請問該怎麼修正，是vulkan 功能不支援 linux aarch64嗎？

如果使用opnecl 則一切正常。

**Comment by jxt1234** [comment]
参见 FAQ 里面 gpu 项，简单起见可以加上 -DMNN_SEP_BUILD=false

**Comment by jxt1234** [comment]
https://mnn-docs.readthedocs.io/en/latest/faq.html

**Comment by roachsinai** [comment]
<img width="579" alt="image" src="https://github.com/alibaba/MNN/assets/9500049/a2f76b7d-a2db-4274-985a-fb26b99199ce">

@jxt1234 大佬 mnn-docs 的颜色主题能不能调整下。点击过的链接根本看不清楚。

**Comment by f745311** [comment]
加入了： -DMNN_SEP_BUILD=OFF
```
cmake .. \
-DMNN_OPENCL=ON \
-DMNN_VULKAN=ON \
-DMNN_BUILD_BENCHMARK=ON \
-DCMAKE_SYSTEM_NAME=Linux \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=aarch64 \
-DCMAKE_C_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-gcc \
-DCMAKE_CXX_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-g++ \
-DMNN_SEP_BUILD=OFF
```
也在benchmark.cpp 的 main中加入了
```
    auto handle_cl = dlopen("libMNN_CL.so", RTLD_NOW);
    auto handle_v = dlopen("libMNN_Vulkan.so", RTLD_NOW);
```
# 結果 
### opencl 一樣正常
<img width="636" alt="截圖 2024-04-09 下午6 14 59" src="https://github.com/alibaba/MNN/assets/17903356/853af865-5ee4-4981-8014-ecc5c11b930a">

### vulkan還是不能使用

![image](https://github.com/alibaba/MNN/assets/17903356/eeb6e529-445e-42af-9308-22213a31ddbe)

**Comment by jxt1234** [comment]
这个是设备上的 vulkan 驱动不支持，估计是驱动有问题或者设备不支持
