### ISSUE TITLE
Win32-cuda  编译失败，不带cuda编译正常

### ISSUE THREAD

**Issue by sg0771** [alibaba/MNN#2813]
16:42:59:803	已启动生成...
16:42:59:896	1>------ 已启动生成: 项目: MNN_CUDA, 配置: Release Win32 ------
16:43:00:046	1>Building NVCC (Device) object source/backend/cuda/CMakeFiles/MNN_CUDA.dir/execution/Release/MNN_CUDA_generated_ArgMinExecution.cu.obj
16:43:01:239	1>CMake Error at MNN_CUDA_generated_ArgMinExecution.cu.obj.Release.cmake:220 (message):
16:43:01:239	1>  Error generating
16:43:01:239	1>  C:/work/MNN/win32_cuda/source/backend/cuda/CMakeFiles/MNN_CUDA.dir/execution/Release/MNN_CUDA_generated_ArgMinExecution.cu.obj
16:43:01:239	1>
16:43:01:239	1>
16:43:01:249	1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(249,5): error MSB8066: “C:\work\MNN\source\backend\cuda\execution\ArgMinExecution.cu”的自定义生成已退出，代码为 1。
16:43:01:249	1>已完成生成项目“MNN_CUDA.vcxproj”的操作 - 失败。
16:43:01:261	========== 生成: 0 成功，1 失败，0 最新，0 已跳过 ==========
16:43:01:261	========= 生成 开始于 16:42，并花费了 01.519 秒 ==========

**Comment by jxt1234** [comment]
有更详细的报错信息么？具体到代码中报错行号?

**Comment by sg0771** [comment]
是 cuda11.7 的cudatoolkit，看起来不像是代码问题，而是编译命令不匹配
