### ISSUE TITLE
mnn模型转换成功。ios demo运行crash

### ISSUE THREAD

**Issue by jtyan123** [alibaba/MNN#2817]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
mac M1 14.4.1

# Github版本:
released this Dec 29, 2023
[ 2.8.1](https://github.com/alibaba/MNN/tree/2.8.1)
 d284430

# 编译方式:
pytorch->onnx->mnn成功。
ios demo中替换自己的模型在createSession时候出现EXC_BAD_ACCESS错误。xocde Version 15.3 。
<img width="1052" alt="截屏2024-04-08 19 18 29" src="https://github.com/alibaba/MNN/assets/96902364/83e239dd-a3a5-4314-bbe0-8fd7c3e85a58">

# 编译日志:
<img width="1435" alt="截屏2024-04-08 19 13 49" src="https://github.com/alibaba/MNN/assets/96902364/084c8ed1-9845-4ad6-a553-1f871a860a26">

# mnn:
[disk.mnn.zip](https://github.com/alibaba/MNN/files/14904711/disk.mnn.zip)

**Comment by jxt1234** [comment]
模型中存在 内容决定形状的情况，无法用 session api 加载，需要换用 module api

**Comment by jtyan123** [comment]
ok。多谢
