### ISSUE TITLE
Android平台MNN使用Vulkan后端推理在createSession时会crash

### ISSUE THREAD

**Issue by yizhaoyanbo** [alibaba/MNN#282]
MNN最新代码tag0.2.0.9，android上使用opencl, opengl 推理没有问题，结果也是正确的，使用vulkan后端推理CreateSession时会crash。
环境如下：华为p30 pro，编译mnn架构为arm64-v8a，4个线程，默认没有开openmp，mobilenetv2分类模型是从onnx转换过来。（在华为荣耀9 上也会出现同样的问题）

**Comment by jiarenyf** [comment]
厉害啊，我用opencl/opengl输出全0，vulkan也会crash。。。

**Comment by jxt1234** [comment]
官方模型会 crash 么，Android 上面的 so 是否有重编替换过？

**Comment by iazrael** [comment]
@jxt1234  我在荣耀v30也遇到这个问题，请问有解决吗？
