### ISSUE TITLE
pip install MNN fail

### ISSUE THREAD

**Issue by xlsd** [alibaba/MNN#2821]
pip install -U MNN
ERROR: Could not find a version that satisfies the requirement MNN (from versions: none)
ERROR: No matching distribution found for MNN.
someone who meet this problem?  how to do ?

**Comment by jxt1234** [comment]
What's your system?

**Comment by lzlwakeup** [comment]
I have the same error
win10 system

**Comment by jxt1234** [comment]
You can download mnn from https://pypi.org/project/MNN/
And check if your python version and system is match
