### ISSUE TITLE
c++ mNN  release lib so 版本选择

### ISSUE THREAD

**Issue by linlongrd** [alibaba/MNN#2822]
我的gcc是9.4.0的，在连接1.1.0版本的mNN  release lib so时候 
G2pEModel.cpp:(.text+0x7ec): undefined reference to `MNN::Interpreter::destroy(MNN::Interpreter*)'
/usr/bin/ld: G2pEModel.cpp:(.text+0x7fc): undefined reference to `MNN::Interpreter::destroy(MNN::Interpreter*)'
请问我应该用哪个版本的 so？

**Comment by jxt1234** [comment]
与 gcc 版本无关。这个函数应该是 2.0 之后的

**Comment by jxt1234** [comment]
与 gcc 版本无关。这个函数应该是 2.0 之后的
