### ISSUE TITLE
onnx转mnn，resize报错

### ISSUE THREAD

**Issue by 123liluky** [alibaba/MNN#2829]
pip安装了mnn 2.8.3
![image](https://github.com/alibaba/MNN/assets/20832778/0d7ad707-d32d-41bb-b071-c1bfa4568e7f)
然后转换yolo8模型，但是出现了和#1116类似的错误
![image](https://github.com/alibaba/MNN/assets/20832778/a4ccabc1-59bb-4e85-be63-bc7947cb5910)
请帮忙确认这个fix了没，谢谢！

**Comment by jxt1234** [comment]
已经 fix 了。应该是你本身的 MNNConvert 版本老。用 MNNConvert --version 可以打印版本号，如果打印不出来，说明是 2.0 之前的。

**Comment by jxt1234** [comment]
要用 pymnn 的 MNNConvert 是用小写的 mnnconvert

**Comment by 123liluky** [comment]
上面第二张图里面看到，mnnconverter的版本是2.1.5,怎么还是会报错呢
