### ISSUE TITLE
windows下是否支持GPU推理？

### ISSUE THREAD

**Issue by puxuntu** [alibaba/MNN#2833]
**我没有编译源代码，是直接使用的release 2.8.1的C++ windows包。**

**模型加载和config代码如下：**
    std::shared_ptr<Interpreter> net;
    net.reset(Interpreter::createFromFile(modelPath));
    if (net == nullptr) {
        MNN_ERROR("Invalid Model\n");
        return 0;
    }
    ScheduleConfig config;
    config.type = MNN_FORWARD_CUDA;
    config.mode = MNN_GPU_TUNING_NORMAL | MNN_GPU_MEMORY_IMAGE;
    auto session = net->createSession(config);
    auto input = net->getSessionInput(session, nullptr);

**控制台输出：**
Can't Find type=2 backend, use 0 instead

**Comment by jxt1234** [comment]
默认发的版本支持 opencl / vulkan ，cuda 的话需要自行编译

**Comment by sg0771** [comment]
Win32  总结
OpenGL 无法直接编译，需要 glew+ libGLES  ，还需要修改不少配置和代码，勉强编译通过也不能正常运行
cuda  使用11.7 的 cudatoolkit 编译出错
opencl 可以编译和运行，benchmark相比cpu执行时间大约1/6 ---- 1/2 ， 但是进程管理器里面没有提示使用 GPU
vulkan 可以编译和运行，正常调用GPU （如果机器比较老不支持会自动切换到cpu）

**Comment by yangy996** [comment]
> 默认发的版本支持 opencl / vulkan ，cuda 的话需要自行编译

cuda 已经自行编译了，但运行的时候还是提示这个，还需要改下哪里的参数呢？

**Comment by yangy996** [comment]
> 默认发的版本支持 opencl / vulkan ，cuda 的话需要自行编译

请问下，编译出带cuda的dll后，引入后，使用报错：OSError: exception: access violation reading 0x000000000000000F，这个需要怎么解决呢？
