### ISSUE TITLE
ONNX模型成功转为MNN后，通过几个测试工具如MNNV2Basic.out测试均未发现错误，使用python加载运行出现段错误

### ISSUE THREAD

**Issue by deahhh** [alibaba/MNN#2837]
0、onnx模型运行一切正常，结果正确，MNN原码使用的是v2.8.3。之前的onnx有错误，但MNN跑得通结果是错的，改正后跑不通，被改掉的问题是 某`Slice`结点的输入`end`本应是个整数，错设成了4维张量。
1、模型转换命令
```bash
./MNNConvert -f ONNX --modelFile model.onnx  --optimizeLevel 1 --optimizePrefer 2 -keepInputFormat --saveStaticModel --debug --MNNModel model.mnn
```
2、库的编译已开启 ` -DMNN_DEBUG=ON `，但是c++方式运行同样出现段错误，有用信息是`====== Tensor (nil) ======`，但不清楚是哪里缺了张量。转换的时候提示Resize有一个输入是空，但经查看，那个空是允许的，只有当使用了`roi：1维张量，仅当coordinate_transformation_mode为tf_crop_and_resize时生效`

3、输入数据为 nparray float shape与模型输入一致。

请问：
1、有提供其他调试工具吗
2、测试中没有出现错误是否可以认定模型出现段错误是输入的原因

**Comment by jxt1234** [comment]
先用 testMNNFromOnnx.py 测试

**Comment by deahhh** [comment]
> 先用 testMNNFromOnnx.py 测试

谢谢~！
