### ISSUE TITLE
ARM 推理设备选用GPU

### ISSUE THREAD

**Issue by BokyLiu** [alibaba/MNN#284]
@li-qing 离大大,请问使用海思3559开发板,有Mali G71的GPU,请问怎么可以使用板载GPU进行推理呢?

**Comment by BokyLiu** [comment]
正确编译了MNN的OPENCL,OPENGL等,但createSession时提示Can't Find type=4 backend, use 0 instead

**Comment by BokyLiu** [comment]
问题已解决,描述如下:
修改了CMakeList中
option(MNN_OPENCL "Enable OpenCL" ON)
option(MNN_OPENGL "Enable OpenGL" ON)
option(MNN_VULKAN "Enable Vulkan" ON)
结果发现并没有生成MNN_CL等so,于是单独编译libopenCL的MMN,成功生成了对应的so
后续使用参考https://github.com/alibaba/MNN/issues/105#issuecomment-508381853

**Comment by a243845305** [comment]
@BokyLiu 请问一下，如何单独编译libopenCL 的 MNN 呢？
我理解的是这样：
1.libOpenCL.so 应该是一个可以被编译为不同平台的开源库；
2.在编译MNN时指定 option(MNN_OPENCL "Enable OpenCL" ON)  得到指定平台的，可以使用opencl的libMNN.so
3.编写代码时手动指定libOpenCL.so （以Linux 为例），完成编译，并执行。

我的问题是这样：
1.不同平台的libOpenCL.so 我可以从哪里获取呢？或者编译？
2.在MNN最外层CMakelist.txt中指定 option(MNN_OPENCL "Enable OpenCL" ON) 后执行cmake ../          MNN_OPENCL 仍然为 OFF，请问是我哪个步骤有问题呢？

**Comment by menchunlei** [comment]
> option
修改CMakeList.txt后，需要把build下的CMakeFiles和CMakeCache.txt删除了，重新cmake ..
