### ISSUE TITLE
手机端高用vulkan失败，不是代码问题，也找到了库文件，也不是库文件的问题，ncnn可以正常使用vulkan

### ISSUE THREAD

**Issue by deahhh** [alibaba/MNN#2841]
1、Linux下作实验，首先`MNN_SEP_BUILD=OFF`，将`MNN_USE_SYSTEM_LIB=ON`时编译时提示找不到`vulkan`；将`MNN_USE_SYSTEM_LIB=OFF`时，创建`runtime`时发现使用的是`cpu`后端，在main函数里使用dlopen也还是不行。系统安装了libvulkan-dev后就能切换到vulkan后端了，但是耗比使用cpu，4个核多三倍，gpu是rtx2070。

2、Arm64下，android自带了`libvulkan.so verion=1.1.0`（记得在哪里看到MNN使用的是更高级版本），运行时能找到系统的libvulkan.so在`/system/lib64/`下，但创建`runtime`时报出段错误，提示说`vkGetDeviceQueue`函数调用出现问题。改用`MNN_USE_SYSTEM_LIB=OFF`，`MNN_SEP_BUILD=OFF`，执行时出错日志一模一样，还是去找库，还是找到了，还是这个函数调用出现段错误。

3、linux下使用了多种测试工具（MNNV2Basic，testMNNFromOnnx，GetMNNInfo）测试了模型转换，运算效率。值得一提的是，测试的时候也会依赖libvulkan，平均耗时比使用时快了几倍，大约比cpu还快一倍，也就是比编译出来（执行前后自己添加了时间戳）快大约8~10倍，也许是库的版本是DEBUG版的原因吧。不知道哪里能看到gpu执行时不支持的算子列表，没这个心里不踏实。

4、反复读了FAQ以及一些Issues，感觉能用的方法都用了，不能确定所述含义的地放就遍历地试，结果还是没用上手机端的gpu。希望大神能不吝指教一二。

在此先表示感谢！

所以，到底怎么加载自带的vulkan，是复制到andoid并覆盖系统自带的libvulkan.so吗？哪里能确定所使用的模型中算子在所用后台上是否支持？当前arm上找到了vulkan却报错是因为版本太低还是硬件不支持呢？

**Comment by jxt1234** [comment]
1. 手机上 vulkan 和 opencl 的使用都是 把 MNN_USE_SYSTEN_LIB 关掉，不要用系统库
2. 一些Android设备上无法在命令行模式下调用 vulkan ，需要在 Android App 中加载使用
3. 默认绝大部分算子 gpu 都支持的，遇到回退的情况反映为性能变慢，提 issue 即可
4. 手机上出于性能考虑建议用 MNN_OPENCL ，优化投入相比 vulkan 更多

**Comment by deahhh** [comment]
非常感谢。
我这系统上没有支持opencl，所以只能用vulkan。
算子的f16和f32看来是一起提供的喽。
不要用系统库，是完全不依赖系统库，还是libMNN.so会去找系统库，不用用户操作？
FQA里面的描述很简单，要么直接把后端编入libMNN.so，要么自己手动加载libMNN_CL.so.  很明显，结合当前所有信息，直接把USE_SYSTEM_LIB=OFF以及MNN_SEP_BUILD=OFF就可以用在arm64上了，但是我这里已经试过好多次了，

**Comment by jxt1234** [comment]
1. 是 mnn 运行时加载 libvulkan.so
2. 报的错是什么，如果是驱动不支持或者找不到库，会有报错

**Comment by deahhh** [comment]
> 1. 是 mnn 运行时加载 libvulkan.so
> 
>     2. 报的错是什么，如果是驱动不支持或者找不到库，会有报错

提示说`vkGetDeviceQueue`函数调用出现问题，错误是个空指针解引用。

**Comment by deahhh** [comment]
系统显示是有vulkan库的，版本是1.1.0，里面的接口函数大概340个

**Comment by deahhh** [comment]
@jxt1234 
       非常感谢大神的指点！
       请大神再指点一下，这vulkan后端使用怎么会错了呢，linux下本地使用都是正确的，手机端的使用也找到了库文件，而vulkan库经ncnn验证也能调起gpu：
```
#!/bin/bash
ANDROID_NDK=/home/han/Android/Sdk/ndk/27.0.11718014/

cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="arm64-v8a" \
-DANDROID_NATIVE_API_LEVEL=android-30  \
-DANDROID_STL=c++_static \
-DMNN_USE_LOGCAT=true \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DMNN_VULKAN=ON \
-DMNN_ARM82=ON \
-DMNN_BUILD_CONVERTER=ON \
-DMNN_PORTABLE_BUILD=ON \
-DMNN_SEP_BUILD=OFF \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3 $4 $5 $6 $7

```

**Comment by deahhh** [comment]
原因已找到，是硬件缺少必要的特性。
