### ISSUE TITLE
Cannot run MNN with OpenCL backend: Can't Find type = 3 backend, use 0 instead

### ISSUE THREAD

**Issue by xudh1991** [alibaba/MNN#285]
linux
Be similar to：https://github.com/alibaba/MNN/issues/105
I try to run model using MNN with OpenCL backend.
code：./benchmark.out ../benchmark/models/ 10 3
error: Can't Find type = 3 backend, use 0 instead
try1: change CMakeLists.txt:
-option(MNN_OPENCL  "Enable OpenCL" OFF)
+option(MNN_OPENCL  "Enable OpenCL" ON)
error: Can't Find type = 3 backend, use 0 instead
try2: try to change CMakeLists.txt:
-option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" OFF)
+option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" ON)
error: unrecognized command line option '-mfloat-abi=hard'
try3: CMakeLists.txt:
-option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" ON)
+option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" OFF)
-option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib" OFF)
+option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib" ON)
cmake:
Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
error: Can't Find type = 3 backend, use 0 instead
try4:
add the my path '/usr/local/cuda-9.0/lib64/libOpenCL.so' to
source/backend/opencl/core/runtime/OpenCLWrapper.cpp
cmake:
Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
error: Can't Find type = 3 backend, use 0 instead
try5:
add 
#inlcude<dlfcn.h>
auto handle = dlopen("libMNN_CL.so", RTLD_NOW);
FUNC_PRINT_ALL(handle, p);
to 
MNN/benchmark/benchmark.cpp
error:对 'dlopen ‘未定义的引用’ ld returned 1 exit status
and i am sure i add #inlcude<dlfcn.h> to the MNN/benchmark/benchmark.cpp
Please help

**Comment by BokyLiu** [comment]
error:对 'dlopen ‘未定义的引用’ ld returned 1 exit status

> linux
> Be similar to：#105
> I try to run model using MNN with OpenCL backend.
> code：./benchmark.out ../benchmark/models/ 10 3
> error: Can't Find type = 3 backend, use 0 instead
> try1: change CMakeLists.txt:
> -option(MNN_OPENCL "Enable OpenCL" OFF)
> +option(MNN_OPENCL "Enable OpenCL" ON)
> error: Can't Find type = 3 backend, use 0 instead
> try2: try to change CMakeLists.txt:
> -option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" OFF)
> +option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" ON)
> error: unrecognized command line option '-mfloat-abi=hard'
> try3: CMakeLists.txt:
> -option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" ON)
> +option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" OFF)
> -option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib" OFF)
> +option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib" ON)
> cmake:
> Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
> error: Can't Find type = 3 backend, use 0 instead
> try4:
> add the my path '/usr/local/cuda-9.0/lib64/libOpenCL.so' to
> source/backend/opencl/core/runtime/OpenCLWrapper.cpp
> cmake:
> Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
> error: Can't Find type = 3 backend, use 0 instead
> try5:
> add
> #inlcude<dlfcn.h>
> auto handle = dlopen("libMNN_CL.so", RTLD_NOW);
> FUNC_PRINT_ALL(handle, p);
> to
> MNN/benchmark/benchmark.cpp
> error:对 'dlopen ‘未定义的引用’ ld returned 1 exit status
> and i am sure i add #inlcude<dlfcn.h> to the MNN/benchmark/benchmark.cpp
> Please help

error:对 'dlopen ‘未定义的引用’ ld returned 1 exit status
需要连接libdl.so.2

**Comment by xudh1991** [comment]
@BokyLiu add libdl.so.2 to <dlfcn.h>?
Would you please show me more detailed operation?
thanks

**Comment by mittkongg** [comment]
what is
 Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "1.2")
error: Can't Find type = 3 backend, use 0 instead mean?
and try1 - ty5?  我也遇到了这个问题，要装个opencl环境吗？感觉太麻烦 我是在docker里弄的
