### ISSUE TITLE
Demo multiPose fail, report  inputChannel: 225, batch:1, width:225, height:3. Input data channel may be mismatch with filter channel count

### ISSUE THREAD

**Issue by bin913** [alibaba/MNN#2859]
平台： ubuntu20.04 intel cpu
```

Github版本: ba4ecd9792f76c21061215342722fe052f5faf5b
```

编译方式:
mkdir build && cd build
cmake .. -DMNN_BUILD_DEMO=ON -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_TORCH=ON
make -j4
```
报错信息：
originalWidth:225
originalHeight:225
originalChannel:4
The device support i8sdot:0, support fp16:0, support i8mm: 0
	**Tensor shape**: 1, 225, 3, 225, 
Error for compute convolution shape, inputCount:3, outputCount:24, KH:3, KW:3, group:1
inputChannel: 225, batch:1, width:225, height:3. Input data channel may be mismatch with filter channel count
Compute Shape Error for MobilenetV1/add

```

**Comment by zyg519** [comment]
https://github.com/alibaba/MNN/blob/ba4ecd9792f76c21061215342722fe052f5faf5b/demo/exec/multiPose.cpp#L337
调整一下维度顺序试试

**Comment by bin913** [comment]
我调整维度顺序之后，测试通过了，多谢

**Comment by lwmonster** [comment]
> 我调整维度顺序之后，测试通过了，多谢

怎么调整的维度？

**Comment by lwmonster** [comment]
> https://github.com/alibaba/MNN/blob/ba4ecd9792f76c21061215342722fe052f5faf5b/demo/exec/multiPose.cpp#L337
> 
> 
> 调整一下维度顺序试试

mnnNet->resizeTensor(input, {1, targetHeight, targetWidth, 3});
调整成这样可以了， 这是为啥呢？
