### ISSUE TITLE
量化工具编译报错，请求帮助。

### ISSUE THREAD

**Issue by hzqqqqq** [alibaba/MNN#286]
cmake  .. -DMNN_BUILD_QUANTOOLS=on
make -j4

cmake时打开量化开关，在make 的时候报错:
/home/xxx/AndroidStudioProjects/MNN/tools/quantization/logkit.h: In destructor ‘LogMessageFatal::~LogMessageFatal()’:
/home/xxx/AndroidStudioProjects/MNN/tools/quantization/logkit.h:185:38: error: exception handling disabled, use -fexceptions to enable
         throw Error(log_stream_.str());

**Comment by hzqqqqq** [comment]
系统为UBUNTU18.04

**Comment by hzqqqqq** [comment]
系统为UBUNTU18.04

**Comment by hzqqqqq** [comment]
CMakeLists.txt 添加开关
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS}    ...  -fexceptions")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  ...  -fno-exceptions -fexceptions")

**Comment by leemengxing** [comment]
多谢指导，编译成功。
