### ISSUE TITLE
MNN1.2 MNN_CODEGEN_REGISTER是什么？可以关了吗？

### ISSUE THREAD

**Issue by xin486946** [alibaba/MNN#2860]
https://github.com/alibaba/MNN/tree/1.2.0/source/backend/arm82/Arm82Backend.cpp中全局如下：
#ifndef MNN_CODEGEN_REGISTER
static const auto __arm82_global_initializer = []() {
    registerArm82RuntimeCreator();
    return true;
}();
#endif

请问这个是干嘛的？如果我定义MNN_CODEGEN_REGISTER把这个屏蔽掉编译mnn库是否可以

**Comment by jxt1234** [comment]
历史上的作用是把 cpu / metal 的注册函数由定义静态变量自注册改为在初始化函数中注册。现在这部分已经全部切换为在初始化函数中注册，不再使用静态变量注册的方法。
