### ISSUE TITLE
MNN推理的内存/cpu使用率

### ISSUE THREAD

**Issue by jamesdod** [alibaba/MNN#2870]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
linux,x86_64

# Github版本:
2.8.2

# 编译方式:
```
cmake ..
make
```

# 设置：
1. 推理代码完全一样，只有forward_type不一样，一个为MNN_FORWARD_CPU，一个为MNN_FORWARD_OPENCL
2. 通过`cat /proc/pid/status`来查看物理内存，**CPU内存**
3. 通过`top`命令查看cpu使用率

# 现象：
1. CPU版本内存为50M，GPU版本内存为150M。这仅是**CPU内存**，为什么GPU版本的**CPU内存**使用比CPU版本还高呢
2. CPU版本的cpu使用率为80%，GPU版本的cpu使用率为60%。为什么GPU版本的cpu使用率还这么高呢，应该只有传入和传出数据，计算量很低吧

**Comment by jxt1234** [comment]
1. 用 MNNV2Basic.out 测试一下
2. 相关模型提交一下吧
