### ISSUE TITLE
手机端OpenCL 在Normal和Low精度下图像推理结果错误（全黑）

### ISSUE THREAD

**Issue by CloudGuardian** [alibaba/MNN#2872]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android maliG57 GPU

# Github版本:
# Github Version:
2.8.1

如标题，我使用OpenCL 推理，在Normal和Low精度下推理结果错误，结果输出为全黑（0）
但Precision_High推理结果正常，且CPU和VULKAN在各个精度下的结果也都正常

**Comment by jxt1234** [comment]
可能是 fp16 计算越界了，更新到 2.9.0 试下 precision = normal

**Comment by CloudGuardian** [comment]
> 可能是 fp16 计算越界了，更新到 2.9.0 试下 precision = normal

![img_v3_02b4_26ab753e-3264-4633-85a6-6a1180e2618g](https://github.com/alibaba/MNN/assets/34885674/349039cd-12af-45e7-91ce-d95f91eada7b)
2.9.0编译android有报错🤠

**Comment by CloudGuardian** [comment]
> 可能是 fp16 计算越界了，更新到 2.9.0 试下 precision = normal

![img_v3_02b4_26ab753e-3264-4633-85a6-6a1180e2618g](https://github.com/alibaba/MNN/assets/34885674/9abda4f2-ce9e-4a50-af3e-bceff4f6cfc8)

2.9.0编译android有报错🤠
