### ISSUE TITLE
meta-llama3-8b-instruct 使用llm_demo 推理报错

### ISSUE THREAD

**Issue by quinlan-w** [alibaba/MNN#2879]
# Platform(Include target platform as well if cross-compiling):  
cross-compiling 

# Github版本:
# Github Version:

# 问题描述：
meta-llama3-8b-instruct-int4 使用llm_demo 推理报错 log 如下
./llm_demo ../meta-llama3-8b-instruct-int4/llm.mnn 0 10 prompt.txt
model path is ../meta-llama3-8b-instruct-int4/llm.mnn
### model name : Llama3_8b
The device support i8sdot:1, support fp16:1, support i8mm: 1
OpenCL init error, fallback ...
Error to use creator of 3, delete it
Can't open file:.tempcache
Load Cache file error.
load tokenizer
load tokenizer Done
### disk embedding is 1
load ../meta-llama3-8b-instruct-int4/llm.mnn ... Done!
main, 95, cost time: 66248.062500 ms
Prepare for resize opt Begin
Compute Shape Error for /layers.0/self_attn/Gather_3_output_0
code=3 in onForward, 391
Segmentation fault

**Comment by jxt1234** [comment]
是否在模型转换时加了 --transformerFuse ? 目前还不支持 llama3 的 transformer fuse
