### ISSUE TITLE
我尝试在win10上编译"模型转换器"时遇到了一些错误

### ISSUE THREAD

**Issue by TCBocean** [alibaba/MNN#288]
我按照https://github.com/alibaba/MNN/issues/156 的提示，成功进行到了最后一步，但是还是出现了错误。我不知道该如何解决它。

有谁遇到了这个问题并解决了的吗？
谁能给我我一些帮助吗？万分感谢！

下面是我出错打印出的日志：
`C:\Users\stars_ocean\Desktop\MNN-0.2.0.9\tools\converter\build>cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
-- The C compiler identification is MSVC 19.16.27032.1
-- The CXX compiler identification is MSVC 19.16.27032.1
-- Check for working C compiler: C:/software/VS2017/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/software/VS2017/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/software/VS2017/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/software/VS2017/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: optimized;D:/protobuf-3.5.1/vsprojects/x64/Release/libprotobuf.lib;debug;D:/protobuf-3.5.1/vsprojects/x64/Debug/libprotobufd.lib (found version "3.5.1")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/stars_ocean/Desktop/MNN-0.2.0.9/tools/converter/build

C:\Users\stars_ocean\Desktop\MNN-0.2.0.9\tools\converter\build>nmake

Microsoft (R) 程序维护实用工具 14.16.27032.1 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

Scanning dependencies of target MNNDump2Json.out
[  0%] Building CXX object CMakeFiles/MNNDump2Json.out.dir/source/MNNDump2Json.cpp.obj
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
MNNDump2Json.cpp
C:\Users\stars_ocean\Desktop\MNN-0.2.0.9\tools\converter\source\IR\MNN_generated.h(5248): error C2440: “初始化”: 无法 从“const int32_t [129]”转换为“const int64_t *”
C:\Users\stars_ocean\Desktop\MNN-0.2.0.9\tools\converter\source\IR\MNN_generated.h(5248): note: 与指向的类型无关；强制转换要求 reinterpret_cast、C 样式强制转换或函数样式强制转换
C:\Users\stars_ocean\Desktop\MNN-0.2.0.9\tools\converter\source\IR\flatbuffers/util.h: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
NMAKE : fatal error U1077: “C:\software\VS2017\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “C:\software\VS2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “C:\software\VS2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.`

**Comment by eudora-jia** [comment]
最后怎么解决的？

**Comment by TCBocean** [comment]
@eudora-jia 最后我放弃了，哈哈哈哈
在win10上你可以装个ubuntu虚拟机，在那里面编译MNN会容易。
如果你只想要模型转换器的话，可以下载一个MNNWorkbench客户端，那里面也有模型转换器。

**Comment by eudora-jia** [comment]
ok
