### ISSUE TITLE
onnx转mnn之后模型推理和原模型差距太大

### ISSUE THREAD

**Issue by huma8848888** [alibaba/MNN#2880]
使用pytorch训练好的模型，转换为onnx之后推理都正常，但是转换mnn之后推理结果差了太多，模型就是一个mobilenetV3 4分类模型，使用mnn模型测试工具显示TEST_SUCCESS,但是在pc侧使用mnn的python session推理结果就不正常，请问一下官方该如何排查，模型出的问题在哪里
[Uploading abcd_mnn.mnn.zip…]()

**Comment by jxt1234** [comment]
用 Module API 推理

**Comment by huma8848888** [comment]
android端侧如何调用module推理

**Comment by jxt1234** [comment]
自行编写 jni 代码，调 MNN_Express 里面的 Module API 推理即可，
https://mnn-docs.readthedocs.io/en/latest/inference/module.html
