### ISSUE TITLE
编译测试工具报错阻塞

### ISSUE THREAD

**Issue by huma8848888** [alibaba/MNN#2887]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
macos
pytorch=1.12.0
python=3.10.14
# Github版本:
# Github Version:
2.9.0
直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake .. -DMNN_BUILD_TOOL=ON
make -j4
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
(convert) tal@TALdeMacBook-Pro build % make -j4   
[  0%] Built target MNNMath
[  1%] Built target MNNCV
[  2%] Built target MNNCore
[  2%] Built target MNNUtils
[  3%] Built target MNNX8664
[  4%] Built target MNNAVX
[  6%] Built target MNNAVXFMA
[  7%] Built target MNNSSE
[  7%] Built target checkDir.out
[  7%] Built target checkFile.out
[ 21%] Built target MNNTransform
[ 32%] Built target MNNCPU
[ 35%] Built target libprotobuf-lite
[ 35%] Built target MNN
[ 35%] Built target MNNCompress
[ 36%] Built target MNN_Express
[ 46%] Built target libprotobuf
[ 54%] Built target MNNConverterTF
[ 60%] Built target MNNConverterONNX
[ 64%] Built target MNNConverterCaffe
[ 64%] Built target MNNConverterMNN
[ 64%] Built target GetMNNInfo
[ 64%] Built target ModuleBasic.out
[ 69%] Built target MNNConverterTFL
[ 69%] Built target SequenceModuleTest.out
[ 70%] Built target mergeInplaceForCPU
[ 70%] Built target mobilenetTest.out
[ 70%] Built target MNNV2Basic.out
[ 70%] Built target testModel.out
[ 70%] Built target backendTest.out
[ 71%] Built target testModelWithDescribe.out
[ 71%] Built target testModel_expr.out
[ 71%] Built target getPerformance.out
[ 71%] Built target checkInvalidValue.out
[ 76%] Built target MNNConverterTorch
[ 76%] Built target testTrain.out
[ 76%] Built target timeProfile.out
[ 77%] Built target fuseTest
[ 94%] Built target MNNConverterOpt
[ 94%] Built target LoRA
[ 95%] Built target winogradExample.out
[ 96%] Built target OnnxClip
[ 96%] Linking CXX shared library libMNNConvertDeps.dylib
ld: warning: ignoring duplicate libraries: '../../3rd_party/protobuf/cmake/libprotobuf.a'
ld: library 'mkl_intel_ilp64' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/converter/libMNNConvertDeps.dylib] Error 1
make[1]: *** [tools/converter/CMakeFiles/MNNConvertDeps.dir/all] Error 2
make: *** [all] Error 2
# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by huma8848888** [comment]
编译示例工程也出现了同样的问题：
ld: warning: ignoring duplicate libraries: '../../3rd_party/protobuf/cmake/libprotobuf.a'
ld: library 'mkl_intel_ilp64' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/converter/libMNNConvertDeps.dylib] Error 1
make[1]: *** [tools/converter/CMakeFiles/MNNConvertDeps.dir/all] Error 2
make: *** [all] Error 2

**Comment by Nithinholalkere** [comment]
what does MNN_ONEDNN in MNN ? just for curiosity
