### ISSUE TITLE
c++ 链接MNN后，编译报错，无法解析的外部符号 _std_init_once_link_alternate_names_and_abort和_std_min_element_4

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#2889]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows

# Github版本:
2.9.0

# 编译方式:
visual studio 引入 静态库
mnn_2.9.0_windows_x64_cpu_opencl\lib\x64\Release\Static\MD\MNN.lib

生成lib文件报错
![image](https://github.com/alibaba/MNN/assets/15188456/beefac7b-44a9-4354-a904-b1effd7bc7f3)

**Comment by yangy996** [comment]
切换到动态库mnn_2.9.0_windows_x64_cpu_opencl\lib\x64\Release\Dynamic\MD\MNN.lib，正常了

**Comment by jxt1234** [comment]
像是因为 vs 版本不一致

**Comment by yangy996** [comment]
> 像是因为 vs 版本不一致

我用的版本是Microsoft Visual Studio Community 2019

**Comment by yangy996** [comment]
动态库引入的方式，编译时候又报错了：
![image](https://github.com/alibaba/MNN/assets/15188456/b2332272-c31b-4857-8a72-6c0660e9938a)

**Comment by yangy996** [comment]
试了好几个版本，无法编译通过
![image](https://github.com/alibaba/MNN/assets/15188456/111742ea-135f-4c36-b064-c76d0a0b494d)

**Comment by jxt1234** [comment]
链接mnn的主工程要打开 C++ 11 这个选项
