### ISSUE TITLE
可以在手机的TEE上运行吗？

### ISSUE THREAD

**Issue by szWingLee** [alibaba/MNN#289]
处于安全原因，要安全环境下运行，目前版本支持吗？

**Comment by li-qing** [comment]
“运行在TEE的应用称为可信应用（即TA，Trusted Apps），其可以访问设备主处理器和内存的全部功能，硬件隔离技术保护其不受安装在主操作系统环境的用户Apps影响。”

按说是没有问题的。你顾虑的点在于？

**Comment by szWingLee** [comment]
代码中有stl的vector，似乎不能在tee中运行。
验证如下：
>>在可以在TEE运行的代码上加过STL测试，TA直接挂了，没有任何log输出，连调用STL之前的log都没有。编译和链接没有任何问题，堆空间也没有问题。OP-TEE之类ta os明确不支持STL的。我用的是linaro gcc 7.3.1，自带libstdc++库，用这个编译器编译的不含STL调用的C++代码是可以在TEE跑的；但可以用STL声明，比如：
std::vector a; //在TEE可以跑通
调用STL则会直接挂掉，比如：
a.push_back(1);//加入这句TEE直接失效，不能启动。
>>初步怀疑是allocator的问题。
>>不使用allocator的stl估计没有问题，待验证。

**Comment by li-qing** [comment]
> 代码中有stl的vector，似乎不能在tee中运行。
> 验证如下：
> 
> > > 在可以在TEE运行的代码上加过STL测试，TA直接挂了，没有任何log输出，连调用STL之前的log都没有。编译和链接没有任何问题，堆空间也没有问题。OP-TEE之类ta os明确不支持STL的。我用的是linaro gcc 7.3.1，自带libstdc++库，用这个编译器编译的不含STL调用的C++代码是可以在TEE跑的；但可以用STL声明，比如：
> > > std::vector a; //在TEE可以跑通
> > > 调用STL则会直接挂掉，比如：
> > > a.push_back(1);//加入这句TEE直接失效，不能启动。
> > > 内存分配使用malloc/free/realloc没有问题，初步怀疑是allocator的问题。
> > > 不使用allocator的stl估计没有问题，待验证。

stl不支持的话是没法跑的
