### ISSUE TITLE
MNN.cv has the rotation issue in loading some photos from the phone

### ISSUE THREAD

**Issue by happylusa-liu** [alibaba/MNN#2891]
## Version
https://pypi.org/project/MNN/
MNN==2.8.3

## Issue 
I think there is something wrong in the` imread()` function inside of MNN.cv package.
`MNN.cv.imread(image_path)` will return an image with clockwise version of the original image but opencv-python could return a correct image without rotation for the same image.

**Comment by jxt1234** [comment]
MNN.cv use stbi. It currently don't support load rotation info from jpg's exif. We will fix it later.
