### ISSUE TITLE
请问MNN如何实现使用同一模型做并行推理？

### ISSUE THREAD

**Issue by CloudGuardian** [alibaba/MNN#2898]
我希望加载同一个mnn模型，但是在多线程下并行地推理多个输入，请问该如何实现呢🐶？

**Comment by CloudGuardian** [comment]
> 参考文档多实例推理 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6

❤

**Comment by CloudGuardian** [comment]
> 参考文档多实例推理 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6

Session API是否也支持多实例推理呢？

**Comment by CloudGuardian** [comment]
> 参考文档多实例推理 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6

大佬在吗？🐱

**Comment by jxt1234** [comment]
> > 参考文档多实例推理 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6
> 
> Session API是否也支持多实例并行推理呢？

目前不支持。Session API 只能分开创建实例进行推理，不支持权重共享

**Comment by CloudGuardian** [comment]
> > > 参考文档多实例推理 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6
> > 
> > 
> > Session API是否也支持多实例并行推理呢？
> 
> 目前不支持。Session API 只能分开创建实例进行推理，不支持权重共享

好吧
