### ISSUE TITLE
可以run一次提取两个层的结果吗？

### ISSUE THREAD

**Issue by xingyanan** [alibaba/MNN#290]
想提取特征最后一个特征层，做两个stage，MNN支持两个输出吗

**Comment by czy2014hust** [comment]
分两种情况：
- 想要获取的输出若是中间层，在[ScheduleConfig](https://github.com/alibaba/MNN/blob/cfad1c3b3b29fda39354569881eb433d07e55e09/include/Interpreter.hpp#L24)中配置输出tensor name，内存防止被复用
- 若就是两个输出，直接调用[API](https://github.com/alibaba/MNN/blob/cfad1c3b3b29fda39354569881eb433d07e55e09/include/Interpreter.hpp#L205)取出就行
