### ISSUE TITLE
手机端vulkan特性 image_write_without_format这个特性影响大吗?

### ISSUE THREAD

**Issue by deahhh** [alibaba/MNN#2906]

**Comment by jxt1234** [comment]
估计是不能用 fp32 写入 image ，这样的话，mnn vulkan - image 无法使用 precision = low / normal 的模式。可以换用 mnn vulkan - buffer (加上 -DMNN_VULKAN_IMAGE=false)

**Comment by deahhh** [comment]
> 估计是不能用 fp32 写入 image ，这样的话，mnn vulkan - image 无法使用 precision = low / normal 的模式。可以换用 mnn vulkan - buffer (加上 -DMNN_VULKAN_IMAGE=false)

我的硬件不支持这个特性，所以一直无法启用gpu，因为没有opencl库。
找到原因后，禁用了这个特性，能运行了，但是速度奇慢：该gpu标称35GFlops与8个核的cpu等同，但是最终计算速度只有四个核心cpu速度的1/10。

不知道这个gpu还有救吗
