### ISSUE TITLE
mnn 模型，Android 平台 benchmark 测试，推理使用 openCL, vulkan 都比 CPU 慢，可能是什么原因？

### ISSUE THREAD

**Issue by dearwind153** [alibaba/MNN#2907]
MNN 版本：MNN-2.9.0
平台：Android 小米9 硬件
NDK: NDK-r20b
编译时，同时编译 Android 平台 CPU， openCL, vulkan 后端

**mnn 模型，Android 平台 benchmark 测试，推理使用 openCL, vulkan 都比 CPU 慢，可能是什么原因？**

CPU backend 测试：          _**max =  297.433 ms  min =  294.566 ms  avg =  296.252 ms**_
openCL backend 测试：     _**max =  720.318 ms  min =  661.634 ms  avg =  699.978 ms**_
vulkan backend 测试：       _**max = 2201.615 ms  min = 2060.933 ms  avg = 2118.065 ms**_

mnn model 已发送到 ：120543985@qq.com

详细测试情况如下：

CPU backend 测试
————————————————————————————————————————————————

./benchmark.out ./mnn_models/ 15 5 0 4 0
MNN benchmark
Forward type: CPU thread=4 precision=0 sparsity=0 sparseBlockOC=1 testQuantizedModel=0
--------> Benchmarking... loop = 15, warmup = 5
[-INFO-]: precision!=2, use fp32 inference.
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc SM8150"
The device support i8sdot:1, support fp16:1, support i8mm: 0
[ - ] onnxsim.mnn    _**max =  297.433 ms  min =  294.566 ms  avg =  296.252 ms**_
![CPU](https://github.com/alibaba/MNN/assets/15264400/9b8ae6b6-ad00-4ac0-ad7a-64e4e89a4c69)

openCL backend 测试
————————————————————————————————————————————————
./benchmark.out ./mnn_models/ 15 5 3 4 0
MNN benchmark
Forward type: OpenCL thread=4 precision=0 sparsity=0 sparseBlockOC=1 testQuantizedModel=0
--------> Benchmarking... loop = 15, warmup = 5
[-INFO-]: precision!=2, use fp32 inference.
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc SM8150"
The device support i8sdot:1, support fp16:1, support i8mm: 0
[ - ] onnxsim.mnn    _**max =  720.318 ms  min =  661.634 ms  avg =  699.978 ms**_
![openCL](https://github.com/alibaba/MNN/assets/15264400/83e23676-807a-4d97-bb35-139e3f6fa6dc)

vulkan backend 测试
————————————————————————————————————————————————
 ./benchmark.out ./mnn_models/ 15 5 7 4 0
MNN benchmark
Forward type: Vulkan thread=4 precision=0 sparsity=0 sparseBlockOC=1 testQuantizedModel=0
--------> Benchmarking... loop = 15, warmup = 5
[-INFO-]: precision!=2, use fp32 inference.
parsed /proc/cpuinfo Hardware = "Qualcomm Technologies, Inc SM8150"
The device support i8sdot:1, support fp16:1, support i8mm: 0
[ - ] onnxsim.mnn    _**max = 2201.615 ms  min = 2060.933 ms  avg = 2118.065 ms**_
![vulkan](https://github.com/alibaba/MNN/assets/15264400/0c070a96-8c1e-4e30-bbfa-3835b5a5df2c)

**Comment by jxt1234** [comment]
可能是有尺寸超出。换用 buffer 试下吧。
OpenCL: numberThread 设成 68
Vulkan ：编译时加上 -DMNN_VULKAN_IMAGE=OFF

**Comment by jxt1234** [comment]
另外模型文件我好像没收到，重新发一下?
