### ISSUE TITLE
鸿蒙32位 推理速度异常缓慢

### ISSUE THREAD

**Issue by Gangti** [alibaba/MNN#2908]
OpenHarmony 32位系统下，运行MNN armeabi-v7a版本，MNN自带的例程运行速度异常缓慢。

如下推理过程耗时 **数十秒**，请问，这个问题怎么解决？

```
# LD_LIBRARY_PATH=./ ./pictureRecognition.out checkpoints/yolov5ss.mnn 000070.jpg
Can't open file:.cachefile
Load Cache file error.
The device support i8sdot:0, support fp16:0, support i8mm: 0
Session Info: memory use 74.788513 MB, flops is 5414.788086 M, backendType is 0, batch size = 1
input: w:640 , h:640, bpp: 3
origin size: 768, 576
For Image: 000070.jpg
6267, 7.124424
7107, 6.997192
7417, 6.943126
7127, 6.860505
23417, 6.754698
7027, 6.675661
22267, 6.660660
23107, 6.552225
38267, 6.535619
1437, 6.521504
#

```

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

OpenHarmony-v4.0-Release, 32位版

在/MNN/project /harmony/build_64.sh的基础上，新建如下编译脚本

/MNN/project /harmony/build_32.sh

```
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$HARMONY_HOME/native/build/cmake/ohos.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DOHOS_ARCH="armeabi-v7a" \
-DOHOS_STL=c++_static \
-DMNN_USE_LOGCAT=false \
-DMNN_BUILD_BENCHMARK=ON \
-DMNN_USE_SSE=OFF \
-DMNN_SUPPORT_BF16=OFF \
-DMNN_BUILD_TEST=ON \
-DOHOS_PLATFORM_LEVEL=9  \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4

```

# 编译方式:
# Compiling Method

/MNN/project /harmony/build_32.sh

**Comment by Gangti** [comment]
> 编译时 arm32 下面的 .S 编译进去了么？

非常感谢，确认了下，ARM32下面的.S件确实没有被编译进去。
编进去之后，就能够正常加速推理了。

**Comment by feixuedudiao** [comment]
@Gangti 你编译的环境配置是啥，具体到ubuntu系统是哪个版本，我这边用buntu 7.5.0-3ubuntu1~18.04编译遇到下面问题：
![图片](https://github.com/user-attachments/assets/cb5c3f72-c856-419d-8e54-3968182f8ae0)
不知道是不是系统版本引起的。
