### ISSUE TITLE
ModuleBasic.out 测试 mnn 模型，load 模型阶段，报错 “PipelineModule:: Can't find enough output from the model, finded is”

### ISSUE THREAD

**Issue by dearwind153** [alibaba/MNN#2911]
### 1. 平台 linux x86_64 centos

    MNN version 2.9.0
    mnn  模型为单输入，多输出

### 2. testMNNFromOnnx.py 生成测试数据正常

    inputs:
    encoder_outputs
    onnx/
    outputs:
    onnx/memory.txt (245, 1, 512)
    onnx/
    onnx/init_query.txt (1, 256)
    onnx/
    onnx/hid.txt (2, 1, 1024)
    onnx/
    onnx/cell.txt (2, 1, 1024)
    onnx/
    ./MNNConvert not exist in this path. Use pymnn instead of C++ to test
    The device support i8sdot:0, support fp16:0, support i8mm: 0
    The device support i8sdot:0, support fp16:0, support i8mm: 0
    Start to Convert Other Model Format To MNN Model..., target version: 2.8
    [19:54:13] :46: ONNX Model ir version: 7
    [19:54:13] :47: ONNX Model opset version: 14
    [19:54:13] :142: Check it out ==> /memory_layer/GRU_output_0 has empty input, the index is 4
    Start to Optimize the MNN Net...
    [19:54:13] :68:  OnnxSequenceGRUMerge:  W shape:{1, 1536, 1024}; R shape: {1, 1536, 512}, inputs num:6, outputs num:2
    inputTensors : [ encoder_outputs, ]
    outputTensors: [ cell, hid, init_query, memory, ]
    Converted Success!
    Check convert result by onnx, thredhold is 0.01

### 3. ModuleBasic.out 测试 crash 

 ModuleBasic.out model.mnn onnx  0 0 1 1 0

    Test model.mnn from input info: onnx
    encoder_outputs
    output: memory
    output: init_query
    output: hid
    output: cell
    Use extra forward type: 0
    precision=0 in main, 205 
    memory=0 in main, 206 
    cacheFileName=s .tempcache in main, 207 
    The device support i8sdot:0, support fp16:0, support i8mm: 0
    Can't open file:.tempcache
    Load Cache file error.
### PipelineModule:: Can't find enough output from the model, finded is:
    [ cell ] [ init_query ] [ memory ]
    main, 256, cost time: 18.879002 ms
    Run for 0 time
    Segmentation fault (core dumped)

### 4. GetMNNInfo 也是 crash 

 GetMNNInfo model.mnn

### PipelineModule:: Can't find enough output from the model, finded is:
    [ cell ] [ init_query ] [ memory ] 
    load model done!
    Model default dimensionFormat is NCHW
    Model Inputs:
    [ encoder_outputs ]: dimensionFormat: NCHW, size: [ 1,-1,512 ], type is float
    Model Outputs:
    [ cell ]
    [ hid ]
    [ init_query ]
    [ memory ]
    Model Version: 2.9.0

**Comment by jxt1234** [comment]
有可能是有输入=输出的情况出现，MNNConvert 时加上 --optimizeLevel=0 试试

**Comment by jxt1234** [comment]
“Can't find enough output from the model” 这个是提示无法找到所有指定输出，去掉 hid 这个输出试下

**Comment by dearwind153** [comment]
@jxt1234 多谢，问题解决了哈，onnx 导出时，opset_version 设置为 11 正常了
