### ISSUE TITLE
编译android release的libMNN.so的时候怎样可以保留带symbol的so，方便上线定位crash

### ISSUE THREAD

**Issue by whuzk** [alibaba/MNN#2914]
目前通过在project/android下编译处理的出来的so，只有无符号的libMNN.so和libMNN_Express.so；需要如何修改可以编译选项可以，同时编译出发版用的无符号的so，以及用来定位线上发版MNN导致的crash的带符号的so库

**Comment by jxt1234** [comment]
Debug 版本建议用 Android Studio 打开 project/android/build.gradle 编译

**Comment by jxt1234** [comment]
也可以试试把mnn CMakeLists.txt 这几行去掉
if(MNN_BUILD_FOR_ANDROID_COMMAND)
                set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -s")
                set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pie -fPIE -s")
                set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--gc-sections")
end()

**Comment by whuzk** [comment]
> 用于发布的版本建议用 Android Studio 打开 project/android/build.gradle 编译

这个方法确实可以拿到obj
