### ISSUE TITLE
C++ multi threads call error.

### ISSUE THREAD

**Issue by AminGeng** [alibaba/MNN#2915]
when I use 1 thread to infer, it runs well. >1 threads, error occur!
All my test information(code, model, image, issue) is in https://github.com/AminGeng/yolov8-demo

**Comment by weikangqi** [comment]
This is not mnn's problem
![QQ截图20240615135847](https://github.com/alibaba/MNN/assets/107830635/6393c270-4e92-4d94-8ee2-d67ab90a1556)

**Comment by AminGeng** [comment]
Can you try using a larger thread count, such as 8, and run the program for a longer duration? This error does not always occur, but the likelihood increases with a higher number of threads. I have tested it on Ubuntu 16 (GCC 5.4), Ubuntu 18 (GCC 7.5), and Ubuntu 22.04 (WSL with GCC 11.4), and the issue persists across all versions.”







At 2024-06-15 13:59:30, "韦康琦" ***@***.***> wrote:

This is not mnn's problem
QQ.20240615135847.png (view on web)
