### ISSUE TITLE
ONNX转换成MNN模型结果错误

### ISSUE THREAD

**Issue by vkeep** [alibaba/MNN#2916]
使用MNN 2.8版本源码编译的转换工具在mac平台，很多onnx转换都正常，但是我现在的onnx 模型转换结果错误。 

使用../tools/script/testMNNFromOnnx.py 测试onnx 模型转换结果，输出的值和onnx不一致

---------
TESTERROR enh value error : absMaxV:1.214276 - DiffMax 1.390584
---------

 我尝试上传我的onnx文件

**Comment by vkeep** [comment]
https://github.com/Xiaobin-Rong/gtcrn/blob/main/stream/onnx_models/gtcrn_simple.onnx
使用上述onnx模型报错

**Comment by vkeep** [comment]
https://github.com/Xiaobin-Rong/gtcrn/blob/main/stream/onnx_models/gtcrn_simple.onnx 使用上述模型报错

**Comment by vkeep** [comment]
模型中有些没有训练的fc层是稀疏化矩阵，使用--detectSparseSpeedUp=0 转换，也存在差异

**Comment by jxt1234** [comment]
ok , 已经复现，排查中

**Comment by vkeep** [comment]
我运行debug 工具：
Error is between  Add_1715  and  ConvTranspose_1716

请问如何debug，是不是ConvTranspose 这个操作存在bug？

**Comment by jxt1234** [comment]
ConvTranspose with group + BN / Scale 的合并有 bug ，内部已经修复，等待同步中
