### ISSUE TITLE
Error in MNN inference process when called by multiple C++ threads

### ISSUE THREAD

**Issue by AminGeng** [alibaba/MNN#2918]
when I use 1 thread to infer, it runs well. >1 threads, like 8, error occur! 

This error does not always occur, but the likelihood increases with a higher number of threads. I have tested it on Ubuntu 16 (GCC 5.4), Ubuntu 18 (GCC 7.5), and Ubuntu 22.04 (WSL with GCC 11.4), and the issue persists across all versions.”

details in  https://github.com/AminGeng/yolov8-demo. please try `./yolov8_demo 8`

error like
```
### box: {31.570251, 37.311340, 299.422791, 339.640869}, class_idx: 0, score: 0.425075
### box: {4.736572, 6.945740, 628.629761, 620.160950}, class_idx: 74, score: 0.306633
Segmentation fault (core dumped)
```

```
*** Error in `./yolov8_demo': double free or corruption (fasttop): 0x00007f81980069a0 ***
...
Aborted (core dumped)
```

**Comment by jxt1234** [comment]
MNN 版本是? 编译选项和运行环境是?

**Comment by jxt1234** [comment]
MNN 版本是? 编译选项和运行环境是?

**Comment by AminGeng** [comment]
相关信息都在 https://github.com/AminGeng/yolov8-demo 中. 如下:
# MNN
- clone MNN Rep date: 2024/06/14
- compiled on ubuntu16(x64) with gcc5.4
- compile command
    ```shell
    git clone https://github.com/alibaba/MNN.git
    cd MNN
    mkdir build && cd build
    cmake -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_BUILD_SHARED_LIBS=OFF ..
    make -j4
    ```
- copy lib and files by `sh` [copy_MNN.sh](copy_MNN.sh) after compiled

# yolov8_demo
[yolov8_demo.cpp](src/yolov8_demo.cpp): 
- original codes copy from https://github.com/wangzhaode/mnn-yolo/blob/main/cpp/yolov8_demo.cpp
- I convert model load and infer process into `class`
- [yolov8n.mnn](yolov8n.mnn) download url: https://github.com/wangzhaode/mnn-yolov8/releases/download/v1.0/yolov8n.mnn 

# compile
```
mkdir build && cd build
cmake ..
make -j4
```

**Comment by AminGeng** [comment]
refer this: https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id6
