### ISSUE TITLE
error with armv7 in Hi3751V352 chip

### ISSUE THREAD

**Issue by Myzhencai** [alibaba/MNN#2926]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows + wsl +ubuntu18.04

target：armv7+linux 
chip:Hi3751V352

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
arm-linux-gnueabihf-g++ 7.5
arm-linux-gnueabihf-gcc 7.5
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
 cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=armv7 -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++ -DCMAKE_INSTALL_PREFIX=../installgpu -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_OPENMP=ON -DMNN_OPENCL=ON -DMNN_OPENGL=ON -DMNN_VULKAN=ON

# 编译日志:
# Build Log:
![image](https://github.com/alibaba/MNN/assets/21084423/76c82f72-f424-410b-87c7-a4c710d56e6f)

```
粘贴在这里
Paste log here or pastebin
```
I put the result .so to mnn-yolo libs dir;
![image](https://github.com/alibaba/MNN/assets/21084423/63306ffb-c8e7-47ce-8fca-5b54fbb907a6)

then I want to use opengl with MNN but I get the result like this 👍 
![image](https://github.com/alibaba/MNN/assets/21084423/a627f7f9-4211-4fe6-b6be-0e268356c9fa)

it seems  i Have the libs file in the /system/lib or current path ,I am really confused ,anyone can help thanks a lot in adavance :-)

**Comment by jxt1234** [comment]
MNN_OPENGL  is depercerated. It's recommended to use vulkan or opencl instead of opengl.

**Comment by Myzhencai** [comment]
@jxt1234  thanks  a lot :-)  I will try vulkan :-)
