### ISSUE TITLE
https://github.com/wangzhaode/llm-export 导出Qwen-1_8B-Chat生成的MNN，在andoid 中输出失败的问题

### ISSUE THREAD

**Issue by sunnyzhaohui** [alibaba/MNN#2927]
1：前期准备：
    1.1：mnn-llm： https://github.com/wangzhaode/mnn-llm
    1.2：使用工具：https://github.com/wangzhaode/llm-export  ，master 分支
    1.3：Qwen-1_8B-Chat 模型自己下载的，魔塔下载位置：https://modelscope.cn/models/qwen/Qwen-1_8B-Chat/files
    1.4：python 版本：Python 3.8.19
    1.5：platform linux

2：执行命令：
python llm_export.py \
        --path ../../modes/Qwen-1_8B-Chat \
        --type Qwen-1_8B-Chat \
        --export_split \
        --export_token  \
        --export_mnn \
        --mnn_path  ./qwen18b-chat-mnn \
        --onnx_path ./qwen18b-chat-onnx \
        --embed_bin \
        --embed_bf16

3:执行结果
    3.1 生成ONNX目录下文件列表：
	block_0.onnx   block_13.onnx  block_17.onnx  block_20.onnx  block_2.onnx  block_6.onnx  embeddings_bf16.bin
	block_10.onnx  block_14.onnx  block_18.onnx  block_21.onnx  block_3.onnx  block_7.onnx  llm_config.json
	block_11.onnx  block_15.onnx  block_19.onnx  block_22.onnx  block_4.onnx  block_8.onnx  lm.onnx
	block_12.onnx  block_16.onnx  block_1.onnx   block_23.onnx  block_5.onnx  block_9.onnx  tokenizer.txt

3.2 生成MNN目录下文件列表：
       block_0.mnn   block_12.mnn  block_15.mnn  block_18.mnn  block_20.mnn  block_23.mnn  block_4.mnn  block_7.mnn
       lm.mnn
	block_10.mnn  block_13.mnn  block_16.mnn  block_19.mnn  block_21.mnn  block_2.mnn   block_5.mnn  block_8.mnn
	block_11.mnn  block_14.mnn  block_17.mnn  block_1.mnn   block_22.mnn  block_3.mnn   block_6.mnn  block_9.mnn

3.3 发现一点问题： 在MNN目录下，没有embeddings_bf16.bin， tokenizer.txt. 我就从ONNX目录下把这两个拷贝过来了。这是个问题吗？
	

	
4: 在mnn-llm的android demo 里（https://github.com/wangzhaode/mnn-llm/tree/master/android） 使用自己刚刚导出的MNN文件。 

5：android 编译执行，MNN模型下载，加载和初始化都没有问题。但是输出有问题。
 
    
结果：输入字符串”今天的天气怎么样？“，没有任何输出。

请帮助看看，是什么问题导致？

**Comment by wangzhaode** [comment]
建议导出时不要使用split的模型了，将`--export_split`修改为`--export`

**Comment by wangzhaode** [comment]
> 发现一点问题： 在MNN目录下，没有embeddings_bf16.bin， tokenizer.txt.

这个没有问题，现在都放在onnx里了，拷贝一下就好了

**Comment by sunnyzhaohui** [comment]
Qwen-1_8B-Chat 模型下面已经有了一个config.json,内容如下， 我是不是把你上面的内容加到下面就行?
==========
{
  "architectures": [
    "QWenLMHeadModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_qwen.QWenConfig",
    "AutoModelForCausalLM": "modeling_qwen.QWenLMHeadModel"
  },
  "attn_dropout_prob": 0.0,
  "bf16": false,
  "emb_dropout_prob": 0.0,
  "fp16": false,
  "fp32": false,
  "hidden_size": 2048,
  "intermediate_size": 11008,
  "initializer_range": 0.02,
  "kv_channels": 128,
  "layer_norm_epsilon": 1e-06,
  "max_position_embeddings": 8192,
  "model_type": "qwen",
  "no_bias": true,
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "onnx_safe": null,
  "rotary_emb_base": 10000,
  "rotary_pct": 1.0,
  "scale_attn_weights": true,
  "seq_length": 8192,
  "tie_word_embeddings": false,
  "tokenizer_class": "QWenTokenizer",
  "transformers_version": "4.32.0",
  "use_cache": true,
  "use_dynamic_ntk": true,
  "use_flash_attn": "auto",
  "use_logn_attn": true,
  "vocab_size": 151936
}

**Comment by sunnyzhaohui** [comment]
我试了第二种方式，不使用分段的模型：
python llm_export.py \
        --path ../../modes/Qwen-1_8B-Chat \
	--type Qwen-1_8B-Chat \
        --export \
        --export_token  \
        --export_mnn \
        --mnn_path  ./qwen18b-chat-mnn \
	--onnx_path ./qwen18b-chat-onnx \
	--embed_bin \
	--embed_bf16 
	
结果：1）qwen18b-chat-mnn 文件夹下只有2个文件：
          llm.mnn  llm.mnn.weight
        2）qwen18b-chat-onnx 文件夹下只有4个文件
         llm_config.json  llm.onnx  llm.onnx.data  tokenizer.txt
      
缺少：  embeddings_bf16.bin 文件，对吗？
我llm_export.py 命令工具使用的是 ： https://github.com/wangzhaode/llm-export  对吗？

**Comment by wangzhaode** [comment]
> 我试了第二种方式，不使用分段的模型： python llm_export.py --path ../../modes/Qwen-1_8B-Chat --type Qwen-1_8B-Chat --export --export_token --export_mnn --mnn_path ./qwen18b-chat-mnn --onnx_path ./qwen18b-chat-onnx --embed_bin --embed_bf16
> 
> 结果：1）qwen18b-chat-mnn 文件夹下只有2个文件： llm.mnn llm.mnn.weight 2）qwen18b-chat-onnx 文件夹下只有4个文件 llm_config.json llm.onnx llm.onnx.data tokenizer.txt
> 
> 缺少： embeddings_bf16.bin 文件，对吗？ 我llm_export.py 命令工具使用的是 ： https://github.com/wangzhaode/llm-export 对吗？ 好像MNN仓库下也有llm_export.py 命令工具，到底用哪一个？

没有加 `--export_embed`

**Comment by sunnyzhaohui** [comment]
在钉钉中，讨论交流了，建议用MNN仓库下llm_export.py， 建议不用split 分片方式

**Comment by sunnyzhaohui** [comment]
加上--export_embed 参数之后，确实能够生成4个文件
embeddings_bf16.bin
llm.mnn
llm.mnn.weight
tokenizer.txt

问题是， https://github.com/wangzhaode/llm-export 仓库和 MNN仓库 生成的文件llm.mnn.weight 大小不一样。
/llm-export 的文件大小：
-rw-rw-r-- 1 cmdc2023 cmdc2023 622329856 Jun 26 18:02 embeddings_bf16.bin
-rw-rw-r-- 1 cmdc2023 cmdc2023   3251184 Jun 26 18:00 llm.mnn
-rw-rw-r-- 1 cmdc2023 cmdc2023 768407146 Jun 26 18:00 llm.mnn.weight
-rw-rw-r-- 1 cmdc2023 cmdc2023   1616272 Jun 26 18:02 tokenizer.txt

MNN 的文件大小：
-rw-r--r-- 1 root     root     622329856 Jun 26 15:46 embeddings_bf16.bin
-rw-rw-r-- 1 cmdc2023 cmdc2023   3251184 Jun 26 15:37 llm.mnn
-rw-rw-r-- 1 cmdc2023 cmdc2023 765759594 Jun 26 15:37 llm.mnn.weight
-rw-r--r-- 1 root     root       1616272 Jun 26 15:46 tokenizer.txt

**Comment by sunnyzhaohui** [comment]
把这四个文件加载到安装apk中，运行是崩溃
22194 22308 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 22308 (Thread-7),
