### ISSUE TITLE
Get output size:0 x 0 x 0

### ISSUE THREAD

**Issue by KanaSukita** [alibaba/MNN#293]
Thank you for the great framework!

I am trying to covert mobilenetV2-deeplabV3 trained on cityscapes from [tensorflow](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) to MNN. When I used the original input size(2049 x 1025) I got correct output in MNN. But after I shrink the input size to 641 x 361 following the steps in [Wenzhao-Xiang](https://github.com/Wenzhao-Xiang/Wenzhao-Xiang.github.io/blob/962ff2557fa74791ed878e772a1feef715b33f9d/intel/webml-examples/examples/semantic_segmentation/model/README.md), I can produce the correct result in tensorflow, but the output size in MNN is 0 x 0 x 0. 

The command I use is :
./MNNConvert -f TF --modelFile mbv2_deeplabv3_641_361_stripped.pb \
--MNNModel deeplabv3_mnv2_cityscapes_train.mnn --bizCode MNN

**Comment by jiarenyf** [comment]
@KanaSukita Did you solve this problem ?

**Comment by jiarenyf** [comment]
@KanaSukita Did you solve this problem ?

**Comment by gordinmitya** [comment]
@KanaSukita How did you solved the problem? xD
