### ISSUE TITLE
CPU后端`Tanh`算子在Windows平台Release编译情况下推理结果出错

### ISSUE THREAD

**Issue by juju812** [alibaba/MNN#2935]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Windows
MSVC版本`v141`（`Visual Studio 15 2017`）

# Github版本:
# Github Version:

2.8.1（经验证2.9.1下也会出现）

# 编译方式:
# Compiling Method

```
cmake "%MNN_ROOT_DIR%" -G Ninja ^
-DCMAKE_BUILD_TYPE=RelWithDebInfo ^
-DMNN_USE_SSE=OFF ^
-DMNN_BUILD_TEST=ON ^
-DMNN_BUILD_SHARED_LIBS=OFF ^
-DMNN_SEP_BUILD=OFF
```

CPU后端`Tanh`算子在Windows平台Release编译情况下推理结果出错，Debug下结果正确。暂时通过使用弃用的`tanhf_poly`修复。如何进一步确认问题？

```cpp
// source/backend/cpu/compute/CommonOptFunction.cpp

void MNNTanh(float* dst, const float* src, size_t dataSize) {
#ifdef _MSC_VER
    // Origin Code
    for (int i = 0; i < dataSize; i++) {
        // outputData[i] = 1 - 2 / (expf(2 * inputData[i]) + 1);
        dst[i] = tanhf_poly(src[i]);
    }
#else
    float offset[2] = {
        -2.0f,
        0.0f
    };
    MNNExp(dst, src, offset, dataSize);
    for (int i = 0; i < dataSize; i++) {
        // outputData[i] = 1 - 2 / (expf(2 * inputData[i]) + 1);
        auto expX2 = dst[i];
        dst[i] = (1.0f - expX2) / (1.0f + expX2);
    }
#endif
}
```

**Comment by Ruoxxi** [comment]
你好，我也遇到了相似的问题，请问你最后找到出现问题的原因了吗

**Comment by yizhaoyanbo** [comment]
MNN在MSVC编译器下，使用了/fp:fast编译选项。
在release模式下，编译器在tanH中计算 1 / (1 + expX2)时，会对浮点除法做优化。通过查看汇编代码是采用了牛顿迭代近似算法，在tanH输入很小的情况下会引入近似误差。而debug模式下不会用牛顿迭代近似，所以结果正常。
![image](https://github.com/user-attachments/assets/931fae25-e10c-4f93-9845-c677249bc0b3)

可以尝试将编译选项改为**/fp:precise**来保障编译器执行更精确的浮点计算。
