### ISSUE TITLE
opencl matmul运行crash

### ISSUE THREAD

**Issue by jamesdod** [alibaba/MNN#2946]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
x86_64 linux,pc

# Github版本:
最新版本

# 编译方式:
cmakelists.txt打开opencl，编译

# 现象
1.使用opencl推理，如果添加了torch.matmul就会crash，是两个二维矩阵的相乘(16x4 matmul 4x216)。去掉matmul运行正常
2.使用cpu推理，有无matmul都正常运行，没有crash

# 问题
1.请问这是符合预期的么，是opencl不支持matmul算子么
2.torch里有其他替代matmul的函数，并且可以转成mnn的么

**Comment by Qxinyu** [comment]
有出问题的模型吗，运行用的gpu是什么的？

**Comment by Qxinyu** [comment]
opencl支持matmul算子，应该是有什么bug

**Comment by jamesdod** [comment]
> 有出问题的模型吗，运行用的gpu是什么的？

rtx 3060,mnn已经用了挺长一段时间，第一次碰到这个问题

**Comment by jamesdod** [comment]
附近包括onnx和转换的mnn文件，使用`MNNV2Basic matmul.mnn 1 0 0`没问题，使用`MNNV2Basic matmul.mnn 1 0 3`会crash，验证过去掉troch.matmul就都可以正常运行了

**Comment by Qxinyu** [comment]
现在看起来是mnn不支持多输入的group大于1卷积导致的，你测试cpu结果是正确的吗

**Comment by jamesdod** [comment]
1. 是指mnn不论什么推理类型，都不支持batch大于1时的多group卷积么。如果是，这个有计划支持么
2. opencl crash了，cpu就没有确认结果了，最终不会用cpu跑的

**Comment by Qxinyu** [comment]
没有，是opencl不支持权重也作为输入，并且group大于1的卷积，于batch无关，这个后续会支持。

**Comment by jxt1234** [comment]
最新版本已经支持
