### ISSUE TITLE
在linux上进行编译时出现错误

### ISSUE THREAD

**Issue by jimwang118** [alibaba/MNN#2950]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux

# Github版本:
# Github Version:
1.1.0

# 编译方式:
# Compiling Method
git clone [vcpkg](https://github.com/microsoft/vcpkg.git)
.\bootstrap-vcpkg.bat
./vcpkg install mnn[core,opencl]:x64-linux 

# 编译日志:
# Build Log:

[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/16106121/install-x64-linux-dbg-out.log)

**Comment by Qxinyu** [comment]
要不试下最新版本的会有问题吗

**Comment by jxt1234** [comment]
在最新版本上测试吧
