### ISSUE TITLE
efficientvit模型fp16精度不对

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#2953]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Intel

# Github版本: MNN2.9.1

模型fp32精度正常，fp16模型精度降太多。

**Comment by v0jiuqi** [comment]
那可能这个模型就没办法用fp16去跑

**Comment by ppl21847** [comment]
> 那可能这个模型就没办法用fp16去跑

那有计划支持吗？

**Comment by v0jiuqi** [comment]
> > 那可能这个模型就没办法用fp16去跑
> 
> 那有计划支持吗？

不是我们支不支持。。。。是你模型本身就是不能用fp16...

**Comment by jxt1234** [comment]
可以更新到 2.9.3 ，用 --weightQuantBits=8 量化 mnn 模型后，用 mnn_low_memory 去跑

**Comment by hajungong007** [comment]
> 可以更新到 2.9.3 ，用 --weightQuantBits=8 量化 mnn 模型后，用 mnn_low_memory 去跑

onnx 的opset设置是多少
