### ISSUE TITLE
onnx模型转mnn后，onnx推理正常，mnn输出异常

### ISSUE THREAD

**Issue by haikefeng** [alibaba/MNN#2959]
onnx模型正常，推理结果输出也正常，另外使用testMNNFromOnnx.py文件对onnx模型进行测试，显示也TEST_SUCCESS。
将onnx模型转mnn过程中间没有警告和错误，显示Converted Success。
为什么使用python mnn对转换后的mnn模型推理输出异常，同时发现对mnn模型进行加载后，打印输出的shape都不对，什么原因。

**Comment by haikefeng** [comment]
这个是使用testMNNFromOnnx.py测试输出结果，命令行python ../tools/script/testMNNFromOnnx.py model.onnx
Dir exist
onnx/test.onnx
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['output', 'state_0', 'state_1', 'state_2', 'state_3', 'state_4', 'state_5', 'state_6', 'state_7', 'state_8', 'state_9', 'state_10', 'state_11', 'state_12', 'state_13', 'state_14', 'state_15', 'state_16', 'state_17', 'state_18', 'state_19', 'state_20', 'state_21', 'state_22', 'state_23', 'state_24', 'state_25', 'state_26', 'state_27', 'state_28', 'state_29', 'state_30', 'state_31', 'state_32', 'state_33', 'state_34', 'state_35']
inputs:
input
onnx/
state_0.1
onnx/
state_1.1
onnx/
state_2.1
onnx/
state_3.1
onnx/
state_4.1
onnx/
state_5.1
onnx/
state_6.1
onnx/
state_7.1
onnx/
state_8.1
onnx/
state_9.1
onnx/
state_10.1
onnx/
state_11.1
onnx/
state_12.1
onnx/
state_13.1
onnx/
state_14.1
onnx/
state_15.1
onnx/
state_16.1
onnx/
state_17.1
onnx/
state_18.1
onnx/
state_19.1
onnx/
state_20.1
onnx/
state_21.1
onnx/
state_22.1
onnx/
state_23.1
onnx/
state_24.1
onnx/
state_25.1
onnx/
state_26.1
onnx/
state_27.1
onnx/
state_28.1
onnx/
state_29.1
onnx/
state_30.1
onnx/
state_31.1
onnx/
state_32.1
onnx/
state_33.1
onnx/
state_34.1
onnx/
state_35.1
onnx/
outputs:
onnx/output.txt (1, 1, 256)
onnx/
onnx/state_0.txt (1, 1, 6)
onnx/
onnx/state_1.txt (1, 8, 2)
onnx/
onnx/state_2.txt (1, 8, 6)
onnx/
onnx/state_3.txt (1, 8, 18)
onnx/
onnx/state_4.txt (1, 8, 3)
onnx/
onnx/state_5.txt (1, 16, 2)
onnx/
onnx/state_6.txt (1, 16, 6)
onnx/
onnx/state_7.txt (1, 16, 18)
onnx/
onnx/state_8.txt (1, 16, 3)
onnx/
onnx/state_9.txt (1, 32, 2)
onnx/
onnx/state_10.txt (1, 32, 6)
onnx/
onnx/state_11.txt (1, 32, 18)
onnx/
onnx/state_12.txt (1, 32, 15)
onnx/
onnx/state_13.txt (1, 64, 2)
onnx/
onnx/state_14.txt (1, 64, 6)
onnx/
onnx/state_15.txt (1, 64, 18)
onnx/
onnx/state_16.txt (1, 64, 15)
onnx/
onnx/state_17.txt (1, 128, 6)
onnx/
onnx/state_18.txt (1, 32, 6)
onnx/
onnx/state_19.txt (1, 128, 8)
onnx/
onnx/state_20.txt (1, 64, 2)
onnx/
onnx/state_21.txt (1, 64, 6)
onnx/
onnx/state_22.txt (1, 64, 18)
onnx/
onnx/state_23.txt (1, 64, 8)
onnx/
onnx/state_24.txt (1, 32, 2)
onnx/
onnx/state_25.txt (1, 32, 6)
onnx/
onnx/state_26.txt (1, 32, 18)
onnx/
onnx/state_27.txt (1, 32, 2)
onnx/
onnx/state_28.txt (1, 16, 2)
onnx/
onnx/state_29.txt (1, 16, 6)
onnx/
onnx/state_30.txt (1, 16, 18)
onnx/
onnx/state_31.txt (1, 16, 2)
onnx/
onnx/state_32.txt (1, 8, 2)
onnx/
onnx/state_33.txt (1, 8, 6)
onnx/
onnx/state_34.txt (1, 8, 18)
onnx/
onnx/state_35.txt (1, 8, 6)
onnx/
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.9
[09:37:29] /data/SpeechFix/mnnprojects/MNN/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[09:37:29] /data/SpeechFix/mnnprojects/MNN/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 14
Start to Optimize the MNN Net...
inputTensors : [ state_35.1, state_31.1, state_27.1, state_23.1, state_19.1, state_18.1, state_17.1, state_16.1, state_12.1, state_8.1, state_4.1, state_0.1, input, state_1.1, state_2.1, state_3.1, state_5.1, state_6.1, state_7.1, state_9.1, state_10.1, state_11.1, state_13.1, state_14.1, state_15.1, state_20.1, state_21.1, state_22.1, state_24.1, state_25.1, state_26.1, state_28.1, state_29.1, state_30.1, state_32.1, state_33.1, state_34.1, ]
outputTensors: [ output, state_0, state_1, state_10, state_11, state_12, state_13, state_14, state_15, state_16, state_17, state_18, state_19, state_2, state_20, state_21, state_22, state_23, state_24, state_25, state_26, state_27, state_28, state_29, state_3, state_30, state_31, state_32, state_33, state_34, state_35, state_4, state_5, state_6, state_7, state_8, state_9, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
input
state_0.1
state_1.1
state_2.1
state_3.1
state_4.1
state_5.1
state_6.1
state_7.1
state_8.1
state_9.1
state_10.1
state_11.1
state_12.1
state_13.1
state_14.1
state_15.1
state_16.1
state_17.1
state_18.1
state_19.1
state_20.1
state_21.1
state_22.1
state_23.1
state_24.1
state_25.1
state_26.1
state_27.1
state_28.1
state_29.1
state_30.1
state_31.1
state_32.1
state_33.1
state_34.1
state_35.1
output: output
output: state_0
output: state_1
output: state_2
output: state_3
output: state_4
output: state_5
output: state_6
output: state_7
output: state_8
output: state_9
output: state_10
output: state_11
output: state_12
output: state_13
output: state_14
output: state_15
output: state_16
output: state_17
output: state_18
output: state_19
output: state_20
output: state_21
output: state_22
output: state_23
output: state_24
output: state_25
output: state_26
output: state_27
output: state_28
output: state_29
output: state_30
output: state_31
output: state_32
output: state_33
output: state_34
output: state_35
output: (1, 1, 256, )
state_0: (1, 1, 6, )
state_1: (1, 8, 2, )
state_2: (1, 8, 6, )
state_3: (1, 8, 18, )
state_4: (1, 8, 3, )
state_5: (1, 16, 2, )
state_6: (1, 16, 6, )
state_7: (1, 16, 18, )
state_8: (1, 16, 3, )
state_9: (1, 32, 2, )
state_10: (1, 32, 6, )
state_11: (1, 32, 18, )
state_12: (1, 32, 15, )
state_13: (1, 64, 2, )
state_14: (1, 64, 6, )
state_15: (1, 64, 18, )
state_16: (1, 64, 15, )
state_17: (1, 128, 6, )
state_18: (1, 32, 6, )
state_19: (1, 128, 8, )
state_20: (1, 64, 2, )
state_21: (1, 64, 6, )
state_22: (1, 64, 18, )
state_23: (1, 64, 8, )
state_24: (1, 32, 2, )
state_25: (1, 32, 6, )
state_26: (1, 32, 18, )
state_27: (1, 32, 2, )
state_28: (1, 16, 2, )
state_29: (1, 16, 6, )
state_30: (1, 16, 18, )
state_31: (1, 16, 2, )
state_32: (1, 8, 2, )
state_33: (1, 8, 6, )
state_34: (1, 8, 18, )
state_35: (1, 8, 6, )
TEST_SUCCESS

**Comment by haikefeng** [comment]
这个是模型转换命令行及输出
./MNNConvert -f ONNX --modelFile model.onnx --MNNModel model.mnn --bizCode biz 
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.9
[09:53:48] /data/SpeechFix/mnnprojects/MNN/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[09:53:48] /data/SpeechFix/mnnprojects/MNN/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 14
Start to Optimize the MNN Net...
inputTensors : [ state_35.1, state_31.1, state_27.1, state_23.1, state_19.1, state_18.1, state_17.1, state_16.1, state_12.1, state_8.1, state_4.1, state_0.1, input, state_1.1, state_2.1, state_3.1, state_5.1, state_6.1, state_7.1, state_9.1, state_10.1, state_11.1, state_13.1, state_14.1, state_15.1, state_20.1, state_21.1, state_22.1, state_24.1, state_25.1, state_26.1, state_28.1, state_29.1, state_30.1, state_32.1, state_33.1, state_34.1, ]
outputTensors: [ output, state_0, state_1, state_10, state_11, state_12, state_13, state_14, state_15, state_16, state_17, state_18, state_19, state_2, state_20, state_21, state_22, state_23, state_24, state_25, state_26, state_27, state_28, state_29, state_3, state_30, state_31, state_32, state_33, state_34, state_35, state_4, state_5, state_6, state_7, state_8, state_9, ]
Converted Success!

这个是使用python mnn对模型进行加载，然后打印加载模型后输入、输出shape代码，以及打印的日志
        interpreter = MNN.Interpreter("model.mnn")
        session = interpreter.createSession()
        input_names = interpreter.getSessionInputAll(session)
        output_names = interpreter.getSessionOutputAll(session)

    print("输入张量形状:")
    for name, tensor in input_names.items():
        print_tensor_shape(tensor, name)

    print("输出张量形状:")
    for name, tensor in output_names.items():
        print_tensor_shape(tensor, name)

此段代码为加载mnn模型后，打印了模型输入输出shape，打印的shape日志如下：
输入张量形状:
input: (1, 1, -1)
state_0.1: (1, 1, 6)
state_1.1: (1, 8, 2)
state_10.1: (1, 32, 6)
state_11.1: (1, 32, 18)
state_12.1: (1, 32, 15)
state_13.1: (1, 64, 2)
state_14.1: (1, 64, 6)
state_15.1: (1, 64, 18)
state_16.1: (1, 64, 15)
state_17.1: (1, 128, 6)
state_18.1: (1, 32, 6)
state_19.1: (1, 128, 8)
state_2.1: (1, 8, 6)
state_20.1: (1, 64, 2)
state_21.1: (1, 64, 6)
state_22.1: (1, 64, 18)
state_23.1: (1, 64, 8)
state_24.1: (1, 32, 2)
state_25.1: (1, 32, 6)
state_26.1: (1, 32, 18)
state_27.1: (1, 32, 2)
state_28.1: (1, 16, 2)
state_29.1: (1, 16, 6)
state_3.1: (1, 8, 18)
state_30.1: (1, 16, 18)
state_31.1: (1, 16, 2)
state_32.1: (1, 8, 2)
state_33.1: (1, 8, 6)
state_34.1: (1, 8, 18)
state_35.1: (1, 8, 6)
state_4.1: (1, 8, 3)
state_5.1: (1, 16, 2)
state_6.1: (1, 16, 6)
state_7.1: (1, 16, 18)
state_8.1: (1, 16, 3)
state_9.1: (1, 32, 2)
输出张量形状:
output: (0, 0, 0, 0)
state_0: (0, 0, 0, 0)
state_1: (0, 0, 0, 0)
state_10: (0, 0, 0, 0)
state_11: (0, 0, 0, 0)
state_12: (0, 0, 0, 0)
state_13: (0, 0, 0, 0)
state_14: (0, 0, 0, 0)
state_15: (0, 0, 0, 0)
state_16: (0, 0, 0, 0)
state_17: (0, 0, 0, 0)
state_18: (0, 0, 0, 0)
state_19: (0, 0, 0, 0)
state_2: (0, 0, 0, 0)
state_20: (0, 0, 0, 0)
state_21: (0, 0, 0, 0)
state_22: (0, 0, 0, 0)
state_23: (0, 0, 0, 0)
state_24: (0, 0, 0, 0)
state_25: (0, 0, 0, 0)
state_26: (0, 0, 0, 0)
state_27: (0, 0, 0, 0)
state_28: (0, 0, 0, 0)
state_29: (0, 0, 0, 0)
state_3: (0, 0, 0, 0)
state_30: (0, 0, 0, 0)
state_31: (0, 0, 0, 0)
state_32: (0, 0, 0, 0)
state_33: (0, 0, 0, 0)
state_34: (0, 0, 0, 0)
state_35: (0, 0, 0, 0)
state_4: (0, 0, 0, 0)
state_5: (0, 0, 0, 0)
state_6: (0, 0, 0, 0)
state_7: (0, 0, 0, 0)
state_8: (0, 0, 0, 0)
state_9: (0, 0, 0, 0)

**Comment by haikefeng** [comment]
从打印的shape上看，输入应该是input: (1, 1, 256)，但打印的为input: (1, 1, -1)，输入的state都是正确的。打印的输出output和state的shape全都不正确

**Comment by v0jiuqi** [comment]
用 testMNNFromOnnx.py脚本验证是 Test success，那说明转模型没有问题。打印的input shape是 (1,1,-1)表示最后一维是动态维度，需要你去指定的。

**Comment by haikefeng** [comment]
> 用 testMNNFromOnnx.py脚本验证是 Test success，那说明转模型没有问题。打印的input shape是 (1,1,-1)表示最后一维是动态维度，需要你去指定的。

嗯，使用mnn模型推理，输入没有问题。获取的输出维度都是有问题，不正确的

**Comment by jxt1234** [comment]
你 python 代码是怎么样的，建议使用 module api 加载运行模型

**Comment by haikefeng** [comment]
转onnx模型时，不使用动态轴，最后再转mnn，可以正常使用
