### ISSUE TITLE
新版本量化工具得出的量化模型不可用

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#296]
有之前已经转好的mnn模型mobileface.mnn
先后使用之前版本、更新版本的量化工具进行量化，preprocessConfig.json为同一个文件
* 旧版本的使用过程
![image](https://user-images.githubusercontent.com/24749356/64399753-3e49a480-d09c-11e9-9ca7-1cda0ac227ed.png)
得到testlh.mnn文件
* 使用新版本量化工具
![image](https://user-images.githubusercontent.com/24749356/64399798-65a07180-d09c-11e9-88cf-813ca9f63ba9.png)
得到testlhnew.mnn文件
然后在demo中使用者两个文件
![image](https://user-images.githubusercontent.com/24749356/64399873-a5ffef80-d09c-11e9-80e0-e5d1a84cc8dd.png)
使用testlh.mnn时，工作正常
![image](https://user-images.githubusercontent.com/24749356/64399907-cd56bc80-d09c-11e9-8396-6d50ba9a7f33.png)
使用testlhnew.mnn文件后
![image](https://user-images.githubusercontent.com/24749356/64399962-fd05c480-d09c-11e9-93d6-e852e34746a3.png)

**Comment by czy2014hust** [comment]
./schema/generate.sh
然后重新编译

**Comment by xiexuliunian** [comment]
如您所言
![image](https://user-images.githubusercontent.com/24749356/64401232-971c3b80-d0a2-11e9-9536-4b1cecf8922a.png)
![image](https://user-images.githubusercontent.com/24749356/64401273-c468e980-d0a2-11e9-8208-a827d522fee0.png)
![image](https://user-images.githubusercontent.com/24749356/64401324-fda15980-d0a2-11e9-984b-566fd5f019ae.png)
* 拷贝相同的preprocessConfig.json文件
![image](https://user-images.githubusercontent.com/24749356/64401368-2a557100-d0a3-11e9-8f87-c7438c6e49e5.png)
* 执行量化操作
![image](https://user-images.githubusercontent.com/24749356/64401443-87512700-d0a3-11e9-908e-b09803a46d5a.png)
* 得到新的testlhnew.mnn,转移到待用文件夹
![image](https://user-images.githubusercontent.com/24749356/64401478-a8b21300-d0a3-11e9-926d-95d46af5ae87.png)
* 更改demo中的模型位置
![image](https://user-images.githubusercontent.com/24749356/64401500-cd0def80-d0a3-11e9-8ca3-5c1c03899e37.png)
![image](https://user-images.githubusercontent.com/24749356/64401509-dbf4a200-d0a3-11e9-9e0f-d3ff7899ef72.png)
一样的结果

**Comment by czy2014hust** [comment]
![image](https://user-images.githubusercontent.com/18324393/64402364-3c391300-d0a7-11e9-9836-0d64d61bcbb5.png)
也得重新编译！

**Comment by xiexuliunian** [comment]
是的呀，我从新make了。再来一遍吧
![image](https://user-images.githubusercontent.com/24749356/64403073-c84c3a00-d0a9-11e9-84df-882cb8a426ca.png)
![image](https://user-images.githubusercontent.com/24749356/64403079-d39f6580-d0a9-11e9-86b5-740a6370005b.png)
