### ISSUE TITLE
Method `getSessionInfo` not working for `BACKENDS`

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [alibaba/MNN#2969]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Ubuntu 20.04 - x86-64 machine

# Github版本:
# Github Version:

From `2.8.1` -> https://github.com/alibaba/MNN/tree/2.8.1

# 编译方式:
# Compiling Method

```
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DMNN_SUPPORT_BF16=ON
  -DMNN_BUILD_CONVERTER=OFF
  -DMNN_BUILD_TEST=OFF
  -DMNN_BUILD_BENCHMARK=OFF
  -DMNN_BUILD_TRAIN=OFF
  -DMNN_OPENCL=ON
  -DMNN_VULKAN=ON
  ../
```

---

The method `getSessionInfo` returns `13` for the Backend:

```cpp
  int32_t backend[] = {0, 0, 0, 0};
  auto flag = _interpreter->getSessionInfo(_session, MNN::Interpreter::SessionInfoCode::BACKENDS, &backend);
  if (flag)
  {
    for (size_t i = 0; i < sizeof(backend) / sizeof(int32_t); i++)
    {
      printf("Backend [%u][%ld]", i, backend[i]);
    }
  }
```

Output:
```
Backend [0][13]
Backend [1][0]
Backend [2][0]
Backend [3][0]
```

However the value `13` isn't a valid Forward Type:
```cpp
typedef enum {
    MNN_FORWARD_CPU = 0,

    /*
     Firtly find the first available backends not equal to CPU
     If no other backends, use cpu
     */
    MNN_FORWARD_AUTO = 4,

    /*Hand write metal*/
    MNN_FORWARD_METAL = 1,

    /*Use IOS's MPS instead of hand-write metal, Not Support yet*/
    MNN_FORWARD_MPS = 2,

    /*Android / Common Device GPU API*/
    MNN_FORWARD_OPENCL = 3,
    MNN_FORWARD_OPENGL = 6,
    MNN_FORWARD_VULKAN = 7,

    /*Android 8.1's NNAPI, Not Support yet*/
    MNN_FORWARD_NN = 5,

    /*User can use API from Backend.hpp to add or search Backend*/
    MNN_FORWARD_USER_0 = 8,
    MNN_FORWARD_USER_1 = 9,
    MNN_FORWARD_USER_2 = 10,
    MNN_FORWARD_USER_3 = 11,

    MNN_FORWARD_ALL
} MNNForwardType;
```

---

Even showing an invalid value for `MNNForwardType` the inference works just fine.

**Comment by jxt1234** [comment]
13 means CPU-Extension . It use fp16 or AVX2 Backend. It's CPU but use different dimentionFormat or data  format

**Comment by caiotoledo-lunasystems** [comment]
> 13 means CPU-Extension . It use fp16 or AVX2 Backend. It's CPU but use different dimentionFormat or data format

Is there a header with this definition? Matching `13` with `CPU-Extension`?
Therefore, is the value returned by `getSessionInfo` for the `MNN::Interpreter::SessionInfoCode::BACKENDS` not `MNNForwardType`?

**Comment by caiotoledo-lunasystems** [comment]
@jxt1234,

I have noticed that I was looking at the wrong header:
https://github.com/alibaba/MNN/blob/2.8.1/project/android/demo/app/includes/MNN/MNNForwardType.h#L12

The right one is:
https://github.com/alibaba/MNN/blob/2.8.1/include/MNN/MNNForwardType.h#L49
And in this case, I can see that the `MNN_FORWARD_CPU_EXTENSION` is `13`.

My IDE got confused by the duplicated headers (thanks to VSCode :smile:)
