### ISSUE TITLE
按batch预测，如何把预处理的数据传给inputTensor

### ISSUE THREAD

**Issue by veepersgit** [alibaba/MNN#297]
有这样一个问题：
同样一个网络模型，一次预测4张图片，shape[0]设置为4
net->resizeTensor(inputTensor, shape);
net->resizeSession(session);
之后，4张不同的预处理图片如何传给inputTensor。

谢谢～

**Comment by jxt1234** [comment]
auto ptr = inputTensor->host<float>() + batchIndex *  inputTensor->stride(0);

然后往 ptr 写数据或者用 ImageProcess 的接口传入

**Comment by twmht** [comment]
@veepersgit 

使用 opencl，batch size > 1 的情況下會比較快嗎？

**Comment by veepersgit** [comment]
@jxt1234 
我尝试了这样做：
auto ptr = inputTensorUser.host<float>() + batchIndex * inputTensor->stride(0);
auto size = inputTensor->stride(0);
pretreat->convert((uint8_t*)inputImage, width, height, 0, (Tensor*)ptr);

出现了Segmentation fault (core dumped)，验证了是最后一句的问题， ImageProcess 的接口传入应该如何做呢？

**Comment by fengyanWang** [comment]
> @jxt1234
> 我尝试了这样做：
> auto ptr = inputTensorUser.host() + batchIndex * inputTensor->stride(0);
> auto size = inputTensor->stride(0);
> pretreat->convert((uint8_t*)inputImage, width, height, 0, (Tensor*)ptr);
> 
> 出现了Segmentation fault (core dumped)，验证了是最后一句的问题， ImageProcess 的接口传入应该如何做呢？

请问这个问题你后来解决了吗？
