### ISSUE TITLE
llm_export.py thorw AttributeError: 'NoneType' object has no attribute 'mnnconvert'

### ISSUE THREAD

**Issue by BruceYang-yeu** [alibaba/MNN#2974]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux

# Github版本:
# Github Version:
602b2e22a470ab7399fb2576ba989d001049425a

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

```shell
git clone xxx MNN
cd MNN/transformers/llm/export
python llm_export.py         --type Qwen2-0_5B-Instruct         --path Qwen2-0.5B-Instruct         --export         --export_token         --export_embed --embed_bin         --export_mnn 
```

Traceback (most recent call last):
  File "llm_export.py", line 1414, in <module>
    llm_exporter.export()
  File "llm_export.py", line 416, in export
    onnx2mnn(onnx_model, self.mnn_path, self.quant_bit, self.asymmetric, True)
  File "llm_export.py", line 43, in onnx2mnn
    MNNTools.mnnconvert(convert_args)
AttributeError: 'NoneType' object has no attribute 'mnnconvert'

**Comment by jxt1234** [comment]
pip install MNN
or use MNNConvert instead of python.

python llm_export.py         --type Qwen2-0_5B-Instruct         --path Qwen2-0.5B-Instruct         --export         --export_token         --export_embed --embed_bin         --export_onnx

Then use MNNConvert to convert onnx to mnn
