### ISSUE TITLE
MNN存在内存泄漏情况

### ISSUE THREAD

**Issue by niucheney** [alibaba/MNN#2976]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
CentOS 7.6 Linux x86_64

# Github版本:
# Github Version: v2.9.2

1. 使用valgrind memcheck检测，发现registerBackend()内部有接近37KB内存泄漏问题，基本都是全局静态指针导致的，这个不属于误报,是真实存在的，希望后续能修复。
2. 在加载模型初始化后，单线程中进行推理，推理后使用valgrind massif测试，发现内存没法复位到推理前的状态，存在内存增长情况，且随着输入变大推理后会变大，如果下一条输入大小变小，则推理后内存会从上一个内存增大的地方变小，这个目前没有定位到哪里的问题，能否协助看一下？

**Comment by jxt1234** [comment]
1. 这个是全局性的初始化内存占用，可以理解为加载 MNN so 所需要的内存，不是内存泄露。
2. 推理时会申请与输入相关的中间内存，这部分不会释放，但如果输入变小重新 resize 时会相应变小。如果希望释放，可以用 clone + destroy module 的方式

**Comment by niucheney** [comment]
谢谢回复，还有两个问题，需要请教下
1. 我这边在Executor.hpp中增加了一个释放全局静态指针的接口和getGlobalExecutor对偶的，能够将37kB全局内存释放掉，但是也会有问题，不能连续初始化和释放了。这部分原因是全局指针的问题，这些全局指针能否挂到某个句柄或类上？
2. 第二个有相关示例可以参考吗？因为有这方面的需求，我用gc函数没有什么作用，释放意味着每次创建线程的时候clone, 然后推理，然后destroy module释放，这样是否要意味着频繁创建/释放线程，因为我想让线程驻留内存。
