### ISSUE TITLE
两个模型轮流失效。。。

### ISSUE THREAD

**Issue by jiarenyf** [alibaba/MNN#298]
我在手机上用了两个convert后的mnn文件，参数一样，输入大小不一样。
首先用一个pb1文件生成mnn1文件，然后修改pb1文件的输入大小得到pb2文件，再生成mnn2文件。
在linux上用cpu运行结果跟tensorflow是一致的。

但是在手机上，两个模型轮流失效（做检测的）：
某个时刻mnn1能检测出框、mnn2也能检测出框；
某个时刻mnn1能检测出框、mnn2不能检测出框；
某个时刻mnn1不能检测出框、mnn2能检测出框；
某个时刻mnn1不能检测出框、mnn2也不能检测出框；

这四种情况随机出现，要疯了。。用的beta0.2.0.9版本。。。

**Comment by jiarenyf** [comment]
救命啊。。。

**Comment by jiarenyf** [comment]
也许跟这个有关：https://github.com/alibaba/MNN/issues/280

**Comment by jiarenyf** [comment]
https://github.com/alibaba/MNN/issues/265

**Comment by jxt1234** [comment]
你手机上有单独跑模型测试么？估计跟你android端的代码有关系

**Comment by jiarenyf** [comment]
@jxt1234 我觉得也许不是跟安卓代码有关，因为两个模型的调用除了输入图片和模型之外，代码是一致的。
而且，在另外一个issue里面（https://github.com/alibaba/MNN/issues/280）：
> 用MNNV2Basic.out对识别模型进行测试时，网络结构含有1*8的dilation cnn，在I7电脑上CPU测试一次且输出正确需要8秒，但是有时候输出很快只要20ms，不过这时候结果一定是错的。。。
尝试过将numthreads设为1，将openmp打开，还是会出现以下情况：
```
同样的input_0.txt，同样的model.mnn，使用 MNNBasic.out进行多次测试，输出的output.txt有时候是正确的（相对于tensorflow的输出），有时候是错误的。

我写了个程序对input_0.txt和output.txt的输出进行判断，格式为[mnn_output]-[tf_output]=[差值]。
见下图1是错误的，下图2是对的。图1图2交替出现，说明应该是有问题的。

测试时使用单线程，且预测时间很短（图1）的时候结果是错的，预测时间很长（图2）的时候结果就是对的。
有没有可能是异步处理出问题了，不是很懂，麻烦看下，谢谢！
```

![Uploading image.png…](Error result.jpg)
![Uploading image.png…](Right result.jpg)

**Comment by jxt1234** [comment]
你这个模型就是有那个 issue 所述的卷积是吧?

**Comment by jiarenyf** [comment]
并不是，这个是检测模型，那个是识别模型。我只是用识别模型出现错误输出的情况来说明检测模型出现的情况应该不是安卓代码的原因。。。麻烦了，谢谢。

**Comment by jiarenyf** [comment]
> @jxt1234 我觉得也许不是跟安卓代码有关，因为两个模型的调用除了输入图片和模型之外，代码是一致的。
> 而且，在另外一个issue里面（[https://github.com/alibaba/MNN/issues/280）：](https://github.com/alibaba/MNN/issues/280%EF%BC%89%EF%BC%9A)
> 
> > 用MNNV2Basic.out对识别模型进行测试时，网络结构含有1*8的dilation cnn，在I7电脑上CPU测试一次且输出正确需要8秒，但是有时候输出很快只要20ms，不过这时候结果一定是错的。。。
> > 尝试过将numthreads设为1，将openmp打开，还是会出现以下情况：
> 
> 同样的input_0.txt，同样的model.mnn，使用 MNNBasic.out进行多次测试，输出的output.txt有时候是正确的（相对于tensorflow的输出），有时候是错误的。
> 
> 我写了个程序对input_0.txt和output.txt的输出进行判断，格式为[mnn_output]-[tf_output]=[差值]。
> 见下图1是错误的，下图2是对的。图1图2交替出现，说明应该是有问题的。
> 
> 测试时使用单线程，且预测时间很短（图1）的时候结果是错的，预测时间很长（图2）的时候结果就是对的。
> 有没有可能是异步处理出问题了，不是很懂，麻烦看下，谢谢！
> 
> 图1（图传不上来。。。）
> 
> ```
> [ -599.679382] - [ -92.764214] = [ -506.915168] ... 
> [ -588.541138] - [ -88.764984] = [ -499.776154] ... 
> [ -587.789001] - [ -96.162323] = [ -491.626678] ... 
> [ -586.640442] - [ -97.628792] = [ -489.011650] ... 
> [ -599.942139] - [ -96.674843] = [ -503.267296] ... 
> [ -591.354675] - [ -94.514015] = [ -496.840660] ... 
> ```
> 
> 图2（图传不上来。。。）
> 
> ```
> [ -92.764267] - [ -92.764214] = [ -0.000053] ... 
> [ -88.765060] - [ -88.764984] = [ -0.000076] ... 
> [ -96.162415] - [ -96.162323] = [ -0.000092] ... 
> [ -97.628860] - [ -97.628792] = [ -0.000068] ... 
> [ -96.674927] - [ -96.674843] = [ -0.000084] ... 
> [ -94.514107] - [ -94.514015] = [ -0.000092] ...
> ```

。。。
