### ISSUE TITLE
mnn_offline_quant离线量化失败

### ISSUE THREAD

**Issue by DommyWorld** [alibaba/MNN#2981]
使用mnn_offline_quant离线量化，模型是多输入，量化后算子仍然是float32类型。但量化过程没有报错，模型文件大小有所缩减，但是模型推理速度并没有上升。附上量化前和量化后的模型。
[量化后.zip](https://github.com/user-attachments/files/16439416/default.zip)
[量化前.zip](https://github.com/user-attachments/files/16439417/default.zip)

**Comment by v0jiuqi** [comment]
多输入的模型可以直接采取权重量化的方式。-MNNConvert --WeightQuantBits这样，具体使用方式参考文档。编译时打开-DMNN_LOW_MEMORY=ON，推理时memory mode使用 low
