### ISSUE TITLE
请问一下非四维度输入的模型怎么传输呢？是不是要添加维度。

### ISSUE THREAD

**Issue by mzb98** [alibaba/MNN#2983]
我模型的原始输入就是 两个一维张量 和 一个三维张量的输入。 转为 mnn 之后，也是如此，但是打印的时候出现 NCHW 的提示，那我是不是应该添加维度再输入数据呢？
Model Inputs:
[ input3 ]: dimensionFormat: NCHW, size: [ 1 ], type is int32
[ input2 ]: dimensionFormat: NCHW, size: [ 1 ], type is int32
[ input1 ]: dimensionFormat: NCHW, size: [ 1,-1, 100 ], type is float
Model Outputs:
[ output1 ]
[ outpu2 ]

我看例子都是 图片作为输入的。

**Comment by jxt1234** [comment]
参考 demo/exec/transformerDemo.cpp ，按实际维度大小创建输入并传入即可。不需要添加维度

**Comment by mzb98** [comment]
好的，谢谢
