### ISSUE TITLE
MAC 上编译hamony版MNN-2.9.0 报错

### ISSUE THREAD

**Issue by jiangyawei** [alibaba/MNN#2988]
mac 上编译 harmony的 MNN报错
MNN版本号2.9.0
MAC: 14.5 (23F79)
cmake : 3.24.3

CMake Error at CMakeLists.txt:68 (include):
  include could not find requested file:

    /@ali/tcpkg/tcpkg.cmake

CMake Error at CMakeLists.txt:69 (export_headers):
  Unknown CMake command "export_headers".

请问怎么解决？
![WechatIMG95](https://github.com/user-attachments/assets/9ccd1d2a-9200-43e1-8375-0d9098f5863b)

**Comment by jxt1234** [comment]
CMakeLists.txt 里面 67-73 行先删掉
