### ISSUE TITLE
编译报错：no member named 'allCpuIdsSorted' in 'MNNCPUInfo'

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#2989]
android
mnn 2.9.3
编译命令：
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_TOOLCHAIN=clang \
-DMNN_USE_LOGCAT=false \
-DMNN_USE_SSE=OFF \
-DMNN_BUILD_TEST=OFF \
-DMNN_BUILD_TOOLS=OFF \
-DMNN_BUILD_BENCHMARK=OFF \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_shared \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DCMAKE_BUILD_TYPE=Release \
-DMNN_SUPPORT_BF16=ON \
-DMNN_OPENCL=ON \
-DMNN_OPENGL=ON \
-DMNN_VULKAN=ON \
-DMNN_USE_THREAD_POOL=OFF \
-DMNN_OPENMP=ON \
-DMNN_ARM82=ON \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4

报错：
[ 47%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUResizeCache.cpp.o
[ 47%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeConvTranspose3D.cpp.o
[ 48%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o
[ 48%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeConvolution.cpp.o
[ 48%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUScale.cpp.o
/Users/tomato/Documents/PycharmProjects/PaddleLite/MNN-2.9.3/source/backend/cpu/CPURuntime.cpp:1131:52: error: no member named 'allCpuIdsSorted' in 'MNNCPUInfo'
    const uint32_t processors_count = cpuinfo_isa->allCpuIdsSorted.size();
                                      ~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 48%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeConvolution3D.cpp.o
[ 49%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeCosineSimilarity.cpp.o
[ 49%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeCrop.cpp.o
make[1]: *** [CMakeFiles/MNNCPU.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 49%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeCropAndResize.cpp.o
[ 49%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeDeconvolution.cpp.o
[ 49%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeDepthToSpace.cpp.o
[ 50%] Building CXX object CMakeFiles/MNNTransform.dir/source/shape/ShapeDequantize.cpp.

**Comment by jxt1234** [comment]
这么修改一下吧:

const uint32_t processors_count = cpuinfo_isa->cpuNumber;
