### ISSUE TITLE
Cannot convert ONNX/TFLITE model to MNN

### ISSUE THREAD

**Issue by K-prog** [alibaba/MNN#2992]
Using the latest MNNConvert, I am not able to convert my original TFLITE model to MNN.
![image](https://github.com/user-attachments/assets/937a003d-da3d-46e9-b502-826effae80b7)

I tried converting it to ONNX and then exporting but it seems to get stuck in a loop and throws warnings, tried using onnx-sim and static batch sizes as well
![image](https://github.com/user-attachments/assets/e59b2cbc-ac78-4c7a-9746-b40fdb7dd363)

Command used:
```
MNNConvert.exe -f ONNX --modelFile "facenet_dynamic-sim.onnx" --MNNModel facenet.mnn --bizCode MNN --info
```
[Model Links](https://drive.google.com/drive/folders/1MjtobJR3Zb7j9RFnTz1h7bJ0JO0tMfJR?usp=sharing)

**Comment by jxt1234** [comment]
Use testMNNFromOnnx.py to test. The error may be caused by subgraph's inputs not valid.

**Comment by K-prog** [comment]
Seems like it stopped at:

Start to Optimize the MNN Net...
![Screenshot 2024-09-01 at 11 53 35 AM_cleanup](https://github.com/user-attachments/assets/922c12eb-86ee-423c-867f-d86a554c5c30)

The ONNX model runs properly.

**Comment by jxt1234** [comment]
It seems has error with dequant. Could you use float model convert to MNN and then quantized it by MNN ?
