### ISSUE TITLE
./MNNConvert --fp16失效？

### ISSUE THREAD

**Issue by deltaguo** [alibaba/MNN#2996]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
macOS

encoder.onnx是fp32的模型，执行：
```shell
./MNNConvert -f ONNX --modelFile ./encoder.onnx --MNNModel ./encoder_fp16.mnn --bizCode biz --fp16
```
之后将模型adb push到Android上，使用timeProfile.out来测性能，发现对比fp32并没有提升。使用Netron打开发现encoder_fp16.mnn中的权重都还是fp32并且值为空
<img width="484" alt="截屏2024-08-16 17 17 18" src="https://github.com/user-attachments/assets/a2382f13-6243-42fe-8d0b-d635e0f3a09d">
所以我转模型转对了吗，或者存在bug？

**Comment by jxt1234** [comment]
搜下历史 issue 就可以找到答案：--fp16 只是降低模型大小，Android 上开启 fp16 推理是打开 MNN_ARM82 宏并设置precision = low
