### ISSUE TITLE
Windows 2022 编译2.9.0报错

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#2997]
命令：cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON

使用了未初始化的局部变量“srcValue0”
[286/321] Building CXX object CMakeFiles\ModuleBasic.out.dir\tools\cpp\ModuleBasic.cpp.obj
D:\WorkSpaceProjects\PycharmProjects\buildProject\MNN\tools\cpp\ModuleBasic.cpp(35): warning C4477: “printf”: 格式字符串“%d”需要类型“int”的参数，但可变参数 4 拥有了类型“const size_t”
D:\WorkSpaceProjects\PycharmProjects\buildProject\MNN\tools\cpp\ModuleBasic.cpp(35): note: 请考虑在格式字符串中使用“%zd”
[320/321] Linking CXX executable LoRA.exe
FAILED: LoRA.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && "D:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\LoRA.dir --rc=D:\WINDOW~1\10\bin\100226~1.0\x64\rc.exe --mt=D:\WINDOW~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- D:\PROGRA~3\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\link.exe /nologo CMakeFiles\LoRA.dir\tools\cpp\LoRA.cpp.obj  /out:LoRA.exe /implib:LoRA.lib /pdb:LoRA.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF /subsystem:console  /WHOLEARCHIVE:D:/WorkSpaceProjects/PycharmProjects/buildProject/MNN/build/MNN.lib  MNN.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "D:\PROGRA~3\MICROS~1\2022\COMMUN~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\link.exe /nologo CMakeFiles\LoRA.dir\tools\cpp\LoRA.cpp.obj /out:LoRA.exe /implib:LoRA.lib /pdb:LoRA.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /DEBUG /OPT:REF /OPT:ICF /subsystem:console /WHOLEARCHIVE:D:/WorkSpaceProjects/PycharmProjects/buildProject/MNN/build/MNN.lib MNN.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST:EMBED,ID=1" failed (exit code 1169) with the following output:
MNN.lib(ConvolutionCommon.cpp.obj) : error LNK2005: "void __cdecl IDSTDecoder::DestorySimpleSet(struct IDSTDecoder::_SIMPLE_SET *)" (?DestorySimpleSet@IDSTDecoder@@YAXPEAU_SIMPLE_SET@1@@Z) 已经在 LoRA.cpp.obj 中定义
LoRA.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
[321/321] Linking CXX executable fuseTest.exe
ninja: build stopped: subcommand failed.
![image](https://github.com/user-attachments/assets/48e0dfba-695b-43fa-bec8-bc2773075f6f)

**Comment by jxt1234** [comment]
更新到 2.9.3 ，lora 这个重定义的问题已经修正

**Comment by yangy996** [comment]
![image](https://github.com/user-attachments/assets/a2cc038a-4e8d-41dc-a2c3-b80b7a4fd762)
