### ISSUE TITLE
undefined reference to'__emutls_get_address'

### ISSUE THREAD

**Issue by xiaohaipeng** [alibaba/MNN#30]
when i follow build for Android, the last step,i met linking error.

[ 92%] Linking CXX shared library libMNN.so
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgomp/libgomp.h:494: error: undefined reference to '__emutls_get_address'
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgomp/libgomp.h:494: error: undefined reference to '__emutls_get_address'
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgomp/libgomp.h:494: error: undefined reference to '__emutls_get_address'
/usr/local/google/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/libgomp/parallel.c:178: error: undefined reference to '__emutls_get_address'
collect2: error: ld returned 1 exit status
CMakeFiles/MNN.dir/build.make:3533: recipe for target 'libMNN.so' failed
make[2]: *** [libMNN.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/MNN.dir/all' failed
make[1]: *** [CMakeFiles/MNN.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

how can i fix this???

**Comment by xiaohaipeng** [comment]
close openmp，maybe gcc version is too  low

**Comment by xiefu5hh** [comment]
> close openmp，maybe gcc version is too low

hi so what gcc version are you use to sloves this problem?

**Comment by xiaohaipeng** [comment]
i just close openmp,no update gcc
