### ISSUE TITLE
MMNConvert run error

### ISSUE THREAD

**Issue by yanlei08** [alibaba/MNN#300]
gcc:5.3.1
protobuf:3.61
cmake:3.12.1
source:0.2.0.9
I built MMConvert sucessfully, but when I run ./MMNConvert --version, it throw error.
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)
Please help, Thanks!

**Comment by xiexuliunian** [comment]
I also have occured the same problem,my solution is add follow to the right places.
find_package(Threads REQUIRED)
target_link_libraries(可执行程序 Threads::Threads)
then you can run without error

**Comment by yanlei08** [comment]
@xiexuliunian MNNConvert run successfully as your comment. Thanks for your help!

**Comment by xiexuliunian** [comment]
> @xiexuliunian MNNConvert run successfully as your comment. Thanks for your help!

好高兴听到老铁的好消息

**Comment by MaybeShewill-CV** [comment]
@yanlei08 遇到一樣的問題 之前的版本編譯的可執行程序都沒有問題 pull了最新的代碼 重新編譯的工具就有這個問題了

**Comment by xiexuliunian** [comment]
繁体字，台湾的兄弟吗？看来我是第一个遇到这个问题的，我提了其他的issues遇到这个问题了，后来自己找解决办法，也算是解决了。但是我现在还是有有的mnn模型量化失败的问题，不知道咋解决。

**Comment by MaybeShewill-CV** [comment]
@yanlei08 不是 是最近輸入法有問題 上面遇到的那個問題解決了 又遇到了新的問題. 我生成的pb文件轉換mnn時候沒有報錯 沒有異常能正常生成mnn模型文件 但是在使用這個mnn模型文件創建會話session的時候會崩潰
![Screenshot from 2019-09-10 14-23-40](https://user-images.githubusercontent.com/15725187/64589369-8a1b8700-d3d7-11e9-9095-9192f1aeb179.png)

**Comment by xiexuliunian** [comment]
> @yanlei08 不是 是最近輸入法有問題 上面遇到的那個問題解決了 又遇到了新的問題. 我生成的pb文件轉換mnn時候沒有報錯 沒有異常能正常生成mnn模型文件 但是在使用這個mnn模型文件創建會話session的時候會崩潰
> ![Screenshot from 2019-09-10 14-23-40](https://user-images.githubusercontent.com/15725187/64589369-8a1b8700-d3d7-11e9-9095-9192f1aeb179.png)

我也曾遇到过这个问题，请把cmake里面libMNN.so的路径 改成新的路径，就好啦。

**Comment by MaybeShewill-CV** [comment]
@xiexuliunian 你说的是哪个cmake文件 我没找到直接链接libMNN.so的cmake文件 求教具体是哪个文件哈. 而且我看这个不像是链接问题啊==！

**Comment by xiexuliunian** [comment]
> @xiexuliunian 你说的是哪个cmake文件 我没找到直接链接libMNN.so的cmake文件 求教具体是哪个文件哈. 而且我看这个不像是链接问题啊==！

你使用mnn，不需要在自己的项目里面添加libMNN.so的路径吗就像这样，
![image](https://user-images.githubusercontent.com/24749356/64596322-41b79580-d3e6-11e9-945d-3bc671e62311.png)
我当时的问题是，路径还是之前版本的libMNN.so文件的路径。

**Comment by MaybeShewill-CV** [comment]
@xiexuliunian 我是直接在https://github.com/alibaba/MNN/blob/master/tools/cpp文件夹中写了一个自己用的测试demo 然后在https://github.com/alibaba/MNN/blob/master/tools/cpp/CMakeLists.txt中添加了自己的这个demo 然后编译都没问题 运行的时候出的问题 🤦‍♂️

**Comment by MaybeShewill-CV** [comment]
@xiexuliunian 我是直接在https://github.com/alibaba/MNN/blob/master/tools/cpp 文件夹中写了一个自己用的测试demo 然后在https://github.com/alibaba/MNN/blob/master/tools/cpp/CMakeLists.txt 中添加了自己的这个demo 然后编译都没问题 运行的时候出的问题 🤦‍♂️

**Comment by xiexuliunian** [comment]
> @xiexuliunian 我是直接在https://github.com/alibaba/MNN/blob/master/tools/cpp 文件夹中写了一个自己用的测试demo 然后在https://github.com/alibaba/MNN/blob/master/tools/cpp/CMakeLists.txt 中添加了自己的这个demo 然后编译都没问题 运行的时候出的问题 🤦‍♂️

这样呀，那应该不是和我类似的问题。我没有踩过你的坑。。。。。。等你解决了，发出来哈

**Comment by CodingMice** [comment]
> I also have occured the same problem,my solution is add follow to the right places.
> find_package(Threads REQUIRED)
> target_link_libraries(可执行程序 Threads::Threads)
> then you can run without error

我也遇到一样的问题。CmakeList.txt修改以后，前面编译的build是否需要全部删除然后再重新编译？
