### ISSUE TITLE
Windows server系统中，c++编译后的dll文件，调用会报错OSError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by yangy996** [alibaba/MNN#3001]
window server 2016
非服务器版的windows系统就正常

mnn：2.9.0
c++代码编译成dll文件后，走到这一行就报错OSError: exception: access violation reading 0x0000000000000000

![image](https://github.com/user-attachments/assets/14d7b915-2bad-49d8-8204-2466d5ef1b3f)

**Comment by jxt1234** [comment]
mnn 编译选项是什么?

**Comment by yangy996** [comment]
> mnn 编译选项是什么?

cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=OFF
ninja

编译出来的是静态库文件，集成到c++中后，windows家庭版和专业版上都正常，就服务器版本上不行

**Comment by jxt1234** [comment]
有可能是 C++ std 库不一致
1. 换用动态库试试
2. 服务器上编译 MNN 及运行 MNNV2Basic.out 等测试工具是否可运行？

**Comment by jxt1234** [comment]
有可能是 C++ std 库不一致
1. 换用动态库试试
2. 服务器上编译 MNN 及运行 MNNV2Basic.out 等测试工具是否可运行？

**Comment by yangy996** [comment]
> 有可能是 C++ std 库不一致
> 
> 1. 换用动态库试试
> 2. 服务器上编译 MNN 及运行 MNNV2Basic.out 等测试工具是否可运行？

找到问题了，编译用的2022版的vc库，服务器上的vc库版本太低，安装最新的vc库就可以了

**Comment by taozigge** [comment]
你好，集成到windows家庭版和专业版是visual studio吗，我集成还是报错
