### ISSUE TITLE
mnn和onnx模型多个输入/输出顺序不匹配，喂数据时对不上顺序

### ISSUE THREAD

**Issue by laofuzi123321** [alibaba/MNN#3002]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android 平台

# Github版本:
# Github Version:
2.0.7版本

**Comment by jxt1234** [comment]
mnn 模型的输入输出是按名字去找的，顺序也可以自己按名字指定：
https://mnn-docs.readthedocs.io/en/latest/inference/module.html
