### ISSUE TITLE
安卓上使用静态库执行createSession报错

### ISSUE THREAD

**Issue by yinghuang** [alibaba/MNN#3003]
# 平台(如果交叉编译请再附上交叉编译目标平台):  windows+ndk
# Platform(Include target platform as well if cross-compiling):  

# Github版本:2.9.3
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake交叉编译

```
    cmake -G"Unix Makefiles" ^
    -DCMAKE_TOOLCHAIN_FILE=%ANDROID_NDK%/build/cmake/android.toolchain.cmake ^
    -DANDROID_ABI=%ANDROID_ABI% ^
    -DANDROID_NDK=%ANDROID_NDK% ^
    -DANDROID_NATIVE_API_LEVEL=android-%MIN_LEVEL% ^
    -DCMAKE_ANDROID_ARCH_ABI=%ANDROID_ABI% ^
    -DCMAKE_ANDROID_NDK=%ANDROID_NDK% ^
    -DCMAKE_MAKE_PROGRAM=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe ^
    -DCMAKE_SYSTEM_NAME=Android ^
    -DCMAKE_SYSTEM_VERSION=%MIN_LEVEL% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DMNN_BUILD_SHARED_LIBS=OFF ^
    -DANDROID_STL=c++_static ^
    -DMNN_USE_LOGCAT=false ^
    -DMNN_BUILD_BENCHMARK=ON ^
    -DMNN_USE_SSE=OFF ^
    -DMNN_BUILD_TEST=OFF ^
    -DMNN_BUILD_FOR_ANDROID_COMMAND=true ^
    -DMNN_OPENCL=ON ^
    -DMNN_VULKAN=OFF ^
    -DMNN_NNAPI=OFF ^
    -DMNN_USE_SYSTEM_LIB=ON ^
    -DMNN_SEP_BUILD=OFF ^
    -B%BUILD_DIR% ^
    -H%CMAKE_DIR%

     %ANDROID_NDK%/prebuilt/windows-x86_64/bin/make.exe -C %BUILD_DIR%  -j12
```

# 问题描述:
静态库和动态库都编译成功
动态库运行没问题
```
MNN::ScheduleConfig net_cfg;
net_cfg.type = MNN_FORWARD_CPU;
net_cfg.numThread = 3;
mnn_session = mnn_net->createSession(net_cfg);
```
但是静态库执行到上面这行的createSession时报错：
```
A/libc: /buildbot/src/android/ndk-r24-release/toolchain/llvm-project/libcxx/../../../toolchain/llvm-project/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
```
如果使用动态库，就完全没问题
也试了添加-Wl,--whole-archive MNN -Wl,--no-whole-archive，还是报错
```
target_link_libraries(${MODULE_NAME} -Wl,--whole-archive MNN -Wl,--no-whole-archive)
```

NDK==20.0.559457，24.0.8215888，27.0.12077973都试过了

**Comment by jxt1234** [comment]
大概是你编译的库的 stl 和 mnn 的 stl 选取不一样，编译 mnn 时把 stl 换成你自己库的 stl 类型

**Comment by yinghuang** [comment]
> 大概是你编译的库的 stl 和 mnn 的 stl 选取不一样，编译 mnn 时把 stl 换成你自己库的 stl 类型

谢谢，发现是跟我引用的另一个库冲突了
