### ISSUE TITLE
mnn输入名字和onnx输入名字不一致

### ISSUE THREAD

**Issue by laofuzi123321** [alibaba/MNN#3006]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
andorid 平台

# Github版本:
# Github Version:
master 分支

问题详述：
onnx转换成mnn之后, 输入tensor个别名字发生的变化，onnx为emb_int，mnn为emb_out

截图：
onnx的输入名字如下图：
![image](https://github.com/user-attachments/assets/21352d15-8ab4-42e4-8816-2dc0a74d5030)
转换之后的输入名字下图：
![image](https://github.com/user-attachments/assets/c0a94916-7471-4b92-a299-41f7cb61d53a)

出错位置：
![image](https://github.com/user-attachments/assets/8e1d5246-aefa-4520-abb8-bcb05011e999)

**Comment by jxt1234** [comment]
这个是输出仅经过 identity 算子计算，然后identity被mnn优化掉的原因。目前解决方案：可以在onnx 转 MNN 模型转换时加 --optimizeLevel=0 （避免identity优化），或者修改模型移除相关输入输出。
