### ISSUE TITLE
arm32的卷积微内核中使用vmlal.s8（8位乘法16位累加）是否会导致溢出？

### ISSUE THREAD

**Issue by aa531811821** [alibaba/MNN#301]
其他框架如NCNN等都是使用的vmlal.s16，但是MNN中使用的是vmlal.s8，这是否会导致溢出？

**Comment by jxt1234** [comment]
MNN模型量化的机制保证了不会溢出并且计算高效，可后续留意相关文档

**Comment by aa531811821** [comment]
> MNN模型量化的机制保证了不会溢出并且计算高效，可后续留意相关文档

我是tflite的8bit模型转成MNN的，也没问题吗？ 量化机制的文档有没有链接，O(∩_∩)O

**Comment by jxt1234** [comment]
也没问题的，目前文档还在补充中哈

**Comment by aa531811821** [comment]
> 也没问题的，目前文档还在补充中哈

好的，后续期待你们的文档哈 :)
