### ISSUE TITLE
opencl，批量推理错误

### ISSUE THREAD

**Issue by prfans** [alibaba/MNN#3010]
windows系统下，批量样本推理得不到正确的结果，例如一次推理4张图像：[4,3,256,256]结果错误，但是推理一张图像[1,3,256,256]正确，cpu下推理正确只有再opencl下推理失败，涉及的版本从2.1-2.9版本。

**Comment by jxt1234** [comment]
相关模型可以发一下？另外 windows 上是什么 gpu ?
