### ISSUE TITLE
请问，我想获取MNN推理时，每个算子的耗时，或者整个流程的耗时，就是做profililng，我该怎么做？？？

### ISSUE THREAD

**Issue by HPUedCSLearner** [alibaba/MNN#3012]
请问，我想获取MNN推理时，每个算子的耗时，或者整个流程的耗时，就是做profililng，我该怎么做？？？
非常感谢，期待您的回复！！！

**Comment by jxt1234** [comment]
参考 ModuleBasic.cpp 里面的写法。
https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out
