### ISSUE TITLE
将onnx fp32的模型，转换为mnn fp16模型，部分层的weight为空

### ISSUE THREAD

**Issue by zhanghang1995** [alibaba/MNN#3021]
转换前：
![image](https://github.com/user-attachments/assets/d9cb6943-b158-4e18-b9a5-198573f6906e)

转换后：
![image](https://github.com/user-attachments/assets/8f6e317d-3e6b-4b45-99ef-129e0aec83a9)

工具：MNN model convert
<img width="1400" alt="image" src="https://github.com/user-attachments/assets/d64b3ea1-8c7f-460f-aa17-05611e9fdcc4">

**Comment by jxt1234** [comment]
fp16 的权重转换为 buffer 存储。netron 无法显示。用 MNNDump2Json 可以把 mnn 打印为 json 查看
