### ISSUE TITLE
rust wrapper over mnn / mnn 上的 rust 包装器

### ISSUE THREAD

**Issue by uttarayan21** [alibaba/MNN#3023]
Hi, we at [aftershoot](https://github.com/aftershootco) ended up writing a rust wrapper over mnn. 

The code is not fully stable yet and all the APIs are not fully exposed in the rust-side.

The code is [here](https://github.com/aftershootco/mnn-rs) if you want to check it out. We'd love some contributions / review if you are able to.

I used google translate

---

大家好，我们在 [aftershoot](https://github.com/aftershootco) 最终在 mnn 上编写了一个 rust 包装器。

代码尚未完全稳定，并且所有 API 尚未在 rust 端完全公开。

如果您想查看，代码位于 [此处](https://github.com/aftershootco/mnn-rs)。如果您愿意，我们很乐意为您提供一些贡献/评论。

我使用了谷歌翻译

--- 

https://github.com/aftershootco/mnn-rs

**Comment by K-prog** [comment]
@jxt1234 we would love to chat about this and make [mnn-rs](https://github.com/aftershootco/mnn-rs) more usable, among the rust community!

**Comment by jxt1234** [comment]
Great work. We will see it later.
