### ISSUE TITLE
grid_sample-5D 算子转mnn后精度不达预期

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#3026]
# 平台(如果交叉编译请再附上交叉编译目标平台):  linux cpu

# Github版本: 2.9.1

grid_sample-5D 算子转mnn, 推理结果与onnx推理结果不一致，差异明显。
1. ModuleBasic.out工具测试, DiffMax 0.250394。
2. 网络其它算子不变，单替换掉grid_sample算子，则预测正常。

**Comment by jxt1234** [comment]
已经定位问题，可以先这么修改解决
diff --git a/source/backend/cpu/CPUGridSample.cpp b/source/backend/cpu/CPUGridSample.cpp
index 3cc633d3d..f39191375 100644
--- a/source/backend/cpu/CPUGridSample.cpp
+++ b/source/backend/cpu/CPUGridSample.cpp
@@ -97,7 +97,7 @@ ErrorCode CPUGridSample::onExecute(const std::vector<Tensor *> &inputs, const st
         auto outH = outputTensor->buffer().dim[3].extent;
         auto outW = outputTensor->buffer().dim[4].extent;
         auto threadCount = static_cast<CPUBackend*>(backend())->threadNumber();
-        auto tileCount = outD;
+        auto tileCount = outD * channelC4;
         auto inOffset  = batches * inH * inW * core->pack;
         auto outOffset = batches * outH * outW * core->pack;
         auto cordPtr = mTempCordBuffer->host<uint8_t>();

**Comment by ppl21847** [comment]
> 已经定位问题，可以先这么修改解决 diff --git a/source/backend/cpu/CPUGridSample.cpp b/source/backend/cpu/CPUGridSample.cpp index 3cc633d3d..f39191375 100644 --- a/source/backend/cpu/CPUGridSample.cpp +++ b/source/backend/cpu/CPUGridSample.cpp @@ -97,7 +97,7 @@ ErrorCode CPUGridSample::onExecute(const std::vector<Tensor _> &inputs, const st auto outH = outputTensor->buffer().dim[3].extent; auto outW = outputTensor->buffer().dim[4].extent; auto threadCount = static_cast<CPUBackend_>(backend())->threadNumber();
> 
> * ```
>      auto tileCount = outD;
>   ```
> 
> * ```
>      auto tileCount = outD * channelC4;
>      auto inOffset  = batches * inH * inW * core->pack;
>      auto outOffset = batches * outH * outW * core->pack;
>      auto cordPtr = mTempCordBuffer->host<uint8_t>();
>   ```

已解决。

**Comment by JackieLitongji** [comment]
@jxt1234 hihi，上述是fp32的修复，如果是arm82，这个估计也会有问题
