### ISSUE TITLE
mobilenetTest.cpp　代码疑问

### ISSUE THREAD

**Issue by zjd1988** [alibaba/MNN#303]
在阅读mobilenetTest.cpp源码时发现下面的代码有些疑问？

.....
line 52:         int netInputHeight       = inputTensorUser.height();
line 53:         int **netOutputWidth**       = inputTensorUser.width();

....

上面加粗的字体的变量的命名不影响代码的正常运行，但是不是有些歧义？
此处表示的意识应该是输入tensor的宽吧？

![WXWorkCapture_15681093229553](https://user-images.githubusercontent.com/7134030/64604713-361f9b00-d3f5-11e9-9084-35f6b920ae04.png)

**Comment by MaybeShewill-CV** [comment]
@zjd1988 我感觉可能是笔误了吧:)

**Comment by hacker-joe** [comment]
嗯嗯。这个地方的确命名写错了
