### ISSUE TITLE
llmexport 导出mnn失败 These Op Not Support: ONNX::FakeLinear

### ISSUE THREAD

**Issue by lzzbutphh** [alibaba/MNN#3035]
使用MNN工程里面 llmexport.py文件导出，报错如题。
运行命令

'''
 python llmexport.py --path /Users/lizongze/PycharmProjects/MNN_demo/Qwen2-1.5B-Instruct  --export mnn
'''

**Comment by jxt1234** [comment]
更新 pymnn 到最新，或者在 MNN 根目录下建 build 文件夹并编译 MNNConvert
