### ISSUE TITLE
iOS v2.9.5 MNN.framework/Headers/Interpreter.hpp 头文件报错

### ISSUE THREAD

**Issue by YiQiu1984** [alibaba/MNN#3036]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
iOS 2.9.5

# Github版本:
# Github Version:

 tag 2.9.5

# 编译方式:
# Compiling Method
xcode直接运行生成MNN.framework
```
集成MNN.framework时，MNN.framework/Headers/Interpreter.hpp 头文件报错：“MNN/ErrorCode.hpp file not found”。
在MNN.framework里面，是没有MNN这一层目录的。

CMAKE集成：
if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  target_include_directories(${PROJECT_NAME} PRIVATE ${LIBMNN_PATH}/iOS/MNN.framework/Headers)
  # link
  target_link_libraries(${PROJECT_NAME} PRIVATE "-framework MNN")
  # framework search dir
  set_target_properties(${PROJECT_NAME} PROPERTIES
            LINK_FLAGS "-Wl,-F  ${LIBMNN_PATH}/iOS")
endif()

**Comment by YiQiu1984** [comment]
使用cmake集成xcode编译出来的MNN.framework
集成脚本：
if (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  target_include_directories(${PROJECT_NAME} PRIVATE ${LIBMNN_PATH}/iOS/MNN.framework/Headers)
  # link
  target_link_libraries(${PROJECT_NAME} PRIVATE "-framework MNN")
  # framework search dir
  set_target_properties(${PROJECT_NAME} PROPERTIES
            LINK_FLAGS "-Wl,-F  ${LIBMNN_PATH}/iOS")
endif()

运行时报错：
MNN.framework/Headers/Interpreter.hpp 头文件报错：“MNN/ErrorCode.hpp file not found”

**Comment by jxt1234** [comment]
framework 中的头文件是适配 xcode 工程引用的，可以自行复制一份头文件出来给 cmake 使用

**Comment by YiQiu1984** [comment]
> framework 中的头文件是适配 xcode 工程引用的，可以自行复制一份头文件出来给 cmake 使用

是说集成的工程里不使用framework里的头文件，另外copy一份出来是吗？这样运行时会不会报错呢？

**Comment by YiQiu1984** [comment]
我想知道xcode工程能不能构建出libMNN.a文件出来呢？我想在C++层使用，能构建出来.a静态库的话，会比较方便

**Comment by jxt1234** [comment]
1. 头文件直接复制就行。MNN的对外头文件保证向下兼容，不会有问题.
2. 编 .a 的话自己用 cmake 编就好了:
mkdir build && cd build
cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DMNN_METAL=ON -DARCHS="arm64" -DENABLE_BITCODE=0 -DMNN_AAPL_FMWK=0 -DMNN_SEP_BUILD=0 -DMNN_ARM82=true -DMNN_BUILD_SHARED_LIBS=false -DMNN_USE_THREAD_POOL=OFF -DMNN_LIB_DIR=.
make -j16
make install

**Comment by jxt1234** [comment]
具体命令参考脚本 package_scripts/ios/buildiOS.sh ，把 -DMNN_AAPL_FMWK=1 去掉就可以
