### ISSUE TITLE
GPU does not speed up the model

### ISSUE THREAD

**Issue by twmht** [alibaba/MNN#304]
the process time of GPU and CPU are very similar.

My model arch is mobilenetV2.

Does anyone got great improvement when using GPU?

**Comment by jxt1234** [comment]
What's your machine? For a few machine (Mi-6, Mi-5, Mi-8, Huawei Mate9 / Mate10 / P10 / P20) or very large model such as resnet50 will gpu run faster than CPU with multi-thread. But normally we need GPU for CPU has other work to do and can't use multi thread.

**Comment by twmht** [comment]
@jxt1234 

The testing device is RK3399 on android.

I can't understand your meaning

> But normally we need GPU for CPU has other work to do and can't use multi thread.

Can you elaborate more?

by the way, there is always an error message when running on RK3399

```
 E/vpu_api: dlopen vpu lib failed
```

Not sure if this is the root cause.

**Comment by jxt1234** [comment]
For rk3399 you can use opencl, and set precision = low. 
The OpenCL with precision low will be faster than CPU.

**Comment by twmht** [comment]
@jxt1234 

this is a good suggestion. 

I tried to run benchmark.out in RK3399 and HTC-10, both can't run opencl mode. 

https://github.com/alibaba/MNN/issues/307

**Comment by twmht** [comment]
@jxt1234 

Is opencl or vulkan preferred NCHW  more than NHWC?  I run mobilenetv2 (NCHW) with vulkan and got 1.5x performance speed up, but much slower with NHWC.

Since my model is converted from caffe, can we convert the format NHWC to NCHW?

**Comment by v1incent** [comment]
> For rk3399 you can use opencl, and set precision = low.
> The OpenCL with precision low will be faster than CPU.

For my test case, CPU is faster than OpenCL. Did I miss something for configuration?

**Comment by mathpopo** [comment]
For rk3399 you can use opencl, and set precision = low, can less than %30

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/faq.html#gpu-cpu
