### ISSUE TITLE
麒麟芯片问题

### ISSUE THREAD

**Issue by dreamer1031** [alibaba/MNN#3042]
如果我将MNN部署在麒麟芯片上，不打开NPU开关，不进行NPU编译的话是不是就是在推理的时候不用NPU推理，还是用GPU推理？
问这个问题的背景是我将检测代码部署在手机上时，发现麒麟芯片的机型普遍推理结果有问题，其他机型没有发现问题。

**Comment by jxt1234** [comment]
跟设置的forwardtype 相关。

**Comment by jxt1234** [comment]
跟设置的forwardtype 相关。

**Comment by jxt1234** [comment]
结果问题先用测试工具测试一下：
https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out
