### ISSUE TITLE
onnx转换mnn模型，输出结果不对，怎么排查

### ISSUE THREAD

**Issue by zhangshabao** [alibaba/MNN#3049]
std::vector<float> substractMeanNormalize(cv::Mat &src, const float *meanVals, const float *normVals) {
        auto inputTensorSize = src.cols * src.rows * src.channels();
        std::vector<float> inputTensorValues(inputTensorSize);
        size_t numChannels = src.channels();
        size_t imageSize = src.cols * src.rows;
        for (size_t pid = 0; pid < imageSize; pid++) {
            for (size_t ch = 0; ch < numChannels; ++ch) {
                float data = (float) (src.data[pid * numChannels + ch] * normVals[ch] - meanVals[ch] * normVals[ch]);
                inputTensorValues[ch * imageSize + pid] = data;  // 这个赋值方式，相当于从nhwc-> nchw?
            }
        }
        return inputTensorValues;
    }
{
  cv::Mat srcResize;
        resize(src, srcResize, cv::Size(1024, 640)); // w*h
        double time0 = getCurrentTime();
        float normValues_[1] = {1 / 255.f};
        float meanValues_[3] = {0.0f};
        std::vector<float> inputTensorValues = substractMeanNormalize(srcResize, meanValues_, normValues_);
        auto input = _mnn_net->getSessionInput(_mnn_session, NULL);
        auto output = _mnn_net->getSessionOutput(_mnn_session, NULL);
        auto shape = input->shape();
        shape[0]   = 1;
        shape[2]   = srcResize.rows;  
        shape[3]   = srcResize.cols;   
        // auto input = _mnn_net->getSessionInput(_mnn_session, NULL);
        float memoryUsage = 0.0f;
        _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::MEMORY, &memoryUsage);
        float flops = 0.0f;
        _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::FLOPS, &flops);
        int backendType[2];
        _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::BACKENDS, backendType);
        DEBUG_LOG("Session Info: memory use %f MB, flops is %f M, backendType is %d", memoryUsage, flops, backendType[0]);

        _mnn_net->resizeTensor(input, shape);
        _mnn_net->resizeSession(_mnn_session);
        auto shapein = input->shape();
        std::vector<int> v = {1,(int)srcResize.channels(),srcResize.rows,srcResize.cols};
        auto nchwTensor = MNN::Tensor::create(v,halide_type_of<float>(),&inputTensorValues[0],MNN::Tensor::CAFFE);
        input->copyFromHostTensor(nchwTensor);
        delete nchwTensor;
        _mnn_net->runSession(_mnn_session);
        std::shared_ptr<MNN::Tensor> outputUser(new MNN::Tensor(output, output->getDimensionType())); //nchw
        output->copyToHostTensor(outputUser.get());
        auto values = outputUser->host<float>();

        MNN::Tensor feat_tensor(output, output->getDimensionType());
        output->copyToHostTensor(&feat_tensor);
        int size = feat_tensor.elementSize(); // 获取元素数量
        float* data = feat_tensor.host<float>(); 
        }
这个是推理代码；onnx模型推理是正常，转mnn后结果输出不对。模型在附件
[model.zip](https://github.com/user-attachments/files/17360351/model.zip)

**Comment by zhangshabao** [comment]
![lQLPKHbKFRe6hivNAdjNAtewJs6qcoSEzO8G9BoWKb2aAA_727_472](https://github.com/user-attachments/assets/e9673a10-9ddd-404a-8751-633eaea008f5)

**Comment by jxt1234** [comment]
图片大小是多少？看这个 onnx 是固定输入尺寸的，不能 resizeSession。 需要在 ImageProcess 里面 resize

**Comment by zhangshabao** [comment]
> 图片大小是多少？看这个 onnx 是固定输入尺寸的，不能 resizeSession。 需要在 ImageProcess 里面 resize

图片是640*640

**Comment by jxt1234** [comment]
另外推理代码不完整，附上完整推理代码吧

**Comment by jxt1234** [comment]
> > 图片大小是多少？看这个 onnx 是固定输入尺寸的，不能 resizeSession。 需要在 ImageProcess 里面 resize
> 
> 图片是640*640

这个模型只支持 640x1280 的输入，需要支持输入尺寸可变的话需要在 export onnx 时加上 dynamic_axes

**Comment by zhangshabao** [comment]
> > > 图片大小是多少？看这个 onnx 是固定输入尺寸的，不能 resizeSession。 需要在 ImageProcess 里面 resize
> > 
> > 
> > 图片是640*640
> 
> 这个模型只支持 640x1280 的输入，需要支持输入尺寸可变的话需要在 export onnx 时加上 dynamic_axes

是固定尺寸输入，输入数据resize到640x1024
 int Model::LoadModelFromFile(const char *model_path)
    {
        _mnn_net = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_path));

        _net_cfg.type  = MNN_FORWARD_CPU;
        _net_cfg.numThread = 4;
        _mnn_session = _mnn_net->createSession(_net_cfg);

        // _mnn_net->setSessionMode(MNN::Interpreter::Session_Backend_Auto);
        // _mnn_net->setSessionHint(MNN::Interpreter::MAX_TUNING_NUMBER, 5);
        // if (nullptr == _mnn_net)
        // {
        //     ERROR_LOG("backend mnn create interpreter failed!");
        //     return -24;
        // }
        // _net_cfg.type = MNN_FORWARD_AUTO;
        // _net_cfg.numThread = 4;
        // _mnn_session = _mnn_net->createSession(_net_cfg);

        // if (nullptr == _mnn_session)
        // {
        //     ERROR_LOG("backend mnn create session failed!");
        //     return -24;
        // }
        DEBUG_LOG("backend mnn init succeed!");
        init_model = true;
        return 6;
    }
    int Model::Execute(const cv::Mat &src)
    {
        DEBUG_LOG(" init_model  :%d", init_model);
        if (init_model == false)
            return -8;

        cv::Mat srcResize;
        cv::cvtColor(src, srcResize, cv::COLOR_GRAY2RGB);
        resize(srcResize, srcResize, cv::Size(640, 640)); // w*h

        double time0 = getCurrentTime();
        const float meanValues[3] = {0.485 * 255, 0.456 * 255, 0.406 * 255};
        const float normValues[3] = {1.0 / 0.229 / 255.0, 1.0 / 0.224 / 255.0, 1.0 / 0.225 / 255.0};
        std::vector<float> inputTensorValues = substractMeanNormalize(srcResize, meanValues, normValues);

        auto input = _mnn_net->getSessionInput(_mnn_session, NULL);
        auto output = _mnn_net->getSessionOutput(_mnn_session, NULL);
        auto shape = input->shape();
        shape[0]   = 1;
        shape[2]   = srcResize.rows;  
        shape[3]   = srcResize.cols;   
        // auto input = _mnn_net->getSessionInput(_mnn_session, NULL);
        // float memoryUsage = 0.0f;
        // _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::MEMORY, &memoryUsage);
        // float flops = 0.0f;
        // _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::FLOPS, &flops);
        // int backendType[2];
        // _mnn_net->getSessionInfo(_mnn_session, MNN::Interpreter::BACKENDS, backendType);
        // DEBUG_LOG("Session Info: memory use %f MB, flops is %f M, backendType is %d", memoryUsage, flops, backendType[0]);

        // _mnn_net->resizeTensor(input, shape);
        // _mnn_net->resizeSession(_mnn_session);
        auto shapein = input->shape();
        std::vector<int> v = {1,(int)srcResize.channels(),srcResize.rows,srcResize.cols};
        auto nchwTensor = MNN::Tensor::create(v,halide_type_of<float>(),&inputTensorValues[0],MNN::Tensor::TENSORFLOW);
        input->copyFromHostTensor(nchwTensor);
        delete nchwTensor;

        _mnn_net->runSession(_mnn_session);
        std::shared_ptr<MNN::Tensor> outputUser(new MNN::Tensor(output, output->getDimensionType())); //nchw
        output->copyToHostTensor(outputUser.get());
        auto values = outputUser->host<float>();

        // MNN::Tensor feat_tensor(output, output->getDimensionType());
        // output->copyToHostTensor(&feat_tensor);
        // int size = feat_tensor.elementSize(); // 获取元素数量
        // float* data = feat_tensor.host<float>(); 

        // std::ofstream outfile("output_data.txt");

        // if (outfile.is_open())
        // {
        //     // 遍历张量的数据并写入文件
        //     for (int i = 0; i < size; ++i)
        //     {
        //         outfile << data[i]<<",";
        //     }
        //     outfile.close(); // 关闭文件
        //     std::cout << "Data saved to output_data.txt" << std::endl;
        // }
        // else
        // {
        //     std::cerr << "Unable to open file for writing." << std::endl;
        // }

        cv::Mat fMapMat(srcResize.rows, srcResize.cols, CV_32FC1); //  h* w  rows* cols
        ::memcpy(fMapMat.data, values, outputUser->stride(1) * sizeof(float));  // 只取第一个channel的数据
        //-----boxThresh-----
        cv::Mat norfMapMat;
        norfMapMat = fMapMat > 0.3;
        if (1)
        {
            cv::Mat src_tmp = norfMapMat.clone();

#ifdef WIN32
            std::string filename = "F:/2023_work/Gitlab/generalocr/generalocr/ncnn_ocr/" + std::to_string(NUM_IMG) + ".bmp";
#else
            std::string filename = "./rslt/" + std::to_string(NUM) + ".bmp";
#endif
            DEBUG_LOG(" filename :%s", filename.c_str());
            cv::imwrite(filename, src_tmp);
            NUM += 1;
        }}
        这个是我完整的推理代码了，保存下来的图像不对。这个模型是dbnet，backbone是mobilenetv3

**Comment by zhangshabao** [comment]
这个模型转换需要什么操作吗？

**Comment by zhangshabao** [comment]
cv::Mat srcResize;
    resize(src, srcResize, cv::Size(s.dstWidth, s.dstHeight));
    std::vector<float> inputTensorValues = substractMeanNormalize(srcResize, meanValues, normValues);
    std::array<int64_t, 4> inputShape{1, srcResize.channels(), srcResize.rows, srcResize.cols};
    auto memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);
    Ort::Value inputTensor = Ort::Value::CreateTensor<float>(memoryInfo, inputTensorValues.data(),
                                                             inputTensorValues.size(), inputShape.data(),
                                                             inputShape.size());
    assert(inputTensor.IsTensor());
    std::vector<const char *> inputNames = {inputNamesPtr.data()->get()};
    std::vector<const char *> outputNames = {outputNamesPtr.data()->get()};
    auto outputTensor = session->Run(Ort::RunOptions{nullptr}, inputNames.data(), &inputTensor,
                                     inputNames.size(), outputNames.data(), outputNames.size());
    assert(outputTensor.size() == 1 && outputTensor.front().IsTensor());
    std::vector<int64_t> outputShape = outputTensor[0].GetTensorTypeAndShapeInfo().GetShape();
    int64_t outputCount = std::accumulate(outputShape.begin(), outputShape.end(), 1,
                                          std::multiplies<int64_t>());
    float *floatArray = outputTensor.front().GetTensorMutableData<float>();
    std::vector<float> outputData(floatArray, floatArray + outputCount);

    //-----Data preparation-----
    int outHeight = (int) outputShape[2];
    int outWidth = (int) outputShape[3];
    size_t area = outHeight * outWidth;

    std::vector<float> predData(area, 0.0);
    std::vector<unsigned char> cbufData(area, ' ');

    for (int i = 0; i < area; i++) {
        predData[i] = float(outputData[i]);
        cbufData[i] = (unsigned char) ((outputData[i]) * 255);
    }
    这个是onnx的推理代码

**Comment by jxt1234** [comment]
resize(srcResize, srcResize, cv::Size(640, 640)); // w*h
改成 
    resize(srcResize, srcResize, cv::Size(640, 1024)); // w*h

**Comment by jxt1234** [comment]
nchwTensor 对应也换成和原模型一样的输入尺寸

**Comment by zhangshabao** [comment]
如果是固定尺寸的是直接resize就可以吗？
按照上面的推理方式，crnn模型转换后输出结果不对，模型在附件。正常输出w=97，h=80，现在w=97，h=1.
cv::Mat img = src;
        DEBUG_LOG(" init_model  :%d", init_model);
        if (init_model == false)
            return -8;

        double time0 = getCurrentTime();
        std::vector<float> inputTensorValues = substractMeanNormalize(img, meanValues, normValues);

        auto input = _mnn_net->getSessionInput(_mnn_session, NULL);
        auto output = _mnn_net->getSessionOutput(_mnn_session, NULL);
        auto shape = input->shape();
        shape[0] = 1;
        shape[2] = img.rows;
        shape[3] = img.cols;

        _mnn_net->resizeTensor(input, shape);
        _mnn_net->resizeSession(_mnn_session);
        auto shapein = input->shape();
        std::vector<int> v = {1, (int)img.channels(), img.rows, img.cols};
        auto nchwTensor = MNN::Tensor::create(v, halide_type_of<float>(), &inputTensorValues[0], MNN::Tensor::TENSORFLOW);
        input->copyFromHostTensor(nchwTensor);
        delete nchwTensor;

        _mnn_net->runSession(_mnn_session);
        std::shared_ptr<MNN::Tensor> outputUser(new MNN::Tensor(output, output->getDimensionType())); // nchw
        output->copyToHostTensor(outputUser.get());

        float *floatArray = outputUser->host<float>();
        outputData.clear();
        out_h = output->shape()[0];
        out_w = output->shape()[2];
        DEBUG_LOG(" out_h :%d out_w :%d",out_h,out_w);
        std::vector<float> floatArray_(floatArray, floatArray + out_h * out_w);
        outputData = floatArray_;
        推理代码是这样。
[crnn_model.zip](https://github.com/user-attachments/files/17374125/crnn_model.zip)

**Comment by jxt1234** [comment]
crnn 这种应该是可变的吧，导出onnx时要设置 dynamic_axes ，转 mnn 后使用用 resizeTensor -> resizeSession
