### ISSUE TITLE
MNN cpu inference createSession crash

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#305]
I have trained a yolov3 object detection model via tensorflow and the converted pb file works correctly in tensorflow environment. I have successfully convert the pb model into mnn model. Nothing happened during the converting procedure. But the program crashed when I use the converted model.

- MNN Source code: 0.2.0.9

- Nothing strange happened during converting procedure
![64603738-6cf4b180-d3f3-11e9-9e80-8800c8dfc3c6](https://user-images.githubusercontent.com/15725187/64608670-c82ba180-d3fd-11e9-8a95-358358e4aaa3.png)

- The test code was listed here as follows
![64603863-9ad9f600-d3f3-11e9-930f-beb6d4ee0b61](https://user-images.githubusercontent.com/15725187/64608734-e72a3380-d3fd-11e9-966f-84be5cf57379.png)

- Crashed when the program goes net->createSession(config)
![Screenshot from 2019-09-10 19-17-10](https://user-images.githubusercontent.com/15725187/64609479-9c112000-d3ff-11e9-957d-a0ecb2424d2d.png)

**Comment by MaybeShewill-CV** [comment]
@czy2014hust crashed here
![64609719-235e9380-d400-11e9-8670-42b5bb4a12d2](https://user-images.githubusercontent.com/15725187/64680336-2b760c00-d4b0-11e9-8b61-eb41b1059de7.png)
![64609729-26f21a80-d400-11e9-9885-fcaa7e0a4114](https://user-images.githubusercontent.com/15725187/64680347-316bed00-d4b0-11e9-900b-db3d155b9ef0.png)
![64609739-29ed0b00-d400-11e9-8035-fdbf36cb5907](https://user-images.githubusercontent.com/15725187/64680352-3335b080-d4b0-11e9-962f-bdf680340743.png)

**Comment by MaybeShewill-CV** [comment]
@jxt1234

**Comment by li-qing** [comment]
well, see that comment -- ellipsis & new axis masks are not supported now.

**Comment by MaybeShewill-CV** [comment]
@li-qing 能问问那两个对应什么op啊.我看看能不能在frozen tensorflow的时候处理下.

**Comment by li-qing** [comment]
strided slice

**Comment by MaybeShewill-CV** [comment]
@li-qing parameter->ellipsisMask() 和 parameter->newAxisMask()分别代表什么含义呢?^^

**Comment by kiyse** [comment]
@MaybeShewill-CV 你好 请问是怎么解决的吗？我试过多个tensorflow模型在android上使用cpu，createsession后失败，caffe的mnn模型倒是可以

**Comment by MaybeShewill-CV** [comment]
@kiyse 把后处理过程（其中用到了strided slice）剥离出来自己实现下就可以了:)

**Comment by kiyse** [comment]
@MaybeShewill-CV 好的 谢谢，但是我很疑惑，我在linux上使用同个mnn模型推理没有问题，不需要自己实现strided slice等操作。部署到android上却createsession失败.

**Comment by MaybeShewill-CV** [comment]
@kiyse 这个需要mnn的大佬们帮你解决了 我还没有在android上部署过==！

**Comment by v1incent** [comment]
> @MaybeShewill-CV 好的 谢谢，但是我很疑惑，我在linux上使用同个mnn模型推理没有问题，不需要自己实现strided slice等操作。部署到android上却createsession失败.

我也遇到了同样的问题，请问你解决了吗？

**Comment by kiyse** [comment]
试一下重新编译libmnn.so。我是通过重新编译，解决了代码模型和linux上的一样，但在Android studio上闪退的问题的.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"v1incent"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月22日(星期一) 中午11:45
收件人:&nbsp;"alibaba/MNN"<MNN@noreply.github.com&gt;;
抄送:&nbsp;"kiyse"<986827826@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/MNN] MNN cpu inference createSession crash (#305)





  
@MaybeShewill-CV 好的 谢谢，但是我很疑惑，我在linux上使用同个mnn模型推理没有问题，不需要自己实现strided slice等操作。部署到android上却createsession失败.
  
我也遇到了同样的问题，请问你解决了吗？
