### ISSUE TITLE
【模型转换】onnx op Unique和CastLike不支持

### ISSUE THREAD

**Issue by vincentme** [alibaba/MNN#3052]
这两个算子我的模型里需要使用，有支持计划吗？

**Comment by jxt1234** [comment]
Unique 应该是支持的，CastLike 你发一个 onnx 模型上来，我们看一下

**Comment by vincentme** [comment]
> Unique 应该是支持的，CastLike 你发一个 onnx 模型上来，我们看一下

你好，我这使用`./MNNConvert -f ONNX --OP`显示的支持op是172个，没有Unique和CastLike，版本2.9.6

模型打包上来了，这些不是深度学习的模型，而是前处理的操作用onnx实现了

[models.zip](https://github.com/user-attachments/files/17387686/models.zip)

**Comment by jxt1234** [comment]
已经支持，等待 3.0 版本同步

**Comment by jxt1234** [comment]
已经同步
