### ISSUE TITLE
intel subgroup支持异常

### ISSUE THREAD

**Issue by zeekimn** [alibaba/MNN#3059]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本: 最新版本
# Github Version:

![image](https://github.com/user-attachments/assets/e7a50812-20d8-45e0-ab4c-d8efa4d03cad
```

**Comment by jxt1234** [comment]
我们检查一下

**Comment by jxt1234** [comment]
如果设备不支持的话 pack 应该是 4 的，不会走到这个逻辑，确认在旧显卡上运行有问题么？

**Comment by Qxinyu** [comment]
可以提供下出错的模型吗，我们这边定位下原因
