### ISSUE TITLE
MNN已编译，pictureRecognition.out 运行时出错

### ISSUE THREAD

**Issue by cefengxu** [alibaba/MNN#306]
## 运行命令
> ./pictureRecognition.out mobilenet-v1-1.0.mnn testcat.jpg synset_words.txt

## 输出错误如下：
> Can't Find type=4 backend, use 0 instead

### 环境配置：
* ubuntu : 16.04
* protofbuf : 3.9.1
* cmake : 3.15.2

### 输入命令 ''cmake ..'' 后的输出如下：

> -- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	DEBUG: OFF
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	OpenMP: OFF
-- 	Hideen: FALSE
-- [*] searching *.c
-- [*] searching *.cc
-- [*] searching *.cpp
-- [*] searching *.s *.S
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/x86_64-linux-gnu/libOpenCL.so (found version "2.0") 
-- [*] linking MNN with OpenCL done
-- /home/xxx/xxx/MNN/build/benchmark
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/xxx/MNN/build

**Comment by czy2014hust** [comment]
这个只是提醒log，并不是错误log

**Comment by cefengxu** [comment]
@czy2014hust 
不是的，跟踪了代码。发现 pictureRecognition.cpp中：
> int main(int argc, const char* argv[]) {
   ...
    auto session = net->createSession(config);  **//运行到 此就走不下去了**

继续往下跟踪，发现 interpreter.cpp:
> Session* Interpreter::createSession(const ScheduleConfig& config) {
   ...   
       result->resize();  **// 运行到此 无法继续**

**Comment by cefengxu** [comment]
@czy2014hust 我怀疑是cl 或者 gl没有编译对，但已核实，libMNN.so 可以在ubuntu16.04上成功编译。

**Comment by niezhongliang** [comment]
你好，楼主有解决这个问题嘛？遇到相同的问题。

**Comment by cefengxu** [comment]
> 你好，楼主有解决这个问题嘛？遇到相同的问题。

更新1.0的版本， cmakelist里边，把cl 和 gl 关闭。
