### ISSUE TITLE
Android  运行 sd 报错tempcache 写入错误，这是什么

### ISSUE THREAD

**Issue by caojian001** [alibaba/MNN#3060]
Model resource path: /data/local/tmp/MNN/mnn_sd/mnn_sd/
Model type is stable diffusion 1.5
(Memory Lack) Each diffusion model will be initilized when using, freed after using.
Backend type: 3
Output image name: demo.jpg
Prompt text: a cute cat
Can't open file:/sys/devices/system/cpu/cpufreq/boost/affected_cpus
CPU Group: [ 0  1 ], 364800 - 2265600
CPU Group: [ 5  6 ], 499200 - 2956800
CPU Group: [ 2  3  4 ], 499200 - 3148800
CPU Group: [ 7 ], 480000 - 3302400
The device supports: i8sdot:1, fp16:1, i8mm: 1, sve2: 0
Can't open file:.tempcache
Load Cache file error.
First time initilizing may cost a few seconds to create cachefile, please wait ...
Load /data/local/tmp/MNN/mnn_sd/mnn_sd//text_encoder.mnn
[#--]  [ 33%]Load /data/local/tmp/MNN/mnn_sd/mnn_sd//unet.mnn
[##-]  [ 66%]Load /data/local/tmp/MNN/mnn_sd/mnn_sd//vae_decoder.mnn
[###]  [100%]
load_modules, 74, cost time: 326.504028 ms
text_encoder, 157, cost time: 1796.601074 ms
[---------------------]  [  0%]unet, 244, cost time: 42520.320312 ms
[#--------------------]  [  4%]unet, 244, cost time: 2433.574219 ms
[##-------------------]  [  9%]unet, 244, cost time: 2432.841064 ms
[###------------------]  [ 14%]unet, 244, cost time: 2436.229004 ms
[####-----------------]  [ 19%]unet, 244, cost time: 2437.259033 ms
[#####----------------]  [ 23%]unet, 244, cost time: 2435.204102 ms
[######---------------]  [ 28%]unet, 244, cost time: 2434.615234 ms
[#######--------------]  [ 33%]unet, 244, cost time: 2436.911133 ms
[########-------------]  [ 38%]unet, 244, cost time: 2437.819092 ms
[#########------------]  [ 42%]unet, 244, cost time: 2437.828125 ms
[##########-----------]  [ 47%]unet, 244, cost time: 2436.665039 ms
[###########----------]  [ 52%]unet, 244, cost time: 2436.689209 ms
[############---------]  [ 57%]unet, 244, cost time: 2438.137207 ms
[#############--------]  [ 61%]unet, 244, cost time: 2754.051025 ms
[##############-------]  [ 66%]unet, 244, cost time: 2897.873047 ms
[###############------]  [ 71%]unet, 244, cost time: 2898.212158 ms
[################-----]  [ 76%]unet, 244, cost time: 2896.182129 ms
[#################----]  [ 80%]unet, 244, cost time: 2893.098145 ms
[##################---]  [ 85%]unet, 244, cost time: 2890.078125 ms
[###################--]  [ 90%]unet, 244, cost time: 2890.336182 ms
[####################-]  [ 95%]unet, 244, cost time: 2896.433105 ms
vae_decoder, 298, cost time: 27462.029297 ms
run, 329, cost time: 124296.226562 ms
Update cache to .tempcache, size = 1449884
Open .tempcache error
Write Cache File error!

**Comment by jxt1234** [comment]
.tempcache 没有权限打开，需要对应修改一下相关代码。设到可写的路径上
