### ISSUE TITLE
转int8模型时效果不一致

### ISSUE THREAD

**Issue by qiuzhewei** [alibaba/MNN#3062]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux

# Github版本:
# Github Version:
MNN主页的zip包，昨天下载的

# 编译方式:
# Compiling Method

```
cd build
cmake ..  -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_QUANTOOLS=ON
make -j 8
```

你好，我在使用检测模型，原先的onnx模型是fp32的，把onnx模型转fp16，出来的结果基本都对。但是在我转int8时，出现了效果上的不一致
转换步骤：
手动修改testMNNFromOnnx.py MNN模型推理那一行
```
convert = mnnconvert_name + ' -f ONNX --bizCode MNN --modelFile onnx/test.onnx --MNNModel convert_cache.mnn --weightQuantBits 8 --weightQuantAsymmetric  --thredhold 1 --keepInputFormat=1 --testdir onnx'
```
然后执行
```
python ../tools/script/testMNNFromOnnx.py picodet_xs_320.onnx
```
出来的结果是"Test Success"，也就是说我在转int8时，指定阈值为1效果基本对的上
但是随后我执行以下两条命令
```
./ModuleBasic.out convert_cache.mnn onnx 0 0 1000
./checkFile.out output/0_0.txt onnx/save_infer_model/scale_0.tmp_0.txt 1
```
出来一大堆对不上的结果
为什么两种方法一次能对得上，另外一次对不上呢？照理说都是和onnx模型推理结果对比的
另外我把testMNNFromOnnx.py中的输入改成了自己的图片后，int8模型和fp32出来的结果，只差1-2个像素点（框的坐标），但是按照原文random的形式生成输入，int8模型和fp32出来的结果有些框相差很大，好几十个像素点差距，这又是为什么呢？

**Comment by jxt1234** [comment]
这个有误差是正常的吧。 --thredhold 1 这个是相对误差，1的话已经是 100% 了，换言之忽略误差了。默认 ModuleBasic 的值应该是 0.01

**Comment by qiuzhewei** [comment]
相对误差是指：比如我的输出是40，--thredhold 1代表着[0, 80]都是可以接受的范围吗？
另外如果想得到性能和原模型接近的int8模型，是不是需要使用quantized.out这个工具进行校正？

**Comment by jxt1234** [comment]
1. 是的。所以设成 1 基本上不比较结果是否正确了。2. 可以考虑加上 --weightQuantBlock=128 （128个数用一个 scale / offset），增加 scale/offset数量，提升精度
