### ISSUE TITLE
tilite模型模型转换正常，执行的时侯会crash

### ISSUE THREAD

**Issue by laofuzi123321** [alibaba/MNN#3065]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android arm64

# Github版本:
# Github Version:
2.7.0

模型已经贴在这里：
[model.zip](https://github.com/user-attachments/files/17552498/model.zip)

**Comment by jxt1234** [comment]
可以复现，我们查下看看

**Comment by jxt1234** [comment]
[tflite.patch](https://github.com/user-attachments/files/17556235/tflite.patch)

可以先合如上的 patch 修正，后续会同步

**Comment by jxt1234** [comment]
已经同步
