### ISSUE TITLE
Request `aarch64 Linux` binaries for MNN package

### ISSUE THREAD

**Issue by lakshanthad** [alibaba/MNN#3069]
Hello,

Our Raspberry Pi CI workflows are currently failing on MNN export of YOLO models due to the absence of `aarch64 Linux` binaries for the MNN package.
https://github.com/ultralytics/ultralytics/actions/runs/11608221105/job/32326211583

Will there be support anytime soon? Thank you.

MNN export PR FYI:
https://github.com/ultralytics/ultralytics/pull/16802

**Comment by wangzhaode** [comment]
Since GitHub action does not provide aarch64 runner, no corresponding Python package has been released. We are trying to use self-hosted runner and release aarch64 Python package as soon as possible.

**Comment by wangzhaode** [comment]
Thank @lakshanthad  for the suggestion on the issue. The MNN 2.9.6 aarch64 Linux Python wheel has been released

**Comment by lakshanthad** [comment]
Thanks a lot @wangzhaode. We will add and experiment this with our Raspberry CI runners!
