### ISSUE TITLE
segmentation fault when running benchmark.out with opencl in android 

### ISSUE THREAD

**Issue by twmht** [alibaba/MNN#307]
Hi,

I have built MNN libraries and  tried to run benchmark.out on my Android device (HTC-10) and RK3399 with android.

CPU works fine. But OPENCL would throw segmentation fault.

I just changed the forward type and keep the other parameter unchanged.

any idea?

**Comment by twmht** [comment]
segmentation fault occurs in https://github.com/alibaba/MNN/blob/master/benchmark/benchmark.cpp#L136

**Comment by twmht** [comment]
by the way, vulkan type works fine in my HTC-10.

**Comment by twmht** [comment]
it runs with inception-v3.mnn

turning on DEBUG mode,

```
...
===> compute shape: InceptionV3/Logits/SpatialSqueeze, [90]
Inputs:
1, 1, 1, 1001,
Outputs:
1, 1001,
Segmentation fault
```

**Comment by hacker-joe** [comment]
The bug has been solved. Please update the code in a few days and try again
