### ISSUE TITLE
yolov11转onnx，使用onnx转mnn模型成功，onnx结果正确，但mnn推理结果有一定偏移，有些类型判断不准确了，这是什么原因？

### ISSUE THREAD

**Issue by wanggogogo** [alibaba/MNN#3071]
无论量化与否都是一样的结构。
现象类似于假设类别列表为：className['A1','A2','B1','B2']
原来训练精准的模型，A1判断为A2  B1判断为B2了

**Comment by wanggogogo** [comment]
Test Node : /model.0/act/Mul False
Error is between  /model.0/conv/Conv  and  /model.0/act/Mul
onnx\test.onnx
tensor(float)
['/model.0/conv/Conv_output_0']
inputs:
images
onnx/
outputs:
onnx//model.0/conv/Conv_output_0.txt (1, 16, 160, 160)
onnx//model.0/conv/
./MNNConvert not exist in this path. Use pymnn instead of C++ to test
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.9
[11:57:38] @ 46: ONNX Model ir version: 10
[11:57:38] @ 47: ONNX Model opset version: 10
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ /model.0/conv/Conv_output_0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01

Test Node : /model.0/conv/Conv False
Error is between  /model.0/conv/Conv  and  /model.0/conv/Conv   用testMnnFromOnnx debug了一下，报第一个卷积层有问题。       
修改model.export(format='onnx',imgsz=320, opset=10)  这里的opset也没有用~

**Comment by jxt1234** [comment]
1. 更新 mnn 并用 C++ 编译 MNNConvert 看下
2. onnx 模型发上来看一下

**Comment by wanggogogo** [comment]
[models2.zip](https://github.com/user-attachments/files/17624962/models2.zip)
感谢回复！
模型文件已经上传。

### 重新测试
我在构建了MNNConvert.exe的文件夹中执行testMnnFromOnnx.py  无论DEBUG和非DEBUG模式都提示成功。
下面是打印的信息
Dir exist
onnx\test.onnx
tensor(float)
['output0']
inputs:
images
onnx/
outputs:
onnx/output0.txt (1, 58, 2100)
onnx/
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.9
[07:36:36] D:\PycharmProjects\MNN2\MNN\tools\converter\source\onnx\onnxConverter.cpp:46: ONNX Model ir version: 10
[07:36:36] D:\PycharmProjects\MNN2\MNN\tools\converter\source\onnx\onnxConverter.cpp:47: ONNX Model opset version: 17
[07:36:36] D:\PycharmProjects\MNN2\MNN\tools\converter\source\onnx\onnxConverter.cpp:146: Check it out ==> /model.11/Resize_output_0 has empty input, the index is 1
[07:36:36] D:\PycharmProjects\MNN2\MNN\tools\converter\source\onnx\onnxConverter.cpp:146: Check it out ==> /model.14/Resize_output_0 has empty input, the index is 1
Start to Optimize the MNN Net...
inputTensors : [ images, ]
outputTensors: [ output0, ]
Converted Success!
Check convert result by onnx, thredhold is 0.01
images
output: output0
output0: (1, 58, 2100, )
TEST_SUCCESS
这样是否可以判断，onnx转mnn的模型是正确的，推理结果应该是相似的。

### 当前依旧存在的问题
那我现在出现的下面的问题，会是我数据预处理或者后处理导致的吗？
现象类似于假设类别列表为：className['A1','A2','B1','B2']
原来训练精准的模型，A1判断为A2 B1判断为B2了，A2和B2类型基本保持原来的类型

### 我的测试代码
[yolo11_mnn_video.zip](https://github.com/user-attachments/files/17625083/yolo11_mnn_video.zip)

再次感谢回复~

**Comment by jxt1234** [comment]
应该是数据前后处理的原因，用新转的模型测试吧。mnn 现在默认保留原始模型的输入输出内存布局，可以减少布局转换代码不对造成的问题。

**Comment by wanggogogo** [comment]
是的，
original_image = cv2.imread(image_path)
            ih, iw, _ = original_image.shape
            length = max((ih, iw))
            scale = length / 320
            image = np.pad(original_image, [[0, length - ih], [0, length - iw], [0, 0]], 'constant')
            image = cv2.resize(image, (320, 320), 0., 0., cv2.INTER_LINEAR, -1, [0., 0., 0.],
                               [1. / 255., 1. / 255., 1. / 255.])  
这个预处理有问题~，感谢回复~
