### ISSUE TITLE
使用quantized.out进行多输入序列模型量化出错

### ISSUE THREAD

**Issue by LXWLZU** [alibaba/MNN#3073]
平台:  x86 Linux
Github版本: 最新2.9.6
编译方式: cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_QUANTOOLS=ON

使用quantized.out工具进行多输入序列模型的量化时出现以下问题：
（1）feature_quantize_method选择EMA方法，量化过程有报错log，量化后模型创建Session错误（Compute Shape Error）
    quantize with EMA: 100.00 %
    Reshape error: 1 -> 128
    Reshape error: 1 -> 256
    Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_output_0
    Can't find input extraTensorDescribe for /enc/emb_gru/Tanh_output_0
    Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_1_output_0
    ......
（2）feature_quantize_method选择ADMM方法，量化过程报错Segmentation fault (core dumped)
（3）feature_quantize_method选择KL方法，量化模型输出相较于量化前差异很大

尝试使用MNNPythonOfflineQuant中python工具进行量化（EMA），量化后模型中间算子输出包含nan，定位到是由Gemm转化的Conv算子输出了nan，而对于nan的输入，后续激活函数输出了1
![20241111-105538](https://github.com/user-attachments/assets/b864e0fd-b607-48c6-8630-252eab90c0d3)
请问以上问题是否是MNN量化实现有点问题或者我的模型设计有问题呢？（可复现的资源https://drive.google.com/file/d/1zyFIADiZxIC4nzbcndv14Ex4-YiLdJrb/view?usp=sharing）

**Comment by jxt1234** [comment]
我们先看一下，可以先使用动态量化方案替代：
1. 打开 MNN_LOW_MEMORY 编译宏编译 MNN （支持动态量化功能）
2. 转换模型时加 --weightQuantBits=8 （量化权重）
3. 使用 mnn 模型时 memory 设成 low

**Comment by v0jiuqi** [comment]
> 平台: x86 Linux Github版本: 最新2.9.6 编译方式: cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_QUANTOOLS=ON
> 
> 使用quantized.out工具进行多输入序列模型的量化时出现以下问题： （1）feature_quantize_method选择EMA方法，量化过程有报错log，量化后模型创建Session错误（Compute Shape Error） quantize with EMA: 100.00 % Reshape error: 1 -> 128 Reshape error: 1 -> 256 Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_output_0 Can't find input extraTensorDescribe for /enc/emb_gru/Tanh_output_0 Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_1_output_0 ...... （2）feature_quantize_method选择ADMM方法，量化过程报错Segmentation fault (core dumped) （3）feature_quantize_method选择KL方法，量化模型输出相较于量化前差异很大
> 
> 尝试使用MNNPythonOfflineQuant中python工具进行量化（EMA），量化后模型中间算子输出包含nan，定位到是由Gemm转化的Conv算子输出了nan，而对于nan的输入，后续激活函数输出了1 ![20241111-105538](https://private-user-images.githubusercontent.com/51389854/384764870-b864e0fd-b607-48c6-8630-252eab90c0d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTM5NjksIm5iZiI6MTczMjE1MzY2OSwicGF0aCI6Ii81MTM4OTg1NC8zODQ3NjQ4NzAtYjg2NGUwZmQtYjYwNy00OGM2LTg2MzAtMjUyZWFiOTBjMGQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxNDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZGNmMGVkNDlkOTNhZmUzN2Q3MDU5ZWY4MzA3MjZhMjA3NmE3NjVlOGQ4MDYwZDJiN2MyYjlmMDdmNzIzNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f9hMgfrvM2oKHcPWqPtEon4y-xzNx9LooQ8Nqzo5cG4) 请问以上问题是否是MNN量化实现有点问题或者我的模型设计有问题呢？（可复现的资源[https://drive.google.com/file/d/1zyFIADiZxIC4nzbcndv14Ex4-YiLdJrb/view?usp=sharing）](https://drive.google.com/file/d/1zyFIADiZxIC4nzbcndv14Ex4-YiLdJrb/view?usp=sharing%EF%BC%89)
这个链接我们公司电脑无法访问。资源可发邮箱：ld1srcv0@163.com

**Comment by jxt1234** [comment]
fixed by 3.0.1

**Comment by J-alchemist** [comment]
> 平台: x86 Linux Github版本: 最新2.9.6 编译方式: cmake .. -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_QUANTOOLS=ON
> 
> 使用quantized.out工具进行多输入序列模型的量化时出现以下问题： （1）feature_quantize_method选择EMA方法，量化过程有报错log，量化后模型创建Session错误（Compute Shape Error） quantize with EMA: 100.00 % Reshape error: 1 -> 128 Reshape error: 1 -> 256 Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_output_0 Can't find input extraTensorDescribe for /enc/emb_gru/Tanh_output_0 Can't find input extraTensorDescribe for /enc/emb_gru/Sigmoid_1_output_0 ...... （2）feature_quantize_method选择ADMM方法，量化过程报错Segmentation fault (core dumped) （3）feature_quantize_method选择KL方法，量化模型输出相较于量化前差异很大
> 
> 尝试使用MNNPythonOfflineQuant中python工具进行量化（EMA），量化后模型中间算子输出包含nan，定位到是由Gemm转化的Conv算子输出了nan，而对于nan的输入，后续激活函数输出了1 ![20241111-105538](https://github.com/user-attachments/assets/b864e0fd-b607-48c6-8630-252eab90c0d3) 请问以上问题是否是MNN量化实现有点问题或者我的模型设计有问题呢？（可复现的资源[https://drive.google.com/file/d/1zyFIADiZxIC4nzbcndv14Ex4-YiLdJrb/view?usp=sharing）](https://drive.google.com/file/d/1zyFIADiZxIC4nzbcndv14Ex4-YiLdJrb/view?usp=sharing%EF%BC%89)

请问mnn的多输入序列模型量化如何解决这个问题呢？能分享一下吗？

**Comment by LXWLZU** [comment]
@J-alchemist 使用最新MNN编译出的量化工具，参照https://mnn-docs.readthedocs.io/en/latest/tools/quant.html#mnn 文档设置即可

**Comment by J-alchemist** [comment]
> [@J-alchemist](https://github.com/J-alchemist) 使用最新MNN编译出的量化工具，参照https://mnn-docs.readthedocs.io/en/latest/tools/quant.html#mnn 文档设置即可

我想再请教您一个问题：关于input_0目录下的某个输入的数据文件xx.txt，该文件的数据是按照一行一行作为模型的一帧矫正数据吗？   因为我看您上面的数据是以一个数据作为一行
