### ISSUE TITLE
LLM分支导出Bge-small模型出问题

### ISSUE THREAD

**Issue by turingboot** [alibaba/MNN#3074]
问题描述：使用llm-export 将Bge-small-v1.5-zh导出为mnn的，报错如下
![image](https://github.com/user-attachments/assets/1c7cb7d1-d283-4f2d-a75e-bf91fd661b3f)
1.mnn貌似没有正常导出，llm-export好像中间会导出一个onnx的模型，导出onnx的时候会有报错， mnn模型文件也没有导出
2.该报错我初步看了下，应该是transformers库的版本问题导致，但是降级很多个版本后还是有问题。

期望： 
能否在llm-export工具下添加能够稳定运行的requirements.txt

平台：Linux
工具链：
torch                       2.4.1
torchaudio              2.4.1+cu124
torchmetrics           1.4.3
torchvision              0.19.1+cu124
transformers           4.46.2

**Comment by jxt1234** [comment]
已经修正，等待同步

**Comment by jxt1234** [comment]
已经同步
