### ISSUE TITLE
MNN  newExecutor 方法每次返回的 指针地址是一样，是 MNN bug 吗？

### ISSUE THREAD

**Issue by dearwind153** [alibaba/MNN#3078]
1. 问题描述

    （1）工程中，pytorch 训练的模型，转换为 onnx 后，分为 4 个模型，生成 4 个 mnn 模型
    （2）模型依次初始化，但初始化后，发现 newExecutor 方法每次返回的 指针地址是一样
    （3）参考 https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id11 中的使用方法
    
![bc93038ced6b0f117b445476df69955](https://github.com/user-attachments/assets/4d8a3d2b-bc45-4f48-b9a7-3339774a143f)

    （4）打印  创建的 newExecutor 返回的指针地址，都是一样的数值，而依次创建的 module 地址是不同的， 跟踪 MNN 源码如下
    
![99f6d165c30db0bab7dc4aae69c3471](https://github.com/user-attachments/assets/2c53b6de-4f67-4394-8569-6834d1dba6a7)

**Comment by jxt1234** [comment]
这个应该是你把 executor 删掉了，巧合而已

**Comment by jxt1234** [comment]
static 是表示这是一个静态方法，不表示它是静态变量。每次创建是不一样的，你可以单独写个程序多 new 几次 executor

**Comment by dearwind153** [comment]
测试发现，同一线程中，newExecutor 获得的指针地址是一样的，不同线程 newExecutor 获得的指针地址是不同的

![a3ea39ec625169aa2fc1120cf5c75c5](https://github.com/user-attachments/assets/cd902f5a-0b01-4f8c-8754-2ba474a47b58)

**Comment by dearwind153** [comment]
**在主进程中，init 时，创建线程，仅用于创建 executor，发现这样，获取到的 executor 指针地址是不同的，似乎是正常的
