### ISSUE TITLE
createSession()报错

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#309]
1. 使用createFromFile(MobileNetV2_224.mnn) 创建interpreter
2. 使用createFromSession()创建session
3. 使用CPU运行MobileNetV2的benchmark
报错：
Segmentation fault (core dumped)

具体在MNN/source/backend/cpu/CPUBackend.cpp：178行
` auto exe = iter->second->onCreate(inputs, outputs, op, this);`

谢谢！

**Comment by GaussRieman** [comment]
![image](https://user-images.githubusercontent.com/20228088/64676370-067d9b00-d4a8-11e9-9e91-1620d21a431e.png)

就是把之前用createFromBuffer的方式改为用createFromFile，因为createFromBuffer需要revertMNNModel.hpp，所以想改为用createFromFile。

**Comment by czy2014hust** [comment]
用的是我们提供的benchmark模型？那必须用revertMNNModel。

**Comment by GaussRieman** [comment]
> 用的是我们提供的benchmark模型？那必须用revertMNNModel。

-_-!  原来如此！ 还有一个问题是，我在Android上读我们自己的模型，用OpenCL可以正常读，用CPU就会报错：
![image](https://user-images.githubusercontent.com/20228088/64677108-8a845280-d4a9-11e9-85d8-7b56d635a261.png)

这个可能是什么原因呢？  用Opencl可以正常create，用CPU就不行了

多谢！

**Comment by czy2014hust** [comment]
请检查模型文件，读模型文件跟指定BackendType无关。
