### ISSUE TITLE
Qwen2.5-0.5B-Instruct 8bit量化 动态加载LoRA精度下降严重

### ISSUE THREAD

**Issue by jfduma** [alibaba/MNN#3098]
实践中以Qwen2.5-0.5B-Instruct为基础模型，针对不同任务训练多个LoRA模型。训练工具为llamafactory-cli
训练后将基础模型进行8bit量化并导出mnn模型，并将多个LoRA模型导出为mnn格式。
在设备上进行验证【cpu + fp16】，发现准确率比量化前下降约15%~40%不等。

尝试过使用MNNConvert --fp16格式导出模型，但是使用apply-lora.py脚本时失败了。失败信息如下：
  File "/byte_auto_model/jiangfeng/mnn/tools/script/apply_lora.py", line 72, in apply_lora
    tag = names[1].split('.')[1] + names[3]
IndexError: list index out of range
(Pdb) names
['', 'q_proj', 'Add_output_0__matmul_converted']

也尝试过直接使用GPTQ的8bit量化版本进行LoRA sft然后转mnn格式，准确率没有提升。

这里想请教两个问题：
1. 如何导出fp16格式的基础模型和LoRA模型？
2. Qwen2.5+LoRA模型转换成8bit量化mnn格式【不合并基模和LoRA，因为需要动态加载多个LoRA】后能否对LoRA进行继续训练？如何操作？

**Comment by jxt1234** [comment]
8bit量化建议 llmexport 时先 --export onnx ，再由 onnx 转 mnn 。目前直接导出 mnn 的话 8bit 量化好像有点问题。

**Comment by jfduma** [comment]
谢谢，我试一下

**Comment by scutzhe** [comment]
我试着转了chatglm3-6b模型，直接转的效果优于先转onnx再转mnn，但是整体输出效果还是不尽人意

**Comment by jxt1234** [comment]
该问题是 tie embedding 的问题，已经修改了
