### ISSUE TITLE
错误的断言 MNN_ASSERT(srcBuffer.dimensions == dstBuffer.dimensions);

### ISSUE THREAD

**Issue by tp-nan** [alibaba/MNN#3099]
https://github.com/alibaba/MNN/blob/707b8a41b25e3d0b7c4a39cd81109d7074ca3c28/source/core/Backend.cpp#L109

DEBUG模式下断言失败，模型本身是个分类模型， srcBuffer.dimensions 为2，  dstBuffer.dimensions 为4，（看了下多了长和宽都为1）

**Comment by jxt1234** [comment]
运行的代码是什么？按理这种情况确实不应该调用 onCopyBuffer
