### ISSUE TITLE
OpenCL 配置共享运行时，出现崩溃

### ISSUE THREAD

**Issue by Jerry3062** [alibaba/MNN#3100]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
OS：windows 10
CPU：intel i7-13700K
GPU：NVIDIA RTX 4090
tool chain：tool chain:Visual Studio 生成工具 2022 LTSC 17.8 , 编译器为cl.exe

# Github版本:
# Github Version:
3.0.0 

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
mnn_3.0.0_windows_x64_cpu_opencl.zip

恳请帮我看看这个问题：
我使用github release下载的MNN 3.0.0在windows10上，配置OpenCL运行时，同时配置共享运行时，会出现崩溃。崩溃应该跟模型相关，因为我删除掉某些模型就能正常运行。同时我debug断点到的崩溃位置也不固定。CPU的共享运行时则能正常运行。

代码链接：
通过网盘分享的文件：mnn_ocl_crash.zip
链接: https://pan.baidu.com/s/1YArn8uNWWoGX7SmHWv-kJw?pwd=7gfq 提取码: 7gfq

**Comment by jxt1234** [comment]
这里不能用百度网盘，可以换成别的。比如发我邮箱？

**Comment by Jerry3062** [comment]
> 这里不能用百度网盘，可以换成别的。比如发我邮箱？

好的，已经发您邮箱啦。

**Comment by jxt1234** [comment]
已经收到

**Comment by Jerry3062** [comment]
用3.0.0转换的模型，目前没有发现这个问题了。
