### ISSUE TITLE
MNN KL量化精度损失严重，推理有报错打印

### ISSUE THREAD

**Issue by sobresee** [alibaba/MNN#3105]
# 问题:  

1. KL量化精度损失严重
2. KL量化的模型与ADMM量化的模型结构不同

# 现象：
## KL量化：

1. 精度损失严重
2. 模型推理时控制台有多条  this relu int8 implementation has error when input output quant info mismatch  的打印
3. 利用timeProfile.out测试模型，有Int8ToFloat/FloatToInt8算子信息
4.  ![fb158c55a1e48101ab0847268f9d2c8b (1)](https://github.com/user-attachments/assets/110a6fd1-4d78-4a2d-81b4-59147e415cfa)
## ADMM量化：

1. 精度损失较小
2. 推理时控制台没有打印this relu int8 implementation has error when input output quant info mismatch打印
3. 利用timeProfile.out测试模型，没有Int8ToFloat/FloatToInt8算子信息
# 平台:  
SSC30K--ARMV7

# Github版本:
MNN-3.0.0和MNN-2.9.3均有该问题

# 编译方式:
cmake .. -DMNN_BUILD_TOOLS=ON -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=armv7 -DCMAKE_C_COMPILER=/opt/Mstar/gcc-sigmastar-9.1.0-2019.11-neon-patch-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/opt/Mstar/gcc-sigmastar-9.1.0-2019.11-neon-patch-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -DMNN_LOW_MEMORY=ON -DMNN_ARM82=OFF

# 模型转换指令:
./MNNConvert -f ONNX --modelFile gtcrn_simple.onnx --MNNModel gtcrn_simple.mnn --bizCode MNN

# 模型量化指令:   
./quantized.out gtcrn_simple.mnn gtcrn_simple_kl.mnn quant.json

# onnx模型:   
https://github.com/Xiaobin-Rong/gtcrn/blob/main/stream/onnx_models/gtcrn_simple.onnx

# 量化配置文件:
{
    "path": "/opt/MNNDevelop/SoundDemo/quantize_data",
    "used_image_num": 128,
    "batch_size": 8,
    "feature_quantize_method": "KL",
    "weight_quantize_method": "MAX_ABS",
    "input_type": "sequence",
    "debug": true,
    "inputs": [
        {
            "name": "mix",
            "shape": [
                1,
                257,
                1,
                2
            ]
        },
        {
            "name": "conv_cache",
            "shape": [
                2,
                1,
                16,
                16,
                33
            ]
        },
        {
            "name": "tra_cache",
            "shape": [
                2,
                3,
                1,
                1,
                16
            ]
        },
        {
            "name": "inter_cache",
            "shape": [
                2,
                1,
                33,
                16
            ]
        }
    ],
    "outputs": [
        "enh",
        "conv_cache_out",
        "tra_cache_out",
        "inter_cache_out"
    ]
}

**Comment by jxt1234** [comment]
先更新到 3.0.1 试试

**Comment by sobresee** [comment]
更新到3.0.1后，这个问题还是存在

**Comment by jxt1234** [comment]
问题已知，修正中

**Comment by jxt1234** [comment]
3.0.2 修正，其他问题重新提 issue 吧
