### ISSUE TITLE
关于 MNN-NPU使用说明 的问题

### ISSUE THREAD

**Issue by XTaoWang** [alibaba/MNN#3109]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本: 3.0
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log: 无

```
粘贴在这里
Paste log here or pastebin
```
问题1 ：backend type设置成：MNN_FORWARD_USER_0  这里需要怎么设置，目录在哪里。
问题2:这些 执行可执行程序（需动态加载：libMNN_NPU.so, libhiai_ir_build.so, libhiai_ir.so, libhiai.so） 这些 jar 都生成了，还需要动态配置吗？
问题3：怎么验证 在 npu 的设备上验证
以上问题基于在android/demo  谢谢

**Comment by jxt1234** [comment]
1. config.type 设成 MNN_FORWARD_USER_0
2. 需要在 java 上动态加载 System.load：libMNN_NPU.so, libhiai_ir_build.so, libhiai_ir.so, libhiai.so
3. 找华为手机如 mate40 可以测试

**Comment by XTaoWang** [comment]
> 1. config.type 设成 MNN_FORWARD_USER_0
> 2. 需要在 java 上动态加载 System.load：libMNN_NPU.so, libhiai_ir_build.so, libhiai_ir.so, libhiai.so
> 3. 找华为手机如 mate40 可以测试

config.type 是模型导出后的 config.json 文件中的  "backend_type": "cpu" 参数修改成 npu 吗

**Comment by XTaoWang** [comment]
> 上面是使用 mnn 加载模型推理的配置。mnn llm 目前不支持使用 npu
那老师，这里的 
1.config.type 设成 MNN_FORWARD_USER_0 中的回答
就是模型导出后的 config.json 文件中的 "backend_type": "cpu" 参数修改成 npu 吗？
还是在其他地方改？要是其他中改，告知下目录路径，谢谢

**Comment by XTaoWang** [comment]
参考这个文档 https://mnn-docs.readthedocs.io/en/latest/inference/session.html 
修改
/** session schedule config */
struct ScheduleConfig {
    /** which tensor should be kept */
    std::vector<std::string> saveTensors;
    /** forward type */
    MNNForwardType type = MNN_FORWARD_USER_0;
    /** CPU:number of threads in parallel , Or GPU: mode setting*/
    union {
        int numThread = 4;
        int mode;
    };

    /** subpath to run */
    struct Path {
        std::vector<std::string> inputs;
        std::vector<std::string> outputs;

        enum Mode {
            /**
             * Op Mode
             * - inputs means the source op, can NOT be empty.
             * - outputs means the sink op, can be empty.
             * The path will start from source op, then flow when encounter the sink op.
             * The sink op will not be compute in this path.
             */
            Op = 0,

            /**
             * Tensor Mode
             * - inputs means the inputs tensors, can NOT be empty.
             * - outputs means the outputs tensors, can NOT be empty.
             * It will find the pipeline that compute outputs from inputs.
             */
            Tensor = 1
        };

        /** running mode */
        Mode mode = Op;
    };
    Path path;

    /** backup backend used to create execution when desinated backend do NOT support any op */
    MNNForwardType backupType = MNN_FORWARD_USER_0;

    /** extra backend config */
    BackendConfig* backendConfig = nullptr;
};
修改 Interpreter_hpp类中的    MNNForwardType type ，代码如上，
在 MNNNetNative java 类中添加 
    static {
        System.loadLibrary("MNN");
        loadGpuLibrary("MNN_Vulkan");
        loadGpuLibrary("MNN_CL");
        loadGpuLibrary("MNN_GL");
        System.loadLibrary("mnncore");


        System.loadLibrary("MNN_NPU");
        System.loadLibrary("hiai_ir_build");
        System.loadLibrary("hiai_ir");
        System.loadLibrary("hiai");
    }
不知道对不对

**Comment by jxt1234** [comment]
1. 是你创建 session 或者 module 的 runtimemanager 里面修改 config.type = MNN_FORWARD_USER_0
2. 如果你是用 mnn llm ，这个不支持 npu
