### ISSUE TITLE
MNN fp16与fp32数据输入结果差异很大

### ISSUE THREAD

**Issue by Fatemanx** [alibaba/MNN#3113]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
linux

# Github版本:
2.8.4

# 编译方式:
![image](https://github.com/user-attachments/assets/ed76a982-f008-4c4d-8b04-2a36bef927e4)

# 问题描述
MNN支持fp16推理，我在测试时发现，fp16/fp32的数据输入，结果差异很大，近乎于不一致；
选择CPU计算后端，PrecisionMode设置为Precision_Low
对于fp16的数据输入：input_tensor->buffer().type = halide_type_t(halide_type_bfloat, 16);
其他的设置完全一致；我的理解来看，似乎两种情况下差异应该不会很大？

**Comment by jxt1234** [comment]
1. fp16 的输入方式与 fp32 是一样的，不要改 input_tensor->buffer().type。
2. fp16 有可能会在运行时越界。
3. 先用测试工具测试: https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out。

**Comment by Fatemanx** [comment]
> 1. fp16 的输入方式与 fp32 是一样的，不要改 input_tensor->buffer().type。
> 2. fp16 有可能会在运行时越界。
> 3. 先用测试工具测试: [https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out。](https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out%E3%80%82)

你可能误解我的意思了。我不是指模型权重的那个fp16/fp32。我指的是模型的输入数据，比如一张图片，可能是fp16表示的。那么我的模型选择fp16精度的时候，如果我输入fp32表示的图片，是需要做类型转换的？那比如我现在用fp16去表示这张图片，大小都会不一样，所以我应该”告诉“MNN需要读取多少字节的输入数据吧？所以我才去设置的 input_tensor->buffer().type，让MNN知道需要读多少数据；但是这样尝试下来，结果差异很大
