### ISSUE TITLE
无法登录阿里云账号

### ISSUE THREAD

**Issue by Win-commit** [alibaba/MNN#3116]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Windows MNN 1.3.6

无法使用手机验证码登录；阿里云账号登录；支付宝扫码登录；均出现 Something went wrong: 401 Unauthorized

**Comment by jxt1234** [comment]
可以在这里下载 release 的版本
https://github.com/alibaba/MNN/releases
