### ISSUE TITLE
GEMM超过GDLOPS峰值

### ISSUE THREAD

**Issue by MrJungle1** [alibaba/MNN#3121]
![image](https://github.com/user-attachments/assets/7a4c4cfa-5564-40c0-9f29-cfede8b4cbd5)
这里是一个conv1d，kernel是1，等价于一个1024*1024 x 1024*1024的GEMM，跑天玑9300的最大核心，单线程，3.25的频率，按照MNN打印的最小耗时，19.148001ms，实际GFLOPS=2*1024*1024*1024/19.148001/1000000=112.15184540673462，但是这个核心的理论峰值是3.25*8*4=104（4个fma单元），使用高叔叔的cpufp实侧性能也是103.4GFLOPS，按照MNN打印的计算量也确实等价1024*1024 x 1024*1024的GEMM，但是MNN现在超过峰值了，这里是怎么做到的。
![image](https://github.com/user-attachments/assets/757197a6-16be-49fc-ac4a-0b5c5601614f)

**Comment by jxt1234** [comment]
应用 strassen 算法的原因，更多算法可以参考 https://zhuanlan.zhihu.com/p/3947249688

**Comment by MrJungle1** [comment]
@jxt1234 我怎么可以确定是否用了 strassen 算法

**Comment by jxt1234** [comment]
找 ConvolutionFloatFactor.cpp ，里面有相关判断逻辑

**Comment by MrJungle1** [comment]
经过验证确实使用了strassen 算法，这里想请教一下，strassen 算法递归的结束条件是啥，就是递归到最里面是会走naive的矩阵乘法吗？还是一个2*2 x 2*2 的最小strassen 算法

**Comment by jxt1234** [comment]
最里面是 native 矩阵乘法
