### ISSUE TITLE
已转换后的mnn模型如何编译

### ISSUE THREAD

**Issue by Zctoylm0927** [alibaba/MNN#3123]
我参照这篇[wiki](https://mnn-docs.readthedocs.io/en/latest/transformers/diffusion.html)，成功进行了Diffusion Demo之前的步骤。其中提到的mnn_path我并不理解是什么，我发现transformers/diffusion下Cmakelist.txt包含了diffusion_demo，于是我在transformers/diffusion目录下创建build并执行了

`cmake .. -DMNN_BUILD_DIFFUSION=ON -DMNN_BUILD_OPENCV=ON -DMNN_IMGCODECS=ON -DMNN_OPENCL=ON -DMNN_SEP_BUILD=OFF -DMNN_SUPPORT_TRANSFORMER_FUSE=ON`
`make -j8`

出现如下报错，

<img width="970" alt="image" src="https://github.com/user-attachments/assets/d67692d7-eb5c-444e-9d40-740c18c285a9">

请问我应该如何操作？

**Comment by jxt1234** [comment]
mnn_path 就是你下载 mnn 的目录。换言之，在 mnn 根目录下面建 build 文件夹

**Comment by Zctoylm0927** [comment]
非常感谢您的及时回复，我之前build时没注意到已经有diffusion_demo了，现在已能成功运行。我的运行命令是，./diffusion_demo mnn_sd1.5_path 0 demo.jpg 1 3 "a cute cat"，请问既然memory_mode在内存充足模式下运行了，sd1.5每一步的时间差异比较大，有时最快可以达到4.4s，最慢达到7s，请问这是什么原因呢？我理解mnn转化对于每一步的模型应该是一样的。

**Comment by jxt1234** [comment]
第一步会增加一个 encode的耗时，其他的波动问题可能是设备上 gpu 有被其他程序抢占

**Comment by Zctoylm0927** [comment]
感谢您的回复
