### ISSUE TITLE
AndroidDemo编译失败

### ISSUE THREAD

**Issue by xiahc** [alibaba/MNN#3126]
# 平台(如果交叉编译请再附上交叉编译目标平台):    
Android

# Github版本:
V3.0.1

# 编译方式:
project/android/demo/READNE.md
```
cd MNN
mkdir build && cd build
cmake -DMNN_BUILD_CONVERTER=ON ..
make -j8
```

# 编译日志:
```
E:\Code\MNN-master\MNN-master\build>make -j8
Makefile:32: ***  。 停止。
```
请帮忙指导，谢谢。

**Comment by jxt1234** [comment]
用 AndroidStudio 打开 project/android/demo 下面的工程就可以编译了
