### ISSUE TITLE
模型转换把matmul算子转成了Conv？

### ISSUE THREAD

**Issue by R-Ceph** [alibaba/MNN#3127]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux

# Github版本:
# Github Version:

98ba45b4561f68cbf6b5a39debb80eb91c64cc32

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

cd MNN
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true
make

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

原始模型：
https://drive.google.com/file/d/1aoom5u-tSA06XwcTGCJUwCfQrXAad9cE/view?usp=drive_link
![image](https://github.com/user-attachments/assets/400b04ea-2c23-4991-9311-cbeed84d3ded)

转换后模型：
https://drive.google.com/file/d/1rkI-4fMnCfQMgj6TUZO9j-TFllbHHy2p/view?usp=drive_link
![image](https://github.com/user-attachments/assets/21b47b63-7771-4988-960a-7ecbdf6547e9)

模型转化命令：

./build/MNNConvert -f ONNX --modelFile my_test/model.onnx --MNNModel my_test/model.mnn

**Comment by jxt1234** [comment]
对于MatMul的第二个输入为常量的情况，会默认转成 Convolution 1x1，以便进行预重排/量化等优化。对最终计算结果没有影响

**Comment by R-Ceph** [comment]
> 对于MatMul的第二个输入为常量的情况，会默认转成 Convolution 1x1，以便进行预重排/量化等优化。对最终计算结果没有影响

感谢大佬回复！
还是想问下，这个结果是符合预期的吗？
一个matmul转成这个多节点，感觉运行时间会增大很多吧

因为我们的模型中大部分都是matmul节点，想问下有什么保留matmul节点的方法吗？MNN针对matmul节点有优化吗？

**Comment by jxt1234** [comment]
不会影响运行时间的，只是看起来复杂。可以在转换时加 --saveStaticModel （输入尺寸固定），模型结构会看着简单一些

**Comment by jxt1234** [comment]
另外，mnn 对 matmul 也是有优化的

**Comment by R-Ceph** [comment]
> 不会影响运行时间的，只是看起来复杂。可以在转换时加 --saveStaticModel （输入尺寸固定），模型结构会看着简单一些

使用以下代码进行转换会报错
` 
PC1:~/workspace/MNN$ ./build/MNNConvert --bizCode biz --saveStaticModel  -f ONNX --modelFile my_test/model.onnx --MNNModel my_test/model.mnn 
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Start to Convert Other Model Format To MNN Model..., target version: 3
[11:12:37] /home/devin/workspace/MNN/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[11:12:37] /home/devin/workspace/MNN/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 15
[11:12:37] /home/devin/workspace/MNN/tools/converter/source/common/writeFb.cpp:174: These Op Not Support: ONNX::Softmax 
Converted Failed!
`
应该是使用了saveStaticModel之后不会优化，但是不优化的softmax算子不支持

想问下是否支持 选定特定算子 优化或者不优化呢？

**Comment by jxt1234** [comment]
应该是你的模型必须要动态输入。这个你可以自行插回调函数或者测试性能看。
https://mnn-docs.readthedocs.io/en/latest/inference/module.html#id12

https://mnn-docs.readthedocs.io/en/latest/tools/test.html#modulebasic-out
