### ISSUE TITLE
MNNConvert 转换特定 (LLM) onnx model 报错: FillComputer: Assertion `res' failed.

### ISSUE THREAD

**Issue by hosiet** [alibaba/MNN#3131]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Linux (Debian 12)

原生编译

问题可以在交叉编译得到的 Android App 上复现，应该是平台无关。

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

85291d01ccfada0d96848d6adaed572a5fa39359

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
cd build/ ; cmake .. -DMNN_LOW_MEMORY=true -DMNN_CPU_WEIGHT_DEQUANT_GEMM=true -DMNN_BUILD_LLM=true -DMNN_SUPPORT_TRANSFORMER_FUSE=true -DMNN_ARM82=true -DMNN_OPENCL=true -DMNN_USE_LOGCAT=true -DMNN_VULKAN=true -DMNN_BUILD_TRAIN=true -DMNN_OPENGL=false -DMNN_BUILD_TOOLS=true
```

# 问题描述
# Problem Description

按下述方式执行 `MNNConvert` 报错：

```
% ./MNN/build/MNNConvert --modelFile ./test-smollm-fixed-size.onnx -f ONNX --MNNModel output.mnn
Can't open file:/sys/devices/system/cpu/cpufreq/schedutil/affected_cpus
CPU Group: [ 6  4  2  0  7  5  3  1 ], 1200000 - 3500000
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Don't has bizCode, use MNNTest for default
Start to Convert Other Model Format To MNN Model..., target version: 3
[13:42:18] /home/hosiet/MODEL_mnn_llm_android/MNN/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 7
[13:42:18] /home/hosiet/MODEL_mnn_llm_android/MNN/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 14
Start to Optimize the MNN Net...
FuseDup run for 2 step
Error for /home/hosiet/MODEL_mnn_llm_android/MNN/source/shape/ShapeFill.cpp, 21
MNNConvert: /home/hosiet/MODEL_mnn_llm_android/MNN/source/shape/ShapeFill.cpp:21: virtual bool MNN::FillComputer::onComputeSize(const MNN::Op*, const std::vector<MNN::Tensor*>&, const std::vector<MNN::Tensor*>&) const: Assertion `res' failed.
[1]    43996 IOT instruction  ./MNN/build/MNNConvert --modelFile ./test-smollm-fixed-size.onnx -f ONNX
```

# 相关 ONNX 文件
# ONNX File

https://github.com/hosiet/onnx-mnn-convertbug-202412/blob/main/test-smollm-fixed-size.onnx

```
-> % md5sum ./test-smollm-fixed-size.onnx 
18f7a89c190dba15aa49ab684f1d1750  ./test-smollm-fixed-size.onnx
```

如有需要，我可以提供如何从 SmolLM2-360M-Instruct 模型转换得到该 ONNX 文件的详细步骤。

**Comment by jxt1234** [comment]
git 下载出错了，看着是文件太大
Error downloading object: test-smollm-fixed-size.onnx (f5ecf82): Smudge error: Error downloading test-smollm-fixed-size.onnx (f5ecf82901c2789b68feb8eaef8a4d9db867b4e9e64334e454c9d7136d434642): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by hosiet** [comment]
@jxt1234 你好，请换用这个外链再试一次： https://filedn.eu/lMOXrMfR8b50jOC0zsXg8xQ/resources/test-smollm-fixed-size.onnx

**Comment by jxt1234** [comment]
ok， 下载中

**Comment by jxt1234** [comment]
测试了一下貌似没有问题。只是模型转换时由于没有有效输入，所以误断言了，用 Release 版本是好的

**Comment by jxt1234** [comment]
问题找到了，trilu 的算子转换实现导致的。可以这么修改：
```
diff --git a/tools/converter/source/optimizer/onnxextra/OnnxPrelu.cpp b/tools/converter/source/optimizer/onnxextra/OnnxPrelu.cpp
index e10738ca9..689aeec6b 100644
--- a/tools/converter/source/optimizer/onnxextra/OnnxPrelu.cpp
+++ b/tools/converter/source/optimizer/onnxextra/OnnxPrelu.cpp
@@ -134,7 +134,7 @@ public:
         }
         auto k = (inputs.size() == 2 ? inputs[1] : _Scalar<int>(0));
         auto mask = (upper ? _GreaterEqual(rangeW, rangeH + k) : _GreaterEqual(rangeH, rangeW - k));
-        mask = _Reshape(mask, _Concat({_Fill(_Size(shape) - _Scalar<int>(2), oneV), _Shape(mask)}, 0));
+        mask = _Reshape(mask, _Concat({_Fill(_Unsqueeze(_Size(shape) - _Scalar<int>(2), {0}), oneV), _Shape(mask)}, 0));
         auto res = _Select(mask, inputs[0], zero);
         res->setName(expr->outputName(0));
         return res->expr().first;

```

**Comment by hosiet** [comment]
初步测试补丁似乎工作正常，谢谢。

**Comment by jxt1234** [comment]
bugfix 已经更新
