### ISSUE TITLE
交叉编译报错cross compile error

### ISSUE THREAD

**Issue by QHenry1990** [alibaba/MNN#3141]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.tar
gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar

# Github版本:
# Github Version: 3.0.0release版本

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
采用cmake交叉编译

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
aarch64能正常编译通过；arm不能编译通过，提示arm82中某些指令不识别。

```
粘贴在这里
Paste log here or pastebin
```
arm32/MNNConvRunForLineDepthwiseFP16.S:89: 错误： selected processor does not support fp16 instruction -- `vmla.f16 q8,q3,q0'
MNN-3.0.0/source/backend/arm82/asm/arm32/MNNConvRunForLineDepthwiseFP16.S:213: 错误： selected processor does not support fp16 instruction -- `vmla.f16 q0,q1,q2'

**Comment by jxt1234** [comment]
armv7 的话把 MNN_ARM82 关掉：cmake .. -DMNN_ARM82=OFF

**Comment by QHenry1990** [comment]
已解决，多谢。

**Comment by QHenry1990** [comment]
你好，现在用armv7 ， 把 MNN_ARM82 关掉：cmake .. -DMNN_ARM82=OFF库能正常编译出来，但是demo测试不通过，提示众多的函数未定义
libMNN.so: undefined reference to `MNNDepthwiseConvFastKernel'

libMNN.so: undefined reference to `MNNSamplerC4BilinearOpt'

libMNN.so: undefined reference to `MNNLoadU8AndSum'

libMNN.so: undefined reference to `MNNWinogradMatrixProductLeft'

libMNN.so: undefined reference to `MNNConvRunForLineDepthwise'

libMNN.so: undefined reference to `MNNCopyC4WithStride'

libMNN.so: undefined reference to `MNNBlitC1ToFloatRGBA'

libMNN.so: undefined reference to `MNNVectorTop1Float'

libMNN.so: undefined reference to `MNNDeconvRunForUnitDepthWise'

libMNN.so: undefined reference to `MNNRGBAToGRAYFast'

libMNN.so: undefined reference to `MNNNV21ToRGBUnit'

libMNN.so: undefined reference to `MNNBlitC3ToFloatRGBA'

libMNN.so: undefined reference to `MNNBinaryMulInt8'

libMNN.so: undefined reference to `MNNBinaryAddInt8'

libMNN.so: undefined reference to `MNNRGBAToBGRFast'

libMNN.so: undefined reference to `MNNReluInt8'

libMNN.so: undefined reference to `MNNMatrixSub'

libMNN.so: undefined reference to `MNNAvgPoolInt8'

libMNN.so: undefined reference to `MNNMinFloat'

libMNN.so: undefined reference to `MNNGetMatMulPackMode'

libMNN.so: undefined reference to `MNNPackedMatMul'

libMNN.so: undefined reference to `MNNBinarySubInt8'

未完待续.........

**Comment by QHenry1990** [comment]
你好，现在用armv7 ， 把 MNN_ARM82 关掉：cmake .. -DMNN_ARM82=OFF库能正常编译出来，但是demo测试不通过，提示众多的函数未定义
libMNN.so: undefined reference to `MNNDepthwiseConvFastKernel'

libMNN.so: undefined reference to `MNNSamplerC4BilinearOpt'

libMNN.so: undefined reference to `MNNLoadU8AndSum'

libMNN.so: undefined reference to `MNNWinogradMatrixProductLeft'

libMNN.so: undefined reference to `MNNConvRunForLineDepthwise'

libMNN.so: undefined reference to `MNNCopyC4WithStride'

libMNN.so: undefined reference to `MNNBlitC1ToFloatRGBA'

libMNN.so: undefined reference to `MNNVectorTop1Float'

libMNN.so: undefined reference to `MNNDeconvRunForUnitDepthWise'

libMNN.so: undefined reference to `MNNRGBAToGRAYFast'

libMNN.so: undefined reference to `MNNNV21ToRGBUnit'

libMNN.so: undefined reference to `MNNBlitC3ToFloatRGBA'

libMNN.so: undefined reference to `MNNBinaryMulInt8'

libMNN.so: undefined reference to `MNNBinaryAddInt8'

libMNN.so: undefined reference to `MNNRGBAToBGRFast'

libMNN.so: undefined reference to `MNNReluInt8'

libMNN.so: undefined reference to `MNNMatrixSub'

libMNN.so: undefined reference to `MNNAvgPoolInt8'

libMNN.so: undefined reference to `MNNMinFloat'

libMNN.so: undefined reference to `MNNGetMatMulPackMode'

libMNN.so: undefined reference to `MNNPackedMatMul'

libMNN.so: undefined reference to `MNNBinarySubInt8'

未完待续.........

**Comment by QHenry1990** [comment]
已经解决，交叉编译要使用armv7而不能用arm
