### ISSUE TITLE
mobilenet_v2 quantized model result is different from floating model

### ISSUE THREAD

**Issue by ovthf** [alibaba/MNN#316]
Check out the latest code, and download mobilenet_v2 caffe model by get_model.sh, convert caffe model to mnn floating model, quantize floating model to quantized model, run mobilenetTest.out to predict cat.jpg by mnn floating and quantized models, but their results are different.
floating model  top 5 result:
278, 0.205878
284, 0.108882
285, 0.108873
280, 0.099243
279, 0.076702
quantized model top 5 result:
278, 0.212680
279, 0.150183
285, 0.089118
280, 0.089118
282, 0.089118

Please take a look.

Thanks a lot.

**Comment by jxt1234** [comment]
ImageProcess compute a little difference from x86 and ARM.
