### ISSUE TITLE
iOS运行project的playground和demo/ios的playground都出错

### ISSUE THREAD

**Issue by wings0820** [alibaba/MNN#318]
首先是preject的
2019-09-12 17:47:06.124734+0800 Playground[640:218310] [DYMTLInitPlatform] platform initialization successful
	running core/memory_utils.
	running op/binary.
2019-09-12 17:47:06.263478+0800 Playground[640:218179] Metal GPU Frame Capture Enabled
2019-09-12 17:47:06.263935+0800 Playground[640:218179] 
Metal API Validation Enabled-[MTLDebugComputeCommandEncoder setComputePipelineState:]:282: failed assertion `computePipelineState must not be nil.'

这个会生成一个MNN.framework,5.9M的MNN文件(没有后缀，也没有libMNN.a)，还有一个metallib文件，但是是0kb，在另一个issue看到要设置 METAL_LIBRARY_FILE_BASE （位于POD file）为 default，这个设置是在文件设置还是哪啊，在demo/ios/podfile里面没有这些设置啊

然后是demo的
ld: warning: directory not found for option '-L/Users/sun/Library/Developer/Xcode/DerivedData/playground-dlpgffhadpppqnfnsgknanfaxdds/Build/Products/Release-iphoneos/MNN'
ld: file not found: /Users/sun/Library/Developer/Xcode/DerivedData/playground-dlpgffhadpppqnfnsgknanfaxdds/Build/Products/Release-iphoneos/MNN/libMNN.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

我是首先运行build_tool.sh，这个步骤没有出什么错 , 然后在demo/iOS 里pod update，网络总是failed没有下载模型，请问那里有错吗

**Comment by li-qing** [comment]
Xcode版本号是？改了metallib文件名一定会找不到的，如果一定需要设置成default，代码里也需要修改。

pod update里没有下载模型吧？？？？

**Comment by suitmyself** [comment]
PODfile中：
s.pod_target_xcconfig = {'**METAL_LIBRARY_FILE_BASE' => 'mnn',** 'HEADER_SEARCH_PATHS' => ' "$(PODS_TARGET_SRCROOT)/3rd_party/flatbuffers/include" ', 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) MNN_CODEGEN_REGISTER=1'}

但实际上项目文件已经生成了，直接在XCode项目中，将其改成 default，这样metal lib 能够正常生成。
