### ISSUE TITLE
两个模型运行时间与初始化顺序有关？

### ISSUE THREAD

**Issue by jiarenyf** [alibaba/MNN#322]
两个模型R1和R2（结构一致、参数不同），分以下两种情况：
1、先初始化1再初始化2，时间 40ms v.s. 100 ms：
```
interpreter1 = Interpreter::createFromFile(modelPath1)
session1 = interpreter1->createSession(config)
interpreter1->releaseModel();
...
interpreter2 = Interpreter::createFromFile(modelPath2)
session2 = interpreter2->createSession(config)
interpreter2->releaseModel();
...
interpreter1->runSession(session1) # 时间：40ms
...
interpreter2->runSession(session2) # 时间：100ms
```

2、先初始化2再初始化1，时间 100ms v.s. 40 ms：
```
interpreter2 = Interpreter::createFromFile(modelPath2)
session2 = interpreter2->createSession(config)
interpreter2->releaseModel();
...
interpreter1 = Interpreter::createFromFile(modelPath1)
session1 = interpreter1->createSession(config)
interpreter1->releaseModel();
...
interpreter1->runSession(session1) # 时间：100ms
...
interpreter2->runSession(session2) # 时间：40ms
```

非常奇怪。。。

**Comment by li-qing** [comment]
试过独立benchmark么？耗时稳定可复现？

**Comment by jiarenyf** [comment]
@li-qing 独立benchmark时每个 interpreterX->runSession(sessionX) 的耗时均为40ms，4种情况（单独1、单独2、先1再2、先2再1）的耗时稳定可复现。
单独1:40ms
单独2:40ms
先初始化1再初始化2:40(1)+100(2)ms
先初始化2再初始化1:100(1)+40(2)ms

**Comment by jxt1234** [comment]
你应该是初始化了三个及以上的Session，MNN的线程池仅支持2个Session使用（实际情况下多个模型都用多线程没有必要），其余的只会用单线程执行。

**Comment by jiarenyf** [comment]
@jxt1234 
嗯嗯，确实是用的三个模型（以为跟第三个模型无关就没写上）。如果需要3个模型都使用多线程应该如何修改编译呢，麻烦指导下，谢谢～

**Comment by jiarenyf** [comment]
@jxt1234  @li-qing 
嗯嗯，确实是用的三个模型（以为跟第三个模型无关就没写上）。
```
https://github.com/alibaba/MNN/blob/cfad1c3b3b29fda39354569881eb433d07e55e09/source/backend/cpu/ThreadPool.cpp#L20
```
请问，修改这里的```#define MNN_THREAD_POOL_MAX_TASKS 3```重新编译 or 设置```-DMNN_USE_THREAD_POOL=off```，好像没用呢，谢谢～

**Comment by jxt1234** [comment]
你应该是编译的库没同步- -

**Comment by jiarenyf** [comment]
@jxt1234 ```libMNN.so libMNN_CL.so libMNN_GL.so libVulkan.so``` 这四个so我都重新编译更新到手机上了，还需要同步其他的库吗？

**Comment by jiarenyf** [comment]
@jxt1234 libMNN.so libMNN_CL.so libMNN_GL.so libVulkan.so 这四个so我都重新编译更新到手机上了，但是还是没有解决问题，还需要同步其他的库吗？

**Comment by dan520520520** [comment]
我也是三个Session，请问你是怎么解决的？

**Comment by xinyu391** [comment]
把这个 改大了有什么影响？
比如程序中用到5个模型，把MNN_THREAD_POOL_MAX_TASKS 设为5，每个模型的推理速度会受影响吗？
