### ISSUE TITLE
OpenCL后端,反卷积计算结果有误

### ISSUE THREAD

**Issue by BokyLiu** [alibaba/MNN#326]
相同的代码,使用CPU计算时完全正确
OpenCL后端时结果不正确,提取结果**conf**代码如下:
`std::shared_ptr<Tensor> outputUser(new Tensor(mnn_->output, dimType));
mnn_->output->copyToHostTensor(outputUser.get());
auto type = outputUser->getType();
auto size = outputUser->elementSize();
if (type.code == halide_type_float)
{
auto values = outputUser->host<float>();
for (int i = 0; i < size; i++)
{
cout << "    conf = " << values[i] << endl;
}
}`

**Comment by twmht** [comment]
有沒有一個可以複製出來的 public model?

**Comment by BokyLiu** [comment]
> 有沒有一個可以複製出來的 public model?

用的PeleeNet作为backbone的模型,在pc上及CPU上都是正确的

**Comment by twmht** [comment]
@BokyLiu 

可不可以給模型的 download link?

**Comment by hacker-joe** [comment]
> > 有沒有一個可以複製出來的 public model?
> 
> 用的PeleeNet作为backbone的模型,在pc上及CPU上都是正确的

可以给个模型吗？我这边帮你测一下。

**Comment by VincentYimmy** [comment]
> > 有沒有一個可以複製出來的 public model?
> 
> 用的PeleeNet作为backbone的模型,在pc上及CPU上都是正确的

这个问题有解决方法吗？目前我这边测试一个带Conv2DBackpropInput反卷积的模型也出现了类似问题。OpenCL结果不正确，CPU结果正确。

**Comment by weixiaolian21** [comment]
请问解决了吗? 我在转centernet的dla34v0 模型时 里边DeconvolutionDepthwise的op, 输出查看了 这个op在opencl的输出是错误的.
