### ISSUE TITLE
interp层错误

### ISSUE THREAD

**Issue by mengdong824** [alibaba/MNN#327]
caffe转MNN模型，打印每一层输出的维度，interp层输出维度错误，排查为对prototxt中interp层的zoom_factor识别有问题，导致数据维度不对

**Comment by AlphaLFC** [comment]
我看了看源码，感觉有问题，原始caffe Interp层的 zoom_factor应该就是指放大倍数，比如zoom_factor=2时，就是放大两倍，可是，MNN里的实现是参考tools/converter/source/caffe/ResizeInterp.cpp
if (Par.has_zoom_factor()) {
        resize->widthScale  = (float)(resize->widthScale + 1.0 / Par.zoom_factor());
        resize->heightScale = (float)(resize->heightScale + 1.0 / Par.zoom_factor());
这是神马操作？!不能理解。我尝试将zoom_factor设成默认的1，看起来对了。但这就仅限于支持2倍放大，且只支持bilinear。
