### ISSUE TITLE
mtcnn caffe模型输出不一致

### ISSUE THREAD

**Issue by zeyuanlicbpm** [alibaba/MNN#329]
![caffe](https://user-images.githubusercontent.com/33452561/64952691-8a25f600-d8b3-11e9-98dc-7825f6be250a.jpg)
![mnn](https://user-images.githubusercontent.com/33452561/64952696-8db97d00-d8b3-11e9-9b0f-841d01af9d49.jpg)
上述两个分别是caffe、mnn的inference过程，并且打印比较了数据网络的数据，是完全一致的；但是网络的数据却不一样！！！！  什么原因呢？

**Comment by zeyuanlicbpm** [comment]
打印比较了网络的输入数据是一致的

**Comment by ChisenZhang** [comment]
第二，第三个网络的输入你是怎么从原图得到的？  直接套几个for循环取box中的像素值？

**Comment by li-qing** [comment]
亲 不建议直接使用host<float>接口写入数据

如果第一层的数据是NC4HW4格式的 你按NCHW的方式填入 结果肯定会不对的

数据输入部分建议参考 https://www.yuque.com/mnn/cn/input
