### ISSUE TITLE
Error compilation  Android OS on Intel CPU

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#331]
I try to compile libMNN library for Android OS and Intel CPU .
I changed build_64.sh with -DANDROID_ABI="x86_64" \

I have error compilation:

MatrixSub.cpp.o
[ 78%] Linking CXX shared library libMNN.so
/home/administrator/Code/MNN/source/core/Tensor.cpp:296: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:317: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:271: error: undefined reference to '__gnu_h2f_ieee'
/home/administrator/Code/MNN/source/core/Tensor.cpp:336: error: undefined reference to '__gnu_h2f_ieee'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/MNN.dir/build.make:3203: recipe for target 'libMNN.so' failed
make[2]: *** [libMNN.so] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/MNN.dir/all' failed
make[1]: *** [CMakeFiles/MNN.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by czy2014hust** [comment]
应该是不支持fp16，https://github.com/alibaba/MNN/blob/cfad1c3b3b29fda39354569881eb433d07e55e09/source/core/Tensor.cpp#L391 可以先把这块注释掉试下
