### ISSUE TITLE
int8 与 uint8

### ISSUE THREAD

**Issue by wuzhiyang2016** [alibaba/MNN#332]
您好，看了MNN中的量化，有int8和uint8的实现，那在转成量化模型时，如何制定模型输出为uin t8还是int8?

**Comment by czy2014hust** [comment]
目前MNN支持tflite的uint8量化模型，也支持采用MNN的量化工具的int8量化模型。

**Comment by xiezheng1995** [comment]
> 目前MNN支持tflite的uint8量化模型，也支持采用MNN的量化工具的int8量化模型。

请问，tflite的uint8量化模型如何转mnn量化模型呢？
