### ISSUE TITLE
两个关于图像处理模块的问题

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#333]
1. 等比缩放
Matrix trans;
trans.setScale((float)(originWidth - 1) / (dstWidth - 1), (float)(originHeight - 1) / (dstHeight - 1));
Matrix 的参数这样设置对吧， 等比缩放是按照最长边缩放到目标尺寸的比例缩放的吗？ 假设dstWith == dstHeight，缩放比例 r = dstWith/max(originWidth, originHeight)，是这样的吗？
2. 关于图像填充
ImageProcess::Config 的参数设为 config.wrap = ZERO;  填充图像到目标尺寸，我看源代码没有看太明白，具体操作好像是原始图像居中 周边填充0到目标尺寸，我的理解对吗？

如果要将一个图像等比缩放，然后填充到固定尺寸，按上述操作设置参数可以得到想要的图像吗？ 具体就是图像先按最长边的缩放比，同时缩放；然后图像周边填充零到指定的尺寸。

**Comment by ChisenZhang** [comment]
又自己研究了一下：
缩放的Matrix.setScale的两个参数分别是宽和长的缩放比例；和用python调opencv做缩放的比例计算是相反的。
图像填充，相当于图像缩放到指定尺寸之后，把缩放后的图像放到了固定尺寸全为零的矩阵的左上角。（拿程序验证出来的）

**Comment by jxt1234** [comment]
请参考 https://www.yuque.com/mnn/cn/input 里面图像处理相关的内容
