### ISSUE TITLE
MNN生成量化模型中为啥连relu/pool层都采用浮点？

### ISSUE THREAD

**Issue by wuzhiyang2016** [alibaba/MNN#334]
像relu/pool这样的层，直接在int8的数据上处理是等价的，为啥要切回浮点？ 比如，relu层的话，浮点0直接映射int8中的0，如果直接将[-127,127]的数值经过relu,其实也能够得到等价的操作，而且还省略了浮点与定点的来回切换，，，而MNN的设计，是否另有深意？  还请哥指点～

**Comment by wuzhiyang2016** [comment]
感谢作者在钉钉上的回复，是我自己搞错了，relu已合并到int8的conv中去了

**Comment by yangcedrus** [comment]
> 像relu/pool这样的层，直接在int8的数据上处理是等价的，为啥要切回浮点？

你好，可以请问下为什么吗。
如果想要使用`OpType_PoolInt8`这个算子的话，在量化时是可以修改哪部分代码达到目的吗。
