### ISSUE TITLE
模型跑GPU输出错误

### ISSUE THREAD

**Issue by ppl21847** [alibaba/MNN#337]
有没有大佬遇到过这个问题呀，
开始的时候在CPU下调试没有问题，切换成FORWARD_AUTO后 输出错误。

**Comment by BokyLiu** [comment]
举手
#326

**Comment by ppl21847** [comment]
> 举手
> #326

GPU连PeleeNet都跑不了？小米的mace平台支持，现在迫于无奈选择了MNN 连PeleeNet都跑不了 不应该吧。

**Comment by jiarenyf** [comment]
。。。我也是，opencl、opengl输出是错的，vulkan直接崩溃。。。

**Comment by BokyLiu** [comment]
> > 举手
> > #326
> 
> GPU连PeleeNet都跑不了？小米的mace平台支持，现在迫于无奈选择了MNN 连PeleeNet都跑不了 不应该吧。

我是用的Hisi3559

**Comment by ppl21847** [comment]
> > > 举手
> > > #326
> > 
> > 
> > GPU连PeleeNet都跑不了？小米的mace平台支持，现在迫于无奈选择了MNN 连PeleeNet都跑不了 不应该吧。
> 
> 我是用的Hisi3559

我在小米9(骁龙855)和华为mate9（Hisilicon Kirin 960）上FORWARD_CPU和 FORWARD_AUTO结果都是对的呀。

**Comment by twmht** [comment]
建議把 net arch 放上來，我來幫各位看看，我這邊用起來沒碰到什麼問題

**Comment by jiarenyf** [comment]
@twmht 请问，你那边用GPU能加速多少呢

**Comment by twmht** [comment]
GPU 目前不會比 CPU 開 4 個 thread 快

**Comment by jiarenyf** [comment]
@twmht 好的，谢谢。

**Comment by jiarenyf** [comment]
GPU下模型输出结果错误我这边也遇到了，是OP不支持opencl的问题，可以在https://www.yuque.com/mnn/en/ops里面看看是不是存在不支持的op。不过也有个问题，就是为啥op不支持不会报错，而是仍然有结果输出。。。

**Comment by xingyanan** [comment]
可能的原因：1、算子不支持，可以确认一下，一般算子不支持在convert模型的时候就会报错
2、输出格式不对，不同backend和不同框架转出来的模型输入通道顺序不一样，输入错了，输出肯定不对
