### ISSUE TITLE
int8add还是float add

### ISSUE THREAD

**Issue by wuzhiyang2016** [alibaba/MNN#338]
哥，您好，我在测试MNN过程中，发现有的add层采用**int8add**(两个输入均为in8卷积输出)，有的采用**float add** (其中一个输入为int8卷积输出，另一个输入为maxpool的int8输出，这两个输入都被转为浮点后计算)，，，在钉钉群提问，回复是为了处理其中有个输入需要broadcast的情况，因而采用浮点，这个可以理解，但是maxpool显然不需要 broadcast，MNN这样处理的依据是？

**Comment by czy2014hust** [comment]
像mobilenetv2/resenet系列的add，可以转为eltwise的add就会支持addInt8，其他情况还是转为float计算
