### ISSUE TITLE
转换类mobilenet主干的检测模型 出错

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#339]
用之前的版本0.2.0.7或者0.2.0.8  哪个版本忘了，转换推理都没有问题；用最新的code，编译转换工具的时候就报了一堆关于tensorflow的waning：not a directory。转换同一个模型，提示以下错误。
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted
iOS端调库加载转换好的模型推理的时候  提示了一个 Can't compute size for 11, name=Net/truediv/y Resize error for Net/truediv/y, code=3.
不知道什么原因。

**Comment by MaybeShewill-CV** [comment]
@ChisenZhang 最新的code 编译converter的时候要在cmakelist里target_link_libraries(your_built_binary_app, Threads:Threads)

**Comment by ChisenZhang** [comment]
> @ChisenZhang 最新的code 编译converter的时候要在cmakelist里target_link_libraries(your_built_binary_app, Threads:Threads)

Converter的CMakeList 里面不是有吗？还要加什么？
![image](https://user-images.githubusercontent.com/16755579/65139489-51b32300-da3f-11e9-8531-b37ae851bd37.png)

**Comment by MaybeShewill-CV** [comment]
@ChisenZhang 增加链接Threads:Threads

**Comment by ChisenZhang** [comment]
> @ChisenZhang 增加链接Threads:Threads
最后一行加了 target_link_libraries(MNNConvert Threads:Threads)
提示找不到 cannot find -lThreads:Threads

**Comment by MaybeShewill-CV** [comment]
@ChisenZhang 前面你要find_package的 ==！find_package(Threads REQUIRED)

**Comment by ChisenZhang** [comment]
> @ChisenZhang 前面你要find_package的 ==！find_package(Threads REQUIRED)

一样

**Comment by MaybeShewill-CV** [comment]
@ChisenZhang 那就是你找不到这个类库了 ==!

**Comment by ChisenZhang** [comment]
> @ChisenZhang 那就是你找不到这个类库了 ==!

确定是这个原因吗？  不是编不过是转换模型出错

**Comment by czy2014hust** [comment]
reference to #302

**Comment by MaybeShewill-CV** [comment]
> 用之前的版本0.2.0.7或者0.2.0.8 哪个版本忘了，转换推理都没有问题；用最新的code，编译转换工具的时候就报了一堆关于tensorflow的waning：not a directory。转换同一个模型，提示以下错误。
> terminate called after throwing an instance of 'std::system_error'
> what(): Unknown error -1
> Aborted

@ChisenZhang 你说的这个问题确定是需要增加Threads的问题 我也遇到过
