### ISSUE TITLE
MNNConvert 遇到protobuf报错

### ISSUE THREAD

**Issue by zhoukismet** [alibaba/MNN#342]
~/MNN/tools/converter/build$ ./MNNConvert --version
[libprotobuf FATAL google/protobuf/generated_message_util.cc:812] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
错误如上，网上说编译需要加-lpthread，我在编译MNNConvert的CMakefile.txt里面加入
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lpthread")
重新编译后仍然报错

**Comment by czy2014hust** [comment]
reference to #302
