### ISSUE TITLE
int 8 overflow?

### ISSUE THREAD

**Issue by dtcrong** [alibaba/MNN#343]
MNNGemmInt8AddBiasScale_16x4_Unit:
    smull v0.8h, v12.8b, v10.8b
    smlal2 v0.8h, v12.16b, v10.16b
    saddlp v24.4s, v0.8h

127 * 127 * 2 overflow v0.8h

**Comment by czy2014hust** [comment]
int16 [-32768, 32767]
127 * 127 * 2 = 32258 < 32767

**Comment by dtcrong** [comment]
> int16 [-32768, 32767]
> 127 * 127 * 2 = 32258 < 32767

Oh yes, sorry.   Silly issue. Closed
