### ISSUE TITLE
模型转换工具报错

### ISSUE THREAD

**Issue by suitmyself** [alibaba/MNN#344]
环境：
ubuntu: 16.04
protobuf:  3.7.1
gcc: 5.4.0

更新最新代码后，构建模型转换工具出现关于protobuf的诸多warning：

cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/attr_value.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/function.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/graph.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/node_def.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/op_def.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/resource_handle.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/tensor.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/tensor_shape.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/types.pb.h: not a directory
cc1plus: warning: /home/weichen/文档/MNN/tools/converter/build/source/tensorflow/versions.pb.h: not a directory

并且调用get_model.sh执行模型转换报错：
[libprotobuf FATAL google/protobuf/generated_message_util.cc:794] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
./tools/script/get_model.sh: 行 36:  6964 已放弃               (核心已转储) ./$CONVERTER -f CAFFE --modelFile $2 --prototxt $4 --MNNModel $6 --bizCode 0000

**Comment by czy2014hust** [comment]
reference to #302
