### ISSUE TITLE
func: CreatMNNSession, line: 222 ModelAddress:0xf15c7010 Don't support type 12, 15_Conv

### ISSUE THREAD

**Issue by caizhigang** [alibaba/MNN#345]
Don't support type 12, 15_Conv
Resize error for 15_Conv, code=2

加载MNN模型时，报错如上，请问是什么原因？不支持的卷积层？
模型从ptorch转换而来.
谢谢。

**Comment by jxt1234** [comment]
.a 形式加载需要 all_load 或才 WL -whole-active
