### ISSUE TITLE
编译IOS库的问题

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#347]
没有用提供的Xcode工程编译。 用cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DIOS_PLATFORM=OS .. -G “Xcode” 生成的工程编的静态库。在模拟器上调用正常，但是换了真机环境就会报arm64架构的东西找不到，arme7的没问题。lipo 查看是有arm7和arm64架构的，怎么回事？    用源码带的工程编出来的framework就不会有什么问题。  
还有就是CMake里面打开metal的选项，可以看到编译的源码中包含了metal的源码，编出来的包体积也变大了，但是用MNN_FORWORD_METAL，会提示没有这个东西，是调用的方式不对吗？

**Comment by li-qing** [comment]
1. armv7/arm64有差别的话，一般是汇编部分代码的差异问题，cmake的时候只包含了armv7的部分；
2. 当前Metal需要配搭metallib；

**Comment by ChisenZhang** [comment]
1. 如果只包含了armv7部分的话  是不是用cmake 生成Xcode工程的时候，这几句导致的，只包含了第一个if的arm7，其实应该包含两个架构
![image](https://user-images.githubusercontent.com/16755579/67185736-111d3f80-f419-11e9-89e7-8c942b9c097d.png)
2. 是需要metallib，但是编译的时候选项选了编译metallib，编出来并没有这个库，较新的commit看到修复了关于编译metallib的东西，可能用新的代码就能编出来metallib的库了，有空再试试

**Comment by li-qing** [comment]
1 & 2 => 是的

**Comment by ChisenZhang** [comment]
> 1 & 2 => 是的

👌

**Comment by YiQiu1984** [comment]
你好，想问一下，不想集成framework的话，iOS能编译出来libMNN.a静态库吗？有了解的大佬，麻烦指点一下。
