### ISSUE TITLE
使用2个月，一些问题

### ISSUE THREAD

**Issue by jiarenyf** [alibaba/MNN#348]
1、多次运行结果不一致，android上run session或者pc上MNNBasic.out都会出现；
2、量化结果误差很大，且速度与未加速差不多10%左右，检测模型出现检测框向左平移的问题，识别模型结果完全错误；检测模型量化配置如下：
```
{
  "format": "RGB",
  "mean": [
    123.68000030517578,
    116.77999877929688,
    103.94000244140625
  ],
  "normal": [
    1.0,
    1.0,
    1.0
  ],
  "width": 640,
  "height": 640,
  "used_image_num": 5000,
  "weight_quantize_method": "MAX_ABS",
  "feature_quantize_method": "KL",
  "path": "./datas/detection_data_samples"
}
```
3、检测模型使用OPENCL、OPENGL输出结果错误，使用VULKAN在runSession这一步报错；
```
public enum DeviceType {
    CPU(0),
    AUTO(4),
    OPENCL(3),
    OPENGL(6),
    VULKAN(7);

    public int type;

    DeviceType(int t) {
        type = t;
    }
}
```
4、在同一个app中使用了一个检测模型、两个识别模型，第二个识别模型运行速度慢，更改```MNN_THREAD_POOL_MAX_TASKS```宏，重新编译android下的so，无效；

以上问题都是花了一个星期左右的时间无法解决的问题，期待好心人解答。。。

**Comment by jxt1234** [comment]
1､每次运行前都需要重新填输入，请确认是否每次 runSession 前都填输入了
2、一般情况下是预处理配置的问题，也有可能是浮点模型本身支持有问题
3、应该是 gpu 某个算子不支持，需要具体的模型检查一下
4、无法复现，建议先写 exe 单测

**Comment by jiarenyf** [comment]
@jxt1234 
1、每次 runSession 前都填输入了相同的数据；
2、浮点检测、识别模型输出正确，但是量化后错误，预处理配置不变，也许是量化的问题；
3、有啥办法检测出不支持的算子呢？
4、我去测试一下

谢谢哈。

**Comment by jxt1234** [comment]
1、是什么类型的模型呢，CPU / GPU ?
2、模型中是否有带pad的卷积层，如果是，近期会更新修复
3、可以用 backendTest.out 逐层对比，或者你发一下模型我们看看

**Comment by jiarenyf** [comment]
@jxt1234 
1、是CPU模型；
2、模型中有3*3+same pad的卷积层；
3、我去试试。

谢谢哈。

**Comment by jiarenyf** [comment]
检测模型使用OPENCL、OPENGL输出结果错误应该是因为GatherV2和Transpose这两个op不支持的原因。

**Comment by jiarenyf** [comment]
更新0.2.1.0版本后，1、2、4问题解决。
检测模型使用OPENCL、OPENGL输出结果错误应该是因为GatherV2和Transpose这两个op不支持的原因。

**Comment by jiarenyf** [comment]
更新0.2.1.0版本之后，检测模型量化之后不会出现检测框向左平移的问题了，但是识别模型量化之后结果还是完全出错了。。。

**Comment by jiarenyf** [comment]
模型量化之后结果完全错误，最后一层输出是一个40*9000的feature map，对axis=1做argmax操作发现都是8999，应该是量化之后哪里出错了吧，换个很多批量化数据，用1W张图片进行量化应该也够了吧。

麻烦帮忙看看，谢谢🙏
@jxt1234

**Comment by czy2014hust** [comment]
1. 识别模型在[量化校准时请确保预处理](https://github.com/alibaba/MNN/blob/73ad3413cc41a18b5097bef9d7ad40aafdde6b8f/tools/quantization/Helper.cpp#L103)和训练保持完全一致;
2. 量化模型请在Arm架构下测试
