### ISSUE TITLE
how to quantize the model?

### ISSUE THREAD

**Issue by qser** [alibaba/MNN#35]
1、如何支持八位量化的推理？

**Comment by li-qing** [comment]
1. 目前支持TensorFlowLite的量化模型，转换即可；
2. 后续会退出无训练的量化工具，敬请期待；

**Comment by LeeRock** [comment]
> 1. 目前支持TensorFlowLite的量化模型，转换即可；
> 2. 后续会退出无训练的量化工具，敬请期待；

Three types of TensorFlowLite quantization is totally supported?
1.Weight quantization | 4x smaller, 2-3x speedup, accuracy | CPU
2.Full integer quantization | 4x smaller, 3x+ speedup | CPU, Edge TPU, etc.
3. Float16 quantization | 2x smaller, potential GPU acceleration | CPU/GPU

**Comment by hacker-joe** [comment]
only support Quantization-aware training now

**Comment by hacker-joe** [comment]
> > 1. 目前支持TensorFlowLite的量化模型，转换即可；
> > 2. 后续会退出无训练的量化工具，敬请期待；
> 
> Three types of TensorFlowLite quantization is totally supported?
> 1.Weight quantization | 4x smaller, 2-3x speedup, accuracy | CPU
> 2.Full integer quantization | 4x smaller, 3x+ speedup | CPU, Edge TPU, etc.
> 3. Float16 quantization | 2x smaller, potential GPU acceleration | CPU/GPU

only support Quantization-aware training now
