### ISSUE TITLE
关于Hi3559A平台OpenCL的加载，提示找不到 libOpenCL.so

### ISSUE THREAD

**Issue by vincent-tx** [alibaba/MNN#351]
Hi3559A 平台，使用海思SDK里的 libOpenCL.so，通过修改source/backend/opencl/CMakeLists.txt文件，
\# find_package(OpenCL)
target_link_libraries(MNN_CL PRIVATE /usr/local/lib/libOpenCL.so ${CMAKE_THREAD_LIBS_INIT})
指定库可以链接到libOpenCL.so。
在 build/source/backend/opencl文件夹下，**可以生成libMNN_CL.so**。
但是在编译testModel.out，mobilenetTest.out, backendTest.out,等时，报错：
aarch64-linux-gnu/bin/ld: warning: libOpenCL.so, needed by ../../source/backend/opencl/libMNN_CL.so, not found (try using -rpath or -rpath-link)
../../source/backend/opencl/libMNN_CL.so: undefined reference to `clBuildProgram'
../../source/backend/opencl/libMNN_CL.so: undefined reference to `clEnqueueNDRangeKernel'
...
个人感觉，既然可以生成 libMNN_CL.so，为什么还会报错找不到libOpenCL.so?
海思SDK里的 libOpenCL.so确定是可以使用的。我用它做了OpenCL的编程，在成功在Hi3559上运行了。
请问MNN如何正确加载OpenCL库？
Please help.

**Comment by vincent-tx** [comment]
由于是直接用的libOpenCL.so, 因此将find_package(OpenCL)注释掉了

**Comment by jxt1234** [comment]
运行程序前增加链接地址
export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH

**Comment by vincent-tx** [comment]
嗯，找到原因了，还是CMakeList.txt里链接库没链上。如：
target_link_libraries(testModel.out ${MNN_DEPEND} OpenCL mali)
后面要加上OpenCL和mali
