### ISSUE TITLE
IOS 推理获取不到结果

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#352]
IOS CPU模式 线程1-4
1. 拿之前的代码运行分类网络，之前的库结果是正确的，但是换了新库（0.2.0.9）之后就取不出来结果来了；调用方式按demo写的；
2. 还有一个检测的网络，用之前的库结果是错的，新库结果就正确，模拟器上结果正确，换真机结果就不对。两个模型都是TF框架转的，MobileNet结构。什么原因呢？ 分类的模型用新代码重新转过结果也一样。在linux上跑结果都是对的。  大佬帮分析下什么原因，急急急

**Comment by jiarenyf** [comment]
是否在更新so的同时忘记更新include的hpp文件呢

**Comment by ChisenZhang** [comment]
> 是否在更新so的同时忘记更新include的hpp文件呢

IOS用的都是用的framework的静态库，应该不会出现这种情况

**Comment by jxt1234** [comment]
CPU / GPU ? 真机是什么机器？CPU 是 armv7a 还是 armv8

**Comment by ChisenZhang** [comment]
> CPU / GPU ? 真机是什么机器？CPU 是 armv7a 还是 armv8

CPU。真机是iphon7P 应该是armv8
第一个问题解决了，第一个问题，把IOS调用的代码 中的一句 MNN::Tensor copy(output); 改成：MNN::Tensor copy(output, output->getDimensionType()); 取不到分类结果的问题解决了。
第二个问题，没有继续做测试为什么出现这种情况，直接换了库
