### ISSUE TITLE
MNNConverter 转换失败采用 0.2.0.9版本 0.2.0.8版本没问题

### ISSUE THREAD

**Issue by lyhehong** [alibaba/MNN#356]
[libprotobuf FATAL google/protobuf/generated_message_util.cc:809] CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (scc->visit_status.load(std::memory_order_relaxed)) == (SCCInfoBase::kRunning): 
Aborted (core dumped)

**Comment by czy2014hust** [comment]
reference to #302
