### ISSUE TITLE
tf模型转mnn模型使用cpu backend推理正常，metal backend推理报错

### ISSUE THREAD

**Issue by zjd1988** [alibaba/MNN#357]
现在移植tensorflow模型到mnn模型，转换正常，而且在c pu后端能够正常运行，但是如果切换到metal后端则运行出错，错误信息如下：

<img width="589" alt="77B90C06-C58B-4EEF-AECE-E13014085BBF" src="https://user-images.githubusercontent.com/7134030/65738399-42edff80-e114-11e9-9889-5eeec0968319.png">

从上面信息看是输入tensor的维度w为0导致的，这一层的算子是square，我看了下代码
<img width="465" alt="A4501AC2-296F-443B-B867-61C409DF0EFA" src="https://user-images.githubusercontent.com/7134030/65738140-711f0f80-e113-11e9-98a5-121190fd8406.png">

w是获取第2维度信息（即维度信息的第三个值），但是这一层只有两维，则w会被赋值为0，所以导致后续的操作失败，因为模型比较大，无法上传，不知道各位大佬有没有遇到过这种情况。

**Comment by jiarenyf** [comment]
也许可以试下在square op之前加一个reshape op 将square的输入expand_dim为(a,b,1,1)；在square op之后再进行suqeeze。

**Comment by zjd1988** [comment]
@jiarenyf  谢谢啦，这样应该能行，目前我是修改ｍｎｎ源码适配我的模型了，后续有时间试试这种方法．
从　https://www.yuque.com/mnn/en/ops　看，貌似所有算子都需要４维输入，感觉不是太方便，要是能改善下就好了．

**Comment by jxt1234** [comment]
应该已经 fixed 了
