### ISSUE TITLE
.pb 转mnn失败，报错，怎么解决呢

### ISSUE THREAD

**Issue by jimwan** [alibaba/MNN#358]
MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...

***********************
Strongly Recommended: Apply Tensorflow Tool [graph transform] firstly!!! ==> fold_constants
***********************

libc++abi.dylib: terminating with uncaught exception of type Error: [16:07:51] /Users/user/Downloads/MNN/tools/converter/source/tensorflow/TmpGraph.cpp:320: Check failed: inputNode->opType == "Const" ==> FusedBatchNorm|SpaceToBatchND Lack Const Tensor
Abort trap: 6

**Comment by jiarenyf** [comment]
如果使用了bn，生成pb时将bn层training参数设为False；
如果使用了dilation conv，需要固定输入图像大小，然后重新生成pb。

**Comment by jimwan** [comment]
我用了bn，然后我在从.h5模型转的时候就把trainable设为False了。然后转换还是一样的错误，有什么办法吗

**Comment by jimwan** [comment]
我用了bn，然后我在从.h5模型转的时候就把trainable设为False了。然后转换还是一样的错误，有什么办法吗

**Comment by jiarenyf** [comment]
@jimwan 不是trainable，是training。。。

**Comment by liziru** [comment]
我没有用bn，也没有用到dilation conv，却也遇到了这个问题，能帮忙提供个建议吗？

**Comment by czy2014hust** [comment]
set training is false
