### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by anlongstory** [alibaba/MNN#36]
After run `cmake ..` on my Ubuntu 16.04 CUDA8.0 ，then run `make -j4` ，I got this error:

>/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:50:33: error: expected initializer before ‘OpType_Size__’
 extern void ___SizeOpComputer__ OpType_Size__();
                                 ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:51:32: error: expected initializer before ‘OpType_Slice__’
 extern void ___SliceComputer__ OpType_Slice__();
                                ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:52:34: error: expected initializer before ‘OpType_SliceTf__’
 extern void ___SliceTfComputer__ OpType_SliceTf__();
                                  ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:53:45: error: expected initializer before ‘OpType_SpaceToBatchND__’
 extern void ___SpaceToBatchNDSizeComputer__ OpType_SpaceToBatchND__();
                                             ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:54:38: error: expected initializer before ‘OpType_Squeeze__’
 extern void ___SqueezeSizeComputer__ OpType_Squeeze__();
                                      ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:55:39: error: expected initializer before ‘OpType_StridedSlice__’
 extern void ___StridedSliceComputer__ OpType_StridedSlice__();
                                       ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:56:44: error: expected initializer before ‘OpType_ConvertTensor__’
 extern void ___TensorConvertSizeComputer__ OpType_ConvertTensor__();
                                            ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:57:44: error: expected initializer before ‘OpType_TfQuantizedConv2D__’
 extern void ___TFQuantizedConv2DComputer__ OpType_TfQuantizedConv2D__();
                                            ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:58:44: error: expected initializer before ‘OpType_QuantizedDepthwiseConv2D__’
 extern void ___TFQuantizedConv2DComputer__ OpType_QuantizedDepthwiseConv2D__();
                                            ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:59:31: error: expected initializer before ‘OpType_Tile__’
 extern void ___TileComputer__ OpType_Tile__();
                               ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:60:37: error: expected initializer before ‘OpType_TopKV2__’
 extern void ___TopKV2SizeComputer__ OpType_TopKV2__();
                                     ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:61:36: error: expected initializer before ‘OpType_Transpose__’
 extern void ___TransposeComputer__ OpType_Transpose__();
                                    ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:62:33: error: expected initializer before ‘OpType_Unpack__’
 extern void ___UnpackComputer__ OpType_Unpack__();
                                 ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:63:36: error: expected initializer before ‘OpType_Where__’
 extern void ___WhereSizeComputer__ OpType_Where__();
                                    ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:64:2: error: ‘nvoid’ does not name a type
 \nvoid registerShapeOps() {
  ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:127:3: error: ‘n’ does not name a type
 }\n}

**Comment by xiefu5hh** [comment]
把hpp的\n去掉，有问题

**Comment by xiefu5hh** [comment]
![image](https://user-images.githubusercontent.com/45812529/57431505-96df7100-7265-11e9-8c2e-34e924ea2fd1.png)
遇到一个其他问题，有人碰到吗

**Comment by anlongstory** [comment]
我是把最后一个 \n 去掉， void 前面的 \n 去掉，还有把` namespace mnn` 前面的 \n 去掉了，然后把` namespace mnn`换行下来，运行还是会报：

> /home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:63:33: error: expected initializer before ‘OpType_Unpack__’
 extern void ___UnpackComputer__ OpType_Unpack__();
                                 ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:64:36: error: expected initializer before ‘OpType_Where__’
 extern void ___WhereSizeComputer__ OpType_Where__();

和

> /home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:66:1: error: ‘___ArgMaxComputer__’ was not declared in this scope
 ___ArgMaxComputer__ OpType_ArgMax__();
 ^
/home/t702/lianghua/MNN/source/shape/ShapeRegister.hpp:67:1: error: ‘___AsStringComputer__’ was not declared in this scope
 ___AsStringComputer__ OpType_AsString__();

**Comment by anlongstory** [comment]
I solved it!  Thx
