### ISSUE TITLE
MNN - OCL kernel

### ISSUE THREAD

**Issue by pure-water** [alibaba/MNN#363]
Hi, 

Any OCL kernels have been deployed in the real-productions applications as described in the READMe? 

"MNN has been integrated in more than 20 apps of Alibaba-inc, such as Taobao, Tmall, Youku and etc., covering live broadcast, short video capture, search recommendation, product searching by image, interactive marketing, equity distribution, security risk control and other scenarios. "

Regards

**Comment by jiarenyf** [comment]
What is OCL ?

**Comment by pure-water** [comment]
OpenCL

**Comment by jxt1234** [comment]
The OpenCL kernel have been deployed in real-productions applications and tested.
