### ISSUE TITLE
Tensor::getDimensionType()存在一个bug

### ISSUE THREAD

**Issue by Guanmoyu** [alibaba/MNN#366]
[https://github.com/alibaba/MNN/blob/master/source/core/Tensor.cpp#L197](url)
Tensor::getDimensionType()只会返回Tensor::getDimensionType()和Tensor::getDimensionType()，对于数据格式为NC4HW4的tensor会导致调用TensorUtils::getDescribe(tensor)->dimensionFormat和tensor->getDimensionType()返回值不一致，即前者返回值为2（NC4HW4）而后者返回值为1（CAFFE：NCHW）。

**Comment by li-qing** [comment]
已知问题，数据legacy problem，实际值以TensorUtils::getDescribe(tensor)->dimensionFormat为准。
