### ISSUE TITLE
钉钉群人满了

### ISSUE THREAD

**Issue by yuangu** [alibaba/MNN#367]
如题

**Comment by li-qing** [comment]
正在申请扩容…敬请期待

**Comment by zhaoyang-star** [comment]
同问，希望可以申请入群

**Comment by Bran-Yang** [comment]
同问，希望可以进群交流

**Comment by wm901115nwpu** [comment]
什么时候可以扩容完成

**Comment by li-qing** [comment]
![image](https://user-images.githubusercontent.com/1464882/67542280-b9cfe580-f71e-11e9-9b47-d51febc8a93a.png)

扩容可能还要等上非常久，这里先建立二群便于交流。

**Comment by dandingol03** [comment]
过期了啊这个二维码
