### ISSUE TITLE
mnn有模型加密的功能吗?

### ISSUE THREAD

**Issue by FB-wh** [alibaba/MNN#371]

**Comment by li-qing** [comment]
没有单独的模型加密功能。可以改用Buffer接口创建Interpreter，这样，从文件到Buffer的链路上，可以自行实现加密。

**Comment by FB-wh** [comment]
> 没有单独的模型加密功能。可以改用Buffer接口创建Interpreter，这样，从文件到Buffer的链路上，可以自行实现加密。

ok，谢谢
