### ISSUE TITLE
python环境下创建的MNN.Tensor不能被释放或改写

### ISSUE THREAD

**Issue by david8862** [alibaba/MNN#374]
在使用MNN python API进行模型验证时，发现如果在python代码中使用MNN.Tensor创建一个host Tensor，其所占用的对象似乎在整个python进程生命周期中无法被释放，导致循环执行时出现内存泄漏。是否有办法强制释放该Tensor？或者能够提供类似setData()之类的方法实现在不使用其他Tensor的情况下修改host Tensor的内容，使得所创建的host Tensor能够被重复利用。

**Comment by stanleywang8888** [comment]
你用del 销毁对象Tensor内存就自然而然销毁掉了啊.

**Comment by david8862** [comment]
尝试了显式调用del，但内存仍无法释放
相关代码可参见: https://github.com/david8862/keras-YOLOv3-model-set/blob/master/eval.py#L133

> 你用del 销毁对象Tensor内存就自然而然销毁掉了啊.

**Comment by stanleywang8888** [comment]
已找到原因, 着急的可以先用tuple(100 * 1 * 28 * 28 *[0.0])代替, tuple没问题的,为方便大家用numpy, 增加numpy的通路时候里面有个引用计数搞错了, 多谢！fix上线以后再通知

**Comment by david8862** [comment]
收到，非常感谢！

> 已找到原因, 着急的可以先用tuple(100 * 1 * 28 * 28 *[0.0])代替, tuple没问题的,为方便大家用numpy, 增加numpy的通路时候里面有个引用计数搞错了, 多谢！fix上线以后再通知

**Comment by stanleywang8888** [comment]
新Python已经修正了

**Comment by stanleywang8888** [comment]
已修正，关闭

**Comment by david8862** [comment]
在pip安装的0.0.6版本上使用相同的代码进行测试，仍然遇到内存泄漏:

```
import numpy as np
import time
import MNN

for i in range(1000000):
    tmpTensor = MNN.Tensor((100, 1, 28, 28), MNN.Halide_Type_Float, np.zeros((100,1,28,28)), MNN.Tensor_DimensionType_Caffe)
    print(i)
    time.sleep(0.01)
    del tmpTensor
```

**Comment by stanleywang8888** [comment]
不好意思，低级错误, 错误休掉后，代码合错了. 后续尽快更新版本通知

**Comment by stanleywang8888** [comment]
请安装新版本，谢谢
