### ISSUE TITLE
demo/exec/pictureRecognition.cpp中的pictureTest.out文件是什么？

### ISSUE THREAD

**Issue by MSKTHU** [alibaba/MNN#376]
我在windows平台编译了mnn主库和模型转换工具，将基于tensorflow的mobilnet_v2转换成了mnn。现在想跑个例程看下，但是在调用demo/exec/pictureRecognition.cpp生成的可执行文件时，发现第一个输入参数./pictureTest.out文件缺失。请问这个文件是什么？从哪里获取？

**Comment by jxt1234** [comment]
这个是修改文件名后代码中没改过来，pictureTest.out   就是 pictureRecognition
