### ISSUE TITLE
cpu backend where op compute bug

### ISSUE THREAD

**Issue by zjd1988** [alibaba/MNN#378]
![企业微信截图_15709286388763](https://user-images.githubusercontent.com/7134030/66709519-aaed4880-ed98-11e9-9f71-b19f5bb3881a.png)

还有就是能否把degault值换成其他无效值（比如：-1之类），这样拿到where的结果时可能更容易判断个数

**Comment by czy2014hust** [comment]
where输出动态shape，目前支持不好，请等待之后版本更新。

**Comment by zjd1988** [comment]
@czy2014hust  ok ,thanks.
