### ISSUE TITLE
When the onnx model is converted to MNN, some of the output is lost.

### ISSUE THREAD

**Issue by DinghaoZhang** [alibaba/MNN#379]
The model mentioned in this issue is [here](https://www.dropbox.com/sh/3oydgbfin44i26m/AADxcbhwVOD-ewm6S_4M3p2xa?dl=0).

I use the lastest converter, and after the conversion, the first two outputs of the model are lost.

The onnx model is as follow:

![img_onnx](https://github.com/DinghaoZhang/MyPublicFiles/blob/master/onnx.png)

The mnn model after the conversion:

![img_mnn](https://github.com/DinghaoZhang/MyPublicFiles/blob/master/mnn.png)

It is worth mentioning that if I add some ops after the output node 7 and 8, the MNN converter will not lose them.

**Comment by bingqingsuimeng** [comment]
对，我也发现了这个问题

**Comment by czy2014hust** [comment]
那只是个引用，为了可视化，实际上mnn还是保存那个节点输出的。
