### ISSUE TITLE
cross build on aarch64

### ISSUE THREAD

**Issue by heweiwill** [alibaba/MNN#38]
How to build arm arch64 binary? 
Tried Install_EN.md, <Cross Compile>, not work

**Comment by li-qing** [comment]
provide detail info like error log plz.

**Comment by heweiwill** [comment]
I figured it out...
Just to close it

**Comment by muddham** [comment]
@heweiwill Please let us know the steps you followed along with your system configuration, so that it helps other users as well. Thanks@
