### ISSUE TITLE
Static version behaves differently

### ISSUE THREAD

**Issue by alcaster** [alibaba/MNN#383]
When building with flag MNN_BUILD_SHARED_LIBS=OFF it cannot compute some sizes.
It prints 

```Can't compute size for 11, name=YoloV3/MobilenetV2/Conv/Const```
from SizeComputer::computeOutputSize

If the flag is MNN_BUILD_SHARED_LIBS=ON then everything is working.

**Comment by czy2014hust** [comment]
link static library should have `-Wl,--whole-archive`
