### ISSUE TITLE
[Android]多次初始化和释放，概率性输出Tensor数据为nan值

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#384]
请问有人遇到过类似的情况吗，在Android上强制多次初始化和释放，随机出现output从第一个开始全部为nan值，且之后每一帧结果都是nan值。

没有这个bug的时候，可以正常运行。

3q！

**Comment by GaussRieman** [comment]
`MNN::Tensor *tensor_out = interpreter->getSessionOutput(session, nullptr);
 MNN::Tensor copy(tensor_out);
 tensor_out->copyToHostTensor(&copy);`

打印的是  copy.host<float>() 的值，为nan

**Comment by GaussRieman** [comment]
检查了初始化和输入tensor都没问题，但是Tensor_out的值都是-nan，且再也无法正确运行

**Comment by GaussRieman** [comment]
且有小概率第一次启动就出现这种情况

**Comment by GaussRieman** [comment]
MNN的纯CPU版本，4线程，机器是vivo R11 高通SDM660, 8核

**Comment by rafezh** [comment]
请问这个问题解决了不

**Comment by wangzhaode** [comment]
已解决
