### ISSUE TITLE
IOS demo issue

### ISSUE THREAD

**Issue by linhanquan** [alibaba/MNN#385]
I can build /project/ios/MNN successfully, but when I build /demo/ios and find this issue

File not found: /Users/username/Library/Developer/Xcode/DerivedData/playground-dhsbckxauliwjygzcaocfvkgytgp/Build/Products/Release-iphoneos/MNN/libMNN.a

**Comment by li-qing** [comment]
did you open the xcworkspace after `pod update`?

open the xcproj may result in library not found.

**Comment by li-qing** [comment]
> @li-qing Same issue. I did `pod update`. Any update on this ?

just built a release playground demo, no error found.

was there any error message in "report navigator" (CMD + 9) when you built libMNN.a?

**Comment by HilmiiKumdakci** [comment]
It worked, thanks. But it ends up with low fps in simulator (Mobilenet 6-7 fps, SqueezeNet 10 fps) with respect to CoreML implementation of the model. Do you have any idea ? I thought it would be faster using METAL backend.

**Comment by li-qing** [comment]
> It worked, thanks. But it ends up with low fps in simulator (Mobilenet 6-7 fps, SqueezeNet 10 fps) with respect to CoreML implementation of the model. Do you have any idea ? I thought it would be faster using METAL backend.
> 
> Edit : It seems like it is not running in METAL even if I chose METAL in app. There is an error "Can't Find type=1 backend, use 0 instead"

Metal is not available on simulator before Xcode 11, which is not fixed yet.

It would be much faster on deivce(armv7/arm64) than simulator(x86).

**Comment by HilmiiKumdakci** [comment]
Yes, It seems so.

Thanks a lot.
