### ISSUE TITLE
模型量化后运行时间比不量化更长，感觉是负优化

### ISSUE THREAD

**Issue by bingqingsuimeng** [alibaba/MNN#387]

**Comment by MaybeShewill-CV** [comment]
@bingqingsuimeng x86_64 没效果的 在arm上测试这个量化:)

**Comment by ChisenZhang** [comment]
我的模型也一样，原来x86_64服务器上16ms，量化后的模型35ms左右；用IOS设备调用原始的模型12-17ms，量化后的模型35ms+  跟服务器上的结果一样。

**Comment by czy2014hust** [comment]
方便的话，原始模型和量化模型邮件一下，我们测试看看。

**Comment by ChisenZhang** [comment]
> 方便的话，原始模型和量化模型邮件一下，我们测试看看。

跟领导请示一下，  结果也不对， 差的还挺多的   正常吗？

**Comment by bingqingsuimeng** [comment]
> @bingqingsuimeng x86_64 没效果的 在arm上测试这个量化:)

就是在arm上测试的。。要是x86的话，我就用不着量化了。。

**Comment by DinghaoZhang** [comment]
+1

**Comment by mayanbin06** [comment]
请问这个问题有结果了么

**Comment by longzeyilang** [comment]
我也遇到这个问题，怎么会这样

**Comment by YangLiji** [comment]
我用https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant 示例进行离线量化，运行时间也变长，请问量化后的模型在推理过程中也是按照int8计算的吗，还是又还原回float了

**Comment by wsqat** [comment]
离线量化的结果，我也变慢了。。。

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/faq.html#id16
