### ISSUE TITLE
Some issues about synchronization of OpenCL and CPU in tools/cpp/timeProfile.cpp

### ISSUE THREAD

**Issue by DinghaoZhang** [alibaba/MNN#388]
I noticed that ```tools/cpp/timeProfile.cpp``` can be compiled to a useful tool ``timeProfile```, which can show the elapsed time and flops for each node in MNN network. 

If you use CPU as the backend, ```timeProfile``` does a great job. However, if you use OpenCL as the backend, you will get an obviously incorrect result from not doing the synchronization of OpenCL and CPU, as shown below.

```bash
Node Name       Op Type                 Avg(ms)         %               Flops Rate
395             Convolution             0.526200        17.219736       2.252029
398             ConvolutionDepthwise    0.026100        0.854115        0.750676
401             Convolution             0.021600        0.706854        1.334535
403             Convolution             0.019000        0.621769        4.003606
406             ConvolutionDepthwise    0.019600        0.641404        0.563007
409             Convolution             0.018600        0.608679        1.501352
411             Convolution             0.019100        0.625042        2.252029
414             ConvolutionDepthwise    0.022200        0.726488        0.844511
417             Convolution             0.017900        0.585772        2.252029
419             Eltwise                 0.017600        0.575955        0.014915
420             Convolution             0.018000        0.589045        2.252029
423             ConvolutionDepthwise    0.018900        0.618497        0.211128
```
I read the code of MNN and found that ```MNN::Backend``` has ```onWaitFinish()```. Moreover, ```MNN::Session::runWithCalBack()``` is also used  ```onWaitFinish()``` to synchronize. But the synchronization is at the pipeline level, not  the unit level.

So I modified the ```source/core/Pipeline.cpp``` to do the synchronization about units as follows.

```cpp
ErrorCode Pipeline::executeCallBack(
        const TensorCallBackWithInfo& before, 
        const TensorCallBackWithInfo& after) {

    mBackend->onExecuteBegin();
    std::shared_ptr<char> __defer(nullptr, [this](void*) { mBackend->onExecuteEnd(); });
    for (auto& u : mUnits) {
        auto code = u->executeCallBack(before, after);
        // I modified it here
        mBackend->onWaitFinish();
        if (code != NO_ERROR) {
            return code;
        }
    }
    return NO_ERROR;
}
```

But the modification still has no effect.

**So, how can I get a synchronized timeProfile result?**

**Comment by hacker-joe** [comment]
The time of a single op is not supported yet. Currently, only the total time consumption is supported (please refer to timeprofile.out). if you want to modify it, you can refer to getCostTime function in openclruntime
