### ISSUE TITLE
树莓派4b OS选择

### ISSUE THREAD

**Issue by liuwuliuyun** [alibaba/MNN#390]
您好，
我希望在树莓派4b上使用MNN，然而如果使用32位的操作系统，例如raspbain，使用aarch64交叉编译时会出错。
log文件名
`/home/pi/mnn/build/CMakeFiles/CMakeOutput.log`
log内容
`The target system is: Linux -l - aarch64
The host system is: Linux -4.19.75-v7l+ - armv7l`
这个时候最佳的实践方法时更换树莓派的OS为 64bit OS还是使用其他编译工具？尝试过教程中另一种arm交叉编译工具还是会报错。
谢谢！

**Comment by liuwuliuyun** [comment]
我自己解决了这个问题，直接本地编译即可，不要被教程里的交叉编译所吸引 🤓

**Comment by Fauny** [comment]
> 我自己解决了这个问题，直接本地编译即可，不要被教程里的交叉编译所吸引 🤓

请教：我本地编译cpp是OK的，pymnn编译失败，有解决办法吗？

```bash

**Comment by liuwuliuyun** [comment]
我没有编译过PYMNN，因为我本来就想在树莓派上跑C++代码的，感觉python太慢了，这个问题可以请教下开发者。

**Comment by naviocean** [comment]
> 请教：我本地编译cpp是OK的，pymnn编译失败，有解决办法吗？

I got the same issue. Do you have any solutions?

**Comment by Daiqianying** [comment]
很奇怪，我也遇到了这个问题，明明静态库是使用fPIC编译的，链接的时候还是遇到了问题

`readelf --relocs foo.o  libcrypto.a | egrep '(GOT|PLT|JU?MP_SLOT)'`

是有R_AARCH64_ADR_GOT的信息输出的，奇了怪了。
