### ISSUE TITLE
ios    failed assertion `computePipelineState must not be nil.'

### ISSUE THREAD

**Issue by LanWong1** [alibaba/MNN#391]
![image](https://user-images.githubusercontent.com/33218397/66900407-54e60280-f02f-11e9-9c8c-5da79aef9378.png)
![image](https://user-images.githubusercontent.com/33218397/66900444-65967880-f02f-11e9-83a9-4690e03aee40.png)
![image](https://user-images.githubusercontent.com/33218397/66900467-721ad100-f02f-11e9-971e-1842dd369039.png)
![image](https://user-images.githubusercontent.com/33218397/66900508-865ece00-f02f-11e9-9a36-593f632ea131.png)
那么 问题出在哪儿呢？

**Comment by LanWong1** [comment]
![image](https://user-images.githubusercontent.com/33218397/66900690-dfc6fd00-f02f-11e9-8bf5-fd11c38249a9.png)

**Comment by jxt1234** [comment]
具体是哪个API触发的?

**Comment by li-qing** [comment]
看图的意思是 用脚本和用Copy Bundle Resource两种方式都不行？

只留下Copy Bundle Resource，不要脚本可以正常运行么？

另，是真机运行么？
