### ISSUE TITLE
新版代码编译出错

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#392]
最新版代码，编译库报这个错：
CPUBinary.cpp:239:14: error: ‘BinaryOpOperation_LESS_EQUAL’ was not declared in this scope
         case BinaryOpOperation_LESS_EQUAL:

**Comment by czy2014hust** [comment]
执行
```bash
cd schema
./generate.sh

**Comment by ChisenZhang** [comment]
> 执行
> 
> ```shell
> cd schema
> ./generate.sh
> ```

把这茬给忘了 谢谢
