### ISSUE TITLE
mnn支持tensorflow的GRU和 全连接 吗

### ISSUE THREAD

**Issue by liziru** [alibaba/MNN#394]
尝试将keras的pb模型转换mnn的模型，得到一下错误：
./MNNConvert -f TF --modelFile ~/keras_to_tensorflow/weights.60.pb --MNNModel ~/test60.mnn --bizCode biz

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...

***********************
Strongly Recommended: Apply Tensorflow Tool [graph transform] firstly!!! ==> fold_constants
***********************

terminate called after throwing an instance of 'Error'
  what():  [18:19:23] /home/lee/MNN-master/tools/converter/source/tensorflow/TmpGraph.cpp:64: 

===========This Model Has NOT_SUPPORTED_OP===========!!!

MNN NOT_SUPPORTED_OP: ======>[ Enter, Exit, Floor, LoopCond, Merge, NextIteration, PlaceholderWithDefault, RandomUniform, Switch, TensorArrayReadV3, TensorArrayScatterV3, TensorArrayV3, TensorArrayWriteV3,  ]<======

[1]    702 abort (core dumped)  ./MNNConvert -f TF --modelFile ~/keras_to_tensorflow/weights.60.pb --MNNModel

请问 mnn支持tensorflow的GRU和 全连接 吗？我找了官方文档依旧没看到这两个网络。

**Comment by yxpandjay** [comment]
同求官方支持

**Comment by czy2014hust** [comment]
编译MNNConvert时打开[TFMODEL_OPTIMIZE](https://github.com/alibaba/MNN/blob/1b120b44b806979fbe5a78bb1ea20151dca16916/tools/converter/CMakeLists.txt#L59)
全链接是支持的
