### ISSUE TITLE
FusedBatchNorm|SpaceToBatchND Lack Const Tensor

### ISSUE THREAD

**Issue by TPcoding** [alibaba/MNN#397]
[相关问题](https://github.com/alibaba/MNN/issues/358)

已经关掉bn的trainable 属性,但是还是无法转换. 模型是带dilation的动态图,无法固定输入大小.预计什么时候可以支持该属性?

下面是我网络模型
[4.zip](https://github.com/alibaba/MNN/files/3743201/4.zip)

**Comment by czy2014hust** [comment]
next version
