### ISSUE TITLE
转换模型的时候闪退

### ISSUE THREAD

**Issue by yuangu** [alibaba/MNN#399]
在转换模型的时候 ，会在PReluOnnx::run(MNN::OpT*, onnx::NodeProto const*, std::vector<onnx::TensorProto const*, std::allocator<onnx::TensorProto const*> >)处闪退。

命令：
./MNNConvert -f ONNX --modelFile ./rnet.proto --MNNModel  ./pnet.mnn --bizCode MNN

模型地址：
链接: https://pan.baidu.com/s/1SjkUgHyYZ4lnyNlRiV-41g&shfl=shareset 提取码: km3f 复制这段内容后打开百度网盘手机App，操作更方便哦

工具版本：
./MNNConvert -v
0.0.0.1

最后吐槽一下MNNConvert参数，-f这个还算正常的，modelFile和MNNModel 等 等 ，建盘输入的时候需要反复换大小写。建议换成input和output，并使用-i 及-o为缩写。

**Comment by czy2014hust** [comment]
之前Prelu的slope不支持非Constant输入，现在已经支持。

**Comment by yuangu** [comment]
谢谢，对了，你有没有onnx的模型格式资料？我想深入研究一下。
