### ISSUE TITLE
MNN/OpRegister.sh has some grammar error

### ISSUE THREAD

**Issue by kychennv** [alibaba/MNN#40]
one error:
it should use bash instead of sh if you want to use function because some shell version has some different usage for function

one error:
read_dir should be put behind findword

one error:
     result=`echo $line| awk -F $3 '{
  should be :
     result=`echo $line| awk -F '$3' '{

one error:
when fix these error, and run it during cmake .. in the build folder:

Register Op Begin
Start Register CPU
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Start Register Shape
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Start Register Metal
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Error: no such file "[(,)]"
Register Op End

**Comment by jxt1234** [comment]
Sorry for the bug. It will be fixed soon.

**Comment by li-qing** [comment]
use register codegen for iOS only now. relative scripts will run on macOS.
