### ISSUE TITLE
输入数据问题

### ISSUE THREAD

**Issue by MSKTHU** [alibaba/MNN#400]
我有一个caffe的模型无法输出正确结果，我采用下面的代码输入数据。我当前的img是按照NHWC形式在内存中存储数据的。
请问，这里的img应该是按照NCHW存储图片还是按照NHWC？

```
auto inputTensor = interpreter->getSessionInput(session, NULL);
auto nchwTensor = new Tensor(inputTensor, Tensor::CAFFE);
for(int i = 0; i < H * W * 3; i++){
    nchwTensor-host<float>()[i] = img[i];
}
inputTensor->copyFromHostTensor(nchwTensor);
delete nchwTensor;
```

**Comment by jxt1234** [comment]
Tensor::CAFFE 表示 NCHW 的输入

img 按照NHWC格式存放的话，需要指定为 NHWC ，也即 auto nchwTensor = new Tensor(inputTensor, Tensor::TENSORFLOW);
