### ISSUE TITLE
OpenCLRuntime.cpp 中 预存的各设备的 gflops 是否正确

### ISSUE THREAD

**Issue by zhaoyang-star** [alibaba/MNN#402]
OpenCLRuntime.cpp 中 `OpenCLRuntime(bool permitFloat16)` 函数内关于设置 Mali 和 Adreno 的 gflops 设置是否正确？比如上面写的 Adreno 640 的算力为 42.74Gflops，但实际上应该比这个高的，我手算的应该是 898Gflops，还请 check

**Comment by hacker-joe** [comment]
这个是实际运算的flops，而不是理论值。

**Comment by zhaoyang-star** [comment]
> 这个是实际运算的flops，而不是理论值。

了解，实际运算的 flops？这个实际值是如何测出的呢？个人认为实测值与测试方法强相关啊。
