### ISSUE TITLE
benchmark.out  opencl  (段错误，核心已转储)

### ISSUE THREAD

**Issue by xudh1991** [alibaba/MNN#403]
使用benchmark.out 测试pytorch版yolov3的耗时，报错：（段错误，核心已转储）
然后使用backendTest.out 测试错误位置：
1.	backendTest.cpp 38行：auto compareSession = net->createSession(compareConfig)
2.	Session.cpp 128行：auto error = iter->prepare()
3.	Pipeline.cpp 243行：auto code = mExecution->onResize(mInputs, mOutputs)
4.	WrapExecution 88行：auto result = mExecution->onResize(mWrapInputTensors, outputs)
发现错误发生在4，并且发现使用CPU时不会调用4，4的函数名就是onResize，并且没有找到其他onResize，因此个人觉得这是一个回调函数，但是发现程序并没有重新进入onResize函数
请求帮助

**Comment by ToBigboss** [comment]
> 使用benchmark.out 测试pytorch版yolov3的耗时，报错：（段错误，核心已转储）
> 然后使用backendTest.out 测试错误位置：
> 
> 1. backendTest.cpp 38行：auto compareSession = net->createSession(compareConfig)
> 2. Session.cpp 128行：auto error = iter->prepare()
> 3. Pipeline.cpp 243行：auto code = mExecution->onResize(mInputs, mOutputs)
> 4. WrapExecution 88行：auto result = mExecution->onResize(mWrapInputTensors, outputs)
>    发现错误发生在4，并且发现使用CPU时不会调用4，4的函数名就是onResize，并且没有找到其他onResize，因此个人觉得这是一个回调函数，但是发现程序并没有重新进入onResize函数
>    请求帮助

我用opencl timeProfile.out也跑出段错误， 同样在iter->prepare()这里，还在排查中

**Comment by jxt1234** [comment]
更新下测试吧
