### ISSUE TITLE
在创建session时提示 input is not ready

### ISSUE THREAD

**Issue by ffffwyy** [alibaba/MNN#405]
跑的一个tensorflow转的模型。结果在创建session时有这个错误提示。“The conv2d_1/convolution's input is not ready”  请问如何解决？

**Comment by czy2014hust** [comment]
这个一般是模型中没有输入维度信息，第一次尝试resize会有此log提示，需要指定输入维度然后再resize

**Comment by ffffwyy** [comment]
创建session时就报错了啊。还没到resize那步

**Comment by xudh1991** [comment]
@ffffwyy， 你好：
我也遇到这个问题了，请问问题解决了吗？？
