### ISSUE TITLE
模型概率性输出nan

### ISSUE THREAD

**Issue by MSKTHU** [alibaba/MNN#409]
完全相同的输入，模型概率性输出-nan。请问下这有可能是什么原因造成的？

**Comment by jxt1234** [comment]
可参考 https://github.com/alibaba/MNN/pull/382/commits/cf150921d1d230d9ca9940946a88e338cf345a7e 

先行规避

**Comment by MSKTHU** [comment]
> 可参考 [cf15092](https://github.com/alibaba/MNN/commit/cf150921d1d230d9ca9940946a88e338cf345a7e)
> 
> 先行规避

出-nan问题是在windows平台运行的。同样的代码在Linux平台运行稳定不出-nan，但是输出结果与windows平台有差异（5%左右）。android平台还没测试。

**Comment by MSKTHU** [comment]
> 可参考 [cf15092](https://github.com/alibaba/MNN/commit/cf150921d1d230d9ca9940946a88e338cf345a7e)
> 
> 先行规避

改了后windows平台还是-nan，Linux平台输出结果没变，感觉没啥影响....

**Comment by wronsky317** [comment]
解决了吗，我也遇到了，而且是在集群跑大规模预测时，偶现nan，最开始以为是BN那出的问题，调查后发现过了第一个dense层就是nan了

**Comment by wangzhaode** [comment]
最新版本没有该问题了
