### ISSUE TITLE
install MNN lib failed

### ISSUE THREAD

**Issue by kychennv** [alibaba/MNN#41]
swqa@swqa-dgx-1v-01:~/MNN/build$ make -j4
*** done ***
[  0%] Built target MNN_SCHEMA
Scanning dependencies of target MNN
[  0%] Building CXX object CMakeFiles/MNN.dir/source/backend/cpu/CPUBackend.cpp.o
[  1%] Linking CXX shared library libMNN.so
[ 90%] Built target MNN
[ 91%] Linking CXX executable ../../getPerformance.out
[ 92%] Linking CXX executable ../../testModel.out
[ 92%] Linking CXX executable ../../MNNV2Basic.out
[ 92%] Linking CXX executable ../../backendTest.out
../../libMNN.so: undefined reference to `_______()'
collect2: error: ld returned 1 exit status
tools/cpp/CMakeFiles/testModel.out.dir/build.make:95: recipe for target 'testModel.out' failed
make[2]: *** [testModel.out] Error 1
CMakeFiles/Makefile2:298: recipe for target 'tools/cpp/CMakeFiles/testModel.out.dir/all' failed
make[1]: *** [tools/cpp/CMakeFiles/testModel.out.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../libMNN.so: undefined reference to `_______()'
collect2: error: ld returned 1 exit status
tools/cpp/CMakeFiles/backendTest.out.dir/build.make:95: recipe for target 'backendTest.out' failed
make[2]: *** [backendTest.out] Error 1
CMakeFiles/Makefile2:187: recipe for target 'tools/cpp/CMakeFiles/backendTest.out.dir/all' failed
make[1]: *** [tools/cpp/CMakeFiles/backendTest.out.dir/all] Error 2
../../libMNN.so: undefined reference to `_______()'
collect2: error: ld returned 1 exit status
tools/cpp/CMakeFiles/MNNV2Basic.out.dir/build.make:121: recipe for target 'MNNV2Basic.out' failed
make[2]: *** [MNNV2Basic.out] Error 1
CMakeFiles/Makefile2:261: recipe for target 'tools/cpp/CMakeFiles/MNNV2Basic.out.dir/all' failed
make[1]: *** [tools/cpp/CMakeFiles/MNNV2Basic.out.dir/all] Error 2
[ 92%] Built target getPerformance.out
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

my env:
x86  ubuntu 18.04

**Comment by jxt1234** [comment]
Fixed
