### ISSUE TITLE
编译依赖MNN的android动态库

### ISSUE THREAD

**Issue by MSKTHU** [alibaba/MNN#410]
我根据语雀编译生成了android的libMNN.so，现自己写了基于MNN库的算法，并想把自己的算法再编译成另一个so。我的做法是在demo目录下创建自己的算法目录，并仿照demo/exec下的CMakeLists编写自己算法的CMakeLists，且将add_executable改为了add_library，能够正常生成.so但是nm -D后发现没有自己的算法接口。请问下是否有类似需求并成功走通的同学可以分享下经验？

**Comment by ChisenZhang** [comment]
干过这事儿，编完交给别人了，自己没测，应该是没问题（因为对方没说不能用。）
不是应该add_library()吗？
CMAKE文件很简单，包含以下自己代码和MNN的include目录，包含一下Android的MNN的库目录
加上下面两句，就行了。
add_library(Net SHARED Net.cpp) # for Net of linux & ANDROID
# add_library(Net STATIC Net.cpp) # for Net of iOS
target_link_libraries(Net MNN) # for Net

CMakeLists.txt 没有问题的话，用以下命令编译。
#!/bin/bash
cmake .. \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-19  \
-DANDROID_TOOLCHAIN=gcc \
make -j4

没遇见什么问题

**Comment by jxt1234** [comment]
估计是和MNN一起编译，被 HIDDEN 了，用 MNN_PUBLIC 加在自己的函数前面就好了
