### ISSUE TITLE
交叉编译 linux aarch64 平台编译不过

### ISSUE THREAD

**Issue by pengcuo** [alibaba/MNN#412]
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:23:10: fatal error: android/log.h: No such file or directory
 #include <android/log.h>
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by pengcuo** [comment]
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c: In function ‘MNNMemoryAllocAlign’:
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:24:32: warning: implicit declaration of function ‘__android_log_print’ [-Wimplicit-function-declaration]
 #define MNN_ERROR(format, ...) __android_log_print(ANDROID_LOG_ERROR, "MNNJNI", format, ##__VA_ARGS__)
                                ^
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:45:13: note: in expansion of macro ‘MNN_ERROR’
             MNN_ERROR("Error for %s, %d\n", __FILE__, __LINE__); \
             ^~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c:19:5: note: in expansion of macro ‘MNN_ASSERT’
     MNN_ASSERT(size > 0);
     ^~~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:24:52: error: ‘ANDROID_LOG_ERROR’ undeclared (first use in this function)
 #define MNN_ERROR(format, ...) __android_log_print(ANDROID_LOG_ERROR, "MNNJNI", format, ##__VA_ARGS__)
                                                    ^
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:45:13: note: in expansion of macro ‘MNN_ERROR’
             MNN_ERROR("Error for %s, %d\n", __FILE__, __LINE__); \
             ^~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c:19:5: note: in expansion of macro ‘MNN_ASSERT’
     MNN_ASSERT(size > 0);
     ^~~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:24:52: note: each undeclared identifier is reported only once for each function it appears in
 #define MNN_ERROR(format, ...) __android_log_print(ANDROID_LOG_ERROR, "MNNJNI", format, ##__VA_ARGS__)
                                                    ^
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:45:13: note: in expansion of macro ‘MNN_ERROR’
             MNN_ERROR("Error for %s, %d\n", __FILE__, __LINE__); \
             ^~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c:19:5: note: in expansion of macro ‘MNN_ASSERT’
     MNN_ASSERT(size > 0);
     ^~~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c: In function ‘MNNMemoryCallocAlign’:
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:24:52: error: ‘ANDROID_LOG_ERROR’ undeclared (first use in this function)
 #define MNN_ERROR(format, ...) __android_log_print(ANDROID_LOG_ERROR, "MNNJNI", format, ##__VA_ARGS__)
                                                    ^
/home/pengcuo/work/MNN_ARM_LINUX/MNN/include/MNNDefine.h:45:13: note: in expansion of macro ‘MNN_ERROR’
             MNN_ERROR("Error for %s, %d\n", __FILE__, __LINE__); \
             ^~~~~~~~~
/home/pengcuo/work/MNN_ARM_LINUX/MNN/source/core/MNNMemoryUtils.c:37:5: note: in expansion of macro ‘MNN_ASSERT’
     MNN_ASSERT(size > 0);

**Comment by jxt1234** [comment]
具体的编译选项是? 你是什么什么方法编译的?

**Comment by pengcuo** [comment]
cmake .. \
-DCMAKE_SYSTEM_NAME=Android \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=aarch64 \
-DCMAKE_C_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-gcc \
-DCMAKE_CXX_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-g++

**Comment by pengcuo** [comment]
cmake 信息如下：
-DCMAKE_SYSTEM_NAME=Android \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=aarch64 \
-DCMAKE_C_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-gcc \
-DCMAKE_CXX_COMPILER=$cross_compile_toolchain/bin/aarch64-linux-gnu-g++ 
-- The C compiler identification is GNU 7.4.1
-- The CXX compiler identification is GNU 7.4.1
-- Check for working C compiler: /home/pengcuo/buffer/mnn/linaro/aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /home/pengcuo/buffer/mnn/linaro/aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/pengcuo/buffer/mnn/linaro/aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /home/pengcuo/buffer/mnn/linaro/aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /home/pengcuo/buffer/mnn/linaro/aarch64/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	DEBUG: OFF
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	OpenMP: OFF
-- 	Hideen: TRUE
-- [*] searching *.c
-- [*] searching *.cc
-- [*] searching *.cpp
-- [*] searching *.s *.S
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pengcuo/work/MNN_DEBUG/MNN/build-linux

**Comment by pengcuo** [comment]
编译器是能够找到的。之前的　commit 号编译的时候，Linux-aarch64 也会有问题，比如　xxx 头文件找不到，添加　cmakeLists.txt 中　添加　include_directories　的话也能编译通过。但总感觉　ＭＮＮ　没有编译 Linux-aarch 这个平台。
有时候调试的时候，Linux 平台比　Android 平台好用多了。
谢谢阿里无私的开源，比某汤不开源却到处修优越感的好太多了。

**Comment by pengcuo** [comment]
非常感谢回复，我拉倒最新的　master ，linux-aarch64 平台能够编译过了。

**Comment by pengcuo** [comment]
这个　issue 可以关闭了
