### ISSUE TITLE
用copytohost取输出tensor的时候排布改变。

### ISSUE THREAD

**Issue by ffffwyy** [alibaba/MNN#415]
输出是tensor是caffe的，copy到hosttensor还是caffe的。结果却是排布变化了。

**Comment by li-qing** [comment]
Caffe下有Caffe_C4和Caffe两种，即，有没有对channel做pack的区别。有布局变化是正常的，只要最终布局符合你的预期就可以。

**Comment by li-qing** [comment]
https://www.yuque.com/mnn/cn/input 文档中有专门描述输入数据的 如果不是太熟悉MNN的数据布局 都建议使用copy相关接口

至于数据输入后对不对 一般都可以使用tensor的print方法 来做一个简单的核查

**Comment by ffffwyy** [comment]
自己把opencv的数据直接传进接口了。结果还是不对。是不是opencv的数据排布与NCHW,NHWC和NC4HW4都不匹配？假如我输入的tensor是NCHW，输出是不是也必须设置位NCHW呢？

**Comment by li-qing** [comment]
> @li-qing copy接口比直接通过host传值进去效率能慢多少呢，这个有测试过吗：）

如果fmt一致，那就是memcpy的时间；如果fmt不一致，那么会增加一个转换时间，转换是经过优化的，一般会比你自己实现要快。

**Comment by li-qing** [comment]
> 自己把opencv的数据直接传进接口了。结果还是不对。是不是opencv的数据排布与NCHW,NHWC和NC4HW4都不匹配？假如我输入的tensor是NCHW，输出是不是也必须设置位NCHW呢？

输入输出可以不一致，但这种情况一般只在TF场景下有。opencv一般是NCHW，有可能是不匹配的。

**Comment by MaybeShewill-CV** [comment]
@li-qing 按照我的理解直接通过host传入数据就是默认两者的fmt一致，使用copy接口则可能存在一个fmt转换的过程，这个转换过程会消耗比较多时间吗,相对于fmt一致不需要转换过程来说:)

**Comment by li-qing** [comment]
> @li-qing 按照我的理解直接通过host传入数据就是默认两者的fmt一致，使用copy接口则可能存在一个fmt转换的过程，这个转换过程会消耗比较多时间吗,相对于fmt一致不需要转换过程来说:)

一般不会太多 除非模型特别小 或者输入特别大

**Comment by MaybeShewill-CV** [comment]
@li-qing 模型特别小为什么还是耗时非常多呢?

**Comment by MaybeShewill-CV** [comment]
@li-qing 为什么模型特别小的时候这个fmt转换过程耗时会比较多呢?

**Comment by daikankan** [comment]
是不是和batchsize > 1有关

**Comment by li-qing** [comment]
> @li-qing 为什么模型特别小的时候这个fmt转换过程耗时会比较多呢?

比例问题而已。时间不会更多。

**Comment by MaybeShewill-CV** [comment]
@li-qing 感谢感谢：）
