### ISSUE TITLE
在Linux服务器上跑SSD，发现ScheduleConfig的线程数对结果影响很大。

### ISSUE THREAD

**Issue by ffffwyy** [alibaba/MNN#416]
请问这是什么原因？还有哪些参数对结果影响大的么。

**Comment by liziru** [comment]
Duplicate of #

**Comment by liziru** [comment]
多线程运行输出不稳定且结果不正确，单线程运行 结果稳定正确。

**Comment by ffffwyy** [comment]
单多线程都不正确。
另外请问谁知道输入和输出的排布如何设置。我传入一个opencv的3通道图进去，排布是如何确定的？我看convert那里没法设置排布。输入的图片直接传就可以么？

**Comment by jxt1234** [comment]
请更新下代码，这个问题最新版本已经解决
