### ISSUE TITLE
Faster rcnn support?

### ISSUE THREAD

**Issue by guoqiang0148666** [alibaba/MNN#417]
非常感谢您们的分享。
请问MNN应该是支持faster rcnn的吧？（我看到支持roi pooling和proposal 层）
请问能提供下faster rcnn的demo代码吗？ 在下是小白，非常感谢。

**Comment by LiXin0202** [comment]
> 非常感谢您们的分享。
> 请问MNN应该是支持更快rcnn的吧？（我看到支持ROI池和建议层）
> 请问能提供下更快rcnn的演示代码吗？在下是小白，非常感谢。

你好，你把faster-rcnn转成MNN模型了吗？我没转成功，想请教请教你

**Comment by li-qing** [comment]
faster rcnn是支持的，但是没有现成的demo。

**Comment by zhedasuiyuan** [comment]
> faster rcnn是支持的，但是没有现成的demo。

Hi, 您能提供更多的信息吗？可以直接用converter转换caffe model吗？多谢

**Comment by zhedasuiyuan** [comment]
试了下自己的caffe model, converter 报错
Start to Convert Other Model Format To MNN Model...
[libprotobuf FATAL /usr/local/include/google/protobuf/repeated_field.h:1537] CHECK failed: (index) < (current_size_): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: (index) < (current_size_): 
zsh: abort      ./MNNConvert -f CAFFE --modelFile  --prototxt  --MNNModel  --bizCode biz

后来发现我的model的caffe.proto 和这个repo里的很不一样 甚至有些ID被定义为不同的operator 请问有什么解决的办法吗？谢谢

**Comment by guoqiang0148666** [comment]
@zhedasuiyuan 

你好,我用的是[py_faster_rcnn](https://github.com/rbgirshick/py-faster-rcnn). 训练了一个googlenet backbone的网络, 转换的命令如下:
```
./MNNConvert -f CAFFE --modelFile XXX.caffemodel --prototxt XXX.prototxt --MNNModel XXX.mnn --bizCode biz (官方)
```
其他的编译MNN的命令都是按照官方的说明操作的.

我看你的命令好像缺了 --MNNModel

**Comment by wtmilk** [comment]
> faster rcnn是支持的，但是没有现成的demo。

大佬，请问怎么转faster rcnn

**Comment by LiXin0202** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到邮件，我将尽快给您回复。
