### ISSUE TITLE
MNN除了能支持android,ios,armlinux,还能支持RTOS+ARM吗？

### ISSUE THREAD

**Issue by yangfei963158659** [alibaba/MNN#422]
hi,我目前在安霸的平台做嵌入式开发，需要跑神经网络，该平台是RTOS(实时操作系统)+ARM，请问MNN能不能在这个平台跑网络?
安霸的交叉编译工具：
CMAKE_C_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc 
CMAKE_CXX_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-g++

 cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-g++

编译的错误信息如下:
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
-- Check for working C compiler: /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc"       
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/yangfei/MNN/build/CMakeFiles/CMakeTmp

  Run Build Command:"/usr/local/bin/make" "cmTC_b333e/fast"

  /usr/local/bin/make -f CMakeFiles/cmTC_b333e.dir/build.make
  CMakeFiles/cmTC_b333e.dir/build

  make[1]: Entering directory `/home/yangfei/MNN/build/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o

  /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
  -o CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o -c
  /home/yangfei/MNN/build/CMakeFiles/CMakeTmp/testCCompiler.c

  Linking C executable cmTC_b333e

  /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b333e.dir/link.txt
  --verbose=1

  /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
  CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o -o cmTC_b333e -rdynamic

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)

-- Configuring incomplete, errors occurred!

**Comment by li-qing** [comment]
这在test c compile的时候就报错了。

如果你确定编译器设置没问题，通过CMAKE_C_COMPILER_WORKS跳过检查试试。

**Comment by getnextwindow** [comment]
> hi,我目前在安霸的平台做嵌入式开发，需要跑神经网络，该平台是RTOS(实时操作系统)+ARM，请问MNN能不能在这个平台跑网络?
> 安霸的交叉编译工具：
> CMAKE_C_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
> CMAKE_CXX_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-g++
> 
> cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=arm -DCMAKE_C_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc -DCMAKE_CXX_COMPILER=/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-g++
> 
> 编译的错误信息如下:
> -- The C compiler identification is GNU 4.9.3
> -- The CXX compiler identification is GNU 4.9.3
> -- Check for working C compiler: /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
> -- Check for working C compiler: /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc -- broken
> CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCCompiler.cmake:61 (message):
> The C compiler
> "/usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc"
> is not able to compile a simple test program.
> 
> It fails with the following output:
> 
> Change Dir: /home/yangfei/MNN/build/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/local/bin/make" "cmTC_b333e/fast"
> 
> /usr/local/bin/make -f CMakeFiles/cmTC_b333e.dir/build.make
> CMakeFiles/cmTC_b333e.dir/build
> 
> make[1]: Entering directory `/home/yangfei/MNN/build/CMakeFiles/CMakeTmp'
> 
> Building C object CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o
> 
> /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
> -o CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o -c
> /home/yangfei/MNN/build/CMakeFiles/CMakeTmp/testCCompiler.c
> 
> Linking C executable cmTC_b333e
> 
> /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b333e.dir/link.txt
> --verbose=1
> 
> /usr/local/gcc-arm-none-eabi-4_9-2015q3-amba-20160323/bin/arm-none-eabi-gcc
> CMakeFiles/cmTC_b333e.dir/testCCompiler.c.o -o cmTC_b333e -rdynamic
> 
> CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
> CMakeLists.txt:3 (project)
> 
> -- Configuring incomplete, errors occurred!

问题解决了么

**Comment by hjchen2** [comment]
@yangfei963158659 请问之前有成功交叉编译过其他项目么，用的是cmake构建系统么？

**Comment by hjchen2** [comment]
@yangfei963158659 我这边使用这里（https://github.com/jobroe/cmake-arm-embedded/blob/master/toolchain-arm-none-eabi.cmake）提供的toolchain文件可以编译一个简单的demo，cmake命令如下：
```shell
cmake . -DTOOLCHAIN_PREFIX=/home/xxx/gcc-arm-none-eabi-5_4-2016q3 -DCMAKE_TOOLCHAIN_FILE=./toolchain-arm-none-eabi.cmake && make
```
另外我也试着编译了一下mnn，不过因为mnn用到的一些特性（比如std::mutex，std::call_once等）还不支持，因此编译失败了。编译命令如下：
```shell
cmake .. -DTOOLCHAIN_PREFIX=/home/chenhoujiang/gcc-arm-none-eabi-9-2020-q2-update -DCMAKE_TOOLCHAIN_FILE=../../test/toolchain-arm-none-eabi.cmake -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_USE_SSE=OFF
```
如果有可能，你可以自己把相关代码修复掉，并欢迎给我们提PR。
