### ISSUE TITLE
win10上编译converter的时候出现值“MT_StaticRelease”不匹配值“MD_DynamicRelease”

### ISSUE THREAD

**Issue by dhdljd** [alibaba/MNN#423]
在windows上编译MNNconverter：
1、正常安装cmake；
2、下载并安装protobuf：
2.1 git clone
2.2 git submodule update --init –recursive
2.3 cmake -G "Visual Studio 16 2019" -Dprotobuf_BUILD_TESTS=OFF ../cmake
2.4 生成sln后，在vs选择为x64 Release模式并编译
2.5 设置环境变量
3 编译MNNconverter
 在x64 native tools command prompt for vs2019 手动编译
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..  && nmake
然后报错
出现：libprotobuf.lib(repeated_field.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(ArgMaxTf.cpp.obj 中)
等错误。
请问，这个问题可能在哪儿？同样的步骤，有编译成功的。

**Comment by li-qing** [comment]
[This error is because your project has different settings of the C Runtime Library with your libraries. All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d0026ac6-0f14-495e-b5c6-19648a97cba4/mismatch-detected-for-runtimelibrary-value-mddynamicrelease-doesnt-match-value?forum=vclanguage)

设置环境变量上是不是有遗漏？

**Comment by dhdljd** [comment]
> [This error is because your project has different settings of the C Runtime Library with your libraries. All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d0026ac6-0f14-495e-b5c6-19648a97cba4/mismatch-detected-for-runtimelibrary-value-mddynamicrelease-doesnt-match-value?forum=vclanguage)
> 
> 设置环境变量上是不是有遗漏？

![image](https://user-images.githubusercontent.com/53200354/67824714-21f93f80-fb02-11e9-8ef1-21b56c9819ee.png)

![image](https://user-images.githubusercontent.com/53200354/67824758-3dfce100-fb02-11e9-8771-eda54e5ecaf9.png)

您好，谢谢回复。
已经把include和Release文件件都设置到环境变量里面了，同时，protobuflib编译选择的是release，mnnconverter工程编译选择的也是release，应该没问题吧？
而且cmake的时候，protobuflib也能找到
![image](https://user-images.githubusercontent.com/53200354/67824992-edd24e80-fb02-11e9-9bac-8f83a805ba51.png)

**Comment by dhdljd** [comment]
> [This error is because your project has different settings of the C Runtime Library with your libraries. All modules passed to a given invocation of the linker must have been compiled with the same run-time library compiler option (/MD, /MT, /LD).](https://social.msdn.microsoft.com/Forums/vstudio/en-US/d0026ac6-0f14-495e-b5c6-19648a97cba4/mismatch-detected-for-runtimelibrary-value-mddynamicrelease-doesnt-match-value?forum=vclanguage)
> 
> 设置环境变量上是不是有遗漏？

我把libprotobuf的运行时改成MD以后，前面编译都顺利了。但是到99%的时候出现下面图这样的错误，请问是什么原因吗？那几个乱码是中文（不知道怎么生成）
![image](https://user-images.githubusercontent.com/53200354/67846751-b41e3980-fb3c-11e9-8e9a-e35effb1b723.png)

**Comment by jxt1234** [comment]
请在最新版本上编译测试
