### ISSUE TITLE
新旧模型转换工具 转换出来的模型 计算量统计值有较大差距

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#424]
同一个TF的pb模型，分别用0.2.0.9的代码和最新的0.2.1.2的代码转换模型，用timeProfile测试模型，时间差不多，但是total mflops：旧代码转换的模型显示是119， 新代码显示的是637;
是计算量统计方法改变了吗？  还是内部做了什么优化导致的？

**Comment by jxt1234** [comment]
之前版本代码转换时 depthwise convolution 的 inputCount 填错了，已经修复
