### ISSUE TITLE
量化工具编译出错

### ISSUE THREAD

**Issue by Royzon** [alibaba/MNN#425]
平台和工具：
Ubuntu16.04
cmake 3.10.2
protobuf 3.9.0
gcc 5.4.0

编译命令：
cmake .. -DMNN_BUILD_QUANTOOLS=on && make -j8

报错信息：
MNN/tools/quantization/Helper.hpp:13:47: fatal error: converter/source/IR/MNN_generated.h: No such file or directory
MNN/tools/quantization/calibration.hpp:17:47: fatal error: converter/source/IR/MNN_generated.h: No such file or directory
MNN/tools/quantization/calibration.hpp:17:47: fatal error: converter/source/IR/MNN_generated.h: No such file or directory

**Comment by jxt1234** [comment]
已经修正
