### ISSUE TITLE
firefly的rk3399  Ubuntu18.04系统，编译opencl后，backend无法识别

### ISSUE THREAD

**Issue by TianminRao** [alibaba/MNN#426]
在rk3399下，ubuntu18.04。编译MNN选项开启了OPENCL，但运行forward type选opencl时，显示can't find type=3 backend。如何才能在linux下找到gpu？

**Comment by hacker-joe** [comment]
在ubuntu下需要手动dlopen mnn_opencl.so

**Comment by TianminRao** [comment]
> 在ubuntu下需要手动dlopen mnn_opencl.so

请问有示例吗？mnn_opencl.so是在backend下的libMNN_CL.so吗

**Comment by hacker-joe** [comment]
可以参考该链接：https://blog.csdn.net/u011808673/article/details/90770168

**Comment by qchfu2006** [comment]
我的Android下面也出现找不到opencl的问题：can't find type=3 backend
经验证 发现 Android里面已经有了libopencl.so，但是跟踪代码，发现__opencl_global_initializer没有被执行，导致opencl backend没有注册。 请问：  这个如何才能被执行？  如何让opencl被识别，并工作起来？谢谢 
 备注：我已经打开了MNN_OPENCL

**Comment by hacker-joe** [comment]
android版本是多少的？有编译出mnnopencl.so吗

**Comment by qchfu2006** [comment]
运行环境是Android6，查看了手机里找到了libopencl.so。 编译出了两个库libMNN.so和libMNN_CL.so。  您说的mnnopencl.so是指哪个？ 如何编译？  麻烦给了链接。多谢

**Comment by zjd1988** [comment]
@hacker-joe 你好，链接失效了。https://blog.csdn.net/u011808673/article/details/90770168

**Comment by xuguozhi** [comment]
Tips:
- main.cpp add header: #include<dlfcn.h>
- int main(): 
auto handle = dlopen("libMNN_CL.so", RTLD_NOW); 
- CMakeLists.txt: target_link_libraries(MNN pthread ${CMAKE_DL_LIBS}) 
我在RK3399 Ubuntu 18上面成功了

**Comment by smartwell** [comment]
mark

**Comment by jxt1234** [comment]
目前较简单的做法是编译时设置 -DMNN_SEP_BUILD=false ，将 opencl backend 部分 与 mnn 主体合并
