### ISSUE TITLE
Dynamic batch size?

### ISSUE THREAD

**Issue by twmht** [alibaba/MNN#431]
Hi,

Does MNN support dynamic batch size? Like tensorrt, I can create large enough batch memory (e.g., maxBatchSize) in the initialization, and at each inference time I can give a batch size which is smaller than maxBatchSize. Thus we don't need to reshape whenever changing the batch size, since reshape regarding to re-allocate the memory, which is time consuming. 

any idea or any future plan to support this feature?

**Comment by li-qing** [comment]
just resize/init the session with larger batch size. memory will be collected for reuse, no release/re-allocate until you release the session.
