### ISSUE TITLE
Tensorflow::TensorArrayGatherV3  Aborted (core dumped)

### ISSUE THREAD

**Issue by lucwan** [alibaba/MNN#433]
/home/titan/Codes/MNN-0.2.1.3/tools/converter/source/common/writeFb.cpp:72: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::TensorArrayGatherV3 | Tensorflow::TensorArrayReadV3 | Tensorflow::TensorArrayScatterV3 | Tensorflow::TensorArraySizeV3 | Tensorflow::TensorArrayV3 | Tensorflow::TensorArrayWriteV3 |
Aborted (core dumped)

**Comment by lucwan** [comment]
how to resolve this error, any hints ?

**Comment by jxt1234** [comment]
请参考 https://github.com/xindongzhang/MNN-APPLICATIONS/tree/master/applications/mssd 去跑 ssd 模型
