### ISSUE TITLE
convert a tf model to mnn model problem

### ISSUE THREAD

**Issue by JoyGun** [alibaba/MNN#434]
I use Keras train a model and convert it to pb file, both work on python code.
Then I use lastest version mnn to convert pb file to mnn I got those issues.

> libc++abi.dylib: terminating with uncaught exception of type Error: [15:44:33] /Users/lailinxiao/Desktop/MNN/tools/converter/source/common/writeFb.cpp:72: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::FusedBatchNorm | Tensorflow::PlaceholderWithDefault | 

> Converte Tensorflow's Op block_14_expand_BN/FusedBatchNorm , type = FusedBatchNorm, failed, may be some node is not const
> The Model Has Control / Extra Op, Please Compile the Code of model.cpp

**Comment by czy2014hust** [comment]
Please check the *is_training* in BN parameter is **False**，if not，set it to be False！
