### ISSUE TITLE
winograd代码相关

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#435]
WinogradGenerater.cpp中的WinogradGenerater函数，在计算mB的时候，做了两次转置，然后赋值，没看懂这两次转置的意义是啥，如下图：
![image](https://user-images.githubusercontent.com/20228088/68016279-350d3a80-fccf-11e9-97d4-00e7ad98b925.png)
打印出来的结果是一样的：
![image](https://user-images.githubusercontent.com/20228088/68016304-435b5680-fccf-11e9-83be-3c4af37a9981.png)

**Comment by jxt1234** [comment]
应该是历史遗留问题，这两次 transpose 不需要，后续修复，或者您方便的话可以提pr修复

**Comment by GaussRieman** [comment]
噢，还是等你们有空了修复吧，这个也不是什么大问题。我也是在学习MNN对winograd实现的时候发现这个的。
