### ISSUE TITLE
MNN 在　TX2 下　使用遇到模型无法加载，转换工具无法使用情况．

### ISSUE THREAD

**Issue by ArmendLee** [alibaba/MNN#436]
在TX2下部署ＭＮＮ模型时，amd64　下可以正常运行，在TX2下模型加载失败，考虑到可能是模型文件的问题，在TX2 下重新转换模型，转换时发生内存泄露，有人遇到类似问题吗？

**Comment by czy2014hust** [comment]
请检查protobuf环境，避免存在多个版本的protobuf

**Comment by BokyLiu** [comment]
Tx2还需要用MNN吗?
