### ISSUE TITLE
Install python package with MNN

### ISSUE THREAD

**Issue by buiduchanh** [alibaba/MNN#437]
I install this git follow the instruction 
https://www.yuque.com/mnn/en/build_linux
It success and I got this file libMNN.so but I can not import the MNN from python. Anyone can help me ?

**Comment by Naville** [comment]
That's the C++ core library not the python binding

**Comment by buiduchanh** [comment]
> That's the C++ core library not the python binding

https://github.com/alibaba/MNN/blob/master/pymnn/examples/MNNEngineDemo/mobilenet_demo.py
This demo using MNN as python lib. Could you check it ?

**Comment by stanleywang8888** [comment]
https://www.yuque.com/mnn/en/usage_in_python

Please see the above link for doc. Generally speaking, you need to install Python MNN package. 
command line like pip install -U MNN

**Comment by buiduchanh** [comment]
@stanleywang8888  I know. I'm working on raspberrypi so I can not install It from pip. Do you have any suggestion ?

**Comment by stanleywang8888** [comment]
Sorry, Python package depends on pip, either you can try to solve the pip issue, or you can try the c++ interface.

**Comment by buiduchanh** [comment]
> Sorry, Python package depends on pip, either you can try to solve the pip issue, or you can try the c++ interface.

I can build it con raspberry pi. Thanks for support :D

**Comment by abhishek1390** [comment]
Hi @buiduchanh ,
We are using nvidia jetson nano, We are able to build for c++ but unable get the python bindings.
We have given the pip3 command and got the error as below

> nvdia@nvdia-desktop:~$  sudo pip3 install -U MNN
> ERROR: Could not find a version that satisfies the requirement MNN (from versions: none)
> ERROR: No matching distribution found for MNN

Can you please share the steps you followed for raspberry pi so that we can try on our board.
Any help is much appreciated. Thanks and regards

**Comment by chakri-muthyala** [comment]
@abhishek1390 
Can you try this!!

**Comment by vocong25** [comment]
hi @buiduchanh, 
can you share you way to compile this lib on raspbian? thanks in advance!

**Comment by Dliang110** [comment]
> I install this git follow the instruction
> https://www.yuque.com/mnn/en/build_linux
> It success and I got this file libMNN.so but I can not import the MNN from python. Anyone can help me ?

Brother, i need you held , Did you succeed in that importing the MNN library from python on raspberry

**Comment by buiduchanh** [comment]
Sorry all. 
At first, we need understand when we build pip package It will build 2 function :
- Pip package for python
- Mnn convert tools 
I sloved this issue below: 
- Build mnn convert tools follow this site : https://www.yuque.com/mnn/en/cvrt_linux
- Build pip package for using in python : 
In file **pymnn/pip_package/setup.py** remove this line : 
`tools = Extension("_tools",\
                    libraries=tools_libraries,\
                    sources=tools_sources,\
                    language='c++',\
                    extra_compile_args=tools_compile_args + extra_compile_args,\
                    include_dirs=tools_include_dirs,\
                    library_dirs=tools_library_dirs,\
                    extra_link_args=tools_extra_link_args +tools_link_args\
                        + [make_relative_rpath('lib')])
    extensions.append(tools)`
and using **pymnn/pip_package/build_wheel.py** for build wheel file

**Comment by Dliang110** [comment]
i  see ,many  thanks------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Bùi&amp;nbsp;Đức&amp;nbsp;Hạnh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月17日(星期四) 中午11:16
收件人:&nbsp;&quot;alibaba/MNN&quot;<MNN@noreply.github.com&gt;;
抄送:&nbsp;&quot;Daliang&quot;<oktai@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/MNN] Install python package with MNN (#437)

**Comment by ling9601** [comment]
@buiduchanh 
can you tell me which mnn version you used ?
