### ISSUE TITLE
为什么量化后推理速度还不如 FP32呢？具体日志如下

### ISSUE THREAD

**Issue by pengcuo** [alibaba/MNN#438]
AARCH64 INT8：
Node Type     	         Avg(ms)   	%         	        Called times 	Flops Rate 	
EltwiseInt8   	         0.184480  	0.162284  	4.000000     	0.026584   	
Int8ToFloat   	         0.817960  	0.719546  	5.000000     	0.112982   	
FloatToInt8   	         1.122070  	0.987067  	3.000000     	0.076798   	
BinaryOp      	         2.569411  	2.260269  	2.000000     	0.053168   	
ConvertTensor 	10.647187 	9.366158  	6.000000     	0.159504   	
Deconvolution 	40.688606 	35.793106 	3.000000     	14.272134  	
ConvInt8      	        57.647507 	50.711586 	17.000000    	85.298729  	
total time : 113.677208 ms, total mflops : 1057.968018

AARCH64 FP32 ：
Node Type     	        Avg(ms)   	%         	       Called times 	Flops Rate 	
Eltwise               	1.192780  	1.081617        4.000000     	0.026635   	
BinaryOp      	        2.429960  	2.203497        2.000000     	0.053269   	
ConvertTensor 	12.368348 	11.215663 	6.000000     	0.159807   	
Deconvolution 	38.991940 	35.358032 	3.000000     	14.299272  	
Convolution   	        55.294624 	50.141365 	17.000000    	85.460922  	
total time : 110.277458 ms, total mflops : 1055.960083 

SoC: RK3399pro（4 x A53 + 2 x A72）
在骁龙 625（8 x A53）上得到的结论类似
工具是使用 timeProfiler.out 测试的

**Comment by pengcuo** [comment]
感谢阿里的同学...

**Comment by pengcuo** [comment]
肿么没有人回？

**Comment by czy2014hust** [comment]
麻烦把模型发给我们，我们来测试下

**Comment by pengcuo** [comment]
[mobilenet-v1.tar.gz](https://github.com/alibaba/MNN/files/3817772/mobilenet-v1.tar.gz)

**Comment by pengcuo** [comment]
在高通手机 855 上测试，就能复现

**Comment by pengcuo** [comment]
core 5 int16 : 15.3561 ops : 6400 time : 416.773
core 5 int8 : 30.7093 ops : 12800 time : 416.812
core 5 float : 38.5264 ops : 6400 time : 166.12
我知道了，在 855 A76 上 vmlal.s8 的吞吐量没有 vmla.f32 这条指令大。A76 变成四发射，每个周期能够执行两条 vmla.f32 指令

**Comment by pengcuo** [comment]
谢谢阿里的同学，这个 issue 可以关闭了
