### ISSUE TITLE
MNNConverter error on ubuntu16.04 x86

### ISSUE THREAD

**Issue by zefan7564** [alibaba/MNN#439]
when i convert caffe model to MNN model,MNN throw “Segmentation fault (core dumped)” 。
gcc/g++ 5.4
cmake 3.15
protobuf 3.11
I debug MNN,the error message is "Program received signal SIGSEGV, Segmentation fault.
google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField (this=0x40000002a) at google/protobuf/map_field.cc:140"

**Comment by zefan7564** [comment]
./$CONVERTER -f CAFFE --modelFile ./squeezenet_v1.1.caffe.caffemodel --prototxt ./squeezenet_v1.1.caffe.prototxt --MNNModel ./squeezenet_v1.1.caffe.mnn --bizCode 0000

throw：
Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by flying0712** [comment]
the same issue comes to me with the when doing:
""
../build/MNNConvert -f CAFFE  --modelFile squeezenet_v1.1.caffe.caffemodel --prototxt squeezenet_v1.1.caffe.prototxt --MNNModel squeezenet_v1.1.caffe.mnn --bizCode biz

MNNConverter Version: 0.0.0.1 - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
"""

ubuntu16.04 x86
gcc 5.4.0 
cmake  3.10.2
libprotoc 3.9.2

**Comment by lth611798** [comment]
mobilenet是正常的，squeezenet就会报错了

**Comment by zefan7564** [comment]
对，转自己的模型也是报错。官方能不能给解决一下

**Comment by czy2014hust** [comment]
我们已经验证过了，我们提供的(squeezenet_v1.1.caffe)[https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1]转换是没有问题的，请检查环境中是否有多个版本的protobuf库，*what(): std::bad_alloc*大概率是protobuf出现问题，可以gdb调试下，提供下更多log，谢谢！

**Comment by czy2014hust** [comment]
我们已经验证过了，我们提供的[squeezenet_v1.1.caffe](https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1)转换是没有问题的，请检查环境中是否有多个版本的protobuf库，*what(): std::bad_alloc*大概率是protobuf出现问题，可以gdb调试下，提供下更多log，谢谢！

**Comment by zefan7564** [comment]
转caffe模型时，运行到creator->run(op, layer, *layerP);跳转到tfOpConverter.cpp下run的(MNN::OpT *dstOp, TmpNode *srcNode)，运行到82行报错。转caffe model跳转tfOpConverter导致的错误吧。到以下是调试log：
Breakpoint 4, main (argc=11, argv=0x7fffffffdfa8) at /home/yzf/yzf/MNN/tools/converter/source/MNNConverter.cpp:31
31	    std::cout << "Start to Convert Other Model Format To MNN Model..." << std::endl;
Breakpoint 2, caffe2MNNNet (prototxtFile="NL_FD_v4_det3.prt", modelFile="NL_FD_v4_det3.cml", bizCode="MNN", netT=std::unique_ptr<MNN::NetT> containing 0x7db280) at /home/yzf/yzf/MNN/tools/converter/source/caffe/caffeConverter.cpp:125
125	        creator->run(op, layer, *layerP);
Program received signal SIGSEGV, Segmentation fault.
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245

**Comment by zefan7564** [comment]
找到原因了，转自己模型时data层为MemoryData，转squeezenet时含Dropout。MemoryData和Dropout不在MNN支持的OP中因此会崩溃。

**Comment by czy2014hust** [comment]
> 转caffe模型时，运行到creator->run(op, layer, *layerP);跳转到tfOpConverter.cpp下run的(MNN::OpT *dstOp, TmpNode *srcNode)，运行到82行报错。转caffe model跳转tfOpConverter导致的错误吧。到以下是调试log：
> Breakpoint 4, main (argc=11, argv=0x7fffffffdfa8) at /home/yzf/yzf/MNN/tools/converter/source/MNNConverter.cpp:31
> 31 std::cout << "Start to Convert Other Model Format To MNN Model..." << std::endl;
> Breakpoint 2, caffe2MNNNet (prototxtFile="NL_FD_v4_det3.prt", modelFile="NL_FD_v4_det3.cml", bizCode="MNN", netT=std::unique_ptrMNN::NetT containing 0x7db280) at /home/yzf/yzf/MNN/tools/converter/source/caffe/caffeConverter.cpp:125
> 125 creator->run(op, layer, *layerP);
> Program received signal SIGSEGV, Segmentation fault.
> __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245

下个版本修复
