### ISSUE TITLE
run get_model.sh error

### ISSUE THREAD

**Issue by wangzilu** [alibaba/MNN#44]
[ 39%] Built target caffe
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
cp: cannot stat '../tools/converter/build/MNNConvert': No such file or directory
downloading model for MobileNet V1

**Comment by czy2014hust** [comment]
Build converter failed! You can try build converter according to [Converter README].(https://github.com/alibaba/MNN/tree/master/tools/converter)

**Comment by wangzilu** [comment]
@czy2014hust Thank you for your reply, but still failed..

[  7%] Linking CXX executable MNNDump2Json.out
[  7%] Built target MNNDump2Json.out
[  8%] Building CXX object source/tflite/CMakeFiles/tflite.dir/ConcatTflite.cpp.o
[  8%] Building CXX object source/tflite/CMakeFiles/tflite.dir/liteOpConverter.cpp.o
[  9%] Building CXX object source/tflite/CMakeFiles/tflite.dir/TfliteUtils.cpp.o
[  9%] Building CXX object source/tflite/CMakeFiles/tflite.dir/liteConverter.cpp.o
[ 10%] Building CXX object source/tflite/CMakeFiles/tflite.dir/ReshapeTflite.cpp.o
[ 11%] Linking CXX shared library libtflite.so
[ 11%] Built target tflite
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangzilu** [comment]
Ubuntu 16.04 gcc 5.4

**Comment by czy2014hust** [comment]
Remove all under the build folder, then camke and make again.(If failed again, please provide more info)

**Comment by wangzilu** [comment]
@czy2014hust  still failed. and here is my cmake information,

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ian/Downloads/face_pro/MNN-master/tools/converter/build

**Comment by wangzilu** [comment]
and here is the error info,
[ 11%] Linking CXX shared library libtflite.so
[ 11%] Built target tflite
[ 11%] Running C++ protocol buffer compiler on versions.proto
versions.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
source/tensorflow/CMakeFiles/tensorflow.dir/build.make:134: recipe for target 'source/tensorflow/versions.pb.cc' failed
make[2]: *** [source/tensorflow/versions.pb.cc] Error 1
CMakeFiles/Makefile2:202: recipe for target 'source/tensorflow/CMakeFiles/tensorflow.dir/all' failed
make[1]: *** [source/tensorflow/CMakeFiles/tensorflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wangzilu** [comment]
maybe my protobuf version is not correct, thx
