### ISSUE TITLE
Inference time is unstable/slow on android

### ISSUE THREAD

**Issue by gasgallo** [alibaba/MNN#442]
I'm testing inference time with different models on android device.
I compare time obtained from benchmark tool and from android demo app and I noticed two things:
- inference time measured with benchmark tool is a lot lower than the one measured in android demo app
- inference time in android app is very unstable, meaning that for the same model executed multiple times the cost time varies up to 300% (e.g. 80-240ms)

Any insight about these two points?

**Comment by jxt1234** [comment]
The android demo app don't pre heat the device or heavily use device, so the cpu / gpu usage is not high and then the freq is not stable. You can use Android Studio's trace to analysis it.

**Comment by gasgallo** [comment]
Is there any way to improve that?

**Comment by xiongzhangdavid** [comment]
same problem, model run on iphone 6 cpu takes 100ms while on mi4 android 4.4 takes 1.5 seconds

**Comment by nsl2014fm** [comment]
+1

**Comment by jenyav94** [comment]
It's likely that the app was compiled in debug mode.
