### ISSUE TITLE
win10+vs2017编译0.2.1.4版本错误

### ISSUE THREAD

**Issue by MSKTHU** [alibaba/MNN#443]
win10；vs2017；cmake 3.16.0-rc2；编译0.2.1.4版本出现如下错误，之前使用0.2.1.0版本从未出现过该问题。

[  0%] Building CXX object CMakeFiles/MNN.dir/source/core/Interpreter.cpp.obj
Interpreter.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\xutility(2310): error C2280: 'std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\memory(1858): note: see declaration of 'std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>::operator ='
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\xutility(2329): note: see reference to function template instantiation '_OutIt std::_Copy_unchecked1<_InIt,_OutIt>(_InIt,_InIt,_OutIt,std::_General_ptr_iterator_tag)' being compiled
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1387): note: see reference to function template instantiation '_OutIt *std::_Copy_unchecked<_Iter,std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>*>(_InIt,_InIt,_OutIt)' being compiled
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Ty=MNN::Pipeline,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1405): note: see reference to function template instantiation 'void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1405): note: see reference to function template instantiation 'void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)' being compiled
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1427): note: see reference to function template instantiation 'void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>*>(_Iter,_Iter)' being compiled
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1427): note: see reference to function template instantiation 'void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>*>(_Iter,_Iter)' being compiled
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\vector(1414): note: while compiling class template member function 'std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)'
        with
        [
            _Ty=MNN::Pipeline
        ]
d:\msk\hms\mnn14\source\core\Session.hpp(145): note: see reference to function template instantiation 'std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)' being compiled
        with
        [
            _Ty=MNN::Pipeline
        ]
d:\msk\hms\mnn14\source\core\Session.hpp(138): note: see reference to class template instantiation 'std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>' being compiled
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\include\memory(1858): note: 'std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': function was explicitly deleted
        with
        [
            _Ty=MNN::Pipeline
        ]
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~4\2017\PROFES~1\VC\Tools\MSVC\1410~1.250\bin\HostX64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by yxpandjay** [comment]
报同样的错。0.2.1.0可正常编译 , 0.2.1.1及以上的版本都会报错

**Comment by zefan7564** [comment]
同样遇到

**Comment by zjd1988** [comment]
[tools.zip](https://github.com/alibaba/MNN/files/3846751/tools.zip)

这个是我根据最新版本0.2.1.2版本，在本地编译的动态库和转换工具，只测试了转换工具是否正常，动态库并没有验证，等后续有空我再编下最新的版本。

**Comment by Martyn10** [comment]
`Session `needs to inherit `NonCopyable`
e.g.
`class MNN_PUBLIC Session : public NonCopyable{`
instead of
`class MNN_PUBLIC Session{`

**Comment by yizhaoyanbo** [comment]
同样遇到，0.2.1.0以上版本都编译不过

**Comment by ChisenZhang** [comment]
真巧 我也遇到了

**Comment by jxt1234** [comment]
已经修复了，请更新到最新版本
