### ISSUE TITLE
Android studio - Unable to run the project on x86 devices

### ISSUE THREAD

**Issue by SairoopaSanthanaraman** [alibaba/MNN#444]
I am trying to run the MNN Android project using Android Studio / Gradle on my x86 machine. I am using Google pixel ADK. When I build the project, it gives me the error
"**Cannot build selected target ABI: x86, no suitable splits configured: armeabi-v7a;**"

I have installed the latest NDK on Android studio also. But I am unable to get this running.

Thanks a lot for your help in advance.

**Comment by ChisenZhang** [comment]
use the true device to test; this error maybe the virtual machine can not found the lib of X86

**Comment by SairoopaSanthanaraman** [comment]
I tried with true device as well.i got the same error. I am not able to find any lib dependencies related to x86 in lib folder. It is present only for armabi-v7a and arm64-v8a

**Comment by ChisenZhang** [comment]
> I tried with true device as well.i got the same error. I am not able to find any lib dependencies related to x86 in lib folder. It is present only for armabi-v7a and arm64-v8a

in the true device the program will not to find x86 lib, mybe something wrong of your setting.

**Comment by yasinxdxd** [comment]
click gradle.properties
you gonna see that --> PROP_APP_ABI=armeabi-v7a
add x86 like that:
PROP_APP_ABI=armeabi-v7a:x86
and sync again

**Comment by miq0717** [comment]
@SairoopaSanthanaraman Found any solution? I'm also facing the same issue :(

**Comment by rahulgsa** [comment]
@miq0717 @SairoopaSanthanaraman Found any solution? I'm also facing the same issue.

**Comment by fpalmqvist** [comment]
check your app's build.gradle, defaultConfig section - you need to add x86 to your ndk abiFilters
`ndk.abiFilters 'armeabi-v7a','arm64-v8a', 'x86'`

**Comment by pospospos2007** [comment]
@fpalmqvist Bruh you saved us.

**Comment by charlottetreesa** [comment]
> click gradle.properties
> you gonna see that --> PROP_APP_ABI=armeabi-v7a
> add x86 like that:
> PROP_APP_ABI=armeabi-v7a:x86
> and sync again

- this worked for me
