### ISSUE TITLE
python 版本 'MNN.Interpreter' object has no attribute 'getSessionOutputAll'

### ISSUE THREAD

**Issue by mcmingchang** [alibaba/MNN#445]
如题。跑的是centernet，有三个部分的输出，getSessionOutput只能获取第一个

**Comment by stanleywang8888** [comment]
收到，看接口后面怎么暴露出来. 可以先用getSessionOutput(tensorname)一个一个拿出来.

**Comment by mcmingchang** [comment]
getSessionOutput(session) 只能这么用啊，不能加tensorname

**Comment by stanleywang8888** [comment]
安装新python包，可以getSessionInputAll, getSessionOutputAll,返回均为dict类型, key是tensorname, item是对应的tensor.
