### ISSUE TITLE
rk3399上ubuntu18系统，使用opencl后端，copyToHostTensor耗时较长。

### ISSUE THREAD

**Issue by bingkunlearn** [alibaba/MNN#447]
新手上路，在rk3399上ubuntu系统使用opencl调用mali-t860 gpu运行，copyToHostTensor耗时需要20ms。请问是什么原因？　若使用deviceid来直接获取结果该怎么使用？　谢谢

**Comment by smartwell** [comment]
> 新手上路，在rk3399上ubuntu系统使用opencl调用mali-t860 gpu运行，copyToHostTensor耗时需要20ms。请问是什么原因？　若使用deviceid来直接获取结果该怎么使用？　谢谢

我好像也是这个问题, 你是怎么解决的

**Comment by chen1399** [comment]
想问下这个问题怎么解决的
