### ISSUE TITLE
Why the size of mobilenetV2 is only 15K?

### ISSUE THREAD

**Issue by kl456123** [alibaba/MNN#448]
First the size of MobileNet-Caffe/mobilenet_v2.caffemodel is 14M .
after converted, it unchanged.
after quantized, it changed to 3.5M.
So how can I make it

**Comment by czy2014hust** [comment]
where mobilenetv2? MNN/benchmark/models?(have no weight parameter data)?
These models is only used for time-benchmark!

**Comment by kl456123** [comment]
Sorry, I misunderstood.
