### ISSUE TITLE
android build fail

### ISSUE THREAD

**Issue by 121786404** [alibaba/MNN#449]
NATIVE_INCLUDE_OUTPUT
默认没有设置的话，MNN_INCLUDE_OUTPUT就越是/MNN,这个目录没有权限

**Comment by 121786404** [comment]
MNN_BUILD_FOR_ANDROID_COMMAND
是什么东西，NDK编译的时候，要加上吗？

**Comment by Naville** [comment]
``MNN_BUILD_FOR_ANDROID_COMMAND`` 是Android编译开关。传true或YES即可

如果您按照这里的编译方式编译的话这几个参数是有帮您加上的 https://www.yuque.com/mnn/cn/build_android
