### ISSUE TITLE
不同图片输入获取结果不变的问题

### ISSUE THREAD

**Issue by zefan7564** [alibaba/MNN#454]
为了代码精简，对MNN进行了一次封装，已测试封装的正确性。在推理人脸识别网络时结果正确，但是在推理人脸检测第二阶段时，输出tensor的数据始终不变。

MNNConvertor输出如下：
`
Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[11:16:28] :122: Inputs: data
[11:16:28] :139: Outputs: conv5-2_16, Type = Reshape
[11:16:28] :139: Outputs: prob1, Type = Softmax
Converted Done! `
测试代码如下：
`string imgname[2]={"o_4.jpg","dog.jpg"};
    NL_InferenceEngine nlif2;
    nlif2.loadModel(NULL,"NL_FD_v4_det2.mnn");
    // nlif2.loadModel(NULL,"mobilenet_v1.caffe.mnn");
    Mat img2,img1;
    for(int i=0;i<200;++i)
    {
        if(i%2==0)
            img2 = imread(imgname[0]);
        else
            img2 = imread(imgname[1]);

        nlif2.inputData(img2.data,img2.cols,img2.rows,3,16,16);

        nlif2.forward();

        vector<float> regData;
        vector<int> regShape;
        vector<float> confData;
        vector<int> confShape;

        //nlif2.getOutput("conv5-2_16",regData,regShape);
        nlif2.getOutput("prob1",confData,confShape);
    } `

分别测试mobilenet_v1.caffe.mnn和NL_FD_v4_det2.mnn。mobilenet_v1.caffe.mnn输入是224*224，NL_FD_v4_det2.mnn输入是16*16
实验结果是mobilenet会随着输入图片的改变输出结果也相应改变，但NL_FD_v4_det2却始终不变。
所以我怀疑是模型上的问题，应该是在MNNConvertor。相同模型在ncnn上是正常的

**Comment by zefan7564** [comment]
当我下载旧版release 0.2.0.6编译MNNConverter，转换出模型。推理结果正常。下面贴出两个版本的MNNConverter输出log。不知道是否属于bug
release 0.2.0.6：
`Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[15:06:39] :44: Inputs: input
[15:06:39] :54: Outputs: conv5-2, Type = Convolution
[15:06:39] :54: Outputs: prob1, Type = Softmax
Converted Done!`

release 0.2.1.2：
`Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
[14:58:26] :169: Inputs: data
[14:58:26] :186: Outputs: conv5-2, Type = Reshape
[14:58:26] :186: Outputs: prob1, Type = Softmax
Converted Done!
`
conv5-2,一个识别出Type = Convolution另一个识别出Type = Reshape
不知道是什么原因导致的

**Comment by czy2014hust** [comment]
应该是模型做了优化，，可否贴下输出的模型结构图？

**Comment by zefan7564** [comment]
layer {
  name: "conv5-2_16"
  type: "InnerProduct"
  bottom: "conv4"
  top: "conv5-2_16"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 4
    #kernel_size: 1
    #stride: 1
    weight_filler {
      type: "xavier"
	}
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}
layer {
  name: "prob1"
  type: "Softmax"
  bottom: "conv5-1_16"
  top: "prob1"
}
最后的输出层的结构如上。
可是文档上支持的OP中也没有Reshape。

**Comment by zefan7564** [comment]
InnerProduct 识别成Convolution感觉也不大合理

**Comment by czy2014hust** [comment]
1. InnerProduct会分成conv+reshape等，所以不用关心最后输出op Type；
2. 【但NL_FD_v4_det2却始终不变】请仔细看下两个模型的调用关系，或者单独测试每个模型正确性

**Comment by zefan7564** [comment]
测试的时候就是单独测试模型的正确性，测试代码贴在一楼，对于MTCNN作者的原始RNet模型使用新版的MNNConverter转换的模型也是相同的问题。

**Comment by czy2014hust** [comment]
现在的问题是结果不对还是结果一直不变？

**Comment by zefan7564** [comment]
release 0.2.0.6结果正确，release 0.2.1.2结果一直不变

**Comment by czy2014hust** [comment]
你把出问题的原始模型和转换过的模型传一下吧，我们测试下。

**Comment by zefan7564** [comment]
使用MTCNN的RNET和ONet。我发现使用直接git clone下来编译的库才有这个问题，release版本不会。大佬们检查一下是否引入新bug了
