### ISSUE TITLE
TFlite model version ERROR!  tensorflow2.0

### ISSUE THREAD

**Issue by 610265158** [alibaba/MNN#458]
How to convert a tf2.0 tflite model ， is it supported?

**Comment by czy2014hust** [comment]
Please send the model to us.

**Comment by 610265158** [comment]
> Please send the model to us.

please check it there

https://drive.google.com/open?id=12EWrzVk77TRWP-QjgueYiaOG8H-Qs6Aq

Thank you

**Comment by czy2014hust** [comment]
Please test again, I did't meet the error.

**Comment by czy2014hust** [comment]
By the way, the tflite support less ops than tensorflow, please convert model from tensorflow(pb) to mnn model.

**Comment by 610265158** [comment]
> By the way, the tflite support less ops than tensorflow, please convert model from tensorflow(pb) to mnn model.

Sorry, it is the reason that i use the old codes. It is fine now.

Pb is the tensorflow1 formate, however, most of my work are done by tf2 now. 
By the way, do you have any plan to support tensorflow2 model?

Thank you very much for quick reply.

**Comment by czy2014hust** [comment]
The format of tf2 is also the frozen graph(protobuffer format, aka pb).

**Comment by 610265158** [comment]
Sorry for bother again.
As i known, in tf2 , the pb (the graph) , and the variables are separate, it really cofuse me.

**Comment by TCBocean** [comment]
@610265158 
Did you solve the problem of exporting the pb model in tf2.x version? I use the keras.Model subclass to define the model. Saving such a model in tflite mode is very simple, but the exported pb model seems to be unusable. I do n’t know the names of its input and output nodes. The model directly exported from keras.Model seems to save all the methods in the Model, not just the call method. I don't know how to convert such a model to MNN?
Do you have any advice?

**Comment by 610265158** [comment]
@TCBocean 
The best method,  stick tight with tensorflow1, LoL.

**Comment by TCBocean** [comment]
@610265158 
LoL.
I saw a blog here, it seems useful, I decided to try it tomorrow
https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/

**Comment by 610265158** [comment]
@TCBocean Working with tensorflow1 and mnn and coreml is quite comfortable, everything seems good. I will retired when tf1 fucked up totally. LoL
