### ISSUE TITLE
EXCUTION MODLE ERROR

### ISSUE THREAD

**Issue by SSunWuKong** [alibaba/MNN#459]
in the  iOS demo, we tried several things ，copyFromHostTensor() always return false,  It is unable to copy data to inptutTensor, Has anyone successfully run their own model？

**Comment by StephenLee2016** [comment]
hi，when i ran my model which convert from onnx i also met this issue ，input tensor return false。

**Comment by SSunWuKong** [comment]
> hi，when i ran my model which convert from onnx i also met this issue ，input tensor return false。

If your model input is variable, get input, resizeTensor and reaizeSession befor copy

**Comment by jxt1234** [comment]
See https://www.yuque.com/mnn/en/input
copyFromHostTensor should be called by the tensor get from session.
