### ISSUE TITLE
Android studio run demo, add_library failed,

### ISSUE THREAD

**Issue by xiaohaipeng** [alibaba/MNN#46]
CMake Error at CMakeLists.txt:34 (add_library):
  add_library cannot create imported target "MNN" because another target with
  the same name already exists.

**Comment by xiaohaipeng** [comment]
[*] searching *.c
[*] searching *.cc
[*] searching *.cpp
[*] searching *.s *.S
[*] linking MNN with Vulkan done
[*] linking MNN with OpenGL done
[*] linking MNN with OpenCL done
[*] Checking OpenMP
CMake Error at CMakeLists.txt:34 (add_library):
  add_library cannot create imported target "MNN" because another target with
  the same name already exists.``

**Comment by jxt1234** [comment]
The android demo's CMakelists.txt needn't be modified.

You may add these code as Tutorial_CN.md: 

add_library( MNN SHARED IMPORTED )
set_target_properties(
                MNN
                PROPERTIES IMPORTED_LOCATION
                ${lib_DIR}/${ANDROID_ABI}/libMNN.so
                )

Just delete these code.

**Comment by xiaohaipeng** [comment]
> The android demo's CMakelists.txt needn't be modified.
> 
> You may add these code as Tutorial_CN.md:
> 
> add_library( MNN SHARED IMPORTED )
> set_target_properties(
> MNN
> PROPERTIES IMPORTED_LOCATION
> ${lib_DIR}/${ANDROID_ABI}/libMNN.so
> )
> 
> Just delete these code.

just open android in demo folder, no need modify anything?

**Comment by jxt1234** [comment]
"just open android in demo folder, no need modify anything?"

Yes

**Comment by xiaohaipeng** [comment]
> "just open android in demo folder, no need modify anything?"
> 
> Yes

your android studio version ,ndk version and cmake version?
