### ISSUE TITLE
输出shape不对的问题

### ISSUE THREAD

**Issue by evi-Genius** [alibaba/MNN#461]
我用onnx输出的shape是(1,1,256,128)然而转换成mnn后
len(output_tensor.getData())=120516  ！=256×128
而且输出的值全都是0！
用https://convertmodel.com/?tdsourcetag=s_pcqq_aiomsg的在线转换工具输出的shape也不对，但是能够输出非0值！

**Comment by evi-Genius** [comment]
看了下每层的输入输出，是反卷积的问题`！=
==> compute shape: deconvupsample_1, [17]
Inputs:
1, 48, 32, 16, 
Outputs:
1, 16, 63, 31,

**Comment by czy2014hust** [comment]
> 看了下每层的输入输出，是反卷积的问题`！=
> ==> compute shape: deconvupsample_1, [17]
> Inputs:
> 1, 48, 32, 16,
> Outputs:
> 1, 16, 63, 31,

更下下代码重新编译MNNConverter，再测试下

**Comment by evi-Genius** [comment]
===> compute shape: deconvupsample_1, [17]
Inputs:
1, 48, 32, 16, 
Outputs:
1, 16, 63, 31, 
git pull后再编译了....还是不对啊！我要哭了

**Comment by evi-Genius** [comment]
Hi...有人嘛

**Comment by czy2014hust** [comment]
> ===> compute shape: deconvupsample_1, [17]
> Inputs:
> 1, 48, 32, 16,
> Outputs:
> 1, 16, 63, 31,
> git pull后再编译了....还是不对啊

不好意思，已经修复还未同步，下个版本更新修复。

**Comment by evi-Genius** [comment]
好的好的O(∩_∩)O~

**Comment by czy2014hust** [comment]
已经更新，重新试下

**Comment by evi-Genius** [comment]
make的时候好像出现错误了...
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp: In member function ‘virtual MNN::OpType CustomTflite::opType(bool)’:
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp:17:12: error: ‘OpType_DetectionPostProcess’ is not a member of ‘MNN’
     return MNN::OpType_DetectionPostProcess;
            ^
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp: In member function ‘virtual MNN::OpParameter CustomTflite::type(bool)’:
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp:21:12: error: ‘OpParameter_DetectionPostProcessParam’ is not a member of ‘MNN’
     return MNN::OpParameter_DetectionPostProcessParam;
            ^
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp: In member function ‘virtual void CustomTflite::run(MNN::OpT*, const std::unique_ptr<tflite::OperatorT>&, const std::vector<std::unique_ptr<tflite::TensorT> >&, const std::vector<std::unique_ptr<tflite::BufferT> >&, const std::vector<std::unique_ptr<tflite::OperatorCodeT> >&, bool)’:
/home/xiang/CLionProjects/MNN/tools/converter/source/tflite/CustomTflite.cpp:32:41: error: ‘DetectionPostProcessParamT’ in namespace ‘MNN’ does not name a type
     auto postProcessParam    = new MNN::DetectionPostProcessParamT;

**Comment by jxt1234** [comment]
进入 schema 文件夹执行 ./generate.sh 更新一下

**Comment by evi-Genius** [comment]
最终输出shape一致了..虽然里面运行的逻辑不知道对不对
===> compute shape: Deconvolution221, [17]
Inputs:
1, 16, 64, 32, 
Outputs:
1, 12, 127, 63, 

===> compute shape: Const221, [11]
Outputs:
8, 

===> compute shape: deconvupsample_2, [45]
Inputs:
1, 12, 127, 63, 
8, 
Outputs:
1, 12, 128, 64, 

又有一个比较重要的问题就是onnx转MNN后大部分的weight都变成了0..

**Comment by czy2014hust** [comment]
可以MNNDump2Json.out去查看weight

**Comment by evi-Genius** [comment]
我是用MNNDump2Json.out 查看weight的..也看了onnx的weight，排除数值极小的onnx weight转mnn可能会变为0，mnn的weight为0的占了80%,而bias却没有为0的值

**Comment by evi-Genius** [comment]
基本就是一整层的weight全都是0

**Comment by czy2014hust** [comment]
把模型发下，我们调试下

**Comment by evi-Genius** [comment]
发您邮件吗

**Comment by evi-Genius** [comment]
> 把模型发下，我们调试下

发您邮件吗

**Comment by evi-Genius** [comment]
已发

**Comment by czy2014hust** [comment]
![image](https://user-images.githubusercontent.com/18324393/68925581-415cc180-07be-11ea-8f23-87be66ea8e84.png)

BN的scale有问题，conv+bn合并之后你看到weight为0正常，请检查模型。

**Comment by czy2014hust** [comment]
> 我用onnx输出的shape是(1,1,256,128)然而转换成mnn后
> len(output_tensor.getData())=120516 ！=256×128
> 而且输出的值全都是0！
> 用[https://convertmodel.com/?tdsourcetag=s_pcqq_aiomsg的在线转换工具输出的shape也不对，但是能够输出非0值！](https://convertmodel.com/?tdsourcetag=s_pcqq_aiomsg%E7%9A%84%E5%9C%A8%E7%BA%BF%E8%BD%AC%E6%8D%A2%E5%B7%A5%E5%85%B7%E8%BE%93%E5%87%BA%E7%9A%84shape%E4%B9%9F%E4%B8%8D%E5%AF%B9%EF%BC%8C%E4%BD%86%E6%98%AF%E8%83%BD%E5%A4%9F%E8%BE%93%E5%87%BA%E9%9D%9E0%E5%80%BC%EF%BC%81)

这也是你看输出全为0的原因。
