### ISSUE TITLE
onnx resize error

### ISSUE THREAD

**Issue by twmht** [alibaba/MNN#463]
Trying to convert retinaface onnx (https://github.com/biubug6/Face-Detector-1MB-with-landmark#c_inference-_ncnn) to mnn

MNNConverter works fine but resize and run would throw the error. 

the default size is set to 640x640

when resize to other resolution and run with the session it would throw 

```
"Can't run session because not resized"
```

```
https://github.com/alibaba/MNN/blob/master/source/core/Session.cpp#L77
```

I have resized the tensor and session according to https://github.com/alibaba/MNN/issues/65#issuecomment-492154021

After digging the code, I found that the root cause is from

https://github.com/alibaba/MNN/blob/master/source/core/Session.cpp#L127

So `mNeedResize` is not set to false.

And the error code is 

```
Resize error for 405, code=3
```

I found that 405 is a binaryOP, not sure what it does.

the model file has been uploaded as an attachment.
[faceDetector.zip](https://github.com/alibaba/MNN/files/3862512/faceDetector.zip)

Any idea?

**Comment by jxt1234** [comment]
I found no error for the model. What's your code for " resize and run" ?

**Comment by twmht** [comment]
@jxt1234 

Here is the sample code to reproduce the issue


```
auto netPtr = MNN::Interpreter::createFromFile(file);
MNN::ScheduleConfig sch_config;
sch_config.type = (MNNForwardType)forwardType;
if ( num_thread > 0 )sch_config.numThread = num_thread;
auto sessionPtr = netPtr->createSession(sch_config);

std::vector<int>dims = { 1, 3, 320, 320};
MNN::Tensor* tensorPtr = netPtr->getSessionInput(sessionPtr, nullptr);
netPtr->resizeTensor(tensorPtr, dims);
netPtr->resizeSession(sessionPtr);

# run the session will throw exceptions as I described.
```

**Comment by czy2014hust** [comment]
Change the **default size** when exporting onnx model.
Because MNNConverter will optimize the model, like constant_fold, it will use the default size information to fold the constant sub-graph, so resize the default size, not other size.

**Comment by twmht** [comment]
@czy2014hust 

so we can't resize the input in runtime if we export with onnx model?

**Comment by czy2014hust** [comment]
Yes, from version 0.2.1.0.
We will discuss this optimization.
By the way, if you want to change the input dimension now, **Change the default size** when exporting onnx model.

**Comment by twmht** [comment]
@czy2014hust  

We don't need to change the default size, since it's already default size when we load the model.

Now I have to convert the model to caffe

**Comment by ystsaan** [comment]
as @czy2014hust described, when exporting onnx model, delete the dynamic_axes, then no resize error occurs.
```
x = torch.randn(1, 1, 224, 224)
torch.onnx.export(torch_model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "super_resolution.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                'output' : {0 : 'batch_size'}})
```
