### ISSUE TITLE
These Op Not Support: Tensorflow::PlaceholderWithDefault

### ISSUE THREAD

**Issue by pangjieai** [alibaba/MNN#465]
/MNN/tools/converter/source/common/writeFb.cpp:                       72: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::PlaceholderWithDefault |

Is there any solution for this issue?  Thanks

**Comment by Naville** [comment]
Duplicate #74

**Comment by wanglirui** [comment]
is there any solution for this issue?
