### ISSUE TITLE
MNN 关于数据输入的例子

### ISSUE THREAD

**Issue by cefengxu** [alibaba/MNN#467]
谢谢大神的解答, 对mnn的数据格式排布和规律，存在疑问？
根据 https://www.yuque.com/mnn/cn/input 提到的：

```
auto inputTensor = interpreter->getSessionInput(session, NULL);
auto nchwTensor = new Tensor(inputTensor, Tensor::CAFFE);
// nchwTensor-host<float>()[x] = ...
inputTensor->copyFromHostTensor(nchwTensor);
delete nchwTensor;
```

**问题1：**
其中，**nchwTensor->host<float>()[x] = ...** 指的是什么？
是把数据通过循环遍历的方式( 比如for循环 )赋值进去吗？
比如，一个已经预处理好的cv::Mat, 如何 快捷便利的赋值到  nchwTensor 中？
已通过如下方式传入，是否可行？
`auto nchwTensor = Tensor::create(inputDims,halide_type_of<float>(),img_cv2.data,Tensor::TENSORFLOW);`

**问题2：**
模型获得输入后， 

- auto shape = input->shape();  **// shape = { 1,3,H,W }**
- auto format = TensorUtils::getDescribe(input)->dimensionFormat; **// format ： MNN_DATA_FORMAT_NC4HW4**

图像数据在OpenCV下的格式为：
- CV_32FC3;
- RGB
- 3通道
- 像素排列： RGBRGBRGBRGB.......

将图像数据值传入MNN的Tensor中，采用如下代码：
```
 std::vector<int> inputDims={1,H,W,3};
 auto nchwTensor = Tensor::create(inputDims,halide_type_of<float>(),img_cv2.data,Tensor::TENSORFLOW);
 input->copyFromHostTensor(nchwTensor);
 delete nchwTensor;
```
上述过程是否正确？合理？
另外，input 的shape 得到的是3通道。但是，拷贝数据后，input 却变成了4通道。为什么？

**Comment by czy2014hust** [comment]
1. nchwTensor->host()就是tensor data的内存地址，上面可以改为auto ptr = nchwTensor->host()；ptr[x]=...（赋值）
2. input应该是NC4HW4的格式，所以看着是4通道，实际有效还是3通道，最后一个通道补0，这是MNN内存做的调整

**Comment by cefengxu** [comment]
谢谢，次规律已明确~！已核实，opencv读取的图片的像素分布，和tensorflow中tensor的像素分布是一致的。RGBRGBRGBRGB...
