### ISSUE TITLE
How to setup python install manually?

### ISSUE THREAD

**Issue by prnvjb** [alibaba/MNN#468]
Hey!
How to setup python install manually on custom hardware like jetson nano. I built the c++ version but installing for python from pymnn/pip_package/setup.py results in "MNN_generated.h" not found error? How to link those libraries? Or how are you building for x86 hardware instead direct release of pip package from pypi.
Any guidance is much appreciated.
Thanks!!

**Comment by stanleywang8888** [comment]
1. First, it's not suggested to build on custom hardware, as most custom hardware can't support python runtime well. 
2. If custom hardware do have some kind of python support, you can try the following basic guide.
   run 
   $ ./generate.sh
   in schema path
   in pymnn/pip_package path, 
   $ python build_deps.py
   $ python build_wheel.py
   and maybe you need to run the below command, when bdist_wheel is not supported 
   $ python -m pip install -U setuptools wheel
