### ISSUE TITLE
量化后的模型之后 BLOB 的数据类型为什么还是 DT_FLOAT 呢？

### ISSUE THREAD

**Issue by pengcuo** [alibaba/MNN#469]
2   extraTensorDescribe: [
     3     {
     4       blob: {
     5         dataFormat: NC4HW4,
     6         dataType: DT_FLOAT
     7       },
     8       index: 0
     9     },
    10     {
    11       blob: {
    12         dataFormat: NC4HW4,
    13         dataType: DT_FLOAT
    14       },
    15       index: 1
    16     },
    17     {
    18       blob: {
    19         dataFormat: NC4HW4,
    20         dataType: DT_FLOAT
    21       },
    22       index: 2
    23     },

不应该是 DT_INT8 么？

**Comment by jxt1234** [comment]
extraTensorDescribe 属性目前已经废弃

**Comment by pengcuo** [comment]
非常感谢这么快的回复。难怪把我看的一愣一愣。
感谢阿里的同学！！！

**Comment by pengcuo** [comment]
20   oplists: [
    19     {
    18       main_type: Input,
    17       main: {
    16         dims: [
    15           1,
    14           3,
    13           256,
    12           256
    11         ],
    10         dtype: DT_FLOAT,
     9         dformat: NC4HW4
     8       },
     7       name: Placeholder,
     6       outputIndexes: [
     5         33
     4       ],
     3       type: Input,
     2       defaultDimentionFormat: NHWC
     1     },
214        {
     1       inputIndexes: [
     2         33
     3       ],
     4       main_type: QuantizedFloatParam,
     5       main: {
     6         tensorScale: [
     7           127.030983,
     8           127.030983,
     9           127.030983
    10         ]
    11       },
    12       name: Placeholder___FloatToInt8___,
    13       outputIndexes: [
    14         0
    15       ],
    16       type: FloatToInt8,
    17       defaultDimentionFormat: NHWC
    18     },

     4   preferForwardType: CPU,
     3   sourceType: TENSORFLOW,
     2   tensorName: [
     1     Placeholder___FloatToInt8___,
639983     "generator/Conv/Relu6",
     1     generator/Conv_1/Relu6,

请问现在是通过     12       name: Placeholder___FloatToInt8___,  这个属性来判断 OP 的输输出吗？

**Comment by pengcuo** [comment]
如果 extraTensorDescribe 废弃了， oplists 里面的 inputIndexes 和 outputIndexes 可是还在使用啊。

**Comment by pengcuo** [comment]
27         ],
    26         dtype: DT_FLOAT,
    25         dformat: NC4HW4
    24       },
    23       name: Placeholder,
    22       outputIndexes: [
    21         33
    20       ],
    19       type: Input,
    18       defaultDimentionFormat: NHWC
还有 dformat 和 defaultDimentionFormat 这个两个的区别是什么？

**Comment by jxt1234** [comment]
通过 op 的 inputIndexes 和 outputIndexes 来判断输入输出

dformat 表示数据排列类型

defaultDimentionFormat 是为了兼容旧模型所加的一个参数，表示无法确认输出的数据排列类型时，Op输出的数据排列类型
