### ISSUE TITLE
Can't find the new op.

### ISSUE THREAD

**Issue by smallt-TAO** [alibaba/MNN#47]
I am following https://github.com/alibaba/MNN/blob/master/doc/AddOp_EN.md this doc to add a tensorflow Op named LinSpace. Compile successfully and passed unit test. But there still a error of MNN NOT_SUPPORTED_OP: ======>[ LinSpace,  ]<======. 
What should I do to solve the problem? Thanks.

**Comment by czy2014hust** [comment]
![image](https://user-images.githubusercontent.com/18324393/57511055-e5127400-733a-11e9-906f-90af175387e9.png)

**Comment by smallt-TAO** [comment]
It's worked, thanks~
