### ISSUE TITLE
how to build latest python API from latest code from github?

### ISSUE THREAD

**Issue by liwei46** [alibaba/MNN#472]
As in the title, 

I wish to use python API to do testing first. But it seems the MNN python API in pypi is not latest one.  I try to set up myself by running  "python setup.py install" in folder "MNN/pymnn/pip_package"
 But It have the following error:
/home/xxx/projects/MNN/pymnn/src/MNNTools.cc:7:10: fatal error: MNN_generated.h: No such file or directory

Thanks.

**Comment by czy2014hust** [comment]
cd schema && ./generate.sh

**Comment by liwei46** [comment]
@czy2014hust 
Thanks for the reply. It still not working.
But when I copy all head files from "MNN/schema/current" to "/home/wei_li/projects/MNN/tools/converter/source/include/" and change line 61, 63 in MNNTools.cc, it seems works.

**Comment by stanleywang8888** [comment]
Basically, 
in $pymnn/pippackage
    $python build_deps.py
    $python build_wheel.py
will generate a local wheel.  (Currently, the github cmake tree is not perfectly right, stay tuned to next release please)
