### ISSUE TITLE
mnn python如何得到正确的output tensor？

### ISSUE THREAD

**Issue by evi-Genius** [alibaba/MNN#473]
onnx模型输入shape 1×3×256×256，输出shape 1×1×256×256
转成mnn后：
`output_tensor = interpreter.getSessionOutput(session)`
得到的output_tensor是1×4×256×256（实际是一维）
使用MNNV2Basic.out 打印内部tensor，最后几行是：
`===> compute shape: deconv_upsample_3_filter_1fwd, [45]
Inputs:
1, 1, 255, 255, 
8, 
Outputs:
1, 1, 256, 256, 
===========> Resize Again...

===> compute shape: pool_downsample_1fwd, [47]
Inputs:
1, 
Outputs:
1, 3, 128, 128, 

===> compute shape: conv_downsample_1fwd, [12]
Inputs:
1, 
Outputs:
1, 13, 128, 128, 
Resize error for conv_downsample_1fwd, code=3
test_main, 192, cost time: 5.401000 ms
===========> Session Resize Done.
===========> Session Start running...
Input: 1, 256, 256, 3
Can't run session because not resizedRun 1 time:
Can't run session because not resizedAvg= 0.005000 ms, min= 0.005000 ms, max= 0.005000 ms
`
 Resize Again是什么意思？是不是转换出错了？

**Comment by stanleywang8888** [comment]
为了性能考量, MNN的部分内部Tensor格式是NC4HW4格式, 所以在通道上做了向上的4对齐, 碰到这种情况,可以创建一个临时的Tensor(不做4对齐）,然后调用Tensor的拷贝函数, copyToHostTensor
