### ISSUE TITLE
windows转换模型错误

### ISSUE THREAD

**Issue by yizhaoyanbo** [alibaba/MNN#474]
windows10, vs2019, protobuf3.11.0, mingw_win64 8.1.0
之前用0.2.1.0，nmake编译没问题，使用也没问题。

最近更新到0.2.1.5，按照文档中的ninja编译，报错如下：
![image](https://user-images.githubusercontent.com/26928415/69520942-d9b22d80-0f98-11ea-82f7-09e3d64a5a92.png)

然后我试着用nmake编译，编译指令如下：
```
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_SHARED_LIBS=OFF
 -DMNN_BUILD_CONVERTER=ON ..
nmake
```

编译全程没有报任何错误，顺利编译通过。
![image](https://user-images.githubusercontent.com/26928415/69521123-39103d80-0f99-11ea-9037-d5cdbb6840b3.png)

然鹅，当我运行MNNConvert.exe，程序直接crash，如下：
![image](https://user-images.githubusercontent.com/26928415/69521242-7b397f00-0f99-11ea-84db-95ba07c542ff.png)
----------------------
我编译debug版报错如下：
```
cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DMNN_BUILD_SHARED_LIBS=OFF
 -DMNN_BUILD_CONVERTER=ON ..
nmake
```
![image](https://user-images.githubusercontent.com/26928415/69539549-b2bb2200-0fbf-11ea-9808-5a729819ce38.png)

----------------------
我运行其他测试工具测试0.2.1.0下正常运行的模型，报错如下：
![image](https://user-images.githubusercontent.com/26928415/69521592-585b9a80-0f9a-11ea-86b3-0a68566f671d.png)
我测试了几个模型，都会报resize error。

另外，windows下的mnn自从0.2.1.0后就一直没有编成功过。

**Comment by yizhaoyanbo** [comment]
@li-qing @jxt1234 
大佬们能来解惑一下吗

**Comment by yizhaoyanbo** [comment]
我用cmake生成vs2019工程，必须把下面代码中的gMutex相关的两行代码注释掉才可以运行起来MNNConvert.exe。
![image](https://user-images.githubusercontent.com/26928415/69711307-ce4b3780-113b-11ea-8347-f6a2d6b0f34e.png)

但是在转换模型的时候会有提示如下错误：
![image](https://user-images.githubusercontent.com/26928415/69711406-fa66b880-113b-11ea-8a16-ce3a3bd4eac6.png)

调试后发现optimizeNet()时，调用sizeComputer的时候会search不到const这个op （optype = 11）, 同时inputs size是0，会输出后面MNN_PRINT的log
![image](https://user-images.githubusercontent.com/26928415/69711662-6517f400-113c-11ea-8d6f-ba15edb8a3d0.png)

这个模型在mac和linux上是可以成功转换的。
求大佬们解答。

**Comment by cvipdream** [comment]
win7 + vs2015 + mnn_2.0.1.5同样，生成MNNConvert.exe， 但是无法运行；跟踪发现：

![image](https://user-images.githubusercontent.com/30815640/71515492-74769280-28de-11ea-896f-7b1732245f24.png)

断点过去，就引发异常：

![image](https://user-images.githubusercontent.com/30815640/71515526-9ff97d00-28de-11ea-8273-32bbc7f55f55.png)

**Comment by cvipdream** [comment]
@yizhaoyanbo 兄弟，你的问题解决了吗

**Comment by yizhaoyanbo** [comment]
> @yizhaoyanbo 兄弟，你的问题解决了吗

解决了，把下面crash的那条语句注释掉，代码中没有用到。
```
std::unique_lock<std::mutex> _l(gMutex)
```
