### ISSUE TITLE
Quantization tool MNN::Tensor copy problem

### ISSUE THREAD

**Issue by hiigao** [alibaba/MNN#476]
Hi，我在centos7 x86 环境下跑了int8量化工具，MNN版本是0.2.1.5。生成的量化模型的shape发生了变化：
原始模型卷积层Tensor的shape（第一层举例）应该是NCHW：64\*0\*1\*1
![image](https://user-images.githubusercontent.com/26385522/69619985-8b279080-1077-11ea-8573-fd990d287495.png)
但是卷积层被替换为int8卷积层之后，shape变成了：64\*16\*1\*1
![image](https://user-images.githubusercontent.com/26385522/69619882-50bdf380-1077-11ea-8c49-0b9e5ce69f50.png)

原因分析：
我在Calibration.cpp中做了shape的输出调试发现在Calibration::_initMaps()方法中，Calibration::_opInfo的赋值可能出了问题，导致在量化模型初始化时代码：
`param->common->inputCount = tensorsPair->second.first[0]->channel();`
初始化变成了错误的设定，channel都被设置成了相同的数值。

导致这个问题产生的原因似乎是，_opInfo里pair的first和second在赋值的时候，直接使用了指针的vector赋值：
定义方法MNN::TensorCallBackWithInfo before = [&](const std::vector<MNN::Tensor*>& nTensors, const MNN::OperatorInfo* info) 时

        _opInfo[info->name()].first = nTensors; //该处做了shallow copy？

        if (Helper::gNeedFeatureOp.find(info->type()) != Helper::gNeedFeatureOp.end()) {
            for (auto t : nTensors) {
                if (_featureInfo.find(t) == _featureInfo.end()) {
                    _featureInfo[t] = std::shared_ptr<TensorStatistic>(
                        new TensorStatistic(t, _featureQuantizeMethod, info->name() + "__input"));
                }
            }
        }

不知道是不是因为没有deep copy导致了first/second vector的item指向了共同的内存地址，所以之前的内容被覆盖了。

**Comment by jxt1234** [comment]
这个看上去只是原先没有计算出 weight 的输入通道数，转换后计算出来了，不像是问题。你模型运行结果有问题么？

**Comment by hiigao** [comment]
我的模型是mnn的模型，结果验证过，是没问题的。这个是量化工具里面的模型转换过程出错，我在before和after里面打印了weight的通道数都是正常的，每一层数值都不一样。但是runsession结束之后再打印通道数值就变成一样的了


发自坚果 Pro 2

jxt1234 <notifications@github.com> 于 2019年11月26日 下午11:59写道：


这个看上去只是原先没有计算出 weight 的输入通道数，转换后计算出来了，不像是问题。你模型运行结果有问题么？

―

**Comment by czy2014hust** [comment]
从你给出的可视化图中看不出问题，**?**应该是没有赋值，没有显示而已。你可以用MNNDump2Json对比下weight的shape信息看是否有问题。
量化后模型运行有没有问题吗？有问题的话，贴下log，或者发下原始float模型我们验证下。

**Comment by hiigao** [comment]
> 从你给出的可视化图中看不出问题，**?**应该是没有赋值，没有显示而已。你可以用MNNDump2Json对比下weight的shape信息看是否有问题。

\"?\"的原因是初始设置为0，但是量化转换之后变成了16。而且是所有的卷积层的？部分都变成了16。按照我的理解应该是\"?\"部分不进行替换，我在源码里面也没有对这个项进行设置。

>量化后模型运行有没有问题吗？有问题的话，贴下log，或者发下原始float模型我们验证下。
量化后的模型运行时有问题的，结果不正确。
这个是我打印出来的几个卷积层的输出：
![image](https://user-images.githubusercontent.com/26385522/69691492-3d0f9d00-110a-11ea-8c7d-061259faa0f7.png)

**Comment by czy2014hust** [comment]
1. **?**只是可视化的问题，肯定不为0！你用MNNDump2Json看下量化前后模型的weight shape
2. 结果不对表现在什么问题上？分类不对？检测框错误？还是上面错误

**Comment by czy2014hust** [comment]
close -> reopen?
