### ISSUE TITLE
segmentation fault when convert model

### ISSUE THREAD

**Issue by sunbinbin1991** [alibaba/MNN#477]
I have model file download from from official readme
` model-mobilenet_v1_075.pb `
however when convert model, then have such problem
`mnnconvert -f TF --modelFile model-mobilenet_v1_075.pb -- MNNModel pose.mnn --bizCode biz
Segmentation fault (core dumped)`
so ， why this happen ？

**Comment by jxt1234** [comment]
You can use lldb or gdb to debug it. It may be the error from protobuffer

**Comment by sunbinbin1991** [comment]
thx, I will try it

**Comment by sunbinbin1991** [comment]
problem solved, I use mnnconvert tools install by pip
`pip install -U MNN`
This tools is not work, then I build it reference below  it works:
[https://www.yuque.com/mnn/en/cvrt_linux](url)
