### ISSUE TITLE
cmake .. -DMNN_BUILD_CONVERTER=true 报错

### ISSUE THREAD

**Issue by ZhangZoffy** [alibaba/MNN#489]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LIBRARY (ADVANCED)
    linked by target "MNNConvert" in directory /home/service/MNN/tools/converter
    linked by target "tensorflow" in directory /home/service/MNN/tools/converter/source/tensorflow
    linked by target "onnx" in directory /home/service/MNN/tools/converter/source/onnx
    linked by target "caffe" in directory /home/service/MNN/tools/converter/source/caffe

-- Configuring incomplete, errors occurred!
See also "/home/service/MNN/build/CMakeFiles/CMakeOutput.log".
See also "/home/service/MNN/build/CMakeFiles/CMakeError.log".

**Comment by sunbinbin1991** [comment]
maybe because PROTOBUF_LIBRARY ,you could try this
https://www.yuque.com/mnn/en/faq
