### ISSUE TITLE
Is there any easy way to  prebuild opencl kernel?

### ISSUE THREAD

**Issue by xiaxinkai** [alibaba/MNN#491]
Hi, Dear mnn team:
Please help me! Thanks in advance!
I'm trying to use mnn on an aarch64 embeded linux system with opencl.
But I found an important thing is that, with opencl mnn boot cost long time.
After lots of debugging, I fount that the program will buildkernel when program start every time.
opencl buildkernel on run time spent much time, so there is any easy way to prebuild the opencl kernel for my model?

**Comment by hacker-joe** [comment]
Kernel binary cache method is under development. it can solve the problem you described

**Comment by xiaxinkai** [comment]
@hacker-joe thanks for your answer. Hope it coming soon!

**Comment by dimitryn** [comment]
Hi @xiaxinkai , when do you expect cache implementation to be available? thanks

**Comment by xiaxinkai** [comment]
@dimitryn I want to use OPENCL to speed up the inference.
when ? Certainly as soon as possible. Currently I'm using MNN with CPU only in my product. If I can use OPENCL cache implementation, I can get better performance.
Thanks.
