### ISSUE TITLE
how to get tensor data easily when using gpu

### ISSUE THREAD

**Issue by kl456123** [alibaba/MNN#492]
due to that tensor is constant. so it is allocated on cpu . 
I used two method to get the value from tensor.

1. tensor->host<int32_t>()[0]
Couldn't find method MNN::Tensor::host<int32_t>
2. ((int32_t*)tensor->buffer().host)[0], success
So Why the first one is failed ?

**Comment by li-qing** [comment]
for GPU data access, refer to 'copy data' part of  https://www.yuque.com/mnn/en/output.

'tensor->host<int32_t>()[0]' works for me.
