### ISSUE TITLE
MNN在windows下编译模型转换工具失败

### ISSUE THREAD

**Issue by xjcvip007** [alibaba/MNN#493]
已经按照https://www.yuque.com/mnn/cn/cvrt_windows的步骤 ，安装好了protobuf。
但是在进行编译模型转换工具步骤时报错如下：
![Popo截图2019122162925](https://user-images.githubusercontent.com/16399125/69944167-9bc98200-1521-11ea-878c-a1aa2f355398.png)
步骤为：
```
cd tools/converter
mkdir build
cd build
cmake -G "Ninja" -DMNN_BUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release ..
```
想知道问题是什么，感谢~

**Comment by Naville** [comment]
需连MNN本体一起编译，文档缺陷。待编译系统大更新合流回master后修复文档

**Comment by wangzhaode** [comment]
已解决
