### ISSUE TITLE
Program stuck on output tensor copy back to host

### ISSUE THREAD

**Issue by kl456123** [alibaba/MNN#494]
platform: RK3399, (limited computation power and memory)
device: both CPU and GPU
after several dectections in video from camera(may be several minutes), the program stuck.

**Comment by li-qing** [comment]
how long does it take for every single detection? how about your frame rate?

if it takes too long to detect sth, and camera callback has higher priority, block or crash is normal.

**Comment by kl456123** [comment]
about 10fps

**Comment by li-qing** [comment]
> about 10fps

so how long does it take for every single detection? if it takes longer than 100ms, the program will block or crash as expected.

**Comment by kl456123** [comment]
> > about 10fps
> 
> so how long does it take for every single detection? if it takes longer than 100ms, the program will block or crash as expected.

No, ~10 fps for detection , 25fps for video frame rate

**Comment by kl456123** [comment]
BTW benchmark tools needs to support multiple inputs and outputs to get the truly result for some model

**Comment by li-qing** [comment]
I don't get it. 10 fps means 100ms for every detection. 25fps video frame rate means 40ms available time break.

you may have a try that not to start another detection until the previous one finish.

**Comment by kl456123** [comment]
But how to wait for the previous on
