### ISSUE TITLE
怎么在MNNV2Basic.cpp里指定一张图片作为模型输入？

### ISSUE THREAD

**Issue by le8888e** [alibaba/MNN#497]
是在input_0.txt里添加图片路径吗？文档有点看不懂，谢谢！

**Comment by czy2014hust** [comment]
参考 [test4Tf.py](https://github.com/alibaba/MNN/blob/master/tools/converter/tools/test4TF.py)

**Comment by le8888e** [comment]
@czy2014hust 所以input_0.txt的每一行只有一个输入图片的像素值对吗？我是想在CPU上输入一张图片，验证INT8量化前后的输出差别，现在量化后的模型输出有结果，量化前的模型输出都是nan和-nan。感觉可能是输入图片有问题，请问有什么建议吗？谢谢

**Comment by czy2014hust** [comment]
那你参考[demo](https://github.com/alibaba/MNN/blob/master/demo/exec/multiPose.cpp)输入图片即可，首先把float的模型调试正确，再测试量化的模型，量化后的模型对比输出数值没有什么意义，直接看你模型demo效果即可。
