### ISSUE TITLE
使用backendTest.out工具测试模型时 Vulkan 后端 Permute 运算的结果错误

### ISSUE THREAD

**Issue by Hconk** [alibaba/MNN#498]
模型文件：
[model.zip](https://github.com/alibaba/MNN/files/3921676/model.zip)
该模型在使用 backendTest.out 程序测试时 Vulkan 后端输出结果错误，测试 OpenCL 后端结果正常。

![image](https://user-images.githubusercontent.com/8470001/70141082-31efda80-16d1-11ea-82bf-234a28540982.png)

调试结果发现是 Vulkan 后端在 Permute 操作时候出错。 由于对 GLSL 不熟悉，对 Permute 的具体实现不太理解，希望能协助看下是什么问题。

具体问题数据如下
![image](https://user-images.githubusercontent.com/8470001/70141911-00780e80-16d3-11ea-9ea6-774d40061dc3.png)
![image](https://user-images.githubusercontent.com/8470001/70141915-02da6880-16d3-11ea-91f0-68f95277116a.png)
。
经过如下修改在第一次 Permute 的时候可以正常执行，结果正确，但是后面 Permute 运算时出错：
![image](https://user-images.githubusercontent.com/8470001/70142396-19cd8a80-16d4-11ea-9439-58fe9b57c00e.png)
![image](https://user-images.githubusercontent.com/8470001/70142436-31a50e80-16d4-11ea-93ae-d32ac695d008.png)

希望能帮忙看下问题，感谢。

**Comment by jxt1234** [comment]
fixed
