### ISSUE TITLE
这篇[文章](http://www.sohu.com/a/312035323_610300)中的Benchmark测试环境是什么样的呢？

### ISSUE THREAD

**Issue by nolanliou** [alibaba/MNN#5]
Hi,

赞大佬们的工作，这篇[文章](http://www.sohu.com/a/312035323_610300)中有些benchmark结果，非常赞。

不过MACE相关的Benchmark结果跟我们测的出入较大，咨询一下你们测的是MACE的哪个版本呢，还有是怎么测得呢？

Thanks

**Comment by li-qing** [comment]
hi there

图中数据由benchmark工程产生，具体到Mace，测试使用的commit为ed1f237a612f28d3ba564fbe28ed02ac3f5caacd。

测试不论CPU还是GPU，都是50次重复推理，取平均耗时。

**Comment by nolanliou** [comment]
还是无法复现你们的benchmark结果。我们测试的结果如下
```
ABI: arm64-v8a
NDK: r15c
commit: ed1f237a612f28d3ba564fbe28ed02ac3f5caacd
model: mobilenet-v2(224x224)
round: 50
device: mi-6(835)

CPU: 30ms
GPU: 11.2ms
```

**Comment by li-qing** [comment]
测试上统一使用了armv7，没有在arm64-v8a下执行。v7上你们的benchmark结果如何？

**Comment by li-qing** [comment]
另gpuPerfHint和gpuPriorityHint都设置为3
