### ISSUE TITLE
最新的代码 WIN平台上 只能用VS2019编？

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#500]
最新的代码 WIN平台上 只能用VS2019编？ 之前编0.2.0.9的时候还能用VS17，现在已经改掉了吗？

**Comment by li-qing** [comment]
应该没有改过 有什么问题？

**Comment by ChisenZhang** [comment]
> 应该没有改过 有什么问题？

[  3%] Building CXX object CMakeFiles/MNN.dir/source/core/Interpreter.cpp.obj
Interpreter.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xutility(2443): error C2280: “std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: 尝试引用已删除的函数
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\memory(2309): note: 参见“std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>::operator =”的声明
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xutility(2462): note: 参见对正在编译的函数 模板 实例化“_OutIt std::_Copy_unchecked1<_InIt,_OutIt>(_InIt,_InIt,_OutIt,std::_General_ptr_iterator_tag)”的引用
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1430): note: 参见对正在编译的函数 模板 实例化“_OutIt *std::_Copy_unchecked<_Iter,std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>*>(_InIt,_InIt,_OutIt)”的引用
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Ty=MNN::Pipeline,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1448): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1448): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1471): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1471): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Ty=MNN::Pipeline,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1457): note: 编译 类 模板 成员函数 "std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)" 时
        with
        [
            _Ty=MNN::Pipeline
        ]
d:\ccode\readmnn\readmnn\source\core\Session.hpp(145): note: 参见对正在编译的函数 模板 实例化“std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)”的引用
        with
        [
            _Ty=MNN::Pipeline
        ]
d:\ccode\readmnn\readmnn\source\core\Session.hpp(138): note: 参见对正在编译的 类 模板 实例化 "std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>" 的 引用
        with
        [
            _Ty=MNN::Pipeline
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\memory(2309): note: “std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: 已显式删除函数
        with
        [
            _Ty=MNN::Pipeline
        ]
NMAKE : fatal error U1077: “C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
编译会报错，按VS2019编好像也报这种错误，我忘了记下来了。应该不是系统没有改unicode编码的问题吧，我之前没有改系统编码也编过了

**Comment by ChisenZhang** [comment]
> > 应该没有改过 有什么问题？
> 
> [ 3%] Building CXX object CMakeFiles/MNN.dir/source/core/Interpreter.cpp.obj
> Interpreter.cpp
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xutility(2443): error C2280: “std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: 尝试引用已删除的函数
> with
> [
> _Ty=MNN::Pipeline
> ]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\memory(2309): note: 参见“std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>::operator =”的声明
> with
> [
> _Ty=MNN::Pipeline
> ]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\xutility(2462): note: 参见对正在编译的函数 模板 实例化“_OutIt std::_Copy_unchecked1<_InIt,_OutIt>(_InIt,_InIt,_OutIt,std::_General_ptr_iterator_tag)”的引用
> with
> [
> _OutIt=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> *,
> _InIt=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> *
> ]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1430): note: 参见对正在编译的函数 模板 实例化“_OutIt _std::_Copy_unchecked<_Iter,std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>_>(_InIt,_InIt,_OutIt)”的引用
> with
> [
> _OutIt=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> _, _Iter=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> _, _Ty=MNN::Pipeline, _InIt=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> * ] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1448): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)”的引用 with [ _Ty=MNN::Pipeline, _Iter=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> * ] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1448): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::_Assign_range<_Iter>(_Iter,_Iter,std::forward_iterator_tag)”的引用 with [ _Ty=MNN::Pipeline, _Iter=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> * ] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1471): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>_,void>(_Iter,_Iter)”的引用 with [ _Ty=MNN::Pipeline, _Iter=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> * ] C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1471): note: 参见对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::assign<std::unique_ptr<_Ty,std::default_delete<_Ty>>_,void>(_Iter,_Iter)”的引用
> with
> [
> _Ty=MNN::Pipeline,
> _Iter=std::unique_ptr<MNN::Pipeline,std::default_deleteMNN::Pipeline> *
> ]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\vector(1457): note: 编译 类 模板 成员函数 "std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)" 时
> with
> [
> _Ty=MNN::Pipeline
> ]
> d:\ccode\readmnn\readmnn\source\core\Session.hpp(145): note: 参见对正在编译的函数 模板 实例化“std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>::operator =(const std::vector<std::unique_ptr<_Ty,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>> &)”的引用
> with
> [
> _Ty=MNN::Pipeline
> ]
> d:\ccode\readmnn\readmnn\source\core\Session.hpp(138): note: 参见对正在编译的 类 模板 实例化 "std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>>,std::allocator<std::unique_ptr<_Ty,std::default_delete<_Ty>>>>" 的 引用
> with
> [
> _Ty=MNN::Pipeline
> ]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include\memory(2309): note: “std::unique_ptr<MNN::Pipeline,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)”: 已显式删除函数
> with
> [
> _Ty=MNN::Pipeline
> ]
> NMAKE : fatal error U1077: “C:\PROGRA~2\MIB055~1\2017\COMMUN~1\VC\Tools\MSVC\1414~1.264\bin\Hostx64\x64\cl.exe”: 返回代码“0x2”
> Stop.
> NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
> Stop.
> NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
> Stop.
> 编译会报错，按VS2019编好像也报这种错误，我忘了记下来了。应该不是系统没有改unicode编码的问题吧，我之前没有改系统编码也编过了



> 应该没有改过 有什么问题？

按文档里面的VS2019编 报错如下，应该是同一个原因
[6/251] Building CXX object CMakeFiles\MNN.dir\source\core\Interpreter.cpp.obj
FAILED: CMakeFiles/MNN.dir/source/core/Interpreter.cpp.obj
D:\VS2019\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\cl.exe  /nologo /TP -DBUILDING_MNN_DLL -DMNN_EXPORTS -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -D_CRT_SECURE_NO_WARNINGS -I..\include -I..\schema\current -I..\3rd_party\flatbuffers\include -I..\3rd_party\half -I..\source -I..\source\core -I..\source\backend\cpu -I..\source\backend\cpu\arm -I..\source\backend\cpu\compute -I..\source\cv -I..\source\math -I..\source\shape -I..\source\backend\cpu\x86_x64 -I..\source\backend\cpu\x86_x64\sse -I..\source\backend\cpu\x86_x64\avx -I..\. /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O2 /MD /O2 /Ob2 /DNDEBUG   /wd4244 /wd4146 /wd4018 /wd4267 /wd4996 /wd4081 /wd4251 -std:c++14 /showIncludes /FoCMakeFiles\MNN.dir\source\core\Interpreter.cpp.obj /FdCMakeFiles\MNN.dir\ /FS -c ..\source\core\Interpreter.cpp
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\xutility(3330): error C2280: “std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =(const std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &)”: 尝试引用已删除的函数
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\memory(1913): note: 参见“std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =”的声明
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\memory(1913): note: “std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =(const std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &)”: 已隐式删除函数
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1128): note: 查看对正在编译的函数 模板 实例化“_OutIt *std::_Copy_unchecked<_Iter,std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*>(_InIt,_InIt,_OutIt)”的引用
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1143): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Assign_range<_Ty*>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1143): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Assign_range<_Ty*>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1154): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::assign<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1154): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::assign<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1151): note: 在编译 类 模板 成员函数“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Copy_assign(const std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>> &,std::false_type)”时
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1170): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Copy_assign(const std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>> &,std::false_type)”的引用
D:\CCode\readMNN\readMNN\source\core\Session.hpp(138): note: 查看对正在编译的 类 模板 实例化“std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>”的引用
[7/251] Building CXX object CMakeFiles\MNN.dir\source\core\Session.cpp.obj
FAILED: CMakeFiles/MNN.dir/source/core/Session.cpp.obj
D:\VS2019\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\cl.exe  /nologo /TP -DBUILDING_MNN_DLL -DMNN_EXPORTS -DMNN_SUPPORT_TFLITE_QUAN -DMNN_USE_SSE -DMNN_USE_THREAD_POOL -D_CRT_SECURE_NO_WARNINGS -I..\include -I..\schema\current -I..\3rd_party\flatbuffers\include -I..\3rd_party\half -I..\source -I..\source\core -I..\source\backend\cpu -I..\source\backend\cpu\arm -I..\source\backend\cpu\compute -I..\source\cv -I..\source\math -I..\source\shape -I..\source\backend\cpu\x86_x64 -I..\source\backend\cpu\x86_x64\sse -I..\source\backend\cpu\x86_x64\avx -I..\. /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O2 /MD /O2 /Ob2 /DNDEBUG   /wd4244 /wd4146 /wd4018 /wd4267 /wd4996 /wd4081 /wd4251 -std:c++14 /showIncludes /FoCMakeFiles\MNN.dir\source\core\Session.cpp.obj /FdCMakeFiles\MNN.dir\ /FS -c ..\source\core\Session.cpp
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\xutility(3330): error C2280: “std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =(const std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &)”: 尝试引用已删除的函数
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\memory(1913): note: 参见“std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =”的声明
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\memory(1913): note: “std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>::operator =(const std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> &)”: 已隐式删除函数
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1128): note: 查看对正在编译的函数 模板 实例化“_OutIt *std::_Copy_unchecked<_Iter,std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*>(_InIt,_InIt,_OutIt)”的引用
        with
        [
            _OutIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *,
            _InIt=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1143): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Assign_range<_Ty*>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1143): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Assign_range<_Ty*>(_Iter,_Iter,std::forward_iterator_tag)”的引用
        with
        [
            _Ty=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1154): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::assign<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1154): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::assign<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>*,void>(_Iter,_Iter)”的引用
        with
        [
            _Iter=std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>> *
        ]
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1151): note: 在编译 类 模板 成员函数“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Copy_assign(const std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>> &,std::false_type)”时
D:\VS2019\VC\Tools\MSVC\14.24.28314\include\vector(1170): note: 查看对正在编译的函数 模板 实例化“void std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>::_Copy_assign(const std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>> &,std::false_type)”的引用
D:\CCode\readMNN\readMNN\source\core\Session.hpp(138): note: 查看对正在编译的 类 模板 实例化“std::vector<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>,std::allocator<std::unique_ptr<MNN::Pipeline,std::default_delete<MNN::Pipeline>>>>”的引用
[11/251] Building CXX object CMakeFiles\MNN.dir\source\core\Schedule.cpp.obj
D:\CCode\readMNN\readMNN\source\core\DirectedAcyclicGraph.hpp(1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
ninja: build stopped: subcommand failed.

**Comment by Hconk** [comment]
因为 Session 有一个私有变量 std::vector<std::unique_ptr<Pipeline>> mPipelines;，std::unique_ptr的拷贝构造函数被删除了，所以 Session 在编译时候生成的默认构造函数会报错。
你可以这样改一下： https://github.com/Hconk/MNN/commit/819a666135a420f680675d503fabfa14028e13d2 ，或者让Session继承一下NonCopyable。

**Comment by ChisenZhang** [comment]
> 因为 Session 有一个私有变量 std::vector<std::unique_ptr> mPipelines;，std::unique_ptr的拷贝构造函数被删除了，所以 Session 在编译时候生成的默认构造函数会报错。
> 你可以这样改一下： [Hconk@819a666](https://github.com/Hconk/MNN/commit/819a666135a420f680675d503fabfa14028e13d2) ，或者让Session继承一下NonCopyable。

好的 我看一下， Linux上怎么不报错？
