### ISSUE TITLE
关于新旧版本代码推理时间的疑问

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#501]
先说一下流程：一个检测模型，主干类似MobileNet，架构类似SSD。
将一些后处理和前处理封到了另一个库callMNN里面，用的时候用代码调callMNN的接口，callMNN调MNN库。就是这么一个流程。
之前用的MNN库版本是0.2.0.9，现在测试的是0.2.1.5
同一个模型
在LINUX上，用MNN里面的工具 timeprofile MNNV2Basic分别测试时间为15ms左右和20ms左右，用0.2.1.5编译出来的工具测试则分别为10ms，15ms左右，主要差别显示在ConvolutionDepthwise 这个OP上   我以为优化提速了

但是

在WIN平台上对比两个版本的库推理时间基本上没有差别
在XCode模拟器里面旧版本的库的推理时间大概是60-70ms之间，新版本则在80-100ms之间

这个结果是那两个评测工具代码在不同版本上有了较大修改，还是MNN库的推理速度确实有提升或者下降

希望大佬给解答一下   多谢

**Comment by ChisenZhang** [comment]
拿IOS设备测了一下， Iphone7P 基本上没啥差别

**Comment by kl456123** [comment]
那个benchmark测试工具不准，以自己实际跑完整个网络为准。。
