### ISSUE TITLE
量化后不准，预处理问题

### ISSUE THREAD

**Issue by noah-lcf** [alibaba/MNN#504]
你好，首先谢谢优秀的开源工具。
量化后发现识别模型根本没法用
原来识别模型中对图片有下面的预处理操作
def prewhiten(x):
    mean = np.mean(x)
    std = np.std(x)
    std_adj = np.maximum(std, 1.0/np.sqrt(x.size))
    y = np.multiply(np.subtract(x, mean), 1/std_adj)
    return y
请问这个怎么设置  我看pretreatConfig.json里面mean和normal这两项上固定的值
需要图片在预处理后保存吗

**Comment by czy2014hust** [comment]
训练完的模型mean normal一般是固定的，不知道为什么要动态计算？

**Comment by noah-lcf** [comment]
多谢回复。
通常是固定的。
如果暂时模型不重训，我自己预先把图片预处理后保存，mean和normal 分别设置为0和1 ，不知道是不是也可以。

**Comment by noah-lcf** [comment]
自己想了下不行 精度丢掉了

**Comment by czy2014hust** [comment]
你的这个情况是什么意思？是你不知道mean和norm？还是不需要预处理？还是预处理在模型中？还是就是必须动态计算？请明确下问题。

**Comment by noah-lcf** [comment]
现在的预处理 是根据当前图片动态计算的mean和norm

**Comment by noah-lcf** [comment]
> 现在的预处理 是根据当前图片动态计算的mean和norm

自己改了下源码 解决了

**Comment by LUOQING1994** [comment]
> > 现在的预处理 是根据当前图片动态计算的mean和norm
> 
> 自己改了下源码 解决了
你好！我使用mobilefacenet.onnx转成mnn 用于人脸的比对时，发现同一张图片的embedding结果不同 尤其是前面几次，差距较大，但后面就趋于稳定了 ，在embedding之前 我使用了和你同样的预处理，所以想请问一些 你是怎么修改源码的呢？十分感谢！
