### ISSUE TITLE
tensorflow RNN模型转MNN时出现问题 

### ISSUE THREAD

**Issue by a1123622944** [alibaba/MNN#508]
你好 ,我现在打算转tensorflow的rnn模型成mnn 但我发现转换时候出现以下问题
![~YGGA)M%1R($YL~OK9E8$EA](https://user-images.githubusercontent.com/26085453/70415751-57496380-1a98-11ea-8a41-28affaad7696.png)
这应该怎么处理呢

**Comment by jxt1234** [comment]
转 rnn 模型建议把 seq_length 固定为常量

**Comment by a1123622944** [comment]
> 转 rnn 模型建议把 seq_length 固定为常量

![image](https://user-images.githubusercontent.com/26085453/70417219-bceb1f00-1a9b-11ea-86fe-e90aeee02b8d.png)
是常量的 但还是有这个问题

**Comment by jxt1234** [comment]
呃，你是不说把训练的节点导出来了，看节点中有 Adam 之类

**Comment by a1123622944** [comment]
> 呃，你是不说把训练的节点导出来了，看节点中有 Adam 之类

之前我保存rnn模型可能有点问题 ,现在用的是freeze模型 输出的节点是softmax层
![image](https://user-images.githubusercontent.com/26085453/70501760-eff3e800-1b59-11ea-9b6e-e8a1d389974a.png)
![image](https://user-images.githubusercontent.com/26085453/70501768-fb471380-1b59-11ea-8dec-c56e7dbb4230.png)
但错误是很奇怪 没看明白这的意思
![image](https://user-images.githubusercontent.com/26085453/70501845-2e89a280-1b5a-11ea-8b12-56f2aa5f99f7.png)

**Comment by jxt1234** [comment]
现在 tensorArray 系列已经支持 (1.1.6)

**Comment by liziru** [comment]
你好，我测试了两个RNN模型，都转换失败。失败结果如下： 
![image](https://user-images.githubusercontent.com/34911790/147097482-5058882b-ac1c-41d7-b072-5fe3b4855b0b.png)
有什么好的建议吗， 尝试转换这两个模型的tflite模型也失败，添加--debug模式也没得到更多的打印信息。 @jxt1234
