### ISSUE TITLE
量化模型识别完全错误，mnn版本0.2.1.5

### ISSUE THREAD

**Issue by firstadam** [alibaba/MNN#509]
配置文件的均值mean，normal和推理都是一样的，我用的标定的图片是训练时的图片，在每一个类别中抽取了20张。没量化之前的模型能正常使用，量化之后的模型完全识别不了。
{
    "format":"RGB",
    "mean":[
        0,
        0,
        0
    ],
    "normal":[
        0.00392157,
        0.00392157,
        0.00392157
    ],
    "width":128,
    "height":128,
    "path":"/home/adamguo/visbot/pizza_co/data/quant"
}

**Comment by czy2014hust** [comment]
1. 确认下format是 BGR还是RGB
2. 你的预处理是resize还是crop，[修改这个地方](https://github.com/alibaba/MNN/blob/62c5ca47964407508a5fa802582e648fc75eb0d9/tools/quantization/Helper.cpp#L110)
3. KL,ADMM可以多测试下
4. 增加或者减少校准样本试下

**Comment by firstadam** [comment]
怎么修改

**Comment by firstadam** [comment]
@czy2014hust 怎么修改

**Comment by xieydd** [comment]
@czy2014hust Why when i use ADMM function, will throw a error `Resize error for input_layer, code=3`, but when i use kl, i will works.

**Comment by zhangpu1987** [comment]
pytorch模型量化全是错的，改了吗

**Comment by 850977164** [comment]
![image](https://user-images.githubusercontent.com/39330916/72505330-aeeaa400-387a-11ea-9405-d2149ead3e98.png)
Hello, I have encountered this problem in MNN0.2.1 implementation,what should i do ?

**Comment by zhangpu1987** [comment]
https://zhuanlan.zhihu.com/p/102357266
