### ISSUE TITLE
model in gpu

### ISSUE THREAD

**Issue by zefan7564** [alibaba/MNN#51]
how can i know my model whether run in gpu or not.i compiled opencl mnn and passed,but test time as long as cpu MNN

**Comment by zefan7564** [comment]
i compiled MNN in linux

**Comment by jxt1234** [comment]
There are three ways to know.
1. Check the log "Can't Find type=3 backend, use 0 instead"
2.top and see the usage of CPU
3. Use MNNV2Basic.out , if opencl , the op cost is very small. Like this:
                                       conv4_2/sep run 10 average cost 0.006100 ms, 0.021 %, FlopsRate: 4.517 %
                                             conv1 run 10 average cost 0.007200 ms, 0.024 %, FlopsRate: 1.906 %
                                             pool6 run 10 average cost 0.010200 ms, 0.034 %, FlopsRate: 0.000 %
Avg= 29.692301 ms, min= 25.267000 ms, max= 35.556999 ms
