### ISSUE TITLE
Is there any way of training RNN on this platform?

### ISSUE THREAD

**Issue by ArnoldLiuIC** [alibaba/MNN#510]
I managed to convert a static RNN (with timestep set constant) into MNN model, however could not train it due to the lack of some ops.

Is there anyway training RNN model online via MNN?

**Comment by ArnoldLiuIC** [comment]
activation ops are easy to implement its grad. but for concat, I am still struggling to go through the CPUConcat.cpp implementation. A brief description of what it is going on behind the scene would be great

**Comment by yinwangsong** [comment]
hello，I wound like to ask that have you implemented RNN Training via MNN on mobile CPU/GPUs？ Thank you~
