### ISSUE TITLE
windows 平台编译过程中出现报错

### ISSUE THREAD

**Issue by thirteener** [alibaba/MNN#513]
![windows error](https://user-images.githubusercontent.com/18388459/70518079-ab297a80-1b74-11ea-8ca5-3a6c56221ab5.PNG)
目前是按照云雀上文档进行设置的 Unicode也更改为英文了  希望各位大佬能够帮忙解答下

**Comment by SyGoing** [comment]
我也是这个问题

**Comment by ToBigboss** [comment]
> ![windows error](https://user-images.githubusercontent.com/18388459/70518079-ab297a80-1b74-11ea-8ca5-3a6c56221ab5.PNG)
> 目前是按照云雀上文档进行设置的 Unicode也更改为英文了 希望各位大佬能够帮忙解答下

拉最新代码编，我这边是OK的
