### ISSUE TITLE
单核推理速度比多核推理速度快

### ISSUE THREAD

**Issue by jianxiezhendong** [alibaba/MNN#515]
跑一个人脸检测程序，出现了单核比多核推理速度快的现象，这是什么原因？

**Comment by czy2014hust** [comment]
设备是什么？这要看设备cpu核心以及频率

**Comment by forfun1012** [comment]
可以先用timeProfile.out工具看一下每一个layer的计算时间，具体情况具体分析...
参考https://www.yuque.com/mnn/cn/tool_test
