### ISSUE TITLE
Support for opencl 1.1 in RK3288

### ISSUE THREAD

**Issue by forfun1012** [alibaba/MNN#516]
I'm trying to build blazeface on rk3288 platform with a mali-T764.
When I set the MNN net forwarding as NMM_FORWARD_OPENCL. I got an error:
"clCreateImage Not Found!
clRetainDevice Not Found!
clReleaseDevice Not Found!
parsing symbols error !!! 
Can't Find type=3 backend, use 0 instead"

It means my libGLES_mail.so supports OpenCL 1.1, but MNN needs  OpenCL 1.2. 
Is there any way to work around without updating the libGLES_mail.so? 
Thx!

**Comment by jxt1234** [comment]
Supported. Please update the code
