### ISSUE TITLE
tensorflow pb文件转mnn后推理速度问题

### ISSUE THREAD

**Issue by reason4** [alibaba/MNN#517]
pb文件转mnn后，推理结果正常，但是在cpu服务器上速度比tensorflow mkl版本慢3倍左右，和常规tensorflow相近，请问mnn在服务端cpu没有做太多优化吧？另外我测试torch转mnn后的模型速度还可以，请问mnn在服务端cpu的推理速度和数据排列方式有关吗（tf是nhwc，torch是nchw）？服务端cpu推理有什么加速方法吗？谢谢！

**Comment by czy2014hust** [comment]
mnn在x86有些优化，但是主要还是在arm端，服务端推荐用GPU

**Comment by reason4** [comment]
> mnn在x86有些优化，但是主要还是在arm端，服务端推荐用GPU

好的，谢谢！
