### ISSUE TITLE
.pb转换失败

### ISSUE THREAD

**Issue by xjqjlu** [alibaba/MNN#519]
tf的模型在使用文档给出的zoo中下载的tf官方模型，.pb格式转换失败，tflite模型可以转换成功
`../../MNN/build/MNNConvert -f TF --modelFile mobilenet_v1_1.0_224_quant_frozen.pb --MNNModel mobile.mnn --bizCode biz

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
For MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_Fold convolution weight is not const
Converte Tensorflow's Op MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_Fold , type = Conv2D, failed, may be some node is not const
For MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise_Fold convolution weight is not const
Converte Tensorflow's Op MobilenetV1/MobilenetV1/Conv2d_1_depthwise/depthwise_Fold , type = DepthwiseConv2dNative, failed, may be some node is not const
For MobilenetV1/MobilenetV1/Conv2d_1_pointwise/Conv2D_Fold convolution weight is not const
Converte Tensorflow's Op MobilenetV1/MobilenetV1/Conv2d_1_pointwise/Conv2D_Fold , type = Conv2D, failed, may be some node is not const`

**Comment by xinyidaren** [comment]
you need to freeze all ops.
