### ISSUE TITLE
bench_android.sh failed for adb with version 1.0.32

### ISSUE THREAD

**Issue by suitmyself** [alibaba/MNN#52]
please change 
`adb push benchmark.out timeProfile.out $ANDROID_DIR`
to
```
adb push benchmark.out $ANDROID_DIR
adb push timeProfile.out $ANDROID_DIR
```
otherwise it reports error:
failed to copy 'benchmark.out' to 'timeProfile.out': couldn't create file: Read-only file system

**Comment by li-qing** [comment]
will be edited in doc soon
