### ISSUE TITLE
libMNN.a 有151M

### ISSUE THREAD

**Issue by xunkaixin** [alibaba/MNN#521]
你好:
        MNN_BUILD_SHARED_LIBS 设置成OFF，编译的android静态库太大，生成的libMNN.a有151M，怎么设置使静态库变小？
        非常感谢

**Comment by anoobtakeoff** [comment]
> 你好:
> MNN_BUILD_SHARED_LIBS 设置成OFF，编译的android静态库太大，生成的libMNN.a有151M，怎么设置使静态库变小？
> 非常感谢

开了DEBUG？

**Comment by xunkaixin** [comment]
没有，

cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DANDROID_TOOLCHAIN=gcc \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DMNN_DEBUG=false \
-DMNN_BUILD_SHARED_LIBS=OFF \

**Comment by EDMIG** [comment]
$ANDROID_NDK/build/cmake/android.toolchain.cmake 里去掉编译选项-g

**Comment by xunkaixin** [comment]
多谢
