### ISSUE TITLE
bugs of x+1

### ISSUE THREAD

**Issue by kl456123** [alibaba/MNN#522]
naive example caused segmentation fault when using opencl backend
```python
class Model(torch.nn.Module):
  def forward(self, x):
    return x+1
```
may be the last line cause the bug because host is null when using opencl
https://github.com/alibaba/MNN/blob/62c5ca47964407508a5fa802582e648fc75eb0d9/source/backend/opencl/execution/EltwiseExecution.cpp#L48-L53

**Comment by jackweiwang** [comment]
#524 the same problem？

**Comment by kl456123** [comment]
> #524 the same problem？

no, opencl backend is obviously low precise and some ops of cpu backend is different from pytorch like upsample. I just don't think develop team can solve the problem in a short time.

**Comment by jackweiwang** [comment]
Maybe my problem and it is associated， 
`sch_config.type = (MNNForwardType)MNN_FORWARD_CPU;`
change to
`sch_config.type = (MNNForwardType)MNN_FORWARD_OPENCL;`

run android process and caused collapse.

**Comment by jxt1234** [comment]
fixed
