### ISSUE TITLE
aarche64处理器，neon编译器了吗？

### ISSUE THREAD

**Issue by anoobtakeoff** [alibaba/MNN#523]
MNN的交叉编译文件夹project/cross-compile/arm-toolchain.cmake文件里，处理器是aarche64v时，cmake配置的是aarche64-linux-gnueabihf-gcc编译器。我在Linaro官网并没有找到aarche64的带hf硬浮点数的编译器。因此用的语雀教程里不带hf的编译器，从而导致MNN根目录下cmakelist.txt里不能配置hard float选项位ON。那么，编译出来的MNN应该没有开启neon指令吧？ 因为反编译查看， 并没有见到V开头的NEON指令。我应该怎么编译neon版本？或者说，我是猪油蒙住了眼睛，没有Linaro官网找到带hf的编译器吗？armv7-a的倒是找到了带hf和不带hf的0.0

**Comment by jxt1234** [comment]
aarch64 的 neon 指令不是 v 开头的，而是类似 fmla v16.4s, v0.4s, v1.s[0] 之类的形式

**Comment by jxt1234** [comment]
另外，对 aarch64  hard float是标配，所以不用开

**Comment by anoobtakeoff** [comment]
> 另外，对 aarch64 hard float是标配，所以不用开
好的，仍然有个疑问没有解决
project/cross-compile/arm-toolchain.cmake有一行配置编译器名字写成了aarche64-linux-gnueabihf-gcc
，这让我很疑惑，好像没有这个编译器。MNN怎么思考这个问题的?我找不到这个编译器0.0

**Comment by anoobtakeoff** [comment]
@jxt1234  
另外，对aarch64 hard float是标配，所以不用开
好的，仍然有个疑问没有解决
方案/cross-compile/arm-toolchain.cmake有一行配置编译器名称写到aarche64-linux-gnueabihf-gcc 
，这让我很疑惑，好像没有这个编译器。MNN怎么思考这个问题的？我发现这个编译器0.0

**Comment by anoobtakeoff** [comment]
@jxt1234  另外，对 aarch64 hard float是标配，所以不用开
好的，仍然有个疑问没有解决
project/cross-compile/arm-toolchain.cmake有一行配置编译器名字写成了aarche64-linux-gnueabihf-gcc
，这让我很疑惑，好像没有这个编译器。MNN怎么思考这个问题的?我找不到这个编译器0.0
