### ISSUE TITLE
使用Vulkan Backend 时 Session 经过 resize 后的输出结果错误

### ISSUE THREAD

**Issue by Hconk** [alibaba/MNN#526]
在使用Vulkan后端时，如果 Session 经过一次 resize ， 则第二次进行推理时计算的结果会出错。
以下代码在 CPU 和 OpenCL 下运行结果基本一致， Vulkan 下第二次推理计算结果错误。
![image](https://user-images.githubusercontent.com/8470001/70967955-e414a280-20d2-11ea-923c-c7fe26d4ba17.png)

[测试例子](https://gist.github.com/Hconk/28b3d724b58b48bc51af4f9938967a43)

输入数据及模型文件：
[data.zip](https://github.com/alibaba/MNN/files/3971658/data.zip)

**Comment by jxt1234** [comment]
可能是 winograd 代码出错的原因，请同步最新代码后测试
