### ISSUE TITLE
how to solve onnx's "data type" error.怎么解决onnx的数据类型错误

### ISSUE THREAD

**Issue by mozheng** [alibaba/MNN#527]
这个onnx是从pytorch转过来的（torch.onnx.export）。
在运行下面转换语句时出现了问题
./MNNConvert -f ONNX --modelFile purnenet.onnx --MNNModel a.mnn --bizCode ONNX
 <img width="528" alt="CDE7B27B-DF94-46B9-A02D-5BF51C17556A" src="https://user-images.githubusercontent.com/9405676/70988327-9745c180-20fc-11ea-80c5-f7ee6d3824ee.png">
这说明onnx文件内部层的格式有问题。但是我该怎么修改?

**Comment by czy2014hust** [comment]
看下是哪种数据类型？

**Comment by jxt1234** [comment]
Fixed
