### ISSUE TITLE
Not supported type on OpenCL

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#531]
Hi , I am running several networks on RK3399 on CPU and GPU.
Build Flags: ABI=arm64-v8a OpenMP=ON Vulkan=OFF OpenCL=ON
MNN benchmark
Forward type: **CPU** thread=4** precision=2

1.CPU pass run fine.
3. OpenCL:
           "  Don't support type 45, block_1_pad/Pad"
           "  Don't support type 68, global_average_pooling2d_1/Mean"
           " Don't support type 39, cnn_model/lm_dense/MatMul"

"Don't support type" means stop execution or fallback to CPU ???? thanks

**Comment by xuguozhi** [comment]
Met the same issue on RK3399 Ubuntu 18. When benchmarking on CPU, everything works fine, while on OpenCL:
Don't support type 33, 415

**Comment by jxt1234** [comment]
Supported
