### ISSUE TITLE
Confusion about depthwise conv implement of mnn

### ISSUE THREAD

**Issue by wxcstc** [alibaba/MNN#532]
I use input [1, 4, 4, 4] (nhwc), filter [2, 2, 4, 2] (filter_height, filter_width, in_channels, channel_multiplier)(I call this hwcn, :-D),  pad mode valid， dilation is 1， stride is 1. It's param in tensorflow.

And I use input [1, 1, 4, 4, 4] (nc4hwc4) which convert from nhwc to nchw and then convert from nchw to nc4hw4. Filter use [2, 4, 2, 2] (channel_multiplier, in_channels, filter_height, filter_width) which convert from hwcn to nchw. Group is 1，Other params are same with tensorflow.It's param in mnn.

The result which run from tensorflow is different from the result which run from mnn.Tensorflow result I had converted to nc4hw4.

I read src code of mnn about implement of depthwise conv.I found that channel_multiplier in mnn seemed to only work with value one .I want to confirm that this is really not supported now？Or it's just a error use of me?Just a incorrect parameters passed?

**Comment by jxt1234** [comment]
channel_multiplier has been supported in 1.1.0
