### ISSUE TITLE
tensorflow argmax not support

### ISSUE THREAD

**Issue by ligonzheng** [alibaba/MNN#536]
Hello,
I make a simple tensorflow pb file using the python script below : 
`import` tensorflow as tf
import numpy as np

def save_model():
    input_x = tf.placeholder(tf.float32,shape=[1,16],name="input_x")
    top = tf.argmax(input_x,1,name="top")
    with tf.Session() as sess:
        x_data = np.random.rand(1,16)
        print(x_data)
        sess.run(tf.global_variables_initializer())
        res = sess.run(top, feed_dict={input_x:x_data})
        print(res)
        graph = tf.get_default_graph()
        input_graph_def = graph.as_graph_def()
        output_node_names = 'top'
        output_graph_def = tf.graph_util.convert_variables_to_constants(sess=sess,
                                                                    input_graph_def=input_graph_def,
                                                                    output_node_names=output_node_names.split(','))
        # serialize to graph and write to disk
        output_graph_def_filename = './frozen_model.pb'
        with tf.gfile.GFile(output_graph_def_filename, 'wb')as f:
            f.write(output_graph_def.SerializeToString())

if __name__ == '__main__':
    save_model()
``
Then I use the MNNConvert to convert it from tensorflow to mnn, but I get this error : 
Can't compute size for 11, name=top/dimension
Don't support not const ArgMax point
Converte Tensorflow's Op top , type = ArgMax, failed, may be some node is not const

So what's the problem ?

**Comment by ligonzheng** [comment]
Please note  this only happen when I turn MNN_BUILD_SHARED_LIBS off.

**Comment by Naville** [comment]
Broken CMake I assume. Should have been fixed in latest release
