### ISSUE TITLE
Xcode11.3按照文档运行Demo报错

### ISSUE THREAD

**Issue by Adleys** [alibaba/MNN#539]
运行get_model.sh脚本时，下载模型一直失败
报Model File Does Not Exist! ==> build/squeezenet_v1.0.caffe.caffemodel；
./../build/MNNConvert: No such file or directory

**Comment by MenSanYan** [comment]
Hello, I just solved this problem. Type "mkdir resource/build" in the root directory of MNN, and run get_model.sh again. You will get yourself on the right way. Have a try now...

**Comment by xuguozhi** [comment]
Solved!
