### ISSUE TITLE
iOS can't use MNN in framework way  (Only pod way valid).

### ISSUE THREAD

**Issue by chrisYooh** [alibaba/MNN#54]
**Target:**
I want to integrate MNN by using iOS static framework.
But I can't find an elegant way to archive it.

**Try:**
1. I open the framework project (MNN-master/project/ios/MNN.xcodeproj) and build it.
2. Use the output framework and try a single MNN demo.

**Visibal Problem:**
The app crashed in Interpreter.cpp (MNN_ASSERT(nullptr != session) )
And I found out the message like this:

```
Cant't Find type=0 backend, use 0 instead
Create Backend Failed because no creator for 0
Invalide Session
```

**Real Problem:**
IOS Static Framework may not support using global variable initial function as an app-before-launch initial function.

I debug the problem and found that the real problem is the CPUBackend and MetalBackEnd can't initial themselves automatically. mean the following global variable can't initial automatic.

```
/* In CPUBackend.cpp */
static bool registerCPUBackendCreator = [] {
    MNNInsertExtraBackendCreator(MNN_ForWARD_CPU, new CPUBackendCreator);
    return true;
}

/* In MetalBackend.mm */
static bool __reg = MNNInsertExtraBackendCreator(MNN_FORWARD_METAL, new MetalBackendCreator);
```

Then we can't find a valid Creator in gExtraCreator.

**Target Again**
So, could you please support me a way to use MNN in iOS static framework way?
Thanks a lot.

**Comment by jxt1234** [comment]
It has been optimized. Please update the code and try again.

**Comment by chrisYooh** [comment]
I update the code and try again.
But when I use the framework, it perhaps cause another problem.

**When I define a MNN net and init it:**

```
std::shared_ptr<MNN::Interpreter> _net;
_net = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(""));
```

**Build failed and the note is :**

```
Undefined symbols for architecture arm64:
  "MNN::registBackend()", referenced from:
      MNN::MNNGetExtraBackendCreator(MNNForwardType) in MNN(Backend.o)
  "MNN::registerShapeOps()", referenced from:
      MNN::SizeComputerSuite::get() in MNN(SizeComputer.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

:-1: Undefined symbol: MNN::registBackend()
:-1: Undefined symbol: MNN::registerShapeOps()
```

**Comment by li-qing** [comment]
is the file <BackendRegister.cpp> included in your build phases?

**Comment by chrisYooh** [comment]
Thanks a lot. 
The problem has been solved and now I can use the iOS static framework. : )

**Comment by fengsky401** [comment]
> Thanks a lot.
> The problem has been solved and now I can use the iOS static framework. : )

Can you tell how you solved the problem?
