### ISSUE TITLE
vulkan的backend在华为meta30上运行出错

### ISSUE THREAD

**Issue by HappyJasonYuan** [alibaba/MNN#541]
环境：
1.cmake version 3.10.2
2.libprotoc 3.11.1
3.gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
4.android-ndk-r20

编译：
1.修改/home/huawei/MNN-master/project/android/build_64.sh 打开-DMNN_VULKAN=ON
2.编译出libMNN.so libMNN_Vulkan.so timeProfile.out 
3.推送so到 /data/local/tmp， 

运行：
1.运行timeProfile.out，参数如下
adb shell "LD_LIBRARY_PATH=%ANDROID_DIR% %ANDROID_DIR%/timeProfile.out %ANDROID_DIR%/benchmark_models/CSRNET_21k_x2_540.mnn 10 7 1x4x180x320"
2.运行结果如下：
Can't Find type=7 backend, use 0 instead

原因是调用auto res = enumeratePhysicalDevices(gpuCount, nullptr);
res=VK_SUCCESS 但是gpuCount=0，google给的demo源码可以运行起来gpuCount=1，看起来像是环境vulkan的运行环境不太对

**Comment by jxt1234** [comment]
华为系统的安全设置的原因，用 adb shell 方式无法打开 vulkan，请启动 app 去测试
