### ISSUE TITLE
The Creator Don't support type 101

### ISSUE THREAD

**Issue by LjwPanda** [alibaba/MNN#543]
tf模型转换成功，但无法使用opencl进行推理，CPU可以，报错如下：
The Creator Don't support type 101, conv1_1/Exp
该节点属性如下，是做一个exp操作，该算子是支持的。
![properties](https://user-images.githubusercontent.com/52033459/71505664-010e5a00-28b9-11ea-8b62-36da693f4cc7.png)
求解

**Comment by jxt1234** [comment]
Supported
