### ISSUE TITLE
CPU和OPENCL结果输出不一致

### ISSUE THREAD

**Issue by KangKangLoveCat** [alibaba/MNN#544]
模型是从mxnet->onnx->mnn转过来的,在CPU下能得到正确的结果,但在OPENCL上结果完全不对,运算中也没有任何错误提示,就是结果不对.
[mobilefacenet.zip](https://github.com/alibaba/MNN/files/4006940/mobilefacenet.zip)

**Comment by KangKangLoveCat** [comment]
使用MNN自带的测试工具在手机上测试,输入1x3x112x112,结果输出不一致

**Comment by xuguozhi** [comment]
训练了PFLD pytorch版本，同样遇到了这个现象

**Comment by ToBigboss** [comment]
> 使用MNN自带的测试工具在手机上测试,输入1x3x112x112,结果输出不一致

backend.out测试一下，在哪个op出错了

**Comment by xuguozhi** [comment]
> Test forward type: 3
Tolerance Rate: 0.050000
Open Model ../../pfld_mnn/pfld/pfld_sim.mnn
Input: 112,112,3,1
precision=0 in main, 159
stopOp.c_str()=s  in main, 164
0: 0.000000 != 0.194880
414 is error

while on CPU backend：

> Test forward type: 0
Tolerance Rate: 0.050000
Open Model ../../pfld_mnn/pfld/pfld_sim.mnn
Input: 112,112,3,1
precision=0 in main, 159
stopOp.c_str()=s  in main, 164
Correct !

414 may be Concat in onnx model

**Comment by KangKangLoveCat** [comment]
/backendTest.out models/mobilefacenet.mnn 3 0.15                              <
Test forward type: 3
Tolerance Rate: 0.150000
Open Model models/mobilefacenet.mnn
Input: 112,112,3,1
precision=0 in main, 157 
stopOp.c_str()=s  in main, 162 
Correct !
/backendTest.out models/mobilefacenet.mnn 0 0.15                              <
Test forward type: 0
Tolerance Rate: 0.150000
Open Model models/mobilefacenet.mnn
Input: 112,112,3,1
precision=0 in main, 157 
stopOp.c_str()=s  in main, 162 
Correct !

**Comment by KangKangLoveCat** [comment]
错误信息：
/backendTest.out models/mobilefacenet.mnn 3 1                                 <
Test forward type: 3
Tolerance Rate: 1.000000
Open Model models/mobilefacenet.mnn
Input: 112,112,3,1
precision=0 in main, 157 
stopOp.c_str()=s  in main, 162 
0: 127.500000 != -127.500000
_minusscalar0 is error
nanopc-t4:/data/local/tmp/mnn_demo $ 

对应网络：
{
  "nodes": [
    {
      "op": "null", 
      "name": "data", 
      "inputs": []
    }, 
    {
      "op": "_minus_scalar", 
      "name": "_minusscalar0", 
      "attrs": {"scalar": "127.5"}, 
      "inputs": [[0, 0, 0]]
    }, 
    {
      "op": "_mul_scalar", 
      "name": "_mulscalar0", 
      "attrs": {"scalar": "0.0078125"}, 
      "inputs": [[1, 0, 0]]
    }, 
    {
      "op": "null", 
      "name": "conv_1_conv2d_weight", 
      "attrs": {
        "kernel": "(3, 3)", 
        "no_bias": "True", 
        "num_filter": "64", 
        "num_group": "1", 
        "pad": "(1, 1)", 
        "stride": "(2, 2)"
      }, 
      "inputs": []
    },

**Comment by KangKangLoveCat** [comment]
算子_minus_scalar应该是对应MNN里面的Binary Sub

**Comment by KangKangLoveCat** [comment]
问题已经解决了。原因是opencl里面算子Binary Sub的减数和被减数被颠倒了，导致算出来的结果是反的，“a-b”变成了"b-a"。

**Comment by xuguozhi** [comment]
你是怎么解决的呢

**Comment by KangKangLoveCat** [comment]
@xuguozhi  opencl后端下的Binary Sub算子应该是有bug，我改了之后结果就对了，你看下你那个算子是不是有问题，然后自己改一下

**Comment by xuguozhi** [comment]
我康康opencl源码
