### ISSUE TITLE
Not Support: Tensorflow::BatchToSpaceND | Tensorflow::SpaceToBatchND

### ISSUE THREAD

**Issue by TPcoding** [alibaba/MNN#546]
log:
MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
Start to Optimize the MNN Net...
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers2/conv_2/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/SpaceToBatchND , type = SpaceToBatchND, failed, may be some node is not const
Not Cost paddingShape
Converte Tensorflow's Op Inference/cnn_layers4/conv_4/conv2d/BatchToSpaceND , type = BatchToSpaceND, failed, may be some node is not const
[16:17:57] :20: Inputs: ac_input
[16:17:57] :37: Outputs: Inference/final_output/output, Type = Reshape
terminate called after throwing an instance of 'Error'
  what():  [16:17:57] /home/aisp/work_resource_mirror/mnn-master/MNN/tools/converter/source/common/writeFb.cpp:107: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: Tensorflow::BatchToSpaceND | Tensorflow::SpaceToBatchND | 
已放弃 (核心已转储)

version:
0.2.1.5,切换到当前最新的master,重新编译,一样也会报错.
conv2d 带dilation,输入是宽度不定的图片. 这个问题纠结很久了. 过了两个月的版本迭代.还是无法成功转换这个模型.麻烦请看一下

**Comment by jxt1234** [comment]
convolution with dilate 在 输入大小不定时 不支持，后续也没有计划支持，因为一般情况下可以固定输入大小去解决问题
