### ISSUE TITLE
How to confirm MNN enabling NEON while running?

### ISSUE THREAD

**Issue by anoobtakeoff** [alibaba/MNN#547]
I could not confirm if NEON was enabled. So,  I tried “arm-linux-gnueabihf-objdump -S libMNN.so”, but no NEON instructions like VADD. The CPU is armv7-a，32bit. Someone help me ? Thanks! 

**I compiled MNN as following:**

1.  Enable  MNN_BUILD_HARD in  CMakeLists.txt
option(MNN_BUILD_HARD "Build -mfloat-abi=hard or not" ON)
2.  Crossing-compile instruction after cd build
cmake .. \
-DCMAKE_SYSTEM_NAME=Linux \
-DCMAKE_SYSTEM_VERSION=1 \
-DCMAKE_SYSTEM_PROCESSOR=armv7-a \
-DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
-DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++
make -j8

**Comment by Naville** [comment]
Seems like our recent build system rewrite left that part out. I'll take a look into this and should be able to push out a quick fix in about 14 hours
