### ISSUE TITLE
MobileNet_V2 tensorflow and MNN different output on RK3399 CPU

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#548]
Hi , 
I have a models TensorFlow MobileNet_V2 and converted mnn model
https://drive.google.com/open?id=14WXTkRHzj-9_pWxsxwLchdn2oa8_39AA
With output results are completely different!!!!!!!!!!!!!
Please advise how to handle it.
OS Android 8.1, CPU. 
Thanks.

**Comment by xuguozhi** [comment]
maybe some layer op is not supported by mnn

**Comment by dimitryn** [comment]
@xuguozhi  yes, but how can I find out.
If MNN supported any layer output I could dump output result tensorflow/MNN and compare. But here I can only provide models and hope someone will look and check

**Comment by xuguozhi** [comment]
try: cd MNN/build
then execute ./backendTest.out models/xx.mnn 3(for opencl) or
./backendTest.out models/xx.mnn 0(for cpu)

**Comment by dimitryn** [comment]
@xuguozhi It will tell me the result I already know, but no reason for that !!!

**Comment by remarkableJ** [comment]
@dimitryn hello, sir, I was troubled by a problem of openvino , https://github.com/opencv/dldt/issues/345, which similar to yours. Fortunately, you had figured it out, please help to handle it.

**Comment by dimitryn** [comment]
@remarkableJ on Linux use official openvino installer and binaries. in CMakeList use only ${OPEN_VINO_DIR}/x86_64/libinference_engine.so  and other so put in the same directory.
