### ISSUE TITLE
Compile Error when build OpenCL in linux X86

### ISSUE THREAD

**Issue by azuredsky** [alibaba/MNN#551]
I add the line in CMakeLists.txt  Line 439  ：
  target_link_libraries(MNN_CL PRIVATE MNN OpenCL)
build is ok
may be is loss link OpenCL library

**Comment by Naville** [comment]
Noted. Will be fixed in the next release. Seems like our current CI configuration doesn't take ``MNN_SEP_BUILD`` into account.
