### ISSUE TITLE
tensorflow 非固定尺寸输入的支持

### ISSUE THREAD

**Issue by reason4** [alibaba/MNN#552]
对于tensorflow固定的输入尺寸可以采用如下的方式集成：
std::vector<int> dims{1, INPUT_SIZE, INPUT_SIZE, 3};
auto nhwc_Tensor = MNN::Tensor::create<float>(dims, NULL, MNN::Tensor::TENSORFLOW);
而如果INPUT_SIZE是动态变化的，在tensorflow生成pb的时候需要将placeholder写成input = tf.placeholder(dtype, (1, None, None, 1), name="src")的形式（尺寸动态变化，写为None），pb可以成功转换为mnn格式，但是在mnn框架下运行会出错，请问有什么方法支持动态shape输入吗

**Comment by czy2014hust** [comment]
请参考[此处文档](https://www.yuque.com/mnn/cn/input#9xXDG)

**Comment by reason4** [comment]
按照文档提供的方法解决了该问题，谢谢！
