### ISSUE TITLE
[regression in 0.2.1.6] relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC

### ISSUE THREAD

**Issue by yurivict** [alibaba/MNN#553]
```
ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by AutoTime.cpp
>>>               CMakeFiles/MNNCore.dir/source/core/AutoTime.cpp.o:(MNN::Timer::Timer())

ld: error: relocation R_X86_64_PC32 cannot be used against symbol __stack_chk_guard; recompile with -fPIC
>>> defined in /lib/libc.so.7
>>> referenced by AutoTime.cpp
>>>               CMakeFiles/MNNCore.dir/source/core/AutoTime.cpp.o:(MNN::Timer::Timer())
```

clang-8

FreeBSD 12

**Comment by Naville** [comment]
``-fPIC`` is indeeded added in our CMakeLists and MNN builds without any issue on our Ubuntu CI so I'm a bit confused about what's going on here. Any more context? output of initial cmake configuration or better yet, a full build log would do.

**Comment by yurivict** [comment]
-fPIC is missing in some command lines. Adding it to CXXFLAGS and CFLAGS environment variables solved the problem.

**Comment by Naville** [comment]
Right. Unless I'm missing something here, [CMakeLists.txt#L173](https://github.com/alibaba/MNN/blob/002ac367e4a9339b98180e14838900271bc55a55/CMakeLists.txt#L173) already sets this flag. And consider this line is above any other target is created/imported, this should have effect on all targets created by CMake. 

Are you sure ``CMAKE_SYSTEM_NAME`` is ``Linux`` on FreeBSD?

**Comment by Naville** [comment]
So ``CMAKE_SYSTEM_NAME`` is ``FreeBSD`` on FreeBSD which breaks that part of the logic. This was never discovered in previous versions because the old ``CMakeLists.txt`` was passing ``-fPIC`` everywhere. This should be fixable in our next release

**Comment by yurivict** [comment]
No, on FreeBSD CMAKE_SYSTEM_NAME=FreeBSD
