### ISSUE TITLE
MNN转换onnx模型后输出数据偏差

### ISSUE THREAD

**Issue by yippeesoft** [alibaba/MNN#555]
MXNET MODEL使用 https://github.com/deepinsight/insightface/wiki/Model-Zoo MobileFaceNet,ArcFace@ms1m-refine-v1
https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA
 
先转换成onnx格式，mxnet使用onnx model也正常。
input_shape=(1,3,112,112)
onnx_file='./model-y1.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)

再用mnnconvert获得MNN模型，运行后得到的数据与mxnet模型偏差很大。

**Comment by KangKangLoveCat** [comment]
您好，能问一下，https://github.com/deepinsight/insightface/tree/master/deploy/mtcnn-model，insightface的mtcnn模型您成功复现了吗

**Comment by KangKangLoveCat** [comment]
您好，能问一下，https://github.com/deepinsight/insightface/tree/master/deploy/mtcnn-model
insightface的mtcnn模型您成功用MNN复现了吗

**Comment by KangKangLoveCat** [comment]
https://github.com/alibaba/MNN/files/4006940/mobilefacenet.zip
这个是我用的mobilefacenet模型，您看下能不能用，我目前用着没有什么问题

**Comment by xuguozhi** [comment]
> https://github.com/alibaba/MNN/files/4006940/mobilefacenet.zip
> 这个是我用的mobilefacenet模型，您看下能不能用，我目前用着没有什么问题

你的模型需要更改MNN源码么，OpenCL

**Comment by KangKangLoveCat** [comment]
[mnn.zip](https://github.com/alibaba/MNN/files/4024488/mnn.zip)
这个是我编译的MNN库，在cpu和opencl下都可正常部署mobilefacenet，但不保证其它模型没有问题

**Comment by KangKangLoveCat** [comment]
我在https://github.com/alibaba/MNN/, commit id: 62c5ca47964407508a5fa802582e648fc75eb0d9，基础上修改过OPENCL下的Binary算子

**Comment by xuguozhi** [comment]
https://github.com/alibaba/MNN/releases 0.2.1.6 好像提到了：OpenCL BinaryOp 相关 Bug 修复

**Comment by KangKangLoveCat** [comment]
您之前不是说Concat算子有问题吗

**Comment by xuguozhi** [comment]
> 您之前不是说Concat算子有问题吗

是的，还在查

**Comment by yippeesoft** [comment]
代码问题。模型正确。谢谢。
