### ISSUE TITLE
win下createSession出错

### ISSUE THREAD

**Issue by vampirecover** [alibaba/MNN#557]
请教大佬，我在win下编译mnn后使用网上一个转换好的mnn模型，发现在linux下没有问题，但是在win下使用有问题，同样的代码同样的模型。请教这是什么原因？
错误：0x000007FEFD4EA06D 处(位于 mnnInrference.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_array_new_length，位于内存位置 0x000000000030F100 处。
code：
`int mnnInference::LoadModel(const char* root_path) 
{
	std::string model_file = std::string(root_path) + "det1.mnn";

	cout << model_file.c_str() << endl;
	landmarker_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));

	MNN::ScheduleConfig config;
	config.numThread = 1;
	config.type =  static_cast<MNNForwardType>(device_);

	MNN::BackendConfig backendConfig;
	backendConfig.precision = (MNN::BackendConfig::PrecisionMode)precision_;
	backendConfig.power = (MNN::BackendConfig::PowerMode) power_;
	backendConfig.memory = (MNN::BackendConfig::MemoryMode) memory_;
	config.backendConfig = nullptr;// &backendConfig;
	session_ = landmarker_->createSession(config);`
模型位置：https://github.com/SyGoing/LFFD-MNN/tree/master/models

**Comment by ToBigboss** [comment]
> 请教大佬，我在win下编译mnn后使用网上一个转换好的mnn模型，发现在linux下没有问题，但是在win下使用有问题，同样的代码同样的模型。请教这是什么原因？
> 错误：0x000007FEFD4EA06D 处(位于 mnnInrference.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_array_new_length，位于内存位置 0x000000000030F100 处。
> code：
> `int mnnInference::LoadModel(const char* root_path)
> {
> std::string model_file = std::string(root_path) + "det1.mnn";
> 
> ```
> cout << model_file.c_str() << endl;
> landmarker_ = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFromFile(model_file.c_str()));
> 
> MNN::ScheduleConfig config;
> config.numThread = 1;
> config.type =  static_cast<MNNForwardType>(device_);
> 
> MNN::BackendConfig backendConfig;
> backendConfig.precision = (MNN::BackendConfig::PrecisionMode)precision_;
> backendConfig.power = (MNN::BackendConfig::PowerMode) power_;
> backendConfig.memory = (MNN::BackendConfig::MemoryMode) memory_;
> config.backendConfig = nullptr;// &backendConfig;
> session_ = landmarker_->createSession(config);`
> ```
> 
> 模型位置：https://github.com/SyGoing/LFFD-MNN/tree/master/models

1.是不是mnn库类型和工程类型没对应，release库只能用release工程，debug库只能用debug工程；
2.是不是你mnn库编得有问题， win上用ninja重编最新版本代码看看。

**Comment by vampirecover** [comment]
感谢 ，问题解决了，应该是我这边debug模式导致
