### ISSUE TITLE
iOS demo incorrect Mobilenetv2 behavior with Metal

### ISSUE THREAD

**Issue by cclaan** [alibaba/MNN#558]
Hi, 
I built the demo ios playground app. When using the default cat photo on CPU, the output is correctly classified as "Egyptian cat", but when Metal is used, the photo is incorrectly classified. The same behavior occurs when using the camera mode when using Metal. It seems to return random labels.
Thanks 
[edit]
Adding my device is an iPhone X running iOS 13.1.2

**Comment by jxt1234** [comment]
Fixed. Please update
