### ISSUE TITLE
protobuf issues

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#559]
I use archlinux docker ,I can build success on the platform.When I build android_32 use the build_32.sh,It occurs can't find Protobuf(in version 0.2.1.6),but I can build sucess in version 0.2.1.0,Ican make sure that protoc has been installed,so how can I sloved this ?any suggestions?

**Comment by Naville** [comment]
???

**Comment by Naville** [comment]
CI上是正常的
