### ISSUE TITLE
Windows下MNNConvert.exe 转换模型失败

### ISSUE THREAD

**Issue by 395062753** [alibaba/MNN#561]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
windows10 64位
visual studio 2019
nmake

MNN.lib 和 MNNConvert.exe都能正常编译出来
在PS中执行脚本 MNNConvert.exe -h 和MNNConvert.exe -v 控制台都没有任何输出，如下
![1](https://user-images.githubusercontent.com/7656229/71716967-6f22c600-2e51-11ea-9188-26d34dc19ee1.png)

执行模型转换时：

./MNNConvert.exe -f CAFFE --modelFile ./mobilenet_v2.caffemodel --prototxt ./mobilenet_v2_d
eploy.prototxt --MNNModel ./mobilenet_v2.mnn --bizCode 0000

![2](https://user-images.githubusercontent.com/7656229/71716969-7518a700-2e51-11ea-8578-1acd2c1c2b7d.png)

没有报错，但也没有结果输出，哪位朋友遇到同样的问题么

**Comment by cvipdream** [comment]
![image](https://user-images.githubusercontent.com/30815640/72488822-11c54680-384d-11ea-98a5-7716d51fa131.png)
编了好几个版本（win7+vs2015），都转不成功模型

**Comment by 850977164** [comment]
ubuntu下编译MNN0.2.1.0，没有生成MNNConvert可执行文件，是什么原因呢

**Comment by ToBigboss** [comment]
> # 平台(如果交叉编译请再附上交叉编译目标平台):
> # Platform(Include target platform as well if cross-compiling):
> windows10 64位
> visual studio 2019
> nmake
> 
> MNN.lib 和 MNNConvert.exe都能正常编译出来
> 在PS中执行脚本 MNNConvert.exe -h 和MNNConvert.exe -v 控制台都没有任何输出，如下
> ![1](https://user-images.githubusercontent.com/7656229/71716967-6f22c600-2e51-11ea-9188-26d34dc19ee1.png)
> 
> 执行模型转换时：
> 
> ./MNNConvert.exe -f CAFFE --modelFile ./mobilenet_v2.caffemodel --prototxt ./mobilenet_v2_d
> eploy.prototxt --MNNModel ./mobilenet_v2.mnn --bizCode 0000
> 
> ![2](https://user-images.githubusercontent.com/7656229/71716969-7518a700-2e51-11ea-8578-1acd2c1c2b7d.png)
> 
> 没有报错，但也没有结果输出，哪位朋友遇到同样的问题么

可以在Linux下面转模型啊！！   windows上面转换工具之前是不能用的，不知道后面搞定了没

**Comment by Lininggggggg** [comment]
请问现在解决了吗？在Windows下还是不能成功吗？只能在其他系统上先转换模型吗？

**Comment by cvwoker** [comment]
现在都用NCNN，近来版本没编译，不知道目前怎么样， 想等段时间再看看，MNN windows上投入有点少



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lininggggggg"<notifications@github.com&gt;; 
发送时间: 2020年4月4日(星期六) 下午4:49
收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;; 
抄送: "kghcy"<767990288@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/MNN] Windows下MNNConvert.exe 转换模型失败 (#561)





 
请问现在解决了吗？在Windows下还是不能成功吗？只能在其他系统上先转换模型吗？

**Comment by Lininggggggg** [comment]
嗯嗯，这样，虽然还是出不来，但还是非常感谢您！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cvwoker"<notifications@github.com&gt;; 
发送时间: 2020年4月6日(星期一) 晚上7:39
收件人: "alibaba/MNN"<MNN@noreply.github.com&gt;; 
抄送: "尹雁"<1296889948@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [alibaba/MNN] Windows下MNNConvert.exe 转换模型失败 (#561)





 现在都用NCNN，近来版本没编译，不知道目前怎么样， 想等段时间再看看，MNN windows上投入有点少 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Lininggggggg"<notifications@github.com&amp;gt;;  
 发送时间: 2020年4月4日(星期六) 下午4:49 
 收件人: "alibaba/MNN"<MNN@noreply.github.com&amp;gt;;  
 抄送: "kghcy"<767990288@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [alibaba/MNN] Windows下MNNConvert.exe 转换模型失败 (#561) 
 
 
 
 
 
   
 请问现在解决了吗？在Windows下还是不能成功吗？只能在其他系统上先转换模型吗？

**Comment by jxt1234** [comment]
1.0.0 已经解决了
