### ISSUE TITLE
pymnn 传送数据效率问题

### ISSUE THREAD

**Issue by smartwell** [alibaba/MNN#562]
首先非常非常感谢,作者的开源精神
pip install mnn 
这是我的代码, cpu i7-7700k
``` python
def detect_face(img, th=0.3):
    t0 = time.time()
    image = cv2.resize(img, (320, 256))
    image = image.transpose((2, 0, 1))
    print("resize image time: ", time.time() - t0)
    t0 = time.time()
    tmp_input = MNN.Tensor((1, 3, 256, 320), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe)
    print("creat Tensor time: ", time.time() - t0)
    d_input_tensor.copyFromHostTensor(tmp_input)
    t0= time.time()
    d_interpreter.runSession(d_session)
    scores = d_interpreter.getSessionOutput(d_session, "centernet0_scores").getData()
    boxes = d_interpreter.getSessionOutput(d_session, "centernet0_boxes").getData()
    print("inference time: ", time.time() - t0)
```
运行结果:
resize image time:  0.0010373592376708984
creat Tensor time:  0.016360044479370117
inference time:  0.016448497772216797
all time:  0.03428483009338379

如结果所示,creat Tensor 占用了大量时间,也想了很多方法,但是没有用,想请教作者有什么改进方式,万分感谢.

**Comment by nullptr-leo** [comment]
自行实现 py 接口把 cv2/numpy 数据传下去

**Comment by stanleywang8888** [comment]
1. 不好意思, 这个问题目前还没有排上日程,  解决方式应该是引入numpy，去掉拷贝，但是这会增加一个不必要的，MNN的设计原则之一就是尽可能减少不必要的依赖。 
2. 可以问一下你们是什么场景嘛，python下的性能是一个重要的关注点嘛？为什么？

**Comment by vocong25** [comment]
@nullptr-leo @smartwell 
Have you overcome this problems? I stuck at it in a while and had no idea to do.

**Comment by smartwell** [comment]
> @nullptr-leo @smartwell @jxt1234
> Have you overcome this problems? I stuck at it in a while and had no idea to do.

sorry, i change to C++

**Comment by nullptr-leo** [comment]
> @nullptr-leo @smartwell @jxt1234
> Have you overcome this problems? I stuck at it in a while and had no idea to do.

Just create an interface to pass in the numpy directly without any data copy.
You can try `Cython` or `boost.numpy`.

**Comment by stanleywang8888** [comment]
约两礼拜后更新解决

**Comment by nullptr-leo** [comment]
> 约两礼拜后更新解决

是引入numpy吗？
