### ISSUE TITLE
我不知道這是否是錯誤，但是，為什麼MNN OpenCL不隱藏源內核代碼文件的.exe中的字符串？

### ISSUE THREAD

**Issue by LeoCloser** [alibaba/MNN#563]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux ubuntu 14.04 LTS.

# 编译方式:
# Compiling Method
Cross compile.

**Comment by Naville** [comment]
> 源內核代碼文件的.exe中的字符串


??????

**Comment by LeoCloser** [comment]
I compiled the current MNN library.

I noticed that  the resulting executable contains the kernel strings. Do You know how to hide them?

In example I can see this:

```
__kernel void int8_to_float(
                      __private const int global_size_dim0, __private const int global_size_dim1, __private const int global_size_dim2,
                       __global char* input_ptr, __write_only image2d_t output, __global FLOAT* scale_ptr, __private const int height, __private const int width) {
    const int channel_block_idx = get_global_id(0);
    const int w                 = get_global_id(1);
    const int hb                = get_global_id(2);
    
    if (channel_block_idx < global_size_dim0 && w < global_size_dim1 && hb < global_size_dim2) {
        
        int index = channel_block_idx*height*width + hb*width + w;
        char4 in = vload4(index, input_ptr);

        FLOAT4 scale = vload4(channel_block_idx, (__global FLOAT *)scale_ptr);

        FLOAT4 result_float = CONVERT_FLOAT4(convert_int4_rte(in)) * scale;

        const int pos  = mad24(channel_block_idx, width, w);
        WI_F(output, (int2)(pos, hb), result_float);
        
    }
    
}
```

**Comment by Naville** [comment]
Right. They are, after all, needs to be sent to the kernel side GPU driver for compilation. So I don't think any protection would be meaningful

**Comment by Naville** [comment]
Some graphical APIs (Including Vulkan/OpenCL if I remember correctly) do have APIs that allows you to save and load compiled GPU object files instead of shader sources. However those object files, by relevant standard, is highly platform/hardware dependent so it makes no sense for us to ship the kernels that way.

**Comment by Naville** [comment]
If this is what you want then I'm afraid you'll need to hack MNN by yourself since this is a use case we currently don't and likely never will/can support
