### ISSUE TITLE
迁移学习得到的 tflite 模型转换失败

### ISSUE THREAD

**Issue by 4dcity** [alibaba/MNN#565]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
Mac

# Github版本(直接下载ZIP包请提供下载日期:
f4e28567d3297682091494e10b262d1626dba6c1

# 编译方式:
CMake

在mac平台成功编译出 MNNConverter，转换从[这个链接](http://download.tensorflow.org/models/tflite_11_05_08/mobilenet_v2_1.0_224.tgz) 下载的模型可以成功，但是用自己迁移学习得到的模型就转换失败，报错也没有任何有用信息
```
will@WilldeMacBook-Pro converter % ./MNNConvert -f TFLITE --modelFile ./new_mobile_model.tflite --MNNModel mobile.mnn --bizCode biz

MNNConverter Version: 0.2.1.7git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
libc++abi.dylib: terminating with uncaught exception of type Error
zsh: abort      ./MNNConvert -f TFLITE --modelFile ./new_mobile_model.tflite --MNNModel   biz
```

**Comment by Naville** [comment]
理论上这里应该有个出错提示，但是没有打印出来。 模型上传到回复里我看一下

**Comment by wuting0521** [comment]
遇到相同的问题了相同的问题

**Comment by wuting0521** [comment]
[mnn_convert_test.tflite.zip](https://github.com/alibaba/MNN/files/4034515/mnn_convert_test.tflite.zip)

**Comment by jiefly** [comment]
也碰到了相同的问题
./MNNConvert -f TFLITE --modelFile ~/Downloads/smartreply_1.0_2017_11_01/smartreply.tflite --MNNModel ../../mnnmdoels/smartreply.tflite.mnn --bizCode 0000

MNNConverter Version: 0.2.1.7git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
libc++abi.dylib: terminating with uncaught exception of type Error
Abort trap: 6

没有有效的提示，模型地址：http://download.tensorflow.org/models/tflite/smartreply_1.0_2017_11_01.zip

**Comment by Naville** [comment]
@jiefly 
> DCHECK(inputTensor->shape.size() == 4) << "Input Shape should be 4D";

**Comment by Naville** [comment]
@wuting0521 包含不支持的Op

**Comment by Naville** [comment]
log相关代码不同步导致，已修复。
