### ISSUE TITLE
'MNN_generated.h' file not found

### ISSUE THREAD

**Issue by Kevin369** [alibaba/MNN#569]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:0.2.1.6
# Github Version:直接下载的压缩包解压

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:xcode编译
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:0.2.1.6
# Build Log:

运行iOS demo的时候出现问题

'MNN_generated.h' file not found

./get_model.sh报错    can't find /build/MNNConvert, building converter firstly

cd demo/iOS
   pod update
报1000多个错误，此处就不粘贴了

pod install可以执行，执行完毕后，再编译报'MNN_generated.h' file not found

请问需要怎么解决？
需要配置下面这个三个环境吗？ 
 cmake（建议使用3.10或以上版本）、
protobuf（使用3.0或以上版本）
gcc（使用4.9或以上版本）
期待解答
```
粘贴在这里
Paste log here or pastebin
```

**Comment by Naville** [comment]
> can't find /build/MNNConvert, building converter firstly

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/5205699/71955246-bda1dd00-3222-11ea-906e-a83ce05657ec.png">

> pod update
> 报1000多个错误，此处就不粘贴了

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/5205699/71955726-1625aa00-3224-11ea-81ef-e9e8aca09fa8.png">

**Comment by Naville** [comment]
> pod install可以执行，执行完毕后，再编译报'MNN_generated.h' file not found
同样本地正常。某些情况下似乎会报错MetalOpRegister.mm找不到，这种时候在源码根目录手动执行以下两条指令即可: 

```
schema/generate.sh
                          python source/backend/metal/MetalCodeGen.py source/backend/metal/ source/backend/metal/MetalOPRegister.mm
```

**Comment by Kevin369** [comment]
请问怎么建立转换器

**Comment by 850977164** [comment]
![image](https://user-images.githubusercontent.com/39330916/72494232-30800900-385e-11ea-82a9-98816bc69830.png)
I had this problem while compiling the installation，how to solve it

**Comment by 850977164** [comment]
如何编译转换工具

**Comment by 850977164** [comment]
@Naville ![image](https://user-images.githubusercontent.com/39330916/72592686-0aca3100-393e-11ea-8875-6acba01f57cd.png)
