### ISSUE TITLE
mac下静态库执行异常，动态库OK

### ISSUE THREAD

**Issue by Volcanoscar** [alibaba/MNN#570]
# 平台(如果交叉编译请再附上交叉编译目标平台):  macOS 10.15

# Github版本: c95892de878d738ecfe451e8baab207fab9daac2

# 编译方式:
cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_SHARED_LIBS=OFF && make -j4

# 问题
使用动态库正常，使用静态库，运行结果不正确，log如下：
Don't support type 12, mobilenetv2/conv1_1/conv1_1/conv2d/Conv2D
Don't support type 12, mobilenetv2/conv1_1/conv1_1/conv2d/Conv2D
Resize error for mobilenetv2/conv1_1/conv1_1/conv2d/Conv2D, code=2

**Comment by Naville** [comment]
应该是静态链接的时候backend被链接优化掉导致backend没有正确注册。试试shared那个设置成ON

**Comment by Volcanoscar** [comment]
shared设置为ON是OK的

**Comment by Bbean** [comment]
-Wl,--whole-archive mnn.a -Wl,--no-whole-archive
链接时加上这个，链接全部内容

**Comment by Volcanoscar** [comment]
@Bbean 
https://github.com/alibaba/MNN/blob/c95892de878d738ecfe451e8baab207fab9daac2/CMakeLists.txt#L459
编译静态库的时候看有加上吧？引用时也需要加上，应该怎么加，麻烦指点下，多谢

**Comment by Bbean** [comment]
在你自己工程的 CMakeLists 文件中链接 mnn 静态库的时候加

**Comment by Volcanoscar** [comment]
@Bbean 多谢指点，mac下貌似是：-Wl,-all_load ${MNN_DEPEND} -Wl,-noall_load，这个，加上后OK了
if (NOT MNN_BUILD_SHARED_LIBS)
    if(APPLE)
        set(MNN_DEPEND -Wl,-all_load ${MNN_DEPEND} -Wl,-noall_load)
    elseif (CMAKE_CXX_COMPILER_ID MATCHES "GNU" OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(MNN_DEPEND -Wl,--whole-archive ${MNN_DEPEND} -Wl,--no-whole-archive)
    endif()
endif()
