### ISSUE TITLE
文件丢失编译失败

### ISSUE THREAD

**Issue by Kevin369** [alibaba/MNN#573]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:不详，我用的sourcetree,看不到
# Github Version:0.2.1.7

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:Xcode
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
Build input file cannot be found: '/Users/zhaosijia/Downloads/MNN-master/test/op/PackTest.cpp' 
# Build Log:

PackTest.cpp文件丢失编译失败

![image](https://user-images.githubusercontent.com/22385493/71966792-357d0100-323d-11ea-94aa-37a51220766f.png)

```
编译MNN项目里面的Playground
PackTest.cpp文件丢失编译失败
```

**Comment by Naville** [comment]
Fixed
