### ISSUE TITLE
/v2/mobilenet_v2_1.0_224.tflite.mnn: No such file or directory

### ISSUE THREAD

**Issue by Kevin369** [alibaba/MNN#574]
版本：最新版
配置完转换工具
![image](https://user-images.githubusercontent.com/22385493/71969025-dae5a400-3240-11ea-9d8a-de403372fa87.png)

生成了model

执行完上面的步骤，然后编译出现了错误
![Uploading image.png…]()

v1.1和v2文件夹下只有.text文件

**Comment by msurguy** [comment]
use the fix in https://github.com/alibaba/MNN/pull/511/files

**Comment by Kevin369** [comment]
I try again, but the new code did not work
**
![Uploading image.png…]()

**

**Comment by Naville** [comment]
图片都上传挂了

**Comment by Kevin369** [comment]
![image](https://user-images.githubusercontent.com/22385493/72131136-5d43a480-33b6-11ea-906f-5ec012b4b2e8.png)


/Users/kevin/Downloads/MNN/resource/model/MobileNet/v2/mobilenet_v2.caffe.mnn: No such file or directory


/Users/kevin/Downloads/MNN/resource/model/MobileNet/v2/mobilenet_v2_1.0_224.tflite.mnn: No such file or directory

/Users/kevin/Downloads/MNN/resource/model/SqueezeNet/v1.1/squeezenet_v1.1.caffe.mnn: No such file or directory

**Comment by jxt1234** [comment]
Run get_model.sh firstly.
