### ISSUE TITLE
how to use DetectionPostProcess？

### ISSUE THREAD

**Issue by bylanhao** [alibaba/MNN#575]
Known Op Requirements For TensorFlow
AddN
Equal (#42 )
SparseToDense (#42 )
Ops(TensorArrayxxx) is from tensorflow Detection postprocess API, which are not necessary to support, because DetectionPostProcess is supported.

TensorArrayGatherV3 (#462)

TensorArrayGatherV3 (#462)

TensorArrayReadV3 (#462)

TensorArrayScatterV3 (#462)

TensorArraySizeV3 (#462)

TensorArrayV3 (#462)

TensorArrayWriteV3 (#462)

You said that the above operators can not  necessary to support, because DetectionPostProcess is supported. How does DetectionPostProcess work in practice? How to convert the model with these operators?
Thank you.

**Comment by czy2014hust** [comment]
[Here](https://github.com/tensorflow/models/blob/80444539849453d45fa2ecfcce7fbeb47d863897/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)
set `--add_postprocessing_op=true`

**Comment by bylanhao** [comment]
Thank you.

**Comment by yjiangling** [comment]
> [Here](https://github.com/tensorflow/models/blob/80444539849453d45fa2ecfcce7fbeb47d863897/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)
> set `--add_postprocessing_op=true`

Sorry, I'm still confused. The link is explaining how to convert TensorFlow model to TensorFlow Lite model? But how can I convert TensorFlow model to MNN model with TensorArray Op? Convert it to TensorFlow Lite and then convert it to mnn?

**Comment by 07freedom** [comment]
If there is an official tutorial for this, that would be great since this problem is so common.
