### ISSUE TITLE
How to build to create lightweight library on android?

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#581]
Hi,
I read this sentence on main. "Android platform: core so size is about 400KB, OpenCL so is about 400KB, Vulkan so is about 400KB." but as I build, the so size is 72.3mb.
I just followed a step of https://www.yuque.com/mnn/en/build_android?language=en-us 
Is there any other option to create small size library?

**Comment by jackweiwang** [comment]
https://github.com/alibaba/MNN/issues/549#issuecomment-570502759

**Comment by Naville** [comment]
Basically. Since Android NDK Toolchain explicitly adds ``-g`` which adds a ton of debug symbols, you'll have to manually strip the symbols.
Previously MNN workarounds this issue by explicitly adding ``-s`` which strips the symbol later, this results in a few issues with packaging on Android.
