### ISSUE TITLE
Ubuntu compilation problem 'MNN_REPOSITORY' was not declared in this scope

### ISSUE THREAD

**Issue by 850977164** [alibaba/MNN#584]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:0.2.1.6

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
# 编译日志:
# Build Log:
![image](https://user-images.githubusercontent.com/39330916/72494547-27436c00-385f-11ea-943b-6c55e589ce91.png)

```
粘贴在这里
Paste log here or pastebin
```

**Comment by Naville** [comment]
converter现在跟主工程一起编译

**Comment by 850977164** [comment]
@Naville 编译了MNN0.2.1.0,确没有生成MNNConvert可执行文件，编译MNN0.2.1.7生成了这个文件

**Comment by 850977164** [comment]
MNN0.2.1.0的模型转换工具如何单独编译呢

**Comment by Naville** [comment]
那我寻思你用0.2.1.7不就完了

**Comment by 850977164** [comment]
@Naville 在转换一个模型，0.2.1.7不支持，现在解决了

**Comment by rlczddl** [comment]
这个问题怎么解决的?我也遇到了.
