### ISSUE TITLE
have plan to support quant retrain?

### ISSUE THREAD

**Issue by HaoLiuHust** [alibaba/MNN#585]
As we know, quant fp32 model to int8 will decrease the performance, some commercial company provide a retrain tool to retrain the int8 model, do you have plan to support this?

**Comment by yyfcc17** [comment]
we are working on it

**Comment by yyfcc17** [comment]
in a month

**Comment by yyfcc17** [comment]
already released quantize aware training

**Comment by HaoLiuHust** [comment]
Thanks for your work, where is the demo and document?

**Comment by HaoLiuHust** [comment]
where is the demo or document to tell us how to use it?

**Comment by yyfcc17** [comment]
here: [MNN doc](https://www.yuque.com/mnn/cn/bhz5eu)
