### ISSUE TITLE
同一模型文件，同一程序，后端为cpu，在pc上跑和安卓上跑输出结果轻微不一致

### ISSUE THREAD

**Issue by xiexuliunian** [alibaba/MNN#586]
服务器pc
![image](https://user-images.githubusercontent.com/24749356/72579301-adb98580-3913-11ea-8e94-66d413bbd9ec.png)
安卓
![image](https://user-images.githubusercontent.com/24749356/72579330-c32eaf80-3913-11ea-9be8-c17b4592070e.png)

**Comment by Guanmoyu** [comment]
可以用MNNV2Basic工具看下输入的数据是不是一样的，逐层对比看看呢

**Comment by xiexuliunian** [comment]
![image](https://user-images.githubusercontent.com/24749356/72673180-cb1c5a00-3aa1-11ea-9787-6c9297c45974.png)
使用MNNV2Basic工具，按照文档上的方式，报错

**Comment by Guanmoyu** [comment]
input的维度不对。
![image](https://user-images.githubusercontent.com/38658608/72673404-efc60100-3aa4-11ea-8f7d-bc21bffef4e4.png)
不清楚你的版本，建议你看下MNNV2Basic的代码，这块使用方法更新有改过，而且说明也不太准确

**Comment by xiexuliunian** [comment]
好的，感谢。我更新下版本，非常感谢您的回复。能开源已经很好了，感谢您们辛苦的工作！！！

**Comment by Guanmoyu** [comment]
感谢阿里的大佬们！

**Comment by jxt1234** [comment]
ImageProcess 在 pc 和 安卓 的计算结果有少许不一致，一般不影响准确率
