### ISSUE TITLE
can't find ../build/MNNConvert, building converter firstly 

### ISSUE THREAD

**Issue by 850977164** [alibaba/MNN#587]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
MNN0.2.1.0

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

./tools/script/get_model.sh

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
can't find ../build/MNNConvert, building converter firstly 

```
粘贴在这里
Paste log here or pastebin
```

**Comment by 850977164** [comment]
我在编译MNN0.2.1.7版本时，build文件下MNNConvert自己生成，而MNN0.2.1.0版本并没有MNNConvert，MNN0.2.1.0版本是单独编译MNNConvert吗，是如何编译的呢

**Comment by 850977164** [comment]
MNN0.2.1.0的模型转换工具如何编译呢

**Comment by Guanmoyu** [comment]
进tools/converter，执行build_tool.sh

**Comment by liuguicen** [comment]
build_tool.sh
没有这个文件，大佬，这好麻烦呀，缺这少那的

**Comment by jxt1234** [comment]
现在 converter 直接 cmake -DMNN_BUILD_CONVERTER=true 就可以了

**Comment by fengsky401** [comment]
> build_tool.sh
> 没有这个文件，大佬，这好麻烦呀，缺这少那的

https://juejin.im/post/6844904070495354887
可以参考这个
感觉官方可以把这个放到readme。。。
