### ISSUE TITLE
MNN 量化 mergeChannel疑问

### ISSUE THREAD

**Issue by Guanmoyu** [alibaba/MNN#588]
# 平台(如果交叉编译请再附上交叉编译目标平台):  全平台
# Github版本: 0.2.1.7
1、mergeChannel似乎并没有作用
[https://github.com/alibaba/MNN/blob/0.2.1.0/tools/quantization/quantizeWeight.cpp#L149](url)
此处针对mergeChannel做了处理，而在调用的时候取了默认值True，在调用处 [https://github.com/alibaba/MNN/blob/0.2.1.0/tools/quantization/calibration.cpp#L410](url)
强行设为false发现，两个分支的结果完全一致，进一步跟踪发现，由于TensorStatistic::mMergeChannel [https://github.com/alibaba/MNN/blob/0.2.1.0/tools/quantization/TensorStatistic.hpp#L57](url)默认为True，代码中也没有进行处理，两个分支实际上都是做了
scale[i] = inputScale[0] * quantizedWeightScale[i] / outputScale[0];
请问这一部分代码是怎么考虑的呢？
我尝试将TensorStatistic::mMergeChannel设置为false，调用是也将mergeChannel=false，但是似乎性能并不好。
2、请问scale[i] = inputScalexWeight * quantizedWeightScale[i] / outputScale[0]这步计算是为了在int8推理时省去requant的过程吗？有相应的介绍吗，跟TensorRT、ncnn相比有什么优势吗？性能怎么样呢？

**Comment by czy2014hust** [comment]
1. mergeChannel目前强制设为true，这是测试不同模式下量化精度
2. 这里的scale不是tensor的scale，是input和weight合并计算的scale
