### ISSUE TITLE
MNN中LSTM相关疑问(bug)

### ISSUE THREAD

**Issue by hset911** [alibaba/MNN#589]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
X86平台 ubuntu16.04

# Github版本:
0.2.1.7

# 编译方式:
x86原生编译

# 所遇问题
**1.转换模型时失败，不识别LSTM的type**
        (1).转换工具提示不支持LSTM的type.
     ### 尝试解决办法：源码中字符串匹配不对，将prototxt中的type:LSTM改为Lstm可读。（对标准caffe支持不完善）
**2.转换模型后所读取LSTM的参数不对**
         (1).lstm层的num_output参数未读取正确.
     ### 尝试解决办法：源码中读取参数的地方顺序2与3相反，临时更改后，输出shape正确。（临时办法）
**3.运行后与预期值不一致**
     ### 无解决办法

**模型**
[https://pan.baidu.com/s/17w8yQ6V_4sj0O2WHOGkdXA](url)
说明：模型文件和input数据文件，另外一个input为【0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1】描述序列

**python上caffe运行代码：**
```
import os
import caffe 
import numpy as np 
deploy='caffe/plate_rec_deploy_cut.prototxt'    #deploy文件 
caffe_model='caffe/licenserecognmodel.caffemodel'  #caffemodel 
import cv2
import os

def Test():
    net = caffe.Net(deploy,caffe_model,caffe.TEST)   
    data_txt = np.loadtxt('caffe/input.txt')

    data_txt=np.reshape(data_txt,(16,1,512))
    data_cont=np.array([0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
    data_cont=np.reshape(data_cont,(16,1))

    net.blobs['data'].data[...] = data_txt
    net.blobs['indicator'].data[...] = data_cont

    #执行测试 
    out = net.forward() 
    fcout= net.blobs['lstm1'].data.flatten()
    print(fcout)
    #取出最后一层并打印
Test()
```

**Comment by hset911** [comment]
mnn现在lstm实现参考的什么工程啊，有bug也不解了？

**Comment by czy2014hust** [comment]
- 针对读取参数不对的可以贴下错误log，不建议修改代码
- 目前LSTM不支持输入状态，也就是初始状态为0

**Comment by lddsjy** [comment]
同样的问题，形状和运行结果都不正确。请问楼主发现运行结果错误是什么原因了么
