### ISSUE TITLE
编译convert是出错，tensorflow1.10， anaconda3 3.6

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#59]
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned long, void (*)(void*))'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::Add(float const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::InternalSwap(google::protobuf::RepeatedField<long>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::Add(unsigned long const&)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::~RepeatedField()'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::RepeatedField(google::protobuf::RepeatedField<unsigned long> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::RepeatedField(google::protobuf::RepeatedField<bool> const&)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::InternalSwap(google::protobuf::RepeatedField<unsigned int>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::DecrementRecursionDepthAndPopLimit(int)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormatLite::UInt32Size(google::protobuf::RepeatedField<unsigned int> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::~RepeatedField()'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Get(int) const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::VerifyUtf8String(char const*, int, google::protobuf::internal::WireFormatLite::Operation, char const*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Add()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::RepeatedField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloatArray(float const*, int, google::protobuf::io::CodedOutputStream*)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::MapFieldBase::SyncRepeatedFieldWithMapNoLock() const'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::AddAlreadyReserved(unsigned int const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::mutable_data()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::AddAlreadyReserved(int const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::Add(double const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint64Fallback()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBoolArray(bool const*, int, google::protobuf::io::CodedOutputStream*)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::UnknownFieldSet::default_instance()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::Clear()'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::MergeFrom(google::protobuf::RepeatedField<unsigned long> const&)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::internal::WireFormat::ReadPackedEnumPreserveUnknowns(google::protobuf::io::CodedInputStream*, unsigned int, bool (*)(int), google::protobuf::UnknownFieldSet*, google::protobuf::RepeatedField<int>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::IncrementRecursionDepthAndPushLimit(int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::Int64Size(google::protobuf::RepeatedField<long> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::data() const'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::InternalSwap(google::protobuf::RepeatedField<unsigned long>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::AddAlreadyReserved(float const&)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `vtable for google::protobuf::internal::MapFieldBase'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::DestroyMessage(void const*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::RepeatedField<int> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::InternalSwap(google::protobuf::RepeatedField<float>*)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::MergeFrom(google::protobuf::RepeatedField<unsigned int> const&)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::internal::WireFormatLite::UInt64Size(google::protobuf::RepeatedField<unsigned long> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::Int32Size(google::protobuf::RepeatedField<int> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::data() const'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::AddAlreadyReserved(unsigned long const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::RepeatedField()'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::~RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::begin() const'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::mutable_data()'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::RepeatedField(google::protobuf::RepeatedField<long> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::Truncate(int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::Add(int const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarint32Fallback(unsigned int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::RepeatedField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint64SlowPath(unsigned long)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::MergeFrom(google::protobuf::RepeatedField<bool> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::Add(long const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::MapFieldBase::SetMapDirty()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::AddAlreadyReserved(bool const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedOutputStream::WriteVarint32SlowPath(unsigned int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::end() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::RepeatedField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::~RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::MergeFrom(google::protobuf::RepeatedField<double> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `typeinfo for google::protobuf::internal::MapFieldBase'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::Clear()'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::internal::DestroyString(void const*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::fixed_address_empty_string[abi:cxx11]'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::Message::SpaceUsedLong() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::SkipFallback(int, int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::InternalSwap(google::protobuf::RepeatedField<double>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::RepeatedField(google::protobuf::RepeatedField<float> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::Add(bool const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::Arena::OnArenaAllocation(std::type_info const*, unsigned long) const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::Resize(int, double const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::GetOwnedMessageInternal(google::protobuf::Arena*, google::protobuf::MessageLite*, google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::InternalSwap(google::protobuf::RepeatedField<bool>*)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::MergeFrom(google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned long)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::unsafe_data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteDoubleArray(double const*, int, google::protobuf::io::CodedOutputStream*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::AddAlreadyReserved(long const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::MergeFrom(google::protobuf::RepeatedField<long> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::RepeatedField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::AddAlreadyReserved(double const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::MapFieldBase::~MapFieldBase()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::MergeFrom(google::protobuf::RepeatedField<float> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::RepeatedPtrField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::Arena*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadVarintSizeAsIntFallback()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::InternalSwap(google::protobuf::RepeatedField<int>*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::~RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::~RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::ReadTagFallback(unsigned int)'
source/onnx/libonnx.so: undefined reference to `google::protobuf::RepeatedField<unsigned long>::Clear()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<bool>::data() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::OnShutdownRun(void (*)(void const*), void const*)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::Truncate(int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::~RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::InternalExtend(int)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<double>::RepeatedField(google::protobuf::RepeatedField<double> const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::Capacity() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<float>::Resize(int, float const&)'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<int>::unsafe_data() const'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::Add(unsigned int const&)'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField()'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedPtrField<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::~RepeatedPtrField()'
source/caffe/libcaffe.so: undefined reference to `google::protobuf::RepeatedField<unsigned int>::size() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::internal::MapFieldBase::SpaceUsedExcludingSelfNoLock() const'
source/tensorflow/libtensorflow.so: undefined reference to `google::protobuf::RepeatedField<long>::size() const'
collect2: error: ld returned 1 exit status
CMakeFiles/MNNConvert.dir/build.make:154: recipe for target 'MNNConvert' failed
make[2]: *** [MNNConvert] Error 1
CMakeFiles/Makefile2:147: recipe for target 'CMakeFiles/MNNConvert.dir/all' failed
make[1]: *** [CMakeFiles/MNNConvert.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by li-qing** [comment]
are you sure that your protobuf version ≥ 3？

**Comment by ChisenZhang** [comment]
3.7.1  不是3.x  会报其他错  编译主程序没问题，编译转换工具到最后一步嘣这个错误

**Comment by czy2014hust** [comment]
Maybe there are more than two version of protobuf，delete，reinstall(search this problem with key word caffe)

**Comment by ChisenZhang** [comment]
> Maybe there are more than two version of protobuf，delete，reinstall(search this problem with key word caffe)
> […](#)
> Sent from my iPhone
> On May 13, 2019, at 8:51 PM, Chisen ***@***.***> wrote: 3.7.1 不是3.x 会报其他错 编译主程序没问题，编译转换工具到最后一步嘣这个错误 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的  我试一下，谢谢

**Comment by ChisenZhang** [comment]
> Maybe there are more than two version of protobuf，delete，reinstall(search this problem with key word caffe)
> […](#)
> Sent from my iPhone
> On May 13, 2019, at 8:51 PM, Chisen ***@***.***> wrote: 3.7.1 不是3.x 会报其他错 编译主程序没问题，编译转换工具到最后一步嘣这个错误 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

果然是这个问题，解决了  卸载了conda安装的protobuf  和系统安装的libprotobuf-dev，自己编译的也重新卸载重新install一次就编译成功了。  谢谢

**Comment by ChisenZhang** [comment]
solved. because multi version of protobuf
