### ISSUE TITLE
build_wheel.py failed with ld error

### ISSUE THREAD

**Issue by nullptr-leo** [alibaba/MNN#590]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 19.10

# Github版本:
# Github Version:
ed8b9f2a238cb9038293ddb421068e3e5be81d55

# 编译方式:
# Compiling Method

```
cd pymnn/pip_package
python3 build_wheel.py
```

# 编译日志:
# Build Log:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libprotobuf.a(bytestream.o): relocation R_X86_64_PC32 against symbol `_ZTVN6google8protobuf7strings20GrowingArrayByteSinkE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

**Comment by stanleywang8888** [comment]
protobuf重新自己源代码编译安装带fpic选项就行了

**Comment by nullptr-leo** [comment]
> protobuf重新自己源代码编译安装带fpic选项就行了

Thanks，已经OK了

**Comment by Daniel-Kelvich** [comment]
@nullptr-leo can you please share how to fix the issue? Have protobuf recompilation helped?

**Comment by aslily1234** [comment]
> protobuf重新自己源代码编译安装带fpic选项就行了

非常感谢！

踩坑记录如下：
`sudo apt-get install autoconf automake libtool curl make g++ unzip
git clone https://github.com/google/protobuf.git
// 指定分支clone
//git clone -b 3.9.x https://github.com/google/protobuf.git     // 3.9.x为指定分支

cd protobuf
git submodule update --init --recursive                    
./autogen.sh

//./configure  使用-fPIC选项编译出protobuf静态库libprotobuf.a
./configure CFLAGS="-fPIC" CXXFLAGS="-fPIC"
make
make check
sudo make install
sudo ldconfig # refresh shared library cache`

**Comment by mm-e1** [comment]
I was able to get this working on a Raspberry Pi 4, using the method provided by @aslily1234.

Do not install `libprotobuf-dev`. Instead, compile protobuf using the below instructions, and then attempt to generate the wheel file using the instructions included in this repo.

```
git clone https://github.com/google/protobuf.git $PB_MAIN_DIR --branch $PB_VERSION --single-branch && \
  cd $PB_MAIN_DIR && \
  git submodule update --init --recursive && \
  ./autogen.sh && \
  ./configure CFLAGS="-fPIC" CXXFLAGS="-fPIC" && \
  make -j8 && \
  make check && \
  make install && \
  ldconfig
```
