### ISSUE TITLE
如何多线程使用MNN？

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#592]
如题，最近想在服务器部署上使用MNN来做推断。

主要是下面的场景：一个算法(如物体识别)在云端的接口，客户端捕获相机图片并发送给云端进行计算，每次客户端调用的时候，服务器都会新启一个线程来完成计算，再返回结果，比较理想的状态是，同一个interpreter、session、process可以完成所有线程的计算。

主要的问题是，上述场景实测会crash或者结果不对，仔细分析后发现，MNN::Interpreter本身不支持多线程的操作(只考虑无锁情况)，因为getSessionInput和getSessionOutput都会修改Interpreter的成员变量mNet，进而导致线程冲突。

请问在不改MNN源码的前提下有没有可能无锁地使用多线程调MNN完成计算呢？

问题比较复杂，感谢您的耐心和建议！

**Comment by jxt1234** [comment]
Interpreter 支持线程间共享，但在调 createSession 、getSessionInput getSessionOutput 等方法时需要上锁。

session  不支持线程间共享，每个线程需要各自 create session 并进行计算

建议建一个线程池，线程池中每个线程各自创建一个 session
