### ISSUE TITLE
Convert onnx to mnn: Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by mingliangfu** [alibaba/MNN#596]
Ubuntu18.04
./schema/generate.sh
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
protobuf3.0, gcc-7.4
MNN-master(2020-01-22)

Start to Convert Other Model Format To MNN Model...
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 85 has empty input, the index is 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 129 has empty input, the index is 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 162 has empty input, the index is 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 188 has empty input, the index is 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 219 has empty input, the index is 4
[23:03:30] /home/**/MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 258 has empty input, the index is 4
Start to Optimize the MNN Net...
Segmentation fault (core dumped)

**Comment by LeoCloser** [comment]
I have the same issue when i use 4k and 1080p images/videos with OPENCL=ON.

**Comment by mingliangfu** [comment]
More build info:
xxx@DESKTOP-4HEARFG:~/MNN/build$ cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
CMake Warning (dev) at 3rd_party/flatbuffers/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
    PROJECT_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.

fatal: No annotated tags can describe 'ed8b9f2a238cb9038293ddb421068e3e5be81d55'.
However, there were unannotated tags: try --tags.
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: x86_64
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      OpenMP: OFF
--      Hidden: TRUE
--      Build Path: /home/xxx/MNN/build
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/MNN/build
[  1%] Built target MNN_SCHEMA_GEN
[  1%] Built target MNNSSE
[  2%] Built target MNNAVX
[  2%] Built target GenVCSHDR
[  5%] Built target MNNCompute
[  6%] Built target MNNCV
[  7%] Built target MNNMath
[ 27%] Built target MNNCPU
[ 30%] Built target MNNX8664
[ 32%] Built target MNNCore
[ 45%] Built target MNNShape
[ 51%] Built target MNNConverterTFL
[ 58%] Built target MNNConverterMNN
[ 58%] Built target MNNConverterONNX
[ 74%] Built target MNNConverterTF
[ 82%] Built target MNNConverterCaffe
[ 82%] Built target MNNDump2Json
[ 84%] Built target MNN
[ 93%] Built target MNNConverterOpt
[ 94%] Built target MNN_Express
[ 95%] Built target timeProfile.out
[ 96%] Built target checkInvalidValue.out
[ 97%] Built target getPerformance.out
[ 98%] Built target testModelWithDescrisbe.out
[ 98%] Built target mobilenetTest.out
[ 98%] Built target backendTest.out
[ 98%] Built target testModel.out
[ 98%] Built target MNNV2Basic.out
[ 98%] Built target MNNConvertDeps
[100%] Built target MNNConvert

**Comment by mingliangfu** [comment]
debug update: MNN converter break off in https://github.com/alibaba/MNN/blob/ed8b9f2a238cb9038293ddb421068e3e5be81d55/tools/converter/source/optimizer/PostConverter.cpp#L113

More detailed pos is in 
https://github.com/alibaba/MNN/blob/ed8b9f2a238cb9038293ddb421068e3e5be81d55/tools/converter/source/optimizer/TemplateMerge.cpp#L21. That's to say, the converter find too many nullptr in the onnx file or intermediate model so that it cannot go to next lines.

**Comment by mingliangfu** [comment]
The onnx file which can reproduce the issue will be attached one or two days later. Any tips will be appreciated.

**Comment by mingliangfu** [comment]
The onnx file which can reproduce segmentation fault can be downloaded [here ](https://pan.baidu.com/s/1ootNp7bfoS7TlvEtSSYhhg) (with a PW: 2e3w).

**Comment by mingliangfu** [comment]
Other outputs of LSTM are used.

**Comment by un-knight** [comment]
@mingliangfu I got the same problem with you, how did you fix the lstm converter core dump?

**Comment by mingliangfu** [comment]
Wait for the next release or just avoid using other ouputs of LSTM directly in my case.

**Comment by mingliangfu** [comment]
> @mingliangfu I got the same problem with you, how did you fix the lstm converter core dump?

Wait for the next release or just avoid using other ouputs of LSTM directly in my case.

**Comment by un-knight** [comment]
> > @mingliangfu I got the same problem with you, how did you fix the lstm converter core dump?
> 
> Wait for the next release or just avoid using other ouputs of LSTM directly in my case.

I changed the LSTM from sequence_first to batch_first, then made the conversion succeeded.
