### ISSUE TITLE
Please help! Unable to convert TFlite model to MNN

### ISSUE THREAD

**Issue by cqx820** [alibaba/MNN#598]
Ubuntu 16.04, x86_64
gcc-5.4, protobuf-3.5.1
MNN-master (2020-01-22)
```
./schema/generate.sh
cmake -DMNN_BUILD_CONVERTER=ON .. && make -j`nproc`
```
`./MNNConvert -f TFLITE --modelFile xxx.tflite --MNNModel xxx.mnn --bizCode MNN`

```
MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [21:21:41] /root/MNN/tools/converter/source/tflite/ReductionTflite.cpp:64: MNN Converter Not Supported!!! Reduction Op: 
Aborted (core dumped)
```
![dbcp tflite](https://user-images.githubusercontent.com/11491470/73025194-5d976300-3dec-11ea-9919-5fa910e003d4.png)

I have visualized the whole network and posted the graph here. Sorry for the large picture. It seems like every op in the graph is supported, but I could still unable to convert to MNN model. Please help.

**Comment by jxt1234** [comment]
You can merge the commit of https://github.com/alibaba/MNN/pull/599 ..
