### ISSUE TITLE
运行MNNConvert时出现错误

### ISSUE THREAD

**Issue by fidmail** [alibaba/MNN#6]
OS:Centos 7
GCC:4.8,4.9,5.3
各个GCC版本都能成功编译MNNConvert,但是运行的时候出现提示：
terminate called after throwing an instance of 'std::regex_error'
whar(): regex_error

直接运行:./MNNConvert 或 ./MNNConvert -version 都出现上面的错误。

**Comment by fidmail** [comment]
执行./MNNConvert时，还没进入main()就出现这个错误提示.

**Comment by czy2014hust** [comment]
GCC >= 4.9

**Comment by fidmail** [comment]
GCC4.9和5.3都试了。

**Comment by fidmail** [comment]
[root@localhost build]# gcc --version

gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)

Copyright (C) 2014 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



[root@localhost build]# ./MNNConvert -version

terminate called after throwing an instance of 'std::regex_error'

  what():  regex_error

**Comment by fidmail** [comment]
解决了，我重新./generate_schema.sh和cmake了。之前是升级gcc后只make.谢谢！

**Comment by quliulangle** [comment]
> 解决了，我重新./generate_schema.sh和cmake了。之前是升级gcc后只make.谢谢！

我也遇到了这个问题  centos7   gcc 4.9.3  cmake 3.12.0  protoc 3.4.0     
MNN-0.2.0.5的版本  可以编译成功   运行的时候就报
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

按照你说的方法也没有解决

**Comment by southsea0725** [comment]
需要将g++的版本也升到4.9以上！！！仅升级gcc的不够。
