### ISSUE TITLE
Error for /ruhuan/Projects/AliNNPrivate/source/backend/cpu/CPUBackend.cpp, 280

### ISSUE THREAD

**Issue by kunalgoyal9** [alibaba/MNN#600]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04 (x86)

# 编译方式:
# Compiling Method
I downloaded compiled version through pip and converted [Tf lite](https://www.tensorflow.org/lite/guide/hosted_models) models through MNNCONVERT. But while running mobilenet_demo.py I am getting above error :(

**Comment by Echosanmao** [comment]
hello，I have encounted this problem，Have you resolved it?
