### ISSUE TITLE
How to provide inference time of each layer?

### ISSUE THREAD

**Issue by lixincn2015** [alibaba/MNN#601]
I've read all the documents and the benchmark.cpp, it seems that MNN can not provide detailed profiling information currently. 

Can MNN provide inference time of each layer?
If yes, is there any demo or documentation?

Thank you.

**Comment by jxt1234** [comment]
You can refer to https://www.yuque.com/mnn/en/tool_test .

MNNV2Basic.out  will print inference time of each layer. You can see the detail code of tools/cpp/MNNV2Basic.cpp

**Comment by zjd1988** [comment]
@jxt1234 你好，MNNV2Basic支持输出opencl后端每层的时间打印吗，我看了下0.2.17的代码，发现在把每层kernel放入队列里之后没有等待完成的动作，不知道是不是我看漏了。
