### ISSUE TITLE
Crash occurred when use vulkan on android.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#602]
Hi,
I added libMNN.so and libMNN_Vulkan.so then changed forward type to MNN_FORWARD_VULKAN but the app was terminated.
I'd like to attach crash dump but there is only one line log. 
"Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 2092."
Is there any option to use vulkan on android?
I changed min sdk version to 26 but it was same.

Also I added libMNN_GL.so, no crash but no result.
If forward type is MNN_FORWARD_CPU, everything is ok.
Please let me know how get hardware acceleration.

**Comment by jxt1234** [comment]
Do you compile vulkan by the source code?  The so in android's demo is not updated.

**Comment by GHLab** [comment]
@jxt1234 Yes, I compiled by cmake with MNN_VULKAN option.

**Comment by jxt1234** [comment]
What's your model and mobile?
You can use backendTest.out to check the backend result.

**Comment by GHLab** [comment]
@jxt1234 I tested https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN on android device. (samsung galaxy s9)

**Comment by kafan1986** [comment]
> @jxt1234 I tested https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN on android device. (samsung galaxy s9)

Can you share the latest .so files for android for armeabi-v7a and arm64-v8a? I don't currently have the setup to build these libraries from latest code.

**Comment by Naville** [comment]
@kafan1986 Yes. They are in `Releases` page if you ever bothered checking

**Comment by kafan1986** [comment]
> @kafan1986 Yes. They are in `Releases` page if you ever bothered checking
Thanks I missed it. Also, I tested the MTCNN face detection using Vulcan and after giving correct result for the first few times. The model starts to give incorrect results and finally crashes.

**Comment by jxt1234** [comment]
I test the model and found it has been fixed
