### ISSUE TITLE
Can't make static library on macos.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#605]
Hi,
I'd like to make static library .a instead of 'dylib' so I set OFF of MNN_BUILD_SHARED_LIBS on CMakeLists.txt but only dylib exists.
Did I do wrong?

**Comment by GHLab** [comment]
I checked cmake/macros.cmake. According to that file, the file name always seems to be dylib on macos. I think the file will be changed 'a' or 'dylib' depends on MNN_BUILD_SHARED_LIBS value.
Can you check it?

**Comment by jxt1234** [comment]
make static library should also set MNN_SEP_BUILD = OFF

**Comment by GHLab** [comment]
@jxt1234 Thank you for your quick reply. I got static library.
