### ISSUE TITLE
tflite to mnn error

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#608]
Hi,
I'd like to convert something tflite model to mnn but error was occurred like below.

Start to Convert Other Model Format To MNN Model...
libc++abi.dylib: terminating with uncaught exception of type Error: [11:59:56] /Users/ghlab/Dev/git/MNN/tools/converter/source/tflite/BroadCastAdd.cpp:61: Check failed: addOption->fused_activation_function == tflite::ActivationFunctionType_NONE ==> BinaryOP Should not has fused_activation_function
Abort trap: 6

Can you check this error?
Thank you.

**Comment by jxt1234** [comment]
Currently don't support binary will activation. You can convert from pb instead

**Comment by 2meeltd** [comment]
Can you make the comment more clear. Thank you.

**Comment by jxt1234** [comment]
activation of tflite's binary has been supported
