### ISSUE TITLE
Segmentation fault: 11 when converting pb to mnn

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#609]
Hi,
I'd like to convert pb to mnn but Segmentation fault: 11 error was occurred.
Can you check this?
You can download the pb file here https://github.com/PINTO0309/TensorflowLite-UNet/blob/master/model/semanticsegmentation_frozen_person_08.pb
Thank you.

**Comment by jxt1234** [comment]
Please update the code. Fixed.

**Comment by GHLab** [comment]
@jxt1234 Thank you. I resolved the converting.
