### ISSUE TITLE
OpenGLES backend

### ISSUE THREAD

**Issue by pure-water** [alibaba/MNN#610]
I saw there are code of opengl es as the backend. What is the roadmap for this backend for MNN framework?

**Comment by jxt1234** [comment]
MNN focus on CPU(x86+ARMv7a+ARMv8.1) , ARMv8.2, Vulkan , OpenCL.
For opengl es will not add any ops or do optimize. But in future we will introduce a new mechanism to make every backend easily to support a lot of ops.
