### ISSUE TITLE
【Cocoapods】重复编译汇编文件

### ISSUE THREAD

**Issue by lldong** [alibaba/MNN#612]
arm32 和 arm64 目录中汇编文件名称相同（内容不同），目录结构如下:
```
├── source
│   ├── backend
│   │   ├── cpu
│   │   │   ├── arm
│   │   │   │   ├── arm32
|   |   |   |   |   ├── MNMNNAddBias.S
│   │   │   │   └── arm64
|   |   |   |   |   ├── MNMNNAddBias.S
```

对应的 podspec 内容如下:

```
  s.source_files = \
  'source/backend/cpu/*.{h,c,m,mm,cc,S,hpp,cpp}',\
  'source/backend/cpu/arm/**/*.{h,c,m,mm,cc,S,hpp,cpp}'
```

执行 pod install 后只有 arm64 目录下的文件被加入编译，而且被加入两次，结果是符号冲突，预期结果是这两个文件分别来自 arm32 和 arm64。这是 Cocoapods  的已知 [bug](https://github.com/CocoaPods/CocoaPods/issues/8289) ，临时解决办法是将 arm32 和 arm64 的代码分别抽离到独立的 subspec。

**Comment by Naville** [comment]
如果没记错的话现在的podspec是下载集成预编译好的MNN

**Comment by lldong** [comment]
@Naville 至少目前根目录中 MNN.podspec 是有问题的
