### ISSUE TITLE
mnn进行网络推理时算子不支持>=5维的输入

### ISSUE THREAD

**Issue by sweezin** [alibaba/MNN#614]
- 平台(如果交叉编译请再附上交叉编译目标平台):  
win10+vs2015 x64  

- Github版本:
0.2.1.5

- 编译方式:
cmake -G "Visual Studio 14 2015 Win64"  -DMNN_BUILD_DEMO=ON -DMNN_BUILD_QUANTOOLS=ON -DMNN_BUILD_CONVERTER=ON ..
cmake --build . --config Release

```
引用编译生成的mnn动态库，将TensorFlow模型文件转成mnn模型后，调用createSession函数即出现以下错误：
“Error for StridedSliceComputer: inputDimension>=5: 5”
“Resize error for pred_mbbox/strided_slice_4, code=3”
经确认是mnn不支持5维的stridedslice输入，麻烦fix下，谢谢。

**Comment by ZSharp7** [comment]
请问这有其它解决方法吗

**Comment by sweezin** [comment]
@ZSharp7 已经在代码重构当中，重构后就可以解决这个问题了，敬请期待。。。

**Comment by MonicaChen426** [comment]
该问题何时可以解决？

**Comment by jxt1234** [comment]
fixed
