### ISSUE TITLE
Segmentation fault: 模型量化

### ISSUE THREAD

**Issue by changshuai5** [alibaba/MNN#615]
模型量化时，参数选择如下："feature_quantize_method":"ADMM"， "weight_quantize_method":"MAX_ABS"，报错：Segmentation fault  。

**Comment by jxt1234** [comment]
feature_quantize_method  选择 ADMM 时，不支持特别多的图片
建议 feature_quantize_method 用 KL
weight_quantize_method 用 ADMM
