### ISSUE TITLE
Error in building  converter on raspberry

### ISSUE THREAD

**Issue by yousefabohend** [alibaba/MNN#617]
I have errors when i try to build the converter raspberry pi 3 B+ with raspbian buster lite.
That what go out in terminal : [ 26%] Built target MNNCompute   make: *** [Makefile:130: all] Error 2
And that what in the CmakeError :
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/pi/MNN/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_52dfd/fast"
/usr/bin/make -f CMakeFiles/cmTC_52dfd.dir/build.make CMakeFiles/cmTC_52dfd.dir/build
make[1]: Entering directory '/home/pi/MNN/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_52dfd.dir/CheckSymbolExists.c.o
/usr/bin/cc   -O3    -o CMakeFiles/cmTC_52dfd.dir/CheckSymbolExists.c.o   -c /home/pi/MNN/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_52dfd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_52dfd.dir/link.txt --verbose=1
/usr/bin/cc  -O3     -rdynamic CMakeFiles/cmTC_52dfd.dir/CheckSymbolExists.c.o  -o cmTC_52dfd 
/usr/bin/ld: CMakeFiles/cmTC_52dfd.dir/CheckSymbolExists.c.o: in function `main':
CheckSymbolExists.c:(.text.startup+0xc): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_52dfd.dir/build.make:87: cmTC_52dfd] Error 1
make[1]: Leaving directory '/home/pi/MNN/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_52dfd/fast] Error 2

File /home/pi/MNN/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/pi/MNN/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dc3a5/fast"
/usr/bin/make -f CMakeFiles/cmTC_dc3a5.dir/build.make CMakeFiles/cmTC_dc3a5.dir/build
make[1]: Entering directory '/home/pi/MNN/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_dc3a5.dir/CheckFunctionExists.c.o
/usr/bin/cc   -O3 -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_dc3a5.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.13/Modules/CheckFunctionExists.c
Linking C executable cmTC_dc3a5
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_dc3a5.dir/link.txt --verbose=1
/usr/bin/cc  -O3 -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_dc3a5.dir/CheckFunctionExists.c.o  -o cmTC_dc3a5 -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_dc3a5.dir/build.make:87: cmTC_dc3a5] Error 1
make[1]: Leaving directory '/home/pi/MNN/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_dc3a5/fast] Error 2

**Comment by Jzz24** [comment]
solved?

**Comment by yousefabohend** [comment]
No

**Comment by jxt1234** [comment]
It seem like don't link pthread. You can update the code and build again
