### ISSUE TITLE
How can add mnn.metalib

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#618]
Hi,
I made test.framework which has libMNN.a for macOS.
But when main program was initialized, log console shows below message.
Can't load mnn.metallib
Can't Find type=1 backend, use 0 instead
And main program was freezing.
So I added mnn.metalib to 'copy bundle resources' of 'Build Phases' but it shows same log.
It's just framework so can't add main bundle I think.
How can I add mnn.metalib and use it?

**Comment by GHLab** [comment]
Well, I resolved that issue but crash was occurred.
"failed assertion `Requested storage mode is not allowed for Heaps.'"
As I think the crash was thrown below codes.
`MTLHeapDescriptor *shared = [[MTLHeapDescriptor alloc] init];
            shared.storageMode        = MTLStorageModeShared;
            shared.size               = 0x1000; // initial size
            _sharedHeap               = [_device newHeapWithDescriptor:shared];`
I'm using osx 10.14.6 (mojave).
Can you check this?

**Comment by GHLab** [comment]
I checked MACOS can pass the '@available(iOS 11.0, *))' condition so I added '#if TARGET_OS_IOS' on '@available(iOS~' so upper assertion problem has been resolved but the other error message was occurred.
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(144) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
Hard to use metal...
Please check using metal on OSX.

**Comment by jxt1234** [comment]
metal for Mac OS is not support currently. Metal is only for IOS.
For Mac OS you can use opencl instead.
