### ISSUE TITLE
Android 静态库编译

### ISSUE THREAD

**Issue by WenguoLi** [alibaba/MNN#619]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

Ubuntu 16.04上交叉编译Android 静态库

# Github版本:
# Github Version:
0.2.1.7

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

先修改CMakelist.txt中
option(MNN_BUILD_SHARED_LIBS "MNN build shared or static lib" OFF)

然后使用 project/android/build_32.sh 编译.

```
#!/bin/bash
cmake ../../../ \
-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_ABI="armeabi-v7a" \
-DANDROID_STL=c++_static \
-DCMAKE_BUILD_TYPE=Release \
-DANDROID_NATIVE_API_LEVEL=android-21  \
-DANDROID_TOOLCHAIN=clang \
-DMNN_BUILD_FOR_ANDROID_COMMAND=true \
-DNATIVE_LIBRARY_OUTPUT=. -DNATIVE_INCLUDE_OUTPUT=. $1 $2 $3

make -j4
```

# 编译日志:
# Build Log:

```
[ 90%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeUnravelIndex.cpp.o
[ 91%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeWhere.cpp.o
[ 91%] Built target MNNShape
Scanning dependencies of target MNN
[ 91%] Building CXX object CMakeFiles/MNN.dir/cmake/dummy.cpp.o
[ 91%] Linking CXX shared library libMNN.so
[ 91%] Built target MNN
Scanning dependencies of target MNN_Express
[ 91%] Building CXX object express/CMakeFiles/MNN_Express.dir/Executor.cpp.o
[ 91%] Building CXX object express/CMakeFiles/MNN_Express.dir/Expr.cpp.o
[ 91%] Building CXX object express/CMakeFiles/MNN_Express.dir/MathOp.cpp.o
[ 92%] Building CXX object express/CMakeFiles/MNN_Express.dir/MergeOptimizer.cpp.o
[ 92%] Building CXX object express/CMakeFiles/MNN_Express.dir/NeuralNetWorkOp.cpp.o
[ 92%] Building CXX object express/CMakeFiles/MNN_Express.dir/Optimizer.cpp.o
[ 93%] Building CXX object express/CMakeFiles/MNN_Express.dir/Utils.cpp.o
[ 93%] Linking CXX shared library ../libMNN_Express.so
[ 93%] Built target MNN_Express
Scanning dependencies of target testModel.out
```
编译的结果,只产生了.so的库, 并没有.a的库,
以前的版本好像是可以编译出.a的静态库, 我pull了最新的代码之后就不可以了.

BRs

**Comment by jxt1234** [comment]
../build_32.sh -DMNN_SEP_BUILD=false -DMNN_BUILD_SHARED_LIBS=false

**Comment by WenguoLi** [comment]
Thanks, I got it.
