### ISSUE TITLE
build demo on linux failed.

### ISSUE THREAD

**Issue by wangzilu** [alibaba/MNN#62]
Hello, I tried to build the demo on linux by using following instructions,
cd path/to/MNN
mkdir build
cmake -DMNN_FREEIMAGE_VALID=ON ..
make -j8

but failed,
/home/ian/Downloads/face_pro/MNN-master/demo/exec/multiPose.cpp: In function ‘int main(int, char**)’:
/home/ian/Downloads/face_pro/MNN-master/demo/exec/multiPose.cpp:327:19: error: ‘shared_ptr’ is not a member of ‘std’
     auto mnnNet = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFro
                   ^
/home/ian/Downloads/face_pro/MNN-master/demo/exec/multiPose.cpp:327:51: error: expected primary-expression before ‘>’ token
     auto mnnNet = std::shared_ptr<MNN::Interpreter>(MNN::Interpreter::createFro
                                                   ^
/home/ian/Downloads/face_pro/MNN-master/demo/exec/multiPose.cpp:351:25: error: ‘shared_ptr’ is not a member of ‘std’
         auto pretreat = std::shared_ptr<CV::ImageProcess>(CV::ImageProcess::cre
                         ^
/home/ian/Downloads/face_pro/MNN-master/demo/exec/multiPose.cpp:351:57: error: expected primary-expression before ‘>’ token
         auto pretreat = std::shared_ptr<CV::ImageProcess>(CV::ImageProcess::cre
                                                         ^
demo/exec/CMakeFiles/multiPose.out.dir/build.make:62: recipe for target 'demo/exec/CMakeFiles/multiPose.out.dir/multiPose.cpp.o' failed
make[2]: *** [demo/exec/CMakeFiles/multiPose.out.dir/multiPose.cpp.o] Error 1
CMakeFiles/Makefile2:237: recipe for target 'demo/exec/CMakeFiles/multiPose.out.dir/all' failed
make[1]: *** [demo/exec/CMakeFiles/multiPose.out.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jxt1234** [comment]
Please update gcc to 4.9 +

**Comment by wangzilu** [comment]
@jxt1234 my gcc version is 5.4. 
add #include <memory> and the error fixed.

**Comment by wangzilu** [comment]
#include<memory>

**Comment by wangzilu** [comment]
memory
