### ISSUE TITLE
如何统计MNN上Memory的使用情况？

### ISSUE THREAD

**Issue by WenguoLi** [alibaba/MNN#621]
Hi，

以Android  64位为例， 做一次inference, 使用多少的memory ， 我该怎么统计？

BRs

**Comment by zjd1988** [comment]
可以使用Android studio profile功能，看下使用MNN和不使用MNN前后的内存变化，大概估算一下。

**Comment by jxt1234** [comment]
使用 CPU 推理可以在 source/backend/cpu/CPUBackend.cpp 中打开 MNN_DUMP_MEMORY_USAGE 宏，后续我们会考虑通过 backend 接口透出这一信息

**Comment by GYxiaOH** [comment]
@jxt1234  你好，打开了这个宏之后要怎么评测时间呢，用默认的basic.out好像还是输不出内存占用

**Comment by Liujingxiu23** [comment]
@jxt1234 你好 我使用 1.1.7版本 发现没有这个宏 我该怎么操作来统计Memory的使用呢？
