### ISSUE TITLE
Issue when converting yolact onnx2mnn, type=slice, failed, may be some node is not const 

### ISSUE THREAD

**Issue by dzyjjpy** [alibaba/MNN#622]
I convert yolact pytorch model(.pth) to onnx file with no problem.
As I convert onnx to mnn, error appeared:
**type=slice, failed, may be some node is not const** 

yolact model introduction:
usage:  instance segmentation
input:  w*h*3 image
output:  list(including 2 parts, original version is dict, cannot convert it  to onnx file) 
I am not sure whether the converted onnx model file is correct or not.

Does anyone have similar experience or advice?  Welcome to discuss.

**Comment by ronjian** [comment]
@dzyjjpy 
I encountered the same issue while converting yolov3. Have you found a solution?

**Comment by dzyjjpy** [comment]
> @dzyjjpy
> I encountered the same issue while converting yolov3. Have you found a solution?

not yeah

**Comment by jxt1234** [comment]
fixed
