### ISSUE TITLE
由TensorFlow转换到MNN的模型可以自定义训练吗？

### ISSUE THREAD

**Issue by ArnoldLiuIC** [alibaba/MNN#624]
MNN旧版，利用transformer工具将TensorFlow模型转成MNN后，可以实现自定义训练（写法比较丑陋）。此时net后接梯度求导算子，类似于静态图的方式。net没有expr和module的概念，都是OP。

MNN新版，支持自定义网络和训练，动态图的方式（写法比较优雅）。此时net由expr和module组成，底层实现的展示也是graph containing a sequence of ops？

问题是：我能否通过方式一（旧版）把TF模型转成MNN后，然后像minstUtils里面的动态图的写法，进行训练？不知道是否阐述清楚，具体困惑在于静态图和动态图之间是否训练上是兼容的。

**Comment by jxt1234** [comment]
可以的，参考 PipelineModule 的使用
后面会有较完善的 finetune / 基于已有网络修改 的训练 demo 放出

**Comment by ArnoldLiuIC** [comment]
好的。另外关于将建好的图进行拓扑排序的逻辑，是在std::vector<EXPRP> Variable::getExecuteOrder(const std::vector<VARP>& outputs)实现的吗，这部分看的有点绕。

**Comment by jxt1234** [comment]
这个一般不需要开发者关注的，请留意后续的 api 说明吧

**Comment by jxt1234** [comment]
请参考 https://www.yuque.com/mnn/cn/vniw5p
