### ISSUE TITLE
split group convolution ERROR

### ISSUE THREAD

**Issue by ronjian** [alibaba/MNN#626]
我正在研究将pytorch模型（ctdet）转ONNX，再转MNN。在ONNX转MNN的过程中遇到这个问题：

# 平台
Ubuntu16

# 编译方式:
```
cd MNN
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true
make -j4
```
# MNN转换
```
./MNNConvert -f ONNX \
--modelFile ctdet_coco_dlav0_1x.onnx \
--MNNModel ctdet_coco_dlav0_1x.mnn \
--bizCode MNN
```

# 报错信息
```
MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
[10:58:31] /workspace/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
Start to Optimize the MNN Net...
terminate called after throwing an instance of 'Error'
  what():  [10:58:31] /workspace/MNN/tools/converter/source/optimizer/postconvert/TransformGroupConvolution.cpp:78: Check failed: srcCount % common->group == 0 && common->outputCount % common->group == 0 ==> split group convolution ERROR! ==> 485
Aborted (core dumped)
```

# pytorch中对应的op
```
nn.ConvTranspose2d(input=64, output=64, kernel=4, strides=2, padding=1,
                    output_padding=0, groups=64, bias=False)
```

# ONNX中对应op
![ONNX ConvTranspose](https://user-images.githubusercontent.com/23271323/74432415-c75dd680-4e99-11ea-97e3-7a6a18448c27.jpg)

# MNN中的形状
```
srcCount:4096
common->group:64
common->outputCount:1
common->group:64
```

请问是因为还MNN还不兼容ONNX的ConvTranspose吗？

**Comment by jxt1234** [comment]
看上去是 bug ，是否有原始模型呢？

**Comment by ronjian** [comment]
> 看上去是 bug ，是否有原始模型呢？

多谢，ONNX模型上传了网盘
链接:https://pan.baidu.com/s/1wNSy4h61ENv5INp8n9mrew  密码:fe82

**Comment by jxt1234** [comment]
百度网盘的链连我打不开，要不你这么修改下再转换试试吧
index 7816803..dc08273 100644
--- a/tools/converter/source/optimizer/onnxextra/OnnxConvolutionMerge.cpp
+++ b/tools/converter/source/optimizer/onnxextra/OnnxConvolutionMerge.cpp
@@ -227,8 +227,13 @@ public:
         // set param
         common->relu        = false;
         common->group       = group;
-        common->outputCount = co;
-        common->inputCount  = ci * group; // conv set inputCount to be ci, dw to be group
+        if (isDeconv) {
+            common->outputCount = co * group;
+            common->inputCount  = ci; // deconv set inputCount to be ci, dw to be group
+        } else {
+            common->outputCount = co;
+            common->inputCount  = ci * group; // conv set inputCount to be ci, dw to be group
+        }
         common->kernelX     = kw;
         common->kernelY     = kh;
         common->dilateX     = dilation_w;

**Comment by ronjian** [comment]
> 百度网盘的链连我打不开，要不你这么修改下再转换试试吧
> 
> [tempPatch.txt](https://github.com/alibaba/MNN/files/4202374/tempPatch.txt)

修改这几行代码之后，可以转换成功。谢谢
