### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by yousefabohend** [alibaba/MNN#629]
That is what appears in the powershell

PS C:\Users\youse\Desktop\MNN\MNN-0.2.1.7\build> cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is MSVC 19.24.28316.0
-- The CXX compiler identification is MSVC 19.24.28316.0
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler
    "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe"
  is not able to compile a simple test program.
  It fails with the following output:
    Change Dir: C:/Users/youse/Desktop/MNN/MNN-0.2.1.7/build/CMakeFiles/CMakeTmp
    Run Build Command(s):nmake /nologo cmTC_40f5a\fast &&       "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_40f5a.dir\build.make /nologo -L                  CMakeFiles\cmTC_40f5a.dir\build
    Building C object CMakeFiles/cmTC_40f5a.dir/testCCompiler.c.obj
        C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe @C:\Users\youse\AppData\Local\Temp\nm3D4E.tmp
    testCCompiler.c
    Linking C executable cmTC_40f5a.exe
        "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_40f5a.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_40f5a.dir\objects1.rsp @C:\Users\youse\AppData\Local\Temp\nm3F24.tmp
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_40f5a.dir/manifest.res CMakeFiles\cmTC_40f5a.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specifiedNMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
    Stop.
    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\nmake.exe"' : return code '0x2'
    Stop.
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:36 (project)
-- Configuring incomplete, errors occurred!
See also "C:/Users/youse/Desktop/MNN/MNN-0.2.1.7/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/youse/Desktop/MNN/MNN-0.2.1.7/build/CMakeFiles/CMakeError.log".

that is what appears in CmakeError

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe 
Build flags: 
Id flags:  
The output was:
2
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
CMakeCCompilerId.c
Microsoft (R) Incremental Linker Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.
/out:CMakeCCompilerId.exe 
CMakeCCompilerId.obj 
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx64/x64/cl.exe 
Build flags: 
Id flags:  
The output was:
2
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
CMakeCXXCompilerId.cpp
Microsoft (R) Incremental Linker Version 14.24.28316.0
Copyright (C) Microsoft Corporation.  All rights reserved.
/out:CMakeCXXCompilerId.exe 
CMakeCXXCompilerId.obj 
LINK : fatal error LNK1104: cannot open file 'LIBCMT.lib'
Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple LLVM version)":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
Checking whether the ASM compiler is ARMClang using "--version" did not match "armclang":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
Checking whether the ASM compiler is HP using "-V" did not match "HP C":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line error D8004 : '/V' requires an argument
Checking whether the ASM compiler is Intel using "--version" did not match "(ICC)":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
Checking whether the ASM compiler is SunPro using "-V" did not match "Sun C":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line error D8004 : '/V' requires an argument
Checking whether the ASM compiler is XL using "-qversion" did not match "XL C":
Microsoft (R) C/C++ Optimizing Compiler Version 19.24.28316 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
cl : Command line warning D9002 : ignoring unknown option '-qversion'
cl : Command line error D8003 : missing source filename
Determining if the C compiler works failed with the following output:
Change Dir: C:/Users/youse/Desktop/MNN/MNN-0.2.1.7/build/CMakeFiles/CMakeTmp
Run Build Command(s):nmake /nologo cmTC_40f5a\fast && 	"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_40f5a.dir\build.make /nologo -L                  CMakeFiles\cmTC_40f5a.dir\build
Building C object CMakeFiles/cmTC_40f5a.dir/testCCompiler.c.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe @C:\Users\youse\AppData\Local\Temp\nm3D4E.tmp
testCCompiler.c
Linking C executable cmTC_40f5a.exe
	"C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_40f5a.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_40f5a.dir\objects1.rsp @C:\Users\youse\AppData\Local\Temp\nm3F24.tmp
RC Pass 1: command "rc /fo CMakeFiles\cmTC_40f5a.dir/manifest.res CMakeFiles\cmTC_40f5a.dir/manifest.rc" failed (exit code 0) with the following output:
The system cannot find the file specifiedNMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by AlphaNumeric99** [comment]
@MNNTeam Can you provide a docker image so that it is easier for windows users instead of compiling it from source.

**Comment by wangzhaode** [comment]
> @MNNTeam Can you provide a docker image so that it is easier for windows users instead of compiling it from source.

You can ref github action build script: https://github.com/alibaba/MNN/actions/workflows/windows.yml

Or reading the doc: https://mnn-docs.readthedocs.io/en/latest/compile/engine.html#windows
