### ISSUE TITLE
MNNConverter还是编译不出来？

### ISSUE THREAD

**Issue by coollofty** [alibaba/MNN#630]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
1. Windows+VC15+Win64
2. Ubuntu18.04（不论是Windows+VC还是Ubuntu+GCC，错误情况都是一样的）

# Github版本: 最新版

问题1：按照网上所有可能找得着的方法，没有一个可以正常编译通过的。但是checkout到0.2.1.0则可以编译出来。最新的版本合并到主工程里，只要编译就会出现什么Deps错误，主工程其它的都能编译过去，和MNNConverter有关的5个工程全部出错

问题2：Release里发布的Windows版预编译包，为何没有MNNConverter.exe？

谢谢

**Comment by ChisenZhang** [comment]
我前两天编的没啥问题呀

**Comment by coollofty** [comment]
用WIndows的Ubuntu子系统编译过去了。。。。
转换TFLITE模型的时候遇到

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [14:32:28] /mnt/e/Projects/MNN/tools/converter/source/tflite/BroadCastAdd.cpp:61: Check failed: addOption->fused_activation_function == tflite::ActivationFunctionType_NONE ==> BinaryOP Should not has fused_activation_function

请问这个fused_activation_function可能支持一下么？

**Comment by coollofty** [comment]
以及

Check failed: creator ==> NOT_SUPPORTED_OP: [ PRELU ]

PRELU这个OP，有没有todo list？ ^_^谢谢大神

**Comment by ChisenZhang** [comment]
operation requirements #74

**Comment by MaltoseMai** [comment]
> 我前两天编的没啥问题呀

请问具体怎么编译才行呢？按文档指引都不行。或者可以发布一下Win10 x64的MNNConvert.exe吗？

**Comment by coollofty** [comment]
> > 我前两天编的没啥问题呀
> 
> 请问具体怎么编译才行呢？按文档指引都不行。或者可以发布一下Win10 x64的MNNConvert.exe吗？

Windows上比较麻烦，又是改系统语言又是开PowerShell，最后还是会在VS里出问题，具体原因我也懒得去研究了，因为系统语言改了还要再改回来，否则很多软件的界面都出乱码了。所以最好用Linux，Win10上有Ubuntu子系统，在子系统下可以编译过去。编译出来的，就在子系统里调用呗，反正那命令行和Windows的命令行也没多大区别，挺方便的。

**Comment by Lininggggggg** [comment]
请问你们解决了吗？MNNConvert.exe这个文件请问是要自己编译生成的吗？麻烦解答下，感谢！

**Comment by coollofty** [comment]
> 请问你们解决了吗？MNNConvert.exe这个文件请问是要自己编译生成的吗？麻烦解答下，感谢！

是的，解决了，但是用的是Windows的Ubuntu子系统编译出来的，用VC始终就没成功

**Comment by Lininggggggg** [comment]
![图片](https://user-images.githubusercontent.com/52039865/78231382-4c15ba00-7505-11ea-9600-f16e5a6f3da1.png)

请问你当时遇到这种情况了吗？
“找不到MNN_generated.h文件”
我目前在运行那个指导文档里的1.2步骤中的最后一步nmake时候出的问题，能麻烦下您解答下吗？感谢！

**Comment by Lininggggggg** [comment]
> 
> 
> > 请问你们解决了吗？MNNConvert.exe这个文件请问是要自己编译生成的吗？麻烦解答下，感谢！
> 
> 是的，解决了，但是用的是Windows的Ubuntu子系统编译出来的，用VC始终就没成功

老哥，请问你有生成这个MNNConvert.exe吗？能不能分享这个文件给我下可以吗？我邮箱1296889948@qq.com
现在编译成功后一直没找到这个文件，看了网上的说法好像是官方的问题

**Comment by jxt1234** [comment]
Fixed
