### ISSUE TITLE
converting caffemodel error.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#631]
Hi,
I have an error when converting caffemodel.

libc++abi.dylib: terminating with uncaught exception of type Error: [17:28:45] /Users/MNN/tools/converter/source/caffe/Crop.cpp:40: Check failed: offsetSize >= 1 ==> crop offset error
Abort trap: 6

I tried to convert this caffemodel https://github.com/Charrin/RetinaFace-Cpp/tree/master/convert_models/mnet 
Can you check this?

**Comment by czy2014hust** [comment]
This caffemodel may come from other framework, not original caffemodel/prototxt. *The prototxt has ERROR in layer Crop*
