### ISSUE TITLE
I see no differences between _const and _trainableParm

### ISSUE THREAD

**Issue by ArnoldLiuIC** [alibaba/MNN#632]
In the code "LinearRegress.cpp", the w and b are both set to _Const. 
By adding w and b to optimizer, they become trainable.  
I am confused by such settings, since I thought the _Const VARP should not be trained no matter whether it is added or not at ll.
Am I wrong with the understanding of such settings or?

**Comment by jxt1234** [comment]
For LinearRegress.cpp, It's a bug and will be fixed.

**Comment by jxt1234** [comment]
Fixed
