### ISSUE TITLE
ONNX LSTM模型转换失败

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#633]
Linux平台
定长LSTM模型，很简单就做了叠了两个LSTM模块，测试一下可转换性，没有做训练
Convertor 版本 0.2.0.9 和 线上最新
0.2.0.9版本提示转换成功，但是中间有提示 not support OP: Slice
线上最新版本，Segment fault，具体如下：
 ./MNNConvert -f ONNX --modelFile modelTranLSTM.onnx --MNNModel modelTranLSTM.mnn --bizCode mnn

MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[17:46:14] MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
[17:46:14] MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 50 has empty input, the index is 4
[17:46:14] MNN/tools/converter/source/onnx/onnxConverter.cpp:153: Check it out ==> 92 has empty input, the index is 4
Start to Optimize the MNN Net...
Segmentation fault

望大佬给解答一下咋回事~   感谢

模型：
[modelTranLSTM.zip](https://github.com/alibaba/MNN/files/4224325/modelTranLSTM.zip)

**Comment by un-knight** [comment]
遇到过类似问题，MNN目前应该支持batch_first的LSTM，所以在导出ONNX模型的时候就要先确保采用的是batch_first，而不是sequence_first的模式。

**Comment by ChisenZhang** [comment]
> 遇到过类似问题，MNN目前应该支持batch_first的LSTM，所以在导出ONNX模型的时候就要先确保采用的是batch_first，而不是sequence_first的模式。可以确认下你是否也因为这个原因。
好的 我试试   谢谢

**Comment by ChisenZhang** [comment]
改了 batch_first 参数，暂时转换没有报错   以后有问题再补充

**Comment by ouyanghuiyu** [comment]
> 改了 batch_first 参数，暂时转换没有报错 以后有问题再补充

你好，请问是改torch中的batch_first参数么？
nn.LSTM(nIn, nHidden, bidirectional=True,batch_first = True)

**Comment by lddsjy** [comment]
> > 改了 batch_first 参数，暂时转换没有报错 以后有问题再补充
> 
> 你好，请问是改torch中的batch_first参数么？
> nn.LSTM(nIn, nHidden, bidirectional=True,batch_first = True)

你好，请问你改batch_first =True成功了么，我改完还是报同样的错

**Comment by cendelian** [comment]
> > > 改了 batch_first 参数，暂时转换没有报错 以后有问题再补充
> > 
> > 
> > 你好，请问是改torch中的batch_first参数么？
> > nn.LSTM(nIn, nHidden, bidirectional=True,batch_first = True)
> 
> 你好，请问你改batch_first =True成功了么，我改完还是报同样的错

你好，请问你解决了吗？ 我lstm模型 onnx转mnn也遇到了一样的问题，改batch_first =True还是一样报错

**Comment by yftongbupt** [comment]
> 

你好，请问你lstm模型onnx转mnn成功了吗？我也是相同的问题

**Comment by yftongbupt** [comment]
> > > > 改了 batch_first 参数，暂时转换没有报错 以后有问题再补充
> > > 
> > > 
> > > 你好，请问是改torch中的batch_first参数么？
> > > nn.LSTM(nIn, nHidden, bidirectional=True,batch_first = True)
> > 
> > 
> > 你好，请问你改batch_first =True成功了么，我改完还是报同样的错
> 
> 你好，请问你解决了吗？ 我lstm模型 onnx转mnn也遇到了一样的问题，改batch_first =True还是一样报错

你好，请问你问题解决了吗？我也是相同的问题
