### ISSUE TITLE
pytorch转换出来的模型的推理结果不正确

### ISSUE THREAD

**Issue by ronjian** [alibaba/MNN#638]
转换过程： pytorch->onnx->mnn, 转换过程没有错误
pytorch中图片预处理的过程是：
cv2.imread() (BGR通道顺序)-> cv2.resize -> 除 255 -> 减均值，除方差 -> 转置 HWC to NCHW

MNN中对pytorch中的均值和方差做了如下变换：
```raw
>>> mean = [0.408,0.447,0.47]
>>> new_mean = [x * 255.0 for x in mean]
>>> std = [0.289,0.274,0.278]
>>> new_std = [1.0/x/255.0 for x in std]
```

参考tools/cpp/mobilenetTest.cpp，修改了几处代码如下：
```c++
Tensor inputTensorUser(inputTensor, Tensor::DimensionType::CAFFE_C4);

float mean[3]     = {104.04f, 113.99f, 119.85f}; // in BGR format
float normals[3]  = {0.014f, 0.014f, 0.014f}; // in BGR format

config.sourceFormat = BGR;
config.destFormat = BGR;
```
但是MNN的推理结果和pytorch的结果相差很多，请问是否还有需要修改的前处理步骤？

**Comment by GYxiaOH** [comment]
楼主发现问题了吗

**Comment by ronjian** [comment]
> 楼主发现问题了吗

可能还是前处理的问题，后来尝试用opencv来做前处理解决了问题。参考：https://github.com/xindongzhang/MNN-APPLICATIONS.git
