### ISSUE TITLE
getShape和getData的大小不匹配，后面填充了字符0

### ISSUE THREAD

**Issue by gnawup** [alibaba/MNN#639]
interpreter = MNN.Interpreter("tflite_graph.pb.mnn")
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
print("shape:",input_tensor.getShape())
input_data = np.array(input_tensor.getData())
print("input:",len(input_tensor.getData()))
![51582247999_ pic_hd](https://user-images.githubusercontent.com/47058059/74995295-721e5800-548b-11ea-86dd-78cdccc423af.jpg)
最后的输出结果（后面填充成0了）：
![61582248017_ pic_hd](https://user-images.githubusercontent.com/47058059/74995301-73e81b80-548b-11ea-88bb-76cb306e77f2.jpg)

**Comment by czy2014hust** [comment]
这是采用了NC/4HW4格式导致，请使用copy tensor接口拷贝出来。

**Comment by tbcxx** [comment]
> 这是采用了NC/4HW4格式导致，请使用copy tensor接口拷贝出来。

hi, i have trouble with getData(). 
    session = model.createSession()
    tmp_input = MNN.Tensor((1, 4, 160, 160), MNN.Halide_Type_Float,
                           in_, MNN.Tensor_DimensionType_Caffe)
    input_tensor = model.getSessionInput(session)
    print("shape of input:", input_tensor.getShape())
    print("input:", len(input_tensor.getData()))
    input_tensor.copyFrom(tmp_input)
    model.runSession(session)
    output_mask = model.getSessionOutput(session)
    print("shape of output after copyfrom:", output_mask.getShape())
    output_mask.printTensorData()
    print('type after copyfrom',type(output_mask.getData()))
    print('tuple中0的个数',output_mask.getData().count(0))
    data = np.array(output_mask.getData())
    print("np size：", data.size)
    print("np shape：", data.shape)

Output_mask.printTensorData() shows the correct data and correct shape(1,2,160,160) ,but after  data = np.array(output_mask.getData()), np get 51200 0 elements，Later processes cannot continue.   为什么MNN.getData()会多出来一倍的0元素啊?

**Comment by Parker-Lyu** [comment]
因为mnn的数组组织形式是NC4HW4，需要copy操作转为通常用的NCHW形式：

` des_tensor = MNN.Tensor((N,C,H,W), MNN.Halide_Type_Float,np.ones((N,C,H,W)), MNN.Tensor_DimensionType_Caffe)
result_tensor.copyToHostTensor(des_tensor)`
这样，des_tensor取出来的东西就可以用了
