### ISSUE TITLE
Initialize MNN.Tensor is so slow

### ISSUE THREAD

**Issue by vocong25** [alibaba/MNN#641]
OS: Raspbian

I tested my model in MNN. 
Inference time is so fast by 30ms approximately. But time of tensor initialization is so slow: 90ms
```
tmp_input = MNN.Tensor((1, 3, self._input_size[1], self._input_size[0]), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe)
print("Create Tensor:", time.time() - time_time)
self._input_tensor.copyFrom(tmp_input)

self._interpreter.runSession(self._session)
scores = self._interpreter.getSessionOutput(self._session, "scores").getData()
boxes = self._interpreter.getSessionOutput(self._session, "boxes").getData()
```
Can you give me an advice for this case?

**Comment by zaiyebuheniwanle** [comment]
> 操作系统：Raspbian
> 
> 我在MNN中测试了我的模型。
> 推理时间大约快30ms。但是张量初始化的时间太慢了：90ms
> 
> ```
> tmp_input = MNN.Tensor((1, 3, self._input_size[1], self._input_size[0]), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Caffe)
> print("Create Tensor:", time.time() - time_time)
> self._input_tensor.copyFrom(tmp_input)
> 
> self._interpreter.runSession(self._session)
> scores = self._interpreter.getSessionOutput(self._session, "scores").getData()
> boxes = self._interpreter.getSessionOutput(self._session, "boxes").getData()
> ```
> 
> 你能给我个建议吗？

你解决了吗？

**Comment by pauloamed** [comment]
Same here. It is slower than the inference cost.

**Comment by stanleywang8888** [comment]
约两礼拜后会更新解决

**Comment by qihaouu** [comment]
> 约两礼拜后会更新解决

您好，初始化tensor比较慢这个问题解决了么

**Comment by stanleywang8888** [comment]
1.0.1发布解决, tensor初始化可以输入numpy. getData也返回numpy.

**Comment by vocong25** [comment]
@stanleywang8888 
-> A note for Raspbian - ARMv7
I noticed that the python version in master branch is still 0.0.9. There are no newer version for armv7 in pypi. So when I recompiled and re-run my model, the initialization is the same.

Init Tensor: 0.1032564640045166
inference time: 0.0741 s

**Comment by stanleywang8888** [comment]
1. most people can get pip package through pip install directly, it's latest version is 1.0.1
2. public code release is not synced to 1.0.1 yet, so for rare cases that you need to build your own wheel package, you need to wait more time

**Comment by metanav** [comment]
@vocong25 How did you solve this? I have checked out latest master and built the pip wheel on Raspbian (RPI 4). It is still very slow around 85ms for just MNN.Tensor initialization. 

@stanleywang8888 what do you mean by "public code release is not synced to 1.0.1 yet, so for rare cases that you need to build your own wheel package, you need to wait more time" ?
I think all latest code must be in the master branch or I am missing something?

**Comment by vocong25** [comment]
@Naveen, It's still not the lastest version (currently py version is 0.9).
The problem not solved yet.

**Comment by stanleywang8888** [comment]
@metanav @vocong25  public prebuilt pip release version is 1.0.1, but corresponding code is not released yet.  You know, it's code release schedule issue, or in other words, you can treat 1.0.1 as a small bug fix, but not a big code update.

**Comment by metanav** [comment]
In the meantime, can you please release a pip wheel for Raspbian Buster (RPI 3/4)?

**Comment by stanleywang8888** [comment]
@metanav sorry, I don't have the device and can't setup the environment

**Comment by metanav** [comment]
No problem! Any ETA for the next release?
