### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by CheungBH** [alibaba/MNN#643]
你好，我编译的时候出现了以下错误：

[ 65%] Built target MNNConverterCaffe
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

前面还有些这些错误
tools/converter/CMakeFiles/MNNConverterTF.dir/build.make:62: recipe for target 'tools/converter/attr_value.pb.cc' failed
make[2]: *** [tools/converter/attr_value.pb.cc] Error 1
function.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
tools/converter/CMakeFiles/MNNConverterTF.dir/build.make:70: recipe for target 'tools/converter/function.pb.cc' failed
make[2]: *** [tools/converter/function.pb.cc] Error 1
CMakeFiles/Makefile2:1310: recipe for target 'tools/converter/CMakeFiles/MNNConverterTF.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/MNNConverterTF.dir/all] Error 2

请问我是环境中缺了什么嘛

**Comment by jxt1234** [comment]
你是按 https://www.yuque.com/mnn/cn/yv9o2e 这个编译的么？

**Comment by CheungBH** [comment]
> 你是按 https://www.yuque.com/mnn/cn/yv9o2e 这个编译的么？

是的，我重新编译了一次，还是这个问题。

onnx-operators.proto:9:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
tools/converter/CMakeFiles/MNNConverterONNX.dir/build.make:70: recipe for target 'tools/converter/onnx-operators.pb.cc' failed
make[2]: *** [tools/converter/onnx-operators.pb.cc] Error 1
CMakeFiles/Makefile2:1421: recipe for target 'tools/converter/CMakeFiles/MNNConverterONNX.dir/all' failed
make[1]: *** [tools/converter/CMakeFiles/MNNConverterONNX.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

不过这次是onnx的编译出了错

**Comment by CheungBH** [comment]
> 你是按 https://www.yuque.com/mnn/cn/yv9o2e 这个编译的么？

![mnn2](https://user-images.githubusercontent.com/39186017/75126235-f4a95080-56f3-11ea-8ca2-407d32d6a7b4.png)
![mnn1](https://user-images.githubusercontent.com/39186017/75126237-f6731400-56f3-11ea-8bd4-4243a38beff1.png)
编译截图在这里

**Comment by jxt1234** [comment]
你电脑上 protobuffer 的版本较老的原因

**Comment by mifan0208** [comment]
你好，请问解决了嘛？我也遇到了这样的问题

**Comment by guoqiang0148666** [comment]
my default installed protobuffer is 2.6.1, another protobuf is 3.6.1 and is installed on /home/guo/protobuf3_install. and the following commands solve my problem:
**Note**: cmake version is 3.5.1
```
// set proto compiler to 3.6.1
export PATH=/home/guo/protobuf3-install/bin/:$PATH  

// set proto include and lib files to 3.6.1
cmake .. -DCMAKE_INSTALL_PREFIX=/home/guo/protobuf3-install 
-DMNN_BUILD_CONVERTER=True

make
```
