### ISSUE TITLE
Don't support type LSTM

### ISSUE THREAD

**Issue by un-knight** [alibaba/MNN#645]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
rk3399 with debian os

# Github版本:
e68fd69a24f0eb009e3d8d447247689b73a6d32c

# 编译方式:

```
cmake .. -DMNN_OPENCL
```

# 问题
使用 `MNN_FORWARD_OPENCL` 进行推理的时候出现错误，提示如下：
```
Don't support type Unsqueeze, Unsqueeze2
Don't support type LSTM, 37
```

但是根据 [MNN LSTM 文档](https://www.yuque.com/mnn/en/ops#LSTM)说明是支持 opencl backend 是支持 LSTM 的，cpu backend 可以正常执行。

**Comment by jxt1234** [comment]
目前支持，不过性能不如 cpu
