### ISSUE TITLE
最后一层网络层不能是relu

### ISSUE THREAD

**Issue by AlpacaKnight** [alibaba/MNN#646]
如果模型的网络中的最后一个节点是relu，在转换模型的时候完全正常，推理的时候能运行，但是得到的结果与原模型不一致，去掉模型网络中最后一个节点的relu，再转mnn模型运行就可以得到原模型去掉relu的正常结果
即 现在的模型最后一个节点不能是relu，否则能转换能运行不报错，但是结果是错的。

**Comment by jxt1234** [comment]
新的代码 （0.2.1.8） 上已经解决了
