### ISSUE TITLE
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4

### ISSUE THREAD

**Issue by dragen1860** [alibaba/MNN#647]
Hi, 
  Currently i came across a bug when export efficientnet-b0 to MNN model. It says:
```

Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4
Imageprocess don't support CAFFE dimension type, please create tensor with type TENSORFLOW or CAFFE_C4

```
But i tried other models, such as mobilenetv2, with others setting unchanged, it works well. Only for this efficientnet-b0 model, the MNN say can not deal with NCHW format. I suppose why MNN does not convert the format this time.

Thank you.

Here is my model mnn file:
  链接: https://pan.baidu.com/s/1pFviuPZ2CJctoAdnoo4tVQ 提取码: ru95

**Comment by yyfcc17** [comment]
it has nothing to do with the model, but your ImageProcess code. i guess you try to use MNN::CV to process your input image, but the tensor you created is NCHW format.  you should create a NHWC format tensor instead.

**Comment by jxt1234** [comment]
Please update code, currently Imageprocess has support nchw format
