### ISSUE TITLE
Invalidate buffer to create interpreter 安卓端的quantized模型运行报错

### ISSUE THREAD

**Issue by WPU93** [alibaba/MNN#649]
./quantized.out pb_time_location_det_fp32.mnn pb_time_location_det_quan.mnn pretreatConfig.json
对模型进行量化得到的量化模型在linux下两个模型均能跑通；
但是在安卓端跑非量化前的模型没有问题（使用p20 pro实测）：
![51582887758_ pic](https://user-images.githubusercontent.com/47058059/75543749-818a3c00-5a5d-11ea-9c30-bc72b3fd7c12.jpg)
但是使用quantized的模型就会爆如下错误：
![41582887666_ pic](https://user-images.githubusercontent.com/47058059/75543817-9ff03780-5a5d-11ea-81da-dfa83e98f776.jpg)
应该是creat interpreter的问题？但是我两个模型的linux都能跑通啊。
![61582888149_ pic_hd](https://user-images.githubusercontent.com/47058059/75544030-17be6200-5a5e-11ea-9b03-b8ad10329c25.jpg)
这是我的代码片段，麻烦各位大佬答疑解惑！

**Comment by jxt1234** [comment]
应该是你安卓端的 mnn so 不是最新编译的

**Comment by gnawup** [comment]
> 应该是你安卓端的 mnn so 不是最新编译的

我用的都是最新编译的so

**Comment by jxt1234** [comment]
才看到你的代码，不用 revert ，直接 createFromFile 试下?
