### ISSUE TITLE
Mnn model with input size None

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#65]
I had  a tf model which the model input size is 1xNonexNonex4, it's support variable input , so how to setup the mnn input coding ?
3q

**Comment by jxt1234** [comment]
resizeTensor -> resizeSession

You can see the code in tools/cpp/MNNV2Basic.cpp

**Comment by zuoshaobo** [comment]
ok, i got it 3q

**Comment by zuoshaobo** [comment]
Dose ios metal gpu backend config  support the property "numThread "? 
if it is releated with the metal api threadGroupCount >?

**Comment by zuoshaobo** [comment]
@jxt1234 still not work,code like:
    auto input = _net->getSessionInput(_session, nullptr);
    MNN::Tensor* inputTensor = input;
    std::vector<int> inputDims={1,3,256,320};
    if (!inputDims.empty()) {
        std::vector<int> inputDims;
        MNN_PRINT("===========> Resize Again...\n");
        _net->resizeTensor(inputTensor, inputDims);
        _net->resizeSession(_session);
    }
error log:
Resize error for layer_0_conv/convolution, code=3

**Comment by jxt1234** [comment]
numThread is not used for metal.

std::vector inputDims={1,3,256,320};
std::vector inputDims;
MNN_PRINT("===========> Resize Again...\n");
_net->resizeTensor(inputTensor, inputDims);
_net->resizeSession(_session);

**Comment by jxt1234** [comment]
The session will resize when firstly created. So the error log will be print once.

**Comment by zuoshaobo** [comment]
The input shape is channel first or channel last?
My model input shape is 1x256x320*4, It can be run without any error if i did't put the above code ,but it will be run crashed after i resized the input shape by the same as current , so is there any other resasons ?

**Comment by li-qing** [comment]
> @jxt1234
> The input shape is channel first or channel last?
> My model input shape is 1x256x320*4, It can be run without any error if i did't put the above code ,but it will be run crashed after i resized the input shape by the same as current , so is there any other resasons ?

query tensor format with 'TensorUtils::getDescribe(tensor)->dimensionFormat'
