### ISSUE TITLE
Failed to build static library for linux host

### ISSUE THREAD

**Issue by Volcanoscar** [alibaba/MNN#652]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux 18.04

# Github版本:
# Github Version:
942246c5a71f4fad10c488d64bafa87859dc4666

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_CONVERTER=ON ..

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
Linking CXX shared library libMNN.so

Still a shared library generated...

**Comment by jxt1234** [comment]
It's a bug. Please currently set MNN_SEP_BUILD=false :
cmake -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_CONVERTER=ON .. -DMNN_SEP_BUILD=OFF

**Comment by Volcanoscar** [comment]
Aye, sir. Problem solved.

> DMNN_SEP_BUILD=OFF
