### ISSUE TITLE
ONNX转MNN的时候slice op的问题， Onnx slice must use the same dimensition

### ISSUE THREAD

**Issue by ronjian** [alibaba/MNN#657]
# 运行：
```
$MNN_HOME/MNNConvert -f ONNX \
--modelFile yolov3.onnx \
--MNNModel yolov3.mnn \
--bizCode MNN
```

# 报错：
```
Onnx slice must use the same dimensition
Convert Onnx's Op 424 , type = Slice, failed, may be some node is not const
[10:36:25] /workspace/MNN/tools/converter/source/optimizer/PostConverter.cpp:20: Inputs: input.1
[10:36:25] /workspace/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 443, Type = Concat
[10:36:25] /workspace/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 446, Type = Concat
terminate called after throwing an instance of 'Error'
  what():  [10:36:25] /workspace/MNN/tools/converter/source/common/writeFb.cpp:107: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX::Slice | 
Aborted (core dumped)
```

看了代码OnnxSlice.cpp，这两处地方报错了，看起来MNN现在支持的slice op是4维度的，但是我的onnx的slice是5维的。
https://github.com/alibaba/MNN/blob/002ac367e4a9339b98180e14838900271bc55a55/tools/converter/source/optimizer/onnxextra/OnnxSlice.cpp#L25
https://github.com/alibaba/MNN/blob/002ac367e4a9339b98180e14838900271bc55a55/tools/converter/source/optimizer/onnxextra/OnnxSlice.cpp#L74

我把onnx模型上传到了百度网盘
链接:https://pan.baidu.com/s/1wN1Iw2axB1I5Ke_1JkPZAg  密码:p19x

**Comment by ronjian** [comment]
相似的两个issue：
https://github.com/alibaba/MNN/issues/614
https://github.com/alibaba/MNN/issues/622

**Comment by jxt1234** [comment]
可否把模型发我邮箱？百度网盘太大的文件我下载不了

**Comment by ronjian** [comment]
> 可否把模型发我邮箱？百度网盘太大的文件我下载不了

已经发送到jxt1234@zju.edu.cn邮箱，请查收。

**Comment by jxt1234** [comment]
我知道了，你这个模型输入形状没有指定，onnx 的模型如果包含 slice ，需要输入形状确定。后面我们加个指定输入形状的选项好了

**Comment by ronjian** [comment]
> 我知道了，你这个模型输入形状没有指定，onnx 的模型如果包含 slice ，需要输入形状确定。后面我们加个指定输入形状的选项好了

你是指在MNNConvert的时候指定输入的形状吗？但我没有找到这样的参数。
```
Usage:
  MNNConvert [OPTION...]

  -h, --help            Convert Other Model Format To MNN Model

  -v, --version         show current version
  -f, --framework arg   model type, ex: [TF,CAFFE,ONNX,TFLITE,MNN]
      --modelFile arg   tensorflow Pb or caffeModel, ex: *.pb,*caffemodel
      --prototxt arg    only used for caffe, ex: *.prototxt
      --MNNModel arg    MNN model, ex: *.mnn
      --fp16            save Conv's weight/bias in half_float data type
      --benchmarkModel  Do NOT save big size data, such as Conv's weight,BN's
                        gamma,beta,mean and variance etc. Only used to test
                        the cost of the model
      --bizCode arg     MNN Model Flag, ex: MNN
      --debug           Enable debugging mode.
      --forTraining     whether or not to save training ops BN and Dropout,
                        default: false
```

**Comment by dzyjjpy** [comment]
@ronjian  have you solve the issue about slice op?

**Comment by ronjian** [comment]
> @ronjian have you solve the issue about slice op?

not yet

@jxt1234 , is there any solution or plan on the ONNX slice OP issue? Thanks.

**Comment by ustcsq** [comment]
指定输入形状虽然可以把模型转成功，但是后期用的时候resize结果还是不对的

**Comment by mna12478** [comment]
@jxt1234, i also meet this problem, is there any solution?

**Comment by GHLab** [comment]
@jxt1234  I have same problem. You can check https://github.com/GHLab/fsanet-onnx-demo/blob/master/fsanet_epoch_95.onnx

**Comment by lddsjy** [comment]
> 指定输入形状虽然可以把模型转成功，但是后期用的时候resize结果还是不对的

请问怎么指定输入形状？mnnconvert 没有这样的参数呀

**Comment by linkerlin** [comment]
我也遇到了类似的情况：
`libc++abi.dylib: terminating with uncaught exception of type Error: [13:02:31] /Users/shawnhe/MNN/MNN/tools/converter/source/common/writeFb.cpp:108: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX::Slice | 
Abort trap: 6`

**Comment by jxt1234** [comment]
已经修正
