### ISSUE TITLE
bench_android 需要root 权限么？

### ISSUE THREAD

**Issue by nightinwhite** [alibaba/MNN#658]
# 问题
运行benchmark.out 会报错：
/system/bin/sh: /sdcard/MNN_test/benchmark.out: can't execute: Permission denied
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android

# Github版本:
# Github Version:
d93a15e52719ebc077854b32ee74232694ac1ef2

# 编译方式:
# Compiling Method
Mac 平台 bench_android.sh

# 编译日志:
# Build Log:

armeabi-v7a
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: armv7-a
-- 	Metal: OFF
-- 	OpenCL: ON
-- 	OpenGL: OFF
-- 	Vulkan: ON
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /Users/night/Code/Xnn_Benchmark/MNN/benchmark/build
CMake Warning at CMakeLists.txt:251 (message):
  Cross Compilation Detected.  Third-Party tools like protobuf/flatbuffer are
  not built.  You'll need to make sure they are available in your $PATH

-- Enabling AArch32 Assemblies
-- MNN Depends:MNNMNN_CLMNN_VulkanMNN_Express
/Users/night/Software/protobuf-3.11.4/install/lib/cmake/protobuf
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/night/Code/Xnn_Benchmark/MNN/benchmark/build
[  0%] Built target MNNOpenCLCodeGen
[  0%] Built target GenVCSHDR
[  1%] Built target MNN_SCHEMA_GEN
[  8%] Built target MNNMath
[ 23%] Built target MNNCV
[ 27%] Built target MNNARM32
[ 28%] Built target MNNCompute
[ 38%] Built target MNNVulkan
[ 50%] Built target MNNCore
[ 61%] Built target MNNShape
[ 86%] Built target MNNCPU
[ 88%] Built target MNNExpress
[ 98%] Built target MNNOpenCL
[ 98%] Built target MNN
[ 98%] Built target MNN_Express
[100%] Built target MNN_CL
[100%] Built target MNN_Vulkan
[100%] Built target benchmark.out
[  0%] Built target GenVCSHDR
[  0%] Built target MNNOpenCLCodeGen
[  1%] Built target MNN_SCHEMA_GEN
[  5%] Built target MNNMath
[  8%] Built target MNNCV
[ 23%] Built target MNNCompute
[ 28%] Built target MNNARM32
[ 46%] Built target MNNCore
[ 53%] Built target MNNVulkan
[ 60%] Built target MNNShape
[ 85%] Built target MNNCPU
[ 86%] Built target MNNExpress
[ 96%] Built target MNNOpenCL
[ 96%] Built target MNN
[ 96%] Built target MNN_Express
[ 98%] Built target MNN_Vulkan
[ 98%] Built target MNN_CL
[100%] Built target timeProfile.out
./armeabi-v7a/libMNN_Express.so: 1 file pushed. 37.4 MB/s (8719000 bytes in 0.222s)
./armeabi-v7a/libMNN.so: 1 file pushed. 38.4 MB/s (84316392 bytes in 2.092s)
./armeabi-v7a/libMNN_CL.so: 1 file pushed. 38.4 MB/s (27777976 bytes in 0.690s)
./armeabi-v7a/libMNN_Vulkan.so: 1 file pushed. 38.0 MB/s (16418396 bytes in 0.412s)
benchmark.out: 1 file pushed. 38.1 MB/s (5651716 bytes in 0.142s)
timeProfile.out: 1 file pushed. 38.0 MB/s (6179676 bytes in 0.155s)

**Comment by 0ct0cat** [comment]
不需要，把bin文件push到/data/local/tmp下，设置LD_LIBRARY_PATH即可。

**Comment by jxt1234** [comment]
用 /data/loca/tmp 文件夹就好

**Comment by jasonlbx13** [comment]
按照文档部署至 /data/local/tmp/MNN还是显示 /system/bin/sh: timeProfile.out: inaccessible or not found 错误，怀疑需要root权限
