### ISSUE TITLE
MNN多输入模型量化问题

### ISSUE THREAD

**Issue by reason4** [alibaba/MNN#659]
mnn模型文件是y,u,v三个输入，而且u,v的长宽和y不一样，像这种情况preprocessConfig.json文件应该怎么写呢

**Comment by jxt1234** [comment]
多输入目前不支持，建议自行修改量化工具。后续会考虑以Python接口或config形式提供

**Comment by YongyuG** [comment]
> 多输入目前不支持，建议自行修改量化工具。后续会考虑以Python接口或config形式提供

今年的fixbug版本支持了嘛

**Comment by wangzhaode** [comment]
仍然需要自行修改
