### ISSUE TITLE
The Creator Don't support type 85 when using metal.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#660]
Hi,
I think it's similar issue with https://github.com/alibaba/MNN/issues/483
The error was occurred when using UltraFace and forward type is metal on iOS.
The app was crashed with below log message.

The Creator Don't support type 85, scores
-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(5) * threadgroupsPerGrid.depth(1))(0) must not be 0.'

Is there unsupported OP on metal?
I tried to set the forward type as MNN_FORWARD_AUTO but same crash when executing 'm_interpreter->runSession(m_session);'.

Please check this.
Thank you.

**Comment by ItchyHiker** [comment]
> Hi,
> I think it's similar issue with #483
> The error was occurred when using UltraFace and forward type is metal on iOS.
> The app was crashed with below log message.
> 
> The Creator Don't support type 85, scores
> -[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(5) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
> 
> Is there unsupported OP on metal?
> I tried to set the forward type as MNN_FORWARD_AUTO but same crash when executing 'm_interpreter->runSession(m_session);'.
> 
> Please check this.
> Thank you.

Similar problem here. Have you solved this?

**Comment by GHLab** [comment]
@ItchyHiker No, I used cpu forward type.

**Comment by jxt1234** [comment]
Please update and check
