### ISSUE TITLE
ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by kunalgoyal9** [alibaba/MNN#662]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Mac os

# 编译方式:
# Compiling Method
I followed the procedure given as in:
[Android](https://www.yuque.com/mnn/en/build_android)

# 编译日志:
# Build Log:
```Build command failed.
Error while executing process /Users/a621592/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/a621592/Work/AI-on-the-edge/MNN_old/MNN/demo/android/app/.cxx/cmake/debug/armeabi-v7a --target mnncore}

ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it```
```

**Comment by jxt1234** [comment]
Please build android so firstly and then build demo

**Comment by kunalgoyal9** [comment]
I built everything but app is crashing. :(

**Comment by jadenwjh** [comment]
I have built android and the armv7 lobrary as stated in the tutorial and set ndk directory in local.properties to the latest version of ndk. I also encountered the same issue.

**Comment by hzung** [comment]
@kunalgoyal9 I got the crash issue also. I fixed it by open the file `MNN/demo/android/app/src/main/java/com/taobao/android/mnndemo/VideoActivity.java`, added the check null code to the onResume method.

```
...
@Override
protected void onResume() {
    super.onResume();
    if (mCameraView != null) {
        mCameraView.onResume();
    }
}
...
```

I also make a note of how to build the library for Android using Docker and configure the demo android project here, hope this could help [https://github.com/hzung/build-mnn-for-android](https://github.com/hzung/build-mnn-for-android)

**Comment by strivehub** [comment]
你好，我加了以上代码，还是报以上错误。但是运行非量化的就不会有错误。

**Comment by dandingol03** [comment]
this `mCameraView ` is not initialized at that time when it is invoked at onResume callback, the error can be easily fixed by bring forward the variable initialization time.
