### ISSUE TITLE
Is the DimensionType of an inputTensor always of “CAFFE” but not of “TENSORFLOW”？

### ISSUE THREAD

**Issue by MenSanYan** [alibaba/MNN#668]
I have converted my model from pb(Tensorflow) to mnn by MNNConverter. However, something has been confusing me since I inspected the DimensionTypes of the inputTensor and the outputTensor of the converted model.
`std::cout<<int(inputTensor->getDimensionType())<<"\t"<<int(outputTensor->getDimensionType())<<"\n";` Finally, the printed message indicates that inputTensor is of "CAFFE" but outputTensor of "TENSORFLOW".  I have to convert "CAFFE" to "TENSORFLOW" by copy data interfaces.

Why the converted model from pb(Tensorflow) has an inputTensor of "CAFFE" ? Is there any solutions for this problem?

**Comment by jxt1234** [comment]
TENSORFLOW means NHWC while CAFFE means NCHW
For model with convolution , the tensor before and after convolution will be changed as NCHW / CAFFE dimension

**Comment by MenSanYan** [comment]
@jxt1234 Thanks for your prompt and kind reply. I get your points.
