### ISSUE TITLE
How to set input data manuly

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#67]
The ios demo use a '->convert' function to set input images to inputtensor,  buy my  input data is not a image, i want to copy my data manuly, can i use  memcpy to  copy my data to temptensor, and then use copyfromhosttensor?
so what's the requirement of the inputdimenison type? if i wanto to do that above ,do i need to convert my NHWC type to another  type?

**Comment by jxt1234** [comment]
You can create host tensor as TENSORFLOW, such use NHWC
eg:
std::shared_ptr<Tensor> hostTensor(Tensor::create<float>({1, 224, 224, 3}, Tensor::TENSORFLOW));
