### ISSUE TITLE
想问一下mnn的cv模块是否有resize功能？

### ISSUE THREAD

**Issue by FB-wh** [alibaba/MNN#672]
mnn的cv模块依次执行裁剪，缩放，归一化。使用cv模块依次做这三个操作有点复杂啊，原谅我问这种简单的问题。这种有简单方法吗？有类似于ncnn或opencv的方法，可以三步就完成的那种吗？

**Comment by jxt1234** [comment]
使用 MNN-CV模块 的方法是最高效，最方便扩展的，矩阵设置可以用 setPolyToPoly ，目标点与源图点位一一对应就好
