### ISSUE TITLE
Batch inference. How to?

### ISSUE THREAD

**Issue by yehorchankov** [alibaba/MNN#673]
## Hello there! 

I am trying to infer batch of images on Android 9 in the MNN demo application and I get the wrong output from MobileNet. I use branch `master` and did no serious changes to the code. The demo works fine.

## What I've tried

In my toy problem, I changed the tensor batch size to be 4 in `VideoActivity.java`:
 
```
dimensions[0] = 4; // force batch = 1  NCHW  [batch, channels, height, width]
mInputTensor.reshape(dimensions);
mSession.reshape();
```

In the `onPreviewFrame` method I concatenated four `data` byte arrays into a single array and copied the data to tensor, like this:

```
byte[] imgBatch = new byte[data.length * 4];
for (int i = 0; i < imgBatch.length; i++) {
     imgBatch[i] = data[i %  data.length];
}
MNNImageProcess.convertBuffer(imgBatch, imageWidth, imageHeight, mInputTensor, config, matrix);
```

Then, I run the session and retrieved the output:

```
mSession.run();

/**
* get output tensor
*/
MNNNetInstance.Session.Tensor output = mSession.getOutput(null);

float[] result = output.getFloatData();
```

As I run inference on 4 images that are the same, I was expecting to get 4 similar results, so that `result[0] == result[1000]`, but it's false. The `result` length is 4000.

I couldn't find any example of how to do batch inference properly, and my variant doesn't seem to work. Can you help, please?

**Comment by jxt1234** [comment]
Currently, MNNImageProcess.convertBuffer only support one batch

**Comment by yehorchankov** [comment]
Do you plan to add support to more than 1 batch in the future?

**Comment by jxt1234** [comment]
You can use C++ API to do it.
How ever, it's not more efficient to use multi batch for inference.

**Comment by yehorchankov** [comment]
@jxt1234 thanks!

**Comment by mingyunzzu** [comment]
> You can use C++ API to do it. How ever, it's not more efficient to use multi batch for inference.

Why is multi batch computing inefficient using MNN?
Is this true for all operators?

**Comment by jxt1234** [comment]
> You can use C++ API to do it. How ever, it's not more efficient to use multi batch for inference.

The argument is no longer valid in the latest code. Now MNN has solved the bug multi batch can't parrellel compute. Now batch inference time depend on the compute flops of device. If one image has reach the peak flops, then batch image will not more efficient.

**Comment by jxt1234** [comment]
1. The issue's bug has been resolved. Now batch inference time depend on the compute flops of device. If one image has reach the peak flops, then batch image will not more efficient.
2. The get the device's compute peak flops, can use ./run_test.out speed/MatMulBConst
3. Normally GPU has more flops than CPU, you can use opencl instead of CPU to forward.
