### ISSUE TITLE
gemm kernel runs slow on OpenCL when precision_low setted

### ISSUE THREAD

**Issue by Sunnyday2016** [alibaba/MNN#675]
when I switched from precision_normal to precision_low on OpenCL, the gpu execution time for gemm increased dramatically. Using snapdragon profiler, I fount that the l1 cache hitting rate drops from about 50% to 10% when using low precision. Any suggestions why this could happen?

**Comment by jxt1234** [comment]
What's your device?

**Comment by peyer** [comment]
May be you should fix the frequence of GPU firstly if you used RK3399 which has a Mali-T860
