### ISSUE TITLE
About quantized precision loss?

### ISSUE THREAD

**Issue by sunbinbin1991** [alibaba/MNN#676]
I want to know about precision loss?
For a normal model, after quantized , maybe precision lose could reach in which degree?
Is there has doc for this part? or example?

**Comment by jxt1234** [comment]
No-train quantized model for mobilenet v1 about 1% precision loss.

For trained quantized model , no precision loss.
you can ref https://www.yuque.com/mnn/cn/bhz5eu

**Comment by sunbinbin1991** [comment]
Thanks for your kind reply
