### ISSUE TITLE
opencl convert ops

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#678]
请问opencl 中  ConvertExecution.cpp 这个kernel是用来做什么的，我发现当输入和输出type不一样的还时候，譬如nhwc-->nc4hw4   或者 nc4hw4->nhwc 的时候，会添加这一层，但是我看cl文件里面已经有buffer_to_image和image_to_buffer这种kernel操作了啊，为何会出现这个convert层？

**Comment by wangzhaode** [comment]
用来修改channel的排布 方便利用FLOAT4进行SIMD计算
