### ISSUE TITLE
"NV-GLX" missing when using vulkan backend

### ISSUE THREAD

**Issue by cysin** [alibaba/MNN#68]
OS: CentOS 7.6
GPU: 1080Ti + 430.14 driver
VULKAN: 1.1.106.0
Any help is appreciated, Thanks !

```
# ./backendTest.out 
Xlib:  extension "NV-GLX" missing on display ":0".
Invalide device for support vulkan
Invalide device for support vulkan
Test forward type: 0
Tolerance Rate: 0.050000
Open Model (null)
Segmentation fault (core dumped)

```

**Comment by wangqiang1588** [comment]
try https://devtalk.nvidia.com/default/topic/1027746/linux-graphics-debugger/xlib-extension-quot-nv-glx-quot-missing-on-display-quot-1-quot-/ 

maybe it's a driver bug

**Comment by wangqiang1588** [comment]
or https://github.com/amonakov/primus/issues/73

**Comment by wangqiang1588** [comment]
maybe your compute have two GPUs ,one is intel another is Nvidia, program default use device 0 , Intel's GPU is device 0 ,and  Nvidia's GPU is device 1 .please check this

**Comment by cysin** [comment]
Thanks for the reply. The first two links doesn't help. I indeed have two GPUs, but both of them are NV's cards, the same model.

**Comment by wangqiang1588** [comment]
sorry ,the log "Invalide device for support vulkan"  twice, so maybe `enumeratePhysicalDevices` failed ,please modify `const bool VulkanInstance::supportVulkan() ` function ,and print error

**Comment by cysin** [comment]
it's -3.
VK_ERROR_INITIALIZATION_FAILED       = -3

so a vulkan driver compatible issue?

**Comment by wangqiang1588** [comment]
try run `vulkaninfo` on terminate , is it success ?

**Comment by wangqiang1588** [comment]
try  `export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json` maybe the dir is not this ,please change this ,then relaunch `./backendTest.out `

**Comment by cysin** [comment]
vulkaninfo output:
```
# vulkaninfo 
Xlib:  extension "NV-GLX" missing on display ":0".
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.106

/home/lunarg/sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.c:5523: failed with VK_ERROR_INITIALIZATION_FAILED

```
the  json file is located at:
`/etc/vulkan/icd.d/nvidia_icd.json`

I tried:
`export VK_ICD_FILENAMES=/etc/vulkan/icd.d/nvidia_icd.json`

then ran `./backendTest.out`， still no lucky with the same error

**Comment by wangqiang1588** [comment]
if `vulkaninfo`  works incorrect , another application will not work too.

Check if you have vulkan-intel installed, it may prevent Nvidia's vulkan driver from being detected

**Comment by wangqiang1588** [comment]
following https://wiki.archlinux.org/index.php/Vulkan#Nvidia_-_vulkan_is_not_working_and_can_not_initialize

**Comment by wangqiang1588** [comment]
your computer CPU  is Intel desktop  or Xeon ？ usually  desktop CPU has a eGPU.

**Comment by wangqiang1588** [comment]
https://devtalk.nvidia.com/default/topic/1044881/linux/vulkaninfo-vulkaninfo-c-3339-failed-with-vk_error_initialization_failed/

**Comment by wangqiang1588** [comment]
that works for Fedora ,maybe it works on CentOS too, but maybe `dnf` is not exists on CentOS ,so try yum install that.
