### ISSUE TITLE
CI error:  ciscripts/Windows/X64.bat  No such file or directory,  pull request check not finished.

### ISSUE THREAD

**Issue by muare** [alibaba/MNN#680]
$ ciscripts/Windows/X64.bat
The command "ciscripts/Windows/X64.bat" exited with 127.
Done. Your build exited with 1.
/c/Users/travis/.travis/functions: line 109: ciscripts/Windows/X64.bat: No such file or directory

Details:

https://travis-ci.org/github/alibaba/MNN/jobs/661841550?utm_medium=notification&utm_source=github_status

**Comment by jxt1234** [comment]
Fixed
