### ISSUE TITLE
在使用ctdet网络mobilenetv2转onnx再转mnn时报错，看上去是分组卷积有问题

### ISSUE THREAD

**Issue by xingyanan** [alibaba/MNN#681]
/tools/converter/source/optimizer/postconvert/TransformGroupConvolution.cpp:78: Check failed: srcCount % common->group == 0 && common->outputCount % common->group == 0 ==> split group convolution ERROR! ==> 510
@jxt1234

**Comment by xingyanan** [comment]
求助

**Comment by jxt1234** [comment]
有 onnx 模型么

**Comment by xingyanan** [comment]
> 有 onnx 模型么

已发

**Comment by jxt1234** [comment]
已经修复提交，请同步下代码

**Comment by xingyanan** [comment]
> 已经修复提交，请同步下代码

把部分代码改动可以发一下吗，没看到代码更新

**Comment by jxt1234** [comment]
https://github.com/alibaba/MNN/commit/b059c817abfa832956688aeb7e6fac2f18829033

请切到 master 分支更新

**Comment by xingyanan** [comment]
> [b059c81](https://github.com/alibaba/MNN/commit/b059c817abfa832956688aeb7e6fac2f18829033)
> 
> 请切到 master 分支更新

已解决，感谢！！
