### ISSUE TITLE
仿照python案例，为什么我用np.array(output.getData())会多出来一倍的0元素啊

### ISSUE THREAD

**Issue by tbcxx** [alibaba/MNN#685]
hi, i have trouble with getData().
session = model.createSession()
tmp_input = MNN.Tensor((1, 4, 160, 160), MNN.Halide_Type_Float,
in_, MNN.Tensor_DimensionType_Caffe)
input_tensor = model.getSessionInput(session)
print("shape of input:", input_tensor.getShape())
print("input:", len(input_tensor.getData()))
input_tensor.copyFrom(tmp_input)
model.runSession(session)
output_mask = model.getSessionOutput(session)
print("shape of output after copyfrom:", output_mask.getShape())
output_mask.printTensorData()
print('type after copyfrom',type(output_mask.getData()))
print('tuple中0的个数',output_mask.getData().count(0))
data = np.array(output_mask.getData())
print("np size：", data.size)
print("np shape：", data.shape)

Output_mask.printTensorData() shows the correct data and correct shape(1,2,160,160) ,but after data = np.array(output_mask.getData()), np get 51200 0 elements，Later processes cannot continue. 为什么MNN.getData()会多出来一倍的0元素啊?

**Comment by stanleywang8888** [comment]
文档里面写过，内部很多tensor是nc4hw4，维度扩大了
