### ISSUE TITLE
How to bind different sessions to different CPUs clusters?

### ISSUE THREAD

**Issue by forfun1012** [alibaba/MNN#686]
# Platform(Include target platform as well if cross-compiling):  Android RK3399

I have two mnn sessions and I want to run one session on A72 cluster and the second  session on A53 cluster. How should I config the sessions, or compile the library?

**Comment by czy2014hust** [comment]
```bash
# close threadpool，open openmp
cmake -DMNN_USE_THREAD_POOL=OFF ..

# then set one session to be Power_High, and the other be Power_Low
