### ISSUE TITLE
Static library shows resize error on windows.

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#690]
Hi,
I set MNN_BUILD_SHARED_LIBS as OFF and made static library on windows.
The static library shows resize error when inferencing on demo project.
(The forward type is CPU)

Don't support type 12, conv2d/BiasAdd
Don't support type 12, conv2d/BiasAdd
Resize error for conv2d/BiasAdd, code=2

Also I tested https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/MNN 
below error was occurred.

Don't support type 12, 185
Don't support type 12, 185
Resize error for 185, code=2
Can't run session because not resized

I don't know why but if use dynamic library (dll) there is no problem.
Can you check this?
Also after linking MNN.lib below error was occurred when build MNNV2Basic.out.

Scanning dependencies of target MNNV2Basic.out
[ 93%] Building CXX object CMakeFiles/MNNV2Basic.out.dir/tools/cpp/MNNV2Basic.cpp.obj
MNNV2Basic.cpp
[ 93%] Building CXX object CMakeFiles/MNNV2Basic.out.dir/tools/cpp/revertMNNModel.cpp.obj
revertMNNModel.cpp
[ 93%] Linking CXX executable MNNV2Basic.out.exe
LINK: command "C:\PROGRA~2\MICROS~4\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\MNNV2Basic.out.dir\objects1.rsp /out:MNNV2Basic.out.exe /implib:MNNV2Basic.out.lib /pdb:C:\Dev\git\MNN\build_x64_static\MNNV2Basic.out.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console MNN.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:MNNV2Basic.out.exe.manifest" failed (exit code 1120) with the following output:
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl MNN::AutoTime::AutoTime(int,char const *)" (__imp_??0AutoTime@MNN@@QEAA@HPEBD@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl MNN::AutoTime::~AutoTime(void)" (__imp_??1AutoTime@MNN@@QEAA@XZ) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl MNN::Tensor::Tensor(class MNN::Tensor const *,enum MNN::Tensor::DimensionType,bool)" (__imp_??0Tensor@MNN@@QEAA@PEBV01@W4DimensionType@01@_N@Z) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl MNN::Tensor::~Tensor(void)" (__imp_??1Tensor@MNN@@QEAA@XZ) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl MNN::Tensor::copyFromHostTensor(class MNN::Tensor const *)" (__imp_?copyFromHostTensor@Tensor@MNN@@QEAA_NPEBV12@@Z) referenced in function "public: void __cdecl <lambda_da6a2c68a47c44238d1604823c0b7d3a>::operator()(void *)const " (??R<lambda_da6a2c68a47c44238d1604823c0b7d3a>@@QEBAXPEAX@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: bool __cdecl MNN::Tensor::copyToHostTensor(class MNN::Tensor *)const " (__imp_?copyToHostTensor@Tensor@MNN@@QEBA_NPEAV12@@Z) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class MNN::Tensor * __cdecl MNN::Tensor::createHostTensorFromDevice(class MNN::Tensor const *,bool)" (__imp_?createHostTensorFromDevice@Tensor@MNN@@SAPEAV12@PEBV12@_N@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum MNN::Tensor::DimensionType __cdecl MNN::Tensor::getDimensionType(void)const " (__imp_?getDimensionType@Tensor@MNN@@QEBA?AW4DimensionType@12@XZ) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl MNN::Tensor::size(void)const " (__imp_?size@Tensor@MNN@@QEBAHXZ) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl MNN::Tensor::elementSize(void)const " (__imp_?elementSize@Tensor@MNN@@QEBAHXZ) referenced in function "void __cdecl dumpTensor2File(class MNN::Tensor const *,char const *)" (?dumpTensor2File@@YAXPEBVTensor@MNN@@PEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl MNN::Tensor::width(void)const " (__imp_?width@Tensor@MNN@@QEBAHXZ) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl MNN::Tensor::height(void)const " (__imp_?height@Tensor@MNN@@QEBAHXZ) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: int __cdecl MNN::Tensor::channel(void)const " (__imp_?channel@Tensor@MNN@@QEBAHXZ) referenced in function "public: bool __cdecl <lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??R<lambda_4f41d6f2d7b9b135e189f7c474bbf2c2>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl MNN::OperatorInfo::name(void)const " (__imp_?name@OperatorInfo@MNN@@QEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: static bool __cdecl std::_Invoker_ret<bool,0>::_Call<class <lambda_9a84bb0dc1904e9c652d0cbe34e0a9f5> &,class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class MNN::OperatorInfo const *>(class <lambda_9a84bb0dc1904e9c652d0cbe34e0a9f5> &,class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class MNN::OperatorInfo const * &&)" (??$_Call@AEAV<lambda_9a84bb0dc1904e9c652d0cbe34e0a9f5>@@AEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@PEBVOperatorInfo@MNN@@@?$_Invoker_ret@_N$0A@@std@@SA_NAEAV<lambda_9a84bb0dc1904e9c652d0cbe34e0a9f5>@@AEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@1@$$QEAPEBVOperatorInfo@MNN@@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: float __cdecl MNN::OperatorInfo::flops(void)const " (__imp_?flops@OperatorInfo@MNN@@QEBAMXZ) referenced in function "public: bool __cdecl <lambda_cc8e7b37ddd0ed6553f89b827e3d351b>::operator()(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class MNN::OperatorInfo const *)const " (??R<lambda_cc8e7b37ddd0ed6553f89b827e3d351b>@@QEBA_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@PEBVOperatorInfo@MNN@@@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class MNN::Interpreter * __cdecl MNN::Interpreter::createFromFile(char const *)" (__imp_?createFromFile@Interpreter@MNN@@SAPEAV12@PEBD@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl MNN::Interpreter::~Interpreter(void)" (__imp_??1Interpreter@MNN@@QEAA@XZ) referenced in function "public: void * __cdecl MNN::Interpreter::`scalar deleting destructor'(unsigned int)" (??_GInterpreter@MNN@@QEAAPEAXI@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class MNN::Session * __cdecl MNN::Interpreter::createSession(struct MNN::ScheduleConfig const &)" (__imp_?createSession@Interpreter@MNN@@QEAAPEAVSession@2@AEBUScheduleConfig@2@@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl MNN::Interpreter::resizeSession(class MNN::Session *)" (__imp_?resizeSession@Interpreter@MNN@@QEAAXPEAVSession@2@@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl MNN::Interpreter::releaseModel(void)" (__imp_?releaseModel@Interpreter@MNN@@QEAAXXZ) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum MNN::ErrorCode __cdecl MNN::Interpreter::runSession(class MNN::Session *)const " (__imp_?runSession@Interpreter@MNN@@QEBA?AW4ErrorCode@2@PEAVSession@2@@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum MNN::ErrorCode __cdecl MNN::Interpreter::runSessionWithCallBack(class MNN::Session const *,class std::function<bool __cdecl(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &,class std::function<bool __cdecl(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &,bool)const " (__imp_?runSessionWithCallBack@Interpreter@MNN@@QEBA?AW4ErrorCode@2@PEBVSession@2@AEBV?$function@$$A6A_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z@std@@1_N@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: enum MNN::ErrorCode __cdecl MNN::Interpreter::runSessionWithCallBackInfo(class MNN::Session const *,class std::function<bool __cdecl(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class MNN::OperatorInfo const *)> const &,class std::function<bool __cdecl(class std::vector<class MNN::Tensor *,class std::allocator<class MNN::Tensor *> > const &,class MNN::OperatorInfo const *)> const &,bool)const " (__imp_?runSessionWithCallBackInfo@Interpreter@MNN@@QEBA?AW4ErrorCode@2@PEBVSession@2@AEBV?$function@$$A6A_NAEBV?$vector@PEAVTensor@MNN@@V?$allocator@PEAVTensor@MNN@@@std@@@std@@PEBVOperatorInfo@MNN@@@Z@std@@1_N@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class MNN::Tensor * __cdecl MNN::Interpreter::getSessionInput(class MNN::Session const *,char const *)" (__imp_?getSessionInput@Interpreter@MNN@@QEAAPEAVTensor@2@PEBVSession@2@PEBD@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class MNN::Tensor * __cdecl MNN::Interpreter::getSessionOutput(class MNN::Session const *,char const *)" (__imp_?getSessionOutput@Interpreter@MNN@@QEAAPEAVTensor@2@PEBVSession@2@PEBD@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class MNN::Tensor *,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class MNN::Tensor *> > > const & __cdecl MNN::Interpreter::getSessionInputAll(class MNN::Session const *)const " (__imp_?getSessionInputAll@Interpreter@MNN@@QEBAAEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVTensor@MNN@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVTensor@MNN@@@std@@@2@@std@@PEBVSession@2@@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl MNN::Interpreter::resizeTensor(class MNN::Tensor *,class std::vector<int,class std::allocator<int> > const &)" (__imp_?resizeTensor@Interpreter@MNN@@QEAAXPEAVTensor@2@AEBV?$vector@HV?$allocator@H@std@@@std@@@Z) referenced in function "int __cdecl test_main(int,char const * * const)" (?test_main@@YAHHQEAPEBD@Z)
MNNV2Basic.out.exe : fatal error LNK1120: 27 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

Above error was also no problem when building shared lib.

**Comment by 604977823** [comment]
Ubuntu18.04 gcc7.04环境下编译出现同样的问题;

使用动态库编译生成测试程序运行正常;
使用静态库可以编译程序 但是运行时会报一些Op找不到;Don't support type 12...

使用master代码库;没有修改代码;只修改了CMakelist.TXT使用静态库;

**Comment by mygmyg** [comment]
遇到同样的问题；即使自己复制原文件，然后自己根据项目重写cmake,也出现同样的错误；

**Comment by 604977823** [comment]
这个问题几天前追踪了一下;发现了问题原因; 有一个临时解决办法; 

看到有好几个人遇到同样的问题;

就回答一下;

Linux环境下默认使用静态库会出现OP链接不完整情况;
临时的解决办法是;
在Cmake生成的编译环境的link.txt 中
在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive

就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive

几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
就可以把所有用到的OP算子链接到执行程序中;

**Comment by 604977823** [comment]
刚好看到有人发现官方关于静态库的使用说明了;
 https://www.yuque.com/mnn/en/faq#CTrE4

前几天没有看文档FAQ;
害的自己找了两天才解决问题;

坑呀!

**Comment by GHLab** [comment]
@604977823 
Are you mentioned below right?

Usage of static library
If you build mnn as static library, when link to your own library , you should add flags like this: 
-Wl,--whole-archive MNN -Wl,--no-whole-archive

I didn't see that guide.
I will try to build again. (I have no window system now)
Thank you!

**Comment by GHLab** [comment]
@604977823 
I built it again but same result.
Also, I think the flags are already added here https://github.com/alibaba/MNN/blob/master/CMakeLists.txt#L477

**Comment by 604977823** [comment]
https://github.com/alibaba/MNN/blob/master/CMakeLists.txt&nbsp;flag is not work！
i try it already ！
i think ，it is a bug but i do not know why！
so i try chang the link.txt then find it is work success！

发自我的iPhone


------------------ Original ------------------

**Comment by xieydd** [comment]
Same error, add `-Wl,--whole-archive MNN -Wl,--no-whole-archive` not working.

**Comment by GHLab** [comment]
@xieydd @604977823 Today, I resolved this issue. @604977823 You right and I misunderstood. That flag is not build flag. It's just linker flag so I added that flag into my project and I checked the issue can't be reproducible. 
Add below linker flag. 
-Wl,--whole-archive MNN -Wl,--no-whole-archive
And if you are using clang on OSX, you can add below flag.
-Wl,-force_load MNN
