### ISSUE TITLE
mnn int8 量化问题

### ISSUE THREAD

**Issue by 205418367** [alibaba/MNN#691]
量化过程出错，使用的是最近两天编译的mnn，模型是mixnet。float模型测试准确率正常。
[15:21:35] /home/cli/project/mnn/tools/quantization/calibration.cpp:142: Input Data Format ERROR!The 397's input is not ready
Resize error for 397, code=3
ComputeFeatureRange: 100.00 %an't run session because not resizedt resized
CollectFeatureDistribution: 100.00 %an't run session because not resized
Can't find tensors for 398
Segmentation fault (core dumped)
(mnn) cli@aries:~/project/mnn/build$ ./quantized.out mixnet_s.mnn mixnet_s_quan.mnn pretreatConfig.json

[test.zip](https://github.com/alibaba/MNN/files/4348023/test.zip)

**Comment by czy2014hust** [comment]
修改[此处](https://github.com/alibaba/MNN/blob/9f1555ffdde9df84faf41dcf6beecba8f0e227f4/tools/quantization/calibration.cpp#L136)
```bash
-    } else if (inputTensorDataFormat == MNN::MNN_DATA_FORMAT_NC4HW4) {
+    } else if (inputTensorDataFormat == MNN::MNN_DATA_FORMAT_NC4HW4 || inputTensorDataFormat == MNN::MNN_DATA_FORMAT_NCHW) {
```
