### ISSUE TITLE
ToTrainQuant中 ”Conv" 和 “Convolution”对应不上

### ISSUE THREAD

**Issue by ArnoldLiuIC** [alibaba/MNN#694]
![image](https://user-images.githubusercontent.com/45121592/77064751-0b08aa80-6a1b-11ea-920e-11968b6c90c4.png)
![image](https://user-images.githubusercontent.com/45121592/77064864-3ab7b280-6a1b-11ea-9ce9-5c70404eb8a5.png)

**Comment by jxt1234** [comment]
原始代码有么？ 像是 Convolution 没被解析出来的原因。

**Comment by ArnoldLiuIC** [comment]
原始代码稍后发给你 我看了源代码的逻辑 pipelineModule的构造函数中，每个expr都会被解析成一个exprModule，同时exprModule的构造函数中依赖EnumNameOpType对moduleType进行set。在文件MNN_generated.h中的枚举值只有"Convolution" 没有 ”Conv"。但是后面的判断又是基于字段"Conv",导致分支一直进不去。
应该不是模型的问题，tensorflow的模型用的就是最基础的conv2D算子

**Comment by ArnoldLiuIC** [comment]
2.1.8版本

**Comment by yyfcc17** [comment]
将mnn推理模型中的卷积解析为可训练卷积，得到的结果卷积应该被解析为ConvModule而不应该是ExprModule，可能你用法不对

**Comment by ArnoldLiuIC** [comment]
核心代码是这样的

auto inputOutputs= loadMap("file_path");
auto varpOutputs = Variable::mapToSequence(inputOutputs.second)
auto varpInputs = Variable::mapToSequence(inputInputs.second)
MNN::Train::Transformer::turnModelToTrainable(MNN::Train::Transformer::TrainConfig())
        ->onExecute(varpOutputs);
auto module = new MNN::Train::PipelineModule(varpInputs, varpOutputs);
module->toTrainQuant();

这样写对吗 @yyfcc17 @jxt1234 谢谢

**Comment by yyfcc17** [comment]
不太对，抱歉这里没有改过来，请参考文档 https://www.yuque.com/mnn/cn/bhz5eu

**Comment by jxt1234** [comment]
MNN::Train::Transformer::turnModelToTrainable(MNN::Train::Transformer::TrainConfig())
->onExecute(varpOutputs); 
auto module = new MNN::Train::PipelineModule(varpInputs, varpOutputs);

这两句去掉，换成 auto module = MNN::Train::PipelineModule::extract(varpInputs, varpOutputs, true);
