### ISSUE TITLE
多输出节点模型，推理结果为nan

### ISSUE THREAD

**Issue by changshuai5** [alibaba/MNN#696]
模型转换过程结果输出如下：
delta_s1/Tanh, Type = TanH
Outputs: local_delta_stage1/Tanh, Type = TanH
Outputs: dense_3/Relu, Type = ReLU
Outputs: delta_s2/Tanh, Type = TanH
Outputs: local_delta_stage2/Tanh, Type = TanH
Outputs: dense_6/Relu, Type = ReLU
Outputs: delta_s3/Tanh, Type = TanH
Outputs: local_delta_stage3/Tanh, Type = TanH
Outputs: dense_9/Relu, Type = ReLU

**Comment by jxt1234** [comment]
可否具体一些? 什么输入什么模型?
