### ISSUE TITLE
静态库

### ISSUE THREAD

**Issue by Jamyw7g** [alibaba/MNN#698]
能够考虑编译静态库的选项

**Comment by jxt1234** [comment]
支持的，打开如下选项：
cmake -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_SEP_BUILD=OFF

**Comment by 604977823** [comment]
静态编译使用楼上的建议就可以编译出静态库;

补充一点;
Linux环境下默认使用静态库会出现OP链接不完整问题;
临时的解决办法是;
在Cmake生成的编译环境的link.txt 中
在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive

就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive

几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
就可以把所有用到的OP算子链接到执行程序中;

**Comment by Jamyw7g** [comment]
> 静态编译使用楼上的建议就可以编译出静态库;
> 
> 补充一点;
> Linux环境下默认使用静态库会出现OP链接不完整问题;
> 临时的解决办法是;
> 在Cmake生成的编译环境的link.txt 中
> 在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive
> 
> 就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive
> 
> 几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
> 使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
> 就可以把所有用到的OP算子链接到执行程序中;

静态库确实出现op不完整，程序运行报错没有这些op，找了很久没有解决方案就又换回了framework

**Comment by mygmyg** [comment]
> 静态编译使用楼上的建议就可以编译出静态库;
> 
> 补充一点;
> Linux环境下默认使用静态库会出现OP链接不完整问题;
> 临时的解决办法是;
> 在Cmake生成的编译环境的link.txt 中
> 在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive
> 
> 就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive
> 
> 几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
> 使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
> 就可以把所有用到的OP算子链接到执行程序中;
采用此方案能解决静态库运行问题，请问下，是什么Ｃ＋＋特性导致这个问题的

**Comment by alanwang4523** [comment]
可在 CMakeList.txt 中 libMNN.a 前后如下操作
target_link_libraries(
                    fd_mnn
                    
                    -Wl,--whole-archive
                    ${MNN_LIB_PATH}/libMNN.a
                    -Wl,--no-whole-archive
)

**Comment by zhanglaplace** [comment]
![image](https://user-images.githubusercontent.com/12178974/153409193-91f503ea-3af1-4823-bde3-876ab1088bc9.png)
静态库出现了这个问题

**Comment by zhanglaplace** [comment]
> ![image](https://user-images.githubusercontent.com/12178974/153409193-91f503ea-3af1-4823-bde3-876ab1088bc9.png) 静态库出现了这个问题 ![image](https://user-images.githubusercontent.com/12178974/153409263-07b64499-3549-46c2-ae41-7eb26ab3655e.png)

这边在jni内部写了jni_onload的函数，编译MNN的时候注释掉source/utils/JNIhelper.cpp的函数即可
![image](https://user-images.githubusercontent.com/12178974/153533249-7d30b759-0b8d-4a7a-91d2-9b5715b13850.png)
