### ISSUE TITLE
caffe multi input size error

### ISSUE THREAD

**Issue by nullian** [alibaba/MNN#70]
My caffe model is multi input like this

```
input: "data"
input: "landmark_position"
input_dim: 1
input_dim: 3
input_dim: 60
input_dim: 60
input_dim: 1
input_dim: 1
input_dim: 2
input_dim: 5
```
when i convert this model to mnn and load it with C++ api
```
    const string modelPath = "model/20190422110551.mnn";

    MNN::Interpreter* interpreter = MNN::Interpreter::createFromFile(modelPath.c_str());
    if(interpreter == nullptr) {
        cout << "create net failed" << endl;
        return -1;
    }

    cout << "create net Successful" << endl;

    MNN::ScheduleConfig scheduleConfig;
    scheduleConfig.type = MNN_FORWARD_CPU;

    MNN::Session* sess = interpreter->createSession(scheduleConfig);
    if(sess == nullptr) {
        cout << "create session failed" << endl;
    }

    cout << "create session successful" << endl;

    auto image = interpreter->getSessionInput(sess, "data");
    auto landmark = interpreter->getSessionInput(sess, "landmark_position");

    MNN_PRINT("_______________________________________________________________________\n");

    MNN_PRINT("image: n:%d , c:%d, h:%d, w: %d\n", image->batch(), image->channel(), image->height(), image->width());
    MNN_PRINT("landmark: n:%d , c:%d, h:%d, w: %d\n", landmark->batch(), landmark->channel(), landmark->height(), landmark->width());
```

and the log 
```
_______________________________________________________________________
image: n:1 , c:3, h:60, w: 60
landmark: n:1 , c:3, h:60, w: 60
```
also, i use MNNDump2Json.out to convert binary model to json format, input layer 
```
{ main_type: Input, main: 
{ dims: 
[ 1, 3, 60, 60, 1, 1, 2, 5 ]
 }
, name: "data", outputIndexes: 
[ 0 ]
, type: Input }
, 
{ main_type: Input, main: 
{ dims: 
[ 1, 3, 60, 60, 1, 1, 2, 5 ]
 }
, name: "landmark_position", outputIndexes: 
[ 1 ]
, type: Input }
```

Is there something wrong? How can i solve it,thanks for any suggestion.

**Comment by nullian** [comment]
Solve this error by change
```
input: "data"
input: "landmark_position"
input_dim: 1
input_dim: 3
input_dim: 60
input_dim: 60
input_dim: 1
input_dim: 1
input_dim: 2
input_dim: 5
```
to
```
layer { 
 name: "data" 
 type: "Input" 
 top: "data" 
 input_param { shape: { dim: 1 dim: 3 dim: 60 dim: 60 } } 
}

layer { 
 name: "landmark_position" 
 type: "Input" 
 top: "landmark_position" 
 input_param { shape: { dim: 1 dim: 1 dim: 2 dim: 5 } } 
} 
```

but, new error happens when create session:
```
Error for /home/yuanhao/osc/MNN/source/shape/ShapeConcat.cpp, 17
mnnSample: /home/yuanhao/osc/MNN/source/shape/ShapeConcat.cpp:17: virtual bool MNN::ConcatSizeComputer::onComputeSize(const MNN::Op*, const std::vector<MNN::Tensor*>&, const std::vector<MNN::Tensor*>&) const: Assertion `res' failed.
```

**Comment by czy2014hust** [comment]
Check whether [Concat] have two inputs

**Comment by nullian** [comment]
change ShapeConcat.cpp and CPUConcat code MNN_ASSERT(inputs.size() >= 2); to MNN_ASSERT(inputs.size() >= 1); solve my issue

**Comment by YongyuG** [comment]
> Solve this error by change
> 
> ```
> input: "data"
> input: "landmark_position"
> input_dim: 1
> input_dim: 3
> input_dim: 60
> input_dim: 60
> input_dim: 1
> input_dim: 1
> input_dim: 2
> input_dim: 5
> ```
> 
> to
> 
> ```
> layer { 
>  name: "data" 
>  type: "Input" 
>  top: "data" 
>  input_param { shape: { dim: 1 dim: 3 dim: 60 dim: 60 } } 
> }
> 
> layer { 
>  name: "landmark_position" 
>  type: "Input" 
>  top: "landmark_position" 
>  input_param { shape: { dim: 1 dim: 1 dim: 2 dim: 5 } } 
> } 
> ```
> 
> but, new error happens when create session:
> 
> ```
> Error for /home/yuanhao/osc/MNN/source/shape/ShapeConcat.cpp, 17
> mnnSample: /home/yuanhao/osc/MNN/source/shape/ShapeConcat.cpp:17: virtual bool MNN::ConcatSizeComputer::onComputeSize(const MNN::Op*, const std::vector<MNN::Tensor*>&, const std::vector<MNN::Tensor*>&) const: Assertion `res' failed.
> ```

Hi, how did you solve multi input things,
I got bug at the stage of ```createSession```
did you change your model??? How come your two jsons of models look differences
