### ISSUE TITLE
python版量化重训练工具

### ISSUE THREAD

**Issue by HaoLiuHust** [alibaba/MNN#701]
有看到MNN支持对量化后的模型进行重训练，但是demo是C++的，比较复杂，有没有计划基于现有的成熟训练框架进行支持，比如pytorch或tensorflow

**Comment by jxt1234** [comment]
MNN-Python 训练量化版本近期内会放出 pip 包，可以先看 pymnn/demo 

考虑后续维护的问题，不会基于 pytorch 和 tensorflow 支持

**Comment by liwei46** [comment]
期待中

**Comment by jxt1234** [comment]
已经更新 python 版本 API
