### ISSUE TITLE
关于convert层

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#703]
我看 当输入是nhwc 和nc4hw4的时候会多出个convert层，我想请问都是image类型的nhwc和nc4hw4有什么区别啊？一定要做转换吗？

**Comment by czy2014hust** [comment]
convert层就是做内存布局调整的，一些算子是按nc4hw4做实现优化的，所以当是其他输入的时候，必须做内存布局调整

**Comment by curehabit** [comment]
> convert层就是做内存布局调整的，一些算子是按nc4hw4做实现优化的，所以当是其他输入的时候，必须做内存布局调整

你好！我在使用mnn时，发现ConvertTensor非常多，每层的前后都有ConvertTensor。使用timeProfile查看，ConvertTensor占用了推理时间的57.9%。还有ConvertTensor是NCHW->NCHW的操作。请问这个ConvertTensor能关掉或者有其他优化方案可选吗？
