### ISSUE TITLE
cc1plus: error: unknown value ‘armv8.2a+fp16’ for -march

### ISSUE THREAD

**Issue by zaiyebuheniwanle** [alibaba/MNN#704]
cc1plus: error: unknown value ‘armv8.2a+fp16’ for -march
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a; did you mean ‘armv8.2-a’?
source/backend/arm82/CMakeFiles/MNNARM82.dir/build.make:62: recipe for target 'source/backend/arm82/CMakeFiles/MNNARM82.dir/Arm82Backend.cpp.o' failed
make[2]: *** [source/backend/arm82/CMakeFiles/MNNARM82.dir/Arm82Backend.cpp.o] Error 1
CMakeFiles/Makefile2:1490: recipe for target 'source/backend/arm82/CMakeFiles/MNNARM82.dir/all' failed
make[1]: *** [source/backend/arm82/CMakeFiles/MNNARM82.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

这该怎么改啊

**Comment by czy2014hust** [comment]
改为armv8.2-a+fp16试下，估计有的编译器不兼容那样
另外你在什么平台上编译的？

**Comment by zaiyebuheniwanle** [comment]
> CMakeLists.txt里没有`armv8.2a+fp16`，是`armv8.2-a+fp16`啊

谢谢， 我手动把CMakeLists.txt里的armv8.2a+fp16改成了armv8.2-a+fp16

**Comment by czy2014hust** [comment]
本来不就是`armv8.2-a+fp16`吗
