### ISSUE TITLE
Ubuntu 18.04上编译模型转换工具失败

### ISSUE THREAD

**Issue by LiuShengchieh** [alibaba/MNN#705]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04.1 LTS

# Github版本:
# Github Version:
0.2.2.1
commit id: a8fcb75fe52f779e56bf9c86a2c7de56a95ccd0c

# 编译方式:
# Compiling Method
cd MNN
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true
make -j20

# 编译日志:
# Build Log:
[ 85%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUReverseSequence.cpp.o
[ 85%] Building CXX object tools/converter/CMakeFiles/MNNConverterOpt.dir/source/optimizer/tfextra/TFSoftsign.cpp.o
[ 85%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o
[ 85%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUScale.cpp.o
[ 85%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUScatterNd.cpp.o
In file included from /root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.cpp:46:0:
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.hpp:37:22: error: 'uint32_t' was not declared in this scope
 float MNNGetCPUFlops(uint32_t number);
                      ^~~~~~~~
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.hpp:37:22: note: suggested alternative: 'u_int32_t'
 float MNNGetCPUFlops(uint32_t number);
                      ^~~~~~~~
                      u_int32_t
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.cpp:250:22: error: redefinition of 'float MNNGetCPUFlops'
 float MNNGetCPUFlops(uint32_t number) {
                      ^~~~~~~~
In file included from /root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.cpp:46:0:
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.hpp:37:7: note: 'float MNNGetCPUFlops' previously defined here
 float MNNGetCPUFlops(uint32_t number);
       ^~~~~~~~~~~~~~
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.cpp:250:22: error: 'uint32_t' was not declared in this scope
 float MNNGetCPUFlops(uint32_t number) {
                      ^~~~~~~~
/root/peter/autoTest/sj/MNN/source/backend/cpu/CPURuntime.cpp:250:22: note: suggested alternative: 'u_int32_t'
 float MNNGetCPUFlops(uint32_t number) {
                      ^~~~~~~~
                      u_int32_t
CMakeFiles/MNNCPU.dir/build.make:1067: recipe for target 'CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 85%] Built target MNNConverterOpt
CMakeFiles/Makefile2:413: recipe for target 'CMakeFiles/MNNCPU.dir/all' failed
make[1]: *** [CMakeFiles/MNNCPU.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 85%] Built target MNNConverterTF
[ 85%] Built target MNNConverterCaffe
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by czy2014hust** [comment]
Please refer to this [PR](https://github.com/alibaba/MNN/pull/700/files)

**Comment by alexcruz0202** [comment]
Hi, @LiuShengchieh 
I have built the MNN Converter with version 0.2.2.1, but its version is 0.2.1.5git.
What do i have mistake?
