### ISSUE TITLE
error: unknown value 'armv8.2-a+dotprod' for -march

### ISSUE THREAD

**Issue by shuaishentao** [alibaba/MNN#706]
编译出现MNN/source/backend/cpu/arm/arm64/MNNAddBias.S:1:0: error: unknown value 'armv8.2-a+dotprod' for -march错误。请问是哪里的问题？

**Comment by czy2014hust** [comment]
你是怎么编译的？

**Comment by shuaishentao** [comment]
> 你是怎么编译的？

RK3399上，CMakeLists中MNN_BUILD_QUANTOOLS、MNN_EVALUATION、MNN_BUILD_CONVERTER改为ON。
之后./schema/generate.sh；mkdir build；cd build；cmake ..；make

上个月下载的版本可以编过，我拉最新的代码就编不过了

**Comment by czy2014hust** [comment]
先在[这个地方](https://github.com/alibaba/MNN/blob/a8fcb75fe52f779e56bf9c86a2c7de56a95ccd0c/source/backend/cpu/arm/CMakeLists.txt#L8)改为**OFF**
后面我们修改一下
