### ISSUE TITLE
Gpu to cpu copy seems very slow 

### ISSUE THREAD

**Issue by zuoshaobo** [alibaba/MNN#71]
I use CopyToHostTensor to get the output data, my output is 256*320*4,it consume about 10ms, is it  normal?

**Comment by li-qing** [comment]
It depends on copying data size and GPU-CPU memory bandwidth.

Besides, if you do not wait for GPU inference to be finished (through runSessionWithCallback with sync), copyToHostTensor has to wait for inference to be finished first.
