### ISSUE TITLE
build error due to  protoc version

### ISSUE THREAD

**Issue by kaishijeng** [alibaba/MNN#711]
My ubuntu has protoc:
 protoc --version
libprotoc 3.7.1

gcc:

gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

I got the following errors protoc related errors: Any idea why it happens?

MNN/build/tools/converter/onnx.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is

Thanks,

**Comment by Lininggggggg** [comment]
我刚刚遇到了你这种情况，是protocbuf版本的问题，你电脑里有多个版本冲突了
