### ISSUE TITLE
动态库能成功运行，静态库编译成功，运行时错误：Resize error for 245, code=2

### ISSUE THREAD

**Issue by mygmyg** [alibaba/MNN#713]
使用MNN进行编译动态库（MNN_BUILD_SHARED_LIBS＝ON or OFF）,并链接到工程中， 运行时动态库版本正常运行，静态库版本运行报错;

版本：release 0.2.1.6 ,最新的版本也有相同问题；

```
Don't support type  12, 245　（ iter == map->end）
Resize error for 245, code=2

```

ldd demo 的输出显示，其他依赖文件都相同

**Comment by Guanmoyu** [comment]
参考这个：https://www.yuque.com/mnn/en/faq#CTrE4

**Comment by 604977823** [comment]
Windows环境不清楚;
Linux环境下我的解决办法是;
在Cmake生成的编译环境的link.txt 中
在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive

就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive

几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
就可以把所有用到的OP算子链接到执行程序中;

**Comment by mygmyg** [comment]
> Windows环境不清楚;
> Linux环境下我的解决办法是;
> 在Cmake生成的编译环境的link.txt 中
> 在libMNN.a的前后增加 -Wl,--whole-archive 和 -Wl,--no-whole-archive
> 
> 就像这样;-Wl,--whole-archive libMNN.a -Wl,--no-whole-archive
> 
> 几天前追踪过;发现是静态链接库时;C++的原因;导致静态库中的OP只有一个会链接到程序中;没有将全部OP链接到程序;
> 使用编译选项-Wl,--whole-archive 和 -Wl,--no-whole-archive;
> 就可以把所有用到的OP算子链接到执行程序中;

谢谢解答，这应该能解决问题，但编译环境中中多个

**Comment by qizhen816** [comment]
windows下用vs cmake的话 这个可以链接：
`SET_TARGET_PROPERTIES(facemnn PROPERTIES LINK_FLAGS_RELEASE "/WHOLEARCHIVE:MNN")
`

**Comment by Travis-Lee** [comment]
编译库所在的 CMakeLists.txt 中 需要加入,example 如下：

target_link_libraries( DetectFace “-Wl,--whole-archive”  ${CMAKE_CURRENT_BINARY_DIR}/libMNN.a "-Wl,--no-whole-archive")
注意：
DetectFace （自己编译的库名，此处只是一个举例）
 ${CMAKE_CURRENT_BINARY_DIR}/libMNN.a （需要加入自己编译后的libMNN.a的相对路径，根据自己的情况来定）
重点就是在此内容的前后加入：
-Wl,--whole-archive   ${CMAKE_CURRENT_BINARY_DIR}/libMNN.a  -Wl,--no-whole-archive

**Comment by feixuedudiao** [comment]
这样设置好像OpenCL的缓存无法生成。
