### ISSUE TITLE
macOS Catalina, QT使用MNN闪退

### ISSUE THREAD

**Issue by Jamyw7g** [alibaba/MNN#718]
#闪退部分日志

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [34486]

VM Regions Near 0:
--> 
    __TEXT                 000000010fadc000-000000010fb2c000 [  320K] r-x/r-x SM=COW  /Users/USER/*/Camera.app/Contents/MacOS/Camera

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   MNN                           	0x000000010fb4cf1d MNN::Interpreter::createMultiPathSession(std::__1::vector<MNN::ScheduleConfig, std::__1::allocator<MNN::ScheduleConfig> > const&) + 13
1   MNN                           	0x000000010fb4d249 MNN::Interpreter::createSession(MNN::ScheduleConfig const&) + 537
2   USER.Camera              	0x000000010fae3df2 Widget::Widget(QWidget*) + 658 (widget.cpp:25)
3   USER.Camera              	0x000000010fae53ad Widget::Widget(QWidget*) + 29 (widget.cpp:30)
4   USER.Camera              	0x000000010fae3abf main + 63 (main.cpp:8)
5   libdyld.dylib                 	0x00007fff6eea0cc9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff6f0a0b68 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff6f0a0b68 start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	0x00007fff6f0a0b68 start_wqthread + 0

Thread 4:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff6efe1e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68a7ab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68a7a9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68a7a7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68a7a1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f0a5109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f0a0b8b thread_start + 15

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff6efe1e36 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff68a7ab16 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff68a7a9b2 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff68a7a7c4 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff68a7a1e4 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff6f0a5109 _pthread_start + 148
6   libsystem_pthread.dylib       	0x00007fff6f0a0b8b thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff6efe1e4e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff6ee47b6b _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff6ee47f97 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff6ee55795 _dispatch_worker_thread + 284
4   libsystem_pthread.dylib       	0x00007fff6f0a5109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6f0a0b8b thread_start + 15

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff6efe1e4e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff6ee47b6b _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff6ee47f97 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff6ee55795 _dispatch_worker_thread + 284
4   libsystem_pthread.dylib       	0x00007fff6f0a5109 _pthread_start + 148
5   libsystem_pthread.dylib       	0x00007fff6f0a0b8b thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000600001bbf088  rcx: 0x0000000000000000  rdx: 0x0000000000000022
  rdi: 0x0000000000000000  rsi: 0x00007ffee0123888  rbp: 0x00007ffee0123870  rsp: 0x00007ffee01237e0
   r8: 0x0000000000000001   r9: 0x00000000000007fb  r10: 0x00007ffee0123ca8  r11: 0x000000010fb4d030
  r12: 0x0000600001bbf020  r13: 0x0000000000000000  r14: 0x00007ffee01238f8  r15: 0x00007ffee01238c0
  rip: 0x000000010fb4cf1d  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     2
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

**Comment by jxt1234** [comment]
是否是以静态库形式链接 mnn 的，需要加额外选项

**Comment by Jamyw7g** [comment]
> 是否是以静态库形式链接 mnn 的，需要加额外选项

不是静态库，使用framework

**Comment by jxt1234** [comment]
像是模型文件读取错误，先确认下路径是否正确吧
