### ISSUE TITLE
About iOS Demo

### ISSUE THREAD

**Issue by huachao1001** [alibaba/MNN#72]
iOS Demo Error:

>  File not found: /Users/username/Library/Developer/Xcode/DerivedData/playground-dhsbckxauliwjygzcaocfvkgytgp/Build/Products/Release-iphoneos/MNN/libMNN.a

**Comment by li-qing** [comment]
failed to reproduce the bug. could you provide detail info like compile log?

**Comment by yurunyang1998** [comment]
I meet this problem as well . how did you fix it ?
