### ISSUE TITLE
设置 zAxisProtected 的动机和意义

### ISSUE THREAD

**Issue by DreamChaserMXF** [alibaba/MNN#721]
https://github.com/alibaba/MNN/blob/9167b9bc7091d492fa29a904549cc144761fe381/source/backend/metal/MNNMetalContext.h#L46

虽然有注释，但还是不太清楚设置这个字段的动机和意义，不知道是否有人能帮忙解答一下？

**Comment by jxt1234** [comment]
Metal 运行时需要对原先的循环数 n 拆分为 group size 和 local size 两级，最终的循环数为 group size * local size ，有可能比 n 大，需要 shader 代码中做限制保护。
zAxisProtected 则表示 shader 代码中是否对第三个维度做了保护，如果没有，需要拆分时保证  group size * local size = n
