### ISSUE TITLE
ios cpu 速度问题

### ISSUE THREAD

**Issue by reason4** [alibaba/MNN#722]
利用mnn运行人脸模型：https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB
在pc的cpu上速度很快，但是在ios cpu上慢了将近20倍，arm上使用mnn有额外需要注意的吗？比如编译的时候打开什么选项，或者其它原因呢？

**Comment by jxt1234** [comment]
你 ios 上的编译方式是? 另外确认下你的手机是否是 省电模式吧

**Comment by reason4** [comment]
ios上源码编译的动态库，手机不是省电模式哦

**Comment by reason4** [comment]
要开启MNN_ARM82才会有较大提速吗

**Comment by jxt1234** [comment]
你是怎么编译的？

**Comment by nsl2014fm** [comment]
同样遇到这样的问题，我的是在安卓上比pc慢了快20倍。 @reason4 你有解决这个问题吗？
