### ISSUE TITLE
a question of image normalization

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#73]
问一个低端问题，大神看到了抽空回两句哈。 图像归一化，我看源码里面是用config.means 和 config.normal控制的，默认应该是0,1。
疑问一，图片读入的时候就已经归一化到了0-1之间对吧？
疑问二，给的示例中，Android的这两个值是默认的，ios是设定的means是rgb的均值然后乘以normal0.017，这是因为两个平台读图有差异还是Android没有写那一部分？（我没做过移动端，这个问题可能比较low，见谅）。
疑问三、如果我想用像素值减均值除以方差的归一化方式，是不是要自己写或者是normal，means的值该怎么设置？

**Comment by jxt1234** [comment]
一：一般图片解码不会归一化，而是解成 RGBA / BGR 之类的格式
二：Android 有多个 demo，其中用 mobilenet v2 作图像识别的那个也是有写 normal 和 mean 的
三：means 设成均值，normal 设成方差的倒数

**Comment by ChisenZhang** [comment]
> 一：一般图片解码不会归一化，而是解成 RGBA / BGR 之类的格式
> 二：Android 有多个 demo，其中用 mobilenet v2 作图像识别的那个也是有写 normal 和 mean 的
> 三：means 设成均值，normal 设成方差的倒数

一，图片单纯解码，不设置手动设置mean和normal的话，只是将0-255的像素值变成了float类型对吧
二，mobilenet v2的demo，我也看到了，设置的都是固定值，不是应该针对每张图计算它的均值，方差做归一化吗？ MNN有没有相关的函数，我翻了翻好像没有翻到
三，matrix的postscale方法，安卓端输入的参数写的是网络长宽分别除以真实图像长宽NW/W, NH/H, IOS端写的是(W-1)/(NW-1),(H-1/(NH-1))，这是不同平台的处理缩放的方式不同还是有什么特殊作用？ 在demo的exec里面还看到了1.0/NW, 1.0/NH 没看明白是什么个意思？

**Comment by jxt1234** [comment]
一、一般是解成 uint8_t 的
二、归一化的均值和方差是模型训练阶段对所有图片统计而得，因此是固定的。针对每张图去算的话应该结果不会正确，也没看到有这么算的。
三、(W-1) 是为了作边界对齐。demo 中的写法采用了若干次坐标空间变换去实现，跟 OpenGL 坐标空间转换类似

**Comment by ChisenZhang** [comment]
> 一、一般是解成 uint8_t 的
> 二、归一化的均值和方差是模型训练阶段对所有图片统计而得，因此是固定的。针对每张图去算的话应该结果不会正确，也没看到有这么算的。
> 三、(W-1) 是为了作边界对齐。demo 中的写法采用了若干次坐标空间变换去实现，跟 OpenGL 坐标空间转换类似

二、tf.image.per_image_standardization() 这个函数不就是对每张图片做减均值除标准差的操作吗？训练的时候这样，推理的时候也应该这样做吧
三、除了减一之外，他们分子分母是颠倒的。 感觉做个resize弄的好复杂

**Comment by jxt1234** [comment]
二、实际推理的时候不会对图像这么做的，都是减固定均值和乘固定normal，跟训练不一样。
三、因为移动端上一般来说不只有缩放，还有旋转、变形等各种各样操作，所以CV模块是按2D渲染引擎设计的，方便处理很复杂的仿射变换。

**Comment by ChisenZhang** [comment]
> 二、实际推理的时候不会对图像这么做的，都是减固定均值和乘固定normal，跟训练不一样。
> 三、因为移动端上一般来说不只有缩放，还有旋转、变形等各种各样操作，所以CV模块是按2D渲染引擎设计的，方便处理很复杂的仿射变换。

嗯， 知道了   谢谢！  再问一个问题，只调用matrix.postScale()对图像做resize，应该没问题吧；我看到exec示例代码里面先将图像坐标resize到0-1，然后又将图像移到y轴中心做翻转，然后再resize到原始大小，没看出来这样做啥目的，感觉也没有resize到网络需要的尺寸
