### ISSUE TITLE
使用tf2.1的mobilenetv2生成的tflite模型，0.2.1.9版本的MNNConvertor不能将该mobilenetv2模型转化成MNN模型

### ISSUE THREAD

**Issue by jah10527** [alibaba/MNN#733]
使用tf2.1的mobilenetv2生成的tflite模型，0.2.1.9版本的MNNConvertor不能将该mobilenetv2模型转化成MNN模型。提示Pad操作不支持。

生成tflite模型代码
```
import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.applications import MobileNetV2

model = MobileNetV2(input_shape=[224, 224,3], alpha=1, include_top=False, weights=None)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
open("mbv2.tflite", "wb").write(tflite_model)
```

使用指令 MNN-0.2.1.9/build# ./MNNConvert -f TFLITE --modelFile mbv2.tflite --MNNModel rf.mnn --bizCode biz
报错
MNN-0.2.1.9/tools/converter/source/tflite/PadTflite.cpp:50: Check failed: false ==> Unknown Pad Operator
Aborted

Looking forward to any response, thanks.

**Comment by jxt1234** [comment]
0.2.2.1 呢 ? 如果还有问题模型发一下吧

**Comment by jah10527** [comment]
> 0.2.2.1 呢 ? 如果还有问题模型发一下吧

一样的问题
MNN-0.2.2.1/tools/converter/source/tflite/PadTflite.cpp:50: Check failed: false ==> Unknown Pad Operator

模型在此
https://jah10527.github.io/res/mbv2.tflite

多谢

**Comment by jxt1234** [comment]
好吧，是最近修复的，同步到 0.2.2.2 吧，已经修正
