### ISSUE TITLE
模型量化时Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zefan7564** [alibaba/MNN#735]
# 平台(如果交叉编译请再附上交叉编译目标平台):  ubuntu16.04
# Platform(Include target platform as well if cross-compiling):  

# Github版本:0.2.2.2
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_SHARED_LIBS=false -DMNN_BUILD_QUANTOOLS=on
```

# 编译日志:
# Build Log:

```
CMake Warning (dev) at 3rd_party/flatbuffers/CMakeLists.txt:6 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
    PROJECT_VERSION_TWEAK
This warning is for project developers.  Use -Wno-dev to suppress it.

fatal: Not a git repository (or any of the parent directories): .git
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/yzf/Downloads/MNN-0.2.2.1/build
-- x86_64: Open SSE
-- Onnx: /home/yzf/Downloads/MNN-0.2.2.1/build/tools/converter/onnx.pb.h;/home/yzf/Downloads/MNN-0.2.2.1/build/tools/converter/onnx-operators.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yzf/Downloads/MNN-0.2.2.1/build
```

模型量化过程中报如下错误：
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/quantized.cpp:21: >>> modelFile: NL_FaceFeatureExt_v5.mnn
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/quantized.cpp:22: >>> preTreatConfig: preprocessConfig.json
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/quantized.cpp:23: >>> dstFile: NL_FaceFeatureExtQuan_v52.mnn
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/quantized.cpp:50: Calibrate the feature and quantize model...
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/calibration.cpp:109: Use feature quantization method: ADMM
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/calibration.cpp:110: Use weight quantization method: ADMM
[14:58:08] /home/yzf/Downloads/MNN-20200407/MNN/tools/quantization/Helper.cpp:100: used image num: 1
Segmentation fault (core dumped)

使用参数为：
{
    "format":"BGR",
    "mean":[
        127.5,
        127.5,
        127.5
    ],
    "normal":[
        0.0078125,
        0.0078125,
        0.0078125
    ],
    "width":96,
    "height":112,
    "path":"/home/yzf/NL/SDKTools/SDK/model/caffe/FaceImage",
    "used_image_num":100,
    "feature_quantize_method":"ADMM",
    "weight_quantize_method":"ADMM"
}

**Comment by czy2014hust** [comment]
If you use *ADMM* quantization method, decrease the number of calibration images. Set it to be 32, then try again.

**Comment by zefan7564** [comment]
设置成32还是报“Segmentation fault”错误，不管使用ADMM还是KL均报错，使用“ac84e11”版本编译出的quantized.out量化时正常

**Comment by czy2014hust** [comment]
- 更新下代码试下
- 如果还有问题的话，可以把模型发下

**Comment by zefan7564** [comment]
[Sphereface.prototxt.zip](https://github.com/alibaba/MNN/files/4473521/Sphereface.prototxt.zip)

更新了最新的代码还是一样，模型为Sphereface

**Comment by czy2014hust** [comment]
> [Sphereface.prototxt.zip](https://github.com/alibaba/MNN/files/4473521/Sphereface.prototxt.zip)
> 
> 更新了最新的代码还是一样，模型为Sphereface

caffemodel?

**Comment by zefan7564** [comment]
链接: https://pan.baidu.com/s/1kV5iOK0jDRCHy0uGtWIu2w 提取码: 2h9g 
已上传网盘

**Comment by czy2014hust** [comment]
- 网盘模型下载不了(没有客户端)
- 最新代码测试[模型](https://github.com/wy1iu/sphereface/blob/master/train/code/sphereface_deploy.prototxt)没有问题

> 看了下你的模型跟[这个模型](https://github.com/wy1iu/sphereface/blob/master/train/code/sphereface_deploy.prototxt)差不多，代码更新，用最新代码重新转换模型，再量化！
