### ISSUE TITLE
How to add TensorArray(in tensorflow) Op to the MNN?

### ISSUE THREAD

**Issue by yjiangling** [alibaba/MNN#737]
It seems that the Op of TensorArray is not included in Supported Ops list. How can I solve it? Could anyone give me some help? Thanks a lot!

**Comment by yjiangling** [comment]
In fact, many ASR model trained by TenosrFlow contain the TensorArray Op, especially in decode step. It's very unconvient to convert pb model to mnn model without this Op supported.

**Comment by czy2014hust** [comment]
What kind of model has *TensorArray*?
Did you freeze your model(pb)?

**Comment by yjiangling** [comment]
> What kind of model has _TensorArray_?
> Did you freeze your model(pb)?

Yes, It is a RNN-Transducer model, an ASR model, the TensorArray Op is used in decoding step to save the decod results. I trainde it by TensorFlow, and freezed it to pb model, but when I convert it to mnn model, It failed, and give the following message:

![捕获](https://user-images.githubusercontent.com/42861880/78973155-e303f700-7b41-11ea-95a0-bac9df0076dd.PNG)

The error message is so little that I can't track it. But I guess it most likely caused by TensorArray Op in my model. How can I solve it? It almost drive me crazy, could U please give me some help? Thank you very much.

**Comment by jxt1234** [comment]
Currently TensorArray is not easily to support.  Please avoid the op or wait us to solve them

**Comment by yjiangling** [comment]
> Currently TensorArray is not easily to support. Please avoid the op or wait us to solve them

OK， Thank you for the reply, I'll close this question.
