### ISSUE TITLE
MNN lose accuracy is too serious！

### ISSUE THREAD

**Issue by sankexin** [alibaba/MNN#738]
![45e1eb980ee6c54689886ba98ac40bab](https://user-images.githubusercontent.com/33318353/78876888-97d6df00-7a82-11ea-954e-f45896bbe112.png)
![042477066e943d4c9b667df64a8e6b01](https://user-images.githubusercontent.com/33318353/78876903-9d342980-7a82-11ea-8ac4-6ad9cfdf7eec.png)
Detection frame dropped from three to two，and the tenth digit starts to go wrong.The accuracy of mnn is not as high as that of ncnn, and the accuracy loss of ncnn is almost negligible.MNN needs a lot of improvement！

**Comment by jxt1234** [comment]
Maybe your pretreat and post treat has error?
