### ISSUE TITLE
转换TFLite模型的时候报出"BinaryOP Should not has fused_activation_function"

### ISSUE THREAD

**Issue by coollofty** [alibaba/MNN#739]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Windows+WSL

# Github版本:
# Github Version:
0.2.1.5git

# 编译方式:
# Compiling Method
gcc 7.4.0

# 编译日志:
编译无问题

运行MNNConvert转换一个TFLite模型的时候，报出如下错误：

Check failed: addOption->fused_activation_function == tflite::ActivationFunctionType_NONE ==> BinaryOP Should not has fused_activation_function

请问有没有解决办法？

**Comment by gttiankai** [comment]
遇到同样的问题

**Comment by jxt1234** [comment]
64246f6a45820ebc763e3bf55d50dd1ec85ad5f8 修正
