### ISSUE TITLE
operation requirements

### ISSUE THREAD

**Issue by li-qing** [alibaba/MNN#74]
### Known Op Requirements For TensorFlow
- AddN
- Equal (#42 )
- SparseToDense (#42 )
> Ops(TensorArrayxxx) is from tensorflow **Detection** postprocess API, which are not necessary to support, because [DetectionPostProcess](https://github.com/alibaba/MNN/blob/master/source/backend/cpu/CPUDetectionPostProcess.cpp) is supported.
- ~~TensorArrayGatherV3 (#462)~~
- ~~TensorArrayGatherV3 (#462)~~
- ~~TensorArrayReadV3 (#462)~~
- ~~TensorArrayScatterV3 (#462)~~
- ~~TensorArraySizeV3 (#462)~~
- ~~TensorArrayV3 (#462)~~
- ~~TensorArrayWriteV3 (#462)~~

- ~~Pad (@rkshuai, @563816752 / #120 )~~
- ~~FusedBatchNorm (@RobertAuditore )~~
- ~~ResizeBilinear+UInt8 (@WenguoLi )~~
- MirrorPad (@alcaster )
- OneHot (@alcaster )
- ~~FakeQuantWithMinMaxVars (#146 @liguiyuan)~~
- ~~FusedBatchNormV3 (@leo-nullptr)~~
- ~~LeakyRelu (@KanaSukita)~~
- ~~StrideSlice (@MaybeShewill-CV )~~
- ~~Iterator/IteratorGetNext (@JiangtianPan )~~
- ~~Merge (@jimdinunzio)~~
- ~~ResizeBicubic (@jimdinunzio)~~
- ~~Switch (@jimdinunzio)~~
- ~~FusedPadConv2D (@jimdinunzio)~~
- LogicalAnd (@JiangtianPan, @ChristineRYY)
- LogicalOr (@ChristineRYY)
- ~~flatten (@ChisenZhang )~~
- ~~GRU Dense (@liziru )~~
 
### Known Op Requirements For TensorFlow Lite
- Mul (@valwang )
- Transpose (@Teragump )
- Fully_Connected (@Teragump )
- LogisticTflite (@GrayRui )
- AddV2 (@yinguobing)
- SUB (@yinguobing)
- RELU (@wikipedia2008)
- Iterator/IteratorGetNext (@JiangtianPan )

### Known Op Requirements For ONNX
- ~~PRelu (#9 )~~
- ~~LeakyReLU (@yizhaoyanbo, #144 @zhyj3038 )~~
- Neg (@ChisenZhang )
- ~~Mul (@563816752)~~
- ~~ReLU6 (@563816752 )~~
- ~~ELU (@MoonBunnyZZZ, @DHNicoles  )~~
- ~~ReduceMean (@alcaster )~~
- ~~Slice (#144 @zhyj3038)~~
- ~~Sigmoid (#144 @zhyj3038)~~
- ~~ReduceSum (#144 @zhyj3038)~~
- ~~Split (@doodoo0006 )~~
- Expand (@leo-nullptr)
- ~~MatMul (@leo-nullptr, #257 @BokyLiu, @liuwuliuyun )~~
- MaxRoiPool (@92ypli)
- ~~LSTM (@Cheneng)~~
- ~~Pad (@yizhaoyanbo)~~
- ~~Slice (@pfeatherstone)~~
- ~~Cast (@pfeatherstone)~~
- ~~ConvTranspose (@bobzhang123, @yizhaoyanbo)~~

### Known Op Requirements For Caffe
- route (@RobertAuditore)
- power (@OOYueshenOO)
- Upsample (@cyf518)

**If you have any op requirements, you could write a comment to let us know, even if it's mentioned above.  Please specify where the op comes from(Tensorflow, Caffe, or ONNX) like this:**

```
Framework:
...

Not Supported OP:
...
```

**Comment by CodingBoO** [comment]
power op

**Comment by 92ypli** [comment]
shuffle op

**Comment by xiaohaipeng** [comment]
Constant op

**Comment by czy2014hust** [comment]
Please specify where the op comes from(Tensorflow, Caffe, or ONNX)
like this:

- Not Supported OP:
...
- Framework
...

**Comment by yizhaoyanbo** [comment]
**Not Supported OP:**
pad
clip
LeakReLU

**Framework:**
ONNX

**Comment by ChisenZhang** [comment]
Not Supported OP:
Cast
Framework
ONNX

**Comment by valwang** [comment]
Not Supported OP:
18        Mul

Framework:
TFLITE

**Comment by 92ypli** [comment]
Not Supported OP:
shufflenet

Framework:
pytorch or onnx

**Comment by li-qing** [comment]
> Not Supported OP:
> shufflenet
> 
> Framework:
> pytorch or onnx

ShuffleNet is a network not an op

**Comment by 92ypli** [comment]
Sorry, my meaning is ShuffleChannel.

**Comment by czy2014hust** [comment]
ShuffleChannel is NOT a OP in pytorch、onnx or tensorflow! By the way tensorflow-shufflenet is tested. You can try.

**Comment by czy2014hust** [comment]
> Sorry, my meaning is ShuffleChannel.

ShuffleChannel is NOT a OP in pytorch、onnx or tensorflow! By the way tensorflow-shufflenet is tested. You can try.

**Comment by ChisenZhang** [comment]
not support OP:
Neg
Framework:
ONNX

**Comment by rkshuai** [comment]
Not Supported OP:
pad

Framework:
tensorflow

**Comment by rkshuai** [comment]
- Not Supported OP:

pad

- Framework:

tensorflow

**Comment by Teragump** [comment]
Not Supported OP:
Transpose
Fully_Connected

Framework:
TensorFlow Lite

**Comment by 92ypli** [comment]
Framework:
onnx

Not Supported OP:
Transpose

**Comment by RobertAuditore** [comment]
Framework:
Tensorflow

Not Supported OP:
FusedBatchNorm

Framework:
caffe

Not Supported OP:
route (yolo2)

**Comment by 563816752** [comment]
Op Requirements For ONNX
Mul 
ReLU6

**Comment by tanhui2975** [comment]
Framework:
onnx

Not Supported OP:
Transpose

**Comment by crj0322** [comment]
Not Supported OP:
FusedBatchNormV3

Framework:
Tensorflow

**Comment by WenguoLi** [comment]
**Not Supported OP**:
ResizeBilinear  Uint8 quantized Mode

**Error**:
Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [16:44:02] /home/apuser/deeplearning/alibaba/MNN/tools/converter/source/tflite/ResizeBilinear.cpp:16: Check failed: !quantizedModel ==> 

**Framework**:
Tensorflow

**Comment by MoonBunnyZZZ** [comment]
Framework:
ONNX(pytorch)

Not Supported OP:
ELU

**Comment by kunyao2015** [comment]
Framework:
onnx

Not Supported OP:
Transpose

**Comment by li-qing** [comment]
@92ypli @tanhui2975 @kunyao2015 
Transpose for ONNX is supported in latest commit.

**Comment by li-qing** [comment]
@yizhaoyanbo  @563816752 
Pad, Clip for ONNX  are supported in latest commit.

**Comment by alcaster** [comment]
Not Supported OP:
ReduceMean

Framework:
ONNX(pytorch)

**Comment by alcaster** [comment]
Not Supported OP:
MirrorPad, OneHot

Framework:
Tensorflow

**Comment by GrayRui** [comment]
Framework:
TFLITE

Not Supported OP:
LogisticTflite

**Comment by xindongzhang** [comment]
Framework:
Pytorch --> ONNX

Not Supported OP:
Permute, dims >= 5

**Comment by xindongzhang** [comment]
Frameword:
tensorflow and tflite (object detection api)

Not Supported OP:
concat, when using OpenCL as backend.

Specifically, we test mobilenet-ssd using MNN OpenCL. And there are **"The Creator Don't support type 10, concat"**

What's more, when the OpenCL-based inference finished, we get different results compared with CPU-based inference.

**Comment by doodoo0006** [comment]
Framework:
onnx
Not Supported OP:
Split

**Comment by DHNicoles** [comment]
Framework:
TensorFlow

Not Supported OP:
ELU

**Comment by leo-nullptr** [comment]
Framework:
ONNX

Not Supported OP:
Expand

**Comment by leo-nullptr** [comment]
Framework:
ONNX

Not Supported OP:
MatMul

**Comment by leo-nullptr** [comment]
Framework:
Tensorflow

Not Supported OP:
FusedBatchNormV3, IteratorGetNext, OneShotIterator, swish_f32

**Comment by 92ypli** [comment]
Framework:
onnx
Not Supported OP:
MaxRoiPool

**Comment by leo-nullptr** [comment]
Framework:
ONNX

Not Supported OP:
Slice (For H & W, not only C)

**Comment by yinguobing** [comment]
Framework: TensorFlow Lite
OPs: `AddV2`

**Comment by laohur** [comment]
插一句 “outpus”拼写错误
[https://github.com/alibaba/MNN/blob/master/doc/OpList.md](url)

**Comment by Cheneng** [comment]
Framework:
onnx
Not Supported OP:
LSTM

**Comment by yizhaoyanbo** [comment]
@li-qing 
Framework:
onnx
Not Supported OP:
Pad

[I have converted onnx to mnn sucessfully. But the following error occurs when creating session:  Currently padding NC4HW4 don't support channel padding, The Creator Don't support type 45, 19, Resize error for 19, code=2]

**Comment by KanaSukita** [comment]
Framework:
tensorflow
Not Supported OP:
LeakyRelu

**Comment by OOYueshenOO** [comment]
not support OP:
power
Framework:
caffe

**Comment by key-word** [comment]
> Framework:
> TFLITE
> 
> Not Supported OP:
> LogisticTflite
> 
> Error:
> ./tools/coverter/source/tflite/LogisticTflite.cpp:15: Check failed: quantizedModel ==> LogisticTflite TODO(float)
Is this problem solved？

**Comment by wikipedia2008** [comment]
Framework:
TFLITE

Not Supported OP:
RELU

**Comment by MaybeShewill-CV** [comment]
Framework:
TF

Not Supported OP:
StrideSlice

**Comment by JiangtianPan** [comment]
Not Supported OP：
Iterator
IteratorGetNext

Framework：
TensorFlow
TFLITE

**Comment by jimdinunzio** [comment]
Framework:
TensorFlow

Not Supported OP:
Merge
ResizeBicubic
Switch
FusedPadConv2D (Less Important to me)

**Comment by JiangtianPan** [comment]
Framework: 
TensorFlow
TFLITE

Not Supported OP:
Assert
LogicalAnd
(in DeepLabv3+ model)

**Comment by bobzhang123** [comment]
Not Supported OP:
ConvTranspose

Framework:
ONNX

**Comment by jiarenyf** [comment]
- Not Supported OP ~ Framework ~ CPU/GPU

- GatherV2 ~ Tensorflow ~ OPENCL

- Transpose ~ Tensorflow ~ OPENCL

**Comment by cyf518** [comment]
MNN/tools/converter/source/caffe/caffeConverter.cpp:143: Don't support type [ Upsample ]

**Comment by ChisenZhang** [comment]
not support OP:
flatten
Framework:
tensorflow

**Comment by ChristineRYY** [comment]
Framework:
TensorFlow
TFLITE

Not Supported OP:
Assert
LogicalAnd
LogicalOr
(in DeepLabv3+ model)

**Comment by jiarenyf** [comment]
Not Supported OP ~ Framework ~ CPU/GPU

GatherV2 ~ Tensorflow ~ OPENCL

Transpose ~ Tensorflow ~ OPENCL

**Comment by liuwuliuyun** [comment]
Framework:
ONNX

Not Supported OP:
MatMul

**Comment by liziru** [comment]
Framework:
tensorflow

Not Supported OP:
GRU Dense

**Comment by zhazhachua** [comment]
TensorFlow
Assert,LogicalAnd,CTCGreedyDecoder,SparseToDense,All,Enter,Exit,LoopCond,Merge,NextIteration,Round,Switch,TensorArrayGatherV3,TensorArrayReadV3,TensorArrayScatterV3,TensorArraySizeV3,TensorArrayV3,TensorArrayWriteV3,FakeQuantWithMinMaxVars,TFLite_Detection_PostProcess,AddN,NonMaxSuppressionV4,FloorMod

**Comment by ZhuLingfeng1993** [comment]
Framework:
caffe

Not Supported OP:
ShuffleChannel

Currently, I find ShuffleChannel is implement with ConvertTensor + Reshape + Transpose, which is very  inefficient!

**Comment by yizhaoyanbo** [comment]
Framework:  
ONNX

Not Supported Op:
ConvTranspose

**Comment by Chanbluky** [comment]
Framework:
Pytorch

Not Supported Op:
Corner pooling

**Comment by lucwan** [comment]
Framework:
TensorFlow

Not Supported Op:
TensorArrayGatherV3,TensorArrayReadV3,TensorArrayScatterV3,TensorArraySizeV3,TensorArrayV3,TensorArrayWriteV3,FakeQuantWithMinMaxVars,TFLite_Detection_PostProcess,AddN,NonMaxSuppressionV4,FloorMod

**Comment by threeds** [comment]
Framework:
Pytorch

Not Supported Op:
pixelshuffle

**Comment by AlphaGoWisdom** [comment]
Freamework：Tensorflow
Not Supported Op：
BatchToSpaceND and SpaceToBatchND

**Comment by zyf001** [comment]
Framework:
ONNX

Not Supported Op:
Tanh

**Comment by Guanmoyu** [comment]
Framework:
Caffe

Not Supported Op:
DeformableConvolution

Caffe GPU implement:
[https://github.com/zhanglonghao1992/Deformable-ConvNets-v1-v2-caffe](url)
and Paddle implement:
[https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/deformable_conv_op.h](url)

Thanks!

**Comment by Naville** [comment]
Framework:
Tensorflow 

Op:
PlaceholderWithDefault

**Comment by xinyidaren** [comment]
Framework:
Tensorflow

Op:
TRANSPOSE_CONV

**Comment by xinyidaren** [comment]
Framework:
Tensorflow2.0

Op:
Unsample

**Comment by wujiexiaowugui** [comment]
Framewor：
Tensorflow Lite

op:
split

**Comment by ffffwyy** [comment]
Framework:
caffe

Not Supported OP:
concat(singal input)
scale(multi input)

**Comment by JerryDeepl** [comment]
Not Supported OP:
ConvTranspose (depthwise mode )
//group == in_channels == out_channels

Framework:
ONNX

**Comment by dbxinj** [comment]
Framework:
ONNX

Not Supported Op:
ReduceL2

**Comment by forfun1012** [comment]
Framework:
Caffe

Not Supported Op:
Power
Axpy

**Comment by ywlife** [comment]
Framework:
ONNX

Not Supported Op:
MatMul
Badcase: the dimensional matrix of 8781 * 3 * 32 is multiplied by a dimensional matrix of 32 * 1

**Comment by nullptr-leo** [comment]
Framework:
Tensorflow

Not Supported Op:
FusedResizeAndPadConv2D

**Comment by bylanhao** [comment]
Known Op Requirements For TensorFlow
AddN
Equal (#42 )
SparseToDense (#42 )
Ops(TensorArrayxxx) is from tensorflow Detection postprocess API, which are not necessary to support, because DetectionPostProcess is supported.

TensorArrayGatherV3 (#462)

TensorArrayGatherV3 (#462)

TensorArrayReadV3 (#462)

TensorArrayScatterV3 (#462)

TensorArraySizeV3 (#462)

TensorArrayV3 (#462)

TensorArrayWriteV3 (#462)


你们说上述算子可以不实现，DetectionPostProcess 可以实现。实际操作的时候，DetectionPostProcess 怎么用？带这些算子的模型怎么转换？
谢谢。

**Comment by bylanhao** [comment]
mfcc算子打算实现吗？

**Comment by pure-water** [comment]
Hi
Regarding to DetectionPostProcess , we can say the CPU backend in MNN has the support of it Howver the MNN Converter does not seem to deal with it  (with crashing ...) 

Are you expecting the model to manually re-factor to MNN friendly form or any other convient way? 

Regards
Yao

**Comment by valwang** [comment]
Hi:

I am trying to update to another network architecture recently for better performance.
And I will try to use MNN converter to see what will happen then. Thanks!

Br
wang

**Comment by XieRuicheng** [comment]
Framework:
TFLite

Not Supported OP:
Pad

**Comment by DamonsJ** [comment]
should support Instance Normalization , Layer Normalization, Batch Normalization and iLN

**Comment by ronjian** [comment]
用最新的master分支编译mnnconvert， 在转换.onnx模型的时提示 NOT_SUPPORTED_OP: [ ConvTranspose ]， 不过可以生成.mnn文件。 请问到底支持ConvTranspose吗？

**Comment by un-knight** [comment]
请问 multi layer LSTM 是否准备支持？

**Comment by xiexuliunian** [comment]
Framework:

onnx

Not Supported OP:

Asymmetrical pads

**Comment by Teragump** [comment]
Framework:
Caffe

Not Supported OP:
ConvolutionDepthwise

**Comment by ZhanHN** [comment]
Not Supported OP:
Tile

Framework:
Caffe

**Comment by nidetaoge** [comment]
Not Supported OP:
Tensorflow::Resampler

Framework:
tensorflow

See this issue:
https://github.com/alibaba/MNN/issues/725

Thx so much!

**Comment by dragen1860** [comment]
Framework:
PyTorch/ONNX

Not Supported OP:
Deformable Convolution

**Comment by coollofty** [comment]
Framework:
TensorflowLite

Not Supported OP:
PRELU

**Comment by dzyjjpy** [comment]
> Framework:
> PyTorch/ONNX
> 
> Not Supported OP:
> Deformable Convolution

+1  dcn op needed for YOLACT++

**Comment by jelloit** [comment]
Framework:
Pytorch/ONNX

Not Supported OP:
MatMul with batch size

**Comment by JesonYYY** [comment]
Framework:
TensorflowLite

Not Supported OP:
PRELU

**Comment by Echosanmao** [comment]
Framework:
TensorflowLite

Not Supported OP:
DIV

**Comment by Kepnu4** [comment]
Framework:
Pytorch/ONNX

Not Supported OP:
NonZero

**Comment by 871699406** [comment]
Framework:
TensorflowLite

Not Supported OP:
ResizeNearestNeighbor

**Comment by buqing2009** [comment]
Framework:
ONNX

Not Supported OP:
And
GatherElements
No
Range
ReduceL1
Slice
Where

**Comment by buqing2009** [comment]
Framework:
ONNX

Not Supported OP:
And
GatherElements
No
Range
ReduceL1
Slice
Where

**Comment by dragen1860** [comment]
Framework:
PyTorch/ONNX

Not Supported OP:
RoiAlign

**Comment by songyanbei** [comment]
Framework:
PyTorch/ONNX

Not Supported OP:
RoiAlign
AliasWithName
BBoxTransform
BoxWithNMSLimit
GenerateProposals

**Comment by lcaikk1314** [comment]
Framework:
tflite

Not Supported OP:
SPACE_TO_BATCH_ND

**Comment by 121786404** [comment]
> Framework:
> TensorflowLite
> 
> Not Supported OP:
> PRELU

https://raw.githubusercontent.com/aqua1907/Gesture-Recognition/master/models/palm_detection_without_custom_op.tflite

**Comment by shwanliu** [comment]
not support OP:
Flatten
Framework:
ONNX（pytorch）

**Comment by TianzhongSong** [comment]
opencl ArgMax (caffe)

**Comment by MingLunHan** [comment]
cosine_similiarity for onnx

**Comment by sudowind** [comment]
Framework:
ONNX (Pytorch)

Not supported OPs:
Atan
Nonzero

**Comment by FrankyCao** [comment]
Not Supported OP:
Tensorflow::ComplexAbs 
Tensorflow::IRFFT 
Tensorflow::If 
Tensorflow::PlaceholderWithDefault
Tensorflow::RFFT 

Framework:
tensorflow

**Comment by 649453932** [comment]
tensorflow lite
NOT_SUPPORTED_OP: [ EXPAND_DIMS ]

**Comment by NiuCY** [comment]
Framework:
ONNX (Pytorch)

Not supported OPs:
ConvTranspose 3D

**Comment by friskyliu** [comment]
Framework:
TensorflowLite

Not Supported OP:
PRELU

**Comment by lvZic** [comment]
Framework:
TensorflowLite

Not Supported OP:
PRELU
