### ISSUE TITLE
onnx到mnn不支持gru的转换

### ISSUE THREAD

**Issue by tangjie2062** [alibaba/MNN#742]
我现在在做ＯＣＲ的工程化，有一个模块用到了GRU,能支持一下么

**Comment by jxt1234** [comment]
模型可以发一下?

**Comment by tangjie2062** [comment]
?贵司已经安排人支持了,多谢

________________________________
发件人: jxt1234 <notifications@github.com>
发送时间: 2020年4月15日 15:27
收件人: alibaba/MNN
抄送: 唐杰(深度学习实验室); Author
主题: [外部邮件] Re: [alibaba/MNN] onnx到mnn不支持gru的转换 (#742)


模型可以发一下?

―

**Comment by RobotGF** [comment]
所以现在支持GRU了嘛？

**Comment by jxt1234** [comment]
最新代码已经支持

**Comment by RobotGF** [comment]
> 最新代码已经支持

 Check it out ==> 269 has empty input, the index is 4 
269是GRU RNNSequenceGRU

**Comment by hatinenshiro** [comment]
> 最新代码已经支持

使用MNNConvert转换onnx模型，GRU的initial hidden state不会出现在mnn模型的inputTensors中（onnx模型中，GRU的initial hidden state是显示输入的）？

**Comment by hatinenshiro** [comment]
> 最新代码已经支持

使用MNNConvert转换onnx模型，GRU的initial hidden state不会出现在mnn模型的inputTensors中？（onnx模型中，GRU的initial hidden state是显示输入的）

**Comment by hatinenshiro** [comment]
> 最新代码已经支持

使用MNNConvert转换onnx模型，GRU的initial hidden state不会出现在mnn模型的inputTensors中？（onnx模型中，GRU的initial hidden state是显式输入的）

**Comment by jxt1234** [comment]
会和 onnx 一致，上面那个 has empty input 不需要关注.
