### ISSUE TITLE
[onnx->mnn] MNN Reshape error: 4096 -> 4096

### ISSUE THREAD

**Issue by fcqfcq** [alibaba/MNN#744]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by fcqfcq** [comment]
MNNConverter Version: 0.2.1.5git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
[14:51:42] /build/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 4
Start to Optimize the MNN Net...
Reshape error: 4096 -> 4096
Convolution should know weight shape infromation!
Convert Onnx's Op 499 , type = Conv, failed, may be some node is not const
Segmentation fault (core dumped)

**Comment by fcqfcq** [comment]
./MNNConvert -f ONNX --modelFile  model.onnx      --MNNModel test.mnn --bizCode MNN

**Comment by jxt1234** [comment]
Can you provide your model ?

**Comment by jxt1234** [comment]
Please update code and test. Maybe the error has been fixed.

**Comment by quanticsolutions** [comment]
I having the same error:

Error for compute convolution shape, need channel = 58, input channel = 1
Compute Shape Error for input.56
Reshape error: 313664 -> 185600
Compute Shape Error for onnx::Transpose_441
Invalid Tensor, the session may not be ready
Error: can't find output: output
Segmentation fault
