### ISSUE TITLE
MNN耗时的几个问题：1）实际部署中15s后耗时陡增  2）8bit量化后速度更慢

### ISSUE THREAD

**Issue by zmdsjtu** [alibaba/MNN#745]
平台：高通845

问题1：什么原因会导致耗时陡增？
一开始400帧（约15s）推理速度很快（约7ms），之后稳定提升到10ms
请问什么原因会导致耗时陡增？ 

问题2：模型量化后openCL运行更慢，CPU也略慢，量化模型什么情况下会更慢，目前是不是只支持CPU？
【现象1】模型8bit量化后openCL@安卓845的速度从10ms增加到20ms
【现象2】另一个8bit模型CPU单核@安卓845从3ms增加到4ms

**Comment by jxt1234** [comment]
1、可能是设备发热降频了，建议把 powermode 设成 normal 或者用单线程
2、打开ARM82 宏[  cmake -DMNN_ARM82=true ] ，用 64 位 so 运行
