### ISSUE TITLE
MNN_Arm82 执行结果错误

### ISSUE THREAD

**Issue by dreadlord1984** [alibaba/MNN#746]
库版本 release 0.2.2.2
硬件 parsed /proc/cpuinfo Hardware = "MT6785V/CC"   readminote8pro
情况描述：
编译mnn库，打开MNN_ARM82开关，生成libMNN.so和libMNN_Arm82.so。编译测试程序push到手机上运行，运行过程提示“[MNNInfo]:*************set armv82 backend*************”，应该是Arm82生效了，该模型执行时间降低了一半，但行结果数值明显不对（设置 precision = MNN::BackendConfig::Precision_Normal 或者MNN::BackendConfig::Precision_Low）。
不知道是什么原因？有什么注意事项吗？

**Comment by jxt1234** [comment]
你的测试代码是？
ARM 82 的输入输出 Tensor 需要像 gpu 一样用 copyFrom / copyTo 以 hostTensor中转，不能直接访问 tensor->host

**Comment by dreadlord1984** [comment]
输入部分：
 std::unique_ptr<MNN::CV::ImageProcess> process(MNN::CV::ImageProcess::create(MNN::CV::BGR, MNN::CV::RGB, mean, 3, norm, 3));
process->convert((const unsigned char*)image.data, image.cols, image.rows, 0, inputTensor);
或者
auto inputTensor  = net->getSessionInput(session, nullptr);
inputTensor->copyFromHostTensor(nhwc_Tensor);
// run network
net->runSession(session);

输出部分：
net->runSession(session);
MNN::Tensor *tensor_lmks  = net->getSessionOutput(session, output_tensor_name0.c_str());
MNN::Tensor tensor_lmks_host(tensor_lmks, tensor_lmks->getDimensionType());
    
tensor_lmks->copyToHostTensor(&tensor_lmks_host);
auto lmks_dataPtr  = tensor_lmks_host.host<float>();

输入部分试了两种方式，其中一种显示有copy；输出看起来也是有copy动作。 不打开Arm82或者使用 Precision_High，结果是正常的。

**Comment by dreadlord1984** [comment]
输入部分：
 std::unique_ptr<MNN::CV::ImageProcess> process(MNN::CV::ImageProcess::create(MNN::CV::BGR, MNN::CV::RGB, mean, 3, norm, 3));
process->convert((const unsigned char*)image.data, image.cols, image.rows, 0, inputTensor);
或者
auto inputTensor  = net->getSessionInput(session, nullptr);
inputTensor->copyFromHostTensor(nhwc_Tensor);
// run network
net->runSession(session);

输出部分：
net->runSession(session);
MNN::Tensor *tensor_lmks  = net->getSessionOutput(session, output_tensor_name0.c_str());
MNN::Tensor tensor_lmks_host(tensor_lmks, tensor_lmks->getDimensionType());
    
tensor_lmks->copyToHostTensor(&tensor_lmks_host);
auto lmks_dataPtr  = tensor_lmks_host.host<float>();

输入部分试了两种方式，其中一种显示有copy；输出看起来也是有copy动作。 不打开Arm82或者使用 Precision_High，结果是正常的。

**Comment by czy2014hust** [comment]
> 结果数值错误: 有具体的数值对比吗？

> 可以把转好的mnn模型发下

**Comment by dreadlord1984** [comment]
> > 结果数值错误: 有具体的数值对比吗？
> 
> > 可以把转好的mnn模型发下
我试了几个模型结果都不正常。
其中一个例子是：https://github.com/xindongzhang/MNN-APPLICATIONS/tree/master/applications/pfld-lite   直接编译放在手机端运行，你可以试一下。

**Comment by czy2014hust** [comment]
- 数值有对比吗？差别多少？
- 请把一个出问题的具体模型发下

**Comment by dreadlord1984** [comment]
> * 数值有对比吗？差别多少？
> * 请把一个出问题的具体模型发下
数值具体差别没有列，因为从可视化结果上看误差比较大（比如上面那个人脸关键点的例子，而且使用一些更小的模型以后误差会明显扩大，不知道是不是因为fp16的精度问题）。
出问题的模型就在上面的github地址里面，clone下来后模型也在代码中。

**Comment by dreadlord1984** [comment]
> * 数值有对比吗？差别多少？
> * 请把一个出问题的具体模型发下
把模型转换成FP16格式来运行也不行。
数据差别很大，比如其中一个人脸关键点位置为 17 19 --> -2311 12117。其他点的位置偏移也比较离谱。

**Comment by czy2014hust** [comment]
测试环境
- 平台：华为 P30Pro
- [模型](https://github.com/xindongzhang/MNN-APPLICATIONS/blob/master/applications/pfld-lite/onnx/jni/graphs/pfld-lite.mnn)
- [输入图像](https://github.com/xindongzhang/MNN-APPLICATIONS/blob/master/applications/pfld-lite/onnx/jni/image-02.jpg)
- 预处理：image = (image - 123.0) / 58.0

> 结果：

![image](https://user-images.githubusercontent.com/18324393/79414971-a40cf000-7fde-11ea-8313-9da1abfe35d7.png)
![image](https://user-images.githubusercontent.com/18324393/79415012-c4d54580-7fde-11ea-80a4-186b03b9e3bd.png)

> 预处理：image = (image - 0) / 255.0同样没有问题

所以fp16计算应该没有问题，fp16精度应该也不存在问题

> copy时有error：暂不支持NHWC(MNN::Tensor::TENSORFLOW)->NC4HW4格式的copy，可以NCHW(MNN::Tensor::CAFFE) copy

**Comment by strivehub** [comment]
怎么解决的呢？？
