### ISSUE TITLE
Does Support to FPN?

### ISSUE THREAD

**Issue by guoqiang0148666** [alibaba/MNN#748]
Thanks your excellent works!

l want to convert caffe format FPN model to MNN model, the backbone of which is ResNet.

l meet a segmentation fault.

So, l just wonder to know whether the FPN @ ResNet model is supported.

Besides, l also meet segmentation fault while l convert vgg16 to MNN.

Any suggestions will be welcomed, Thanks.

**Comment by jxt1234** [comment]
Maybe your caffe model is too old. Please convert it firstly to new one

**Comment by guoqiang0148666** [comment]
@jxt1234 

Thanks for you response.

l don't upgrade caffe model but pull the latest MNN to solve my problems:

```
git describe --tags
0.2.2.3
```
