### ISSUE TITLE
MNN 在linux上如何使用GPU进行推断？

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#749]
### 背景
一直在用MNN作为移动端的推断框架，在Android上，CPU和Opencl的banckend都尝试成功。

### GPU的使用情况
近期打算将算法部署到服务器，排除了`[多线程的问题](https://github.com/alibaba/MNN/issues/592)`之后，又遇到一个问题：使用Opencl和Vulkand都不能完成推断。
一开始是提示缺少这个backend，在参考了[这篇issue](https://github.com/alibaba/MNN/issues/105)之后解决了。
现在的问题是，Opencl推断，命令行一直刷新Error Code : 48；Vulkan支持的操作有限，会提示段错误。

### 问题
请问如何正确地在Linux上使用Opencl进行推断呢？

**Comment by jxt1234** [comment]
Vulkan 缺少的操作是?  有相应的模型么？

**Comment by GaussRieman** [comment]
> Vulkan 缺少的操作是? 有相应的模型么？

我就是测试的benchmark中的模型，看下来有两个不支持：
![mnn_vulkan_bug](https://user-images.githubusercontent.com/20228088/79720693-a095a380-8313-11ea-8e29-9c42bd591df5.png)

另外CL的报错也有截图：
![mnn_cl_bug](https://user-images.githubusercontent.com/20228088/79720788-d33f9c00-8313-11ea-9f21-4164a26e7666.png)

**Comment by GaussRieman** [comment]
@jxt1234

**Comment by jxt1234** [comment]
看上去就是 pad 不支持，这个可以自己设法优化掉或者加 Pad 的实现。
目前 MNN - GPU 后续会有一个新机制去更好的支持各种类型的op，所以暂时不会新加Op支持。

**Comment by GaussRieman** [comment]
@jxt1234 好的，谢谢，那就把这个issue关了吧
