### ISSUE TITLE
how does MNN handle batch norm in quantization aware training? 

### ISSUE THREAD

**Issue by liwei46** [alibaba/MNN#750]
Hello,
Glad to know that MNN supports quantization aware training. 
One point I wish to make clear is how does MNN handle batch norm in quantization aware training? 
1) does MNN support batch norm quantization?
2) does MNN consider the effect of folding batch norm to conv layer?

Regards,

**Comment by yyfcc17** [comment]
how we do QAT is presented here: https://www.yuque.com/mnn/cn/bhz5eu
code is located at: MNN_ROOT/tools/train/source/module/NN.cpp: class ConvBNReluFusedModule

answer to your question:
1. what do you mean by "batch norm quantization"?
2. in training phase of QAT, we pack conv + bn + relu together to do the quantization, bn params are updated during the phase. in test phase of QAT, bn params are folded into conv weights, and we use the scales caculated during the training phase to quantize the Conv module to ConvInt8 module.

**Comment by liwei46** [comment]
@yyfcc17 
Thanks for the reply.  
by "batch norm quantization", I mean how to handle the batch norm layers in the quantization. And you already answered my question.  :)

**Comment by Liujingxiu23** [comment]
@yyfcc17 请问MNN在训练量化的时候，支持其他量化方式吗？比如LayerNorm，weight_norm，spectral normalization.

**Comment by yyfcc17** [comment]
@Liujingxiu23 你说的这些不是量化方式，这些norm能不能合并进卷积要看它能不能合并到卷积参数之后对卷积结果的影响

**Comment by Liujingxiu23** [comment]
@yyfcc17  奥奥 是我手误写错了，是norm方式。 我没太明白你的意思。我说下我的思路哈，比如我的原始训练脚本是torch的，想导出“推理时候”使用的模型，这时候weight_norm，spectral normalization都是可以移除的，就是最后只有一个conv的weight，但“训练量化”的话，在导出模型的话，这些norm的方式，应该需要保留在模型中，参与到训练中。 如果说导出“训练量化”的MNN模型时， 就删除这些norm，能保证最终的模型效果吗？不知道你有什么经验分享吗？

另外，能否帮忙看下这个问题 ，也是跟训练量化相关的。
https://github.com/alibaba/MNN/issues/1793

**Comment by yyfcc17** [comment]
这些norm不是删除了，是合并到卷积权值了，量化训练的时候也可以合并

**Comment by Liujingxiu23** [comment]
@yyfcc17  不好意思没太明白哈  请问什么是“合并”，有没有样例呢？
