### ISSUE TITLE
Huawei Hisilicon Kirin990 Benchmark模型推断OpenCL比CPU only慢30%左右

### ISSUE THREAD

**Issue by alphaRGB** [alibaba/MNN#755]
MNN 版本: v0.2.2.3
MNN编译选项: OPENCL=ON, VULKAN=ON,OPENMP=ON

# CPU Only
## CPU Info:  Android Huawei Nova6,8核, Hisilicon Kirin990
Processor	: AArch64 Processor rev 0 (aarch64)
processor	: 0
BogoMIPS	: 3.84
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd05
CPU revision	: 0
## CPU Inference
Build Flags: ABI=arm64-v8a OpenMP=ON Vulkan=ON OpenCL=ON
MNN benchmark
Forward type: **CPU** thread=4** precision=2
--------> Benchmarking... loop = 20, warmup = 5
[ - ] inception-v3.mnn            max =  102.379ms  min =   90.584ms  avg =   92.163ms
[ - ] resnet-v2-50.mnn            max =   73.135ms  min =   60.275ms  avg =   61.885ms
[ - ] MobileNetV2_224.mnn         max =    9.241ms  min =    7.934ms  avg =    8.173ms
[ - ] SqueezeNetV1.0.mnn          max =   16.684ms  min =   14.573ms  avg =   14.895ms
[ - ] mobilenet-v1-1.0.mnn        max =   12.817ms  min =   11.910ms  avg =   12.095ms

# OpenCL Inference
Build Flags: ABI=arm64-v8a OpenMP=ON Vulkan=ON OpenCL=ON
MNN benchmark
Forward type: **OpenCL** thread=4** precision=2
--------> Benchmarking... loop = 20, warmup = 5
[ - ] inception-v3.mnn            max =  142.062ms  min =  136.756ms  avg =  139.431ms
[ - ] resnet-v2-50.mnn            max =  100.619ms  min =   91.372ms  avg =   96.693ms
[ - ] MobileNetV2_224.mnn         max =   39.754ms  min =   37.829ms  avg =   38.935ms
[ - ] SqueezeNetV1.0.mnn          max =   35.420ms  min =   31.378ms  avg =   33.691ms
[ - ] mobilenet-v1-1.0.mnn        max =   23.077ms  min =   18.544ms  avg =   20.202ms

很明显,CPU Only < OpenCL Inference time. OpenCL程序负优化

**Comment by menchunlei** [comment]
> MNN 版本: v0.2.2.3
> MNN编译选项: OPENCL=ON, VULKAN=ON,OPENMP=ON
> 
> # CPU Only
> ## CPU Info: Android Huawei Nova6,8核, Hisilicon Kirin990
> Processor : AArch64 Processor rev 0 (aarch64)
> processor : 0
> BogoMIPS : 3.84
> Features : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
> CPU implementer : 0x41
> CPU architecture: 8
> CPU variant : 0x1
> CPU part : 0xd05
> CPU revision : 0
> 
> ## CPU Inference
> Build Flags: ABI=arm64-v8a OpenMP=ON Vulkan=ON OpenCL=ON
> MNN benchmark
> Forward type: **CPU** thread=4** precision=2
> --------> Benchmarking... loop = 20, warmup = 5
> [ - ] inception-v3.mnn max = 102.379ms min = 90.584ms avg = 92.163ms
> [ - ] resnet-v2-50.mnn max = 73.135ms min = 60.275ms avg = 61.885ms
> [ - ] MobileNetV2_224.mnn max = 9.241ms min = 7.934ms avg = 8.173ms
> [ - ] SqueezeNetV1.0.mnn max = 16.684ms min = 14.573ms avg = 14.895ms
> [ - ] mobilenet-v1-1.0.mnn max = 12.817ms min = 11.910ms avg = 12.095ms
> 
> # OpenCL Inference
> Build Flags: ABI=arm64-v8a OpenMP=ON Vulkan=ON OpenCL=ON
> MNN benchmark
> Forward type: **OpenCL** thread=4** precision=2
> --------> Benchmarking... loop = 20, warmup = 5
> [ - ] inception-v3.mnn max = 142.062ms min = 136.756ms avg = 139.431ms
> [ - ] resnet-v2-50.mnn max = 100.619ms min = 91.372ms avg = 96.693ms
> [ - ] MobileNetV2_224.mnn max = 39.754ms min = 37.829ms avg = 38.935ms
> [ - ] SqueezeNetV1.0.mnn max = 35.420ms min = 31.378ms avg = 33.691ms
> [ - ] mobilenet-v1-1.0.mnn max = 23.077ms min = 18.544ms avg = 20.202ms
> 
> 很明显,CPU Only < OpenCL Inference time. OpenCL程序负优化

@alphaRGB hi, would you fix the issue?

**Comment by wangzhaode** [comment]
2.x版本OpenCL的性能已经有了很多优化，可以在测试比较下
