### ISSUE TITLE
MAC使用metal推断报错

### ISSUE THREAD

**Issue by xiaoqunSun** [alibaba/MNN#756]
# 平台(如果交叉编译请再附上交叉编译目标平台):   MAC
# Platform(Include target platform as well if cross-compiling):  

# Github版本: 9f1555ffdde9df84faf41dcf6beecba8f0e227f4
# Github Version: 

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cmake -DMNN_BUILD_DEMO=ON -DMNN_VULKAN=ON -DMNN_USE_SYSTEM_LIB=ON -DMNN_BUILD_TOOLS=OFF -DMNN_BUILD_CONVERTER=OFF -DMNN_PORTABLE_BUILD=ON -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_BUILD_BENCHMARK=ON -DMNN_METAL=ON ..

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

===================================

Forward type: **Metal** thread=4** precision=2
--------> Benchmarking... loop = 20, warmup = 0
validateMTLStorageMode:176: failed assertion `Invalid storageMode (Invalid)'
[1]    70162 abort      ./benchmark.out ../benchmark/models 20 0 1

**Comment by GHLab** [comment]
I did get an answer that mnn metal is not support mac. You can check https://github.com/alibaba/MNN/issues/618

**Comment by xiaoqunSun** [comment]
哦 这样的 了解了
