### ISSUE TITLE
安卓demo出现闪退

### ISSUE THREAD

**Issue by kingLCH** [alibaba/MNN#758]
windows上运行demo下的安卓工程，出现闪退，提示缺少个库（另外只有mnn_CL,没有vulkan和gl）
dlopen failed: library "libomp.so" not found

**Comment by yehorchankov** [comment]
Hello! You can comment out the next lines in `demo/android/app/CMakeLists.txt`:
```
#set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp")
#set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
```
And add the following instead:
```
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
```  
It helped me, however, compiling without this flag may cause your application to run slower.

**Comment by kingLCH** [comment]
> Hello! You can comment out the next lines in `demo/android/app/CMakeLists.txt`:
> 
> ```
> #set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp")
> #set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
> ```
> 
> And add the following instead:
> 
> ```
> set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
> set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
> ```
> 
> It helped me, however, compiling without this flag may cause your application to run slower.

I tried  as you say, it works and my application could run.But cpu mode is faster than vulkan mode and opengl mode, is it right?

**Comment by yehorchankov** [comment]
On my device (Mi 8) and a couple of others that I tested on, including Galaxy s10, s20+, CPU mode is faster.

**Comment by Lamply** [comment]
@kingLCH @yehorchankov This may help: https://stackoverflow.com/questions/59794824/android-app-crash-after-ndk-upgraded-from-20-1-to-21-0
