### ISSUE TITLE
Android build error with arm82 option

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#759]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
android build on mac

# Github版本:
# Github Version:
latest version

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
After change option(MNN_ARM82 "Enable ARM82" ON) and move MNN/project/android
mkdir build_32 && cd build_32 && ../build_32.sh
```

# 编译日志:
# Build Log:

```
[ 79%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o
/Users/ghlab/Dev/git/MNN/source/backend/cpu/CPURuntime.cpp:356:23: error: use of
      undeclared identifier 'getauxval'
    return (uint32_t) getauxval(AT_HWCAP);
                      ^
[ 79%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUScale.cpp.o
1 error generated.
make[2]: *** [CMakeFiles/MNNCPU.dir/source/backend/cpu/CPURuntime.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/MNNCPU.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by czy2014hust** [comment]
- NDK版本是多少？把开始的cmake log贴一下
- arm82只对armv8有效，也就是需要用build_64脚本

**Comment by GHLab** [comment]
@czy2014hust Ooops! I'm sorry misunderstood. Thank you!
