### ISSUE TITLE
Model output copy time is high

### ISSUE THREAD

**Issue by SanthoshRajendiran** [alibaba/MNN#76]
Is there any way in which we can copy the inputs and outputs fast in android, like using concepts like SSBO or PBO, in order to reduce the copy time and overall inference time. On running the current demo application, we found that OpenCL has been performing very good in terms of model running, whereas copying the output tensor was making its performance overall bad. On going through many references like TFLite GPU delegate, we think SSBO, can help us out in these areas. Any suggestions on how to do it with the demo application and is there any chance of releasing the application with SSBO in the near future??

**Comment by jxt1234** [comment]
What's your output size and do you have the data of cost time? OpenCL's getOutput will wait for GPU's work done.

In normal case, the cost of getOutput only cost about 1% - 5%

**Comment by SanthoshRajendiran** [comment]
In the portrait model in demo app, we logged the time at each step..
This information is from Oneplus3 (Gpu: Adreno530, CPU: Snapdragon 830)

mSession.run() is taking around 9ms.
mOutputTensor.getFloatData() is taking around 30ms.
nativeConvertMaskToPixelsMultiChannels() is taking around 1 ms.
Bitmap Creation is taking around 60ms.

As per our current understanding, mSession.run() is the actual model running time. And mOutputTensor.getFloatData() is the output copy time. Correct us if any mistakes on our understanding of the concept..

**Comment by jxt1234** [comment]
For OpenCL, mSession.run() + mOutputTensor.getFloatData() is the running time + output copy time.

But  mSession.run() doesn't mean the  actual model running time, it's asynchronous.

**Comment by SanthoshRajendiran** [comment]
These are the values we recorded for the other counterparts of OpenCL.

OpenGL: 
mSession.run() - 390ms
mOutputTensor.getFloatData() - 1ms
nativeConvertMaskToPixelsMultiChannels() - 1ms

Vulcan: 
mSession.run() - 102ms
mOutputTensor.getFloatData() - 3ms
nativeConvertMaskToPixelsMultiChannels() - 3ms

CPU: 
mSession.run() - 190ms
mOutputTensor.getFloatData() - 0ms
nativeConvertMaskToPixelsMultiChannels() - 1ms

We can find that overall, there is a variation in everything.. Is there any way we can find out specifically, which is the actual model running time and what is the copy time between the CPU and GPU. Can this be improved by any methods like SSBO??

**Comment by jxt1234** [comment]
Vulcan:
mOutputTensor.getFloatData() - 3ms

The 3ms is nearly be right copy time.

**Comment by li-qing** [comment]
if you do not wait for GPU inference to be finished (through runSessionWithCallback with sync), copyToHostTensor has to wait for inference to be finished first.

**Comment by SanthoshRajendiran** [comment]
It is clear that copyToHostTensor needs time to wait for inference in GPU to be completed. But the context, I am asking is, if the output can be handled at the GPU level itself instead of bringing it back to CPU? There are some proven concepts like SSBO which is able to fetch GPU output as textures in GPU level itself.

**Comment by li-qing** [comment]
> It is clear that copyToHostTensor needs time to wait for inference in GPU to be completed. But the context, I am asking is, if the output can be handled at the GPU level itself instead of bringing it back to CPU? There are some proven concepts like SSBO which is able to fetch GPU output as textures in GPU level itself.

deviceId for a GPU tensor is a pointer pointing to GPU buffer. You can access data without calling copyToHostTensor.
