### ISSUE TITLE
Can't Find type=4 backend, use 0 instead

### ISSUE THREAD

**Issue by fxfviolet** [alibaba/MNN#760]
我是用keras进行模型训练，然后转成tensorflow的.pb格式，最后按教程转成.mnn格式，转换成功没有报错。
但是在调用.mnn模型，出现如下错误：
Can't Find type=4 backend, use 0 instead
Can't compute size for 11, name=batch_normalization_4/moving_variance/biased
Resize error for batch_normalization_4/moving_variance/biased, code=3

**Comment by lcaikk1314** [comment]
可以尝试以下方法：在你创建session的时候，config.type的值设置为MNN_FORWARD_CPU，不要使用MNN_FORWARD_AUTO
