### ISSUE TITLE
onnx的分组卷积转mnn时被拆成slice+convolution+concat

### ISSUE THREAD

**Issue by JerryDeepl** [alibaba/MNN#762]
如下，一个group=3的卷积被拆分成slice + 3个convolution + concat
275                     Concat          0.018230        0.297583        0.035917   
275_____slice           Slice           0.071520        1.167477        0.047889   
275__group__0           Convolution     0.066560        1.086512        0.903874   
275__group__1           Convolution     0.065710        1.072636        0.903874   
275__group__2           Convolution     0.065370        1.067086        0.903874 

# Github版本:
commit 9f1555ffdde9df84faf41dcf6beecba8f0e227f4 (HEAD -> master, tag: 0.2.2.3, origin/master, origin/HEAD)

**Comment by jxt1234** [comment]
计算结果存在问题? 这个是正常的情况吧。

**Comment by JerryDeepl** [comment]
结果没问题哈。
是想问下，mnn的卷积算子里面不是有group的配置，为什么不转成一个卷积，里面配置group=3。
主要是设计的网络里有大量分组卷积，slice占了不少时间，如果转成convolution(group=3) 会不会比 slice + 3 convolution(group=1)+concat的推理时间快些？还是说这两种是等价实现的？

**Comment by jxt1234** [comment]
两种是等价实现的，为了简化卷积实现，MNN只支持depthwise 和 group = 1 的卷积计算，在实现 group 卷积时是内部做 convert + slice + 3 convolution + concat + convert  ，和在图上拆解是等价的，效率方面还稍低一些

**Comment by JerryDeepl** [comment]
了解了，谢谢
