### ISSUE TITLE
是否支持 海思 麒麟 含有 npu 的芯片

### ISSUE THREAD

**Issue by verigle** [alibaba/MNN#763]
MNN是否支持 海思 麒麟 970， 980，990， 810， 820 等含有npu 的芯片 部署优化 呢？

**Comment by jxt1234** [comment]
970 的非达芬奇架构支持不了。之后的正在合作中，完善了会放出来。

**Comment by zkfzle** [comment]
980、990的架构能run么？以及，这块是否受到hisi ddk本身能力的限制？
