### ISSUE TITLE
MNN::Interpreter->getSessionInput得到的host为空

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#766]
Android平台，r14b ndk编译的。
config.type = MNNForwardType::MNN_FORWARD_OPENCL;
。。。
MNN::Tensor* input_tensor = net->getSessionInput(this->session, NULL);
float* p_tensor = this->input_tensor->host<float>();

发现p_tensor为空，在config.type为CPU时是正常的，为GPU(opencl/VULKAN/OPENGL)都为空，看到mnn文档说如果用GPU的话需要通过deviceid来填充数据：
The simplest way to fill tensor data  is assigning value to host directly, but this usage is limited to the CPU backend,  other backends need to write data via deviceid.
问一下有通过deviceid来填充input tensor的例子吗？

**Comment by jxt1234** [comment]
请参考 https://www.yuque.com/mnn/cn/input    
目前暂不支持通过 deviceid 直接填充，需要建 host tensor 并且拷贝

**Comment by zhangkom** [comment]
能提供一个列子吗？比如：
config.type = MNNForwardType::MNN_FORWARD_VULKAN;
session = net->createSession(config);

input_tensor = net->getSessionInput(this->session, NULL);

**Comment by jxt1234** [comment]
请参考 demo/exec/multiPose.cpp 和  demo/exec/pictureRecognition.cpp

**Comment by zhangkom** [comment]
multiPose.cpp  pictureRecognition.cpp 这两个里面的例子是CPU的，现在需要的GPU，能有个具体例子吗？

**Comment by jxt1234** [comment]
这两个例子都是支持 GPU 的...
