### ISSUE TITLE
模型转换时 --forTraining 没有效果

### ISSUE THREAD

**Issue by yuanhaoqiang** [alibaba/MNN#767]
在用 MNNConvert 将onnx模型转换为mnn时 ，无论加不加 --forTraining 生成的模型文件大小 参数都是一样的，目测都将BN融合到了卷积中  那怎么在转换为mnn模型的同时 保留BN参数？

**Comment by jxt1234** [comment]
已经问题，修复后的版本还没合入，请稍等

**Comment by hukv1990** [comment]
请问修复后的版本是否已经合入，这边今天也发现有这样的问题。

**Comment by dandanli814** [comment]
您好，我也尝试了./MNNConvert -f ONNX --modelFile test.onnx --MNNModel test.mnn --bizCode biz --forTraining，发现加不加--forTraining，生成的mnn文件大小是一样的，不知道上述问题解决了吗？
