### ISSUE TITLE
请问，benchmark下面的models里的mobilenetv1/v2是来自caffe转换的嘛

### ISSUE THREAD

**Issue by ysh329** [alibaba/MNN#768]
请问，benchmark下面的models里的mobilenetv1/v2，是来自shicai的那个最官方标准的caffe模型，转换得到的mnn模型的嘛

感谢~Thanks♪(･ω･)ﾉ

**Comment by jxt1234** [comment]
是 Tensorflow 的 https://www.yuque.com/mnn/cn/demo_zoo
最官方标准的应该是 Tensorflow 的，mobilenet 是 google 提出的。。。

**Comment by ysh329** [comment]
> 是 Tensorflow 的 https://www.yuque.com/mnn/cn/demo_zoo
> 最官方标准的应该是 Tensorflow 的，mobilenet 是 google 提出的。。。

感谢~
