### ISSUE TITLE
请问，MNN的OpenCL有int8的性能数据吗

### ISSUE THREAD

**Issue by ysh329** [alibaba/MNN#769]
请问，MNN的OpenCL有int8的性能数据吗

**Comment by elinx** [comment]
CPU Int8:
```shell
Forward type: **CPU** thread=4** precision=2
--------> Benchmarking... loop = 100, warmup = 10
parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"

[MNNInfo]:*************set armv82 backend*************
[ - ] squeezenet_v1.1.caffe.mnn    max =   21.991ms  min =   17.586ms  avg =   18.896ms
parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"

[MNNInfo]:*************set armv82 backend*************
[ - ] mobilenet_v1.caffe.mnn      max =   17.030ms  min =   16.255ms  avg =   16.404ms
```
OpenCL Int8:
```shell
Forward type: **OpenCL** thread=4** precision=2
--------> Benchmarking... loop = 100, warmup = 10
parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
[ - ] squeezenet_v1.1.caffe.mnn    max =    4.714ms  min =    2.064ms  avg =    2.874ms
parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
[ - ] mobilenet_v1.caffe.mnn      max =    1.760ms  min =    0.787ms  avg =    1.305ms
```

@ysh329 自己跑出来的，参考一下。

**Comment by ysh329** [comment]
> CPU Int8:
> 
> ```shell
> Forward type: **CPU** thread=4** precision=2
> --------> Benchmarking... loop = 100, warmup = 10
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> 
> [MNNInfo]:*************set armv82 backend*************
> [ - ] squeezenet_v1.1.caffe.mnn    max =   21.991ms  min =   17.586ms  avg =   18.896ms
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> 
> [MNNInfo]:*************set armv82 backend*************
> [ - ] mobilenet_v1.caffe.mnn      max =   17.030ms  min =   16.255ms  avg =   16.404ms
> ```
> 
> OpenCL Int8:
> 
> ```shell
> Forward type: **OpenCL** thread=4** precision=2
> --------> Benchmarking... loop = 100, warmup = 10
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> [ - ] squeezenet_v1.1.caffe.mnn    max =    4.714ms  min =    2.064ms  avg =    2.874ms
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> [ - ] mobilenet_v1.caffe.mnn      max =    1.760ms  min =    0.787ms  avg =    1.305ms
> ```
> 
> @ysh329 自己跑出来的，参考一下。

感谢哇，这是用什么机器跑的呀

**Comment by czy2014hust** [comment]
> CPU Int8:
> 
> ```shell
> Forward type: **CPU** thread=4** precision=2
> --------> Benchmarking... loop = 100, warmup = 10
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> 
> [MNNInfo]:*************set armv82 backend*************
> [ - ] squeezenet_v1.1.caffe.mnn    max =   21.991ms  min =   17.586ms  avg =   18.896ms
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> 
> [MNNInfo]:*************set armv82 backend*************
> [ - ] mobilenet_v1.caffe.mnn      max =   17.030ms  min =   16.255ms  avg =   16.404ms
> ```
> 
> OpenCL Int8:
> 
> ```shell
> Forward type: **OpenCL** thread=4** precision=2
> --------> Benchmarking... loop = 100, warmup = 10
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> [ - ] squeezenet_v1.1.caffe.mnn    max =    4.714ms  min =    2.064ms  avg =    2.874ms
> parsed /proc/cpuinfo Hardware = "Hisilicon Kirin990"
> [ - ] mobilenet_v1.caffe.mnn      max =    1.760ms  min =    0.787ms  avg =    1.305ms
> ```
> 
> @ysh329 自己跑出来的，参考一下。

你在麒麟990上run可能有问题吧

> mbv1 CPU: Avg= 6.159301 ms, min= 5.627000 ms, max= 10.629001 ms
OPENCL: Avg= 19.487120 ms, min= 16.714001 ms, max= 22.234001 ms
sqv1.1 CPU: Avg= 4.946840 ms, min= 4.196000 ms, max= 11.348001 ms
OPENCL: Avg= 24.557302 ms, min= 17.563002 ms, max= 31.548002 ms

@ysh329 可以用MNNV2Basic.cpp测试

**Comment by bylanhao** [comment]
MNN的OpenCL有没有量化和量化前的数据比较？我们这边用MALI G52测试，量化前后性能没有优化。

**Comment by elinx** [comment]
用的Mate 30;
忘记说了，这里没有算IO时间，只算了inference的时间。

**Comment by ysh329** [comment]
非常感谢~

**Comment by lawgeorge202** [comment]
@elinx 请教一下这个opencl跑INT8是怎么实现的？RME上不是说GPU-OPENCL不支持INT8吗？
