### ISSUE TITLE
 fatal error: GLES2/gl2.h: No such file or directory

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#77]
Scanning dependencies of target MNN_GL
[ 84%] Building CXX object source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBackend.cpp.o
In file included from /data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/source/backend/opengl/GLProgram.h:13:0,
                 from /data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/source/backend/opengl/./execution/GLConvolution.h:14,
                 from /data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/source/backend/opengl/GLBackend.cpp:11:
/data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/source/backend/opengl/GLHead.h:21:23: fatal error: GLES2/gl2.h: No such file or directory
compilation terminated.
source/backend/opengl/CMakeFiles/MNN_GL.dir/build.make:62: recipe for target 'source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBackend.cpp.o' failed
make[2]: *** [source/backend/opengl/CMakeFiles/MNN_GL.dir/GLBackend.cpp.o] Error 1
CMakeFiles/Makefile2:214: recipe for target 'source/backend/opengl/CMakeFiles/MNN_GL.dir/all' failed
make[1]: *** [source/backend/opengl/CMakeFiles/MNN_GL.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
编译开启了Opencl和opengl， 编译Android的so，opencl，opengl，vulkan都没问题，编译Linux本地库，就会报如上的错误，opencl好像也有问题，是没把相关的目录加到环境变量里面还是linux本地编译不能开启opencl，opengl？

**Comment by jxt1234** [comment]
目前 opengl 是用的 opengl es，不支持 Linux 系统，可以安装 angle 去支持

opencl 应该Linux 下也能编的，具体是什么问题?

**Comment by ChisenZhang** [comment]
> 目前 opengl 是用的 opengl es，不支持 Linux 系统，可以安装 angle 去支持
> 
> opencl 应该Linux 下也能编的，具体是什么问题?

-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - not found
-- Looking for CL_VERSION_1_1
-- Looking for CL_VERSION_1_1 - not found
-- Looking for CL_VERSION_1_0
-- Looking for CL_VERSION_1_0 - not found
-- Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR) 
-- [*] linking MNN with OpenCL done
-- [*] Checking OpenMP
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- /data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/build/benchmark
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OpenCL_LIBRARY (ADVANCED)
    linked by target "MNN_CL" in directory /data1/image_data/data/online_pushed_data/parse_result/illegalPicCls/MNN/source/backend/opencl

-- Configuring incomplete, errors occurred!

是不是要单独编一个opencl装上？
顺便问一下，demo里面的exec怎么编译？ 直接在里面 cmake完之后 make没反应，是要在主的CMake文件里面设置什么吗？

**Comment by jxt1234** [comment]
呃，这个log说明你的系统里面没有装 OpenCL 的驱动。

demo/exec 下面有 README.md

**Comment by ChisenZhang** [comment]
> 呃，这个log说明你的系统里面没有装 OpenCL 的驱动。
> 
> demo/exec 下面有 README.md

OK 已搞定  谢谢
