### ISSUE TITLE
静态库链接报错undefined reference to 'std::__ndk1::__next_prime(unsigned int)'

### ISSUE THREAD

**Issue by fxj8911** [alibaba/MNN#770]
错误信息为
libMNN.a(Schedule.cpp.o):Schedule.cpp:function std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, int>, std::__ndk1::__unordered_map_hasher<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, std::__ndk1::__hash_value_type<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, int>, std::__ndk1::hash<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> > >, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, std::__ndk1::__hash_value_type<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, int>, std::__ndk1::equal_to<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> > >, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::shared_ptr<MNN::Node<MNN::Op*> >, int> > >::rehash(unsigned int): error: undefined reference to 'std::__ndk1::__next_prime(unsigned int)

**Comment by jxt1234** [comment]
请确认编译 mnn 的 stl 与其他库的 stl 是否一致（均为 gnu 或均为 c++）
