### ISSUE TITLE
mnn_converter_tensorflow_lite(2.1.0)__upsample_RESIZE_NEAREST_NEIGHBOR 算子不支持

### ISSUE THREAD

**Issue by Lannister-Xiaolin** [alibaba/MNN#771]
## 平台:  
Ubuntu 16.04
## mnn converter  Version:
0.2.1.5git
## mnn   Version:
MNN-0.2.2.3
## 报错情况:
`
root@e45f7d0907dc:/workspace/MNN-0.2.2.3/build# ./MNNConvert -f TFLITE --modelFile /workspace/upsampe.tflite --MNNModel XXX.mnn --bizCode biz      
MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [03:14:32] /workspace/MNN-0.2.2.3/tools/converter/source/tflite/liteConverter.cpp:234: Check failed: creator ==> NOT_SUPPORTED_OP: [ RESIZE_NEAREST_NEIGHBOR ]
Aborted (core dumped)
`
## 转换文件
[upsample.tflite_tf2.1.0导出文件](https://github.com/Lannister-Xiaolin/xl_mnn_tools/raw/master/upsampe.tflite)

## 补充说明
推测应该时版本问题导致RESIZE_NEAREST_NEIGHBOR的对应名称无法识别

**Comment by jxt1234** [comment]
了解了，您可以先在 tools/converter/source/tflite/ResizeBilinear.cpp 最后一行加一句兼容一下：
REGISTER_CONVERTER(ResizeBilinear, BuiltinOperator_RESIZE_NEAREST_NEIGHBOR);

我们后续添加支持

**Comment by Lannister-Xiaolin** [comment]
> 了解了，您可以先在 tools/converter/source/tflite/ResizeBilinear.cpp 最后一行加一句兼容一下：
> REGISTER_CONVERTER(ResizeBilinear, BuiltinOperator_RESIZE_NEAREST_NEIGHBOR);
> 
> 我们后续添加支持


好的，我还是试一试把模型采样方式改成插值的试下效果吧

**Comment by Lannister-Xiaolin** [comment]
@jxt1234 
您好，这边转换时又出现不支持的算子

`Check failed: creator ==> NOT_SUPPORTED_OP: [ SUM ]
Aborted (core dumped)`
这个算子应该挺常用的，是因为我使用的版本过高吗，我看这里面也没有

![image](https://user-images.githubusercontent.com/37075966/80564759-48e8ed80-8a21-11ea-8f74-aea5b199c78e.png)

### 模型文件地址
[efficientdetd0_512](https://github.com/Lannister-Xiaolin/xl_mnn_tools/blob/master/efficientdet0_512.tflite)

**Comment by jxt1234** [comment]
请更新代码，已经 fix
