### ISSUE TITLE
runSession 得到返回值4 NO_EXECUTION       = 4

### ISSUE THREAD

**Issue by fxj8911** [alibaba/MNN#773]
runSession 得到返回值4 NO_EXECUTION       = 4
请问NO_EXECUTION       是哪里报的异常

**Comment by jxt1234** [comment]
这个一般会在  创建 session 或者 resize 时有错误日志打出

**Comment by jxt1234** [comment]
一般情况是静态库使用问题，参考 https://www.yuque.com/mnn/en/faq

**Comment by wanggogogo** [comment]
我也遇到了，请问有解决吗？
