### ISSUE TITLE
bench_android.sh里一个Bug & 是否支持端侧GPU训练？

### ISSUE THREAD

**Issue by Nova-xiao** [alibaba/MNN#774]
# 1. bench_android.sh的bug
在adb shell阶段输入的命令行参数与benchmark.cpp的main中定义的命令行参数有出入，第三个参数应该是warmup的取值，但是输入的命令行参数是ForwardType，导致第二次输入的命令行还是使用CPU推理（本应该是使用Vulkan）

# 2.关于端侧GPU训练的问题
我在您们提供的官方文档中没有看到关于端侧使用GPU训练的相关叙述，我尝试修改demo里程序的MNNForwardType参数（具体做法是MnistUtils的train函数中修改了exe设置参数时传入的type），但是执行时会报错Error to Find Creator，想请问您们是否有关于端侧GPU训练的文档？
另外，mac端编译opencl会报错，具体如下：（benchmark的编译log）
```
CMakeFiles/MNN_CL.dir/execution/cl/opencl_program.cc.o:(.bss._ZN3MNN16OpenCLProgramMapE+0x0): multiple definition of `MNN::OpenCLProgramMap'
CMakeFiles/MNN_CL.dir/execution/cl/opencl_program_2.cc.o:(.bss._ZN3MNN16OpenCLProgramMapE+0x0): first defined here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
## Platform(Include target platform as well if cross-compiling):  
macOS Catalina 10.15->Android10（Xiaomi 9 SE，MIUI11)交叉编译

## Compiling Method
使用Android ndk的toolchain（API版本：29）执行交叉编译

**Comment by jxt1234** [comment]
1、bench_android.sh 问题知道了，后续修复
2、端侧 GPU 训练确实是这样的使用方式，但目前还没有调通（主要是性能问题），待后续完善
