### ISSUE TITLE
StridedSliceComputer: inputDimension一定要小于5吗

### ISSUE THREAD

**Issue by MonicaChen426** [alibaba/MNN#776]
1、基于Mobilenet_yolov3进行物体识别，执行时，最后一层不能正常创建和执行，由于
StridedSliceComputer: inputDimension>=5
这个限制能否修改

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux version 4.15.0-74-generic (buildd@lgw01-amd64-036) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)) #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019

# Github版本:3.27下载
# Github Version:

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:
Error for StridedSliceComputer: inputDimension>=5: 5
Resize error for [StridedSlice], pred_sbbox/strided_slice_3, code=3
```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
修正了
