### ISSUE TITLE
MAC安装MNN后现实make成功，但是build文件夹内没有MNNConvert

### ISSUE THREAD

**Issue by janyChan** [alibaba/MNN#779]
MAC安装MNN后现实make成功，但是build文件夹内没有MNNConvert
显示，-bash: ./MNNConvert: No such file or directory

**Comment by janyChan** [comment]
cmake DMNN_BUILD_DEMO设置为ON不行，设置为true可以了。
是不是语雀上面的文档没改过来？

**Comment by jxt1234** [comment]
cmake .. -DMNN_BUILD_CONVERTER=true
