### ISSUE TITLE
CaffeModel's inference result is wrong

### ISSUE THREAD

**Issue by ZichenTian** [alibaba/MNN#78]
**I tried to deploy MTCNN caffemodel to MNN and get wrong result. And I suspend that the problem come from CAFFE and CAFFE_C4.**

here are the details:

----

I compared MNN inference result to NCNN inference result, and found something interesting.

when I set all values in the Input Tensor to 1.0f, NCNN and MNN got the exactly same result. Then I change the Input Tensor channel(0) to 1.0f, channel(1) to 2.0f, channel(2) to 3.0f, and I got different result.

so I guess that the difference come from Tensor Data Type;

----

I also make another try. 

I got two .mnn model from tflite and caffe, both are mobilenet_v2. And found that the cls_score differ a lot.  The code is just the /demo/exec/pictureRecognition.cpp.

**Comment by jxt1234** [comment]
What's your input data code?

It's suggest to create a tensor as CAFFE, fill the tensor and copy to Session's input tensor
