### ISSUE TITLE
同样的模型文件和输入图片，用MNN和tensorflow跑出来的数据不一样

### ISSUE THREAD

**Issue by MonicaChen426** [alibaba/MNN#780]
针对我们自己的Mobilenet_yolov3模型，用MNN前向跑出来的数据和tensorflow跑出来的数据不一致，合理吗？可能什么原因

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
模型？输入？输出具体差别？

**Comment by wangzhaode** [comment]
没有提供足够的信息，长时间未答复；问题关闭
