### ISSUE TITLE
mnn编译出现check failed:creator not supported op[DIV]

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#781]
# 平台
Ubuntu14.04
# mnn converter Version:
0.2.1.5git
#mnn Version:
MNN-1.0.0.0

# 报错情况：
# ./MNNConvert -f TFLITE --modelFile /workspace/model.tflite --MNNModel modelmnn --bizCode biz
Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
what(): [03:14:32] /home/test/MNN/tools/converter/source/tflite/liteConverter.cpp:234: Check failed: creator ==> NOT_SUPPORTED_OP: [ DIV ]
Aborted (core dumped)

**Comment by jxt1234** [comment]
已经支持
