### ISSUE TITLE
ONNX -> MNN Resize operation outputs extra dimension

### ISSUE THREAD

**Issue by yehorchankov** [alibaba/MNN#784]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 19.10

# Github版本:
# Github Version:

0df31a8667bdfdbdea084eef43b6812897e75db9

# 编译方式:
# Compiling Method

MNNConvert compiled from the source from the latest version

Hello! I am investigating some issues with ONNX to MNN model conversion. 

In particular, I created a simple model that only rescales an input image. 

![image](https://user-images.githubusercontent.com/12156459/81411318-e1325100-914a-11ea-993e-c76445c28d11.png)

My pytorch model:

```
class TestNet(nn.Module):
    def forward(self, x):
        return F.interpolate(x, (256, 256))
```

Later I compared the results of MNN model to the results from ONNX and found out that MNN returns one extra dimension of data. 

```
def check_mnn(path, img):
    interpreter = MNN.Interpreter(path)
    session = interpreter.createSession()
    input_tensor = interpreter.getSessionInputAll(session)
    img_input = MNN.Tensor((1, 3, 512, 512), MNN.Halide_Type_Float, img, MNN.Tensor_DimensionType_Caffe)
    input_tensor['image'].copyFrom(img_input)
    interpreter.runSession(session)
    output_tensor = interpreter.getSessionOutputAll(session)
    result = list(output_tensor.values())[0].getData()
    return result

def check_onnx(path, img):
    onnx.checker.check_model(onnx.load(path))
    sess = ort.InferenceSession(path)
    outs = [s.name for s in sess.get_outputs()]
    result = sess.run(outs, {'image': img})
    return result[0]
```

In my example, ONNX returns numpy array of shape (1, 3, 256, 256), with the total number of elements 3\*256\*256 = 196608. But MNN model returns a tuple of length 262144 = **4**\*256\*256. The extra dimension seems to have only zeroes. 

Models are here: 
[test_net_simple.zip](https://github.com/alibaba/MNN/files/4599272/test_net_simple.zip)

In this test example I can filter out an extra dimension, but I am afraid of the wrong shape of the data inside complex models. Is this a bug?

**Comment by jxt1234** [comment]
https://www.yuque.com/mnn/en/faq
Please see NC4HW4 format

**Comment by yehorchankov** [comment]
@jxt1234 thanks! 
Not related to the question, but can I somehow view MNN graph, like ONNX one in Netron? 
Can I convert MNN graph back to ONNX?

**Comment by jxt1234** [comment]
You can use Netron to see MNN graph

**Comment by yehorchankov** [comment]
I got it! I was using a desktop version of netron on Ubuntu and could not see files with .mnn extension. So I had to launch netron from the terminal and open a model in a browser.
