### ISSUE TITLE
检测模型离线量化问题

### ISSUE THREAD

**Issue by nsl2014fm** [alibaba/MNN#785]
检测模型转化为mnn后，测试过输出正常，然后使用quantized.out进行离线量化，**量化后的模型输出结果异常，模型输出结果全部异常。**

转化时有如下的中间日志：
`Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
Error for 38
ComputeFeatureRange: 20.16 %
CollectFeatureDistribution: 20.16 %`

确认过如下：
1、数据无问题
2、预处理的配置项无问题
3、调整校正图片数量依旧不行
3、分类模型能够正常量化，检测模型不能正常量化

**能请问下检测模型离线量化需要怎么处理**

**Comment by xuguozhi** [comment]
人脸landmark模型支持量化否？

**Comment by wsqshiqing** [comment]
@nsl2014fm 
> Error for 38
It means An error appears in the quantization process, the detail error informations will be printed if you use an Debug Version MNN LIB.

**Comment by nsl2014fm** [comment]
> @nsl2014fm
> 
> > Error for 38
> 
> It means An error appears in the quantization process, the detail error informations will be printed if you use an Debug Version MNN LIB.

Thanks for your reply. One more quesion, how can I reach to the Debug verison?

**Comment by wxy1234567** [comment]
> 检测模型转化为mnn后，测试过输出正常，然后使用quantized.out进行离线量化，**量化后的模型输出结果异常，模型输出结果全部异常。**
> 
> 转化时有如下的中间日志：
> `Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 Error for 38 ComputeFeatureRange: 20.16 % CollectFeatureDistribution: 20.16 %`
> 
> 确认过如下：
> 1、数据无问题
> 2、预处理的配置项无问题
> 3、调整校正图片数量依旧不行
> 3、分类模型能够正常量化，检测模型不能正常量化
> 
> **能请问下检测模型离线量化需要怎么处理**

遇到同样的问题，请问找到原因了吗？

**Comment by siweimaodou** [comment]
我也遇到这个问题了，我用的是yolov3的一个裁剪模型
