### ISSUE TITLE
如何修改一个Tensor的DimensionType

### ISSUE THREAD

**Issue by MonicaChen426** [alibaba/MNN#789]
1、如何修改一个Tensor的DimensionType？
2、针对一个.pb模型转化的MNN模型，getSessionOutput输出的Tensor的DimensionType是根据什么来的？
3、inputTensor->copyFromHostTensor(nhwc_Tensor); 该函数是否会改变inputTensor的DimensionType？   我的nhwc_Tensor的DimensionType是0，inputTensor的DimensionType是1，请问是否正常？

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
1. session 内的 tensor dimensionType 无法修改，只能自己外部建 hostTensor 然后 copy 进去
2. 根据所属节点是否输出 NC4HW4 格式确定
3. 不会，同 1
