### ISSUE TITLE
量化支持的op

### ISSUE THREAD

**Issue by FzuGsr** [alibaba/MNN#792]
请问离线量化的时候，用工具quantized.out 看了下，目前只支持std::set<std::string> Helper::gNeedFeatureOp = {"Convolution", "ConvolutionDepthwise", "Eltwise", "Pooling"}; 这几个op的量化吗？如果是的话，是不是理解为量化主要是针对卷机操作的？类似做transformer的含有大量的matmul的op这种操作是否支持量化呢？谢谢

**Comment by yyfcc17** [comment]
嗯，矩阵乘的量化正在支持中，目前你可以自己hack一下，把矩阵乘转换成卷积，然后做量化

**Comment by FzuGsr** [comment]
> 嗯，矩阵乘的量化正在支持中，目前你可以自己hack一下，把矩阵乘转换成卷积，然后做量化

你好，感谢您的回答，我试着将 eltwise的量化去掉了，可以量化成功，但是用MNN提供的测试工具都没法加载成功，报 “Segmentation fault: 11”的错误，看了下好像没有创建成功session，量化的时候，是一定要加eltwise吗？ 不能手动去掉吗？ 谢谢

**Comment by yyfcc17** [comment]
你用netron看看网络结构
