### ISSUE TITLE
ONNX转mnn:check failed:(maxvalue)==(6.0f)

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#794]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
./MNNConvert -f ONNX --modelFile model.onnx --MNNModel model.mnn --bizCode biz
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
看报错mnn是不支持relu6吗?我查了一下是支持的呀

**Comment by yehorchankov** [comment]
I have the same error in Clip.cpp converting from Pytorch ---> ONNX --x-> MNN, is there any solution?

**Comment by Echosanmao** [comment]
> I have the same error in Clip.cpp converting from Pytorch ---> ONNX --x-> MNN, is there any solution?

No, I have not  find the solution.

**Comment by yehorchankov** [comment]
@Echosanmao I found a workaround. You can open `/tools/converter/source/onnx/Clip.cpp` and comment out two lines with `DCHECK_EQ`. Then rebuild converter with `cmake .. -DMNN_BUILD_CONVERTER=true && make -j4`.

**Comment by yehorchankov** [comment]
As I understood, Clip op uses a prototype of tensorflow's ReLU6 operation, that's why it checks for max value of 6 (`DCHECK_EQ(maxValue, 6.0f)`), but in Clip op max value can be anything.

Is it an expected behavior or a bug?

**Comment by Echosanmao** [comment]
Thanks a lot for your help!!You are so nice!!
It's work for me.
But next I have another error which is:
check failed:(input_size()==4)||(input_size()==2)==>"onnx resize should have 4 or 2 inputs!"
segmentation fault(core dumped)
Have you encountered this problem?

**Comment by Echosanmao** [comment]
> As I understood, Clip op uses a prototype of tensorflow's ReLU6 operation, that's why it checks for max value of 6 (`DCHECK_EQ(maxValue, 6.0f)`), but in Clip op max value can be anything.
> 
> Is it an expected behavior or a bug?

I remember the mnn support RELU6 operation, I just could't understand why the error appered.

**Comment by JerryDeepl** [comment]
@Echosanmao 
pytorch -> onnx -> mnn碰过类似的错，记录如下
1. relu6在onnx的op是clip；
2. pytorch 转 onnx 有个opset_version 设置，不同配置转出来clip描述不一样，如果opset_version=9，可以转成relu6, 如果opset_version=11，就会报错；
3. 差异在于提供maxvalue的方式改变了，opset_version=9是attr，11是input，当前mnn只能解析到attr的

**Comment by Echosanmao** [comment]
Ok.
我是keras->onnx->mnn
我找了一下keras相关opset设置,发现有个target_opset
但是我怎么确定这个参数该设置为多少呢?

**Comment by Echosanmao** [comment]
> @Echosanmao
> pytorch -> onnx -> mnn碰过类似的错，记录如下
> 
>     1. relu6在onnx的op是clip；
> 
>     2. pytorch 转 onnx 有个opset_version 设置，不同配置转出来clip描述不一样，如果opset_version=9，可以转成relu6, 如果opset_version=11，就会报错；
> 
>     3. 差异在于提供maxvalue的方式改变了，opset_version=9是attr，11是input，当前mnn只能解析到attr的

I 用了不同的target_opset,7,8,9都会有一些不支持的情况出现,11的时候还是会有
check failed:(maxvalue)==(6.0f)
所以我就按照 @yehorchankov 的方法,就不报这个错了
虽然接下来我又遇到了新的问题

**Comment by JerryDeepl** [comment]
> > @Echosanmao
> > pytorch -> onnx -> mnn碰过类似的错，记录如下
> > ```
> > 1. relu6在onnx的op是clip；
> > 
> > 2. pytorch 转 onnx 有个opset_version 设置，不同配置转出来clip描述不一样，如果opset_version=9，可以转成relu6, 如果opset_version=11，就会报错；
> > 
> > 3. 差异在于提供maxvalue的方式改变了，opset_version=9是attr，11是input，当前mnn只能解析到attr的
> > ```
> 
> I 用了不同的target_opset,7,8,9都会有一些不支持的情况出现,11的时候还是会有
> check failed:(maxvalue)==(6.0f)
> 所以我就按照 @yehorchankov 的方法,就不报这个错了
> 虽然接下来我又遇到了新的问题

我好像也碰到这种情况，不同opset_version可能会有个别op不支持，我的解决方案是把冲突的op替换掉，比如relu6换成了relu，或者upsample换成deconvolution之类的，简单粗暴，哈哈

**Comment by Echosanmao** [comment]
> > > @Echosanmao
> > > pytorch -> onnx -> mnn碰过类似的错，记录如下
> > > ```
> > > 1. relu6在onnx的op是clip；
> > > 
> > > 2. pytorch 转 onnx 有个opset_version 设置，不同配置转出来clip描述不一样，如果opset_version=9，可以转成relu6, 如果opset_version=11，就会报错；
> > > 
> > > 3. 差异在于提供maxvalue的方式改变了，opset_version=9是attr，11是input，当前mnn只能解析到attr的
> > > ```
> > 
> > 
> > I 用了不同的target_opset,7,8,9都会有一些不支持的情况出现,11的时候还是会有
> > check failed:(maxvalue)==(6.0f)
> > 所以我就按照 @yehorchankov 的方法,就不报这个错了
> > 虽然接下来我又遇到了新的问题
> 
> 我好像也碰到这种情况，不同opset_version可能会有个别op不支持，我的解决方案是把冲突的op替换掉，比如relu6换成了relu，或者upsample换成deconvolution之类的，简单粗暴，哈哈

你是怎么替换的?是把你pytorch模型中的op替换掉,然后重新训练模型吗?

**Comment by JerryDeepl** [comment]
> > > > @Echosanmao
> > > > pytorch -> onnx -> mnn碰过类似的错，记录如下
> > > > ```
> > > > 1. relu6在onnx的op是clip；
> > > > 
> > > > 2. pytorch 转 onnx 有个opset_version 设置，不同配置转出来clip描述不一样，如果opset_version=9，可以转成relu6, 如果opset_version=11，就会报错；
> > > > 
> > > > 3. 差异在于提供maxvalue的方式改变了，opset_version=9是attr，11是input，当前mnn只能解析到attr的
> > > > ```
> > > 
> > > 
> > > I 用了不同的target_opset,7,8,9都会有一些不支持的情况出现,11的时候还是会有
> > > check failed:(maxvalue)==(6.0f)
> > > 所以我就按照 @yehorchankov 的方法,就不报这个错了
> > > 虽然接下来我又遇到了新的问题
> > 
> > 
> > 我好像也碰到这种情况，不同opset_version可能会有个别op不支持，我的解决方案是把冲突的op替换掉，比如relu6换成了relu，或者upsample换成deconvolution之类的，简单粗暴，哈哈
> 
> 你是怎么替换的?是把你pytorch模型中的op替换掉,然后重新训练模型吗?

是的
