### ISSUE TITLE
问下安卓端如何配置从而使用vulkan或者opencl推理？

### ISSUE THREAD

**Issue by luqiang6q** [alibaba/MNN#795]
我的做法：
- 我在config中的MNNForwardType中配置了opencl或vulkan，但是运行速度与cpu没差别。

问题：
- 编译生成的libMNN_CL.so和libMNN_Vulkan.so有啥用呢，需要放到安卓工程中使用么，demo工程中的cmakelists.txt只用到了libMNN.so，但是却仍然能进行opencl的推理，这是如何配置的呢

**Comment by jxt1234** [comment]
java 层 调 system.load(libMNN_CL.so)

**Comment by luqiang6q** [comment]
> java 层 调 system.load(libMNN_CL.so)

谢谢。我这样做了，可是opencl和vulkan的速度还是和cpu差不多，甚至慢一些。。。
