### ISSUE TITLE
Python tensor.getData is wrong

### ISSUE THREAD

**Issue by Kepnu4** [alibaba/MNN#797]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
python 3.6
MNN version 1.0.0 (through pip install)

Tensor method getData() returns wrong shaped tensor 
simple demo with dummy model which only has one conv layer
```
numpy_input = np.random.rand(1, 3, 4, 4)

interpreter = MNN.Interpreter('dummy.mnn')
session = interpreter.createSession()
input_tensor = interpreter.getSessionInput(session)
tmp_input = MNN.Tensor(numpy_input.shape, MNN.Halide_Type_Float,
                       numpy_input[0], MNN.Tensor_DimensionType_Caffe)
input_tensor.copyFrom(tmp_input)
ret = interpreter.runSession(session)

interpreter.getSessionOutput(session, 'output').printTensorData()
print(interpreter.getSessionOutput(session, 'output').getData())
```
gives 
```
====== Tensor 0x556b67eda640 ======
Dimension: 1, 1, 4, 4, 
Data: batch 0:
0.216720, 0.178342, 0.299887, 0.633679, 
0.144036, 0.460203, 0.297389, 0.375050, 
0.735741, 0.256527, 0.184011, 0.258405, 
0.289951, 0.428287, 0.562942, 0.608845, 
--------------
(0.21671971678733826, 0.0, 0.0, 0.0, 0.1783420741558075, 0.0, 0.0, 0.0, 0.2998868227005005, 0.0, 0.0, 0.0, 0.6336793899536133, 0.0, 0.0, 0.0, 0.14403602480888367, 0.0, 0.0, 0.0, 0.46020299196243286, 0.0, 0.0, 0.0, 0.29738935828208923, 0.0, 0.0, 0.0, 0.375049889087677, 0.0, 0.0, 0.0, 0.7357410788536072, 0.0, 0.0, 0.0, 0.25652655959129333, 0.0, 0.0, 0.0, 0.1840110421180725, 0.0, 0.0, 0.0, 0.25840508937835693, 0.0, 0.0, 0.0, 0.2899511754512787, 0.0, 0.0, 0.0, 0.42828744649887085, 0.0, 0.0, 0.0, 0.5629415512084961, 0.0, 0.0, 0.0, 0.6088448166847229, 0.0, 0.0, 0.0)
```

model graph:
![dummy](https://user-images.githubusercontent.com/2921717/81915726-a3ff1080-95db-11ea-819e-5e131d21b927.png)

**Comment by jxt1234** [comment]
请参考 
https://www.yuque.com/mnn/cn/output 
https://www.yuque.com/mnn/en/faq
里面的NC4HW4 数据排布说明

**Comment by Kepnu4** [comment]
Ok, thank you, got it to work like this:
```
    tensor = interpreter.getSessionOutput(session, output_name)
    output_shape = tensor.getShape()
    output = MNN.Tensor(output_shape, MNN.Halide_Type_Float,
                           np.zeros(output_shape), MNN.Tensor_DimensionType_Caffe)
    tensor.copyToHostTensor(output)
```
But it still weird. I think this should be in example if it's intended behaviour

**Comment by Echosanmao** [comment]
> Ok, thank you, got it to work like this:
> 
> ```
>     tensor = interpreter.getSessionOutput(session, output_name)
>     output_shape = tensor.getShape()
>     output = MNN.Tensor(output_shape, MNN.Halide_Type_Float,
>                            np.zeros(output_shape), MNN.Tensor_DimensionType_Caffe)
>     tensor.copyToHostTensor(output)
> ```
> 
> But it still weird. I think this should be in example if it's intended behaviour

您好,我用了您的这种方式进行修改,还是发现getData()多出一些0值
input_tensor = interpreter.getSessionInput(session)
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)
input_tensor.copyFromHostTensor(tmp_tensor)
这么执行之后我的input_tensor还是RGB0RGB0格式,多了一个通道,这是为什么呢?
