### ISSUE TITLE
mnn测试结果与pb模型结果不一致

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#798]
# 平台
Ubuntu16.04
# 简介
tensorflow转mnn
.pb文件测试结果正确
输入单张图片(1,256,256,3)，并归一化
输出分割后的labelmap
# code:
 interpreter = MNN.Interpreter(model)
 session = interpreter.createSession()
 input_tensor = interpreter.getSessionInput(session)
 tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image,  MNN.Tensor_DimensionType_Tensorflow)
input_tensor.copyFrom(tmp_tensor)
interpreter.runSession(session)
output_tensor = interpreter.getSessionOutput(session)
output_tensor1 = np.array(output_tensor.getData())
output_tensor2 = output_tensor1.reshape(256,256,3)
# 问题:
为什么最终输出的output_tensor2，只在第0通道上概率最大呢?
mnn全预测为1个类别

**Comment by jxt1234** [comment]
outputTensor 可能是 NC4HW4 布局的，需要建一个 NHWC 的格式并拷贝

**Comment by wangzhaode** [comment]
长时间未回复，问题关闭
