### ISSUE TITLE
copyFrom()之后变成NC4HW4 格式???

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#799]
#copyFrom()
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)
input_tensor.copyFrom(tmp_tensor)
为什么copyFrom运行之后，input_tensor.getShape=(1, 3, 256, 256),但是len(input_tensor.getData())=4x256x256呢???
不是经过copy之后能转变为NHWC吗?

**Comment by jxt1234** [comment]
copy 是把 NHWC 的数据格式的数据 复制进去，不是修改数据格式

**Comment by Echosanmao** [comment]
Ok.但是有一个问题是:
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)
len(tmp_tensor)=3x256x256=196608

但是我执行input_tensor.copyFrom(tmp_tensor)之后
len(input_tensor.getData())=4x256x256=262144
所以copyFrom执行了什么呢?

**Comment by Echosanmao** [comment]
而且后面我执行output_tensor = interpreter.getSessionOutput(session)之后,
len(output_tensor.getData())=3x256x256=196608
又恢复为和tmp_tensor一致了.
那么中间出现的这个len(input_tensor.getData())=4x256x256=262144
会影响最终的结果吗?

**Comment by Echosanmao** [comment]
> copy 是把 NHWC 的数据格式的数据 复制进去，不是修改数据格式
您好,我看了下mnn上面对数据排布的介绍
我发现copyFrom()使得数据格式变成了NC4HW4,因为数据后面都多了一个0,变成了RGB0RGB0这种输出
我看了下mnn上的对数据格式转换的方式
input_tensor = interpreter.getSessionInput(session)
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)    
input_tensor.copyFromHostTensor(tmp_tensor)
为什么这么执行之后我的input_tensor还是RGB0RGB0格式呢?

**Comment by Echosanmao** [comment]
> copy 是把 NHWC 的数据格式的数据 复制进去，不是修改数据格式

您好,我看了下mnn上面对数据排布的介绍
我发现copyFrom()使得数据格式变成了NC4HW4,因为数据后面都多了一个0,变成了RGB0RGB0这种输出
我看了下mnn上的对数据格式转换的方式
input_tensor = interpreter.getSessionInput(session)
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)
input_tensor.copyFromHostTensor(tmp_tensor)
为什么这么执行之后我的input_tensor还是RGB0RGB0格式呢?

**Comment by Echosanmao** [comment]
> copy 是把 NHWC 的数据格式的数据 复制进去，不是修改数据格式

OK.
数据格式这块我明白了.
另外有个问题想咨询您.
我是tensorflow转mnn,.pb转.mnn的过程中并没有报错
但.pb文件测试结果正确, .mnn结果就特别差
我的模型输出是3通道的labelmap,对人脸和背景进行分割,我的mnn模型只在第0通道上概率值最大,都预测为背景类,这会是什么原因呢?
期待您的回复!
感谢!

**Comment by jxt1234** [comment]
输出处理是怎样的？
