### ISSUE TITLE
check failed:(input_size()==4)||(input_size()==2)==>"onnx resize should have 4 or 2 inputs!" 

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#801]
# onnx转mnn
# onnx version 
onnx model ir version 6和version7都有这个问题
# 报错
check failed:(input_size()==4)||(input_size()==2)==>"onnx resize should have 4 or 2 inputs!"
segmentation fault(core dumped)

**Comment by sunsiyang2015** [comment]
请问你解决这个问题了吗？我现在遇到了相同的问题

**Comment by sunsiyang2015** [comment]
> # onnx转mnn
> # onnx version
> onnx model ir version 6和version7都有这个问题
> 
> # 报错
> check failed:(input_size()==4)||(input_size()==2)==>"onnx resize should have 4 or 2 inputs!"
> segmentation fault(core dumped)

请问你解决这个问题了吗？我现在遇到了相同的问题

**Comment by mchalecki** [comment]
我也有同样的问题。 有什么办法吗?

**Comment by DLTensor** [comment]
遇到同样问题，请问有解决的吗

**Comment by gordinmitya** [comment]
plus one to this issue

**Comment by jxt1234** [comment]
fixed.
