### ISSUE TITLE
pytorch nn.GroupNorm 转onnx 为ATen, 在转为MNN后变成了ConsineSimilarity,  inference运行报错

### ISSUE THREAD

**Issue by gangeqian** [alibaba/MNN#803]
我的pytorch模型中用到了 nn.GroupNorm 
 nn.GroupNorm 转onnx 在netron中可以看到模块名为ATen, 
再转为MNN后变成了ConsineSimilarity, 
![image](https://user-images.githubusercontent.com/39591200/82025595-25ca6900-96c4-11ea-812a-bf552e5eb359.png)
![image](https://user-images.githubusercontent.com/39591200/82025622-2c58e080-96c4-11ea-9e00-647176c9d4d1.png)

inference运行报错:

Error for /project/mnn/source/shape/ShapeCosineSimilarity.cpp, 17
Error for /project/mnn/source/shape/ShapeCosineSimilarity.cpp, 22
Error for /project/mnn/source/shape/ShapeCosineSimilarity.cpp, 26
Error for /project/mnn/source/shape/ShapeCosineSimilarity.cpp, 28
Resize error for 564, code=3

![image](https://user-images.githubusercontent.com/39591200/82025659-37ac0c00-96c4-11ea-9b2f-771811c6d2d1.png)
其中564为ConsineSimilarity 输入ConvertTensor的name.

请问groupNorm 转mnn 有解吗？

**Comment by wangzhaode** [comment]
使用torchscript直接转换
