### ISSUE TITLE
海思hi3519AV100测试速度非常慢，同模型在rk3288&3326上测试很快

### ISSUE THREAD

**Issue by weitaoatvison** [alibaba/MNN#806]
我们在hi3519AV100上测试了一个模型，用 timeprofile工具测试，发现在海思3519上非常慢，耗时在3.6s。该平台有2*A53。同时，我们同模型在rk3288&3326上分别进行了测试，时间分别为28ms(A17*4), 68ms(A35 *4)，想问问有没有人遇到果这样的问题？是海思的芯片需要特殊的编译选项吗？

**Comment by czy2014hust** [comment]
应该是cmake没有判断出arm架构导致neon未打开吧

**Comment by zhcv** [comment]
@weitaoatvison  我在hisi3516dv300 上速度太慢，差不多3.5s 左右， 你找到问题啦吗

**Comment by weitaoatvison** [comment]
@zhcv 没有找到，暂时换ncnn解决了。

**Comment by zhcv** [comment]
> @zhcv 没有找到，暂时换ncnn解决了。
用ncnn, 大概耗时多久啊

**Comment by zhcv** [comment]
> @zhcv 没有找到，暂时换ncnn解决了。

> @weitaoatvison   用ncnn, 大概耗时多久啊

**Comment by jxt1234** [comment]
在 source/core/Macro.h 里面把 MNN_USE_NEON 强制打开就好了
