### ISSUE TITLE
input_tensor=NC4HW4, output_tensor自动转换为NHWC?

### ISSUE THREAD

**Issue by Echosanmao** [alibaba/MNN#807]
# 输入
input_tensor = interpreter.getSessionInput(session)#NC4HW4,随机数
tmp_tensor = MNN.Tensor((1, 256, 256, 3), MNN.Halide_Type_Float, image, MNN.Tensor_DimensionType_Tensorflow)    
input_tensor.copyFromHostTensor(tmp_tensor)

# 输入shape
tmp_tensor.getShape()=(1,256,256,3),len(tmp_tensor.getData())=196608
数据格式为NHWC
input_tensor.getShape()=(1,3,256,256),len(input_tensor.getData())= 262144
数据格式为NC4HW4
# 输出
output_tensor = interpreter.getSessionOutput(session)
这里output_tensor.getShape=(1,256,256,3),len(output_tensor.getData())=196608
数据格式为NHWC?自动转化数据格式了?
不需要使用copyToHostTensor()?

**Comment by czy2014hust** [comment]
> 数据格式为NHWC?自动转化数据格式了?
> 不需要使用copyToHostTensor()?

有些op(Conv,Pool...)内存布局为了优化加速采用了NC4HW4的布局，但是有些并不是，你这种最后输出内存布局为NHWC，本质上不需要copy(CPU Backend)，但是依然建议采用copy的形式，避免出错！
