### ISSUE TITLE
MNN on virtual machine copyToHostTensor Error?

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#809]
如题：
在虚拟机(Debian9.1  gcc 6.3.0)上运行MNN的CPU版本，报错。
定位发现在
```c++
MNN::Tensor copy(tensor_out);
tensor_out->copyToHostTensor(&copy);
```
在拷贝时报错``Segmentation fault``。

之前在linux实体机是可以正常运行的。

请问虚拟机是否会出现上述问题呢？

**Comment by wangzhaode** [comment]
这个问题跟虚拟机无关；需要提供一下Segment fault的错误堆栈信息
