### ISSUE TITLE
About BufferAllocator and Reorder内存管理与内存排序方面咨询

### ISSUE THREAD

**Issue by huwenfeng** [alibaba/MNN#81]
尝试扩展OP一些疑问：
在使用Opencl时，需要在CPU（host？）和GPU（device？）之间交换内存，使用原生Opencl可以使用DMA/SVM等方式创建交换Device的内存，MNN这块如何处理；
使用CPU推理时，是否还需要区分host和device的内存管理和交互？

是否有更多推理运行时机制以及内部API介绍，谢谢

**Comment by jxt1234** [comment]
1、出于性能/减少内存占用的考虑 opencl / vulkan 一般使用 fp16 的 image 作为存储格式，这种格式 cpu 无法或不易直接使用（image 类型其内存并不一定是线性排列的），因此必然有一个转换的过程，由于深度学习是计算密集型应用，大部分情况下转换过程所占的损耗比很小。
2､使用 CPU 时均为 host 内存，不需要管 device 。
3、其他文档参考：
doc/AddBackend_CN.md
doc/FAQ.md

**Comment by huwenfeng** [comment]
>>STATIC内存不复用，一般用于op常量存储；DYNAMIC内存可复用，一般用于变量存储；

请问，static复用，是否是指在同一个推理session中多次出现的同一种op之间？
