### ISSUE TITLE
How can initialize image and rect?

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#812]
Hi,
I think if I will use tracker model by mnn, I have to initialize image and ROI rect but I don't know how to this.
Exactly, I'd like to implement like this https://github.com/dongfangduoshou123/DaSiamRPN-Caffe2/blob/master/main.cpp#L46
Please let me know about this.
Thank you.

**Comment by jxt1234** [comment]
Use image process and use setPolyToPoly to set the matrix. Like demo/exec/pictureRecognition
