### ISSUE TITLE
可以支持出入数据shape不确定的模型吗？

### ISSUE THREAD

**Issue by baiyu8534** [alibaba/MNN#815]
我的tensorflow模型输入的数据必须是不定长的数据，因为要输入文件，对文件处理后，生成对应对文件。
因为文件类型，用户输入对文件肯定是不一样对
而且要根据源文件经过模型处理后生成文件

tflite模型只支持确定shape对数据输入

请问MNN可以转换输入数据shape不确定对tensorflow模型吗？

或者MNN可以在移动端实现支持不确定shape对数据输入对模型？

望解答！谢谢！！🙏🙏🙏🙏🙏

**Comment by jxt1234** [comment]
一般是支持的。

**Comment by baiyu8534** [comment]
@jxt1234 谢谢！！
tensorflow  RNN模型可以转化为MNN可以用的模型吗？
不行我就去看一下怎么用MNN训练模型

**Comment by jxt1234** [comment]
static_rnn 可以转化的
