### ISSUE TITLE
为什么 release-1.0.0 中的 libMNN.so 和自己编译出来的大小不同？

### ISSUE THREAD

**Issue by 8V8N** [alibaba/MNN#816]
### 平台(如果交叉编译请再附上交叉编译目标平台):  
Android arm64

### Github版本:
commit id: 0df31a86
即 release 1.0.0

### 编译方式:
travis 编译，和 https://github.com/alibaba/MNN/blob/master/.travis.yml 中的编译方法一致。
编译日志： https://travis-ci.org/github/8V8N/MNN/builds/689553648

### 问题：
可以看到我编译出来的 libMNN.so 大小是 1,333,504 Bytes.
而 https://github.com/alibaba/MNN/releases/download/1.0.0/Android.zip 中 Android/android_packages/arm64/libMNN.so 大小是 1,070,936 Bytes. 

两者相差 262 KB.

请问 release 中的 libMNN.so是怎么编译出来的？直接使用 release 中的libMNN.so 会有风险么？

**Comment by jxt1234** [comment]
把 ../build_64.sh 里面的 -DANDROID_STL=c++_static 改成 -DANDROID_STL=c++_shared

**Comment by jxt1234** [comment]
使用的时候，保证其他的so都用 -DANDROID_STL=c++_shared 编译，并且把 libc++_shared.so 打包进 app 即可
