### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by yurivict** [alibaba/MNN#818]
https://github.com/alibaba/MNN/blob/master/tools/cpp/CMakeLists.txt#L19

**Comment by jxt1234** [comment]
? What's the problem?

**Comment by yurivict** [comment]
```testModelWithDescrisbe``` should probably be ```testModelWithDescribe```.

**Comment by wangzhaode** [comment]
Yes, thanks

**Comment by wangzhaode** [comment]
will fix next version.
