### ISSUE TITLE
Demo/exec inference result is wrong of converted tensorflow pb model

### ISSUE THREAD

**Issue by ChisenZhang** [alibaba/MNN#82]
用exec中的pictureRecognition.cpp 调用tensorflow pb分类模型转换的mnn模型。
只改了 归一化部分的mean和normal， 归一化到0-1； 和输入输出的通道格式
float mean[3]     = {0.0f, 0.0f, 0.0f};
float normals[3]  = {0.00392f, 0.00392f, 0.00392f};
config.sourceFormat = RGB;
config.destFormat   = RGB;

推理出来的结果（一共两类）会固定在某个值的一个小范围内变动，（例如0.5x， 0.4x，加和是1）
PB模型单独测试过，没什么问题。

**Comment by jxt1234** [comment]
config.sourceFormat = RGB;

这个 FreeImage 如果解出来是 RGBA 的话，需要指定为 RGBA

**Comment by ChisenZhang** [comment]
> config.sourceFormat = RGB;
> 
> 这个 FreeImage 如果解出来是 RGBA 的话，需要指定为 RGBA

试过换RGBA，但是一样

**Comment by jxt1234** [comment]
具体一些的代码是?

**Comment by ChisenZhang** [comment]
> 具体一些的代码是?

//
//  pictureTest.cpp
//  MNN
//
//  Created by MNN on 2018/05/14.
//  Copyright © 2018, Alibaba Group Holding Limited
//

#include <stdio.h>
#include "ImageProcess.hpp"
#include "Interpreter.hpp"
#define MNN_OPEN_TIME_TRACE
#include <algorithm>
#include <fstream>
#include <functional>
#include <memory>
#include <sstream>
#include <vector>
#include "AutoTime.hpp"
#include "FreeImage.h"
#include <iostream>

using namespace MNN;
using namespace MNN::CV;

int main(int argc, const char* argv[]) {
    if (argc < 3) {
        MNN_PRINT("Usage: ./pictureTest.out model.mnn input.jpg [word.txt]\n");
        return 0;
    }
    std::shared_ptr<Interpreter> net(Interpreter::createFromFile(argv[1]));
    ScheduleConfig config;
    config.type  = MNN_FORWARD_CPU;
    auto session = net->createSession(config);

    auto input  = net->getSessionInput(session, NULL);
    auto output = net->getSessionOutput(session, "MobileNet/prob");
    std::vector<std::string> words;
    if (argc >= 4) {
        std::ifstream inputOs(argv[3]);
        std::string line;
        while (std::getline(inputOs, line)) {
            words.emplace_back(line);
        }
    }
    {
        auto dims    = input->shape();
        int inputDim = 0;
        int size_w   = 0;
        int size_h   = 0;
        int bpp      = 0;
        bpp          = input->channel();
        size_h       = input->height();
        size_w       = input->width();
        if (bpp == 0)
            bpp = 1;
        if (size_h == 0)
            size_h = 1;
        if (size_w == 0)
            size_w = 1;
        MNN_PRINT("input: w:%d , h:%d, bpp: %d\n", size_w, size_h, bpp);

        auto inputPatch     = argv[2];
        FREE_IMAGE_FORMAT f = FreeImage_GetFileType(inputPatch);
        FIBITMAP* bitmap    = FreeImage_Load(f, inputPatch);
        MNN_ASSERT(NULL != bitmap);
        int BPP = FreeImage_GetBPP(bitmap);
        auto newBitmap = FreeImage_ConvertTo32Bits(bitmap);
        FreeImage_Unload(bitmap);
        auto width  = FreeImage_GetWidth(newBitmap);
        auto height = FreeImage_GetHeight(newBitmap);
        MNN_PRINT("origin size: %d, %d, %d\n", width, height, BPP);
        Matrix trans;
        // Dst -> [0, 1]
        trans.postScale(1.0 / size_w, 1.0 / size_h);
        // Flip Y
        trans.postScale(1.0, -1.0, 0.0, 0.5);
        //[0, 1] -> Src
        trans.postScale(width, height);
        ImageProcess::Config config;
        config.filterType = BILINEAR;
        float mean[3]     = {0.0f, 0.0f, 0.0f};//{103.94f, 116.78f, 123.68f};
        float normals[3]  = {0.00392f, 0.00392f, 0.00392f};
        //float mean[3]     = {103.94f, 116.78f, 123.68f};
        //float normals[3]  = {0.017f, 0.017f, 0.017f};
        ::memcpy(config.mean, mean, sizeof(mean));
        ::memcpy(config.normal, normals, sizeof(normals));
        config.sourceFormat = RGB;
        config.destFormat   = RGB;

        std::shared_ptr<ImageProcess> pretreat(ImageProcess::create(config));
        pretreat->setMatrix(trans);
        pretreat->convert((uint8_t*)FreeImage_GetScanLine(newBitmap, 0), width, height, 0, input);
        FreeImage_Save(FIF_PNG, newBitmap, argv[3], PNG_DEFAULT);
        FreeImage_Unload(newBitmap);
    }
    net->runSession(session);
    {
        MNN_PRINT("output size:%d\n", output->elementSize());
        auto type = output->getType();

        auto size = output->elementSize();
        std::vector<std::pair<int, float>> tempValues(size);
        if (type.code == halide_type_float) {
            auto values = output->host<float>();
            for (int i = 0; i < size; ++i) {
                tempValues[i] = std::make_pair(i, values[i]);
            }
        }
        if (type.code == halide_type_uint && type.bytes() == 1) {
            auto values = output->host<uint8_t>();
            for (int i = 0; i < size; ++i) {
                tempValues[i] = std::make_pair(i, values[i]);
            }
        }
        // Find Max
        std::sort(tempValues.begin(), tempValues.end(),
                  [](std::pair<int, float> a, std::pair<int, float> b) { return a.second > b.second; });

        int length = size > 10 ? 10 : size;
        if (words.empty()) {
            for (int i = 0; i < length; ++i) {
                MNN_PRINT("%d, %f\n", tempValues[i].first, tempValues[i].second);
            }
        } else {
            for (int i = 0; i < length; ++i) {
                MNN_PRINT("%s: %f\n", words[tempValues[i].first].c_str(), tempValues[i].second);
            }
        }
    }
    return 0;
}

就原始demo/exec/pictureRecognition.cpp  改了上面说的几行，用自己的模型   我打印了读入图片的BPP，应该就是RGB的

**Comment by jxt1234** [comment]
由于前面已经调了 auto newBitmap = FreeImage_ConvertTo32Bits(bitmap); 
肯定是要设 sourceFormat = RGBA 的

其他的需要看有没有额外的报错信息

**Comment by ChisenZhang** [comment]
> 由于前面已经调了 auto newBitmap = FreeImage_ConvertTo32Bits(bitmap);
> 肯定是要设 sourceFormat = RGBA 的
> 
> 其他的需要看有没有额外的报错信息

其他就没有什么报错了

**Comment by ChisenZhang** [comment]
> 由于前面已经调了 auto newBitmap = FreeImage_ConvertTo32Bits(bitmap);
> 肯定是要设 sourceFormat = RGBA 的
> 
> 其他的需要看有没有额外的报错信息

即使改过来结果也是不正常的，按说pb文件没问题，转换成MNN的时候也没有报错，模型应该是没问题的，但是结果不正确，还有没有其他方面的原因？ 有没有可能是输入的通道顺序和模型使用的通道顺序不一致（NHWC NC4HW4）？我参考了工程里面的其他代码用了如下代码做了转换：
MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());
input->copyFromHostTensor(&inputTensorUser);
不知道调用的对不对，但是跑出来的结果跟不加这两行代码的差不多。

**Comment by jxt1234** [comment]
> > 由于前面已经调了 auto newBitmap = FreeImage_ConvertTo32Bits(bitmap);
> > 肯定是要设 sourceFormat = RGBA 的
> > 其他的需要看有没有额外的报错信息
> 
> 即使改过来结果也是不正常的，按说pb文件没问题，转换成MNN的时候也没有报错，模型应该是没问题的，但是结果不正确，还有没有其他方面的原因？ 有没有可能是输入的通道顺序和模型使用的通道顺序不一致（NHWC NC4HW4）？我参考了工程里面的其他代码用了如下代码做了转换：
> MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());
> input->copyFromHostTensor(&inputTensorUser);
> 不知道调用的对不对，但是跑出来的结果跟不加这两行代码的差不多。

不需要加这个转换。因为用的 ImageProcess 直接转到输入 Tensor 上，
需要看模型的结构了，以及模型输入是不是需要调整大小。
另外代码有更到最新么？

**Comment by ChisenZhang** [comment]
> > > 由于前面已经调了 auto newBitmap = FreeImage_ConvertTo32Bits(bitmap);
> > > 肯定是要设 sourceFormat = RGBA 的
> > > 其他的需要看有没有额外的报错信息
> > 
> > 
> > 即使改过来结果也是不正常的，按说pb文件没问题，转换成MNN的时候也没有报错，模型应该是没问题的，但是结果不正确，还有没有其他方面的原因？ 有没有可能是输入的通道顺序和模型使用的通道顺序不一致（NHWC NC4HW4）？我参考了工程里面的其他代码用了如下代码做了转换：
> > MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());
> > input->copyFromHostTensor(&inputTensorUser);
> > 不知道调用的对不对，但是跑出来的结果跟不加这两行代码的差不多。
> 
> 不需要加这个转换。因为用的 ImageProcess 直接转到输入 Tensor 上，
> 需要看模型的结构了，以及模型输入是不是需要调整大小。
> 另外代码有更到最新么？

模型的输入要求的就是256*256；
Matrix trans;
// Dst -> [0, 1]
trans.postScale(1.0 / size_w, 1.0 / size_h);
// Flip Y
trans.postScale(1.0, -1.0, 0.0, 0.5);
 //[0, 1] -> Src
trans.postScale(width, height);
这几行代码就已经做了resize了吧？ 只不过中间那一句Y轴平移翻转是什么目的，没看懂
代码前几天更新过，刚才又更新了一次，重编之后 一样的结果。
而且发现了一个现象，训练模型使用直接除以255归一化到0-1做的训练，用demo原始代码里面的归一化（设定减固定的均值除以固定的标准差），输出结果竟然比较正常，设置减零除以255做0-1的归一化，输出的结果就是上面说的比较固定，这有可能是什么原因？是因为1/255值太小，优化把图像的很多值都置成0了吗？
模型我给你截图吧，有空帮忙看一下   谢谢
![image](https://user-images.githubusercontent.com/16755579/58020690-79e74f80-7b3b-11e9-915b-4a10ba9bd79e.png)

**Comment by jxt1234** [comment]
那个 Y 值翻转是因为 FreeImage 解码出来的图像 Y 方向是反的，所以额外翻转一次。

"训练模型使用直接除以255归一化到0-1做的训练"，这个要不你再check一下，另外，建议在

pretreat->convert((uint8_t*)FreeImage_GetScanLine(newBitmap, 0), width, height, 0, input);

之后，把 input 里面的值打印出来看看
auto dataPtr = input->host<float>();
for (int h=0; h<256; ++h) {
for (int w=0; w<256; ++w) {
for (int bpp=0; bpp<4; ++bpp) {
printf("%f, ", dataPtr[4*(h*256+w)+bpp]);
}
printf("\n");
}
printf("\n\n");

}

**Comment by ChisenZhang** [comment]
> 那个 Y 值翻转是因为 FreeImage 解码出来的图像 Y 方向是反的，所以额外翻转一次。
> 
> "训练模型使用直接除以255归一化到0-1做的训练"，这个要不你再check一下，另外，建议在
> 
> pretreat->convert((uint8_t*)FreeImage_GetScanLine(newBitmap, 0), width, height, 0, input);
> 
> 之后，把 input 里面的值打印出来看看
> auto dataPtr = input->host();
> for (int h=0; h<256; ++h) {
> for (int w=0; w<256; ++w) {
> for (int bpp=0; bpp<4; ++bpp) {
> printf("%f, ", dataPtr[4*(h*256+w)+bpp]);
> }
> printf("\n");
> }
> printf("\n\n");
> 
> }

check过了，打印归一化之后的值，也没有发现异常，正常的四通道，0-1之间的值，alpha通道都是零；runSession的返回值也是正常的值；难道说模型有问题？ 我单独测试过PB文件，测试集上分类正常，转换MNN模型也没有报错

**Comment by jxt1234** [comment]
你“测试过PB文件”的代码是怎么样的，另外可以用回调接口打印 MNN 中间输出的结果看一下，看是否是某个 Op 计算错误了

**Comment by jxt1234** [comment]
对了，你这个模型的输出只有 2，所以建议这段代码改成

    auto size = 2;
    std::vector<std::pair<int, float>> tempValues(size);
    if (type.code == halide_type_float) {
        auto values = output->host<float>();
        for (int i = 0; i < size; ++i) {
            tempValues[i] = std::make_pair(i, values[i]);
        }
    }

**Comment by ChisenZhang** [comment]
> 你“测试过PB文件”的代码是怎么样的，另外可以用回调接口打印 MNN 中间输出的结果看一下，看是否是某个 Op 计算错误了

'''
        :param pb_path:pb文件的路径
        :param image_path:测试图片的路径
        :return:
        '''
    with tf.Graph().as_default():
        output_graph_def = tf.GraphDef()
        with open(pb_path, "rb") as f:
            output_graph_def.ParseFromString(f.read())
            tf.import_graph_def(output_graph_def, name="")
        with tf.Session() as sess:

            # 定义输入的张量名称,对应网络结构的输入张量
            input_image_tensor = sess.graph.get_tensor_by_name("x:0")

            # 定义输出的张量名称
            output_tensor_name = sess.graph.get_tensor_by_name("MobileNet/prob:0")
            for subFd in os.listdir(folder):
                subPath = os.path.join(folder, subFd)
                for fileN in os.listdir(subPath):
                    imgPath = os.path.join(subPath, fileN)
                    try:
                        image = Image.open(imgPath)
                        image_data = utils.process_image(image) # 读图归一化图片
                    except Exception as E:
                        print('Open Error! ', imgPath, E)
                        continue
                    else:
                        picName = fileN.split('/')[-1]
                        cls = picName.split('_')[-1][:4]
                        if cls == 'NOR1':
                            cls = 'NORMAL'
                            NORN += 1
                        else:
                            cls = 'ILLEGAL'
                            ILLN += 1
                        t1 = time.time()
                        out = sess.run(output_tensor_name, feed_dict={input_image_tensor: image_data})
                        pred_class_index = np.argmax(out, axis=1)[0]
                        pred_prob = out[0, pred_class_index]
                        pred_class = classes[pred_class_index]
                        t2 = time.time()
                        if pred_class == cls:
                            tp += 1
                        else:
                            if cls == 'NORMAL':
                                NOREN += 1
                                # open(os.path.join(NOREP, picName), 'wb').write(open(os.path.join(tmPath, line), 'rb').read())
                            else:
                                ILLEN += 1
                                # open(os.path.join(ILLEP, picName), 'wb').write(open(os.path.join(tmPath, line), 'rb').read())
                            print(picName, cls, pred_class, pred_prob)
                        count += 1

PB模型测试代码大概就是这样

中间结果，打出来怎么看它计算的对不对？

**Comment by ChisenZhang** [comment]
> 对了，你这个模型的输出只有 2，所以建议这段代码改成
> 
> ```
> auto size = 2;
> std::vector<std::pair<int, float>> tempValues(size);
> if (type.code == halide_type_float) {
>     auto values = output->host<float>();
>     for (int i = 0; i < size; ++i) {
>         tempValues[i] = std::make_pair(i, values[i]);
>     }
> }
> ```
> 
> 输出的不稳定有可能是因为取了未定义的 values[2], values[3]

取了未定义的值，应该是个随机值吧，不可能每次都正好加和等1，我也试了，没什么变化

**Comment by jxt1234** [comment]
参考 tools/cpp/MNNV2Basic.cpp 的代码，正常的话每次 Op 中间输出是相同的。
看哪个 Op 的输出结果多次跑有变化就好。

utils.process_image 具体是？

**Comment by ChisenZhang** [comment]
> 参考 tools/cpp/MNNV2Basic.cpp 的代码，正常的话每次 Op 中间输出是相同的。
> 看哪个 Op 的输出结果多次跑有变化就好。
> 
> utils.process_image 具体是？

def process_image(image, imgSize=(256, 256)):
    image_resize = image.resize(imgSize)
    image_data = np.array(image_resize)
    img_ = image_data/255.
    img_ = img_.reshape([1, imgSize[0], imgSize[1], 3])
    return img_

回调我试了一下   beforecallBack 和callBack 还没弄懂什么意思，但是里面我都把tensor的值打印出来了，callback代码如下：
MNN::TensorCallBack beforeCallBack = [&](const std::vector<MNN::Tensor*>& ntensors, const std::string& opName) {
            //if (!saveInput) {
            //    return true;
            //}
            for (int i = 0; i < ntensors.size(); ++i) {
                auto ntensor      = ntensors[i];
                auto expectTensor = new MNN::Tensor(ntensor, MNN::Tensor::TENSORFLOW);
                ntensor->copyToHostTensor(expectTensor);

                auto tensor = ntensor;

                //std::ostringstream outputFileName;
                auto opCopyName = opName;
                for (int j = 0; j < opCopyName.size(); ++j) {
                    if (opCopyName[j] == '/') {
                        opCopyName[j] = '_';
                    }
                }
                MNN_PRINT("Dump %s Input, %d, %d X %d X %d\n", opName.c_str(), i, tensor->width(), tensor->height(), tensor->channel());
                //outputFileName << "output/Input_" << opCopyName << "_" << i;
                
                auto dataPtr = expectTensor->host<float>();
                for (int h=0; h<expectTensor->height(); ++h) {
                   for (int w=0; w<expectTensor->width(); ++w) {
                      for (int bpp=0; bpp<expectTensor->channel(); ++bpp) {
                          printf("%f, ", dataPtr[expectTensor->channel()*(h*expectTensor->height()+w)+bpp]);
                      }
                      printf("\n");
                   }
                   printf("\n\n");
                }
                delete expectTensor;
            }
            return true;
        };
        MNN::TensorCallBack callBack = [&](const std::vector<MNN::Tensor*>& ntensors, const std::string& opName) {
            for (int i = 0; i < ntensors.size(); ++i) {
                auto ntensor      = ntensors[i];
                auto expectTensor = new MNN::Tensor(ntensor, ntensor->getDimensionType());
                ntensor->copyToHostTensor(expectTensor);

                auto tensor = expectTensor;

                //std::ostringstream outputFileName;
                auto opCopyName = opName;
                for (int j = 0; j < opCopyName.size(); ++j) {
                    if (opCopyName[j] == '/') {
                        opCopyName[j] = '_';
                    }
                }
                MNN_PRINT("W,H,C,B: %d X %d X %d X %d, %s : %d\n", tensor->width(), tensor->height(), tensor->channel(), tensor->batch(), opName.c_str(), i);
                //outputFileName << "output/" << opCopyName << "_" << i;
                auto dataPtr = expectTensor->host<float>();
                for (int h=0; h<expectTensor->height(); ++h) {
                   for (int w=0; w<expectTensor->width(); ++w) {
                      for (int bpp=0; bpp<expectTensor->channel(); ++bpp) {
                          printf("%f, ", dataPtr[expectTensor->channel()*(h*expectTensor->height()+w)+bpp]);
                      }
                      printf("\n");
                   }
                   printf("\n\n");
                }
                delete expectTensor;
            }
            return true;
        };
    auto err_code = net->runSessionWithCallBack(session, beforeCallBack, callBack, true);

除了输入之外出现了大批零值，输入之后  绝大部分输出都是零， 如果回调的打印部分没有写错，这个不正常吧；  我把归一化的除以255，改成了除以128，又会有很多零值变成非零

**Comment by ChisenZhang** [comment]
> 参考 tools/cpp/MNNV2Basic.cpp 的代码，正常的话每次 Op 中间输出是相同的。
> 看哪个 Op 的输出结果多次跑有变化就好。
> 
> utils.process_image 具体是？

我对比了，同一张图多次跑的结果是完全相同的，用上面的代码只打出来callback的tensor，第一个卷积开始，很多tensor的值都是零，模型应该不至于稀疏到这种程度吧？第一层卷积我是用的7*7 stride=4，有没有可能是这里的问题？

**Comment by jxt1234** [comment]
Tensor 的很多值为零的原因是估计是有很多负数，而第一层卷积合并了 relu6

**Comment by ChisenZhang** [comment]
> Tensor 的很多值为零的原因是估计是有很多负数，而第一层卷积合并了 relu6

这种情况的话怎么解决？模型学习不应该学习到权重乘输入得到很多负值的输入吧，这样的话一张图可以理解，很多张图都这样就说不通了，大量的零值也有可能是模型容量太大了，样本太少，但是在我的这个应用上不太成立。有很多负数的话，relu6换成relu也解决不了问题。我尝试把PB模型转换成ONNX模型，ONNX的调用输出结果是正常的，ONNX再转MNN的话就提示Cast OP不支持。

**Comment by jxt1234** [comment]
方便的话能发一个可以复现问题的pb模型到我邮箱么，这个没有具体场景我暂时看不出问题在哪

**Comment by ChisenZhang** [comment]
> 方便的话能发一个可以复现问题的pb模型到我邮箱么，这个没有具体场景我暂时看不出问题在哪

已发，麻烦了

**Comment by ChisenZhang** [comment]
bug of MNN converter, due to BN behind the relu. Thanks for @jxt1234 's help.

**Comment by chenjun2hao** [comment]
@ChisenZhang ,你好，请问你的模型截图，是可视化的mnn格式的模型，还是其他格式的模型呀？我想看一下mnn格式模型保存的样式。感谢。
