### ISSUE TITLE
MNN训练框架在前向推理时是否会存储中间结果？如果会的话是存储在何处呢

### ISSUE THREAD

**Issue by Nova-xiao** [alibaba/MNN#821]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
MacOS Catalina 10.15交叉编译到Xiaomi 9SE

我在手机上测试了一下MobileNetV2的训练Demo，发现默认的BatchSize会卡死，检测发现是存储的原因。现在希望修改一下训练框架，加入swap或者recompute来减少中间结果的存储，不过官方文档中对于训练框架的描述太少，目前不太清楚MNN训练时中间结果具体是在框架里哪个部分存储？

**Comment by jxt1234** [comment]
MNN训练框架基于表达式计算机制。
表达式计算机制默认不会存储中间结果，但可以指定部分变量存储中间结果以减少重复计算。
MobilenetV2 里面有个BN 层会调用这个接口。具体代码可以参考

tools/train/source/module/NN.cpp

和 

express/Executor.cpp

**Comment by Nova-xiao** [comment]
没有存储中间结果的话，那训练框架具体是怎么计算grad的呢？反向传播时会重新计算吗？

**Comment by jxt1234** [comment]
表达式计算机制是延迟计算，一般情况下是反向传播到最后需要更新梯度时，才对整图进行计算

**Comment by Nova-xiao** [comment]
有两个问题：
（1）这个”延迟计算“是recompute（也就是需要时重新计算tensor的技术）的意思吗？据我的了解，这种技术是为了减少内存开销，但是如果最后还是需要对整图进行计算，那么似乎并不能减少内存开销？
（2）MNN训练框架为什么要采用这种设计，而不是像tensorflow和pytorch那样，在inference时就储存中间结果？

**Comment by jxt1234** [comment]
（1）只需要保存用户需要的结果即可，不需要保存中间结果
（2）主要出于性能考虑，使动态图的用法接近静态图inference的性能。
A、可以减少中间内存开销
B、可以做一些计算路径的优化，提升整体性能

**Comment by Nova-xiao** [comment]
感觉您没有明白我的意思😢我想问的是关于这个训练框架，既然反向传播需要前向推理时的中间结果，而且前向推理时也没有存储这个中间结果，那么在使用时是通过重新计算来获得的吗？这个重新计算的机制大概是怎么个实现方式呢？麻烦您了~

**Comment by jxt1234** [comment]
反向传播需要前向推理时的中间结果，但不需要存储，最终存储梯度即可，中间结果会有内存复用机制复用
