### ISSUE TITLE
win10运行使用opencl后端推理报错

### ISSUE THREAD

**Issue by dl8207531** [alibaba/MNN#823]
windows10 64位
mnn1.0 
opencl 2.1
i3 7100u
cpu推理正常
--------------------------
MNN benchmark
Forward type: **OpenCL** thread=4** precision=2
--------> Benchmarking... loop = 10, warmup = 10
ERROR CODE : -54
ERROR CODE : -54
ERROR CODE : -54
ERROR CODE : -54
ERROR CODE : -54
ERROR CODE : -54
ERROR CODE : -54

**Comment by jxt1234** [comment]
opencl 不同机型的适配可能存在问题，建议编译并使用 Vulkan 后端

**Comment by dl8207531** [comment]
推荐使用Vulkan 是吧，是说Vulkan 兼容性更好是吗？ 
opencl这些适配性问题后面会修改吗？

**Comment by jxt1234** [comment]
1、是的。
2、暂无针对PC机进一步完善OpenCL Backend的计划
