### ISSUE TITLE
MNN with cuda support

### ISSUE THREAD

**Issue by naserpiltan** [alibaba/MNN#825]
Hi.
I am working on a road segmentation project with MNN.
I searched a lot and found this usefull repo (thanks to @MaybeShewill-CV ):
[https://github.com/MaybeShewill-CV/lanenet-lane-detection](https://github.com/MaybeShewill-CV/lanenet-lane-detection)
I built all the necessary libraries and dependencies successfully and can use lanenet.MNN model in my c++ project successfully.
But my segementation operation is too slow because it is running on the CPU (1 FPS )and that is a big issue for me .
I am wondering to build MNN with cuda support to accelerate inference operation . I read docs bout couldn't find any thing about that.
My question is : does MNN support cuda toolkit ? and what is proper way to use MNN models like lanenet.MNN model with cuda support.?
Thanks in advance.

**Comment by jxt1234** [comment]
Currently MNN don't support CUDA. You can use vulkan instead.

**Comment by naserpiltan** [comment]
@jxt1234  thanks for your answer.
Im  not familiar with vulkan.can you give some information about that and how can build MNN with vulkan support ?

**Comment by jxt1234** [comment]
If you are linux system, install vulkan diver and then build MNN as this:
cmake .. -DMNN_VULKAN=true -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false

**Comment by naserpiltan** [comment]
@jxt1234 thank you . Yeah im on linux OS . I got it.
Im going to try it and i will write the result here.

**Comment by naserpiltan** [comment]
@jxt1234  im tried your provided command : 

> cmake .. -DMNN_VULKAN=true -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false

But cmake rises below warning :

`CMake Warning:
  Manually-specified variables were not used by the project:
    MNN_SEP_BUILD
    MNN_USE_SYSTEM_LIB
    MNN_VULKAN
`

**Comment by naserpiltan** [comment]
@jxt1234  sorry . i was on wrong project. i deleted my previous comment. Now i am on MNN project.
i installed vulkan and tested it successfully with this command :  **vulkaninfo | less**. Now vulkan is linked with my NVIDIA GTX 1060 graphic card. 
Then i created a build directory in the MNN project and opened a terminlal and tried this CMAKE command :
` cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_VULKAN=true -DMNN_USE_SYSTEM_LIB=true -DMNN_SEP_BUILD=false` 

But Now i have this error :

`CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindVulkan.cmake:69 (find_package_handle_standard_args)
  source/backend/vulkan/CMakeLists.txt:9 (find_package)
`
seems that cmake can not find vulkan correct path.do i have to modify CMakeLists.txt ?
Please give me a solution.
Thank you

**Comment by naserpiltan** [comment]
Ok, i solved the above problem. I had to install the vulkan sdk and now can build the MNN with vulkan backend.
i set **mnn_config.type = MNN_FORWARD_VULKAN ** nad run my program.
But it is too slow and have some issues like this :

> Vulkan don't support 2, ArgMax: lanenet_model/vgg_backend/binary_seg/ArgMax
Vulkan don't support 9, Cast: lanenet/Cast

@jxt1234  do you know that  what is the problem ?

**Comment by jxt1234** [comment]
Only two op not support may don't cause it too slow. Do you test it by MNNV2Basic.out ?

**Comment by naserpiltan** [comment]
@jxt1234  i tested it as you said with this commands :
**./MNNV2Basic.out model.mnn 3 0 0**

 gives output :

> Use extra forward type: 0
Open Model model.mnn
test_main, 195, cost time: 1371.335083 ms
===========> Session Resize Done.
===========> Session Start running...
Input: 1, 256, 512, 3
Run 3 time:
                       lanenet/final_binary_output 	[Squeeze] run 3 average cost 0.025000 ms, 0.003 %, FlopsRate: 0.000 %
                                      lanenet/Cast 	[Cast] run 3 average cost 0.030333 ms, 0.004 %, FlopsRate: 0.000 %
              lanenet/final_pixel_embedding_output 	[Squeeze] run 3 average cost 0.115667 ms, 0.014 %, FlopsRate: 0.001 %

and  **./MNNV2Basic.out model.mnn 3 0 7**
gives output :

> Use extra forward type: 7
 Open Model model.mnn
Vulkan don't support 2, ArgMax: lanenet_model/vgg_backend/binary_seg/ArgMax
Vulkan don't support 9, Cast: lanenet/Cast
test_main, 195, cost time: 1218.801025 ms
===========> Session Resize Done.
===========> Session Start running...
Input: 1, 256, 512, 3
Run 3 time:
 lanenet/final_binary_output 	[Squeeze] run 3 average cost 0.046667 ms, 0.001 %, FlopsRate: 0.000 %
                                      lanenet/Cast 	[Cast] run 3 average cost 0.052667 ms, 0.002 %, FlopsRate: 0.000 %
       lanenet_model/vgg_backend/binary_seg/ArgMax 	[ArgMax] run 3 average cost 2235.100098 ms, 68.559 %, FlopsRate: 0.000 %

in my own lanenet project (based on this repo [https://github.com/MaybeShewill-CV/lanenet-lane-detection](https://github.com/MaybeShewill-CV/lanenet-lane-detection)
with **mnn_config.type = MNN_FORWARD_CPU** result :

> detect, 211, cost time: 0.246000 ms
detect, 146, cost time: 0.838000 ms
detect, 153, cost time: 872.728027 ms
detect, 204, cost time: 29.430002 ms

with **mnn_config.type = MNN_FORWARD_VULKAN** result :

> Vulkan don't support 2, ArgMax: lanenet_model/vgg_backend/binary_seg/ArgMax
Vulkan don't support 9, Cast: lanenet/Cast
detect, 146, cost time: 0.755000 ms
detect, 153, cost time: 2487.019043 ms
detect, 204, cost time: 31.821001 ms

I think MNN lanenet can't use vulkan. but i dont know why.

**Comment by jxt1234** [comment]
Could you send me your model? Just the structure?

**Comment by naserpiltan** [comment]
@jxt1234  sir, Did you check it ? 
I stuck in this step and i don't know what to do .

**Comment by jxt1234** [comment]
Sorry. I can't find your mode in project, could you upload it?

**Comment by naserpiltan** [comment]
@jxt1234  ok, i uploadet it , you can find it in this link :
[https://gofile.io/d/GVQVrU](https://gofile.io/d/GVQVrU)

**Comment by jxt1234** [comment]
Currently mnn has supported cuda.

**Comment by TomatoBoy90** [comment]
> Currently mnn has supported cuda.

mnn文档里面还没呢，怎么使用？
