### ISSUE TITLE
采用python接口进行mnn推理，结果predict.shape和predict.read()出来的数据维度不一样

### ISSUE THREAD

**Issue by zymale** [alibaba/MNN#826]
dv=F.const(img.flatten().tolist(),[1,1,512,512],F.data.format.NCHW)
predict=feature_extractor.forward(dv)
print(predict.shape)
out=np.array(predict.read())
out1=out.reshape(1,-1,64,64)
print(out1.shape)
输出为:
[1,2,64,64]
[1,4,64,64]
read读取的数据维度不对，实际模型输出应该是1,2,64,64
mnn的python库版本，1.0.0

**Comment by stanleywang8888** [comment]
文档里面提过的, 因为部分内部tensor是nc4hw4的输出，维度扩增到4的倍数了, 创建一个tensor拷贝出来就可以了

**Comment by zymale** [comment]
但是我用forward输出的不是tensor是mnncengine.expr.var对象，只有interpreter.getSessionOutput接口输出才是tensor，这样我要训练模型没找到对应转换接口

**Comment by stanleywang8888** [comment]
1. predict的format打出来看看
2. 用1.0.1的接口, 直接出来就是numpy了

**Comment by mjanddy** [comment]
> 1. predict的format打出来看看
> 2. 用1.0.1的接口, 直接出来就是numpy了

用mnn1.0.1，使用out.getData(),出来的结果是NCHW还是NC4HW4呢？

**Comment by stanleywang8888** [comment]
1. 原有的接口是无法看出来是nc4hw4还是nchw的, getData()出来数据多了, 就是nc4hw4 . 
2. 不确定的tensor在于session里面的type, 也就是说模型转换时有的模型输入输出为了性能考虑，就已经转成了nc4hw4,  所以绝对不会错误的逻辑在于， session里面拿到的input tensor从临时tensor里面copy进来/output tensor拷贝到零时的tensor里面去，这样做逻辑上绝对不会错，但是可能多了一次不必要的拷贝操作
3. MNN的很多场景里面对性能要求也极高，原始设计没有说去了为了易用性去做多余的判断和自动拷贝去对用户隐藏这个内部的nc4hw4格式，所以选择权在于用户自己判断，需要debug一下，新的numpy也延续了这个逻辑，你临时的tensor是对的，numpy就是对的，你出来的是nc4hw4，出来的numpy就是错的，需要一次copy，用拷贝后的tensor转的numpy出来

**Comment by mjanddy** [comment]
> 1. 原有的接口是无法看出来是nc4hw4还是nchw的, getData()出来数据多了, 就是nc4hw4 .
> 2. 不确定的tensor在于session里面的type, 也就是说模型转换时有的模型输入输出为了性能考虑，就已经转成了nc4hw4,  所以绝对不会错误的逻辑在于， session里面拿到的input tensor从临时tensor里面copy进来/output tensor拷贝到零时的tensor里面去，这样做逻辑上绝对不会错，但是可能多了一次不必要的拷贝操作
> 3. MNN的很多场景里面对性能要求也极高，原始设计没有说去了为了易用性去做多余的判断和自动拷贝去对用户隐藏这个内部的nc4hw4格式，所以选择权在于用户自己判断，需要debug一下，新的numpy也延续了这个逻辑，你临时的tensor是对的，numpy就是对的，你出来的是nc4hw4，出来的numpy就是错的，需要一次copy，用拷贝后的tensor转的numpy出来

有具体怎么copy的代码吗？我使用
![image](https://user-images.githubusercontent.com/27938658/84224326-ce76b780-ab0e-11ea-9732-55e21a6ca37b.png)方法，但是出来的的结果还是不对，不知道是不是用错了

**Comment by stanleywang8888** [comment]
为啥不是dst_tensor.getData()?

**Comment by mjanddy** [comment]
> 为啥不是dst_tensor.getData()?

不清楚用法..我试试

**Comment by mjanddy** [comment]
> 为啥不是dst_tensor.getData()?

其他的代码写的正确吗？

**Comment by stanleywang8888** [comment]
片段看起来是对的,你最后getData不放出来，我都想不到你能这么getData. 
session里面的格式你不知道, copy出来以后确定了，你还从原来不确定的地方拿

**Comment by mjanddy** [comment]
> 片段看起来是对的,你最后getData不放出来，我都想不到你能这么getData.
> session里面的格式你不知道, copy出来以后确定了，你还从原来不确定的地方拿

terminate called after throwing an instance of 'std::runtime_error'
  what():  numpy type does not match
 生成des-tensor 那行报错，是什么问题吗？

**Comment by stanleywang8888** [comment]
x = np. ones([1,17,120,112])
x = x.astype(np.float32)
des_tensor = ...

**Comment by HuangShiqing** [comment]
> > 片段看起来是对的,你最后getData不放出来，我都想不到你能这么getData.
> > session里面的格式你不知道, copy出来以后确定了，你还从原来不确定的地方拿
> 
> terminate called after throwing an instance of 'std::runtime_error'
> what(): numpy type does not match
> 生成des-tensor 那行报错，是什么问题吗？

试一下pip install MNN==1.0.0。目前默认安装是1.0.1版本的，按上面说的应该是数据检查更严格了
