### ISSUE TITLE
Onnx slice must use the same dimensition

### ISSUE THREAD

**Issue by GHLab** [alibaba/MNN#829]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Mac OS

# Github版本:
# Github Version: 1.0.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
Hi,
I commencted https://github.com/alibaba/MNN/issues/657 but not being resolved so comment again.
I tried to convert onnx to mnn but it was failed. 
You can check the log below and can reproduce it by https://github.com/GHLab/fsanet-onnx-demo/blob/master/fsanet_epoch_95.onnx
I tested the onnx on python and c++ environment by onnxruntime library but there was no issue.
Can you check this?
Thank you.

Start to Optimize the MNN Net...
Error for 20
Error for 21
Error for 20
Error for 21
Error for 20
Error for 21
Error for 17
Onnx slice must use the same dimensition
Convert Onnx's Op 313 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 324 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 323 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 322 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 314 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 326 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 327 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 325 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 315 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 329 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 330 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 328 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 313 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 324 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 323 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 322 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 314 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 326 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 327 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 325 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 315 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 329 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 330 , type = Slice, failed, may be some node is not const
Onnx slice must use the same dimensition
Convert Onnx's Op 328 , type = Slice, failed, may be some node is not const
Error for 20
Error for 21
Error for 20
Error for 21
Error for 20
Error for 21
Error for 17
Error for 20
Error for 21
Error for 20
Error for 21
Error for 20
Error for 21
Error for 17
37 op name is empty or dup, set to Input37
[11:38:34] /Users/ghlab/Dev/git/MNN/tools/converter/source/optimizer/PostConverter.cpp:20: Inputs: input.1
[11:38:34] /Users/ghlab/Dev/git/MNN/tools/converter/source/optimizer/PostConverter.cpp:20: Inputs: 37
[11:38:34] /Users/ghlab/Dev/git/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 448, Type = BinaryOp
libc++abi.dylib: terminating with uncaught exception of type Error: [11:38:34] /Users/ghlab/Dev/git/MNN/tools/converter/source/common/writeFb.cpp:128: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX::Slice |
Abort trap: 6

**Comment by jxt1234** [comment]
Currently ONNX::Slice only support for fixed dimension. We will try to solve it.

**Comment by lcaikk1314** [comment]
> Currently ONNX::Slice only support for fixed dimension. We will try to solve it.



> Currently ONNX::Slice only support for fixed dimension. We will try to solve it.

你好，我使用的模型是输入尺寸固定的，在转化时依然会报这个错，请问你所指的是否是输入固定分辨率？
