### ISSUE TITLE
./schema/generate.sh   error

### ISSUE THREAD

**Issue by shigang** [alibaba/MNN#83]
ubuntu 18.04  
cmake version 3.10.2
gcc version 7.4.0

output:
```
*** building flatc ***
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: Error executing cmake::LoadCache(). Aborting.

*** cleaning up ***
*** generating fbs under default ***
xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Generating Schema...
*** building flatc ***
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in

CMake Error: Error executing cmake::LoadCache(). Aborting.

xargs: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
./generate_schema.sh: line 39: ../../3rd_party/flatbuffers/tmp/flatc: No such file or directory
===> Done!
*** done ***
```

how can i fix the problem ?

**Comment by ChisenZhang** [comment]
install cmake>=3.9

**Comment by shigang** [comment]
> install cmake>=3.9
thx, but my cmake version is  3.10.2

**Comment by ChisenZhang** [comment]
> > install cmake>=3.9
> > thx, but my cmake version is  3.10.2

add cmake's path and bin folder to system PATH, use cmake --version to check

**Comment by shigang** [comment]
> > > install cmake>=3.9
> > > thx, but my cmake version is  3.10.2
> 
> add cmake's path and bin folder to system PATH, use cmake --version to check

![image](https://user-images.githubusercontent.com/11625340/58004354-a4261680-7b15-11e9-9d33-a99482a1bcd4.png)

**Comment by ChisenZhang** [comment]
> > > > install cmake>=3.9
> > > > thx, but my cmake version is  3.10.2
> > 
> > 
> > add cmake's path and bin folder to system PATH, use cmake --version to check
> 
> ![image](https://user-images.githubusercontent.com/11625340/58004354-a4261680-7b15-11e9-9d33-a99482a1bcd4.png)

my ~/.bashrc write like this：
export CMAKE_HOME=/your/path/of/cmake/cmake-3.14.3
export PATH=$PATH:$CMAKE_HOME/bin
may be you can try like this, I think the error was happened because  your system can't find the root path of cmake

**Comment by shigang** [comment]
> > > > > install cmake>=3.9
> > > > > thx, but my cmake version is  3.10.2
> > > 
> > > 
> > > add cmake's path and bin folder to system PATH, use cmake --version to check
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/11625340/58004354-a4261680-7b15-11e9-9d33-a99482a1bcd4.png)
> 
> my ~/.bashrc write like this：
> export CMAKE_HOME=/your/path/of/cmake/cmake-3.14.3
> export PATH=$PATH:$CMAKE_HOME/bin
> may be you can try like this, I think the error was happened because your system can't find the root path of cmake

![image](https://user-images.githubusercontent.com/11625340/58009073-3b906700-7b20-11e9-85f4-84bd16a66287.png)
![image](https://user-images.githubusercontent.com/11625340/58009085-43500b80-7b20-11e9-9301-9241c22470a7.png)

don't work...

**Comment by li-qing** [comment]
check doc/FAQ.md. we provide solutions there.

**Comment by mali105358** [comment]
In this sh file, use "env -i bash -l -c cmake ...", it mean use a new empty environment, so can not find cmake environment. you can remove "env -i" or remove "-i".

**Comment by Asuna88** [comment]
解决方法： 
1.git clone https://github.com/google/flatbuffers
2.replace /MNN/3rd_party/flatbuffers
https://github.com/alibaba/MNN/issues/1141
