### ISSUE TITLE
Using MNN in javascript

### ISSUE THREAD

**Issue by jadenwjh** [alibaba/MNN#832]
Hi can i use MNN in a javascript framework? I am planning to convert run an ONNX model in a mobile browser using MNNConverter.

嗨，我可以在JavaScript框架中使用MNN吗？我打算使用MNNConverter在移动浏览器中转换运行ONNX模型。

**Comment by Swapnil-gautam** [comment]
Hey @jadenwjh were you able to find a solution ?

**Comment by wangzhaode** [comment]
可以尝试编译到`wasm`
