### ISSUE TITLE
分割模型安卓部署时遇到的问题

### ISSUE THREAD

**Issue by luqiang6q** [alibaba/MNN#838]
版本0.2.2+安卓部署：
1. 非固定输入+VULKAN情况下，runSession卡住然后强退或者预测结果会突然一直不正确
3. 非固定输入+OPENCL+宽高比过大情况下（宽是高的7-8倍以上），runSession卡住然后强退或预测结果会不正确

以上问题，非固定输入下，在CPU下运行未出现上述问题。或者将输入尺寸固定，采用OPENCL或VULKAN计算，也不会出现以上问题。。。。。很奇怪

**Comment by luqiang6q** [comment]
更新下第二条中，宽高比过大的表述不准确，主要是最大尺寸的限制，我在我模型上测试，最大尺寸超过528模型结果就会不正确

**Comment by jxt1234** [comment]
Vulkan / OpenCL 存在 Tensor 大小限制，大于一定值时由于系统的纹理大小限制会无法支持，这个问题我们在想办法解决中

**Comment by GYxiaOH** [comment]
这个问题现在解决了吗，我输入图像过大好像也会提示无法支持
