### ISSUE TITLE
MNN_OPTIMIZE_INT8_SSE ON doesn't compile

### ISSUE THREAD

**Issue by charlestamz** [alibaba/MNN#839]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version: 1.0

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
cmake 3.16
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
bin/cmake -DCMAKE_BUILD_TYPE=Release  -DMNN_FMA_ENABLE=ON -DMNN_OPTIMIZE_INT8_SSE=ON  -G "CodeBlocks - Unix Makefiles" /home/kanbig/cpplib/MNN
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/kanbig/cpplib/MNN/build
-- x86_64: Open SSE
-- Configuring done
-- Generating done

-- Build files have been written to:  cpplib/MNN/build

[Finished]

# 编译日志:
# Build Log:
[  3%] Built target MNNSSE
Scanning dependencies of target GenVCSHDR
[  3%] Built target MNNMath
[  8%] Built target MNNCV
[ 13%] Built target MNNCore
[ 14%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp.o
[ 14%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNMatrixAdd.cpp.o
[ 14%] Building CXX object CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNMatrixSub.cpp.o
[ 14%] Built target GenVCSHDR
[ 22%] Built target MNNCompute
[ 51%] Built target MNNShape
[ 97%] Built target MNNCPU
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:31:0,
                 from /home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:12:
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp: In function ?void _AVX_MNNGemmInt8AddBiasScale_16x4_Unit(int8_t*, const int8_t*, const int8_t*, const int32_t*, const float*, size_t, size_t, size_t)?:
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(2) long long int? to ?__v4sf {aka __vector(4) float}? in initialization
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(2) long long int? to ?__v4sf {aka __vector(4) float}? in initialization
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(2) long long int? to ?__v4sf {aka __vector(4) float}? in initialization
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(2) long long int? to ?__v4sf {aka __vector(4) float}? in initialization
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(4) float? to ?__vector(2) long long int? in assignment
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(4) float? to ?__vector(2) long long int? in assignment
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(4) float? to ?__vector(2) long long int? in assignment
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
/home/kanbig/cpplib/MNN/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp:110:13: error: cannot convert ?__vector(4) float? to ?__vector(2) long long int? in assignment
             _MM_TRANSPOSE4_PS(dst0, dst1, dst2, dst3);
             ^
CMakeFiles/MNNAVX.dir/build.make:88: recipe for target 'CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp.o' failed
make[3]: *** [CMakeFiles/MNNAVX.dir/source/backend/cpu/x86_x64/avx/MNNGemmFloatCommon_4.cpp.o] Error 1
CMakeFiles/Makefile2:151: recipe for target 'CMakeFiles/MNNAVX.dir/all' failed
make[2]: *** [CMakeFiles/MNNAVX.dir/all] Error 2
CMakeFiles/Makefile2:303: recipe for target 'CMakeFiles/MNN.dir/rule' failed
make[1]: *** [CMakeFiles/MNN.dir/rule] Error 2
Makefile:229: recipe for target 'MNN' failed
make: *** [MNN] Error 2
```
粘贴在这里
Paste log here or pastebin
```

**Comment by jxt1234** [comment]
The int8 inference in x86 will optimized by another way. The macro is only for test
