### ISSUE TITLE
MNNConverter from tensorflow not working

### ISSUE THREAD

**Issue by dimitryn** [alibaba/MNN#84]
Hi , I am trying to test MNN on our device .

 I took our pb model and try to call MNNConverter according to your doc.

Ubuntu 16
MNN-0.1.1.3

./MNNConvert -f TF --modelFile /home/administrator/Shared/sphereface_v3.pb --MNNModel model.mnn -bizCode 0000 

No matter what I do , it always  print out :

Usage:
  MNNConvert [OPTION...]

  -h, --help            Convert Other Model Format To MNN Model

  -v, --version         show current version
  -f, --framework arg   model type, ex: [TF,CAFFE,ONNX,TFLITE,MNN]
      --modelFile arg   tensorflow Pb or caffeModel, ex: *.pb,*caffemodel
      --prototxt arg    only used for caffe, ex: *.prototxt
      --MNNModel arg    MNN model, ex: *.mnn
      --benchmarkModel  Do NOT save big size data, such as Conv's weight,BN's
                        gamma,beta,mean and variance etc. Only used to test
                        the cost of the model
      --bizCode arg     MNN Model Flag, ex: MNN
      --debug           Enable debugging mode.

Can you help me with it.
Thanks.

**Comment by czy2014hust** [comment]
—bizCode
