### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by clive-g-brown** [alibaba/MNN#840]
OSX Catalina

fatal error: 'MNN_generated.h'
      file not found
#include "MNN_generated.h"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution1x1Strassen.cpp.o] Error 1
make[1]: *** [CMakeFiles/MNNCompute.dir/all] Error 2
make: *** [all] Error 2

# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by Sejudyblues** [comment]
兄弟你解决了嘛 按照语雀的快速上手的例程，编译出现与你同样的问题。。。

**Comment by xiao9616** [comment]
同问题

**Comment by clive-g-brown** [comment]
No i only had a quick look. Cloned the repo and followed the quick start exactly. I can't find this file in the repo?


MNN/source/cv/ImageFloatBlitter.cpp:10:10: fatal error: 'Tensor_generated.h' file not
      found
#include "Tensor_generated.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o] Error 1
make[1]: *** [CMakeFiles/MNNCV.dir/all] Error 2

**Comment by clive-g-brown** [comment]
OK one of my colleagues figured it out, you need to run. ./schema/generate.sh

that's not clear from the build instructions.

**Comment by iiSeymour** [comment]
Full instructions for building on MacOS -

```bash
$ brew install protobuf
$ ./schema/generate.sh
$ mkdir macosbuild
$ cd macosbuild
$ cmake ../ -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_TRAIN=ON -DMNN_BUILD_DEMO=ON -DMNN_BUILD_QUANTOOLS=ON -DMNN_EVALUATION=ON -DMNN_BUILD_CONVERTER=ON -DMNN_SUPPORT_TFLITE_QUAN=ON -DMNN_METAL=ON -DMNN_BUILD_TEST=ON -DMNN_BUILD_BENCHMARK=ON
$ make -j8
```

**Comment by Sejudyblues** [comment]
> OK one of my colleagues figured it out, you need to run. ./schema/generate.sh
> 
> that's not clear from the build instructions.

thanks,bro. i will try it.

**Comment by ZHUTAO142857** [comment]
> Full instructions for building on MacOS -
> 
> ```shell
> $ brew install protobuf
> $ ./schema/generate.sh
> $ mkdir macosbuild
> $ cd macosbuild
> $ cmake ../ -DCMAKE_BUILD_TYPE=Release -DMNN_BUILD_TRAIN=ON -DMNN_BUILD_DEMO=ON -DMNN_BUILD_QUANTOOLS=ON -DMNN_EVALUATION=ON -DMNN_BUILD_CONVERTER=ON -DMNN_SUPPORT_TFLITE_QUAN=ON -DMNN_METAL=ON -DMNN_BUILD_TEST=ON -DMNN_BUILD_BENCHMARK=ON
> $ make -j8
> ```
$ brew install protobuf
$ ./schema/generate.sh
$ mkdir build && cd build
$ cmake -DMNN_BUILD_DEMO=ON ..
$ make
