### ISSUE TITLE
按照语雀的示例编译出错

### ISSUE THREAD

**Issue by Sejudyblues** [alibaba/MNN#841]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
linux

# Github版本:
# Github Version:
git clone https://github.com/alibaba/MNN

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.17") 
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /content/MNN/build
-- x86_64: Open SSE
-- Configuring done
-- Generating done
-- Build files have been written to: /content/MNN/build

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```
Scanning dependencies of target MNNMath
Scanning dependencies of target MNNShape
Scanning dependencies of target GenVCSHDR
Scanning dependencies of target MNNCV
[  1%] Built target MNNAVX
[  1%] Building CXX object CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o
[  1%] Generating Version Control Info
[  1%] Building CXX object CMakeFiles/MNNMath.dir/source/math/WingoradGenerater.cpp.o
[  1%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution1x1Strassen.cpp.o
[  4%] Built target MNNSSE
[  4%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageBlitter.cpp.o
-- Found Git: /usr/bin/git (found version "2.17.1") 
Scanning dependencies of target MNNCore
[  5%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o
[  5%] Built target GenVCSHDR
[  5%] Building CXX object CMakeFiles/MNNShape.dir/source/shape/ShapeArgMax.cpp.o
[  6%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Backend.cpp.o
[  5%] Building CXX object CMakeFiles/MNNCore.dir/source/core/AutoTime.cpp.o
In file included from /content/MNN/source/backend/cpu/compute/Convolution1x1Strassen.hpp:13:0,
                 from /content/MNN/source/backend/cpu/compute/Convolution1x1Strassen.cpp:9:
/content/MNN/source/backend/cpu/CPUConvolution.hpp:13:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNCompute.dir/build.make:88: recipe for target 'CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution1x1Strassen.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution1x1Strassen.cpp.o] Error 1
CMakeFiles/Makefile2:221: recipe for target 'CMakeFiles/MNNCompute.dir/all' failed
make[1]: *** [CMakeFiles/MNNCompute.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /content/MNN/source/math/Matrix.cpp:12:0:
/content/MNN/source/core/TensorUtils.hpp:13:10: fatal error: Tensor_generated.h: No such file or directory
 #include "Tensor_generated.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNMath.dir/build.make:62: recipe for target 'CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o' failed
make[2]: *** [CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  6%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BackendFactory.cpp.o
[  6%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUAsString.cpp.o
In file included from /content/MNN/source/backend/cpu/CPUArgMax.cpp:11:0:
/content/MNN/source/backend/cpu/CPUBackend.hpp:17:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNCPU.dir/build.make:62: recipe for target 'CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  6%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BackendRegister.cpp.o
In file included from /content/MNN/source/shape/ShapeArgMax.cpp:10:0:
/content/MNN/source/core/SizeComputer.hpp:16:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNShape.dir/build.make:62: recipe for target 'CMakeFiles/MNNShape.dir/source/shape/ShapeArgMax.cpp.o' failed
make[2]: *** [CMakeFiles/MNNShape.dir/source/shape/ShapeArgMax.cpp.o] Error 1
CMakeFiles/Makefile2:341: recipe for target 'CMakeFiles/MNNShape.dir/all' failed
make[1]: *** [CMakeFiles/MNNShape.dir/all] Error 2
/content/MNN/source/core/Backend.cpp:11:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNCore.dir/build.make:75: recipe for target 'CMakeFiles/MNNCore.dir/source/core/Backend.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCore.dir/source/core/Backend.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  7%] Building CXX object CMakeFiles/MNNCore.dir/source/core/BufferAllocator.cpp.o
[  8%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o
[  8%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
In file included from /content/MNN/source/backend/cpu/CPUAsString.hpp:12:0,
                 from /content/MNN/source/backend/cpu/CPUAsString.cpp:9:
/content/MNN/source/backend/cpu/CPUBackend.hpp:17:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNCPU.dir/build.make:75: recipe for target 'CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUAsString.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUAsString.cpp.o] Error 1
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/MNNCPU.dir/all' failed
make[1]: *** [CMakeFiles/MNNCPU.dir/all] Error 2
[  8%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageSampler.cpp.o
/content/MNN/source/cv/ImageFloatBlitter.cpp:10:10: fatal error: Tensor_generated.h: No such file or directory
 #include "Tensor_generated.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /content/MNN/source/cv/ImageProcess.cpp:13:0:
/content/MNN/source/core/TensorUtils.hpp:13:10: fatal error: Tensor_generated.h: No such file or directory
 #include "Tensor_generated.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/MNNCV.dir/build.make:75: recipe for target 'CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/MNNCV.dir/build.make:88: recipe for target 'CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o' failed
make[2]: *** [CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o] Error 1
CMakeFiles/Makefile2:378: recipe for target 'CMakeFiles/MNNCV.dir/all' failed
make[1]: *** [CMakeFiles/MNNCV.dir/all] Error 2
CMakeFiles/Makefile2:304: recipe for target 'CMakeFiles/MNNMath.dir/all' failed
make[1]: *** [CMakeFiles/MNNMath.dir/all] Error 2
CMakeFiles/Makefile2:453: recipe for target 'CMakeFiles/MNNCore.dir/all' failed
make[1]: *** [CMakeFiles/MNNCore.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/issues/840#issuecomment-635958939
