### ISSUE TITLE
华为P40 Pro使用OPENCL推理时速度比CPU推理慢很多

### ISSUE THREAD

**Issue by HiDream** [alibaba/MNN#846]
同样时Mali-G76的GPU，华为mate20 pro的推理速度就比华为P40 pro的推理速度快很多，这是什么什么原因，是因为底层库的位置不对，导致这个结果吗？

**Comment by jxt1234** [comment]
应该是GPU限频的原因，设成性能模式了么？

**Comment by jxt1234** [comment]
更新一下试试吧
