### ISSUE TITLE
run benchmark inception-v3.mnn model error 

### ISSUE THREAD

**Issue by ftdlyc** [alibaba/MNN#85]
用的opencl后端, intel i7 8700 gpu, inception-v3的第二层卷积149x149x32卷积时出错
`benchmark.out: /home/lyc/src/MNN/source/backend/opencl/execution/ConvWinograd.cpp:296: virtual MNN::ErrorCode MNN::OpenCL::ConvWinograd::onExecute(const std::vector<MNN::Tensor*>&, const std::vector<MNN::Tensor*>&): Assertion `res' failed.`

我猜是opencl分配image2d时超出max size了, 在MNN/source/backend/opencl/execution/ConvWinograd.cpp的第205行, mSource需要分配32 x 21904大小的image2d, 然而intel gpu的最多支持16384 x 16384, 没分配成功. 所以在ConvWinograd::onExecute时, 执行mSourceTransform kernel, opencl返回错误代码-52

**Comment by li-qing** [comment]
will be fixed soon.
