### ISSUE TITLE
Compiling for x86 windows

### ISSUE THREAD

**Issue by itayalfia** [alibaba/MNN#850]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Compiling from - x86_64 windows
Target - x86 (32 bit) windows

# Question:

I can't seem to find documentation for 32 bit windows compilation, is it possible?

Do you have optimizations specifically for old SSE2 32bit CPUs?

Thanks for the help!

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/compile/engine.html#windows
