### ISSUE TITLE
MNN交叉编译的话，可以支持protobuffer 2.6.5版本吗？

### ISSUE THREAD

**Issue by niezhongliang** [alibaba/MNN#853]
# 平台(如果交叉编译请再附上交叉编译目标平台):  imx6 （A9芯片）
# Platform(Include target platform as well if cross-compiling):  

最近，想将MNN代替开发板上原有的NCNN库。但是原有的开发板必须得依靠protobuffer 2.6.5。 请问有什么方法可以吗？

**Comment by jxt1234** [comment]
可以不编译模型转换部分？

**Comment by czy2014hust** [comment]
可以在pc上编译模型转换部分，然后交叉编译MNN推理引擎部分
