### ISSUE TITLE
Convert quantized model 

### ISSUE THREAD

**Issue by Kepnu4** [alibaba/MNN#855]
Is it possible to convert quantized model from other framework? 
I see converterOps for quantized tflite but i found only instructions to do QAT in MNN. So should converter work for quantized models?  I have rather big pipeline and i don't want to translate it to MNN.

**Comment by jxt1234** [comment]
Currently we won't support convert quantized model, because it's not standard and will change freqencily.
You can use MNN's fp16 or offline quantization method.
