### ISSUE TITLE
安卓手机上，我的模型在GPU推理速度不如4线程的CPU

### ISSUE THREAD

**Issue by TCBocean** [alibaba/MNN#856]
Github版本:1.0.0
编译方式如语雀中所提到的那样，在ubuntu18.04下完成编译。
使用的测试手机是小米note3，SoC为骁龙660。
我的模型是mobilenetv2+yolov3（精简了一些结构），模型从tflite（tensorflow2.1.0）转到mnn。
单线程CPU运行时间为平均164ms一帧，4线程CPU运行时间为平均90ms一帧
OpenCL运行时间为平均107ms一帧，Vulkan在423~253ms一帧。
BackendConfig一直保持如下设置
```
    MNN::BackendConfig backendConfig;
    backendConfig.precision = MNN::BackendConfig::Precision_Low; 
    backendConfig.power = MNN::BackendConfig::Power_Normal; 
    backendConfig.memory = MNN::BackendConfig::Memory_Normal;
```
请问多线程CPU比GPU速度快，可能是什么原因造成的呢？

**Comment by jxt1234** [comment]
你模型是?

**Comment by TCBocean** [comment]
emmm，我不知道怎么发上来，你能留一个邮箱吗？  @jxt1234

**Comment by TCBocean** [comment]
链接：https://pan.baidu.com/s/1887g-yjjQQFbbKOtR46e9A 
提取码：zkl4
@jxt1234 我上传了一个未训练的模型到百度云，它的运行速度和训练过的模型是相同的，所以我想应该可以用来分析问题。

**Comment by jxt1234** [comment]
对了，补充一点，660 上 gpu 不如 cpu 4线程是正常的，而且 cpu 开 ARM82 后会更快。但 Vulkan 性能这么慢我们会查一下

**Comment by TCBocean** [comment]
@jxt1234 好的，那麻烦你们了~
另外我想问一下ARM82的库要怎么编译呀？
我把CMakeList.txt中的MNN_ARM82改为默认ON后，按https://www.yuque.com/mnn/cn/build_android所说运行../build_32.sh，编译出现了报错。
报错内容如下：
```
[ 87%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUWhere.cpp.o
[ 88%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUZeroLike.cpp.o
[ 88%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/ThreadPool.cpp.o
[ 88%] Built target MNNCPU
Scanning dependencies of target MNN
[ 88%] Building CXX object CMakeFiles/MNN.dir/cmake/dummy.cpp.o
[ 88%] Linking CXX shared library libMNN.so
/home/tcb/MNN-1.0.0/source/backend/cpu/CPUConvInt8.cpp:601: error: undefined reference to 'MNNGemmInt8AddBiasScale_ARMV82_Unit'
/home/tcb/MNN-1.0.0/source/backend/cpu/CPUConvInt8.cpp:605: error: undefined reference to 'MNNGemmInt8AddBiasScale_ARMV82_Unit'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/MNN.dir/build.make:670: recipe for target 'libMNN.so' failed
make[2]: *** [libMNN.so] Error 1
CMakeFiles/Makefile2:521: recipe for target 'CMakeFiles/MNN.dir/all' failed
make[1]: *** [CMakeFiles/MNN.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by jxt1234** [comment]
ARM82 只支持 armv8a 编译

**Comment by TCBocean** [comment]
@jxt1234
我发现这个模型运行速度和模型本身又挺大关系的。
我又换了一个人像分割的模型，OPENCL运行时间最慢才8ms，而CPU运行时间最快都要24ms。
我后来又试了一下tflite的GPU，要100多ms，MNN是真的牛！

**Comment by jiuzhuanzhuan** [comment]
> Github版本:1.0.0
> 编译方式如语雀中所提到的那样，在ubuntu18.04下完成编译。
> 使用的测试手机是小米note3，SoC为骁龙660。
> 我的模型是mobilenetv2+yolov3（精简了一些结构），模型从tflite（tensorflow2.1.0）转到mnn。
> 单线程CPU运行时间为平均164ms一帧，4线程CPU运行时间为平均90ms一帧
> OpenCL运行时间为平均107ms一帧，Vulkan在423~253ms一帧。
> BackendConfig一直保持如下设置
> 
> ```
>     MNN::BackendConfig backendConfig;
>     backendConfig.precision = MNN::BackendConfig::Precision_Low; 
>     backendConfig.power = MNN::BackendConfig::Power_Normal; 
>     backendConfig.memory = MNN::BackendConfig::Memory_Normal;
> ```
> 
> 请问多线程CPU比GPU速度快，可能是什么原因造成的呢？

弱弱的问 在android上部署的时候 官方的demo并没有MNN::BackendConfig backendConfig; 这个参数了 您是怎么配置这里的呀 是要自己改一下java么？

**Comment by TCBocean** [comment]
@jiuzhuanzhuan 
我的代码都是用C++写的，具体是参照https://www.yuque.com/mnn/cn/create_session里面所说的那样

**Comment by Kevin35L** [comment]
@TCBocean  你好，方便问下你人像分割换成了什么模型速度这么快吗？

**Comment by TCBocean** [comment]
@Kevin35L 嘿嘿，是从BiSeNetV2魔改的模型

**Comment by wuhuangcangg** [comment]
之前有遇到类似的问题
对于安卓手机，有些模型的速度瓶颈不在opencl 的运行速度上，而在opencl的 消息队列塞入。
即有些时候opencl数据已经处理完成，但是在等待下一个消息塞入，导致性能较低。

**Comment by jiuzhuanzhuan** [comment]
> 之前有遇到类似的问题 对于安卓手机，有些模型的速度瓶颈不在opencl 的运行速度上，而在opencl的 消息队列塞入。 即有些时候opencl数据已经处理完成，但是在等待下一个消息塞入，导致性能较低。

可以理解为 opencl接受输入数据很慢么?  那请问有什么解决方法么

**Comment by wuhuangcangg** [comment]
换模型，换设备。。。

> > 之前有遇到类似的问题 对于安卓手机，有些模型的速度瓶颈不在opencl 的运行速度上，而在opencl的 消息队列塞入。 即有些时候opencl数据已经处理完成，但是在等待下一个消息塞入，导致性能较低。
> 
> 可以理解为 opencl接受输入数据很慢么? 那请问有什么解决方法么
