### ISSUE TITLE
Python版MNN 1.0.1进行MNN.Tensor时出错

### ISSUE THREAD

**Issue by panda162** [alibaba/MNN#857]
# Ubuntu 18.04
# Tensorflow 2.2.0
# python 3.6.9
# MNN 1.0.1(直接pip安装)

在利用MNN.Tensor进行数据转换时提示如下错误：
terminate called after throwing an instance of 'std::runtime_error'
  what():  numpy type does not match
转换代码如下：
    image = cv2.imread('test.jpg')
    #change to rgb format
    image = image[..., ::-1]
    image = image.astype(float)
    image = image * (1/255, 1/255, 1/255)
    #cv2 read shape is NHWC, Tensor's need is NCHW,transpose it
    #image = image.transpose((2, 0, 1))
    #construct tensor from np.ndarray
    #image = np.expand_dims(image, axis=0)
    tmp_input = MNN.Tensor((1, 64, 64, 3), MNN.Halide_Type_Float,\
                    image, MNN.Tensor_DimensionType_Tensorflow)

其中image的dtype是float64
无论image数据形状是（64,64,3）还是（1,64,64,3）均出现上述错误。

但是pip安装MNN 1.0.0 就可以正常推理，之前钉钉群有工程师回复1.0.1检查更加严格，考虑性能，外部的numpy数据类型和里面的数据类型要对应起来。

**Comment by yoobright** [comment]
我也遇到了同样的问题

**Comment by panda162** [comment]
> 我也遇到了同样的问题

https://github.com/alibaba/MNN/issues/861你按照这个里面的方法再试一下,看看是否可以

**Comment by 07freedom** [comment]
我这边也是，希望能尽快修复

**Comment by strivehub** [comment]
请问这个问题无法解决吗？？各位解决了吗，我也是在这里提示错误
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: numpy type does not match
Abort trap: 6

**Comment by ycdhqzhiai** [comment]
感谢钉钉群工程师回复，输入"dtype是np.float32，输入shape是1，3，64，64”
实测在1.0.3上通过
```python
image=data_processing(image)[np.newaxis, ...].transpose(0,3,1,2).astype(np.float32)
```

> # Ubuntu 18.04
> # Tensorflow 2.2.0
> # python 3.6.9
> # MNN 1.0.1(直接pip安装)
> 在利用MNN.Tensor进行数据转换时提示如下错误：
> terminate called after throwing an instance of 'std::runtime_error'
> what(): numpy type does not match
> 转换代码如下：
> image = cv2.imread('test.jpg')
> #change to rgb format
> image = image[..., ::-1]
> image = image.astype(float)
> image = image * (1/255, 1/255, 1/255)
> #cv2 read shape is NHWC, Tensor's need is NCHW,transpose it
> #image = image.transpose((2, 0, 1))
> #construct tensor from np.ndarray
> #image = np.expand_dims(image, axis=0)
> tmp_input = MNN.Tensor((1, 64, 64, 3), MNN.Halide_Type_Float,
> image, MNN.Tensor_DimensionType_Tensorflow)
> 
> 其中image的dtype是float64
> 无论image数据形状是（64,64,3）还是（1,64,64,3）均出现上述错误。
> 
> 但是pip安装MNN 1.0.0 就可以正常推理，之前钉钉群有工程师回复1.0.1检查更加严格，考虑性能，外部的numpy数据类型和里面的数据类型要对应起来。

**Comment by ycdhqzhiai** [comment]
感谢钉钉群里工程师回复，输入需要是np.float32，注意送入MNN.Tensor 的image shape是N H W C
```python
    image=data_processing(image)[np.newaxis, ...].astype(np.float32)
    print(image.shape)
    #cv2 read shape is NHWC, Tensor's need is NCHW,transpose it
    tmp_input = MNN.Tensor((1,INPUTSIZE, INPUTSIZE,3), MNN.Halide_Type_Float,image, MNN.Tensor_DimensionType_Tensorflow)
```


> # Ubuntu 18.04
> # Tensorflow 2.2.0
> # python 3.6.9
> # MNN 1.0.1(直接pip安装)
> 在利用MNN.Tensor进行数据转换时提示如下错误：
> terminate called after throwing an instance of 'std::runtime_error'
> what(): numpy type does not match
> 转换代码如下：
> image = cv2.imread('test.jpg')
> #change to rgb format
> image = image[..., ::-1]
> image = image.astype(float)
> image = image * (1/255, 1/255, 1/255)
> #cv2 read shape is NHWC, Tensor's need is NCHW,transpose it
> #image = image.transpose((2, 0, 1))
> #construct tensor from np.ndarray
> #image = np.expand_dims(image, axis=0)
> tmp_input = MNN.Tensor((1, 64, 64, 3), MNN.Halide_Type_Float,
> image, MNN.Tensor_DimensionType_Tensorflow)
> 
> 其中image的dtype是float64
> 无论image数据形状是（64,64,3）还是（1,64,64,3）均出现上述错误。
> 
> 但是pip安装MNN 1.0.0 就可以正常推理，之前钉钉群有工程师回复1.0.1检查更加严格，考虑性能，外部的numpy数据类型和里面的数据类型要对应起来。

**Comment by baoxin1100** [comment]
改成
`image = image.astype(np.float32)
tmp_input = MNN.Tensor((1,INPUTSIZE, INPUTSIZE,3), MNN.Halide_Type_Float,image, MNN.Tensor_DimensionType_Tensorflow)`
切记不管前面多少次float类型转换都没用，一定要把这两句连着写
