### ISSUE TITLE
object detection

### ISSUE THREAD

**Issue by haiyang1981** [alibaba/MNN#86]
How to read out the result from the caffe DetectionOutput layer?

**Comment by jxt1234** [comment]
Two ways to read:
1. Create a host tensor and copy output tensor, use the data of host tensor.
2. Read the output tensor of DetectionOutput directly by read element step by 4:
data[0*4], data[1*4], data[2*4], data[3*4] ......

**Comment by haiyang1981** [comment]
thanks for your solution and an other question, 
auto output = mnnNet->getSessionOutput(session, nullptr);
or
auto output = mnnNet->getSessionOutput(session, "DetectionOutput");
which way is the right way for getting output result? when i use the second way, there is an error and the point of output has nothing.
moreover, if you will show me a demo code for Object detection, i would very appreciate!

**Comment by haiyang1981** [comment]
in addition, i use caffe model to convert mnn model

**Comment by haiyang1981** [comment]
when i use auto output = mnnNet->getSessionOutput(session, "DetectionOutput");
the console prints output as "can't find DetectionOutput"
why?

**Comment by jxt1234** [comment]
auto output = mnnNet->getSessionOutput(session, nullptr);  //OK


auto output = mnnNet->getSessionOutput(session, "DetectionOutput"); // The name should be the right name of output(Tensor's name, not the layer's name)

**Comment by haiyang1981** [comment]
how can i find the tensor's name corresponding to the layer's name

**Comment by jxt1234** [comment]
layer {
  name: "detection_out"
  type: "DetectionOutput"
  bottom: "mbox_loc"
  bottom: "mbox_conf_flatten"
  bottom: "mbox_priorbox"
  top: "detection_out0"
...
}

the top name: detection_out0

**Comment by haiyang1981** [comment]
thank you very much! I find the right way to get the result. this issue can be closed.
