### ISSUE TITLE
如何获取中间层输出

### ISSUE THREAD

**Issue by lakehui** [alibaba/MNN#864]
我在ScheduleConfig 中配置了outputs的名字，但是在net->getSessionOutput时依旧提示 “can't find output: xx”

**Comment by lakehui** [comment]
我在ScheduleConfig 中配置了outputs的名字，但是在net->getSessionOutput时依旧提示 “can't find output: xx”

**Comment by jxt1234** [comment]
在 saveTensors 里面加，另外需要注意，Op 的名字和 Tensor 的名字不一定一样

**Comment by lakehui** [comment]
> 在 saveTensors 里面加，另外需要注意，Op 的名字和 Tensor 的名字不一定一样

搞定了，感谢
