### ISSUE TITLE
DOWNLOAD Mobilenet_v1.caffe.caffemodel failed

### ISSUE THREAD

**Issue by wuyuhan1218** [alibaba/MNN#865]
![d85daf38ee0181ef38ff50ea0261cf6](https://user-images.githubusercontent.com/55457458/83857598-d076fa00-a74d-11ea-86d0-afeb392d79b0.jpg)

**Comment by jxt1234** [comment]
caffe 版本的mobilenet 链接挂掉了.... 用 tflite / tensorflow 的吧
