### ISSUE TITLE
Build Error in the link phase due to the protobuf version

### ISSUE THREAD

**Issue by Leslie-Fang** [alibaba/MNN#866]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
X86_64

# Github版本:
# Github Version:
master branch
f5dae040a0b60678726a5893b7b2778e15ce690c 

# 编译方式:
# Compiling Method
GCC 8.3
cmake 3.17.3
自己编译了一版protobuf3.6.1 参考这个issue: https://github.com/alibaba/MNN/issues/643

```
export PATH=$protobuf_install/bin:$PATH
export CPLUS_INCLUDE_PATH=$protobuf_install/include:$CPLUS_INCLUDE_PATH
 cmake .. -DCMAKE_PREFIX_PATH=$protobuf_install -DMNN_BUILD_CONVERTER=True -DMNN_BUILD_DEMO=ON
mamke -j 4
```

# 编译日志:
# Build Log:

```
/home/protobuf_3_6_1/install/lib/libprotobuf.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
```

**Comment by czy2014hust** [comment]
protobuf多个版本的问题
