### ISSUE TITLE
如何归一化到[-1.0, 1.0]

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#871]
pytorch ：

transform2 = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean = (0.5, 0.5, 0.5), std = (0.5, 0.5, 0.5))
    ]
)

MNN我该如何改? :

const float means[3] = {103.94f, 116.78f, 123.68f};
const float normals[3] = {0.017f, 0.017f, 0.017f};
MNN::CV::ImageProcess::Config process;
::memcpy(process.mean, means, sizeof(means));
::memcpy(process.normal, normals, sizeof(normals));
process.sourceFormat = MNN::CV::RGBA;
process.destFormat = MNN::CV::BGR;
std::shared_ptr<MNN::CV::ImageProcess> pretreat(MNN::CV::ImageProcess::create(process));

**Comment by yyfcc17** [comment]
const float means[3] = {0.5f, 0.5f, 0.5f};
const float normals[3] = {2.0f, 2.0f, 2.0f};

process.destFormat根据你的实际情况配置

**Comment by alicera** [comment]
根据配置
const float means[3] = {0.5f, 0.5f, 0.5f};
const float normals[3] = {2.0f, 2.0f, 2.0f};
就会实现
channel=（channel-mean）/std 吗??

**Comment by yyfcc17** [comment]
我们的是（x - mean) * normal

**Comment by alicera** [comment]
MNN::CV::ImageProcess 的 CODE该去哪找

**Comment by alicera** [comment]
the MNN::CV::ImageProcess  can do the （x / 255 - mean) * normal
how to design the "/ 255"

**Comment by bobo0810** [comment]
@alicera     It Is equivalent to  ` [(x / 255) - 0.5] / 0.5`

    const float _mean[3] = {127.5f,127.5f,127.5f};
    const float _normal[3] = {1/127.5f,1/127.5f,1/127.5f};
