### ISSUE TITLE
Failed to load the model with static built library 

### ISSUE THREAD

**Issue by aabghari** [alibaba/MNN#872]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux x86_64

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id
f5dae040a0b60678726a5893b7b2778e15ce690c

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method
gcc
```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```
$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
CMake Warning at CMakeLists.txt:74 (message):
  Close MNN_SEP_BUILD for static library

-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/arash/workspace/MNN/build-static
-- x86_64: Open SSE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/arash/workspace/MNN/build-static

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

When building static library, it fails to load the model properly, while with the dynamic library every thing works properly. Here is the output with static lib:

Don't support type [Convolution], 121
Don't support type [Convolution], 121
Resize error for [Convolution], 121, code=2

The network is a Yolo v4.

**Comment by jxt1234** [comment]
see https://www.yuque.com/mnn/en/faq for static library

**Comment by aabghari** [comment]
Thanks, it's working now.
