### ISSUE TITLE
onnx与mnn的精度不一样，预测结果也不一样

### ISSUE THREAD

**Issue by mjanddy** [alibaba/MNN#876]
onnx转换为mnn后，mnn的结果与onnx的不一样，效果很差，是有什么需要注意的地方吗？
 input -= (104, 117, 123)
 input /= 128
 input = input.transpose(2, 0, 1)
 input = np.expand_dims(input, axis=0)
 input = input.astype(np.float32)
tmp_input=MNN.Tensor((1,3,480,448),MNN.Halide_Type_Float,input,MNN.Tensor_DimensionType_Caffe)
 input_tensor.copyFrom(tmp_input)
 interpreter.runSession(session)
 out = interpreter.getSessionOutput(session)

 output_data = out.getData()

**Comment by jxt1234** [comment]
需要转格式(NC4HW4->NCHW)

**Comment by mjanddy** [comment]
> 需要转格式(NC4HW4->NCHW)

这个用python该怎么转呢？

**Comment by mjanddy** [comment]
> 需要转格式(NC4HW4->NCHW)

我用的是mnn 1.0.1版本

**Comment by alicera** [comment]
你是說 這個function 本身要輸入資料 NCHW 格式  還是相反 NC4HW4

tmp_input=MNN.Tensor((1,3,480,448),MNN.Halide_Type_Float,input,MNN.Tensor_DimensionType_Caffe)

**Comment by mjanddy** [comment]
> 你是說 這個function 本身要輸入資料 NCHW 格式 還是相反 NC4HW4
> 
> tmp_input=MNN.Tensor((1,3,480,448),MNN.Halide_Type_Float,input,MNN.Tensor_DimensionType_Caffe)

输入的是NCHW

**Comment by alicera** [comment]
那何时才是 NC4HW4

**Comment by siweimaodou** [comment]
我也遇到这种问题了，需要怎么解决啊

**Comment by siweimaodou** [comment]
我这边也出现这个问题，图像输入时NCHW格式，输出也是NCHW格式；没有发现MNN默认输出NC4HW4的情况啊
