### ISSUE TITLE
demo中caffe模型替换成tf模型

### ISSUE THREAD

**Issue by wuyuhan1218** [alibaba/MNN#879]
刚刚才看到faq有写需要转换format，不太清楚那两行code需要放在哪里，是mnnnetnative.cpp里面的getsessioninput那里吗? 但是又有halide_type_t 和 tensor::dimensiontype not compatible的问题。

**Comment by wuyuhan1218** [comment]
我只替换了mobilenet的模型。用pb和tflite都试了以下，但是输入格式不符会出问题

**Comment by wuyuhan1218** [comment]
试了下用
auto inputTensor = interpreter->getSessionInput(session, NULL);
auto nhwcTensor = new Tensor(inputTensor, Tensor::TENSORFLOW);
// nhwcTensor-host<float>()[x] = ...
inputTensor->copyFromHostTensor(nhwcTensor);
delete nhwcTensor;
没有语法问题了 但是Run的时候还是会报错
FATAL EXCEPTION: MNNNet
VideoActivity.java: 164
VideoActivity.java: 42
VideoActivity.java: 225

**Comment by jxt1234** [comment]
MNN::Tensor::create({1,224,224,3},  nullptr, MNN::Tensor::TENSORFLOW);

**Comment by wuyuhan1218** [comment]
> MNN::Tensor::create({1,224,224,3}, nullptr, MNN::Tensor::TENSORFLOW);

谢谢
是auto nhwcTensor=MNN::Tensor::create({1,224,224,3}, nullptr, MNN::Tensor::TENSORFLOW); 吗，还是显示Parameter type mismatch: Taking pointer from integer without a cast

**Comment by wuyuhan1218** [comment]
> MNN::Tensor::create({1,224,224,3}, nullptr, MNN::Tensor::TENSORFLOW);

我试了下auto nhwcTensor=MNN::Tensor::create({1,224,224,3}, halide_type_of<float>(),nullptr, MNN::Tensor::TENSORFLOW); 可以运行了，但是run的时候又会报错
FATAL EXCEPTION: MNNNet
VideoActivity.java: 164
VideoActivity.java: 42
VideoActivity.java: 225
跟没有改过的一样的问题

**Comment by jxt1234** [comment]
是模型没加载成功？

**Comment by wuyuhan1218** [comment]
> 是模型没加载成功？

没有显示没加载成功，我用转换成mnn之后的pb模型替换了原有的caffe转的mnn模型，目前只做了以上几行nhwc的修改，不清楚其他地方要不要改

**Comment by wuyuhan1218** [comment]
只改了mobilenet的模型
