### ISSUE TITLE
demo无法运行

### ISSUE THREAD

**Issue by IQ17** [alibaba/MNN#88]
按照https://github.com/alibaba/MNN/tree/master/demo/exec
运行./multiPose.out model.mnn input.jpg pose.jpg

模型是官方提供的，但是运行得到

The MobilenetV1/Conv2D's input is not ready
Resize error for MobilenetV1/Conv2D, code=3
main, 369, cost time: 82.332001 ms
main, 392, cost time: 0.272000 ms

**Comment by jxt1234** [comment]
这个报错日志不影响的
