### ISSUE TITLE
clang++: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by mathpopo** [alibaba/MNN#884]
使用(base) chenxin@Nitro-AN515:~/Downloads/MNN/project/android$ mkdir build_64 && cd build_64 && ../build_64.sh
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Android
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/chenxin/Downloads/MNN/project/android/build_64
-- Enabling AArch64 Assemblies
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chenxin/Downloads/MNN/project/android/build_64
．．．．．
[100%] Built target testModelWithDescrisbe.out
[100%] Linking CXX executable MNNV2Basic.out
[100%] Built target MNNV2Basic.out

使用生成的libMNN.so：

/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/chenxin/Downloads/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN-test-copy-no-opencv-amv8/mnn/lib/libMNN.so, not found (try using -rpath or -rpath-link)
/home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libandroid.so, needed by /home/chenxin/Downloads/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN-test-copy-no-opencv-amv8/mnn/lib/libMNN.so, not found (try using -rpath or -rpath-link)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/Ultra-face-mnn.dir/build.make:113: recipe for target 'Ultra-face-mnn' failed
make[2]: *** [Ultra-face-mnn] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/Ultra-face-mnn.dir/all' failed
make[1]: *** [CMakeFiles/Ultra-face-mnn.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mathpopo** [comment]
bench_android.sh 修改ABI="arm64-v8a"
执行ｓｈ
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/MNN.dir/build.make:659: recipe for target 'libMNN.so' failed
make[3]: *** [libMNN.so] Error 1
CMakeFiles/Makefile2:524: recipe for target 'CMakeFiles/MNN.dir/all' failed
make[2]: *** [CMakeFiles/MNN.dir/all] Error 2
CMakeFiles/Makefile2:161: recipe for target 'CMakeFiles/benchmark.out.dir/rule' failed
make[1]: *** [CMakeFiles/benchmark.out.dir/rule] Error 2
Makefile:177: recipe for target 'benchmark.out' failed
make: *** [benchmark.out] Error 2

**Comment by mathpopo** [comment]
o: In function `operator()':
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:119: undefined reference to `MNNMatrixCopyUnit'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:120: undefined reference to `MNNGemmFloatUnit_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:132: undefined reference to `MNNGemmFloatOne_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:134: undefined reference to `MNNGemmFloatCommon_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:153: undefined reference to `MNNGemmFloatUnit_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:159: undefined reference to `MNNGemmFloatOne_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:165: undefined reference to `MNNGemmFloatCommon_4'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:279: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:280: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:291: undefined reference to `MNNMatrixAdd'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:292: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:303: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:304: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:315: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:332: undefined reference to `MNNStrassenMergeCFunction'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:334: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:346: undefined reference to `MNNMatrixSub'
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/StrassenMatmulComputor.cpp:355: undefined reference to `MNNMatrixAdd'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o: In function `MNN::WinogradFunction::productLeft(float const*, float const*, float*, unsigned long, unsigned long, unsigned long, unsigned long)':
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/WinogradOptFunction.cpp:79: undefined reference to `MNNWinogradMatrixProductLeft'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o: In function `MNN::WinogradFunction::productRight(float const*, float const*, float*, unsigned long, unsigned long, unsigned long, unsigned long)':
/home/chenxin/Downloads/MNN/source/backend/cpu/compute/WinogradOptFunction.cpp:84: undefined reference to `MNNWinogradMatrixProductRight'

**Comment by czy2014hust** [comment]
> 使用(base) chenxin@Nitro-AN515:~/Downloads/MNN/project/android$ mkdir build_64 && cd build_64 && ../build_64.sh
> -- >>>>>>>>>>>>>
> -- MNN BUILD INFO:
> -- System: Android
> -- Processor: aarch64
> -- Metal: OFF
> -- OpenCL: OFF
> -- OpenGL: OFF
> -- Vulkan: OFF
> -- ARM82: OFF
> -- OpenMP: OFF
> -- Hidden: TRUE
> -- Build Path: /home/chenxin/Downloads/MNN/project/android/build_64
> -- Enabling AArch64 Assemblies
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/chenxin/Downloads/MNN/project/android/build_64
> ．．．．．
> [100%] Built target testModelWithDescrisbe.out
> [100%] Linking CXX executable MNNV2Basic.out
> [100%] Built target MNNV2Basic.out
> 
> 使用生成的libMNN.so：
> 
> /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/chenxin/Downloads/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN-test-copy-no-opencv-amv8/mnn/lib/libMNN.so, not found (try using -rpath or -rpath-link)
> /home/chenxin/armnn-devenv/toolchains/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libandroid.so, needed by /home/chenxin/Downloads/Ultra-Light-Fast-Generic-Face-Detector-1MB/MNN-test-copy-no-opencv-amv8/mnn/lib/libMNN.so, not found (try using -rpath or -rpath-link)
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> CMakeFiles/Ultra-face-mnn.dir/build.make:113: recipe for target 'Ultra-face-mnn' failed
> make[2]: *** [Ultra-face-mnn] Error 1
> CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/Ultra-face-mnn.dir/all' failed
> make[1]: *** [CMakeFiles/Ultra-face-mnn.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

看着MNN编译没有问题，是你自己工程环境的问题！

**Comment by mathpopo** [comment]
@czy2014hust   三楼：bench_android.sh 修改ABI="arm64-v8a"，能这么改吗（试试）？我只是想试试６４位的

**Comment by czy2014hust** [comment]
./bench_android.sh -64

**Comment by YueWenjun** [comment]
我遇到了一样的错误
/usr/share/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libandroid.so, needed by ../src/main/jniLibs/arm64-v8a/libMNN.so, not found (try using -rpath or -rpath-link)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by zhuoran-guo** [comment]
你好，同样的情况，这个问题解决了吗
