### ISSUE TITLE
Memory Leak if more than 2 threads are used.

### ISSUE THREAD

**Issue by kafan1986** [alibaba/MNN#888]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Android v8a (library compiled on linux)

# Github版本:
# Github Version:
Current Development version (master branch) 

https://github.com/alibaba/MNN/commit/f5dae040a0b60678726a5893b7b2778e15ce690c

If I run inference with 2 or more threads there is memory leak. The inference works fine with single thread.

```
MNN::ScheduleConfig schedule_config;
schedule_config.type = MNN_FORWARD_CPU;
schedule_config.numThread = 1;
```

**Comment by kafan1986** [comment]
@jxt1234 On some model the inference is leaking memory on even single thread, CPU inference.

**Comment by jxt1234** [comment]
What's the phenomenon?

**Comment by MirrorYuChen** [comment]
https://github.com/MirrorYuChen/mnn_example/issues/19

**Comment by kafan1986** [comment]
@jxt1234 There are 2 issues. In the https://github.com/MirrorYuChen/mnn_example you can find two different model - **ultra face detecter** and **zqlandmarker**

For Ultra face detecter, the memory leakage is there, if I use more than 1 thread.

For zqlander, there is memory leakage even with 1 thread. I have used latest android release as well as current development libraries on ARM v8.

**Comment by kafan1986** [comment]
@jxt1234 I have created a minimal android app to test the memory leakage. APK and project code is shared for you to test it. Currently 2 thread for each face and landmark detection model inference is used. Latest MNN android library from master branch(14th June 2020) is used.

You can see the memory usage keeps on increasing more and more before eventually crashing. You can change the number of threads for each model in **CreateEngine** for each model by changing values in **MNNMemoryLeakTestApp** class in com.mnnexamples.mnnmemoryleaktest package.

To disable landmark detection altogether, comment the below line of code in **PCountlib.cpp**
`vision_engine->ExtractKeypoints(CamRGBImage, faces[i].location_, &keypoints); // COMMENT THIS LINE TO DISABLE THE FAE LANDMARK MODEL`

The problem as described earlier, **face detection model leaks memory for inference with 2 or more thread count**. The **landmark detection model leaks memory even with 1 thread inference**.

Instructions to build project and some miscellaneous details are provided below.

APK Link:
[app-debug.apk.zip](https://github.com/alibaba/MNN/files/4776277/app-debug.apk.zip)

Android project:
[MNNMemoryLeakTest.zip](https://github.com/alibaba/MNN/files/4776280/MNNMemoryLeakTest.zip)

Instructions for running android project:
// Setting OpenCV
1) Download latest Opencv SDK from official site and save it to your local directory
2) Go to **settings.gradle** and change the opencv location
3) Go to **CMakeLists.txt** and change values for **set_target_properties** and **include_directories**

// Setting MNN
4) Go to **CMakeLists.txt** and **set_target_properties** to the local MNN pre-compiled libraries location

**Comment by kafan1986** [comment]
Solved it on my own.

**Comment by AnhPC03** [comment]
Hi @kafan1986 , could you share the way how did you solve this problem? Thanks.

**Comment by kafan1986** [comment]
@AnhPC03 MNN did not have that leak. It was in some other place, that was involved in the image pre-processing.
