### ISSUE TITLE
error when test the time of  "mobilenet_v2_tfpb_train_public.mnn"

### ISSUE THREAD

**Issue by dandanli814** [alibaba/MNN#889]
Hi, thank you for your job.
I want to compare the time of the model before and after quantification.
So I test this file "mobilenet_v2_tfpb_train_public.mnn" you provided from quantization-aware training from https://www.yuque.com/mnn/en/ricgpz, I run the following command:

./timeProfile.out  mobilenet_v2_tfpb_train_public.mnn 10 0 1x3x224x224

But I got the following error:

Use extra forward type: 0
1 3 224 224
Open Model mobilenet_v2_tfpb_train_public.mnn
Resize error for [Convolution], MobilenetV2/Conv/BatchNorm/FusedBatchNorm, code=3
Don't support type [BatchNorm], MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm
Don't support type [BatchNorm], MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm
Resize error for [BatchNorm], MobilenetV2/expanded_conv/depthwise/BatchNorm/FusedBatchNorm, code=2
Output not available

Looking forward to your answer.

**Comment by jxt1234** [comment]
If you convert model by the parameter --training=true, the model can't be directly run by MNN.
It should be run by MNNTrain's Module.

**Comment by dandanli814** [comment]
OK, thank you.
