### ISSUE TITLE
Onnx Convert Error：Segmentation fault: 11

### ISSUE THREAD

**Issue by AliceSchaw** [alibaba/MNN#890]
MNNConvert -f ONNX --modelFile yolov5.onnx --MNNModel yolov.mnn --bizCode biz

MNNConverter Version: 0.2.1.5git - MNN @ 2018
Start to Convert Other Model Format To MNN Model...
ONNX Model ir version: 6
Start to Optimize the MNN Net...
Segmentation fault: 11

here is onnx file.
[yolov5.onnx.zip](https://github.com/alibaba/MNN/files/4768665/yolov5.onnx.zip)

**Comment by czy2014hust** [comment]
Fixed! Please wait for PR.

**Comment by jnulzl** [comment]
> Fixed! Please wait for PR.

I encountered the same error. Have solved it??

**Comment by edwardnguyen1705** [comment]
> Fixed! Please wait for PR.

Have you solved this issue?
