### ISSUE TITLE
在MTK G90上跑opencl后端，runSession()很快，但是copyToHostTensor读取输出十分慢

### ISSUE THREAD

**Issue by lakehui** [alibaba/MNN#892]
你好，我在mtk的芯片上测试opencl后端，runSession()只需要20ms, 但是copyToHostTensor却需要120ms，请问这现象是正常的吗？
作为对比，我的模型在cpu端运行是60ms, copyToHostTensor基本不耗时。
以上测试都是循环100次的统计结果，排除Warming up的影响

**Comment by jxt1234** [comment]
正常的。。。runSession 20 ms 已经很多了（估计是模型中有 opencl 不支持的 Op） 
copyToHostTensor 时会等待 opencl 执行完成

**Comment by lakehui** [comment]
> 正常的。。。runSession 20 ms 已经很多了（估计是模型中有 opencl 不支持的 Op）
> copyToHostTensor 时会等待 opencl 执行完成
嗯嗯。另外GPU端运行比CPU慢很多。这个和mnn benchmark里面的mobilenet测试表现来有点不太一致（我自己的模型是一个类似mobilenet结构的检测模型）

**Comment by lakehui** [comment]
> 正常的。。。runSession 20 ms 已经很多了（估计是模型中有 opencl 不支持的 Op）
> copyToHostTensor 时会等待 opencl 执行完成

嗯嗯。另外GPU端运行比CPU慢很多。这个和mnn benchmark里面的mobilenet测试表现来有点不太一致（我自己的模型是一个类似mobilenet结构的检测模型）

**Comment by jxt1234** [comment]
设置 precision = Precision_low 了么，另外是否是有很多不支持的算子？

**Comment by lakehui** [comment]
> 设置 precision = Precision_low 了么，另外是否是有很多不支持的算子？

换成precision_low确实会快一些。opencl不支持的算子倒是没有。感觉可能和我的模型本身也有一定关系，计算有点碎片化了，不利于gpu并行

**Comment by weixiaolian21** [comment]
> 正常的。。。runSession 20 ms 已经很多了（估计是模型中有 opencl 不支持的 Op）
> copyToHostTensor 时会等待 opencl 执行完成

我也遇到了这个情况, runSession 10ms ,   copyToHostTensor() 花了1200ms ,请问以下 runSession是不是就完成了 网络的前向运算,   你提及到的 "copyToHostTensor 时会等待 opencl 执行完成 " 是什么意思?  这个复制时间有什么优化方法吗

**Comment by menchunlei** [comment]
> 正常的。。。runSession 20 ms 已经很多了（估计是模型中有 opencl 不支持的 Op）
> copyToHostTensor 时会等待 opencl 执行完成

@jxt1234 runSession() 不会等执行完再返回吗？opencl有两种模式，一种是block；一种是非 block。
