### ISSUE TITLE
iOS 使用 Metal 报错

### ISSUE THREAD

**Issue by digital-nomad-cheng** [alibaba/MNN#896]
在调用runSession的时候报以下错误:

-[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'

库是从release下的，mnn.metallib 是自己编译的，CPU模式下可以正常跑
代码如下:
```
    auto shape = this->_Lnet_input_tensor->shape();
    
    MNN::CV::Matrix trans;
    trans.postScale(1.0f/this->input_width, 1.0f/this->input_height);
    trans.postScale(face.cols, face.rows);
    this->pretreat_data->setMatrix(trans);
    this->pretreat_data->convert((uint8_t*)face.data, face.cols, face.rows, 0, this->_Lnet_input_tensor);

    this->_Lnet->runSession(this->_Lnet_sess);
    
    float *out;
    if (this->forward_type == MNN_FORWARD_METAL) {
        auto host_ouput_tensor = new MNN::Tensor(this->_Lnet_output_tensor, MNN::Tensor::DimensionType::CAFFE);
        this->_Lnet_output_tensor->copyToHostTensor(host_ouput_tensor);
        out = host_ouput_tensor->host<float>();
    } else {
        out = this->_Lnet_output_tensor->host<float>();
    }
```

**Comment by jxt1234** [comment]
具体是什么模型，哪个 op 报的错呢?

**Comment by ItchyHiker** [comment]
> 具体是什么模型，哪个 op 报的错呢?

是自己设计的一个人脸关键点模型，createSession的时候没有报错(没有返回nullptr)，但是runSession的时候返回上面的报错信息，具体哪个 op 没有看到，请问如何看是哪个 op 的错误呢？
这个问题仅仅在开启metal后端出现，CPU可以正常运行结果也正常。

**Comment by Stephen-Adams** [comment]
> 在调用runSession的时候报以下错误:
> 
> -[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
> 
> 库是从release下的，mnn.metallib 是自己编译的，CPU模式下可以正常跑
> 代码如下:
> 
> ```
>     auto shape = this->_Lnet_input_tensor->shape();
>     
>     MNN::CV::Matrix trans;
>     trans.postScale(1.0f/this->input_width, 1.0f/this->input_height);
>     trans.postScale(face.cols, face.rows);
>     this->pretreat_data->setMatrix(trans);
>     this->pretreat_data->convert((uint8_t*)face.data, face.cols, face.rows, 0, this->_Lnet_input_tensor);
> 
>     this->_Lnet->runSession(this->_Lnet_sess);
>     
>     float *out;
>     if (this->forward_type == MNN_FORWARD_METAL) {
>         auto host_ouput_tensor = new MNN::Tensor(this->_Lnet_output_tensor, MNN::Tensor::DimensionType::CAFFE);
>         this->_Lnet_output_tensor->copyToHostTensor(host_ouput_tensor);
>         out = host_ouput_tensor->host<float>();
>     } else {
>         out = this->_Lnet_output_tensor->host<float>();
>     }
> ```

您好，请问这个问题您解决了吗？

**Comment by ItchyHiker** [comment]
> > 在调用runSession的时候报以下错误:
> > -[MTLDebugComputeCommandEncoder dispatchThreadgroups:threadsPerThreadgroup:]:982: failed assertion `(threadgroupsPerGrid.width(0) * threadgroupsPerGrid.y(1) * threadgroupsPerGrid.depth(1))(0) must not be 0.'
> > 库是从release下的，mnn.metallib 是自己编译的，CPU模式下可以正常跑
> > 代码如下:
> > ```
> >     auto shape = this->_Lnet_input_tensor->shape();
> >     
> >     MNN::CV::Matrix trans;
> >     trans.postScale(1.0f/this->input_width, 1.0f/this->input_height);
> >     trans.postScale(face.cols, face.rows);
> >     this->pretreat_data->setMatrix(trans);
> >     this->pretreat_data->convert((uint8_t*)face.data, face.cols, face.rows, 0, this->_Lnet_input_tensor);
> > 
> >     this->_Lnet->runSession(this->_Lnet_sess);
> >     
> >     float *out;
> >     if (this->forward_type == MNN_FORWARD_METAL) {
> >         auto host_ouput_tensor = new MNN::Tensor(this->_Lnet_output_tensor, MNN::Tensor::DimensionType::CAFFE);
> >         this->_Lnet_output_tensor->copyToHostTensor(host_ouput_tensor);
> >         out = host_ouput_tensor->host<float>();
> >     } else {
> >         out = this->_Lnet_output_tensor->host<float>();
> >     }
> > ```
> 
> 您好，请问这个问题您解决了吗？
No, I did not solve it. Turns out that CPU is better for my situation.

**Comment by bitxsw93** [comment]
Please update lastest mnn code, retry again. If having any problem, please let me know.
