### ISSUE TITLE
训练量化代码存在内存泄漏

### ISSUE THREAD

**Issue by arcadiaphy** [alibaba/MNN#897]
在x86机器上跑训练量化的代码，存在严重的内存泄漏问题，用ASAN排查了下，问题出在：

https://github.com/alibaba/MNN/blob/master/express/Expr.cpp#L128
https://github.com/alibaba/MNN/blob/master/express/Expr.cpp#L199
https://github.com/alibaba/MNN/blob/master/express/Expr.cpp#L375
https://github.com/alibaba/MNN/blob/master/express/Expr.cpp#L461

类似`shared_ptr<char>(new char[10])`的结构，由于`shared_ptr`默认析构函数是`delete`而不是`delete []`，会导致内存泄漏

**Comment by yyfcc17** [comment]
非常感谢，内部已经修复
