### ISSUE TITLE
error for quantization_aware_training using pymnn

### ISSUE THREAD

**Issue by Danee-wawawa** [alibaba/MNN#898]
Hi, thank you for your job.
When I run MNN/pymnn/examples/MNNTrain/quantization_aware_training/quant_aware_training.py, 
the process is always killed at a specific time. I made the following marks in the program.
![image](https://user-images.githubusercontent.com/24379250/84726861-60276e80-afc0-11ea-820a-76f3ba65a13d.png)

And the result is as following:
![image](https://user-images.githubusercontent.com/24379250/84726888-72a1a800-afc0-11ea-963a-1d1428d5fb89.png)

Multiple attempts to run this file on the same server will be killed at the same time. 
It may be a problem of memory leak. Please check it, thank you.

**Comment by yyfcc17** [comment]
thank you, known issue, we are fixing it.

**Comment by dandanli814** [comment]
Okay, please let me know if you fix it, thank you.

**Comment by dandanli814** [comment]
And I have another question, do I have to specify "width" and  "height" parameters in this file https://github.com/alibaba/MNN/blob/master/tools/quantization/preprocessConfig.json? 
If I want the size of the input image to be a fixed height, the width is scaled in the same proportion. What should I do？
Looking forward to your answer, thank you.

**Comment by caijinana** [comment]
Traceback (most recent call last):
  File "train_cifar_qat.py", line 403, in <module>
    main()
  File "train_cifar_qat.py", line 322, in main
    fused_model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'

**Comment by yyfcc17** [comment]
@caijinana is this mnn original code? try this:
https://github.com/alibaba/MNN/tree/master/tools/MNNPythonOfflineQuant
