### ISSUE TITLE
Convert onnx model err

### ISSUE THREAD

**Issue by nullian** [alibaba/MNN#9]
I hava compiled the mnn converter successful. When i convert a onnx model to mnn use : 

./MNNConvert -f ONNX --modelFile mobilefacenet.onnx --MNNModel mobilefacenet.mnn --bizCode MNN

and i face this error:
MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[09:36:17] /home/yuanhao/osc/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
terminate called after throwing an instance of 'Error'
  what():  [09:36:17] /home/yuanhao/osc/MNN/tools/converter/source/onnx/onnxConverter.cpp:83: Check failed: opConverter ==> MNN Converter NOT_SUPPORTED_OP: [ PRelu ]
Aborted (core dumped)

How can i solve this problem, thanks!

**Comment by czy2014hust** [comment]
OK, get it. NOW not support for converting Prelu in ONNX model，will be added later! (Appreciate that You contribute to this work 😊)

**Comment by coollofty** [comment]
liteConverter.cpp:154: Check failed: creator ==> NOT_SUPPORTED_OP: [ PRELU ]

我在转换一个tflite模型的时候，依然报出了PRELU不支持，是还没加上吗？

**Comment by do-van-long** [comment]
> I hava compiled the mnn converter successful. When i convert a onnx model to mnn use :
> 
> ./MNNConvert -f ONNX --modelFile mobilefacenet.onnx --MNNModel mobilefacenet.mnn --bizCode MNN
> 
> and i face this error:
> MNNConverter Version: 0.0.0.1 - MNN @ 2018
> 
> Start to Convert Other Model Format To MNN Model...
> [09:36:17] /home/yuanhao/osc/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 3
> terminate called after throwing an instance of 'Error'
> what(): [09:36:17] /home/yuanhao/osc/MNN/tools/converter/source/onnx/onnxConverter.cpp:83: Check failed: opConverter ==> MNN Converter NOT_SUPPORTED_OP: [ PRelu ]
> Aborted (core dumped)
> 
> How can i solve this problem, thanks!

Hi @nullian ,
How (or where) did you get mobilefacenet.onnx model. I have tried to convert original MXNET models (from insightface) to ONNX models but not successful.
Could you please send me your mobilefacenet.onnx model?
Many thanks.

**Comment by jinfagang** [comment]
Hi, may I ask how does the Conv op converter registered? Since the Convolution only supported caffe and Tensorflow.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/21303438/161504167-e69d412b-e9b4-41ac-8529-593ffd8f4f18.png">

how does onnx conv parsed?

**Comment by lvZic** [comment]
PRELU OP not supported when cvting from TFLITE model
