### ISSUE TITLE
build demo/project cmake error

### ISSUE THREAD

**Issue by xiaohaipeng** [alibaba/MNN#90]
Build command failed.
Error while executing process C:\Users\11101477\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build D:\android_project\MNN-master\demo\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target mnncore}
[1/338] cmd.exe /C "cd /D D:\android_project\MNN-master\demo\android\app\build && bash D:/android_project/MNN-master/schema/generate.sh -lazy"
FAILED: ../../../../build/CMakeFiles/MNN_SCHEMA 
cmd.exe /C "cd /D D:\android_project\MNN-master\demo\android\app\build && bash D:/android_project/MNN-master/schema/generate.sh -lazy"

**Comment by xiaohaipeng** [comment]
problem with gcc or protobuf?

**Comment by li-qing** [comment]
check FAQ. windows is not currently supported.
