### ISSUE TITLE
precisionmode怎么配置

### ISSUE THREAD

**Issue by enduringstack** [alibaba/MNN#900]
你好！

1、该参数怎么配置？

2、该参数是表示模型参数如权值参数数据类型还是运行的结果的数据类型？

3、该参数应该可以看做决定了模型的精度，关于精度和性能，用户如何平衡？还是框架平衡？

**Comment by czy2014hust** [comment]
1. 参数分为Normal,Low,High: 默认情况下为Normal，如果用GPU作为Backend，设为Low可以提升性能(fp16，fp16存储 or/and fp16计算)，选用CPU并开启Armv8.2时设为Low也可以提升性能(fp16计算存储)，这种情况数值精度基本不变的
2. 运行结果的数据类型和你本身的模型保持一致，只是运行时计算的数据类型
3. 并不决定模型的精度；平衡的话，最好设为Low，但是对于INT8模型，设为Normal。
