### ISSUE TITLE
关于量化工具的编译产物问题

### ISSUE THREAD

**Issue by dandanli814** [alibaba/MNN#902]
您好，我看到  https://www.yuque.com/mnn/cn/tool_quantize  文档中有提到cmake .. -DMNN_BUILD_QUANTOOLS=on 之后会有两个编译产物quantized.out和testQuanModel.out，但是我现在执行完之后只有quantized.out，没有testQuanModel.out，请问下是怎么回事呢？

**Comment by czy2014hust** [comment]
文档还没有更新，这个testQuanModel已经删除！

**Comment by dandanli814** [comment]
那请问下，最新的MNN还提供了其他什么用于对比量化前后模型的工具吗？
