### ISSUE TITLE
image process 

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#906]
这段CODE 的意思是 MNN再做图像处理
需要把 RBGA 当作输入 才能处理吗
之后再把他转成 RGB

有没有其他可能的格式转法？
像是 BGR 当作输入并用MNN处理 输出是RGB

> `	MNN::CV::Matrix trans;

	trans.setScale(1.0f, 1.0f);
	MNN::CV::ImageProcess::Config img_config;
	img_config.filterType = MNN::CV::BICUBIC;
	::memcpy(img_config.mean, meanVals_, sizeof(meanVals_));
	::memcpy(img_config.normal, normVals_, sizeof(normVals_));
	img_config.sourceFormat = MNN::CV::RGBA;
	img_config.destFormat = MNN::CV::RGB;
	pretreat_ = std::shared_ptr<MNN::CV::ImageProcess>(MNN::CV::ImageProcess::create(img_config));
	pretreat_->setMatrix(trans);`

**Comment by jxt1234** [comment]
img_config.sourceFormat = MNN::CV::BGR; 这样改就行了

**Comment by alicera** [comment]
谢谢你的回答
我又想到MNN模型要求输入为NCHW
所以用opencv读取图片作为输入 不用管NCHW 或NHWC格式吗？

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/issues/909#issuecomment-646501337
