### ISSUE TITLE
MNN/project/ ?

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#907]
MNN/project/ 中的资料夹
能否說明 這3個資料夾要如何使用？？
满感兴趣的,谢

**Comment by czy2014hust** [comment]
交叉编译Android/iOS/其他平台的MNN库

**Comment by alicera** [comment]
MNN/project/cross-compile/
你是说他是用来编译 android AND IOS 环境时用到的
像是进入android 编译就执行./project/cross-compile/build.sh 编译
