### ISSUE TITLE
读取格式

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#909]
1.如何得知目前数据 是NHWC 还是 NCHW

2. 以下 是用OPENCV 读取 HWC格式 然后用MNN::Tensor::TENSORFLOW把图片转成 NHWC
之后又由 inputTensor->copyFromHostTensor(nhwc_Tensor);
转成 NCHW ， 不知道我的理解有无错误，请各位大大指教

>  // wrapping input tensor, convert nhwc to nchw    

    std::vector<int> dims{1, INPUT_SIZE, INPUT_SIZE, 3};
    auto nhwc_Tensor = MNN::Tensor::create<float>(dims, NULL, MNN::Tensor::TENSORFLOW);
    auto nhwc_data   = nhwc_Tensor->host<float>();
    auto nhwc_size   = nhwc_Tensor->size();
    ::memcpy(nhwc_data, image.data, nhwc_size);

    auto session = net->createSession(config);
    std::string input_tensor = "normalized_input_image_tensor";
    auto inputTensor  = net->getSessionInput(session, nullptr);
    inputTensor->copyFromHostTensor(nhwc_Tensor);

3. 由 inputTensor->copyFromHostTensor(nhwc_Tensor);
转成 NCHW ，是因为 auto inputTensor = net->getSessionInput(session, nullptr);的关系吗？
net 读取的.mnn 已把输入格式变成NCHW ，故get到的getSessionInput 必然是NCHW

**Comment by czy2014hust** [comment]
1. 你只需要关心你自己create的tensor格式就行，TENSORFLOW->NHWC, ONNX/CAFFE->NCHW
2. 不一定是转换为NCHW,有可能是NC4HW4，这个内部做的处理，不需要关心
3. 从网络中拿到的tensor不需要关心格式，只需要create你需要的格式的tensor，然后调用copy就行了

**Comment by alicera** [comment]
只需要关心你自己create的tensor格式就行

这句话是指 当我用OPENCV 读取图片后
如果 MNN MODEL 来自 CAFFE 就要把图片转成 NCHW
如果 MNN MODEL 来自 TENSORFLOW 就要把图片转成 NHWC

**Comment by czy2014hust** [comment]
你可以都创建NCHW或者都创建NHWC格式的tensor，不需要你管MNN模型输入要求什么格式。

**Comment by alicera** [comment]
再请教一下，那这段CODE 不就始终保持 NHWC，
根本没像注解那样 convert nhwc to nchw 最终为 NCHW

> // wrapping input tensor, convert nhwc to nchw

        std::vector<int> dim{1, input_H, input_W, 3};
        auto nhwc_Tensor = MNN::Tensor::create<float>(dim, NULL, MNN::Tensor::TENSORFLOW);
        auto nhwc_data = nhwc_Tensor->host<float>();
        auto nhwc_size = nhwc_Tensor->size();
        ::memcpy(nhwc_data, resized_image.data, nhwc_size);
        input->copyFromHostTensor(nhwc_Tensor);
        gettimeofday(&endtime, nullptr);

**Comment by cendelian** [comment]
请教一下 python下怎么是输入数据格式转为NC4HW4？

**Comment by hzpzlz** [comment]
https://github.com/hzpzlz/MNN-Opencv
MNN+opencv验证mnn模型完整教程
记得留个小星星！
