### ISSUE TITLE
unit tests for ios failed

### ISSUE THREAD

**Issue by suitmyself** [alibaba/MNN#91]
when I run playgroud on iphone xs max (not iphone 7 as in  [issue 19](https://github.com/alibaba/MNN/issues/19)),  I still get the following  precision error:
![图片](https://user-images.githubusercontent.com/5646651/58167164-e8541b00-7cbd-11e9-8a8f-c7984e624648.png)
so I comment this test,  but I still get:
![企业微信截图_4be10b67-9833-405e-95c3-8d0e9b6a2b89](https://user-images.githubusercontent.com/5646651/58166693-f81f2f80-7cbc-11e9-82b0-ad0c18ac27d6.png)
and then I comment the whole test,  but still have
![图片](https://user-images.githubusercontent.com/5646651/58166937-78459500-7cbd-11e9-85ff-1847353dc141.png)
then I comment the wrong tests one by one, but there always exists a wrong test.

It seems that when I run playgroud multi-times, xcode would reports errors at different locations.
And I change `MNN_METAL_FULL_PRECISION` (.h & .metal) to 1, the above precision error still exists.

**Comment by li-qing** [comment]
we disabled metal validation when developing, validation relative assertion will be fixed later.

for now, you could disable it in target settings - run - options - Metal API Validation.
