### ISSUE TITLE
量化报resized错误

### ISSUE THREAD

**Issue by HaoLiuHust** [alibaba/MNN#913]
使用的是python包里的mnnquant工具，原始模型是onnx，先用mnnconvert转换成了mnn，转换没有报错。但量化时出错了

![image](https://user-images.githubusercontent.com/7233091/85220349-4d0c0880-b3dd-11ea-82f1-7471dc2cdb73.png)

**Comment by HaoLiuHust** [comment]
如果不转成ONNX，而是转成caffe，然后再转成MNN, 量化就不报错

**Comment by huyangc** [comment]
same problem as #691

**Comment by Jayyyyyyyyyyyy** [comment]
你这闭环玩的真牛逼
