### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by marsupialtail** [alibaba/MNN#914]
Intel x86

 >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: x86_64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /home/ziheng/MNN/build
-- x86_64: Open SSE
-- MNN Depends:MNNMNN_Express
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ziheng/MNN/build

make -j8

[  1%] Built target GenVCSHDR
[  1%] Building CXX object CMakeFiles/MNNMath.dir/source/math/Matrix.cpp.o
[  1%] Built target MNNAVX
[  1%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageFloatBlitter.cpp.o
[  3%] Built target MNNSSE
[  4%] Building CXX object CMakeFiles/MNNCore.dir/source/core/Backend.cpp.o
[  4%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution1x1Strassen.cpp.o
[  5%] Building CXX object CMakeFiles/MNNCV.dir/source/cv/ImageProcess.cpp.o
[  5%] Building CXX object CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Convolution3D3x3.cpp.o
[  5%] Building CXX object CMakeFiles/MNNMath.dir/source/math/WingoradGenerater.cpp.o
[  6%] Building CXX object CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUArgMax.cpp.o
In file included from /home/ziheng/MNN/source/math/Matrix.cpp:12:0:
/home/ziheng/MNN/source/core/TensorUtils.hpp:13:10: fatal error: Tensor_generated.h: No such file or directory
 #include "Tensor_generated.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/ziheng/MNN/source/core/Backend.cpp:11:10: fatal error: MNN_generated.h: No such file or directory
 #include "MNN_generated.h"
          ^~~~~~~~~~~~~~~~~

**Comment by czy2014hust** [comment]
schema/generate.sh
