### ISSUE TITLE
MNN的training过程是静态图还是动态图？

### ISSUE THREAD

**Issue by stainless-steel-rat** [alibaba/MNN#918]
请问MNN框架的训练过程是静态图吗？ 例如train demo里的mnist例子：
                 auto predict = model->forward(example.first[0]);
                auto loss    = _CrossEntropy(predict, newTarget);
                sgd->step(loss);
这里的predict变量是在执行到model->forward()这句话的时候就获得了吗？

**Comment by yyfcc17** [comment]
是动态图，不过是lazy的，如果你不去取输出结果（variable里面的数据内容），那整个计算都不会进行，只进行必要的计算

**Comment by stainless-steel-rat** [comment]
> 是动态图，不过是lazy的，如果你不去取输出结果（variable里面的数据内容），那整个计算都不会进行，只进行必要的计算

好的，谢谢，还有一点我挺疑惑的，就是一个图创建完了，例如上面的lenet，一个Conv层是一个Module，对应的参数是一个VARP对象，对应的内部有一个Inside结构体，他的mUnit对象的exe成员是指向对应op实现的指针，这里的mUnit对象是在执行到哪一步或者说在哪个函数里被赋于特定Execution的指针的？

**Comment by jxt1234** [comment]
readMap 或者 grad 的 step -> prepareCompute
