### ISSUE TITLE
Finetuning MNN model with multiple outputs

### ISSUE THREAD

**Issue by minhhoangbui** [alibaba/MNN#919]
I'm currently retraining model using mnn model which is originally from TensorFlow. My model has two outputs, says `heatmaps` and `pafs`. 
When I use my mnn model for inference, I could access to 2 output tensors using `interpreter.getSessionOutput`. However, when I use `nn.load_module_from_file` to initialize model to retrain, I cannot get these 2 ` by using out_1, out_2 = net.forward(data)`

Then I change my loading method to :
```
def load_pose_model(model_file):
    var_dict = F.load_as_dict(model_file)
    input_var = var_dict['self']
    heatmaps_var = var_dict['light_weight_open_pose/StatefulPartitionedCall/StatefulPartitionedCall/refinement_stage/sequential_11/conv_26/RefinementStage_heat_conv2d/BiasAdd']
    pafs_var = var_dict['light_weight_open_pose/StatefulPartitionedCall/StatefulPartitionedCall/refinement_stage/sequential_12/conv_28/RefinementStage_paf_conv2d/BiasAdd']
    model = nn.load_module([input_var], [heatmaps_var, pafs_var], True)
    return model
```
But the error remains there although model loading is successful:
```
File "utils/quant.py", line 58, in quantize
    out_1, out_2 = net.forward(data)
ValueError: too many values to unpack (expected 2)
```
@yyfcc17 Can you have a look here?

**Comment by yyfcc17** [comment]
```
outputs = net.forward([data])
```
where ```outputs``` is a list containing the two outputs.
