### ISSUE TITLE
inputTensor->getDimensionType() error

### ISSUE THREAD

**Issue by xjcvip007** [alibaba/MNN#92]
Thank you for your job~ I have a .pb model with two input, one for a image (shape: (1, 36, 60, 3)), the other is a vector (shape: (1, 2)). I use converter tools to convert pb model to man model:
`./MNNConvert -f TF --modelFile ../pupilModel.pb --MNNModel pupilModel2.mnn --bizCode MNN`
But when  I use inputTensor->getDimensionType() to show the dimension type, which result is CAFFE not TENSORFLOW, and inference result is wrong. Why?

**Comment by li-qing** [comment]
guess first op in your model is conv. for performance consideration, we use NC4HW4 format in few op. use inputTensor's copyFromHostTensor to copy data from your tensor with TensorFlow dimType.

**Comment by xjcvip007** [comment]
thank you for your response, you mean use the link below to convert between formats.
[https://github.com/alibaba/MNN/blob/master/doc/FAQ.md#how-to-convert-between-formats-](url)
But some questions, in the document you use 
`auto srcTensor = Tensor::create({1, 224, 224, 3}, Tensor::TENSORFLOW);`

However,  in Tensor.hpp the function prototype is like below:
`static Tensor* create(const std::vector<int>& shape, halide_type_t type, void* data = NULL,
                          DimensionType dimType = TENSORFLOW);`
My question is that, what type value I should pass to the halide_type_t type?

**Comment by jxt1234** [comment]
auto srcTensor = Tensor::create<float>({1, 224, 224, 3}, Tensor::TENSORFLOW);

or 
auto srcTensor = Tensor::create({1, 224, 224, 3}, halide_type_of<float>(), Tensor::TENSORFLOW);

**Comment by xjcvip007** [comment]
Thanks for your response. My code is showing below, but error results, can you figure out something wrong? ('inputs/input_img' is the name of rgb order image input which shape is (1, 36, 60, 3), 'inputs/head_angle' is the name of vector which shape is (1, 2)). 
'
void setInput(cv::Mat &data, const char *name)
    {
        if(!strcmp("inputs/input_img", name))
        {       
            if(data.type() != CV_32FC3)
            {
                data.convertTo(data, CV_32FC3);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            const std::vector<int> dims = {1, 36, 60, 3};
            auto srcTensor = MNN::Tensor::create(dims, halide_type_of<float>());
            MNN::Tensor inputTensorUser(srcTensor, srcTensor->getDimensionType());
            if (nullptr == inputTensorUser.host<float>()) {

            } else {
                auto inputData = inputTensorUser.host<float>();
                for(int i = 0; i < data.rows; ++i)//36
                {
                    cv::Vec3f *row = data.ptr<cv::Vec3f>(i);
                    for(int j = 0; j < data.cols; ++j)//60
                    {
                        inputData[i*data.cols*3 + j*3] = row[j][0];
                        inputData[i*data.cols*3 + j*3 + 1] = row[j][1];
                        inputData[i*data.cols*3 + j*3 + 2] = row[j][2];
                    }
                }
                inputTensor->copyFromHostTensor(&inputTensorUser);
            }
        }
        else if(!strcmp("inputs/head_angle", name))
        {
            if(data.type() != CV_32FC1)
            {
                data.convertTo(data, CV_32FC1);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());

            if (nullptr == inputTensorUser.host<float>()) {
                
            } else {
                auto inputData = inputTensorUser.host<float>();
                inputData[0] = data.ptr<float>(0)[0];
                inputData[1] = data.ptr<float>(0)[1];
                inputTensor->copyFromHostTensor(&inputTensorUser);
            }
        }
    }` void setInput(cv::Mat &data, const char *name)
{  

        if(!strcmp("inputs/input_img", name))
        {       
            if(data.type() != CV_32FC3)
            {
                data.convertTo(data, CV_32FC3);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            const std::vector<int> dims = {1, 36, 60, 3};
            auto srcTensor = MNN::Tensor::create(dims, halide_type_of<float>());
            MNN::Tensor inputTensorUser(srcTensor, srcTensor->getDimensionType());
            if (nullptr == inputTensorUser.host<float>()) {
    
            } else {
                auto inputData = inputTensorUser.host<float>();
                for(int i = 0; i < data.rows; ++i)//36
                {
                    cv::Vec3f *row = data.ptr<cv::Vec3f>(i);
                    for(int j = 0; j < data.cols; ++j)//60
                    {
                        inputData[i*data.cols*3 + j*3] = row[j][0];
                        inputData[i*data.cols*3 + j*3 + 1] = row[j][1];
                        inputData[i*data.cols*3 + j*3 + 2] = row[j][2];
                    }
                }
                inputTensor->copyFromHostTensor(&inputTensorUser);
            }
        }
        else if(!strcmp("inputs/head_angle", name))
        {
            if(data.type() != CV_32FC1)
            {
                data.convertTo(data, CV_32FC1);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());
            if (nullptr == inputTensorUser.host<float>()) {
  
            } else {
                auto inputData = inputTensorUser.host<float>();
                inputData[0] = data.ptr<float>(0)[0];
                inputData[1] = data.ptr<float>(0)[1];
                inputTensor->copyFromHostTensor(&inputTensorUser);
            }
        }
    }
`

**Comment by jxt1234** [comment]
auto srcTensor = MNN::Tensor::create(dims, halide_type_of<float>());
        MNN::Tensor inputTensorUser(srcTensor, srcTensor->getDimensionType());

Turn to :

        MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());

**Comment by xjcvip007** [comment]
Thx, but the result of inputTensor->getDimensionType() is CAFFE for image input (even our mnn model is convert from tf pb format), which shape is (1,3,36,60), but the shape of our input image is (1, 36, 60, 3). So I use (1, 36, 60, 3) shape pass to srcTensor, then copy it to inputTensor.

**Comment by jxt1234** [comment]
Write as this:

    MNN::Tensor inputTensorUser(inputTensor, Tensor::TENSORFLOW);

**Comment by xjcvip007** [comment]
感谢，其实之前就是按照这个写法，inputTensorUser初始化成TF的类型，inputData按照（1，36，60，3）的rgb方式赋值，这样的话，copyFromHostTensor之后数据应该会转化成NCHW的格式，结果应该是正确的，但是结果仍然是错误的。

`void setInput(cv::Mat &data, const char *name)
{

    if(!strcmp("inputs/input_img", name))
    {       
        if(data.type() != CV_32FC3)
        {
            data.convertTo(data, CV_32FC3);
        }
        auto inputTensor = interpreter->getSessionInput(session, name);
        MNN::Tensor inputTensorUser(inputTensor, MNN::Tensor::TENSORFLOW);
        if (nullptr == inputTensorUser.host<float>()) {

        } else {
            auto inputData = inputTensorUser.host<float>();
            for(int i = 0; i < data.rows; ++i)//36
            {
                cv::Vec3f *row = data.ptr<cv::Vec3f>(i);
                for(int j = 0; j < data.cols; ++j)//60
                {
                    inputData[i*data.cols*3 + j*3] = row[j][0];
                    inputData[i*data.cols*3 + j*3 + 1] = row[j][1];
                    inputData[i*data.cols*3 + j*3 + 2] = row[j][2];
                }
            }
            inputTensor->copyFromHostTensor(&inputTensorUser);
        }
    }
    else if(!strcmp("inputs/head_angle", name))
    {
        if(data.type() != CV_32FC1)
        {
            data.convertTo(data, CV_32FC1);
        }
        auto inputTensor = interpreter->getSessionInput(session, name);
        MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());

        if (nullptr == inputTensorUser.host<float>()) {
            
        } else {
            auto inputData = inputTensorUser.host<float>();
            inputData[0] = data.ptr<float>(0)[0];
            inputData[1] = data.ptr<float>(0)[1];
            inputTensor->copyFromHostTensor(&inputTensorUser);
        }
    }
}
`

**Comment by jxt1234** [comment]
你图像缩放做了么

**Comment by xjcvip007** [comment]
我的tf的model是不对图像做任何处理，直接image pixel（0～255，shape：3*36*60）的直接输入的。

**Comment by li-qing** [comment]
有一点不理解，你新建一个Caffe或者TensorFlow的tensor，按照NCHW（Caffe）或者NHWC（TensorFlow）填充数据；之后，通过copy方法将tensor输入传入inputTensor，copy内会处理掉格式转换。是这么个流程？

**Comment by xjcvip007** [comment]
@li-qing ，感谢回复，我的想法是这样，本身原始的TF模型的输入格式是（1，36，60，3），但是转化成MNN的格式后输入格式是变成了（1，3，36，60），但是函数接口输入数据是Opencv的Mat格式，我先将其转化成NHWC，存入inputTensorUser的host中，再通过copy方法来进行格式转换来保证NCHW的输入格式正确。这样做的问题是什么呢？
还有一个问题，我尝试将两个模型输入都用全1.0，但是结果的输出仍然和我之前pb模型的输出不同，我不太清楚我数据读入的过程哪里出现了问题，还是模型转化出了问题，下附输入全1.0的代码，期待您的回复。
`    
 void setInput(cv::Mat &data, const char *name)

    {
        if(!strcmp("inputs/input_img", name))
        {       
            if(data.type() != CV_32FC3)
            {
                data.convertTo(data, CV_32FC3);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            MNN::Tensor inputTensorUser(inputTensor, MNN::Tensor::TENSORFLOW);
            if (nullptr == inputTensorUser.host<float>()) {

            } else {
                auto inputData = inputTensorUser.host<float>();
                auto size = inputTensorUser.size();
                for(int i = 0; i < data.rows; ++i)//36
                {
                    cv::Vec3f *row = data.ptr<cv::Vec3f>(i);
                    for(int j = 0; j < data.cols; ++j)//60
                    {
                        inputData[i*data.cols*3 + j*3] = 1.0;//row[j][0];
                        inputData[i*data.cols*3 + j*3 + 1] = 1.0;//row[j][1];
                        inputData[i*data.cols*3 + j*3 + 2] = 1.0;//row[j][2];
                    }
                }
                inputTensor->copyFromHostTensor(&inputTensorUser);
                int b = 0;
            }
        }
        else if(!strcmp("inputs/head_angle", name))
        {
            if(data.type() != CV_32FC1)
            {
                data.convertTo(data, CV_32FC1);
            }
            auto inputTensor = interpreter->getSessionInput(session, name);
            MNN::Tensor inputTensorUser(inputTensor, inputTensor->getDimensionType());
            if (nullptr == inputTensorUser.host<float>()) {
                
            } else {
                auto inputData = inputTensorUser.host<float>();
                inputData[0] = 1.0;//data.ptr<float>(0)[0];
                inputData[1] = 1.0;//data.ptr<float>(0)[1];
                std::cout << "result headangle " << inputData[0] << " " << inputData[1] << std::endl;
                inputTensor->copyFromHostTensor(&inputTensorUser);
                int b = 0;
            }
        }
    }
`

**Comment by chenti2x** [comment]
@xjcvip007 ，请问这个问题解决了吗？我也不太懂这里^_^

**Comment by Superlee506** [comment]
我觉得，你应该把你的图片输入变成NCHW格式吧
