### ISSUE TITLE
MNN format problem

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#921]
read the images with opencv , so the image format is HWC 

and the code is  let HWC to nhwc  :    opencv  >>  MNN Tensor TENSORFLOW       
and  "input->copyFromHostTensor(nhwc_Tensor);" will let  MNN Tensor TENSORFLOW    to NCHW
right ?

>  // wrapping input tensor, convert nhwc to nchw

        std::vector<int> dim{1, input_H, input_W, 3};
        auto nhwc_Tensor = MNN::Tensor::create<float>(dim, NULL, 
        MNN::Tensor::TENSORFLOW);//TENSORFLOW
        auto nhwc_data = nhwc_Tensor->host<float>();
        auto nhwc_size = nhwc_Tensor->size();
        ::memcpy(nhwc_data, resized_image.data, nhwc_size);
        input->copyFromHostTensor(nhwc_Tensor);
        gettimeofday(&endtime, nullptr);

**Comment by czy2014hust** [comment]
YES.
