### ISSUE TITLE
android端和windows端的数据差异问题

### ISSUE THREAD

**Issue by gudandenanhaier** [alibaba/MNN#922]
![image](https://user-images.githubusercontent.com/13115947/85511551-4f63a200-b62b-11ea-84b4-a057c01d4cdb.png)
 
用的是分割模型，根据网络的数据和0进行判断；android端的数据和0比较得到的图像、windows端的数据和0比较得到的图像差异比较明显；这是mnn框架目前支持的效果不好还是我用的有问题；

**Comment by jxt1234** [comment]
是否涉及图像预处理?

**Comment by gudandenanhaier** [comment]
不涉及预处理。。。。

**Comment by gudandenanhaier** [comment]
有预处理的过程   就是减均值 归一化   不涉及放缩

**Comment by jxt1234** [comment]
取网络输入打出来看一下？

**Comment by wangzhaode** [comment]
长时间未回复，关闭问题
