### ISSUE TITLE
onnx转mnn报错

### ISSUE THREAD

**Issue by daffia02** [alibaba/MNN#924]
Start to Convert Other Model Format To MNN Model...
[13:40:24] /root/git/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
terminate called after throwing an instance of 'Error'
  what():  [13:40:24] /root/git/MNN/tools/converter/source/onnx/Clip.cpp:37: Check failed: (maxValue) == (6.0f) ==> 
Aborted

是因为使用了relu6而转换不支持clip吗？该怎么办呢...

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/issues/794#issuecomment-628989896

**Comment by daffia02** [comment]
> [#794 (comment)](https://github.com/alibaba/MNN/issues/794#issuecomment-628989896)
谢谢！
