### ISSUE TITLE
question about quantization-aware training using quantized.out

### ISSUE THREAD

**Issue by Danee-wawawa** [alibaba/MNN#927]
Thank you for your work.
I have a question, do I have to specify "width" and "height" parameters in this file https://github.com/alibaba/MNN/blob/master/tools/quantization/preprocessConfig.json?
If I want the size of the input image to be a fixed height, the width is scaled in the same proportion. Can this be achieved?
Looking forward to your answer, thank you.

**Comment by yyfcc17** [comment]
yes, input images will be resized to (height, width)

maybe you can try out our python version offline quant. by removing the ```solver.step(loss)``` line in QAT process.

reference:
https://github.com/alibaba/MNN/issues/904#issuecomment-646485738

**Comment by dandanli814** [comment]
OK, thank you, I will try it.

**Comment by dandanli814** [comment]
Hi, as you suggest, I try out your python version offline quant. by removing the solver.step(loss) line in QAT process. But I meet an error:

![image](https://user-images.githubusercontent.com/24379250/86224224-2f982500-bbbb-11ea-9163-d82decf07a8b.png)

in the following code:

for epoch in range(5):
        train_func(net, train_dataloader, opt, num_classes)
        # save model
        file_name = '%d.ocrnet.mnn' % epoch
        net.train(False)
        print("1111")
        predict = net.forward(F.placeholder([1, 1, 32, 512], F.NC4HW4))   //where the error is
        print("222")
        print("Save to " + file_name)
        F.save([predict], file_name)

What is the cause of this error?
Looking forward for your answer, thank you.

**Comment by dandanli814** [comment]
@yyfcc17 

Hi, I try out your python version offline quant by removing the solver.step(loss) line in QAT process, but the accuracy of the obtained quantified model is much lower than that obtained model when using "quantized.out". Is there any way to improve the accuracy of the quantified model obtained by your python version offline quant?

In addition, do you have a plan to support CTC loss in MNN, and if so, when can it be supported?

Looking forward for your answer.

**Comment by awl-hoang-bui** [comment]
@dandanli814 The whole quantization doesn't work for me neither, even with QAT or pseudo-training without `solver.step(loss)`. It's really queer to me.
I think that we need to wait for the new update.
Please keep me posted if you find anything interesting

**Comment by dandanli814** [comment]
@awl-hoang-bui 
They have recently updated a version,  I tried it and found that the accuracy still dropped a lot. And the accuracy of the new version is not as good as the old version. This is very strange.

**Comment by yyfcc17** [comment]
i am sorry for the inconvenience. we are considering release a tf/pytorch tool, maybe that will help? @awl-hoang-bui @dandanli814

**Comment by awl-hoang-bui** [comment]
@yyfcc17 Please release that tool. I'm happy to try this with my TF2.0 code base

**Comment by dandanli814** [comment]
@yyfcc17 
Yeah, please release that tool. Mine is based on pytorch.

**Comment by wangzhaode** [comment]
https://mnn-docs.readthedocs.io/en/latest/tools/compress.html#mnncompress
