### ISSUE TITLE
ResizeNearestNeighbor int8 tflite转换时报错

### ISSUE THREAD

**Issue by 871699406** [alibaba/MNN#928]
$ ./MNNConvert -f TFLITE --modelFile detect8.tflite --MNNModel detect8.tflite.mnn --bizCode MNN

MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
libc++abi.dylib: terminating with uncaught exception of type Error: [18:24:53] 。。。/MNN/tools/converter/source/tflite/ResizeBilinear.cpp:16: Check failed: !quantizedModel ==>
Abort trap: 6

模型里的op是ResizeNearestNeighbor,为什么报错会是ResizeBilinear.cpp？不知道和int8模型有没有关系

**Comment by 871699406** [comment]
![Foxmail20200628062934](https://user-images.githubusercontent.com/8012818/85945116-1ea6a400-b96e-11ea-90d5-3109262b1451.png)

[detect8.tflite.zip](https://github.com/alibaba/MNN/files/4842085/detect8.tflite.zip)
文件和截图

**Comment by jxt1234** [comment]
暂不支持tflite 的量化 resize
