### ISSUE TITLE
Does MNN plan to support half precision conversion in tflite format?

### ISSUE THREAD

**Issue by dom607** [alibaba/MNN#929]
While converting the tflite model I want to use with the conversion tool, the conversion process ended without any message. This seems to be because the flatbuffer used inside MNN does not support half precision. Do you have any plans to support it?

PS : The model I am trying to convert is ```face_landmark.tflite``` in the Google mediapipe repository.

**Comment by czy2014hust** [comment]
Find the tensorflow model(Pb), then convert it using MNNConveter with _--fp16_ parameter
