### ISSUE TITLE
MAC端No module named 'MNN'

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#930]
在mac平台上，编译过安卓和ios的库，都正常使用。
今天要在mac上使用python调用mnn的库，出现以下错误：
 import MNN
ModuleNotFoundError: No module named 'MNN'

已经在mac上执行了：
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

也运行了
mkdir build && cd build && cmake .. && make -j4 && sudo make install

**Comment by czy2014hust** [comment]
https://github.com/alibaba/MNN/blob/master/pymnn/INSTALL.md
