### ISSUE TITLE
32位arm7a编译的MNN动态库，测试fp16耗时不降，是因为MNN本身就不支持arm7a平台fp16加速吗？

### ISSUE THREAD

**Issue by lcaikk1314** [alibaba/MNN#931]

**Comment by czy2014hust** [comment]
fp16的加速只在armv8(64位机器)上有效果

**Comment by lcaikk1314** [comment]
> fp16的加速只在armv8(64位机器)上有效果

谢谢你答复，刚才我重新编译了64位库，推理时设置了fp16推理， 编译选项也打开了MNN_ARM82；在麒麟955（核心Cortex A72基于64位ARMv8），测试依然没有耗时下降，是不是严格要求arm8.2以上平台？

**Comment by czy2014hust** [comment]
- 麒麟955应该不是armv8.2指令集，所以不支持的话，退回原始的CPU实现
- 必须要支持armv8.2指令集的机器上才有加速效果
