### ISSUE TITLE
tf模型转换后修改DimensionType为TENSORFLOW

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#932]
有个tensorflow的pb模型转换成MNN后，调用getSessionInput得到的tensor的getDimensionType，返回的是MNN::Tensor::CAFFE。
我想强制改成MNN::Tensor::TENSORFLOW，请问有接口吗？

**Comment by czy2014hust** [comment]
不能修改！
我猜你要输入数据，请参考https://github.com/alibaba/MNN/issues/921#issue-644367377
