### ISSUE TITLE
执行推理时，如何指定异构的不同后端？

### ISSUE THREAD

**Issue by enduringstack** [alibaba/MNN#934]
Android平台做模型推理：

1. 在模型执行推理时，如何让一部分算子跑在一个后端上，另一部分算子跑在另一部分后端上？
2. 异构后端选择完成后，precisionmode这个参数怎么填写？ 不同后端若使用不同的精度范围计算怎么操作？ （比如cpu使用fp16，gpu使用fp32）

谢谢

**Comment by DamonsJ** [comment]
同问，是不是支持这种一个推理在不同端上执行

**Comment by wangzhaode** [comment]
可以参考：https://mnn-docs.readthedocs.io/en/latest/inference/session.html#id6

不过这样做往往性能并不会太好
