### ISSUE TITLE
MNN images process

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#936]
I know MNN images process support  mean an std
does it support divide method?

like  this
"/ "  of  ( image / 255 )  - mean

**Comment by yyfcc17** [comment]
do a little math here, you can figure it out.

**Comment by alicera** [comment]
（x - mean) * normal
it will process with this

> const float means[3] = {103.94f, 116.78f, 123.68f};

const float normals[3] = {0.017f, 0.017f, 0.017f};
MNN::CV::ImageProcess::Config process;
::memcpy(process.mean, means, sizeof(means));
::memcpy(process.normal, normals, sizeof(normals));
process.sourceFormat = MNN::CV::RGBA;
process.destFormat = MNN::CV::BGR;
std::shared_ptrMNN::CV::ImageProcess pretreat(MNN::CV::ImageProcess::create(process));


if I want to do （x/255 - mean) * normal
the "/255" how to do

**Comment by jxt1234** [comment]
Merge /255 to mean and normal, That is:
(x - 255.0 * mean) * (normal / 255.0)

meanNew = 255.0 * mean 
normalNew = normal/255.0

**Comment by alicera** [comment]
ok, I got it.
But it should be  normalNew = normal*255.0
