### ISSUE TITLE
copyToHostTensor

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#937]
MNN::Tensor* output_score = classifier_interpreter_->getSessionOutput(classifier_sess_, nullptr);
    // copy to host
    MNN::Tensor score_host(output_score, output_score->getDimensionType());
    output_score->copyToHostTensor(&score_host);

为什么 要把输出的TENSOR在COPY到其他同类型TENSOR ，这样不是多一个变数

**Comment by alicera** [comment]
const float meanVals[3] = { 103.94f, 116.78f, 123.68f };
    const float normVals[3] = {  0.017f,  0.017f,  0.017f };
顺序是 BGR 还是RBG

**Comment by jxt1234** [comment]
1、session 内的 tensor 为便于计算的内存布局（NC4HW4 或者 GPU 内存中），copy 出来之后为用户可访问的状态
2、这个顺序由 ImageProcess.Config.destFormat 指定
