### ISSUE TITLE
convert MNN failed

### ISSUE THREAD

**Issue by ljiqy** [alibaba/MNN#938]
my pytorch model have torch.gather, I can convert it to onnx, in onnx it is ONNX::GatherElements, but when I convert onnx model to MNN model, it failed: Check failed: (notSupportOps.size()) == (0) ==> These Op Not Support: ONNX::GatherElements |
Is there an alternative to Gather in MNN? Dose anyone know about it?

**Comment by jxt1234** [comment]
ONNX::Gather is supported.

**Comment by ljiqy** [comment]
> ONNX::Gather is supported.

but I used ONNX::GatherElements, not ONNX::Gather, Is there an alternative?

**Comment by MaybeShewill-CV** [comment]
@ljiqy 请问这个问题有什么解决方案吗

**Comment by murphypei** [comment]
The GatherElements of MNN converter dosen't support dynamic shape, maybe you should fix the input shape.

**Comment by wangzhaode** [comment]
目前已经支持该算子

**Comment by murphypei** [comment]
> 目前已经支持该算子

great job, thx for all your team's work!
