### ISSUE TITLE
MNNConverter failed to convert TFLITE model to MNN model

### ISSUE THREAD

**Issue by valwang** [alibaba/MNN#94]
I hava compiled the mnn converter successful. When i convert a TFLITE model to MNN model. I got following error:

 $ ./MNNConvert -f TFLITE --modelFile note_model.tflite --MNNModel note_model.mnn --bizCode MNN

MNNConverter Version: 0.0.0.1 - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
terminate called after throwing an instance of 'Error'
  what():  [22:40:02] /home/valwang/project/MNN-master/tools/converter/source/tflite/liteConverter.cpp:90: Check failed: creator ==> NOT_SUPPORTED_OP: [ 18 ]
Aborted (core dumped)

It did not show the OP name. Do you know which OP it is? And how to solve it? Thanks!

**Comment by czy2014hust** [comment]
Mul,
Find in [this file](https://github.com/alibaba/MNN/blob/master/tools/converter/source/tflite/schema/schema.fbs)

**Comment by valwang** [comment]
@czy2014hust 
Thanks for the answer. Is there plan to support it?

**Comment by czy2014hust** [comment]
Please comment on #74
