### ISSUE TITLE
在海思3559c上使用opencl前向报错

### ISSUE THREAD

**Issue by weixiaolian21** [alibaba/MNN#946]
使用cpu前向一切正常：
当使用opencl前向时报错
`
unhandled level 2 translation fault (11) at 0x00000000, esr 0x92000046
pgd = ffffffc040f2e000
[00000000] *pgd=00000000800b9003, *pud=00000000800b9003
, *pmd=0000000000000000

CPU: 1 PID: 1860 Comm: dot_mnn Tainted: P           O    4.9.37 #1
Hardware name: Hisilicon HI3559AV100 DEMO Board (DT)
task: ffffffc040759800 task.stack: ffffffc040280000
PC is at 0x409158
LR is at 0x409144
pc : [<0000000000409158>] lr : [<0000000000409144>] pstate: 40000000
sp : 0000007fc7518a00
x29: 0000007fc7518a00 x28: 0000000000000000 
x27: 000000000045db90 x26: 000000000045a0d0 
x25: 000000000046b970 x24: 0000007fc7518b5c 
x23: 0000007fc7518b58 x22: 0000007fc7518ad0 
x21: 0000007fc7518b60 x20: 0000007fc7518ba0 
x19: 0000007fc7518c00 x18: 0000007fc75181f0 
x17: 0000007f74c904f8 x16: 0000007f74ff4678 
x15: 0000000000000124 x14: 0000000000000000 
x13: 0001000000000000 x12: 0000007f6b000000 
x11: 0000000000000000 x10: 0000000000833000 
x9 : 0000000000b43860 x8 : 0000000000000000 
x7 : 0000000000000000 x6 : 0000000000000000 
x5 : 0000007f74d5f9a8 x4 : 00000000ffffffff 
x3 : 0000000000000000 x2 : 0000000000000000 
x1 : 0000000000699e60 x0 : 000000000045a0d0 

Segmentation fault
`
交叉编译的benchmark.out 运行自己转的模型也是正常能运行的，说明模型没问题。
怀疑是我编译时候有问题，有大佬知道编译自己的代码时如何编译带有opencl的吗？

**Comment by weixiaolian21** [comment]
错误的愿意是直接把cpu的数据 让gpu调用了 ,中间得参考例子 先把数据复制到cpu的mat上  然后用mat构造gpu的mat再前向

**Comment by dan520520520** [comment]
> 
> 
> 错误的愿意是直接把cpu的数据 让gpu调用了 ,中间得参考例子 先把数据复制到cpu的mat上 然后用mat构造gpu的mat再前向
请问你是参考的哪个代码？编译时，cmake -DCMAKE_TOOLCHAIN_FILE=../project/cross-compile/arm.toolchain.cmake -DARM_NAME=hisi3559a100 -DMNN_OPENCL=ON ..，使用opencl编译还有什么需要做的吗？我这边虽然编译成功了，但是板端推理一直有错误。
