### ISSUE TITLE
ONNX to MNN converter segmentation fault with no other information

### ISSUE THREAD

**Issue by jadenwjh** [alibaba/MNN#950]
MacOSX

steps taken:
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz

Usually if the operations on the onnx models are not supported, error lines such as "Check it out => ... " will appear. 

However, for this particular error, I only got the message mentioning the IR version of my model (IR 6), and "segmentation fault", without any numbers behind it.

Full error log:
Start to Convert Other Model Format To MNN Model...
[14:30:55] /Users/usr/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
zsh: segmentation fault  ./MNNConvert -f ONNX --modelFile input.onnx --MNNModel   biz

**Comment by fangchengji** [comment]
The same problem. I use the onnx opset 11, pytorch 1.6. 
Did you solved the problem?
Thanks!

**Comment by smartadpole** [comment]
Did you solved it, I got the same problem. @fangchengji @jadenwjh 
convert output:    
```
MNNConverter Version: 0.2.1.5git - MNN @ 2018


Start to Convert Other Model Format To MNN Model...
[11:22:29] /media/hao/WORK/SOURCE/DL/MOBILE_INFERENCE/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 4
Start to Optimize the MNN Net...
...
[11:22:29] PostConverter.cpp:37: Outputs: 1136, Type = Convolution
Converted Done!
```
and the forward post :     
```
./benchmark.out model/ 10 10 3 4
MNN benchmark
Forward type: **OpenCL** thread=4** precision=2
--------> Benchmarking... loop = 10, warmup = 10
Segmentation fault (core dumped)
```

**Comment by fangchengji** [comment]
I got through with opset 9 and only use the basic operation.

**Comment by DavdGao** [comment]
Got the same problem in Version 2.0.0

**Comment by wangzhaode** [comment]
Need more crash log. Can you provide the crash stack ?

**Comment by wangzhaode** [comment]
Or can you provide ONNX model ?
