### ISSUE TITLE
OPENCL  ERRO CODE -63 

### ISSUE THREAD

**Issue by weixiaolian21** [alibaba/MNN#955]
使用pytorch训练了一个多输入的分类模型,  pytorch->onnx->mnn,进行前向推理:
CPU推理正确,使用opencl推理报错.
使用pytorch->caffe->mnn转换模型.两个都正确.
对比转换后的模型的不同.
onnx转换过来的会多两个ConvertTensor层, 并使用matmul层和binaryop层联合实现全连接层.
caffe转换过来的模型是用卷积层替代全连接层.
还是想知道这个onnx转换过来的模型的报错原因.

**Comment by bitxsw93** [comment]
你好，感谢反馈。可否把opencl报错的模型提供一下，方便我们来看下？

**Comment by bitxsw93** [comment]
> 使用pytorch训练了一个多输入的分类模型, pytorch->onnx->mnn,进行前向推理:
> CPU推理正确,使用opencl推理报错.
> 使用pytorch->caffe->mnn转换模型.两个都正确.
> 对比转换后的模型的不同.
> onnx转换过来的会多两个ConvertTensor层, 并使用matmul层和binaryop层联合实现全连接层.
> caffe转换过来的模型是用卷积层替代全连接层.
> 还是想知道这个onnx转换过来的模型的报错原因.

是实现内部concat尺寸获取上有潜在bug，修复了会同步到GitHub。
