### ISSUE TITLE
writeFb.cpp源代码的一个疑问

### ISSUE THREAD

**Issue by Gankerzzl** [alibaba/MNN#96]
https://github.com/alibaba/MNN/blob/master/tools/converter/source/common/writeFb.cpp

这个源文件里 if (benchmarkModel) 这个条件分支的目的是做什么呢？网络结构优化？因为我发现从onnx转换过来的BatchNorm操作在MNN里没有了。

另外，这个分支里switch语句有些case分支没有break语句是特意为之？

**Comment by czy2014hust** [comment]
- Please read [Converter README](https://github.com/alibaba/MNN/blob/master/tools/converter/README.md) about [benchmarkModel]
- BatchNorm will be converted to be Scale or will be fused into Convolution.

**Comment by Gankerzzl** [comment]
@czy2014hust Thanks.
