### ISSUE TITLE
Onnx slice must use the same dimensition问题

### ISSUE THREAD

**Issue by CallMeEricChiu** [alibaba/MNN#960]
onnx转mnn出现以下报错，我看别人也有类似问题下面回答是固定输入大小，请问如何固定呢？我在调用pytorch转onnx接口时已经指定输入tensor大小了呀。。。
`MNNConverter Version: 0.2.1.5git - MNN @ 2018

Start to Convert Other Model Format To MNN Model...
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/onnx/onnxConverter.cpp:29: ONNX Model ir version: 6
Start to Optimize the MNN Net...
Don't support broadcast for binaryOp, i0=130, i1=128
Onnx slice must use the same dimensition
Convert Onnx's Op 555 , type = Slice, failed, may be some node is not const
Check failed: scalesSize == 4 ==> "ONNX resize sizes should have 4 elements(n,c,h,w)"
Onnx slice must use the same dimensition
Convert Onnx's Op 576 , type = Slice, failed, may be some node is not const
Check failed: scalesSize == 4 ==> "ONNX resize sizes should have 4 elements(n,c,h,w)"
Don't support broadcast for binaryOp, i0=130, i1=128
Don't support broadcast for binaryOp, i0=130, i1=128
Don't support broadcast for binaryOp, i0=130, i1=128
Don't support broadcast for binaryOp, i0=130, i1=128
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:20: Inputs: input
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: output0, Type = Interp
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 597, Type = Interp
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 614, Type = Interp
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 631, Type = Interp
[10:59:27] /home/zhiyi.qiu/MNN/tools/converter/source/optimizer/PostConverter.cpp:37: Outputs: 648, Type = Interp
Converted Done!
`
如下图，slice op是为了获取featuremap的batch和channel然后与(H,W)concat之后作为resize op的sizes参数的输入
![image](https://user-images.githubusercontent.com/51788361/86722783-d2d4b880-c059-11ea-8644-a60d92240226.png)

**Comment by jxt1234** [comment]
Don't support broadcast for binaryOp, i0=130, i1=128 

是之前有错误，你模型方便发来看一下么?

**Comment by CallMeEricChiu** [comment]
.pt和.onnx发您了，感谢大佬！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jxt1234"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月7日(星期二) 下午2:23
收件人:&nbsp;"alibaba/MNN"<MNN@noreply.github.com&gt;;
抄送:&nbsp;"邱志贻"<936142924@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/MNN] Onnx slice must use the same dimensition问题 (#960)





 
Don't support broadcast for binaryOp, i0=130, i1=128
 
是之前有错误，你模型方便发来看一下么?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

BiSeNetV2.onnx (14.02M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7435336619812f9e7b5dff514731024e56565150510606591a56075f021c04570f0d1e045202524c5303025e0401070305000454613f30235e66562804456653195a5d0819310d&t=exs_ftn_download&code=753fa10a




BiSeNetV2.pth (14.05M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2361623600722acf2d09ae014036071f52040053030507514c005404041b015103024f0e510f501d545803025055560152545b04663b357208320778034263024f11165e660b&t=exs_ftn_download&code=aab6f650

**Comment by CallMeEricChiu** [comment]
@jxt1234 请问大佬是我模型的问题还是mnn问题。。

**Comment by jxt1234** [comment]
fixed

**Comment by zhepherd** [comment]
> fixed

i have the same problem, how to fixed??
