### ISSUE TITLE
Python Api 没有releaseSession接口，存在内存泄漏问题

### ISSUE THREAD

**Issue by anyongjin** [alibaba/MNN#963]
windows
python3.6.8
pip install -U MNN方式安装的

通过createSession创建调用模型后，存在内存泄漏问题，没有releaseSession接口，无法释放占用内存。

**Comment by geekzhu001** [comment]
修改模型输入尺寸的接口好像也有问题

**Comment by wangzhaode** [comment]
session析构后会自动释放，目前版本不存在内存泄露
