### ISSUE TITLE
stream operation 

### ISSUE THREAD

**Issue by fangxuefei1989** [alibaba/MNN#965]
官方会考虑推出流式的算子实现吗？在实时的数据流中，可以收到一部分数据就处理，可以减少延迟，分摊运算量

谷歌在tensorflow的develop中有类似的实现：https://github.com/google-research/google-research/tree/master/kws_streaming

相关文献：Streaming keyword spotting on mobile devices

**Comment by jxt1234** [comment]
在设计中，多谢建议
