### ISSUE TITLE
hrnet转换后结果不对

### ISSUE THREAD

**Issue by Yoline777** [alibaba/MNN#966]
```
model.load_state_dict(torch.load('../models/pytorch/pose_coco/pose_hrnet_w32_256x192.pth'), strict=False)
dummy_input = torch.zeros(1, 3, 192, 256)
input_names = [ "input" ]
output_names = [ "output" ]
torch.onnx.export(model, dummy_input, "pose_hrnet_w32_256x192.onnx", verbose=True, input_names=input_names, output_names=output_names, do_constant_folding=True)

./MNNConvert -f ONNX --modelFile XXX.onnx --MNNModel XXX.mnn --bizCode biz
```
这是我用的转换方法 最后在Android里用一张全黑的图和pytorch的全0输出作比较 输出结果不一样

**Comment by Yoline777** [comment]
```
UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
```转换ONNX的时候 这个有影响么

**Comment by Yoline777** [comment]
```
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1,
                               bias=False)
        self.bn1 = nn.BatchNorm2d(64, momentum=BN_MOMENTUM)
```
只用网络的前2层做实验
输入全为0的时候conv1的结果都为0 但是bn1的结果（前10个）分别为[-0.00023686, -0.00023686, -0.00023686, -0.00023686, -0.00023686,
        -0.00023686, -0.00023686, -0.00023686, -0.00023686, -0.00023686]和-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4*-2.4213358E-4

**Comment by Yoline777** [comment]
输入全为0.5的时候conv1的结果分别为
[ 1.91486142e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05, -7.71571940e-05] 和
1.9148618E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5*-7.715718E-5
bn1的结果为
[-0.00022722, -0.00023008, -0.00023008, -0.00023008, -0.00023008, -0.00023008, -0.00023008, -0.00023008, -0.00023008, -0.00023008] 和
-2.4157808E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4*-2.4437194E-4

**Comment by Yoline777** [comment]
想请问bn层需要作特殊处理么 还是存在精度损失问题

**Comment by weixiaolian21** [comment]
是不是没有设置 model.eval()  让模型处于预测模式固定一些参数.

**Comment by jxt1234** [comment]
关闭历史问题，更新 MNN 后测试有问题再重新提 issue
