### ISSUE TITLE
Error for 502,  while inference with MNNmodel

### ISSUE THREAD

**Issue by NewCoderQ** [alibaba/MNN#967]
tflite 模型转 MNN 模型没有问题，使用 python 接口调用 MNN 模型做前向推理的时候 报 Error for 502错误

**Comment by yubinyes** [comment]
你解决了吗?    我用pb转换mnn，命令也没有提示错误，运行的时候出现 error for 297      error for 300

**Comment by NewCoderQ** [comment]
还没有解决呢，这两天没顾上解决 这个问题

**Comment by yubinyes** [comment]
我这边没问题了， MNN.Tensor的时候和前面的图像type对应就好了

**Comment by ShihuaiXu** [comment]
@yubinyes
兄弟 我也报了error for 297 error for 300
用默认的mobilenet_demo.py的代码 请问你是怎么解决的

**Comment by yubinyes** [comment]
@ShihuaiXu  我这边把类型对应好就没错了，MNN.Tensor((1, input_size, input_size, 3), MNN.Halide_Type_Uint8, inputData,NN.Tensor_DimensionType_Tensorflow)，我这边输入的是Uint8，shape是行列通道

**Comment by yubinyes** [comment]
@ShihuaiXu  我这边把类型对应好就没错了，MNN.Tensor((1, input_size, input_size, 3), MNN.Halide_Type_Uint8, inputData,MNN.Tensor_DimensionType_Tensorflow)，我这边输入的是Uint8，shape是行列通道

**Comment by ShihuaiXu** [comment]
谢谢兄弟 方便加个qq聊一下吗 我们的业务可能相似 我的qq是531232693

**Comment by wangzhaode** [comment]
应该是输入格式/数据类型不正确导致
