### ISSUE TITLE
timeProfile.out工具统计tensorflow(pb模型)转MNN模型FLOPs结果错误

### ISSUE THREAD

**Issue by whuwiqian** [alibaba/MNN#971]
如题

**Comment by jxt1234** [comment]
有具体模型么？

**Comment by whuwiqian** [comment]
tensorflow和MNN模型
[model.zip](https://github.com/alibaba/MNN/files/4930289/model.zip)

**Comment by whuwiqian** [comment]
> 有具体模型么？
模型文件
[model.zip](https://github.com/alibaba/MNN/files/4930293/model.zip)
