### ISSUE TITLE
no member named 'minValue' in 'MNN::Relu6

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#973]
下载最新代码编译，使用默认shell配置，出现错误：

kom:android kom$ cd build_32
kom:build_32 kom$ ../build_32.sh 

MNN/source/backend/cpu/CPURelu.cpp:129:23: error: no member named 'minValue' in 'MNN::Relu6'
            minV = p->minValue();
                   ~  ^
MNN/source/backend/cpu/CPURelu.cpp:130:23: error: no member named 'maxValue' in 'MNN::Relu6'
            maxV = p->maxValue();

**Comment by jxt1234** [comment]
重新生成 schema 文件: cd schema && ./generate.sh
