### ISSUE TITLE
你好，我才用pytorch实现了一个网络模型，并且将它通过onnx转化为了一个mnn，我在对他进行量化的时候爆下面的错误

### ISSUE THREAD

**Issue by ChenCongGit** [alibaba/MNN#975]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by ChenCongGit** [comment]
[20:06:50] /data00/home/chencong/MNN/tools/quantization/calibration.cpp:142: Input Data Format ERROR!The ConvertTensor2's input is not ready Resize error for [ConvertTensor], ConvertTensor2, code=3 Can't run session because not resized Can't run session because not resized

**Comment by lipeng1109** [comment]
这个问题很棘手啊，我出现了没有思路去怎么解决，是不是MNN对pytorch的支持不是太好，里面很多的层级不支持的原因？

**Comment by yyfcc17** [comment]
请更新代码试一下

**Comment by wangzhaode** [comment]
长时间未回复，关闭问题；
