### ISSUE TITLE
cannot find -lGLESv3

### ISSUE THREAD

**Issue by zhangkom** [alibaba/MNN#976]
使用的是最新的0.1的版本，commit如下：
commit a6836bb50a4ba615bfc8b6a367d282120a274097 (HEAD -> master, origin/master, origin/HEAD)
Author: xiaying <xiaotang.jxt@alibaba-inc.com>
Date:   Thu Jul 9 14:44:34 2020 +0800

    Support Tensorflow ClipByValue

打开了opencl opengl vulkan三个开关：
-DMNN_OPENCL=ON \
-DMNN_OPENGL=ON \
-DMNN_VULKAN=ON \

结果编译出现了问题：
[ 83%] Linking CXX shared library ../../../libMNN_GL.so
/Users/kom/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lGLESv3

**Comment by Xyzhao1999** [comment]
可能是因为MNN的编译脚本build_32.sh 中Android api版本为14  而根据文档，编译OpenGL最低需要api版本为21。

**Comment by black-giser** [comment]
step.1、download your expected ndk
step.2、set the ndk version as your version in CMakeLists.txt

**Comment by TUT-jiayou** [comment]
我想要在设备aarch64 ubuntu 上面,运行gpu, 使用x86-64 ubuntu 交叉编译MNN ,但是遇到了下面的错误
```
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lGLESv3
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lEGL

```

有人遇到过这个问题么?

**Comment by jxt1234** [comment]
Linux 上默认不支持 OpenGL ES ，需要安装 angle （不推荐）
一般建议采用 opencl / cuda
