### ISSUE TITLE
MNN Document problem

### ISSUE THREAD

**Issue by alicera** [alibaba/MNN#979]
https://www.yuque.com/mnn/en/input#CoM0X
I see the Fill Data say 
"The simplest way to fill tensor data  is assigning value to host directly, but this usage is limited to the CPU backend,  other backends need to write data via deviceid. On the other hand, users need to handle the differences between NC4HW4 and NHWC data layouts."

Because I use the config, I have to use Copy Data method, right? 
>    ScheduleConfig config;
    config.type = MNN_FORWARD_AUTO;

if I use the config, I wont use Copy Data method, right? 
>  ScheduleConfig config;
    config.type = MNN_FORWARD_CPU;

**Comment by wangzhaode** [comment]
Suggest using  `copyFromHost` whatever backend.
