### ISSUE TITLE
Is it possible to run model which is converted from onnx without optimization?

### ISSUE THREAD

**Issue by Gankerzzl** [alibaba/MNN#98]
in MNNConverter.cpp, it will optimize the net which is not MNN model, can I comment the "optimizeNet" statement? Is the result equal to optimized net?

    if (modelPath.model != modelConfig::MNN) {
        std::cout << "Start to Optimize the MNN Net..." << std::endl;
        std::unique_ptr<MNN::NetT> newNet = optimizeNet(netT);
        writeFb(newNet, modelPath.MNNModel, modelPath.benchmarkModel);
    } else {
        writeFb(netT, modelPath.MNNModel, modelPath.benchmarkModel);
    }

**Comment by czy2014hust** [comment]
No! If your model has BatchNorm, it will return "Not Supported" error, because there is no BatchNorm in MNN(will be optimized to be Scale).

**Comment by Gankerzzl** [comment]
@czy2014hust then what's CPUInstanceNorm doing?
