### ISSUE TITLE
我的onnx转成mnn模型成功，但是推理的时候报这个错：Execute Error for [GatherV2], 6, code=10，是因为onnx转mnn不支持GatherV2算子吗？

### ISSUE THREAD

**Issue by zhang7-qi** [alibaba/MNN#980]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by zheLim** [comment]
same issue here.

**Comment by jxt1234** [comment]
GatherV2 在输入非法的时候，会返回 该错误码，不属于错误
另外一个可能的原因是 Onnx 的 int64 输入类型到 MNN 是 int32 ，在输入时用错数据类型了

**Comment by underspirit** [comment]
这个问题解决了吗， 我用模型转换工具转了一个tensorflow模型报的这个错, 不知道在哪看更详细的信息
