### ISSUE TITLE
Accuracy decrease Onnx->MNN

### ISSUE THREAD

**Issue by Akshaysharma29** [alibaba/MNN#985]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Ubuntu 18.04

# Github版本:
# Github Version:
0.2.1.5git

# 编译方式:
# Compiling Method
cd MNN/
./schema/generate.sh
mkdir build
cd build
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4

# 编译日志:
# Build Log:
Build  Successfully 

# Issue
I have converted the model successfully from onnx->MNN but the accuracy has decreased a lot. Can someone tell the possible reason?
Ask if any further details is required.
Thanks

**Comment by jxt1234** [comment]
Please check your input and output.
You can use TestConvertResult to check if onnx and MNN output same
