### ISSUE TITLE
[必现]只打开opencl，静态编译，执行benchmark会一直阻塞

### ISSUE THREAD

**Issue by pineleen** [alibaba/MNN#986]
# 平台:  
编译环境  x64 linux server. 交叉编译
target环境： 3399pro， aarch64
工具链：gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu

# Github版本: 
1.0.1 release版

# 编译方式:
cmake .. -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_OPENCL=ON -DMNN_BUILD_BENCHMARK=ON  -DCMAKE_TOOLCHAIN_FILE=/workspace/cmake/linux-aarch64-none.toolchain.cmake

# 问题
编译成功后，在3399pro上运行： ./benchmark.out modeldir 20 5 3 1
MNN benchmark
Forward type: **OpenCL** thread=1** precision=2
--------> Benchmarking... loop = 20, warmup = 5
执行到这里之后一直卡住不动。

同样的编译和运行方法，如果删除掉-DMNN_BUILD_SHARED_LIBS=OFF，就能成功执行。

尝试修改 benchmark/CMakefile.txt   target_link_libraries(benchmark.out "-Wl,--whole-archive" ${MNN_DEPS} "-Wl,--no-whole-archive")
问题依然存在。

**Comment by hzzh11856** [comment]
请问您解决了吗，我也碰到的类似的问题

**Comment by pineleen** [comment]
> 请问您解决了吗，我也碰到的类似的问题

也还没解决

**Comment by pineleen** [comment]
因为在mnn的CMakelist.txt中，如果定义成编译静态库， 就会在链接选项上加上 -static，会导致所有的链接库都会去找静调库链。 去掉-static，第三方库默认去链动态库就可以了。

**Comment by pineleen** [comment]
> 请问您解决了吗，我也碰到的类似的问题

如果你能看到，可以参考下我的改动。
