### ISSUE TITLE
About MNN Input. If my model needs a 4 channels Image like this (1, h, w, 4), 32 bit float data, what should I do to deliver it to the input tensor in C++?

### ISSUE THREAD

**Issue by MingmChen** [alibaba/MNN#988]

**Comment by jxt1234** [comment]
The same as https://www.yuque.com/mnn/en/input

**Comment by MingmChen** [comment]
when I process the imput image in python like this:
    raw = rawpy.imread(in_path)
    input_full = pack_raw(raw)* ratio     
    input_full = np.minimum(input_full, 1.0)
    print("Input_full shape", input_full.shape)    #(1835, 2748, 4)

    # MNN inference.
    tmp_input = MNN.Tensor((1, 1835, 2748, 4), MNN.Halide_Type_Float, input_full, MNN.Tensor_DimensionType_Tensorflow)
    input_tensor.copyFrom(tmp_input)
    input_tensor.getShape()
    input_tensor.printTensorData()
    interpreter.runSession(session)
    output_tensor = interpreter.getSessionOutput(session)
    ...
The out put is
    ('Input_full shape', (1835, 2748, 4))
   (1L, 4L, -1L, -1L)
   ====== Tensor 0x352a440 ======
   Dimension: 1, 4, -1, -1, 
   Data: batch 0:
   --------------
   --------------
   --------------
   --------------
 why?

**Comment by jxt1234** [comment]
You should resize input_tensor before copyFrom

**Comment by MingmChen** [comment]
你好，我将输入tensor进行了resize，代码如下：
int SuperNight::denoise(cv::Mat& img, int height, int width, int channels){
    image_h = height;
    image_w = width;
    channel = channels;
    if(img.type() != CV_32FC4)
    {
        img.convertTo(img, CV_32FC4);
        std::cout << "Data convert to CV_32FC4" << std::endl;
    }

    sid->resizeTensor(input_tensor, {1,image_h, image_w, 4});
    sid->resizeSession(sess_sid);

    const std::vector<int> dims{1, image_h, image_w, 4};
    auto nhwc_Tensor = MNN::Tensor::create<float>(dims, NULL, MNN::Tensor::TENSORFLOW);
    auto nhwc_data   = nhwc_Tensor->host<float>();
    auto nhwc_size   = nhwc_Tensor->size();
    ::memcpy(nhwc_data, img.data, nhwc_size);

    input_tensor->copyFromHostTensor(nhwc_Tensor);

    //run network
    sid->runSession(sess_sid);

    //get output
    std::string denoise_tensor = "ImgOutput";
    output_tensor = sid -> getSessionOutput(sess_sid, denoise_tensor.c_str());
    MNN::Tensor DenoiseImg_host(output_tensor,output_tensor->getDimensionType());
    output_tensor->copyToHostTensor(&DenoiseImg_host);
    auto out = DenoiseImg_host.host<float>();

}
但是运行会报如下错误，为什么？我的训练模型输入维度为（１，1835，2748, 4）.　期待您的回复。
Error for compute convolution shape, need channel = 4, input channel = 1835
Resize error for [Convolution], g_conv1_1/BiasAdd, code=3

**Comment by anklebreaker** [comment]
@MingmChen I have same error, did you ever find a solution?
