### ISSUE TITLE
请问如何在已加载的网络追加算子操作？

### ISSUE THREAD

**Issue by Eddylib** [alibaba/MNN#990]
如题，关于方法论的咨询，应该不需要平台介绍....

目前已想到的办法是使用/tool/train模块生产一个网络模型，保存成文件之后加载，然后将tensor在两个网络之间流动得到输出。

这种方法是否太笨了？有何优雅的方法？

**Comment by jxt1234** [comment]
你是需要拼接多个网络么？可以用表达式相关API ，include/MNN/expr 路径下

**Comment by jxt1234** [comment]
可以看下 https://www.yuque.com/mnn/cn/hksf1g ，C++ 的操作原理也一样

**Comment by Eddylib** [comment]
我现在就想在
 std::shared_ptr<MNN::Interpreter> net(MNN::Interpreter::createFromFile(model_file.c_str()));
这个net后面追加softmax等操作，请问还是需要搞模型拼接吗？
VARP和Tensor是一回事吗？可以吧net的runsession后的输出直接装入VARP里面吗？

**Comment by Eddylib** [comment]
或者请问，VARP和Tensor有何交互接口吗？

**Comment by jxt1234** [comment]
可以参考 demo/exec/segment.cpp ，用 expr 的 api 加载模型，这样可以直接追加。

VARP和Tensor之间的交互目前可以先建输入： 
VARP input = _Input();
然后复制 Tensor 的内容进去：
