### ISSUE TITLE
关于mmn转换模型时对scale层双输入的支持

### ISSUE THREAD

**Issue by dog-qiuqiu** [alibaba/MNN#997]
layer {
    bottom: "layer88-conv"
    bottom: "layer91-conv_flatten"
    top: "layer92-scale_channels"
    name: "layer92-scale_channels"
    type: "Scale"
    scale_param {
        bias_term: false
        axis: 0
    }
}
我通过caffe的scale双输入来支持SE模块，但是发现MNN的caffemodel转换工具不支持这种操作，如上例子所示
这是模型完整的prototxt:https://github.com/dog-qiuqiu/MobileNetv2-YOLOV3/blob/master/yoloface-500k/v2/yoloface-500k-v2.prototxt
谢谢！！！

**Comment by PhenomenalOnee** [comment]
I also faces the same issue, did you find any solution?
